### ISSUE TITLE
[BUG/ISSUE] Inconsistency in lightning emissions in different versions

### ISSUE THREAD

**Issue by RuijunDang** [geoschem/geos-chem#1003]
Hi @ltmurray,

I have been comparing NOx emissions in v13.2 with those in v11.2 (both used the MERRA-2 meteorology). I found that the lightning NOx emissions in v13.2 simulation is much smaller than those in v11.2, which is very weird because the offline data should be identical to the online calculation. The attached figure compares the US lightning NOx emission profiles in these two versions. Do you have any clue where the bias come from?

Also, when traced back the benchmarks since v11.2, I found that in the v12.9, there is a noticeable difference in lightning emissions between the two versions ([see page6](http://ftp.as.harvard.edu/gcgrid/geos-chem/1yr_benchmarks/GC_12/12.9.0/FullChem/GCC/Plots/Nitrogen/Jul2016/Nitrogen_Emissions_Jul2016.pdf)). GCv12.9 is the version when you updated the offline lightning data to v2020-03, but the offline data of July 2016 in v2020-03 is identical to that in v2019-01. So I don't know where the difference come from, and I am not sure if it is related to the lightning bias in my simulation.

![image](https://user-images.githubusercontent.com/42425781/141371501-82be728f-6f7e-41c5-80fb-3af942fac37b.png)

**Comment by yantosca** [comment]
@RuijunDang: Is this still an unresolved issue?  Or can we close this out?

**Comment by Ruijun-Dang** [comment]
> @RuijunDang: Is this still an unresolved issue? Or can we close this out?

The difference between versions is due to the switch from online calculation to offline calculation of lightning emissions. There should be an increase when switching to offline calculation. I've attached some notes here. [Lightning.pdf](https://github.com/user-attachments/files/15596725/Lightning.pdf). Not sure why my previous plots show a decease though... We can close this issue out now!

**Comment by yantosca** [comment]
Thanks @RuijunDang!  Closing out this issue now.
