### ISSUE TITLE
[BUG/ISSUE] Error in nested-grid fullchem simulatin with complex SOA_SVPOA option

### ISSUE THREAD

**Issue by yangning-code** [geoschem/geos-chem#1004]
### Description of the problem
When I use GEOS-Chem.13.2.1 to run gc_025x03125_geosfp_fullchem_complexSOA_SVPOA in Asia. The model always reports an error, the content is as follows GEOS-CHEM ERROR: WARNING: Negative concentration for species SALAAL at (I,J,L) = 223 130 46; GEOS-Chem ERROR:at DO_TEND (in module GeosCore/mixing_mod.F90); GEOS-Chem ERROR: Error encountred in "DO_TEND"!at DO_MIXING (in module GeosCore/mixing_mod.F90); GEOS-CHEM ERROR: Error encountered in "Do_Mixing"! STOP at  -> at GEOS-Chem (in GeosCore/main.F90). The specific content is placed in the  input_geos.log.

### Description of troubleshooting performed
Describe any troubleshooting that you have already performed here. Also include any leads or suspicions here.

### GEOS-Chem version
Enter your GEOS-Chem version here.

### Description of modifications
GEOS-Chem.13.2.1
[geoschem.zip](https://github.com/geoschem/geos-chem/files/7523963/geoschem.zip)

### Log files
- Build log (if applicable): CMakeCache.txt
- Run logs (if applicable): input_geos.log
- Run script (if applicable):  qsub_logs

### Software versions
- CMake version: cmake version 3.21.3
- Compilers (Intel or GNU, and version): ifort (IFORT) 17.0.5 20170817
- NetCDF version: netcdf-4.6.1-withhdf5

**Comment by yantosca** [comment]
Thanks for writing @yangning-code.  This may be due to boundary condition issues.  Have you created the boundary conditions from a global simuation (i.e. archiving the BoundaryConditions collectioin in History diagnostics)?

**Comment by yangning-code** [comment]
I had created the boundary conditions from a global simulation. For specific settings, you can check the following two files(HEMCO_Config.aisa.rc and HEMCO_Config.global.rc) and a screenshot.
![BoundaryConditions](https://user-images.githubusercontent.com/51811371/141662916-6418468a-8c48-4cad-9e39-6941a0de5c34.JPG)
[HEMCO_Config.zip](https://github.com/geoschem/geos-chem/files/7532970/HEMCO_Config.zip)

I started running on December 1, 2017, and will report an error on time on December 7, 2017. If it is a problem with boundary conditions, then there should be an error during the period from December 1 to 6, 2017, but no error was reported during this period.
