### ISSUE TITLE
[QUESTION]Model diagnostics of N2O5 uptake coefficients and ClNO2 yields

### ISSUE THREAD

**Issue by yangxiajie** [geoschem/geos-chem#1009]
In GEOS-Chem v12.9.3, the model include N2O5 uptake on chlorine-containing aerosols, which based on the analysis of WINTER observations in McDuffie et al., JGR, 2018. I want to output the model-calculated N2O5 uptake coefficients and ClNO2 yields. I found `Chem_GammaN2O5fine` and `Chem_YieldClNO2fine` from `StateChm diagnostic`, I wonder if they are model-calculated N2O5 uptake coefficients and ClNO2 yields?

**Comment by yantosca** [comment]
Thanks for writing @yangxiajie.  It looks like these variables in State_Chm are allocated but not used (at least not in 13.3.1).

**Comment by yangxiajie** [comment]
Thank you @yantosca .
I feel a little confused. Is there anything wrong about `Chem_GammaN2O5fine` and `Chem_YieldClNO2fine` ? Becasue StateChm can output these two diagnostics. 
Or, `Chem_GammaN2O5fine` and `Chem_YieldClNO2fine` can not represent model-calculated N2O5 uptake coefficients and ClNO2 yields, respectively?

**Comment by yangning-code** [comment]
Which version of GEOSChem can output N2O5 uptake coefficients and ClNO2 yields?
