### ISSUE TITLE
[BUG/ISSUE] OFFLINE_BIOVOC files missing for 1999 and 2000

### ISSUE THREAD

**Issue by sdeastham** [geoschem/geos-chem#1010]
### Description of the problem
Some months are empty/not fully populated for OFFLINE_BIOVOC on the master WUStL server. At minimum, I've found that November and December 1999 (http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_BIOVOC/v2019-10/0.5x0.625/1999/11/ and http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_BIOVOC/v2019-10/0.5x0.625/1999/12/) and most months in 2000 (e.g. http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_BIOVOC/v2019-10/0.5x0.625/2000/07/) are missing some/all files.

**Comment by LiamBindle** [comment]
I think this is an issue with the OFFLINE_BIOVOC collection, not the WUSTL/ComputeCanada hosting of it. We don't have a copy of that data in either location.

Perhaps @hongjianweng knows what's happened here? Do you guys have OFFLINE_BIOVOC data for this time period?

**Comment by sdeastham** [comment]
Ping - has this been fixed?

**Comment by YanshunLi-washu** [comment]
Hi @sdeastham I'll check with Hongjian who is the developer. Hi @hongjianweng , did you got a chance to help looking on that?

**Comment by hongjianweng** [comment]
@sdeastham @LiamBindle The missing some/all files have been updated.
