### ISSUE TITLE
[QUESTION]Questions about BC emission diagnostics + meteorological input

### ISSUE THREAD

**Issue by bzhang419** [geoschem/geos-chem#1014]
Hi,

I encountered two problems when running simulations with Geos-Chem version 12.9.3.

The first one is that the BC emission from HEMCO diagnostic file seems incorrect. I calculate the total BC emission in all sectors (EmisBCPI_Total+Emis_BCPO_Total) and got >400 Tg /year. I also looked at emissions in different layers, which are shown in the following figure, and I found that the emission is higher than 5.8Tg in all layers, and emissions in the layers (25-72) are exactly the same. I did not change the default settings in HEMCO_Config.rc and HEMCO_Diag.rc related to BC, so I am confused about the reason causing this issue.
![BC_emission](https://user-images.githubusercontent.com/67564320/142094167-5db1e394-4915-4a5d-854c-450111a3665f.png)

Besides, I also encountered an error when running simulations in 2000 using merra2 4×5 meteorological files. The error message is like "
 Cannot find field with valid time stamp in /path/shared/GEOS-Chem/data/ExtData/GEOS_4x5/MERRA2/2000/12/MERRA2.20001231.I3.4x5.nc4 - Cannot get field PS_NEXTDAY. Please check file name and time (incl. time range flag) in th
ERROR LOCATION: HCOIO_READ_STD (hcoio_read_std_mod.F90)
ERROR LOCATION: HCOIO_DataRead (hcoio_dataread_mod.F90)
ERROR LOCATION: ReadList_Fill (hco_readlist_mod.F90)
ERROR LOCATION: ReadList_Read (hco_readlist_mod.F90)
ERROR LOCATION: HCO_RUN (hco_driver_mod.F90)
"
I checked the file MERRA2.20001231.I3.4x5.nc4 online and I found no variable named PS_NEXTDAY in it. I am wondering how to solve this issue.

Thank you!

**Comment by yantosca** [comment]
@bzhang419, the Cannot get field PS_NEXTDAY error sounds like you do not have he met data for 20010101 on your disk.  Can you check?

**Comment by yantosca** [comment]
@bzhang419, are you sure there isn't a unit conversion issue in your code.  From the latest 1-year GEOS-Chem benchmark for 13.3.0 we get:
```
###################################################################################
### Emissions totals for species BCPI [Tg]                                      ###
### Ref = GCC_13.2.0; Dev = GCC_13.3.0                                          ###
###################################################################################
                                    Ref                 Dev     Dev - Ref    % diff
BCPI Aircraft      :           0.005417            0.005417      0.000000     0.000
BCPI Anthro        :           1.150436            1.150436      0.000000     0.000
BCPI BioBurn       :           0.401294            0.401294      0.000000     0.000
BCPI Ship          :           0.016124            0.016124      0.000000     0.000
-----------------------------------------------------------------------------------
BCPI Total         :           1.573271            1.573271      0.000000     0.000


###################################################################################
### Emissions totals for species BCPO [Tg]                                      ###
### Ref = GCC_13.2.0; Dev = GCC_13.3.0                                          ###
###################################################################################
                                    Ref                 Dev     Dev - Ref    % diff
BCPO Anthro        :           4.601743            4.601743      0.000000     0.000
BCPO BioBurn       :           1.605175            1.605175      0.000000     0.000
BCPO Ship          :           0.064495            0.064495      0.000000     0.000
-----------------------------------------------------------------------------------
BCPO Total         :           6.271418            6.271418      0.000000     0.000
```

**Comment by bzhang419** [comment]
Thanks @yantosca  for your reply! I will try to restart my simulation after downloading the met data for 20010101.
For the second question, I do not think there is a unit conversion issue because I got the similar result (i.e. <10 Tg) when using the  HEMCO diagnostic files for version 13.1.0-13.3.0 published as the benchmark here (http://ftp.as.harvard.edu/gcgrid/geos-chem/1mo_benchmarks/GC_13/). But when I try to calculate with the file for version 13.0.0 or earlier, I still got a result larger than 400 Tg. Could you please check if you get a similar result with the earlier versions? Since I used version 12.9.3 for my simulation, is this possibly related to a code change between different versions? Thanks!

**Comment by yantosca** [comment]
@bzhang419, I am not aware of the 1-year benchmark outputs having shown 400 Tg/yr.    If you look at the 12.9.0 1-year benchmark we get:
```
###############################################################################
### Emissions totals for species BCPI                                       ###
### Ref = GC_12.8.0; Dev = GC_12.9.0                                        ###
###############################################################################
                                       Ref                 Dev      Dev - Ref
BCPI Aircraft         :           0.005443            0.005438      -0.000005 Tg
BCPI Anthro           :           1.393638            1.393521      -0.000118 Tg
BCPI BioBurn          :           0.330065            0.329790      -0.000275 Tg
BCPI Ship             :           0.033441            0.033441       0.000000 Tg
-------------------------------------------------------------------------------
BCPI Total            :           1.838681            1.838220      -0.000461 Tg


###############################################################################
### Emissions totals for species BCPO                                       ###
### Ref = GC_12.8.0; Dev = GC_12.9.0                                        ###
###############################################################################
                                       Ref                 Dev      Dev - Ref
BCPO Anthro           :           5.574554            5.574083      -0.000471 Tg
BCPO BioBurn          :           1.320259            1.319159      -0.001099 Tg
BCPO Ship             :           0.133766            0.133766       0.000000 Tg
-------------------------------------------------------------------------------
BCPO Total            :           7.332956            7.331126      -0.001830 Tg
```
These are computed with the data from the HEMCO_diagnostics *.nc files.

**Comment by bzhang419** [comment]
Thanks for your answer @yantosca, I think I find the reason causing high BC emissions in my result. I did not notice BCPO_Total is a 2-d matrix while BCPI_Total is a 3-d matrix, when I simply add them up using MATLAB, each layer in the third dimension of BCPI_Total will be added by a BCPO_Total, so the BCPO_Total is repeatedly counted many times. After I fixed this, I got the same result as yours.

**Comment by yantosca** [comment]
Thanks @bzhang419, I'll close out this issue now.
