### ISSUE TITLE
[QUESTION] unavailable directories in GC13.3.2 due to sym links

### ISSUE THREAD

**Issue by jinlx** [geoschem/geos-chem#1018]
Hi there,

I was trying to download GCv13.3.2 by using git clone but it seems that run directory and test directory are unavailable due to sym links. In order to make use of it, am I supposed to use src directory from GC12.9.3?

Cheers,
Lixu

**Comment by lizziel** [comment]
Hi Lixu, is this first time you are using version 13? We changed things in the version such that GEOS-Chem and HEMCO are now git submodules within the GC-Classic repository. This means you need to do the following command after cloning to populate the submodules. 

git submodule update --init --recursive

This should fix the broken links. For more information about using version 13 see our [wiki user guide](http://wiki.seas.harvard.edu/geos-chem/index.php/Getting_Started_with_GEOS-Chem). We also have a few [YouTube videos](https://www.youtube.com/c/geoschem) on version 13 that you may find helpful.
