### ISSUE TITLE
[FEATURE REQUEST] Replace am_I_Root argument with Input_Opt

### ISSUE THREAD

**Issue by lizziel** [geoschem/geos-chem#102]
Passing logical am_I_Root to GEOS-Chem submodules can be replaced with use of existing logical Input_Opt%RootCPU. Usage of that Input_Opt variable can be further made clear by renaming it Input_Opt%amIRoot. This update would remove a lot of extraneous code. Zero diffs are expected.

**Comment by msulprizio** [comment]
In addition to replacing `am_I_Root` with `Input_Opt%amIRoot` in GEOS-Chem source code, we can also replace `am_I_Root` throughout HEMCO with `HcoState%amIRoot`.

This is in progress and is being completed as part of https://github.com/geoschem/geos-chem/issues/92.

**Comment by msulprizio** [comment]
This is now included in the `dev/12.8.0` branch.
