### ISSUE TITLE
[BUG/ISSUE] Slowness on http://geoschemdata.wustl.edu

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/geos-chem#1024]
### What institution are you from?
GCST

### Description of the problem
http://geoschemdata.wustl.edu is experiencing intermittent slowness. 

We have an open ticket with the server admin. I'll post updates here.

**Comment by LiamBindle** [comment]
The admins suspect the slowness was caused by some file system issues that are now resolved. Closing this for now. If anyone experiences slowness, please reopen.

**Comment by LiamBindle** [comment]
Reopening. @laestrada says that this morning he's getting very slow responses. He wrote
> Eg. it took 3 minutes to download a 73 Mb file. Most of this time was spent establishing a connection and then 14s for the actual download

**Comment by IshirDutta** [comment]
Hi @LiamBindle, as of this afternoon I'm also seeing both long connection times as well as slow download speeds to the MIT svante cluster. Tried downloading a couple files from ComputeCanada as a comparison, and got download speeds ~400 MB/s

<img width="569" alt="image" src="https://user-images.githubusercontent.com/33105692/144305319-376fee0b-12aa-4745-ae34-ec3c9ac26374.png">

**Comment by LiamBindle** [comment]
Hi @IshirDutta, thanks for letting us know.

It sounds like the root problem is that the server is under speced for how many people are using it. Unfortunately, that means it will probably be like this until we an up the server's capacity (work in-progress, but realistically it will take some time). Switching between ComputeCanada and WUSTL is a good workaround in the interim.

**Comment by LiamBindle** [comment]
If people can limit the number of parallel downloads they're running, that would help us out too (e.g., I used to run like 10 parallel downloads as a time....we should avoid doing that right now).

**Comment by IshirDutta** [comment]
Good to know! I'm just running one of them from my dry run log, so it's going on autopilot sequentially in the background. Given that upgrades on the WUSTL server will likely take a while, would it be possible to sync it with ComputeCanada with the latest set of input files? I noticed a few of the newer folders were missing on CC (CEDS comes to mind immediately, but I'm sure there are others I can't remember too).

**Comment by yantosca** [comment]
@YanshunLi-washu, is the sync to ComputeCanada possible?

**Comment by YanshunLi-washu** [comment]
Hi @yantosca and @IshirDutta, would you give a try on the globus endpoint named GEOS-Chem Data (WashU)? Hi @LiamBindle, just for checking do we still have automatic sync between Washu compute1 and Compute Canada?

**Comment by LiamBindle** [comment]
@YanshunLi-washu I don't think so. Would you be able to copy the recently added HEMCO collections (i.e. those added in 13.2 and 13.3)? You can find the new directories on the Wiki pages that describe the releases.  It's probably easiest to do on the Globus website. (Sorry for the bad timing)

**Comment by YanshunLi-washu** [comment]
@LiamBindle Just to make sure, are those recently added collections uploaded to CCVM but not Compute1?

**Comment by LiamBindle** [comment]
They're on Compute1 but not CCVM. So Compute1->CCVM is the direction

**Comment by YanshunLi-washu** [comment]
Hi @LiamBindle @IshirDutta I've transferred CEDS v2021-06, Yuan_XLAI v2021-06, OFFLINE_SSALT and NEI2016 v2021-06 to CCVM. Let me know anything else. Thanks

**Comment by LiamBindle** [comment]
Hi all, just a quick update. There are quite a few illegitimate requests being made to the server (from hosts like 163data.com.cn and hn.kd.ny.adsl which are well known spammers/brute force attack attempters). We're working on a solution for discarding these requests without disrupting everyones download scripts. Current ideas are:
- an IP allowlist (users send us their IP address, and we add it to the allowlist)
- a simple global username and password (e.g., username=geoschem, password=geoschem; these can be put in `.netrc` for use with curl/wget)

Feel free to chime in if you have any thoughts/ideas on how we can minimize disrupting your workflow. Note that these are just a means for discarding requests from spam bots.

**Comment by LiamBindle** [comment]
The data portal is down right now (and it looks like it has been for a few days). Sorry for the inconvenience. I'll post an update when I hear back from the admins.

**Comment by LiamBindle** [comment]
Hi all, http://geoschemdata.wustl.edu/ should be back online. Can you try it now?

As an update regarding the slowness, the admins have a development version of the server which they are testing right now. They think it should remedy some of the slowness issues we've been seeing lately.

**Comment by LiamBindle** [comment]
The server might be down for a few hours today while it undergoes maintenance.

**Comment by CharikleiaGRN** [comment]
"Connection timed out"

The "http://geoschemdata.wustl.edu/" is not responding. Is it the same for other users also?

**Comment by YanshunLi-washu** [comment]
Thanks @yantosca Hi @CharikleiaGRN, I experienced the same. It's high possible that the WashU IT team is maintaining the site.  It will usually resume soon. Don't worry. @LiamBindle may know more.

**Comment by CharikleiaGRN** [comment]
Hey! Hi! Permission denied for  "/ExtData/GEOSCHEM_RESTARTS/v2021-12" but not for other folders.

**Comment by CharikleiaGRN** [comment]
It is not possible to download these files. 
the same for:
/ExtData/HEMCO/MERCURY/v2022-04

**Comment by YanshunLi-washu** [comment]
@CharikleiaGRN Hey, thanks for letting us know. I've contact @LiamBindle who has the permission of these files. Hopefully, it can be fixed very soon. I'll keep you posted.

**Comment by YanshunLi-washu** [comment]
@CharikleiaGRN All fixed now!

**Comment by CharikleiaGRN** [comment]
Thank you :P :P :)

**Comment by yantosca** [comment]
I will close out this issue for now.
