### ISSUE TITLE
[BUG/ISSUE] GEOS-Chem simulation with TOMAS (40 bins) Negative O3 concentration

### ISSUE THREAD

**Issue by xalejandrux** [geoschem/geos-chem#1025]
### What institution are you from?
Université de Montréal / University of Montréal

### Description of the problem
We set up a GEOS-Chem simulation with TOMAS (40 bins). When we try to run the simulation, we find a bug that tells us that the concentration of O3 is negative in the coordinates (I, J, L) = (39 37 1)

### Description of troubleshooting performed
GEOS-Chem ERROR:
 -> at DO_TEND (in module GeosCore/mixing_mod.F90)

GEOS-Chem ERROR: Error encountred in "DO_TEND"!
 -> at DO_MIXING (in module GeosCore/mixing_mod.F90)

GEOS-CHEM ERROR: Error encountered in "Do_Mixing"!
STOP at  -> at GEOS-Chem (in GeosCore/main.F90)

### GEOS-Chem version
13.2.1

### Description of modifications
Describe your modifications here.

### Log files
- Build log (if applicable):
- Run logs (if applicable):
- Run script (if applicable):

### Software versions
- CMake version: 3.16.5
- Compilers (Intel or GNU, and version): intel 19.1.1.217
- NetCDF version: 4.7.4

Thank you for your time. Here the files
[HEMCO.log.txt](https://github.com/geoschem/geos-chem/files/7586042/HEMCO.log.txt)
[slurm-27772762.out.txt](https://github.com/geoschem/geos-chem/files/7586043/slurm-27772762.out.txt)

**Comment by yantosca** [comment]
Thanks for writing @xalejandrux.  I am tagging Jeff Pierce (@theloniuspunk) who is with the TOMAS development team.

**Comment by theloniuspunk** [comment]
Hi folks,

Betty Croft recently found this too. We really don't have many ideas. TOMAS
should not be influencing O3 (the bulk aerosol species are what interacts
with radiation and photolysis rates as well as heterogeneous chemistry).
The only thing I can think of is that running TOMAS makes us turn off the
non-local PBL mixing scheme (and maybe this is now doing something funky?)
or maybe the HEMCO_config files are now not aligned?

Jeff

**Comment by xalejandrux** [comment]
Thank you very much for your answers. We have tried to find the source of the problem. We have tried to run another simulation in another run directory (simulation option: 1. Standard). We did this simulation with exactly the same parameters that we configured for TOMAS and we have encountered exactly the same error. (Negative concentration of O3). I think it is important to mention that in the configuration of the input.geos (=> Use non-local PBL?: F). As you mentioned TOMAS should not be influencing O3, and we don't really know the origin of the problem. I have attached some files.
[HEMCO.log.txt](https://github.com/geoschem/geos-chem/files/7612686/HEMCO.log.txt)
[slurm-28005880.out.txt](https://github.com/geoschem/geos-chem/files/7612687/slurm-28005880.out.txt)

**Comment by theloniuspunk** [comment]
Thanks!

GCST, it seems like the issue is outside of TOMAS but in some general
GEOS-Chem parameter that is set differently between TOMAS and non-TOMAS
simulations. "Use non-local PBL?: F" seems like a leading candidate.
Something about this PBL setup must be sometimes creating chemical
conditions that is making something wacky happening in predicting O3.

Jeff

**Comment by yantosca** [comment]
You might want to update to [GEOS-Chem 13.3.3](https://github.com/geoschem/GCClassic/releases/tag/13.3.3).  There was a bug in HEMCO that prevented manual diagnostics from updating.

**Comment by yantosca** [comment]
I will close out this issue now.  Feel free to open another issue if you still have problems or concerns.
