### ISSUE TITLE
[QUESTION] Offline biogenic VOC emissions not available for simulation year

### ISSUE THREAD

**Issue by bsuther** [geoschem/geos-chem#103]
# Ask a question about GEOS-Chem

## Type your question:

Version: 12.5.0

Hello,

I am a new GEOS chem user and am trying to get it running for the first time. I am trying to set up a run for the summer months of 2014. I believe the errors I am getting are because I do not have the correct offline biovoc files for that year. I got the v2019-08 files off of the harvard ftp site, but those do not have the year I need. I also got the v2019-10 files from the geoschedata.computecanada.ca site. That seems to have the year I need, but my version of the code is looking for the files in the v2019-08 directory, not the v2019-10 directory. How do I tell geos chem to look in a different directory, or what would be the appropriate way to get it working for a 2014 run?

Thank you,
Bethany

[GC.log](https://github.com/geoschem/geos-chem/files/3756355/GC.log)
[HEMCO.log](https://github.com/geoschem/geos-chem/files/3756356/HEMCO.log)
[other inputs.zip](https://github.com/geoschem/geos-chem/files/3756397/other.inputs.zip)

Feel free to delete all of the text above this line...

**Comment by msulprizio** [comment]
Hi Bethany,

Offline biogenic VOC emissions are not yet available for 2014. To get around the error, you can turn off the OFFLINE_BIOVOC option at the top of HEMCO_Config.rc and turn on the MEGAN extension for computing online biogenic emissions. For example:

```
# ----- OFFLINE EMISSIONS -------------------
# To use online emissions instead set the
# offline emissions to 'false' and the
# corresponding HEMCO extension to 'on':
#   OFFLINE_DUST        - DustDead or DustGinoux
#   OFFLINE_BIOGENICVOC - MEGAN and MEGAN_Mono
#   OFFLINE_SEASALT     - SeaSalt
#   OFFLINE_SOILNOX     - SoilNOx
#--------------------------------------------
    --> OFFLINE_DUST           :       true
    --> OFFLINE_BIOGENICVOC    :       false
    --> OFFLINE_SEASALT        :       true
    --> OFFLINE_SOILNOX        :       true

...

108     MEGAN                  : on    ISOP/ACET/PRPE/C2H4/ALD2/EOH/SOAP/SOAS
    --> Isoprene scaling       :       1.0
    --> CO2 inhibition         :       true
    --> CO2 conc (ppmv)        :       390.0
    --> Isoprene to SOAP       :       0.015
    --> Isoprene to SOAS       :       0.015
#3% mass yield from isoprene to SOA
109     MEGAN_Mono             : on    MTPA/MTPO/LIMO/SESQ
    --> Monoterp to SOAP       :       0.050
    --> Monoterp to SOAS       :       0.050
#10% mass yield from monoterpenes to SOA
    --> Othrterp to SOAP       :       0.050
    --> Othrterp to SOAS       :       0.050
#10% mass yield from other terpenes to SOA
```
