### ISSUE TITLE
[QUESTION] Molecular weight of SO4{D1,D2,D3,D4}?

### ISSUE THREAD

**Issue by lixiao-bit** [geoschem/geos-chem#1031]
### Ask a question about GEOS-Chem:
Hi all,

What should we set the molecular weight of SO4D1-4 to? Should we set it to the same as sulfate or the molecular weight of DST1-4? 

thanks.
Xiao Li

**Comment by yantosca** [comment]
I will close out this issue for now.  Please let us know if you have further questions.
