### ISSUE TITLE
[BUG/ISSUE] Double counting of HCl uptake on alkaline sea-salt aerosols

### ISSUE THREAD

**Issue by viral211** [geoschem/geos-chem#1034]
The following line in `sulfate_mod.F`
https://github.com/geoschem/geos-chem/blob/4252e96ff0614772dd1228c4d08c5d8dbc3d2a37/GeosCore/sulfate_mod.F90#L4710
should be executed only when SO2 chemistry is called with the `FullRun` flag set to `True`. Currently it is executed twice in a chemistry time step and double counts the HCl lost to sea salt aerosols.

### Proposed edit:
`IF (FullRun) Spc(I,J,L,id_HCl) = MAX( HCl_vv - HCl_ss, MINDAT )`

**Comment by yantosca** [comment]
I am also tagging @msl3v, since the appropriate fix will also need to be made in `KPP/fullchem/fullchem_SulfurChemFuncs.F90`.

**Comment by yantosca** [comment]
We can close this issue, as PR #1041 has been merged into the 13.4.0 development stream.
