### ISSUE TITLE
[FEATURE REQUEST] Update QFED emissions through the end of 2020

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#1037]
Hongyu Liu pointed out that the QFED emissions files in [`ExtData/HEMCO/QFED/v2018-07/2020/`](http://ftp.as.harvard.edu/gcgrid/data/ExtData/HEMCO/QFED/v2018-07/2020/) are only available through 2020/08/01. Christoph Keller says files for the rest of 2020 are available on Discover at `/discover/nobackup/projects/gmao/share/dao_ops/fvInput_nc3/PIESA/sfc/QFED/v2.5r1/0.1/`.

**Comment by yantosca** [comment]
@lizziel, could you transfer these files over?  I no longer have access to Discover.

**Comment by lizziel** [comment]
I'll download these files from discover.

**Comment by yantosca** [comment]
@lizziel, has this been completed?  If so, we can close out this issue.

**Comment by lizziel** [comment]
This is all set.

**Comment by msulprizio** [comment]
For future reference...

Christoph Keller wrote:
>There are two QFED products: a real-time stream and a ‘gap-filled’ analysis product that is considered higher quality but is produced with a latency of approx. 2 weeks. The discover path listed [above] points to the post-processed QFED files. You can expect them to always lag by ~2 weeks.

**Comment by lizziel** [comment]
We now have data through Feb 2022 available and I will download future months as they become available. Extending the year range in HEMCO_Config.rc from 2020 to 2022 will be included in 13.4.

**Comment by yantosca** [comment]
This PR has now been merged into the 13.4.0 development stream.
