### ISSUE TITLE
[QUESTION] cannot find ExtData/CHEM_INPUTS/FAST_JX/v2021-10

### ISSUE THREAD

**Issue by clearsky112** [geoschem/geos-chem#1038]

**Comment by yantosca** [comment]
@clearsky112, did you do a dry-run simulation?  That should have pulled down the FAST_JX/v2021-10 files.

**Comment by clearsky112** [comment]
> 

Thanks. Yes, I did use the dryrun simulation, just could not connect to the wu site at that moment, while the cc and ur sites don't have the files. Later, the wu site was back and I downloaded them.
