### ISSUE TITLE
[QUESTION] where can I find the restart files for v13.3.2

### ISSUE THREAD

**Issue by clearsky112** [geoschem/geos-chem#1039]
### Ask a question about GEOS-Chem:

Hi GEOS-Chem help desk,
    I'm trying to use the v13.3.2 GC and wonder where I could find the restart file as the initial condition? The one I used for v13.2.1 doesn't work for v13.3.2 directly.  I chose full chemistry+Benchmark. 
Thanks in advance.

**Comment by yantosca** [comment]
The restart files are at this path: http://ftp.as.harvard.edu/gcgrid/data/ExtData/GEOSCHEM_RESTARTS/v2021-09/.  They are also on the WashU server but there have been some connectivity issues there lately.

If you have created a run directory from the 13.3.2 folder, then the proper restart file should be placed in your run directory automatically.

**Comment by clearsky112** [comment]
thanks! seems the v2021-09 has not been added into http://geoschemdata.wustl.edu/ExtData/GEOSCHEM_RESTARTS/

**Comment by clearsky112** [comment]
May I quickly check that whether the monthly restart files from the GEOS-Chem 13.3.2 10-year full-chemistry benchmark (2010-2019) are available? Thanks.

**Comment by yantosca** [comment]
In the `download_data.yml` file in your run directory, change:

```yaml
fullchem:
    remote: GC_13.0.0/GEOSChem.Restart.fullchem.20190701_0000z.nc4
```
to
```
fullchem:
    remote: v2021-09/GEOSChem.Restart.fullchem.20190701_0000z.nc4
``` 
that should pick the proper restart file. This might also have been the result of a Git merge.

**Comment by yantosca** [comment]
I have fixed this in commit 0648444e7a3bcccf867c7cd65f92e548f322dcfa, which is in the bugfixes branch.

**Comment by clearsky112** [comment]
Thank you!

**Comment by yantosca** [comment]
@clearsky112, thanks for reporting this.  I think we had this originally set correctly but it might have been overridden in a Git merge.  I'll close this issue out.  Let us know if you encounter any other problems.

**Comment by yantosca** [comment]
We are preparing to add this into another patch version 13.3.4.

**Comment by clearsky112** [comment]
thank you for the information.
