### ISSUE TITLE
[CH4 Emission from Ocean]

### ISSUE THREAD

**Issue by Rainbow1994** [geoschem/geos-chem#104]
The current emission documents of CH4 from HEMCO don't include marine CH4 emissions, I wonder if there will be any documents in this regard in the near future. If it is in the recent development plan of geos-chem? and if not, would you please add this problem into the future plan. Thanks a lot!

**Comment by msulprizio** [comment]
There is no current plan to include marine CH4 emissions in GEOS-Chem. If you are working on this and would like it added to the list of [model development priorities ](http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_model_development_priorities), please contact the [Carbon Cycle Working Group](http://wiki.seas.harvard.edu/geos-chem/index.php/Carbon_Cycle_Working_Group) leaders and they can bring it up at the next GEOS-Chem Steering Committee meeting.

**Comment by Rainbow1994** [comment]
Thanks for your attention!
