### ISSUE TITLE
[BUG/ISSUE] Error in GEOS-FP input file (GEOSFP.20210404.I3.4x5.nc)

### ISSUE THREAD

**Issue by jahwilson** [geoschem/geos-chem#1040]
### Description of the problem
Something strange happened to the temperature field in the file `GEOSFP.20210404.I3.4x5.nc`. Here is an extract from `ncdump -v,T GEOSFP.20210404.I3.4x5.nc | grep NaNf`:

`  -1.647451e-28, -8.237937e-13, NaNf, -1.60089e-17, -1.184781e-15, 
    9.555167e+22, 3.22281e+11, -3.999537e+34, -3.017839e-30, NaNf, 
    -1.460925e-29, 5.764052e+37, 1.765101e+35, 1.886043, NaNf, -7.579884e+08, 
    1.444538e-16, NaNf, -5.745918e-08, -9.579036e+10, -5.258085e-06, 
    1.436176e-16, 1.119095e-30, 0.1659331, 2.342981e-37, 1.203122e-06, NaNf, 
    -3.639667e+26, NaNf, 2.304086e+36, -0.0006254265, -2.416517e+31, 
    -1.855821e-35, -3.476218e+18, 0.2499086, 9.464427e+10, -5.425462, NaNf, 
    1.989213e-24, 4.590297e+14, NaNf, 5.875813e+36, 8.959077e+27, 
    4.824387e-08, 1.136062e+30, NaNf, 2.229169e-36, 6.81708e+20,`

### Description of troubleshooting performed
I checked a few different locations (aws, cc, Harvard) and the problem is the same. Other files for that date `2021-04-04` seem OK. I also checked `GEOSFP.20210404.I3.2x25.nc` which is fine. Perhaps an error was introduced during regridding?

**Comment by yantosca** [comment]
@YanshunLi-washu, this sounds like a corrupted met field file.  Could you look into it when you get a chance?

**Comment by YanshunLi-washu** [comment]
Sure Bob @yantosca 
Hi @jahwilson, have you checked the data from the washu data portal (http://geoschemdata.wustl.edu/ExtData/GEOS_4x5/GEOS_FP/). I did "ncdump -v,T GEOSFP.20210404.I3.4x5.nc | grep NaNf" and found no NaN values there.

**Comment by jahwilson** [comment]
Hi @YanshunLi-washu, you are right, the washu data portal version works fine - thanks!

I didn't check it initially as it was taking some time to connect. Cheers!

**Comment by yantosca** [comment]
Thanks @jahwilson @YanshunLi-washu.  I'll close out this issue.
