### ISSUE TITLE
[FEATURE REQUEST] Update global methane anthropogenic emissions to EDGAR v6

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#1044]
In the methane simulation, we currently use EDGAR v4.3.2 emissions (1970-2012) as the default global anthropogenic emissions inventory. EDGAR v6.0 emissions (1970-2018) are now available at https://edgar.jrc.ec.europa.eu/dataset_ghg60. We will update to these more recent emissions, but overwrite global oil, gas, and coal emissions with [GFEI v2 emissions](https://github.com/geoschem/geos-chem/issues/1043) from [Scarpelli et al. (2021)](https://acp.copernicus.org/preprints/acp-2021-911/acp-2021-911.pdf).

**Comment by yantosca** [comment]
Linked PR #1104 has been merged into the 13.4.0 development stream.  We can now close out this issue.
