### ISSUE TITLE
[BUG/ISSUE] Re. SpeciesConcSubset COLLECTION

### ISSUE THREAD

**Issue by luhu0** [geoschem/geos-chem#1045]
### What institution are you from?
U Montana

### Description of the problem
I set up the THE SpeciesConcSubset COLLECTION in the HISTORY.rc, and I got the 'Invalid latitude subset values for collection' error. But my lon and lat ranges were correct. 

### Description of troubleshooting performed
The problem appears to be in the history_mod.F90 in the Error check latitudes in Lines 1066-1067:

```
                IF ( CollectionSubsetInd(N,C) < -90.0_f8  .or.               &
                     CollectionSubsetInd(N,C) >  90.0_f8 ) THEN
```

### GEOS-Chem version
GCC v13.3.2 nested version

### Description of modifications
It should check the latitudes, not their indeces. The following replacements appear to fix it:

```
                IF ( Subset(1) < -90.0_f8  .or.               &
                     Subset(2) >  90.0_f8 ) THEN   
```

### Log files
- Build log (if applicable):
- Run logs (if applicable):
- Run script (if applicable):

### Software versions
- CMake version: 3.19.5
- Compilers (Intel or GNU, and version): GNU 9.2.0
- NetCDF version: 4.7.4

**Comment by yantosca** [comment]
I have issued a fix in commit 9ab6931db5b556eafd0e002e9fd4fdbcbd5fbb44.  We are preparing a 13.3.4 release.

NOTE: This issue only affects GEOS-Chem Classic History diagnostics.
