### ISSUE TITLE
[QUESTION] OFFLINE_LIGHTNING and OFFLINE_BIOGENICVOC data required

### ISSUE THREAD

**Issue by jinlx** [geoschem/geos-chem#1046]
Hi there,

I am trying running GC in 2020 but it seems that the OFFLINE_LIGHTNING and OFFLINE_BIOGENICVOC are not in the washu server after 2019. I was wondering if the data is ready and if you could update that in the server if it's possible. 

Cheers,
Lixu

**Comment by YanshunLi-washu** [comment]
Hi @jinlx Hongjian Weng from Peking University is developing these data, I'll contact him and let you know ASAP.

**Comment by jinlx** [comment]
Thanks Yanshun! I appreciate it.

**Comment by yantosca** [comment]
Also note #1010 is a similar issue.

**Comment by YanshunLi-washu** [comment]
Thanks Bob @yantosca I already sent an email to Hongjian, haven't got any reply yet

**Comment by jinlx** [comment]
I guess the biogenic data will fine since we can run it online anyway. But the missing lightning data may have some impact on NOx.

**Comment by YanshunLi-washu** [comment]
@ltmurray Dr. Murray is working on that. Hi Dr. Murray do we have any updates on the update of offline lightning NOx?

**Comment by ltmurray** [comment]
2020 is available for MERRA2 at /ExtData/HEMCO/OFFLINE_LIGHTNING/v2020-03/MERRA2/2020.  GEOS-FP is delayed because a large amount of global native I3 met fields needed to be reprocessed for 2020 and 2021 as they were corrupt, and that only recently finished. For now, I'd recommend users just use MERRA2 lightning.

**Comment by YanshunLi-washu** [comment]
@ltmurray Thanks! Sorry about the delay of fixing the I3 fields, hope they are now good to use. Let me know if there is anymore met fields corruption.

**Comment by ltmurray** [comment]
Yes, the unconstrained fields have been calculated, and everything worked fine. It takes a few weeks to do the constraint at that resolution, and 2020 is going to be challenging because of the huge change in convection that occurred in FP, so will require extra testing.

**Comment by YanshunLi-washu** [comment]
Sounds great. Thanks for the efforts and letting us know. @jinlx

**Comment by YanshunLi-washu** [comment]
Hi @jinlx Hongjian told me it will take around two weeks to update the MERRA2-based offline biogenic voc emissions for 2020 and around three weeks to update the GEOSFP-based ones.

**Comment by jinlx** [comment]
Thanks for letting me know it @YanshunLi-washu ! I appreciate it. I will start with calculating it online and please free feel to close the comment.
