### ISSUE TITLE
GC13 ISSUE

### ISSUE THREAD

**Issue by random-dengf** [geoschem/geos-chem#1048]
### What institution are you from?
U of Toronto
### Description of the problem
I run GCClassic v13s/ifort v13/14(xe_2013.0.079) using MERRA2 at 2x2.5 (reduced 47) to simulate CO2 field, got extremely large and small values in north of 80degreeN after 1hr run, while everything is fine for similar 4x5 run. CO2 MR at level 1 attached. 

### Description of troubleshooting performed
Did 4x5 runs

### GEOS-Chem version
All  versions of  v13 GCClassic

### Description of modifications
Nothing

### Log files
- Build log (if applicable):
- Run logs (if applicable):
- Run script (if applicable):

### Software versions
- CMake version: 3.19.5
- Compilers (Intel or GNU, and version): ifort13/14(xe_2013.0.079) 
- NetCDF version: netcdf 4.
![SpeciesConc_CO2_in_GEOSChem SpeciesConc 20000101_0000z2x25](https://user-images.githubusercontent.com/95658889/144935943-633e5928-43f9-4546-8ef9-72a1826a7801.png)
2
![SpeciesConc_CO2_in_GEOSChem SpeciesConc 20010101_0000z4x5](https://user-images.githubusercontent.com/95658889/144935982-554913ea-faa8-46f4-b166-a18fe1573f26.png)

**Comment by yantosca** [comment]
Thanks for writing @random-dengf.  A couple of things:

  1. Could you attach your rundir configuration files (e.g. input.geos, HEMCO_Config.rc) to this issue?  Make sure that they end with .txt and you can just drag & drop into the comment box.
  2. Are you running an "out-of-the-box" simulation, or have you made modifications to the code?

**Comment by random-dengf** [comment]
Thanks.
1.  HEMCO_Config.rc and input.geos
[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/7669793/HEMCO_Config.txt)
[input.geos.txt](https://github.com/geoschem/geos-chem/files/7669803/input.geos.txt)
2. I did not  make any modification to the code.

**Comment by random-dengf** [comment]
I found the problem of my runs. I have a problematic initial condition.
Sorry for this complication.

**Comment by yantosca** [comment]
No worries @random-dengf.  Always feel free to post an issue if you have a question or encounter a problem.  I'll close this out now.  Thanks again.
