### ISSUE TITLE
Adding the species to the GEOS-Chem 12.1.0

### ISSUE THREAD

**Issue by liruiliruiliruilirui** [geoschem/geos-chem#1049]
Hello, everyone,
                       I wanted to add the species into the GEOS-Chem 12.1.0 with advection, dry and wet deposition. I have added the emission and basic information in HEMCO_Config.rc of merra2_2x25_RnPbBe and species_database.F90, respectively. Unfortunately, the added species only showed concentrations, while the dry and wet deposition cannot be calculated. Could you help me?

Best regards

**Comment by yantosca** [comment]
@liruiliruiliruilirui, thanks for writing.  Would you be able to update to a more recent version (say 13.3.4)?  By now 12.1.0 is two years old and it is hard for us to support these older versions.

Also in the newer versions of GEOS-Chem, the species database has been converted to a text-based file (species_database.yml) so it should be easier to add new species information there.

**Comment by liruiliruiliruilirui** [comment]
Dear Prof. Yantosca,
                    Thank for your reply! I will update to a more recent version and try to add the species in this version. I hope you can give me some advice when I have some problems with this issue. Many thanks!


Best regards
Rui Li


-----原始邮件-----
发件人:"Bob Yantosca" ***@***.***>
发送时间:2021-12-08 23:39:36 (星期三)
收件人: geoschem/geos-chem ***@***.***>
抄送: liruiliruiliruilirui ***@***.***>, Mention ***@***.***>
主题: Re: [geoschem/geos-chem] Adding the species to the GEOS-Chem 12.1.0 (Issue #1049)



@liruiliruiliruilirui, thanks for writing. Would you be able to update to a more recent version (say 13.3.4)? By now 12.1.0 is two years old and it is hard for us to support these older versions.

Also in the newer versions of GEOS-Chem, the species database has been converted to a text-based file (species_database.yml) so it should be easier to add new species information there.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yantosca** [comment]
Thanks for writing @liruiliruiliruilirui.  If you are new to GEOS-Chem 13, please take a look at some of the tutorial videos that we have on our GEOS-Chem Youtube Channel: https://youtube.com/c/geos-chem.  These will walk you through the process of setting up GEOS-Chem 13.

I'll close out this issue but feel free to open a new issue if you get stuck.  Thanks again!
