### ISSUE TITLE
[QUESTION] about SOA

### ISSUE THREAD

**Issue by yangning-code** [geoschem/geos-chem#1050]
### Ask a question about GEOS-Chem:
The chemical process by which SESQ and SVOCs (POG) are oxidized cannot be found in the KPP of GEOS-Chem, but other VOCs such as MTPA can be found. Which code can I find them under? There is another question. What is the relationship between the VBS's gas-solid distribution of MONITS/MONITU/HONIT generated by MTPA after oxidation?

**Comment by yantosca** [comment]
Thanks for writing @yangning-code.  To your questions:

  1. GeosCore/carbon_mod.F90 has the code where chemistry of SOA species are handled.
  2. I would ask the Aerosols Working Group (cc'ing @theloniuspunk @beckyalexander) about your VBS question, as that is more of a science question.

**Comment by theloniuspunk** [comment]
I don't know the answer to the VBS question. Maybe loop in Eloise or
Colette?

**Comment by yantosca** [comment]
Tagging @eamarais and @coletteheald

**Comment by eamarais** [comment]
Hi @yangning-code, the mechanism that includes MONITS and so on are described in Jenny Fisher's paper: https://acp.copernicus.org/articles/16/5969/2016/acp-16-5969-2016.pdf, so I've tagged @jennyfisher too.

**Comment by jennyfisher** [comment]
Thanks Eloise. We weren't using the SOA simulation in that work, so I'm not sure how it gets treated in a VBS scheme.

**Comment by yangning-code** [comment]
> 
Thanks
1. GeosCore/carbon_mod.F90 does have SESQ, but only the corresponding distribution under VBS, and there is no process of SESQ being oxidized. Compared with MTAP, there is one less process of SESQ being oxidized into secondary aerosol. Can I understand that after SESQ is discharged, I will directly use VBS for distribution?

**Comment by yangning-code** [comment]
Duplicate of #

**Comment by yangning-code** [comment]
> Hi @yangning-code, the mechanism that includes MONITS and so on are described in Jenny Fisher's paper: https://acp.copernicus.org/articles/16/5969/2016/acp-16-5969-2016.pdf, so I've tagged @jennyfisher too.

Thanks.
I read this article. This article contains the process of MTPA/MTPO/LIMO generating MONITS. When I sorted out the SOA mechanism of GEOS-Chem.13.2.1, I made a table. The table indicates POA, OPOA , SESQ is a process that is not oxidized, but there is a VBS allocation process. ISOP removes the VBS mechanism in 12.6. The rest of the SOA precursors have the oxidation process and the VBS mechanism. Maybe I haven’t found all of them, but I want to seek you For help, complete this piece of content.  
The content in the table comes from KPP/fullchem.eqn and GeosCore/carbon_mod.F90 
[GEOS-Chem SOA mechanism.xlsx](https://github.com/geoschem/geos-chem/files/7672594/GEOS-Chem.SOA.mechanism.xlsx)

**Comment by yangning-code** [comment]
I have another question. I think the SOA_SVPOA calculation method of PM2.5 should be modified, and the specific reasons are in the document. 
[SOA_SVPOA  PM2.5 calculation.docx](https://github.com/geoschem/geos-chem/files/7672661/SOA_SVPOA.PM2.5.calculation.docx)

**Comment by yangning-code** [comment]
I have another question. I think the SOA_SVPOA calculation method of PM2.5 should be modified, and the specific reasons are in the document.
[SOA_SVPOA  PM2.5 calculation.docx](https://github.com/geoschem/geos-chem/files/7672689/SOA_SVPOA.PM2.5.calculation.docx)

**Comment by eamarais** [comment]
HI @yangning-code, just to make sure I follow what's in your word doc. You're saying that the PM2.5 is greater for the ComplexSOA than it is for the SOA_SVPOA? By how much? Have you looked at which component is contributing to this issue with the AerosolMass diagnostic collection? Could it be to do with the OC to OM conversion factors (2.1, 1.5) applied to POA and OPOA?

**Comment by yangning-code** [comment]
> HI @yangning-code, just to make sure I follow what's in your word doc. You're saying that the PM2.5 is greater for the ComplexSOA than it is for the SOA_SVPOA? By how much? Have you looked at which component is contributing to this issue with the AerosolMass diagnostic collection? Could it be to do with the OC to OM conversion factors (2.1, 1.5) applied to POA and OPOA?

Thank you for your reply. PM2.5 specific differences are in the PM25 and its components difference document.
[PM25 and its components difference.docx](https://github.com/geoschem/geos-chem/files/7685577/PM25.and.its.components.difference.docx)

**Comment by yantosca** [comment]
I will close out this issue now.  Feel free to open another issue if you still have questions or concerns.
