### ISSUE TITLE
[QUESTION] Should nested model boundary conditions be generated as instantaneous or time-averaged?

### ISSUE THREAD

**Issue by eamarais** [geoschem/geos-chem#1051]
### Ask a question about GEOS-Chem:

The default setting of BoundaryConditions.mode in HISTORY.rc to save out boundary conditions is 'instantaneous'. Would it not be better to set this to 'time-averaged' to reduce influence of instantaneous changes in tracer species at the boundaries of nested domains (effectively smoothing out temporal variability)?

**Comment by yantosca** [comment]
Thanks @eamarais for writing.  That could work but I'm not sure of what the impact would be.  If you could try a short run and see if it improves things we can make the recommendation going forward.

**Comment by eamarais** [comment]
Sure @yantosca. I can look at this.
