### ISSUE TITLE
[BUG/ISSUE] Segmentation fault occurred when running HEMCO

### ISSUE THREAD

**Issue by yangxiajie** [geoschem/geos-chem#1052]
A segmentation fault occurred when running HEMCO coupled with GEOS-Chem 12.9.3: 
```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
libifcoremt.so.5   00002AE95C4672F6  for__signal_handl     Unknown  Unknown
libpthread-2.17.s  00002AE95E4D05E0  Unknown               Unknown  Unknown
geos               000000000091DE84  hcox_gfed_mod_mp_         292  hcox_gfed_mod.F90
geos               00000000008ADC60  hcox_driver_mod_m         646  hcox_driver_mod.F90
geos               000000000042DE32  hcoi_gc_main_mod_         934  hcoi_gc_main_mod.F90
geos               00000000005DF54B  emissions_mod_mp_         202  emissions_mod.F90
geos               0000000000406FB8  MAIN__                   1494  main.F90
geos               0000000000403BDE  Unknown               Unknown  Unknown
libc-2.17.so       00002AE95E902C05  __libc_start_main     Unknown  Unknown
geos               0000000000403AE9  Unknown               Unknown  Unknown
```
It seems that `hcox_gfed_mod.F90` has something wrong after I added a new dry matter. 

However, there is no specfic error occurred. I wonder if there is a way to solve this problem.

[Code_and_logs.zip](https://github.com/geoschem/geos-chem/files/7674667/Code_and_logs.zip)

Thank you very much.

**Comment by yantosca** [comment]
Thanks for writing @yangxiajie.  I would recommend that you re-configure and rebuild GEOS-Chem with the debug option (`-DCMAKE_BUILD_TYPE=Debug`.

The error seems to be happening at line 292 in hcox_gfed_mod.F90.  It seems like it might be a parallelization error.  If you have added new variables within a parallel loop then you might need to hold them !$OMP PRIVATE.  Please see our [Parallelizing GEOS-Chem wiki page](http://wiki.seas.harvard.edu/geos-chem/index.php/Parallelizing_GEOS-Chem) for more information about how OpenMP parallel loops work.

**Comment by yangxiajie** [comment]
Thank you @yantosca .

I find the `Segmentation fault` occurred where I call the modeled species concentration.

First, I try to use` Ind_('HNO2') `to call the HNO2 concentration by setting `Spc(I,J,L)=State_Chm%Species(I,J,L,Ind_('HNO2'))`. However, errors occuurred when compling the code, which are :
```
../../../lib/libHeaders.a(state_chm_mod.o): In function `state_chm_mod_mp_getnumprodlossspecies_':
state_chm_mod.F90:(.text+0xa85e): undefined reference to `gckpp_monitor_mp_fam_names_'
../../../lib/libHeaders.a(state_chm_mod.o): In function `state_chm_mod_mp_mapprodlossspecies_':
state_chm_mod.F90:(.text+0xaa0f): undefined reference to `gckpp_monitor_mp_fam_names_'
../../../lib/libHeaders.a(species_database_mod.o): In function `species_database_mod_mp_unique_species_names_':
species_database_mod.F90:(.text+0x128e): undefined reference to `gckpp_monitor_mp_spc_names_'
species_database_mod.F90:(.text+0x1372): undefined reference to `gckpp_monitor_mp_spc_names_'
species_database_mod.F90:(.text+0x1e9b): undefined reference to `gckpp_monitor_mp_spc_names_'
make[8]: *** [exe] Error 1
make[8]: Leaving directory `/public/home/yangxj/geos_chem_12.9/Code.12.9.3_test_1/HEMCO/src/Interfaces'
make[7]: *** [all] Error 2
make[7]: Leaving directory `/public/home/yangxj/geos_chem_12.9/Code.12.9.3_test_1/HEMCO/src/Interfaces'
make[6]: *** [check] Error 2
make[6]: Leaving directory `/public/home/yangxj/geos_chem_12.9/Code.12.9.3_test_1/HEMCO'
make[5]: *** [lib] Error 2
make[5]: Leaving directory `/public/home/yangxj/geos_chem_12.9/Code.12.9.3_test_1/HEMCO'
make[4]: *** [libhemco] Error 2
make[4]: Leaving directory `/public/home/yangxj/geos_chem_12.9/Code.12.9.3_test_1/GeosCore'
make[3]: *** [lib] Error 2
make[3]: Leaving directory `/public/home/yangxj/geos_chem_12.9/Code.12.9.3_test_1/GeosCore'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/public/home/yangxj/geos_chem_12.9/Code.12.9.3_test_1/GeosCore'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/public/home/yangxj/geos_chem_12.9/Code.12.9.3_test_1'
```
Then I use `SPC(I,J,L) = State_Chm%Species(I,J,L,State_Chm%HetInfo%HNO2%mId)`  instead of `Ind_('HNO2')`, same as `gckpp_Hetrate.F90`. After theat, the Code can be compiled successfully while `segmentation fault` occurred when running GC.

I wonder if there is wrong for calling species concentration, or how can I fix errors above?

Thank you :)

**Comment by yangxiajie** [comment]
Thank you @yantosca 

I have already fix that after I see `GeosCore/hco_interface_gc_mod.F90` .

Thank you very much again :)
