### ISSUE TITLE
[QUESTION] Are SO4D1-D4 included in PM2.5?

### ISSUE THREAD

**Issue by lixiao-bit** [geoschem/geos-chem#1058]
### Ask a question about GEOS-Chem:

Hello!

Are SO4D1-SO4D4 included in the calculation of PM25 in GC, or only SO4? 

This is the default calculation in the model: 

"PM25 = ( NH4 + NIT  + SO4 ) * 1.10
     + BCPI 
     + BCPO 
     + ( OCPO + ( OCPI * 1.05 ) ) * (OM/OC ratio)  # OM/OC ratio = 2.1 by default
     + DST1 
     + DST2 * 0.30                                 # F. Yu suggests 30% of DST2 (Nov 2011); prior value was 38% of DST2
     + SALA * 1.86
     + SOA  * 1.05"

I think there are some problems with this way of calculating

I am not sure the factor for SO4D1-SO4D4 should follow SO4's factor or the DST1-DST4's factor, as shown below:

"PM25 = ( NH4 + NIT  + SO4**_+ SO4D1 + SO4D2 + SO4D3 + SO4D4_** ) * 1.10
     + BCPI 
     + BCPO 
     + ( OCPO + ( OCPI * 1.05 ) ) * (OM/OC ratio)  # OM/OC ratio = 2.1 by default
     + DST1 
     + DST2 * 0.30                                 # F. Yu suggests 30% of DST2 (Nov 2011); prior value was 38% of DST2
     + SALA * 1.86
     + SOA  * 1.05"

or

"PM25 = ( NH4 + NIT  + SO4 ) * 1.10
     + BCPI 
     + BCPO 
     + ( OCPO + ( OCPI * 1.05 ) ) * (OM/OC ratio)  # OM/OC ratio = 2.1 by default
     + DST1 _**+ SO4D1 **_
     + (DST2 _**+ SO4D2**_) * 0.30                                 # F. Yu suggests 30% of DST2 (Nov 2011); prior value was 38% of DST2
     + SALA * 1.86
     + SOA  * 1.05"

thank you.

**Comment by yantosca** [comment]
Thanks for writing @lixiao-bit.  I would run this by the Aerosols Working Group (@theloniuspunk @beckyalexander).  

Also note: the SO4D1-D4 species are only used for the simulation with dust aciduptake, which is maintained by the community, and is not covered by our regular benchmarking process.  So it is possible that the PM2.5 may need to be updated for the aciduptake simulations.

**Comment by theloniuspunk** [comment]
Becky may have a better feel for this, but I think that the first option (( NH4 + NIT + SO4**+ SO4D1 + SO4D2 + SO4D3 + SO4D4** ) * 1.10) makes more sense.

**Comment by theloniuspunk** [comment]
Right! Good call Becky! They should use the bin fractions used for dust.

**Comment by lixiao-bit** [comment]
thanks for hearing from you.

the radius of SO4D1 SO4D2 SO4D3 SO4D4 is defined as 0.7, 1.4, 2.4 and 4.5 microns in species_data.yml. considering this information, I consider that  SO4D1 should be treated the same as DST1, SO4D2 should be treated the same as DST2, SO4D3 should be treated the same as DST3, SO4D4 should be treated the same as DST4 when calculate PM2.5.  That is to say,  in my opinion, PM2.5 should be calculated as below:

"PM25 = ( NH4 + NIT + SO4 ) * 1.10
+ BCPI
+ BCPO
+ ( OCPO + ( OCPI * 1.05 ) ) * (OM/OC ratio) # OM/OC ratio = 2.1 by default
+ DST1 **+ **_SO4D1_** **
+ (DST2 + **_SO4D2_**) * 0.30 # F. Yu suggests 30% of DST2 (Nov 2011); prior value was 38% of DST2
+ SALA * 1.86
+ SOA * 1.05"

however, I am still not sure about this question.

thank you.

**Comment by theloniuspunk** [comment]
Hi,

No, what I'm saying is to do PM25 = ( NH4 + NIT + SO4 + *SO4D1* + *SO4D2* *
0.30 ) * 1.10 ...

Jeff

**Comment by lixiao-bit** [comment]
Thanks for hearing from you.

I got it.

so, what is the correct way for calculating PM10?  

This is the way for PM10 on the website:
"PM10 = PM2.5 
     + ( DST2 * 0.7  )
     + DST3
     + ( DST4 * 0.9  )
     + ( SALC * 1.86 )   # NOTE: The value of 1.86 is the SSA_GROWTH factor at 35% RH"

therefore, Should this be the correct way to calculate PM10 ?
"PM10 = ( NH4 + NIT + SO4 + SO4D1 + SO4D2*0.30 ) * 1.10 + 
     + ( DST2 * 0.7  )
     + DST3
     + ( DST4 * 0.9  )
     + ( SALC * 1.86 )   # NOTE: The value of 1.86 is the SSA_GROWTH factor at 35% RH"

or 

"PM10 = ( NH4 + NIT + SO4 + SO4D1 + SO4D2*0.30 ) * 1.10 + 
     + ( DST2 * 0.7  )
     + DST3 + **_SO3D1_** 
     + ( DST4 * 0.9  ) + ( **_SO4D4 * 0.9_**  ) 
     + ( SALC * 1.86 )   # NOTE: The value of 1.86 is the SSA_GROWTH factor at 35% RH"

thank you.

**Comment by lixiao-bit** [comment]
thank you. i got it.

**Comment by yantosca** [comment]
I will close out this issue.  Feel free to open a new issue if you still have problems or concerns.
