### ISSUE TITLE
[BUG/ISSUE]Larg discrepancies in methane concentration between v12.5.0 and v13.3.3

### ISSUE THREAD

**Issue by Rainbow1994** [geoschem/geos-chem#1059]
### Description of the problem
I found new versions of GC that could use OH fields simulated by full chemistry run, so I prepared to use the latest version. When I compared the 1-month benchmark using the same emission inventories and restart field, it seems large discrepancies (nearly 100 ppbv) in surface concentration fields between v12.5.0 and v13.3.3. I tried to turn off OH and Cl sinks, but the result was similar. I need your help to check is there anything wrong with the transportation process in GC.    

### Description of troubleshooting performed
Here is the comparison result about surface methane field with OH and Cl sink turned off
![concentration](https://user-images.githubusercontent.com/29177864/145545657-a9e5a9f2-2a1e-42e9-939b-5f8b42a200b5.png)

And it's the difference in our total emission diagnosis outputs and restart fields.

![EmisCH4_Total](https://user-images.githubusercontent.com/29177864/145545633-15deafae-f7f5-4eee-b661-bd1d5e9e8d24.png)
![restart](https://user-images.githubusercontent.com/29177864/145545643-a4dab14d-f01d-4145-b370-57d7f55f9176.png)

### GEOS-Chem version
v12.5.0 and v13.3.3

- CMake version:
- Compilers (Intel or GNU, and version):
- NetCDF version:

**Comment by yantosca** [comment]
Thanks for writing @Rainbow1994.  I know that there have been a lot of changes to the methane simulation since 12.5.0, and I think several emissions sources have changed.  Tagging @msulprizio @pennelise @hannahnesser, as I am not as familiar with the methane simulation.

**Comment by yantosca** [comment]
I am going to close this issue as the methane simulation has been migrated up to GEOS-Chem 14, and the input emissions etc. have been updated.  GEOS-Chem 12 versions are no longer supported.
