### ISSUE TITLE
[BUG/ISSUE] Segmentation fault occurred when running GEOS-Chem v902 without specific error

### ISSUE THREAD

**Issue by Yuhang-Zhang** [geoschem/geos-chem#1060]
A segmentation fault occurred when I was running 2x2.5 simulaiton on 2021.04.04 using GC v902. The met fields are GEOS-FP and no modifications were made to the source code.

<img width="581" alt="0b40c676649efb0dc3fbe8d41913bb7" src="https://user-images.githubusercontent.com/58896800/145549694-f319c2f5-997b-4183-9f03-c605ddaff71a.png">

There is no specific error, and the same bug arised when I was running nested 0.25x0.3125_CH simulation on the same day. I think perhaps there is something wrong in met fields. 

Thank you very much.

**Comment by yantosca** [comment]
Hi Yuhang.  I think the met fields were corrupted.  Try downloading them from the WashU server again (@YanshunLi-washu reprocessed them recently).

**Comment by YanshunLi-washu** [comment]
Yes @Yuhang-Zhang I reprocessed them recently. Please try redownload from http://geoschemdata.wustl.edu/. Let me know if there is still errors.

**Comment by Yuhang-Zhang** [comment]
> Hi Yuhang. I think the met fields were corrupted. Try downloading them from the WashU server again (@YanshunLi-washu reprocessed them recently).



> Yes @Yuhang-Zhang I reprocessed them recently. Please try redownload from http://geoschemdata.wustl.edu/. Let me know if there is still errors.

Thanks for your all kindly reply. I've downloaded the met fileds on that day from  http://geoschemdata.wustl.edu/, but the same error still arised. Have you tested them by running a simple one-day simulation? I'm not sure now whether there are something else wrong or not. 

Thanks again!
