### ISSUE TITLE
[BUG/ISSUE] Permission denied to download MERRA2 August, 2021

### ISSUE THREAD

**Issue by shirleyxyliu** [geoschem/geos-chem#1066]
### What institution are you from?
Hi this is Xueying from University of Houston. 

### Description of the problem
(Not sure if it's just me but) Writing to report a download problem for 2021 August MERRA2 met fields from http://geoschemdata.wustl.edu. Users are not granted access for this resources according to the download page http://geoschemdata.wustl.edu/ExtData/GEOS_2x2.5/MERRA2/2021/08/. Could support team kindly check this? Thanks!

**Comment by YanshunLi-washu** [comment]
@shirleyxyliu Hi, should be fine now. I updated it last night. Thanks

**Comment by shirleyxyliu** [comment]
Noted with thanks.
