### ISSUE TITLE
[FEATURE REQUEST] Update IsCoards script to give GEOS-Chem compatibility warnings

### ISSUE THREAD

**Issue by lizziel** [geoschem/geos-chem#1068]
This feature request is a follow-up to GCHP issue https://github.com/geoschem/GCHP/issues/166. That issue reported problems reading a file into GCHP due to formatting issues. These issues have been encountered by users in the past but are hard to debug. 

We recommend users run the [IsCoards](https://github.com/geoschem/geos-chem/blob/main/NcdfUtil/perl/isCoards) script on new input files. Putting checks for these common issues into the script would be useful. Since these format requirements are specific to GEOS-Chem we could issue warnings that the file will not be compatible with GEOS-Chem even if COARDS-compliant, and print a suggestion on what to change.

Here are requirements that could be added:

Dimension ordering 'lat', 'lon', 'time'
Use lowercase letters for dimension names
Units string does not include decimals (e.g. does not contain `00:00:0.0`)
Include positive attribute if level dimension is present

**Comment by yantosca** [comment]
Also see https://github.com/geoschem/geos-chem/issues/281

**Comment by yantosca** [comment]
These changes have now all been incorporated into [netcdf-scripts v0.14](https://github.com/geoschem/netcdf-scripts/releases/tag/v0.1.4).

**Comment by lizziel** [comment]
Excellent! I am closing out this feature request now.
