### ISSUE TITLE
[QUESTION] Include time-invariant fields in a new history diagnostic file?

### ISSUE THREAD

**Issue by joeylamcy** [geoschem/geos-chem#107]
Hi GCST, 

I would like to know how to add a 2D field (constant in time) to a history diagnostic file, just like how the surface area is present in each of the history diagnostic file. Also, does creating my own collection complicate the situation?

Of course it would be possible to save the 2D field for each time step, but it would make the file quite a lot smaller if the time dimension can be removed.

#### Version
(Branched from) GEOS-Chem v12.2.0

**Comment by yantosca** [comment]
Thanks for writing.  The index fields (including AREA) are written when the file is created in history_netcdf_mod.F90:

https://github.com/geoschem/geos-chem/blob/601e919cf1163839d743daea0d835bde88a3de82/History/history_netcdf_mod.F90#L582-L625
I think it would be much easier to define a special collection with the frequency "End" just for the constant field that you want to save out.  Then when you analyze the data, you can use the xarray openmf_dataset function to read data from multiple files into the same dataset, e.g.:

```python
import xarray as xr
files = ['GEOSChem.Constant.20170101_0000z.nc4',  'GEOSChem.SpeciesConc.20170101_0000z.nc4']
ds = xr.open_mfdataset(files)
```

Then if you want to create a new netCDF file with the constant field included within it, type:

```python
ds.to_netcdf('Combined_data.nc4')
```

This avoids having to touch history_netcdf_mod.F90 at all.

**Comment by joeylamcy** [comment]
That's a good alternative. Thank you for the suggestion.
