### ISSUE TITLE
[QUESTION]How to specify Ocean regions in GEOS-Chem?

### ISSUE THREAD

**Issue by yangxiajie** [geoschem/geos-chem#1070]
In GEOS-Chem v12.9, I want to add a new reaction, which is only on the ground. I wonder if there is a way to specify OCEAN regions in `gckpp_Hetrate.F90`, so that I can set rate constant as 0 at ocean ?

Thank you for your help.

**Comment by yantosca** [comment]
You should be able to use `State_Met%IsWater(I,J)` from within `gckpp_HetRates.F90`. This field is TRUE if (I,J) is a predominantly ocean box and FALSE if not.

**Comment by yangxiajie** [comment]
Thank you @yantosca .

Now I fix that. Thank you for your help again :) .
