### ISSUE TITLE
[QUESTION] PHOTOL index and J value

### ISSUE THREAD

**Issue by jinlx** [geoschem/geos-chem#1071]
Hi there, I am trying to make GEOS-Chem chemsitry compatible to a matlab-based box model. For J values in GC, I suppose that all values are calculaed by FAST-JX, which I am not very familiar with. In my understanding, the index is based on the id# in FJX_j2j.dat. The link is provided below.

http://geoschemdata.wustl.edu/ExtData/CHEM_INPUTS/FAST_JX/v2021-10/FJX_j2j.dat

I found that there are several reactions (2nd column) have same factor/fastJX/code(a6) (3rd column). See example for #139-#141. I was wondering if these reactions are sharing the same J values even though they have different PHOTOL id. 

```
 138 RIPA      PHOTON    MVK CH2O OH HO2                   1.000 /CH3OOH/
 139 RIPB      PHOTON    MACR CH2O OH HO2                  1.000 /CH3OOH/
 140 RIPC      PHOTON    OH HO2 HC5A                       1.000 /CH3OOH/
 141 RIPD      PHOTON    OH HO2 HC5A                       1.000 /CH3OOH/
```

Cheers,
Lixu

**Comment by yantosca** [comment]
Hi @jinlx.  I believe that in this case, RIPA, RIPB, RIPC, and RIPD use the same optical properties (e.g. cross-sections, quantum yields) as CH3OOH.  I am not sure if that would lead to identical J-values output, but you can look in the JValues collection to make sure.

I believe this is done when species are similar enough to each other that you can assume the same optical properties, and if there are no measured optical properties available.

**Comment by yantosca** [comment]
I will close out this issue for now.  Please let us know if you still have questions or concerns.
