### ISSUE TITLE
[FEATURE REQUEST] Anthropogenic Methane Emission Inventory for Canada

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#1072]
Anthropogenic CH4 emissions for Canada are available for 2018 as described in Scarpelli et al. (2021, submitted). These emissions should be used in the standard CH4 simulation and will be used in the Integrated Methane Inversion (IMI version 1.0) workflow (Varon et al., in prep).

Reference:

>Scarpelli, T.R., D.J. Jacob, M. Moran, F. Reuland, and D. Gordon, [https://projects.iq.harvard.edu/acmg/publications/gridded-inventory-canadas-anthropogenic-methane-emissions A gridded inventory of Canada's anthropogenic methane emissions], submitted to Environ. Res. Lett., 2021.

**Comment by yantosca** [comment]
PR #1104 has been merged into the 13.4.0 development stream, so we can close out this issue.
