### ISSUE TITLE
[QUESTION] Error while zero out emission from a particular region. 

### ISSUE THREAD

**Issue by map06** [geoschem/geos-chem#1075]
### Description of the problem
I want to zero out emission within a particular rectangular grid. I followed the following link :
http://wiki.seas.harvard.edu/geos-chem/index.php/HEMCO_examples

1. Added scale factor in scale factor  section as follows:

 
```
###############################################################################
### BEGIN SECTION SCALE FACTORS
###############################################################################

# ScalID Name sourceFile sourceVar sourceTime C/R/E SrcDim SrcUnit Oper

(((EMISSIONS
501 SCALE_COUNTRY 0.0 - - - xy unitless 1 1011
```

2. Then added a mask with grid. For checking, I used Australian grid similar to example.

```
#==============================================================================
# Country/region masks
#==============================================================================
1011 MY_AUSTRALIA_MASK 105.0/-46.0/160.0/-10.0 – 2000/1/1/0 C xy 1 1 105.0/-46.0/160.0/-10.0
```

Then added the values to emission inventory as follows:
```
0 CEDS_NO_AGR     $ROOT/CEDS/v2020-08/$YYYY/NO-em-total-anthro_CEDS_$YYYY.nc            NO_agr             1970-2017/1-12/1/0 C xy kg/m2/s NO    25/501     1 5
```
But, whenever I run the model I get error:
```
Reading fields of HEMCO configuration file: HEMCO_Config.rc
At line 312 of file /home/ubuntu/tutorial/gc_merra2_fullchem/CodeDir/src/HEMCO/src/Core/hco_chartools_mod.F90
Fortran runtime error: Bad integer for item 1 in list input
```
[HEMCO_Config.zip](https://github.com/geoschem/geos-chem/files/7770562/HEMCO_Config.zip)

### GEOS-Chem version
13.0.0

**Comment by yantosca** [comment]
Hi @map06, thanks for writing,  If your mask is square then you shouldn't need to use the country mask first.  You should just be able to use:

```console
0 CEDS_NO_AGR   ...etc...  1970-2017/1-12/1/0 C xy kg/m2/s NO    25/1011     1 5
```

**Comment by map06** [comment]
@yantosca Thank you. I was able to zero out emission, creating a square mask.
