### ISSUE TITLE
[BUG/ISSUE]NetCDF I/O Modules

### ISSUE THREAD

**Issue by cacaowang** [geoschem/geos-chem#1078]
### Description of the problem
Simulation for December under Fully Chemistry and MERRA with 2X2.5 in 2017, 2018, 2019 separately. It is used as a control simulation, so all the settings are default and no modifications. But the simulation stopped at opening the files of 12/28 for all of these years.

### Description of troubleshooting performed
Describe any troubleshooting that you have already performed here. Also include any leads or suspicions here.

### GEOS-Chem version
GEOS-Chem version 13.0.2

### Log files
- Build log (if applicable):
![Screen Shot 2021-12-31 at 11 24 28 AM](https://user-images.githubusercontent.com/89403837/147833971-2009e3a0-eff6-4b22-ae96-67ab577ff3bc.png)

- Run logs (if applicable):
<img width="1110" alt="Screen Shot 2021-12-22 at 4 04 14 PM" src="https://user-images.githubusercontent.com/89403837/147833955-d64a6d48-e01d-4978-a416-83eece302b2f.png">

- Run script (if applicable):

### Software versions
Currently Loaded Modules:
  1) intel/2019   2) cmake/3.21.1   3) netcdf/4.7.1   4) hdf5/1.10.4   5) jasper/1.9   6) zlib/1.2.11   7) libpng/1.2.50   8) python/3.8

**Comment by yantosca** [comment]
Thanks for writing @cacaowang.  This was a known issue in 13.0.2 and has since been fixed in later versions.  Please see: https://github.com/geoschem/HEMCO/pull/85 and
https://github.com/geoschem/HEMCO/issues/84.

**Comment by cacaowang** [comment]
Hi @yantosca Thank you for it.
