### ISSUE TITLE
how to decide spin up time for mercury simulation?

### ISSUE THREAD

**Issue by chakri6023** [geoschem/geos-chem#1079]
### Ask a question about GEOS-Chem:
1. I want to understand how to give and where to give spin up time as an input to the model.
2. I want to run nested mercury simulation over asian region for 2 years. I am confused how much should be the spin up time for my simulation?

**Comment by yantosca** [comment]
For the Hg simulation you probably would need a spinup of about 6 months or so.  Maybe a year is better but that is up to you.

**Comment by yantosca** [comment]
Also "spin up" is best done as a separate simulation.  The start & end dates are given in input.geos.  See our Getting Started with GEOS-Chem page at http://manual.geos-chem.org/.
