### ISSUE TITLE
[QUESTION]How to save budget of OH and HO2 ?

### ISSUE THREAD

**Issue by yangxiajie** [geoschem/geos-chem#1080]
In GEOS-Chem v12.9.3, I try to save budget of OH and HO2 by THE Budget COLLECTION in `HISTORY.rc`.  I also set OH and HO2 as  Advected species by setting `Is_Advected: true` at `species_database.yml`. However, the budget of OH and HO2 still can not be saved in Budget diagnostic files. 
I wonder how to save budget of OH and HO2 from model? 
Thank you for your help.

**Comment by yantosca** [comment]
Thanks for writing @yangxiajie.  Could you post your HISTORY.rc file here?

The Budget collection will provide the change in species attributed to specific operations (like Transport, Convection, Wetdep, etc).  We no longer use this diagnostic collection as it was proven to add a lot of computational overhead to our benchmark simulations. 

You can get an idea of how we compute budgets in the benchmark by looking at https://github.com/geoschem/gcpy/blob/main/gcpy/budget_ox.py.  Maybe you can adapt that for your purposes.

**Comment by yangxiajie** [comment]
Thank you @yantosca . I have posted my HISTORY.rc file here.

I have a question about the budget calculations. How can I have a budget about a species due to a specific reaction (e.g. a budget of OH from NO + HO2) ? 

Thank you for your time.
[HISTORY.zip](https://github.com/geoschem/geos-chem/files/7874984/HISTORY.zip)
