### ISSUE TITLE
[BUG/ISSUE] I encounter a bug 

### ISSUE THREAD

**Issue by wenjie1992** [geoschem/geos-chem#1085]
### What institution are you from?
I am from Max-Planck institute for chemistry

### Description of the problem
Describe your problem here.  Describe the steps to reproduce the problem here, if possible.

I am running geos chem with nested grid mode. I set up to running for a month with each wall time of 5 days. After I submit the job, only the first wall time can be finished. But the following wall time failed due to an abrupt stop. There is no additional error reported in gc.log or Hemco.log. The tjob.error file prompt that "longjmp causes uninitialized stack frame ***: ./gcclassic terminated". The enclosed is the log files (the first wall time and second wall time) and the tjob.error file. 
I try to restart the running from the second wall time, it also failed.
In addition, I try to run for a month with only one wall time. However, it still failed due to an abrupt stop.  

### Description of troubleshooting performed
Describe any troubleshooting that you have already performed here. Also include any leads or suspicions here.

### GEOS-Chem version
13.2.0

### Description of modifications
Describe your modifications here.

### Log files
- Build log (if applicable):
- Run logs (if [applicable):
- Run script (if applicable):
[geos_chem.zip](https://github.com/geoschem/geos-chem/files/7835315/geos_chem.zip)

### Software versions
- CMake version:
- Compilers (Intel or GNU, and version):
- NetCDF version:

**Comment by yantosca** [comment]
Thanks for writing @wenjie1992.  I think your job may have run out of memory.  Please check to see that you have requested enough memory for the job. 

We are not familiar with the TJOB scheduler.  You might want to ask your sysadmin or IT staff about how to request more memory for your job.

**Comment by wenjie1992** [comment]
Dear Bob，

 I have asked my sysadmin and IT staff about this issue. They don't think that it is related to the amount of memory available. The following is their reply:


The first line of the tjob.err file reads:

forrtl: error (65): floating invalid

This comes from the Intel Fortran compiler and means that a invalid floating point operation has occured in the code. I suspect that the other errors follow from this. You should probably talk to the GEOS Chem developers again to debug this error. I don't think that it is related to the amount of memory available to the code.


Best regards


Wenjie


________________________________

**Comment by yantosca** [comment]
Thanks for the reply.  One question, did you add any modifications to the code or are you running it "out of the box"?  If you added modifications of your own then that is the place to check first.

You can compile the code with debugging flags on by passing the -DCMAKE_BUILD_TYPE=Debug when you configure GEOS-Chem.  That should tell you the place where the error occurred.

**Comment by sdeastham** [comment]
Could this be an OpenMP stack size issue? I didn't see `OMP_STACKSIZE` being set anywhere, and weird memory nonsense early in the run has always been one of the consequences of a too-small stacksize for me.

**Comment by wenjie1992** [comment]
Dear Bob,


Many thanks for your reminding. Sorry that I didn't clearly describe my problem before. When I run the nested mode with GEOSFP 0.25x0.3125 (V13.0 or later version), the first restart can be finished, but the second and later restart will fail. I think it is likely related to the restart file or restart procedure. The enclosed is the error.

Note that in HEMCO.config.rc, I have modified the GEOS-Chem restart from EY into CYS.  I didn't add any other modifications to the code.

Best regards

Wenjie

________________________________

**Comment by yantosca** [comment]
@wenjie1992, which version of Intel Fortran are you using?  If you have the time, you might want to try to recompile a short debugging job with Gfortran (i.e. use -DCMAKE_BUILD_TYPE=Debug when configuring the code), starting from the 6th of the month.  We find that Gfortran catches errors better than Intel Fortran does.
