### ISSUE TITLE
[QUESTION] Cannot reach GEOS-Chem data server from China

### ISSUE THREAD

**Issue by Jiangxiaodong-99999** [geoschem/geos-chem#1086]
### Ask a question about GEOS-Chem:
Hello, may I ask why the website for downloading data catalog cannot be opened in China?  A few days ago, data could be downloaded normally, but today, suddenly, data cannot be downloaded

**Comment by YanshunLi-washu** [comment]
Hi @Jiangxiaodong-99999, we can't open it in the US either. It could be some technical issues from the university server. I suggest trying to use the "GEOS-Chem Data (WashU)" globus endpoint for data downloading now. The website should be recovered when the server is back. Hi @LiamBindle, feel free to comment if I left any details. Thanks.

**Comment by LiamBindle** [comment]
Hi @Jiangxiaodong-99999, sorry for the inconvenience. The data portal is down right now, and it has been for a couple days (oops!). The admins are working on it right now. Please follow
- [\[BUG/ISSUE\] Unable to download from geoschemdata.computecanada.ca · Issue #758 · geoschem/geos-chem](https://github.com/geoschem/geos-chem/issues/758)
- [\[BUG/ISSUE\] Slowness on  · Issue #1024 · geoschem/geos-chem](https://github.com/geoschem/geos-chem/issues/1024)

for updates.
