### ISSUE TITLE
[BUG/ISSUE] KPP source code build in GEOS-Chem 13.3 leads to convergence issues

### ISSUE THREAD

**Issue by mvermeuel** [geoschem/geos-chem#1087]
### What institution are you from?
Please tell us what institution you are from.
University of Minnesota - Twin Cities

### Description of the problem
I am having a KPP solver error when I build a custom mechanism module in GC 13.3 using KPP 2.3.1.gc I get the known “Step size too small: T + 10*H = T or H < Roundoff” error over multiple grid cells when trying to run a fullchem 4 x 5 deg global run. I tried changing ATOL and RTOL in fullchem_mod.F90 by an order of magnitude in both directions and in some cases the simulation terminates by itself and in some cases it keeps running and makes a large (1 GB+) output log from the KPP debug. 

To get to this output I first ran the build_mechanism.sh script for gckpp.kpp in my GCClassic/src/GEOS-Chem/KPP/custom folder. In order to compile gcclassic successfully using this custom KPP I had to make some extra changes which seemed odd. There were some missing global variables in gckpp_Global.F90 so I needed to update gckpp.kpp and adding them in (K300_OVER_TEMP, NUMDEN, SR_TEMP, TEMP_OVER_K300, MW, and SR_MW). I also had to remove equations from the custom.eqn that came with GCClassic that involved the rates AqRate_SALAAL_xxx and HOCL or HOBRUptkBySO3mm and UptkByHSO3mm since those variables are not defined elsewhere. Once I corrected those issues I could successfully build gcclassic but when I tried to execute it in a run with an input.geos, a HEMCO_config.rc, and a GEOSChemRestart file that previously had no issue when using the fullchem module that came with GCClassic, I witnessed a convergence issue.

To test if there was anything off in my custom.eqn or initial gckpp.kpp file I just copied the directory of the "fullchem" module, changed nothing within it, used fullchem.eqn, and built KPP based on what was in the gckpp.kpp for the fullchem and I got  the same issues: missing variables and a convergence error. So it looks like there's some inconsistencies between the pre-compiled fullchem that comes with the GCClassic install and what happens when you build the mechanism using build_mechanism.sh.

The reason I want to use a custom mechanism is that I want to follow the production and loss rates of multiple tracers which requires me to modify the families in gckpp.kpp and I want to update the mechanism to add in some chemical equations.

### Other leads
I also noticed that gckpp_Integrator.F90 files for the custom build (header in figure below, left) and the fullchem (below, right) are different sizes and that the fullchem was built with kpp 2.3.3_gc and the custom uses kpp 2.3.1_gc. 
![image](https://user-images.githubusercontent.com/97476637/148851568-50aa7a14-2e43-4a14-9178-bb1f2ab911ac.png)

The documentation for kpp says to use 2.3.1_gc for any released GEOS-Chem versions and only use 2.3.3 for development so I did not use it. I also cannot successfully compile kpp 2.3.3_gc to test if using that will make a difference. I have attached the two gckpp_Integrator.F90 files for the custom build and fullchem if you want to look at the differences between the two. 
[gckpp_Integrator_custom.txt](https://github.com/geoschem/geos-chem/files/7842436/gckpp_Integrator_custom.txt)
[gckpp_Integrator_fullchem.txt](https://github.com/geoschem/geos-chem/files/7842437/gckpp_Integrator_fullchem.txt)

### GEOS-Chem version
GC 13.3.0

### Software versions
- CMake version: 3.16.2
- Compilers (Intel or GNU, and version): Intel 2018; gcc 8.2.0
- NetCDF version: 4.6.2-gcc8.2.0-serial

Thanks

Michael

**Comment by mvermeuel** [comment]
Thanks! That's what I thought the issue was but as I mentioned I thought I was not able to build KPP 2.3.3_gc successfully so I did not test it. It turns out it did build successfully I just was getting many warnings and notes during the build after make all and they looked like fatal errors but were not. I have attached my make all warning list in case it is helpful but I am now able to build my custom module and run my simulation successfully.

[make_all_output.txt](https://github.com/geoschem/geos-chem/files/7848688/make_all_output.txt)

**Comment by yantosca** [comment]
Great!  I just updated the documentation on the https://kpp.readthedocs.io site so that it reads properly now.  [See this link](https://kpp.readthedocs.io/en/latest/usage-details/installation.html#kpp-for-geos-chem-2-3-3-gc-for-geos-chem-13-3-0-and-later).

Also note: we are in the process of migrating to a new KPP repository (https://github.com/KineticPreProcessor/KPP) so at some point in the future we will retire the geoschem/KPP repo.  But geoschem/KPP is still the operational KPP repo for GEOS-Chem at this time.

I'll go ahead and close out this issue.  Thanks again!
