### ISSUE TITLE
[QUESTION]Can boundary condition files from an older version be used for nested grid simulation. 

### ISSUE THREAD

**Issue by bsuther** [geoschem/geos-chem#1089]
### Ask a question about GEOS-Chem:
Hello, 
I have boundary condition files from a previous run using GEOS-Chem version 13.1.0. I updated to version 13.3.3. Is it possible to still use the older boundary condition files, and if so what modifications would I need to make for them to be compatible?  Would it be best to just create new ones? Currently I am getting this error when I try to do it:

> HEMCO: Opening /rs1/researchers/n/nmeskhi/rundirs/gc13.1.0_4x5_geosfp_fullchem_RRTMG_BCs/OutputDir/GEOSChem.BoundaryConditions.20140301_0000z.nc4

HEMCO ERROR: Cannot find field BC_AONITA. Please check variable name in the co
 nfig. file

HEMCO ERROR: Error encountered in routine HCOIO_Read!

HEMCO ERROR: Error in HCOIO_DATAREAD called from HEMCO ReadList_Fill: BC_AONIT
 A
 --> LOCATION: ReadList_Fill (HCO_ReadList_Mod.F90)

HEMCO ERROR: Error in ReadList_Fill (4) called from HEMCO ReadList_Read
 --> L
 OCATION: ReadList_Read (HCO_ReadList_Mod.F90)
 Error in ReadList_Read called from hco_run
===============================================================================
GEOS-Chem ERROR: Error encountered in "HCO_Run"!
 -> at HCOI_GC_Run (in module GeosCore/hco_interface_gc_mod.F90)

THIS ERROR ORIGINATED IN HEMCO!  Please check the HEMCO log file for
additional error messages!
===============================================================================

===============================================================================
GEOS-Chem ERROR: Error encountered in "HCOI_GC_Run"!
 -> at Emissions_Run (in module GeosCore/emissions_mod.F90)
===============================================================================

===============================================================================
GEOS-CHEM ERROR: Error encountered in "Emissions_Run", Phase 0

Thank you for your help.

**Comment by yantosca** [comment]
Thanks @bsuther for writing.  In general we recommend to use the same GEOS-Chem version to generate the  boundary conditions to run the nested-grid simulations.  

In this case, there have been extra species such as AONITA added to GEOS-Chem 13.3.0, while other species like IONITA have been taken out.  These modifications came in due to chemistry mechanism updates in 13.3.0. That is the cause of the HEMCO error, that it can't find the new species in the old boundary conditions.

**Comment by bsuther** [comment]
Okay, I will create new boundary files. Thank you for your quick response!
