### ISSUE TITLE
[BUG/ISSUE] Malformed OFFLINE_BIOVOC data file for 2017-12-28

### ISSUE THREAD

**Issue by kilicomu** [geoschem/geos-chem#1091]
### What institution are you from?
Wolfson Atmospheric Chemistry Laboratories

### Description of the problem
The HEMCO data file [`OFFLINE_BIOVOC/v2019-10/0.5x0.625/2017/12/biovoc_05.20171228.nc`](http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_BIOVOC/v2019-10/0.5x0.625/2017/12/biovoc_05.20171228.nc) appears to malformed, and is causing my simulations to crash. Any chance it can be reprocessed?

### Description of troubleshooting performed
Looked at the GCHP log files to point me at the cause of the crash, narrowed it down to an `OFFLINE_BIOVOC` file by looking at dates and file sizes - you can see that the file for 2017-12-28 is much smaller than all others for the month. I dumped the data from that file using `ncdump` and there looks to be an awful lot more zeroes in that file than in the others!

### GEOS-Chem version
N/A

### Description of modifications
N/A

### Log files
N/A

### Software versions
N/A

**Comment by kilicomu** [comment]
Thinking about it...I'd be surprised if nobody else had hit this problem before with GC Classic...

The specific error message that I got came through GCHP's `allPEs.log`:

```
0000: CAP.EXTDATA: ERROR: ExtData could not find bracketing data from file template ./HcoDir/OFFLINE_BIOVOC/v2019-10/0.5x0.625/%y4/%m2/biovoc_05.%y4%m2%d2.nc for side R
```

Would this be handled differently in GC Classic?

**Comment by lizziel** [comment]
We've had issues with the offline biovoc files in the past due to the timestamps. In your ncdump what does it say the time for the file is?

**Comment by lizziel** [comment]
See also https://github.com/geoschem/GCHP/issues/84.

**Comment by lizziel** [comment]
One other thing. If your simulation is at 12/28 then the right bracket is likely 12/29, so that would be the problematic file.

**Comment by kilicomu** [comment]
Yep, you got it. The timestamp on the file for the 29th is not correct (set to the 27th!). I'll change that and give it another go.

However, I am still concerned about the file for the 28th - it weighs about 1MB vs the ~35MB of all other files in the month and is largely 0 where other files around it are not!

**Comment by lizziel** [comment]
Have you tried re-downloading the data? @YanshunLi-washu and @LiamBindle, this was fixed for the data available to download, correct?

**Comment by kilicomu** [comment]
Yeah I did - the `OFFLINE_BIOVOC` index at http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_BIOVOC/v2019-10/0.5x0.625/2017/12/ reports a file size of 932k for that file, compared with 35-39mb for the others.

**Comment by kilicomu** [comment]
I should say that touching up the timestamps in the files for the last few days of my simulation has got it working now, so, thanks for the pointer towards that!

**Comment by YanshunLi-washu** [comment]
Hi @kilicomu @lizziel , the PKU group recently produced a new version http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_BIOVOC/v2021-12/0.5x0.625/2017/12/.
Let me know whether this could help. Thanks

**Comment by kilicomu** [comment]
@YanshunLi-washu Thanks for the heads up - I actually grabbed this dataset already, so I'll see how it goes with my next simulation.

**Comment by lizziel** [comment]
@kilicomu, are you all set with this issue?

**Comment by kilicomu** [comment]
Sure, I've got my simulations running.
