### ISSUE TITLE
[BUG/ISSUE] seg fault in drydep in CESM and GEOS

### ISSUE THREAD

**Issue by lizziel** [geoschem/geos-chem#1093]
The following [code](https://github.com/geoschem/geos-chem/blob/9ab6931db5b556eafd0e002e9fd4fdbcbd5fbb44/GeosCore/drydep_mod.F90#L589-L595) in drydep_mod.F90 causes a segmentation fault in CESM and GEOS using ifort21 if the DryDepVel diagnostic is not enabled:

```
          ! Archive dry dep velocity for diagnostics in [cm/s]
          IF ( State_Diag%Archive_DryDepVel ) THEN
             S = State_Diag%Map_DryDepVel%id2slot(D)
             IF ( S > 0 ) THEN
                State_Diag%DryDepVel(I,J,S) = DVZ
             ENDIF
          ENDIF
```

There is a CESM work-around to simply skip this code if compiling with MODEL_CESM. I am applying the equivalent work-around while running GEOS. I have not been able to replicate the problem in GCHP or GC-Classic on the Harvard compute cluster.

I am also able to avoid the issue with this:

```
          ! Archive dry dep velocity for diagnostics in [cm/s]
          IF ( State_Diag%Archive_DryDepVel ) THEN
             S = 1
             IF ( S > 0 ) THEN
                State_Diag%DryDepVel(I,J,S) = DVZ
             ENDIF
          ENDIF
```

and also this:

```
          ! Archive dry dep velocity for diagnostics in [cm/s]
          IF ( State_Diag%Archive_DryDepVel ) THEN
                State_Diag%DryDepVel(I,J,D) = DVZ
          ENDIF
```

I am looking into why this issue is occurring by testing in GEOS and hope to have a fix for 13.4. @yantosca, do you have any insight? The problem came in with reduction of diagnostic memory update which introduced the id2slot array.

**Comment by yantosca** [comment]
@lizziel, have you tried this in GC-Classic with ifort21?  Wondering if there is an optimization issue or something.  Do we have ifort21 on Cannon?

**Comment by yantosca** [comment]
@lizziel, I found your env file for ifort21 and am running some tests.  Will report soon.

If you request DryDepVel output for a species that doesn't drydep, it should write an error messages then stop the run.   You might want to see if that is the case, maybe a CESM species needs to be flagged as dry-depositing in the species_database.yml.

**Comment by lizziel** [comment]
The issue is bit thornier than that.

- It only occurs when DryDepVel diagnostics are **off**.
- The seg fault is occurring at the start of the species do loop, not the code that is causing the issue.
- I verified `State_Diag%Archive_DryDepVel `is false.
- The seg fault can be avoided by adding a print right before the block that is causing the problem.
- It is a problem regardless of whether OpenMP is enabled.

**Comment by lizziel** [comment]
I was able to fix this issue by rearranging where the diagnostics are computed within drydep_mod.F90 subroutine `Update_DryDepFreq`. The fix is included in PR https://github.com/geoschem/geos-chem/pull/1088 (updates for GEOS). See commit https://github.com/geoschem/geos-chem/pull/1088/commits/621268c249495f4a544142483f04a8f9114702f2.
