### ISSUE TITLE
[FEATURE REQUEST] Stratospheric adjustment with RRTMG in GEOS-Chem

### ISSUE THREAD

**Issue by sdeastham** [geoschem/geos-chem#1094]
### Fixed dynamical heating with RRTMG, and other improvements
Our lab (MIT LAE) recently(ish) completed some work which uses RRTMG in GEOS-Chem v11-02 to evaluate the impacts of supersonic aviation on the environment. To facilitate this, we implemented the fixed dynamical heating assumption in RRTMG, allowing stratospherically-adjusted radiative forcing to be calculated at the tropopause (consistent with IPCC definitions) rather than the TOA and surface instantaneous radiative forcing which is standard in GEOS-Chem at the moment. This request is to signal that I'd like to merge the updated RRTMG into the GEOS-Chem main branch in the near future, pending appropriate approval and merge processes. New features:

* Evaluation of RF at the tropopause, as well as at the surface and TOA
* Fixed dynamical heating assumption (Feys at al, 1980; Maycock et al, 2011) allows evaluation of stratospheric adjustment
* Stratospheric temperature adjustment now available as an output
* Direct radiative effect of CO2, H2O, N2O, and CFCs can now be calculated and output if desired
* Removed arbitrary constraints which were left over from when UCX was optional (e.g. only including tropospheric BC in calculations)
* Added an implementation-agnostic message logging interface which allows GC to take advantage of pfLogger in MAPL [_not related to RRTMG - but was developed to assist with debugging_]
* Experimental implementation of seasonally-evolving FDH per Forster et al. (1997), with 

The new implementation is designed for use with GCHP. The GC-Classic call to RRTMG supports only the original functionality (instantaneous RF). Extension for use in GCHP should be relatively straightforward if a user is interested in doing so.

_References_

Fels S B, Mahlman J D, Schwarzkopf M D and Sinclair R W 1980 Stratospheric Sensitivity to Perturbations in Ozone and Carbon Dioxide: Radiative and Dynamical Response J. Atmos. Sci. 37 2265–97
de F. Forster P M and Shine K P 1997 Radiative forcing and temperature trends from stratospheric ozone changes J. Geophys. Res. 102 10841–55
Maycock a. C, Shine K P and Joshi M M 2011 The temperature response to stratospheric water vapour changes Quart. J. Roy. Meteor. Soc. 137 1070–82

**Comment by yantosca** [comment]
This has been added to the GEOS-Chem Model Development Priorities table (not prioritized, for now): 

http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_model_development_priorities#Feature_integration_not_yet_prioritized

**Comment by yantosca** [comment]
Also see this related fix for RRTMG build issues: https://github.com/geoschem/geos-chem/pull/1112

**Comment by msulprizio** [comment]
Pull request #2010 resolves this issue and has been merged into the 14.3.0 development branch
