### ISSUE TITLE
[BUG/ISSUE] Segmentation fault when running GEOS-Chem v13.3.2 aerosol only with 2x2.5 and finer resolution

### ISSUE THREAD

**Issue by nbderenzqy66** [geoschem/geos-chem#1096]
### What institution are you from?
Baylor University

### Description of the problem
I tried default settings to run GC v13.3.2 simulation of aerosol with MERRA2 2x2.5 and 0.5x0.625 (boundary conditions generated from MERRA2 4x5). 
The error message from the cluster is: "/var/spool/pbs/mom_priv/jobs/632778.batch.SC: line 36: 20349 Segmentation fault      (core dumped) ./gcclassic > GC_13.log"
I checked GC_13.log and HEMCO.log, there is no error in those files. I also followed Inter Fortran Compiler (http://wiki.seas.harvard.edu/geos-chem/index.php/Intel_Fortran_Compiler#Resetting_stacksize_for_Linux) and added ulimit commands both before compiling and in my bash file. The same error occured. I tried GEOSFP, GC v13.2.0, GC v12.9.3, all of them occurred segmentation faults. 

### GEOS-Chem version
13.3.2.

### Log files
- Build log (if applicable):
- Run logs (if applicable):
[GC_13.log](https://github.com/geoschem/geos-chem/files/7876201/GC_13.log)
[HEMCO.log](https://github.com/geoschem/geos-chem/files/7876202/HEMCO.log)
[error.txt](https://github.com/geoschem/geos-chem/files/7876207/error.txt)

- Run script (if applicable):
[aerosol_v13.txt](https://github.com/geoschem/geos-chem/files/7876205/aerosol_v13.txt)

### Software versions
- CMake version: 3.13.3
- Compilers (Intel or GNU, and version): gcc/8.2.0
- NetCDF version: netcdf/4.7.4

**Comment by yantosca** [comment]
Thanks for writing.  I think the issue is that INIT_UCX is being called for the aerosol-only simulation but it should only be called for the fullchem simualtion.  See the fix in commit https://github.com/geoschem/geos-chem/commit/0d2b8eaea9ae26c159b99083fb2382d017c48d2c, which will go into GEOS-Chem 13.4.0.  Also see

**Comment by nbderenzqy66** [comment]
> Thanks for writing. I think the issue is that INIT_UCX is being called for the aerosol-only simulation but it should only be called for the fullchem simualtion. See the fix in commit [0d2b8ea](https://github.com/geoschem/geos-chem/commit/0d2b8eaea9ae26c159b99083fb2382d017c48d2c), which will go into GEOS-Chem 13.4.0.
Thanks for the reply! Finally, the 2x2.5 simulation works by setting "export OMP_STACKSIZE = 14g" and using GEOSFP on our end. The 0.25x0.3125 simulation works by setting "export OMP_STACKSIZE = 256g" on our end. And the version we used is GEOS-Chem 13.3.2.

**Comment by yantosca** [comment]
Great.  I'll close out this issue.  Thanks for letting us know @nbderenzqy66.
