### ISSUE TITLE
[QUESTION] How to calculate the dry deposition velocity and wet deposition velocity

### ISSUE THREAD

**Issue by lixiao-bit** [geoschem/geos-chem#1098]
### Ask a question about GEOS-Chem:

Hi!

How to calculate the dry deposition velocity and wet deposition velocity? Can i calculate these two parameters by using the WetLossLS, WetLossConv, DryDep, and SpeciesConc ?

**Comment by yantosca** [comment]
Thanks for writing @lixiao-bit.  The dry-deposition velocity is computed in the `drydep_mod.F90` module and can be archived by saving out the [DryDep collection from the GEOS-Chem History diagnostics](http://wiki.seas.harvard.edu/geos-chem/index.php/History_collections_for_dry_deposition#The_DryDep_collection).

I do not know how to compute a wet deposition velocity, as I think this is not a term used in the computation of wet scavenging.  For more information, please see: http://geos-chem.org/Wet_deposition

**Comment by yantosca** [comment]
I will close out this issue for now.  Please feel free to open a new issue if you still have questions.
