### ISSUE TITLE
[FEATURE REQUEST] Define properties for all GEOS-Chem species in the species database

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#110]
The species database in GEOS-Chem currently primarily includes definitions of advected species. Many chemical species defined in KPP are not includes and are therefore assigned a molecular weight of -1. Daniel Jacob has suggested the following:

>Assign molecular weights to all non-transported species.  That some are proxies/lumped should not be a limitation – we can just assume MWs for them, and as long as we’re consistent from version to version that would be fine. Kelvin Bates could give you MWs for all these species.

**Comment by yantosca** [comment]
This is now slated for 12.8.0.

**Comment by msulprizio** [comment]
This is now slated for 12.9.0. In gcpy, we have converted to species database in YAML format and will ideally be reading this into GEOS-Chem instead of having the species database in Fortran. It makes more sense to add the species database updates listed here to the .yml file instead of to the much more cumbersome `species_database_mod.F90`.

**Comment by msulprizio** [comment]
A new file `species_database.yml` has been added to the `feature/SpeciesDatabase_YAML` branch. See https://github.com/geoschem/geos-chem/blob/feature/SpeciesDatabase_YAML/Headers/species_database.yml. 

This first draft has been sent to Kelvin Bates and the Chemistry Working Group leaders for assistance in filling in missing molecular weights for some chemical species defined in KPP. 

The updated species database may not officially be implemented until GEOS-Chem 13.0.0 because the Fortran-YAML package may rely on the new directory structure in GEOS-Chem that allows us to access common external libraries.

**Comment by msulprizio** [comment]
This is now complete in the `feature/SpeciesDatabase_YAML` branch and will be included in 12.9.0.
