### ISSUE TITLE
[BUG/ISSUE] Missing data for biovoc

### ISSUE THREAD

**Issue by XueyingYu-1993** [geoschem/geos-chem#1107]
### Description of the problem
The data of HEMCO/OFFLINE_BIOVOC/v2021-12/0.25x0.3125/2020/01 only up to Jan 28, missing Jan 29-31.

**Comment by YanshunLi-washu** [comment]
Hi @XueyingYu-1993 I've contact Hongjian who is the developer via email for fixing this. Thanks for yr patience.

**Comment by XueyingYu-1993** [comment]
Thank you! I very much appreciate it!
