### ISSUE TITLE
[BUG/ISSUE] Help regarding debug code to print species conc and reaction rates if integrate failed twice error is hit

### ISSUE THREAD

**Issue by SadiaToma** [geoschem/geos-chem#1108]
### Ask a question about GEOS-Chem:
Good afternoon. Recently, I was trying to run a GCHP simulation, my runs crashed with the following error:

```console
--> Step size too small: T + 10*H = T or H < Roundoff
 T=   782.054026812095      and H=  1.996249177370893E-013
 ### INTEGRATE RETURNED ERROR AT:            3           7          17
 Forced exit from Rosenbrock due to the following error:
 --> Step size too small: T + 10*H = T or H < Roundoff
 T=   678.098870177050      and H=  3.522081190087462E-013
 ## INTEGRATE FAILED TWICE !!! 
===============================================================================
GEOS-CHEM ERROR: Integrator error code : -7
STOP at INTEGRATE_KPP`
```

I was looking at the previous GCHP issues and found this previous issue https://github.com/geoschem/GCHP/issues/170#issuecomment-948727411 very helpful, where a debug code was added to print species conc and reaction rates if integrate failed twice error is hit. Since I could not figure out the problem yet, I think looking into the species conc and reaction rates​ would be very helpful for me. I would highly appreciate it if you could help me in this regard. 

Thanks,
Sadia

**Comment by yantosca** [comment]
Thanks for writing @SadiaToma.  Make sure to have these debug print statements in your code.  They should print out the values of the concentration (C array) and reaction rates (RCONST array) at the point of failure. 

https://github.com/geoschem/geos-chem/blob/9ab6931db5b556eafd0e002e9fd4fdbcbd5fbb44/GeosCore/fullchem_mod.F90#L1063-L1107

Look for concentrations and reaction rates that are either negative, Infinity, or Not-A-Number (NaN).  That will help point you to what went wrong.

**Comment by yantosca** [comment]
@SadiaToma It could be that a reaction rate encountered a division by zero (although when I cleaned up the reaction rates in the fullchem mechanism I tried to put in error traps for that).  It could also be that a species went to essentially zero concentration, which could be the case if the initial condition is very small.

**Comment by SadiaToma** [comment]
Thank you so much @yantosca for your quick response. I have one more question for now. After adding these lines of code, I think I need to recompile the code before running. Am I right?

Thanks.

**Comment by lizziel** [comment]
Yes, you will need to recompile before rerunning to get the changes to take effect. Make sure you remember to install step so that executable gets copied over to the run directory.

**Comment by SadiaToma** [comment]
Thanks @lizziel .

**Comment by SadiaToma** [comment]
Hi @yantosca, after adding the code lines, I was trying to recompile the code. But getting the following error: 

`/home/safrin/Code.GCHP.CAM.debug/src/GCHP_GridComp/GEOSChem_GridComp/geos-chem/GeosCore/fullchem_mod.F90(1015): error #6404: This name does not have a type, and must have an explicit type.   [FAILED2X]
              Failed2x = .TRUE.
--------------^

/home/safrin/Code.GCHP.CAM.debug/src/GCHP_GridComp/GEOSChem_GridComp/geos-chem/GeosCore/fullchem_mod.F90(1015): error #6303: The assignment operation or the binary expression operation is invalid for the data types of the two operands.
              Failed2x = .TRUE.
-------------------------^

compilation aborted for /home/safrin/Code.GCHP.CAM.debug/src/GCHP_GridComp/GEOSChem_GridComp/geos-chem/GeosCore/fullchem_mod.F90 (code 1)
`
It looks like it can not recognize "Failed2x". Do you have any thoughts on why that might be?

Thanks,
Sadia

**Comment by lizziel** [comment]
Hi Sadia, I think Bob's gone for the day but I can step in to help. That error indicates that the variable Failed2x was never declared with its type (logical). You need to add this line to the file: https://github.com/geoschem/geos-chem/blob/9ab6931db5b556eafd0e002e9fd4fdbcbd5fbb44/GeosCore/fullchem_mod.F90#L55.

**Comment by SadiaToma** [comment]
Thank you so much @lizziel. I am going to add those lines too.
