### ISSUE TITLE
[FEATURE REQUEST] Investigate saving REAL*8 fields to the restart file

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#111]
## Overview
We are looking into removing differences between GEOS-Chem runs that execute over a long period, and runs that are restarted.  One of the reasons for these differences might be insufficient precision in the GEOS-Chem restart files.  We can experiment with saving REAL*8 data to the SpeciesRst collection and see if this helps to improve the situation.

**Comment by yantosca** [comment]
While the History diagnostics had derived types that would allow for carrying diagnostics as REAL*8, the I/O code (in `History/history_netcdf_mod.F90` would cast everything to REAL*4 and then write it to netCDF.  This situation has been corrected in commit 652bb239abed2b12e4331ca0de18d0a3db2de7f7.  Several modifications were made to the following modules:

- `Headers/registry_mod.F90`
- `Headers/state_diag_mod.F90`
- `History/history_mod.F90`
- `History/history_netcdf_mod.F90`

Specifically, we now have included a variable within derived-type objects that indicates the KIND value (i..e. REAL*8 or REAL*4) for the netCDF output.  Prior to this, it was always assumed that netCDF variables would be written to disk with the same KIND value with which they were defined.

NOTE: Similar modifications need to be made in HEMCO in order to read in REAL*8 data.  Right now HEMCO can only read in REAL*4 data from netCDF files.

**Comment by msulprizio** [comment]
This will likely go into an early GEOS-Chem 13 version

**Comment by yantosca** [comment]
The GCC History can now save output as REAL*4 or REAL*8 (cf. https://github.com/geoschem/geos-chem/commit/6e004b7a9cb0d1dbd09e4142e79a5b984abf0f2e merge).

However, at present, HEMCO can still only read and carry REAL*4 data in its data structures.  This needs to be resolved first before this issue is closed.

**Comment by yantosca** [comment]
The remaining work needs to be done on the HEMCO side, as the GEOS-Chem "Classic" History component can now write REAL\*8 fields to disk.  

Therefore, I am closing out this issue, and have opened a new feature request (https://github.com/geoschem/HEMCO/issues/69) on the HEMCO repository issue tracer,
