### ISSUE TITLE
[QUESTION] How does the GFED emissions option affect the model simulations? 

### ISSUE THREAD

**Issue by Z-Dong-AK** [geoschem/geos-chem#1113]
Hi everyone! I am a new user of GEOS-Chem and currently I am trying to use GEOS-Chem to simulate PM2.5 in Alaska area. I made 4 sensitive test runs with slightly different settings in "GFED emission" and "nested option". The GFED emission part is in the HEMCO_Config.rc, and the difference is whether to set GFED_daily or GFED_3hourly to true. The "nested option" is in the geos.input "Nested grid simulation?". Here I show the comparison of PM2.5 of the same day between 4 sensitive runs.   
![Screenshot 2022-02-02 162445](https://user-images.githubusercontent.com/99012569/152506681-5eaf8fb9-637f-4e11-b5fd-570989aba844.png)
As the figure above shows, "nested option" affects the distribution of PM2.5 and "GFED daily or 3houly option" affects the intensity of the PM2.5 concentrations, with "daily" being much higher than "3hourly". In my expectation, both "daily" and "3hourly" should generate similar results (maybe different but should not be drastically different as my simulations show) I am curious about how GFED_daily and GFED_3hourly affect the simulation in the codes and computations, but as a new user I don't quite know how it works. Could someone explain to me about how the GFED emissions daily and 3hourly work in the GEOS-Chem model on the level of physics and chemistry meanings? As well as how the "nested option" work in the model?

**Comment by Z-Dong-AK** [comment]
[HEMCO_Config_Zhao.rc.txt](https://github.com/geoschem/geos-chem/files/8007630/HEMCO_Config_Zhao.rc.txt)
[input.geos_A.txt](https://github.com/geoschem/geos-chem/files/8007631/input.geos_A.txt)
[input.geos_B.txt](https://github.com/geoschem/geos-chem/files/8007632/input.geos_B.txt)
[input.geos_Dong.txt](https://github.com/geoschem/geos-chem/files/8007633/input.geos_Dong.txt)
[input.geos_Zhao.txt](https://github.com/geoschem/geos-chem/files/8007634/input.geos_Zhao.txt)
[HEMCO_Config_A.rc.txt](https://github.com/geoschem/geos-chem/files/8007635/HEMCO_Config_A.rc.txt)
[HEMCO_Config_B.rc.txt](https://github.com/geoschem/geos-chem/files/8007636/HEMCO_Config_B.rc.txt)
[HEMCO_Config_Dong.rc.txt](https://github.com/geoschem/geos-chem/files/8007637/HEMCO_Config_Dong.rc.txt)
Hi, @yantosca, the HEMCO_Config.rc and input.geos for 4 runs are listed above. Thanks!

**Comment by yantosca** [comment]
Hi @Z-Dong-AK, thanks for your patience.  I looked at your control A input.geos:
```console
%%% GRID MENU %%%       :
Grid resolution         : 0.5x0.625
Longitude min/max       : -175.0 -125.0
Latitude  min/max       : 45.0   80.0
 Half-sized polar boxes?: T
Number of levels        : 47
Nested grid simulation? : F
 Buffer zone (N S E W ) :  3  3  3  3
```
I think the issue is that you are specifying a nested region but the nested-grid simulation flag is set to FALSE.  This may cause the regridding not to work properly.

If you turn off the nested-grid simulation then the values for lon & lat min & max have to be:
```console
Longitude min/max       : -180.0 180.0
Latitude  min/max       :   -90.0   90.0
```

We can put an error trap into `GeosCore/input_mod.F90` that will throw an error message if you try to configure a non-nested-grid simulation with less than the global grid extent.
