### ISSUE TITLE
[compile]undefined reference

### ISSUE THREAD

**Issue by Yuan-yuan-2021** [geoschem/geos-chem#1114]
### Ask a question about GEOS-Chem:

Hello,
I'm getting the following issue during compiling, which breaks the compilation:
ld: /lib/libpnetcdf.a(nonblocking.o): undefined reference to symbol 'MPI_File_write_all'
/impi/lib64/libmpi.so.12: error adding symbols: DSO missing from command line
My linux environment has obviously installed these libraries, so what is the reason for this?How do I solve this problem？
Thanks！

**Comment by yantosca** [comment]
@Yuan-yuan-2021, thanks for writing.  Could you add your log file with compilation output to this issue, and also attach the error message?  

It looks like your build cannot find the netCDF library file (libnetcdf.a).  Or that netCDF wasn't built with MPI support and the system expects it to be.

**Comment by Yuan-yuan-2021** [comment]
> @Yuan-yuan-2021, thanks for writing. Could you add your log file with compilation output to this issue, and also attach the error message?
> 
> It looks like your build cannot find the netCDF library file (libnetcdf.a). Or that netCDF wasn't built with MPI support and the system expects it to be.

Thanks for your reply @yantosca, after I reinstalled netcdf, the problem disappeared.
