### ISSUE TITLE
[BUG/ISSUE]HEMCO ERROR: Cannot find field with valid time stamp in restart file

### ISSUE THREAD

**Issue by chakri6023** [geoschem/geos-chem#1116]
![Screenshot (13)](https://user-images.githubusercontent.com/84584444/152563987-3ff29909-f411-4ec2-a4cc-1558ee01e3f3.png)
I am running Version 13.3.3 for mercury simulation. But got stuck in above error. can you please give your comments on this?

**Comment by yantosca** [comment]
Please see issues #940, #948, #971
