### ISSUE TITLE
[QUESTION] HISTORY diagnostics with non-spatial dimensions

### ISSUE THREAD

**Issue by cdholmes** [geoschem/geos-chem#1117]
Is it possible for a HISTORY diagnostic variables to have a non-spatial dimension? For example, could the netCDF output file contain a 3-D variable with dimensions (longitude, latitude, LU), where LU is variable indicating the land-use types found within the grid cell? 

The application is that I want to create diagnostics for all of the resistance terms in the dry deposition calculations. Each grid cell can contain several LU types (11 max). There are about 10 resistance terms. If the netCDF variables produced by HISTORY diagnostics are restricted to spatial dimensions, then it will take 110 netCDF variables to specify the dry deposition of /each/ dry deposited species. (There are about 160 dry deposited species). If LU could be a dimension in the netCDF file, then it would only take 10 variables per species, which would be much easier to analyze.

**Comment by lizziel** [comment]
Non-spatial dimensions in output fields is not a supported feature in GEOS-Chem yet. However, an easy work-around is possible if your other dimension is length 72 or less. You can define the diagnostic as having a level dimension and only fill the first N elements, where N is the true length of your other dimension. The rest would be zeros or some bad value that you define. It's a waste of memory so not something we'd want to include in the standard model, but it works.

**Comment by yantosca** [comment]
@cdholmes this has been on our to-do list but we haven't gotten there yet.  For 1-d outputs we recommend to use (or hack) Obspack.

**Comment by cdholmes** [comment]
Thanks. Hacking the level dimension should work for me for now.
