### ISSUE TITLE
[QUESTION] Gaseous Elemental Mercury data from the model output

### ISSUE THREAD

**Issue by chakri6023** [geoschem/geos-chem#1118]
### Ask a question about GEOS-Chem:
Dear All,
I am using GEOS-Chem 13.3.2 and unable to find Gaseous Elemental Mercury data from the model output. Please suggest me in this regards.

**Comment by yantosca** [comment]
@chakri6023, I believe Hg0 is gaseous elemental mercury.

**Comment by chakri6023** [comment]
I am unable to find variable to plot gaseous elemental mercury(Hg0) from the output of geos-chem. I have checked GEOSChem.MercuryChem.20100101_0000z.nc4 file.

**Comment by yantosca** [comment]
Look in the `SpeciesConc` collection.  Hg0 is saved as `SpeciesConc_Hg0` there.  Best.
