### ISSUE TITLE
[BUG/ISSUE] forrtl: severe (174): SIGSEGV, segmentation fault occurred

### ISSUE THREAD

**Issue by Yuan-yuan-2021** [geoschem/geos-chem#1119]
### What institution are you from?
Please tell us what institution you are from.
BNU
### Description of the problem
Describe your problem here.  Describe the steps to reproduce the problem here, if possible.
The experiment I chose was merra2_2x25_tropchem，I get an error when I run the experiment .
### Description of troubleshooting performed
Describe any troubleshooting that you have already performed here. Also include any leads or suspicions here.
```console
********************************************
* B e g i n   T i m e   S t e p p i n g !! *
********************************************

---> DATE: 2010/11/01  UTC: 00:00  X-HRS:      0.000000
 HEMCO already called for this timestep. Returning.
===============================================================================
TPCORE_FVDAS (based on GMI) Tracer Transport Module successfully initialized
===============================================================================
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
libifcoremt.so.5   00007F6B327F8F0C  for__signal_handl     Unknown  Unknown
libpthread-2.17.s  00007F6B32D756D0  Unknown               Unknown  Unknown
geos               000000000058DA65  transport_mod_mp_         356  transport_mod.F90
geos               000000000058D389  transport_mod_mp_         204  transport_mod.F90
geos               00000000004A2667  MAIN__                   1347  main.F90
geos               0000000000403CFE  Unknown               Unknown  Unknown
libc-2.17.so       00007F6B2FE8F445  __libc_start_main     Unknown  Unknown
geos               0000000000403C09  Unknown               Unknown  Unknown
```
### GEOS-Chem version
Enter your GEOS-Chem version here.
12.9.3
### Description of modifications
Describe your modifications here.

### Log files
- Build log (if applicable):
- Run logs (if applicable):
- Run script (if applicable):

### Software versions
- CMake version:
- Compilers (Intel or GNU, and version):
- NetCDF version: netCDF 4.7.4

**Comment by lizziel** [comment]
Hi @Yuan-yuan-2021,

Typically segmentation faults in transport are due to running out of memory. Try upping the amount of memory you are requesting for your job. If you still have problems please include more information in your support request. See our [Submitting support requests wiki page](http://wiki.seas.harvard.edu/geos-chem/index.php/Submitting_GEOS-Chem_support_requests) for guidance.

**Comment by yantosca** [comment]
@Yuan-yuan-2021, this looks like a STOP was encountered. Or you were running in a queue and the job ran beyond the time limit.

Also, we recommend not to use the tropchem simulation, but instead to use fullchem with 47 levels.  See issue #839.

**Comment by Yuan-yuan-2021** [comment]
Thanks for your reply @yantosca, after I added node, this problem no longer occurs. Then I have a new problem. I want to output the boundary  file, and it seems that I have trouble reading and writing. This is a reminder of the error file. 

    - Creating file for BoundaryConditions; reference = 20101101 001000
        with filename = OutputDir/GEOSChem.BoundaryConditions.20101101_0010z.nc4

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In Nccr_Wr, cannot create:  OutputDir/GEOSChem.BoundaryConditions.20101101_0010z.nc4

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Code stopped from DO_ERR_OUT (in module NcdfUtil/m_do_err_out.F90) 

This is an error that was encountered in one of the netCDF I/O modules,
which indicates an error in writing to or reading from a netCDF file!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In Ncwr_3d_R4 #2:  NetCDF: HDF error
     65536       173

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Code stopped from DO_ERR_OUT (in module NcdfUtil/m_do_err_out.F90) 

This is an error that was encountered in one of the netCDF I/O modules,
which indicates an error in writing to or reading from a netCDF file!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by yantosca** [comment]
Thanks for the feedback @Yuan-yuan-2021.  This error could mean a couple of things:

  1. You are over quota (i.e. ran out of disk space in your account)
  2.  The file `OutputDir/GEOSChem.BoundaryConditions.20101101_0010z.nc4` already exists and it is write-protected, so you can't overwrite it.

**Comment by yantosca** [comment]
It can also mean that the OutputDir folder does not exist in your run directory.

**Comment by yantosca** [comment]
Have you solved this problem @Yuan-yuan-2021?  If so, let us know and we can close out this issue.

**Comment by Yuan-yuan-2021** [comment]
> Have you solved this problem @Yuan-yuan-2021? If so, let us know and we can close out this issue.

Yes,ti's I/O problem,not the model. Thank you@yantosca.

**Comment by XR-peking** [comment]
So, how can we solve this problem? I met exactly the same one.
