### ISSUE TITLE
[QUESTION] GEOS-Chem doesn't read boundary conditions as HEMCO_Config.rc sets

### ISSUE THREAD

**Issue by Holton1** [geoschem/geos-chem#1121]
Hi, I am using GEOS-Chem v12.5.0 to do a nested simulation based on FlexGrid. The run doesn't crash but keeps reporting:

"GEOS-Chem ERROR: No boundary condition found for NO
 -> at Get_Boundary_Conditions (in GeosCore/hcoi_gc_main_mod.F)"

Using TotalView, I find that when the calling "Get_Boundary_Conditions" in GeosCore/hcoi_gc_main_mod.F90, the model cannot find the boundary condition variables such as "BC_NO" from the list. 

Seems like the boundary condition file, though defined in "HEMCO_Config.rc", is not imported, thus the boundary condition ( BC_xx variables) are not on the list.  

I follow the instruction on GEOS-Chem wiki about nested run, and inserted the boundary condition configuration to HEMCO_Config.rc. The nested domain is around Alaska.   

Attached are the HEMCO_Config.rc and input.geos I used:
[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/8020069/HEMCO_Config.rc.txt)
[input.geos.txt](https://github.com/geoschem/geos-chem/files/8020070/input.geos.txt)

**Comment by yantosca** [comment]
Thanks for writing @Holton1.  Could you also attach the `HEMCO.log` file to this issue?

**Comment by Holton1** [comment]
Hi Bob, thanks for replying. Sorry, there's something wrong with my server, it took some time to run the model again. Here attached are the HEMCO.log and model standard output.

[HEMCO.log.txt](https://github.com/geoschem/geos-chem/files/8039740/HEMCO.log.txt)
[log.txt](https://github.com/geoschem/geos-chem/files/8039741/log.txt)

**Comment by yantosca** [comment]
@Holton1, thanks for replying.  The run should die if it cannot find a field in the boundary conditions file.  I believe this has been fixed in more recent versions than 12.5.0.

I'm wondering if there is a name mismatch between the entry in HEMCO_Config.rc and the species names in the boundary condition netCDF files.  In HEMCO_Config.rc we have:

```
#==============================================================================
# --- GEOS-Chem boundary condition file ---
#==============================================================================
(((GC_BCs
* BC_ $ROOT/BC/2016/merra2_2x25_tropchem/OutputDir/GEOSChem.BoundaryConditions.$YYYY$MM$DD_$HH$MNz.nc4  SpeciesBC_?ADV?  1980-2019/1-12/1-31/0-23 RFY xyz 1 * - 1 1
)))GC_BCs
```
but if the species in the GEOSChem.BoundaryConditions* files do not begin with `SpeciesRst_` then that is a problem.

At this point we would recommend upgrading to a newer model version if possible, as 12.5.0 is by now about 2 years old.

**Comment by Holton1** [comment]
Hi Bob, thanks for the detailed response! I think that the species in GEOSChem.BoundaryConditions* files begin with `SpeciesBC_` (`SpeciesRst_` seems is the header of variables in a restart file). But seems like the boundary condition variables are not imported during loading the HEMCO variables. I am trying to switch to GC12.7.0 to see if this issue is fixed.

**Comment by yantosca** [comment]
We would recommend that you update to a more recent version, say 13.4.0 (once it is released).

**Comment by yantosca** [comment]
I will close out this issue for now.  Please let us know if you continue to have problems.
