### ISSUE TITLE
AMI for newer versions of GEOS-Chem

### ISSUE THREAD

**Issue by mosaichaoyan** [geoschem/geos-chem#1125]
### Ask a question about GEOS-Chem:
Hi There,

I am trying to spin up an AWS EC2 for some trial simulations using GEOS-Chem. The most recent AMI I can find is for 13.2.1. 
The other AMIs I tried from the Wiki page are not there.
Should I just go with 13.2.1 or the AMIs for newer version is different from what the Wiki page suggests.

Thank you very much!

<img width="1069" alt="Screen Shot 2022-02-11 at 3 10 59 PM" src="https://user-images.githubusercontent.com/62110889/153663522-692303f0-ebe4-415c-9614-35f4ca623e63.png">

**Comment by laestrada** [comment]
It seems that we didn't set the AMI for 13.3.4 to public -- I have just updated the permissions and it should be available (ami-069af8bd933eefa4d).

Additionally, we recently updated our policy on which AMIs we host. To reduce our storage costs we are now only hosting AMIs for: 
- the current major update (eg. versions 13.0 and onward). 
- the latest patch for each minor update (eg. 13.3.4, 13.2.1, 13.1.2, and 13.0.1 are kept) 

However, if you ever need a specific version of GEOS-Chem, that we do not have an ami published for, you can always checkout the necessary version with git from any ami version. The primary reason we maintain different version preloaded is for ease of access by new users.

Thanks for posting this!

**Comment by mosaichaoyan** [comment]
Got it! Thanks a lot!
