### ISSUE TITLE
[QUESTION] about tagged CO2 simulation

### ISSUE THREAD

**Issue by kimm1na** [geoschem/geos-chem#1126]
### Ask a question about GEOS-Chem:

Hello,
I am trying a tagged CO2 run using GC 13.0.1. 

Tagged CO2 description is not on the wiki yet, so I'm having trouble. 
I apologize in advance for the many questions.

1) I wonder if it is enough to just add this to the species name list in input.geos when doing tag CO2 simulation.

```
**------------------------+------------------------------------------------------
%%% ADVECTED SPECIES MENU %%%:
Species name            : CO2
Species name            : CO2ff
Species name            : CO2se
Species name            : CO2av
Species name            : CO2oc
Species name            : CO2corr
Species name            : CO2bal
------------------------+------------------------------------------------------**
```
2) I wonder how to set the "Tagged CO2 runs" part option in input.geos.

```
**Tagged CO2 runs         :---
  Save Fossil in Bckgrnd: F
  Tag Bio/Ocean CO2 reg : F
  Tag Land FF CO2 reg   : F
  Tag Global Ship CO2   : F
  Tag Global Plane CO2  : F**
```
3) There are CO2corr and CO2bal,... etc in the HEMCO_Config.rc file. (for example, CO2bal as below)

```
**(((BBIO_DIURNAL
0 BBIOCO2_DIURNAL    $ROOT/CO2/v2014-09/BBIO/BBIO_diurnal_CO2.nc CO2 1985/1-12/1-31/0-23 C xy kg/m2/s CO2    - 3 1
0 BBIOCO2BAL_DIURNAL -                                           -   -                   - -  -       CO2bal - 3 1
)))BBIO_DIURNAL**
```

However, these 4 species are missing : CO2bb, CO2bf, CO2ch, and CO2nte, so I wonder if I can add them to the species name (in input.geos).

4) I wonder if it is necessary to configure other settings for tagged CO2 run.

Thank you very much.

Sincerely, Mina Kim

**Comment by monszel** [comment]
Hi @kimm1na,
as far as I remember, when I was running CO2 tagged simulations, I just listed species of interest tin the **ADVECTED SPECIES MENU** and changed the flag to **true** in the **Tagged CO2 runs** section.

Regards
Monika

**Comment by kimm1na** [comment]
thank you for telling me.

When I add only the species name, the model runs well, but when I set the tag option to True, the following error appears.

Have you had a similar experience?

thank you.

![image](https://user-images.githubusercontent.com/89123880/155447932-5daaf476-2048-4923-b059-8657377512ae.png)

**Comment by monszel** [comment]
Hi,
I did have that problem. At that point I thought its problem on my side and my setup. I copied the Regions_land.dat and Regions_ocean.dat from 12.9 version of the model into the run directory and it worked. But I did not have time to check this issue and now it seems it is more common problem. Maybe @yantosca will know better what's wrong with the files.
Regards,
Monika

**Comment by yantosca** [comment]
I will close out this issue.  Thanks much and reach out if you are still having problems.

**Comment by rippleofheart** [comment]
> Hi, @kimm1na, I did have that problem. At that point I thought it is problem on my side and with my setup. I copied the Regions_land.dat and Regions_ocean.dat from 12.9 version of the model into the run directory and it worked. But I did not have time to check this issue and now it seems it is more common problem. Maybe @yantosca will know better what's wrong with the files. Regards, Monika

Hi, @monszel . I am running the GEOS-Chem v14.4, I encountered a problem about Regions_land.dat. I typed 'true' in tag_bio_and_ocean_CO2, but when I used the command './gcclassic' the error came out:'READ_REGIONS: Reading Regions_land.dat
        ?/%??5???@??/%?mm????@??H2O2                                                            
At line 396 of file /data/gpfs/projects/punim0711/YuhaoMo/test6_CO2_simple_0926/CodeDir/src/GEOS-Chem/GeosCore/co2_mod.F90
Fortran runtime error: Bad value during integer read
'
I think it is because it didn't generate the regions_land.dat and Regions_ocean.dat before running the code './gcclassic'. I don't know how to solve this problem and where I can find the datasets. I saw you can solve the problem by copying the right Regions_land.dat from other version. Could you help me generate the datasets or send me a copy of Regions_land.dat and Regions_ocean.dat to me? Thank you.

Best Regards,
Morry
