### ISSUE TITLE
[BUG/ISSUE] Unused line of code in KPP rate law function

### ISSUE THREAD

**Issue by ktravis213** [geoschem/geos-chem#1132]
### What institution are you from?
NASA LaRC
### Description of the problem
I think the following on line 570 in fullchem_RateLawFuncs.F90 is not needed, it doesn't appear to be used or part of the JPL equation:
    r0     = a0 * ( 1.0_dp + 0.6_dp * 9.871E7_dp * PRESS )

**Comment by yantosca** [comment]
Thanks @ktravis213.  I believe that you are right.  I can remove that line, as it'll avoid useless computations.  Thanks for finding this!

**Comment by msulprizio** [comment]
This fix has now been implemented in 3e8166d and will be included in GEOS-Chem 13.4.0.
