### ISSUE TITLE
[BUG/ISSUE] GEOS-Chem 12.7.2 crashes during runtime:   HEMCO ERROR: Negative values found! 

### ISSUE THREAD

**Issue by Holton1** [geoschem/geos-chem#1133]
### What institution are you from?
University of Alaska Fairbanks

### Description of the problem
I am using GEOS-Chem 12.7.2 to do a nested grid simulation over Alaska domain for 2018 summer. The model runs well for 2018 May, June and several early days of July, but crashes at July 6, when HEMCO is running. The error message is:

```console
4128 HEMCO (VOLCANO): Opening /import/GREENING/shared/data/ExtData/HEMCO/VOLCANO/v2019-08/2018/07/so2_volcanic_emissions_Carns.20180706.rc
4129 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
4130 HEMCO ERROR: Negative values found!
```

### Description of troubleshooting performed
I checked the data. The data is properly downloaded. Since using the same model configuration, it can run properly for May and June, I guess that the issue can be due to errors during calculations with volcanic emission. 

### GEOS-Chem version
GEOS-Chem 12.7.2

### Description of modifications
In the HEMCO/Extensions/hcox_megan_mod.F90, I modify the code to make all the BVOC AEF being calculated online using EF from Guenther et al 2012 paper, instead of reading offline data.

### Log files
[HEMCO.log.txt](https://github.com/geoschem/geos-chem/files/8103445/HEMCO.log.txt)
[log.txt](https://github.com/geoschem/geos-chem/files/8103446/log.txt)

### Software versions
- CMake version:  /
- Compilers (Intel or GNU, and version):   ifort (IFORT) 16.0.3 20160415
- NetCDF version:   
        module load data/netCDF/4.4.1.1-pic-intel-2016b
        module load data/netCDF-Fortran/4.4.4-pic-intel-2016b

**Comment by yantosca** [comment]
@Holton1, have you resolved your issue?  Just checking in.

**Comment by Holton1** [comment]
Hi Bob, thanks for following up this issue. I have resolved this issue. The error happens near the bound of my nested domain, so I slightly cut my nest domain and the error doesn't appear.
