### ISSUE TITLE
[BUG/ISSUE] error about Compiling geos-chem 

### ISSUE THREAD

**Issue by jie0314ouc** [geoschem/geos-chem#1135]
After configuring and running GEOS Chem, I encountered some error messages when compiling with make -j4 build command, but I don't know where the problem is and how to solve it. I hope you can help me!

```console
The error information is as follows:
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
make[1]: Entering directory `/home/zhangj/GC/rundirs/merra2_2x25_Hg'
rm -f *.log
rm -f slurm-*
make[1]: Leaving directory `/home/zhangj/GC/rundirs/merra2_2x25_Hg'
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
make[1]: Entering directory `/home/zhangj/GC/rundirs/merra2_2x25_Hg'
rm -f geos
rm -f hemco_standalone.x
rm -f compile.log
rm -f lastbuild
make[1]: Leaving directory `/home/zhangj/GC/rundirs/merra2_2x25_Hg'
make[1]: Entering directory `/home/zhangj/GC/Code.12.9.3'
make[2]: Entering directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
make[3]: Entering directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
make[4]: Entering directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
make[5]: Entering directory `/home/zhangj/GC/Code.12.9.3/NcdfUtil'
ar crs libNcUtils.a m_do_err_out.o m_netcdf_io_checks.o m_netcdf_io_close.o m_ne                                                                                                                                   tcdf_io_create.o m_netcdf_io_define.o m_netcdf_io_get_dimlen.o m_netcdf_io_handl                                                                                                                                   e_err.o m_netcdf_io_open.o m_netcdf_io_read.o m_netcdf_io_readattr.o m_netcdf_io                                                                                                                                   _write.o ncdf_mod.o
mv libNcUtils.a ../lib
make[5]: Leaving directory `/home/zhangj/GC/Code.12.9.3/NcdfUtil'
make[4]: Leaving directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
make[4]: Entering directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
make[5]: Entering directory `/home/zhangj/GC/Code.12.9.3/KPP'
make[6]: Entering directory `/home/zhangj/GC/Code.12.9.3/KPP/Standard'
make[6]: Nothing to be done for `firstpass'.
make[6]: Leaving directory `/home/zhangj/GC/Code.12.9.3/KPP/Standard'
make[5]: Leaving directory `/home/zhangj/GC/Code.12.9.3/KPP'
make[4]: Leaving directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
make[4]: Entering directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
make[5]: Entering directory `/home/zhangj/GC/Code.12.9.3/Headers'
gfortran -cpp -w -std=legacy -fautomatic -fno-align-commons -fconvert=big-endian                                                                                                                                    -fno-range-check -O3 -funroll-loops -fopenmp -mcmodel=medium -fbacktrace -g -DM                                                                                                                                   ODEL_CLASSIC -DLINUX_GFORTRAN -DBPCH_DIAG -DUSE_REAL8 -J../mod -I/opt/netcdf/4.1                                                                                                                                   .3/pgi/19.4/include -c -ffree-form -ffree-line-length-none dictionary_m.F90
gfortran -cpp -w -std=legacy -fautomatic -fno-align-commons -fconvert=big-endian                                                                                                                                    -fno-range-check -O3 -funroll-loops -fopenmp -mcmodel=medium -fbacktrace -g -DM                                                                                                                                   ODEL_CLASSIC -DLINUX_GFORTRAN -DBPCH_DIAG -DUSE_REAL8 -J../mod -I/opt/netcdf/4.1                                                                                                                                   .3/pgi/19.4/include -c -ffree-form -ffree-line-length-none CMN_DIAG_mod.F90
dictionary_m.F90:26.41:

     character(len=:), allocatable :: key
                                         1
Error: Deferred-length character component 'key' at (1) is not yet supported
dictionary_m.F90:26.41:

     character(len=:), allocatable :: key
                                         1
Error: Deferred-length character component 'key' at (1) is not yet supported
dictionary_m.F90:26.41:

     character(len=:), allocatable :: key
                                         1
Error: Deferred-length character component 'key' at (1) is not yet supported
dictionary_m.F90:138.16:

       allocate(this%buckets(h)%entries, source=tmp_bucket%entries)
                1
Error: Array specification required in ALLOCATE statement at (1)
make[5]: *** [dictionary_m.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[5]: Leaving directory `/home/zhangj/GC/Code.12.9.3/Headers'
make[4]: *** [libheaders] Error 2
make[4]: Leaving directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
make[3]: *** [lib] Error 2
make[3]: Leaving directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/zhangj/GC/Code.12.9.3'
cp -f ./CodeDir/bin/geos geos
cp: omitting directory ‘./CodeDir/bin/geos’
make: *** [build] Error 1
```

**Comment by yantosca** [comment]
Thanks for writing @jie0314ouc.  Which compiler version are you using?  You can find out by typing either
```console
gfortran --version
```
or 
```console
ifort  --version
```
depending on which compiler you are using.  It might be that the version of the compiler you have is too old to compile this code (which is Headers/dictionary_m.F90).

**Comment by jie0314ouc** [comment]
Today, I reinstalled the gcc-9.3.0 compiler and recompiled goes Chem, but there are still error information, as follows:
&nbsp;

fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
 
Use '--' to separate paths from revisions, like this:
 
'git <command&gt; [<revision&gt;...] -- [<file&gt;...]'
 
fatal: bad default revision 'HEAD'
 
fatal: bad default revision 'HEAD'
 
fatal: bad default revision 'HEAD'
 
fatal: bad default revision 'HEAD'
 
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
 
Use '--' to separate paths from revisions, like this:
 
'git <command&gt; [<revision&gt;...] -- [<file&gt;...]'
 
fatal: bad default revision 'HEAD'
 
fatal: bad default revision 'HEAD'
 
fatal: bad default revision 'HEAD'
 
fatal: bad default revision 'HEAD'
 
make[1]: Entering directory `/home/zhangj/GC/rundirs/merra2_2x25_Hg'
 
rm -f *.log
 
rm -f slurm-*
 
make[1]: Leaving directory `/home/zhangj/GC/rundirs/merra2_2x25_Hg'
 
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
 
Use '--' to separate paths from revisions, like this:
 
'git <command&gt; [<revision&gt;...] -- [<file&gt;...]'
 
fatal: bad default revision 'HEAD'
 
fatal: bad default revision 'HEAD'
 
fatal: bad default revision 'HEAD'
 
fatal: bad default revision 'HEAD'
 
make[1]: Entering directory `/home/zhangj/GC/rundirs/merra2_2x25_Hg'
 
rm -f geos
 
rm -f hemco_standalone.x
 
rm -f compile.log
 
rm -f lastbuild
 
make[1]: Leaving directory `/home/zhangj/GC/rundirs/merra2_2x25_Hg'
 
make[1]: Entering directory `/home/zhangj/GC/Code.12.9.3'
 
make[2]: Entering directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
 
make[3]: Entering directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
 
make[4]: Entering directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
 
make[5]: Entering directory `/home/zhangj/GC/Code.12.9.3/NcdfUtil'
 
ar crs libNcUtils.a m_do_err_out.o m_netcdf_io_checks.o m_netcdf_io_close.o m_netcdf_io_create.o m_netcdf_io_define.o m_netcdf_io_get_dimlen.o m_netcdf_io_handle_err.o m_netcdf_io_open.o m_netcdf_io_read.o m_netcdf_io_readattr.o m_netcdf_io_write.o ncdf_mod.o
 
mv libNcUtils.a ../lib
 
make[5]: Leaving directory `/home/zhangj/GC/Code.12.9.3/NcdfUtil'
 
make[4]: Leaving directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
 
make[4]: Entering directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
 
make[5]: Entering directory `/home/zhangj/GC/Code.12.9.3/KPP'
 
make[6]: Entering directory `/home/zhangj/GC/Code.12.9.3/KPP/Standard'
 
make[6]: Nothing to be done for `firstpass'.
 
make[6]: Leaving directory `/home/zhangj/GC/Code.12.9.3/KPP/Standard'
 
make[5]: Leaving directory `/home/zhangj/GC/Code.12.9.3/KPP'
 
make[4]: Leaving directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
 
make[4]: Entering directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
 
make[5]: Entering directory `/home/zhangj/GC/Code.12.9.3/Headers'
 
ar crs libHeaders.a charpak_mod.o taggeddiaglist_mod.o state_chm_mod.o registry_params_mod.o state_met_mod.o registry_mod.o CMN_DIAG_mod.o roundoff_mod.o CMN_O3_mod.o precision_mod.o state_diag_mod.o qfyaml_mod.o species_mod.o inquireMod.o errcode_mod.o state_grid_mod.o diaglist_mod.o species_database_mod.o CMN_FJX_MOD.o CMN_SIZE_mod.o physconstants.o input_opt_mod.o dictionary_m.o
 
mv libHeaders.a ../lib
 
make[5]: Leaving directory `/home/zhangj/GC/Code.12.9.3/Headers'
 
make[4]: Leaving directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
 
make[4]: Entering directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
 
make[5]: Entering directory `/home/zhangj/GC/Code.12.9.3/GeosUtil'
 
ar crs libGeosUtil.a time_mod.o regrid_a2a_mod.o bpch2_mod.o unitconv_mod.o file_mod.o error_mod.o gc_grid_mod.o ifort_errmsg.o julday_mod.o timers_mod.o henry_mod.o pressure_mod.o transfer_mod.o grid_registry_mod.o
 
mv libGeosUtil.a ../lib
 
make[5]: Leaving directory `/home/zhangj/GC/Code.12.9.3/GeosUtil'
 
make[4]: Leaving directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
 
make[4]: Entering directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
 
make[5]: Entering directory `/home/zhangj/GC/Code.12.9.3/KPP'
 
make[6]: Entering directory `/home/zhangj/GC/Code.12.9.3/KPP/Standard'
 
ar crs libKpp.a gckpp_Global.o gckpp_HetRates.o gckpp_Parameters.o gckpp_Model.o gckpp_JacobianSP.o gckpp_Rates.o gckpp_LinearAlgebra.o gckpp_Precision.o gckpp_Monitor.o gckpp_Util.o gckpp_Integrator.o gckpp_Jacobian.o gckpp_Initialize.o gckpp_Function.o
 
mv libKpp.a ../../lib
 
make[6]: Leaving directory `/home/zhangj/GC/Code.12.9.3/KPP/Standard'
 
make[5]: Leaving directory `/home/zhangj/GC/Code.12.9.3/KPP'
 
make[4]: Leaving directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
 
make[4]: Entering directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
 
make[5]: Entering directory `/home/zhangj/GC/Code.12.9.3/History'
 
ar crs libHistory.a history_netcdf_mod.o metahistcontainer_mod.o histitem_mod.o history_util_mod.o history_mod.o metahistitem_mod.o histcontainer_mod.o
 
mv libHistory.a ../lib
 
make[5]: Leaving directory `/home/zhangj/GC/Code.12.9.3/History'
 
make[4]: Leaving directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
 
make[4]: Entering directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
 
make[5]: Entering directory `/home/zhangj/GC/Code.12.9.3/ObsPack'
 
ar crs libObsPack.a obspack_mod.o
 
mv libObsPack.a ../lib
 
make[5]: Leaving directory `/home/zhangj/GC/Code.12.9.3/ObsPack'
 
make[4]: Leaving directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
 
make[4]: Entering directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
 
make[5]: Entering directory `/home/zhangj/GC/Code.12.9.3/HEMCO'
 
make[6]: Entering directory `/home/zhangj/GC/Code.12.9.3/HEMCO'
 
make[7]: Entering directory `/home/zhangj/GC/Code.12.9.3/HEMCO/src/Core'
 
ar crs libHCO.a hco_interp_mod.o hco_vertgrid_mod.o hcoio_read_esmf_mod.o hco_scale_mod.o hcoio_write_std_mod.o hco_filedata_mod.o hcoio_dataread_mod.o hco_chartools_mod.o hco_restart_mod.o hco_diagn_mod.o hco_logfile_mod.o hcoio_write_esmf_mod.o hco_extlist_mod.o hco_geotools_mod.o messy_ncregrid_base.o hco_emislist_mod.o hco_calc_mod.o interpreter.o hco_datacont_mod.o hco_driver_mod.o hco_unit_mod.o hco_types_mod.o hco_readlist_mod.o hco_arr_mod.o messy_ncregrid_mpi.o hco_timeshift_mod.o hco_tidx_mod.o hcoio_read_std_mod.o hco_fluxarr_mod.o hco_config_mod.o hco_error_mod.o hco_clock_mod.o hcoio_diagn_mod.o hco_state_mod.o hcoio_messy_mod.o
 
mv libHCO.a ../../../lib
 
make[7]: Leaving directory `/home/zhangj/GC/Code.12.9.3/HEMCO/src/Core'
 
make[6]: Leaving directory `/home/zhangj/GC/Code.12.9.3/HEMCO'
 
make[6]: Entering directory `/home/zhangj/GC/Code.12.9.3/HEMCO'
 
make[7]: Entering directory `/home/zhangj/GC/Code.12.9.3/HEMCO/src/Extensions'
 
ar crs libHCOX.a hcox_dustdead_mod.o hcox_tomas_dustdead_mod.o hcox_gc_POPs_mod.o drydep_toolbox_mod.o hcox_seaflux_mod.o hcox_ch4wetland_mod.o hcox_tomas_jeagle_mod.o hcox_gfed_mod.o hcox_finn_mod.o hcox_custom_mod.o hcox_gc_RnPbBe_mod.o ocean_toolbox_mod.o hcox_dustginoux_mod.o hcox_paranox_mod.o hcox_seasalt_mod.o hcox_state_mod.o hcox_iodine_mod.o hcox_driver_mod.o hcox_tools_mod.o hcox_lightnox_mod.o hcox_soilnox_mod.o hcox_volcano_mod.o hcox_megan_mod.o
 
mv libHCOX.a ../../../lib
 
make[7]: Leaving directory `/home/zhangj/GC/Code.12.9.3/HEMCO/src/Extensions'
 
make[6]: Leaving directory `/home/zhangj/GC/Code.12.9.3/HEMCO'
 
make[6]: Entering directory `/home/zhangj/GC/Code.12.9.3/HEMCO'
 
make[7]: Entering directory `/home/zhangj/GC/Code.12.9.3/HEMCO/src/Interfaces'
 
ar crs libHCOI.a hcoi_esmf_mod.o hemco_standalone.o hcoi_standalone_mod.o
 
mv libHCOI.a ../../../lib
 
make[7]: Leaving directory `/home/zhangj/GC/Code.12.9.3/HEMCO/src/Interfaces'
 
make[6]: Leaving directory `/home/zhangj/GC/Code.12.9.3/HEMCO'
 
make[6]: Entering directory `/home/zhangj/GC/Code.12.9.3/HEMCO'
 
make[7]: Entering directory `/home/zhangj/GC/Code.12.9.3/HEMCO/src/Interfaces'
 
make[8]: Entering directory `/home/zhangj/GC/Code.12.9.3/HEMCO/src/Interfaces'
 
ar crs libHCOI.a hcoi_esmf_mod.o hemco_standalone.o hcoi_standalone_mod.o
 
mv libHCOI.a ../../../lib
 
make[8]: Leaving directory `/home/zhangj/GC/Code.12.9.3/HEMCO/src/Interfaces'
 
make[8]: Entering directory `/home/zhangj/GC/Code.12.9.3/HEMCO/src/Interfaces'
 
gfortran -cpp -w -std=legacy -fautomatic -fno-align-commons -fconvert=big-endian -fno-range-check -O3 -funroll-loops -fopenmp -mcmodel=medium -fbacktrace -g -DMODEL_CLASSIC -DLINUX_GFORTRAN -DBPCH_DIAG -DUSE_REAL8 hcoi_esmf_mod.o hemco_standalone.o hcoi_standalone_mod.o -L../../../lib -lHCOI -lHCOX -lHCO -lGeosUtil -lHeaders -lNcUtils -L/opt/netcdf/4.1.3/pgi/19.4/lib -lnetcdff -lnetcdf -o hemco_standalone.x
 
cp -f hemco_standalone.x ../../../bin
 
make[8]: Leaving directory `/home/zhangj/GC/Code.12.9.3/HEMCO/src/Interfaces'
 
make[7]: Leaving directory `/home/zhangj/GC/Code.12.9.3/HEMCO/src/Interfaces'
 
make[6]: Leaving directory `/home/zhangj/GC/Code.12.9.3/HEMCO'
 
make[5]: Leaving directory `/home/zhangj/GC/Code.12.9.3/HEMCO'
 
make[4]: Leaving directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
 
make[4]: Entering directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
 
make[5]: Entering directory `/home/zhangj/GC/Code.12.9.3/ISORROPIA'
 
ar crs libIsorropia.a isorropiaII_main_mod.o
 
mv libIsorropia.a ../lib
 
make[5]: Leaving directory `/home/zhangj/GC/Code.12.9.3/ISORROPIA'
 
make[4]: Leaving directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
 
make[4]: Entering directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
 
make[4]: Nothing to be done for `librad'.
 
make[4]: Leaving directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
 
make[4]: Entering directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
 
make[4]: Nothing to be done for `libapm'.
 
make[4]: Leaving directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
 
make[4]: Entering directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
 
make[4]: Nothing to be done for `libcore'.
 
make[4]: Leaving directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
 
make[3]: Leaving directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
 
make[3]: Entering directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
 
gfortran -cpp -w -std=legacy -fautomatic -fno-align-commons -fconvert=big-endian -fno-range-check -O3 -funroll-loops -fopenmp -mcmodel=medium -fbacktrace -g -DMODEL_CLASSIC -DLINUX_GFORTRAN -DBPCH_DIAG -DUSE_REAL8 cleanup.o flexgrid_read_mod.o diag_oh_mod.o pops_mod.o strat_chem_mod.o main.o get_met_mod.o tomas_mod.o modis_lai_mod.o depo_mercury_mod.o oasave.o diag53_mod.o hcoi_gc_main_mod.o tpcore_window_mod.o tccon_ch4_mod.o input_mod.o co2_mod.o gc_environment_mod.o aero_drydep.o apm_driv_mod.o drydep_mod.o initialize.o land_mercury_mod.o pjc_pfix_mod.o mapping_mod.o ucx_mod.o wetscav_mod.o YuIMN_Code.o ocean_mercury_mod.o global_ch4_mod.o convection_mod.o tagged_o3_mod.o pjc_pfix_window_mod.o ndxx_setup.o pbl_mix_mod.o seasalt_mod.o toms_mod.o vdiff_pre_mod.o RnPbBe_mod.o gosat_ch4_mod.o transport_mod.o exchange_mod.o uvalbedo_mod.o sfcvmr_mod.o cldice_HBrHOBr_rxn.o tpcore_fvdas_mod.o diagnostics_mod.o dust_mod.o planeflight_mod.o olson_landmap_mod.o diag_mod.o emissions_mod.o chemistry_mod.o diag51_mod.o flexchem_mod.o hcoi_gc_diagn_mod.o diag03_mod.o rpmares_mod.o linoz_mod.o diag1.o diag3.o aerosol_mod.o set_global_ch4_mod.o diag51b_mod.o vdiff_mod.o set_prof_o3.o global_br_mod.o isorropiaII_mod.o hco_interface_mod.o carbon_mod.o tagged_co_mod.o sulfate_mod.o rrtmg_rad_transfer_mod.o gamap_mod.o fast_jx_mod.o mixing_mod.o mercury_mod.o calc_met_mod.o get_ndep_mod.o -L../lib -lIsorropia -lObsPack -lHistory -lHCOI -lHCOX -lHCO -lGeosUtil -lKpp -lHeaders -lNcUtils -L/opt/netcdf/4.1.3/pgi/19.4/lib -lnetcdff -lnetcdf -o geos
 
cp -f geos ../bin
 
cp: cannot overwrite directory ‘../bin/geos’ with non-directory
 
make[3]: *** [exe] Error 1
 
make[3]: Leaving directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
 
make[2]: *** [all] Error 2
 
make[2]: Leaving directory `/home/zhangj/GC/Code.12.9.3/GeosCore'
 
make[1]: *** [all] Error 2
 
make[1]: Leaving directory `/home/zhangj/GC/Code.12.9.3'
 
cp -f ./CodeDir/bin/geos geos
 
cp: omitting directory ‘./CodeDir/bin/geos’
 
make: *** [build] Error 1





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "geoschem/geos-chem"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月22日(星期二) 晚上10:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [geoschem/geos-chem] error about Compiling geos-chem  (Issue #1135)





 
Also it would be helpful if you could post the output from the compilation command that you used, as well as the version of GEOS-Chem and the version of the compilers you have.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jie0314ouc** [comment]
After I reinstall the compiler, netcdf-c and NetCDF FORTRAN,&nbsp; I executed "make - j4 build" in the generated running directory , there is no previous error information. See attachment-1&nbsp;for the command prompt after execution; See attachment-2 for the content displayed after executing ll - RT in the same level folder. I don't see “geos.mp" generation, I don't know if I compile correctly at present.​ Besides,&nbsp;my environment configuration can be&nbsp;seen in the&nbsp; attachment-3​.​
Furthermore, ​I dont know how to check and solve&nbsp;the question about&nbsp;​branch (dire​ctory is in detached HEAD state).
​



​

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "geoschem/geos-chem"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月23日(星期三) 凌晨1:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [geoschem/geos-chem] [BUG/ISSUE] error about Compiling geos-chem  (Issue #1135)





 
@jie0314ouc, is your code checked out on a branch?  It looks like your code dire​ctory is in detached HEAD state.
 
Also, it looks like you are using the older GNU Make method of compiling GEOS-Chem.  We would recommend using CMake as it is more user-friendly.   See this manual page:
  
http://wiki.geos-chem.org/Compiling_with_CMake
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
