### ISSUE TITLE
[BUG/ISSUE] Error reading timezones_voronoi_1x1.nc

### ISSUE THREAD

**Issue by jie0314ouc** [geoschem/geos-chem#1137]
### What institution are you from?
I am a graduate student in the school of environment, Ocean University of China.

### Description of the problem
After ./gcclassic , there was a error 
In Ncop_Rd, cannot open:  /home/zhangj/Geos-Chem/data/ExtData/HEMCO/TIMEZONES/v2015-02/timezones_voronoi_1x1.nc

Code stopped from DO_ERR_OUT (in module NcdfUtil/m_do_err_out.F90)
This is an error that was encountered in one of the netCDF I/O modules,
which indicates an error in writing to or reading from a netCDF file!

### Description of troubleshooting performed
At first, I suspected that it was a file permission problem, so I gave the highest permission to the file, but there were still the same errors

### GEOS-Chem version
Enter your GEOS-Chem version here.

### Description of modifications
Describe your modifications here.

### Log files
```console
===============================================================================
READ_DRYDEP_INPUTS: Opening /home/zhangj/Geos-Chem/data/ExtData/CHEM_INPUTS/Olson_Land_Map_201203/Olson_2001_Drydep_Inputs.nc
%% Successfully read DRYCOEFF [1]
%% Successfully read IOLSON [1]
%% Successfully read IDEP [1]
%% Successfully read IWATER [1]
%% Successfully read IZO [Default roughness heights for each Olson land type]
%% Successfully read IDRYDEP [1]
%% Successfully read IRI [s m-1]
%% Successfully read IRLU [s m-1]
%% Successfully read IRAC [s m-1]
%% Successfully read IRGSS [s m-1]
%% Successfully read IRGSO [s m-1]
%% Successfully read IRCLS [s m-1]
%% Successfully read IRCLO [s m-1]
%% Successfully read IVSMAX [1e-2 cm s-1]
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

INIT_DRYDEP: List of dry deposition species:

  #   Name      Species DEPVEL Henry's    React.   Molec.   Aerosol?
                Number Index  Law Const  Factor   Weight   (T or F)
----------------------------------------------------------------------
  1   Hg0          1     1     1.1E-01    0.000    0.201     F
  2   Hg2          2     2     1.0E+14    0.000    0.201     F
  3   HgP          3     3     0.0E+00    0.000    0.201     T

INIT_WETSCAV: List of soluble species:

  #             Name  Species Mol Wt  Henry K0  Henry CR  Henry pKa
                        ID    g/mol    M/atm      K         1
----------------------------------------------------------------------
  1              Hg2     2    200.6  1.40E+06  8.40E+03     -
  2              HgP     3    200.6     -         -         -

Registered variables contained within grid_registry_mod.F90:
===============================================================================
 GRID_LONBND                    | Longitude bounds (CF | bx    | degrees_east
 GRID_LONE                      | Longitude edges      | x     | degrees_east
 GRID_LON                       | Longitude            | x     | degrees_east
 GRID_LATBND                    | Latitude bounds (CF- | by    | degrees_north
 GRID_LATE                      | Latitude edges       | y     | degrees_north
 GRID_LAT                       | Latitude             | y     | degrees_north
 GRID_ILEV                      | hybrid level at inte | z     | level
 GRID_HYBI                      | hybrid B coefficient | z     | 1
 GRID_HYAI                      | hybrid A coefficient | z     | hPa
 GRID_LEV                       | hybrid level at midp | z     | level
 GRID_HYBM                      | hybrid B coefficient | z     | 1
 GRID_HYAM                      | hybrid A coefficient | z     | hPa
 GRID_TIME                      | Time                 | t     | minutes since YYYY-MM-DD hh:mm:ss
 GRID_P0                        | reference pressure   | -     | hPa
 GRID_AREA                      | Surface area         | xy    | m2

HISTORY (INIT): Opening ./HISTORY.rc

===============================================================================
DEFINED DIAGNOSTIC COLLECTIONS:
===============================================================================
 Collection        Restart
   -> FileName     ./GEOSChem.Restart.%y4%m2%d2_%h2%n2z.nc4
   -> Format       not found
   -> Frequency    End
   -> Duration     End
   -> Mode         instantaneous
 Collection        SpeciesConc
   -> FileName     OutputDir/GEOSChem.SpeciesConc.%y4%m2%d2_%h2%n2z.nc4
   -> Format       not found
   -> Frequency    00000100000000
   -> Duration     00000100000000
   -> Mode         time-averaged
===============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%               HEMCO: Harmonized Emissions Component                 %%%%%
%%%%%               You are using HEMCO version 3.0.0                     %%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Reading settings & switches of HEMCO configuration file: HEMCO_Config.rc

 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 Switches read from HEMCO_Config.rc:
   EMISSIONS :  T
   LightNOx  :  F
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Reading fields of HEMCO configuration file: HEMCO_Config.rc
HEMCO: Opening /home/zhangj/Geos-Chem/data/ExtData/HEMCO/MERCURY/v2018-04/WHET_Hg0.geos.1x1.2010_final.nc
HEMCO: Opening /home/zhangj/Geos-Chem/data/ExtData/HEMCO/MERCURY/v2018-04/WHET_Hg2.geos.1x1.2010_final.nc
HEMCO: Opening /home/zhangj/Geos-Chem/data/ExtData/HEMCO/MERCURY/v2018-04/WHET_HgP.geos.1x1.2010_final.nc
HEMCO: Opening /home/zhangj/Geos-Chem/data/ExtData/HEMCO/MERCURY/v2014-09/NATURAL/newnatural.geos.4x5.nc
HEMCO: Opening /home/zhangj/Geos-Chem/data/ExtData/HEMCO/MERCURY/v2014-09/SOIL/soilHg.presentday.v11-01.geosfp.4x5.nc

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In Ncop_Rd, cannot open:  /home/zhangj/Geos-Chem/data/ExtData/HEMCO/TIMEZONES/v2015-02/timezones_voronoi_1x1.nc

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Code stopped from DO_ERR_OUT (in module NcdfUtil/m_do_err_out.F90)

This is an error that was encountered in one of the netCDF I/O modules,
which indicates an error in writing to or reading from a netCDF file!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
### Software versions
- CMake version: 3.22.0
- Compilers (Intel or GNU, and version):9.3.0
- NetCDF version: netcdf-c-4.7.4，netcdf-fortran-4.5.3

**Comment by yantosca** [comment]
Thanks for writing @jie0314ouc.  Can you confirm that you have the file:

`/home/zhangj/Geos-Chem/data/ExtData/HEMCO/TIMEZONES/v2015-02/timezones_voronoi_1x1.nc`

on disk.  I think if you are missing this file then it would produce the error that you are seeing.

**Comment by yantosca** [comment]
Thanks @jie0314ouc .  If it can't be read by ncdump then the file is corrupted.  Can you try downloading it again from:
http://geoschemdata.computecanada.ca/ExtData/HEMCO/TIMEZONES/v2015-02/timezones_voronoi_1x1.nc

**Comment by jie0314ouc** [comment]
I redownload the file, but it still didn’t work.





------------------ Original ------------------
From: Bob Yantosca ***@***.***&gt;
Date: Thu,Feb 24,2022 11:30 PM
To: geoschem/geos-chem ***@***.***&gt;
Cc: jie0314ouc ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [geoschem/geos-chem] [BUG/ISSUE] Error reading timezones_voronoi_1x1.nc (Issue #1137)





 
Thanks @jie0314ouc .  If it can't be read by ncdump then the file is corrupted.  Can you try downloading it again from:
 http://geoschemdata.computecanada.ca/ExtData/HEMCO/TIMEZONES/v2015-02/timezones_voronoi_1x1.nc
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yantosca** [comment]
@jie0314ouc, if you type

```console
$ ncdump  /home/zhangj/Geos-Chem/data/ExtData/HEMCO/TIMEZONES/v2015-02/timezones_voronoi_1x1.nc
```
do you get output or is the files still corrupted?

**Comment by jie0314ouc** [comment]
After&nbsp;ncdump  /home/zhangj/Geos-Chem/data/ExtData/HEMCO/TIMEZONES/v2015-02/timezones_voronoi_1x1.nc
error information : 




But I can ncdump other downloaing ncfile like&nbsp;WHET_Hg0.geos.1x1.2010_final.nc successfully.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "geoschem/geos-chem"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月25日(星期五) 凌晨3:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [geoschem/geos-chem] [BUG/ISSUE] Error reading timezones_voronoi_1x1.nc (Issue #1137)





 
@jie0314ouc, if you type
 $ ncdump  /home/zhangj/Geos-Chem/data/ExtData/HEMCO/TIMEZONES/v2015-02/timezones_voronoi_1x1.nc
 
do you get output or is the files still corrupted?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jie0314ouc** [comment]
After ncdump  /home/zhangj/Geos-Chem/data/ExtData/HEMCO/TIMEZONES/v2015-02/timezones_voronoi_1x1.nc
error information :

```
lxh3: ~/Geos-Chem/data/ExtData/HEMCO/TIMEZONES/v2015-02$ ncdump timezones_voronoi_1x1.nc
ncdump: timezones_voronoi_1x1.nc: timezones_voronoi_1x1.nc: NetCDF: Attempt to use feature that was not turned on when netCDF was built.
```

**But I can ncdump other downloaing ncfile like WHET_Hg0.geos.1x1.2010_final.nc successfully.**

```
lxh3: ~/Geos-Chem/data/ExtData/HEMCO/MERCURY/v2018-04$ ncdump WHET_Hg2.geos.1x1.2010_final.nc|less
netcdf WHET_Hg2.geos.1x1.2010_final {
dimensions:
        lon = 360 ;
        lat = 180 ;
variables:
        double lon(lon) ;
                lon:units = "degrees_east" ;
                lon:long_name = "lon" ;
        double lat(lat) ;
                lat:units = "degrees_north" ;
                lat:long_name = "lat" ;
        float Hg2(lat, lon) ;
```

**Comment by jie0314ouc** [comment]
I

**Comment by yantosca** [comment]
I still think that this is caused by a corrupted file on your end.

@YanshunLi-washu, can you verify that the timezones_voronoi_1x1.nc file at the WashU data portal is OK?

**Comment by yantosca** [comment]
Thanks @YanshunLi-washu!  @jie0314ouc, could you try downloading this file again from the http://geoschemdata.wustl.edu/ExtData/HEMCO/TIMEZONES/v2015-02/timezones_voronoi_1x1.nc?

**Comment by jie0314ouc** [comment]
Thanks @yantosca ！I redownloaded the file from http://geoschemdata.wustl.edu/ExtData/HEMCO/TIMEZONES/v2015-02/timezones_voronoi_1x1.nc, but there was still  the same error information prompts here. 
I wondered if there was something wrong with my environment variables?

**Comment by yantosca** [comment]
I don't know what the issue is.  If you've downloaded the file (which was shown to be uncorrupted at WashU) and it still doesn't work then maybe it's an issue with your netCDF or Linux environment setup.  Regrettably, we cannot assist you with fixing issues that are local to your computer system.

Maybe try re-installing netCDF and the other required software libraries and see if that helps.

Sorry we cannot do more.

**Comment by yantosca** [comment]
Closing out this issue.

**Comment by XR-peking** [comment]
Hi Bob,
If our study area is in China, do we need to adjust the time different in the output file like add 8 hours?  and if that is true, what 'timezones_voronoi_1x1.nc' do for us.
Best
