### ISSUE TITLE
[BUG/ISSUE] negative concentrations in nested run

### ISSUE THREAD

**Issue by bsuther** [geoschem/geos-chem#1138]
### What institution are you from?
North Carolina State University

### Description of the problem
I am getting negative NO concentrations at the beginning of time stepping during a  0.25x0.3125 nested NA grid run using version 13.3.3. I believe this is similar to #969  #734 #584. Are you able to tell me why this is occurring and the best resolution? Thank you for your help. 

> ********************************************
> * B e g i n   T i m e   S t e p p i n g !! *
> ********************************************
> 
> ---> DATE: 2014/01/07  UTC: 00:00  X-HRS:      0.000000
>  HEMCO already called for this timestep. Returning.
> NASA-GSFC Tracer Transport Module successfully initialized
> HEMCO (VOLCANO): Opening /rs1/researchers/n/nmeskhi/InputData/gcgrid/data/ExtData/
> HEMCO/VOLCANO/v2021-09/2014/01/so2_volcanic_emissions_Carns.20140107.rc
> --- Initialize surface boundary conditions from input file ---
> --> CCl4 will use prescribed surface boundary conditions from field SfcVMR_CCl4
> --> CFC11 will use prescribed surface boundary conditions from field SfcVMR_CFC11
> --> CFC113 will use prescribed surface boundary conditions from field SfcVMR_CFC11
> 3
> --> CFC114 will use prescribed surface boundary conditions from field SfcVMR_CFC11
> 4
> --> CFC115 will use prescribed surface boundary conditions from field SfcVMR_CFC11
> 5
> --> CFC12 will use prescribed surface boundary conditions from field SfcVMR_CFC12
> --> CH2Cl2 will use prescribed surface boundary conditions from field SfcVMR_CH2Cl
> 2
> --> CH3Br will use prescribed surface boundary conditions from field SfcVMR_CH3Br
> --> CH3CCl3 will use prescribed surface boundary conditions from field SfcVMR_CH3C
> Cl3
> --> CH3Cl will use prescribed surface boundary conditions from field SfcVMR_CH3Cl
> --> CHCl3 will use prescribed surface boundary conditions from field SfcVMR_CHCl3
> --> H1211 will use prescribed surface boundary conditions from field SfcVMR_H1211
> --> H1301 will use prescribed surface boundary conditions from field SfcVMR_H1301
> --> H2402 will use prescribed surface boundary conditions from field SfcVMR_H2402
> --> HCFC141b will use prescribed surface boundary conditions from field SfcVMR_HCF
> C141b
> --> HCFC142b will use prescribed surface boundary conditions from field SfcVMR_HCF
> C142b
> --> HCFC22 will use prescribed surface boundary conditions from field SfcVMR_HCFC2
> 2
> --> N2O will use prescribed surface boundary conditions from field SfcVMR_N2O
> --> OCS will use prescribed surface boundary conditions from field SfcVMR_OCS
> --> H2 will use prescribed surface boundary conditions from field SfcVMR_H2
> --- Finished initializing surface boundary conditions ---
>  WARNING: Negative concentration for species NO at (I,J,L) =            9
>          200           2
>  WARNING: Negative concentration for species NO at (I,J,L) =            9
>          200           3
>  WARNING: Negative concentration for species NO at (I,J,L) =            9
>          200           4
>  WARNING: Negative concentration for species NO at (I,J,L) =            9
>          200           5
>  WARNING: Negative concentration for species NO at (I,J,L) =            9
>          200           6
>  WARNING: Negative concentration for species NO at (I,J,L) =            9
>          200           7
>  WARNING: Negative concentration for species NO at (I,J,L) =            9
>          200           8
>  WARNING: Negative concentration for species NO at (I,J,L) =            9
>          200           9
>  WARNING: Negative concentration for species NO at (I,J,L) =            9

### Description of troubleshooting performed
 I believe this is similar to #969  #734 #584. However, since it is happening right away it does not seem like the proposed solutions will work. I am already using the shorter recommended timestep of 300 sec. I also tried doubling the background concentration of NO in the species_database.yml file. I am open to making the modification of changing 
IF ( State_Chm%Species(I,J,L,N) < 0.0_fp ) THEN {...}
to
State_Chm%Species(I,J,L,N) = MAX(State_Chm%Species(I,J,L,N),0.0_fp)
in mixing_mmod.F90 as described in #734 however, I wanted to make sure that this is the best option first. I am also worried about this violating mass conservation. Is there a simple way to check how big of an effect this will have?

### GEOS-Chem version
===> GEOS-Chem version         : 13.3.3

### Description of modifications
I modified the species_database.yml file. 

### Log files

[GC.log](https://github.com/geoschem/geos-chem/files/8133887/GC.log)
[input.txt](https://github.com/geoschem/geos-chem/files/8133900/input.txt)
[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/8133919/HEMCO_Config.txt)
[make.txt](https://github.com/geoschem/geos-chem/files/8133939/make.txt)

### Software versions
- CMake version: 3.19.0
- Compilers (Intel or GNU, and version): intel/2019.2.199
- NetCDF version: 4.6.1-intel2017

**Comment by yantosca** [comment]
Thanks for writing @bsuther and for your patience (we have been very busy here).  Typically when this happens it means that a particular concentration gets too small or too large and the KPP solver cannot converge to a solution.  Have you checked the concentrations of NO in your boundary condition file?  If bad values are getting read in then that might cause issues.

You could try flushing negative values to zero and see what happens.  Another thing you can do is to turn off operations one by one and see if you can isolate which operation the negatives are occurring in.  It seems like it might be happening in mixing.
