### ISSUE TITLE
[QUESTION] question about sulfur chemistry via KPP

### ISSUE THREAD

**Issue by lumosmoon** [geoschem/geos-chem#1139]
Hi Geos-Chem team,

I noticed that you have implemented sulfur in-cloud and on aerosols reactions via KPP. I have some questions after reviewing the code.

1. Both produce SO4, so why are some reactants written as SO2 (e.g., `SO2+ H2O2 = SO4` )while others are written as HSO3m/SO3mm (e.g., `HOCl + HSO3m = SO4 + HCl`)? Is it true that the latter reaction produces SO4 without consuming SO2? It instead consumes HSO3m. This brings me to my second question. 

2. It seems that HSO3m/SO3mm are calculated in `SUBROUTINE AQCHEM_SO2` in `KPP/fullchem/fullchem_SulfurChemFuncs.F90`. At each timestep, they are calculated from the dissolving equilibrium of SO2, which does not appear to be affected by its consumption in KPP? 

Any help you could provide would be much appreciated

**Comment by yantosca** [comment]
Thanks for writing.  I am tagging @msl3v, who can give a better explanation than I can.

**Comment by msl3v** [comment]
Hello lumosmoon,
See below...

On 2/25/22 03:52, lumosmoon wrote:
>
> Hi Geos-Chem team,
>
> I noticed that you have implemented sulfur in-cloud and on aerosols 
> reactions via KPP. I have some questions after reviewing the code.
>
> 1.
>
>     Both produce SO4, so why are some reactants written as SO2 (e.g.,
>     |SO2+ H2O2 = SO4| )while others are written as HSO3m/SO3mm (e.g.,
>     |HOCl + HSO3m = SO4 + HCl|)? Is it true that the latter reaction
>     produces SO4 without consuming SO2? It instead consumes HSO3m.
>     This brings me to my second question.
>
The original code for hypohalous acids HOBr and HOCl branched the 
reactions into two, accounting for HSO3m and SO3mm pathways, though it 
did so a little differently than done here. (Note you'll find the same 
operations in sulfate_mod.F90 that you find in 
fullchem_SulfurChemFuncs.F90) The goal with the transition to KPP was to 
maintain as much of the original structure as possible and only move the 
chemical reaction computation into KPP. That is reflected here. I wanted 
to put HSO3m and SO3mm in explicitly to lay the groundwork for proper 
dissolved-phase partitioning when/if it becomes possible or necessary. I 
hope it's not too confusing.
>
> 1.
>
>
>  2. It seems that HSO3m/SO3mm are calculated in |SUBROUTINE
>     AQCHEM_SO2| in |KPP/fullchem/fullchem_SulfurChemFuncs.F90|. At
>     each timestep, they are calculated from the dissolving equilibrium
>     of SO2, which does not appear to be affected by its consumption in
>     KPP?
>
This was also meant to be consistent with the previous implementation. 
You point out a real potential issue here regarding accounting and mass 
balance. The way I justified keeping the original behavior was that 
consumption of any dissolved S(IV) would in any case be replenished by 
more uptake from gas phase, and that gas/particle would always be in 
equilibrium. If we can assume that little of the S(IV) dissolved in a 
timestep remains as as S(IV), then we can also assume mass balance error 
is minimized. Unless I am overlooking anything in the sulfur code, there 
is no way for dissolved S(IV) to return to the gas phase (right?).

Ultimately, the sum of both of your questions seems to highlight some 
inconsistency in the sulfur code with regards to gas/particle 
partitioning. If GCSC or GCST don't like this implementation, it is 
possible to make the reactions more like the H2O2 pathway. The HSO3m and 
SO3mm partitioning calculation would still have to be performed in 
either case.

I hope I answered your questions. Let me know if you have any more, or 
if you see any options for improvement. I'm eager to see this part of 
the code get more scrutiny.

Sincerely,
Michael Long

**Comment by lumosmoon** [comment]
Hello @msl3v . Thanks a lot for your detailed response. I still have some questions.

`SO2+H2O2=SO4` can deduct SO2 directly and the remaining SO2 will be passed to the next time step; but when it comes to `HOCl+HSO3m=SO4+HCl`, although HSO3m is consumed, the code does not see how the effect of HSO3m consumption is passed to the next time step.

As at the next time step, HSO3m is calculated by the gas-liquid rebalance of SO2 using this formula (see below). Unless the consumption of HSO3m/SO3mm also affects the concentration of hydrogen ions, which is linked to the thermodynamic process (ISORROPIA)?
![image](https://user-images.githubusercontent.com/61012072/156165553-238d5d76-635e-44c2-89da-94d58c9c30da.png)

We use pSO2(the partial pressure of SO2) and H+ to calculate HSO3m/SO3mm, but we do not subtract these parts from SO2(g), right? So if we write other reactions `e.g. H2O2+ HSO3m/SO3mm = SO4 `similar to HOCl, will the SO2(g) concentration never drop due to chemistry? Perhaps I am missing something in the code.

Maybe some tests could be done: ①`HOCl + HSO3m = SO4 + HCl` ②`HOCl + SO2 = SO4 + HCl`. Then we can see how much impact these treatments would have on SO2 and sulfate abundance.

Thanks for your kind help.

**Comment by msl3v** [comment]
@lumosmoon
Since your original questions, the decision was made to rewrite the 
reactions to use SO2 directly. The HSO3m/SO3mm calculation will only be 
used as a scaling coefficient in the rate constant calculation. This 
should resolve your concerns. Please let me know if you have others.

**Comment by djxjacob** [comment]
Mike, will you make that change in 13.4 or does it require more testing? As you know, we need to redo the benchmarking of 13.4 to disable SSA debromination so there’s an opportunity to slip it in there.  Daniel

**Comment by msl3v** [comment]
The code is done, and I'll do some short-term testing on it this week. 
Otherwise, it's not a complex change, and it can definitely make it into 
the re-benchmark.

**Comment by msulprizio** [comment]
The update described above has now been merged into `dev` and will be included in GEOS-Chem 13.4.0.
