### ISSUE TITLE
[QUESTION] maximum timestep for transport in input_mod.F90

### ISSUE THREAD

**Issue by jinlx** [geoschem/geos-chem#1141]
Hi there,

I noticed that the GEOS-Chem has timestep limits for each resolution in input_mod.F90. The max transport timestep is 5min for 0.25x0.3125 in the default setting. I was wondering if therea are any specific reasons of doing it. Do previous studies suggests that there have large performance diff between 5min and larger than 5min (e.g., 10 min) at 0.25 resoultion? 

Cheers,
Lixu

**Comment by djxjacob** [comment]
Recommended time steps in GEOS-Chem aim to balance accuracy and performance. You can try longer time steps to improve performance and decide if the loss of accuracy is acceptable. Daniel

From: Lixu Jin ***@***.***>
Sent: Sunday, February 27, 2022 5:17 PM
To: geoschem/geos-chem ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [geoschem/geos-chem] [QUESTION] maximum timestep for transport in input_mod.F90 (Issue #1141)


Hi there,

I noticed that the GEOS-Chem has timestep limits for each resolution in input_mod.F90. The max transport timestep is 5min for 0.25x0.3125 in the default setting. I was wondering if therea are any specific reasons of doing it. Do previous studies suggests that there have large performance diff between 5min and larger than 5min (e.g., 10 min) at 0.25 resoultion?

Cheers,
Lixu

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_geoschem_geos-2Dchem_issues_1141&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=rhdjeCmvErplnjGEj5OoH_CDkPdqB-BDUxqwWC1AzIs&m=Ocy_z9F1bu-ayRzkEUgMxyBdnrmr3sN6vDtiqAEC0WGZZfEcj_k9IHWpJDJaVPYY&s=EtcnFS08CIjSBYkBntPwvPT69laXvm1XfoD1_4hHAXs&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AKHHSVJTZXI6TYEEIBOTAPDU5KPETANCNFSM5PPQTV5A&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=rhdjeCmvErplnjGEj5OoH_CDkPdqB-BDUxqwWC1AzIs&m=Ocy_z9F1bu-ayRzkEUgMxyBdnrmr3sN6vDtiqAEC0WGZZfEcj_k9IHWpJDJaVPYY&s=NZ0JZdVWWbfv54iemU0nwgAMpuIjN3R9PAvnI-fg6Ns&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=rhdjeCmvErplnjGEj5OoH_CDkPdqB-BDUxqwWC1AzIs&m=Ocy_z9F1bu-ayRzkEUgMxyBdnrmr3sN6vDtiqAEC0WGZZfEcj_k9IHWpJDJaVPYY&s=a8Dqlkyk9aFy75lE6hTh_f_LEtDNDUGddzIunLDusfw&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=rhdjeCmvErplnjGEj5OoH_CDkPdqB-BDUxqwWC1AzIs&m=Ocy_z9F1bu-ayRzkEUgMxyBdnrmr3sN6vDtiqAEC0WGZZfEcj_k9IHWpJDJaVPYY&s=LrAx89X2RrM5aHRMxBahENSw-tgcmQLs_Q4a5Uq4dls&e=>.

**Comment by jinlx** [comment]
Thanks Daniel! I am most interested in seeing if GC will reproduce simliar performance but save CPU time at different timesteps at 0.25. It seems that no one has tested the sensitivity at 0.25 before but please let me if any folks has tested it. I will go with running a few weeks and see if 10min transport timestep will reproduce simliar result as 5min for now. - Lixu

**Comment by lizziel** [comment]
Hi @jinlx, we have had reports of instability at higher transport timesteps in nested grid model runs. If you set the timesteps too large, you could end up violating the Courant limit (i.e. instead of moving air from one box to a neighboring box,  it could move air two or more boxes away).

**Comment by jinlx** [comment]
Hi Lizzie! That makes a lot of sense to me. Thanks for the helpful informaiton!  I guess the sensitive of transport time steps will be most significant with deep convection in summers but may be less sensitive in winters. Is that right? I wonder if you see those reports mostly in simulations for summers or winters?

**Comment by djxjacob** [comment]
You just have to try, you may be OK, and if you get crappy results you will know why.  The time steps we recommend are conservative and you might be able to get away with longer.

**Comment by jinlx** [comment]
Sounds great! Thanks Daniel! Please feel free to close the issue.
