### ISSUE TITLE
[BUG/ISSUE] GEOS-Chem-Hg 13.3.3 budgets

### ISSUE THREAD

**Issue by CharikleiaGRN** [geoschem/geos-chem#1146]
Hi all!
I am using GEOS-Chem 13.3.3 for mercury simulation. 
2x2.5 , GEOS-FP, production year: 2015

I would just like to mention some of the annual budget outputs that look weird:
1) Dry Deposition HgP is almost zero= 5.9 e-08 tonnes
2) FluxHg0fromAirtoOcean = 1.043 tonnes
3) FluxHg0fromOceantoAir = 2.601 tonnes
the 2) and 3) should be like double. By the way, the long names of these two variables should be exchanged. 

Another thing, for the upcoming version 13.4. I used the code from the author. I think there is a small problem with the output of EmisHg2HgPanthro. They are higher than they should. Checked this for Streets inventory and some others.

Thank you very much!!!

**Comment by yantosca** [comment]
Thanks for writing @CharikleiaGRN.  Am tagging @jennyfisher, @cdholmes, and @yanxuz, who are the Hg & POPs WG Co-chairs.  Also @viral211 who has done a lot of work on the new Hg code.  Feel free to add any comments here.

At this point the 13.4.0 Hg code is in validation and once it checks out will replace the 13.3.3 code.   Also, I wouldn't necessarily trust the History diagnostic collection as they were never properly validated against the older bpch diagnostics.  The 13.4.0 emissions diagnostics are now archived by HEMCO.
