### ISSUE TITLE
[QUESTION] How to calculate wet depositon velocity?

### ISSUE THREAD

**Issue by yangning-code** [geoschem/geos-chem#1149]
### Ask a question about GEOS-Chem:
The dry-deposition velocity is computed in the drydep_mod.F90 module and can be archived by saving out the DryDep collection from the GEOS-Chem History diagnostics. However, How to calculate the wet deposition velocity?

**Comment by yantosca** [comment]
Thanks for writing @yangning-code.  I do not believe we use a wet deposition velocity in the GEOS-Chem wet deposition scheme.  I would ask either the Transport Working Group or the Emission and Deposition Working Group.
