### ISSUE TITLE
[QUESTION] CO2 simulation question and empty HEMCO diagnostic files

### ISSUE THREAD

**Issue by kimm1na** [geoschem/geos-chem#1154]
Ask a question about GEOS-Chem:

Hello, @yantosca @msulprizio

I am trying CO2 simulation using GEOS-Chem 13.0.1.
I have a few questions about HEMCO_Diagn.rc file and HEMCO_diagnostics.XXXX.nc output file.

1) In HEMCO_Config.rc , there are no DiagnFile contents so HEMCO_diagnostic output files are almost empty. It seems to be some kind of bug. (so I added the line 5 and it worked.)

![image](https://user-images.githubusercontent.com/89123880/157189989-6bb52052-c70e-45e5-adcc-61e5930142ea.png)

2) Can EmisCO2_CO2SurfCorr in HEMCO_Diagnostic output file be considered CO2corr?

3) There are EmisCO2_ship, EmisCO2_ocean, ... etc in HEMCO_Diagnostic output files. But where can I find CO2chem? Is it ProdCO2fromCO in a file like GEOSChem.CO2.xxxxx.nc4, not HEMCO_Diagnostic file?

Thank you very much.
Sincerely, Mina Kim

**Comment by yantosca** [comment]
I also think EmisCO2_CO2SurfCorr correlates to CO2corr.  Also you are right, the ProdCO2fromCO HISTORY diagnostic will save the production of CO2 from CO oxidation.  You can look at the source code in `src/GEOS-Chem/GeosCore/co2_mod.F90`.

**Comment by kimm1na** [comment]
> 
Thank you, @yantosca 

But I mean HEMCO_Config.rc file does not have 'Diagn File : HEMCO_Diagn.rc' in line 5 originally so there are no contents in diagnostic output (in GC 13.0.1. ver). 

Could you please check the default HEMCO_Config.rc for CO2 simulation in GC 13.0.1. ?


![image](https://user-images.githubusercontent.com/89123880/157562855-4af84112-f538-43c6-8d4c-e1ad84612693.png)

(Now I added the 5th line in that screenshot and it worked)

**Comment by yantosca** [comment]
Thanks for the feedback.  I will close out this issue.  Feel free to contact us again.
