### ISSUE TITLE
[BUG/ISSUE] Is MULTISEAICE supposed to be 1984-2017?

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/geos-chem#1158]
### What institution are you from?
WUSTL

### Description of the problem
I noticed that `MULTISEAICE` in HEMCO_Config.rc has a period of 1984-2017
https://github.com/geoschem/geos-chem/blob/9ab6931db5b556eafd0e002e9fd4fdbcbd5fbb44/run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem#L2890
but http://geoschemdata.wustl.edu/ExtData/HEMCO/MULTI_ICE/v2021-07/ has data for 1980-2020. Should the period in HEMCO_Config.rc actually be 1980-2020? Any idea @msulprizio @yantosca or @lizziel?

IIUC, GC-Classic is using the 2017 file for 2018 onwards. 

(fyi @laestrada)

**Comment by LiamBindle** [comment]
Same goes for CEDS_NO_SHP in CEDS/v2021-06. The data period in HEMCO_Config is 1750-2010 but the data in v2021-06 is 1750-2019.
https://github.com/geoschem/geos-chem/blob/9ab6931db5b556eafd0e002e9fd4fdbcbd5fbb44/run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem#L2415

CEDS/v2021-06 on data portal: http://geoschemdata.wustl.edu/ExtData/HEMCO/CEDS/v2021-06/

Shoudl the line in HEMCO_Config be 1750-2019?

**Comment by msulprizio** [comment]
That's definitely a typo for `CEDS_NO_SHIP`. It should be updated to 2019 for the latest version of CEDS. We can fix that in 13.4.0.

**Comment by msulprizio** [comment]
@lizziel It looks like you added the `MULTI_ICE` files, possible for the emissions from blowing snow update? I assume the years should be  1980-2020 as @LiamBindle points out. Can you confirm?

**Comment by lizziel** [comment]
Yes, that date range was an error. The HEMCO_Config.rc submission for the update in https://github.com/geoschem/geos-chem/pull/356 contained 1984-2017, and then the developer said she was submitting data for 1984-2018. I never checked the actual data submitted to change that string. Yes that will change the benchmark.

**Comment by LiamBindle** [comment]
Awesome, thanks @msulprizio and @lizziel!

**Comment by yantosca** [comment]
We can close this issue since PR #1159 has been merged into the 13.4.0 development stream.  At this time 13.4.0 is pending benchmark approval.
