### ISSUE TITLE
Problems regarding to GFED4

### ISSUE THREAD

**Issue by Jim-Xu** [geoschem/geos-chem#116]
Recently I met up with a problem regarding to HEMCO. When I run the Hg simulation, the default biomass burning emission inventory GFED4 always have the error which will kill the simulation. The error information remind me to check the HEMCO.log  file, it seems that there's some coding problem, which make the compiler cannot recognize and read the species name. (I used intel 17 version of compiler, this problems will not be report as an error when using intel 15 version)
I am really looking forward to hearing from anyone who can give me some advice. 
Many thanks in advance!

I have attached the HEMCO.log file. 
[HEMCO.log](https://github.com/geoschem/geos-chem/files/3781806/HEMCO.log)

**Comment by yantosca** [comment]
Have you also tried compiling with the debug flags?
```
make -j4 DEBUG=y BOUNDS=y FPEX=y build
```
Also please see our Debugging GEOS-Chem wiki page for more tips.
http://wiki.geos.chem.org/Debugging_GEOS-Chem

**Comment by Jim-Xu** [comment]
> It looks like some of the input files might be corrupted. For example, when it tries to print the species name there is garbage.
> 
> ```
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> HEMCO ERROR: Species �       �       Øgë�    A       not found in GFED
> ```
> 
> Can you also attach the following files:
> 
> 1. input.geos
> 2. HEMCO_Config.rc
> 3. lastbuild file

Thanks for your reply. I attached the recent files below. I am not sure whether it's this two files corrupted or not since I basically didn't change it. I only changed the necessary part like simulation time, thus most of it are still remain in default status. 
Like I mentioned in my question, this problem will not occur in intel 15 version compiler, so I used version 15 compiler to run a simulation with the same input.geos and HEMCO_Config.rc, the version 15 simulation works but version 17 failed. 
[Files.zip](https://github.com/geoschem/geos-chem/files/3786740/Files.zip)

**Comment by Jim-Xu** [comment]
> Have you also tried compiling with the debug flags?
> 
> ```
> make -j4 DEBUG=y BOUNDS=y FPEX=y build
> ```
> 
> Also please see our Debugging GEOS-Chem wiki page for more tips.
> http://wiki.geos.chem.org/Debugging_GEOS-Chem

Thank you so much! I just tried your recommendation, using  _**make -j12 MET=GEOSFP GRID=4x5 BPCH_TPBC=y DEBUG=y BOUNDS=y FPEX=y**_  to compile in Code12.2.1 with version 17 compiler and move geos into rundir (geosfp_4*5_standard), this time will not report error.  Many thanks again!

**Comment by msulprizio** [comment]
This may error be specific to certain fortran compiler versions. See https://github.com/geoschem/geos-chem/issues/231.
