### ISSUE TITLE
[QUESTION] ProdLoss Diagnostic: ProdSO4 gas phase in fullchem

### ISSUE THREAD

**Issue by IshirDutta** [geoschem/geos-chem#1160]
### Ask a question about GEOS-Chem:

Hi folks, I'm running v13.2.1 and trying to make a version of Figure 2 from [Hattori et al., 2021](https://www.science.org/doi/10.1126/sciadv.abd4610) that shows different SO2 oxidation pathways. Based on magnitudes I would think that "ProdSO4fromO3s" (formerly ND05#19) is gas phase oxidation (SO2 + OH) rather than ozone on sea salt. However, unless I'm missing something, "ProdSO4fromGasPhase" appears to exist for the aerosol-only version of the model. What would be equivalent to ProdSO4fromGasPhase when running fullchem?

Thanks!

![image](https://user-images.githubusercontent.com/33105692/157744567-75cefaae-1470-4627-a955-3eaa0f98a445.png)

**Comment by yantosca** [comment]
Thanks for writing @IshirDutta.  You are correct, it is the same as ND05 slot number 19.

The nomenclature `O3s` was picked by the developer of the feature (I think Quanjie Chen at UW), as that is the variable name in `sulfate_mod.F90`.

**Comment by IshirDutta** [comment]
Just to clarify (I realize I phrased the question poorly!) - ProdSO4fromO3s is the equivalent of SO2 + OH for fullchem?
Thanks!

**Comment by yantosca** [comment]
I believe that is correct.  Also tagging Mike Long (@msl3v) who has been looking into the sulfur chemistry.

**Comment by msl3v** [comment]
Hey all.

If you look in sulfate_mod.F90, you find that ProdSO4fromO3s is from the 
aqueous reaction
SO3-- + O3 -> ...

The SO2 + OH reaction is in KPP and I don't know if there's a specific 
diagnostic in place for that. It would be possible to add a dummy 
species as a product and use that to track the reaction.

**Comment by IshirDutta** [comment]
Thanks, @msl3v! My understanding of that section of sulfate_mod was that it was roughly meant to represent:

SO2 + OH + M -> HOSO2 + M
HOSO2 + O2 -> HO2 + SO3
SO3 + H2O + M -> H2SO4 + M

with O3 as a stand-in for the intermediate HOx cycling, mostly because there's already an in-cloud O3 production diagnostic with comparable magnitude...
