### ISSUE TITLE
[BUG/ISSUE] the Restart file output error when the simulation end is the time of the begining of month

### ISSUE THREAD

**Issue by hgrhgy** [geoschem/geos-chem#1168]
As following configuration,  running the CO2 simulation will result in the following error `GEOS-Chem ERROR: No diagnostic output will be created for collection:  
"Restart"!  Make sure that the length of the simulation as specified in 
"input.geos" (check the start and end times) is not shorter than the frequency 
setting in HISTORY.rc!` 

And modify the `frequency` and `duration` to `00000000 060000`, the simulation is fine. It seems the calculations of the duration or frequency were incorrectly, when the simulation end is the begining of the months.

GEOSCHEM version: 13.3.3
gcc: 9.4.0

```bash
# input.geos file #
%%% SIMULATION MENU %%% :
Start YYYYMMDD, hhmmss  : 20170131 180000
End   YYYYMMDD, hhmmss  : 20170201 000000

# HISTORY.rc #
...
#==============================================================================
# %%%%% THE Restart COLLECTION %%%%%
#
# GEOS-Chem restart file fields
#
# Available for all simulations
#==============================================================================
  Restart.filename:           './GEOSChem.Restart.%y4%m2%d2_%h2%n2z.nc4',
  Restart.frequency:          'End',     # modify to '00000000 060000'， the simulation is fine
  Restart.duration:           'End',     # modify to '00000000 060000', the simulation is fine
  Restart.mode:               'instantaneous'
  Restart.fields:             'SpeciesRst_?ALL?               ',
                              'Met_DELPDRY                    ',
                              'Met_PS1WET                     ',
                              'Met_PS1DRY                     ',
                              'Met_SPHU1                      ',
                              'Met_TMPU1                      ',
::
...
```

**Comment by yantosca** [comment]
Thanks for writing @hgrhgy.  We have made some updates that will be added to 13.4.0 that I think will fix this problem.  See: #1020

**Comment by yantosca** [comment]
I will close out this issue as the solution is listed in #1020.
