### ISSUE TITLE
[QUESTION] GEOS-Chem13.3.1: GFED4 vertical distribution of emissions

### ISSUE THREAD

**Issue by wanghlin** [geoschem/geos-chem#1172]
When running the fullchem simulation, I found that the biomass burning emissions in the HEMCO_diagnostics results became double. I am not sure what might lead to this, can you offer me some help?

**Comment by wanghlin** [comment]
Maybe there is a problem in the vertical distribution of biomass burning emissions. Because I didn't distribute 65% to PBL and 35% to FT, the total biomass burning emissions were correct. Here is the code that I have changed the distribution.
[hcox_gfed_mod.F90.txt](https://github.com/geoschem/geos-chem/files/8253056/hcox_gfed_mod.F90.txt)

**Comment by msulprizio** [comment]
Also note that particular code in the GFED extension was added back in v11-02a (in early 2017), before HEMCO was separated out as a submodule in GEOS-Chem. It's likely that many structural changes have been made to that code, so I would not be surprised if that feature no longer works properly.

**Comment by yantosca** [comment]
I will close out this issue for now.

**Comment by zsx-GitHub** [comment]
@wanghlin Hi, just want to know, have you figured out whether this feature is working properly in GCv13.3.1 after your edits? Thank you!

**Comment by zsx-GitHub** [comment]
Hi @wanghlin, have you figured out whether your edits are working properly in GCv13.3.1? Thank you!

**Comment by wanghlin** [comment]
> @wanghlin have you figured out whether this feature is working properly in GCv13.3.1 after your edits? Thank you!

Hi @zsx-GitHub, I have reworked the code for vertically distributed emissions in hcox_gfed_mod.F90 in GCv13.3.1. It has been able to successfully distribute 65% of the biomass burning emissions to PBL and 35% to FT.

**Comment by zsx-GitHub** [comment]
Thanks! Have you changed anything? Or just released the commented lines in hcox_gfed_mod.F90?
