### ISSUE TITLE
[BUG/ISSUE] Problem with downloading HEMCO files from WUSTL

### ISSUE THREAD

**Issue by ssj94** [geoschem/geos-chem#1173]
### What institution are you from?
University of Wollongong, Australia

### Description of the problem
I was trying to download HEMCO GFAS files from WUSTL (using the following URL "http://geoschemdata.wustl.edu/ExtData/HEMCO/GFAS/v2018-09/") into my working space. I used the following command to download the files,

```console
wget -r -np -R "index.html*" -nH --cut-dirs=4 -c "http://geoschemdata.wustl.edu/ExtData/HEMCO/GFAS/v2018-09/2003/"
```
However, it returned with an error message as shown below,

```console
--2022-03-15 16:47:16--  http://geoschemdata.wustl.edu/ExtData/HEMCO/GFAS/v2018-09/2003/
Resolving geoschemdata.wustl.edu (geoschemdata.wustl.edu)... 35.209.233.133
Connecting to geoschemdata.wustl.edu (geoschemdata.wustl.edu)|35.209.233.133|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1467 (1.4K) [text/html]
Saving to: ‘2003/index.html.tmp’

2003/index.html.tmp 100%[===================>]   1.43K  --.-KB/s    in 0s      

2022-03-15 16:47:18 (112 MB/s) - ‘2003/index.html.tmp’ saved [1467/1467]

Loading robots.txt; please ignore errors.
--2022-03-15 16:47:18--  http://geoschemdata.wustl.edu/robots.txt
Reusing existing connection to geoschemdata.wustl.edu:80.
HTTP request sent, awaiting response... 200 OK
Length: 26 [text/plain]
Saving to: ‘robots.txt’

robots.txt          100%[===================>]      26  --.-KB/s    in 0s      

2022-03-15 16:47:18 (2.57 MB/s) - ‘robots.txt’ saved [26/26]

Removing 2003/index.html.tmp since it should be rejected.

FINISHED --2022-03-15 16:47:18--
Total wall clock time: 1.7s
Downloaded: 2 files, 1.5K in 0s (64.3 MB/s)
```

### Description of troubleshooting performed
Describe any troubleshooting that you have already performed here. Also include any leads or suspicions here.

### GEOS-Chem version
Enter your GEOS-Chem version here.

### Description of modifications
Describe your modifications here.

### Log files
- Build log (if applicable):
- Run logs (if applicable):
- Run script (if applicable):

### Software versions
- CMake version:
- Compilers (Intel or GNU, and version):
- NetCDF version:

**Comment by yantosca** [comment]
Please see issue #1173 for a solution.

**Comment by bzhang419** [comment]
Hi, I had the same issue before, I fixed it by turning off wget robots.txt. See #1165

**Comment by yantosca** [comment]
> Please see issue #1173 for a solution.

Oops, sorry, I meant to type #1165, which is the solution by @bzhang419.

**Comment by ssj94** [comment]
Thank you!. it is working now.

**Comment by eamarais** [comment]
Would it be possible to update the download instructions on the wiki (http://wiki.seas.harvard.edu/geos-chem/index.php/Downloading_data_from_WashU)?
