### ISSUE TITLE
[QUESTION] the calculation of the gravitational velocity and gravitational deposition flux

### ISSUE THREAD

**Issue by lixiao-bit** [geoschem/geos-chem#1176]
### Ask a question about GEOS-Chem:
Hi GC Team, 

I have recently read subroutines like DEPVEL and DO_DRYDEP in drydep_mod.F90, which is used to calculate DryDepVel. According to [Zhang et al. 2001], the dry deposition velocity for aerosol should be calculated as Vd = Vg+ 1/(Va+Vs).  However, the code may ignore the gravitational velocity (Vg) and only calculate the second term (1/(Va+Vs)) in the equation. In my opinion,  it is necessary to add Vg to the original VD(k) and finally assigned it to DryDepVel(I, J, K).

the second question is about the updated dry deposition velocity of SO2 and DST1-4. In general, the dry deposition velocity of gas should be smaller than particles. So, why is the dry deposition velocity of dust is still smaller than SO2's after updates?

The third question is about the calculation of gravitational deposition flux, which is achieved in sulfate_mod.F90 for SO4s, NITs, SO4D1-4 and NITD1-4. The gravitational deposition flux is assigned to DryDepChm finally. So can I note the calculation of these species' gravitational deposition flux and use the new dry deposition velocity mentioned above. That is to say, use the updated Vd to calculate DryDepMix instead of the original calculation of the sum of DryDepMix and DryDepChm.

The fourth question is about the gravitational deposition flux of other particles except for SO4s, NITs, SO4D1-4 and NITD1-4. In this regard, can I understand that at least for other aerosols like sulfate and nitrate, the code ignores the gravitational deposition flux that should be included in DryDep finally?

I hope to hear from you soon. thanks.

**Comment by yantosca** [comment]
Thanks for writing @lixiao-bit.  These are science questions and should be directed to the Emissions & Deposition working group.

**Comment by yantosca** [comment]
Closing out this issue.
