### ISSUE TITLE
[BUG/ISSUE] Met fields from incorrect times get saved to GEOS-Chem Classic restart files

### ISSUE THREAD

**Issue by WilliamDowns** [geoschem/geos-chem#118]
Several meteorology fields are saved to GEOS-Chem Classic restart files to preserve information from the end of a run that is needed at the beginning of another run of the model. These fields are meant to contain conditions from the very end of a run. However, these fields are currently saved to the restart file before the final update of met fields in a run. As a result, some of the met fields saved to the restart file contain out-of-date values. For example, a run ending at 00z should save 00z met fields to the restart file, but actually saves 21z met fields and claims they are from 00z.

**Comment by msulprizio** [comment]
This is now fixed in https://github.com/geoschem/geos-chem/commit/e6df95964b1fc1bac7ddc51271671433fc68f47d
