### ISSUE TITLE
[BUG/ISSUE]When I submit the job, there is an error in reading HEMCO, as follows

### ISSUE THREAD

**Issue by callazhao** [geoschem/geos-chem#1180]
### Description of the problem
Hi！When I submit the job, there is an error in reading HEMCO, as follows
![image](https://user-images.githubusercontent.com/101862285/158960528-500f9b4c-9a1d-420b-a30c-d5c19b6ceb08.png)
These are hemco.log and  log respectively interface.
But in the log file I found this problem and I won't solve it.
![image](https://user-images.githubusercontent.com/101862285/158961087-5e90ab72-35a8-4d8a-b53b-8d6d0921ad5b.png)
Can you give me some suggestions？
Good luck！
### Description of troubleshooting performed
Describe any troubleshooting that you have already performed here. Also include any leads or suspicions here.

### GEOS-Chem version
12.9.3
[input.geos.txt](https://github.com/geoschem/geos-chem/files/8302646/input.geos.txt)
[lastbuild.txt](https://github.com/geoschem/geos-chem/files/8302647/lastbuild.txt)

### Description of modifications
Describe your modifications here.

### Log files
- Build log (if applicable):
- Run logs (if applicable):
- Run script (if applicable):
[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/8302641/HEMCO_Config.txt)

### Software versions
- CMake version:
- Compilers (Intel or GNU, and version):
- NetCDF version:

**Comment by yantosca** [comment]
Thanks @callazhao for writing. This error means that there is a syntax error in your `HEMCO_Config.rc` file.  Maybe there are too many or too few entries on a given line.  

Try to check your `HEMCO_Config.rc`against an "out-of-the-box" version (i.e. a `HEMCO_Config.rc` file from a newly-created run directory).  You should be able to isolate where the error is very quickly that way.

**Comment by callazhao** [comment]
Thank you for your reply. I have managed to find errors and correct them. Your help is very useful to me. Thanks！
