### ISSUE TITLE
memory usuage problem when using GC13.3.0

### ISSUE THREAD

**Issue by LiHui94** [geoschem/geos-chem#1181]
### Ask a question about GEOS-Chem:
when I ran GC13.3.0 with 8 cpus running in parallel on a single node, nearly 250GB of memory was used. Is this usage normal? 
Besides, I wonder why there is no option for the following sector when I created my run directory with 13.3.0. It seems I can only choose fullchem?
     Choose chemistry domain:
     -----------------------------------------------------------
       1. Troposphere + stratosphere (Recommended)
       2. Troposphere only

**Comment by yantosca** [comment]
I don't know why your run is using 250GB of memory, that is not normal.

Also, please note that the "tropchem" mechanism (i.e. not using UCX) has been retired in GEOS-Chem 13.3.0.  See issue #332.

**Comment by LiHui94** [comment]
> I don't know why your run is using 250GB of memory, that is not normal.
> 
> Also, please note that the "tropchem" mechanism (i.e. not using UCX) has been retired in GEOS-Chem 13.3.0. See issue #332.

OK, the memory problem has been fixed, it seems to be a problem when submitting a task.  Thanks for letting me know about "tropchem" mechanism".
