### ISSUE TITLE
[BUG/ISSUE] Code stopped from DO_ERR_OUT (in module NcdfUtil/m_do_err_out.F90)

### ISSUE THREAD

**Issue by LiHui94** [geoschem/geos-chem#1184]
### What institution are you from?
Tsinghua University.

### Description of the problem
In Nccr_Wr, cannot create:  OutputDir/GEOSChem.SpeciesConc.20190701_0000z.nc4
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Code stopped from DO_ERR_OUT (in module NcdfUtil/m_do_err_out.F90)
This is an error that was encountered in one of the netCDF I/O modules,
which indicates an error in writing to or reading from a netCDF file!

### GEOS-Chem version
13.3.3
### Log files
- Build log (if [applicable):](url)
- Run logs (if applicable):
- Run script (if applicable):

### Software versions
- cmake-compiler/3.20.1:
- compiler/intel-compiler/2021.3.0:
- mathlib/netcdf/intel/4.7.4:

**Comment by yantosca** [comment]
Thanks for writing @LiHui94.  This can mean that the code tried to write the file into the OutputDir folder of your run directory, but the OutputDir folder either had the wrong permission, or did not exist.  It can also happen if the GEOSChem.SpeciesConc.20190701_0000z.nc4 is read-only.
