### ISSUE TITLE
[QUESTION]Question when compiling GCC13.3.4 with cMake

### ISSUE THREAD

**Issue by LiHui94** [geoschem/geos-chem#1186]
### Ask a question about GEOS-Chem:
when I excute make -j during the compiling, this warning pop up: 
ld: warning: libnetcdf.so.18, needed by /public/software/mathlib/netcdf/intel/4.7.4/lib/libnetcdff.so, may conflict with libnetcdf.so.15

and then when excute ./gcclassic >GC.log, error pop up:
./gcclassic: error while loading shared libraries: libnetcdf.so.15: cannot open shared object file: No such file or directory

I wonder what caused this problem, the version I am using is GCC13.3.4.
Compiler is netcdf-4.1.3

**Comment by yantosca** [comment]
Have you resolved this issue @LiHui94?

**Comment by yantosca** [comment]
Have you also tried adding:
```bash
export FC=ifort
export CC=icc
export CXX=icpc
```
into your ~/.bashrc?  That might tell it to pick up the ifort compiler.

See: http://wiki.seas.harvard.edu/geos-chem/index.php/Specifying_compilers_for_GEOS-Chem#Defining_the_proper_environment_variables

**Comment by LiHui94** [comment]
> Have you resolved this issue @LiHui94?

Yes, thanks for your concern. I added anthor PATH after those setting, and I fixed it already.

**Comment by yantosca** [comment]
Thanks for letting us know. I'll close this issue out.
