### ISSUE TITLE
[QUESTION] Modifying reaction rate for SOAP + OH

### ISSUE THREAD

**Issue by yangning-code** [geoschem/geos-chem#1193]
### Ask a question about GEOS-Chem:
How to modify the rate of SOAP+OH reaction in simplified SOA mechanism in GEOS-Chem.13.3.2?

**Comment by yantosca** [comment]
Thanks for writing @yangning-code.  I think you would modify the SOAP lifetime in `GeosCore/carbon_mod.F90`:

https://github.com/geoschem/geos-chem/blob/9ab6931db5b556eafd0e002e9fd4fdbcbd5fbb44/GeosCore/carbon_mod.F90#L396-L410

This might also be a good question to ask the Aerosols Working Group.  Also tagging @eamarais.
