### ISSUE TITLE
[QUESTION]Specifying hourly O3 output in GEOS-Chem 12.9.3

### ISSUE THREAD

**Issue by Yuan-yuan-2021** [geoschem/geos-chem#1199]
### Ask a question about GEOS-Chem:
Hello!
 Now I’m trying to use GEOS-Chem, Code.12.9.3, merra2_tropchem, I want to output the hourly O3 concentration file individually ,because GEOSChem.SpeciesConc.nc4 file is too large。Can you tell me how to set and get the hourly value of O3?

**Comment by yantosca** [comment]
Thanks for writing @Yuan-yuan-2021.  You can change `SpeciesConc_?ADV?` to `SpeciesConc_O3` to just archive O3 instead of all species.  If you would like to one file per day you can set duration to `00000001 000000`.

**Comment by yantosca** [comment]
Also see our [Guide to GEOS-Chem History diagnostics](http://wiki.seas.harvard.edu/geos-chem/index.php/Guide_to_GEOS-Chem_History_diagnostics).

**Comment by Yuan-yuan-2021** [comment]
> Thanks for writing @Yuan-yuan-2021. You can change `SpeciesConc_?ADV?` to `SpeciesConc_O3` to just archive O3 instead of all species. If you would like to one save file per day you can set duration to `00000001 000000`.

Thank you very much,@yantosca. I get your point.
