### ISSUE TITLE
[tagCH4 RESTART ]

### ISSUE THREAD

**Issue by Rainbow1994** [geoschem/geos-chem#120]
# Ask a question about GEOS-Chem

 I noticed that the online tagCH4 RESTART document only contains spc_CH4 fields. When I tried to conduct global tagCH4 similation, the program cannot find SpeciesRst field of tagCH4 species and thus always interrupted. I'm writing to ask for a entire global TagCH4 RESTART document. Thank you in advance!

**Comment by msulprizio** [comment]
We do not have a sample restart file available for the tagCH4 simulation. You can either [spin up your simulation](http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_restart_files#Overview) to create one or email the [GEOS-Chem Carbon Cycle Working Group ](http://wiki.seas.harvard.edu/geos-chem/index.php/Carbon_Cycle_Working_Group) to see if anyone has a tagCH4 restart file that they can share with you.
