### ISSUE TITLE
Query regarding GEOS-Chem-RRTMG

### ISSUE THREAD

**Issue by kunalbali** [geoschem/geos-chem#1202]
Hi,
I am facing some issues when I am running geos-chem with RRTMG 
The error looks like 
<img width="648" alt="Screen Shot 2022-04-01 at 5 40 36 PM" src="https://user-images.githubusercontent.com/6864691/161360663-090e3d11-8a17-468f-8d14-2b0ded32b9ba.png">

I have modified the HISTORY.rc according to [http://wiki.seas.harvard.edu/geos-chem/index.php/Coupling_GEOS-Chem_with_RRTMG](url)  
<img width="698" alt="Screen Shot 2022-04-01 at 5 39 17 PM" src="https://user-images.githubusercontent.com/6864691/161360626-cbe13fac-62a5-4165-a094-6481242665d4.png">

my input.geos for RRTMG also looks like
<img width="601" alt="Screen Shot 2022-04-01 at 5 42 11 PM" src="https://user-images.githubusercontent.com/6864691/161360697-d6f00005-1732-4e54-b1b6-bee3cdb6e8dd.png">

my geos version and configuration are
<img width="768" alt="Screen Shot 2022-04-01 at 5 43 17 PM" src="https://user-images.githubusercontent.com/6864691/161360733-c714ae5c-2f69-479a-9496-9bbfc5152488.png">

please let me know how could I solve this issue. 

Thanks

**Comment by yantosca** [comment]
Thanks for writing @kunalbali.  The RRTMG simulation in had several issues that were not fixed until GEOS-Chem 13.1.0.  We wouild recommend updating to a more recent version to take advantage of these fixes.

**Comment by yantosca** [comment]
I will close out this issue for now, as the solution is to upgrade to version 13.1.0 or later.

**Comment by kunalbali** [comment]
Hi, 
Thanks for your thoughts on that. However, I am able to run model (12.9.3) with GGRTM. I am able to get the output successfully. 
But still, I am getting some errors such as :

<img width="632" alt="Screen Shot 2022-04-08 at 1 05 55 PM" src="https://user-images.githubusercontent.com/6864691/162530528-780389a6-2fd3-469c-bf7d-1bf702989186.png">

Could you please provide some information on that? What exactly is the meaning of these errors? How can I resolve it? 

Thanks
Kunal
