### ISSUE TITLE
Form of heterogeneous function unstable for large reaction rates

### ISSUE THREAD

**Issue by sdeastham** [geoschem/geos-chem#1205]
The `CloudHet` calculation of heterogeneous reaction rates in the following fails for very large values of `kk`:

https://github.com/geoschem/geos-chem/blob/9ab6931db5b556eafd0e002e9fd4fdbcbd5fbb44/KPP/fullchem/rateLawUtilFuncs.F90#L263

This is referenced in detail in an issue which is currently filed under GCHP: https://github.com/geoschem/GCHP/issues/211. However, the necessary fix would need to take place in the GEOS-Chem code. My suggestion is that `xx` be forced to be greater than or equal to zero.

**Comment by yantosca** [comment]
Thanks for writing @sdeastham.  We can try to get this into either 13.4.0 or 14.0.0, depending on where the benchmarking status is.  Also tagging @msulprizio.

**Comment by msulprizio** [comment]
This will need to go into 14.0.0. Benchmarks for 13.4.0 are complete and will be sent out for approval soon.

**Comment by yantosca** [comment]
Thanks @msulprizio, I'll prepare a PR for 14.0.0.

**Comment by yantosca** [comment]
This has now been merged into the 13.4.0 development stream, so we can close this issue.
