### ISSUE TITLE
[QUESTION]How to get dry deposition velocities in KPP?

### ISSUE THREAD

**Issue by yangxiajie** [geoschem/geos-chem#1210]
I try to add a new reaction rate in GEOS-Chem v12.9.3, which is a function of dry deposition velocities of HNO3. Is there any way to get the dry deposition velocity of HNO3 in `gckpp_HetRates.F90`?  

Thank you for your time.

**Comment by yantosca** [comment]
Thanks for writing @yangxiajie.  You would need to modify the rate law function for that reaction by passing in dry deposition velocity (which I believe is in State_Chm%Depvel) as an argument to the function.

**Comment by yangxiajie** [comment]
Thank you @yantosca .

Now I fix that. 

Thank you for your help again
