### ISSUE TITLE
[QUESTION]IMIN error of ND51b when running the nested simulation (GC12.3.0)

### ISSUE THREAD

**Issue by LiHui94** [geoschem/geos-chem#1214]
### Ask a question about GEOS-Chem:
An error like this occured when runing a nested simulation from 20190701 to 20190801. I don't really understand this error. Isn't the IMIN value of ND51b set automatically? what does this error mean and how to tackle it?

GEOS-CHEM ERROR: Bad ND51b_IMIN value!
STOP at INIT_DIAG51b ("diag51b_mod.f")

Configuration files are attached here.
[Config.zip](https://github.com/geoschem/geos-chem/files/8464584/Config.zip)

**Comment by yantosca** [comment]
Thanks for writing @LiHui94.  IMIN/IMAX, are the min and max longitude indices (in the range of 1...State_Grid%NX) that you want to save out.  Similarly for JMIN/JMAX, LMIN/LMAX.

From your input.geos file you have:
```console
%%% ND51b MENU %%%      :
Turn on ND51b diagnstic : T
LT avg timeseries file  : ./output/ts_13_15.YYYYMMDD.bpch
Output as HDF5?         : F
Tracers to include      : 1 2 4 20 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 64 65 66 501 502 507 511 512
GMT Hour for disk write :  1
Avg Period [LT hours]   :  13  15
IMIN, IMAX of region    :   1  145
JMIN, JMAX of region    :   1  133
LMIN, LMAX of region    :   1  47%%% ND51b MENU %%%      :
Turn on ND51b diagnstic : T
LT avg timeseries file  : ./output/ts_13_15.YYYYMMDD.bpch
Output as HDF5?         : F
Tracers to include      : 1 2 4 20 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 64 65 66 501 502 507 511 512
GMT Hour for disk write :  1
Avg Period [LT hours]   :  13  15
IMIN, IMAX of region    :   1  145
JMIN, JMAX of region    :   1  133
LMIN, LMAX of region    :   1  47
```
It might be that the grid size in longitude for your nested region is less than 145 grid boxes.

**Comment by LiHui94** [comment]
> Thanks for writing @LiHui94. IMIN/IMAX, are the min and max longitude indices (in the range of 1...State_Grid%NX) that you want to save out. Similarly for JMIN/JMAX, LMIN/LMAX.
> 
> From your input.geos file you have:
> 
> ```
> %%% ND51b MENU %%%      :
> Turn on ND51b diagnstic : T
> LT avg timeseries file  : ./output/ts_13_15.YYYYMMDD.bpch
> Output as HDF5?         : F
> Tracers to include      : 1 2 4 20 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 64 65 66 501 502 507 511 512
> GMT Hour for disk write :  1
> Avg Period [LT hours]   :  13  15
> IMIN, IMAX of region    :   1  145
> JMIN, JMAX of region    :   1  133
> LMIN, LMAX of region    :   1  47%%% ND51b MENU %%%      :
> Turn on ND51b diagnstic : T
> LT avg timeseries file  : ./output/ts_13_15.YYYYMMDD.bpch
> Output as HDF5?         : F
> Tracers to include      : 1 2 4 20 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 64 65 66 501 502 507 511 512
> GMT Hour for disk write :  1
> Avg Period [LT hours]   :  13  15
> IMIN, IMAX of region    :   1  145
> JMIN, JMAX of region    :   1  133
> LMIN, LMAX of region    :   1  47
> ```
> 
> It might be that the grid size in longitude for your nested region is less than 145 grid boxes.

The nested simulation I ran is "0.5 x 0.625 AS nested grid" whose grid boxes is 145 in total from longtitude aspect, isn't it?

0.5° x 0.625° AS longitude centers:

  60.000   60.625   61.250   61.875   62.500   63.125   63.750   64.375
  65.000   65.625   66.250   66.875   67.500   68.125   68.750   69.375
  70.000   70.625   71.250   71.875   72.500   73.125   73.750   74.375
  75.000   75.625   76.250   76.875   77.500   78.125   78.750   79.375
  80.000   80.625   81.250   81.875   82.500   83.125   83.750   84.375
  85.000   85.625   86.250   86.875   87.500   88.125   88.750   89.375
  90.000   90.625   91.250   91.875   92.500   93.125   93.750   94.375
  95.000   95.625   96.250   96.875   97.500   98.125   98.750   99.375
 100.000  100.625  101.250  101.875  102.500  103.125  103.750  104.375
 105.000  105.625  106.250  106.875  107.500  108.125  108.750  109.375
 110.000  110.625  111.250  111.875  112.500  113.125  113.750  114.375
 115.000  115.625  116.250  116.875  117.500  118.125  118.750  119.375
 120.000  120.625  121.250  121.875  122.500  123.125  123.750  124.375
 125.000  125.625  126.250  126.875  127.500  128.125  128.750  129.375
 130.000  130.625  131.250  131.875  132.500  133.125  133.750  134.375
 135.000  135.625  136.250  136.875  137.500  138.125  138.750  139.375
 140.000  140.625  141.250  141.875  142.500  143.125  143.750  144.375
 145.000  145.625  146.250  146.875  147.500  148.125  148.750  149.375
 150.000

**Comment by yantosca** [comment]
@LiHui94, i just noticed this in your file:

```console
LMIN, LMAX of region    :   1  47%%% ND51b MENU %%%      :
Turn on ND51b diagnstic : T
```
is that real or did that happen when you cut and pasted into the Github issue?

**Comment by LiHui94** [comment]
> @LiHui94, i just noticed this in your file:
> 
> ```
> LMIN, LMAX of region    :   1  47%%% ND51b MENU %%%      :
> Turn on ND51b diagnstic : T
> ```
> 
> is that real or did that happen when you cut and pasted into the Github issue?

It seems to happen when cut and pasted in to the Github issue, the real version is like this in the input.geos.
![ND51b](https://user-images.githubusercontent.com/99778602/162853319-6b5a07b0-7eae-41f8-8e0e-a3c92acf77c6.png)

**Comment by LiHui94** [comment]
> Thanks for writing @LiHui94. IMIN/IMAX, are the min and max longitude indices (in the range of 1...State_Grid%NX) that you want to save out. Similarly for JMIN/JMAX, LMIN/LMAX.
> 
> From your input.geos file you have:
> 
> ```
> %%% ND51b MENU %%%      :
> Turn on ND51b diagnstic : T
> LT avg timeseries file  : ./output/ts_13_15.YYYYMMDD.bpch
> Output as HDF5?         : F
> Tracers to include      : 1 2 4 20 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 64 65 66 501 502 507 511 512
> GMT Hour for disk write :  1
> Avg Period [LT hours]   :  13  15
> IMIN, IMAX of region    :   1  145
> JMIN, JMAX of region    :   1  133
> LMIN, LMAX of region    :   1  47%%% ND51b MENU %%%      :
> Turn on ND51b diagnstic : T
> LT avg timeseries file  : ./output/ts_13_15.YYYYMMDD.bpch
> Output as HDF5?         : F
> Tracers to include      : 1 2 4 20 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 64 65 66 501 502 507 511 512
> GMT Hour for disk write :  1
> Avg Period [LT hours]   :  13  15
> IMIN, IMAX of region    :   1  145
> JMIN, JMAX of region    :   1  133
> LMIN, LMAX of region    :   1  47
> ```
> 
> It might be that the grid size in longitude for your nested region is less than 145 grid boxes.

Hi, so in your opinoin, what caused this problem? and  how may I fix it?
