### ISSUE TITLE
WETDEP: ERROR using GC12.3.0

### ISSUE THREAD

**Issue by LiHui94** [geoschem/geos-chem#1217]
### Ask a question about GEOS-Chem:
When I ran a simulation today, this error pop up, but I successfully ran it days before.  why I can't run it today?
"WETDEP: ERROR at    1   3  46 for species    7 in area RESUSPENSION in middle levels"
![error message](https://user-images.githubusercontent.com/99778602/163119870-755f82e2-5589-448a-aa40-90ac76e147f3.png)
[Config.zip](https://github.com/geoschem/geos-chem/files/8478927/Config.zip)

**Comment by LiHui94** [comment]
> Thanks for writing @LiHui94. Could you attach your input and log files to this issue?
> 
> Usually this error means that you have a negative value. It could be due to the restart file you are using.
> 
> Also, 12.3.0 is by now almost 3 years old and many issues have been fixed since then. We would recommend that you update to a more recent version if possible.

All the configuration and log files are packed in the Config.zip which I have already uploaded here. Some file form are not supported in Github, so I packed them.
![微信截图_20220414071722](https://user-images.githubusercontent.com/99778602/163285038-c5dddf55-e0e8-4344-8498-afadcac56022.png)

**Comment by LiHui94** [comment]
> Thanks for writing @LiHui94. Could you attach your input and log files to this issue?
> 
> Usually this error means that you have a negative value. It could be due to the restart file you are using.
> 
> Also, 12.3.0 is by now almost 3 years old and many issues have been fixed since then. We would recommend that you update to a more recent version if possible.

The restart file I used did not cause problems in the last successful run, and I also tried the restart file downloaded from http://ftp.as.harvard.edu/gcgrid/data/ExtData/GEOSCHEM_RESTARTS/

**Comment by yantosca** [comment]
I noticed that you have in your log file:
```console
TIMESTEP MENU
---------------
Transport/Convection [sec]  :   900
Chemistry/Emissions  [sec]  :  1800
```
I wonder if these timesteps are causing the issue.  Have you tried with the smaller 600/1200 second timesteps?

**Comment by LiHui94** [comment]
> I noticed that you have in your log file:
> 
> ```
> TIMESTEP MENU
> ---------------
> Transport/Convection [sec]  :   900
> Chemistry/Emissions  [sec]  :  1800
> ```
> 
> I wonder if these timesteps are causing the issue. Have you tried with the smaller 600/1200 second timesteps?

I tried with the smaller 600/1200 second timesteps, did not work. Same problem still existed.
