### ISSUE TITLE
[QUESTION] Downloading older versions of GEOS-Chem

### ISSUE THREAD

**Issue by yangning-code** [geoschem/geos-chem#1218]
### Ask a question about GEOS-Chem:
How to download older versions of GEOS-Chem, for example:GEOS Chem 8.1.4?

**Comment by yantosca** [comment]
Thanks for writing @yangning-code.  You would have to download them via FTP from the 1-year benchmark site on the Harvard FTP server.  Use this link for v8-01-04: https://ftp.as.harvard.edu/gcgrid/geos-chem/1yr_benchmarks/v8-01-04/

NOTE: These versions are no longer supported so the GCST cannot answer questions about them.  Proceed at your own risk.

**Comment by yantosca** [comment]
Also the manual pages for these older versions have been preserved here: https://geoschem.github.io/gcclassic-manpage-archive/

**Comment by yangning-code** [comment]
Thank you.
