### ISSUE TITLE
[HEMCO]emission inventory of PM25 and PM10 

### ISSUE THREAD

**Issue by XR-peking** [geoschem/geos-chem#1221]
In our team, there are emission inventory of PM2.5 and PM10, then should I split and then put them in the HEMCO_Config.rc. Or actually I just need to put inventory of the component of PM2.5, such as BC, OC, CO, SO2, NOx, NH3 ?

**Comment by yantosca** [comment]
PM2.5 and PM10 are not advected species in GEOS-Chem.  Therefore, I believe you would have to add PM2.5 or PM10 components individually (as BC, OC, etc.)

Also tagging @msulprizio

**Comment by XR-peking** [comment]
Thanks so much.

**Comment by yantosca** [comment]
You are welcome @XR-peking!  I'll close this issue now.
