### ISSUE TITLE
Add a new species in RRTMG produce gas and aerosol direct radiative effect

### ISSUE THREAD

**Issue by Lianheng257** [geoschem/geos-chem#1222]
If I want to add a new species in the RRTMG calculation about the radiative effect and have the output like BC. where can I path the species concentrations in RRTMG?  I had seen the  AOD data is read in by fast_jx mod in function CALL RD_AOD, but still not clear about how it coupling to RRTMG.

Thank you !
Yumin

**Comment by yantosca** [comment]
I am tagging @sdeastham and @lizziel who might be able to help you further.

**Comment by sdeastham** [comment]
This question has two answers:

1. If the species is already considered by RRTMG and simply does not have diagnostic output (e.g. H2O) and/or uses offline concentration data (e.g. CO2), then this is straight-forward. You just need to modify the "hooks" in RRTMG - I can describe this if needed as I will soon have a pending PR which does exactly this for H2O and CO2.
2. If the species is _not_ already considered by RRTMG, then this is a much trickier question. I would start by looking at how a similar species - such as ozone for gases, or sulfate for aerosols - is handled elsewhere by GEOS-Chem and RRTMG. However this is beyond anything I've ever tried to do.

**Comment by Lianheng257** [comment]
Thank yantosca and sdeastham for your kind help!

I think this problem is more like adding species not already considered by RRTMG.  I just want to use several separate species to replace the OA (organic aerosol) in RRTMG model.  SO that I can give different AOD data for different species, not just a bulk OA. 

Thanks a lot again!
Yumin

**Comment by Lianheng257** [comment]
I also find the RRTMG calculation process in GEOS-Chem - RRTMG (GCRT) Documentation http://wiki.seas.harvard.edu/geos-chem/images/Guide_to_GCRT_Oct2013.pdf.

![1650444539(1)](https://user-images.githubusercontent.com/75835812/164189550-477758a6-0ab7-48a4-b82f-b99828854291.png)
I think I need to find out where to perform the first three steps? so that I can add in new species in the same way.

**Comment by cbarker211** [comment]
I would also be really interested in adding a new species not already considered by RRTMG (or at least seeing if it is possible and worth the effort/time required). Yumin, did you ever manage to make any progress on this?
