### ISSUE TITLE
[BUG/ISSUE] Incorrect uptake coefficient of N2O5 in GCv12.6.1

### ISSUE THREAD

**Issue by khm0601s** [geoschem/geos-chem#123]
Hi,
I found a mistake in calculating uptake coefficient of N2O5 (gckpp_HetRates.F90)
The equation in 6151 lines:
![image](https://user-images.githubusercontent.com/56626609/68104223-a17d7900-ff1d-11e9-8f74-4efe1806f8ae.png)
0.05 in red box should be 0.005!
If not, uptake coefficient decreases as RH increases.

**Comment by yantosca** [comment]
Thanks for bringing this to our attention.  Do you have any kind of quantification about how much of a change this will add to GEOS-Chem results?  

Although this is a bug fix, because it has the potential to impact our benchmark results, we should probably include this into 12.7.0, so that we can assess its impact with benchmark simulations.

**Comment by yantosca** [comment]
Erin MacDuffie wrote:

> Hi Chris, 
> 
> Did you make this change to the N2O5-sea salt uptake parameterization? It doesn’t look familiar to me. 
> 
> Besides the noted bug on line 6152 in gckpp_HetRate.F90 (if it is in fact a typo), there seems to be a bigger
>  issue in that this calculation is treating ‘relhum' as defined between 0 and 1, when relhum is actually between 0 and 100 (calculated on line 387 in the same file). Doing a quick search through the file, this would impact the NO3 uptake coefficients on sea salt, sulfate, and BC, NO2 uptake on sea salt, and N2O5 uptake on sea salt. 
> 
> Maybe I missed something, but this would make NO3, NO2, and N2O5 uptake too large in the current simulation. Maybe not a large effect, but likely to have some regional impacts. 
> 
> Best,
> Erin
>

**Comment by khm0601s** [comment]
> Thanks for bringing this to our attention. Do you have any kind of quantification about how much of a change this will add to GEOS-Chem results?
> 
> Although this is a bug fix, because it has the potential to impact our benchmark results, we should probably include this into 12.7.0, so that we can assess its impact with benchmark simulations.

I just found this before running model. So, I don't have model result with this bug.

**Comment by yantosca** [comment]
A fix for this bug has been submitted by Chris Holmes as: Pull Request https://github.com/geoschem/geos-chem/pull/124

**Comment by yantosca** [comment]
This update will be merged into 12.7.0 pending successful unit tests.  Our protocol is to put any changes (such as this one) that would affect GC-Classic benchmark results into a "Y" benchmark (e.g. 12.7.0 but not 12.6.2).

**Comment by yantosca** [comment]
Also I made a slight modification (https://github.com/geoschem/geos-chem/commit/6737c9ddbc46eb717c91a91a22903b7a7354d74f) on top of PR https://github.com/geoschem/geos-chem/pull/124 to make sure that all number constants in routine N2O5 get explicitly declared with REAL(fp) precision.

**Comment by yantosca** [comment]
PR https://github.com/geoschem/geos-chem/pull/124 has now been merged into dev/12.7.0, and will "go live" in GEOS-Chem 12.7.0.
