### ISSUE TITLE
[QUESTION]add species in Aerosolmass module in HISTORY.RC

### ISSUE THREAD

**Issue by XR-peking** [geoschem/geos-chem#1232]
### Ask a question about GEOS-Chem:
hello,guys
I want to analysis the specific components of PM2.5, like BC, OC and so on. 
But well I could not find the mass of DUST and SOA (simple SOA mechanism was used). And SALA & SALC was lumped as SAL which could not be separated.
Then I tried to add these species in HISTORY.RC, but there were error which showed these species cannot be found.
![6a90bcf3783c368b0583399b830d5eb](https://user-images.githubusercontent.com/103945599/165489892-5c0176c1-3bc7-419a-88b3-1abf68d04700.png)

**Comment by yantosca** [comment]
Thanks for writing @XR-peking.  Just adding information to HISTORY.rc is not enough, you will need to add new diagnostic arrays and metadata to the `Headers/state_diag_mod.F90` file.  See our instructions here: http://wiki.geos-chem.org/Adding_new_History_diagnostics
