### ISSUE TITLE
[BUG/ISSUE] nested domain winter ozone appears very high values

### ISSUE THREAD

**Issue by clearsky112** [geoschem/geos-chem#1234]
### Description of the problem
global runs: 2x2.5 hourly, benchmark setting 
nested GC runs: 0.5 x 0.625 North America, benchmark setting
We found extremely large surface o3 values in the nested domain for the DJF months, other months seems are reasonable. The o3 values in the global runs look reasonable. 

### Description of troubleshooting performed
tested runs with or without NEI emissions
enlarge or shrink the nested domain 

### GEOS-Chem version
v13.3.4

Hi GC help desk,
   Could you help me diagnose the problem as described above? Maybe I didn't make the correct setting?
Thanks,

**Comment by yantosca** [comment]
Thanks for writing @clearsky112.  We would need to see your input and log files.  Could you attach them here?

Also, we are unable to provide scientific advice as that is not our expertise.  But we can see if something is wrong with your configuration.

**Comment by clearsky112** [comment]
[GC.log](https://github.com/geoschem/geos-chem/files/8626363/GC.log)

**Comment by clearsky112** [comment]
[GC.log](https://github.com/geoschem/geos-chem/files/8626388/GC.log)
[HEMCO_Config.log](https://github.com/geoschem/geos-chem/files/8626389/HEMCO_Config.log)
[HISTORY.log](https://github.com/geoschem/geos-chem/files/8626390/HISTORY.log)
[input.geos.log](https://github.com/geoschem/geos-chem/files/8626391/input.geos.log)

Thanks, I attached them here.

**Comment by clearsky112** [comment]
thank you so much. After the correction, it works.
