### ISSUE TITLE
[FEATURE REQUEST] add MO2 + NO3 reaction

### ISSUE THREAD

**Issue by kelvinhb** [geoschem/geos-chem#1235]
### Request a new GEOS-Chem feature:

Hi team! Daniel and I think we should add a new reaction to KPP: 

MO2 + NO3 = NO2 + CH2O + HO2 : 1.20d-12;

It's well-documented by IUPAC (https://iupac-aeris.ipsl.fr/htdocs/datasheets/pdf/ROO_19_CH3O2_NO3.pdf) and even though it probably won't make much difference in most of the atmosphere, it could play a role in the methyl peroxy budget under some circumstances (like remote areas where the peroxy radical lifetime is long but where long-range NOx transport can still provide an NO3 source). Let me know if there are any questions on this!

-Kelvin

**Comment by yantosca** [comment]
Hi @kelvinhb, thanks for the heads-up!   This could be added to 14.0.0, which is the next version that we'll run benchmarks for.

**Comment by kelvinhb** [comment]
Sounds great!

**Comment by yantosca** [comment]
@kelvinhb, we are working on bringing this into 14.1.0.

**Comment by msulprizio** [comment]
This update has now been merged into the `dev/14.1.0` branch.

**Comment by msulprizio** [comment]
1-month benchmark output documenting the impact of this fix can be found at:

https://gc-dashboard.org/difference?primary_key=diff-gcc-4x5-1Mon-14.1.0-alpha.0-gcc-4x5-1Mon-14.1.0-alpha.1
