### ISSUE TITLE
[BUG/ISSUE] Missing OFFLINE_DUST file on WUSTL

### ISSUE THREAD

**Issue by IshirDutta** [geoschem/geos-chem#1236]
### What institution are you from?
MIT

### Description of the problem
(Effectively) missing OFFLINE_DUST file on WUSTL server ([1990-06-30](http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/1990/06/))

### Description of troubleshooting performed
Downloaded file from [Harvard server](https://ftp.as.harvard.edu/gcgrid/data/ExtData/HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/1990/06/), this is just a heads up to fix the sync!

### GEOS-Chem version
13.3.4, ran dry run script before submitting job 

### Description of modifications
-NA-

**Comment by yantosca** [comment]
I will close out this issue as it is now resolved.
