### ISSUE TITLE
[QUESTION] Modifying the HEMCO restart file frequency

### ISSUE THREAD

**Issue by XR-peking** [geoschem/geos-chem#1237]
### Ask a question about GEOS-Chem:
GC 13.0.0

How can I get HEMCO_restart files each month in simulation?  There were no new HEMCO_restart files automatically created during a four month simulation.

**Comment by yantosca** [comment]
Thanks for writing @XR-peking.  You can change the HEMCO restart frequency at the top of the HEMCO_Config.rc file.  Simply change:
```console
DiagnFreq: End
```
to
```console
DiagnFreq:  Monthly
````
You can also use other frequencies e.g. `Daily`, or specify it as a `YYYYMMDD hhmmss` value (i.e. '00000100 000000` will specify monthly output, `00000001 000000` will specify daily output, etc.

**Comment by XR-peking** [comment]
sorry, but does that only control the output frequency of GEOSChem.Restart file, not for HEMCO_restart file.
Because I have already change it, but there were still no monthly HEMCO_restart files in the end.

**Comment by yantosca** [comment]
The GEOS-Chem restart file frequency is specified in the `HISTORY.rc` file in your run directory.  You can use `00000001 000000` to request monthly data.

**Comment by XR-peking** [comment]
Thanks

**Comment by yantosca** [comment]
Thanks @msulprizio for the heads up, I was unaware.  We can maybe implement that as a new feature later.

**Comment by XR-peking** [comment]
Thanks both of you
