### ISSUE TITLE
[BUG/ISSUE] Not Being Able to Output JVal_NIT and JVal_NITs to plane.log

### ISSUE THREAD

**Issue by laura-hyesung-yang** [geoschem/geos-chem#1240]
### What institution are you from?
Harvard University

### Description of the problem
I wish to output JVal_NIT and JVal_NITs to the plane.log file. However, it seems like JVal_NIT and JVal_NITs are not part of the state_Diag object. Also, they aren't mapped to the FAST_JX cross-section when I checked the GC.log. @viral211

### Description of troubleshooting performed
I modified my planeflight_mod.F90 file like the following:
`   !---------------------------------------------------------------
             ! Photolysis reaction rates
             !---------------------------------------------------------------
             CASE ( 30001:99998 )

               ! Increment reaction count
               R = R + 1

               ! Get the reaction number index from the
               NUM = JPREAC(R) - 30000

               ! Extract this reaction number from the state diag
               ! NOTE: JValues collection must have been requested in HISTORY.rc
               VARI(V) = State_Diag%JVal(I,J,L, NUM )
		
		CASE (31001)
		  VARI(V) = State_Diag%JVal_NIT(I,J,L)
		
		CASE (31002)
		  VARI(V) = State_Diag%JVal_NITs(I,J,L)
`

But received an error stating "‘jval_nit’ at (1) is not a member of the ‘dgnstate’ structure; did you mean ‘jval’?" in GC.log when I ran `make -j' in the build directory. 

### GEOS-Chem version
GC v13.3.4

**Comment by yantosca** [comment]
@viral211, @sdeastham: Question, do we know why NIT and NITs do not map to any FAST_JX species?

**Comment by lizziel** [comment]
I'm not sure why FJX_j2j.dat has blank photolysis species next to the NIT/NITs reactions, but I wonder if it has to do with the scaling in fast_jx_mod.F90. The photolysis rates for NITs and NIT reactions are set to the rates of HNO2 multiplied by a scale factors set in `input.geos`. Perhaps that special handling just never made it into the netcdf diagnostic for J-values? https://github.com/geoschem/geos-chem/blob/0f63ed913861620deb8dbbfd4b0f8c61e87cb3ac/GeosCore/fast_jx_mod.F90#L5325-L5360.

**Comment by viral211** [comment]
@laura-hyesung-yang, I think you can output the NIT and NITs J-values in plane.log by simply including `JVL_` followed by the reaction number from FJX_j2j.dat in the header of planeflight.dat, without modifying planeflight.F90. From FJX_j2j.dat, the reaction numbers for NITs are 130 and 131 and for NIT are 132 and 133.

**Comment by laura-hyesung-yang** [comment]
Thank you everyone for looking into this! @viral211 I'm currently trying this implementation. I added Jval_HNO3, Jval_NIT, and Jval_NITs in my HISTORY.rc file in addition to what you suggested. I will keep you posted on if I get a reasonable result. Do I simply add JVAL_130 and JVAL_131 to get Jval_NITs?
