### ISSUE TITLE
[QUESTION]unit conversion

### ISSUE THREAD

**Issue by XR-peking** [geoschem/geos-chem#1241]
### Ask a question about GEOS-Chem:
If I want to analyze the various compounds of PM2.5, how can I convert the speciesConc_ADV (unit:mol/mol dry air) to the mass concentration (unit: ug/m^3).
I can find the molecular weight of each species, but I can't find the related air parameters to conver mol-1 dry to m3.

**Comment by msulprizio** [comment]
Please see the unit conversion code in unitconv_mod.F90 (linked below) for details. You should be able to get fields needed for conversion from [the StateMet collection](http://wiki.seas.harvard.edu/geos-chem/index.php/History_collections_for_met_fields_and_related_quantities#The_StateMet_collection).

https://github.com/geoschem/geos-chem/blob/0f63ed913861620deb8dbbfd4b0f8c61e87cb3ac/GeosUtil/unitconv_mod.F90#L983-L1000

**Comment by XR-peking** [comment]
Thanks so much

**Comment by yantosca** [comment]
I will close out this issue now.  Thanks again.
