### ISSUE TITLE
[BUG/ISSUE] Incorrect meteorology written to GC-Classic restart

### ISSUE THREAD

**Issue by lizziel** [geoschem/geos-chem#1244]
### What institution are you from?
Harvard University (GCST)

### Description of the problem
The output restart values for TMPU1, SPHU1, PS1_WET, and PS1_DRY are incorrect if written at a time divisible by 3 hours, including midnight. The values saved correspond to 3 hrs previously, e.g. SPHU1 for 21:00 through 23:50 is written for restart file at 00:00. This introduces error if splitting up a GC-Classic into multiple segments, including in the 1-year benchmark simulations of GC-Classic.

### Description of troubleshooting performed
I diagnosed this problem by running one GC-Classic run continuously for 6 hrs and another split into two 3 hr runs. I printed TMPU1, SPHU1, PS1_WET, and PS1_DRY at each timestep. I compared the values from the run logs and saw that the restart values used in the second part of the 2-segment run correspond to the same values used in the first part of the 1-segment run. These values are supposed to change every 3 hours, where TMPU1 becomes TMPU2, etc and a new value for TMPU1 et al. is read in from file.

### GEOS-Chem version
14.0.0-alpha.0. However, this problem has been present for some time.

### Description of modifications
I am looking into a fix now. If we don't need these variables in the restart I will remove them. If we do need them then TMPU2 etc should be saved to TMPU1 if the restart is output at a time divisible by 3 hours. If it is not divisible by 3 hrs then outputting TMPU1 would be okay since it should stay the same in the next timestep when the restart values would be used.

### Related issues
https://github.com/geoschem/geos-chem/issues/1225

**Comment by msulprizio** [comment]
This fix has now been merged into `dev` and will be included in 14.0.0.
