### ISSUE TITLE
[QUESTION]How to install and compile GEOS-Chem 13.4.0

### ISSUE THREAD

**Issue by Moonshadow-bc** [geoschem/geos-chem#1247]
### Ask a question about GEOS-Chem:
I used the new version of Geos-Chem for the first time, and I would like to ask you about the basic installation and compilation.
when I install GEOS-Chem GCClassic13.4.0, I find the dir of GCClassic.13.4.0 differs from version 13.3.4, there is on src directory.
I use this command to download GCClassic13.4.0:  git clone https://github.com/geoschem/geos-chem.git GCClassic.13.4.0
The download was successful. What puzzles me is this, then I executive command to check submodule update: git submodule update —init —recursive
I haven't seen the output in the terminal. Is this normal in the new version?
then I go to the directory: cd run/GCClassic/  and create run directories use: ./createRunDir.sh
when  i compile 
cd run directories
cd build   cmake ../CodeDir/v13.4/GCClassic.13.4.0/  -DRUNDIR=..  
then i Received such a mistake:
![图片](https://user-images.githubusercontent.com/61733216/168023933-5d18e7da-0c67-4851-834a-f7d2123af2ac.png)
![图片](https://user-images.githubusercontent.com/61733216/168023651-12f98f16-975e-4bec-a62f-a71e9359907b.png)
i don't know how to solve.
Thank.

**Comment by yantosca** [comment]
Thanks for writing @Moonshadow-bc.  I suspect it may be an issue with the Intel 15 compiler family.  Have you tried using GNU Fortran (versions 7 and higher should work).

**Comment by Moonshadow-bc** [comment]
> > I use this command to download GCClassic13.4.0: git clone https://github.com/geoschem/geos-chem.git
> 
> Hi @Moonshadow-bc, this is not the correct repository to download for GC-Classic 13. The new repository is https://github.com/geoschem/gcclassic.

Thank. It is my mistake, I solved it by switching to this URL.
