### ISSUE TITLE
[QUESTION] HEMCO_diagnostics

### ISSUE THREAD

**Issue by XR-peking** [geoschem/geos-chem#1253]
### Ask a question about GEOS-Chem:
Dose anyone ever met the issue that the values of species_anthro in HEMCO_diagnostics were not the same with the emission inventory you put in.
And the most weird thing I met was that the diagnostics file of some date was correct.
As I started the simulation in 2009-12-31, then HEMCO_diagnostics.200912310000 was incorrect, but the HEMCO_diagnostics.201001010000 was exactly correct.

**Comment by XR-peking** [comment]
And also should we start the simulation at the first of each month? or is it OK to start any day? And the emission inventory file will be automatically read at the very beginning if the simulation start at the middle of one month?

**Comment by XR-peking** [comment]
It seems like only when the simulation start date is the first day of month can the HEMCO_diagnostic files are correct.

**Comment by msulprizio** [comment]
@XR-peking That's right. When you have `DiagnFreq: Monthly` in HEMCO_Config.rc, you will need to start your simulation on the first of the month. If you want to start on a different day, you can try setting `DiagnFreq` to `Daily` or `End` instead.

**Comment by XR-peking** [comment]
actually, I just start my simulation at 2009-06-30, so the date of HEMCO_diagnostics files created was 2009-06-30, 2009-07-30....2010-01-01. Then I found the emission rates of 2009-06-30 and 2009-07-30 were not correct, but that of 2010-01-01 was correct.
 So I wonder if it's OK to start our simulation any day of one month, not just the first day of one month. And if so, why some HEMCO_diagnostics files created in the simulation which started at 2009-06-30 were incorrect, thanks.

**Comment by XR-peking** [comment]
And today I tried again, it seems right. But I still don't know why.

**Comment by msulprizio** [comment]
Hi @XR-peking. I would recommend you set `Verbose : 3` at the top of HEMCO_Config.rc and examine the HEMCO.log file to answer your questions. That will tell you what data (file, timestamp, etc.) HEMCO is using when starting a simulation on a day other than the first of the month.

**Comment by XR-peking** [comment]
Actually it seems like the reason was that the first HEMCO diagnostic file of 2009-06-30 was the mean value of 06-30 to 07-30. Because the frequency of diagnostic file was set to Monthly, while the start date was 06-30.
