### ISSUE TITLE
[BUG/ISSUE] Errors when trying to run a nested simulation of China using GCClassic 13.3.3

### ISSUE THREAD

**Issue by GaoT0531** [geoschem/geos-chem#1254]
### What institution are you from?
Beijing Normal University

### Description of the problem
I am attempting to run a nested (0.5x0.625) fullchem simulation of China, two regional inventories named 'GTbase' and 'MEIC' were added in HEMCO_Config. But it failed before timestepping.
![1652796653(1)](https://user-images.githubusercontent.com/35188027/168831481-d6e4369e-4b66-493c-97b6-92a823e752a7.png)
(See GC_log.txt below).

### Description of troubleshooting performed
I recompiled GEOS-Chem with the debug option as suggested in #788. But it stoped even ealier and reported a 'Fortran runtime error'.
![1652797441(1)](https://user-images.githubusercontent.com/35188027/168834574-0994c6c5-6141-4e24-a49f-51a06f4d9d83.png)
(See GC_debug_log.txt below).
Besides, I have successfully run a nested 'Aerosols only' simulation and verified the restart and boundary condition files were read in successfully.

### GEOS-Chem version
GCClassic 13.3.3

### Log files
[GC_debug_log.txt](https://github.com/geoschem/geos-chem/files/8709202/GC_debug_log.txt)
[GC_log.txt](https://github.com/geoschem/geos-chem/files/8709204/GC_log.txt)
[HEMCO_Config_rc.txt](https://github.com/geoschem/geos-chem/files/8709205/HEMCO_Config_rc.txt)
[HEMCO_log.txt](https://github.com/geoschem/geos-chem/files/8709206/HEMCO_log.txt)
[HISTORY_rc.txt](https://github.com/geoschem/geos-chem/files/8709207/HISTORY_rc.txt)
[input_geos.txt](https://github.com/geoschem/geos-chem/files/8709208/input_geos.txt)

### Software versions
- CMake version: 3.19.1
- Compilers (Intel or GNU, and version):  GNU
- NetCDF version: 4.7.4

**Comment by GaoT0531** [comment]
Thank you for your prompt attention. 
Maybe I have made a mistake somewhere unknown. Anyway, the error report did not appear again after updating to GC v13.4.0. 


Tong Gao
| |
gtsdnu
|
|
***@***.***
|
---- Replied Message ----
| From | Bob ***@***.***> |
| Date | 5/20/2022 03:36 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [geoschem/geos-chem] [BUG/ISSUE] Errors when trying to run a nested simulation of China using GCClassic 13.3.3 (Issue #1254) |

Thanks for writing @GaoT0531. I'm not sure why it is reading the CMIP6 surface CH4 boundary flux when you have the NOAA GMD flux specified:

    --> GMD_SFC_CH4            :       true     # 1979-2020    --> CMIP6_SFC_CH4          :       false    # 1750-1978

Do you get the same error when you run without the MEIC and GTbase inventories? Maybe there is an error in those that is causing this error.

**Comment by yantosca** [comment]
@GaoT0531, also see this bug: https://github.com/geoschem/HEMCO/issues/150.  Users have reported a bug when there are tabs in the `HEMCO_Config.rc` file.  As a quick fix, use a text editor to strip out all tabs in your copy of `HEMCO_Config.rc` and then try again.  We have a PR to address this (see https://github.com/geoschem/HEMCO/pull/151).

Thank you for your patience.  Earlier this month a lot of us were at the IGC10 meeting.

**Comment by SLF2265127725** [comment]
@GaoT0531 Hello, I encountered this problem, how did you solve it?
![QQ图片20220803164417](https://user-images.githubusercontent.com/58589530/182565294-9c02cd0b-1c7a-4629-a040-ce69adbe4f80.jpg)

**Comment by SLF2265127725** [comment]
This shows that the limit value cannot be modified
![QQ图片20220803171936](https://user-images.githubusercontent.com/58589530/182573033-9e905cfa-c85b-4aac-a56a-efbc0c6d407c.jpg)
