### ISSUE TITLE
[QUESTION] WUSTL data archive is down?

### ISSUE THREAD

**Issue by yangning-code** [geoschem/geos-chem#1256]
### Ask a question about GEOS-Chem:
http://geoschemdata.wustl.edu/：
This website has been unable to enter, there is no way to download GEOS-FP?

**Comment by YanshunLi-washu** [comment]
Hi @yangning-code This could happen from time to time as the university IT team may be maintaining the server now. Please wait for a few days, it will usually recover soon. Thanks

**Comment by LiamBindle** [comment]
I've opened at ticket with our IT. I don't think it should be down right now. Sorry for the inconvenience.

**Comment by yangning-code** [comment]
Thank you
