### ISSUE TITLE
[FEATURE REQUEST] Enable RO2concAfterChem diagnostic

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#1265]
The RO2concAfterChem diagnostic was added for GEOS-GC simulations (i.e. when compiling with `MODEL_GEOS`). However, this diagnostic would be a useful option for all users. Currently, RO2concAfterChem is computed in fullchem_mod.F90:

https://github.com/geoschem/geos-chem/blob/7e51a0674aba638c8322fef493ac9251095e8cf4/GeosCore/fullchem_mod.F90#L2012-L2132

We could simply remove the `#ifdef MODEL_GEOS ` from all lines pertaining to that diagnostic and add that to the ConcAfterChem collection in HISTORY.rc. Another option may be to define RO2 as a family in KPP/fullchem/gckpp.kpp and obtain the concentration of that family in fullchem_mod.F90 (this would reduce the number of lines in that module).

**Comment by yantosca** [comment]
This update failed integration tests with the following error:
```console
t line 2341 of file /n/holyscratch01/jacob_lab/ryantosca/tests/alpha.7/GCC_alpha7/gc_4x5_fullchem_merra2/CodeDir/src/GEOS-Chem/Headers/state_chm_mod.F90
Fortran runtime error: Index '-999' of dimension 1 of array 'state_chm%map_gasspc' below lower bound of 1
```
Usually when an error like this happens, there is a species missing from the species database file. I am looking into a fix.

Tagging @msulprizio @Jourdan-He @SaptSinha

**Comment by yantosca** [comment]
The error is because we do not have an entry for PRO2 in the `run/shared/species_database.yml` file.  Uncommenting this debug print statement in `Headers/state_chm_mod.F90`
```F90
       !---------------------------------------------------------------------
       ! Set up the mapping for GAS SPECIES
       !---------------------------------------------------------------------
       IF ( ThisSpc%Is_Gas ) THEN
          C                       = ThisSpc%GasSpcId
          !###
          !### Uncomment for debug print if Map_GasSpc goes out-of-bounds
          print*, '===> ', ThisSpc%Name, C, ThisSpc%ModelId
          !###
          State_Chm%Map_GasSpc(C) = ThisSpc%ModelId
       ENDIF
```
shows that the PRO2 "dummy" species does not have a GasSpcId value assigned to it:
```console
 ===> XRO2                                    200         236
 ===> POx                                     201         237
 ===> LOx                                     202         238
 ===> PCO                                     203         239
 ===> LCO                                     204         240
 ===> PSO4                                    205         241
 ===> LCH4                                    206         242
 ===> PH2O2                                   207         243
 ===> PRO2                                   -999         244
```
Also another question for @msulprizio: For the molecular weight of PRO2, should we take a weighted average of the MWs of its constituent species?

**Comment by yantosca** [comment]
I wrote a python script to get the average MW for RO2.  @msulprizio, let me know if this looks OK.
```python
#!/usr/bin/env python

from gcpy.util import read_config_file

# List oF RO2 species
ro2_spc_names = [ 
    'A3O2','ATO2','B3O2','BRO2','ETO2','HO2','LIMO2','MO2',
    'PIO2','PO2','PRN1','R4N1','R4O2','TRO2','XRO2','IHOO1',
    'IHOO4','ICHOO','IHPOO1','IHPOO2','IHPOO3','IEPOXAOO',
    'IEPOXBOO','C4HVP1','C4HVP2','HPALD1OO','HPALD2OO',
    'ISOPNOO1','ISOPNOO2','INO2D','INO2B','IDHNBOO','IDHNDOO1',
    'IDHNDOO2','IHPNBOO','IHPNDOO','ICNOO','IDNOO'
]

# Read GEOS-Chem species database
config = read_config_file('species_database.yml')

# Take average MW for RO2
mw = 0.0
for v in ro2_spc_names:
    mw += config[v]['MW_g']
mw = mw / float(len(ro2_spc_names))
print(f"RO2 average MW is: {mw:10.2f}")
```
I got this output:
```console
Using configuration file species_database.yml
RO2 average MW is:     146.98
```
which seems reasonable to me. I'll push this to the `feature/ro2-diag` branch.

**Comment by yantosca** [comment]
Also we will have to add PRO2 to the restart file so as to avoid this issue (caused by time cycle `EFYO` when reading the restart file.
```console
HEMCO: Opening /n/holyscratch01/external_repos/GEOS-CHEM/gcgrid/data/ExtData/HEMCO/OFFLINE_LIGHTNING/v2020-03/MERRA2/2019/FLASH_CTH_MERRA2_0.5x0.625_2019_07.nc4
HEMCO: Opening ./GEOSChem.Restart.20190701_0000z.nc4
 
HEMCO ERROR: Cannot find field SPC_PRO2. Please check variable name in the config. file
 
HEMCO ERROR: Error encountered in routine HCOIO_Read!
 
HEMCO ERROR: Error in HCOIO_DATAREAD called from HEMCO ReadList_Fill: SPC_PRO2
 --> LOCATION: ReadList_Fill (HCO_ReadList_Mod.F90)
 
HEMCO ERROR: Error in called ReadList_Fill (7) from HEMCO ReadList_Read
 --> LOCATION: ReadList_Read (HCO_ReadList_Mod.F90)
 Error in ReadList_Read called from hco_run
```

**Comment by msulprizio** [comment]
It's not clear that this diagnostic is a priority. I will close out this issue for now.
