### ISSUE TITLE
[QUESTION]Missing functions after adding new species in KPP

### ISSUE THREAD

**Issue by ymfu2021** [geoschem/geos-chem#1266]
### Ask a question about GEOS-Chem:
I'm using KPP-2.2.4_gc to do some simulation. I have just added some new species in my '.eqn' and 'gckpp.kpp' files, deleting nothing from original files. It shows" KPP has succesfully created the model "gckpp" ". However, I found the so many functions missed in 'gckpp_Rates.F90', which had been declared in 'gckpp.kpp' with no modification. That also cause my whole GEOS-Chem model failed. I wonder how this problem comes, and how can i fix it.

**Comment by yantosca** [comment]
Thanks for writing @ymfu2021.  We would recommend to use a newer version than KPP 2.2.4_gc.

NOTE: We are in the process of migrating the KPP repository from https://github.com/geoschem/KPP to https://github.com/KineticPreProcesor/KPP.  GEOS-Chem 14.0.0 (to be released sometime after IGC10, once benchmarks have cleared) will be compatible with the newest version of KPP, which is currently 2.5.0.

**Comment by ymfu2021** [comment]
Get it. Thanks for your help@yantosca.
