### ISSUE TITLE
[DISCUSSION]Unexpected higher value of reaction rates (kI) during the heterogeneous cloud chemistry

### ISSUE THREAD

**Issue by SadiaToma** [geoschem/geos-chem#1267]
In my simulation, the algorithm used for calculating the in-cloud to the out-of-cloud ratio of mass (xx) in the ‘rateLawUtilFuncs.F90’ script is producing +1 and -1 values under some circumstances, which ultimately crashes the simulation. Although the problem is resolved by flushing the negative values of xx to zero (as suggested in a previous issue: https://github.com/geoschem/GCHP/issues/211), +1 value of xx is a problem too. It means that the heterogeneous chemistry rate kHet will end up being kI/2 rather than just kI, so the rate is halved incorrectly. To resolve the problem, we tried to trace back. 
[rateLawUtilFuncs.F90.pdf](https://github.com/geoschem/geos-chem/files/8787320/rateLawUtilFuncs.F90.pdf)

In our simulation, the grid-average cloud fraction (H%CldFr) was very small [causing a high value of grid-average cloud condensate surface area density (area)], but not small enough to turn the ‘area’ zero based on the SafeDiv function. This high value of ‘area’ is ultimately causing a high value of reaction rates (kI) as well as those problematic xx values. From our analysis, we also found that bounding the value of kI to 3.6e4 possibly would not cause this kind of issue.

So, would be happy to discuss more on this topic.

**Comment by yantosca** [comment]
Thanks for writing @SadiaToma.  I suspect we might have to put a trap in there as you have described.  We can add this shortly after IGC10.

**Comment by msulprizio** [comment]
Is there an update on this? Were we able to get confirmation on the fix and create a PR?

**Comment by yantosca** [comment]
Have not heard an update

**Comment by msulprizio** [comment]
@SadiaToma Is this issue resolved? Do we still need to implement a fix? If so, could you submit a pull request?

**Comment by yantosca** [comment]
Closing out this issue
