### ISSUE TITLE
[BUG/ISSUE] Issue in nested simulations. GC v12.9.3

### ISSUE THREAD

**Issue by gopikrishnangs44** [geoschem/geos-chem#1269]
I am trying to do a nested grid simulation in GEOS CHEM v12.9.3.

I am running a global 4x5 geosfp standard simulation to save the BC files.

4x5 simulations works quiet well for me and I am getting outputs as well.

Unfortunately, while turning on 

 Nested grid simulation? : T
 Buffer zone (N S E W ) : 40  02  60  105

I am getting core dumped issue. Attaching the log file here.

[test_wo_BC.txt](https://github.com/geoschem/geos-chem/files/8811298/test_wo_BC.txt)

Requesting help from the team.

Regards,
Gopikrishnan

Software versions using spack
spack load gcc@8.3.0
spack load openmpi
spack load hdf5
spack load netcdf-c
spack load netcdf-fortran
spack load esmf

**Comment by yantosca** [comment]
Thanks for writing @gopikrishnangs44.  For the 4x5 simulation, you should not specify:
```console
Nested grid simulation? : T
Buffer zone (N S E W ) : 40 02 60 105
```
This should only be turned on for the nested-grid resolution at 0.25 x 0.3125 resolution with GEOS-FP.

**Comment by gopikrishnangs44** [comment]
Dear @yantosca,

Thank you.

I made the boundary conditions through a standard geosfp 4x5 simulation.

CopyRunDirs.input 
geosfp   4x5         -      standard         2016070100   2016070200     -

and nested rundirs using:
geosfp   025x03125   as     tropchem         2016070100   2016070200     -

Can I run a tropchem simulation using BC from a standard geosfp 4x5 run? 
Or should I need to create BC using a 4x5 tropchem run for a nested run?

**Comment by SLF2265127725** [comment]
@gopikrishnangs44 ,Hello, I had the same problem when I set up the simulated Asia region, how can I fix it
![10](https://user-images.githubusercontent.com/58589530/182099916-17259b04-b118-4645-b6b4-d4e142601952.jpg)

**Comment by gopikrishnangs44** [comment]
@SLF2265127725 I DIDN'T FIXED IT YET.

**Comment by SLF2265127725** [comment]
@gopikrishnangs44 I tried it, and I found that as long as 0.5*0.625 is selected, an error will be reported. And I looked through the official website, he said that the amount of data is too large, and the array needs to be improved, but I don't know how to change it.

![微信图片_20220801171657](https://user-images.githubusercontent.com/58589530/182116044-2efc7fa9-7422-406f-9e58-db962b75abe3.jpg)
http://wiki.seas.harvard.edu/geos-chem/index.php/Segmentation_faults#Invalid_memory_access

**Comment by yantosca** [comment]
Thanks for writing @SLF2265127725.  Have you set the `OMP_STACKSIZE` limit to `unlimited` in your login environment?  See https://geos-chem.readthedocs.io/en/latest/gcc-guide/01-startup/login-env-parallel.html
