### ISSUE TITLE
[QUESTION]Offline aerosol data after 2019 cannot be found in the WashU website

### ISSUE THREAD

**Issue by xiaoyu-ss** [geoschem/geos-chem#1276]
### Ask a question about GEOS-Chem:
I'd like to calculate the aerosol AOD in 2020 by the GEOS-Chem aerosol module. The version I use is 13.4.1. I found that I need the offline aerosol data in 2020 and also found this set-up in the HEMCO_Config.rc file (I copy the part of offline_dust from the file): 

> (((OFFLINE_DUST
(((.not.DustDead.or.DustGinoux
0 EMIS_DST1 $ROOT/OFFLINE_DUST/v2021-08/0.5x0.625/$YYYY/$MM/dust_emissions_05.$Y
YYY$MM$DD.nc EMIS_DST1 1980-2021/1-12/1-31/* C xy kg/m2/s DST1 - 3 2
0 EMIS_DST2 $ROOT/OFFLINE_DUST/v2021-08/0.5x0.625/$YYYY/$MM/dust_emissions_05.$Y
YYY$MM$DD.nc EMIS_DST2 1980-2021/1-12/1-31/* C xy kg/m2/s DST2 - 3 2
0 EMIS_DST3 $ROOT/OFFLINE_DUST/v2021-08/0.5x0.625/$YYYY/$MM/dust_emissions_05.$Y
YYY$MM$DD.nc EMIS_DST3 1980-2021/1-12/1-31/* C xy kg/m2/s DST3 - 3 2
0 EMIS_DST4 $ROOT/OFFLINE_DUST/v2021-08/0.5x0.625/$YYYY/$MM/dust_emissions_05.$Y
YYY$MM$DD.nc EMIS_DST4 1980-2021/1-12/1-31/* C xy kg/m2/s DST4 - 3 2
))).not.DustDead.or.DustGinoux
)))OFFLINE_DUST

If I understand correctly, the set-up here is shown that the data of offline_dust is updated to 2021. But I can only find the data till 2019 from the WashU website (e.g. [http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/].) Has the data of offline aerosol not been updated yet? If I want to calculate the AOD in 2020, does that mean I need to use the closest year to 2020, the offline-aerosol data in 2019?

**Comment by msulprizio** [comment]
@YanshunLi-washu is in the process of updating these emissions to present, but those will not be available for another few weeks. In the meantime, if you want to run a simulation beyond 2019 then we recommend turning the online emissions (i.e. the `DustDead` extension`) on instead of using `OFFLINE_DUST`.

**Comment by xiaoyu-ss** [comment]
Great to hear that! For now, I am using the online emission. I will use the offline dust in the future.

**Comment by yantosca** [comment]
Going to close out this issue.
