### ISSUE TITLE
[BUG/ISSUE] the Compute_DeltaYmdHms_For_End work incorrectly

### ISSUE THREAD

**Issue by hgrhgy** [geoschem/geos-chem#1278]
### Description of the problem

>GEOS-Chem ERROR: No diagnostic output will be created for collection: "Restart"! Make sure that the length of the simulation as specified in "input.geos" (check the start and end times) is not shorter than the frequency setting in HISTORY.rc!

### Description of troubleshooting performed
sim start: 20170131 180000
sim end : 20170201 000000
Compute_DeltaYmdHms_For_End  return delta  1 month and 6 hours.

``` fortran
  SUBROUTINE Compute_DeltaYmdHms_For_End( yyyymmdd,     hhmmss,              &
                                          yyyymmdd_end, hhmmss_end,          &
                                          deltaYmd,     deltaHms            )
   ....
    ! Compute intervals
    dYear    = Year1   - Year0
    dMonth   = Month1  - Month0
    dDay     = Day1    - Day0
    dHour    = Hour1   - Hour0
    dMinute  = Minute1 - Minute0
    dSecond  = Second1 - Second0

    ! Adjust intervals (NOTE: Might not be as robust, more testing needed)
    IF ( dSecond < 0 ) THEN
       dSecond = dSecond + 60
       dMinute = MAX( dMinute - 1, 0 )
    ENDIF

    IF ( dMinute < 0 ) THEN
       dMinute = dMinute + 60
       dHour   = MAX( dHour - 1, 0 )
    ENDIF

    IF ( dHour < 0 ) THEN
       dHour   = dHour + 24
       dDay    = MAX( dDay - 1, 0 ) ! MAX function here will set the dDay zero and  block the modication of dMonth
    ENDIF

    IF ( dDay < 0 ) THEN
       dDay    = dDay + Day0
       dMonth  = MAX( dMonth - 1, 0 )  
    ENDIF

    IF ( dMonth < 0 ) THEN
       dMonth  = dMonth + 12
       dYear   = MAX( dYear - 1, 0 )
    ENDIF

    IF ( month1 < month0 ) THEN
       dYear = MAX( dyear - 1, 0 )
    ENDIF
    ....
  END SUBROUTINE Compute_DeltaYmdHms_For_End
```

### GEOS-Chem version
13.4.1

**Comment by hgrhgy** [comment]
I found that there were problems with CO2 simulation in versions 13.4.0 and 13.4.1.  The simulation results are completely different from those in 13.3.4.

**Comment by yantosca** [comment]
Thanks for your patience @hgrhgy.  Earlier this month we were at the IGC10 meeting.  I will take a look at this as soon as we can and we can maybe get a fix into an upcoming version (14.0.1 or 14.1.0).

**Comment by hgrhgy** [comment]
Thank you for replying. When the `Restart.frequency` and `Restart.duration` are set to `End`,  the problem may occur. 
I have try to set `Restart.frequency` and `Restart.duration` in `YYYYMMDD hhmmss` form to fix this problem. And It works.

**Comment by SLF2265127725** [comment]
> Thank you for replying. When the `Restart.frequency` and `Restart.duration` are set to `End`, the problem may occur. I have try to set `Restart.frequency` and `Restart.duration` in `YYYYMMDD hhmmss` form to fix this problem. And It works.

Hello, how to fix the problem in detail.

**Comment by hgrhgy** [comment]
@SLF2265127725 if you want to generate restart file in short time cycles, set Restart.frequency and Restart.duration in `YYYYMMDD hhmmss` format. For example, set `00000000 060000` for restart file in 6 hours.

**Comment by SLF2265127725** [comment]
@hgrhgy Thanks for your help, I am using GEOS-Chem13.3.4. It works well

**Comment by yantosca** [comment]
Closing out this issue
