### ISSUE TITLE
[BUG/ISSUE] 403 forbidden when downloading C720 derived wind fields

### ISSUE THREAD

**Issue by kilicomu** [geoschem/geos-chem#1280]
### What institution are you from?
Wolfson Atmospheric Chemistry Laboratories

### Description of the problem
When trying to download the `GEOS_C720` derived wind fields (e.g. http://geoschemdata.wustl.edu/ExtData/GEOS_C720/GEOS_FP_DerivedWind/Y2021/M05/D01/) I receive an HTTP 403 forbidden code.

### Description of troubleshooting performed
Tried with `wget`, with `wget` ignoring `robots.txt`, and in several browsers - all receive the same HTTP code. I can download the C720 `GEOS_FP_Native` fields just fine!

### GEOS-Chem version
N/A

### Description of modifications
N/A

### Log files
- Build log (if applicable): N/A
- Run logs (if applicable): N/A
- Run script (if applicable): N/A

### Software versions
- CMake version: N/A
- Compilers (Intel or GNU, and version): N/A
- NetCDF version: N/A

**Comment by LiamBindle** [comment]
Oops, thanks for point this out. Should be fixed now.

Can you try again?
