### ISSUE TITLE
[BUG/ISSUE] Emissions ignored if true/false toggle in HEMCO_Config.rc contains tabs

### ISSUE THREAD

**Issue by lizziel** [geoschem/geos-chem#1282]
This is a bug report about a silent bug affecting GEOS-Chem. I recently discovered that using tabs rather than spaces in the extension switch section of the HEMCO config file will cause HEMCO to interpret the emissions bracket as false. All emissions in that emissions bracket in `HEMCO_Config.rc` will then be skipped despite being set to true in the emissions switches section.

A separate bug report about this is on HEMCO which is where the fix will be.  https://github.com/geoschem/HEMCO/issues/150

**Comment by yantosca** [comment]
This issue should be fixed by PR https://github.com/geoschem/HEMCO/pull/151
