### ISSUE TITLE
[FEATURE REQUEST] Updated Soil NOx emission scheme

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#1288]
@ywang37 wrote:

> I’m Yi Wang, and I was a postdoc in Prof. Jun Wang’s group. You maybe interested in our work about revised soil emissions in GEOS-Chem (use new temperature function and use soil temperature directly); it is my pleasure to share the code. I have made all the code  public in my GitHub. And you can use git command to download them and track my modification.
>
> (1) Soil temperature is not in the standard GEOS-Chem archive, you need to  extract soil temperature (TSOIL1, the layer that is closest to surface) from original MERRA-2 or GEOS-FP data. Although I extracted TSOIL1, TSOIL2, …, and TSOIL6, only TOSIL1 is used by GEOS-Chem. 
>
> MERRA-2: https://github.com/ywang37/MERRA2.git
> GEOS-FP: https://github.com/ywang37/GEOS-FP.git
>
>You will find `python/main_process_month.py`, and can run it to extract data.
> main_process_month.py calls some python functions from mylib, all mylib code is at https://github.com/ywang37/pylib.git
> 
> (2) GEOS-Chem code
> https://github.com/ywang37/GEOS-Chem_soil_NOx_12.7.2.git
>
> for run directory, you need to modify HEMCO_Config.rc. Add
> 
> `* TSOIL1    $METDIR/$YYYY/$MM/$MET.$YYYY$MM$DD.A1.$RES.$NC     TSOIL1   1980-2019/1-12/1-31/*/+30minute RFY xy  1  * -  1 1`
> 
> in the `# --- A1 fields --- `section.
> 
> Please feel free to contact me if you have questions about the code.

**Comment by yantosca** [comment]
### Table 1. Soil NOx emissions scheme settings

Name | Soil NOx emissions scheme
-- | --
Control | Soil temperature is derived from 2-m air temperature through linear and empirical relationships, and the old exponential function is used.
STold | MERRA soil temperature is used, and the old T function is kept.
STnew | MERRA soil temperature is used, and the new T function is used.

![Picture1](https://user-images.githubusercontent.com/5880296/191574175-a1a1e73a-a211-418c-b38f-28c83762efec.png)

Figure 1. Summer (JJA) averages in 2005-2019 of 2-m air temperature (a), soil temperature (b), the difference (c) between soil temperature and 2-m air temperature, soil NOx emissions from the Control run (d), the STold run (e), the STnew run (f). Also shown are the corresponding differences/relative differences between STold and Control, between STnew and Control, and between STnew and STold are shown in (g)/(j), (h)/(k), and (i)/(l), respectively

**Comment by yantosca** [comment]
@ywang37: would you be able to create a Github pull request so that we can get the code?  Also, do you have data files already prepared?

**Comment by msulprizio** [comment]
This update has been shelved for the time being based on discussion at the GCSC meeting on September 21, 2022. There were concerns about:

- Accuracy of MERRA-2 soil temperature vs surface air temperature
- Need to process the entire MERRA-2 and GEOS-FP records to extract the additional soil fields
- Need to regenerate offline soil NOx emissions for the entire MERRA-2 and GEOS-FP records
- Validation of this scheme is currently only for US, where existing soil NOx algorithm has been validated globally

**Comment by ywang37** [comment]
I have extracted MERRA-2 TOSIL1 (soil temperature) for July 2022. 
These data is available at
https://www.dropbox.com/scl/fi/eot1etlarlivmwdaeznpd/TSOIL.zip?rlkey=dv1pnn7toqod3f48x228a7vre&dl=0

MERRA2.20220701.A1.05x0625.nc4 is same as the official counterpart, but TOSIL1  is included.

sub.MERRA2.20220701.A1.05x0625.nc4 only contains TSOIL.

**Comment by yantosca** [comment]
The source code for this update is now in GEOS-Chem 14.5.0.  However we still need to generate the archive of TSOIL1 met fields before this feature can be used.  We can close out this issue as the various PRs have been merged.
