### ISSUE TITLE
[QUESTION] How many IVOC's are allocated to each bin of VBS?

### ISSUE THREAD

**Issue by yangning-code** [geoschem/geos-chem#1290]
### Ask a question about GEOS-Chem:
Under the VBS mechanism, NAP is used as a substitute for IVOC, that is, IVOC=66*NAP. How many IVOCs are allocated to each bin of VBS? Where can this distribution ratio be found in the GEOS-Chem code?

**Comment by yantosca** [comment]
Thanks for writing @yangning-code.  I am going to tag @jaredbrewer, who knows more about the particulars of the VBS SOA scheme than I do.

**Comment by jaredbrewer** [comment]
> Thanks for writing @yangning-code. I am going to tag @jaredbrewer, who knows more about the particulars of the VBS SOA scheme than I do.

You've got the wrong person - not sure who you were looking for.

**Comment by yantosca** [comment]
Also tagging the co-chairs of the Aerosols WG: @theloniuspunk @beckyalexander @wporter.

**Comment by theloniuspunk** [comment]
Do you mean "how many distinct IVOC species are lumped into a give VBS bin?" It's an unknown amount because the number is large, and we generally can't measure every species.

**Comment by yantosca** [comment]
Closing out this issue
