### ISSUE TITLE
[QUESTION] NEI-2011 OC emissions as POG1 and POG2 in ComplexSOA_SVPOA simulations?

### ISSUE THREAD

**Issue by chfite** [geoschem/geos-chem#1291]
I am using v12.6.0 and the ComplexSOA_SVPOA mechanism with NEI-2011 anthropogenic emissions over the U.S. I noticed that in HEMCO_Config, OC is emitted through NEI as OCPO and OCPI. It is my understanding that since OCPO and OCPI are not species in ComplexSOA_SVPOA simulations, these OC emissions would be ignored by HEMCO, correct? Does this mean that OC in NEI needs to be emitted via POG1 and POG2, similar to #599 suggested with fire emissions? Or does HEMCO have a way of accommodating for this on its own?

**Comment by chfite** [comment]
I'll add that CEDS appears to already list OC emissions for OCPO/OCPI and POG1 and POG2, but this is not the case for NEI

**Comment by msulprizio** [comment]
Hi @chfite. Yes, entries for POG1 and POG2 should be added for NEI emissions as is done for other inventories. The omission of those lines was an oversight. This only impacts ComplexSOA_SVPOA simulations.

**Comment by chfite** [comment]
@msulprizio Thanks for your reply. To add to this, it seems CEDS emits OCPO, OCPI, POG1, and POG2 (of course of which OCPO and OCPI would be ignored, as you said). Where they emit POG1&2 in HEMCO_Config they first scale OC to OCPO (factor of 0.5), and then apply the POG scaling factors. So does this mean that for NEI (or really any inventory that emits OC) should one first scale to OCPO before applying the POG scale factors or apply POG scale factors directly to OC? Represented by:

POG1 = NEI_OC * OC2OCPO * POGSCAL * SV2POG1
POG2 = NEI_OC * OC2OCPO * POGSCAL * SV2POG2


**OR**

POG1 = NEI_OC * POGSCAL * SV2POG1
POG2 = NEI_OC * POGSCAL * SV2POG2

where NEI_OC represents OC emissions from any inventory and the scale factors are as follows:

72 OC2OCPI  0.5  - - - xy unitless 1
73 OC2OCPO  0.5  - - - xy unitless 1
74 POGSCAL  1.27 - - - xy unitless 1
76 SV2POG1  0.49 - - - xy unitless 1
77 SV2POG2  0.51 - - - xy unitless 1

267 NEI11_OC2OCPI     0.5        - -               - xy 1 1
268 NEI11_OC2OCPO     0.5      - -               - xy 1 1

From what I have seen, APEI and EDGAR go with the latter approach, where they do emit POG1&2, as they should, but by NOT applying the OC2OCPO scale factor. CEDS **_DOES_** apply that scale factor, which would halve the amounts going into POG1 and POG2. 

I did another check, and the inventories that should emit OC but do NOT emit it as POG1 and POG2 _at all_ are NEI, NEI-Ship, DICE, EDGAR-Trash, CEDS-Ship, RCP emissions, and for fire emissions: QFED and GFAS. I'm just noting this down for the record for anyone that may need to account for this. Like you said, this would only affect complexSOA-SVPOA simulations.

**Comment by chfite** [comment]
@msulprizio I just saw in (https://github.com/geoschem/HEMCO/issues/54) that someone has asked a similar question about why OC is scaled by OC2OCPO in CEDS entries, and not for other OC emission inventories. 

It sounds like you suggest that one should remove the OC2OCPO scale factors in CEDS entries, therefore only applying the POGSCAL and either SV2POG1/SV2POG2 scaling factors to total OC emissions?

You also mentioned that the OC2OCPO scale factor for CEDS entries were likely being removed in v13.0, but that doesn't seem to the case yet from what I've seen. Is that still the plan or am I maybe looking in the wrong place?

**Comment by msulprizio** [comment]
I will close this issue as it is resolved by PR https://github.com/geoschem/geos-chem/pull/1299 which will be included in 14.1.0.
