### ISSUE TITLE
[QUESTION] How to assess Tropospheric Ozone concentration changing  by CH4

### ISSUE THREAD

**Issue by tjansakoo** [geoschem/geos-chem#1294]
Hi, currently I'm interested to assess the impact of CH4 emission on ground surface ozone concentration.
There is a possible way to assess it via GEOS-chem as I know GEOS-Chem assumes that CH4 emission on the surface layer is not changing right?

Thank you in advance.

**Comment by msulprizio** [comment]
The full-chemistry simulation in GEOS-Chem uses monthly mean surface methane distributions from NOAA GMD flask observations. These are read in via HEMCO:

https://github.com/geoschem/geos-chem/blob/7e51a0674aba638c8322fef493ac9251095e8cf4/run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem#L3413-L3418

See this wiki page for more details on those data: http://wiki.seas.harvard.edu/geos-chem/index.php/Tropospheric_chemistry_mechanism#CH4_concentrations.

We've had a few users inquire in the past about using CH4 emissions from the CH4 simulation in the full-chemistry simulation, but I'm not sure if anyone has attempted that. It would involve manually bringing in entries from [HEMCO_Config.rc for the CH4 simulation](https://github.com/geoschem/geos-chem/blob/main/run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.CH4) into the HEMCO_Config.rc for your full-chemistry simulation. One thing to keep in mind is that the CH4 simulation uses archived OH concentrations from v5 of GEOS-Chem.

**Comment by tjansakoo** [comment]
Thank you so much I will check the HEMCO_Config.rc

**Comment by yantosca** [comment]
Closing out this issue for now.
