### ISSUE TITLE
[QUESTION] Could not get species information

### ISSUE THREAD

**Issue by ymfu2021** [geoschem/geos-chem#1295]
### Ask a question about GEOS-Chem:
I have been using GEOS-Chem updated by Shah(2021), adding new species through KPP. I could't run the GC model successfully. It showed the error "Please add the information to the CASE statement in module Headers/species_database_mod.F90! ", which I already added related codes about my new species in that module as well as in file "input.geos". I don't know why GC could not get species info. 
 
Thanks in advance.

**Comment by lizziel** [comment]
Hi @ymfu2021, could you provide your updated code and your run log files? You can add `.txt` to the filename extensions and then drag and drop them into the GitHub comment box. Seeing these files will help us figure what the problem is.

**Comment by ymfu2021** [comment]
I have uploaded species_database_mod.F90 and my log file. My modification was about at line 4747, adding 'HGBRIO',  'HGBRI' as well as in 'SELECT CASE 'below. 
These two files may be useful. Again, thanks for your help.

[geos.log](https://github.com/geoschem/geos-chem/files/9010900/geos.log)
[species_database_mod.txt](https://github.com/geoschem/geos-chem/files/9010906/species_database_mod.txt)

**Comment by yantosca** [comment]
Thanks for the files @ymfu2021.  It looks like your `species_database.yml` file is missing an entry for HgBrIO.   I think if you add that and run again it should work.

**Comment by ymfu2021** [comment]
Hi @Contributor
[yantosca](https://github.com/yantosca). Where should the entry be in this file ? or in other files?  I didn't see any entry for other species.  Maybe I miss them. Would you please give me some hints

**Comment by yantosca** [comment]
Sorry for the late reply.  The `species_database.yml` file is in your run directory.  It is just a text file in [YAML](https://yaml.org) markup format. You can edit it with any text editor.
