### ISSUE TITLE
[BUG/ISSUE] GFAS data cannot be downloaded from washu server

### ISSUE THREAD

**Issue by jinlx** [geoschem/geos-chem#1296]
Hi there, 

I am trying to download GFAS 2021 data after September from washu server (http://geoschemdata.wustl.edu/ExtData/HEMCO/GFAS/v2018-09/2021/). However, it seems that the data is not open to public and cannot be downloaded. I was wondering if it's easy to fix it.

Cheers,
Lixu

**Comment by msulprizio** [comment]
@YanshunLi-washu @LiamBindle Could you please fix the GFAS file permissions at WashU? Also, we have the data up through January 2022 at Harvard but December 2021 and January 2022 are missing at WashU.

**Comment by YanshunLi-washu** [comment]
Hi @msulprizio Thanks for letting us know. I tried to fix it but I have no authorization for GFAS_202109.nc, GFAS_202110.nc and GFAS_202111.nc. Hey @LiamBindle could you kindly help to fix it and also the missing files for Dec 2021 and Jan 2022? I saw that you are the owner of these files.

**Comment by LiamBindle** [comment]
Done. Thanks for reporting this.
