### ISSUE TITLE
[QUESTION] Missing Offline Lightning Emissions GEOS-FP for 2020

### ISSUE THREAD

**Issue by tessac2** [geoschem/geos-chem#1297]
### What institution are you from?
University of Illinois Urbana Champaign

### Description of the problem
Hello! I am trying to run GEOS-Chem (GEOS-FP, v13.1.1) for 2020 but I noticed the offline lightning emissions are only available until 2019. However, in the HEMCO_Config file, it says they should be available until 2021 (says 1980-2021). I noticed in Issue #1046 from December 2021 that GEOS-FP lightning emissions are delayed for 2020 to 2021 because "a large amount of global native I3 met fields needed to be reprocessed for 2020 and 2021 as they were corrupt, and that only recently finished."  (@ltmurray)  I was wondering if this data will be available soon, or if it is still being reprocessed? 

In the case that 2020 GEOS-FP lightning emissions are not available, I was hoping to use 2019 emissions instead for 2020. I tried modifying the script so that the YYYY read 2019 and the script says 1980-2019, in an effort to try to use 2019 Lightning emissions for 2020, however I was not sure if this is the correct way to modify the HEMCO_Config? 

LightNOx
* FLASH_DENS $ROOT/OFFLINE_LIGHTNING/v2020-11/$MET/$2019/FLASH_CTH_$MET_0.25x0.3125_$**2019**_$MM.nc4  LDENS 1980-**2019**/1-12/1-31/0-23/+90minute RFY3 xy  1  * -  1 1
* CONV_DEPTH $ROOT/OFFLINE_LIGHTNING/v2020-11/$MET/$2019/FLASH_CTH_$MET_0.25x0.3125_$**2019**_$MM.nc4  CTH   1980-**2019**/1-12/1-31/0-23/+90minute RFY3 xy  1  * -  1 1
)))LightNOx

### GEOS-Chem version
13.2.1

### Description of modifications
Have modified HEMCO_Config to reference most recent versions of emissions (ie v2020-11 for lightning emissions)

**Comment by tessac2** [comment]
Hello, I just wanted to follow up on the above questions about the availability of offline lightning emissions for GEOS-FP for 2020 and 2021. I was able to run the model with 2019 emissions data, but would prefer to use the 2020/2021 if they are available soon. 

In addition to the 2020/2021 OFFLINE LIGHTNING, I was wondering when the OFFLINE_SEASALT for 2020/2021 might be available, and when the 2021 OFFLINE_BIOVOC and OFFLINE_SOILNOX will be available on http://geoschemdata.wustl.edu/ExtData/HEMCO/ ? 

@yantosca I was having trouble trying to figure out how to add the Emissions/Deposition (GC-WG:Emis-Dep) tag to this--would you mind adding this tag or providing instructions on how to do so? Thank you so much!

**Comment by tessac2** [comment]
Hello, I just wanted to follow up on the above questions about the availability of offline lightning emissions for GEOS-FP for 2020 and 2021. I was able to run the model with 2019 emissions data, but would prefer to use the 2020/2021 if they would be available. 

In addition to the 2020/2021 OFFLINE LIGHTNING, I was wondering when the OFFLINE_SEASALT for 2020/2021 might be available, and when the 2021 OFFLINE_BIOVOC and OFFLINE_SOILNOX will be available on http://geoschemdata.wustl.edu/ExtData/HEMCO/ ? 

Thank you! @yantosca I was having trouble trying to figure out how to add the Emissions/Deposition (GC-WG:Emis-Dep) tag to this

**Comment by msulprizio** [comment]
Hi @tessac2. I suspect the offline emissions for 2021 are not immediately available, so you may want to switch to using the online emissions options instead.

@ltmurray Could you provide a status update on the offline lightning NOx?

@hongjianweng Do you have an estimate on when the offline biogenic VOC and soil NOX emissions will be updated through 2021?

**Comment by ltmurray** [comment]
There is no online lightning emission option anymore. We recommend use of the offline lightning climatology fields instead for periods where the daily files are not yet available.

**Comment by msulprizio** [comment]
We will be implementing a user-friendly option for enabling the lightning climatology option in GEOS-Chem 14.1.0.
