### ISSUE TITLE
[BUG] New code to check MET/RES in hco_config breaks non-GCC implementations

### ISSUE THREAD

**Issue by sdeastham** [geoschem/geos-chem#130]
# Report a GEOS-Chem bug or technical issue

GCHP throws a runtime error regarding "Improperly formatted grid resolution" while reading the HEMCO_Config file.

## To Reproduce
Compile and run GCHP with the dev/12.6.2 branch, as of 2019-11-08.

## Expected behavior
GCHP runs.

## Error messages
"Improperly formatted grid resolution"

## Required information
GCC and GCHP version dev/12.6.2
Compiled on Odyssey with ifort 17 and OpenMPI 3.1.1 - standard GCHP environment

## Additional context
This is occurring because the code in hco_config_mod.F90 asks for `RES` from HEMCO, and also asks for the FOUND(=OptFound) flag. The assumption underlying the code is that FOUND will be `.False.` if RES is not present in the HEMCO_Config.rc file. However, the GetExtOpt code only returns `OptFound=.False.` if the option in question is not present in the option list - **and RES has a default value**. As such, `OptFound=.True.` even when RES isn't specified in HEMCO_Config.rc (as is the case with GCHP). One workaround is to check for `Trim(RES) .ne. "unknwon_res` (the default value), but this is pretty ugly. It would be better to do something explicit which ignores this code when it's not relevant (i.e. in every case except GC Classic).

**Comment by yantosca** [comment]
Sorry about that.  I was going to test w/ GCHP but didn’t get to it.  We can wrap that code in an #ifndef ESMF_ block.  That should work.  For now, try that fix in your code.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sdeastham** [comment]
Thanks Bob! I’m a bit concerned about using an ESMF_ block, as this bug would affect ANY non-GCC implementation (not just ESMF-based ones). If we did want to use C-preprocessor flags then I’d actually prefer an “#ifdef ( GC_CLASSIC)” or something. Using the workaround I suggested does seem to fix the issue for now, but a more robust fix would be better.

**Comment by yantosca** [comment]
Hi Seb,

For now I have implemented this.  We don't have a MODEL_CLASSIC #ifdef yet but maybe we can add one later.

```F90
#ifndef MODEL_GEOS
#ifndef MODEL_WRF
#ifndef MODEL_CESM
#ifndef ESMF_
    !=======================================================================
    ! Look for met field and grid resolution.  When running the HEMCO
    ! standalone these will need to be read from the configuration file.
    ! Otherwise, HEMCO will inherit the met field and grid resolution
    ! of the parent model (GC-Classic, GCHP, etc.)
    !
    ! NOTE: Only do this check if not using GEOS-Chem in an external ESM!
    !=======================================================================

    ! Look for met field
    CALL GetExtOpt( HcoConfig, CoreNr, 'MET', &
                    OptValChar=MetField, FOUND=FOUND, RC=RC )
    IF ( FOUND ) THEN
       HcoConfig%MetField = TRIM( MetField )
    ENDIF

    ! Look for grid resolution
    ! Make sure resolution string is in the proper FlexGrid format
    CALL GetExtOpt( HcoConfig, CoreNr, 'RES', &
                    OptValChar=GridRes, FOUND=FOUND, RC=RC )
    IF ( FOUND ) THEN
       SELECT CASE( TRIM( GridRes ) )
          CASE( '4x5' )
             GridRes = '4.0x5.0'
          CASE( '2x25', '2x2.5' )
             GridRes = '2.0x2.5'
          CASE( '05x0625' )
             GridRes = '0.5x0.625'
          CASE( '025x03125' )
             GridRes = '0.25x0.3125'
          CASE DEFAULT
             Msg = 'Improperly formatted grid resolution: ' // TRIM( GridRes )
             CALL HCO_Error( HcoConfig%Err, Msg, RC, Loc )
             RETURN
       END SELECT
       HcoConfig%GridRes = TRIM( GridRes )
    ENDIF
#endif
#endif
#endif

This is implemented in commit https://github.com/geoschem/geos-chem/commit/bab7c79801d86cfffcd6c0318084442f2dbcc60b.

**Comment by sdeastham** [comment]
Thanks Bob!

**Comment by yantosca** [comment]
I just now verified that the above-mentioned fix now allows an "out-of-the-box" c24 gchp_standard simulation to execute properly. 

Also see related issues: https://github.com/geoschem/geos-chem/issues/126 and https://github.com/geoschem/HEMCO/issues/5

**Comment by Zitely** [comment]
Hi, 

When running HEMCO standalone v3.0.0, I am getting the same error as above (which I think is making other errors to appear). Is fix you mentioned on Nov 12, 2019 only for GCHP? Do you have any fix for HEMCO standalone?

libgomp: Invalid value for environment variable OMP_NUM_THREADS
  
Reading entire HEMCO configuration file: HEMCO_sa_Config.rc
 **HEMCO ERROR: Improperly formatted grid resolution: 0.5x0.625**
 ERROR LOCATION: ReadSettings (hco_config_mod.F90)
 
 HEMCO ERROR: Error encountered in routine "Config_Readfile!"
 ERROR LOCATION: HCOI_SA_Init (in module HEMCO/Interfaces/hcoi_standalone_mod.F90)
 
 HEMCO ERROR: Error encountered in routine "HCO_Sa_Init"!
 ERROR LOCATION:  -> at HCOI_StandAlone_Run (in module HEMCO/Interfaces/hcoi_standalone_mod.F90)
 
HEMCO_STANDALONE EXITED WITH ERROR!

real	0m0.010s
user	0m0.006s
sys	0m0.001s

**Comment by lizziel** [comment]
Hi Zitely,

This should be fixed in the latest HEMCO dev, which is 3.0.0 (not yet released). Could you tell me what is the last commit of the version you are using? Also, how are you generating a run directory? Things have changed somewhat in the dev version.

**Comment by Zitely** [comment]
Hi Lizzie, 

This is the last commit:
$ git log -1
commit 9beb248880270985d4fc3df6d954ccf0df56d932 (HEAD -> master, origin/master, origin/HEAD)
Author: Melissa Sulprizio <mpayer@seas.harvard.edu>
Date:   Fri Jun 5 10:12:57 2020 -0400

    Restore fix to hcoio_read_std_mod.F to exit search only if a field is to be interpolated and isn't discontinuous
    
    This fix was added in an earlier commit (bd08db47), but was undone by a
    later commit overwriting these files with files from GEOS-Chem.
    
    For the implementation of Yuan-processed MODIS LAI in GEOS-Chem 12.7.0,
    code was added to hcoi_read_std_mod.F90 to exit the search for the right
    timestamp. The search was supposed to be used only for non-interpolated
    data, but it turns out that code is needed to properly read in met fields
    for the HEMCO standalone. As a fix, we only exit the search if the dataset
    is to be interpolated and is not discontinuous (as is the case for Yuan-
    processed MODIS LAI).
    
    Signed-off-by: Melissa Sulprizio <mpayer@seas.harvard.edu>

To create a new run directory I do the following:
1) 'cd run' inside the HEMCO code directory 
2) type ./createRunDir.sh 
3) Select 1, then select 3, then type a path for a HEMCO_Config.rc, a path and name for the new run directory like 'new_test'.

**Comment by lizziel** [comment]
Thanks! I was able to reproduce this issue. I was able to get around it by changing this:
          CASE( '05x0625' )
             GridRes = '0.5x0.625'
to this:
          CASE( '05x0625', '0.5x0.625' )
             GridRes = '0.5x0.625'
It appears this same fix was previously made to fix this bug for 2x2.5 standalone runs but not extended to other resolutions for some reason. We will make this fix. This concerns the same code as in this GitHub issue but is a slightly different problem. I will make a new GitHub issue for it.

Beware that I am running into additional problems with HEMCO standalone. It appears that our dev version of HEMCO needs some additional work for running as standalone. I will make GitHub issues as needed to address these.

**Comment by Zitely** [comment]
Hi Lizzie, 
I made the change in hco_config_mod.F90, then went back to the run directory and did ./runHEMCO.sh , but the error shows again. Should I do an extra step for the change to be implemented?

Thanks,
Zitely

**Comment by Zitely** [comment]
I was wondering if I should create a new run directory and build the model again?

**Comment by lizziel** [comment]
Hmm, that's odd. Did you do `make -j` and then `make install` in the build directory before rerunning?

**Comment by Zitely** [comment]
No, I didn't. I will do that.

Thanks,
Zitely

**Comment by Zitely** [comment]
Hi Lizzie, 
I did make -j and then make install, but the error appeared again. It was until I created a new run directory that HEMCO ran just fine :)

Thanks,
Zitely

**Comment by lizziel** [comment]
That's concerning since the run directory should be no different before and after. Did you verify that your new executable was copied to your old run directory before rerunning?

**Comment by Zitely** [comment]
Oh, oh! It didn't ran fine. Another error shows and I found the same error message on another bug fix. I will follow their suggestions, but maybe I will comment on that thread as well :\

Thanks and probably talk to you soon :P

**Comment by Zitely** [comment]
Did you verify that your new executable was copied to your old run directory before rerunning?
I checked, but the executable was not replaced after doing make -j and make install. That's why I decided to create a brand new run directory.

**Comment by lizziel** [comment]
Okay, good to know! It is possible the make install is not working for HEMCO standalone, which is another thing I will look at. I am going to create a new github issue for HEMCO standalone now and will post the link to it here. We can then switch the conversation to that issue.

**Comment by lizziel** [comment]
Okay, see new issue (in the HEMCO repo): https://github.com/geoschem/HEMCO/issues/40
