### ISSUE TITLE
Why there was information of "Min = *******" about BCs when running a nested Hg simulation 

### ISSUE THREAD

**Issue by jie0314ouc** [geoschem/geos-chem#1304]
I want to run a nested Hg simulation (AS，Grid=0.5°×0.625°) based on the BCs produced a global simulation with 2°×2.5°，and according to the [[http://wiki.seas.harvard.edu/geos-chem/index.php/Setting_up_GEOS-Chem_nested_grid_simulations#GEOS-Chem_12.4.0_and_later](url)
  And I had verify the input.geos and HEMCO_Config.rc in the rundirs. Finally, after ./geos, I found this nested simulation was successfully to produce Outputfiles. 
  However, I also found the following prompt on the interface：

      `SNOW_HG_LAND_STORED not found in restart file, set to zero
        ===============================================================================
        Min and Max of each species in BC file [mol/mol]:
        Species   1,      Hg0: Min = ***************  Max = 7.614199527E-13
        Species   2,      Hg2: Min = ***************  Max = 1.281034062E-13
        Species   3,      HgP: Min = ***************  Max = 2.437486790E-13
        GET_BOUNDARY_CONDITIONS: Done applying BCs at 2012/01/02 00:00
        vdinti: pbl height will be limited to bottom           25  model levels. top is    431.25009999999997       hpa

        ********************************************
        * B e g i n   T i m e   S t e p p i n g !! *
        ********************************************`
  Despite this prompt, the run succeeds and the output file is generated. The following figure was the concentration of Hg0 . I don't know if this simulation was actually successful.

  Gcc version : 9.3
  Geos-chem version: 12.9.3
  Netcdf-c version:4.8.1
  Netcdf-f version: 4.5.3
  
![image](https://user-images.githubusercontent.com/100178108/178437252-065cdcdc-a1aa-4e3e-b3f5-ab47bc83a9d8.png)

**Comment by jie0314ouc** [comment]
Thanks for your reply. If the value could not fit in the specified format defined in the code, how did it was used in the running?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "geoschem/geos-chem"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月12日(星期二) 晚上10:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [geoschem/geos-chem] Why there was information of "Min = *******" about BCs when running a nested Hg simulation  (Issue #1304)





 
Hi @jie0314ouc - It looks like your run was indeed successful. The printing of all asterisks indicates the value could not fit in the specified format defined in the code. You can read more about that sort of issue here.
 
In newer versions of GEOS-Chem we no longer have that code. If you want to verify your BC file indeed okay I suggest opening it with a netcdf viewer such as Panoply or ncview that will show you the min and max of the dataset.

**Comment by lizziel** [comment]
The string printed to the log is not the same as the value used during running. The print statement that shows the min and max is informational only, and the fortran code for printing fixed width is finicky. My guess is the minimum value in the BC file is very small such that the fixed width specification in the print needs modification.

You could test this by adding another print to the code that does not use fixed width. Grepping the GEOS-Chem repository in the version you have for `Min and Max of each species` will bring you to where the print is located. You can then add a line that is simply:

`print *, "Debugging print of min value in BC file: ", x`

where x is the variable used in the original print for minimum value.
