### ISSUE TITLE
Ask for the units of parameters in RRTMG optical input files

### ISSUE THREAD

**Issue by Lianheng257** [geoschem/geos-chem#1305]
Dear GC group members

I am trying to edit the optical input parameters for the RRTMG.

The optical input file is shown below (eg. org.dat):

![1657617952300](https://user-images.githubusercontent.com/75835812/178457957-a19b7f6e-a1de-43b8-a6e9-07ba885ac908.png)

I just want to make sure about the unit of Q (mass extinction efficiency) used here.

I read this paper https://acp.copernicus.org/articles/14/5513/2014/acp-14-5513-2014.pdf .  so that I assume the unit may be [m2 g-1] but I am not very confident.

I also see the code in Geoschem/GeosCore/aerosol_mod.F90 line 1783-1815 uses the Q to calculate the AOD (showing as ODAER in code) for aerosols, but I can not balance the dimension base on the known unit.
![1657618361191](https://user-images.githubusercontent.com/75835812/178459314-e09ad34c-b8a0-47c6-bf34-f7434629b5fa.png)

Looking forward to your reply and thanks for your help!

Best regards,
Yumin

**Comment by sdeastham** [comment]
Thanks @yantosca ! Unfortunately I'm not hugely familiar with this part. Dave Ridley performed the RRTMG implementation (including replacing the aerosol input files), the same input is used for RRTMG and Fast-JX, and this specific part of the code is inherited from the pre-Fast-JX code if I remember correctly... so I'm not sure I have much insight here.

**Comment by Lianheng257** [comment]
Thanks, yantoscan and sdeastham,

Yes, the RRTMG and Fast-JX have the same input files. So that they use the same Q input values.  So the unit I think should be same as used in Fast-JX.

Best regards，
Yumin

**Comment by Lianheng257** [comment]
But where I can find the units of the optical input parameters for Fast-JX？ such as the Q in the first figure I showed before.

**Comment by Lianheng257** [comment]
Thanks, sdeastham, 

If I understand correctly, the Q (QQAA) in aerosol_mod is the extinction efficiency (unitless), and the relationship between Q and the mass extinction efficiency (MEE in unit eg. m2/g) which is usually reported in the literature is MEE = Q/ (mass density * radius ) ?

**Comment by xuanw0316** [comment]
@Lianheng257 Q is unitless, the mass extinction you are saying is in fact the "Alpha" column in optical input files. To connect Q and MEE: MEE = 0.75 * Q / (effective radius * mass density).

**Comment by Lianheng257** [comment]
Thanks [xuanw0316](https://github.com/xuanw0316) !

Can I also ask about the other parameters as well as their unit in the optical  input table? Just to make sure, the ss-alb is the single scattering albedo (unitless), g-sym is the asymmetry parameter (unitless), RgDry, Rgwet are the radius in μm, and N and iK are the complex refractive index. 
How about the r-eff, Sg, and the pi(0) to pi (7)?

**Comment by yantosca** [comment]
Closing out this issue as it seems resolved.
