### ISSUE TITLE
[QUESTION] Altitude of GEOS-Chem vertical grid

### ISSUE THREAD

**Issue by JinZheeee** [geoschem/geos-chem#1308]
Hi:
I want to know how to obtain the altitudes of the 47 vertical layers. The website (http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_vertical_grids) listed the 47-layer altitudes, but are these values fixed for all the grids all the time?
![图片](https://user-images.githubusercontent.com/38269950/179349084-6651d3a9-ed5f-43f5-ba58-e5c9a7bf289c.png)

**Comment by yantosca** [comment]
Thanks for writing @JinZheeee.  The example shown below assumes a surface pressure of 1013.25 hPa.  

The hybrid grid formula is given in this section on the wiki: http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_vertical_grids#Hybrid_grid_definition 

Note that above about level 36 or so the levels transition from varying with surface pressure to fixed.   So near the top of the atmopshere the levels are the same for all (I,J,L) grid box locations.  But near the surface the pressure follows the surface pressure.

**Comment by yantosca** [comment]
From the wiki, the transition pressure is about 170hPa.  Any grid boxes skyward of 170 hPa are on fixed pressure levels.
