### ISSUE TITLE
[QUESTION]Error when distributing emissions in the vertical

### ISSUE THREAD

**Issue by ShutingZhai** [geoschem/geos-chem#131]
I was wondering if there are any updates about the issue when distributing emissions in the vertical (http://wiki.seas.harvard.edu/geos-chem/index.php/HEMCO_versions#Error_when_distributing_emissions_in_the_vertical). I'm using version 11-02d and have distributed some of emissions to PBL and free troposphere and ran into the error described in the wiki. When I commented out the parallel loop, I didn't get negative emissions nor 'Subscript #3 of the array VAL has value -1 which is less than the lower bound of 1' error any more, but I got 'Subscript #3 of the array OUTARR_3D has value -1 which is less than the lower bound of 1'. In HEMCO/Core/hco_calc_mod.F90, OUTARR_3D(I,J,L) is still using lowll values for the 3rd subscript. So I was wondering if there's a permanant fix for this issue to avoid getting -1 for lowll variable. Thanks!

**Comment by yantosca** [comment]
Have you tried searching the Git history with the gitk browser (or at github.com)?  Search for commits with PBL and see if the fix has already been implemented.

**Comment by ShutingZhai** [comment]
Thanks Bob! Found it.

**Comment by yantosca** [comment]
Glad you found it!
