### ISSUE TITLE
Forced exit from Rosenbrock[QUESTION]

### ISSUE THREAD

**Issue by zsx-GitHub** [geoschem/geos-chem#1315]
### Ask a question about GEOS-Chem:
I am using GEOS-Chem version 13.3.4 and I keep on receiving a warning in my v13.3.4.log file:

 Forced exit from Rosenbrock due to the following error:
 --> Step size too small: T + 10*H = T or H < Roundoff
 T=   357.77547468306676      and H=   1.8615952554265796E-013
 ### INTEGRATE RETURNED ERROR AT:           45          41          38

The simulation will stop with a notice "## INTEGRATE FAILED TWICE !!!", together with many other numbers.

The v.13.3.4.log file is attached. Thank you!

[v13.3.0.log.txt](https://github.com/geoschem/geos-chem/files/9174867/v13.3.0.log.txt)

**Comment by zsx-GitHub** [comment]
I find that I have this issue in running certain time periods than others. For example, if my simulation is for November 2017, this problem will occur. But if my simulation is for November 2014, no such warning will occur.

**Comment by yantosca** [comment]
Thanks for writing @zsx-Github.  See issue #1205 for the description of the bug and PR #1206 for a fix.  This went into 13.4.0 but you are still using 13.3.4, so your version probably doesn't have the fix.

**Comment by yantosca** [comment]
Also see commit https://github.com/geoschem/geos-chem/pull/1206/commits/70aba397343a58fc775ba0654b128286e96341d7.  This was a 1-liner fix.

**Comment by yantosca** [comment]
I will close out this issue now.  Thanks @zsx-GitHub and let us know if you still have problems.

**Comment by Ruijun-Dang** [comment]
Hi Bob,

I also experienced the same problem though using v13.4.1 with the bug in CloudHet already fixed. 

It happened in 0.25x0.3125 simulation but not 4x5. And it happened in some regions (e.g. east Asia in my case) or some specific days but not others. Is anything else could be related to that?

My logfile is attached. Thank you! 
[loggeos.txt](https://github.com/geoschem/geos-chem/files/9260792/loggeos.txt)

**Comment by yantosca** [comment]
Hi @Ruijun-Dang, I will open a new issue for your error.  Thanks.

**Comment by petersherman123** [comment]
Hi @yantosca, I seem to be running into a similar issue on version 14.1.1 at a specific time (November 15, 2019, 8:20 PM) for two different simulations. I've attached the log file for one of the simulations here.

[GC.log](https://github.com/geoschem/geos-chem/files/11835507/GC.log)

Thanks,
Peter
