### ISSUE TITLE
Missing files in v2018-04 for FINN

### ISSUE THREAD

**Issue by Mashiat25** [geoschem/geos-chem#1317]
I am trying to turn on FINN in HEMCO standalone for January 2017. While changing the directory to the latest version  v2018-04 I have noticed that it does not include any files ending with "with_num.nc" (e.g.- FINN_daily_2015_0.25x0.25_with_num.nc) as can be found in the previous version v2015-02. However, the HEMCO_Config is set to look for these files for the variable FINN_DAILY_NUMBER. 

Looking for suggestions on how to get around this issue. 

[HEMCO_Config_Finn.txt](https://github.com/geoschem/geos-chem/files/9186159/HEMCO_Config_Finn.txt)

**Comment by yantosca** [comment]
Hi @Mashiat25, thanks for writing.

So I believe the FINN/v2018-04 may be an incomplete data set.  There is a warning in the README file:
```console
###############################################################################
##### IMPORTANT NOTE FROM FINN AUTHOR CHRISTINE WIEDINMYER (02 May 2018)  #####
#####									  #####
#####									  #####
##### From: "Christine Wiedinmyer" <christine.wiedinmyer.ucar@gmail.com>  #####
##### Subject: FINN UPDATE- PLEASE READ					  #####
##### Date: May 2, 2018 at 9:15:47 AM EDT				  #####
##### To: <emmons@ucar.edu>, "'Carl Drews'" <drews@ucar.edu>		  #####
##### Cc: <christine.wiedinmyer.ucar@gmail.com>				  #####
#####									  #####
##### Hello, 								  #####
##### You are receiving this email because you have downloaded 		  #####
##### at least one FINNv1.6 emissions file from 			  #####
##### http://bai.acom.ucar.edu/Data/fire/				  #####
#####									  #####
##### It has recently been brought to my attention that some of the 	  #####
##### files include incorrect emission estimates. In light of this recent #####
##### discovery, we have removed FINNv1.6 from the site and replaced the  #####
##### files available for download with FINNv1.5			  #####
#####									  #####
##### It is not recommended that you continue the use of FINNv1.6. I am   #####
##### currently looking into the issues and reprocessing the files now.   #####
##### You will be contacted when the next version is completed and 	  #####
##### available for download. 						  #####
##### 									  #####
##### I am terribly sorry for the inconvenience. 			  #####
#####									  #####
##### Christine Wiedinmyer						  #####
##### http://bai.acom.ucar.edu/Data/fire/				  #####
##### christine.wiedinmyer.ucar@gmail.com                                 ##### 
###############################################################################
```
I'm not sure we ever fixed this. 

You might want to consider using the older FINN/v2015-02 data.  If you need more recent years there is also the GFAS biomass burning product, which is actively being produced (and we have data up until about May 2022).

**Comment by Mashiat25** [comment]
Hi @yantosca! Thanks for your response. I look forward to using 2017 data which is missing in FINN/v2015-02. I guess I'll continue using GFAS for my simulations at the moment.

**Comment by yantosca** [comment]
Thanks @Mashiat25.  We would need someone to provide the GCST s with the updated FINN products.  If that is a priority for your research you could bring it to the attention of the Emissions working group, and maybe they could see who in the community could do that work.
