### ISSUE TITLE
[FEATURE REQUEST] Reaction and/or production rates in planeflight diagnostics

### ISSUE THREAD

**Issue by kelvinhb** [geoschem/geos-chem#132]
## Add your feature request below:

It would be very helpful to be able to output reaction rates and/or species production rates along plane/ship tracks as part of the planeflight diagnostic. This was an option with SMVGEAR, but with the move to Flexchem it hasn't been available. There is more info [here](http://wiki.seas.harvard.edu/geos-chem/index.php/Planeflight_diagnostic#Saving_out_reaction_rates_with_FlexChem). For what it's worth, I agree with Mat Evans' comment that the current planeflight format is perfectly workable, but archiving reaction rates would be a particularly valuable addition.

**Comment by tsherwen** [comment]
I second what Kelvin is saying here. I have used this feature in past versions and would definitely make use of it if it became available again.

**Comment by msulprizio** [comment]
This is not a priority for the GCST at the moment, but we welcome input from the community to add this feature  for rates from KPP.

**Comment by ktravis213** [comment]
This is so important, myself and others have used this many times, particularly for photolysis to compare against field campaign observations, but also for looking at the importance of different pathways for chemistry (such as in Karen Yu's SEAC4RS) paper. I would definitely request this feature.

**Comment by tsherwen** [comment]
Hello, 

In case it is of use to anyone else, I've pushed to Github how I setup extracting j-rates via planeflight from the KPP mechanism ([linked here on branch `v12.9.1_dev_PL_JVAL_extraction`](https://github.com/tsherwen/geos-chem/tree/v12.9.1_dev_PL_JVAL_extraction)). I could set up a pull request too unless there any comments / suggested improvements? 

This approach could be used to get reaction rates via (`State_Diag%RxnRate`) or production rates (via a `State_Diag%Prod...` container). I have explored this, but the shared commit is just for J-rates currently (as per issue #412).

Cheers, 

Tomas

**Comment by msulprizio** [comment]
Thanks @tsherwen! A pull request would be great. I think may users would be interested in this feature. Since it won't impact benchmark output, we could bring this update into the standard code at any time.

**Comment by tsherwen** [comment]
Hello @msulprizio, thanks. I will submit a pull request once I have resolved why I am seeing an issue within a custom nested grid. I tested the code changes on a couple of datasets on a global scale, where it all worked fine. However, within my custom nested grid, I get a segmentation fault after the run successfully outputs the planeflight header. I will work on debugging this again next week. If you have anything that pops into your head about the `State_Diag` object in nested runs vs. global runs, then please do say.

**Comment by tsherwen** [comment]
I have now submitted a pull request (#615) for this. I resolved what was causing the issue I mentioned in my last message, which was unrelated to the pushed code.

**Comment by msulprizio** [comment]
This feature request has been resolved by the above linked pull request. These updates will be included in [13.1.0](https://github.com/geoschem/geos-chem/milestone/17).
