### ISSUE TITLE
[QUESTION] How to modify the starting and ending time of simulation

### ISSUE THREAD

**Issue by SLF2265127725** [geoschem/geos-chem#1325]
### Ask a question about GEOS-Chem:
In the latest version of GEOS Chem, how to modify the simulation time? I don't want to use the default time

**Comment by yantosca** [comment]
Thanks for writing @SLF2265127725. 

If you are using GEOS-Chem 13.4.1, then you need to modify settings in the input.geos file as explained in our user manual: http://wiki.geos-chem.org/Getting_Started_with_GEOS-Chem

NOTE: For the upcoming 14.0.0 release, we are migrating out documentation from the wiki to https://geos-chem.readthedocs.io.

**Comment by lizziel** [comment]
HI @SLF2265127725, please also let us know if you are using GCHP. The instructions for changing start/end time for GCHP are different than for GEOS-Chem Classic.

**Comment by SLF2265127725** [comment]
Hi, the version of GEOS-Chem I'm using is 13.4.1. When I modify the time between 2019.7.1 and 2019.8.1 in input.geos, no error will be reported. When the time I set is not within this range, the following error will be reported

**Comment by SLF2265127725** [comment]
Like this

**Comment by SLF2265127725** [comment]
> Thanks for writing @SLF2265127725.
> 
> If you are using GEOS-Chem 13.4.1, then you need to modify settings in the input.geos file as explained in our user manual: http://wiki.geos-chem.org/Getting_Started_with_GEOS-Chem
> 
> NOTE: For the upcoming 14.0.0 release, we are migrating out documentation from the wiki to https://geos-chem.readthedocs.io.

Hi, the version of GEOS-Chem I'm using is 13.4.1. When I modify the time between 2019.7.1 and 2019.8.1 in input.geos, no error will be reported. When the time I set is not within this range, the following error will be reported

**Comment by SLF2265127725** [comment]
> HI @SLF2265127725, please also let us know if you are using GCHP. The instructions for changing start/end time for GCHP are different than for GEOS-Chem Classic.



> HI @SLF2265127725, please also let us know if you are using GCHP. The instructions for changing start/end time for GCHP are different than for GEOS-Chem Classic.

I didn't use GCHP

**Comment by SLF2265127725** [comment]
When I download the weather data and run it using the Dry Run method, the following error message appears
![QQ图片20220730112825](https://user-images.githubusercontent.com/58589530/181871016-9d33fc35-d974-448b-974e-9cc56f95f95c.jpg)

**Comment by SLF2265127725** [comment]
> Thanks for writing @SLF2265127725.
> 
> If you are using GEOS-Chem 13.4.1, then you need to modify settings in the input.geos file as explained in our user manual: http://wiki.geos-chem.org/Getting_Started_with_GEOS-Chem
> 
> NOTE: For the upcoming 14.0.0 release, we are migrating out documentation from the wiki to https://geos-chem.readthedocs.io.

Thanks for your help. I've solved my problem,
I need to set GC_RESTART to False in hemco_config.rc

**Comment by SLF2265127725** [comment]
> HI @SLF2265127725, please also let us know if you are using GCHP. The instructions for changing start/end time for GCHP are different than for GEOS-Chem Classic.
Thank you. I've solved my problem,

**Comment by yantosca** [comment]
Thanks @SLF2265127725.  I'll close out this issue.
