### ISSUE TITLE
[QUESTION] Transport error in GEOS-Chem 13.4.1

### ISSUE THREAD

**Issue by XueyingYu-1993** [geoschem/geos-chem#1326]
### Ask a question about GEOS-Chem:
I get the below false simulation for methane when turn on transport. It is not related with PBL mixing scheme.
![image](https://user-images.githubusercontent.com/77073047/181815341-a2218a88-6934-4578-8063-887fd18fd15a.png)

**Comment by SLF2265127725** [comment]
Hello, I would like to konw which version of GEOS-Chem are you using?

**Comment by SLF2265127725** [comment]
What I did was a CO2 simulation, and I feel that the result I got is very similar to your picture. I don't know what went wrong
Problem 1: The picture is blurred
Problem2: CO simulation is incorrect
![Uploading SpeciesConc_CO2_in_GEOSChem.SpeciesConc.20190701_0000z.png…]()

**Comment by SLF2265127725** [comment]
What I did was a CO2 simulation, and I feel that the result I got is very similar to your picture. I don't know what went wrong
Problem 1: The picture is blurred
Problem2: CO simulation is incorrect
![SpeciesConc_CO2_in_GEOSChem SpeciesConc 20190701_0000z](https://user-images.githubusercontent.com/58589530/181871481-c4ddac46-b35b-4030-aba9-023a247cbc0e.png)

**Comment by XueyingYu-1993** [comment]
I am using the newest version, maybe v14 or late v13. How about you? @SLF2265127725

**Comment by SLF2265127725** [comment]
> I am using the newest version, maybe v14 or late v13. How about you? @SLF2265127725

GEOS-Chem13.4.1

**Comment by SLF2265127725** [comment]
> I am using the newest version, maybe v14 or late v13. How about you? @SLF2265127725

Hi, I think there are some problems of this version. I put the question link  here, you can have a look.
https://github.com/geoschem/geos-chem/issues/1278

**Comment by yantosca** [comment]
Thanks for writing @XueyingYu-1993.  We would need to know more about how you set up your simulation..  Would you be able to attach your input.geos, HEMCO_Config.rc, geos-chem log, HEMCO.log, and HISTORY.rc files to this issue?

Also you didn't specify if you are using an "out-of-the-box" simulation or if you have made any additional modifications to the source code.  If you have made additional modifications then please doublecheck that code to see if there are any potential bugs.

We have recently posted a debugging guide that may be helpful at our GEOS-Chem ReadTheDocs page: https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html.  That has some suggestions that you can try to identify errors in the code and/or run directory configuration files.

**Comment by XueyingYu-1993** [comment]
Thank you so much! Attached are input.geos, HEMCO_Config.rc, geos-chem log, HEMCO.log, and HISTORY.rc files. I did not make any change to the code. I tried the debug in [#1278](url), which does not work.

[run.log](https://github.com/geoschem/geos-chem/files/9240220/run.log)
[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/9240230/HEMCO_Config.rc.txt)
[HISTORY.rc.txt](https://github.com/geoschem/geos-chem/files/9240231/HISTORY.rc.txt)
[input.geos.txt](https://github.com/geoschem/geos-chem/files/9240232/input.geos.txt)
[HEMCO.log](https://github.com/geoschem/geos-chem/files/9240221/HEMCO.log)

**Comment by XueyingYu-1993** [comment]
> > I am using the newest version, maybe v14 or late v13. How about you? @SLF2265127725
> 
> Hi, I think there are some problems of this version. I put the question link here, you can have a look. #1278

Hi, did the solution in #1278 worked in your case? Mine isn't.

**Comment by SLF2265127725** [comment]
@XueyingYu-1993 Hi, I switched the version of 13.3.4 to make a new simulation

**Comment by XueyingYu-1993** [comment]
Thank you! Make sense. I am going to use the older version too.
