### ISSUE TITLE
[QUESTION]How to apply grid data in a small area to the GEOS-Chem13.3.4 model

### ISSUE THREAD

**Issue by SLF2265127725** [geoschem/geos-chem#1327]
### Ask a question about GEOS-Chem:
Grid Resolution
The grid resolutions currently supported are 4.0x5.0, 2.0x2.5, 0.5x0.625, and 0.25x0.3125 (real numbers, not integers, must be used). Theoretically, any grid resolution should work, but this has not been validated. But, for a global model, the results for a very small area are not obvious at all. Now, I have emissions data for a city, how do I apply it to this model? Or whether GEOS-Chem can be used to model CO2 in a city

**Comment by yantosca** [comment]
Thanks for writing @SLF2265127725.  If you need to model a smaller simulation domain (such as on the scale of a city or a region), you might consider using WRF-GC.  This will let you define up to 3 nested domains around a point of interest, and use GEOS-Chem's chemistry and emissions.  See our WRF-GC manual for more information: https://wrf.geos-chem.org

**Comment by yantosca** [comment]
Also -- sometimes wrf.geos-chem.org site takes a while to connect.  Keep trying it,

**Comment by SLF2265127725** [comment]
@yantosca Thanks for your help
