### ISSUE TITLE
[QUESTION] Add NON-EMISSIONS DATA

### ISSUE THREAD

**Issue by Rainbow1994** [geoschem/geos-chem#133]
I would like to add some NON-EMISSIONS DATA items for specific simualtion. When I added these new items in HEMCO_Config.rc and ran GEOS-CHEM, it seemed that the HEMCO didn't read the new items. If I need to add these items in the readlist of HEMCO or modify other files?  Do you have any advice for the problem?

**Comment by yantosca** [comment]
Thanks for writing.  HEMCO treats non-emissions data separately from emissions data.  Non-emissions data are read in from disk and stored in the HEMCO state.  It is up to the user to manually obtain the non-emissions data by getting a pointer to them (via call to routine HCO_GetPtr). 

For example, let's take a look at the example in GeosCore/carbon_mod.F.  At the top of the module we have these pointer arrays defined above the CONTAINS statement:

```F77
      ! Pointers to fields contained in the HEMCO data structure
      ! These must all be declared as REAL(f4), aka REAL*4.
      REAL(f4), POINTER     :: O3(:,:,:)  => NULL()
      REAL(f4), POINTER     :: OH(:,:,:)  => NULL()
      REAL(f4), POINTER     :: NO3(:,:,:) => NULL()
```

then
```F77
      ! am I root? 
      aIR                  = am_I_Root

      ... etc ...

      ! First-time initialization
      IF ( FIRSTCHEM ) THEN

         ! Zero SOG4 and SOA4 (SOA from ISOP in gas & aerosol form)
         ! for offline aerosol simulations.  Eventually we should have
         ! archived isoprene oxidation fields available for offline
         ! simulations but for now we just set them to zero. 
         ! (dkh, bmy, 6/1/06)
         IF ( IT_IS_AN_AEROSOL_SIM ) THEN

          ... etc omitting...

            IF ( LSOA ) THEN
               ! Get offline oxidant fields from HEMCO (mps, 9/23/14)
               CALL HCO_GetPtr( aIR, HcoState, 'GLOBAL_OH',  OH,  RC )
               IF ( RC /= GC_SUCCESS )
     &         CALL ERROR_STOP( 'Cannot get pointer to GLOBAL_OH',  LOC)

               CALL HCO_GetPtr( aIR, HcoState, 'GLOBAL_NO3', NO3, RC )
               IF ( RC /= GC_SUCCESS )
     &         CALL ERROR_STOP( 'Cannot get pointer to GLOBAL_NO3', LOC)

               CALL HCO_GetPtr( aIR, HcoState, 'O3',         O3,  RC )
               IF ( RC /= GC_SUCCESS )
     &         CALL ERROR_STOP( 'Cannot get pointer to O3',         LOC)
            ENDIF

            ... etc omitting ...
         ENDIF
```

As you can see, we call Hco_GetPtr to get the "GLOBAL_OH" field and store it in the pointer array called OH, and similarly for NO3 and O3.  

NOTE: This is wrapped in an IF ( FIRSTCHEM ) block, which will only execute on the first call to this routine in carbon_mod.F.  Once you define a pointer, it will be automatically updated every emissions call.

At the end of the simulation (in your cleanup routine), you should add

```F77
       O3  => NULL()
       NO3 => NULL()
       OH  => NULL()
```
which will free the memory occupied by these pointers.

If you search for HCO_GetPtr in the code with:

```
grep -in HCO_GetPtr */*.F*
```

You can also see how other GEOS-Chem modules use the call to HCO_GetPtr.  I would try to follow one of those examples in the code.

**Comment by Rainbow1994** [comment]
Thank you very much! I have already modified the code just similar as what you said. Fortunately it works. Thanks again!

**Comment by yantosca** [comment]
Glad it works!  Thanks again.
