### ISSUE TITLE
Trying coarser resolution (12.0x15.0) with GEOS-Chem Classic results in errors with KPP solvers [BUG/ISSUE]

### ISSUE THREAD

**Issue by supergr35** [geoschem/geos-chem#1335]
### What institution are you from?
Rice University

### Description of the problem
When running GEOS-Chem at 12x15 resolution, KPP solvers are unable to converge. We're testing at 12.0x15.0 resolution despite 4x5 MERRA2 meteorology to see if GEOS-Chem can be ran faster without loss of too much data. I believe it's on the first time step and isn't able to continue time stepping, but I haven't verified this. 
![image](https://user-images.githubusercontent.com/23623348/182727761-8c668edf-8387-4f18-bf0e-346877e13908.png)

Steps:
Set resolution in input.geos to 12.0x15.0
Remove any hard-coded checks for a supported resolution and recompile
Run geos-chem

### Description of troubleshooting performed
Describe any troubleshooting that you have already performed here. Also include any leads or suspicions here.
According to https://github.com/geoschem/geos-chem/issues/66 I've tried to adjust RTOL and ATOL up and down by an order of magnitude with no effect. 

Finally, I've also tried to adjust the timesteps in input.geos to higher and lower values with no change.

### GEOS-Chem version
12.9.2

### Description of modifications
An earlier error required me to add a dust emissions tuning factor for my specific resolution in hcox_dustdead_mod.F (according to http://wiki.seas.harvard.edu/geos-chem/index.php/Mineral_dust_aerosols#Generating_dust_tuning_factors), and some threads have pointed to dust emissions being too high as a potential error. I've adjusted my tuning factor up and down, but I'm still getting errors in the KPP solvers.

I set RES in HEMCO_Config.rc to 4x5 to ensure that our meteorology files (MERRA2 at 4x5) are still read in correctly.

I've also set UCX_MOD=.FALSE in ucx_mod.F90 to get rid of the following error
<img width="501" alt="image" src="https://user-images.githubusercontent.com/23623348/182728289-f74dce64-310a-4add-ab97-b781c90d0a4a.png">

### Log files
- Build log (if applicable):
- Run logs (if applicable):
- Run script (if applicable):

### Software versions
- CMake version: 
- Compilers (Intel or GNU, and version): gfortran-10, gcc-10, g++-10
- NetCDF version:

**Comment by yantosca** [comment]
Thanks for writing @supergr35.  We have no experience running GEOS-Chem Classic at coarser resolutiion than 4 x 5.

One thing that may be happening is that you might have to reduce the dynamic and chemical timesteps.  It could be that the default timesteps of 600/1200 seconds are violating the Courant limit in transport.   

To test this hypothesis, run a short simulation with transport turned off and see if you do not get the KPP integration error.   If you still get the KPP integrate error, then try turning off other operations (e.g. drydep, wetdep, PBL mixing) and see if you can isolate which operation is causing the problem.  We also have some tips at our new debugging guide on ReadTheDocs: https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html

**Comment by yantosca** [comment]
Oops I meant increase the timesteps.  When you go to finer resolution you should reduce the default timesteps but when you go to coarser resolution you have to increase them.  Sorry for the confusion.

**Comment by yantosca** [comment]
Closing out this issue
