### ISSUE TITLE
[BUG/ISSUE] Forced exit from Rosenbrock solver in 13.4.1

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#1337]
@Ruijun-Dang wrote:

> I also experienced the same problem as reported in #1315 though using v13.4.1 with the bug in CloudHet already fixed.
>   
> It happened in 0.25x0.3125 simulation but not 4x5. And it happened in some regions (e.g. east Asia in my case) or some 
> specific days but not others. Is anything else could be related to that?
>
> My logfile is attached. Thank you!
>
> [loggeos.txt](https://github.com/geoschem/geos-chem/files/9260792/loggeos.txt)

**Comment by yantosca** [comment]
Hi @Ruijun-Dang,

I looked at the log file.  At the trouble box it seems that there may be some reactions that are either several orders of magnitude too large or too small.  Most reactions have a rate of something of order 1e-10  to 1e-16 or so but we have here:

```console
 10140446.407880969      ClOO --> Cl + O2
 ...
   9.7159248066260724E-025 CH3CCl3 --> 3 Cl
   2.8614745246518153E-024 CCl4 --> 4 Cl
   5.0791410237424481E-025 CFC11 --> 3 Cl
   2.2290765575012239E-026 CFC12 --> 2 Cl
   5.7967527712625206E-026 CFC113 --> 3 Cl
   3.3357124140563279E-027 CFC114 --> 2 Cl
   2.9449117971028078E-028 CFC115 --> Cl
   6.1647102007237372E-026 HCFC123 --> 2 Cl
   6.8724667289211356E-026 HCFC141b --> 2 Cl
   4.5456764722640063E-028 HCFC142b --> Cl
   1.1028918950571653E-028 HCFC22 --> Cl
```

The ClOO -> Cl + O2 looks like it may be the culprit.  The rate for this is computed by rate-law function:
```F90
ClOO {+M} = Cl + O2 {+M} :                   GCJPLEQ_acabab(6.60d-25, 2502.0d0, 2.20d-33, 3.1d+00, 1.8d-10, 0.0d0, 0.6d0);     {JPL 15-10; XW}
```
which looks like it might be a pressure-dependent reaction.  The function calls another rate-law function `GCJPLPR_abab`, which  has this code:

```F90
    rlow  = a1 * ( K300_OVER_TEMP**b1 ) * NUMDEN
    rhigh = a2 * ( K300_OVER_TEMP**b2 )
    xyrat = rlow / rhigh
    blog  = LOG10( xyrat )
    fexp  = 1.0_dp / ( 1.0_dp + ( blog * blog ) )
    k     = rlow * ( fv**fexp ) / ( 1.0_dp + xyrat )
```
If I had to guess, I think it's blowing up in the `LOG10` function.  If `xryat` is close to zero then that could be a huge number, I think.  You could try checking that out.

The concentration of ClOO going into the reaction is  5.2435587933417791 molec/cm3/s, so maybe that is causing some kind of blow-up in the rate-law expression.

You could try to play around with the convergence criteria `RTOL` and `ATOL` in `GeosCore/fullchem_mod.F90`.  You could also try reducing the transport and chemistry timesteps as well to see if that helps.

**Comment by yantosca** [comment]
Also tagging @Jourdan-He for reference

**Comment by Ruijun-Dang** [comment]
Thanks @yantosca! I tried reducing the transport and chemistry timesteps to 150s and 300s, respectively. I also tried tightening the ATOL and RTOL by reducing them to 1e-3 and 5e-4 (default values are 1e-2 and 5e-3). But both didn't help. The problem still seems to be ClOO. Do you have any recommendation for RTOL and ATOL values?

**Comment by yantosca** [comment]
Hi @Ruijun-Dang.  I don't have a lot of experience in picking out RTOL/ATOL values other than what is provided in `fullchem_mod.F90`.   I think you just have to play around with finding proper values.

You might also want to check your transport boundary conditions.  If ClOO is coming in from the boundary conditions with a weird value, then maybe you can add code to reset it to something more reasonable. 

You can also try turning off the operations one at a time (i.e. transport, wet deposition, dry deposition, etc) to see if you can find the operation that is causing the problem.

Also tagging @viral211 and @Jourdan-He

**Comment by Ruijun-Dang** [comment]
Thanks @yantosca! It turned out the problem was "convection". Changing KPP tolerances didn't help. Concentrations of ClOO in restart and boundary conditions are all reasonable. Using different restart/boundary conditions/buffer zone/nested domain didn't help. All bugs disappeared once I turn off the convection process.  

Seems like it is the convection process that brought the ClOO concentration on that grid box to a high value and further led to an error in KPP, but I don't know why that is. I don't think this is a problem of convection module in GEOS-Chem, as it has been quite stable across the versions, so I solved the problem by simply skipping that day.

**Comment by yantosca** [comment]
Thanks @Ruijun-Dang for the feedback.  It might have been that ClOO got to a really small concentration and then maybe blew up a mathematical operation which led to an unreasonable value. Glad to know that it's solved.   I can close out this issue now.

**Comment by laura-hyesung-yang** [comment]
@Ruijun-Dang Hi Ruijun, I am experiencing very similar issue with my v13.3.4. Could I ask how you implemented code to skip one day from convection process?

**Comment by Ruijun-Dang** [comment]
@laura-hyesung-yang Hi Laura, I didn't change any code. I just skipped that day, say 2022-01-01, by starting the simulation from 2022-01-02 and changing the original restart file name and timestamp from 2022-01-01 to 2022-01-02. Hope this works for your problem!

**Comment by laura-hyesung-yang** [comment]
@Ruijun-Dang Ah I see! Thank you, Ruijun! I was starting my simulation on April 1st and it brutally failed. But when I start on different day, it seems to work! Maybe this blow up concentration occurs on specific day due to transport or convection and we just have to avoid that day. Thanks for the tip!
