### ISSUE TITLE
[FEATURE REQUEST] Reactivity rate diagnostics

### ISSUE THREAD

**Issue by lizziel** [geoschem/geos-chem#134]
There is a reactivity rate diagnostic in the GEOS version of GEOS-Chem which would be useful to the GEOS-Chem community in the standard model.  It is the set of 3D arrays containing reaction rate coefficients for each chemistry reaction. 

For example, the gas-phase reaction O3 + NO = NO2 + O2 has an associated equation rate calculated in KPP as A(1) = RCT(1)*V(229)*V(239) where,

- V(229) is concentrations of variable species (local) NO

- V(239) is concentrations of variable species (local) O3

- RCT is rate constants (local)

 
The diagnostic would be the set of A arrays.

**Comment by yantosca** [comment]
This update has been added to 12.7.0, with the following commits: https://github.com/geoschem/geos-chem/commit/bdcf78ed9f7e61fe0eb112dc1f022bd4a0ff87a0, https://github.com/geoschem/geos-chem/commit/6d33375b4db3a12ad13e396207c8dabcdc0e81db, https://github.com/geoschem/geos-chem/commit/6ca463ff6022618e27923e4804bb470b51ef89c5, https://github.com/geoschem/geos-chem/commit/3dfc382b8feb2bcf13103ed27dc27fe670f7a72b, https://github.com/geoschem/geos-chem/commit/6e831c54cd091125772195a86c2cb9ad69849ea6, https://github.com/geoschem/geos-chem/commit/8e1605af1b2861aa2e6f07c350e5199b4534eedb, https://github.com/geoschem/geos-chem/commit/b8866edf0a279da0aba12abb3d5050486d8e3c32, https://github.com/geoschem/geos-chem/commit/8cc9e155eacc0ef697c498ced9df17766687dd27, https://github.com/geoschem/geos-chem/commit/0a19e43dc7e5afb9bb5091eafb74a8ea3c9c06e1

**Comment by lizziel** [comment]
Besides the reaction rates diagnostics, the OH reactivity diagnostic will also be added.  OH reactivity is computed by parsing the KPP mechanism and combining all reactions that consume OH into a single ‘rate’, which is the OH consumption. Christoph originally created it for the ATOM campaign.

**Comment by lizziel** [comment]
The reaction rate diagnostics will be functional but silent in 12.7. Besides being off by default, they will not be included in HISTORY.rc until a future version in which dynamic allocation of the state_diag reaction rates array is possible. As is, if the reaction rate diagnostic is requested for one or more equations then the diagnostic array is allocated for ALL equations. For the standard full chemistry run this translates to 750 3D 72-level arrays. This is a big memory burden and therefore not recommended unless memory is not a limiting factor. The OH reactivity diagnostic does not have this problem but will also be left out of HISTORY.rc until the reaction rate diagnostics per equation are dynamically allocated.

To enable the OH reactivity diagnostic as well as reaction rate diagnostics for ALL equations, include the following in HISTORY.rc:
```
#====================================================================
# %%%%% THE RxnRate COLLECTION %%%%%
# Reaction rate per KPP equation, and OH reactivity
# Available for all full-chemistry simulations
#====================================================================
  RxnRate.template:           '%y4%m2%d2_%h2%n2z.nc4',
  RxnRate.format:             'CFIO',
  RxnRate.frequency:          010000
  RxnRate.duration:           010000
  RxnRate.mode:               'time-averaged'
  RxnRate.fields:             'OHreactivity           ', 'GIGCchem',
                              'RxnRate_?RXN?          ', 'GIGCchem',
::
```
To output reaction rates for certain equations, replace wildcard ?RXN? with EQ followed by equation number within 3 digits. You can look up the equation number per equation in gckpp_Monitor.F90. For example:
```
  RxnRate.fields:             'RxnRate_EQ001          ', 'GIGCchem',
                              'RxnRate_EQ032          ', 'GIGCchem',
                              'RxnRate_EQ421          ', 'GIGCchem',
```
