### ISSUE TITLE
which species should I use If I want to simulate CO2

### ISSUE THREAD

**Issue by zha-hash** [geoschem/geos-chem#1341]
### Ask a question about GEOS-Chem:
Hi, I want to simulate CO2 concentration using Geoschem. I remember in old version Geoschem11-01, I can directly choose CO2 species. However, in the latest version GCHP 13.4 I can only see three types: full chemistry, transport tracer, carbon flux. I am wondering which option should I choose?

**Comment by lizziel** [comment]
Hi @zha-hash, the carbon simulation is not yet available in GCHP. For now you can use GEOS-Chem Classic, or you can wait for it to be available in GCHP. @yantosca is currently working on moving the carbon chemistry to KPP. After this is complete we will make a carbon run directory available for GCHP and you will be able to simulate CO2 in GCHP the same way you will be able to in GEOS-Chem Classic. We hope to have this available by the end of the year.

**Comment by zha-hash** [comment]
> Hi @zha-hash, the carbon simulation is not yet available in GCHP. For now you can use GEOS-Chem Classic, or you can wait for it to be available in GCHP. @yantosca is currently working on moving the carbon chemistry to KPP. After this is complete we will make a carbon run directory available for GCHP and you will be able to simulate CO2 in GCHP the same way you will be able to in GEOS-Chem Classic. We hope to have this available by the end of the year.

Thank you so much for your reply. I will try GEOS-Chem Classic firstly. When GCHP is ready, I will use it.
