### ISSUE TITLE
[BUG/ISSUE] data not writing to restart files

### ISSUE THREAD

**Issue by bsuther** [geoschem/geos-chem#1342]
### What institution are you from?
North Carolina State University

### Description of the problem
Restart files are being created, however no data is being written to them. I started a 1 year simulation for 2013, Restart files were successfully created for February and March and had data as expected, however all of the variables in the file created for April were empty. The run stopped in Mid April due to time limits on my hpc. 

### Description of troubleshooting performed
I restarted my simulation from the last successful restart created, GEOSChem.Restart.20130301_0000z.nc4 and ran it through May 5th. It once again created Restart files for April and May. This time the April restart was populated with, but the second one in May did not. Am I just misunderstanding when the data gets written to the files? Does the data not get written until the end of the month, despite the restart being for the first of the month? If that is the case, could you please explain the logic of this to me? I was my understanding that the restart file should represent the state of the system for that date, not for the average for the entire month.  If you could help me understand what is going on I would really appreciate it. If this is the expected behavior, can you make any suggestion for how I should modify my runs to be more efficient? Currently I am only able to complete about 65 days before my run times out and since it isn't writing the first new restart until the end of the month and is not able to complete more than two months I am essentially having to do two month of computing for each month and then restart it a month back. Thanks for your help!

### GEOS-Chem version
13.4.0

### Description of modifications
No modifications.

### Log files
[GC.log](https://github.com/geoschem/geos-chem/files/9291263/GC.log)

[GEOSChem.Restart.20130501_0000z.zip](https://github.com/geoschem/geos-chem/files/9291268/GEOSChem.Restart.20130501_0000z.zip)

[HISTORY.zip](https://github.com/geoschem/geos-chem/files/9291272/HISTORY.zip)

[out.zip](https://github.com/geoschem/geos-chem/files/9291284/out.zip)

### Software versions
- CMake version: cmake/3.19.0
- Compilers (Intel or GNU, and version): intel/2018.2.199
- NetCDF version: netcdf/4.6.1-intel2017

**Comment by yantosca** [comment]
Thanks @bsuther for writing.  It may be that the HISTORY diagnostics isn't closing instantaneous files until the next file is opened.  I had thought we fixed that behavior but I can doublecheck.

In the meantime you may want to submit monthly jobs, since there seems to be enough time in your computational queue for these runs.  That would better ensure that you get restart file output.

**Comment by bsuther** [comment]
Thank you @yantosca, that is a good idea. If the issue is it waiting until the next file is opened, is it fair to assume that just changing the simulation length won't fix the problem, but changing the HISTORY.rc file to 
Restart.frequency:          'End',
Restart.duration:           'End',
and adjusting the end date would?
Thanks for looking into this!

**Comment by yantosca** [comment]
Hi @bsuther.  So I set up a very quick run (with 13.4.1) for a day and a half with the CH4 simulation (which is fast to run).  I specified `00000001 000000` for both `Restart.frequency and Restart.duration`.  This should produce a restart file after the frist day but not at the end of the run (1.5 days elapsed time).

After the run, I found everything as expected.  The `GEOSChem.Restart.201902_0000z.nc4` was created at the start of the 2nd day, but there was no restart file at the end-of-run.:

```console
archiveRun.sh*     GC.log                               HISTORY.rc
build/             GEOSChem.Restart.20190101_0000z.nc4  input.geos
build_info/        GEOSChem.Restart.20190102_0000z.nc4  metrics.py*
cleanRunDir.sh*    getRunInfo*                          OutputDir/
CodeDir@           HEMCO_Config.rc                      README
core.27376         HEMCO_Config.rc.gmao_metfields       rundir_vars.txt
download_data.py*  HEMCO_Diagn.rc                       rundir.version
download_data.yml  HEMCO.log                            runScriptSamples@
gcclassic*         HEMCO_restart.201901021200.nc        species_database.yml
```
And the restart file definitely had non-zero data in the `SpeciesRst_CH4` variable:

![rst](https://user-images.githubusercontent.com/5880296/183943252-88ce8254-2b49-4d2a-89e6-e14d231ab9b5.png)

I was also able to get debug printout for the `SpeciesRst` collection by setting  `Turn on debug printout: T` in `input.geos`:

```console
===============================================================================
DEFINED DIAGNOSTIC COLLECTIONS:
===============================================================================
 Collection        Restart
   -> FileName     ./GEOSChem.Restart.%y4%m2%d2_%h2%n2z.nc4
   -> Format       not found
   -> Frequency    00000001000000
   -> Duration     00000001000000
   -> Mode         instantaneous
 ------------------------------------------------------------------------------
 ------------------------------------------------------------------------------
 Container Name   : Restart
 Container Id #   :               1
...
 UpdateMode       : instantaneous
 UpdateYmd        :        00000001
 UpdateHms        :          000000
 UpdateIvalSec    :           86400.0
 UpdateAlarm      :           86400.0
 Operation        : Copy from source      
 HeartBeatDtSec   :             600.0
...
 FileWriteYmd     :        00000001
 FileWriteHms     :          000000
 FileWriteIvalSec :           86400.0
 FileWriteAlarm   :           86400.0
 FileCloseYmd     :        00000001
 FileCloseHms     :          000000
 FileCloseIvalSec :           86400.0
 FileCloseAlarm   :               0.0
 ... 
 Items archived in this collection:
  Met_TMPU1            | Instantaneous temperature at time=T | xyz | K
  Met_SPHU1            | Instantaneous specific humidity at  | xyz | g kg-1
  Met_PS1DRY           | Dry surface pressure at dt start    | xy  | hPa
  Met_PS1WET           | Wet surface pressure at dt start    | xy  | hPa
  Met_DELPDRY          | Delta-pressure across grid box (dry | xyz | hPa
  SpeciesRst_CH4       | Dry mixing ratio of species CH4     | xyz | mol mol-1 dry
===============================================================================
```
The `Restart.frequency` setting is copied to `FileWriteAlarm` and `Restart.duration` is `FileCloseAlarm`.  Both of these are set to 1 day based on what I defined in the restart file.  So we are closing the previous restart file when we should -- based on the setting of the `Restart.duration`.  We are not waiting for the next file to be opened before closing the file.

So I'm not sure what happened.  You might try to get the debug output for the collection like I did and see if it's any different from what is printed above.

Also tagging @Jourdan-He for reference.

**Comment by yantosca** [comment]
@bsuther: For monthly output we recommend:

```console
Restart.frequency:  00000100 000000
Restart.duration:  00000100 000000`
```
which will generate a restart file each month, regardless of the simulation length.  But if you are doing monthly runs, then 

```console
Restart.frequency:  'End'
Restart.duration:  'End'
```
should also work.

**Comment by bsuther** [comment]
I did the debug output, and I think they seem to be correct in mine as well. 

> ===============================================================================
DEFINED DIAGNOSTIC COLLECTIONS:
===============================================================================
 Collection        Restart
   -> FileName     ./GEOSChem.Restart.%y4%m2%d2_%h2%n2z.nc4
   -> Format       not found
   -> Frequency    00000100000000
   -> Duration     00000100000000
   -> Mode         instantaneous
------------------------------------------------------------------------------
 ------------------------------------------------------------------------------
 Container Name   : Restart
 Container Id #   :               1
 nX               :             144
 nY               :              91
 nZ               :              72
 nB               :               2
 EpochJsec        :    212234126400.0
 EpochJd          :         2456413.5
 CurrentJSec      :    212234126400.0
 CurrentJd        :         2456413.5
 CurrentYmd       :        20130501
 CurrentHms       :          000000
 ElapsedSec       :               0.0
 UpdateMode       : instantaneous
 UpdateYmd        :        00000100
 UpdateHms        :          000000
 UpdateIvalSec    :         2678400.0
 UpdateAlarm      :         2678400.0
 Operation        : Copy from source      
 HeartBeatDtSec   :             600.0
 ReferenceYmd     :        20130501
 ReferenceHms     :          000000
 ReferenceJsec    :         2456413.5
 ReferenceJd      :         2456413.5
 FileWriteYmd     :        00000100
 FileWriteHms     :          000000
 FileWriteIvalSec :         2678400.0
 FileWriteAlarm   :         2678400.0
 FileCloseYmd     :        00000100
 FileCloseHms     :          000000
 FileCloseIvalSec :         2678400.0
 FileCloseAlarm   :               0.0

**Comment by yantosca** [comment]
@bsuther: could it have been a quirk of the LSF scheduler on your system?

**Comment by bsuther** [comment]
Hmm I am not sure. It is certainly possible. The behavior is consistent on my end. I will probably keep doing shorter runs to be safe until I figure out what is going on.
