### ISSUE TITLE
[QUESTION]How to run multiple CO2 simulations?

### ISSUE THREAD

**Issue by helpyuan** [geoschem/geos-chem#1349]
### Ask a question about GEOS-Chem:
Hi all,

I want to use multiple scale factors to simulate multiple CO2 concentrations. 

In general, if I run a CO2 simulation, I only need to configure some inventories (such as fossil fuel, biomass burning, biosphere exchange, ocean exchange and so on) in the HEMCO_Config.rc.

And now, I want to run 20 CO2 simulations (named CO2_01, CO2_02, ..., CO2_20) with 20 different biosphere exchange scale factors at a time. 

Can this be implemented in GEOS Chem v13.3.2? If feasible, which file do I need to modify?

I appreciate any help.

**Comment by yantosca** [comment]
Thanks for writing @helpyuan.  I think it would be simpler to set up 20 run directories for the CO2 simulation and then change the scale factor in each run directory.  Then you could run 20 simulations independently of each other.

For example, if you have 40 cores on your computational node, you can set up each job to run with 2 cores (i.e. `export OMP_NUM_THREADS=2` and then submit 20 jobs simultaneously).

**Comment by helpyuan** [comment]
Thanks for replying @yantosca ! I have already done  so.

**Comment by yantosca** [comment]
No problem @helpyuan!  I'll close out this issue now.  Feel free to create a new issue if you are still having problems.
