### ISSUE TITLE
[BUG/ISSUE] Negative values for SALCAL in nested simulation

### ISSUE THREAD

**Issue by chfite** [geoschem/geos-chem#1351]
### Description of the problem
I am running GCClassic 13.3.4 (with a few cherry-picked updates from 13.4). I am getting negative value warnings for SALCAL on 20191228 at 9:35 UTC for 50 or so grid cells before  `DO_TEND` errors in `mixing_mod.F90` and kills my simulation. This appears to be a similar issue to https://github.com/geoschem/geos-chem/issues/1138, https://github.com/geoschem/geos-chem/issues/969, https://github.com/geoschem/geos-chem/issues/734, and https://github.com/geoschem/geos-chem/issues/584 except those did not have the issue occurring with SALCAL. Based on those posts it seems that my options to fix the issue are either  1) change the `Background_VV` in `species_database.yml`, 2) flush the values to zero if they are negative (like it used to?) , 3) adjust the time steps (I am already using 300/600 and probably wouldn't want to change this part way through my simulations).

If I go option 1, changing the `Background_VV` in `species_database.yml`, it looks like I will have to add this to the `SALC_PROP` category which is applied to all SALC species. There is currently no `Background_VV` provided there, so is it acceptable for me to add one? The only other aerosol I see with a `Background_VV` provided is HMS, which uses a value of 1.0e-15. Would that be an acceptable value to use for SALCAL?

If I go option 2,  forcing negative values to 0, this would be an easy fix, but I thought I would ask whether it is advisable to choose this over adding `Background_VV` like option 1? It looks like https://github.com/geoschem/geos-chem/issues/734 fixed their issue by reverting the check-and-error for negative values back to the method of forcing the values to 0. However, https://github.com/geoschem/geos-chem/issues/584, which preceded https://github.com/geoschem/geos-chem/issues/734, suggested the importance of not just forcing values to 0 for mass balance reasons and is the reason the model now kills when negative values occur.

### Description of troubleshooting performed
I have a test simulation to duplicate the error running right now with `Verbose: 3` set. I can post any log or configuration files if you feel they are needed but based on the past issues it sounds like my fix will be one of the options above.

**Comment by chfite** [comment]
I have since done a test using `Background_VV: 1.0e-15` for SALCAL and I still end up with negative values

**Comment by yantosca** [comment]
Thanks for writing @chfite.  The `BackgroundVV` defaults to 1.0e-20 if a value is not specified in the species database.  

This output shows the min & max concentration from one of our recent 1-hour benchmark simulations (see http://s3.amazonaws.com/benchmarks-cloud/benchmarks/1Hr/gcc/gcc-4x5-1Hr-14.0.0-rc.1-1-gb8cca7f/RunGCC.txt) 

```console
Species 213,     SALA: Min = 4.400660732E-33  Max = 3.728070741E-09  Sum = 1.185665315E-05
Species 214,   SALAAL: Min = 0.000000000E+00  Max = 7.886570286E-10  Sum = 6.705845976E-07
Species 215,   SALACL: Min = 0.000000000E+00  Max = 1.688765239E-09  Sum = 2.925773515E-06
Species 216,     SALC: Min = 5.093551762E-40  Max = 7.496031174E-08  Sum = 1.175813304E-04
Species 217,   SALCAL: Min = 0.000000000E+00  Max = 4.060052206E-08  Sum = 5.068803875E-05
Species 218,   SALCCL: Min = 6.454858122E-31  Max = 3.607224031E-08  Sum = 5.558129851E-05
```
So you could try setting `BackgroundVV` to something in the range of 1e-10 to 1e-8 and see if you get past the error.

Also tagging @Jourdan-He

**Comment by yantosca** [comment]
Also, I believe SALCAL etc. are in the restart files in this folder. 
You can trry using those to initialize your simulation. http://geoschemdata.wustl.edu/ExtData/GEOSCHEM_RESTARTS/v2021-09/

**Comment by jdshutter** [comment]
@chfite Did you try setting `Background_VV` to something in the range of 1e-10 to 1e-8 as recommended by @yantosca from the benchmark simulations to fix the error? I just noticed the same error in my (nested grid) production runs and can't just swap out my already spun up restart file or change the time steps halfway through my production run. It's happening to me for both NO and SALCAL depending on the domain I'm simulating.

**Comment by chfite** [comment]
@jdshutter I believe I tried setting `Background_VV` to 1e-10 for SALCAL but still received the error. I ended up going the route of just forcing the negative value to 0, which isn't ideal since that was the old approach to that issue, but I don't think it would affect results of my simulation greatly for the species used in my own research. You might try a test with that magnitude to see if it works for you.

**Comment by yantosca** [comment]
Closing out this issue as it seems that it is resolved by setting the negatives to zero in this case.

**Comment by Alex-Fang66** [comment]
@jdshutter Did you figure out why appears the negative values of NO and SALCAL? My nested simulation encountered similar problems.

**Comment by jdshutter** [comment]
@Alex-Fang66 So I changed the default time steps in input.geos to 300 and 600 s for transport/convection and chemistry/emission, respectively, instead of using the default 600 and 1200 s. That fixed the problem on my end, but it appears folks have also just forced the value to 0 when something goes negative. Of course, decreasing the value of the time step makes the simulation go longer...
