### ISSUE TITLE
[FEATURE REQUEST] Maintaining Documentation for Recent Model Versions

### ISSUE THREAD

**Issue by cdholmes** [geoschem/geos-chem#1359]
### Request a new GEOS-Chem feature:
It would be very helpful if documentation could be maintained for recent model versions. 

It seems that we are losing documentation for prior versions as soon as a new version comes out (or even before). Since many users continue to use a single version for the duration of a research project (commonly 1-2 years), I think there is a need to retain information on how to use recent prior versions.  

For example, I am running version 13.4 and I am looking at the ["Configure your simulation"](https://geos-chem.readthedocs.io/en/latest/gcc-guide/03-config/geoschem-config.html) on readthedocs.io. As you know, version 13.4 and all prior versions of GEOS-Chem use input.geos to configure many simulation options. The documentation page describes "geoschem_config.yml" and doesn't mention the input.geos file. I think the yml file is used in version 14.0, which isn't even released yet, so the documentation is out of step with what most users will need. 

It appears that readthedocs.io has the capability to display documentation for multiple versions, which the user can select on the lower left corner of the webpage. That would be ideal. If the documentation for older versions is already retained somewhere, then I think directing users to it would be helpful. 

Thanks!

**Comment by yantosca** [comment]
Thanks for writing @cdholmes.  Most of the RTD doc for GC and HEMCO wasn't written before 14.0.0.  So going forward we will have the ability to preserve older versions.

The [Getting Started with GEOS-Chem]{http://wiki.geos-chem.org/Getting_Started_with_GEOS-Chem} wiki manual has been updated to point to the https://geos-chem.readthedocs.io where content is the same between versions 13 and 14.  Sections that are specific to older versions (eg. like the `input.geos` description) have been preserved there.

**Comment by yantosca** [comment]
Good point @cdholmes.  I'll fix it.

**Comment by yantosca** [comment]
Now fixed in http://wiki.geos-chem.org/Getting_Started_with_GEOS-Chem.
