### ISSUE TITLE
[QUESTION] Applying scale factors to non-emissions data

### ISSUE THREAD

**Issue by ShutingZhai** [geoschem/geos-chem#136]
I added a scale factor for Stratospheric Bry emissions in HEMCO_Config for my historical simulations, and was wondering if I need to call HCO_EvalFld instead of HCO_GetPtr in Set_BryPointers in strat_chem_mod.F, similar as described in the wiki(http://wiki.seas.harvard.edu/geos-chem/index.php/HEMCO_examples#Applying_scale_factors_to_non-emissions_data). Since it's a nonemission data, I assume I should. But I'm not sure how to set the output array for HCO_EvalFld. Unlike wiki, this module doesn't have an existing field to store the output of HCO_EvalFld. Should I create an Arr3D_day/ Arr3D_night array to save out the fields and store them to State_Chm? Could you suggest a way to do this? Thanks!

**Comment by yantosca** [comment]
Thanks for writing.  I believe with non-emissions data that you would have to scale those manually, so I'm not sure Hco_EvalFld would work.  

Maybe what you could do is to add a field to the PL_Pointers type:

```F90
  ! PL_Pointers is a derived type to hold pointers to the production
  ! and loss fields
  TYPE :: PL_Pointers
     REAL(f4), POINTER  :: PROD(:,:,:) => NULL() ! Production rate [v/v/s]
     REAL(f4), POINTER  :: LOSS(:,:,:) => NULL() ! Loss frequency [s-1]
     REAL(f4), POINTER :: ScaleFac(:,:) => NULL()
  END TYPE PL_Pointers 
```

and then use e.g. BrPtrDay(N)%ScaleFac and BrPtrNight(N)%ScaleFac to hold the scale factors.  Then you can multiply the prod/loss by those as needed.
