### ISSUE TITLE
[BUG/ISSUE] CMIP6 Input Files Missing on WUSTL

### ISSUE THREAD

**Issue by IshirDutta** [geoschem/geos-chem#1363]
### What institution are you from?
MIT

### Description of the problem
@LiamBindle just a quick heads up that the latest CMIP6 files haven't been synced to WashU / Harvard servers from the [Rochester server](http://atmos.earth.rochester.edu/input/gc/ExtData/HEMCO/CMIP6/)

### GEOS-Chem version
v13.3.4

**Comment by msulprizio** [comment]
This is intentional, at least at Harvard. We recommend getting those files directly from Rochester as they host the data needed for simulations using GCAP2.0 and for running future/historical scenarios.

**Comment by IshirDutta** [comment]
Copy that, thanks @msulprizio!
