### ISSUE TITLE
How to determine species order in  RTODAER or ODAER [QUESTION]

### ISSUE THREAD

**Issue by bsuther** [geoschem/geos-chem#1366]
### Ask a question about GEOS-Chem:
Hello,
I am attempting to make a modification in GeosCore/rrtmg_rad_transfer_mod.F90 where I change a certain input to rrtmg_sw based on the optical depths for black carbon, organic carbon, sulfate etc. My understanding is that I want to use the RTODAER variable and that the 4th dimension corresponds to the wavelength and the 5th dimension corresponds with the species. I am just not sure how to determine what wavelength RTODAER(:,:,:,X,:) would be or what species RTODAER(:,:,:,:,X) would be. Can you point me in the right direction? My assumption is that I need to do something similar to lines 1214 - 1248 in GeosCore/aerosol_mod.F90, but I am not sure what would be the appropriate database to query. I am using version 13.4.0.
Thank you!
Beth

**Comment by bsuther** [comment]
Update: I found that in the Set_SpecMask subroutine (lines 1736 to 1739 of GeosCore/rrtmg_rad_transfer_mod.F90) it says
`    !ISPECRADMENU IS THE INDEX OF THE SPECIES WITHIN THE INPUT MENU
    !THE INDEX OF SPECMASK INDICATES THE POSITION OF THE SPECIES IN
    !THE RT OPTICS ARRAY FOR THE AEROSOL
    !E.G. SO4 = 1 I.E. RTODAER(*,*,*,*,1)`
So if I understand that correctly and combine it with the rest of the lines in Set_SpecMask I get that the species are: 
RTODAER(*,*,*,*,1) = Sulfate
RTODAER(*,*,*,*,2) = nitrate
RTODAER(*,*,*,*,3) = ammonium
RTODAER(*,*,*,*,4) = black carbon (hydrophilic + phobic)
RTODAER(*,*,*,*,5) = organic aerosol (hydrophilic + phobic)
RTODAER(*,*,*,*,6) = Sea salt
RTODAER(*,*,*,*,7) = Sea salt
RTODAER(*,*,*,*,8:7+NXTRA) = extra species
RTODAER(*,*,*,*,8+NXTRA) = Dust
RTODAER(*,*,*,*,9+NXTRA) = Dust
RTODAER(*,*,*,*,10+NXTRA) = Dust 
RTODAER(*,*,*,*,11+NXTRA) = Dust
RTODAER(*,*,*,*,12+NXTRA) = Dust
RTODAER(*,*,*,*,13+NXTRA) = Dust
RTODAER(*,*,*,*,14+NXTRA) = Dust
RTODAER(*,*,*,*,15+NXTRA) = Ozone
RTODAER(*,*,*,*,16+NXTRA) = Methane
correct? However, I am still having a hard time determining what the wavelengths are. 
Thanks!

**Comment by yantosca** [comment]
Also tagging @sdeastham, who has worked on RRTMG in the past.

**Comment by bsuther** [comment]
Hello, 
I just wanted to check in as I am still hoping I can receive help figuring out how to verify which indexes correspond to what wavelengths. Thank you.

**Comment by yantosca** [comment]
Hi @bsuther, thanks for checking in.  The GCST doesn't have a lot of experience with RRTMG so maybe @sdeastham is the best person to reply.

**Comment by sdeastham** [comment]
Hi all - unfortunately I'm not sure how to check the wavelengths used. I am vaguely aware that the wavelengths at which OD are output should correspond to those chosen in the GC input file, but beyond this I'm afraid it's not something I've ever experimented with. I suspect that to change the absorption and scattering behavior, you would instead need to change how the aerosols themselves are represented within RRTMG, but I am far from certain. My apologies!

**Comment by yantosca** [comment]
This might also be a question for the Aerosols Working Group.  @beckyalexander @wporter @jeffpierce.  Maybe they know who would be the best person to ask.
