### ISSUE TITLE
Could we simulate global CO2 at 0.5*0.625?

### ISSUE THREAD

**Issue by zha-hash** [geoschem/geos-chem#1371]
### Ask a question about GEOS-Chem:
I tried to simulate CO2 with GCClassic 13.4.1. I used the ./createRunDir.sh to setup the run directory using parameters below:
Choose simulation type: CO2
Choose meteorology source: MERRA-2
Choose horizontal resolution：0.5*0.625
Choose horizontal grid domain: Global
Choose number of levels: 72

Then I have download all the related data and tried to run the program using ./gcclassic. The following error will appear.

At line 1048 of file codeDir/src/GEOS-Chem/GeosCore/input_mod.F90
Fortran runtime error: Bad logical value while reading item 1

 
If I change the horizontal resolution to 2.0*2.5 or 4.0*4.5, it can simulate CO2 successfully. Or I change the horizontal grid domain  to Asia, it can run. But global 0.5*0.625, it always appear the above errors.

**Comment by msulprizio** [comment]
Can you upload your GEOS-Chem input.geos and log files? It sounds like one of the settings there is incorrect when attempting to run the global high-resolution simulation. 

To our knowledge, no one has attempted running GEOS-Chem at 0.5x0.625 resolution on a global domain. Typically that resolution is used with nested-grid domains. Theoretically it should be possible, but may be computationally expensive.

**Comment by zha-hash** [comment]
Hi msulprizio,

Thank you very much for your reply. I think you are right. I doubt that  longitute  or lagitude's settings in global 0.5*0.625 simulation may be incorrect and the errors seemed to location setting out ot range. My server memory should be enough to run global 0.5*0.625 simulation.

I cannot find the log in the OutputDir and it is empty. I try to save the error on the screen in the file"errors. docx" and upload input.geos.log. 

[input.geos.log](https://github.com/geoschem/geos-chem/files/9531868/input.geos.log)
[errors.docx](https://github.com/geoschem/geos-chem/files/9531869/errors.docx)

**Comment by zha-hash** [comment]
> Can you upload your GEOS-Chem input.geos and log files? It sounds like one of the settings there is incorrect when attempting to run the global high-resolution simulation.
> 
> To our knowledge, no one has attempted running GEOS-Chem at 0.5x0.625 resolution on a global domain. Typically that resolution is used with nested-grid domains. Theoretically it should be possible, but may be computationally expensive.
Hi msulprizio,

Thank you very much for your reply. I think you are right. I doubt that longitute or lagitude's settings in global 0.50.625 simulation may be incorrect and the errors seemed to location setting out ot range. My server memory should be enough to run global 0.50.625 simulation.

I cannot find the log in the OutputDir and it is empty. I try to save the error on the screen in the file"errors. docx" and upload input.geos.log.
[errors.docx](https://github.com/geoschem/geos-chem/files/9531885/errors.docx)
[input.geos.log](https://github.com/geoschem/geos-chem/files/9531886/input.geos.log)

**Comment by yantosca** [comment]
Thanks for writing @zha-hash.  In your `input.geos` file, the grid menu has this line:
```console
%%% GRID MENU %%%       :
Grid resolution         : 0.5x0.625
Longitude min/max       : -180.0 180.0
 Center on 180E/W?      : T
Latitude  min/max       :  -90.0  90.0
 Half-sized polar boxes?: ${RUNDIR_GRID_HALF_POLAR}
Number of levels        : 72
Nested grid simulation? : F
 Buffer zone (N S E W ) : 0  0  0  0
```
The `${RUNDIR_GRID_HALF_POLAR}` should have been replaced with `T`, but this somehow was not done.  Try making the edit manually and re-running your simulation.

**Comment by zha-hash** [comment]
> 



> Thanks for writing @zha-hash. In your `input.geos` file, the grid menu has this line:
> 
> ```
> %%% GRID MENU %%%       :
> Grid resolution         : 0.5x0.625
> Longitude min/max       : -180.0 180.0
>  Center on 180E/W?      : T
> Latitude  min/max       :  -90.0  90.0
>  Half-sized polar boxes?: ${RUNDIR_GRID_HALF_POLAR}
> Number of levels        : 72
> Nested grid simulation? : F
>  Buffer zone (N S E W ) : 0  0  0  0
> ```
> 
> The `${RUNDIR_GRID_HALF_POLAR}` should have been replaced with `T`, but this somehow was not done. Try making the edit manually and re-running your simulation.

Thank you so much. You are right. When I replaced ${RUNDIR_GRID_HALF_POLAR} with T, it can run.   However,  it has another new problem "out of memory". Do you know what is the minimum memory requirement when we simulate global CO2 at 0.5*0.625? Currently my server memory is 128 G.

**Comment by yantosca** [comment]
Thanks for the feedback @zha-hash.  We have never run the CO2 simulation at that resolution so we cannot say.  You can try to reduce the number of diagnostics that are archived to disk (both the HISTORY diagnostics and the HEMCO diagnostics) and see if you get past the out-of-memory error.

**Comment by yantosca** [comment]
Also tagging @Jourdan-He and @SaptSinha for reference

**Comment by yantosca** [comment]
Closing out this issue
