### ISSUE TITLE
[QUESTION] KPP failed to build gckpp_Rates.F90

### ISSUE THREAD

**Issue by yangning-code** [geoschem/geos-chem#1374]
### Ask a question about GEOS-Chem:
When I use kpp.3.0.0 to generate a new mechanism in version 1, the error is as follows:KPP failed to build gckpp_Rates.F90! Aborting.
The details are in the attached figure
![error](https://user-images.githubusercontent.com/51811371/190031464-1dd85cc7-8a1e-4e73-8b13-b7bad57da6d7.png)

**Comment by yantosca** [comment]
Thanks for writing @yangning-code.  Please see issue #1372 for a solution.

**Comment by yantosca** [comment]
I'll close out this issue as it is a duplicate of #1372.

**Comment by yangning-code** [comment]
Where can I download KPP.2.3.0?
