### ISSUE TITLE
[QUESTION] How does oxidant concentration in Hg simulation go from monthly to daily ？

### ISSUE THREAD

**Issue by sunxianyi** [geoschem/geos-chem#1376]
### Ask a question about GEOS-Chem:
I have a question about the Hg simulation: in HEMCO, the input oxidant concentration is the monthly average concentration, but in fact, some oxidants have strong daily concentration changes. May I ask how the Hg simulation in GEOS-Chem deals with this problem? thank you！

**Comment by yantosca** [comment]
Thanks for writing @sunxianyi.  Specialty simulations such as Hg are set up to use monthly mean oxidant fields by default.  These are taken from the most recent GEOS-Chem 10 year benchmark simulation.  If you need more frequent oxidant fields than monthly, then you can set up a GEOS-Chem full-chemistry simulation to archive fields at daily or hourly resolution.  But typically we find the monthly-mean data is sufficient.

Also tagging @arifein @cdholmes @jennyfisher @yanxuz for comment

**Comment by sunxianyi** [comment]
Thank you for your reply @yantosca . I will use the full-chem simulation to get the step size of the oxidant concentration I need, and then input it into the Hg simulation. Thank you again, wish everything goes well with your work!

**Comment by yantosca** [comment]
Thanks @sunxianyi!  I'll close out this issue now.  Best to you.
