### ISSUE TITLE
[QUESTION] Where can I download AEIC2019 emissions?

### ISSUE THREAD

**Issue by yangning-code** [geoschem/geos-chem#1377]
### Ask a question about GEOS-Chem:
Where to download AEIC2019 emisssion input data？

**Comment by yantosca** [comment]
Thanks for writing @yangning-code.  You can download this data from: 
http://geoschemdata.wustl.edu/ExtData/HEMCO/AEIC2019/

Also see our new GEOS-Chem manual at geos-chem.readthedocs.io for more information:
https://geos-chem.readthedocs.io/en/latest/gcc-guide/04-data/input-overview.html
