### ISSUE TITLE
[QUESTION]Oxidant's horizontal resolution and vertical resolution in Hg simulation

### ISSUE THREAD

**Issue by sunxianyi** [geoschem/geos-chem#1379]
### Ask a question about GEOS-Chem:
The Hg simulation requires an archive of oxidant concentrations (e.g. OH, Br) as an input. When the resolution of the oxidant concentration (horizontal resolution and vertical resolution) is not consistent with the resolution set for  Hg simulation. Does the model automatically regrid oxidant concentrations to the resolution of the mercury simulation?

**Comment by yantosca** [comment]
Thanks for the question @sunxianyi.  The Harmonized Emissions Component (HEMCO) will regrid input data such as emissions, met fields, and chemistry inputs (such as oxidants) from their native resolution to whichever resolution you are using with GEOS-Chem.  So you don't have to worry about data files being at one resolution and your GEOS-Chem simulation grid being at at another resolution.

For more information, please see our new HEMCO documentation at https://hemco.readthedocs.io.

**Comment by sunxianyi** [comment]
Thank you very much for your guidance and suggestions @yantosca ！

**Comment by yantosca** [comment]
Thanks much @sunxianyi.  I'll close out this issue now.
