### ISSUE TITLE
[QUESTION]OPOA alpha from carbon_mod.F90?

### ISSUE THREAD

**Issue by yangning-code** [geoschem/geos-chem#1381]
### Ask a question about GEOS-Chem:
OPOA alpha from carbon_mod.F90 is inconsistent with OPOA alpha from literature :A global perspective on aerosol from low-volatility organic compounds? 
Was it a number input error when writing the code?

具体内容如图所示：
![OPOA alpha from carbon_mod F90](https://user-images.githubusercontent.com/51811371/190962619-68971536-8b5d-4b03-9aed-256d5f2334ac.png)
![OPOA alpha from Pye et al 2010](https://user-images.githubusercontent.com/51811371/190962631-5502627e-6da0-4996-a513-e88693876fc6.png)

**Comment by yantosca** [comment]
Thanks for writing @yangning-code.  The `carbon_mod.F90` module has been around for a long time so I wonder if the alpha has changed recently.  In any case, this would be a question for the Aerosols Working Group, so I will tag the group co-chairs here: @theloniuspunk @beckyalexander @wporter

**Comment by yantosca** [comment]
Also tagging @Jourdan-He and @SaptSinha for reference

**Comment by yangning-code** [comment]
No changes, code taken from GEOS-Chem.14.0.0 @yantosca, and I think it should be changed to 1.5.

**Comment by theloniuspunk** [comment]
Hi Yangning,

Can you send the link to the paper that you showed the table from? I'm wondering if the key text in the code is the "note that this is the carbon yield" if the 1.5 is the yield of the total organics and if they are assuming that the carbon mass is 2/3 of the organic mass. 

Jeff

**Comment by yangning-code** [comment]
Thank you @theloniuspunk 
I didn't notice in the article that they are assuming that the 。carbon mass is 2/3 of the organic mass. Now I send you the link to the literature.[https://acp.copernicus.org/articles/10/4377/2010/](url).you check again

**Comment by yangning-code** [comment]
Hi @theloniuspunk 
I read this literature carefully today and found that your statement is true. You can check again if it is convenient.
Thanks

**Comment by theloniuspunk** [comment]
Yeah, not sure. My guess is that it got updated at some point. From a quick skim of these papers (https://acp.copernicus.org/articles/16/1603/2016/acp-16-1603-2016.pdf, https://acp.copernicus.org/articles/20/2637/2020/acp-20-2637-2020.pdf), I didn't see a mention of a change. 

Shantanu Jathar's group has been updating all of the yields to our recent understanding, but I don't think that their updates are in the code yet. 

Oh, I just see now that you wrote another comment that it is related to OA:OC.

**Comment by yangning-code** [comment]
[Pye, Seinfeld - 2010 - A global perspective on aerosol from low-volatility organic compounds.pdf](https://github.com/geoschem/geos-chem/files/9603453/Pye.Seinfeld.-.2010.-.A.global.perspective.on.aerosol.from.low-volatility.organic.compounds.pdf)
[Grieshop et al. - 2009 - Laboratory investigation of photochemical oxidation of organic aerosol from wood fires 1 Measurement and simula.pdf](https://github.com/geoschem/geos-chem/files/9603454/Grieshop.et.al.-.2009.-.Laboratory.investigation.of.photochemical.oxidation.of.organic.aerosol.from.wood.fires.1.Measurement.and.simula.pdf)
Have you read these two articles? SVOC in GEOS-Chem14.0.0 is still modified according to the contents of these two articles.

**Comment by yangning-code** [comment]
I don't know now if the ratio is 1 or 1.5？therefore, can you help determine if the ratio is 1 or 1.5?

**Comment by theloniuspunk** [comment]
@yangning-code I'm not sure. I haven't be able to find what they are assuming for OA:OC ratios. You may want to reach out to Eloise Marais.

I just pinged Shantanu Jathar to see if he was willing to share the updated scheme that's in review, "Bilsback, Kelsey; He, Yicong; Cappa, Christopher; Chang, Rachel; Croft, Betty; Martin, Randall ; Ng, Nga Lee; Seinfeld, John; Pierce, Jeffrey; Jathar, Shantanu: Vapors are Lost to Walls, Not to Particles on the Wall: Artifact-Corrected Parameters from Chamber Experiments and Implications for Global Secondary Organic Aerosol, submitted to Env. Sci. Tech, 2022."

**Comment by yangning-code** [comment]
I want to identify this issue sooner, who else can I contact to discuss this issue? @theloniuspunk

**Comment by theloniuspunk** [comment]
Eloise Marais and Sid Pai might have some ideas eloise.marais@leicester.ac.uk, sidhantp@mit.edu

**Comment by yangning-code** [comment]
Thanks @theloniuspunk

**Comment by yangning-code** [comment]
Hi @theloniuspunk
How can I contact the GC support team, they may be able to guide me on the specifics？

**Comment by theloniuspunk** [comment]
@yangning-code This is the place to do it. Bob @yantosca, who was the first to respond, is on the support team. I suspect they might not know the details here since this is more on the science side, which is why Bob pinged me and others.  I pinged him again here, so he can comment on if the support team can help.

Unfortunately, I have not personally used the complex OA scheme much (my group uses the simple SOA scheme since that's what works with the TOMAS aerosol microphysics). Will Porter (@wporter) might be the only aerosol working group chair who might have worked with the complex scheme in a hands-on way. 

I realize it's important to nail down what the values are and mean (e.g., is the yield multiplied by an OA:OC factor?), but there are a lot of uncertainty in the yields and our knowledge of OA has advanced since the Pye 2010 paper. I just remember that Jared Brewer (brewe222@umn.edu) had updated the scheme as well. I do not see his paper on this published yet.

**Comment by wporter** [comment]
I have worked with the complex SOA scheme, but unfortunately I don't have any additional insights on the origins and accuracy of this particular factor. I agree with @theloniuspunk that Eloise Marais and Sid Pai may be good contacts for more details here, as well as the team working on updated and corrected values for some of these SOA parameters.

**Comment by theloniuspunk** [comment]
Thanks, Will! @wporter

**Comment by yantosca** [comment]
Closing out this issue
