### ISSUE TITLE
[QUESTION] Where can I download KPP 2.3.0?

### ISSUE THREAD

**Issue by yangning-code** [geoschem/geos-chem#1382]
### Ask a question about GEOS-Chem:
Where can I download KPP.2.3.0?

**Comment by yantosca** [comment]
Thanks for writing @yangning-code.  This is available at the older repo: https://github.com/geos-chem/KPP.  Make sure you check out the GC_updates branch after cloning.

**Comment by yangning-code** [comment]
Thank you @yantosca
