### ISSUE TITLE
[QUESTION]Does gfortran10.2 support old GC code?

### ISSUE THREAD

**Issue by lshen2009** [geoschem/geos-chem#1384]
### Ask a question about GEOS-Chem:

Does gfortran10.2 support GEOS-Chem code before version 12.9? I am able to compile the code for version 13 and v14 in my new machine but not for v12. So I am back to my Harvard account and I get similar bugs. Thanks.

source ~/envs/gcc.gfortran10.2_cannon.env

If I compile the v12 code here:

/n/holyscratch01/jacob_lab/lshen/CH4/GEOS-Chem/Flexgrid_global/Code.CH4_Inv_for_Boundary_20220329/Pert_clean 

I get this error:

/bin/bash: /nc-config: No such file or directory
grep: /netcdf.inc: No such file or directory

**Comment by yantosca** [comment]
Thanks for writing @lshen2009.  It looks like the netCDF library environment is not being loaded.  Are you using CMake or GNU Make to compile?  If you are using CMake it should find the netCDF library automatically.  If you are using GNU Make, then you will need to set the following environment variables for Cannon:

```bash
export GC_BIN=$NETCDF_HOME/bin
export GC_INCLUDE=$NETCDF_INCLUDE
export GC_LIB=$NETCDF_LIB
export GC_F_BIN=$NETCDF_FORTRAN_HOME/bin
export GC_F_INCLUDE=$NETCDF_FORTRAN_INCLUDE
export GC_F_LIB=$NETCDF_FORTRAN_LIB
```

but if you can I would recommend compiling with CMake as described here: https://geos-chem.readthedocs.io/en/latest/gcc-guide/02-build/compile.html

**Comment by yantosca** [comment]
@lshen2009, has your issue been solved by setting the environment variables mentioned above?

**Comment by yantosca** [comment]
Closing out this issue
