### ISSUE TITLE
[QUESTION]How to deal with segmentation fault？

### ISSUE THREAD

**Issue by zhangziqi721** [geoschem/geos-chem#1390]
### Ask a question about GEOS-Chem:I found "yhrun: error: cn1832: task 0: Segmentation fault (core dumped)" and cannot find where the error is. There is no error about my configs and inputfiles in the log now. However, the model cannot run to its end and log shows me it has segmentation fault. Please tell me how to deal with it and make it. THANK U!
yhrun: error: cn1832: task 0: Segmentation fault (core dumped)
[log.zip](https://github.com/geoschem/geos-chem/files/9603523/log.zip)

**Comment by yantosca** [comment]
Thanks for writing @zhangziqi721.  I took a look at your log file and saw that the run stopped with a seg fault after the TPCORE initialization.  Please see this link for instructions on how to fix this issue: 

  - https://geos-chem.readthedocs.io/en/latest/gcc-guide/01-startup/login-env-parallel.html

**Comment by yantosca** [comment]
Also tagging @Jourdan-He and @SaptSinha for reference.

**Comment by yangbyy** [comment]
Hi, currently, I'm also experiencing this problem. Can you tell me how you solved this problem? @zhangziqi721  Thank you very much.
