### ISSUE TITLE
Units verification for Met_PHIS in History Diagnostic

### ISSUE THREAD

**Issue by chfite** [geoschem/geos-chem#1392]
I wanted to verify what the current units are for the StateMet history diagnostic variable `Met_PHIS`?

Based on #531, now when `flexgrid_read_mod.F90` reads in PHIS (originally as m2/s2) from GEOS-FP or MERRA-2 files, they are then divided by gravity to obtain surface altitude [m], and it is to be interpreted as such elsewhere in the model wherever `State_Met%PHIS ` is used in calculations (like in`planeflight_mod.f90`).

However, when I use output StateMet fields from the History diagnostics, the `Met_PHIS` variable says that it has units of (m2/s2) and it is labeled as surface geopotential height. Are those the actual units of PHIS when written in history output, or is this a mislabeling of units for the netcdf files? And is the intention for that output variable to be in m2/s2 or m?

If this is just a typo for the netcdf file unit definition, then I think all that would need changing is the line:
`PHIS:units              = m2 s-2`    in `NcdfUtil/perl/definitions_cn.rc`

**Comment by yantosca** [comment]
Thanks for writing @chfite.  In `GeosCore/flexgrid_read_mod` (in routine `Flexgrid_Read_CN`), the PHIS data gets converted from m2/s2 to m:
```F90
    ! Read PHIS
    v_name = "PHIS"
    CALL Get_Met_2D( Input_Opt, State_Grid, Q, TRIM(v_name) )
    State_Met%PHIS = Q

    ! Echo info
    stamp = TimeStamp_String( 20110101, 000000 )
    WRITE( 6, 10 ) stamp
 10 FORMAT( '     - Found all CN     met fields for ', a )

    !======================================================================
    ! Cleanup and quit
    !======================================================================

    ! Convert PHIS from [m2/s2] to [m]
    State_Met%PHIS = State_Met%PHIS / g0
```

I believe PHIS is not used for much in the model other than diagnostic output.

Also tagging @Jourdan-He and @SaptSinha

**Comment by chfite** [comment]
@yantosca Ok thank you for looking into it. If the diagnostic output is in [m] and not [m2 s-2] then that unit descriptor for the netcdf variable may need to be changed to reflect that conversion so that no one misinterprets it.

**Comment by yantosca** [comment]
Thanks @chfite, we can add that into an upcoming patch version.
