### ISSUE TITLE
[QUESTION]the oxygen-to-carbon ratio to affect the SOA yield

### ISSUE THREAD

**Issue by yangning-code** [geoschem/geos-chem#1393]
### Ask a question about GEOS-Chem:
Which code in the GEOS-Chem.13.3.2 will consider the oxygen-to-carbon ratio to affect the SOA yield?

**Comment by yantosca** [comment]
Thanks for writing @yangning-code.  The SOA code is in `GeosCore/carbon_mod.F90` but I wouldn't know where exactly it was.  You can look through the code and see if you can find it in the comments.

Also tagging the Aerosols Working Group co-chairs: @theloniuspunk @beckyalexander @wporter

Also tagging @Jourdan-He and @SaptSinha for reference.

**Comment by yangning-code** [comment]
Thanks @yantosca 
I will look carefully.

**Comment by yantosca** [comment]
Closing out this issue
