### ISSUE TITLE
[QUESTION]GEOS-Chem CO2 simulation : Carbon source and sink 

### ISSUE THREAD

**Issue by kimm1na** [geoschem/geos-chem#1394]
### Ask a question about GEOS-Chem:

hi @yantosca @msulprizio ,
I am doing CO2 simulation using GEOS-Chem.

There are roughly 4 source and sink for CO2 (Fossil Fuel, Land Use Change, Ocean sink, Land sink) 
in Global Carbon Budget.

![image](https://user-images.githubusercontent.com/89123880/191438966-addc1c1d-eacb-4f28-b6c8-038c73a709af.png)
(Global Carbon Budget, Pierre Friedlingstein et al.)

But in GEOS-Chem,
There are Fossil Fuel, Biomass Burning, Aviation, Ship, Ocean Sink, Land Sink, ...

I wonder how the two classifications are different.
For example,
how biomass burning used in geos-chem (from GFED4) is different from land use change of global carbon budget.
(GCB does not have biomass burning portion)

Thank you
Sincerely, Mina Kim

**Comment by msulprizio** [comment]
@kimm1na Thanks for writing. The GCST is unfamiliar with the GCB specifics. We recommend the following resources for details on the CO2 simulation in GEOS-Chem in the hopes that they would answer your questions:

- [Nassar et al. (2010)](https://gmd.copernicus.org/articles/3/689/2010/gmd-3-689-2010.html) 
- [CO2 simulation page on the GEOS-Chem wiki](http://wiki.seas.harvard.edu/geos-chem/index.php/CO2_simulation)

**Comment by kimm1na** [comment]
Thank you @msulprizio @yantosca,
and also I am curious about CO2 lifetime (residual time in atmosphere)  in GEOS-Chem CO2 simulation.

Thank you

sincerely, Mina Kim

**Comment by yantosca** [comment]
Closing out this issue as inactive
