### ISSUE TITLE
[QUESTION]Question about GEOS-CHEM RUN DIRECTORY CREATION

### ISSUE THREAD

**Issue by HuTuDouZ** [geoschem/geos-chem#1398]
Hi,
I am a newer for GEOS-Chem. I am stuck in running ./createRunDir.sh.
After running ./createRunDir.sh, it shows Warning: Default root data directory does not exist! Set new path below or manually edit /home/.geoschem/config and I can not enter a new path. How can I change default root and set new path? I delete GCClassic file and redownload it, but problem is still there.
Thanks.

**Comment by yantosca** [comment]
Thanks for writing @HuTuDouZ.  Can you provide some additional information?

  1. The version you are using
  2. Are you running GEOS-Chem locally, or on the cloud
  3. The commands that you typed at the prompts when running createRundir.sh

Also tagging @Jourdan-He and @SaptSinha.

**Comment by HuTuDouZ** [comment]
Hi yantosca,
I found the way how to solve this. Type history -c when using linux.
Thanks a lot.
