### ISSUE TITLE
[BUG/ISSUE] CHLR fields not read for marine POA simulations in GC 12.3.0 and later

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#140]
In GEOS-Chem 12.3.0, an update was made to read and regrid MODIS LAI fields via HEMCO instead of in `GeosCore/modis_lai_mod.F90`. At that time, it appears that code to read MODIS CHLR (chlorophyll-a) was removed, but those fields were never implemented via HEMCO. Therefore, `State_Met%MODISCHLR` is no longer populated and this has complications for code in `HEMCO/Extensions/hcox_seasalt_mod.F` since `ExtState%CHLR%Arr%Val(I,J)` will be zero.

The fix should be to add an entry to read MODIS CHLR from file in HEMCO_Config.rc and add a call to get the pointer from HEMCO in `GeosCore/modis_lai_mod.F90` to update `State_Met%MODISCHLR`.

**Comment by yantosca** [comment]
This issue is now resolved with commit https://github.com/geoschem/geos-chem/commit/757f917ef1146729bf9ac79e5b06f94dd903b0e5.   It will ship with the 12.7.0 release.
