### ISSUE TITLE
[QUESTION]Questions about GCAP2.0 simulation results

### ISSUE THREAD

**Issue by zhiweistu** [geoschem/geos-chem#1401]
### Ask a question about GEOS-Chem:
Dear GEOSChem developer and GCAP2.0 developer,

My GC version is 13.4.1 and I used GCAP 2.0 to run 2014 year simulation. I have 3 questions about my output results.

1.I used GCAP 2.0 default emissions, I found BB4MIPs is on in configure file, but in HEMCO_diagnostic, values of biomass burning emission in output files are zero, how to solve it?
![image](https://user-images.githubusercontent.com/109276335/192143915-9ab6f97d-8446-41b9-a781-d732e976568c.png)

2.I found total SO2 emissions seemed to deviate from the sum of each sector emissions. 

Data Operation: Python 3 and cdo

Output File: HEMCO_diagnostics.201409010000.nc

_______________________________________
EmisSO2_Total:       12.013206 Tg
________________________________________
EmisSO2_Aircraft:         0.04441736  Tg
EmisSO2_Anthro:          8.250498    Tg
EmisSO2_BioBurn:        0          Tg
EmisSO2_VolcDegas:   1.6766878   Tg
EmisSO2_VolcErupt:     1.0986866   Tg
EmisSO2_Ship:             0.7750698   Tg
Sum:                           11.84535956 Tg
_________________________________________
SO2_emission Deviation = 0.16784644 Tg

____________________________________
EmisSO4_Total:       0.28116214  Tg
____________________________________
EmisSO4_Aircraft:    0.00136924  Tg
EmisSO4_Anthro:     0.25576583  Tg 
EmisSO4_Ship:         0.02402717  Tg
Sum:                         0.28116224 Tg
Deviation:       1e-7
___________________________________

For SO4 emission, the sum of each sector is equal to EmisSO4_Total, but for SO2 emission, it seems not equal.

________________________________
EmisSO2_Total:       139.13725 Tg
________________________________
EmisSO2_Aircraft:           0.5168573  Tg
EmisSO2_Anthro:           101.66893   Tg
EmisSO2_BioBurn:          0                 Tg
EmisSO2_VolcDegas:      20.399708   Tg
EmisSO2_VolcErupt:        5.3493414   Tg
EmisSO2_Ship:                 9.032977    Tg
Sum:                              136.9678137 Tg
_________________________________
SO2_emission Deviation = 2.1694363  Tg

Besides, I also estimated 2014 year total SO2 emission, the deviation is about 2 Tg. Why is there such a discrepancy?

3.In output file “GEOSChem.SpeciesConc ”

Does the variable "SpeciesConc_SO4" represent total sulfate concentration (sum of SO4s and SO4 dust..)?

![image](https://user-images.githubusercontent.com/109276335/192144034-01a18dd3-0680-4176-873e-2f0c303bb46e.png)
Thanks for your helps!

**Comment by zhiweistu** [comment]
[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/9640774/HEMCO_Config.txt)

**Comment by zhiweistu** [comment]
Hi, everyone. I checked my output files “GEOSChem.ProdLoss”.
I found only the value of variable chemical production of sulfate is not zero. 
Other values of variable about SO4 production are zero, 
how to solve it ? thanks!

![image](https://user-images.githubusercontent.com/109276335/192225029-41d99cfe-7816-4c49-8c1b-6c65467e13c9.png)
![image](https://user-images.githubusercontent.com/109276335/192225071-75e5bbc2-6d61-4de9-901c-bfb7eb3e7efe.png)
![image](https://user-images.githubusercontent.com/109276335/192225123-246138bb-146c-400c-ae7d-0eed2ed5d4cd.png)
![image](https://user-images.githubusercontent.com/109276335/192225164-191bf54c-6b42-438d-918d-0a2a29fddbaf.png)
![image](https://user-images.githubusercontent.com/109276335/192225197-a2cf85a2-426a-4e59-b680-b8f6649adb53.png)
![image](https://user-images.githubusercontent.com/109276335/192225239-fb8614ec-335f-4015-a718-b82dbf152cbc.png)
![image](https://user-images.githubusercontent.com/109276335/192225264-87f01e74-e28f-47ee-a8e9-f2ccea083846.png)
![image](https://user-images.githubusercontent.com/109276335/192225290-088618f9-0676-47ba-988c-bff840c8975f.png)
![image](https://user-images.githubusercontent.com/109276335/192225330-b6489b67-9c8b-47b7-ba83-379f1a05c63c.png)

[HEMCO_Diagn.txt](https://github.com/geoschem/geos-chem/files/9644243/HEMCO_Diagn.txt)
[HISTORY.txt](https://github.com/geoschem/geos-chem/files/9644249/HISTORY.txt)
[input.geos.txt](https://github.com/geoschem/geos-chem/files/9644254/input.geos.txt)

**Comment by yantosca** [comment]
Thanks for writing @zhiweistu.  I am tagging @ltmurray, who is more familiar with the GCAP simulations than I am.

Also tagging @Jourdan-He and @SaptSinha for reference.

**Comment by ltmurray** [comment]
If you are using BB4MIPs, then you need to modify your HEMCO_Diagn.rc file to use prescribed emissions rather (category 5) than the GFED extension, e.g., for acetone,

`EmisACET_BioBurn   ACET   0      5   -1   2   kg/m2/s  ACET_emission_flux_from_biomass_burning`

There is no reason that the additional sulfate production diagnostics should not be working in GCAP as far as I can see. @yantosca, can you confirm that they are working in the MERRA2-driven versions of GEOS-Chem?

**Comment by zhiweistu** [comment]
Thanks@yantosca@ltmurray. 
Do you mean that I actually used BB4MIPs emission, and the emission deviation represent emissions from biomass burning. 
For example, 0.16784644 Tg is the monthly SO2 emissions from biomass burning(BB4MIPs).

**Comment by zhiweistu** [comment]
Thanks@yantosca @ltmurray.
Do you mean that I actually used BB4MIPs emission, and the emission deviation represent emissions from biomass burning.
For example, 0.16784644 Tg is the monthly SO2 emissions from biomass burning(BB4MIPs).

**Comment by yantosca** [comment]
Closing out this issue.
