### ISSUE TITLE
HISTORY.rc output inconsistency [QUESTION]

### ISSUE THREAD

**Issue by JbourJabber** [geoschem/geos-chem#1404]
I have been working on getting a tagged tracer simulation for C2H6 working, see here for more information (https://github.com/geoschem/geos-chem/issues/1329), and have nearly got it working properly--but the following issues continues to persist:

The SpeciesConc_fields for each of the tagged C2H6 subspecies are only being written to the output for some months in the year-long simulation, see below:

Months **January through March, 2018** - Only the global SpeciesConc_fields by source are being written (_Panoply_)

![GEOSChem SpeciesConcMonthlyAvg Output_Failure_032018](https://user-images.githubusercontent.com/89486250/192914786-40313706-7dca-48fe-9123-95d91a30b911.PNG)

Months **April through December, 2018** - Output all of the specified SpeciesConc_fields in the History.rc (_Panoply_)

![GEOSChem SpeciesConcMonthlyAvg Output_Success_042018](https://user-images.githubusercontent.com/89486250/192914800-da03228e-075d-49d8-a683-a5345cb0dcac.PNG)

Below I've attached copies of my configuration files, as I may be missing something within these--thank you in advance and I am happy to see this inching closer to working properly.

[GCHP.rc.txt](https://github.com/geoschem/geos-chem/files/9513953/GCHP.rc.txt)
[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/9513956/HEMCO_Config.rc.txt)
[HEMCO_Diagn.rc.txt](https://github.com/geoschem/geos-chem/files/9513962/HEMCO_Diagn.rc.txt)
[HISTORY.rc.txt](https://github.com/geoschem/geos-chem/files/9513963/HISTORY.rc.txt)
[input.geos.txt](https://github.com/geoschem/geos-chem/files/9513964/input.geos.txt)
[runConfig.sh.txt](https://github.com/geoschem/geos-chem/files/9513965/runConfig.sh.txt)
[species_database.yml.txt](https://github.com/geoschem/geos-chem/files/9513966/species_database.yml.txt)
[ExtData.rc.txt](https://github.com/geoschem/geos-chem/files/9513967/ExtData.rc.txt)

**Comment by JbourJabber** [comment]
I ended up resubmitting this job, without changing of the configuration files--and the output on the second attempt successfully output the desired diagnostics for each month. Not sure what the issue was originally, but it has been resolved now.

**Comment by yantosca** [comment]
Thanks for letting us know @JbourJabber!
