### ISSUE TITLE
[BUG/ISSUE] "B3O2" and "ATO2" hash to the same value, causing incorrect saving of B3O2 species concentrations

### ISSUE THREAD

**Issue by WilliamDowns** [geoschem/geos-chem#141]
In the current hashing scheme in charpak_mod.F90, "B3O2" and "ATO2" both hash to the same value. A consequence of this bug is that B3O2 is saved to GEOS-Chem restart files with the species concentration values of ATO2 rather than its own values from State_Chm.

**Comment by yantosca** [comment]
This is now resolved with commit; https://github.com/geoschem/geos-chem/commit/c5a8b93055903ef0d72b8e2259d7b4cd45201706, which will ship with 12.7.0.  We can now close out this issue.
