### ISSUE TITLE
[FEATURE REQUEST] Retire met-field LWI in GC-Classic

### ISSUE THREAD

**Issue by lizziel** [geoschem/geos-chem#1413]
This feature request is to (1) remove use of land-water-ice index (LWI) meteorology input in GC-Classic, and (2) remove the GEOS-Chem `State_Met%LWI`. 

The motivation for this is the land-water-ice index in the GEOS-Chem input meteorology will not be available in the GEOS-IT dataset. Updates have already removed the dependency in GCHP by using other input met-fields to determine if each grid cell is predominantly land, water, or ice. https://github.com/geoschem/geos-chem/blob/412ba5906b2aa9dcd72a2188c76c50220c3697b7/Interfaces/GCHP/Includes_Before_Run.H#L65-L74

There is only one location in GEOS-Chem that uses LWI for computation, in dry deposition. 
https://github.com/geoschem/geos-chem/blob/412ba5906b2aa9dcd72a2188c76c50220c3697b7/GeosCore/drydep_mod.F90#L2271-L2273

GEOS-Chem also passes LWI to HEMCO which uses it in several extensions. HEMCO will thus need to be updated to use the available land type met-fields to do this instead, and I'll make a separate feature request in HEMCO for this.

I will work on getting this update into 14.1. It will impact the benchmark but the impact should be minor.

**Comment by yantosca** [comment]
For reference, here is the definition of LWI in GEOS-5. 

>**LWI**: A Land-Water-Ice mask provided for backward compatibility with the GEOS-4 product. It is 1 over continental areas, 0 over open ocean, and 2 over sea-ice covered ocean. Since in GEOS-5 a grid box can be a combination of these, continental areas are arbitrarily defined as those where FRLAND+FRLANDICE>=0.5. The remaining grid boxes are designated as sea-ice if the ice cover exceeds 50%; otherwise they are open (ice-free) ocean.

Note, this field was introduced in GEOS-5 for backwards compatibilty with the GEOS-4 `SURFTYPE` variable.  `LWI` is going to be retired from the newer GEOS-IT dataset as it can be created from a combination of other fields:

**Comment by yantosca** [comment]
@lizziel, we probably shouldn't be too tied to GEOS-4.

**Comment by lizziel** [comment]
I have a couple draft PRs almost ready for review. Integration tests are in progress.
https://github.com/geoschem/geos-chem/pull/1435
https://github.com/geoschem/HEMCO/pull/170

**Comment by msulprizio** [comment]
These PRs are now included in the `dev/14.1.0` branch. I will close out this feature request.
