### ISSUE TITLE
[Feature Request] Move aerosol module variables to State_Chm

### ISSUE THREAD

**Issue by lizziel** [geoschem/geos-chem#1418]
We are trying to move away from module variables and instead store data that is persistent across timesteps within state variables. There are several module variables in aerosol_mod.F90 that could be moved to State_Chm.

**Comment by yantosca** [comment]
This will be a necessary step in the work that I will be doing to clean up `aerosol_mod.F90`.

**Comment by msulprizio** [comment]
The corresponding pull request (#2015) has now been merged into `dev/14.3.0`.
