### ISSUE TITLE
[Feature Request] Add OpenMP parallelization tests to test suite

### ISSUE THREAD

**Issue by lizziel** [geoschem/geos-chem#1419]
GEOS-Chem Classic currently has a parallelization issue that snuck in since we retired the Unit Tester without replacing parallelization tests. Once the problem is fixed we should implement a comprehensive parallelization tester to sit alongside our integration tests.

**Comment by yantosca** [comment]
Adding PR #1565 here.

**Comment by yantosca** [comment]
The integration test update going into 14.1.1 contains separate scripts for running GEOS-Chem Classic parallelization tests.  See PR #1565 for details.

**Comment by yantosca** [comment]
We can now close this issue as PR #1565 has been merged into the 14.1.1 development stream.
