### ISSUE TITLE
[DISCUSSION] Investigate scalability of GEOS-Chem Classic with gcc 10.2.0 and gcc 12.2.0

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#1424]
The recent switch from the ifort19 to gcc 10.2.0 compiler for internal benchmarks has revealed that GEOS-Chem simulations with gcc 10.2.0 run just as fast as ifort19. These simulations ran on all 48 CPUs of one Intel Cascade Lake node on Harvard's Cannon cluster. Interestingly, scalability (using wall time / cpu time as a proxy) of simulations with ifort19 was much better (~90% ideal) than simulations with gcc 10.2.0 (~31% ideal). If we can improve upon scalability of simulations using gcc 10.2.0, that may suggest that those simulations have the potential to be faster than simulations using ifort19. 

See the [GEOS-Chem Internal Benchmark Google Sheet](https://docs.google.com/spreadsheets/d/1Yird5jRUIX1KKdRZq8lZGO_x2VQnsedn0QQK052n__8/edit?usp=sharing) for performance details.

**Comment by yantosca** [comment]
I am waiting for TAU to be rebuilt on our cluster.  I might be able to do profiling relatively soon.  Stay tuned!

**Comment by yantosca** [comment]
Closing out this issue
