### ISSUE TITLE
[QUESTION] Is CEDS_GBDMAPS data avaialbe for years after 2017?

### ISSUE THREAD

**Issue by jinlx** [geoschem/geos-chem#1427]
Hi there,

I am trying to add additional sources for VOCs by using CEDS_GBDMAPS. I wonder if anyone has updated CEDS_GBDMAPS after 2017. If so, I wonder if it's easy to upload the data in the data server (e.g., washu server).

Thanks,
Lixu

**Comment by msulprizio** [comment]
Hi @jinlx. We are not aware of anyone having updated the CEDS GBD-MAPS files to more recent years. I'm tagging the original developer @emcduffie to see if she has handed off this work to anyone.

**Comment by emcduffie** [comment]
Hi @jinlx, thanks for your question and interest. No, there are no current plans to update the CEDS GBD-MAPS dataset. However, the official CEDS dataset (developed at PNNL) is available here (https://github.com/JGCRI/CEDS) and extends emissions to the year 2019.

**Comment by jinlx** [comment]
Thanks @msulprizio and @emcduffie! 

Erin- I was wondering if there are any easy ways to mimic your CEDS GBD-MAPS from the current official CEDS for data after 2017. If not, we will just go with 2017 instead. Thanks again! -Lixu

**Comment by emcduffie** [comment]
Hi @jinlx - it depends what you are trying to do. If you just want total emissions, go ahead and use the new official CEDS data. If you're interested in the fuel-specific emissions, the most accurate approach would be to follow the procedure in the CEDS-GBD-MAPS paper to re-process the CEDS emissions to extract the additional fuel information. That will require a significant amount of time and some $. Therefore, the simplest approach could be to try applying the fractional contribution of each fuel type in 2017 to the 2018 and 2019 total emissions for each country and sector. However - I haven't done this (nor fully thought through the implications or assumptions of this option) so I'm not necessarily endorsing this option, but it might provide reasonable results.

**Comment by yantosca** [comment]
Closing out the issue now!  Thanks
