### ISSUE TITLE
[BUG/ISSUE] Need $MM in file path for AEIC2019_DAILY in HEMCO_Config template for Aerosol-only simulations

### ISSUE THREAD

**Issue by chfite** [geoschem/geos-chem#1428]
I noticed a small typo that should be a quick fix. In the HEMCO_Config templates for the aerosol-only simulation (`run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.aerosol`) the AEIC2019_DAILY emissions need a $MM in the file path, as that is how they are stored on the FTP sites. 

Currently the template lists:
$ROOT/AEIC2019/v2022-03/2019/AEIC_2019$MM$DD.0.5x0.625.36L.nc
But should list:
$ROOT/AEIC2019/v2022-03/2019/$MM/AEIC_2019$MM$DD.0.5x0.625.36L.nc

I checked and this typo _does not_ exist in the fullchem templates for HEMCO_Config, so it should only be a quick fix needed for the aerosol-only template.

The program should kill anyway and alert a user that it can't find the file, so it wouldn't be that difficult of an issue to solve for the user - but I thought I'd go ahead and report it.

**Comment by yantosca** [comment]
Thanks for the feedback @chfite.  I think there will be a 14.0.1 release after the 14.0.0 release, and this is a quick fix, so we can get it into 14.0.1.

**Comment by msulprizio** [comment]
This is now resolved in commit 6e206e96 (currently in the `patch/14.0.1` branch).
