### ISSUE TITLE
[QUESTION] Is a BC-only aerosol simulation possible?

### ISSUE THREAD

**Issue by chfite** [geoschem/geos-chem#1430]
I am using GCClassic v13.3.4 (CONUS nested 0.25x0.3125) and want to do a BC-only simulation _if possible_. I have created a run-directory from the aerosol simulation template. In `input.geos` I removed all aerosol species, except for BCPO and BCPI, from the advected species list. In the aerosol menu I turned OFF online sulfate, dust, and seasalt aerosols. I left carbon aerosols ON (although I am not listing OCPO/OCPI in the advected species list and as a result also have complex SOA and SVPOA turned off.).

The model kills right when it appears it will start time-stepping (or right before) and I get the segmentation fault error that is pasted at the bottom here. Is it possible to just do a BCPO/BCPI simulation or will I need to list all aerosol species in `input.geos`? 

I tested turning OFF chemistry in `input.geos` and the simulation does not kill and is able to time-step just fine. It does provide the SpeciesConc history diagnostic output for BCPO and BCPI like I would like. However, the `AerMassBC` and BC AOD component ,`AODHyg500nm_BCPI`, are both all filled with all zeros, so this workaround won't work for me since I need the AOD output, unless there is a way to resolve the issue of it filling zeros.

Even if I turn all aerosols on (which I assume would resolve the issue) it defaults to the simple SOA/OA species, but my boundary conditions file for this nested simulation came from a complexSOA_SVPOA simulation and so it cannot find the needed simple OA variables in the boundary condition output. Switching this to an aerosol simulation WITH complexSOA_SVPOA would require adding a bunch of additional IVOCs/NAP species to `input.geos`, which would slow my run down a lot I'd assume.

Here are some of my input and output files, I had verbose=3 and warnings=2 in HEMCO_Config.rc.
[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/9748598/HEMCO_Config.rc.txt)
[input.geos.txt](https://github.com/geoschem/geos-chem/files/9748597/input.geos.txt)
[HEMCO.log.txt](https://github.com/geoschem/geos-chem/files/9748599/HEMCO.log.txt)
[GC.log.txt](https://github.com/geoschem/geos-chem/files/9748600/GC.log.txt)

Here is the error I get with just the BCPO/BCPI species listed:
```console
`********************************************
* B e g i n   T i m e   S t e p p i n g !! *
********************************************

---> DATE: 2019/08/01  UTC: 00:00  X-HRS:      0.000000
 HEMCO already called for this timestep. Returning.
NASA-GSFC Tracer Transport Module successfully initialized
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% USING O3 COLUMNS FROM THE MET FIELDS! %%% 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
gcclassic          0000000000C7CA2A  Unknown               Unknown  Unknown
libpthread-2.27.s  0000145C755DF980  Unknown               Unknown  Unknown
gcclassic          000000000040C89B  aerosol_mod_mp_ae         383  aerosol_mod.F90
gcclassic          00000000004269DD  chemistry_mod_mp_         557  chemistry_mod.F90
gcclassic          0000000000406034  MAIN__                   1611  main.F90
gcclassic          0000000000404F82  Unknown               Unknown  Unknown
libc-2.27.so       0000145C751FDC87  __libc_start_main     Unknown  Unknown
gcclassic          0000000000404E6A  Unknown               Unknown  Unknown`
```

**Comment by yantosca** [comment]
That IF block needs `id_SO4`, `id_SALA`, `id_POA1`, and `id_OCPI` all to be nonzero, as they are used to look up species concentrations.  You could add this code:

```F90
SIA_GROWTH = 0.0_fp
ORG_GROWTH=0.0_fp
SSA_GROWTH=0.0_fp

IF ( FIRST .and. id_SO4 > 0 .and. id_OCPI > 0 .and. id_POA1 > 0 .and. id_SALA > 0 ) THEN
```
Ideally maybe we should split these out of the same IF block in a future version,.  But that fix should allow you to proceed.

**Comment by chfite** [comment]
Thanks @yantosca that did indeed fix that issue. For any other users that are interested in doing something similar, there were a couple other spots in `aerosol_mod.F90` that needed to be altered as well, but it was just a couple additional changes.

When the mapping of `NRHAER` is defined (roughly around line 1220), it references `SpcID = State_Chm%Map_HygGrth(N)` for determining species info. Since I only have `BCPO` and `BCPI` as advected species in this simulation, `Map_HygGrth(1)` is connected to BCPI, rather than SO4. Referencing `Map_HygGrth(N)` with any N>1 yields a SpcID over 5000...which of course doesn't make sense. To avoid this mapping issue altogether, I altered that IF statement where this mapping occurs with the same `IF ( FIRST .and. id_SO4 > 0 .and. id_OCPI > 0 .and. id_POA1 > 0 .and. id_SALA > 0 ) THEN` conditions like for the growth factors described above in this thread. I then just set `Map_NRHAER(1) = 2` for my own purposes, since this would map hygroscopic aerosol 1 (BC) to the value N=2 since N=2 is used elsewhere in code for referencing and calculating BC AOD and concentrations. My changes are as follows:

```
    IF ( FIRST .and. id_BCPI > 0 .and. id_SO4 < 1 .and. id_OCPI < 1 .and. id_POA1 < 1 .and. id_SALA < 1) THEN

      Map_NRHAER(1) = 2 !in BC-only simulation: mapping hygroscopic aerosol=1 to value of 2 since N=2 it is used to reference BC throughout
      Map_NRHAER(2) = 1 ! for the rest of these I just default to other values, which shouldn't matter since I am not saving out or simulating species other than BC
      Map_NRHAER(3) = 3
      Map_NRHAER(4) = 4
      Map_NRHAER(5) = 5
    ENDIF


    ! Initialize the mapping between hygroscopic species in the
    ! species database and the species order in NRHAER
    IF ( FIRST .and. id_SO4 > 0 .and. id_BCPI > 0 .and. id_OCPI > 0 .and. id_POA1 > 0 .and. id_SALA > 0 ) THEN
       DO N = 1, NRHAER

          ! Get the species database index from the species database
          ! mapping array for hygroscopic growth species
          SpcID = State_Chm%Map_HygGrth(N)

          ! Point to the Species Database entry for species N
          SpcInfo => State_Chm%SpcData(SpcID)%Info

          ! Set the mapping to the ordering of aerosol densities in RD_AOD
          SELECT CASE ( TRIM(SpcInfo%Name) )
          CASE ( 'SO4' )
             Map_NRHAER(N) = 1
          CASE ( 'BCPI' )
             Map_NRHAER(N) = 2
          CASE ( 'OCPI', 'POA1' )
             Map_NRHAER(N) = 3
          CASE ( 'SALA' )
             Map_NRHAER(N) = 4
          CASE ( 'SALC' )
             Map_NRHAER(N) = 5
          CASE DEFAULT
             ErrMsg = 'WARNING: aerosol diagnostics not defined' // &
                      ' for NRHAER greater than 5!'
             CALL GC_ERROR( ErrMsg, RC, 'RDAER in aerosol_mod.F90' )
          END SELECT

          ! Free pointer
          SpcInfo => NULL()

       ENDDO
    ENDIF
```


Then, further down, species info is used to assigning densities to `MSDENS` and errors when trying to find the density information for species that are not BCPI. Therefore, I made the following similar changes, where I use the conditional like above, assign the correct density for BCPI, and I just filled in filler values of 1 for the other indices in MSDENS, like so:

```
   !if these other aerosols exist in simulation, assign actual densities
    IF ( id_SO4 > 0 .and. id_OCPI > 0 .and. id_POA1 > 0 .and. id_SALA > 0 ) THEN
      MSDENS(1) = State_Chm%SpcData(id_SO4)%Info%Density
      MSDENS(2) = State_Chm%SpcData(id_BCPI)%Info%Density
      IF ( IS_POA ) THEN
         MSDENS(3) = State_Chm%SpcData(id_POA1)%Info%Density
      ELSE IF ( IS_OCPI ) THEN
         MSDENS(3) = State_Chm%SpcData(id_OCPI)%Info%Density
      ENDIF
      MSDENS(4) = State_Chm%SpcData(id_SALA)%Info%Density
      MSDENS(5) = State_Chm%SpcData(id_SALC)%Info%Density
    ELSE !those species should be off in the BC sim, so only reference density info here...
      MSDENS(1) = 1.0_fp !forcing to 1 since SO4 is not species, so no density to map to
      MSDENS(2) = State_Chm%SpcData(id_BCPI)%Info%Density !assigning actual BCPI desnity
      MSDENS(3) = 1.0_fp !forcing to 1 since POA/OCPI not species, so no density to map to
      MSDENS(4) = 1.0_fp !forcing to 1 since SALA not species, so no density to map to
      MSDENS(5) = 1.0_fp !forcing to 1 since SALC not species, so no density to map to
    ENDIF 
```

Overall this appeared to resolve all issues and the model runs now and saves out all BC concentrations, aerosol mass, and BC AOD, likely much quicker than running all aerosols or all species. My edits may not be the cleanest or most practical, but they worked for my purposes.

**Comment by yantosca** [comment]
Thanks @chfite.  I am going to be looking at aerosol_mod in the near future so I'll try to get these fixes in.  Maybe ready by 14.1.0.

**Comment by yantosca** [comment]
Closing out this issue
