### ISSUE TITLE
[QUESTION]Should diurnal scale factors be set by localtime?

### ISSUE THREAD

**Issue by yangxiajie** [geoschem/geos-chem#1432]
Hi. 

I want to add new diurnal scale factors in `HEMCO_Config.rc` in GEOS-Chem v12.9.3 like this:

`32 NO a1/a2/a3/.../a24 - - - xy unitless 1`
 
The number `32` above is set in MIX inventory, and the default number (`25`) in removed.  

Should I set the sequence of diurnal scale factors (eg, `a1/a2/a3/.../a24`) by Local Time? Or just UTC ?

Thank you :)

**Comment by yantosca** [comment]
Thanks for writing @yangxiajie.  I believe you would want to use local time for the scale factors, as that would capture the local conditions (i.e. rush hour, overnight, etc).  If you use UTC then those patterns would be several hours off. 

Also tagging @Jourdan-He and @SaptSinha

**Comment by yangxiajie** [comment]
Thanks @yantosca . 

I fix that already.
