### ISSUE TITLE
[BUG/ISSUE] GCClassic analytical inversion option is activated in geoschem_config.yml.CH4

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#1436]
The analytical inversion option is activated by default in the template file `run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.CH4`.

https://github.com/geoschem/geos-chem/blob/9b2cde0932b33ab9e0ecc874266aa285d19f616f/run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.CH4#L67-L82

However, this causes an error in HEMCO:
```console
HEMCO ERROR: AnalyticalInv is set to false in HEMCO_Config.rc 
but should be set to true for this simulation.
```
This was causing integration tests to fail.  I think that the analyical inversion should also be turned off in the `geoschem_config.yml.CH4` template file.  

Tagging @msulprizio, @Jourdan-He and @SaptSinha

**Comment by msulprizio** [comment]
Hi @yantosca. I'm confirming this should be off by default for CH4 simulations.
