### ISSUE TITLE
[QUESTION] Wrong molecular ration explanation in wiki and comments of configuration file?

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/geos-chem#144]
I read but got confused by the description in [HEMCO standalone wiki](http://wiki.seas.harvard.edu/geos-chem/index.php/HEMCO_standalone#Species_definition). You said `molecular ration (molecules emitted species per molecule of species, unitless)` but I found the `MOLECRATIO` column is calculated as `MW/EMISMW`. Hence should the ratio be `molecules of species per molecule of emitted species`? I also found these on `HEMCO_sa_Spec.rc` (see the following screenshot) and other HEMCO related wiki such as [this](http://wiki.seas.harvard.edu/geos-chem/index.php/The_HEMCO_User%27s_Guide#Units_in_HEMCO). I want to confirm if it is my misunderstanding of English or a typo of description?

![image](https://user-images.githubusercontent.com/43779303/69256260-1d7bf000-0bb1-11ea-91fe-35d6e8ef5e79.png)

**Comment by yantosca** [comment]
Thanks for writing.  So in practice this is only used for hydrocarbons.  Some species are carried as equivalent carbon atoms (e.g. ACET = 3 carbons, which has a MOLERAT = 3, ISOP = 5 carbons, which has a MOLERAT = 5, etc). 

So perhaps it should be "equivalent atoms of C per molecule of species" 

In a future GC version we will make all species be carried as the species themselves and not as equivalent carbon atoms.  In that case, MOLERAT can be removed.

**Comment by FeiYao-Edinburgh** [comment]
> So perhaps it should be "equivalent atoms of C per molecule of species"

This makes sense as I suddenly found that some values of `MOLERAT` is not `MW/MWEMIS`.
