### ISSUE TITLE
[ISSUE] geoschemdata.wustl.edu missing OFFLINE_BVOC files for 04-05 2015

### ISSUE THREAD

**Issue by eamarais** [geoschem/geos-chem#1449]
In this parent directory on the wustl mirror site (http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_BIOVOC/v2021-12/0.5x0.625/2015/) all files are missing for May and files for the last 3 days are missing for April.

**Comment by msulprizio** [comment]
These files are also missing from Harvard's copy.  

@hongjianweng Do you have these files available? If so, can you transfer them to WashU?

**Comment by eamarais** [comment]
Hi @msulprizio, just wanted to flag that this has been marked automatically as stale and closed, but isn't addressed yet.

**Comment by msulprizio** [comment]
Hi @eamarais. I am reopening this issue. We have not heard back from @hongjianweng who generated these files. I will send an email to the PKU group so we can try to resolve this.

**Comment by msulprizio** [comment]
Hi again @eamarais. Hongjian tells us he has uploaded the missing files. Please let us know if you have any other issues.

**Comment by eamarais** [comment]
Excellent. Thank you both.

**Comment by msulprizio** [comment]
@Jourdan-He or @SaptSinha could you please fix the permissions of the files at the path specified above?

**Comment by Jourdan-He** [comment]
@msulprizio @eamarais I'm having some permission issue in changing file permissions, but I'm working on it. Will update once it's solved.

**Comment by Jourdan-He** [comment]
Hi @eamarais , the permission has been fixed now.

**Comment by eamarais** [comment]
@Jourdan-He, thanks for letting me know. I successfully downloaded the files today.
