### ISSUE TITLE
[DISCUSSION] Fortran hash table / dictionary libraries for species indexing

### ISSUE THREAD

**Issue by JiaweiZhuang** [geoschem/geos-chem#145]
We should use a mature hash table library for the [GEOS-Chem species database](http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_species_database), instead of re-inventing such basic data type. Python has the built-in dictionary type, implemented as hash table with `O(1)` access; C++ STL has `std::map`, implemented as red-black tree with `O(log n)` access. There is no built-in dict type for Fortran, but the Fortran Wiki lists several hash table libraries: http://fortranwiki.org/fortran/show/Hash+tables. 

The GMAO FTL library (https://github.com/Goddard-Fortran-Ecosystem/gFTL) also contains `List`, `Set`, and `Map` structures.

 Related #141 @WilliamDowns

**Comment by JiaweiZhuang** [comment]
There are also libraries for linked lists: http://fortranwiki.org/fortran/show/Linked+list

**Comment by yantosca** [comment]
The gFTL sounds pretty useful, but practically I think we have to wait till 13.0.0, until we completely retire GNU Make, as it requires CMake.  

Also when adding new dependencies to GCC, we would also have to train users as to how to build those.  So that is an additional time commitment on the GCST's part.  

In the meantime I will look into a better quick fix for dev/12.7.0.  I think I have something in mind.

**Comment by JiaweiZhuang** [comment]
> Also when adding new dependencies to GCC, we would also have to train users as to how to build those. So that is an additional time commitment on the GCST's part.

Right, this is a big annoyance with using external Fortran libraries. If it doesn't need to be updated, maybe just include its source code into GC's source code?

**Comment by yantosca** [comment]
Also I just found a single file implementation of a hash table.  This might solve our problem.

https://github.com/pdebuyl/fortran_hash_table

**Comment by yantosca** [comment]
Also this set of algorithms: http://www.cse.yorku.ca/~oz/hash.html

**Comment by sdeastham** [comment]
The dictionary_m implementation looks great!

**Comment by yantosca** [comment]
@sdeastham I agree.  I think we have to tweak it a little bit so that the value is an integer rather than a string (because then otherwise you are doing string comparisons).  But that's a minor fix.

**Comment by sdeastham** [comment]
Hang on – I’m confused. Aren’t the string comparisons 100% required? How can you avoid hash collisions without performing a string comparison between the supplied key and the stored key?

**Comment by yantosca** [comment]
I was thinking of returning the value as an integer, not the key.  I can run some tests.

```F90
 !> Single entry in the dictionary
  type entry_t
     character(len=:), allocatable :: key
!BMY     character(len=:), allocatable :: value
     integer                       :: value
  end type entry_t
```

**Comment by sdeastham** [comment]
Ahh, my apologies. So the key would still be stored, and used for collision checking – it’s just changing the stored thing to be an integer (ie index) rather than a second string. Got it.

**Comment by yantosca** [comment]
Yes, and the stored thing (integer) can be the ModelID value.  Then once you know the ModelID, then you can use Ind_ to get the other ID's as well.

**Comment by lizziel** [comment]
To clarify on an earlier comment on gFTL, we do not need to wait until 13.0.0 to use gFTL since it is built as an external library. In GCHP we do not yet build the model with CMake but we do use gFTL without issue. CMake is readily available and the gFTL build is quite simple. You do not even need to use the same compiler as what you end up using with GEOS-Chem.

**Comment by lizziel** [comment]
I like the dictionary_m implementation too. Regardless of how easy or hard connecting to gFTL would be, I think using the pdebuyl/fortran_hash_table is the best way to go. It is well commented and limited to what we need.

**Comment by yantosca** [comment]
We have implemented the dictionary_m.F90 lookup table for the species database in 12.7.0 (see commit https://github.com/geoschem/geos-chem/commit/c5a8b93055903ef0d72b8e2259d7b4cd45201706).

However, we should also probably implement it for the Registry linked list search as well, to prevent further hash collisions.

**Comment by yantosca** [comment]
We can close out this issue, since we are using dictionary_m.

**Comment by yc-chan** [comment]
Hello Bob, I wonder if GCST is still planning to implement the this new hast table function for the Registry linked list search. 

When I am using 12.7.0, the hash table bug affected some of my Prodloss diagnostics. For now, I rename some of the species in the model to temporarily fix the issue, but I am still looking forward to a more permanent fix.

**Comment by yantosca** [comment]
Thanks for bringing this up.  I am closing out this discussion but have opened a feature request (https://github.com/geoschem/geos-chem/issues/264) so that we don't forget to add the dictionary_m lookup to registry objects.  This is currently slated for 13.0.0.
