### ISSUE TITLE
[BUG/ISSUE] Cannot find field with valid time stamp in restart file

### ISSUE THREAD

**Issue by lshen2009** [geoschem/geos-chem#1450]
### What institution are you from?
Please tell us what institution you are from.
Harvard

### Description of the problem
Describe your problem here.  Describe the steps to reproduce the problem here, if possible.

I created a standard 4x5 run directory. And then I changed the start date from 20190701 to 20190101, and also moved GEOSChem.Restart.20190701_0000z.nc4 to GEOSChem.Restart.20190101_0000z.nc4. Then I get an error. Does it mean I need also to change the dates in the restart file? Thanks.  
```console
/n/holyscratch01/jacob_lab/lshen/GC_v14/gc_4x5_47L_merra2_fullchem

HEMCO: Opening ./Restarts/GEOSChem.Restart.20190101_0000z.nc4

HEMCO ERROR: Cannot find field with valid time stamp in ./Restarts/GEOSChem.Restart.20190101_0000z.nc4 - Cannot get field SPC_ACET. Please check file name and time (incl. time range flag) in the config. file

HEMCO ERROR: Error encountered in routine HCOIO_Read!

HEMCO ERROR: Error in HCOIO_DATAREAD called from HEMCO ReadList_Fill: SPC_ACET
 --> LOCATION: ReadList_Fill (HCO_ReadList_Mod.F90)
```

**Comment by yantosca** [comment]
Thanks @lshen2009 for writing.  Yes, a while ago the GEOS-Chem Steering Committee requested that we add an option into the HEMCO_Config.rc` files so that the run will stop if the simulation date & time does not match that of the restart file.

There is an easy way to update the restart file date & time with the CDO utilities:
```console
cdo setreftime,2019-07-01,00:00:00 GEOSChem.Restart.20190101_0000z.nc4 tmp.nc4
cdo setdate,2019-07-01 tmp.nc4 GEOSChem.Restart.20190101_0000z.nc4
```
It will ask you if you wish to clobber (aka) replace the original file, you can say yes.

**Comment by msulprizio** [comment]
Another option is to change the time cycle flag in HEMCO_Config.rc to allow for other dates. You can change the line:

```
* SPC_           ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 SpeciesRst_?ALL?    \
$YYYY/$MM/$DD/$HH EFYO xyz 1 * - 1 1
```

to:

```
* SPC_           ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 SpeciesRst_?ALL?    \
$YYYY/$MM/$DD/$HH CYS xyz 1 * - 1 1
```

Where `EFYO` tells HEMCO to use force using the exact date and `CYS` tells HEMCO to use the closest date available and skip a species field if it's not available.

**Comment by yantosca** [comment]
Closing out this issue.
