### ISSUE TITLE
[QUESTION] How to download the entire directory and subdirectories of input files using wget?

### ISSUE THREAD

**Issue by croy64** [geoschem/geos-chem#1453]
### How to download the entire directory and subdirectories of input files using wget?
I tried to use the wget command to download the input data, but only a html file is generated. I am unable to start a recursive download. I am using the following command:
wget -r -np -R "index.html*" http://geoschemdata.wustl.edu/ExtData/

Could you please suggest another method to do this?

Thank you

**Comment by psadavarte** [comment]
Hi, I've recently started working around GEOSChem and found the concept of "dryrun" simulations very easy to download the required input files for any kind of run. Just follow the steps mentioned in this YouTube video tutorial on GEOSChem: https://www.youtube.com/watch?v=L7T5QtWehLs&t=647s

**Comment by yantosca** [comment]
We also now have available the [bashdatacatalog](https://github.com/LiamBindle/bashdatacatalog/wiki) utility that can generate the proper wget commands for you.

**Comment by yantosca** [comment]
@croy64, have you solved this problem?

**Comment by croy64** [comment]
Yes. This problem is solved
