### ISSUE TITLE
[FEATURE REQUEST] Flush restart data to disk quickly

### ISSUE THREAD

**Issue by cdholmes** [geoschem/geos-chem#1464]
It appears that data in the HISTORY diagnostics are not written to the disk until the following diagnostic time interval. This can be frustrating for restart files (and any other instantaneous diagnostic). For example, on my system a restart file may be created on June 1, the metadata are written to disk but the data is not written to disk until the simulation reaches July 1, when the netCDF file is closed. I recently had a long simulation halt on June 3 (due to an unrelated system error). Since the June 1 data had not been written to disk, I had to restart on May 1 (frustrating).

For restart files (or all instantaneous diagnostics), it would be nice if the netCDF file is closed immediately or the data is otherwise promptly flushed to disk, so that simulations can restart if there is an error.

**Comment by yantosca** [comment]
We can now close this issue as PR #1515 has been merged into the 14.0.2 development stream.
