### ISSUE TITLE
[QUESTION] Offline seasalt emissions in HEMCO_Config.rc for Marine POA option?

### ISSUE THREAD

**Issue by Mashiat25** [geoschem/geos-chem#1466]
### Ask a question about GEOS-Chem:

I am using Marine POA simulation option to evaluate the contribution of marine primary organic aerosols to TOA over Benguela region. I have recently noticed that this option uses online seasalt in input.geos & HEMCO_Diagn.rc while turning on offline seasalt in HEMCO_Config.rc. I was wondering which condition (online/offline) overrides the other in such situation? Should I change it to online seasalt in HEMCO_Config.rc? Also, do we get proper representation of marine POA while the the seasalt is offline? 

[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/9873515/HEMCO_Config.txt)
[HEMCO_Diagn.txt](https://github.com/geoschem/geos-chem/files/9873513/HEMCO_Diagn.txt)
[input.geos.01..txt](https://github.com/geoschem/geos-chem/files/9873518/input.geos.01.txt)

**Comment by yantosca** [comment]
Thanks for writing @Mashiat25.  By default all of the fullchem simulations (except benchmark) are set up to use the offline seasalt (read from disk).  However, in the offline seasalt files there are only fields `SALA_TOTAL` and `SALC_TOTAL`.  So I believe for the marine POA simulation you should turn on the online seasalt in HEMCO_Config.rc:
```console
107     SeaSalt                : off   SALA/SALC/SALACL/SALCCL/SALAAL/SALCAL/BrSALA/BrSALC/MOPO/MOPI
```
Also I noticed in your input.geos the Marine POA switch is off:
```console
 => MARINE ORG AEROSOLS : F
```
So these are probably inconsistencies in the run directory generation that need to be corrected.  We usually don't test with the MarinePOA simulation so it's possible this slipped under the radar for us.

Note: we are phasing out input.geos in 14.0.0 for geoschem_config.yml, so I'll make sure that this gets set properly in the 14.0.0 version.

**Comment by Mashiat25** [comment]
Thanks @yantosca for your feedback! I'll make the changes you have suggested and try running it again.

Thanks for taking it in consideration for version 14.0.0.

**Comment by msulprizio** [comment]
@Mashiat25 This is already corrected in 14.0.0. When using `createRunDir.sh` to create a run directory, if you specify MarinePOA for the additional simulation option:

```
-----------------------------------------------------------
Choose additional simulation option:
-----------------------------------------------------------
  1. Standard
  2. Benchmark
  3. Complex SOA
  4. Marine POA
  5. Acid uptake on dust
  6. TOMAS
  7. APM
  8. RRTMG
4
```

the script will automatically change those settings for you in HEMCO_Config.rc.

https://github.com/geoschem/geos-chem/blob/0f85431c4beedb0af8325b54d789f910cd3d6357/run/GCClassic/createRunDir.sh#L958-L961

It looks like this came in for GEOS-Chem 13.4.0, so perhaps you are either using an older version without that modification or you started from a standard fullchem run directory.

**Comment by Mashiat25** [comment]
Thanks for your response @msulprizio. I am using version 13.4.0 so that might be the reason for those inconsistencies. However, do I need to turn on the Marine POA switch in input.geos for this simulation? If I do so, my simulation dies with the attached segmentation fault.

[gc_dryrun.txt](https://github.com/geoschem/geos-chem/files/9903577/gc_dryrun.txt)

**Comment by msulprizio** [comment]
Yes, the marine POA option should be turned on in input.geos. Can you confirm if you created your run directory using the `createRunDir.sh` script and selecting `Marine POA` as the additional simulation option? That should have automatically turned on the appropriate settings input.geos as well. If not, I would suggest recreating a clean run directory by selecting those options.

If you still get the above segmentation fault error, could you please upload the complete GEOS-Chem log file so we can better evaluate the error?

**Comment by Mashiat25** [comment]
I did create my run directory using createRunDir.sh script and selecting Marine POA as the additional simulation option. I recompiled after changing to the appropriate settings in HEMCO_Config and input.geos. Still, I'm getting the segmentation fault error. 

[logdryrun.txt](https://github.com/geoschem/geos-chem/files/9905809/logdryrun.txt)

**Comment by msulprizio** [comment]
The error message in your log file is:

```
===============================================================================
GEOS-Chem ERROR: LMPOA=T but MARINE ORGANIC AEROSOLS are undefined!
-> at Do_Error_Checks (in GeosCore/input_mod.F90)
===============================================================================
```

which is triggered by this code in `GeosCore/input_mod.F90`:

https://github.com/geoschem/geos-chem/blob/53cac3b937064bdceed21acec721a157b6fb8b1e/GeosCore/input_mod.F90#L5750-L5772

Can you check your input.geos and see if you have the species MOPO and MOPI included in the advected species list?

**Comment by Mashiat25** [comment]
No, these species are not included in the input.geos. Is there anything I can do to change that?

**Comment by Mashiat25** [comment]
Thanks for your help! The simulation is finally running.

**Comment by msulprizio** [comment]
Glad to hear that! I will close out this issue but feel free to open a new issue if you encounter any other problems.
