### ISSUE TITLE
[BUG/ISSUE] About the hdf during configure geoschem 

### ISSUE THREAD

**Issue by StrangeFrog** [geoschem/geos-chem#1469]
Hi, my name is Howie. I have encountered a problem during the configuration of geoschem (https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/spack.html#build-libraries-with-spack) on my own computer. I hope I can get your help.

### Description of the problem
 When I run this code line, I have encountered the problem in the image.
`$: spack install hdf5%gcc@10.2.0 target=x86_64 +cxx+fortran+hl+pic+shared+threadsafe`

![S5UIV9$X_NZRNHJBCFS2OO2](https://user-images.githubusercontent.com/93367256/198553233-f1a69cc5-87df-40f4-a5a4-8efd9558e919.png)

### Log files
- Build log (if applicable): NONE
- Run logs (if applicable): NONE
- Run script (if applicable): NONE

### Software versions
- CMake version: NONE
- Compilers (Intel or GNU, and version): gcc@10.2.0  gcc@7.5.0
- NetCDF version: NONE

**Comment by StrangeFrog** [comment]
Maybe this picture will provide some help for this problem.

![08MJN`FT)G VTAK~VQI(%%U](https://user-images.githubusercontent.com/93367256/198554379-f8eaff99-9999-4dfe-9ec4-4616757f0009.png)

**Comment by yantosca** [comment]
Thanks for writing @StrangeFrog.  You might want to post this issue on the [Spack Github page](https://github.com/spack/spack).  It may be that a newer version of Spack has changed the build process.  You could also try with an older Spack version to see if it works.

**Comment by yangbyy** [comment]
Hi, I had the same problem with my similation(GEOS CHEM V14.0.0). Can you tell me how you solved it? THANK U!

**Comment by yantosca** [comment]
When you clone spack, you are automatically placed on the newest branch (called "develop").  We have found that updates to this branch can cause issues in the build process, as they are often putting new features in that can potentially break other packages.

We would recommend cloning an older Spack release. The official releases are in the `releases/vX.Y` branches.  You can try er releases e.g.

```console
$ git clone -b releases/v0.18 https://github.com/spack/spack.git
```

v0.18 is the latest official release, but you can try older versions to find one that works.

Also tagging @Jourdan-He @SaptSinha

**Comment by yantosca** [comment]
Closing out this issue
