### ISSUE TITLE
[QUESTION] Visualizing and plotting GEOS-Chem output

### ISSUE THREAD

**Issue by ykaore** [geoschem/geos-chem#147]
Dears,
Where can I have the especifically manual for GEOS-Chem version 12.3.2? I am using this version, so when I try to understand what the model did/does, the website http://wiki.seas.harvard.edu/ it describes the newest version, which it is a bit different and cause some doubts.

I could sucessfully run the GEOS-Chem (just two months, because it was a test). But I`m trying to understand the outputs and how can I plot the map, and use the air pollutant concentrations time series to a regional model.

Thank you very much.
Best regards,
Yasmin.

**Comment by ykaore** [comment]
Dears, 
Where can I have the especifically manual for GEOS-Chem version 12.3.2? I am using this version, so when I try to understand what the model did/does, the website `http://wiki.seas.harvard.edu/` it describes the newest version, which it is a bit different and cause some doubts. 

I could sucessfully run the GEOS-Chem (just two months, because it was a test). But I`m trying to understand the outputs and how can I plot the map, and use the air pollutant concentrations time series to a regional model.

Thank you very much.
Best regards, 
Yasmin.

**Comment by yantosca** [comment]
Thanks for writing.  We have a pretty good GEOS-Chem Python tutorial that will guide you through the basics of making plots.  See: https://github.com/geoschem/GEOSChem-python-tutorial.

You can create time-series for any of the History diagnostics by saving to instantaneous concentrations at e.g. hourly or 3-hourly intervals.  I would also see the [Guide to GEOS-Chem History diagnostics](http://wiki.seas.harvard.edu/geos-chem/index.php/Guide_to_GEOS-Chem_History_diagnostics) that we have posted on the wiki.

The GCST would be unable to assist you with interfacing timeseries emissions into a regional model, but my guess is that as long as the output data is in netCDF then it should be pretty easy for the other model to read them in.
