### ISSUE TITLE
[QUESTION]Add a satellite XCO2 sampling diagnostic module like ObsPack

### ISSUE THREAD

**Issue by helpyuan** [geoschem/geos-chem#1470]
### Ask a question about GEOS-Chem:
Hi all,

I want to write a module for satellite XCO2 concentration sampling, similar to obspack_mod.F90, but this is the first time I try to write a module in GEOS-Chem v13.3.2. 

So I would like to ask if there is any guidance on adding modules to GEOS-Chem and if there are any calls between modules that I need to be aware of.

I appreciate any help.

**Comment by yantosca** [comment]
Thanks for writing @helpyuan.  We cannot offer much in the way of programming advice beyond this [style guide](http://wiki.seas.harvard.edu/geos-chem/index.php/Developing_GEOS-Chem).

Also we would recommend not to access global module variables from other modules when possible.  Inputs should be via Input_Opt, State_Grid, and State_Met; Outputs via State_Diag (diagnostics) and State_Chm (chemistry-related quantities).

**Comment by yantosca** [comment]
Also tagging @Jourdan-He and @SaptSinha

**Comment by helpyuan** [comment]
Thanks for replying @yantosca !

**Comment by yantosca** [comment]
Closing out this issue
