### ISSUE TITLE
Srun error: res_nsearch error:Unknown Host & DNS SRV lookup failed

### ISSUE THREAD

**Issue by yangbyy** [geoschem/geos-chem#1471]
I am a graduate student and am currently new to the field. Thank you very much for taking the time to answer my questions.

Firstly, when I try to run the command "./geoschem.run | tee GC ", the biggest problem I've encountered so far is the "Srun error", which can be specifically described by the following text.
**srun: error:** resolve_ctls_from_dns_srv: res_nsearch error: Host name lookup failure
**srun: error:** fetch_config: DNS SRV lookup failed
**srun: error:** _establish_config_source: failed to fetch config
**srun: fatal:** Could not establish a configuration source
![image](https://user-images.githubusercontent.com/115625689/198995099-b66fc3f4-5f9b-48a0-bae7-7fdc71f165c9.png)

I made some adjustments based on online tutorials, juast as described below, but still couldn't fix it.
![image](https://user-images.githubusercontent.com/115625689/198997114-52c1e177-c5c2-4080-9180-26dd6d579e6c.png)
My network connectivity is fine, as well as DNS. So, at the moment I don't know what the problem is or where to start. Could you please do me a favor?

Secondly, in an earlier step, when I try to run the command "./gcclassic --dryrun >  log.dryrun ", something wrong with "main.F90" was appeared, which can be specifically described by the following text.
![image](https://user-images.githubusercontent.com/115625689/198999815-1ac516e7-07e4-4862-88ea-dda00494fb6d.png)
I didn't process this issue, so could the final error reported be related to this?

Thirdly, I actually made some modifications of geoschem_config.yml, HEMCO_Config.rc and HISTORY.rc, relating to the end time of the run, DiagnFreq, Restart.frequency, Restart.duration, SpeciesConc. frequency and SpeciesConc. Duration. There are the files that I have made changes.
[geoschem_config.docx](https://github.com/geoschem/geos-chem/files/9900820/geoschem_config.docx)
[HEMCO_Config.docx](https://github.com/geoschem/geos-chem/files/9900825/HEMCO_Config.docx)
[HISTORY.docx](https://github.com/geoschem/geos-chem/files/9900831/HISTORY.docx)

GEOS-Chem version: 14.0.0
Operating system: Ununtu 22.04.1
Running Directory：gc_4x5_merra2_fullchem（Standard, MERRA2, 4.0*5.0, 72 levels）
Start time of run:  20190701 000000
End time of run:   20190701 010000
[HEMCO_Diagn.docx](https://github.com/geoschem/geos-chem/files/9900873/HEMCO_Diagn.docx)
[geoschem.docx](https://github.com/geoschem/geos-chem/files/9900896/geoschem.docx)
![image](https://user-images.githubusercontent.com/115625689/199006009-88553b5c-5c3d-4a89-b0fc-4fc4e5559736.png)

### Log files
[log.docx](https://github.com/geoschem/geos-chem/files/9900869/log.docx)
[GC.docx](https://github.com/geoschem/geos-chem/files/9900871/GC.docx)

### Software versions
- CMake version: 3.22
- Compilers (Intel or GNU, and version): GNU 11.2.0
- NetCDF version: 4.5.4

**Comment by yangbyy** [comment]
Maybe this picture will provide some help for this problem.
![image](https://user-images.githubusercontent.com/115625689/199009414-def38201-659b-4a16-a355-c8e6ee4e463f.png)

**Comment by yantosca** [comment]
Thanks for writing @yangbyy.  Are you running GEOS-Chem on the AWS cloud?  If so then you don't need to do `sbatch geoschem.run`.  You can just run at the command line `./geoschem.run`.   The sbatch command is for the SLURM scheduler (which is one of the schedulers used on multi-user systems).  If you are on the cloud or on your own virtual machine, then you own the whole instance and you don't have to worry about other users  -- so no need for a scheduler.

Also tagging @Jourdan-He and @SaptSinha.

**Comment by yangbyy** [comment]
Thank you very much for your reply. Actually, I am on my own virtual machine, not the cloud. Though I own the whole instance, I still can't get any output results by using the command "./geoschem.run | tee GC.log". Is there something wrong with my final command? If so, what is the correct command to execute the running program? Or could you guide me to perhaps what steps went wrong? I'm at the end of my rope. I am looking forward to your reply. -- your sincerely little yang.

**Comment by yangbyy** [comment]
Here's my latest run. Could you please give me some advice on what should I check firstly?
![image](https://user-images.githubusercontent.com/115625689/199209567-42ec7ccb-d59a-42e6-9698-739c5b02e349.png)
![image](https://user-images.githubusercontent.com/115625689/199209931-20324040-7456-4f95-b1b0-6034f83aa30d.png)
[GC.log](https://github.com/geoschem/geos-chem/files/9908844/GC.log)

**Comment by yantosca** [comment]
You could also try installing nproc with your package manager if you don't have it.

Also tagging @Jourdan-He and @SaptSinha

**Comment by yangbyy** [comment]
Thank you very much for your reply.  I didn't try using manually setting OMP_NUM_THREADS to the number of cores.  Next, I will try to  install on my virtual machine. Thanks again, I will continue to share my problems.  -- your sincerely little yang.

**Comment by androidpifu** [comment]
@yangbyy , I haved a same bugs that you issued. Do you solved this problem.

**Comment by yangbyy** [comment]
Actually, I found out that the error was caused by my incorrect run command. Because I was running it on my local computer, the  command statement (_sbatch geoschem.run_ or _./geoschem.run_) didn't fit ( from what I understand, it fits the run on the cloud server). Therefore, the run statement I can use is this: _./gcclassic | tee GC.log_
Not sure if my answer helped.
