### ISSUE TITLE
[BUG/ISSUE] missing file at OFFLINE_SOILNOX/v2021-12/0.5x0.625/2015/12/?

### ISSUE THREAD

**Issue by hyungmini** [geoschem/geos-chem#1474]
### What institution are you from?
Please tell us what institution you are from.
Ewha Womans University

### Description of the problem
Describe your problem here.  Describe the steps to reproduce the problem here, if possible.
The file for 20151231 is missing at HEMCO/OFFLINE_SOILNOX/v2021-12/0.5x0.625/2015/12/ (I am looking at the WashU server)

**Comment by Jourdan-He** [comment]
@hongjianweng This is the same missing file as in issue #1440 . Could you take a look?

**Comment by YanshunLi-washu** [comment]
Hi @hyungmini @Jourdan-He I've reproduced and uploaded this file, feel free to check this path:
http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_SOILNOX/v2021-12/0.5x0.625/2021/12/

**Comment by Jourdan-He** [comment]
Thanks @YanshunLi-washu !
