### ISSUE TITLE
GCClassic14.0.0_signal SIGSEGV: Segmentation fault

### ISSUE THREAD

**Issue by yangbyy** [geoschem/geos-chem#1479]
When I use the command "./gcclassic > GC.log", here comes the problems:
![image](https://user-images.githubusercontent.com/115625689/199770651-7c20bf71-f177-4439-a261-9109fc90bb49.png)

Plus, there are my latest log.dryrun and GC.log respectively.
[log.txt](https://github.com/geoschem/geos-chem/files/9930956/log.txt)
[GC.log](https://github.com/geoschem/geos-chem/files/9930884/GC.log)

There are some configure files, which may be helpful!
[geoschem_config.txt](https://github.com/geoschem/geos-chem/files/9930947/geoschem_config.txt)
[HISTORY.txt](https://github.com/geoschem/geos-chem/files/9930950/HISTORY.txt)
[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/9930958/HEMCO_Config.txt)
[HEMCO_Diagn.txt](https://github.com/geoschem/geos-chem/files/9930961/HEMCO_Diagn.txt)
[HEMCO_Config_rc.txt](https://github.com/geoschem/geos-chem/files/9930972/HEMCO_Config_rc.txt)

**Comment by yantosca** [comment]
Thanks for writing.  The error is caused by the restart file timestamp not matching the start date of your simulation.  Please see #1450 for a workaround.

**Comment by yangbyy** [comment]
Thank you! I think I've worked it out. So I'm going to close this topic.
