### ISSUE TITLE
GCClassic14.0.0_./gcclassic_no output

### ISSUE THREAD

**Issue by yangbyy** [geoschem/geos-chem#1481]
### Ask a question about GEOS-Chem:
When I use the command "./gcclassic | tee GC.log", I checked the GC.log file and there was no error reported throughout the process, but I didn't get any output either. Moreover, sometimes the program flickers when I run the command, until now I didn't quite understand what the problem is. There are some screenshots on this issue.
![image](https://user-images.githubusercontent.com/115625689/199963845-9f4742a9-64d6-46cc-97b3-3f797aa7b760.png)
![image](https://user-images.githubusercontent.com/115625689/199963366-52f53412-d402-4269-9e75-70f13d799470.png)
 
Plus, these files below may help  understand my issue.
[log.txt](https://github.com/geoschem/geos-chem/files/9937850/log.txt)
[GC.txt](https://github.com/geoschem/geos-chem/files/9937853/GC.txt)
[geoschem_config.txt](https://github.com/geoschem/geos-chem/files/9937858/geoschem_config.txt)
[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/9937859/HEMCO_Config.txt)
[HEMCO_Config_rc.txt](https://github.com/geoschem/geos-chem/files/9937861/HEMCO_Config_rc.txt)
[HEMCO_Diagn.txt](https://github.com/geoschem/geos-chem/files/9937863/HEMCO_Diagn.txt)

**Comment by yantosca** [comment]
Thanks for writing @yangbyy.  Your run stopped after the TPCORE initialization occurred:
```console
===============================================================================
TPCORE_FVDAS (based on GMI) Tracer Transport Module successfully initialized
===============================================================================
```
which is indicative of [not having environment variables set properly](https://geos-chem.readthedocs.io/en/stable/gcc-guide/01-startup/login-env-parallel.html#errors-caused-by-incorrect-environment-variable-settings) 

We invite you to read the GEOS-Chem and HEMCO user manuals if you are new to GEOS-Chem:
- https://geos-chem.readthedocs.io
- https://hemco.readthedocs.io

**Comment by yantosca** [comment]
This issue is a duplicate of #1390

**Comment by yangbyy** [comment]
Sorry, I can't get this point. Indeed, I'm new to this. I tried to set OMP_STACKSIZE bigger, but nothing changed. So  Can you give some more specific instructions? This question is driving me crazy. Thank you very, very much. --sincerely little yang.

**Comment by yangbyy** [comment]
Sorry to take up your time. I really ran out of ideas. In my simulation, is “SIGKILL” is equivalent to "Segmentation fault"? At this time, I really do not know how to fix it. THANK U! --sincerely little yang
![c2bc285cdf3d9b98ade8c53b75baed8](https://user-images.githubusercontent.com/115625689/200568382-9233bc7d-006a-406d-9597-36b883702103.jpg)

**Comment by yantosca** [comment]
Thanks for the update @yangbyy.  A SIGKILL is a program termination, usually by the operating system:

>Macro: int SIGKILL
>The SIGKILL signal is used to cause immediate program termination. It cannot be handled or ignored, and is therefore always fatal. It is also not possible to block this signal.
>
>This signal is usually generated only by explicit request. Since it cannot be handled, you should generate it only as a last resort, after first trying a less drastic method such as C-c or SIGTERM. If a process does not respond to any other termination signals, sending it a SIGKILL signal will almost always cause it to go away.
>
>In fact, if SIGKILL fails to terminate a process, that by itself constitutes an operating system bug which you should report.
>
>The system will generate SIGKILL for a process itself under some unusual conditions where the program cannot possibly continue to run (even to run a signal handler).

Usually this happens when a program takes up too many system resources and the operating system has to terminate the program to avoid a system crash.

What type of system are you trying to run GEOS-Chem on?  It could be that your system does not have enough memory for the simulation that you are trying to run.

**Comment by yantosca** [comment]
Also tagging @Jourdan-He @SaptSinha

**Comment by yantosca** [comment]
Oh, OK.  So you are using the Windows Subsystem for Linux on a local PC.  Depending on the simulation you are trying to do, there just might not be enough memory on your local PC for it.

We would also recommend using GEOS-Chem on a cluster or on the AWS cloud if possible rather than on a PC.

**Comment by yangbyy** [comment]
Thanks for your help!  I tried to reset the momory size and the number of processors , then this problem disappeared. You're my savior!
![image](https://user-images.githubusercontent.com/115625689/200869674-89f80e8c-fad1-490c-b8c8-b23b830931b6.png)
