### ISSUE TITLE
[BUG/ISSUE]The simulation results of sulfate in GCAP2.0 is higher

### ISSUE THREAD

**Issue by zhiweistu** [geoschem/geos-chem#1486]
### What institution are you from?
Peking University.

### Description of the problem
Dear GEOSChem developer and GCAP2.0 developer,

I used GCAP2.0 (E2.1 meteorological data) to simulate sulfate in 2014. But I find the simulated result is higher than observation(about 100%) and most of the cmip6 models. May I ask what the reason is ?

Besides, Does the same higher simulation of sulfate happen in the normal version(MERRA2-driven)?

Do you have the official GCAP 2.0 and normal gc sulfate simulation results of 2014 for my reference?
I'd really appreciate it if you could solve my problem!

### GEOS-Chem version
13.4.1
### gcap2.0 files
[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/9945342/HEMCO_Config.txt)
[HEMCO_Diagn.txt](https://github.com/geoschem/geos-chem/files/9945344/HEMCO_Diagn.txt)
[HISTORY.txt](https://github.com/geoschem/geos-chem/files/9945345/HISTORY.txt)

### Supplementary information
1.Observation and GCAP2.0 sulfate simulation
![image](https://user-images.githubusercontent.com/109276335/200159910-9cf9e4f7-f552-4654-8c73-c398db0b99d3.png)
(sulfate concentration is year mean, the first black line is 1:1 , the second black is 1:2,observation data from Eanet,Castnet,EMEP, using 105 station data in 2014.)

2.GCAP2.0 and 6 cmip6 models results
![image](https://user-images.githubusercontent.com/109276335/200159941-57c00fd5-0cb6-42cd-9d5d-5646820e3403.png)
(GCAP2.0 is 5.02e-06,CESM2-WACCM-FV2 is 4.80e-06)

**Comment by zhiweistu** [comment]
3.2014 GCAP2.0 sulfate column concerntration (my simulation result)
![2014_gcap2 0](https://user-images.githubusercontent.com/109276335/200160546-728b792f-7463-4f23-a62b-34adb925ef4b.png)

**Comment by yantosca** [comment]
Thanks for writing @zhiweistu.  This is a scientific question and as such, it lies outside the expertise of the GEOS-Chem Support Team.  Tagging @ltmurray, who is our local expert on the GCAP2 simulation.

Also tagging @Jourdan-He and @SaptSinha.

**Comment by ltmurray** [comment]
Figure 18 of Murray et al. (2021) shows the comparison of SO2 columns and surface PM2.5 between GCAP 2.0 and the regular MERRA2 simulation. I would first check to see if you are able to consistently reproduce those values. Otherwise, you may have an issue with your restart file not being appropriately initialized (resulting in too much sulfate in the stratosphere where it will linger in the model).

**Comment by zhiweistu** [comment]
Thanks for replying @yantosca  @ltmurray . 

I downloaded GCAP2.0 restart file from 
input/gc/ExtData/GCAP2_RESTARTS/v2021-09/40L/GCAP2.Restart.fullchem.20190701_0000z.nc4

I used cdo to change the date of GCAP2 restart file to 20130701, and used it to spin up 6 months to restart my simulation.(simulation time: 20130701-20150101)

I will simulate it again and let you know results!

Best Regards

**Comment by ltmurray** [comment]
There will not be a major difference between the decadal mean and the 2014 value. But here are the sulfate concentrations for 2014 from the free-running GCAP2 simulations in that manuscript.
[SO4.2014.nc.zip](https://github.com/geoschem/geos-chem/files/9963668/SO4.2014.nc.zip)

**Comment by zhiweistu** [comment]
Hi @yantosca @ltmurray. I used GCAP2.0(GC 14.0.1) simulated the sulfate again. The output results is very similar with my previous results. And I am able to reproduce my previous results(GC 13.4.1). 

This is a vertical comparison between your results and mine(using GC 13.4.1). My results is higher than your, especially in surface. I think your results is more reasonable, I hope we can find the reason introduce the higher surface concentration and fix it.

![image](https://user-images.githubusercontent.com/109276335/205479495-e386e537-8b83-4512-85da-e8d0e9368d58.png)
Thanks for your helps!

**Comment by yantosca** [comment]
Thanks for writing @zhiweistu.  As this is a research issue we would look to the GEOS-Chem user community to assist in finding a solution.
