### ISSUE TITLE
[QUESTION]How to modify GCAP2.0 resolution?

### ISSUE THREAD

**Issue by pku-tjh** [geoschem/geos-chem#1493]
Hi, everyone.
I want to use GCAP2.0 simulation, but I find the option is only 2x2.5 resolution. To save compute resource, I want to use 4x5 resolution. How can I set it?
My GCclassic version is 13.4.1
Thanks for helps!

**Comment by yantosca** [comment]
Thanks for writing @kimm1na.  You can still use 4x5 resolution, but the data will be regridded, as the GCAP2 met fields are at 2 x 2.5.

Tagging @ltmurray, also @Jourdan-He and @SaptSinha
