### ISSUE TITLE
[BUG/ISSUE] UCX_MOD Error & GEOS-CHEM I/O ERROR

### ISSUE THREAD

**Issue by jiaying002** [geoschem/geos-chem#1495]
After I submitted my job, it run for 40 seconds, then I got this error from GC.log.
![image](https://user-images.githubusercontent.com/113654537/201076648-9565f0e9-bf3b-4b96-9709-f45259fccdf7.png)
I don't know how to solve those two errors. I would be super appreciative if anyone could help. Thanks!

Here are some files that might be useful:
[GC.log.txt](https://github.com/geoschem/geos-chem/files/9980520/GC.log.txt)
[geoschem_config.yml.txt](https://github.com/geoschem/geos-chem/files/9980515/geoschem_config.yml.txt)
[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/9980516/HEMCO_Config.rc.txt)
[HISTORY.rc.txt](https://github.com/geoschem/geos-chem/files/9980519/HISTORY.rc.txt)

**Comment by yantosca** [comment]
Thanks for writing @jiaying002.  Have you looked at the file `/home/jiaying002/GCClassic/src/CHEM_INPUTS/UCX_201403/NoonTime/Grid2x25/InitCFC_JN2O_01.dat` to make sure that (1) it is on disk and (2) it isn't corrupted?  That is the first step.

**Comment by jiaying002** [comment]
Thank you so much, it turns out that the file is corrupted. Sorry for this stupid question. Thank you!
