### ISSUE TITLE
[QUESTION] Where are compiler options defined when using unit tester to create a rundir?

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/geos-chem#151]
Hi there,

I accidentally know the role of the first line in `input.geos` file when I asked how to run a nested simulation [here](https://github.com/geoschem/geos-chem/issues/31), where @msulprizio told me that the first line in `input.geos` tells the Makefile what GRID, MET, and simulation we will use. I tested this recently and found that it does great job and hence it might be a good way to specify compiler options as we usually do explicitly in command line. However, I found no description about this on your [wiki](http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_input_files#The_input.geos_file), which I personally think might be worthy added to inform users.

Nevertheless, I still have one confusion that I want to confirm. Below shows two settings for the first line in `input.geos` and corresponding `lastbuild.mp` information. I found four fields changed, namely `MET, GRID, SIM, CHEM`. I can understand the first three but not the last one. My question lies in that is the `CHEM` automatically determined by `MET, GRID, SIM`?

- GEOS-CHEM UNIT TEST SIMULATION: geosfp_2x25_complexSOA_SVPOA
![image](https://user-images.githubusercontent.com/43779303/69439658-4f22c180-0d3f-11ea-98a7-79b9339fb16c.png)

- GEOS-CHEM UNIT TEST SIMULATION: merra2_4x5_complexSOA
![image](https://user-images.githubusercontent.com/43779303/69439688-63ff5500-0d3f-11ea-95e3-33150bacbc2c.png)

Thanks for your help in advance!

**Comment by FeiYao-Edinburgh** [comment]
Following my first comment above, I just realise that we also need to re-compile the geos-chem if we change certain but not all contents in the `input.geos` file. This could be a caveat and might be suggested to remind users too?

**Comment by msulprizio** [comment]
Starting in [GEOS-Chem 12.4.0](http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_12#12.4.0), users no longer need to recompile GEOS-Chem for the met grid, resolution, and nested domain that they want to use. These options are now determined at runtime from the settings in the simulation menu and grid menu of input.geos and are printed to the GEOS-Chem log file instead of lastbuild. Please see a complete description of these updates on the [FlexGrid wiki page](http://wiki.seas.harvard.edu/geos-chem/index.php/FlexGrid#Define_meteorology_field_and_grid_parameters_in_input.geos). The documentation on the [GEOS-Chem input files wiki page](http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_input_files#The_input.geos_file) reflects these updates -- in general, the GEOS-Chem wiki documentation reflects the current public release version of GEOS-Chem unless otherwise noted.

**Comment by FeiYao-Edinburgh** [comment]
Thanks for your reply. Honestly, I think the simulation menu and grid menu of input.geos can only tell met grid, resolution, and nested domain just as you mentioned.

What I really want to know is the mechanism ***how GC determines SIM and CHEM shown in lastbuild, i.e. which part in input.geos tells it?***. I appreciate your further reply.

**Comment by yantosca** [comment]
See the Makefile in the run directory.  It has several switches that set the proper options.  

```make
ifeq ($(SIM),benchmark)
 CHEM        :=Standard
 TIMERS      :=1
endif

ifeq ($(SIM),aciduptake)
 CHEM        :=Standard
endif

ifeq ($(SIM),marinePOA)
 CHEM        :=Standard
endif

ifeq ($(SIM),complexSOA)
 CHEM        :=Tropchem
endif

ifeq ($(SIM),complexSOA_SVPOA)
 CHEM        :=SOA_SVPOA
 NEST        :=n
endif

ifeq ($(SIM),tropchem)
 CHEM        :=Tropchem
endif

ifeq ($(SIM),custom)
 CHEM        :=Custom
endif
```

**Comment by FeiYao-Edinburgh** [comment]
> See the Makefile in the run directory.

This makes sense. Now I can confirm that `CHEM` is determined by `SIM`, which is determined by the first line in `input.geos`.




> Starting in [GEOS-Chem 12.4.0](http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_12#12.4.0), users no longer need to recompile GEOS-Chem for the met grid, resolution, and nested domain that they want to use. These options are now determined at runtime from the settings in the simulation menu and grid menu of input.geos and are printed to the GEOS-Chem log file instead of lastbuild.

But lastbuild still contains MET, GRID, and SIM determined from the first line in `input.geos` and we can still re-compile the model by changing the first line in `input.geos`. That's why I think it is important to inform the role of the first line in `input.geos`, which is currently missing in the wiki.

**Comment by msulprizio** [comment]
>But lastbuild still contains MET, GRID, and SIM determined from the first line in input.geos and we can still re-compile the model by changing the first line in input.geos. That's why I think it is important to inform the role of the first line in input.geos, which is currently missing in the wiki.

MET, GRID, and SIM were inadvertantly left at the top of input.geos in GEOS-Chem 12.4.0 and 12.5.0, even though they're not actually used aside from printing information to the lastbuild file. In GEOS-Chem 12.6.0, the input.geos and run directory Makefiles were cleaned up to remove MET, GRID, and SIM to avoid such confusion. These lines are no longer included in lastbuild. For example, see the lastbuild file from the GEOS-Chem 12.6.0 1-month benchmark: http://ftp.as.harvard.edu/gcgrid/geos-chem/1mo_benchmarks/GC_12/12.6.0/GCC/lastbuild.

**Comment by FeiYao-Edinburgh** [comment]
> MET, GRID, and SIM were inadvertantly left at the top of input.geos in GEOS-Chem 12.4.0 and 12.5.0, even though they're not actually used aside from printing information to the lastbuild file.

Good to know but just want to have one more check. [FlexGrid wiki](http://wiki.seas.harvard.edu/geos-chem/index.php/FlexGrid) only says that MET and GRID are omitted when compiling. In the GC 12.6 lastbuild you provided, I also see CHEM, which is determined by SIM according to @yantosca 's hint above. Therefore, if the first line in `input.geos` is useless, how does the GC determine SIM and thereby CHEM in GC 12.5.0 whose rundir still has input.geos and Makefile?

**Comment by msulprizio** [comment]
The first line in input.geos that used to include MET_GRID_SIM is completely removed from GEOS-Chem 12.6.0. The information about the simulation type used to determine which chemistry mechanism to use is now defined in the Simulation Menu of input.geos (see last line):

```
%%% SIMULATION MENU %%% :
Start YYYYMMDD, hhmmss  : 20160701 000000
End   YYYYMMDD, hhmmss  : 20160801 000000
Run directory           : ./
Root data directory     : /n/holylfs/EXTERNAL_REPOS/GEOS-CHEM/gcgrid/data/ExtData
Met field               : geosfp
Simulation name         : benchmark
```

The script `getRunInfo` in the run directory obtains the simulation name from input.geos and passes that information to the `Makefile` to determine which chemistry mechanism to use as described in @yantosca's  post.

**Comment by FeiYao-Edinburgh** [comment]
> The information about the simulation type used to determine which chemistry mechanism to use is now defined in the Simulation Menu of input.geos (see last line)

This makes sense. Thanks for your reply. But I believe the first line in input.geos that used to include MET_GRID_SIM is still useful for GC versions prior to 12.6.0 like 12.5.0?

BTW, I suppose the last line in the Simulation Menu of input.geos has not been posted on your wiki yet.

**Comment by yantosca** [comment]
Thanks.  We can add that to the wiki.

**Comment by FeiYao-Edinburgh** [comment]
> But I believe the first line in input.geos that used to include MET_GRID_SIM is still useful for GC versions prior to 12.6.0 like 12.5.0?

I have verified this by removing the first line and compiling. Complainants occurred in `getRuninfo` and hence my statement is correct. Benefiting from Flex Grid, now only `CHEM` matters!
