### ISSUE TITLE
[BUG/ISSUE] HEMCO time shift issue in a nested china simulation initializing met fields

### ISSUE THREAD

**Issue by jin-choi** [geoschem/geos-chem#1517]
### What institution are you from?
CU Boulder

### Description of the problem

**A nested China simulation starting from _2016/04/01-00:00_** stopped at its initialization when it was starting to read GEOS-FP met fields. Instead of opening the right file (_GEOSFP.20160401.A1.025x03125.nc_), the simulation opened _GEOSFP.20160331.A1.025x03125.nc_, hence it couldn't get the field for the right date and time (_201604010030_). 

There was no issue in my global simulations. 

### Description of troubleshooting performed
N/A

### GEOS-Chem version
GEOs-Chem Classic v14.0.1

### Description of modifications
N/A

### Log files
- HEMCO.log:
125780 -------------------------------------------------------------------------------
125781  Processing container: ALBEDO
125782  Parsing source file and replacing tokens
125783  Adjusted time stamp of field ALBEDO
125784  Time shift (YMDhms):            0           0           0           0          30                  0
125785  Original Yr/Mt/Dy-Hr:Mn = 2016/04/01-00:00
125786  Adjusted Yr/Mt/Dy-Hr:Mn = 2016/04/01-00:30
125787  Opening file: /glade/scratch/jinkyulchoi/GCdata/GEOS_0.25x0.3125/GEOS_FP/2016/03/GEOSFP.20160331.A1.025x03125.nc
125788 HEMCO: Entering GET_TIMEIDX (HCOIO_UTIL_MOD.F90) ( 6)
125789  Number of time slices found:           24
125790  Time slice range :    201603310030.000        201603312330.000
125791  Adjusted time stamp of field ALBEDO
125792  Time shift (YMDhms):            0           0           0           0          30                  0
125793  Original Yr/Mt/Dy-Hr:Mn = 2016/04/01-00:00
125794  Adjusted Yr/Mt/Dy-Hr:Mn = 2016/04/01-00:30
125795           preferred datetime:  201604010030.
125796  Data is hourly. Entire day will be read.
125797               selected tidx1:             -1
125798         assigned delta t [h]:              0
125799  local time?  F
125800 HEMCO: Leaving GET_TIMEIDX (HCOIO_UTIL_MOD.F90) ( 6)
125801 
125802 -------------------------------------------------------------------------------
125803 HEMCO 3.0.0 FINISHED.
125804 Warnings (level 3 or lower):    225
125805 -------------------------------------------------------------------------------

**Comment by yantosca** [comment]
Thanks for writing @jin-choi.  Could you attach to this issue:
1. The entire GEOS-Chem log output (GC.log)
2. The entire HEMCO log output
3. Your HEMCO_Config.rc file

We would need to see these inputs to be able to diagnose what happened.

**Comment by yantosca** [comment]
Also tagging @Jourdan-He and @SaptSinha

**Comment by yantosca** [comment]
Closing out this issue
