### ISSUE TITLE
[QUESTION] The model value of NH4 wet deposition

### ISSUE THREAD

**Issue by LuoBiaodll** [geoschem/geos-chem#1518]
### Ask a question about GEOS-Chem:

I simulated 1-month and got wetlossls and wetlossconv diagnostics file in GCHP 13.2.1. I found that the unit is kg/s, how can i convert it into kg/m2? I got kg/m2 by summing the wetloss vertical layers, multiplying by the simulation time and dividing by the grid area. However, I found that the conversion result is quite different from the actual. In addition, I found the Budgetwetdep diagnostic value is negative when the wetloss summing value is positive. Is that right?

Could you give me some suggestions? Thanks very much for your time and help.

**Comment by yantosca** [comment]
Tagging @Jourdan-He and @SaptSinha for reference.

**Comment by LuoBiaodll** [comment]
Thanks for your reply. I have checked the diagnostic file, in which i didn't find AREA varaible. I also checked the HISTORY.rc.
For budget, may be it's difference between initial and final (final minus innitial)?

**Comment by yantosca** [comment]
@LuoBiaodll: are you using GCHP?  If so then the AREA would not be in the diagnostic files (it is only for GCClassic).  You can also use the area values (m^2) stored in Met_AREAM2 in the StateMet collection.

**Comment by LuoBiaodll** [comment]
Yes, i am using GCHP. I will turn on 'StateMet' collection. Thank you very much!

**Comment by yantosca** [comment]
Thanks @LuoBiaodll.  I'll close out this issue now.
