### ISSUE TITLE
[QUESTION]How to change the ExtData path?

### ISSUE THREAD

**Issue by pku-tjh** [geoschem/geos-chem#1524]
### Ask a question about GEOS-Chem:
Hi, everyone. My gc version is 14.0.1.
When I first run gc, It prompted me to enter the path of ExtData. Now I want to change the path I first entered, What files should I modify?
Thanks for your helps!

**Comment by yantosca** [comment]
Thanks for writing @pku-tjh.  The first time you create a run directory, the path to ExtData is stored in the file `~/.geoschem/config` in your home directory.  To change the path, edit the GC_DATA_ROOT variable in this file:

```bash
export GC_DATA_ROOT=/path/to/your/ExtData
```

**Comment by yantosca** [comment]
Also tagging @Jourdan-He and @SaptSinha for reference

**Comment by pku-tjh** [comment]
Thanks for the answer! I will close this comment
