### ISSUE TITLE
[FEATURE REQUEST] Expand version checkout info on Read the Docs 

### ISSUE THREAD

**Issue by jhaskinsPhD** [geoschem/geos-chem#1525]
### Request a new GEOS-Chem feature

I was hoping we could expand the documentation on ReadtheDocs about how to properly checkout older versions of GEOS-Chem. I'm hitting a lot of errors that I think come from me checking out the right GCClassic version, but not the right corresponding HEMCO version and a few more explicit examples on the ReadtheDocs would certainly help me/others, I think!

**Comment by msulprizio** [comment]
See the instructions from @lizziel in https://github.com/geoschem/geos-chem/issues/1559. Essentially, you need to remember to update the submodules after checking out a branch, commit, or tag from the super project.

**Comment by jhaskinsPhD** [comment]
I'd followed those but I still couldn't get 13.3.4 to compile- though I now believe this is because we recently moved servers & have had a lot of under the hood changes. All of the compiled source code I had for the versions I've been working on got deleted in the server move, but now that things are a bit more stable, I'll try again & report back if I have ongoing issues.

**Comment by msulprizio** [comment]
@jhaskinsPhD That makes sense. I would suggest doing a fresh clone of GCClassic in that case and then trying to revert to an older version. Git uses many hidden files, so perhaps some of those were not carried over.

**Comment by yantosca** [comment]
@jhaskinsPhD @msulprizio: Also, your new server might use a slightly different O/S version, so that means that any binary files (like the Git objects in the `.git` folder) from the old server might not be readable on the new server.  When moving servers it's always good to re-download and/or re-install software to remove any binary file incompatibilities from happening.

**Comment by yantosca** [comment]
Closing out this issue for now.
