### ISSUE TITLE
[BUG/ISSUE] NetCDF files with a missing time dimension (or with time[0] != 0)

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#1528]
Similar to #1527, files without a netCDF time dimension are problematic for GCHP.  I will keep a list of such files here.

1. ExtData/HEMCO/CH4/v2017-10/GEPA/GEPA_Annual.nc
    - The time dimension is missing
    - lat is not monotonic

2. ExtData/HEMCO/CH4/v2017-10/GEPA/GEPA_Daily.nc
    - lat is not monotonic
    - time[0] != 0 (this is required for GCHP) ]
    - time:calendar is missing 
    -  "time:units" should be "{days,hours,minutes,seconds} since" a reference date/time"

3. ExtData/HEMCO/CH4/v2017-10/GEPA/GEPA_Monthly.nc
    - lat is not monotonic

4. ExtData/HEMCO/CH4/v2020-09/Scarpelli_Mexico/MEX_Tia2020*.nc
    - Files are missing a time dimension

Also the following files have `time[0] != 0`, which also causes GCHP to die with an ExtData error.

1. ExtData/HEMCO/CO2/v2015-04/BIO/Net_terrestrial_exch_5.29Pg.generic.1x1.nc

**Comment by yantosca** [comment]
Tagging @msulprizio @Jourdan-He @SaptSinha @lizziel

**Comment by lizziel** [comment]
See this feature request in GEOS-Chem to expand our coards check script to include the GCHP requirements. This might help catch these issues earlier.
https://github.com/geoschem/geos-chem/issues/281

**Comment by lizziel** [comment]
And also this feature request which is related: https://github.com/geoschem/geos-chem/issues/1068

**Comment by yantosca** [comment]
NOTE: I have created the repo https://github.com/geoschem/netcdf-scripts/, with an updated version of `isCoards`.  This should now catch a couple of more issues that will prevent files from being read into GCHP.

**Comment by yantosca** [comment]
Update:
1. COARDS-compliant GEPA files are now in `ExtData/HEMCO/CH4/v2024-11/GEPA/`
2. COARDS-compliant Scarpelli_Mexico files are now in `ExtData/HEMCO/CH4/v2024-11/Scarpelli_Mexico/`

**Comment by yantosca** [comment]
Also note: https://github.com/geoschem/netcdf-scripts/ v0.1.2 now contains an updated version of isCoards that checks if any of the variables are of type "int".

**Comment by yantosca** [comment]
The `isCoards` file in [netcdf-scripts v0.1.5 and later](https://github.com/geoschem/netcdf-scripts/releases/tag/v0.1.5) has been updated to catch more issues that would render netCDF file unreadable by GCHP.  We can close out this issue now.
