### ISSUE TITLE
[BUG/ISSUE] GEOS-CHEM ERROR: Could not find FLASH_DENS in HEMCO data list!

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/geos-chem#153]
## Describe the bug
I am running GC 12.5.0 to do a global 2x2.5 complexSOA_SVPOA simulation for year 2013. I have realised the several new emission directories and downloaded them in time. Some of these new directories do not contain data for 2013 or before and hence I turned them off in `HEMCO_Config.rc`. However, I still got the following error.
```
HEMCO ERROR: Cannot find file for current simulation time: /geos/d21/s1855106/ExtData/HEMCO/OFFLINE_LIGHTNING/v2019-01/GEOSFP/1712/FLASH_CTH_GEOSFP_0.25x0.3125_1712_01.nc4 - Cannot get field FLASH_DENS. Please check file name and time (incl. time range fl
```
To address this bug, I searched `HEMCO_Config.rc` again but can only found the following two entries within Base emission menu. I thus turned them off by prepending `#` at the beginning of each line as I have not found corresponding [data files](http://ftp.as.harvard.edu/gcgrid/data/ExtData/HEMCO/OFFLINE_LIGHTNING/v2019-01/GEOSFP/) for 2013.
```
#* FLASH_DENS $ROOT/OFFLINE_LIGHTNING/v2019-01/$MET/$YYYY/FLASH_CTH_$MET_0.25x0.3125_$YYYY_$MM.nc4  LDENS 1980-2019/1-12/1-31/0-23/+90minute RFY xy  1  * -  1 1
#* CONV_DEPTH $ROOT/OFFLINE_LIGHTNING/v2019-01/$MET/$YYYY/FLASH_CTH_$MET_0.25x0.3125_$YYYY_$MM.nc4  CTH   1980-2019/1-12/1-31/0-23/+90minute RFY xy  1  * -  1 1
```
However, this brought me the following new error that I have not solved it yet.
```
===============================================================================
GEOS-CHEM ERROR: Could not find FLASH_DENS in HEMCO data list!
STOP at GET_MET_2D (get_met_mod.F90)
===============================================================================
```
As it indicates the error occurred at GET_MET_2D (get_met_mod.F90), I was wondering if I could address it by using a previous get_met_mod.F90 like in GC 12.2.1. However, using `diff` command I found their arguments are different... so I am here to seek for your help.
```
51c51
<   SUBROUTINE Get_Met_2D( Q, v_name, t_index )
---
>   SUBROUTINE Get_Met_2D( State_Grid, Q, v_name, t_index )
58a59
>     USE State_Grid_Mod,     ONLY : GrdState
63,64c64,66
<     CHARACTER(LEN=*),INTENT(IN)            :: v_name    ! netCDF variable name
<     INTEGER,         INTENT(IN), OPTIONAL  :: t_index   ! Time index (default=1)
---
>     TYPE(GrdState),  INTENT(IN)            :: State_Grid ! Grid State object
>     CHARACTER(LEN=*),INTENT(IN)            :: v_name     ! netCDF variable name
>     INTEGER,         INTENT(IN), OPTIONAL  :: t_index    ! Time index(default=1)
68,69c70,71
<     REAL*4,          INTENT(OUT)           :: Q(IIPAR,JJPAR) ! Temporary
<                                                              ! data array
---
>     REAL*4,          INTENT(OUT)           :: Q(State_Grid%NX, & ! Temporary
>                                                 State_Grid%NY)   !  data array

```

## To Reproduce
**Generate rundir**
Within `.../UT/perl`, turn on the following in `CopyRunDirs.input` and run `./gcCopyRunDirs`
```
geosfp   2x25        -      complexSOA_SVPOA 2013010100   2014010100     -
```
Within the generated rundir, turned off the following within `HEMCO_Config.rc`

```
 125 # ----- OFFLINE EMISSIONS -------------------
 126     --> OFFLINE_DUST           :       false
 127     --> OFFLINE_BIOGENICVOC    :       false
 128     --> OFFLINE_SEASALT        :       false
 129     --> OFFLINE_SOILNOX        :       false

2464 #* FLASH_DENS $ROOT/OFFLINE_LIGHTNING/v2019-01/$MET/$YYYY/FLASH_CTH_$MET_0.25x0.3125_$YYYY_$MM.nc4  LDENS 1980-2019/1-12/1-31/0-23/+90minute RFY xy  1  * -  1 1
2465 #* CONV_DEPTH $ROOT/OFFLINE_LIGHTNING/v2019-01/$MET/$YYYY/FLASH_CTH_$MET_0.25x0.3125_$YYYY_$MM.nc4  CTH   1980-2019/1-12/1-31/0-23/+90minute RFY xy  1  * -  1 1

```
Within the generated rundir, turned off all but GC restart collection in `HISTORY.rc`
Within the generated rundir, turned off all HEMCO diagnostics in `HEMCO_Diagn.rc`

**Compilation commands**
```
make realclean; make -j4 mpbuild NC_DIAG=y BPCH_DIAG=n BPCH_TPBC=n BPCH_TIMESER=n
```

**Run commands**
```
./geos.mp
```

## Required information
Please include the following:
 - GEOS-Chem version you are using: 12.5.0
 - Compiler version that you are using: GNU Fortran (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
 - netCDF and netCDF-Fortran library version: netCDF 4.3.3.1, netCDF-Fortran 4.2
 - Computational environment: a common server
 - Are you using "out of the box" code, or have you made modifications?
  - No modifications.

## Input and log files to attach
For more info, see: http://wiki.geos-chem.org/Submitting_GEOS-Chem_support_requests
 - The lastbuild file 
[lastbuild.mp.txt](https://github.com/geoschem/geos-chem/files/3883771/lastbuild.mp.txt)

 - The input.geos file
[input.geos.txt](https://github.com/geoschem/geos-chem/files/3883772/input.geos.txt)

- The HEMCO_Config.rc file
[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/3883773/HEMCO_Config.rc.txt)

 - The HEMCO.log file
[HEMCO.log](https://github.com/geoschem/geos-chem/files/3883768/HEMCO.log)

 - Error output from your scheduler, if applicable [e.g. slurm*.out]
 - Any other error messages

## Additional context
I appended `txt` for several configuration filenames above to allow them be uploaded.

BTW, I found a lot of unit conversion warnings in `HEMCO.log`. Not sure if that is fine. It's using the default emission you provide.

**Comment by yantosca** [comment]
Thanks for writing.  I believe this error is happening because we do not have the data for FLASH_DENS and CONV_DEPTH for GEOS-FP 0.25 x 0.3125 for the year 2013.  In our data folder, the first year of data is 2014.

This is the line in the HEMCO_Config.rc file defining the FLASH_DENS input:
```
#==============================================================================
# --- Fields for lightning emissions (Extension 103) ---
#
# Native-resolution lightning flash rates constrained to LIS/OTD climatology
# and convective depth are now prescribed as offline meteorology.
#                                                    --Lee Murray (16 Jan 2019)
#==============================================================================
* FLASH_DENS $ROOT/OFFLINE_LIGHTNING/v2019-01/$MET/$YYYY/FLASH_CTH_$MET_0.25x0.3125_$YYYY_$MM.nc4  LDENS 1980-2019/1-12/1-31/0-23/+90minute RFY xy  1  * -  1 1
* CONV_DEPTH $ROOT/OFFLINE_LIGHTNING/v2019-01/$MET/$YYYY/FLASH_CTH_$MET_0.25x0.3125_$YYYY_$MM.nc4  CTH   1980-2019/1-12/1-31/0-23/+90minute RFY xy  1  * -  1 1
```

and on our HEMCO/OFFLINE_LIGHTNING/v2019-01/GEOSFP folder there are only these folders on disk:
```
2014/   2015/   2016/   2017/   2018/   README*
```

@ltmurray was the preparer of this data.  I am not sure if there are data for 2013 yet...he might know.

You could use MERRA2 for years prior to 2013.  There are many more years on disk:
```
1980/  1984/  1988/  1992/  1996/  2000/  2004/  2008/  2012/  2016/
1981/  1985/  1989/  1993/  1997/  2001/  2005/  2009/  2013/  2017/
1982/  1986/  1990/  1994/  1998/  2002/  2006/  2010/  2014/  2018/
1983/  1987/  1991/  1995/  1999/  2003/  2007/  2011/  2015/  README*
```

**Comment by FeiYao-Edinburgh** [comment]
> You could use MERRA2 for years prior to 2013.

Thanks for reminding. It helps solve the bug. But I still wonder why commenting the two lines will cause the model terminated? It means that these emissions are hard-coded in GC codes and hence must be read in?

**Comment by msulprizio** [comment]
The FLASH_DENS and CONV_DEPTH fields are read in by HEMCO and treated as meteorology fields. That is, they're obtained from HEMCO and stored in State_Met in hcoi_gc_main_mod.F90. Met fields are always required and will cause the model to crash when they cannot be found.

**Comment by FeiYao-Edinburgh** [comment]
> The FLASH_DENS and CONV_DEPTH fields are read in by HEMCO and treated as meteorology fields.

I think they are new features added recently because I did not seem them in previous `HEMCO_Config.rc` like GC 12.2.2?

Thanks for your clarification! I am almost there.

**Comment by msulprizio** [comment]
Correct. The FLASH_DENS and CONV_DEPTH fields were added to HEMCO_Config.rc in [GEOS-Chem 12.4.0](http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_12#12.4.0), with the implementation of the offline lightning NOx emissions.
