### ISSUE TITLE
[QUESTION] How to add new emission source to the total emission?

### ISSUE THREAD

**Issue by debatoshpartha** [geoschem/geos-chem#1532]
### Issue:

I am computing a new source of NOx emission from snow (i.e. NOx emission flux from snow & ice covered land) and developed a GEOS-Chem/GeosCore F90 code for calculating the Snow NOx flux in every time-step using our parameterization equation. The SNOWNOx emission flux results are given below from both sensitivity (that includes our newly developed code) and control (fresh directory w/o our code) simulations. 

Our parameterization equation (final unit: molecules/cm2/s), 

`SNOWNOx flux[I,J] = Deposition of NIT[I,J] * constants * fraction of snow&ice covered land[I,J]`

<img width="1440" alt="Screen Shot 2022-11-24 at 1 28 24 PM" src="https://user-images.githubusercontent.com/65563613/203847948-b0680c83-68da-4e57-85d3-9cc83159b1df.png">

Please note that our parameterization equation uses the deposition of NIT and the SNOWNOx flux from Sensitivity simulation is directly archived from our code itself and to compute (and compare) the SNOWNOx flux from Control simulation, we used the deposition flux of NIT from default HISTORY.rc collection of `DryDep` and `WetDepLoss`. 

As this 4-day averaged Snow NOx emission flux is significant and GEOS-Chem has not included the NOx emission flux from SNOW yet along with soil, fertilizer and lightning NOx, we need to add this new NOx emission flux from snow to the total NOx emission so that the model can pick up the new Snow NOx emission  and couple it with its chemistry mechanism so that we can assess the impact of this new NOx emission on tropospheric O3 formation. 

We have the SNOWNOx code ready for implementing into the new version of GEOS-Chem and want help from the GCST on how to add this emission to the total NOx emission.

**Comment by debatoshpartha** [comment]
Hi Mr. @yantosca, do you have any insights?

**Comment by msulprizio** [comment]
I'm also tagging @beckyalexander. Maria Zatko, a former member of her group, developed a snow NOx emissions algorithm several years back (see [Zatko et al., 2016](https://acp.copernicus.org/articles/16/13837/2016/)), but it was based on pre-HEMCO code. I'm not sure if Becky is aware of anyone that  has updated that code for use in HEMCO.

**Comment by yantosca** [comment]
@debatoshpartha: I've also restored some text that was inadvertently not ported from the older GEOS-Chem wiki documentation to ReadTheDocs.  Please see: https://hemco.readthedocs.io/en/latest/hco-ref-guide/extensions.html#adding-new-hemco-extensions.  Apologies for the omission.

**Comment by msulprizio** [comment]
I will close out this issue, but feel free to comment here or open a new issue if there are further questions.
