### ISSUE TITLE
GCClassic_RRTMG_Cannot find field with valid time stamp

### ISSUE THREAD

**Issue by yangbyy** [geoschem/geos-chem#1533]
### Ask a question about GEOS-Chem:
Hey, all!
When I changed the start date to 20161001 and ran the command "./gcclassic | tee GC.log", then I got this error.
HEMCO ERROR: Cannot find field with valid time stamp in /home/yang/GCClassic/ExtData/GEOS_4x5/MERRA2/2016/10/MERRA2.20161001.I3.4x5.nc4 - Cannot get field PS_NEXTDAY. Please check file name and time (incl. time range flag) in the config. file

I referenced #1450 & #1499, and updated the restart file date & time with the CDO utilities:
cdo setreftime,2016-10-01,00:00:00 GEOSChem.Restart.20190701_0000z.nc4 tmp.nc4
cdo setdate,2016-10-01 tmp.nc4 GEOSChem.Restart.20161001_0000z.nc4
![image](https://user-images.githubusercontent.com/115625689/204005717-fe96049a-cf8f-450e-a825-9b67d337c9ca.png)

Moreover, I also made some changes to the highlighted lines, turned the "EFYO" to "CYS". 
![image](https://user-images.githubusercontent.com/115625689/204004557-0b13a331-8eb8-4098-a122-029efc27b0d6.png)
There are some files which may help you understand my question.
[geoschem_config.txt](https://github.com/geoschem/geos-chem/files/10093606/geoschem_config.txt)
[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/10093608/HEMCO_Config.txt)
[HEMCO_Diagn.txt](https://github.com/geoschem/geos-chem/files/10093613/HEMCO_Diagn.txt)
[HEMCO_Config_rc.gmao_metfields.txt](https://github.com/geoschem/geos-chem/files/10093708/HEMCO_Config_rc.gmao_metfields.txt)
[HISTORY.txt](https://github.com/geoschem/geos-chem/files/10093614/HISTORY.txt)
[log.dryrun.txt](https://github.com/geoschem/geos-chem/files/10093628/log.dryrun.txt)
[GC.log](https://github.com/geoschem/geos-chem/files/10093642/GC.log)
 Thanks for your help!

**Comment by yangbyy** [comment]
Sorry，I made a stupid mistake. The reason for the error is that I didn't download all my data！Still thanks all!

**Comment by yantosca** [comment]
Thanks for letting us know @yangbyy.
