### ISSUE TITLE
[BUG/ISSUE]Abnormal wet deposition when using Luo et al scheme in 14.0.1

### ISSUE THREAD

**Issue by zhiweistu** [geoschem/geos-chem#1534]
### What institution are you from?
Peking University

### Description of the problem

Dear GEOSChem Developer:
My gc version is 14.0.1. I found that the diagnostic file “wetlossLS” in simulation with Luo et al wet deposition seems abnormal.
The sign is negative and there is an order of magnitude difference from my previous simulation results(v13.4.1, default wet deposition). How to resolve it ?

Thanks for your helps!

### Supplementary information

![image](https://user-images.githubusercontent.com/109276335/204142046-abacbcf6-7530-4624-9f96-f3008f58bd28.png)
(using default wet deposition in gc 13.4.1, the value is positive)

![image](https://user-images.githubusercontent.com/109276335/204142101-3bfef341-9b5a-4a83-baa0-ebc9d30d0912.png)
(using Luo et al wet deposition in gc 14.0.1, the value is negative, the magnitude is so larger)

### GC files using Luo et al wet deposition in version 14.0.1：
[log.gc.txt](https://github.com/geoschem/geos-chem/files/10098565/log.gc.txt)
[geoschem_config.txt](https://github.com/geoschem/geos-chem/files/10098567/geoschem_config.txt)
[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/10098568/HEMCO_Config.txt)

**Comment by yantosca** [comment]
Thanks for writing @zhiweistu.  This is more of a science question so I would refer you @ganluoasrc, who is the author of the wet scavenging scheme.  Also pinging the Transport Working Group chairs (whose WG is responsible for wet scavenging): @aschuh @ktravis213

**Comment by yantosca** [comment]
Also tagging @Jourdan-He and @SaptSinha for reference

**Comment by ganluoasrc** [comment]
@zhiweistu When I run GC14.0.1, wet deposition looks fine to me.
![dft-WetLossLS_SO4_in_org-GEOSChem WetLossLS 20160801_0000z](https://user-images.githubusercontent.com/42379787/204311924-e5eb21a1-bef0-4dc5-abeb-69c45bd294d5.png)
(LS wet deposition of SO4 for 201608 with default scheme)

![l2020-WetLossLS_SO4_in_l2020-GEOSChem WetLossLS 20160801_0000z](https://user-images.githubusercontent.com/42379787/204312111-5c0bf5b8-0a4d-49ef-91a2-5ef77685bd9f.png)
(LS wet deposition of SO4 for 201608 with Luo2020 scheme)

**Comment by ganluoasrc** [comment]
@zhiweistu When I run GC14.0.1, LS wet deposition looks fine to me. I did not find negative values.

<img width="587" alt="Default-GC14 0 1" src="https://user-images.githubusercontent.com/42379787/204345898-ddc5409b-0885-464e-a936-61e2f272deb4.PNG">
(LS wet deposition of SO4 simulated by GC14.0.1 with default scheme for 201608)

<img width="589" alt="L2020-GC14 0 1" src="https://user-images.githubusercontent.com/42379787/204346124-2bdded84-37ad-497c-b636-c21c229f4be0.PNG">
(LS wet deposition of SO4 simulated by GC14.0.1 with Luo2019 scheme for 201608)

**Comment by zhiweistu** [comment]
Thanks for reply @yantosca @ganluoasrc.
My simulation with default wet deposition scheme seems normal. So I guessed my abnormal result with Luo 2019 scheme may be induced by model settings. 
I will describe my operation in detail and these files provide detailed information about model settings when using Luo 2019 wet deposition scheme.

Operation:
I used GCAP2.0 simulation and used code 
cmake ../CodeDir -DLUO_WETDEP=y
to use Luo 2019 wet deposition scheme. Successfully compiled and there was no error when I run simulation with Luo 2019 wet deposition scheme.
But when I used panoply to check wetlossLS files, I found the values in all species are negative, so I realized it is abnormal.

Model settings files:
[geoschem_config.txt](https://github.com/geoschem/geos-chem/files/10109331/geoschem_config.txt)
[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/10109337/HEMCO_Config.txt)
[HEMCO_Diagn.txt](https://github.com/geoschem/geos-chem/files/10109340/HEMCO_Diagn.txt)
[HISTORY.txt](https://github.com/geoschem/geos-chem/files/10109342/HISTORY.txt)
[log.gc.txt](https://github.com/geoschem/geos-chem/files/10109345/log.gc.txt)

I am sorry that I could not find the issue to induced abnormal wet deposition
I would appreciate it if you could solve my problem！

**Comment by zhiweistu** [comment]
Thanks for reply @yantosca @ganluoasrc.

My simulation with default wet deposition scheme seems normal. So I guessed my abnormal result with Luo 2019 scheme may be induced by model settings. 
I will describe my operation in detail and these files provide detailed information about model settings when using Luo 2019 wet deposition scheme.

Operation:
I used GCAP2.0 simulation and used code 
cmake ../CodeDir -DLUO_WETDEP=y -DRUNDIR=..
to use Luo 2019 wet deposition scheme. Successfully compiled and there was no error when I run simulation with Luo 2019 wet deposition scheme.
But when I used panoply to check wetlossLS files, I found the values in all species are negative, so I realized it is abnormal.

Model settings files:
[geoschem_config.txt](https://github.com/geoschem/geos-chem/files/10109469/geoschem_config.txt)
[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/10109471/HEMCO_Config.txt)
[HEMCO_Diagn.txt](https://github.com/geoschem/geos-chem/files/10109472/HEMCO_Diagn.txt)
[HISTORY.txt](https://github.com/geoschem/geos-chem/files/10109473/HISTORY.txt)
[log.gc.txt](https://github.com/geoschem/geos-chem/files/10109474/log.gc.txt)

I am sorry that I could not find the reason to induced abnormal wet deposition
I would appreciate it if you could solve my problem

**Comment by ganluoasrc** [comment]
@yantosca is right. @zhiweistu , the abnormal performance of Luo et al scheme with the GCAP2 met fields is caused by unphysical performance of ground level rainfall in the GCAP2 met fields. If you check the GCAP2 met fields, you will find all rainfall values at ground level are 0. When you use Luo et al scheme, it assumes there is only evaporation rather wet deposition when ground level is no rain. The negative values represent evaporation.

**Comment by zhiweistu** [comment]
Thanks for the answer @yantosca  @ganluoasrc. I also tested the Luo wet deposition with merra2, and the results are normal. 

Besides, I wonder if we can fix the bug, and added some change to make luo wet deposition also suitable for GCAP2.0 meteorology. Because the Luo wet deposition is advanced scheme, I think it will make GCAP2.0 simulation more accurate.

**Comment by yantosca** [comment]
There is a new version of the Luo wetdep scheme (based on [Luo et al 2023](https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2023GL104258) that will likely go into GEOS-Chem soon.

**Comment by yantosca** [comment]
Closing out this issue
