### ISSUE TITLE
[FEATURE REQUEST] Reduce lines printed by default to log file

### ISSUE THREAD

**Issue by lizziel** [geoschem/geos-chem#1539]
The GEOS-Chem log file includes both GEOS-Chem and HEMCO prints starting in 14.0. This has made the already large file even larger. It would be good to go through what is printed and determine what is actually needed by default. Everything else can be removed, either by including in the `debug_printout` option in `geoschem_config.yml` or in a higher value of `VERBOSE` or `WARNINGS` in HEMCO. We could also simplify the print options in HEMCO (e.g. consolidate the hierarchical `VERBOSE` and `WARNINGS` into a single on/off switch) but I will make a separate feature request for that in HEMCO.

**Comment by yantosca** [comment]
See companion PR #1549 (currently in progress)

**Comment by yantosca** [comment]
Also see the corresponding PR in HEMCO: https://github.com/geoschem/HEMCO/pull/182

**Comment by msulprizio** [comment]
https://github.com/geoschem/geos-chem/pull/1549 has been merged into `dev/14.2.0` and https://github.com/geoschem/HEMCO/pull/182 has been merged into `dev/3.7.0. I will close out this feature request.
