### ISSUE TITLE
[BUG/ISSUE] Weird NetCDF output time and size in GC12.5.0

### ISSUE THREAD

**Issue by luxiao-atchem** [geoschem/geos-chem#154]
# Report a GEOS-Chem bug or technical issue
I am running methane simulation using GC12.5.0 on Harvard Cannon. I notice that the monthly NetCDF outputs are not written out right after the simulated month as expected, instead, they would be delayed for one month or so compared to simulating time. And there would be an error in the NetCDF file for the last second month of the running period (output.png). Similar features are also reported from Dr. Shaojie Song, who is running GC tropchem on Cannon.

Bash used here is ~/init/init.gc-classic.ifort15.centos7.

**Comment by luxiao-atchem** [comment]
Files are loaded below. Input.geos and HEMCO_Config.rc follow the default settings.

[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/3889563/HEMCO_Config.txt)
[HISTORY.txt](https://github.com/geoschem/geos-chem/files/3889564/HISTORY.txt)
[input.txt](https://github.com/geoschem/geos-chem/files/3889565/input.txt)
[lastbuild.mp.txt](https://github.com/geoschem/geos-chem/files/3889566/lastbuild.mp.txt)
![output](https://user-images.githubusercontent.com/56967618/69591896-37a73b00-0fc2-11ea-99da-0aca54f479a7.png)
[Prior_base.log](https://github.com/geoschem/geos-chem/files/3889567/Prior_base.log)

**Comment by msulprizio** [comment]
>I notice that the monthly NetCDF outputs are not written out right after the simulated month as expected, instead, they would be delayed for one month or so compared to simulating time.

Are you basing this off of the timestamps of the netCDF files in your directory? If so, it is possible that the previous months files are being "touched" by GEOS-Chem, whereas the data was already written to that file at the correct simulation time. You may want to try turning on debug printout (ND70 in input.geos) to see if that reveals any more information about when files are being accessed in your simulation. You can also add debug print statements to the areas in the code that write to the netCDF files to see if your suspicion is correct.

> And there would be an error in the NetCDF file for the last second month of the running period (output.png).

Could you please attach the reference file? I can't seem to find the error that you're referring to in the log file you provided.

**Comment by luxiao-atchem** [comment]
![print](https://user-images.githubusercontent.com/56967618/70367432-cbec8a00-186d-11ea-9eb9-430e9e9fae62.png)

Hi Melissa,

Thanks for writing, and sorry for my late follow-up. It turns out that finally, the monthly NC outputs have reasonable size. I have checked that the results from bpch and NC outputs are the same, so I am almost sure that there is not an output error.

It is just still kind of “weird” to me that 1) there appears to be an update of the NC file after it has been “fully” generated, as can be seen from the comparison of the edited time of “GEOSChem.CH4.20161101_0000z.nc4” in two figures, 2) the results of the last two months are output at the same time, which is not as expected. I wonder whether this also appears in your simulation in Harvard Cannon.

**Comment by yantosca** [comment]
Am wondering if it could have been issues on the /scratchlfs disk.   That disk was wonky lately but now seems to be functioning normally.  We can go ahead and close this out.
