### ISSUE TITLE
Daily restart files

### ISSUE THREAD

**Issue by angothelene** [geoschem/geos-chem#1541]
Hi, I'm doing a simulation ending on 201911**14** 000000.
At the end of the simulation I get the following two restart files:
HEMCO_restart.201911**14**0000.nc and GEOSChem.Restart.201911**01**_0000z.nc4.
Is it possible to get GEOSChem.Restart.201911**14**_0000z.nc4 instead?
Thanks much!

**Comment by yantosca** [comment]
Thanks for writing @angothelene.  It could be that the out-of-the-box settings for `Restart.frequency` and `Restart.duration` collection were reset from `00000100 0000001` to `00000014 000000`.  Or if you would like to get daily restarts, then these should be `00000001 0000000`.

You can also set the`DiagnFreq` setting to the same value as in the HISTORY.rc file (it accepts words like `Daily`, `Monthly`, `End`, or also intervals like `0000001 000000`. 

Note that PR #1515 (which will be released in GEOS-Chem 14.0.2, hopefully today) fixes an issue where the restart file was not flushed to disk immediately after writing.

**Comment by yantosca** [comment]
Also tagging @Jourdan-He and @SaptSinha

**Comment by angothelene** [comment]
Thanks Bob, interestingly the settings were set to "End" in both HISTORY.nc and HEMCO_Config.rc that's why I was suprised to get GEOSChem.Restart.20191101_0000z.nc4 instead of GEOSChem.Restart.20191114_0000z.nc4.

DiagnFreq:                   End

#==============================================================================
# %%%%% THE Restart COLLECTION %%%%%
#
# GEOS-Chem restart file fields
#
# Available for all simulations
#==============================================================================
  Restart.filename:           './GEOSChem.Restart.%y4%m2%d2_%h2%n2z.nc4',
  Restart.format:             'CFIO',
  Restart.frequency:          'End',
  Restart.duration:           'End',
  Restart.mode:               'instantaneous'

**Comment by yantosca** [comment]
@angothelene: Which version are you using?

**Comment by yantosca** [comment]
Ah OK.  If you can, try to add the modifications in #1515 to your code and see if that resolves it.  You can do a short run (1 or 2 days) to test.  There have also been other minor fixes to History diagnostics since 12.9.3.

**Comment by angothelene** [comment]
Not yet, I’ve been busy with other stuff. I’ll work on that early Jan and will report back!

**Comment by angothelene** [comment]
It actually works when changing Restart.duration to the same value as in Restart.frequency in HISTORY.rc. So to save a restart file every day the following works:

Restart.frequency:         00000001 000000
Restart.duration:            00000001 000000

**Comment by yantosca** [comment]
Thanks @angothelene for the feedback.  We can close this issue out then.
