### ISSUE TITLE
[BUG/ISSUE] Corrupted OFFLINE_DUST files (1987/01/07 and 1987/07/21)

### ISSUE THREAD

**Issue by Row-Bean** [geoschem/geos-chem#1544]
### What institution are you from?
Université de Montréal

### Description of the problem
Two of the OFFLINE_DUST emissions files at http://geoschemdata.wustl.edu have size zero, and contain no information. Specifically these two:
http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/1981/07/dust_emissions_05.19810716.nc
http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/1981/07/dust_emissions_05.19810721.nc

**Comment by yantosca** [comment]
@Jourdan-He and/or @SaptSinha, would you be able to look into this issue?

**Comment by Jourdan-He** [comment]
@Row-Bean , @YanshunLi-washu has helped to fix these corrupted files.

**Comment by Row-Bean** [comment]
Excellent, thank you very much!

**Comment by Row-Bean** [comment]
Hello,
The previous problem is now resolved. But I found another corrupt file:
http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/1982/06/dust_emissions_05.19820618.nc

**Comment by msulprizio** [comment]
> I found another corrupt file: 
http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/1982/06/dust_emissions_05.19820618.nc

@YanshunLi-washu Would you be able to also fix this file?

**Comment by YanshunLi-washu** [comment]
No problem! Fixed. @msulprizio @Row-Bean

**Comment by YanshunLi-washu** [comment]
Hi @Jourdan-He and @SaptSinha, due to the instability of the compute1 file system, there will sometimes be corrected files affecting our users. Would you mind submitting a ticket to RIS next time when we encounter this? They may have better solutions to recover the corrected files for us so that we don't have to reproduce them. Thanks!

**Comment by msulprizio** [comment]
Thanks @YanshunLi-washu. 

@Row-Bean I will close out this issue, but please let let us know if you encounter other problems here or by opening a new issue.

**Comment by Jourdan-He** [comment]
Hi @YanshunLi-washu , sure! I will contact RIS if this issue persists in future.

**Comment by Row-Bean** [comment]
Thanks again for fixing the last file! However, I found another one:
http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/1982/06/dust_emissions_05.19820815.nc

**Comment by Row-Bean** [comment]
I just noticed that there's an error in my link above, sorry. It should be:
http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/1982/08/dust_emissions_05.19820815.nc

I looked through the offline dust files up to the end of 1986 for other obviously corrupt (zero size) files, and I found a few more:
http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/1984/06/dust_emissions_05.19840611.nc
http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/1984/06/dust_emissions_05.19840613.nc
http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/1986/01/dust_emissions_05.19860119.nc

**Comment by Row-Bean** [comment]
I don't want to be a bother, but do you have an estimate of when the fixed files will be uploaded? If you need much more time, I can run with online dust emissions for this time period. But I would prefer to use the offline dust emissions to ensure consistency with the rest of the simulation period.

**Comment by SaptSinha** [comment]
Hello @Row-Bean, pardon me for the delay. It looks like this issue was closed earlier and I did not receive the previous notification. I am reopening this issue and assigning this to myself to better monitor. 

I have gone through the list of corrupted files you provided. It looks like I might have to reproduce the offline dust emissions for the entirety of those particular years. As this might take some time, I would recommend working with the offline dust emissions for the other time periods.

**Comment by Row-Bean** [comment]
Okay, thank you for the information.

**Comment by SaptSinha** [comment]
Hello @Row-Bean, thank you again for your patience. We have now resolved the earlier issues involving inconsistency with global dust strength values. The following files were identified to have been corrupted in the WashU storage cluster. I have now reprocessed and uploaded them to http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/. Please do not hesitate to reach out if you find any other corrupted files.


OFFLINE_DUST/v2021-08/0.5x0.625/1980/07/dust_emissions_05.19800712.nc
OFFLINE_DUST/v2021-08/0.5x0.625/1980/08/dust_emissions_05.19800804.nc

OFFLINE_DUST/v2021-08/0.5x0.625/1982/08/dust_emissions_05.19820815.nc

OFFLINE_DUST/v2021-08/0.5x0.625/1984/06/dust_emissions_05.19840611.nc
OFFLINE_DUST/v2021-08/0.5x0.625/1984/06/dust_emissions_05.19840613.nc

OFFLINE_DUST/v2021-08/0.5x0.625/1986/01/dust_emissions_05.19860119.nc

OFFLINE_DUST/v2021-08/0.5x0.625/1988/05/dust_emissions_05.19880530.nc

OFFLINE_DUST/v2021-08/0.5x0.625/1992/02/dust_emissions_05.19920223.nc

OFFLINE_DUST/v2021-08/0.5x0.625/1994/01/dust_emissions_05.19940128.nc
OFFLINE_DUST/v2021-08/0.5x0.625/1994/12/dust_emissions_05.19941204.nc

**Comment by Row-Bean** [comment]
Thank you very much! I will let you know if I find any other corrupted files.
