### ISSUE TITLE
[QUESTION]Out of memory error using sbatch script in SLURM scheduler

### ISSUE THREAD

**Issue by pku-tjh** [geoschem/geos-chem#1545]
### Ask a question about GEOS-Chem:
Dear GEOSChem experts:
I can successfully ./ gcclassic to execute the job. But When I used sbatch script to run my job, the system always report the error:
'''
srun: ROUTE: split_hostlist: hl=a3411n10 tree_width 0
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=3679495.0 cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
srun: error: a3411n10: task 30: Out Of Memory
srun: launch/slurm: _step_signal: Terminating StepId=3679495.0
slurmstepd: error: *** STEP 3679495.0 ON a3411n10 CANCELLED AT 2022-12-01T20:27:06 ***
'''

The node has 200GB memory, it is enough. so I think the there may be other reason to induce that error.
Thanks for your helps.

My simulation: fullchem, 20140701-20140801, MERRA2,2X2.5
GC version:14.0.1
![image](https://user-images.githubusercontent.com/117807730/205110653-73c8d608-5169-447b-89fd-2e8b4cec053b.png)
(run script)

error information:
[log.error_information.txt](https://github.com/geoschem/geos-chem/files/10134356/log.error_information.txt)

script:
[run.slurm-serial.txt](https://github.com/geoschem/geos-chem/files/10134357/run.slurm-serial.txt)

**Comment by yantosca** [comment]
Thanks for writing @pku-tjh.  Even though the node has 200GB of memory, there may be some memory taken up by the operating system.  Try using a lower amount of memory (say 100GB) and see if your run works.

**Comment by pku-tjh** [comment]
Thanks for your help, I have solved this issue!

**Comment by yantosca** [comment]
Thanks for letting us know @pku-tjh!

**Comment by QuantumLab-ZY** [comment]
> Thanks for your help, I have solved this issue!

Hi @pku-tjh,

I've encountered a similar issue. Could you please share how you resolved it?

Thank you!
