### ISSUE TITLE
[QUESTION] A small question for the description of Input_Opt%LDUST

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/geos-chem#155]
Hi there,

When I read the [Aerosol Menu](http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_input_files#Aerosol_Menu) part of `input.geos` wiki, I found the description for `Input_Opt%LDUST` is a little bit from others. While setting T means turning chemistry on for most species, setting T for `Input_Opt%LDUST` means **removal** for mineral dust aerosol species (DST1, DST2, DST3, DST4). I believe it means turning dry/wet deposition on for mineral dust rather than not using mineral dust species? I would be grateful if you help with confirmation.

Thanks in advance!

**Comment by yantosca** [comment]
Yes, that is true.  Setting LDUST = T means 

1. That you are going to use the bulk dust species DST1, DST2, DST3, DST4, and
2. That you are turning on dust "chemistry", which is actually removal.

**Comment by FeiYao-Edinburgh** [comment]
Thanks for letting know!
