### ISSUE TITLE
[QUESTION] HDF5 install fails on Spack

### ISSUE THREAD

**Issue by 509miankuang** [geoschem/geos-chem#1550]
### Ask a question about GEOS-Chem:
<img width="369" alt="question" src="https://user-images.githubusercontent.com/54264317/205845357-c8673775-e0d9-49e1-ada8-bfdeea95870a.png">
excuse me, I can not find the pic appending in the HDF5, can you help me ? Thanks a lot?

**Comment by yantosca** [comment]
Thanks for writing @509miankuang.  I would report this to the Spack Github issue tracker.

You might need to use an older version of Spack to get around this issue.
