### ISSUE TITLE
How to add a regional emission inventory to the GCClassic

### ISSUE THREAD

**Issue by yangbyy** [geoschem/geos-chem#1552]
### Ask a question about GEOS-Chem:
Hi, all!
I am new to GEOS-Chem and with the help of documentation, I successfully ran the GEOS-Chem Classic coupled with RRTMG model(using full chemistry run directory ). Then I'm wondering how to add a regional emission inventory to the GCClassic? 

- For example, if I want to add the MEIC emission inventory of China  to the GC model (the inventory data has been successfully obtained), what should I do? 
- What I mean is that I just need to add the MEIC data to the HEMCO folder and then add the MEIC switch to the Extension section of the HEMCO_Con file（besides I'm not quite sure where to put my data.）? 
- Perhaps the base emissions, scale factors, and masks sections also need to be modified accordingly. If so, what I want to know is are these modifications manually added according to my needs? And do other configuration files also need to be changed?

I'm sorry maybe my question is not described very clearly. I didn't find a suitable tutorial. Can you give me some guidance? 
 Extremely grateful!

**Comment by yantosca** [comment]
Thanks for writing @yangbyy.  We have documentation on how to do this at https://hemco.readthedocs.io.  Specifically, see this link: https://hemco.readthedocs.io/en/stable/hco-ref-guide/basic-examples.html#example-2-overlay-regional-emissions

**Comment by bxh2000** [comment]
Hello, now I have the same problem. Have you solved it yet？
