### ISSUE TITLE
[BUG/ISSUE] Nf_Def_Var_Deflate: can not compress variable : P0

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/geos-chem#1553]
### What institution are you from?
The University of Edinburgh

### Description of the problem
We're trying to run GEOS-Chem Classic v12.9.3 on a small cluster but have the following issues:
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Nf_Def_Var_Deflate: can not compress variable : P0

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### Description of troubleshooting performed
We tried to run with output compression turned off by following this [guide](https://githubhelp.com/geoschem/hemco/issues/41); however, we are still using GNU Make to compile, so we have yet to find the relevant files to edit.

### GEOS-Chem version
v12.9.3

### Description of modifications
We have made some modifications to output more diagnostics that's of our interest. But that's definitely not the root of evil because we have previously run smoothly on local servers. The issue simply appears as we are trying to run on a small cluster. We might also wonder whether it is due to that [the cluster uses Parallel I/O](https://github.com/ExeClim/Isca/issues/80) which is unlike a single server.

### Log files

[GC.log.txt](https://github.com/geoschem/geos-chem/files/10177603/GC.log.txt)
[geos.lsf.s.txt](https://github.com/geoschem/geos-chem/files/10177604/geos.lsf.s.txt)
[HEMCO.log.txt](https://github.com/geoschem/geos-chem/files/10177605/HEMCO.log.txt)
[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/10177606/HEMCO_Config.rc.txt)
[HEMCO_Diagn.rc.txt](https://github.com/geoschem/geos-chem/files/10177607/HEMCO_Diagn.rc.txt)
[HISTORY.rc.txt](https://github.com/geoschem/geos-chem/files/10177608/HISTORY.rc.txt)
[compile.log.txt](https://github.com/geoschem/geos-chem/files/10177609/compile.log.txt)

### Software versions
- GNU Make version
```
GNU Make 4.3
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
- Compilers (Intel or GNU, and version)
```
ifort (IFORT) 19.0.1.144 20181018
Copyright (C) 1985-2018 Intel Corporation.  All rights reserved.
```
- NetCDF version
```
netCDF 4.9.0 and netCDF-Fortran 4.6.0
```

**Comment by yantosca** [comment]
Thanks for writing @FeiYao-Edinburgh.  This issue was raised in #634.  Please see the discussion in #634 for a fix.

**Comment by FeiYao-Edinburgh** [comment]
Thanks @yantosca That's the issue resolved!

**Comment by yantosca** [comment]
Thanks @FeiYao-Edinburgh.  We ran across that because certain newer versions of netCDF do not let you compress a variable unless it is at least 1-D.  So the solution is to just not compress the P0 variable (which is a scalar).
