### ISSUE TITLE
[QUESTION] Spack build error

### ISSUE THREAD

**Issue by 509miankuang** [geoschem/geos-chem#1556]
### Ask a question about GEOS-Chem:
excuse me, when I run this command, I had the following problem, as the picture shows. I can not  understand what it means. Could you help me? Thank you very much.
![question2-1](https://user-images.githubusercontent.com/54264317/206440918-aa785bf4-b1f5-49c5-9be1-2a43d2f4c3ea.png)
![question2-2](https://user-images.githubusercontent.com/54264317/206440940-6022e9f5-b454-4468-bd0c-11c64ce58cdf.png)

**Comment by yantosca** [comment]
Thanks for writing @509miankuang.  I would report this to the Spack Github issue tracker: https://github.com/spack/spack/issues/
