### ISSUE TITLE
[QUESTION] How can I process the MERRA2 raw files for GEOSChem

### ISSUE THREAD

**Issue by hgrhgy** [geoschem/geos-chem#1557]
I found the archived repo `https://github.com/geoschem/MERRA2`, which seems to process the raw MERRA2 files.
Is there any intructions about how to use the tools?
I want to generated the latest met files (0.5x0.625 with 47 levels ) for geoschem.  
Thank you.

**Comment by msulprizio** [comment]
Hi @hgrhgy. The archive linked above has been archived. Newer tools are available from the WashU group: https://github.com/Atmospheric-Composition-Analysis-Group. @Jourdan-He or @SaptSinha can provide further assistance if needed.

**Comment by hgrhgy** [comment]
@msulprizio Thank you for replying.  
HI @Jourdan-He @SaptSinha , I downloaded the code from: https://github.com/Atmospheric-Composition-Analysis-Group/metfield-processing
I tried to configure paths and run doMerra2 scripts.  An error occured: `Can‘t open Merra2_Driver.input file`.
The input file is not included in the repo.  How can I get or create this file？

**Comment by msulprizio** [comment]
It looks like that file should be on the Compute1 cluster at WashU. From file `regrid-MERRA2.bsub` it references the processdir path:

```
processdir=/storage1/fs1/rvmartin/Active/GEOS-Chem-shared/MetFieldProcessing/MERRA2

...

sed -i "95s#.*#$tempdir#" $processdir/bin/Merra2_Driver.input
```

@SaptSinha @YanshunLi-washu @LiamBindle Do you have that file handy to push to the `metfield-processing` repo? Also, do you have any instructions for utilizing the met field scripts in the ACAG Github? Community members occasionally need to process met fields on their own to include additional fields or for flight campaigns and documentation would be very useful in those cases.

**Comment by hgrhgy** [comment]
@msulprizio  thanks for replying.  I have copy the  configure file  from archived repo and modified according the errors when running.  And finally it works . The GEOS-Chem can read these file and seems to work well.  
But the size of  the output file I processed is larger than the file I downloaded from the WashU sites. I guess maybe the compress Level or the datatype are different.  The variables of them are excatly the same. Is there any changelog for the merra processing program? I believe it helps. @msulprizio @SaptSinha 

```
895M Dec 12 08:13 MERRA2.20220801.A1.05x0625.nc4
2.7G Dec 12 08:15 MERRA2.20220801.A3cld.05x0625.nc4
2.3G Dec 12 08:18 MERRA2.20220801.A3dyn.05x0625.nc4
1.8G Dec 12 08:19 MERRA2.20220801.A3mstC.05x0625.nc4
2.3G Dec 12 08:21 MERRA2.20220801.A3mstE.05x0625.nc4
1.4G Dec 12 08:23 MERRA2.20220801.I3.05x0625.nc4
```

**Comment by msulprizio** [comment]
The met fields at WashU are compressed and chunked. If you do `ncdump -h -s` on any of those files, they should include for example:

```
                lev:_Storage = "chunked" ;
                lev:_ChunkSizes = 72 ;
                lev:_DeflateLevel = 5 
```

NetCDF files can be compressed and chunked using the `nccopy` command. In the metfield-processing repository this is done in [`MERRS2/regrid.sh`](
https://github.com/Atmospheric-Composition-Analysis-Group/metfield-processing/blob/e480876a33926cae97116073c3606769e3d46ca8/MERRA2/regrid.sh#L112-L135).

**Comment by hgrhgy** [comment]
All my problems have been solved! Thanks a lot!
