### ISSUE TITLE
[QUESTION]How to choose the code version when download gcclassic and geochem?

### ISSUE THREAD

**Issue by pku-tjh** [geoschem/geos-chem#1559]
### Ask a question about GEOS-Chem:
Hi, everyone. I want to ask how to use git clone to get the older version GCClassic and GEOSChem? I want to get GCClassic 13.1.0 and GEOSChem 12.9.0. 
But I used git clone --recurse-submodules https://github.com/geoschem/GCClassic.git, I will get the newest GCClassic.
Thanks for helps!

**Comment by lizziel** [comment]
Hi @pku-tjh. After cloning GC-Classic you can checkout 13.1.0 using the following commands:
```
git checkout tags/13.1.0
git submodule update --init --recursive
```

Version 12.9.0 pre-dates the move to the GC-Classic wrapper repository. To get GEOS-Chem 12.9.0 you should clone only the geos-chem repository and then checkout the 12.9.0 tag.
```
git clone https://github.com/geoschem/geos-chem.git code.gcc_12.9.0
cd code.gcc_12.9.0
git checkout tags/12.9.0
```

**Comment by pku-tjh** [comment]
Thanks for your detailed reply, I am so grateful!
