### ISSUE TITLE
[QUESTION] What's the role of validate.pl that resides in rundir

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/geos-chem#156]
Hi there,

I have noticed that there will always be a file called `validate.pl` that resides in rundir created from unit tester. I have not found any description for this file on [this](http://wiki.seas.harvard.edu/geos-chem/index.php/Creating_GEOS-Chem_run_directories) wiki. I realise that it is a perl script and hence open it within a text editor and found the following.
```
 10 # !DESCRIPTION: This perl script validates GEOS-Chem output files f rom
 11 #  either unit tests or difference tests.  It compares the md5sums of
 12 #  2 corresponding files (*.sp vs. *.mp, or *.Ref vs. *.Dev) and then
 13 #  creates user-friendly output.
```
But honestly, I hardly understand these descriptions. What GC output files does it validate? I guess it won't be GC diagnostic files...

Thanks in advance!

**Comment by yantosca** [comment]
This is for the unit tests and difference tests.  It isn't really meant for anything else.
