### ISSUE TITLE
[BUG/ISSUE]GEOS-Chem ERROR: Error encountered in "DO_TEND"!

### ISSUE THREAD

**Issue by bxh2000** [geoschem/geos-chem#1560]
Hello I first did a fullchem simulation using GEOS-Chem 14.0.1 and it runs correctly with the following configuration

pbl_mixing:
   activate: false
   use_non_local_pbl: true
However, when I performed aerosol simulation, the setting could not be performed and the following error will appear.

GEOS-Chem ERROR: Error encountered in "DO_TEND"!
-> at DO_MIXING (in module GeosCore/mixing_mod.F90)

GEOS-CHEM ERROR: Error encountered in "Do_Mixing"!
STOP at -> at GEOS-Chem (in GeosCore/main.F90)
I tried to find a solution, but without success. I want to know why this problem occurs and how to solve it.

Also, when I try to set to true, it simulates fine.

pbl_mixing:
  activate: true
  use_non_local_pbl: true
Thank you

**Comment by yantosca** [comment]
This is a duplicate of #1555

**Comment by bxh2000** [comment]
The following is my configuration file and I am looking forward to your answers
geoschem_config.yml

---
### geoschem_config.yml: GEOS-Chem Runtime configuration options.
### Customized for simulations using the KPP "fullchem" mechanism.
###
### NOTE: Add quotes around nitrogen oxide ('NO'), because YAML
### parsers will confuse this with a negative "no" value.

#============================================================================
# Simulation settings
#============================================================================
simulation:
  name: fullchem
  start_date: [20190101, 000000]
  end_date: [20190201, 000000]
  root_data_dir: /data/gcdata/ExtData
  met_field: MERRA2
  species_database_file: ./species_database.yml
  debug_printout: false
  use_gcclassic_timers: false

#============================================================================
# Grid settings
#============================================================================
grid:
  resolution: 0.5x0.625
  number_of_levels: 47
  longitude:
    range: [ 60.0, 150.0]
    center_at_180: true 
  latitude:
    range: [-11.0,  55.0]
    half_size_polar_boxes: true 
  nested_grid_simulation:
    activate: true 
    buffer_zone_NSEW: [3, 3, 3, 3]

#============================================================================
# Timesteps settings
#============================================================================
timesteps:
  transport_timestep_in_s: 300
  chemistry_timestep_in_s: 600
  radiation_timestep_in_s: 10800

#============================================================================
# Settings for GEOS-Chem operations
#============================================================================
operations:

  chemistry:
    activate: true
    linear_chemistry_aloft:
      activate: true
      use_linoz_for_O3: true
    active_strat_H2O:
      activate: true
      use_static_bnd_cond: true
    gamma_HO2: 0.2

  convection:
    activate: true

  dry_deposition:
    activate: true
    CO2_effect:
      activate: false
      CO2_level: 600.0
      reference_CO2_level: 380.0
    diag_alt_above_sfc_in_m: 10

  pbl_mixing:
     activate: false
     use_non_local_pbl: true 

  photolysis:
    input_dir: /data/gcdata/ExtData/CHEM_INPUTS/FAST_JX/v2021-10/
    overhead_O3:
      use_online_O3_from_model: true 
      use_column_O3_from_met: true
      use_TOMS_SBUV_O3: false
    photolyze_nitrate_aerosol:
      activate: false
      NITs_Jscale_JHNO3: 0.0
      NIT_Jscale_JHNO2: 0.0
      percent_channel_A_HONO: 66.667
      percent_channel_B_NO2: 33.333

  rrtmg_rad_transfer_model:
    activate: false
    aod_wavelengths_in_nm:
      - 550
    longwave_fluxes: false
    shortwave_fluxes: false
    clear_sky_flux: false
    all_sky_flux: false

HEMCO_Confg.rc
#------------------------------------------------------------------------------
#                  Harmonized Emissions Component (HEMCO)                     !
#------------------------------------------------------------------------------
#BOP
#
# !MODULE: HEMCO_Config.rc
#
# !DESCRIPTION: Contains configuration information for HEMCO. Define the
#  emissions inventories and corresponding file paths here. Entire
#  configuration files can be inserted into this configuration file with
#  an '>>>include' statement, e.g. '>>>include HEMCO\_Config\_test.rc'
#  The settings of include-files will be ignored.
#\\
#\\
# !REMARKS:
#  See The HEMCO User's Guide for file details:
#    http://wiki.geos-chem.org/The_HEMCO_User%27s_Guide
#
# !REVISION HISTORY:
#  See https://github.com/geoschem/geos-chem for complete history
#EOP
#------------------------------------------------------------------------------
#BOC
###############################################################################
### BEGIN SECTION SETTINGS
###############################################################################

ROOT:                        /data/gcdata/ExtData/HEMCO
METDIR:                      /data/gcdata/ExtData/GEOS_0.5x0.625/MERRA2
GCAPSCENARIO:                not_used
GCAPVERTRES:                 47
Logfile:                     *
DiagnFile:                   HEMCO_Diagn.rc
DiagnPrefix:                 ./OutputDir/HEMCO_diagnostics
DiagnFreq:                   Monthly
Wildcard:                    *
Separator:                   /
Unit tolerance:              1
Negative values:             0
Only unitless scale factors: false
Verbose:                     0
Warnings:                    1

### END SECTION SETTINGS ###

###############################################################################
### BEGIN SECTION EXTENSION SWITCHES
###############################################################################
# ExtNr ExtName                on/off  Species  Years avail.
0       Base                   : on    *
# ----- MAIN SWITCHES ---------------------------------------------------------
    --> EMISSIONS              :       true
    --> METEOROLOGY            :       true     # 1980-2021
    --> CHEMISTRY_INPUT        :       true
# ----- RESTART FIELDS --------------------------------------------------------
    --> GC_RESTART             :       true
    --> HEMCO_RESTART          :       true
# ----- NESTED GRID FIELDS ----------------------------------------------------
    --> GC_BCs                 :       true 
# ----- REGIONAL INVENTORIES --------------------------------------------------
    --> APEI                   :       false    # 1989-2014
    --> NEI2016_MONMEAN        :       false    # 2002-2020
    --> DICE_Africa            :       false    # 2013
# ----- GLOBAL INVENTORIES ----------------------------------------------------
    --> CEDSv2                 :       true     # 1750-2019
    --> CEDS_GBDMAPS           :       false    # 1970-2017
    --> CEDS_GBDMAPS_byFuelType:       false    # 1970-2017
    --> EDGARv43               :       false    # 1970-2010
    --> HTAP                   :       false    # 2008-2010
    --> GEIA_NH3               :       true     # 1990
    --> SEABIRD_NH3            :       true     # 1990
    --> POET_EOH               :       false    # 1985
    --> TZOMPASOSA_C2H6        :       true     # 2010
    --> XIAO_C3H8              :       true     # 1985
    --> LIANG_BROMOCARB        :       true     # 2000
    --> ORDONEZ_IODOCARB       :       true     # 2000
    --> DECAYING_PLANTS        :       true     # 1985
    --> AFCID                  :       true     # 2015
# ----- AIRCRAFT EMISSIONS ----------------------------------------------------
# There are 3 switches:
#
#  1. AEIC2019_DAILY selects daily AEIC 2019 emissions.  For most simulations,
#     this is not recommended due to the amount of computational overhead
#     that will be incurred in regridding.  But this may be useful for
#     research purposes.  Recommended setting: "AEIC2019_DAILY: false".
#
#  2. AEIC2019_MONMEAN selects monthly-mean AEIC 2019 emisisons, which will
#     incur much less computational overhaead.  This options should suffice
#     for most simulations.  Recommended setting "AEIC2019_MONMEAN: true".
#
#  3. AEIC_SCALE_1990_2019: If "false", the AEIC 2019 data from the year
#     2019 alone will be used.  This will yield a "best estimate" of
#     aviation emisssion. This could be important because simply scaling
#     aviation emissions up and down is rather nonphysical.  But if
#     AEIC_SCALE_1990_2019 is set to true, then aviation emissions for
#     1990 to 2019 are estimated by:
#
#     a. Scaling ALL aviation emissions based on the growth in fuelburn
#        from 1990 to 2019* estimated by Lee et al. (2021); and
#
#     b. Scaling aviation NOx emissions by an additional factor to reflect
#        the changes in the NOx emissions index over the same period as
#        reported by Lee et al. (2021).
#
#     Recommended setting: "AEIC_SCALE_1990_2019: true"
#
# See additional notes in the AEIC scale factor section below.
#------------------------------------------------------------------------------
    --> AEIC2019_DAILY         :       false    # 2019 (daily data)
    --> AEIC2019_MONMEAN       :       true      # 2019 (monthly-mean data)
    --> AEIC_SCALE_1990_2019   :       true      # Scale to year in 1990-2019
# ----- SHIP EMISSIONS --------------------------------------------------------
    --> SHIP                   :       true
    --> CEDSv2_SHIP            :       true     # 1750-2017
    --> CEDS_GBDMAPS_SHIP      :       false    # 1970-2017
    --> CEDS_GBDMAPS_SHIP_byFuelType:  false    # 1970-2017
    --> HTAP_SHIP              :       false    # 2008-2010
    --> ICOADS_SHIP            :       false    # 2002
    --> ARCTAS_SHIP            :       false    # 2008
    --> CORBETT_SHIP           :       false    # 1985
# ----- RCP FUTURE EMISSIONS --------------------------------------------------
    --> RCP_3PD                :       false    # 2005-2100
    --> RCP_45                 :       false    # 2005-2100
    --> RCP_60                 :       false    # 2005-2100
    --> RCP_85                 :       false    # 2005-2100
# ----- CMIP6 ANTHRO EMISSIONS / BOUNDARY CONDITIONS --------------------------
#   Set GCAPSCENARIO (e.g., HIST, SSP585) above in SECTION SETTINGS
    --> CMIP6_SFC_BC           :       false    # 1750-2100
    --> CMIP6_SFC_LAND_ANTHRO  :       false    # 1850-2100
    --> CMIP6_AIRCRAFT         :       false    # 1850-2100
    --> CMIP6_SHIP             :       false    # 1850-2100
# ----- BIOMASS BURNING EMISSIONS ---------------------------------------------
    --> QFED2                  :       ture    # 2000-2020
    --> GFAS                   :       false    # 2003-2021
    --> BB4MIPS                :       false    # 1850-2100
# ----- OFFLINE EMISSIONS -----------------------------------------------------
# To use online emissions instead set the offline emissions to 'false' and the
# corresponding HEMCO extension to 'on':
#   OFFLINE_DUST        - DustDead or DustGinoux
#   OFFLINE_BIOGENICVOC - MEGAN
#   OFFLINE_SEASALT     - SeaSalt
#   OFFLINE_SOILNOX     - SoilNOx
#
# NOTE: When switching between offline and online emissions, make sure to also
# update ExtNr and Cat in HEMCO_Diagn.rc to properly save out emissions for
# any affected species.
#------------------------------------------------------------------------------
    --> OFFLINE_DUST           :       false     # 1980-2019
    --> OFFLINE_BIOGENICVOC    :       false     # 1980-2020
    --> OFFLINE_SEASALT        :       false     # 1980-2019
    -->  CalcBrSeasalt         :       false
    --> OFFLINE_SOILNOX        :       false     # 1980-2020
# ----- NON-EMISSIONS DATA ----------------------------------------------------
    --> UVALBEDO               :       true     # 1985
    --> CCM_STRAT_Bry          :       true     # 2007
    --> GMI_OH                 :       true     # 2005
    --> GMI_PROD_LOSS          :       true     # 2005
    --> OMOC_RATIO             :       false    # 2010
    --> GMD_SFC_CH4            :       true     # 1979-2020
    --> CMIP6_SFC_CH4          :       false    # 1750-1978
    --> OLSON_LANDMAP          :       true     # 1985
    --> YUAN_MODIS_LAI         :       true     # 2000-2020
    --> RRTMG                  :       false    # 2002
    --> SfcVMR                 :       true     # 1750-2014
    --> OCEAN_O3_DRYDEP        :       true     # 1985
# -----------------------------------------------------------------------------

HISTORY.rc
###############################################################################
###  HISTORY.rc file for GEOS-Chem full chemistry simulations               ###
###  Contact: GEOS-Chem Support Team (geos-chem-supportg.harvard.edu)      ###
###############################################################################

#============================================================================
# EXPID allows you to specify the beginning of the file path corresponding
# to each diagnostic collection.  For example:
#
#   EXPID: ./GEOSChem
#      Will create netCDF files whose names begin "GEOSChem",
#      in this run directory.
#
#   EXPID: ./OutputDir/GEOSChem
#      Will create netCDF files whose names begin with "GEOSChem"
#      in the OutputDir sub-folder of this run directory.
#
#============================================================================
EXPID:  ./OutputDir/GEOSChem

#==============================================================================
# %%%%% COLLECTION NAME DECLARATIONS %%%%%
#
# To enable a collection, remove the "#" character in front of its name. The
# Restart collection should always be turned on.
#
# NOTE: These are the "default" collections for GEOS-Chem, but you can create
# your own customized diagnostic collections as well.
#==============================================================================
COLLECTIONS: 'Restart',
             #'Metrics',
             #'SpeciesConc',
             #'AdvFluxVert',
             'AerosolMass',
             'Aerosols',
             ##'Budget',
             ##'CloudConvFlux',
             ##'ConcAboveSfc',
             ##'ConcAfterChem',
             ##'DryDep',
             #'JValues',
             ##'KppDiags',
             ##'LevelEdgeDiags',
             ##'ProdLoss',
             ##'RRTMG',
             ##'RxnRates',
             ##'StateChm',
             'StateMet',
             ##'StratBM',
             ##'WetLossConv',
             ##'WetLossLS',
             ##'BoundaryConditions',
::

**Comment by yantosca** [comment]
@bxh2000: I think you may need to turn on dry deposition and pbl mixing in order to avoid this issue.
