### ISSUE TITLE
GCClassic_full chemistry coupled with RRTMG

### ISSUE THREAD

**Issue by yangbyy** [geoschem/geos-chem#1561]
### Ask a question about GEOS-Chem:
Hi, all!
I want to use the RRTMG mode to simulate the brown carbon radiation effect, I have added brown carbon CASE in the RRTMG_rad_transfer_mod. F90 file, I now want to know how I should change the array length in the CMN_FJX_MOD. F90 file?
Is it to modify the variables in the following picture? But I don't quite understand what they mean. What should I revise it according to?
![image](https://user-images.githubusercontent.com/115625689/206851762-5217cbe0-3560-41b6-b3b2-56be11143533.png)
Hoping to  get your guidance, extremely THANKS!

**Comment by lizziel** [comment]
Hi @yangbyy, could you include your edited file along with clear comments in the file on what parts you added? Thanks!
