### ISSUE TITLE
[QUESTION]Missing file in ExtData/CHEM_INPUTS/UCX_201403/NoonTime/Grid4x5

### ISSUE THREAD

**Issue by pku-tjh** [geoschem/geos-chem#1562]
### Ask a question about GEOS-Chem:
Hi, my gc version is 13.0.0. I used dryrun, and it reminded me 

UCX (SFCMR_READ): REQUIRED FILE NOT FOUND/data1/ExtData/CHEM_INPUTS/UCX_201403/NoonTime/Grid4x5/InitCFC_
![image](https://user-images.githubusercontent.com/117807730/206913040-56f0c244-c57b-4a3e-8e24-cfb90dd7b081.png)

But I did not find the InitCFC_file in http://geoschemdata.wustl.edu/ExtData/CHEM_INPUTS/UCX_201403/NoonTime/Grid4x5/
I think it is an error, how to solve it?
Thanks for your helps!

[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/10202560/HEMCO_Config.txt)
[log.dryrun.txt](https://github.com/geoschem/geos-chem/files/10202563/log.dryrun.txt)

**Comment by pku-tjh** [comment]
I solved the question, thanks!

**Comment by Liushcsj** [comment]
Hello,I also encountered this issue and my gc is 13.0.0 too. I would like to ask you how to solve it.

**Comment by Liushcsj** [comment]
Hello, I also encountered this issue and my gc is 13.0.0 too. I would like to ask you how to solve it.
Many thanks to you.

**Comment by yonghumu** [comment]
> 我解决了问题，谢谢！

How was it solved, thank you
