### ISSUE TITLE
[QUESTION]How to convert the output 72 levels data to the altitude data like kilometer ?

### ISSUE THREAD

**Issue by Aydr199406** [geoschem/geos-chem#1564]
### Ask a question about GEOS-Chem:
Hello everyone, i have a question about the output data. I get the output results which have the 72 levels. However, i do not know the altitudes corresponding to the 72 levels. How to convert the levels to the altitude?

**Comment by yantosca** [comment]
Thanks for writing @Aydr199406.  We do have some approximate vertical altitudes corresponding to the 72-layer and 47-layer grids at the [GEOS-Chem vertical grids page on the GEOS-Chem wiki](https://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_vertical_grids#72-layer_vertical_grid).

If you know the pressure, you can also use the [hydrostatic equation](https://www.aoml.noaa.gov/ftp/hrd/annane/prelim_notes/hypsometric_equation.pdf) to convert pressure to altitude.  For GEOS-Chem we use a scale factor of 7600.

If you've saved out the `State_Met` diagnostic collection, the `Met_BXHEIGHT` field is the height of each grid box in meters above the surface.  You can sum the values of `Met_BXHEIGHT` to find the height of the column (surface to top of grid box) in meters.  (For the topmost grid box you can use 1/2 the height to get to the height of the vertical center of the grid box above the surface).

**Comment by yantosca** [comment]
Also note: the GMAO 72-layer grid has terrain-following levels near the surface and fixed-pressure levels in the stratosphere.  I believe above level 36 or so all of the levels have the same pressure regardless of horizontal location.

**Comment by Aydr199406** [comment]
Thanks for your professional and detailed answer @yantosca . My problems is solved. I'll close out this issue.
