### ISSUE TITLE
[BUG/ISSUE]  NetCDF: Index exceeds dimension bound

### ISSUE THREAD

**Issue by TylerElgiar** [geoschem/geos-chem#1566]
### What institution are you from?
Please tell us what institution you are from.
Utah State University
### Description of the problem
Describe your problem here.  Describe the steps to reproduce the problem here, if possible.
I have been trying to run a 025x03125 resolution model. I have ran an almost identical model in the past, only this run is for a different time period, and I receive the following error:
```console
In Ncrd_3d_R4 #2:  NetCDF: Index exceeds dimension bound
     65536       133

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Code stopped from DO_ERR_OUT (in module NcdfUtil/m_do_err_out.F90) 

This is an error that was encountered in one of the netCDF I/O modules,
which indicates an error in writing to or reading from a netCDF file!
```
I have not encountered this error in my previous runs, and I'm not quite sure how to address it.

### Description of troubleshooting performed
Describe any troubleshooting that you have already performed here. Also include any leads or suspicions here.

### GEOS-Chem version
Enter your GEOS-Chem version here.
12.8.0
### Description of modifications
Describe your modifications here.

### Log files
- Build log (if applicable):
- Run logs (if applicable):
- Run script (if applicable):

### Software versions
- CMake version:
- Compilers (Intel or GNU, and version):
- NetCDF version:

**Comment by yantosca** [comment]
Thanks for writing @TylerElgiar.  This can indicate that one of the netCDF files that you have on disk is corrupted.  From the log file output, can you determine which file is being read?

Usually the solution is to re-download the file from the WashU archive and try again.

**Comment by yantosca** [comment]
Also tagging @Jourdan-He and @SaptSinha for reference.

**Comment by TylerElgiar** [comment]
I deleted my restart file and copied form another run. The model appears to be running now. Thank you for your help! I will let you know if there are any further issues.

-Tyler
     On Wednesday, December 14, 2022, 11:29:35 AM MST, Bob Yantosca ***@***.***> wrote:  
 
 


Thanks for writing @TylerElgiar. This can indicate that one of the netCDF files that you have on disk is corrupted. From the log file output, can you determine which file is being read?

Usually the solution is to re-download the file from the WashU archive and try again.

**Comment by yantosca** [comment]
No problem @TylerElgia!  Write us with any problems or issues you encounter.  Glad it's all working.
