### ISSUE TITLE
[QUESTION]Compiler warning in 13.1.0

### ISSUE THREAD

**Issue by pku-tjh** [geoschem/geos-chem#1573]
### Ask a question about GEOS-Chem:
Hi, everyone. My gc version is 13.1.0. When I compiled, it reported warning:
Scanning dependencies of target HCO
src/HEMCO/src/Core/CMakeFiles/HCO.dir/depend.make:358: warning: overriding recipe for target 'src/HEMCO/src/Core/CMakeFiles/HCO.dir/hcoio_read_mod.mod.stamp'
src/HEMCO/src/Core/CMakeFiles/HCO.dir/depend.make:334: warning: ignoring old recipe for target 'src/HEMCO/src/Core/CMakeFiles/HCO.dir/hcoio_read_mod.mod.stamp'
src/HEMCO/src/Core/CMakeFiles/HCO.dir/depend.make:411: warning: overriding recipe for target 'src/HEMCO/src/Core/CMakeFiles/HCO.dir/hcoio_write_mod.mod.stamp'
src/HEMCO/src/Core/CMakeFiles/HCO.dir/depend.make:390: warning: ignoring old recipe for target 'src/HEMCO/src/Core/CMakeFiles/HCO.dir/hcoio_write_mod.mod.stamp'

![image](https://user-images.githubusercontent.com/117807730/209364799-4bb9269b-6b04-4a8e-af0c-e4c33dc751fe.png)
![image](https://user-images.githubusercontent.com/117807730/209364823-cc19779e-3917-4a6d-9f89-b89b15019fd8.png)

cmake version: 3.20.1
netcdf4 : 4.8.0
netcdf4-fortran:4.5.3

How to resolve it? 
Thanks for your helps!

**Comment by yantosca** [comment]
Thanks for writing @pku-tjh.  Have you tried typing
```console
$ cd build
$ make distclean
```
That should remove everything in the build folder.  Then you can do a clean build.  If the problem persists then create a new build folder in your run directory and use that to configure and build.

**Comment by yantosca** [comment]
Closing out this issue due to inactivity.  Feel free to open a new issue if you are still having problems.
