### ISSUE TITLE
[QUESTION] GCAP2.0 input data download

### ISSUE THREAD

**Issue by jiaying002** [geoschem/geos-chem#1574]
Dear GEOS-Chem support team, 

My project plan is to use GCAP2.0 in future scenarios. I tried to use the dry-run simulation to download the required data. The auto-generated download script contained some data that I could not found some of the data from any of these databases (wustl, rochester and harvard, I cannot have access to computecanada). 

I concluded the data I could not find into  parts:
1) _**YYYY0229.aijh2E213SSP119aF40oQ40.nc4**_ file missing (YYYY is a leap year)
2) _**ExtData/HEMCO/GCAP2/Bry/v2015-01/---2VERTRESL/GEOSCCM_Bry.2007xx.xxxxx.nc**_ file missing
3) **_ExtData/HEMCO/GCAP2/GMI/v2015-02/---2VERTRESL/gmi.clim.XXXX.geos5.2x25.nc_** file missing
4) _**ExtData/HEMCO/SAMPLE_BCs/v2021-09/fullchem/GEOSChem.BoundaryConditions.20xxxxxx_0000z.nc4**_ file missing (from 20400101 to 20991231)
Where can I find those data? 

I really need the answer before Christmas since the project is an emergency. I would suuuuuuper appreciate you if you could help me with this! 
[auto_generated_download_script.sh.txt](https://github.com/geoschem/geos-chem/files/10296688/auto_generated_download_script.sh.txt)

**Comment by jiaying002** [comment]
I already figured out question 2&3, which are located here:
http://atmos.earth.rochester.edu/input/gc/ExtData/HEMCO/GCAP2/Bry/40L/
http://atmos.earth.rochester.edu/input/gc/ExtData/HEMCO/GCAP2/GMI/40L/

I still need help with question 1&4. Thank you!

**Comment by jiaying002** [comment]
Okay I think I figured out all of them:
for Q1, I copied the file 0228 and rename it as 0229
for Q4, I realized that I need to run a 4*5 or 2*2.5 simulation first to get the boundary conditions. In case anyone in the future occurred the same isse, check this link: http://wiki.seas.harvard.edu/geos-chem/index.php/Setting_up_GEOS-Chem_nested_grid_simulations

**Comment by yantosca** [comment]
Thanks @jiaying002.  Most of us were off the whole week between Christmas and New Year's.  Glad to know that you found a solution.
