### ISSUE TITLE
[FEATURE REQUEST] Reinstate Iy sink reactions on alkaline sea salt aerosol and remove IONO2 recycling on alkaline sea salt aerosol

### ISSUE THREAD

**Issue by beckyalexander** [geoschem/geos-chem#1585]
### Request a new GEOS-Chem feature:
Prior to 13.3, uptake of HOI, HONO, and IONO2 on alkaline sea salt aerosol formed ISALA and ISALC. This was removed in 13.3. Also in 13.3, IONO2 recyling on alkaline sea salt aerosol was added. This has contributed to the decrease in ozone in the model. 

I've reinstated the sink reactions and removed the IONO2 recycling reaction. This, along with the sea salt alkalinity bug fixes ([here](https://github.com/geoschem/geos-chem/issues/1506) and [here](https://github.com/geoschem/geos-chem/issues/1547)), brings ozone back to previous model versions when sea salt debromination is turned on. 

These sink reactions may not be real and may serve as a straw man for missing Iy sinks. I recommend putting these sink reactions back in so that we can run the model with sea salt debromination turned on.

I've included a plot comparing this model version and two others with surface ozone observations. I've also included a patch file for this change. The model version for the patch file is 13.4.1 and was run with the above-mentioned bug fixes, this patch, and sea salt debromination turned on.

[surface.O3.geos.pdf](https://github.com/geoschem/geos-chem/files/10365194/surface.O3.geos.pdf)
[hetIy-patch-file.txt](https://github.com/geoschem/geos-chem/files/10365196/hetIy-patch-file.txt)

**Comment by yantosca** [comment]
Thanks @beckyalexander,  I can make a PR from the patch file.  This can go into 14,2.0, as we are currently wrapping up 14.1.0.

**Comment by msulprizio** [comment]
The corresponding PR (#1620) has now been merged into the 14.2.0 development branch.
