### ISSUE TITLE
Southeast Asia mask is wrong [BUG/ISSUE]

### ISSUE THREAD

**Issue by zsx-GitHub** [geoschem/geos-chem#1586]
Dear GCST, I noticed that the SE Asia mask file (/n/holyscratch01/external_repos/GEOS-CHEM/gcgrid/gcdata/ExtData/HEMCO/MASKS/v2014-07/SE_Asia_mask.generic.1x1.nc) incorrectly includes too much area to the north. That is, most parts of China are included in the Southeast Asia mask.

**Comment by yantosca** [comment]
Thanks @zsx-GitHub for writing.  That looks like an old mask file that may have been developed for a specific inventory.  @msulprizio, do you know more about this mask?

**Comment by msulprizio** [comment]
@zsx-GitHub @yantosca It looks like that mask file is quite old and was used for the Streets emissions inventory which was unsupported in GEOS-Chem 12.4.0. Most mask files are customized for specific inventories and don't necessarily represent official region definitions. If a regional mask is needed for research purposes, we recommend users generate their own using tools in python, GIS, etc.

**Comment by zsx-GitHub** [comment]
Thank you @yantosca and @msulprizio! I have generated the mask files myself. But will it be better to remove those outdated mask files and the corresponding lines in the HEMCO_Config.rc file to avoid confusion?

**Comment by yantosca** [comment]
Thanks for the update @zsx-GitHub.  We usually keep files like that for the sake of reference.  We would refer users to the README file in the folder.  I'll add a comment to denote that this mask is for Streets data and is obsolete. 

Glad that you've created the mask that you need.  I'll close out this issue.

**Comment by zsx-GitHub** [comment]
Thank you @yantosca
