### ISSUE TITLE
[FEATURE REQUEST] Remove unused HEMCO_Config entries and code for the Hg simulation

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#1587]
@jennyfisher wrote:

>Hi @yantosca - I've just cloned dev/14.1.0 and am starting to test. I noticed a couple of switches that still exist in HEMCO_Config.rc, even though we removed the sections for these as they were no longer used:
>
>1. `AERO_HG2_PARTITION`
>2. `LRED_JNO2`
>
>I think that these lines can be deleted now. @arifein @viral211 - can you confirm this is correct?

@arifein replied:

>Hi @jennyfisher, I agree that they are no longer used. However, I still see legacy lines of code referring to `LRED_JNO2` in `ocean_mercury_mod.F90` and `mercury_mod.F90` that may also have to be deleted for it to be removed in HEMCO_Config.rc as well: 
```
GeosCore/mercury_mod.F90:  USE Ocean_Mercury_Mod, ONLY : LRED_JNO2
GeosCore/mercury_mod.F90:    LRED_JNO2=.TRUE. ! Make propto JNO2 otherwise [OH]
GeosCore/mercury_mod.F90:    CALL GetExtOpt( HcoState%Config, -999, 'LRED_JNO2', &
GeosCore/mercury_mod.F90:                    OptValBool=LRED_JNO2, FOUND=FOUND, RC=RC )
GeosCore/mercury_mod.F90:       errMsg = 'LRED_JNO2 not found in HEMCO_Config.rc file!'
GeosCore/mercury_mod.F90:       LRED_JNO2 = .FALSE.
GeosCore/mercury_mod.F90:    WRITE( 6, 110   ) LRED_JNO2
GeosCore/mercury_mod.F90:110 FORMAT( 'LRED_JNO2  is set to ', L1                          )
GeosCore/ocean_mercury_mod.F90:  PUBLIC :: LRED_JNO2,   LGEOSLWC
GeosCore/ocean_mercury_mod.F90:  LOGICAL   :: LRED_JNO2,   LGEOSLWC

**Comment by msulprizio** [comment]
The corresponding PR for this feature request is now merged into `dev/14.1.0`.
