### ISSUE TITLE
[QUESTION] EXPID:  ./OutputDir/GEOSChem does not work when do not collect HEMCO_diagnostics

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/geos-chem#159]
Hi there,

I have been advised that I can [disable all HEMCO diagnostics collection by simply removing DiagnFile, DiagnPrefix, DiagnFreq from HEMCO_Config.rc](https://github.com/geoschem/geos-chem/issues/149). I also reported that this kind of practice will return us 'dry' HEMCO diagnostics files, which from my perspective is acceptable but imperfect. Today, I found that `EXPID:  ./OutputDir/GEOSChem` does not work, either, under this circumstance. Taking Restart as an illustration, I will receive all GEOSChem.Restart.*.nc4 files under the rundir instead of OutputDir subdirectory under the rundir. My model configuration is as the same as I reported [here](https://github.com/geoschem/geos-chem/issues/146) except that I have removed DiagnFile, DiagnPrefix, DiagnFreq from HEMCO_Config.rc.

I suppose this is not a bug but you might be interested in addressing it so as to improve the GC code to a higher standard. I will provide you my GC and HEMCO log files with verbose information switched on in a later time for you to check. Their sizes will be relatively big this time.

Thanks for all of your work!

Yours faithfully,
Fei

**Comment by christophkeller** [comment]
Hi Fei,
thanks for reporting. Have you tried setting DiagnFreq to '99999999 999999'? This might do what you are looking for.
Either way, we can update the code so that no diagnostics are written out if no DiagnFile is provided. We can add this to the planned HEMCO updates.

**Comment by FeiYao-Edinburgh** [comment]
> I will provide you my GC and HEMCO log files with verbose information switched on in a later time for you to check.

Here are the [GC](https://uoe-my.sharepoint.com/:u:/g/personal/s1855106_ed_ac_uk/EcYy0YipLvhDm4-NyMr460oBZ-jl_sRac0r6yQ0DHRQ8Ww?e=Mq1cgI) and [HEMCO](https://uoe-my.sharepoint.com/:u:/g/personal/s1855106_ed_ac_uk/EaveRa2NuxhImdF-2OHRwKcBpqYiFLcU4HqX-xCysalWiw?e=tpPh7T) log files that might be useful for you to check the problem.



> Have you tried setting DiagnFreq to '99999999 999999'?

Seems a good idea and is trying now.



> We can add this to the planned HEMCO updates.

This is much appreciated.

**Comment by FeiYao-Edinburgh** [comment]
> I will receive all GEOSChem.Restart.*.nc4 files under the rundir instead of OutputDir subdirectory under the rundir.

Just realised that there is a line change for Restart collection in HISTORY.rc from GC 12.2.1 to GC 12.5.0 and hence might lead to the Restart file collection under the rundir.
```
Restart.template:           '%y4%m2%d2_%h2%n2z.nc4',
```
= >
```
Restart.filename:           './GEOSChem.Restart.%y4%m2%d2_%h2%n2z.nc4',
```
Anyway, I finally realise that it might be more reasonable to receive GC restart files under the rundir since they are read in from there.

**Comment by yantosca** [comment]
Thanks for writing.  A couple of things:

1. The Restart.filename is used to force GC to write the restart files to the rundir instead of to OutputDir.  Only HISTORY and HEMCO diagnostic output should go into the OutputDir folder.  This update was made in I think 12.3.0 or 12.4.0.
2. As Christoph said, we can update HEMCO so that "dry" diagnostic files won't be written out.

We are planning some updates for HEMCO so things may change over the next few versions.
