### ISSUE TITLE
[FEATURE REQUEST] Add tagO3 simulation to GCHP integration tests

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#1593]
The tagO3 run directory for GCHP has been added in 14.1.0 (see https://github.com/geoschem/geos-chem/pull/1380). We should now include this simulation in the GCHP integration tests to ensure it is functioning properly.

**Comment by yantosca** [comment]
This will be done also in PR #1565

**Comment by yantosca** [comment]
We can now close this issue as PR #1565 has been merged into the 14.1.1 development stream.
