### ISSUE TITLE
[QUESTION] the MERRA2 data in the website

### ISSUE THREAD

**Issue by LiHui94** [geoschem/geos-chem#1599]
### Ask a question about GEOS-Chem:

Hi, I have been checking the MERRA2 data in the 
http://geoschemdata.wustl.edu/ExtData/. While the MERRA2 uploaded on the website stopped in July 2022, without further updating (more specifically, from August to December 2022). Is there anything wrong with MERRA2 data, and when will the MERRA2 data after July 2022 be uploaded?

**Comment by SaptSinha** [comment]
Thank you for your patience! We have been able to resolve some of the issues we encountered earlier for processing the MERRA2 datasets. You can now access all the relevant MERRA2 datasets from the year 2022 by using the following links:

http://geoschemdata.wustl.edu/ExtData/GEOS_0.5x0.625/MERRA2/2022/
http://geoschemdata.wustl.edu/ExtData/GEOS_0.5x0.625_AS/MERRA2/2022/
http://geoschemdata.wustl.edu/ExtData/GEOS_0.5x0.625_EU/MERRA2/2022/
http://geoschemdata.wustl.edu/ExtData/GEOS_0.5x0.625_NA/MERRA2/2022/
