### ISSUE TITLE
Possible issue with NEI Day of Week (DOW) scalars

### ISSUE THREAD

**Issue by kelaar** [geoschem/geos-chem#1608]
**Description of the problem**

I have been investigating a problem where my simulation results were noticeably different within NEI-covered areas depending on the date I started my simulation.  An example of this is shown in the attached figure (NO2Difference.png):

![NO2Difference](https://user-images.githubusercontent.com/70774972/213262700-94dc681d-3806-4525-b60f-1f3205104642.png)

Here I started one simulation in mid-May 2007 and a second simulation using the first simulation's restart file for June 14.  Comparing the output from these two simulations on June 30 demonstrates the sort of differences I am seeing.

**Description of troubleshooting performed**

Disabling the DOW scalar within HEMCO removed the inconsistencies between my simulations with different start dates, suggesting that the day of week indices is not being calculated and/or applied correctly to the monthly mean NEI emissions.  Closer inspection of the NEI99 Day of Week (DOW) scalars (NEI99.dow.geos.1x1.nc) also showed that all values are 1 for weekdays and <1 for weekends (see below).  As a result, it appears that even if the scalars were being appropriately applied they would erroneously produce a decrease in the NEI monthly total emissions compared to the original monthly totals.

![NEI99DOWscalars](https://user-images.githubusercontent.com/70774972/213262706-13ba1177-2078-4a4f-891a-1ee5f891e37a.png)

**GEOS-Chem version**

13.2.1

**Description of modifications**

No longer applying the NEI99 DOW scalars to NEI2011 removes the immediate issue, but there may be a remaining issue within GEOS-Chem as to how such DOW scalars are implemented.

**Comment by yantosca** [comment]
Thanks for writing @kelaar.  I am not sure if this has been resolved in later GC/HEMCO versions.  We can take a look but it may take us a bit.

**Comment by lizziel** [comment]
Hi @kelaar, I have been looking into this issue due to a separate report of the problem. I have a fix which I will make a pull request for today. It will go into the MAPL version used in GEOS-Chem 14.1.

**Comment by lizziel** [comment]
To be more clear, I am fixing a DOW issue in GCHP. Are you using GCHP or GC-Classic?

**Comment by kelaar** [comment]
Thanks Lizzie!  I'm using GCHP, so your fix would be applicable.  Relatedly, have you given any thought as to whether the NEI99 DOW scalars are appropriate to use with the monthly mean NEI2011/NEI2016 emission inventories?  As I mentioned above, it looks to me as though the DOW scalars would change the total monthly emissions even if the correct day of week was being indexed since they don't average to one over the week.

**Comment by yantosca** [comment]
@kelaar: The NEI99 scale factors might be an issue to bring up to the Emissions WG.  Maybe a new set of scale factors need to be developed for NEI16.

**Comment by lizziel** [comment]
Hi @kelaar, you can try applying my changes here to your version of MAPL to see if it fixed the day of week issue.

Regarding the appropriateness of using the NEI99 DOW scalars with monthly mean NEI2011/NEI2016, I also recommend contacting the Emissions Working Group. I am tagging Co-Chairs Eloise Marais (@eamarais) and Lyatt Jaegle (@jaegle).

**Comment by lizziel** [comment]
If you don't hear back from anyone here you can also try emailing them. Contact info is on the [Emissions Working Group wiki page](http://wiki.seas.harvard.edu/geos-chem/index.php/Emissions_Working_Group).

**Comment by kelaar** [comment]
Thanks for the suggestion, Lizzie.  I'll follow-up directly, if necessary.

**Comment by eamarais** [comment]
Hi @kelaar, it would be good to confirm that this is for sure an error and not intentional. I agree with you that it would be logical that the sum of a week of weekend/weekday scaling factors should add to 7. 
Is there anything in the README file or data processing code in the ExtData/HEMCO subdirectory with the scaling factor file(s) that might explain scaling < 1 on weekends and =1 on weekdays?

**Comment by lizziel** [comment]
@kelaar, could you also identify who you are and what institution you are at?

**Comment by kelaar** [comment]
Eloise: Good idea.  I can't speak to NEI2016, but the README for NEI2011 did not mention any adjustment for the NEI99 DOW scalars.  The wiki for NEI2011 (https://wiki.seas.harvard.edu/geos-chem/index.php/EPA/NEI11_North_American_emissions) provided a link to the script used to create the monthly mean NEI2011 files from their hourly source (/NEI2011/v2017-02-MM/scripts/NEI2011_monthly_mean.sh).  I'm not deeply familiar with all the commands used in this script, but I don't see anywhere that such an adjustment is being made to be compensate for the bias potentially added via the NEI99 DOW scalars.

Lizzie: Apologies for not identifying myself earlier; I thought you had this information as part of my login during posting.  This is Aaron van Donkelaar from WashU.

**Comment by eamarais** [comment]
Hi @kelaar. Thanks for looking into this. I think then this should be fixed. NEI is no longer a default inventory in the global simulations, but many still turn it on. It's also possible that this has been an issue for a while. At least since these DOW files were converted from bpch to NetCDF for development of HEMCO. Longer if the original bpch files were used as is.

Have you implemented a fix for this in your copy of GEOS-Chem that you could share with the GCST?

**Comment by kelaar** [comment]
Due to some tight deadlines, for my part I just removed the NEI99 DOW scalars from use with the monthly mean NEI2011 emissions.  I'm not sure this counts as a 'fix', as it removes the representation of the weekend/weekday emission variability when using the monthly mean NEI emissions.  That said, I expect anyone interested in such daily features would be using the hourly NEI2011 inventory instead.  The same would be true for NEI2016, assuming these also use the NEI99 DOW scalars.

To my knowledge, the NEI99 DOW scalars aren't used by HTAP, or any other monthly mean inventory, plus given how out of date these factors are, perhaps the answer is just to retire the NEI99 DOW factors altogether and remove them from the default HEMCO configuration files?

**Comment by eamarais** [comment]
@kelaar, I agree that these are likely out of date and are anyway coarse (1 deg) in comparison to the NEI2016 inventory and the nested and GCHP simulations. Even if we decide to retire these they might need to be replaced with a temporary correction factor and perhaps in the future a more contemporary set of scaling factors, as the NEI2016 emissions are provided as monthly averages. And there may be groups using earlier versions of GEOS-Chem (adjoint, perhaps?) that still default to NEI emissions over the US. 

I've included @SaptSinha in case he knows how to check whether users have in the last few months or so been downloading the dow files from http://geoschemdata.wustl.edu/ExtData/HEMCO/NEI2005/v2014-09/scaling/.  This might give us a sense of user uptake. If so, I've written python code to recalculate these scaling factors to retain the original relative scaling and ensure these add to 7 for all grids each week.

**Comment by kelaar** [comment]
Hi Eloise,

If we're making a new/corrected weekend/weekday scalar anyways, might it make more sense to use the hourly NEI2011 emissions as a base? Since the NEI99 scalars have been both incorrect and incorrectly applied, I'm not sure there is tremendous value in producing an NEI99-based factor given their age and coarseness.  I can't speak to the adjoint (which is a good point), but otherwise NEI99 base emissions aren't even implemented in the standard code.

The NEI2011 are at 0.1 x 0.1 degree and using these for weekend/weekday scalars would be more consistent with the NEI2011 emissions (and likely NEI2016 as well).  I haven't looked in detail, but it appears that the NEI2011 hourly files provide an emission for each day (and hour) within 2011.  Sorting each month by weekend/weekday and taking the ratio between the average of each and the weekly-averaged conditions should be all it takes.

What do you think?

**Comment by eamarais** [comment]
Yes, of course. A more recent inventory would be better, but I don't have the time to do this. Someone in the community would have to take this on. At the very least correcting the NEI99.dow data would offer a quick fix for those using the NEI99.dow scaling factors.

**Comment by kelaar** [comment]
I certainly understand such time constraints.  Yes, the NEI99.dow fix you propose would at least be consistent with what was originally intended for use with NEI2011/NEI2016.

**Comment by eamarais** [comment]
Hi @lizziel, I've created a file of correct dow scaling factors that can be used with the NEI monthly emissions. I haven't tested it though. I might have some time to do this tomorrow or Friday. Unless someone from the GCST can do a quick HEMCO standalone test to make sure there aren't any issues reading and using the variables in the file? Let me know and I can share the file.

For reference, the updated scaling factors should increase gridded NEI emissions by up to ~4.5% for NOx, ~7.5% for CO, ~3.5% for ALK4, ~0.4% for ACET and MEK, ~5.5% for PRPE, ~2.2% for C3H8, ~3.5% for C2H6, ~4% for SOx, ~7.5% for MSA, ~8% for BC and ~2.5% for OC for individual grids. The impact on the nested domain total will be relatively small.

**Comment by lizziel** [comment]
Thanks @eamarais. When you are satisfied with the file you can send it to us and we will include it in the next version.

**Comment by eamarais** [comment]
The data compressed to a size small enough to share via GitHub. The attached zipped file includes the corrected dow file and the python code I wrote to convert the data. 

I preserved the names and structure of the file, so that implementation in HEMCO_Config.rc just requires updating the file name. I tested that it is read and applied with GCClassic v13.0.0. I assume it should work with more recent versions? Expected changes to the emissions are documented in the python code and in my previous comment.  

[FixNEI99DOW.zip](https://github.com/geoschem/geos-chem/files/10535752/FixNEI99DOW.zip)

**Comment by yantosca** [comment]
Thanks @eamarais. I'll create a PR with the new scale factors.  Stay tuned.

**Comment by yantosca** [comment]
I have added PR #1633 to point the `HEMCO_Config.rc` and `ExtData.rc` files to the updated scale factor file created by @eamarais.

@lizziel is looking into a separate day-of-week issue in GCHP/MAPL.

**Comment by lizziel** [comment]
The fix I implemented for MAPL is going into 14.1.1. If there are further issues with NEI day of week scale factors please open a new issue.
