### ISSUE TITLE
Track species production/loss from multiple reactions separately

### ISSUE THREAD

**Issue by hazel008** [geoschem/geos-chem#1610]
### Ask a question about GEOS-Chem:
Hello,

I want to track the chemical productions and losses of several species in GEOS-Chem. There are multiple reactions contribute to the production and loss, and I want to track them separately. For example, we have the following reactions contribute to C production and loss:
```console
A + B = C
D + E = C
C + F = G
C + H = I
```
If I want to calculate the contributions from these reactions, I can add four dummy tracers on the right side as below in fullchem.eqn file:
```console
A + B = C + C_Pab
D + E = C + C_Pde
C + F = G + C_Lf
C + H = I + C_Lh
```
I wonder if there are some better or simpler ways to do this? Because I have tens of reactions to tag.

Thank you,
Hansen

**Comment by yantosca** [comment]
Thanks for writing @hazel008.  You could define production and loss families for C in the *.kpp file as described in our KPP user manual ([click here for link](https://kpp.readthedocs.io/en/stable/using_kpp/04_input_for_kpp.html#families))

You will have to update to KPP 2.5.0+ in order to be able to use the family species (in GEOS-Chem 14.0.0 and later).

**Comment by hazel008** [comment]
Hi Bob, 

Thanks for the quick response! 
I've taken a look at the manual you suggested. It seems that using the family species in *.kpp file can track the total chemical production and total chemical sink for the family species (e.g. Ox). 

However, I want to track the production (or loss) from each reaction separately, not in a total way. For example, I want to calculate how much the reaction A + B contributes to C production, and how much D + E contributes to C production. It seems that I need to tag these reactions separately using different dummy species. I wonder if there is a way to tag these reactions automatically? Thanks!

Best,
Hansen

**Comment by yantosca** [comment]
Thanks @hazel008.  In that case, yes you would probably need to add dummy species.  I don't think you can tag those automatically right now.

Also tagging @msl3v
