### ISSUE TITLE
Surface CH4 mixing ratios and trends

### ISSUE THREAD

**Issue by KBMoiseenko** [geoschem/geos-chem#1612]
### What institution are you from?
Obukhov Institute of atmospheric physics, Moscow

### Description of the problem
I have some troubles with methane simulations when using the 14-02 version of the model as discussed in the attached .doc file. The model underestimates severely near-surface methane concentrations and shows negative trends in methane mixing ratios which is opposite to the observed positive trend

[methane simulations.docx](https://github.com/geoschem/geos-chem/files/10464064/methane.simulations.docx)

### Description of troubleshooting performed
I have checked GEOS-chem 14-02 global EDGAR CH4 emissions against those used in the previous GEOS-chem version. The current emissions are seemed to be correct

### GEOS-Chem version
14-02

### Description of modifications
No modifications

### Log files
- Build log (if applicable):
- Run logs (if applicable):
- Run script (if applicable):

### Software versions
- CMake version: 3.22.1
- Compilers (Intel or GNU, and version): Intel 19.1.3.304
- NetCDF version: 4.8.0

**Comment by yantosca** [comment]
Dear @KBMoiseenko, would you be able to send us a short description about your institution and the research that you do?  We can post that on the GC People and Projects page.

**Comment by KBMoiseenko** [comment]
*Short description:*

Obukhov Institute of Atmospheric Physics, Russia

Atmospheric modeling and air quality research group

We use GEOS-chem model to study impact of photochemistry and long-range
transport on the regional budget of ozone-related species and atmospheric
oxidation capacity for the regions of northern Eurasia including European
part of the continent, Siberia, and Far East.

Grope Website: http://ifaran.ru/index.html?&locale=en
Grope Leader: Konstantin B. Moiseenko (Research Scientist); email:
***@***.***

*Kind regards, Konstantin*

пт, 20 янв. 2023 г. в 17:50, Bob Yantosca ***@***.***>:

**Comment by lizziel** [comment]
Hi @KBMoiseenko. This is beyond the scope of support offered by the GEOS-Chem Support Team. I suggest reaching out to the appropriate GEOS-Chem working group. Contact information for working groups is located [here](https://geos-chem.seas.harvard.edu/geos-working-groups).

**Comment by Eileencd** [comment]
I have the same problem in CH4 simulation, but with the same emission settings, the methane concentration trend in tagCH4 simulation mode is positive. I would like to ask if this problem has been solved.
