### ISSUE TITLE
[ISSUE] Emission file on geoschemdata.wustl incomplete

### ISSUE THREAD

**Issue by eamarais** [geoschem/geos-chem#1616]
An offline biogenic VOC 0.5 deg resolution file provided on geoschemdata.wustl.edu only has 16 of 24 timesteps. The path to the file is http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_BIOVOC/v2021-12/0.5x0.625/2018/01/biovoc_05.20180114.nc. A screenshot below shows it's a smaller size than the other files. There doesn't appear to be an issue with the file on the same day at 0.25 deg resolution.

![Screenshot 2023-01-23 at 13 27 02](https://user-images.githubusercontent.com/55648553/214112120-77cf6784-864d-48f0-a93e-7f75a3da85cc.png)

**Comment by SaptSinha** [comment]
I am afraid I do not have an answer to this issue as I have not yet gotten a chance at generating offline emissions of biogenic VOCs and other species, due to the ongoing issues with my compute1 account. My guess is that the file in question might have been corrupted and it would be useful to contact the person who generated this in 2021.

**Comment by eamarais** [comment]
Thanks @SaptSinha. 

@hongjianweng, you're listed as the data generator in the README.txt file. Do you know if the file I've referred to above was corrupted when it was generated? Or if it was corrupted when it was added to the GEOS-Chem data repo?

**Comment by eamarais** [comment]
Two more offline biogenic VOC files that are missing data entries:
./OFFLINE_BIOVOC/v2021-12/0.5x0.625/2018/08/biovoc_05.20180814.nc
./OFFLINE_BIOVOC/v2021-12/0.5x0.625/2018/08/biovoc_05.20180822.nc

Not sure who is responsible for these now? No response from @hongjianweng.

**Comment by msulprizio** [comment]
@YanshunLi-washu would you be able to assist @SaptSinha with correcting these files?

**Comment by SaptSinha** [comment]
I am very sorry to learn that this has not yet been resolved, @eamarais. I checked both the folders http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_BIOVOC/v2021-12/0.5x0.625/2018/01/ and http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_BIOVOC/v2021-12/0.5x0.625/2018/08/, and it looks like there are at least three files that are missing additional entries.

I attempted going through the guidelines available in the HowTos folder so as to try reproducing and re-uploading all the files for both 2018/01 and 2018/08. But it looks like I do not have access to the zipped files, viz. compress.zip and OFFLINE_SNOx_BVOCs_SSA.zip, that I need to start the process. If @msulprizio or someone else can provide me with access to these files, I can try to assist with this issue.

**Comment by YanshunLi-washu** [comment]
Hi @msulprizio Sure thing!  Hi @SaptSinha, please check the email with attachments I just sent. Feel free to reach out to me if you have any questions.

**Comment by SaptSinha** [comment]
Great! Thank you very much. 

I just wanted to keep you all updated and let you know that I have started working on this issue. I will let you know once this is resolved or if I need anything else.

**Comment by SaptSinha** [comment]
Hello @eamarais, I just wanted to quickly follow up and let you know that @YanshunLi-washu and I are continuing to work on this front. So far, I have located the following list of corrupted files and it might take awhile before all of them are rectified. No worries about opening another GitHub issue but please feel free to let us know if you come across any other corrupted files with missing entries.


http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_SOILNOX/v2021-12/0.5x0.625/2018/08/20180814.nc
http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_BIOVOC/v2021-12/0.5x0.625/2018/01/biovoc_05.20180114.nc
http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_BIOVOC/v2021-12/0.5x0.625/2018/08/biovoc_05.20180814.nc
http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_BIOVOC/v2021-12/0.5x0.625/2018/08/biovoc_05.20180822.nc

/storage1/fs1/rvmartin/Active/GEOS-Chem-shared/ExtData/HEMCO/OFFLINE_BIOVOC/v2019-10/0.5x0.625/2015/01/.biovoc_05.20150101.nc.mSgT6f
/storage1/fs1/rvmartin/Active/GEOS-Chem-shared/ExtData/HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/1988/05/dust_emissions_05.19880530.nc
/storage1/fs1/rvmartin/Active/GEOS-Chem-shared/ExtData/HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/1984/06/dust_emissions_05.19840611.nc
/storage1/fs1/rvmartin/Active/GEOS-Chem-shared/ExtData/HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/1984/06/dust_emissions_05.19840613.nc
/storage1/fs1/rvmartin/Active/GEOS-Chem-shared/ExtData/HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/1986/01/dust_emissions_05.19860119.nc
/storage1/fs1/rvmartin/Active/GEOS-Chem-shared/ExtData/HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/1994/01/dust_emissions_05.19940128.nc
/storage1/fs1/rvmartin/Active/GEOS-Chem-shared/ExtData/HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/1994/12/dust_emissions_05.19941204.nc
/storage1/fs1/rvmartin/Active/GEOS-Chem-shared/ExtData/HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/1980/08/dust_emissions_05.19800804.nc
/storage1/fs1/rvmartin/Active/GEOS-Chem-shared/ExtData/HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/1980/07/dust_emissions_05.19800712.nc
/storage1/fs1/rvmartin/Active/GEOS-Chem-shared/ExtData/HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/1982/08/dust_emissions_05.19820815.nc
/storage1/fs1/rvmartin/Active/GEOS-Chem-shared/ExtData/HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/1992/02/dust_emissions_05.19920223.nc

**Comment by eamarais** [comment]
Thanks for the update.

**Comment by SaptSinha** [comment]
Hello @eamarais, I wanted to let you know that the following emission files with missing data entries have now been rectified in the archive:

http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_SOILNOX/v2021-12/0.5x0.625/2018/08/20180814.nc
http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_BIOVOC/v2021-12/0.5x0.625/2018/01/biovoc_05.20180114.nc
http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_BIOVOC/v2021-12/0.5x0.625/2018/08/biovoc_05.20180814.nc
http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_BIOVOC/v2021-12/0.5x0.625/2018/08/biovoc_05.20180822.nc

Additionally, the ".biovoc_05.20150101.nc.mSgT6f" file does not appear to be a data file (as it could be a meta-data entry created via a different process). You can safely ignore this file.

I am also planning to rectify the remaining dust emission files by the upcoming week but I wanted to update you about the specific files above that you pointed out earlier.

**Comment by eamarais** [comment]
Thanks @SaptSinha, I've downloaded the updated files to our system. In case anyone uses this thread to update their files, the first link should be:
http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_SOILNOX/v2021-12/0.5x0.625/2018/08/soilnox_05.20180814.nc

**Comment by eamarais** [comment]
Hi @SaptSinha, there's another offline biogenic VOC file that needs to be reprocessed: 
http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_BIOVOC/v2021-12/0.5x0.625/2018/11/biovoc_05.20181121.nc

**Comment by eamarais** [comment]
Thanks. I've downloaded it to our local servers.

**Comment by msulprizio** [comment]
I will close out this issue. Please feel free to reply here or open another issue if there are other problematic files.
