### ISSUE TITLE
[FEATURE REQUEST] Add nitrate photolysis from Shah et al. (2023)

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#1622]
Viral Shah (@viral211) has implemented nitrate photolysis into GEOS-Chem 12.9.3. Nadia Columbi (Harvard) is currently evaluating this update in combination with SSA debromination on/off and fixes for [sea salt alkalinity](https://github.com/geoschem/geos-chem/issues/1547) and restoration of the [Iy sink](https://github.com/geoschem/geos-chem/issues/1585).

**Reference:** 

>Shah, V., Jacob, D. J., Dang, R., Lamsal, L. N., Strode, S. A., Steenrod, S. D., Boersma, K. F., Eastham, S. D., Fritz, T. M., Thompson, C., Peischl, J., Bourgeois, I., Pollack, I. B., Nault, B. A., Cohen, R. C., Campuzano-Jost, P., Jimenez, J. L., Andersen, S. T., Carpenter, L. J., Sherwen, T., and Evans, M. J.: Nitrogen oxides in the free troposphere: implications for tropospheric oxidants and the interpretation of satellite NO2 measurements, Atmos. Chem. Phys., 23, 1227–1257, https://doi.org/10.5194/acp-23-1227-2023, 2023.

**Comment by yantosca** [comment]
I have submitted PR #1623, which will implement this feature request.  All integration tests have passed.

**Comment by msulprizio** [comment]
The pull request (#1623) for this feature has now been merged into the 14.2.0 development branch.
