### ISSUE TITLE
[FEATURE REQUEST] ALK4 and R4N2 chemistry from Brewer et al. (2023)

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#1625]
R4N2 was a common product of alkane, isoprene, and monoterpene oxidation and produced organonitrate SOA but we don’t want ALK4 to produce organonitrate SOA. Jared Brewer has implemented a fix to address this.

**Reference**

>Brewer, J.F., D.J. Jacob, S.H. Jathar, Y. He, A. Akherati, S. Zhai, D.S. Jo, A. Hodzic, B.A. Nault, P. Campuzano-Jost, J.L. Jimenez, R.J. Park, Y.J. Oak, and H. Liao, [A scheme for representing aromatic secondary organic aerosols in chemical transport models: application to source attribution of organic aerosols over South Korea during the KORUS-AQ campaign,](https://doi.org/10.1029/2022JD037257) J. Geophys. Res., e2022JD037257, https://doi.org/10.1029/2022JD037257, 2023.

**Comment by yantosca** [comment]
@msulprizio, do we have code for this or do we have to manually edit the KPP *.eqn file from the paper?

**Comment by msulprizio** [comment]
I've emailed Jared to get these code updates. We do not have them yet.

**Comment by msulprizio** [comment]
@JFBrewer is there any update on this? Could you create a pull request with these updates or point us to your code?

**Comment by yantosca** [comment]
We can now close this issue as PR #2352 has been merged into the GEOS-Chem 14.5.0 development stream.
