### ISSUE TITLE
[FEATURE REQUEST] Add S(IV) + HOBr/HOCl to enhanced in-cloud sulfate production rates in large cloud droplets

### ISSUE THREAD

**Issue by beckyalexander** [geoschem/geos-chem#1627]
### Request a new GEOS-Chem feature:
Chen et al., GRL, (2017) added S(IV) + HOBr to GEOS-Chem v9-02. In v9-02. This reaction was included in the enhanced in-cloud sulfate production rate for larger, higher-pH cloud droplets in addition to the "bulk" cloud chemistry. Previously, this enhancement in the sulfate production rate was applied only to S(IV) + O3 (Alexander et al., JGR, 2012). When S(IV)+HOBr was implemented into the standard version of GEOS-Chem, it was mistakenly not included in the enhanced sulfate production (termed "SR" in the code, where SR = size-resolved cloud droplets). This mistake occurred because the original implementation (and resulting publication) was in SMVGEAR and the transfer to KPP was incomplete. I did not realize this until recently.

This does not change the enhanced sulfate production rate (SR) because SR is the same but is now split up between O3, HOBr, and HOCl instead of all being attributed to O3. I suggest fixing this so that the chemistry in the model is as it is described in Chen et al., (2017).

I added this to the code (13.4.1) and have included a patch file here. The changes to SO2, SO4, HOBr, HBr, HOCl, HCl, O3, and BrO for January 2019 are small to negligible. 

[SR_HOX-patch-file.txt](https://github.com/geoschem/geos-chem/files/10522321/SR_HOX-patch-file.txt)

[SRHOX_ssdebromBrClIhet_HOBrHBr.pdf](https://github.com/geoschem/geos-chem/files/10522326/SRHOX_ssdebromBrClIhet_HOBrHBr.pdf)
[SRHOX_ssdebromBrClIhet_HOClHCl.pdf](https://github.com/geoschem/geos-chem/files/10522328/SRHOX_ssdebromBrClIhet_HOClHCl.pdf)
[SRHOX_ssdebromBrClIhet_O3BrO.pdf](https://github.com/geoschem/geos-chem/files/10522329/SRHOX_ssdebromBrClIhet_O3BrO.pdf)
[SRHOX_ssdebromBrClIhet_SO2SO4.pdf](https://github.com/geoschem/geos-chem/files/10522330/SRHOX_ssdebromBrClIhet_SO2SO4.pdf)

**Comment by yantosca** [comment]
Thanks @beckyalexander.  I'll pull this into a PR shortly.

**Comment by yantosca** [comment]
All GCHP integration tests passed:
```console
==============================================================================
GCHP: Execution Test Results

Number of execution tests: 3
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gchp_fullchem_benchmark_merra2_c48..................Execute Simulation....PASS
gchp_fullchem_standard_merra2_c24...................Execute Simulation....PASS
gchp_TransportTracers_geosfp_c24....................Execute Simulation....PASS
 
Summary of execution test results:
------------------------------------------------------------------------------
Execution tests passed:        3
Execution tests failed:        0
Execution tests not completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
