### ISSUE TITLE
[QUESTION] Translating SOA reactions from carbon_mod to KPP

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#1629]
This question is directed at the Aerosols WG: @beckyalexander @theloniuspunk @wporter and Mike Long @msl3v.  If anyone else has any suggestions feel free to chime in!

I've been looking at the complex SOA in carbon_mod.F90.  I've been able to separate the computation of kinetic rates vs. equilibrium constants, in preparation for porting the kinetic rates to KPP.  That part was pretty straightforward.

I'm now looking at the code in routine CHEM_NVOC to see if I can identify the equations to add to KPP:
https://github.com/geoschem/geos-chem/blob/ee8d0eb04d7ad095fe07fb930f28036f256b6709/GeosCore/carbon_mod.F90#L3385-L3522

Just considering the first lumped semivolatile (MTPA, LIMO, MTPO, SESQ) for now, I believe that what the code is doing is implementing these reactions:

```console
MTPA + O3 + OH + NO3 = TSOG1  ; k = (KO3(1)*C(ind_O3) + KOH(1)*C(ind_OH) + KNO3(1)*C(ind_NO3))
LIMO + O3 + OH + NO3 = TSOG1  ; k = (KO3(2)*C(ind_O3) + KOH(2)*C(ind_OH) + KNO3(2)*C(ind_NO3))
MTPO + O3 + OH + NO3 = TSOG1  ; k = (KO3(3)*C(ind_O3) + KOH(3)*C(ind_OH) + KNO3(3)*C(ind_NO3))
SESQ + O3 + OH + NO3 = TSOG1  ; k = (KO3(4)*C(ind_O3) + KOH(4)*C(ind_OH) + KNO3(4)*C(ind_NO3))

MTPA + O3 + OH + NO3 = TSOG2  ; k = (KO3(1)*C(ind_O3) + KOH(1)*C(ind_OH) + KNO3(1)*C(ind_NO3))
LIMO + O3 + OH + NO3 = TSOG2  ; k = (KO3(2)*C(ind_O3) + KOH(2)*C(ind_OH) + KNO3(2)*C(ind_NO3))
MTPO + O3 + OH + NO3 = TSOG2  ; k = (KO3(3)*C(ind_O3) + KOH(3)*C(ind_OH) + KNO3(3)*C(ind_NO3))
SESQ + O3 + OH + NO3 = TSOG2  ; k = (KO3(4)*C(ind_O3) + KOH(4)*C(ind_OH) + KNO3(4)*C(ind_NO3))

MTPA + O3 + OH + NO3 = TSOG3  ; k = (KO3(1)*C(ind_O3) + KOH(1)*C(ind_OH) + KNO3(1)*C(ind_NO3))
LIMO + O3 + OH + NO3 = TSOG3  ; k = (KO3(2)*C(ind_O3) + KOH(2)*C(ind_OH) + KNO3(2)*C(ind_NO3))
MTPO + O3 + OH + NO3 = TSOG3  ; k = (KO3(3)*C(ind_O3) + KOH(3)*C(ind_OH) + KNO3(3)*C(ind_NO3))
SESQ + O3 + OH + NO3 = TSOG3  ; k = (KO3(4)*C(ind_O3) + KOH(4)*C(ind_OH) + KNO3(4)*C(ind_NO3))

MTPA + O3 + OH + NO3 = TSOG0  ; k = (KO3(1)*C(ind_O3) + KOH(1)*C(ind_OH) + KNO3(1)*C(ind_NO3))
LIMO + O3 + OH + NO3 = TSOG0  ; k = (KO3(2)*C(ind_O3) + KOH(2)*C(ind_OH) + KNO3(2)*C(ind_NO3))
MTPO + O3 + OH + NO3 = TSOG0  ; k = (KO3(3)*C(ind_O3) + KOH(3)*C(ind_OH) + KNO3(3)*C(ind_NO3))
SESQ + O3 + OH + NO3 = TSOG0  ; k = (KO3(4)*C(ind_O3) + KOH(4)*C(ind_OH) + KNO3(4)*C(ind_NO3))
```
The reaction rates in `KOH(1-4)` are in cm3/molec/s, so they have to be multiplied by the concentrations `C` in `molec/cm3` to get the rate to be `1/s` for KPP.  Have I interpreted this correctly?

Also, there is also some additional code that depends on the change in concentrations of these species (everything below the `IF CHANGE(JHC) ... block)`.  It would seem that this part would have to be done after KPP is called, since it depends on the change in concentration of each hydrocarbon, as well as high/low NOx conditions.  It seems that this code would have to be done outside of KPP, as I think you couldn't get the change in concentration until you exit KPP (and then compare the concentrations before & after integration.  Would you have any suggestions on how to proceed? 

Thanks much for your insights.  This is the first time I've really looked into how the complex SOA code works myself, so I'm still getting acclimated.  I will post any further questions I have on this thread.

**Comment by theloniuspunk** [comment]
Hi Bob,

I have not done much within the complex scheme, but what you wrote seems to
make sense to me.

Jeff

**Comment by msl3v** [comment]
> MTPA + O3 + OH + NO3 = TSOG1 ; k = (KO3(1)*C(ind_O3) + 
> KOH(1)*C(ind_OH) + KNO3(1)*C(ind_NO3))
You're correct re. the units of the rate constants and the resulting 
rates. I think you need to be sure to break the reactions up into their 
components e.g.
     MTPA + O3 = ...
     MTPA + OH = ...
     MTPA + NO3 = ...
etc.
> Also, there is also some additional code that depends on the change in 
> concentrations of these species (everything below the |IF CHANGE(JHC) 
> ... block)|. It would seem that this part would have to be done after 
> KPP is called, since it depends on the change in concentration of each 
> hydrocarbon, as well as high/low NOx conditions. It seems that this 
> code would have to be done outside of KPP, as I think you couldn't get 
> the change in concentration until you exit KPP (and then compare the 
> concentrations before & after integration. Would you have any 
> suggestions on how to proceed?
Jeebers this is a complicated chunk of code here. Have you been able to 
determine what this portion of code is actually producing? It looks to 
me like its generating the quantity GM0. And that GM0 is used as the 
initial gas concentration for gas/particle equilibration.
    Also, I think I'd recommend keeping this out of KPP. You'd probably 
have to add some P/L-type dummy vars. Even if they didn't impact the 
solution, they'd increase the problem size and compute time.

**Comment by yantosca** [comment]
@msl3v, it computes GM0 (gas mass) and then partitions that later into AM0 (carbon mass), which is done in SOA_CHEMISTRY and CHEM_NVOC in carbon_mod.F90.  I also agree we'd have to split up the reactions indivudually like you said, I was just trying to see what the result operations were. 

Unless we just operate on the lumped semivolatiles in KPP.  We could make a new species SV1 = MTPO + LIMO + MTPA + SESQ and then it'd be just 12 reactions I think:
```console
SV1 + O3 = TSOG1
SV1 + O3 = TSOG1
SV1 + O3 = TSOG1
etc. for TSOG2, TSOG3, TSOG0.
```
But you're right, that is adding a lot of reactions.

Also tagging @djxjacob.

**Comment by yantosca** [comment]
Closing out this issue
