### ISSUE TITLE
[BUG/ISSUE] gamma N2O5 correction

### ISSUE THREAD

**Issue by cdholmes** [geoschem/geos-chem#163]
Xuan Wang found a bug in the organic coating thickness on inorganic aerosol. Erin McDuffie and I agree that this fix should be included in the next model version. This bug affects version 12.6 only.

We expect this correction will decrease gamma(N2O5) in organic-rich environments (e.g. continental boundary layer) resulting in somewhat greater NOx and O3 and lower NIT. 

I submitted a pull request.

**Comment by yantosca** [comment]
Thanks Chris & Erin.  We will put this into 12.8.0, as it will need to be benchmarked.

**Comment by cdholmes** [comment]
Has 12.7 already been benchmarked? If not, could we slip this in with the other heterogeneous chemistry fix already in 12.7?

Chris

**Comment by msulprizio** [comment]
@cdholmes I also think this makes sense to include in 12.7.0 with the other het fixes. Benchmarking for that version will start later this week or early next week.

**Comment by msulprizio** [comment]
This fix is now resolved in PR https://github.com/geoschem/geos-chem/pull/162 and will be included in 12.7.0.
