### ISSUE TITLE
[BUG/ISSUE] GFAS biomass burning Methanol emissions not included by default 

### ISSUE THREAD

**Issue by Twize** [geoschem/geos-chem#1631]
## Describe the bug:
Methanol is a species which is included in the GFASv1.2 biomass burning inventory, but by default it is not included in the GFAS section of HEMCO_Config.rc. This affects both GEOS-Chem classic and GCHP v13 (and I assume HEMCO standalone). I have not checked in GC v14 yet. 

### Expected behavior: ###
The GFAS section of HEMCO_Config.rc should include the following line:

`0 GFAS_CH3OH $ROOT/GFAS/v2018-09/$YYYY/GFAS_$YYYY$MM.nc ch3ohfire     2003-2021/1-12/1-31/0 C xyL=1:scal300 kg/m2/s MOH  75     5 3`

### Actual behavior: ###
The aforementioned line is absent in the default version of HEMCO_Config.rc, so no methanol emissions are emitted from biomass burning when GFAS is turned on. Adding the line solves the issue, but it should likely be included by default.

### Your HEMCO version and runtime environment:

- GEOS-Chem version: v13.3.2 (Classic and GCHP)
 - HEMCO version: 3.0.0

**Comment by yantosca** [comment]
On second thought because this is a zero-diff update (as it won't affect the benchmarks, which use GFED), we can try to add this to 14.1.1 instead of 14.2.0.

**Comment by Twize** [comment]
> On second thought because this is a zero-diff update (as it won't affect the benchmarks, which use GFED), we can try to add this to 14.1.1 instead of 14.2.0.

Ah gotcha, seems like it should be a quick fix hopefully 🙂 

As a side-note, I was wondering approximately how far out v14.1.1 is from release? I'm hoping to make use of all of the fixes for GFAS in my GCHP simulations.

**Comment by yantosca** [comment]
We can close this issue as PR #1632 has been merged into the 14.1.1 development stream.

**Comment by Twize** [comment]
Hi @yantosca, not sure if I should make a new issue since this is a relatively quick fix, but it seems that the entry for `GFAS_CH3OH` was not added to ExtData.rc, which will likely cause users to encounter an 'unfulfilled import' HEMCO error in when using GCHP from if they switch on GFAS and uncomment all of the GFAS-related lines in ExtData.rc. 

ExtData.rc should contain the following line: 
`GFAS_CH3OH kg/m2/s N Y F%y4-%m2-%d2T00:00:00 none none ch3ohfire     ./HcoDir/GFAS/v2018-09/%y4/GFAS_%y4%m2.nc`
