### ISSUE TITLE
[FEATURE REQUEST] Update GFED4 emissions through Oct 2022

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#1634]
@mkelp has processed the GFED4 emissions from 2020 up through October 2022 (the latest date currently available). The emissions presently in `ExtData/HEMCO/GFED4/v2022-11` only go through 2019.

**Comment by LukeAParsons** [comment]
Good morning! I was about to ask about this as we are trying to run a simulation Jan 2018 through Dec 2021. Do you have any sense about when the GFED4 emissions data post-2019 will be added? Thank you!

**Comment by LukeAParsons** [comment]
Thanks - will do!

**Comment by yantosca** [comment]
Actually this will have to go into 14.2.0 as it will change benchmark results.  But you can download the data yourself if you need it in the meantime.

**Comment by LukeAParsons** [comment]
@yantosca - where else are the post-2019 data available? I didn't see the post-2019 data on the default WU site (http://geoschemdata.wustl.edu/ExtData/HEMCO/GFED4/v2022-11/)- my apologies for not knowing where else to look (I did a brief google search)- I am new to all of this. thank you!

**Comment by yantosca** [comment]
@LukeAParsons, I don't think the data has yet been uploaded yet to WashU.  Thanks for your patience.

**Comment by LukeAParsons** [comment]
@msulprizio - thank you!

**Comment by msulprizio** [comment]
The pull request (#1709) for this feature has now been merged into the 14.2.0 development branch.
