### ISSUE TITLE
[QUESTION] Nested grid simulation negative concentration error

### ISSUE THREAD

**Issue by tessac2** [geoschem/geos-chem#1635]
### Ask a question about GEOS-Chem:
Hello, I have been running GEOS-Chem version 13.2.1 nested grid simulation. Before starting the nested grid simulation, I ran at 4x5 resolution for the years 2018-2020. I want to run the nested grid simulation for 2019 over North America at 0.25x0.3125 resolution. I was able to run from June 1 through October 24 at 2 week increments. However, on October 24 the run stops, saying that there is a negative concentration for SO2 and the error was encountered in "D0_Tend" and "Do_Mixing". I tried recompiling and running with the compiler debug flags, following the solution outlined in #712 & #1081 but that did not seem to solve the issue. I was wondering if you had any suggestions on what to try next?

<img width="677" alt="image" src="https://user-images.githubusercontent.com/70339432/216180180-9819b11d-764e-4358-a156-30639b50cf93.png">

**Comment by yantosca** [comment]
Thanks for writing @tessac2.  One thing you can try is to increase the size of the nested-grid transport buffer zone as described in this issue: https://github.com/geoschem/geos-chem/discussions/875#discussioncomment-1415092.

I think there have also been some fixes added since 13.2.1.  Another thing you can do is just to zero out the negative concentrations if they occur.

**Comment by yantosca** [comment]
@tessac2: I wonder also if SO2 is getting titrated out due to wet deposition or chemistry.  You could also try some short simulations turning those operations off to see if you don't get the negatives.

**Comment by tessac2** [comment]
Thanks Bob! I tried increasing the size of the nested-grid transport buffer zone and got the same error message, so I will try the other solutions you presented next!

**Comment by tessac2** [comment]
Hi Bob, I was wondering how I would zero out the negative concentrations if they were to occur, or if there is a previous GitHub that directs on how to do this? Similarly for turning off the wet deposition. My worry with that is that there are multiple grid boxes with the negative concentration at different vertical levels

[GC.log.20191016_1101.txt](https://github.com/geoschem/geos-chem/files/10671481/GC.log.20191016_1101.txt)

**Comment by yantosca** [comment]
Hi Tessa.  You could comment out the error code and add an IF statement here in mixing_mod:

```F90
#else

                IF ( ( N /= id_CH4_SAB ) .and. ( N /= id_CO2 ) ) THEN

                 ! KLUDGE: skip the warning message for CH4_SAB, which can be
                 ! negative (it's a soil absorption flux).  The TagCH4
                 ! simulation is not used regularly as of Feb 2021 -- fix this
                 ! later if need by. (bmy, 2/25/21)
!                 Print*, 'WARNING: Negative concentration for species ',     &
!                          TRIM( SpcInfo%Name), ' at (I,J,L) = ', I, J, L
!                 ErrorMsg = 'Negative species concentations encountered.' // &
!                            ' This may be fixed by increasing the'        // &
!                            ' background concentration or by shortening'  // &
!                            ' the transport time step.'
!                 RC = GC_FAILURE
            
                  ! Zero out negative values
                  IF ( State_Chm%Species(I,J,L,N) < 0 ) THEN
                      State_Chm%Species(I,J,L,N) = 0.0_fp
                ENDIF
#endif
```
That should prevent negatives from happening.  Let me know if that works.

**Comment by zhifeng1310** [comment]
Hi yantosca, I am a graduate student of Beihang, in China. I am currently running an one-hour short simulation of CO2 on Amazon server, and there is a simular error in my program. According to issues I have modified time step and mixing_mod.F90, and can't solve this error. Could you tell me the solution in detail? And could you please give a tutorial to simulate CO2 or CH4?  Thank you very much. 

My GCClassic version is 14.0.1 .
 WARNING: Negative concentration for species CO2 at (I,J,L) =           40          44           1
===============================================================================
GEOS-Chem ERROR:
 -> at DO_TEND (in module GeosCore/mixing_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem ERROR: Error encountred in "DO_TEND"!
 -> at DO_MIXING (in module GeosCore/mixing_mod.F90)
===============================================================================

===============================================================================
GEOS-CHEM ERROR: Error encountered in "Do_Mixing"!
STOP at  -> at GEOS-Chem (in GeosCore/main.F90)
===============================================================================
     - CLEANUP: deallocating arrays now...

-------------------------------------------------------------------------------
HEMCO 3.0.0 FINISHED.
Warnings (level 3 or lower):    119
-------------------------------------------------------------------------------

**Comment by tessac2** [comment]
@yantosca Sorry I forgot to follow up--that fix you suggested helped! Thank you!

**Comment by tessac2** [comment]
@yantosca Hello! I have been able to run GEOS-Chem with the amended mixing_mod to 0 out negative concentrations. However, I am now running into an issue on April 9, 2020 (so almost 6 months after the original issue in October 2019) where there is now an issue with the wetdep. I was wondering if this could be related to the 0s--it seems like the day before the simulation stopped running that there were a lot 0s.  

<img width="746" alt="image" src="https://user-images.githubusercontent.com/70339432/229684277-2c429dd8-7915-4537-b470-dc4cbcde1909.png">
[GC.log.20200401_0416.txt](https://github.com/geoschem/geos-chem/files/11144544/GC.log.20200401_0416.txt)

**Comment by Liushcsj** [comment]
> [@yantosca](https://github.com/yantosca) Hello! I have been able to run GEOS-Chem with the amended mixing_mod to 0 out negative concentrations. However, I am now running into an issue on April 9, 2020 (so almost 6 months after the original issue in October 2019) where there is now an issue with the wetdep. I was wondering if this could be related to the 0s--it seems like the day before the simulation stopped running that there were a lot 0s.
> 
> <img alt="image" width="746" src="https://user-images.githubusercontent.com/70339432/229684277-2c429dd8-7915-4537-b470-dc4cbcde1909.png">
> 
> [GC.log.20200401_0416.txt](https://github.com/geoschem/geos-chem/files/11144574/GC.log.20200401_0416.txt)

Hello, I also encountered the same issue as shown in the picture. Have you resolved this problem?

**Comment by tessac2** [comment]
@Liushcsj I found out that it was an issue with GEOS-FP meteorology inventory that started in 2020 (I think the convection scheme changed which led to errors in GEOS-Chem). I changed to MERRA-2 and started using version 14.3.1 since I was doing a new run and it was most recent version at the time. I have not had an issue since. I am not sure if the issue with GEOS-FP has been resolved for 2020 onward.

**Comment by Liushcsj** [comment]
> [@Liushcsj](https://github.com/Liushcsj) I found out that it was an issue with GEOS-FP meteorology inventory that started in 2020 (I think the convection scheme changed which led to errors in GEOS-Chem). I changed to MERRA-2 and started using version 14.3.1 since I was doing a new run and it was most recent version at the time. I have not had an issue since. I am not sure if the issue with GEOS-FP has been resolved for 2020 onward.

My issue does not seem to originate from the meteorological inventory, as I am also using MERRA-2. I resolved the problem by reducing the time steps to 300/600, but this has doubled the simulation time.
