### ISSUE TITLE
[QUESTION] WUSTL server not responding.

### ISSUE THREAD

**Issue by gopikrishnangs44** [geoschem/geos-chem#1639]
I am trying to download the input data from geoschem.wustl.edu

I am facing very slow download speed from FTP. Mostly the download stops in between while using wget to download the data.
![Screenshot from 2023-02-06 22-27-52](https://user-images.githubusercontent.com/59282012/217035328-48253c2f-cfe7-4df8-a196-296a9e67078c.png)

**Comment by msulprizio** [comment]
@SaptSinha @Jourdan-He Can either of you confirm the status of the WashU site?

**Comment by SaptSinha** [comment]
I just checked the ExtData path (http://geoschemdata.wustl.edu/ExtData/) and tried test downloading this file: http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_BIOVOC/v2019-10/0.5x0.625/2019/01/biovoc_05.20190119.nc

It is working from my end. It could be an issue with a VPN/off-campus setting on the user's end.

**Comment by gopikrishnangs44** [comment]
@SaptSinha 
I will contact the systems manager here in my institute and let you know. 
Also, will the download stop once started?

**Comment by SaptSinha** [comment]
@gopikrishnangs44
Ideally, the download process should not terminate in between. Besides the VPN settings, you might also want to check if there are any other issues with a particular firewall setting that might be interrupting the process.

**Comment by gopikrishnangs44** [comment]
Dear @SaptSinha @msulprizio 

This issue is from the internal systems management. Thank you for the timely response.

**Comment by gopikrishnangs44** [comment]
@SaptSinha some files do download faster, but some do not.

For eg, the AmSTE and AmSTC files have a good download speed, whereas A3dyn files are too slow

**Comment by SaptSinha** [comment]
Hello @gopikrishnangs44, the A3dyn files are significantly larger than the AmSTE and AmSTC files, so the overall download time for the A3dyn files will be more than the others. However, the download speed should typically remain consistent for all these files as the nature or structure of them should not affect it.
