### ISSUE TITLE
[BUG/ISSUE] Several reactions in fullchem.eqn are using GCARR_abc when they should use GCARR_ac

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#1641]
### What institution are you from?
Harvard University 

### Description of the problem
I noticed several of the chemistry updates added to fullchem.eqn after GEOS-Chem 13.0.0 use the `GCARR_abc` function when they should use `GCARR_ac` because the B term is zero. From fullchem.eqn:

```
// (3) To avoid useless CPU cycles, we have introduced new rate law functions
//     that skip computing Arrhenius terms (and other terms) that would
//     evaluate to 1.  The Arrhenius terms that are passed to the function
//     are in most cases now noted in the function name (e.g. GCARR_abc takes
//     Arrhenius A, B, C parameters but GCARR_ac only passes A and C
//     parameters because B=0 and the (300/T)*B would evaluate to 1).
//     This should be much more computationally efficient, as these functions
//     are called (sometimes multiple times) for each grid box where we
//     perform chemistry.
//        -- Bob Yantosca (25 Jan 2020)
```

The reactions that can be modified to use `GCARR_ac` can mainly be found in these lines:

https://github.com/geoschem/geos-chem/blob/205995a40535e8d43dffc3d436bf640880ec4823/KPP/fullchem/fullchem.eqn#L1386-L1483

### GEOS-Chem version
GEOS-Chem 14.1.0

**Comment by yantosca** [comment]
PR #1717 has now been merged into the 14.4.0 development branch.  We can now close out this issue.
