### ISSUE TITLE
[BUG/ISSUE] Restore vertical allocation of CEDS emissions

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#1646]
@1Dandan wrote:

>I noticed there was a github feature request (https://github.com/geoschem/HEMCO/issues/46) about the vertical allocation of energy, non-solvent industry, and ship emissions. When I browse the issue, it looks like it was implemented in GEOS-Chem v13.1 for CEDS_GBD-MAPS as suggested, but when I check versions of 13.2 and 13.4 using CEDSv2 as global emission inputs, the feature of vertical allocation is deprecated for all energy, industry and ship emissions by default.

**Comment by msulprizio** [comment]
@1Dandan @barronh This is indeed a bug. When we updated to CEDSv2 the scale factors applying the vertical allocation of those emissions were inadvertently dropped. We can restore them in 14.2.0.

**Comment by msulprizio** [comment]
The pull requests (#1712 and #1730) resolving this issue have now been merged into the 14.2.0 development branch.

**Comment by barronh** [comment]
You rock!
