### ISSUE TITLE
[QUESTION]How to convert ozone concentration unit dry mixing ratio  to number density?

### ISSUE THREAD

**Issue by Aydr199406** [geoschem/geos-chem#1654]
In GEOS-Chem 12.9.3, the results of ozone concentration unit are “mol mol-1 dry”. I want to save the concentration unit of ozone as “molecules/cm3”. How can I make that happen in GEOS-Chem 12.9.3?

Thank you.

**Comment by lizziel** [comment]
Hi @Aydr199406, we are no longer supporting GEOS-Chem 12.9.3. Starting in version 14.1.0 you have the option of outputting as either mol/mol (SpeciesConcVV_*) or molecules/cm3 (SpeciesConcMND_*).

If you want to stick with 12.9.3 then you can look at the unit conversions in GEOS-Chem file `GeosUtil/unitconv_mod.F90` to find equations converting between mol/mol and molecules/cm3. You would want to convert at the place where `State_Diag%SpeciesConc` is set, and also change the units string of the `SpeciesConc` metadata in `Headers/state_diag_mod.F90`. 

NOTE: We are now asking users to identify themselves and their institutions when requesting help. Please do this in the future. Thanks!
