### ISSUE TITLE
[QUESTION]About "configuration files"

### ISSUE THREAD

**Issue by forgetmenot9911** [geoschem/geos-chem#1659]
### Ask a question about GEOS-Chem:
Hello! If there are no configuration files (like `HEMCO_Config.rc` or `geoschem_config.yml`) in my new run directory, does it mean that I should manually copy one from `~/GCClassic/src/GEOS-Chem/run/GCClassic/xxx.templates` to this run directory? Or is it just because I may have operational errors. Thanks~

**Comment by capelson** [comment]
Hi. According to guides https://geos-chem.readthedocs.io/en/stable/ this files automatically will be created after successful compilation using CMake and make.

**Comment by yantosca** [comment]
Thanks for writing @forgetmenot9911.  If you follow [these instructions](https://geos-chem.readthedocs.io/en/stable/gcc-guide/02-build/create-rundir.html), the run directory will be created with all proper configuration files.

NOTE: We are now asking users to identify themselves and their institutions when requesting help. Please do this in the future. Thanks!

**Comment by forgetmenot9911** [comment]
Hi, @yantosca. Thanks for helping. Next time I have any questions, I will pay attention to identifying myself. 
Thanks!
