### ISSUE TITLE
[BUG/ISSUE] Dryrun lightning NOx emission error in 14.1.0

### ISSUE THREAD

**Issue by eamarais** [geoschem/geos-chem#1661]
My group at UCL has started using version 14.1.0. We noticed that it's not possible to perform a dryrun without turning off lightning NOx (changing "103 LightNOx" from "on" to "off"), presumably because the (((LightNOx))) field is no longer in the HEMCO_Config.rc file. If we don't turn off lightning we get an error that the relevant FLASH_CTH_* file could not be found.

Are the offilne_lightning files read in elsewhere in the model? And if so, is there a way to run a dryrun to identify which lightning NOx fields need to be downloaded from the wustl repo?

Specific details about our simulation: 4x5, fullchem, GEOS-FP (as we plan to also conduct a nested simulation at 0.25x0.3125).

**Comment by yantosca** [comment]
Thanks @eamarais.  We will take a look at this.

**Comment by yantosca** [comment]
Thanks @eamarais for bringing this up.  Is this for the fullchem simulation or one of the specialty simulations?

**Comment by eamarais** [comment]
Thanks for looking into this. It's for the fullchem simulation. A question you had that appeared in my email, but doesn't appear in this thread.
