### ISSUE TITLE
[BUG/ISSUE] Downloading inputs from WashU Globus endpoint

### ISSUE THREAD

**Issue by jgeddes85** [geoschem/geos-chem#1664]
### What institution are you from?
Boston University

### Description of the problem
Yesterday I was able to successfully transfer files from the WashU GEOS-Chem input data repository to our cluster at Boston University using Globus endpoints. However, today when I try to proceed with a new file transfer request, I am getting permission denied errors:

>   Denied by endpoint, Command Failed: Error (list)
>   Endpoint: GEOS-Chem Data (WashU) (438de6bc-e680-11eb-884a-aba19178789c)
>   Server: dtn1.ris.wustl.edu:2811
>   Command: MLST ~/
>   Message: Fatal FTP Response
>   Details: 550-GlobusError: v=1 c=PERMISSION_DENIED
>   550-GridFTP-Errno: 13
>   550-GridFTP-Reason: System error in stat
>   550-GridFTP-Error-String: Permission denied
>   550 End.  

Is an issue on my end? (I'm able to access the GEOS-Chem data at the Harvard FAS RC Holyoke endpoint.)

Thanks for any help!

Jeff

**Comment by jgeddes85** [comment]
Seems like it was probably something temporary. I appear to be able to access the Wash U endpoint on Globus again. I'm OK with marking this as resolved, but cannot explain what the issue was.

**Comment by SaptSinha** [comment]
Hello @jgeddes85, thank you for the update. The "PERMISSION_DENIED" error is usually encountered when you have multiple logins with different Universities to Globus and there is a mismatch in credentials.

I will close this issue for now. If you encounter this error again, you might find this [section](https://docs.globus.org/how-to/gcp-troubleshooting-guide/#troubleshooting_problems_accessing_a_file_directory_or_removable_drive) from the globus troubleshooting guide helpful.
