### ISSUE TITLE
[QUESTION] Can GEOS-Chem be started using a restart file that has a different vertical resolution?

### ISSUE THREAD

**Issue by bsuther** [geoschem/geos-chem#1667]
### Ask a question about GEOS-Chem:
Hello, can GEOS-Chem be started using a restart file that has a different vertical resolution from the run?
I was reading in #911 that for full chemistry runs, spinup can be done at 4x5 resolution. When I try to start my 2x2.5 run using a Restart file from my 4x5 spin up run it crashes after opening the restart file and does not give any error message. The end of my .log file just says 

> HEMCO: Opening ./Restarts/GEOSChem.Restart.20101225_0000z.nc4

I am wondering if the issue is because the restart has 47 vertical levels and I am trying to do the 2x2.5 run with 72 vertical levels. Could this be the problem? Or is there something else (like manual regridding) that you have to do if you want to use a coarser grid run to spin up a finer grid one?

Thank you,
Bethany (NCSU)

**Comment by yantosca** [comment]
Hi @bsuther, thanks for writing.  HEMCO can regrid data from 47L to 72L, so that shouldn't be the problem.  Could you attach the full log file and geoschem_config.yml/HEMCO_Config.rc etc files?  We can take a look.

**Comment by yantosca** [comment]
Another thing is that if you have species that are contained in your 2x25 run that are not in the 4x5 restart file, the default behavior is to stop the run.  This is controlled by the HEMCO time cycle flag `EFYO`.  Changing that to `CYS` will allow species that are not in the restart file to be set to default background values (like 1e-20).   Seehttps://geos-chem.readthedocs.io/en/stable/gcc-guide/04-data/restart-files-gc.html.

**Comment by bsuther** [comment]
Thank you for your help on this @yantosca. I have attached the log files. I thought that if the restart did not have the necessary species it usually gives you an error that indicates which species it could not find. If it were the case that it was caused by a missing species, but does not give an error to indicate which species, how would I determine what species to edit in HEMCO? Thanks.
