### ISSUE TITLE
[QUESTION] Rerunning a simulation to get different diagnostic collections?

### ISSUE THREAD

**Issue by TylerElgiar** [geoschem/geos-chem#1668]
### Ask a question about GEOS-Chem:

Hello, my name is Tyler Elgiar, my institution is Utah State University

I ran three different Hg simulations, changing reaction rates for different mechanisms in the model. I only allowed "SpeciesConc" and "StateMet" for the output in the HISTORY.rc file. I would like to rerun the models to get some different output files (e.g., DryDep). Do I need to change the mechanism again and recompile the model for each run? Or can I just rerun the model using restart files specific to each modified run?

Thanks!

**Comment by yantosca** [comment]
Thanks for writing @TylerElgiar.

If you have created a separate run directory for each Hg simulation, then you can do the following in each run directory

```console
./archiveRun.sh backup_files  # Saves the current run directory to a folder called `backup_files`
cp -R Restarts backup_files   # Also preserve the Restarts file folder (if there is one)
./cleanRunDir.sh              # Remove existing diagnostics & log files
```
Then edit the `HISTORY.rc` file to add your extra collections and rerun the simulation.  Your previous diagnostic files will be in `backup_files/OutputDir` and your new diagnostic files will be in `OutputDir`.

**Comment by yantosca** [comment]
Also if you are using an older version than 14.0.0, then you will manually have to copy restart files to the `backup_files` folder.

**Comment by TylerElgiar** [comment]
Perfect, thanks for the help!

-Tyler
     On Thursday, February 23, 2023, 02:23:21 PM MST, Bob Yantosca ***@***.***> wrote:  
 
 


Also if you are using an older version than 14.0.0, then you will manually have to copy restart files to the backup_files folder.

**Comment by yantosca** [comment]
No problem!  I'll keep this issue open until you are sure that everything worked OK.  Then feel free to close it.
