### ISSUE TITLE
[QUESTION]Does GEOSChem convert the units of Oxidant fields read via HEMCO automatically ?

### ISSUE THREAD

**Issue by ymfu2021** [geoschem/geos-chem#1670]
### Ask a question about GEOS-Chem:
Hi! I'm using  standard GEOS-Chem 12.8.0 to do some simulation about Hg. Recently, I try to add few oxidant dields through HEMCO_Config.rc while i find out their units were different from other oxides already there. 

FOR EXAMPLE:
O3 is original with unit "molec/cm3", and X is new added with unit "mol/mol dry". here are my codes:

* GLOBAL_O3        SpeciesConc.nc4                                                                       O3                       2016/1-12/1/0 C xyz 1  * - 1 1
* GLOBAL_X        ./GEOSChem.SpeciesConc.2014$MM01_0000z.nc4                    SpeciesConc_I     2014/1-12/1/0 C xyz v/v  * - 1 1

I'd like to know if geoschem will convert units of X from "mol/mol dry" to  "molec/cm3" automatically, or I need to do it by myself sinceI noticed a function called"Convert_Spc_Units" in "mercury_mod.F":
 
       ! Get pointers to fields read via HEMCO
       CALL Set_HCOPointers ( Input_Opt, State_Chm, State_Met,State_Grid, RC )
    !======================================================================
    ! Convert species to [molec/cm3] (ewl, 8/16/16)
    !======================================================================
    CALL Convert_Spc_Units( Input_Opt, State_Chm, State_Grid, State_Met, &
                            'molec/cm3', RC, OrigUnit=OrigUnit )
    IF ( RC /= GC_SUCCESS ) THEN
       ErrMsg = 'Unit conversion error!'
       CALL GC_Error( ErrMsg, RC, 'mercury_mod.F90')
       RETURN
    ENDIF
-----------------------------
Besides, my nc files of 'GLOBAL_X' are listed as 12 files in one folder instead of 1 files whose time dimension are 12, Did I write the statement right ?

**Comment by ymfu2021** [comment]
@yantosca

**Comment by yantosca** [comment]
Thanks for writing @ymfu2021.  I believe that oxidant fields do not have units converted when being read in via HEMCO.  In GEOS-Chem 13 and later we have disabled all implicit unit conversions in HEMCO to reduce confusion.  Unit conversions for emissions are applied via scale factors in HEMCO_Config.rc,

Also note, with the release of GEOS-Chem 14.1.0, we are no longer officially supporting GEOS-Chem 12 versions.

NOTE: We are now asking users to identify themselves and their institutions when requesting help. Please do this in the future. Thanks!

**Comment by ymfu2021** [comment]
Thanks for your reply
