### ISSUE TITLE
[BUG/ISSUE] Small bug fix in gc_grid_mod.F90

### ISSUE THREAD

**Issue by olivian13** [geoschem/geos-chem#1675]
Hi!

My name is Olivia Norman (MIT).

I ran into an issue with the planeflight diagnostic reporting that the point was out of the nested window when it wasn't.

Simple fix though! In GeosUtil/gc_grid_mod.F90, line 983 should be changed from:

`IF ( TLAT < 1 .or. TLAT > State_Grid%NX ) THEN`

to 

`IF ( TLAT < 1 .or. TLAT > State_Grid%NY ) THEN`

Best,
Olivia

**Comment by yantosca** [comment]
Hi @olivian13, thanks for writing,  We are making this fix in GEOS-Chem 14.1.1 which will ship soon.  See PR #1663.  In the meantime go ahead and make the fix in your code.

**Comment by yantosca** [comment]
@olivian13, I'll close out this issue but do feel free to create another issue if you are still having problems.  We should have 14.1.1 out soon (this version will have several fixes for bugs and other technical issues).
