### ISSUE TITLE
GC14.1.1 compilation error after KPP adds species

### ISSUE THREAD

**Issue by ximuzi0709** [geoschem/geos-chem#1687]
### Name and Institution (Required)

Name: Li Yali
Institution: Southern University of Science and Technology

### Description of your issue or question
    
When using version 14.1.1 of GEOS-Chem, and adding species using KPP, I ran into a problem compiling. After I finish adding species, when I recompile in the [build] directory, I get the following error:
```console
[100%] Linking Fortran executable ../bin/gcclassic
GEOS-Chem/GeosCore/libGeosCore.a(fullchem_mod.F90.o): In function `fullchem_mod_mp_do_fullchem_':
fullchem_mod.F90:(.text+0x65c3): undefined reference to `fullchem_autoreducefuncs_mp_fullchem_ar_keephalogensactive_'
fullchem_mod.F90:(.text+0x8027): undefined reference to `fullchem_autoreducefuncs_mp_fullchem_ar_setkeepactive_'
fullchem_mod.F90:(.text+0x917e): undefined reference to `fullchem_autoreducefuncs_mp_fullchem_ar_setintegratoroptions_'
fullchem_mod.F90:(.text+0xe493): undefined reference to `fullchem_autoreducefuncs_mp_fullchem_ar_updatekppdiags_'
GEOS-Chem/GeosCore/libGeosCore.a(carbon_gases_mod.F90.o): In function `carbon_gases_mod_mp_chem_carbon_gases_':
carbon_gases_mod.F90:(.text+0x60ec): undefined reference to `carbon_funcs_mp_carbon_convertkgtomoleccm3_'
carbon_gases_mod.F90:(.text+0x62ee): undefined reference to `carbon_funcs_mp_carbon_computerateconstants_'
carbon_gases_mod.F90:(.text+0x6720): undefined reference to `carbon_funcs_mp_carbon_convertmoleccm3tokg_'
carbon_gases_mod.F90:(.text+0x7064): undefined reference to `carbon_funcs_mp_carbon_get_co2fromoh_flux_'
carbon_gases_mod.F90:(.text+0x7124): undefined reference to `carbon_funcs_mp_carbon_get_cofromnmvoc_flux_'
carbon_gases_mod.F90:(.text+0x719e): undefined reference to `carbon_funcs_mp_carbon_get_cofromch4_flux_'
make[2]: *** [bin/gcclassic] Error 1
make[1]: *** [src/CMakeFiles/gcclassic.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by yantosca** [comment]
Thanks for writing @ximuzi0709.  Which version of KPP did you use to rebuild the mechanism?  (When you generate the Fortran code with KPP, you should see a message such as `This is KPP-X.Y.Z`, where `X.Y.Z` is the version number.

You will need at least KPP 3.0.0 for GEOS-Chem 14.1.1.  For more info, please see:
- https://kpp.readthedocs.io
- [Update chemical mechanisms with KPP](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/using-kpp-with-gc.html)

**Comment by yantosca** [comment]
Glad to hear it's working @ximuzi0709!  I'll close out this issue.
