### ISSUE TITLE
meteorology for pre-2014 nested grid NA 0.25x0.3125 simulation 

### ISSUE THREAD

**Issue by bsuther** [geoschem/geos-chem#1688]
### Name and Institution (Required)

Name: Bethany Sutherland
Institution: North Carolina State University

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Hello,
Could someone please clarify for me the correct procedure for handling the meteorology fields when conducting a 0.25° x 0.3125° nested grid simulation over North America for time periods prior to 2014? The geos-fp met fields on this grid do not go back that far and the MERRA-2 files are only regridded down to 0.5° x 0.625° so I wanted to confirm what would be the best approach here.

I also asked this question in the comments of #694 as this is closely related to my previous question. However, I was not sure if anyone would be notified/see my new comment since #694 had been previously closed. For future reference so that I can do it correctly next time, would the correct procedure be to ask a follow up question in an old thread when they are related or to start a new one?

Thank you for your help,
Beth

**Comment by yantosca** [comment]
Thanks for writing @bsuther.  I am not sure there is much to do other than to use the MERRA-2 archive, as the GEOS-FP product as we know it started in 2014.

**Comment by bsuther** [comment]
Thanks, I was thinking that might be the answer, but wanted to confirm it would be fine to use the coarser resolution files? I was not sure if that could cause problems.  Do you know of any reasons why using the coarser met fields might be problematic? 

Would the correct steps be to:

1. create a run directory using ./createRunDir.sh and choose the meteorology source as GEOS-FP, and the horizontal resolution as 0.25 x 0.3125
2. modify the METDIR in HEMCO_Config.rc and HEMCO_Config.rc.gmao_metfields to point to the MERRA2 files rather than the GEOS_FP ones.

Am I on the right track here? Can you think of any other necessary modifications which I have not thought of?

Thanks for your guidance!

**Comment by bsuther** [comment]
Okay, thank you for your recommendations. I will try it out. Fingers crossed.
