### ISSUE TITLE
Abstract KPP mechanism history into a changelog

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#1689]
### Name and Institution (Required)

Name: Bob Yantosca
Institution: Harvard + GCST

### Confirm you have reviewed the following documentation

- [x] [Contributing guidelines](https://geos-chem.readthedocs.io/en/stable/reference/CONTRIBUTING.html)

### New GEOS-Chem feature or discussion

In the full-chemistry mechanism KPP equation files (i.e. `KPP/fullchem/fullchem.eqn`, `KPP/custom/custom.eqn`, `KPP/fullchem/aciduptake.eqn`), we repeat the mechanism history information, which is quite long.  I wonder if we should consider abstracting this into a `CHANGELOG__FULLCHEM.md` file that could be kept in the `KPP/fullchem` folder and linked to the other folders.

**Comment by yantosca** [comment]
Here is the permalink to the `KPP/fullchem/fullchem.eqn` file history:

https://github.com/geoschem/geos-chem/blob/4722f288e90291ba904222f4bbe4fc216d17c34a/KPP/fullchem/fullchem.eqn#L10-L173

**Comment by msulprizio** [comment]
The PR associated with this request has now been merged into dev/14.2.0.
