### ISSUE TITLE
[QUESTION] 'FluxHg2HgPfromAirToOcean' in 'MercuryOcean' output file not working

### ISSUE THREAD

**Issue by TylerElgiar** [geoschem/geos-chem#1695]
### Name and Institution (Required)

Name: Tyler Elgiar
Institution: Utah State University

### Confirm you have reviewed the following documentation

- [x ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [ x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

Hello, I am running the Hg simulation with GEOS-Chem version 12.8.0. I have been trying to look at the 'MercuryOcean' output file using GCPy. I am trying to display 'FluxHg2HgPfromAirToOcean' but am only able to display 'FluxHg0fromAirToOcean' and 'FluxHg0fromOceanToAir'. All other parameters in the 'MercuryOcean' file show up pretty much blank (no color on the surface maps). The map will display, but there is no value that shows up except for the two parameters I mentioned. This doesn't seem correct as HgII should be readily deposited to the oceans. I'm not sure if it's an issue with GCPy or how I have the model set up. I imagine it's the latter since GCPy has been working for all other applications I have used it for. Any information is greatly appreciated.

**Comment by yantosca** [comment]
Thanks for writing @TylerElgiar.  The GEOS-Chem 12.8.0 code is no longer supported.  We have an improved Hg in GEOS-Chem 14.1.0 and later versions.  This also includes the updates to Hg0 dry deposition by Feinberg et al 2022.

**Comment by TylerElgiar** [comment]
Okay, that makes sense. I'll try GEOS-Chem verison 14.1.0. Thank you!
