### ISSUE TITLE
Adding product and loss for new species

### ISSUE THREAD

**Issue by HuTuDouZ** [geoschem/geos-chem#1696]
Hi,
I was trying to simulate the production for new species like methanol.
I added PMOH in gckpp.kpp and rebuild kpp. 

But there was an error when I was trying to simulate it.

The log file is following:
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Nf_Def_Var: can not define variable : Prod_MOH

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Code stopped from DO_ERR_OUT (in module NcdfUtil/m_do_err_out.F90) 

This is an error that was encountered in one of the netCDF I/O modules,
which indicates an error in writing to or reading from a netCDF file!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by yantosca** [comment]
Thanks for writing @HuTuDouZ.   We would need some more information to answer your question, such as the version of GEOS-Chem that you are using, the simulation that you are using.  If you could also post the input files and logs to this issue that would be helpful.

You might need to check that your new species is in the `species_database.yml` file.  Also you might need to do a clean build of GEOS-Chem (i.e. remove all files in the build folder and then build GEOS-Chem again.)

NOTE: We are now asking users to identify themselves and their institutions when requesting help. Please do this in the future. Thanks!

**Comment by HuTuDouZ** [comment]
That makes sense. Thanks. I am not quite sure if I use 'Prod_?PRD?                    ' in HISTORIC.rc.  I can run my simulation successfully. But if I use  'Prod_?PRD?                    '
