### ISSUE TITLE
[BUG/ISSUE] HEMCO ERROR: Container not found: GLOBAL_H2, in Hg simulation

### ISSUE THREAD

**Issue by TylerElgiar** [geoschem/geos-chem#1700]
### Name and Institution (Required)

Name: Tyler Elgiar
Institution: Utah State University

### Confirm you have reviewed the following documentation

- [ x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

I am trying to run a Hg simulation using GEOS-Chem version 14.1.0. I keep encountering this error: 

```console
HEMCO ERROR: Container not found: GLOBAL_H2
 --> LOCATION: HCO_GetPtr_3D (hco_emislist_mod.F90)
===============================================================================
GEOS-Chem ERROR: Cannot get pointer from HEMCO! Oxidant data is expected to be 
listed in the HEMCO configuration file. This error occured when trying to get 
field GLOBAL_H2
 -> at Set_HCOPointers (in module GeosCore/mercury_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem ERROR: Error encountered in "Set_HCOPointers"!
 -> at ChemMercury (in GeosCore/mercury_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem ERROR: Error encountered in "ChemMercury"!
 -> at Do_Chemistry  (in module GeosCore/chemistry_mod.F90)
===============================================================================

===============================================================================
GEOS-CHEM ERROR: Error encountered in "Do_Chemistry"!
STOP at  -> at GEOS-Chem (in GeosCore/main.F90)
===============================================================================
     - CLEANUP: deallocating arrays now...
```
From what I have seen in the past, it doesn't look like there was a 'GLOBAL_H2' in the HEMCO_Config.rc files I've used. Any assistance is greatly appreciated. Thanks!

[GC.log](https://github.com/geoschem/geos-chem/files/10981333/GC.log)
[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/10981408/HEMCO_Config.txt)

**Comment by yantosca** [comment]
P.S.  @TylerElgiar... I make this mistake all the time myself :-)

**Comment by TylerElgiar** [comment]
Thank you for your response! I remember seeing that step in the documentation, but must have forgot to implement it when compiling the model again after solving some other issues. The model appears to be running now.
