### ISSUE TITLE
Implement updates to allow unit conversions for all species or per species

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#1701]
### Name and Institution (Required)

Name: Bob Yantosca
Institution: Harvard + GCST

### Confirm you have reviewed the following documentation

- [x] [Contributing guidelines](https://geos-chem.readthedocs.io/en/stable/reference/CONTRIBUTING.html)

### New GEOS-Chem feature or discussion
I have been comparing the performance of the carbon simulation (with KPP) using a single advected CH4 species vs. the traditional CH4 specialty simulation.  One of the areas where the carbon (single CH4) simulation underperforms is in unit conversions.  

In the various routines in `GeosUtil/unitconv_mod.F90`, we convert all units (both advected and KPP/non-advected) upon entry to each operation and then do the inverse unit conversion.  For some operations (e.g. transport, convection, wetdep), we may only need to convert advected species, since the non-advected species are not touched.  This can have a big impact on simulations like single tracer carbon, as there are several KPP-only species that need to be present in the mechanism but only 1 advected species.

I propose adding an optional argument to the unit conversion routines to indicate that only advected species should be considered in unit conversions.

**Comment by lizziel** [comment]
It gets dangerous to have different elements of an array with different units at the same time, which is why we haven't done this. However, it would indeed be a lot better performance to get rid of unnecessary conversions. How about we also replace `State_Chm%Spc_Units` with two new fields, one for advected species units and the other for non-advected species units. Then if things goes haywire at some point we can use that as a sanity check that's it not the units.

**Comment by yantosca** [comment]
Very good idea @lizziel.  I will implement this.

**Comment by yantosca** [comment]
At a recent GCST meeting, we decided that the following aspects would be desirable:

1. To allow the option of doing unit conversions for all species, or for only a subclass of species (e.g. wetdep, drydep, advecteed, etc).
2. To replace string comparisons for units with integer comparisons (and define integer parameters for each unit). This will reduce computational overhead.
3. To create a per-species units metadata field (probably an integer in `State_Chm%Species`)

@yantosca will start on this shortly.

**Comment by yantosca** [comment]
Closed by #2072

**Comment by yantosca** [comment]
NOTE: PR #2072 causes TOMAS simulations to break, due to the internal unit conversions implemented in TOMAS.

**Comment by yantosca** [comment]
PR #2072 has been merged, so we can close out this issue.
