### ISSUE TITLE
Some questions about the steps and understanding of nested simulations.

### ISSUE THREAD

**Issue by cj2262** [geoschem/geos-chem#1704]
### Name and Institution (Required)

Name:jc
Institution:ECNU

### New GEOS-Chem feature or discussion

Hi, I want to do a nested simulation for China. Can you help to see if my steps are accurate？
1. Do a spin-up for the global simulation first and output the restart file.
2. Use the restart file generated in the step 1 to run a global simulation to provide the boundary conditions for the nested simulation.
3. Do a spin-up for the nested simulation and output the restart file.
4. Run a Chinese nested simulation using the boundary conditions generated in step 2 and the restart file generated in step 3.
Does this mean that the model needs to be run a total of four times to do the nested simulations? Are there any steps that can be omitted? Do the configurations and scenarios need to be the same for both global and nested simulations?

Also I would like to ask, does the latitude and longitude range of the global simulation have to be global? Can I set a range myself? For example, if the nested simulation is for China, can I change the range of the global simulation to Asia. Is this feasible or does it affect the accuracy of the results? Similarly, when I select a nested simulation with a custom range, does it mean I can set the latitude and longitude range of the nested simulation by myself?

**Comment by yantosca** [comment]
Also we would recommend breaking up the runs into smaller stages (like a month at a time).  That way if you run into an error, you can restart from the month with the last good restart file.

**Comment by cj2262** [comment]
Thank you for your reply @yantosca, now I understand it more clearly.

But I have a new question, I read in other articles that HEMCO 3.0 contains MEIC emission inventory, but the current ExtData/HEMCO does not seem to have MEIC. Has MEIC been removed from the current download site? 

If so, I would like to ask what is the output VOC mechanism used by GEOS-Chem? I think I should download and use the same mechanism to make MEIC consistent with GEOS-Chem. Besides that, do I need to regrid MEIC?

**Comment by yantosca** [comment]
Thanks for your question @cj2262.  MEIC is not distributed by default with GEOS-Chem since I believe it requires you to obtain permission from the author.  You can feel free to contact the authors of MEIC to ask for permission.

The default mechanism in GEOS-Chem is "fullchem".  This uses the simple SOA scheme.  You could of course also run with the complex (VBS) SOA scheme if you wish.  Please see: https://wiki.geos-chem.org/Carbonaceous_aerosols for more information.

You would not need to regrid MEIC as HEMCO will do the regridding as it reads the data in from disk.

**Comment by JairoVS** [comment]
Hello! I'm very sorry for intruding on your discussion. I am a new Geos-Chem user running the 14.1.1 version. I will run a nested simulation and am trying to figure out how to proceed. I have completed a global simulation (4x5) for generating the boundary conditions, which means I have already created a run directory, compiled, configured, and downloaded the inputs once. If I understand correctly, for my nested simulation, I must first create a new run directory with nested simulation configuration, recompile the source code, configure the simulation, and download the input data using a dry simulation. Is it correct?
The resolution for my nested simulations will be 0.5 x 0.625. I will be running three nested simulations for three different custom domains. Then, I am unsure whether I should repeat the process (new run directory, compile, configure, download inputs) every time I run a nested domain choosing the Custom grid or if I could set it to “Global” and only change the longitude and latitude in the “Grid settings” in the geoschem_congif.yml every time I run one of the domains. I hope I have explained myself well, and I appreciate any insight you can provide about this.

**Comment by cj2262** [comment]
Hi, @JairoVS.

In my understanding, it may not be necessary to create a new run directory for the nested simulation and compile it, but it is more convenient for subsequent operations.

If you already have all the data that may be used in the simulation on your server, there is no need to run a dry simulation.

If you have already downloaded all the data for all the custom domains and the scheme settings are the same for all the different custom domains, you can skip repeating the process and just change the longitude and latitude in the "grid settings" in geoschem_congif.yml, but also remember to change the MET data if it is in a different path, you should also remember to change the root directory of MET.

The above is just my personal opinion.

**Comment by JairoVS** [comment]
Thank you, @cj2262. I did not have all the data, so I had to rerun the dry simulation to download it. The simulation is going well as far. Thank you very much for your guidance!!
