### ISSUE TITLE
Fullchem nested grid integration tests fail due to missing species in boundary conditions

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#1705]
### Name and Institution (Required)

Name: Bob Yantosca
Institution: Harvard + GCST

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question
Integration tests show that nested-grid fullchem simulations will fail because the new Furans species are currently missing from the sample boundary conditions file:
```console
HEMCO ERROR: Cannot find field BC_BUTDI. Please check variable name in the config. file
 
HEMCO ERROR: Error encountered in routine HCOIO_Read!
 
HEMCO ERROR: Error in HCOIO_DATAREAD called from HEMCO ReadList_Fill: BC_BUTDI
 --> LOCATION: ReadList_Fill (HCO_ReadList_Mod.F90)
 
HEMCO ERROR: Error in ReadList_Fill (4) called from HEMCO ReadList_Read
 --> LOCATION: ReadList_Read (HCO_ReadList_Mod.F90)
 Error in ReadList_Read called from hco_run
```
I will work on a fix for this.  Integration tests and parallel tests should also change the `EFY` time cycle flag for GEOS-Chem boundary conditions to `CYS` to allow for the integration tests to proceed.

Tagging @msulprizio

**Comment by msulprizio** [comment]
The corresponding PR for this feature request has been merged into the 14.2.0 development branch.
