### ISSUE TITLE
Full chemical simulations in 2022 could not be performed due to FLASH_CTH_MERRA2 data.

### ISSUE THREAD

**Issue by ximuzi0709** [geoschem/geos-chem#1707]
Name:Yali LI
Institution:Southern University of Science and Technology

Hello! I'm doing a full chemistry simulation for 2022. However, the following issues are encountered：

HEMCO ERROR: Cannot find file for current simulation time: ~/data/ExtData/HEMCO/OFFLINE_LIGHTNING/v2020-03/MERRA2/0001/FLASH_CTH_MERRA2_0.5x0.625_0001_01.nc4 - Cannot get field FLASH_DENS. Please check file na
 me and time (incl. time range flag) in the config. 

I have downloaded the OFFLINE_LIGHTNING data for v2020-03 and it only has 1980-2020 data. I can still do a full chemistry simulation in 2021, but I can't do a full chemistry simulation in 2022. The GEOS-CHEM is v 14.0.2.

**Comment by yantosca** [comment]
Closing out this issue since it is a duplicate.
