### ISSUE TITLE
Add GFED dry matter and scale factor data for 2020 - 2022

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#1708]
### Name and Institution (Required)

Name: Bob Yantosca
Institution: Harvard + GCST

### Confirm you have reviewed the following documentation

- [x] [Contributing guidelines](https://geos-chem.readthedocs.io/en/stable/reference/CONTRIBUTING.html)

### New GEOS-Chem feature or discussion

Several users have requested more recent years of the GFED4 biomass burning data, which currently only goes up to 2019.  

We are currently working on this as an update for GEOS-Chem 14.2.0.

Tagging @dylanbm @eamarais @jaegle for your reference.

**Comment by msulprizio** [comment]
This is a duplicate issue. Please see https://github.com/geoschem/geos-chem/issues/1634 instead.
