### ISSUE TITLE
[BUG/ISSUE] Compute Canada's HEMCO directory is missing DUST_DEAD/v2018-04

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/geos-chem#171]
# Report a GEOS-Chem bug or technical issue
@Jun-Meng, I noticed Compute Canada's HEMCO directory is missing DUST_DEAD/v2018-04.

## Describe the bug
The HEMCO directory on Compute Canada is missing DUST_DEAD/v2018-04. I figured I'd submit an issue because @junmeng is away this week, and I'm not too sure if it was intentionally or accidentally omitted. It's required for default 12.1.0 runs though, so it seems like it should probably be there.

## To Reproduce
See Harvard ftp: http://ftp.as.harvard.edu/gcgrid/data/ExtData/HEMCO/DUST_DEAD/
See Compute Canada ftp: http://geoschemdata.computecanada.ca/ExtData/HEMCO/DUST_DEAD/

## Additional context
I noticed this when I was trying to set up a default 12.1.0 run on compute1 (ExtData on compute1 was downloaded from Compute Canada). It was failing because DUST_DEAD/v2018-04 was missing.

**Comment by Jun-Meng** [comment]
It is on Compute Canada archive now.
