### ISSUE TITLE
Bug in CH4 chemistry for selecting troposphere-stratosphere boundary

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#1714]
### Name and Institution (Required)

Name: Melissa Sulprizio
Institution: Harvard / GCST

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

@toddmooring discovered the CH4 chemistry in global_ch4_mod.F90 is being done throughout both the troposphere and stratosphere, when it is intended to be done only in the troposphere. Archived GMI loss frequencies are then applied above the tropopause. This bug has likely been present since version 13.2.1, when the troposphere-only full-chemistry option was retired. At that time `State_Met%InChemGrid` was modified so that the chemistry grid extends to the stratopause (see commit ea348342).

For more details on the fix and its impact see PR #1710.

This bug may also impact the carbon simulation. @yantosca and I will investigate further.

**Comment by yantosca** [comment]
@msulprizio @toddmooring: This bug would only affect the CH4 specialty simulation but not the carbon simulation.  The routine in which the rate constants are computed uses `State_Met%InTropopause`.

https://github.com/geoschem/geos-chem/blob/4722f288e90291ba904222f4bbe4fc216d17c34a/KPP/carbon/carbon_Funcs.F90#L112-L250
