### ISSUE TITLE
Bad FP A3mstE files for Feb 29, 2020

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#1719]
### Name and Institution (Required)

Name:  Bob Yantosca 
Institution: Harvard + GCST

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question
@ltmurray wrote:
>While QAing the offline FP lightning, I discovered that all A3mstE variables are zero in the last timestamp of the Feb 29, 2020 file.  Since this includes the convective mass fluxes, then we calculated zero CTHs and zero lightning. But it also means we have no convective transport during those three hours in the model.
>
>I’ve found this is at least the global 0.25x0.3125, 2x2.5 and 4x5 files, so it may reflect an error in the native GMAO output files themselves.

**Comment by SaptSinha** [comment]
Hello @ltmurray, pardon me for the delay in responding. I checked the following archives for possible corrupted A3mstE files corresponding to the timestamp of Feb 29, 2020:

http://geoschemdata.wustl.edu/ExtData/GEOS_0.25x0.3125/GEOS_FP/2020/02/
http://geoschemdata.wustl.edu/ExtData/GEOS_2x2.5/GEOS_FP/2020/02/
http://geoschemdata.wustl.edu/ExtData/GEOS_4x5/GEOS_FP/2020/02/
http://geoschemdata.wustl.edu/ExtData/GEOS_4x5/MERRA2/2020/02/
http://geoschemdata.wustl.edu/ExtData/GEOS_2x2.5/MERRA2/2020/02/

I compared the A3mstE file sizes for Feb 29 with that of Feb 27, 28, etc. It appears the following three files might have missing data entries:

[GEOSFP.20200229.A3mstE.025x03125.nc](http://geoschemdata.wustl.edu/ExtData/GEOS_0.25x0.3125/GEOS_FP/2020/02/GEOSFP.20200229.A3mstE.025x03125.nc)
[GEOSFP.20200229.A3mstE.2x25.nc](http://geoschemdata.wustl.edu/ExtData/GEOS_2x2.5/GEOS_FP/2020/02/GEOSFP.20200229.A3mstE.2x25.nc)
[GEOSFP.20200229.A3mstE.4x5.nc](http://geoschemdata.wustl.edu/ExtData/GEOS_4x5/GEOS_FP/2020/02/GEOSFP.20200229.A3mstE.4x5.nc)

Let me know if these are the files that you were referencing earlier. If so, I can reprocess/regrid these files and update the archive.

**Comment by msulprizio** [comment]
@SaptSinha Is this now resolved?

**Comment by SaptSinha** [comment]
Yes, I updated the Feb 2020 GEOSFP repository for all the 29 days in that month as some of the other files had possible missing data entries. The updated A3mstE files can now be accessed from:
http://geoschemdata.wustl.edu/ExtData/GEOS_0.25x0.3125/GEOS_FP/2020/02/
http://geoschemdata.wustl.edu/ExtData/GEOS_2x2.5/GEOS_FP/2020/02/
http://geoschemdata.wustl.edu/ExtData/GEOS_4x5/GEOS_FP/2020/02/

**Comment by ltmurray** [comment]
Thanks. I'll start processing the offline FP lightning emissions now.

**Comment by SaptSinha** [comment]
My guess is that it could have been an issue with the post processing on our end, or a local file system error within the WashU cluster that has corrupted some of our MetFields dataset files in earlier occasions. 

Before updating, I recorded the file sizes of those 3 files just as a reference to compare later. Here they are:

http://geoschemdata.wustl.edu/ExtData/GEOS_0.25x0.3125/GEOS_FP/2020/02/
GEOSFP.20200229.A3mstE.025x03125.nc     2020-09-27 00:07  551M
GEOSFP.20200229.A3mstE.025x03125.nc     2023-05-17 19:45  491M

http://geoschemdata.wustl.edu/ExtData/GEOS_2x2.5/GEOS_FP/2020/02/
GEOSFP.20200229.A3mstE.2x25.nc    2020-10-29 14:49   19M
GEOSFP.20200229.A3mstE.2x25.nc    2023-05-17 19:45   16M

http://geoschemdata.wustl.edu/ExtData/GEOS_4x5/GEOS_FP/2020/02/
GEOSFP.20200229.A3mstE.4x5.nc   2021-10-05 05:00  5.2M
GEOSFP.20200229.A3mstE.4x5.nc   2023-05-17 19:45  4.8M

**Comment by msulprizio** [comment]
Great. I will close out this issue then.
