### ISSUE TITLE
[QUESTION]How may I specify the SpecConc output for a designate tracer?

### ISSUE THREAD

**Issue by evanliu3594** [geoschem/geos-chem#172]
Hello, I have run GEOS-Chem 12.5.0 successfully for a 1-month simulation. When I processing the SpecConc output file I realized that this species concentration output was time-averaged. Then I checked out the [_Overview of History diagnostics_](http://wiki.seas.harvard.edu/geos-chem/index.php/Overview_of_History_diagnostics) for detailed configurations. But I still failed to figure out how to solely configure the hourly O3 output. Should I find the settings in the HISTORY.rc or the input.geos file?

**Comment by msulprizio** [comment]
You may specify hourly O3 output by changing the SpeciesConc collection in HISTORY.rc to:

```
#==============================================================================
# %%%%% THE SpeciesConc COLLECTION %%%%%
#
# GEOS-Chem species concentrations (default = advected species)
#
# Available for all simulations
#==============================================================================
  SpeciesConc.template:       '%y4%m2%d2_%h2%n2z.nc4',
  SpeciesConc.format:         'CFIO',
  SpeciesConc.frequency:      00000000 010000                # Save fields hourly
  SpeciesConc.duration:       00000001 000000                # Save to daily files
  SpeciesConc.mode:           'instantaneous'                # Save instantaneous values
  SpeciesConc.fields:         'SpeciesConc_O3', 'GIGCchem',  # Save only O3, not all
::
```

(You can exclude the text after the `#` symbols above. Those are just my comments indicating the changes to make.)

**Comment by evanliu3594** [comment]
> You may specify hourly O3 output by changing the SpeciesConc collection in HISTORY.rc to:
> 
> ```
> #==============================================================================
> # %%%%% THE SpeciesConc COLLECTION %%%%%
> #
> # GEOS-Chem species concentrations (default = advected species)
> #
> # Available for all simulations
> #==============================================================================
>   SpeciesConc.template:       '%y4%m2%d2_%h2%n2z.nc4',
>   SpeciesConc.format:         'CFIO',
>   SpeciesConc.frequency:      00000000 010000                # Save fields hourly
>   SpeciesConc.duration:       00000001 000000                # Save to daily files
>   SpeciesConc.mode:           'instantaneous'                # Save instantaneous values
>   SpeciesConc.fields:         'SpeciesConc_O3', 'GIGCchem',  # Save only O3, not all
> ::
> ```
> 
> (You can exclude the text after the `#` symbols above. Those are just my comments indicating the changes to make.)

Thank you very much! Now I see that I can directly add direct <spcname> after SpeciesConc_ to get the designate tracer diagnostics.

What if I want to obtain other pollution concentrations at the monthly-average scale simultaneously?

Shall I use **SpeciesConc** collection for the monthly mean concentration of advected species, and use the **SpeciesConcSubset**  collection for hourly concentration of O3? like this :

```
#=================================================
# %%%%% THE SpeciesConc COLLECTION %%%%%
#
# GEOS-Chem species concentrations (default = advected species)
#
# Available for all simulations
#==================================================
SpeciesConc.template:           '%y4%m2%d2_%h2%n2z.nc4',
SpeciesConc.frequency:          00000100 000000,
SpeciesConc.format:             'CFIO',
SpeciesConc.duration:           00000100 000000,
SpeciesConc.mode:               'time-averaged',
SpeciesConc.fields:             'SpeciesConc_?ADV?',  'GIGCchem',

#===================================================
# %%%%% THE SpeciesConcSubset COLLECTION %%%%%
#
# Same as the SpeciesConc collection, but will subset data in the horizontal
# and vertical dimensions so that the netCDF diagnostic files will cover
# a smaller region of the globe.  This can save disk space and memory.
#
# NOTE: This capability will be available in GEOS-Chem "Classic" 12.5.0
# and later versions.
#
# Available for all simulations
#===================================================
SpeciesConcSubset.template:     '%y4%m2%d2_%h2%n2z.nc4',
SpeciesConcSubset.frequency:    00000000 010000,
SpeciesConcSubset.format:       'CFIO',
SpeciesConcSubset.duration:     00000000 010000,
SpeciesConcSubset.mode:         'instantaneous',
SpeciesConcSubset.LON_RANGE:    70.0 140.0,
SpeciesConcSubset.LAT_RANGE:    15.0 55.0,
SpeciesConcSubset.fields:       'SpeciesConc_O3',  'GIGCchem',
::
```
Will that work in GC 12.5.0?

**Comment by lizziel** [comment]
Yes, you can create another collection and output SpeciesConc fields using it. Your implementation is correct except for two problems:

1. Collections must be separated with a line containing '::'. You have it at the end of SpeciesConcSubset but not SpeciesConc. Be sure to add it after the SpeciesConc collection.
2. All collections must be included in the Collections list at the top of HISTORY.rc. Search for where SpeciesConc is declared in the list and add SpeciesConcSubset right after it.

You can add as many collections as you want in this way.

**Comment by evanliu3594** [comment]
> Yes, you can create another collection and output SpeciesConc fields using it. Your implementation is correct except for two problems:
> 
> 1. Collections must be separated with a line containing '::'. You have it at the end of SpeciesConcSubset but not SpeciesConc. Be sure to add it after the SpeciesConc collection.
> 2. All collections must be included in the Collections list at the top of HISTORY.rc. Search for where SpeciesConc is declared in the list and add SpeciesConcSubset right after it.
> 
> You can add as many collections as you want in this way.

Copy that. Thank you for your help!
