### ISSUE TITLE
How to convert unit from mol mol-1 dry to PPb?

### ISSUE THREAD

**Issue by xuexb1230** [geoschem/geos-chem#1722]
Name: Robinson
Institution: Fudan University

### Description of your issue or question
I am a student from Fudan University and started GEOS-Chem simulation several weeks ago. The species concentration in output file is mol/mol dry. How do I convert this unit to PPb? My GEOS-Chem version is 13.3. 

Looking forward to your help！
Thanks!

**Comment by yantosca** [comment]
See: https://acmg.seas.harvard.edu/files/acmg/files/lecture_eps133_chapter_1_0.pptx
