### ISSUE TITLE
This is not a component name that is defined in the encompassing structure.   [WLI]

### ISSUE THREAD

**Issue by Qinchuang2019** [geoschem/geos-chem#1723]
### Name and Institution (Required)

Name:Qin Chuang
Institution:Tsinghua University

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question
Hello, when I compile GCC14.0.0:

/ public/home/sunxy/GCClassic - 14.0.0 / run/test_qin/CodeDir/SRC/administrators - Chem/GeosCore/hco_interface_gc_mod. F90 (2313) : error #6460: This is not a component name that is defined in the encompassing structure.   [WLI]

CALL ExtDat_Set( HcoState, ExtState%WLI, 'LWI', &

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- - ^

/ public/home/sunxy/GCClassic - 14.0.0 / run/test_qin/CodeDir/SRC/administrators - Chem/GeosCore/hco_interface_gc_mod. F90 (2313) : error #6285: There is no matching specific subroutine for this generic subroutine call.   [EXTDAT_SET]

CALL ExtDat_Set( HcoState, ExtState%WLI, 'LWI', &

-- -- -- -- -- -- -- -- - ^

compilation aborted for  / public/home/sunxy/GCClassic - 14.0.0 / run/test_qin/CodeDir/SRC/administrators - Chem/GeosCore/hco_interface_gc_mod. F90 (code 1)

make[2]: *** [src/GEOS-Chem/GeosCore/CMakeFiles/GeosCore.dir/hco_interface_gc_mod.F90.o] Error 1

make[2]: *** Waiting for unfinished jobs....

make[1]: *** [src/GEOS-Chem/GeosCore/CMakeFiles/GeosCore.dir/all] Error 2

make: *** [all] Error 2

module list:
 1) compiler/intel/2021.3.0   4) mathlib/hdf5/intel/1.12.0   
 2) compiler/cmake/3.20.1     5) mathlib/netcdf/intel/4.7.4  
 3) mpi/openmpi/intel/4.0.3  

How can I solve this problem? Thank you very much!

**Comment by lizziel** [comment]
Hi @Qinchuang2019, it looks like maybe HEMCO was not compiled. The paths listed in the error message are strange, such as this:
`/ public/home/sunxy/GCClassic - 14.0.0 / run/test_qin/CodeDir/SRC/administrators - Chem/GeosCore/hco_interface_gc_mod. F90`

Are you following instructions to download and build the model in GCHP ReadTheDocs? The pages for 14.0.0 are [here](https://geos-chem.readthedocs.io/en/14.0.0/). Could you detail the steps you took to download, create a run directory, and build?

**Comment by Qinchuang2019** [comment]
Hello, thank you. I have successfully installed GEOS-CHEM14.1.1(geos-chem-14.1.zip, HEMCO-3.6.2.zip) following the user guide. However, the above error occurs when installing CHEM14.10.0(geos-chem-14.0.0.zip, HEMCO-3.6.0.zip).

**Comment by lizziel** [comment]
Hi @Qinchuang2019, if 14.1.1 works then it is best to go with that version. It is the most recent version and contains bug fixes needed since 14.0.

**Comment by lizziel** [comment]
Could you also specify what part of the user guide is instructing installation via zip files? The recommended way of getting GEOS-Chem is via git clone.

**Comment by yantosca** [comment]
@lizziel: I think it may be the Zip files from the Github release pages.  They are available but that is definitely not the recommended installation method.

**Comment by Qinchuang2019** [comment]
> Could you also specify what part of the user guide is instructing installation via zip files? The recommended way of getting GEOS-Chem is via git clone.
Hello,, thank you.  Because the local server I am using cannot use the git clone command to obtain the geos-chem installation package, I installed it offline by downloading the zip installation package. There may be errors in the downloaded zip file.

**Comment by Qinchuang2019** [comment]
@lizziel 
Hello, thank you. Because the local server I am using cannot use the git clone command to obtain the geos-chem installation package, I installed it offline by downloading the zip installation package. There may be errors in the downloaded zip file.
