### ISSUE TITLE
How does GEOS-Chem run results without calling meteorological data

### ISSUE THREAD

**Issue by yangning-code** [geoschem/geos-chem#1725]
### Name and Institution (Required)

Name:
Institution:

### Confirm you have reviewed the following documentation

- [ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

**Comment by yantosca** [comment]
@yangning-code I am not sure what you mean.  GEOS-Chem needs to input meteorological data in order to run.
