### ISSUE TITLE
[BUG/ISSUE] Doesn't HEMCO read POET_EOH or SHIP inventories?

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/geos-chem#173]
Hi there,

I am running GC 12.5.0 complexSOA_SVPOA simualtion and suddenly found that HEMCO did not read or maybe read but not display POET_EOH inventory. All the model configurations are similar to [those I previously posted](https://github.com/geoschem/geos-chem/issues/146). For convenience, I provide updated necessary files below.

[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/3956276/HEMCO_Config.rc.txt)
[HEMCO_Diagn.rc.txt](https://github.com/geoschem/geos-chem/files/3956277/HEMCO_Diagn.rc.txt)
[HISTORY.rc.txt](https://github.com/geoschem/geos-chem/files/3956278/HISTORY.rc.txt)
[input.geos.txt](https://github.com/geoschem/geos-chem/files/3956279/input.geos.txt)

I run the model for two times with turning on or off POET_EOH and collect corresponding GC log files.
```
    --> POET_EOH               :       true
```
```
    --> POET_EOH               :       false
```

[GC_y.log](https://github.com/geoschem/geos-chem/files/3956283/GC_y.log)
[GC_n.log](https://github.com/geoschem/geos-chem/files/3956284/GC_n.log)

By comparing these two file `diff GC_y.log GC_n.log`, I only found the following difference.
```
12c12
< ===> SIMULATION START TIME: 2019/12/12 13:52 <===
---
> ===> SIMULATION START TIME: 2019/12/12 13:56 <===
2475c2475
< ===> SIMULATION END TIME: 2019/12/12 13:55 <===
---
> ===> SIMULATION END TIME: 2019/12/12 13:58 <===
```

So you see in both cases HEMCO has not read POET_EOH. I wonder whether this is bug or HEMCO did read but not display it?

**Comment by FeiYao-Edinburgh** [comment]
With the identical configurations above, I am also concerned about the SHIP inventories. Within HEMCO_Config.rc, you can see that I have turned on both SHIP and CEDS_SHIP inventories.
```
 112     --> SHIP                   :       true
 113     --> CEDS_SHIP              :       true
```
```
1715 #==============================================================================
1716 # --- Ship emissions ---
1717 #
1718 # ==> CEDS ship emissions are now the default.
1719 # ==> If CEDS_SHIP is turned off above then ARCTAS should be used over ICOADS,
1720 #     CORBETT, and HTAP for SO2 and ICOADS should be used for CO and NO.
1721 # ==> The ship inventory for NEI11 only goes a few km from land, so it isn’t
1722 #     a complete 'ship inventory'. NEI2011_SHIP_* is set to false for now.
1723 # ==> Ship NO emissions are used by PARANOx and the extension number must be
1724 #     adjusted accordingly. If PARANOx is turned off, set the ExtNr back to
1725 #     zero.
1726 #==============================================================================
1727 (((SHIP
1728 0  ARCTAS_SHIP_SO2     $ROOT/ARCTAS_SHIP/v2014-07/ARCTAS_ship.generic.1x1.nc           SO2             2008/1/1/0             C xy kg/m2/s  SO2  11/19        10 1
1729 #0 ICOADS_SHIP_SO2     $ROOT/ICOADS_SHIP/v2014-07/ICOADS.generic.1x1.nc                SO2             2002/1-12/1/0          C xy kg/m2/s  SO2  11/15/60     10 2
1730 #0 CORBETT_SHIP_SO2    $ROOT/CORBETT_SHIP/v2014-07/CORBETT_ship.geos.1x1.nc            SO2_SHIP        1985/1-12/1/0          C xy kg/m2/s  SO2  -            10 3
1731 #0 HTAP_SHIP_SO2       $ROOT/HTAP/v2015-03/EDGAR_HTAP_SO2_SHIPS.generic.01x01.nc       emi_so2         2008-2010/1/1/0        C xy kg/m2/s  SO2  11/29        10 4
1732
1733 0  ICOADS_SHIP_CO      $ROOT/ICOADS_SHIP/v2014-07/ICOADS.generic.1x1.nc                CO              2002/1-12/1/0          C xy kg/m2/s  CO   6/10         10 2
1734 0  ICOADS_SHIP_SOAP    -                                                               -               -                      - -  -        SOAP 6/10/280     10 2
1735 #0 HTAP_SHIP_CO        $ROOT/HTAP/v2015-03/EDGAR_HTAP_CO_SHIPS.generic.01x01.nc        emi_co          2008-2010/1/1/0        C xy kg/m2/s  CO   6/28         10 4
1736 #0 HTAP_SHIP_SOAP      -                                                               -               -                      - -  -        SOAP 6/28/280     10 4
1737
1738 (((CEDS_SHIP
1739 0 CEDS_CO_SHP     $ROOT/CEDS/v2018-08/$YYYY/CO-em-anthro_CMIP_CEDS_$YYYY.nc            CO_shp            1750-2014/1-12/1/0 C xy kg/m2/s CO    26     10 5
1740 0 CEDS_SOAP_SHP   -                                                                    -                 -                  - -  -       SOAP  26/280 10 5

```

I thought there is an including relationship between (((SHIP)))SHIP and (((CEDS_SHIP)))CEDS_SHIP Data collection. I believe this means CEDS_SHIP will only be enabled on condition that SHIP is enabled? But those base emissions at the top of SHIP collection and outside of CEDS_SHIP collection should be enabled anyway? However, by `grep -n ICOADS_SHIP GC_y.log` I got no results. Doee the GC source codes have some special treatment for SHIP inventories?

**Comment by yantosca** [comment]
1. POET EOH has a lower hierarchy (1) than CEDS (5).  This is because POET EOH was added before CEDS became available.  If CEDS is turned off, then the POET EOH should get read.

2. Same idea, all of the other SHIP emissions have lower hierarchy values than CEDS_SHIP.  If you turn off CEDS_SHIP, the the other ship emissions will be added in the following order:

   a. ARCTAS_SHIP has the lowest priority (hier=1)
   b. ICOADS_SHIP is next (hier=2)
   c. CORBETT_SHIP is next (hier=3)
   d. HTAP_SHIP is next (hier=4)
   e. CEDS_SHIP has the highest priority (hier=5)
   
3. Yes, Turning off SHIP will turn off ALL ship emissions.
