### ISSUE TITLE
[QUESTION] Fields assigned to any other extension number will be ignored for emission calculation

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/geos-chem#174]
Hi there,

I read this sentence "Fields assigned to any other extension number will be ignored for emission calculation" on [HEMCO user guide wiki](http://wiki.seas.harvard.edu/geos-chem/index.php/The_HEMCO_User%27s_Guide#Extension_switches). I personally think it might lead to some misunderstanding as I see the following items in a default HEMCO_Diagn.rc file in GC 12.2.1.
```
 23 ###############################################################################
 24 EmisACET_Total     ACET   -1     -1  -1   3   molec/cm2/s   ACET_total_emissions
 25 EmisACET_Anthro    ACET   0      1   -1   3   atomsC/cm2/s  ACET_emissions_from_anthropogenic
 26 EmisACET_BioBurn   ACET   111    -1  -1   2   atomsC/cm2/s  ACET_emissions_from_biomass_burning
 27 EmisACET_Biofuel   ACET   0      2   -1   2   atomsC/cm2/s  ACET_emissions_from_biofuel
 28 EmisACET_Biogenic  ACET   108    -1  -1   2   atomsC/cm2/s  ACET_emissions_from_biogenic_sources
 29 EmisACET_DirectBio ACET   108    -1  -1   2   atomsC/cm2/s  ACET_emissions_from_direct_emissions
 30 EmisACET_MethylBut ACET   108    -1  -1   2   atomsC/cm2/s  ACET_emissions_from_methyl_butenol
 31 EmisACET_Monoterp  ACET   108    -1  -1   2   atomsC/cm2/s  ACET_emissions_from_monoterpenes
```
So you see we can also collect emissions with extension number other than 0. I believe you intended to mean "Fields assigned to any other extension number will be ignored for emission calculation within HEMCO core"? I would be grateful if you could confirm my guess!

BTW, in the HEMCO_Diagn.rc settings above, I saw several variables sharing the same species, cat, and hier. Checking the output HEMCO diagnostics using Python, I did find that they are totally the same. Therefore, I believe the values in a certain HEMCO diagnostic variable are mainly determined by species, cat, and hier?

Thanks in advance!

**Comment by yantosca** [comment]
I have updated the text in the HEMCO manual to be more specific:

>HEMCO expects an extension with extension number zero, denoted the 'base' extension. All emission fields linked to the base extension will be used for automatic emission calculation. Fields assigned to any other extension number will not be inlcuded in the base emissions calculation, but they are still read/regridded by HEMCO (and can be made available readily anywhere in the model code). These data are only read if the corresponding extension is enabled.
