### ISSUE TITLE
[BUG/ISSUE] Unexpected differences in full-chemistry simulation caused by TOMAS updates

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#1742]
### Name and Institution (Required)

Name: Melissa Sulprizio
Institution: Harvard/GCST

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Following the merge of the PRs listed below into dev/14.2.0, we observed differences in GCClassic and GCHP 1-hour full-chemistry benchmark simulations when we expected none.

- https://github.com/geoschem/geos-chem/pull/1378 
- https://github.com/geoschem/geos-chem/pull/1569
- https://github.com/geoschem/HEMCO/pull/164
- https://github.com/geoschem/GCHP/pull/252

Differences are summarized below:

- [GCC_Difference_Summary.txt](https://github.com/geoschem/geos-chem/files/11180438/GCC_Difference_Summary.txt)
- [GCHP_Difference_Summary.txt](https://github.com/geoschem/geos-chem/files/11180437/GCHP_Difference_Summary.txt)

We will revert dev/14.2.0 to before the merge of the TOMAS PRs because we need to better understand these differences.

Tagging @bettycroft @yantosca

**Comment by yantosca** [comment]
@BettyCroft: I think I remember this... it doesn't look like there is a clean way of making the PH2SO4 and PSO4AQ species work as `#FAMILIES`, as I think KPP doesn't have a way of knowing that in those rxns SO4 is aqueous.  I think I remember that is why we proceeded this way.

If we need to keep this setup, then we will have to implement a separate mechanisms for TOMAS (i.e. in its own GEOS-Chem/KPP/tomas subfolder).  Then we would have to compile that with `-DMECH=tomas -DTOMAS=y -DTOMAS_BINS=15 or 30`.  Because this causes changes to the `fullchem` simulation (and the benchmarks), we cannot bring it in as it is now.  Happy to consider alternatives.

**Comment by yantosca** [comment]
Also tagging @TheloniusMonk

**Comment by BettyCroft** [comment]
@yantosca - yes I am remembering this in the same as you are in your previous message. I'm not aware of any alternatives. 

@msl3v helped me with these code development to pass the aqueous sulfate production rates from KPP to TOMAS - and perhaps he can weigh in here regarding if there are any alternatives we should consider. My understanding from our previous discussions was that these dummy species were the best option for pasing the cloud chem production rates to TOMAS..

**Comment by BettyCroft** [comment]
@theloniuspunk, how does the approach of a separate chemical mechanism for TOMAS to you?

**Comment by theloniuspunk** [comment]
I guess this is fine. I worry a bit about how this may affect the TOMAS simulations down the road when the full chem mechanism gets updated. Will these updates now not transfer to the TOMAS simulations?

**Comment by yantosca** [comment]
Thanks @BettyCroft.  We think that we can use this mechanism as-is but it should be defined as a separate mechanism from the fullchem.  We have to be sensitive to not only the numerical differences that are generated w/r/t fullchem. but also adding extra species adds extra memory overhead that can affect how GEOS-Chem works in e.g. the NASA/GEOS model, where memory usage is already at a premium.

NOTE: We are about to freeze 14.2.0 so this might have to be one of the first updates in 14.3.0.

**Comment by BettyCroft** [comment]
@yantosca, would you be able to point out where/how to view the magnitude of the differences?

**Comment by msl3v** [comment]
You can set the dummy species value to a large number before integration, and then subtract the number afterwards and effectively eliminate the impact on integration

**Comment by yantosca** [comment]
Interesting idea @msl3v.

**Comment by BettyCroft** [comment]
Thanks @yantosca and @msl3v, - are these differences low enough to be in the realm of just going with it?

**Comment by msl3v** [comment]
It would be worth performing the test to make sure this is the cause.

**Comment by BettyCroft** [comment]
Hi @yantosca - checking in on this issue - what are your suggestions on how to proceed? Please let me know if you have suggestions on how I might be able to help. Thanks, Betty

**Comment by msulprizio** [comment]
Hi @BettyCroft. The plan is to include the TOMAS updates linked above first thing in 14.3.0 and accept the numerical differences as noise from the solver. However, issue https://github.com/geoschem/geos-chem/issues/1741, which documents the failure of TOMAS simulations in both GCClassic and GCHP, still remains. We are hoping the TOMAS simulation can be fixed in a separate pull request for inclusion in 14.3.0 or soon thereafter, we just don't want the code to diverge too much from the original pull requests.

**Comment by BettyCroft** [comment]
Thanks @msulprizio! That would be great if the TOMAS update for KPP (linked above) can go in 14.3.0. In regard to the other updates for implementation of TOMAS in GCHP and removal of TOMAS' dependency on bpch diagnostics - I agree that we do not want the code to diverge too much from the original pull requests. Please let me know if I can be of help.

**Comment by yantosca** [comment]
I think we can close this issue now that PR #2060 has been merged.
