### ISSUE TITLE
CO2 simulation

### ISSUE THREAD

**Issue by liwenjia12** [geoschem/geos-chem#1744]
### Name and Institution (Required)

Name: wenjialee
Institution: China University of Petroleum-Beijing

### Confirm you have reviewed the following documentation

- [Yes ] [Contributing guidelines](https://geos-chem.readthedocs.io/en/stable/reference/CONTRIBUTING.html)

### New GEOS-Chem feature or discussion

I was doing a CO2 simulation, I want to simulate the concentration of CO2 in 2019, So I just run the simulation from 2014 to 2019 for spin up, then I use the newly-created restart file in 20190101 to begin the silulation at 2019. I do not know if I did this right, I was a greenhand so I look forward to your reply. Thank you!

**Comment by yantosca** [comment]
Thanks for writing @liwenjia12.  Technically that is right.  However, because CO2 is a long-lived species, you may want to make sure that on the Jan 1st of each year you are using an initial condition that is is consistent with observations.  This is because CO2 is long-lived.

**Comment by liwenjia12** [comment]
Thanks for replying, so I want to ask that how can I make sure that the initial condition I use is consitent with observations, if I have to modify the restart file.

**Comment by liwenjia12** [comment]
And I wonder how can I change the restart file
