### ISSUE TITLE
Possible bug in HOBr uptake rate calculation

### ISSUE THREAD

**Issue by viral211** [geoschem/geos-chem#1746]
### Name and Institution (Required)

Name: Viral Shah
Institution: NASA GMAO

### Confirm you have reviewed the following documentation

- [X] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [X] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [X] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [X] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

GEOS-Chem version 14.1

I noticed a possible bug in the following functions that calculate the reaction rates of HOBr with S(IV) in clouds:
https://github.com/geoschem/geos-chem/blob/4722f288e90291ba904222f4bbe4fc216d17c34a/KPP/fullchem/fullchem_RateLawFuncs.F90#L2013-L2082

The functions calculate the reaction rate constant for the reaction: 
HOBr + SO<sub>2</sub> -> HBr + SO<sub>4</sub><sup>2-</sup>.
with a reaction rate (in molec cm-3 s-1 ) as:
R =  k<sup>II</sup> [HOBr] [SO<sub>2</sub>]
The functions assume that HOBr is the limiting reactant. Thus, k<sup>II</sup> is calculated as:
k<sup>II</sup> = k<sup>I</sup> / [SO<sub>2</sub>], 
where k<sup>I</sup> is the first-order loss rate coefficient of HOBr in reactions with HSO<sub>3</sub><sup>-</sup> and SO<sub>3</sub><sup>2-</sup>.
However, the rate is further scaled by the fraction of SO<sub>2</sub> present as HSO<sub>3</sub><sup>-</sup> (or SO<sub>3</sub><sup>2-</sup>), presumably because the actual reactants in the above reaction are HSO<sub>3</sub><sup>-</sup> and SO<sub>3</sub><sup>2-</sup> and not SO<sub>2</sub> (see Lines 2046 and 2080 in the above code snippet). But I don’t think we should be doing this scaling since the reaction rate is calculated assuming that the reaction is HOBr-limited and the concentration of the second reactant doesn't appear in the rate expression. It is implicitly accounted for in the k<sup>I</sup> calculation instead.

### Proposed fix
Delete `* H%HSO3m` on Line 2046 and `* H%SO3mm` on Line 2080.

Fixing this will increase the loss of HOBr (to HBr) and could lower BrOx levels, with a larger effect for simulations that include sea salt aerosol debromination.  
Tagging @beckyalexander. Becky, please correct me if I misunderstood this. Also tagging @msl3v.

**Comment by yantosca** [comment]
Thanks @viral211, we will take a look.  Also tagging @msulprizio and @lizziel.

**Comment by beckyalexander** [comment]
I'm not sure that this is incorrect the way that it is. kIIR1Ltd turns a first-order rate constant into a second-order rate constant by dividing by the reactant that is less likely to be limiting. KPP then simply multiplies the second-order rate constant by the reactant that is not limiting (in this case SO2) and by the reactant that is limiting (HOBr) to get the reaction rate. Multiplying by the fraction of SO2 present as HSO3- or SO32- effectively slows this reaction down, since it is only happening for one of the two S(IV) species. Perhaps there is a better way to do it, but I don't think it should be removed.

**Comment by beckyalexander** [comment]
I agree with Viral's assessment. The first-order rate constant calculated in Gam_HOBr_Cld and Gam_HOCl_Cld already breaks up the reaction rate between HSO3- and SO32-, so there is no need to multiply the second-order rate constant by this fraction.

**Comment by msulprizio** [comment]
Thanks @viral211 @beckyalexander. The fix for this (PR #1746) has now been merged into the 14.2.0 development branch. Benchmarking for that version will begin later today.
