### ISSUE TITLE
Implement a parameterization of SNA and OM dry size 

### ISSUE THREAD

**Issue by Haihui-Zhu** [geoschem/geos-chem#1747]
### Name and Institution (Required)

Name: Haihui Zhu 
Institution: Washington University in St. Louis

### Confirm you have reviewed the following documentation

- [x] [Contributing guidelines](https://geos-chem.readthedocs.io/en/stable/reference/CONTRIBUTING.html)

### New GEOS-Chem feature or discussion

I am writing to request implement of a parameterization of the dry aerosol size for SNA and OM. It improves the agreements between simulation and measurements such as aerosol extinction from aircraft and AOD from AERONET. The manuscript is under review:  

> Zhu, H., Martin, R., Croft, B., Zhai, S., Li, C., Bindle, L., Pierce, J., Chang, R., Anderson, B., Ziemba, L. and Hair, J., 2022. [Parameterization of Size of Organic and Secondary Inorganic Aerosol for Efficient Representation of Global Aerosol Optical Properties](https://egusphere.copernicus.org/preprints/2022/egusphere-2022-1292/). EGUsphere, pp.1-31.

Key figures: 
1. (Top) Surface dry effective radii (Reff) for SNA and OM when applying the parameterization to GEOS-Chem bulk model. Reff is shown when their mass is greater than 80% of the total aerosol mass. (Middle) The GEOS-Chem simulated AOD using parameterized Reff. (Bottom) the absolute difference between updated AOD and default AOD using dry Reff = 101 nm. Large enhancements in AOD are introduced by the parameterization:
![image](https://user-images.githubusercontent.com/71397044/231014347-3c63ba95-8c61-4fea-be72-4e0692aca48d.png)

2. Scatter plot of AERONET versus simulated AOD with the default Reff (blue dots, line, and text), and with the parameterized Reff (red dots, line, and text). The 1:1 line is dashed. NRMSD = normalized root mean square deviation. N is the number of points. Each dot represents an annual mean value for an AERONET site. The agreement is enhanced after applying the parameterization:
<img width="254" alt="image" src="https://user-images.githubusercontent.com/71397044/231013616-0ab859c2-d44a-41a9-8ebd-e386688dddbc.png">

3. Scatter plot of parameterized Reff and measured Reff from DISCOVER-AQ and KORUS-AQ. Each point represents a daily mean measurement.
<img width="273" alt="image" src="https://user-images.githubusercontent.com/71397044/231012642-47be859a-9694-46f3-9181-d6d9ee6b9485.png">

**Comment by theloniuspunk** [comment]
I'm in favor of this inclusion. It will affect photolysis and AOD calculations. However, do we generally wait until the paper is through peer review?

**Comment by yantosca** [comment]
NOTE: PR #1902 requires code modifications to the Cloud-J repository.  This must be done in collaboration with the Cloud-J developers.

**Comment by yantosca** [comment]
We can now close this issue as PR #2238 has been merged into the GEOS-Chem 14.4.0 development stream (see commits c5d1f155d48b4ce6d68ea3f876bd7cd210c4eae2 and 546fda29180c491bf4c6fb08fb13b0749cb5d70b.  Thanks @Haihui-Zhu!

**Comment by Haihui-Zhu** [comment]
> We can now close this issue as PR #2238 has been merged into the GEOS-Chem 14.4.0 development stream (see commits [c5d1f15](https://github.com/geoschem/geos-chem/commit/c5d1f155d48b4ce6d68ea3f876bd7cd210c4eae2) and [546fda2](https://github.com/geoschem/geos-chem/commit/546fda29180c491bf4c6fb08fb13b0749cb5d70b). Thanks @Haihui-Zhu!

Thank you, Bob!
