### ISSUE TITLE
[question] How to download future emission datasets?

### ISSUE THREAD

**Issue by pkufubo** [geoschem/geos-chem#1752]
### Name and Institution (Required)

Name: Bo Fu
Institution: Peking University

### Confirm you have reviewed the following documentation

- [√] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [√] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [√] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [√] [Current and past Github issues](https://github.com/geoschem/GCClassic/issues)

### Description of your issue or question

Hello GC developers.
I want to run a **full chemistry** simulation of the **future**. But I don't know how to get future emissions data. 
1. SSP emissions (of CMIP6) are preferred, but it seems that the current version of GC does not have this feature. 
2. RCP are also OK. But I don't know how RCP emission can be downloaded either. (http://geoschemdata.wustl.edu/ExtData/HEMCO/RCP/v2020-07/) is not available.

**Comment by ltmurray** [comment]
@yantosca the URL is  http://atmos.earth.rochester.edu/input/gc/ExtData (lowercase gc). I didn't realize URLs could be case-sensitive, but apparently, they can.

**Comment by ltmurray** [comment]
@pkufubo just follow the directions for creating a GEOS-Chem run directory, and select ModelE2.1 meteorology for a future decade. This will generate a run directory that uses the SSP meteorology and emissions, which you can download using the data downloader pointed to the Rochester server.

**Comment by yantosca** [comment]
Thanks @ltmurray.  I'll fix the link in the documentation.

**Comment by pkufubo** [comment]
> 

Thank @ltmurray , I will follow your suggestion.
