### ISSUE TITLE
problem with spin-up

### ISSUE THREAD

**Issue by cj2262** [geoschem/geos-chem#1759]
### Name and Institution (Required)

Name:cj
Institution:ECNU

### Description of your issue or question

Hello,

I have now performed a spin-up of the global and nested simulations of the benchmark experiment and output the restart file. But now I need to close a certain artificial emission inventory based on the benchmark experiment, can I continue to use the results of the benchmark experiment spin-up or do I need to perform a new spin-up for closing this emission inventory?

Thank you in advance for your answer.

**Comment by yantosca** [comment]
Thanks for writing @cj2262.  It is not strictly required that the spinup and simulation use the same emissions.  But we would recommend using the same options in both spinup and simualtion wherever possible.
