### ISSUE TITLE
[QUESTION] Still some concerns on POET_EOH and SHIP inventories

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/geos-chem#176]
@yantosca 

Hi there,

Previously I have posted a [question on HEMCO reading POET_EOH and SHIP inventories](https://github.com/geoschem/geos-chem/issues/173). I appreciate your reply in that I did find HEMCO reading POET_EOH if turning off CEDS and reading ARCTAS_SHIP if turning off CEDS_SHIP. Well from the [HEMCO user guide](http://wiki.seas.harvard.edu/geos-chem/index.php/The_HEMCO_User%27s_Guide#Data_collections), I would like to think these effects should be achieved via configurations like the following.
```
(((POET_EOH
(((.not.CEDS
...
))).not.CEDS
)))POET_EOH
```
However, I just saw the independent POET_EOH configurations in HEMCO_Config.rc as follows.
```
#==============================================================================
# --- POET EOH ---
#==============================================================================
(((POET_EOH
0 POET_EOH $ROOT/POET/v2017-03/POET_EOH.geos.2x25.nc EOH 1985/1/1/0 C xy kgC/m2/s EOH 26 1 1
)))POET_EOH
```
That's why I expect HEMCO would read POET_EOH irrespective CEDS turning on or off. But as we saw, HEMCO did not read POET_EOH. You said something about hierarchy but I might not prefer agreeing that is the reason since HEMCO read MIX (cat: 1 hier: 45) and NEI2011_MONMEAN (cat: 1 hier: 50) simultaneously. Examples also include the order you provided as follows.
```
a. ARCTAS_SHIP has the lowest priority (hier=1)
b. ICOADS_SHIP is next (hier=2)
c. CORBETT_SHIP is next (hier=3)
d. HTAP_SHIP is next (hier=4)
e. CEDS_SHIP has the highest priority (hier=5)
```
Given all the above, I wonder whether the relationship between POET_EOH and CEDS is determined by GC source codes?

Sorry for opening this issue again as I think you can only be notified in opened issues. Many thanks again for your kind help in advance!

Yours faithfully,
Fei

**Comment by FeiYao-Edinburgh** [comment]
Yeah I have seen the following comments in HEMCO_Config.rc.
```
1835 # ==> CEDS ship emissions are now the default.
1836 # ==> If CEDS_SHIP is turned off above then ARCTAS should be used over ICOADS,
1837 #     CORBETT, and HTAP for SO2 and ICOADS should be used for CO and NO.
```
I just wonder whether it is achieved by HEMCO configurations or GC source codes?

**Comment by yantosca** [comment]
This comment in HEMCO_Config.rc explains the default behavior, as I also tried to explain above.  It is done solely by the HEMCO configuration file.

**Comment by yantosca** [comment]
> I would like to think these effects should be achieved via configurations like the following.
```
(((POET_EOH
(((.not.CEDS
...
))).not.CEDS
)))POET_EOH
```

That is probably another way in which it can be done.  However, knowing that the inventory with the  higher hierarchy value supersedes the inventory with the lower hierarchy value, an explicit bracket statement like the one shown above is not necessary.

In GEOS-Chem 12.7.0, we will have the ability for GEOS-Chem (and HEMCO) to produce a list of files that is actually required for each simulation.  So hopefully this will cut down on some of the confusion that currently exists.

Please bear with us!  A lot of things in GEOS-Chem and HEMCO are in flux now...

**Comment by FeiYao-Edinburgh** [comment]
> However, knowing that the inventory with the higher hierarchy value supersedes the inventory with the lower hierarchy value, an explicit bracket statement like the one shown above is not necessary.

I agree that the inventory with the higher hierarchy value supersedes the inventory with the lower hierarchy value, but I might would like to think this process occurs in the second step of RUN ("Calculate") according to your [HEMCO paper](https://www.geosci-model-dev.net/7/1409/2014/)? For example, the CEDS, APEI, MIX, NEI2011_MONMEAN, and so forth have the same category (1) but different hierarchy (5, 45, 50, 60...), and they are all got read into GEOS-Chem (**e.g. GC.log displays that they have got read in**), after which they would be assembled into final calculated emissions based on their category and hierarchy. However, **I do not find any HEMCO reading logs for POET_EOH or ICOADS_SHIP even if they are switched on in HEMCO_Config.rc**. You said that an explicit bracket statement like the one shown below is not necessary for POET_EOH, but I do think it is necessary for combining inventories like CEDS, APEI, MIX, NEI2011_MONMEAN.
```
(((POET_EOH
(((.not.CEDS
...
))).not.CEDS
)))POET_EOH
```
So that's why I initially guess there might be some special treatment (or special configuration rules but missing in [HEMCO user guide](http://wiki.seas.harvard.edu/geos-chem/index.php/The_HEMCO_User%27s_Guide#Data_collections)?) for POET_EOH and ICOADS_SHIP? I do not that inventories with lower hierarchy values are not read into GC in [HEMCO user guide](http://wiki.seas.harvard.edu/geos-chem/index.php/The_HEMCO_User%27s_Guide#Data_collections)...

I understand that this issue does not matter too much. I just feel a bit uncomfortable of my imagined inconsistent rules. I am sorry for the disturbance. I look forward to seeing new features in GC 12.7.0!

Yours faithfully,
Fei

**Comment by msulprizio** [comment]
The key here is that CEDS and POET_EOH are both global inventories. HEMCO recognizes that and only reads in the global inventory with the higher hierarchy. When regional inventories with masks are involved HEMCO will the global inventory with the highest hierarchy and all of the regional inventories. In HCO_CalcEmis, it will then combine the global and regional inventories according to the hierarchies.

**Comment by FeiYao-Edinburgh** [comment]
> The key here is that CEDS and POET_EOH are both global inventories. HEMCO recognizes that and only reads in the global inventory with the higher hierarchy.

Thanks for your clarification!
