### ISSUE TITLE
TagCH4 Problems

### ISSUE THREAD

**Issue by yangning-code** [geoschem/geos-chem#1763]
### Name and Institution (Required)

Name:YangNing
Institution:JNU

### Confirm you have reviewed the following documentation

- [ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question
When I finish running the TagCH4 module, the simulated CH4 concentration has a negative value, I checked that the CH4 concentration in the restart file is positive, and the input CH4 emission is also positive, and now I don't know what caused the CH4 concentration to be negative
Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

**Comment by yantosca** [comment]
Thanks for writing @yangning-code.  The tagCH4 simulation has not been updated in a while, so there may be issues with it.

We would refer you to our debugging guide for some tips as to investigate why the negative values are occurring.
- https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html

**Comment by msulprizio** [comment]
@yangning-code Were you able to sort this out? If not, could you please provide more information (plots, log files, model version)?

**Comment by yantosca** [comment]
Closing out this issue
