### ISSUE TITLE
Variable referenced when not assigned

### ISSUE THREAD

**Issue by sdeastham** [geoschem/geos-chem#1771]
The variable `POAEMISS` is assigned a value of 0.0 in the `EMISSCARBON` routine before any checks have taken place to ensure that it is allocated: https://github.com/geoschem/geos-chem/blob/4722f288e90291ba904222f4bbe4fc216d17c34a/GeosCore/carbon_mod.F90#L4725

This issue can occur if the user is running a full chemistry simulation but does not include carbonaceous aerosols (e.g. if testing, as in my case). A simple fix is to move the initialization to occur after the existing check to see if the species are defined (which results in the routine returning before the initialization): https://github.com/geoschem/geos-chem/blob/4722f288e90291ba904222f4bbe4fc216d17c34a/GeosCore/carbon_mod.F90#L4764

Issue raised by: Seb Eastham, MIT

**Comment by yantosca** [comment]
Thanks @sdeastham.  We'll take a look.

**Comment by yantosca** [comment]
Closed by #1987

**Comment by yantosca** [comment]
PR #1987 has been merged into our "no-diff-to-benchmark" development stream.  We can now close out this issue.
