### ISSUE TITLE
question about CH4 and CO2 simulation results  by GCClassic

### ISSUE THREAD

**Issue by zhifeng1310** [geoschem/geos-chem#1775]
### Name and Institution (Required)

Name:zhifeng
Institution:beihang university

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question
Hi, sorry to disturb you, I simulate the CO2 and CH4 by the GCClassic, but my result mabe have some problem, like CO2 simulation result just have ProdCO2fromCO's value and CH4 simulation have lossCH4byCinTrop, LossCH4byOHinTrop, LossCH4inStrat value. I don't know whether it is right. If it is wrong, how can i get the specific CO2 or CH4 concentration? please, thank you!
Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.
gcc@10.2.0
GEOSChem@14.1.1
1 day simulation for CH4 and CO2
![image](https://user-images.githubusercontent.com/109587027/234283068-a0908cf0-6a30-4831-b1e2-afa44b7fe4a5.png)
![image](https://user-images.githubusercontent.com/109587027/234283185-5b7f47fb-cd53-48b9-89ab-ddafc453b39b.png)

**Comment by yantosca** [comment]
Thanks for writing @zhifeng1310.  As described at the page below, species concentrations are archived in the `SpeciesConc` diagnostic collection.  See:

- https://geos-chem.readthedocs.io/en/latest/gcclassic-user-guide/diag-outputs-hist.html

**Comment by zhifeng1310** [comment]
oh, thank you so much, yantosca. I see it and I will close this issue, thanks again!
