### ISSUE TITLE
[BUG/ISSUE] NetCDF: Index exceeds dimension bound when using Yuan processed LAI

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/geos-chem#178]
Hi there,

I am trying to switch to [Yuan processed LAI](http://wiki.seas.harvard.edu/geos-chem/index.php/Leaf_area_indices_in_GEOS-Chem) for my 2x2.5 complexSOA_SVPOA simulation in 2013. I am using GC 12.5.0. After reading the wiki, I believe I need to do [a fix to force the timestamp search algorithm work correctly](http://wiki.seas.harvard.edu/geos-chem/index.php/Leaf_area_indices_in_GEOS-Chem#Quick_fix_to_use_Yuan-processed_MODIS_LAI_in_GEOS-Chem_Classic). I did that and the GC compiled well. However, when I run the model, it complained the following error. I would appreciate your help.
```
HEMCO: Opening /geos/d21/s1855106/ExtData/HEMCO/Yuan_XLAI/v2019-03/Yuan_proc_MODIS_XLAI.025x025.2013.nc

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In Ncrd_2d_R4 #2:  NetCDF: Index exceeds dimension bound
     65536         1

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Code stopped from DO_ERR_OUT (in module NcdfUtil/m_do_err_out.F90)

This is an error that was encountered in one of the netCDF I/O modules,
which indicates an error in writing to or reading from a netCDF file!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

Yours faithfully,
Fei

**Comment by yantosca** [comment]
Thanks for writing.  The Yuan XLAI requires a further fix in HEMCO to allow for arbitrary interpolation periods.  This will ship with GC 12.7.0.  So you will not be able to the Yuan XLAI with 12.5.0.

We are going to start benchmarking 12.7.0, but due to the holiday break, it might not be ready until sometime in January.

**Comment by lijimdavid** [comment]
Hi,
I am running GC 13.0.2 for 2014 and my simulations stopped (for 12/27/2014) abruptly with the following error 

HEMCO: Opening /GEOS-Chem/ExtData/HEMCO/Yuan_XLAI/v2019-03/Yuan_proc_MODIS_XLAI.025x025.2014.nc
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In Ncrd_2d_R4 #2:  NetCDF: Index exceeds dimension bound
    262144         1

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Code stopped from DO_ERR_OUT (in module NcdfUtil/m_do_err_out.F90)
This is an error that was encountered in one of the netCDF I/O modules,
which indicates an error in writing to or reading from a netCDF file!

I would appreciate getting help. 
Thanks,
Liji

**Comment by yantosca** [comment]
Hi @lijimdavid, thanks for writing.  This will be fixed in HEMCO 3.0.0 (which will be released in GEOS-Chem 13.1.0).

You can get the fix from here: https://github.com/geoschem/HEMCO/pull/85.

**Comment by zichongchen** [comment]
Thanks Bob, this saved my day! And I assume this is only an issue for a quarter resolution runs?  And FYI, I also read others who post this problem, it seems that error always happens on the day of 12/27.  --Zichong

**Comment by zichongchen** [comment]
@yantosca Sounds great and thanks for letting me know.
