### ISSUE TITLE
Disabling SO2 emissions in GFED

### ISSUE THREAD

**Issue by Mashiat25** [geoschem/geos-chem#1780]
### Name and Institution (Required)

Name: Mashiat
Institution: University of Illinois at Urbana-Champaign

### Description of your issue or question

I am currently running a 0.5x0.625 simulation for 2017 with GEOS-Chem 13.3.3 to investigate the contribution of marine sources to sulfate aerosols. As part of our analysis, we plan to disable SO2 & SO4 emissions originating from land sources. However, I have noticed that unlike other biomass burning inventories such as QFED or GFAS, it is not possible to disable only SO2 emissions in GFED. This could be due to the online calculation feature of GFED. I am interested to know if there is a way to disable SO2 emissions in GFED without modifying the code.

**Comment by yantosca** [comment]
Hi @Mashiat25, thanks for writing.  You can set a scale factor for any species in an extension by using `Scaling_<spcname>` in the extension settings.  For GFED we have these entries:
```console
111     GFED                   : on    NO/CO/ALK4/ACET/MEK/ALD2/PRPE/C2H2/C2H4/C3H8/CH2O/C2H6/SO2/NH3/BCPO/BCPI/OCPO/OCPI/POG1/POG2/MTPA/BENZ/TOLU/XYLE/NAP/EOH/MOH/SOAP/FURA/PHEN/MVK/ISOP/ACTA/MGLY/GLYX/RCHO
    --> GFED4                  :       true
    --> GFED_daily             :       false
    --> GFED_3hourly           :       false
    --> Scaling_CO             :       1.05
    --> Scaling_NAP            :       2.75e-4
    --> hydrophilic BC         :       0.2
    --> hydrophilic OC         :       0.5
    --> fraction POG1          :       0.49
    --> CO to SOAP             :       0.013
    --> GFED_subgrid_coag      :       false
#see the note near scale factor 281 for the source of this emis factor``console
```
so here CO is scaled by 1.05 and NAP is scaled by 2.75e-4.  If you add:

```console
--> Scaling_SO2 : 0.0
```
then this should zero out SO2 emissions.  You can try a short simulation (like a couple of hours) and then see if SO2 from biomass burning is zeroed out.  Let me know if this works.

**Comment by yantosca** [comment]
@Mashiat25: Were you able to resolve this issue?

**Comment by Mashiat25** [comment]
Hi @yantosca! Yes, setting the scaling factor to 0 disabled SO2 emissions. Thanks for the help :)
