### ISSUE TITLE
Weighted average based on air density

### ISSUE THREAD

**Issue by capelson** [geoschem/geos-chem#1782]
Hello everyone.
I have created CH4 simulation using GEOS-Chem 14.1.0 for 72 levels and got my results about concentration of methane on each level. I want to calculate weighted average for whole column of air (from 1 to 72th level) using air density as weights, since bottom levels has higher air density then top levels. How can I implement this?

Thank you

**Comment by yantosca** [comment]
Thanks for writing @capelson.  The `StateMet` collection has some air density fields (e.g. `Met_AIRDEN`, `Met_AIRNUMDEN`) so you could use those in your calculations.   You can write a Python script to do the averaging in post-processing.

NOTE: We are now asking users to identify themselves and their institutions when requesting help. Please do this in the future. Thanks!

**Comment by capelson** [comment]
Thank you so much.

**Comment by yantosca** [comment]
Thanks, I'll close out this issue.
