### ISSUE TITLE
restart file is not generated when creating the new run directory

### ISSUE THREAD

**Issue by lee1046** [geoschem/geos-chem#1786]
### Name and Institution (Required)

Name: Jungmin Lee
Institution: LLNL

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

I freshly cloned GEOS-CHEM version 14.1.1 and followed the instruction to create a run directory. But I do not see any GEOS-Chem.Restart.*.nc4 file generated under rundir/Restart/ or rundir/ 
Below is the snapshot of my rundir. You can see that there is no restart file. If there is any additional information that I can provide to help you with, please let me know.

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/40573463/236071239-cc64feff-31b2-4d01-bfb5-a2a36ac86ef0.png">

**Comment by lizziel** [comment]
Hi @lee1046, you can try creating another run directory and look closely at every line printed to the screen. Check if there are any messages about not being able to copy a file. If you see one copy and paste it here in the issue.

**Comment by lee1046** [comment]
I create the run directory using createRunDir.sh script and below is the all I see on the screen.
[lee1046@quartz770:run]$ ./createRunDir.sh 

===========================================================
GEOS-CHEM RUN DIRECTORY CREATION
===========================================================

-----------------------------------------------------------
Choose simulation type:
-----------------------------------------------------------
   1. Full chemistry
   2. Aerosols only
   3. CH4
   4. CO2
   5. Hg
   6. POPs
   7. Tagged CH4
   8. Tagged CO
   9. Tagged O3
  10. TransportTracers
  11. Trace metals
  12. Carbon
>>> 10

-----------------------------------------------------------
Choose meteorology source:
-----------------------------------------------------------
  1. MERRA-2 (Recommended)
  2. GEOS-FP 
  3. GISS ModelE2.1 (GCAP 2.0)
>>> 1

-----------------------------------------------------------
Choose horizontal resolution:
-----------------------------------------------------------
  1. 4.0  x 5.0
  2. 2.0  x 2.5
  3. 0.5  x 0.625
>>> 2

-----------------------------------------------------------
Choose number of levels:
-----------------------------------------------------------
  1. 72 (native)
  2. 47 (reduced)
>>> 1

-----------------------------------------------------------
Enter path where the run directory will be created:
-----------------------------------------------------------
>>> /p/lustre1/lee1046/LDRD_STE/run_dir

-----------------------------------------------------------
Enter run directory name, or press return to use default:

NOTE: This will be a subfolder of the path you entered above.
-----------------------------------------------------------
>>> 
  -- Using default directory name gc_2x25_merra2_TransportTracers

  See /p/lustre1/lee1046/LDRD_STE/run_dir/gc_2x25_merra2_TransportTracers/CreateRunDirLogs/rundir_vars.txt for run directory settings.


  -- This run directory has been set up to start on  and
     restart files for this date are in the Restarts subdirectory.

  -- Update start and end dates in geoschem_config.yml.

  -- Add restart files to Restarts as GEOSChem.Restart.YYYYMMDD_HHmmz.nc4.

  -- The default frequency and duration of diagnostics is set to monthly.
     You may modify these settings in HISTORY.rc and HEMCO_Config.rc.

  -- The following sample restart provided for this simulation was not found:
     /p/lustre1/lee1046/LDRD_STE/run_dir/GEOSCHEM_RESTARTS/GC_14.0.0/GEOSChem.Restart.TransportTracers.20190101_0000z.nc4
     You will need to provide this initial restart file or disable
     GC_RESTARTS in HEMCO_Config.rc to initialize your simulation
     with default background species concentrations.

-----------------------------------------------------------
Do you want to track run directory changes with git? (y/n)
-----------------------------------------------------------
>>> n^?y
Input not recognized. Try again.
>>> y

**Comment by lizziel** [comment]
Hi @lee1046, did you check to see if you have that file at that path? If not, you can download it at http://geoschemdata.wustl.edu/ExtData/GEOSCHEM_RESTARTS/GC_14.0.0/.

**Comment by lee1046** [comment]
Thanks @lizziel. I checked the appropriate restart file was copied under Restart directory under the run directory. I will close this
