### ISSUE TITLE
When I run the GEOS-Chem simulation, the ./geos.mp file has the following problems

### ISSUE THREAD

**Issue by cui34466** [geoschem/geos-chem#1787]
### Name and Institution (Required)

Name:Cui jiangyu
Institution:Beijing Normal University

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question
CANNOT WRITE : /home/cuijiangyu/model/output/Pb-global/2012/trac_avg.geosfp_2x2
 5_RnPbBe.201201010000                                                          
                                                                                
                                  
===============================================================================
GEOS-CHEM I/O ERROR    29 in file unit    12
Encountered at routine:location open_bpch2_for_write:1

Error   29: File not found
===============================================================================

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

**Comment by yantosca** [comment]
This issue probably means that the folder in which you are trying to write the output file does not exist.

Also please note that v11-01 is no longer supported.  We would encourage you to update to the latest version, which is 14.1.1 as of this writing.
