### ISSUE TITLE
INIT_WETSCAV error before starting simulation with GEOS-Chem version 11.01

### ISSUE THREAD

**Issue by cui34466** [geoschem/geos-chem#1788]
### Name and Institution (Required)

Name:Cui jiangyu
Institution:BNU

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question
I freshly used GEOS-CHEM version 11.01 and followed the instruction （./geos.mp)to start a stimulation. But I faced following problem. I think this problem is related to INIT_WETSCAV.If there is any additional information that I can provide to help you with, please let me know. thank you!
INIT_WETSCAV: List of soluble species:
```console
  #             Name  Species Mol Wt  Henry K0  Henry CR  Henry pKa
                        ID    g/mol    M/atm      K         1
----------------------------------------------------------------------
  1               Pb     2    210.0     -         -         -    
  2              Be7     3      7.0     -         -         -    
  3          HMCD_F1     4    112.4     -         -         -    
  4          HMCD_F2     5    112.4     -         -         -    
===============================================================================
GEOS-CHEM I/O ERROR    29 in file unit    11
Encountered at routine:location create_dinfo:1

Error   29: File not found
===============================================================================
     - CLEANUP: deallocating arrays now...
Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.
```

**Comment by yantosca** [comment]
Thanks for writing @cui34466.  GEOS-Chem v11-01 is no longer supported, as this model version is more than 7 years old.  We would encourage you to update to the latest model version, which at this time is 14.1.1.
