### ISSUE TITLE
[BUG/ISSUE] An error in HEMCO_Config.rc for Hg simulation?

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#179]
I am submitting this issue on behalf of Win Trivitayanurak:

>I spotted an error (so I think) in the HEMCO_Config.rc in my mercury simulation.  I traced it back to the UT in the HEMCO_Config.template (both 4x5 and for 0.25x0.3125)  at the lines for WHET
>
>This is the original lines:
```
#==============================================================================
# WHET emissions inventory
#==============================================================================

(((WHET
0 WHET_HG0 $ROOT/MERCURY/v2018-04/WHET_Hg0.geos.1x1.2010_final.nc Hg0 2010/1/1/0 C xy kg/m2/s Hg0 - 1 1
0 WHET_HG2 $ROOT/MERCURY/v2018-04/WHET_Hg2.geos.1x1.2010_final.nc Hg2 2010/1/1/0 C xy kg/m2/s Hg2 - 1 1
0 WHET_HGP $ROOT/MERCURY/v2018-04/WHET_HgP.geos.1x1.2010_final.nc HgP 2010/1/1/0 C xy kg/m2/s Hg2 - 1 1
)))WHET
```
>
>Now what I see is the emission species name for HgP (after the unit) is written "Hg2"   So this means that with this setting, the values read out for HgP file, extracted for the field name "HgP", would be put into Hg2 --- am I right?   Please help confirm so I can rectify my runs.  Thank you very much.

**Comment by yantosca** [comment]
I think this might be correct.  I believe HgP emissions are added into the Hg2 species but I am not sure of the reasoning behind it.  @cdholmes @jennyfisher: can you clarify?

**Comment by cdholmes** [comment]
The HEMCO file is behaving as intended. The GC mercury simulation assumes that both Hg(II) gas and Hg(II)-particle are semi-volatile and uses equilibrium partitioning of Hg(II) between the gas and aerosol. As a result, the inventory "HgP" can be emitted as "Hg2" (or vice versa) with negligible effect on the simulation.

**Comment by yantosca** [comment]
Thanks Chris for your clarification. I will close out this issue.
