### ISSUE TITLE
GEOS_0.5x0.625/MERRA2 data missing

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#1793]
### Discussed in https://github.com/geoschem/geos-chem/discussions/1792

<div type='discussions-op-text'>

<sup>Originally posted by **haohe1982** May 12, 2023</sup>
hi I am running GC for the NA 0.5x0.625 domain. Everything runs well. But when I start the year of 2003, the MERRA2 data of Feb 2003 was missing on the server (I download 01, 03, 04, .. but not 02). I tried 'wu', 'cc', and 'ur' sources, but none of them have the 2003/02 data. Could you please check with IT administrator of these data FTP?

Hao</div>

**Comment by yantosca** [comment]
Thanks for writing.  I've tagged @SaptSinha, who is in charge of the data processing at WashU.

**Comment by SaptSinha** [comment]
The missing dataset is now available at: http://geoschemdata.wustl.edu/ExtData/GEOS_0.5x0.625/MERRA2/2003/02/

**Comment by haohe1982** [comment]
Great. I downloaded the Feb data, but seems like the May data are also not complete http://geoschemdata.wustl.edu/ExtData/GEOS_0.5x0.625/MERRA2/2003/05/, fyi.

**Comment by haohe1982** [comment]
Update. My GC stopped at 02/10 showing the following error

HEMCO ERROR: Cannot find field with valid time stamp in
/scratch/zt1/project/haohe-prj/user/haohe/GEOSChem/data/ExtData/GEOS_0.5x0.625/MERRA2/2003/02/
MERRA2.20030210.I3.05x0625.nc4 -

Cannot get field PS_NEXTDAY. Please check file name and time (incl. time range flag) in the config. file

Seems like the updated files are not right. I also find the size of Feb is much larger than other months. Please see below

login-2.zaratan.umd.edu{haohe}334: du -sh *
88G     01
209G    02
80G     03
81G     04
8.6G    05
79G     06
81G     07
81G     08
80G     09
82G     10
78G     11
81G     12

**Comment by haohe1982** [comment]
Looks like this file is still missing

--2023-05-15 20:20:56--  http://geoschemdata.wustl.edu/ExtData/GEOS_0.5x0.625/MERRA2/2003/02/MERRA2.20030211.I3.05x0625.nc4
Resolving geoschemdata.wustl.edu (geoschemdata.wustl.edu)... 35.209.233.133
Connecting to geoschemdata.wustl.edu (geoschemdata.wustl.edu)|35.209.233.133|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-05-15 20:20:56 ERROR 404: Not Found.

**Comment by SaptSinha** [comment]
-- The updated May 2003 dataset is now available at: http://geoschemdata.wustl.edu/ExtData/GEOS_0.5x0.625/MERRA2/2003/05/

-- The "[MERRA2.20030211.I3.05x0625.nc4](http://geoschemdata.wustl.edu/ExtData/GEOS_0.5x0.625/MERRA2/2003/02/MERRA2.20030211.I3.05x0625.nc4)" file is now available at http://geoschemdata.wustl.edu/ExtData/GEOS_0.5x0.625/MERRA2/2003/02/

-- Ignore the folder/file sizes, unless they are missing any entries.

**Comment by haohe1982** [comment]
Great. But the 02/11 I3 files is still missing

Downloading data from washu
--2023-05-16 12:40:21--  http://geoschemdata.wustl.edu/ExtData/GEOS_0.5x0.625/MERRA2/2003/02/MERRA2.20030211.I3.05x0625.nc4
Resolving geoschemdata.wustl.edu (geoschemdata.wustl.edu)... 35.209.233.133
Connecting to geoschemdata.wustl.edu (geoschemdata.wustl.edu)|35.209.233.133|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-05-16 12:40:22 ERROR 403: Forbidden.

**Comment by SaptSinha** [comment]
The file in question is not missing, I re-checked the permissions and it can be accessed from the link I provided earlier. Check your code and any local settings, or re-run the simulation.
![image](https://github.com/geoschem/geos-chem/assets/70730479/eacd0fdd-847a-4e4c-b159-a0275bbe0dc6)

**Comment by SaptSinha** [comment]
The file in question is not missing, I re-checked the permissions and it can be accessed from the link I provided earlier. Check your code and any local settings, or re-run the simulation.

**Comment by haohe1982** [comment]
Sorry I downloaed the file. For whatever reason, the download python script can not access the file, but the web browser works. thanks a lot for your help. You can close the ticket now

**Comment by SaptSinha** [comment]
You can re-download the files and run the simulation again with the latest downloaded files. It could be possible that the files in your local directory were not synced properly.
