### ISSUE TITLE
OC and OA value difference

### ISSUE THREAD

**Issue by jiaying002** [geoschem/geos-chem#1795]
### Name and Institution (Required)

Name: Jiaying Li
Institution: Nanyang Technological University

### New GEOS-Chem feature or discussion
I generated the OC and OA results using GCAP2.0 scenarios. All the result for OC is zero in all the scenarios, but I did get the OA values. (i.e., I did some other work on the OA one, I just put it to justify I did get the OA result.)

![image](https://github.com/geoschem/geos-chem/assets/113654537/85a7524e-cc4b-4c93-a7a3-86a8810531d0)
![image](https://github.com/geoschem/geos-chem/assets/113654537/240d7f21-05aa-497c-8d63-beaf794990ad)

If the ratio between OA and OC is 2.1, then how come to the OA has values, but OC is zero?
![image](https://github.com/geoschem/geos-chem/assets/113654537/e1972c13-677e-4d5b-b57d-248c472fb1b2)

Thank you in advance.

**Comment by yantosca** [comment]
Thanks for writing @jiaying002.  Did you turn on secondary organic aerosols in your simulation?  I think the OA diagnostics might only be activated if either complex SOA or complex SOA with SVPOA are turned on.  

The default is to use the simple SOA precursor and species, which is computationally faster but does not include a breakdown of organic aerosol species as do the complex SOA options.

**Comment by jiaying002** [comment]
Thank u so much! @yantosca 

I didn’t turn on the secondary organic aerosols! Btw, would you mind tell me how to turn it on?

Besides that, I am also generating results for ozone, OH and NOx. I’d like to know if the results are incorrect if I didn’t turn on the SOA.

**Comment by yantosca** [comment]
Hi @jiaying002.  The secondary organic aerosols can be toggled in `geoschem_config.yml` as described at ReadTheDocs:

https://geos-chem.readthedocs.io/en/stable/gcc-guide/03-config/geoschem-config.html#aerosols-settings

The secondary organic aerosols are also an option.  They are currently computed separately from O3, OH, NOx.  However, there might be some small differences since the secondary aerosol concentrations may result in a different aerosol optical depth, which gets fed into photolysis.  You can do a quick test w/r/t the run you've already done to assess the difference with secondary organic aerosols off.

**Comment by jiaying002** [comment]
Got it! Thank u so much for helping me!

**Comment by jiaying002** [comment]
@yantosca Thank u again for your help in this question before! Well, when I active the complex SOA, I occurred an error like this:
![image](https://github.com/geoschem/geos-chem/assets/113654537/3323869c-0d1b-47ea-930e-45aff4803f15)

I tried to add "output_species: -OC" but still not working. I'd like to generate the organic carbon result. Would you please help me a little?

Btw, I read the introduction website of the simple SOA and complex SOA, but not sure if I get the difference correct. Would you please correct me if I am wrong.
1) Simple SOA only includes emissions of monoterpenes, isoprene, biomass-burning CO, biofuel CO, and fossil fuel CO in HEMCO, but complex SOA includes more sources. 
2) Simple SOA has already been considered chemical reactions related to SOA precursors (e.g., O3, NOx, OH, etc.), so opening the complex SOA will not have a significant change to the SOA precursors.

Cheers!

**Comment by yantosca** [comment]
Thanks @jiaying002.  For complex SOA you would need to add POA1, POA2, POG1, POG2, TSOA1, TSOA2, TSOA3, TSOG0, TSOG1, TSOG2, TSOG3, ASOA1, ASOA2, ASOA3, ASOAN, ASOG1, ASOG2, ASOG3 to the list of transported species in `geoschem_config.yml`.  That will eliminate the error.

**Comment by jiaying002** [comment]
Got it! Thank u so much! @yantosca 

I’ve read the official website of SOA, but not sure if I got the concepts correct. Would you mind help me check if my understandings below of the difference between simple and complex version of SOA is correct? 
1) Simple SOA only includes emissions of monoterpenes, isoprene, biomass-burning CO, biofuel CO, and fossil fuel CO in HEMCO, but complex SOA includes more sources.
2) Simple SOA has already been considered chemical reactions related to SOA precursors (e.g., O3, NOx, OH, etc.), so opening the complex SOA will not have a significant change to the SOA precursors.

Thank u again!

**Comment by yantosca** [comment]
Thanks @jiaying002.  I would recommend consulting the following references:

- Simple SOA: Pai et al 2020, https://doi.org/10.5194/acp-20-2637-2020
- Complex SOA: Pye et al 2010: http://www.atmos-chem-phys.net/10/11261/2010/acp-10-11261-2010.pdf

**Comment by jiaying002** [comment]
Thank you so much for the references! 

For the coding issue, I added those species as you said, but got an error like this: "Semivolatile POA species is defined in addition to Nonvolatile POA." Then I found the origin code, and it seems like " ! OCPI and OCPO are the non-volatile POA tracers.  ! POA (along w/ POG, OPOA, and OPOG) are the semivol POA tracers. You can't have both!" So I tried to delete the OCPI and OCPO, and it pumped up an error saying, "Semivolatile POA requires LSOA=T and LSVPOA=T". 

![image](https://github.com/geoschem/geos-chem/assets/113654537/e7273e81-6b48-4bbd-ba08-4f856a0712b9)

Then I tried to delete the POA1, POA2, POG1 and POG2. This time the simulation could run, but it stopped here somehow...
![image](https://github.com/geoschem/geos-chem/assets/113654537/6c6aecd7-038f-4996-b4d5-372867f0009a)

Would you please let me know if I did it correctly? If not, what should I do? 

Besides that, I wonder if I get an OA value, can I directly calculate the OC by the ratio of 1.5?
(https://github.com/geoschem/geos-chem/issues/1381)

I am so grateful for your help!

**Comment by yantosca** [comment]
For complex SOA you should delete OCPO, OCPI and keep POA1, POA2, I think.

**Comment by msulprizio** [comment]
@jiaying002 Adding on to Bob's comment above, If you want to use complex SOA, I would recommend creating a new run directory using `createRunDir.sh` and selecting the complex SOA option to ensure you have proper settings and species.

**Comment by jiaying002** [comment]
Thank u so much for your help! @yantosca @msulprizio Working on the new run directory now!

Besides that, just wanna double check that if there is any way that I can get OC value using simple SOA? Cuz I’ve run the simulation for about four months with the simple SOA. It would be a disaster to me if I have to redo everything.

Super appreciate your help!!!!!!!

**Comment by msulprizio** [comment]
In the simpleSOA simulation, you can use the GEOSChem.SpeciesConc* output for OCPI and OCPO to evaluate organic carbon.

**Comment by yantosca** [comment]
Thanks for writing @jiaying002 

> How to use OCPI and OCPO to calculate OC?

OC = OCPI + OCPO.

>I noticed the original code for OC contains other species like TSOA and ASOA, I wonder if I should consider the values of other species as zero?

The TSOA, ASOA, etc. are only defined when you use one of the complex SOA simulations.  If you are using the default fullchem simulation option (which only uses simple SOA precursor (SOAP) and simple SOA species (SOAS)), then all of the TSOA, etc. species can be neglected.
