### ISSUE TITLE
Differences in the vertical profile of (NIT, NH3, etc.) concentrations with future GCAP fullchem simulations

### ISSUE THREAD

**Issue by flavioquadros** [geoschem/geos-chem#1800]
### Name and Institution (Required)

Name: Flávio Quadros
Institution: Delft University of Technology

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

I ran some GEOS-Chem classic (v13.3.3) fullchem simulations using 40-level GCAP2.0 met data and CMIP6 emissions for the year 2040 (SSP2-4.5), and the resulting concentrations of several species above ground level are quite different to what we see in "regular" simulations using MERRA-2, as described below. I am wondering if this is a known issue/characteristic or if there is something going wrong, perhaps someone who worked with GCAP2 simulations could kindly tell me if this expected behavior or not?

What caught my eye was the much higher concentrations of NIT and NH4 aerosol, higher NH3, and lower OH compared to our simulations for 2005 and 2019. Although other species also have similar patterns. I am interested in the effect of aviation emissions, so the higher aerosol loading at altitude makes a big difference, but the plots shown below are for simulations without any aircraft emissions. The plots show the global annual average concentration of each species per the hybrid vertical coordinate. At the end, I also include a comparison of the zonal mean of NIT for July 2040 with the GEOS-Chem v13.3 [benchmark](http://ftp.as.harvard.edu/gcgrid/geos-chem/1yr_benchmarks/13.3.0-rc.0/GCClassic/FullChem/BenchmarkResults/Aerosols/Jul2019/Aerosols_FullColumn_ZonalMean_Jul2019.pdf).

Additional details about the simulations:
* 2x2.5 resolution
* 72 vertical levels for 2005 and 2019, 40 levels for 2040
* 2040 was spun-up for 3 years at 4x5 resolution by re-running the same year
* 2040 has 2019 volcanic emissions
* Other than disabling aviation emissions, the settings for the three simulations are pretty much standard

<details>
    <summary>Plots</summary>

![vert_annualConc_NIT](https://github.com/geoschem/geos-chem/assets/72943805/5c039df5-e3ae-4e05-92c0-ed6b3b7530d0)
![vert_annualConc_NH4](https://github.com/geoschem/geos-chem/assets/72943805/cd7fde20-8f2e-4a90-b1da-8b923404db5e)
![vert_annualConc_NH3](https://github.com/geoschem/geos-chem/assets/72943805/4d1cdbbb-bb0e-4f60-b36b-9744576a620e)
![vert_annualConc_OH](https://github.com/geoschem/geos-chem/assets/72943805/de2fb670-82dc-439c-9c58-54be25132bc5)

![image](https://github.com/geoschem/geos-chem/assets/72943805/8ff6546f-0295-4124-b55d-eed4a57298fc)
![zonal_JUL_AerMassNIT_2040](https://github.com/geoschem/geos-chem/assets/72943805/ae37d2e0-ef80-4b7c-a481-aa395c2fc5dd)
</details>

**Comment by msulprizio** [comment]
Hi @flavioquadros. This is a science question that is best geared to the Chemistry-Climate Working Group. Please see [this wiki page](http://wiki.seas.harvard.edu/geos-chem/index.php/Chemistry-Climate_Working_Group) for contact information.

Also tagging @ltmurray
