### ISSUE TITLE
error while running ./gcclassic --dry-run

### ISSUE THREAD

**Issue by lee1046** [geoschem/geos-chem#1801]
### Name and Institution (Required)

Name: Jungmin Lee
Institution: Lawrence Livermore National Lab

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

I am using version 14.1.1. After I create run directory, configure and compile the code, I modified goes_config.yml so that I can run simulation for 1 year from 2017-01-01. Then, I ran dry-run simulation to download necessary input data. Below is the HEMCO error message that I get. It's trying to access a file that I don't have. Do I manually download this file that HEMCO is trying to read? or is there another solution? 

<img width="997" alt="image" src="https://github.com/geoschem/geos-chem/assets/40573463/2ca38b54-f7ec-43c9-abdf-347e1432df7f">

**Comment by yantosca** [comment]
Thanks for writing @lee1046.  If you have added a new species to the simulation, then HEMCO probably cannot find the new species in the restart file, which is causing the error.  Changing the time cycle flag for the `SPC_` container in `HEMCO_Config.rc` from `EFYO` to `CYS` should work.  See: https://geos-chem.readthedocs.io/en/latest/gcclassic-user-guide/restart-files-gc.html

**Comment by lee1046** [comment]
Thanks for providing a prompt solution. I will try it. By the way, I did not add a new species. I am running the default TransportTracers case starting 2017-01-01.

**Comment by yantosca** [comment]
@lee1046: It could also be that the time stamp is different in the restart file than in your starting date.  That would result in the same error.  Changing the time cycle flag as described would fix this as well.

**Comment by lee1046** [comment]
@yantosca I changed the time cycle flag for the SPC_ in HEMCO_Config.rc to CYS, but I get the same error.

**Comment by yantosca** [comment]
@lee1046: I am not so familiar with the CEDS 2017 data.  I am not sure if that is a standard field.  Tagging @msulprizio.

**Comment by msulprizio** [comment]
Hi @lee1046. Could you rerun your simulation with verbose and warnings set to 3 in HEMCO_Config.rc and then upload your HEMCO_Config.rc and log files?

Usually you get this error if a file cannot be found or the specified field (in this case it should be `CO_agr`) cannot be read from the file. The verbose output should tell us more.

**Comment by yantosca** [comment]
Hi @lee1046, we also now have some information on what causes segmentation faults.  See https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/error-guide.html#segmentation-faults-and-similar-errors

**Comment by lee1046** [comment]
Hi @msulprizio 
I would like to reiterate the steps that I took until I was hit by the error message. After I manually downloaded `CO-em-anthro_CMIP_CEDS_2017.nc` into the corresponding ExtData directory, I recreated the run directory, changed simulation starting time to 2017-01-01, and put 2017 restart file to Restart directory. And then I ran `./gcclassic --dry-run | tee log.dryrun` expecting to identify input files that are not present in my ExtData directory. It is now telling me that one of MERRA file is missing. Please see my geoschem_config.yml, HISTORY.rc, HEMCO_Config.rc and log.dryrun files inside the zipped file. Other than the zipped files, I did not modify anything. Please let me know if you find anything. Thank you.
[log.tar.gz](https://github.com/geoschem/geos-chem/files/11511488/log.tar.gz)

**Comment by lee1046** [comment]
I found out that I used ./gcclassic --dry-run instead of ./gcclassic --dryrun. This causes for necessary input data to be not downloaded. The problem is solved for now so I will close this issue.

**Comment by yantosca** [comment]
Thanks for the feedback @lee1046.  Glad your issue is resolved.
