### ISSUE TITLE
segment error

### ISSUE THREAD

**Issue by zhifeng1310** [geoschem/geos-chem#1802]
### Name and Institution (Required)

Name:li
Institution:beihang univercity

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question
I am running the simulation of global CO2, resolution is 0.5x0.625, GC version is 14.1.1, and I met segment error. And I searched the isuues which is similar to my error, but I didn't find anything. Do you know how to solve this? 

HEMCO: Opening /home/zf/geoschem/ExtData//HEMCO/Yuan_XLAI/v2021-06/Yuan_proc_MODIS_XLAI.025x025.2019.nc
HEMCO: Opening /home/zf/geoschem/ExtData//HEMCO/CO2/v2022-11/BIO/SiB3_3hr_NEP.nc
HEMCO: Opening /home/zf/geoschem/ExtData//HEMCO/CO2/v2015-04/FOSSIL/TIMES_diurnal_scale_factors.nc
HEMCO: Opening ./Restarts/GEOSChem.Restart.20190201_0000z.nc4
TIMEZONES (i.e. OFFSETS FROM UTC) WERE READ FROM A FILE
     - Found all CN     met fields for 2011/01/01 00:00
     - Found all A1     met fields for 2019/02/01 00:30
     - Found all A3cld  met fields for 2019/02/01 01:30
     - Found all A3dyn  met fields for 2019/02/01 01:30
     - Found all A3mstC met fields for 2019/02/01 01:30
     - LightNOX extension is off. Skipping FLASH_DENS and CONV_DEPTH fields in FlexGrid_Read_A3mstE.

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

**Comment by zhifeng1310** [comment]
And when I set warnnings from 1 to 3, it printout:
HEMCO WARNING: Simulation time is outside of time range provided for DELPDRY - field is ignored for the time being!

**Comment by lizziel** [comment]
Hi @zhifeng1310, are you building with debug flag on? You can do this by including the following in your configuration when running cmake: `-DCMAKE_BUILD_TYPE=Debug`. After rebuilding and rerunning you may get more information on why there is a segmentation fault.

If you still get an error please include the logs, config, and run files in your help request. You can drag and drop text files into the comment box after renaming them to include suffix `.txt`. Please also include the full error message if it shows up on the screen (running interactively) rather than in a log file (such as slurm.out).

**Comment by zhifeng1310** [comment]
I get  a same error when I bulding with debug flag on, and my screen error message is ''段错误 (核心已转储)''.
[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/11514971/HEMCO_Config.rc.txt)
[gc.log](https://github.com/geoschem/geos-chem/files/11514973/gc.log)
[geoschem_config.yml.txt](https://github.com/geoschem/geos-chem/files/11514975/geoschem_config.yml.txt)

**Comment by yantosca** [comment]
@zhifeng1310: Have you [maxed out the stacksize memory](https://geos-chem.readthedocs.io/en/latest/getting-started/login-env-parallel.html?highlight=omp_stacksize) as described on geos-chem.readthedocs.io?  Also, if you are submitting your job to a computational queue you might need to request more memory.

**Comment by yantosca** [comment]
Closing out this issue.
