### ISSUE TITLE
HEMCO_HEMCO_Diagn_annual emissions of specific species

### ISSUE THREAD

**Issue by yangbyy** [geoschem/geos-chem#1803]
### Name and Institution (Required)

Name: bingyan yang
Institution:  Tianjin Normal University, Tianjin, China

- How does HEMCO get the annual emissions of specific species? 

For example, if I want to get the annual emissions of OC from CEDS inventory, what should I do? The output of HEMCO_Diagn. rc is in kg/m2/s, which looks more like the emission rate. I have carefully read the HEMCO user guide, but I am still not sure how to set it to get the annual emission. 
If anyone could help me, I will be very grateful!

**Comment by yantosca** [comment]
Thanks for writing @yangbyy.  You would take the kg/m2/s that HEMCO produces and convert it to kg/yr.   Multiply by the surface area (stored within the AREA variable in the HEMCO_Diagnostic file) * the number of seconds in a year.

**Comment by yangbyy** [comment]
Thank you for your reply! I just found that the _sum_emption. ipynb_  file in the src folder is the same as what you described. Thanks again!
