### ISSUE TITLE
Benchmark and standard difference

### ISSUE THREAD

**Issue by jiaying002** [geoschem/geos-chem#1807]
### Name and Institution (Required)

Name: Jiaying Li
Institution: Nanyang Technological University

### New GEOS-Chem feature or discussion
I found the GCClassic 14.0.0 10-yr benchmark here: http://ftp.as.harvard.edu/gcgrid/geos-chem/10yr_benchmarks/14.0.0/GCClassic/Restarts/

I used 2010 data to have a one-year spin-up for my simulation for 2010, and I found out that my result for ozone and OH is basically the same as the benchmark, while for PM2.5, the result is 3 times higher than the benchmark. Would you please give me an acceptable range of ratio between the benchmark and users' results (, like a 10 or 50% percentage difference), so I can check my result by myself in the future?

Thank you in advance!

**Comment by yantosca** [comment]
Thanks for writing @jiaying002.  The benchmark simulation uses both the simple SOA and the complex SOA simultaneously... although the complex SOA is only used for diagnostic output and is not allowed to impact the simulation results.  This allows us to diagnose any issues.

We would invite you to look at some of the benchmark plots and tables on our GEOS-Chem wiki.  Each of the X.Y.0 versions has a 1-month benchmark (and sometimes a 1-year benchmark depending on what was added).  A list of GEOS-Chem versions may be found here:

- https://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_versions

and when you go to each version's wiki page you can see the benchmark plots & tables associated with that version.
