### ISSUE TITLE
[QUESTION] Several small questions on compiling GEOS-Chem using GNU make

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/geos-chem#181]
Hi there,

Thanks for [addressing my concern of compiling a nested complexSOA_SVPOA simulation in GC 12.4.0 or earlier via unit tester](https://github.com/geoschem/geos-chem/issues/169). @msulprizio lastly replied me that I can compile within the top-level code directory by explicitly specifying NEST and SIM flags. I just want to confirm if it is also feasible to do similar practice within the rundir? I have tested `make -j4 mpbuild NEST=CH SIM=complexSOA_SVPOA` and it seemed did the job if only according to lastbuild.mp. I want your confirmation simply because I have not seen these OPTIONAL-FLAGS from `make help` output run from rundir. If it is the case, would it be great to inform that it is still fine to explicitly specify these kind of OPTIONAL-FLAGS to overwrite flags read by getRunInfo within rundir in the wiki? Would it be great to contain these OPTIONAL-FLAGS in `make help` output run from rundir? Currently it only has the following and seems indicate that only one (but actually one or more) can be specified.
```
----------------------------------------------------------
OPTIONAL-FLAGS may be one of the following:
----------------------------------------------------------
DEBUG=y           Compiles GEOS-Chem with various debugging options
BOUNDS=y          Compiles GEOS-Chem with out-of-bounds error checks
FPE=y             Compiles GEOS-Chem with floating-point math error checks
TRACEBACK=y       Compiles GEOS-Chem with traceback error printout (this is the default)
NO_ISO=y          Compiles GEOS-Chem and turns off ISORROPIA
TIMERS=1          Compiles GEOS-Chem with timers turned on
```

I have also carefully gone through your wiki on [compiling GEOS-Chem](http://wiki.seas.harvard.edu/geos-chem/index.php/Compiling_GEOS-Chem) and would appreciate your confirmation for my following concerns.

1. Using GC 12.5.0, I typed `make help` from rundir and top-level code dir, respectively. I have obtained the similar results for the top-level code dir case. However for rundir case, my `make help` output has the similar results as your wiki listed output for GC versions older than 12.4.0. I wonder if 12.4.0 is not the correct dividing version? Maybe 12.6.0 but I am not very sure...

2. I believe `make clean` and `make realclean` do the same thing either run from rundir or top-level code dir? but they are explained differently as follows. If so, would it be great to unify description, I just feel the first two lines are a bit ambiguous... although this is not that important...
```
clean             Makes "clean" in source code directory ODE_DIR
realclean         Makes "realclean" in the source code directory ODE_DIR

clean           Removes *.o, *.mod files in source code subdirs only
realclean       Removes all *.o, *mod, *.lib *.a, *.tex, *ps, *pdf files everywhere
```

3. When I learned [AWS tutorial](https://cloud-gc.readthedocs.io/en/latest/chapter02_beginner-tutorial/research-workflow.html#configure-unit-tester-and-generate-run-directory) previously I used `NC_DIAG=y` flag but I have not found this flag either from your wiki or `make help` output. Maybe the Makefile can tell me all the OPTIONAL-FLAGS that I can specify?

This might be the last question before Christmas. I really appreciate all of your help provided this year!!!

Yours faithfully,
Fei

**Comment by yantosca** [comment]
Thanks for writing.  We typically recommend compiling in the run directory, so that all applicable flags for the given simulation will be defined.

2.  Yes, Make clean and Make realclean do the same thing.
3. NC_DIAG=y is now always applied (I think since 12.2.0 and higher).

Also, FYI, we will be phasing out GNU Make in GEOS-Chem 13.0.0.  We will replace it with CMake, in order to be compatible with changes at GMAO. Therefore, we will no longer be actively supporting GNU Make.  

CMake is already added to 12.6.0 and higher versions, but we are not advertising it quite yet.

**Comment by FeiYao-Edinburgh** [comment]
> We typically recommend compiling in the run directory, so that all applicable flags for the given simulation will be defined.

But it is still fine to explicitly define them within rundir to overwrite flags read by getRunInfo? 

> Also, FYI, we will be phasing out GNU Make in GEOS-Chem 13.0.0.

Thanks for letting know!

**Comment by yantosca** [comment]
Also one clarification: "make clean" will just clean up *.o *.a *.mod *.x files in a single directory but "make realclean" will do a "make clean" for all subdirectories.

You can compile code from the code directory but then you have to always remember the flags for each simulation.  Which tends to confuse a lot of users... and which is why we recommend compiling from the run directory.

**Comment by FeiYao-Edinburgh** [comment]
> You can compile code from the code directory but then you have to always remember the flags for each simulation.

I totally understand it. I just want to make sure it is also fine to do so from **rundir**? For instance,  make -j4 mpbuild NEST＝ch SIM ＝complexSOA_SVPOA will overwrite NEST and SIM values read by getRunInfo？

Sorry for not having expressed my concerns.

**Comment by yantosca** [comment]
Hi Fei.  I have updated the compilation documents on the wiki.  Please see:  http://wiki.geos-chem.org/Compiling_GEOS-Chem.  I've added info about how to use CMake (which is in 12.6.0 and later) and GNU Make (which will be retired in 13.0.0).  Hopefully this will be more clear.

We are updating the manual as time allows.  Until we get to updating everything, a few pages may still have out-of-date info.  Please bear with us.

I will close this issue out for now but feel free to reopen.
