### ISSUE TITLE
Simple SOA and complex SOA result difference

### ISSUE THREAD

**Issue by jiaying002** [geoschem/geos-chem#1810]
### Name and Institution (Required)

Name: Jiaying Li
Institution: Nanyang Technological University

### New GEOS-Chem feature or discussion
This is a follow-up question for https://github.com/geoschem/geos-chem/issues/1795 and https://github.com/geoschem/geos-chem/issues/1807.
 
I used GEOS-Chem v14.0.0 with MERRA-2 data to run two 20 days of simulations from 20090701 to 20090720. I used the same restart file, and all the settings are the same except for the SOA. I created one directory using a standard model, and the other is a complex SOA. @yantosca said the results of complex SOA might have a small difference from the simple one since the secondary aerosol concentrations may result in a different aerosol optical depth, which gets fed into photolysis.

I found that results from simple and complex SOA can be different, ranging from 0 to 15%. For aerosols like OCPI and OCPO, the result is 0 difference. For H2O2 and HO2, the difference can be as high as 15% (complex SOA is larger). The difference for other species like PAN, NH4, and SO4 basically ranges from 1% to 10%.
![SEAOCPI9](https://github.com/geoschem/geos-chem/assets/113654537/d2c126d9-6deb-4d7f-b1ec-d4f73a255dbf
![SEAH2O28](https://github.com/geoschem/geos-chem/assets/113654537/66a6dc97-aaa4-46c6-a899-f71c0b606dab)

I wonder:
1) If the difference of around 15% can be treated as small?
2) If my simulation result is correct. I know it is a lot to ask, but would you please help me run it on your server to see if I did it correctly... I've literally been struggling for weeks...
3) If my simulation result is correct and the difference can not be treated as small, which one would you recommend users to use, regardless of the running time (honestly, they took basically the same amount of time...)?

Thank you so much for your time!!!

**Comment by yantosca** [comment]
Thanks for writing @jiaying002.  Your question is more of a science question and would be better posed to the GEOS-Chem Aerosols Working Group.  Tagging @wporter @theloniuspunk @beckyalexander.

**Comment by theloniuspunk** [comment]
The discussion of differences here focuses on gas-phase species, so I (Jeff Pierce) have less intuition here. A couple thoughts though.

- The reactions for complex SOA are explicitly tied in with gas-phase chemistry, hence there is a potential for directly chemistry impacts from the complex-SOA reactions. The simple SOA does not touch the gas-phase chemistry. Some of the simple SOA is formed upon emission, the rest is formed on a 1-day first-order timescale from a single advected "precursor" species.

- You mention using the same restart file for both simulations. Does the restart file have pre-spun-up values for both the complex SOA and simple SOA species? If not, the model will start with 0 values for the species, and there will be an associated spinup time, which could be a few weeks to over a month for the aerosols to find a new steady state.

- How much does the SOA vary between the two simulations? Is it consistent with Sid Pai's paper that compares the two schemes (https://doi.org/10.5194/acp-20-2637-2020)?

Jeff

**Comment by jiaying002** [comment]
@theloniuspunk @yantosca Thank you so much for your help!

I did not spin it up. After I spun up, the value maintained the difference I showed above. I carefully read the paper you provided, and I believe the difference between simple and complex SOA methods may cause that 0-20% value difference.

**Comment by theloniuspunk** [comment]
Ok, great!
