### ISSUE TITLE
Slowdown in GEOS-Chem 14.2.0

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#1814]
### Name and Institution (Required)

Name: Melissa Sulprizio
Institution: Harvard / GCST

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

The 1-month benchmarks for 14.2.0 alpha tags indicate a large increase in run time:

<img width="1353" alt="image001" src="https://github.com/geoschem/geos-chem/assets/4805437/4f9534e5-8c5b-46da-bd5e-ede40f0c9045">

<img width="388" alt="Screenshot 2023-05-31 at 10 23 59 AM" src="https://github.com/geoschem/geos-chem/assets/4805437/948820a5-821e-4ab2-be95-52fba1e60f8c">

The largest increase is seen in the gas-phase chemistry and came in with the PR #1620 to restore Iy sink reactions. We see another smaller increase in wall time after merging in PR #1702 to restore consideration of sea salt alkalinity to heterogenerous acid-catalyzed reactions of halogens on sea salt aerosols.

PR #1620 also included modifying the RTOL value in fullchem_mod.F90 from 0.5e-2 to 0.5e-3 to avoid convergence errors. However, since other chemistry updates have gone into 14.2.0, we may be able to restore RTOL to its previous value.

Tagging @yantosca @beckyalexander @viral211 for further comments.

**Comment by yantosca** [comment]
The wall time increases 01:20 in going from alpha.4 to alpha.5.  I took a look at the code but I didn't see anything that stands out that would have caused the slowdown.  In fact, I replaced several `(1.0_dp - H%f_Alk_SSA)` etc. expressions with `H%f_Acid_SSA`, where that is only computed once per grid box.  The increase in wall time might have also been due to the tolerance being so tight.

**Comment by msulprizio** [comment]
As a follow up, the model performance returns to 14.1.1 wall times after reverting RTOL (#1815).

<img width="1876" alt="Screenshot 2023-06-21 at 11 21 04 AM" src="https://github.com/geoschem/geos-chem/assets/4805437/248989b3-560b-48b8-a271-74cdcb04e25b">
