### ISSUE TITLE
How to add NOxTau diagnostic from HISTORY.rc in GEOS-Chem 14.1.1

### ISSUE THREAD

**Issue by Tan-ws** [geoschem/geos-chem#1818]
### Name and Institution (Required)

Name: Wanshan Tan 
Institution:Sun Yat-sen University

### Description of your issue or question
I wanna save NOx lifetime in GEOS-Chem 14.1.1 and added NOx diagnostic in HISTORY.rc like this:
```console
##==============================================================================
  NOxlifetime.template:       '%y4%m2%d2_%h2%n2z.nc4',
  NOxlifetime.frequency:      00000001 000000
  NOxlifetime.duration:       00000001 000000
  NOxlifetime.mode:           'time-averaged'
  NOxlifetime.fields:         'NOxTau             ',
```
But model reported errors:
```console
===============================================================================
GEOS-Chem ERROR: NOXTAU is not found in the registry for the DIAG object!
 -> at Registry_Lookup (in Headers/registry_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem ERROR: Could not locate NOxTau diagnostics state registry.
 -> History_AddItemToCollection (in History/history_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem ERROR: Could not add diagnostic "NOxTau" to collection: NOxlifetime
 -> at History_ReadCollectionData (in module History/history_mod.F90)

 -> ERROR occurred at (or near) line    121 of the HISTORY.rc file
===============================================================================

===============================================================================
GEOS-Chem ERROR: Error encountered in "History_ReadCollectionData"!
 -> at History_Init (in module History/history_mod.F90)
===============================================================================

===============================================================================
GEOS-CHEM ERROR: Error encountered in "History_Init"!
STOP at  -> at GEOS-Chem (in GeosCore/main.F90)
===============================================================================
```
I don't how to deal with this problem.
HISTORY.rc and GC.log are as follows.

Thanks for your help!

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.
[HISTORY.rc.txt](https://github.com/geoschem/geos-chem/files/11635590/HISTORY.rc.txt)
[GC.txt.log](https://github.com/geoschem/geos-chem/files/11635591/GC.txt.log)

**Comment by lizziel** [comment]
If there is interest community interest in making this diagnostic available beyond GEOS we could do that. All of the `MODEL_GEOS` blocks for it are in `state_diag_mod.F90` and `fullchem_mod.F90`.

**Comment by Tan-ws** [comment]
> Thanks for writing @Tan-ws. The NOxTau diagnostic is only used when running the NASA GEOS ESM. The code for this diagnostic is wrapped within
> 
> ```fortran-modern
> #ifdef MODEL_GEOS
> ... code goes here ...
> #endif
> ```
> 
> blocks, which only are activated when you compile GEOS-Chem for use with the NASA GEOS ESM.
> 
> If you wish to use this diiagnostic, you can try commenting out the #ifdef MODEL_GEOS blocks in which the NoxTau diagnostic code is defined (i.e. change `#ifdef` to `!#ifdef` and change `#endif` to `!#endif`. However we cannot assist you in debugging this.

Thanks for your reply. I have commented out  #ifdef MODEL_GEOS blocks and GEOS-Chem run successfully. But the result seems higher than reported NOx lifetime(Shah et al., ACP, 2020).

**Comment by Tan-ws** [comment]
> If there is interest community interest in making this diagnostic available beyond GEOS we could do that. All of the `MODEL_GEOS` blocks for it are in `state_diag_mod.F90` and `fullchem_mod.F90`.

Thanks for your reply.

**Comment by christophkeller** [comment]
Thanks for your interest in the NOxTau diagnostics, @Tan-ws. Note that this diagnostics is not equivalent to the method used in Shah et al. (2020). We added it for development / debugging purposes and it hasn't been evaluated in a lot of detail. Before making it available as a "general" diagnostics, it should be vetted more thoroughly. We are happy to help with that, if there is interest in this.

**Comment by Tan-ws** [comment]
> 

Ok, I get it now, thanks！

**Comment by Tan-ws** [comment]
> Thanks for your interest in the NOxTau diagnostics, @Tan-ws. Note that this diagnostics is not equivalent to the method used in Shah et al. (2020). We added it for development / debugging purposes and it hasn't been evaluated in a lot of detail. Before making it available as a "general" diagnostics, it should be vetted more thoroughly. We are happy to help with that, if there is interest.

Ok, I get it now, thanks！
