### ISSUE TITLE
[BUG/ISSUE] Boundary condition latitude range issue

### ISSUE THREAD

**Issue by ktravis213** [geoschem/geos-chem#182]
## Describe the bug
I am using v12.6.0 to run a nested Asia simulation.  When I output the boundary conditions, the longitudes are correct, but the latitudes have increased by 1. For my grid:
  BoundaryConditions.LON_RANGE:  60.0 150.0,
  BoundaryConditions.LAT_RANGE:  -11.0 55.0,::

The resulting boundary conditions in my first file, GEOSChem.BoundaryConditions.20160501_0000z.nc4
have limits for lon of 60 to 150 as specified, but -10 to 56 for lat.  

## To Reproduce
Include the steps that must be done in order to reproduce the observed behavior:
1. Run 2x25 simulation with the below Boundary Conditions specification.
```
#==============================================================================
# %%%%% THE BoundaryConditions COLLECTION %%%%%
#
# GEOS-Chem boundary conditions for use in nested grid simulations
#
# Available for all simulations
#==============================================================================
  BoundaryConditions.template:   '%y4%m2%d2_%h2%n2z.nc4',
  BoundaryConditions.format:     'CFIO',
  BoundaryConditions.frequency:  00000000 030000
  BoundaryConditions.duration:   00000001 000000
  BoundaryConditions.mode:       'instantaneous'
  BoundaryConditions.LON_RANGE:  60.0 150.0,
  BoundaryConditions.LAT_RANGE:  -11.0 55.0,::
  BoundaryConditions.fields:     'SpeciesBC_?ADV?             ', 'GIGCchem',
::
```
## Error messages
```
===============================================================================
GEOS-Chem ERROR: Invalid latitude subset values for collection " BoundaryConditions"!
 -> at History_ReadCollectionData (in module History/history_mod.F90)

 -> ERROR occurred at (or near) line    638 of the HISTORY.rc file
===============================================================================
```

**Comment by lizziel** [comment]
I think the issue is a typo in your HISTORY.rc file. 

`BoundaryConditions.LAT_RANGE: -11.0 55.0,::`

should be

`BoundaryConditions.LAT_RANGE: -11.0 55.0,`

Try removing the "::" and see if it solves the issue.

**Comment by yantosca** [comment]
Yes, the :: signals the end of a collection.  It should only go after the last diagnostic field listed in the .fields section.  If you place it anywhere else it will mess up the parsing of the HISTORY.rc file.

Maybe what we can do is to add a better error check for :: to make sure that it only comes at the end of a collection.
