### ISSUE TITLE
How to associate the Met_TropLev with the pressure levels in SpeciesConc_ to extract tropospheric data

### ISSUE THREAD

**Issue by JairoVS** [geoschem/geos-chem#1822]
### Discussed in https://github.com/geoschem/geos-chem/discussions/1821

<div type='discussions-op-text'>

<sup>Originally posted by **JairoVS** June  6, 2023</sup>
Hello everyone! Thank you for taking the time to read my question and providing any advice. I have recently started using Geoschem. I have run a nested simulation with 47 sigma levels. Now I want to extract tropospheric concentrations of some pollutants, but I am unsure how to proceed. 

I have already extracted the Met_TropLev variable from the StateMet collection. I want to use it to determine until which of the 47 vertical layers I should use for getting only tropospheric values from the SpeciesConc_. Units are different between the TropLev data and the Levels in SpeciesConc.

I have looked for related information on the discussions but have not found anything. I appreciate any help you can give me on this.</div>

**Comment by msulprizio** [comment]
Hi @JairoVS. The SpeciesConc collection provides species concentrations for each grid box with dimension lat,lon,lev. The Met_TropLev field from the State_Met collection provides the level of the tropopause. To obtain tropospheric concentration, you will want to use all values of SpeciesConc below the level specified for Met_TropLev. For more information on the diagnostics, please see our [Guide to GEOS-Chem History diagnostics](http://wiki.seas.harvard.edu/geos-chem/index.php/Guide_to_GEOS-Chem_History_diagnostics). Specifically:

- [The StateMet collection](http://wiki.seas.harvard.edu/geos-chem/index.php/History_collections_for_met_fields_and_related_quantities#The_StateMet_collection)
- [The SpeciesConc collection](http://wiki.seas.harvard.edu/geos-chem/index.php/History_collections_for_species_concentrations#The_SpeciesConc_collection)

**Comment by JairoVS** [comment]
Thank you very much @msulprizio for your prompt answer!

I appreciate your help. For example, for one of my grids, the value in Met_TropLev is 34.63 (Meaning that all the concentrations below this value are part of the troposphere). Then for the same grid in SpeciesConc, I have concentrations distributed in 47 eta levels ranging from 3.8e-5 at the top to 0.992 at the lowest level. How can I determine which of the 47 eta levels at SpeciesConc corresponds to the 34.63 in TropLev? 

I hope I am explaining my issue well, and again thank you so much for taking the time to read my answer and for any help you can provide.

**Comment by yantosca** [comment]
Thanks @JairoVS for your patience.  Our computer system underwent an OS upgrade and we've had to focus our attention on that in these days.

Thanks for your explanation.  What we typically do in post-simulation analysis is to take only the purely tropospheric levels.  So if Met_TropLev(I,J) = 34.63 at a certain (I,J) grid box, you can take the floor (discarding the decimal point and taking just the integer part).  So levels 1-34 are in the troposphere and 35-47 are in the stratosphere/mesosphere.

If you are doing this analysis in Python, I think there is a `numpy.floor()` function that you can use.

**Comment by JairoVS** [comment]
Thank you @yantosca, for your time and guidance! I understand; I was wondering if it was necessary to round up or down, but I will use the floor as you suggest. Yes, I am doing the analysis with Python; I will try to do this with numpy then. 

Since the number of (I,J) in the domain is high, and the Met_TropLev is specific for every (I, J),  is there a function or package that you could recommend to me for extracting only tropospheric values in every grid box of the SpeciesConc?

Again thank you very much for your support!

**Comment by yantosca** [comment]
You can use the routine `gcpy.grid.get_troposphere_mask`  to return a mask of grid boxes where it is troposphere

```python
import numpy as np
import xarray as xr
from gcpy.grid import get_troposphere_mask

# open files
ds_met = xr.dataset_open("/path/to/GEOSChem.StateMet.YYYYMMDD_hhmmz.nc4")
ds_spc = xr.dataset_open("/path/to/GEOSChem.SpeciesConcYYYYMMDD_hhmmz.nc4")

# Get numpy ndarray containing 1s or 0s depending on whether each grid box is tropospheric or not
tropmask = get_troposphere_mask(ds_met)

# Return a numpy ndarray containing tropospheric O3 (change for whatever other species you want)
trop_o3 = np.ma.masked_array(ds_met["SpeciesConc_O3"].values), tropmask)
```
etc.  You can look at the numpy and gcpy documentation. for more details.  Numpy works on whole arrays so it should be pretty fast.

**Comment by JairoVS** [comment]
Thank you @yantosca! I appreciate your guidance. I will do what you suggest to me.

**Comment by yantosca** [comment]
Thanks @JairoVS.  I will close out this issue.  Feel free to reach out again if you are still having problems.
