### ISSUE TITLE
Configure with CMake

### ISSUE THREAD

**Issue by ast222340** [geoschem/geos-chem#1825]
### Name and Institution (Required)

Name: Subhadeep Ghsoh
Institution:Indian Institute of Technology Delhi ,New Delhi,India

### Confirm you have reviewed the following documentation

- [ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)
      Confirm all above.
### Description of your issue or question
       Dear GEOS-Chem community sir,
### https://github.com/geoschem/geos-chem/assets/135971477/ebc13c0b-2b13-42a4-80d1-5289ff3bc44e
       Please help me,I don't understand,,,I tried many times.
### https://github.com/geoschem/geos-chem/assets/135971477/56290a46-5fd5-431c-839b-f8bdcb8e54df
       This is my hpc's Cmake version,,It would be great if there was some other way to model configure..because module load cmake/3.17.3-fasrc01 this is clearly mention in Geos-Chem Classic environment file page..Now what should I do??             

  GEOS-Chem version number - 14.1.1

**Comment by ast222340** [comment]
Try to apps/cmake/3.23.1/gnu: CMake 3.23.1 GNU this module,,showing error.
### https://github.com/geoschem/geos-chem/assets/135971477/3e167551-612e-4b11-9dd3-7965af1dd342

**Comment by yantosca** [comment]
Thank you @ast222340 for reaching out.  It looks like you don't have netcdf-fortran installed (or loaded).  I would check with your HPC cluster's IT staff if there is a version of netcdf-fortran present.  If you have a module system installed then there should be a command such as `module load netcdf-fortran` or similar.

Also, GEOS-Chem requires CMake version 3.13 or later.  If you are using an earlier version it should stop with an error.

**Comment by ast222340** [comment]
Thank you Sir.

**Comment by yantosca** [comment]
Thanks @ast222340.  I'll close out this issue.

**Comment by yantosca** [comment]
I'll also make sure we make a note of this in the documentation.

**Comment by ast222340** [comment]
yes sir..There is a problem with loading the module.The module I want may not be in our system but another module may be replaced.I installed these modules to run the GEOS-Chem Classic.
  1) lib/XScrnSaver/1.2.2
  2) suite/intel/parallelStudio/2020
  3) lib/intel/2020/pnetcdf/1.12.2
  4) lib/intel/2020/hdf5/1.12.1
  5) lib/intel/2020/netcdf/c-4.8.0-cxx-4.3.1-f-4.5.3
  Thank you sir...

**Comment by yantosca** [comment]
Thanks @ast222340. For GEOS-Chem Classic you don't need pnetcdf.  If there is a netcdf-c there should also be a netcdf-fortran.  You can ask your sysadmins.

**Comment by ast222340** [comment]
Thanks @yantosca for giving me suggestion.
