### ISSUE TITLE
Run GEOS-Chem Classic

### ISSUE THREAD

**Issue by ast222340** [geoschem/geos-chem#1830]
### Name and Institution (Required)

Name: Subhadeep Ghosh
Institution: indian institute of technology delhi

### Confirm you have reviewed the following documentation

- [ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)
     Done above
### https://github.com/geoschem/geos-chem/files/11742945/11.pdf 
        This problem is appearing every time I run it,why are invalid directory being mentioned again and again?we will always run in the         gc_4x5_merra2_fullchem directory.
        I don't know exactly what to do

**Comment by yantosca** [comment]
Thanks for your patience @ast222340.  Our computer cluster just underwent an OS upgrade and our attention has been focused on that in these days.

It looks like you are missing the `ExtData/CHEM_INPUTS` directory.  You can download this from:
http://geoschemdata.wustl.edu/ExtData/CHEM_INPUTS/

Also it looks like your data directory is on a scratch disk.  If that is so, then the data on this disk might be purged at regular intervals.  You can ask your system administrator for more information.

**Comment by ast222340** [comment]
Thank you sir. This time there is a problem with the HEMCO data. Each time one HEMCO data is downloading and inputting the model and showing one error again,by doing this I have created 34 folders so far,every time I am running,I am getting error every time.How do I have to download the HEMCO data every time,It takes a lot of time to come one by one,but I can do it one by one.Does it have any key short process?
I have added the picture of last time the error has come.
### https://github.com/geoschem/geos-chem/assets/135971477/30efe716-d53b-4425-ab5b-ffb9296e1fe5
### https://github.com/geoschem/geos-chem/assets/135971477/1103665b-c21b-4fe4-a82a-09144cbd1101
I have created these folders for now.

**Comment by ast222340** [comment]
Thank you sir @yantosca. No sir..I done with GEOS-Chem Classic not "dry-run".Now I have a problem.I can't run a year at a time,it's not possible.Because we have a limit for takeing nodes on our HPC.Below I have attached the line in model run and hpc job details.
qsub -IX -q low -P cas -l select=2:ncpus=2 -l walltime=24:00:00 
time -p ./gcclassic > GC.log 2>&1

when I run it,I only get 24 files..I need one year day by day file..simulating 2019-01-01 to 2019-12-31..But create from GEOSChem.SpeciesConc.20190101_0000z.nc4 to GEOSChem.SpeciesConc.20190124_0000z.nc4.
My problem is that when I restart and restart it starts creating the same file again on the first jan day..Sir,if do this,my one year simulation is not possible.If you tell me something about this,how can I do it?

**Comment by yantosca** [comment]
@ast222340: Are you running each stage of the simulation in the same run directory?  You will have to edit the geoschem_config.yml file so that the end date of the previous stage becomes the start date of the current stage.  Then it should not overwrite any of the data.

Also, it could be an issue with your queue system, where you reach the end of the job (or the job is terminated) and then the scheduler restarts the job.

**Comment by yantosca** [comment]
@ast222340: For a nested grid simulation you will need to create separate run directories for the global (4x5) and nested (0.5 x 0.625 or 0.25 x 0.3125) runs.

**Comment by ast222340** [comment]
@yantosca :Thank you sir.I have some doubts, it would be better if you say.If I don't create run directory for nested simulation,What would happen if it change the grid settings of that file geoschem_config.yml ,HISTORY.rc and HEMCO in Global model I was running?I have attached the GC.log file.

## GC.log(https://github.com/geoschem/geos-chem/files/12345230/GC.log)

**Comment by yantosca** [comment]
Closing out this issue
