### ISSUE TITLE
[FEATURE REQUEST] Use yml and incorporate other form elements in issue templates

### ISSUE THREAD

**Issue by lizziel** [geoschem/geos-chem#1831]
### Name and Institution (Required)

Name: Lizzie Lundgren
Institution: Harvard University

### New GEOS-Chem feature or discussion

This is non-urgent nice-to-have feature request for a rainy day.

Sometimes a submitted GitHub issue does not have all of the information that GCST requests, or has a format that is difficult to read. We could encourage better issue reports by using drop-down menus and comment boxes in our issue templates. To facilitate this we could also change from using markdown to yaml format in the template files.

An example of another model that does this is CAM in CESM. See [here](https://github.com/ESCOMP/CAM/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml&title=Put+brief+%28%3C65+char%29+bug+title+here%21) for what the user sees and [here](https://github.com/ESCOMP/CAM/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml?plain=1) for the template code.

GitHub documentation on this topic::
[Syntax for issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)
[Syntax for GitHub's form schema](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema)

**Comment by msulprizio** [comment]
Adding to that, it would be nice to remove the checklists asking users to verify that they've reviewed the docs and instead include an autoresponse pointing users to the documentation if they are reporting a bug. See: https://www.techielass.com/automate-your-replies-to-github-issues/.

**Comment by yantosca** [comment]
This has now been done in 14.4.0.  We can close out this issue.
