### ISSUE TITLE
Wet deposition error GEOS-Chem Classic 14.1.1

### ISSUE THREAD

**Issue by nicodgomez** [geoschem/geos-chem#1833]
Name: Nicolás Damián Gómez
Institution: Instituto de Investigaciones Fisicoquímicas Teóricas y Aplicadas

Hello I am performing full chemistry calculation within the period 2019-08-01 and 2019-09-01, while testing the new version of GeosChem Classic 14.1.1, and the calculation ends with the following error message regarding wet depositions,

```console
HEMCO: Opening /mnt/d/GCClassic14/ExtData/HEMCO/OFFLINE_LIGHTNING/v2020-03/MERRA2/2019/FLASH_CTH_MERRA2_0.5x0.625_2019_08.nc4
HEMCO WARNING: Data is treated as unitless, but file attribute suggests it is not: km-2 s-1. File: /mnt/d/GCClassic14/ExtData/HEMCO/OFFLINE_LIGHTNING/v2020-03/MERRA2/2019/FLASH_CTH_MERRA2_0.5x0.625_2019_08.nc4
--> LOCATION: HCOIO_READ (HCOIO_READ_STD_MOD.F90)
     - Found all A1     met fields for 2019/08/06 12:30
     - Found all A3cld  met fields for 2019/08/06 13:30
     - Found all A3dyn  met fields for 2019/08/06 13:30
     - Found all A3mstC met fields for 2019/08/06 13:30
     - Found all A3mstE met fields for 2019/08/06 13:30
     - Found all I3     met fields for 2019/08/06 15:00
     - DO_LINEAR_CHEM: Linearized chemistry at 2019/08/06 12:00
     - LINOZ_CHEM3: Doing LINOZ
---> DATE: 2019/08/06  UTC: 12:30  X-HRS:    876.500000
---> DATE: 2019/08/06  UTC: 13:00  X-HRS:    877.000000
     - Found all A1     met fields for 2019/08/06 13:30
     - DO_LINEAR_CHEM: Linearized chemistry at 2019/08/06 13:00
     - LINOZ_CHEM3: Doing LINOZ
---> DATE: 2019/08/06  UTC: 13:30  X-HRS:    877.500000
---> DATE: 2019/08/06  UTC: 14:00  X-HRS:    878.000000
     - Found all A1     met fields for 2019/08/06 14:30
     - DO_LINEAR_CHEM: Linearized chemistry at 2019/08/06 14:00
     - LINOZ_CHEM3: Doing LINOZ
---> DATE: 2019/08/06  UTC: 14:30  X-HRS:    878.500000
===============================================================================
WETDEP: ERROR at   26  21  46 for species  138 in area RESUSPENSION in middle levels
 LS          :  T
 PDOWN       :    0.0000000000000000     
 QQ          :    0.0000000000000000     
 ALPHA       :    0.0000000000000000     
 ALPHA2      :    0.0000000000000000     
 RAINFRAC    :    0.0000000000000000     
 WASHFRAC    :    0.0000000000000000     
 MASS_WASH   :    0.0000000000000000     
 MASS_NOWASH :    0.0000000000000000     
 WETLOSS     :   -0.0000000000000000     
 GAINED      :    0.0000000000000000     
 LOST        :    0.0000000000000000     
 DSpc(NW,:)  :    0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000     
 Spc(I,J,:N) :    0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000       -1.2849770293398076E-015  -8.0779888589528323E-017  -8.8102506812858465E-017  -5.3927902421794934E-017  -4.0545610791012624E-017  -1.0902801693807967E-017  -1.9886315234041463E-019  -4.6813203996063033E-021  -1.2808408875215489E-022  -1.0014770955386624E-024  -3.4022316965556948E-026  -1.1399429870965761E-028  -3.4706723627820576E-035  -1.6038990706864857E-038  -3.8985070819143704E-032  -5.0490856268728717E-032  -1.8687703134055252E-031
===============================================================================
===============================================================================
GEOS-Chem ERROR: Error encountered in wet deposition!
 -> at SAFETY (in module GeosCore/wetscav_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem ERROR: Error encountered in "Safety"!
 -> at Do_Complete_Reevap (in module GeosCore/wetscav_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem ERROR:
 -> at WetDep (in module GeosCore/wetscav_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem ERROR: Error encountered in "Wetdep"!
 -> at Do_WetDep (in module GeosCore/wetscav_mod.F90)
===============================================================================

===============================================================================
GEOS-CHEM ERROR: Error encountered in "Do_WetDep"!
STOP at  -> at GEOS-Chem (in GeosCore/main.F90)
===============================================================================
     - CLEANUP: deallocating arrays now...

-------------------------------------------------------------------------------
HEMCO 3.6.2 FINISHED.
Warnings (level 1 or lower):   1865
-------------------------------------------------------------------------------
```
**GEOS-Chem version**
14.1.1

**Software versions**
CMake version: 3.16.3
Compilers (Intel or GNU, and version): GNU 8.4.0
NetCDF version: 4.7.3

I attach the respective geoschem_config.yml, HEMCO_Config.rc, HISTORY.rc and GC.log files.

I am running Geos-Chem within Windows Subsystem for Linux in Windows 10.

I have tested the run with two different Restarts giving the same error. 

[geoschem_config.txt](https://github.com/geoschem/geos-chem/files/11776679/geoschem_config.txt)
[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/11776680/HEMCO_Config.txt)
[HISTORY.txt](https://github.com/geoschem/geos-chem/files/11776681/HISTORY.txt)
[GC.log](https://github.com/geoschem/geos-chem/files/11776692/GC.log)

The output is giving some negative and very small values, may it is related with this. I have read some other issues regarding wet deposition errors, but it is not clear to me the cause of error, and then, I could not find a solution. 

Thancks

**Comment by yantosca** [comment]
Thanks for writing @nicodgomez.  We do not have experience using GEOS-Chem (fullchem simulation) on WSL. 

There are couple of fixes going into 14.2.0.  What looks like is happening is that you are getting very small values up in the stratosphere (there is a  `WETLOSS     :   -0.0000000000000000 `,  which could be really a denormal number like -1e-300 or so. 

In GEOS-Chem 14.2.0, we added fixes into certain sea salt reactions to prevent removal of sea salt in the stratosphere (where concentrations are already very low).  You can follow the changes that we made in PR #1779.  That might help your simulation.

**Comment by nicodgomez** [comment]
Hello Bob Yantosca and thanck you for the quick response. Regarding the present issue I have recently completed the calculation using different timesteps for transport and chemistry, in the original calculation I have used a timestep of 1800 seg for transport, and 3600 seg for chemistry. This calculation presented the WETDEP ERROR. Doing the calculation with a timestep of 1200 seg for transport, and 2400 seg for chemistry, the WETDEP ERROR does not occur. 
I will try the same calculations with GCClassic 14.2.0 as you suggest, but I am not sure how to install this version, since the default version using git clone form github is 14.1.1. I do not have much experience using depositories from github. Is there a way to install version 14.2.0 using git clone?

I attach the new geoschem_config.yml file, which completes the calculation without error.

Thanck you. 

[geoschem_config_2.txt](https://github.com/geoschem/geos-chem/files/11849297/geoschem_config_2.txt)

**Comment by yantosca** [comment]
Thanks for the update @nicodgomez.  GEOS-Chem 14.2.0 is undergoing benchmarking right now (the 1-year benchmark is almost finished) and once it passes final approval it will be released.  There are a lot of changes in the chemistry in 14.2.0 as well. We wouild recommend waiting until the official 14.2.0 release.

Also, reducing the timesteps makes sense.  It could be that if you have very small concentrations in a grid box then at 1800 seconds dynamic timestep, a species could be completely removed from the box by either advection or wetdep, and thus you could get negatives floating around, which would wreak havoc on the chemistry.  Reducing the timestep is a good solution but it will increase the run time as you are doing more transport steps.

**Comment by yantosca** [comment]
Closing out this issue
