### ISSUE TITLE
Data on deaths from CO2 in the world

### ISSUE THREAD

**Issue by Reroque** [geoschem/geos-chem#1834]
Reginaldo Roque
Student Pos Graduate, USP-ESALQ

Hello, I'm doing a postgraduate work in Data Science, based on CO2 emissions x deaths around the world. I found your work and would like to gain access to the generated database to extract insights for my research. I would be very grateful and honored if you could make this data available to me, in return, I am willing to share the extracted data and participate in your research, if you so wish. Thanks in advance.

- [ ] [Contributing guidelines](https://geos-chem.readthedocs.io/en/stable/reference/CONTRIBUTING.html)

### New GEOS-Chem feature or discussion

Please provide a clear and concise overview of the discussion topic or new feature requested.

**Comment by yantosca** [comment]
Thank you for writing @Reroque.  The GEOS-Chem Support Team can only provide assistance with coding/technical issues.  

In general we do not store output from GEOS-Chem (except for the output from benchmark simulations).  However, you are welcome to download and run GEOS-Chem to generate the data that you need.  Please see instructions in https://geos-chem.readthedocs.org.   

If you are referring to work cited in a specific journal article, we would encourage you to contact the authors directly.

**Comment by yantosca** [comment]
Closing out this issue.
