### ISSUE TITLE
Issue with TotalOC diagnostics in GEOS-Chem v14.1.1

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/geos-chem#1836]
### Name and Institution (Required)

Name: Fei Yao
Institution: The University of Edinburgh

### Description of your issue or question

Dear GC team,

I recently attempted to archive `TotalOC` using full chemistry simulations in GEOS-Chem `v14.1.1`. However, I encountered an issue where all the values were zeros. It appears that this diagnostic has not been assigned proper values in `aerosol_mod.F90`.

I believe this issue may be related to this GitHub [issue](https://github.com/geoschem/geos-chem/issues/1806). I am using the simple SOA scheme. Should I use a formula like TotalOC=OCPI+OCPO+SOAS/OCFOPOA in another `IF`?

Thank you for your assistance.

Best regards,
Fei

**Comment by yantosca** [comment]
Thanks @FeiYao-Edinburgh.  I believe the TotalOC diagnostic is only activated when one of the complex SOA options are used. 

If you wish. you can modify the code using a formula such as the one listed above.

**Comment by yantosca** [comment]
Closing out this issue.

**Comment by FeiYao-Edinburgh** [comment]
Hi @yantosca I'm trying to modify the "TotalOC" diagnostic for simple SOA. I wonder why do we need the following "Zero out" for "TotalOC" but NOT for all other diagnostics like "TotalOA" before the "$OMP PARALLEL DO" section. Would commenting this "Zero out" break the "TotalOC" diagnostic?

```
    ! Zero out the totalOC diagnostic
    IF ( State_Diag%Archive_TotalOC ) THEN
       State_Diag%TotalOC = 0.0_fp
    ENDIF
```
