### ISSUE TITLE
GCAP2.0 data demand & How to fix meteorology year & Trace more species & Lon/Lat setting issue

### ISSUE THREAD

**Issue by jiaying002** [geoschem/geos-chem#1837]
### Name and Institution (Required)

Name: Jiaying Li
Institution: Nanyang Technological University

###New HEMCO feature or discussion
I am using GEOS-Chem v 14.0.0, and using GCAP2.0 to run my simulations. I wonder:

1. Current dataset (2040-2049 & 2090-2099) is really useful! People always stand on the shoulders of giants to continue exploring, so is it possible to provide more data (i.e., 2030-2039 & 2050-2059) for users to analyze? I believe scientists will contribute a lot more to our community based on that extra data in the near future.
2. I've read the HEMCO and GCClassic instructions carefully but cannot find how to fix the meteorology year. Would you please tell me what to do?
3. I saw there are options (tag O3, etc. )to trace ozone, CH4 and CO. Is there any way to trace other species (like PM2.5)?
4. I noticed the default setting of longitude and latitude is not the same between MERRA/GEOS-FP and GCAP2.0. I've tried the set the center 180 and half-sized polar boxes as true for GCAP2.0, and it could work. Would you please share with me if there is anything I ignored that led you to set the default setting as false?
![image](https://github.com/geoschem/geos-chem/assets/113654537/0d71133f-450f-4c36-97a6-8db58ade55fb)
 
@ltmurray @yantosca 
Thank you so much for reading! Looking forward to your reply!

**Comment by ltmurray** [comment]
Hi @jiaying002. All the CMIP6 emission files for all years and scenarios have been prepared and are available at `http://atmos.earth.rochester.edu/input/gc/ExtData/HEMCO/CMIP6/v2022-03`. Once I submit my latest publication, hopefully in the next few weeks, those will become the new default path in HEMCO_Config.rc.

If you're interested in additional meteorology (additional years and/or GISS-E2-1-R ensemble members), those are not difficult or time consuming for me to generate. However, they take up a tremendous amount of storage space (e.g., the MERRA-2 meteorology only exists for ~40 years and we're presently hosting 165 years of GCAP2 meteorology), so I will only serve them if there is a guarantee that they will be used in publications to justify the storage on the web server, and preferably if there is interest from multiple end users. Please send me an email to the GISS-GC listserv or to me directly to discuss your proposed application, what decades, scenarios and/or ensemble members you're interested in, and how you forsee use by the broader community.

**Comment by jiaying002** [comment]
@ltmurray Thank you so much for your reply! I sent you an email talking about my application for the data on Aug 2nd, 8 AM Manchester time from _jiaying002@e.ntu.edu.sg_. Would you please help me check if you have received my email?
