### ISSUE TITLE
Suggest renaming TOMAS binned aerosol species to include leading zero

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#1841]
### Name and Institution (Required)

Name: Melissa Sulprizio
Institution: Harvard/GCST

### Confirm you have reviewed the following documentation

- [x] [Contributing guidelines](https://geos-chem.readthedocs.io/en/stable/reference/CONTRIBUTING.html)

### New GEOS-Chem feature or discussion

The latest updates for the TransportTracer simulation (https://github.com/geoschem/geos-chem/pull/1816) rename sulfur hexafluoride from "SF6Tracer" to "SF6" for consistency with other models. This update causes the TOMAS simulation to fail integration tests because SF6 is also defined in `species_database_tomas.yml` to represent sulfate aerosol, size bin 6.

https://github.com/geoschem/geos-chem/blob/4722f288e90291ba904222f4bbe4fc216d17c34a/run/shared/species_database_tomas.yml#L944-L973

To avoid conflicts in species names, I suggest renaming the TOMAS species to something like SF06 (i.e. using a leading zero for size bins 1-9) and doing the same for the other binned aerosol species (AW, DUST, ECIL, ECOB, NK, OCIL, OCOB, SS).

Tagging @BettyCroft @theloniuspunk @yantosca for comments/concerns.

**Comment by BettyCroft** [comment]
Hi @msulprizio - I've discussed with @theloniuspunk and we are in agreement with this name change to use leading zeros for TOMAS species names. Tagging @yantosca for update. Thanks for your help with this issue!

**Comment by msulprizio** [comment]
Excellent. Thanks for confirming @BettyCroft and @theloniuspunk! I will proceed with making these updates and aim to get them into 14.2.1.

**Comment by yantosca** [comment]
I believe we can close this out as the tomas updates have been merged into the GEOS-Chem 14.3.0 development stream.
