### ISSUE TITLE
Forced exit from Rosenbrock error

### ISSUE THREAD

**Issue by petersherman123** [geoschem/geos-chem#1844]
Name: Peter Sherman
Institution: Harvard University

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

Hi, I'm using version 14.1.1 of GEOS-Chem and running into this forced exit issue on a specific day (November 15, 2019, 8:20 PM) on two separate simulations. I've attached the log file for reference [GC.log](https://github.com/geoschem/geos-chem/files/11849253/GC.log). This seems similar to [this issue](https://github.com/geoschem/geos-chem/issues/1315) though I'm using a version of GEOS-Chem that is beyond v 13.4.0.

Thanks,
Peter

**Comment by petersherman123** [comment]
Hi @yantosca, got it thanks! I tried switching over to the dev/14.2.0 branch, but running into 

```
[ 62%] Building Fortran object src/GEOS-Chem/KPP/fullchem/CMakeFiles/KPP.dir/fullchem_HetStateFuncs.F90.o
/n/holyscratch01/mcelroy_lab/Users/psherman/aviation_test/midres/Aviation_Jan_4/CodeDir/src/GEOS-Chem/KPP/fullchem/fullchem_RateLawFuncs.F90:1837:50:

 1837 |        area = H%ClearFr * H%aClArea * H%f_Acid_SSA
      |                                                  1
Error: ‘f_acid_ssa’ at (1) is not a member of the ‘hetstate’ structure; did you mean ‘h_conc_ssa’?
```

when running `make -j` after pulling from the new branch, creating a new run directory, and running `cmake ../CodeDir -DRUNDIR=..` in the build directory. Is there a step I'm missing here?

Thanks,
Peter

**Comment by viral211** [comment]
This seems related to the KPP error discussed in #1880.

**Comment by petersherman123** [comment]
Hi @viral211, yes when moving over to the dev/14.2.1 branch I'm running into several 

` Forced exit from Rosenbrock due to the following error:
 --> Step size too small: T + 10*H = T or H < Roundoff` 
 
 errors before it inevitably crashes. Should I hold off on running simulations until this has been resolved?
 
 Thanks!

**Comment by yantosca** [comment]
Closing out this issue
