### ISSUE TITLE
A bug in GEOS-Chem 2x2.5 methane simulation

### ISSUE THREAD

**Issue by lshen2009** [geoschem/geos-chem#1845]
### Name and Institution (Required)

Name: Lu Shen
Institution: Peking University

### Confirm you have reviewed the following documentation
Yes
### Description of your issue or question
**I got a bug when I run global 2x2.5 methane simulation (v14.1.1) driving by MERRA2 met fields.**

 Reading from existing stream: /home/shared/ExtData/GEOS_2x2.5/MERRA2/2019/08/MERRA2.20190816.A3cld.2x25.nc4
HEMCO: Entering GET_TIMEIDX (HCOIO_UTIL_MOD.F90) ( 6)
 Number of time slices found:            8
 Time slice range :    201908160130.00000        201908162230.00000
 Adjusted time stamp of field OPTDEPTH
 Time shift (YMDhms):            0           0           0           0          90           0
 Original Yr/Mt/Dy-Hr:Mn = 2019/08/16-00:00
 Adjusted Yr/Mt/Dy-Hr:Mn = 2019/08/16-01:30
          preferred datetime:  201908160130.
 Data is 3-hourly. Entire day will be read.
              selected tidx1:              1
    corresponding datetime 1:  201908160130.
              selected tidx2:              8
    corresponding datetime 2:  201908162230.
        assigned delta t [h]:              3
 local time?  F
HEMCO: Leaving GET_TIMEIDX (HCOIO_UTIL_MOD.F90) ( 6)
 Will read vertical levels            1  to           72
 Reading variable OPTDEPTH

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In Ncrd_4d_R4 #2:  NetCDF: HDF error
    327680         6

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Code stopped from DO_ERR_OUT (in module NcdfUtil/m_do_err_out.F90)

This is an error that was encountered in one of the netCDF I/O modules,
which indicates an error in writing to or reading from a netCDF file!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Then I go to check if the file is broken. I typed this**
[lshen@mgmt gc_2x25_47L_merra2_CH4]$ ncdump -h /home/shared/ExtData/GEOS_2x2.5/MERRA2/2019/08/MERRA2.20190816.A3cld.2x25.nc4
netcdf MERRA2.20190816.A3cld.2x25 {
dimensions:
	time = 8 ;
	lev = 72 ;
	lat = 91 ;
	lon = 144 ;
variables:
	int time(time) ;
		time:calendar = "gregorian" ;
		time:long_name = "time" ;
		time:standard_name = "time" ;
		time:units = "minutes since 2019-08-16 00:00:00.0" ;
		time:delta_t = "0000-00-00 03:00:00" ;
		time:begin_date = "20190816" ;
		time:begin_time = "000000" ;
		time:time_increment = "030000" ;
	float lev(lev) ;
		lev:long_name = "levels" ;
		lev:standard_name = "levels" ;
		lev:units = "1" ;
	float lat(lat) ;
		lat:long_name = "latitude" ;
		lat:standard_name = "latitude" ;
		lat:units = "degrees_north" ;
	float lon(lon) ;
		lon:long_name = "longitude" ;
		lon:standard_name = "longitude" ;
		lon:units = "degrees_east" ;
	float CLOUD(time, lev, lat, lon) ;
		CLOUD:long_name = "cloud_fraction_for_radiation" ;
		CLOUD:standard_name = "cloud_fraction_for_radiation" ;
		CLOUD:units = "1" ;
		CLOUD:gamap_category = "GMAO-3D$" ;
		CLOUD:missing_value = 1.e+15f ;
		CLOUD:_FillValue = 1.e+15f ;
		CLOUD:scale_factor = 1.f ;
		CLOUD:add_offset = 0.f ;
	float OPTDEPTH(time, lev, lat, lon) ;
		OPTDEPTH:long_name = "in_cloud_optical_thickness" ;
		OPTDEPTH:standard_name = "in_cloud_optical_thickness" ;
		OPTDEPTH:units = "1" ;
		OPTDEPTH:gamap_category = "GMAO-3D$" ;
		OPTDEPTH:missing_value = 1.e+15f ;
		OPTDEPTH:_FillValue = 1.e+15f ;
		OPTDEPTH:scale_factor = 1.f ;
		OPTDEPTH:add_offset = 0.f ;
	float QI(time, lev, lat, lon) ;
		QI:long_name = "mass_fraction_of_cloud_ice_water" ;
		QI:standard_name = "mass_fraction_of_cloud_ice_water" ;
		QI:units = "kg kg-1" ;
		QI:gamap_category = "GMAO-3D$" ;
		QI:missing_value = 1.e+15f ;
		QI:_FillValue = 1.e+15f ;
		QI:scale_factor = 1.f ;
		QI:add_offset = 0.f ;
	float QL(time, lev, lat, lon) ;
		QL:long_name = "mass_fraction_of_cloud_liquid_water" ;
		QL:standard_name = "mass_fraction_of_cloud_liquid_water" ;
		QL:units = "kg kg-1" ;
		QL:gamap_category = "GMAO-3D$" ;
		QL:missing_value = 1.e+15f ;
		QL:_FillValue = 1.e+15f ;
		QL:scale_factor = 1.f ;
		QL:add_offset = 0.f ;
	float TAUCLI(time, lev, lat, lon) ;
		TAUCLI:long_name = "in_cloud_optical_thickness_for_ice_clouds" ;
		TAUCLI:standard_name = "in_cloud_optical_thickness_for_ice_clouds" ;
		TAUCLI:units = "1" ;
		TAUCLI:gamap_category = "GMAO-3D$" ;
		TAUCLI:missing_value = 1.e+15f ;
		TAUCLI:_FillValue = 1.e+15f ;
		TAUCLI:scale_factor = 1.f ;
		TAUCLI:add_offset = 0.f ;
	float TAUCLW(time, lev, lat, lon) ;
		TAUCLW:long_name = "in_cloud_optical_thickness_for_liquid_clouds" ;
		TAUCLW:standard_name = "in_cloud_optical_thickness_for_liquid_clouds" ;
		TAUCLW:units = "1" ;
		TAUCLW:gamap_category = "GMAO-3D$" ;
		TAUCLW:missing_value = 1.e+15f ;
		TAUCLW:_FillValue = 1.e+15f ;
		TAUCLW:scale_factor = 1.f ;
		TAUCLW:add_offset = 0.f ;

// global attributes:
		:Title = "MERRA2 time-averaged 3-hour cloud parameters (A3cld), processed for GEOS-Chem input" ;
		:Contact = "GEOS-Chem Support Team (geos-chem-support@as.harvard.edu)" ;
		:References = "www.geos-chem.org; wiki.geos-chem.org" ;
		:Filename = "MERRA2_Glob" ;
		:History = "File generated on: 2019/10/01 19:46:12 GMT-0300" ;
		:ProductionDateTime = "File generated on: 2019/10/01 19:46:12 GMT-0300" ;
		:ModificationDateTime = "File generated on: 2019/10/01 19:46:12 GMT-0300" ;
		:Format = "NetCDF-4" ;
		:SpatialCoverage = "global" ;
		:Conventions = "COARDS" ;
		:Version = "MERRA2" ;
		:VersionID = "5.12.4" ;
		:Nlayers = "72" ;
		:Start_Date = "20190816" ;
		:Start_Time = "00:00:00.0" ;
		:End_Date = "20190816" ;
		:End_Time = "23:59:59.99999" ;
		:Delta_Time = "030000" ;
		:Delta_Lon = "2.5" ;
		:Delta_Lat = "2" ;
}

**Do you know how to fix this bug? Thank you!**

**Comment by lshen2009** [comment]
Problem solved after re-downloading the file.

**Comment by msulprizio** [comment]
Excellent. Thanks for letting us know @lshen2009!
