### ISSUE TITLE
Libraries and met data for compiling and running GCC on Pleiades

### ISSUE THREAD

**Issue by hannahnesser** [geoschem/geos-chem#1851]
### Name and Institution (Required)

Name: Hannah Nesser
Institution: JPL

### Confirm you have reviewed the following documentation

- [x] [Contributing guidelines](https://geos-chem.readthedocs.io/en/stable/reference/CONTRIBUTING.html)

### New GEOS-Chem feature or discussion

I am attempting to compile and run GEOS-Chem classic on Pleiades. @yantosca advised me that the environment files with the necessary libraries may have already been prepared for Pleiades, and suggested I contact @SaptSinha and @1Dandan.

I was also curious if met fields have already been downloaded somewhere on Pleiades, and if so, at what path these can be found. If the time period/resolution I need isn't available, I was also wondering if I should publicize the location of any met data I download.

Thanks for any guidance that can be provided.

**Comment by yantosca** [comment]
Also if there are any environment files (i.e. with `module load` statements) we can add those to the `runScriptSamples/operational_examples` rundir folders for GCClassic and GCHP.  Let us know.

**Comment by 1Dandan** [comment]
Sure, I have wrote some tips for running GCHP on nasa pleiades https://acag.readthedocs.io/en/latest/tips_for_pleiades.html
which contains the environment files and path for some met and emission inputs for GCHP.

Also attaching the submitting scripts I used here: 
[run-600.pbs.txt](https://github.com/geoschem/geos-chem/files/11994369/run-600.pbs.txt)

**Comment by lizziel** [comment]
Thanks @1Dandan. Do you also have an environment file for Pleiades? And would you like your run script to replace the [existing sample run script](https://github.com/geoschem/geos-chem/blob/dev/14.2.0/run/GCHP/runScriptSamples/operational_examples/nasa_pleiades/gchp.pleiades.run) that is included in GEOS-Chem?

Note that your run script has a different approach for doing similar things as our sample run scripts (e.g. [here](https://github.com/geoschem/geos-chem/blob/dev/14.2.0/run/GCHP/runScriptSamples/gchp.batch_job.sh)). This is fine but may make it harder to keep up-to-date since GCST will not edit non-standard run scripts for new versions. An example of such an edit is in [this PR](https://github.com/geoschem/geos-chem/pull/1868). I recommend taking a look at why the run scripts differ and removing differences where possible.

**Comment by 1Dandan** [comment]
Hi @lizziel, sure, I created a module file to load relevant environments for GCHP simulations. The module file is located under `/u/dzhang8/modulefiles/GCHPenv/2023-04.Intel` with specific content of:
```
#%Module
 
proc ModulesHelp { } {
   puts stderr  "GEOS-Chem High Performance (GCHP) build and runtime environment."
}
 
module-whatis   "GCHP build and runtime dependencies"
 
module load git/2.30.2
module load cmake/3.23.1-TOSS4
module load other/manage_externals
module load other/mepo
module load other/gh
module load ImageMagick/7.0.8-53

module load comp-gcc/11.2.0-TOSS4
module load comp-intel/2020.4.304
module load mpi-hpe/mpt
module load hdf4/4.2.12
module load hdf5/1.8.18_mpt
module load netcdf/4.4.1.1_mpt
 
setenv  COMPILER                intel
setenv  CC                      icc
setenv  CXX                     icpc
setenv  FC                      ifort
setenv  F90                     ifort
setenv  F77                     ifort
setenv  CMAKE_PREFIX_PATH       /nobackup/dzhang8/software/esmf-8.3.1/install
 
set     version         2023.04-intel
```

Loading the environment can be achieved by:
```
#======================================================
# load GCHP simulation environment 
#======================================================
 
module --force purge
module use -a /nobackup/gmao_SIteam/modulefiles
module use -a /u/dzhang8/modulefiles
module load GCHPenv/2023-04.Intel
```

For the operational examples, it looks good to me. Maybe only adding the following environmental setting is enough:
```
export MPI_LAUNCH_TIMEOUT=40
export PATH=$PATH:/u/scicon/tools/bin

export FOR_IGNORE_EXCEPTIONS=false
export MPI_COLL_REPRODUCIBLE
unset MPI_MEMMAP_OFF
unset MPI_NUM_MEMORY_REGIONS
export MPI_XPMEM_ENABLED=yes
unset SUPPRESS_XPMEM_TRIM_THRESH
unset PMI_RANK
```
which is originally from @mathomp4 in the ticket of https://github.com/GEOS-ESM/MAPL/issues/1005.

**Comment by yantosca** [comment]
Closing out this issue as resolved
