### ISSUE TITLE
Overlay regional emissions_Country Mask

### ISSUE THREAD

**Issue by yangbyy** [geoschem/geos-chem#1853]
### Name and Institution (Required)

Name: Shuangqin Yang
Institution: Tianjin Normal University, China
Run Directory: gc_4x5_47L_merra2_fullchem_complexSOA_SVPOA (also turned on RRTMG)
Simulation Date: from 20190701 000000 to  20190701 010000 
GCClassic: v14.0.0
HEMCO: v3.5
I am trying to add the MIX list to the GCClassic model, and despite the fact that I have downloaded the MIX country mask file (MIX_Asia_mask.generic.025x025.nc) and data (MIX_Asia_OC.generic.025x025.nc) to the appropriate location in the ExtData folder, the program runs with the error: HEMCO ERROR: Cannot find field MIX_OC_POW. Please check variable name in the config. file.
![image](https://github.com/geoschem/geos-chem/assets/115625689/e4f41e86-34e8-481e-a9d7-5952398bcc2a)

Here is a screenshot of my HEMCO_Config.rc file.
![image](https://github.com/geoschem/geos-chem/assets/115625689/77e7d8a8-74b4-42f8-9631-fc1736ab10af)
![582a5537ebbad461da3b3d50cbb9cc3](https://github.com/geoschem/geos-chem/assets/115625689/7dc4100b-0628-4dce-96ab-729098c905d7)
![image](https://github.com/geoschem/geos-chem/assets/115625689/fa2bddcb-b0c7-4995-adc4-2328329790d3)

These files will help you better understand my troubles. Thanks in advance!
[GC.txt](https://github.com/geoschem/geos-chem/files/11901783/GC.txt)
[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/11901784/HEMCO_Config.txt)
[HEMCO_Diagn.txt](https://github.com/geoschem/geos-chem/files/11901786/HEMCO_Diagn.txt)
[HISTORY.txt](https://github.com/geoschem/geos-chem/files/11901787/HISTORY.txt)
[species_database.txt](https://github.com/geoschem/geos-chem/files/11901789/species_database.txt)

**Comment by yangbyy** [comment]
I seemed to know what caused the error. I deleted some code in the MASK section, re-downloaded the data, and the program suddenly worked.

**Comment by yantosca** [comment]
Thanks for the update @yangbyy.  Glad it worked!
