### ISSUE TITLE
[Bugfix] Move EDGAR REF_TRF from OtherAnthropogenic to Oil emissions category for CH4 simulation

### ISSUE THREAD

**Issue by nicholasbalasus** [geoschem/geos-chem#1855]
### Name and Institution (Required)

Name: Nicholas Balasus
Institution: Harvard University

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Currently, for the default HEMCO configuration for the CH4 simulation (ignoring regional inventories), GFEIv2 is used for Oil, Gas, and Coal and all other anthropogenic emissions come from EDGAR. One of our included _Other Anthropogenic_ files from EDGAR is REF_TRF (Oil refineries and Transformation Industry, IPCC 2006 codes of 1A1b+1A1ci+1A1cii+1A5biii+1B1b+1B2aiii6+1B2biii3+1B1c). [GFEIv2](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/HH4EUM) includes all 1B1 and 1B2 sector emissions, meaning that including REF_TRF is (partially) double counting. I suggest we move it into the EDGAR Oil emissions category so it is superseded by GFEIv2 Oil.

**Comment by yantosca** [comment]
Thanks @nicholasbalasus for bringing this to our attention.  Tagging @msulprizio.

**Comment by msulprizio** [comment]
I have confirmed with @nicholasbalasus that this is a bug. We will implement the fix in 14.2.1.

**Comment by yantosca** [comment]
PR #1856 has now been merged into the 14.2.1 development stream.  We can now close this issue.
