### ISSUE TITLE
Question about simulation output

### ISSUE THREAD

**Issue by Fearlessssssss** [geoschem/geos-chem#1859]
### Name and Institution (Required)

Name:Tyler
Institution:THU

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

Hi, everyone. I wonder where can I get the output of CCN concentration or number concentrations of particles? I haven't seen the related collections in HISTORY.rc. Is it Ok to get the output of these fields directly?

**Comment by yantosca** [comment]
Thanks for writing @Fearlessssssss.  I believe that you would need to run one of the microphysics simulations (either APM or TOMAS) to be able to save out CCN.  You might want to contact the Aerosols Working Group for further guidance.  Tagging @theloniuspunk @bettycroft

**Comment by theloniuspunk** [comment]
Hi Tyler, this is Jeff Pierce. If you run with TOMAS, you can calculate CCN offline from the output (number and composition in each size bin). You can also calculate CCN offline from the standard aerosol scheme, but you need to assume a size distribution for each species (some assumptions on how to do that are here: https://doi.org/10.1002/2016JD025886). As far as I know CCN are not calculated online for any run option (perhaps they are for the APM scheme).

**Comment by Fearlessssssss** [comment]
Got it, thanks a lot!
