### ISSUE TITLE
Missing data for biovoc

### ISSUE THREAD

**Issue by Fearlessssssss** [geoschem/geos-chem#1861]
### Name and Institution (Required)

Name:Tyler
Institution:

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.
The data HEMCO/OFFLINE_BIOVOC/v2021-12/0.5x0.625/2018/01/biovoc_05.20180114 is incomplete, the dimension of time is only 16 not 24.

**Comment by Fearlessssssss** [comment]
The data HEMCO/OFFLINE_BIOVOC/v2021-12/0.5x0.625/2018/01/biovoc_05.20180822 is incomplete as well

**Comment by SaptSinha** [comment]
The following files are now rectified and can be accessed from the [2018/01](http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_BIOVOC/v2021-12/0.5x0.625/2018/01/) and [2018/08](http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_BIOVOC/v2021-12/0.5x0.625/2018/08/) pages:

biovoc_05.20180114.nc
biovoc_05.20180814.nc
biovoc_05.20180822.nc

**Comment by yantosca** [comment]
Thanks @SaptSinha and @Fearlessssssss.  I'll close out this issue now that the files have been restored.

**Comment by JFBrewer** [comment]
Hi Bob - I just wanted to flag that somehow this issue seems to have re-surfaced. 20180114 definitely only has 16 hours worth of data on the WASHU and Harvard data repositories as well as the link that you included in the above post, and it looks like 20180814 and 20180822 are too small, as well. Each file should be about 53 MB but the incomplete ones are much smaller.
