### ISSUE TITLE
Significant difference between input flux vs HEMCO_diagnostics.xxxxxxx.nc in carbon mass

### ISSUE THREAD

**Issue by kimm1na** [geoschem/geos-chem#1862]
### Name and Institution (Required)

Name: Mina Kim
Institution: Seoul National Univ. in South Korea

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

----------------------------
Let's say (A) is converted to mass (PgC/year) by multiplying NEE flux (kg/m2/s) entered in 
HEMCO_Config.rc by area.

When creating A, the area is:
```
ct = xr.open_dataset('./my_NEE_file.nc')

# mass conversion
lon = ct['lon'] ; lat = ct['lat']

ceds_area = np.zeros((len(lat),len(lon)))
dlat = lat[1] - lat[0]
dlon = lon[1] - lon[0]
for j in range(len(lat)):
     sedge = (lat[j] - dlat/2.) * np.pi/180.
     nedge = (lat[j] + dlat/2.) * np.pi/180.
     ceds_area[j,:] = dlon * (np.pi/180.) * (6.375e+6)**2. * (np.sin(nedge)-np.sin(sedge))
```

Let's say that (B) is converted to mass (PgC/year) by multiplying the emissions (kg/m2/s) of the HEMCO_diagnostics.xxxxxxx.nc file by the AREA attached to the file.

A and B should be the same, but there is a difference of about 0.1 to 0.5 PgC/year. 
(ex. -3.5PgC/year vs -4.0PgC/year)

In the case of other input data such as fossil fuels and oceans, there was only an error of about 0.01.

Only NEE flux has this phenomenon. What is the reason?

**Comment by yantosca** [comment]
Thanks for writing @kimm1na.  Can you print out the sum of the area that you computed vs. the area from the HEMCO_Diagnostics file?

Printing out the area from the HEMCO_Diagnostics file I get this value:
```python
$ python
Python 3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:39:48) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import xarray as xr
>>> ds = xr.open_dataset("HEMCO_diagnostics.201907010000.nc")
>>> print(np.sum(ds["AREA"]))
<xarray.DataArray 'AREA' ()>
array(5.10065625e+14)
>>> 
```
If your conputed area does not match the AREA from the HEMCO diagnostics then this could be causing the differences that you observe.

GEOS-Chem and HEMCO use this algorithm for computing the surface area:
```F90
    !======================================================================
    ! Compute grid box surface areas
    !
    ! The surface area of a grid box is derived as follows:
    !
    !    Area = dx * dy
    !
    ! Where:
    !
    !    dx is the arc length of the box in longitude
    !    dy is the arc length of the box in latitude
    !
    ! Which are computed as:
    !
    !    dx = r * delta-longitude
    !       = ( Re * cos[ YMID[J] ] ) * ( 2 * PI / IIIPAR )
    !
    !    dy = r * delta-latitude
    !       = Re * ( YEDGE[J+1] - YEDGE[J] )
    !
    ! Where:
    !
    !    Re         is the radius of the earth
    !    YMID[J]    is the latitude at the center of box J
    !    YEDGE[J+1] is the latitude at the N. Edge of box J
    !    YEDGE[J]   is the latitude at the S. Edge of box J
    !
    ! So, the surface area is thus:
    !
    !    Area = ( Re * cos( YMID[J] ) * ( 2 * PI / IIIPAR ) *
    !             Re * ( YEDGE[J+1] - YEDGE[J] )
    !
    !    2*PI*Re^2    {                                            }
    ! = ----------- * { cos( YMID[J] ) * ( YEDGE[J+1] - YEDGE[J] ) }
    !     IIIPAR      {                                            }
    !
    ! And, by using the trigonometric identity:
    !
    !    d sin(x) = cos x * dx
    !
    ! The following term:
    !
    !    cos( YMID[J] ) * ( YEDGE[J+1] - YEDGE[J] )
    !
    ! May also be written as a difference of sines:
    !
    !    sin( YEDGE[J+1] ) - sin( YEDGE[J] )
    !
    ! So the final formula for surface area of a grid box is:
    !
    !            2*PI*Re^2    {                                     }
    !    Area = ----------- * { sin( YEDGE[J+1] ) - sin( YEDGE[J] ) }
    !              IIIPAR     {                                     }
    !
    !
    ! NOTES:
    ! (1) The formula with sines is more numerically stable, and will
    !      yield identical global total surface areas for all grids.
    ! (2) The units are determined by the radius of the earth Re.
    !      if you use Re [m], then surface area will be in [m2], or
    !      if you use Re [cm], then surface area will be in [cm2], etc.
    ! (3) The grid box surface areas only depend on latitude, as they
    !      are symmetric in longitude.  To compute the global surface
    !      area, multiply the surface area arrays below by the number
    !      of longitudes (e.g. IIIPAR).
    ! (4) At present, assumes that GEOS-Chem will work on a
    !      Cartesian grid.
    !
    ! (bmy, 4/20/06, 2/24/12)
    !======================================================================

    ! Loop over horizontal grid
    DO J = 1, State_Grid%NY
    DO I = 1, State_Grid%NX

       ! Sine of latitudes at N and S edges of grid box (I,J)
       SIN_N = SIN( State_Grid%YEdge_R(I,J+1) )
       SIN_S = SIN( State_Grid%YEdge_R(I,J  ) )

       ! Difference of sin(latitude) at N and S edges of grid box
       SIN_DIFF = SIN_N - SIN_S

       ! Grid box surface areas [m2]
       State_Grid%Area_M2(I,J) = ( State_Grid%DX * PI_180 ) * &
                                   ( Re**2 ) * SIN_DIFF

    ENDDO
    ENDDO
```

**Comment by yantosca** [comment]
Also the physical constants are in `Headers/physconstants.F90` in the GEOS-Chem source code.  GEOS-Chem passes the surface area thus computed to HEMCO.

**Comment by kimm1na** [comment]
@yantosca , 

Thank you for quick response.
My area calculation method is as follows.

-----------
In [2]: ct = xr.open_dataset('/veloce2/mak/storage/INVE
   ...: NTORY/LANDSINK/SiB3_3hr_ct_0215.nc')

In [3]: # mass conversion
   ...: lon = ct['lon']
   ...: lat = ct['lat']
   ...:
   ...: ceds_area = np.zeros((len(lat),len(lon)))
   ...: dlat = lat[1] - lat[0]
   ...: dlon = lon[1] - lon[0]
   ...: for j in range(len(lat)):
   ...:     sedge = (lat[j] - dlat/2.) * np.pi/180.
   ...:     nedge = (lat[j] + dlat/2.) * np.pi/180.
   ...:     ceds_area[j,:] = dlon * (np.pi/180.) * (6.3
   ...: 75e+6)**2. * (np.sin(nedge)-np.sin(sedge))
   ...:

In [4]: ceds_area.sum()
Out[4]: 510705155749190.75

In [5]: hemco_diag_file = xr.open_dataset('/veloce2/mak
   ...: /storage/GC_model_output/co2_2015_2020/state_ve
   ...: ctor_odiac/HEMCO_diagnostics.201501010000.nc')

In [6]: hemco_diag_file['AREA'].sum()
Out[6]:
<xarray.DataArray 'AREA' ()>
array(5.10065625e+14)

In [7]: ceds_area.sum()/hemco_diag_file['AREA'].sum()
Out[7]:
<xarray.DataArray 'AREA' ()>
array(1.00125382)

-----------
The error for the area is only about 1%.

Above all, for other fluxes, including fossil fuel, the mass of the input file and the mass calculated from hemco_diagnostic were almost the same (around 1%).

Errors of this magnitude only happen to NEE fluxes..
Perhaps some error occurs when NEE flux is applied in the model?

thank you

**Comment by yantosca** [comment]
Thanks @kimm1na.  I think the 1% differences in area might be explained by the difference in physical constants:
In your code you are using np.pi:
```console
print(np.pi)
3.141592653589793 
```
but in GEOS-Chem `physconstants.F90` we use:
```F90
REAL(fp), PARAMETER :: PI     = 3.14159265358979323_fp
```
and you are using 6.375e6 but in GEOS-Chem we use:
```F90
REAL(fp), PARAMETER :: Re = 6.3710072e+6_fp               ! was 6.375e+6_fp
```
The parameter values in GEOS-Chem come from the NIST recommended values.

Also the AREA value in the HEMCO_diagnostics file has 4-byte precision,m whereas your ceds_area has 8-byte precision.  This is because HEMCO currently saves all data to diagnostic outputs as 4-byte precision.    So there may be some roundoff going on.

**Comment by yantosca** [comment]
Closing out this issue
