### ISSUE TITLE
GEOS-Chem（14.1.1）tagged CH4——The total concentration of each tracer is not equal to the concentration of Total methane

### ISSUE THREAD

**Issue by Hugh-Su** [geoschem/geos-chem#1863]
### Name and Institution (Required)

Name: Hugh Su
Institution: Institute for Environment and Climate Research, Jinan University
   
I used the GEOS-Chem chemical transport model ( 14.1.1 ) tagged CH4 simulation to understand the contribution of each emission source to the total amount of methane, simulated over 2021-2022.

I found that the concentration values of each tracer ( CH4 _ OIL, CH4 _ GAS, CH4 _ COL, CH4 _ LIV, CH4 _ LDF, CH4 _ WST, CH4 _ RIC, CH4 _ OTA, CH4 _ BBN, CH4 _ WTL, CH4 _ SEE, CH4 _ LAK, CH4 _ TER and CH4 _ SAB ) in the generated GEOSChem.Restart file and GEOSChem.SpeciesConc file do not add up to the concentration value of ' Total methane '. 

The current situation is that the concentration of these tracers accounts for only a very small part of ' Total methane '. This makes me confused.

I wonder if my initial GEOSChem.Restart file is not right ? Is there a successfully tested GEOSChem.Restart file available for me to use ? 

I wonder if the concentration of these tracers is actually only a very small part of ' Total methane ' ( CH4 ) ?

**Comment by msulprizio** [comment]
Hi @Hugh-Su. The GCST does not maintain spun up restart files for all specialty simulation types, including the tagCH4 simulation. We ask that the user community provide those. If you don't receive a response from any community members here, you may also try emailing the [Carbon Working Group](http://wiki.seas.harvard.edu/geos-chem/index.php/Carbon_Cycle_Working_Group). Short of that, we would recommend you spin up your own restart file.

**Comment by Hugh-Su** [comment]
> Hi @Hugh-Su. The GCST does not maintain spun up restart files for all specialty simulation types, including the tagCH4 simulation. We ask that the user community provide those. If you don't receive a response from any community members here, you may also try emailing the [Carbon Working Group](http://wiki.seas.harvard.edu/geos-chem/index.php/Carbon_Cycle_Working_Group). Short of that, we would recommend you spin up your own restart file.

Hi @msulprizio . Is the sum of the concentrations of each tracer in tagCH4 simulation equal to the total methane concentration ? Or is the total concentration of tracers only a small part of the total methane concentration ?

**Comment by msulprizio** [comment]
>Is the sum of the concentrations of each tracer in tagCH4 simulation equal to the total methane concentration ? Or is the total concentration of tracers only a small part of the total methane concentration ?

The source of total CH4 tracer is the sum of emissions of the tagged CH4 tracers minus soil absorption.

https://github.com/geoschem/geos-chem/blob/4722f288e90291ba904222f4bbe4fc216d17c34a/GeosCore/global_ch4_mod.F90#L468-L473

Chemistry (loss by OH/Cl and in the stratosphere) is applied to the total CH4 tracer and then distributed among the tagged tracers.

https://github.com/geoschem/geos-chem/blob/4722f288e90291ba904222f4bbe4fc216d17c34a/GeosCore/global_ch4_mod.F90#L1487-L1507

**Comment by yantosca** [comment]
Closing out this issue
