### ISSUE TITLE
Modify the meteorological inputs in GEOS-Chem to include biases

### ISSUE THREAD

**Issue by ankitpatel0698** [geoschem/geos-chem#1864]
### IIT-Madras, Chennai

Name: Ankit Patel
Institution: IIT Madras

### Description of your issue or question

Dear GEOS-Chem Community

I have recently started learning about GEOS Chem and I am currently working to simulate the meteorological parameters in the GEOS-Chem model. When compared to the observations, I have calculated the biases. I am keen to insert these biases back into the GEOS-Chem and then analyse them further.
I wanted to ask what should be the correct approach to running GEOS-Chem with the inclusion of biases? 
What are the steps involved in the process? 
Is there a way already in the model where we can introduce the biases and the model can preprocess the input meteorological data and do the simulations.

Thank you in advance.

Since I am a beginner with GEOS-Chem modelling, I apologize in advance if my question expresses a potential lack of expertise or knowledge with the topic.

**Comment by yantosca** [comment]
Thanks for writing @ankitpatel0698.  I think the best way to do what you wish is to add scale factors for the relevant meteorology fields to the HEMCO_Config.rc. file.  Then HEMCO will apply those scale factors as it reads the meteorological fields into your simulation.

For more information about how to define scale factors, see https://hemco.readthedocs.io.

**Comment by ankitpatel0698** [comment]
Thank you so much for the response dear @yantosca.

In continuation of the above concern I want to clarify one thing, which is mentioned below;  
Since GOES Chem is a Chemistry Transport Model and it does not simulate meteorology during the model run. Keeping this in mind when the model is driven by MERRA-2, the model output data ( _only for meteorological variables_) should be identical to the meteorological variables of input data (MERRA-2).  
However, when I am running GEOS-Chem, I could find discrepancies in the meteorological variables of MERRA-2 data and the meteorological output of GEOS Chem data (e.g. Temperature). Also, the grid size, time period and grid box were identical for the comparison.

My doubt is if the model does not simulate meteorology, then what could be the possible reasons for the discrepancies in MERRA-2 input data to the model and GEOS Chem output data (only for meteorological variables).

Thanks in advance

**Comment by yantosca** [comment]
Thanks for the clarification @ankitpatel0698.  Several of the input meteorological variables are archived differently (i.e. instantaneous vs time-averaged, 3h vs.1h), so you may see differences if you are comparing to the out-of-the-box StateMet collection (which is time-averaged).  

Your question seems more like a science question than a technical issue that the GCST can resolve.  You might want to contact one of the working groups (e.g. Transport Working Group) for more advice.

**Comment by ankitpatel0698** [comment]
Thank you again @yantosca for the information. Can you please mention someone whom I can contact for the advice on above query?

**Comment by lizziel** [comment]
Adding on to this, not all input meteorology are unchanged in the model upon read. For example, `State_Met%T` (temperature) is time-interpolated from other inputs (see code [here](https://github.com/geoschem/geos-chem/blob/4722f288e90291ba904222f4bbe4fc216d17c34a/GeosCore/calc_met_mod.F90#L823-L829)). To see if the input you are interested in is changed in the model you can grep the repository for `State_Met%X` and `=`, where `X` has diagnostic named `Met_X`. For example, `git grep -in "State_Met%T.*="`.

**Comment by ankitpatel0698** [comment]
> Thanks for writing @ankitpatel0698. I think the best way to do what you wish is to add scale factors for the relevant meteorology fields to the HEMCO_Config.rc. file. Then HEMCO will apply those scale factors as it reads the meteorological fields into your simulation.
> 
> For more information about how to define scale factors, see https://hemco.readthedocs.io.

It looks like changing the scale factors will only apply to the changes in the emissions used in HEMCO and it does not effect the meteorological inputs in any way. In that case, the problem in including the biases in  meteorological input remains as it is. Is there any other way by which we can incorporate meteorologcial biases for the GEOS-Chem simulation ?

**Comment by christophkeller** [comment]
@ankitpatel0698 The meteorology fields are read in `get_met_mod.F90` via subroutine `HCO_GC_GetPtr` (e.g., [here](https://github.com/geoschem/geos-chem/blob/main/GeosCore/get_met_mod.F90#L110C25-L110C25)). The get pointer call does not take into account scale factors. One could replace the `HCO_GC_GetPtr` calls in `get_met_mod.F90` with [`HCO_GC_EvalFld`](https://github.com/geoschem/geos-chem/blob/main/GeosCore/hco_utilities_gc_mod.F90#L41C18-L41C18), which checks for scale factors and applies them to the base field that is being read in. 
However, it looks like `HCO_GC_EvalFld` currently does not accept the time index as an input argument, so this would have to be added to it. Also, `HCO_GC_EvalFld` has more overhead and I don't know how this change would impact runtimes.
Just thought I would share in case you want to go down that route...

**Comment by yantosca** [comment]
Thanks @christophkeller!  I had the wrong module.  Thanks for the correction.

**Comment by yantosca** [comment]
Closing out this issue now.  Feel free to open a new issue if you are still encountering problems.
