### ISSUE TITLE
 SOA prodution for aromatics SOA, Terpene SOA, and Isoprene SOA

### ISSUE THREAD

**Issue by yangbyy** [geoschem/geos-chem#1865]
### Name and Institution (Required)

Name: Shuangqin Yang
Institution: Tianjin Normal University, China

Ask a question about GEOS-Chem:
The model version I am using is v14.0.0. I would like to know how to calculate and see the contribution of each component of SOA to its total yield. Specifically, I would like to know the SOA yields for aromatics SOA, Terpene SOA, and Isoprene SOA for their respective counterparts, what should I do? Perhaps someone could tell me where I need to set this up or guide me to which source files I should be looking at. I've been trying to figure this out for a few days, but I'm still having trouble.
Anyone who can help me I would appreciate it!

**Comment by yantosca** [comment]
Tagging @theloniuspunk @wporter @eamarais @wporter

**Comment by theloniuspunk** [comment]
I unfortunately have not worked with the complex SOA scheme directly. 

Do you want to know the yields of each parent species to the different volatility bins upon reaction with different oxidants (these are fixed values and are in the code somewhere)? Or do you want to know the mass concentration of SOA that has come from the different parent compounds as a function of time/location?

**Comment by yangbyy** [comment]
Thank you so much for your reply! To be honest, I would like to know the final SOA yield for each parent HC, as Table 3 in the pye2010 article（http://dx.doi.org/10.5194/acp-10-11261-2010）.
![image](https://github.com/geoschem/geos-chem/assets/115625689/d06350be-7f36-41c6-8639-28936d6a7f6b)


Based on your reply it seems I have to know the SOA Yield Parameterizations first, and I'll try to find these fixed values inside the code.

**Comment by wporter** [comment]
Hi Shuangqin, if I understand correctly it looks like you are after total annual mass, broken down by SOA precursor, correct? If so, the SOA yield parameters themselves won't help you -- you can just look at the SOA-relevant species in the diagnostic output. If you are interested in total mass differentiated by precursor, you can find it in the AerosolMass output files (e.g. as AerMassTSOA for terpenes). Is this what you're after? If you do need actual production rather than just burden you may need to do a bit more work to track that with production/loss diagnostics, but this can get you started on a precursor-specific breakdown.

**Comment by yangbyy** [comment]
Thank you @wporter. Sorry that I did not state my needs very well at first.
Actually, you've got the point, I do want to know the total annual mass broken down by SOA precursor. I have found the variables you mentioned in the AerosolMass output file, but it seems that they represent the mass concentration of SOA.
But what I need is the annual production of SOA for each precursor, especially ASOA. So I need to track the production/loss of precursors in the reaction to get the yield of SOA, right? Well, to be honest, this is going to be a huge challenge for me.

**Comment by theloniuspunk** [comment]
Hi Shuangqin,

I want to note that the word "yield" has a very specific meaning in the SOA community. It's the ratio of the amount of product formed per precursor reacted, expressed as either kg/kg or mol/mol. In GEOS-Chem, these yield values are specific for each precusor (and depends on the oxidant and sometimes other factors). What you're looking for are the global production rates, not the yields. 

I believe that you can get these global production rates from the "Budget" collection in the HISTORY.rc file. Turning the Budget collection on and make sure you have BudgetChemistryFull_?ADV? or BudgetChemistryTrop_?ADV? specified will give the mass production rate of each tracer (including the SOA tracers) in the full column or tropospheric column in units of kg/s. You can then sum all of the model columns and convert the mass/time units to Tg/yr. 

@yantosca can you confirm that I'm interpretting the Budget menu correctly?

**Comment by theloniuspunk** [comment]
Actually, I'm not sure how gas-particle partitioning works in to the budget menu. @wporter do you know?

**Comment by wporter** [comment]
> Actually, I'm not sure how gas-particle partitioning works in to the budget menu. @wporter do you know?

I'm not sure either! I suspect that we can track the chemistry itself as you described, but that getting the partitioning numbers would be more complicated. The "Simple" scheme may be the best approach here, if that's acceptable, since it will have fixed yields allowing the production rates to be back-solved from precursor concentrations.

**Comment by yangbyy** [comment]
Thank you so much @theloniuspunk @wporter,  Thanks for pointing out what "yield" means in the SOA community, I did not realize that before. It seems to me that the next thing I can try to do is to utilize Budget collection to get global SOA production. Given that I'm trying to get SOA production from different precursors, the simple scheme SOA may not be for me. I will try what you all suggested, thanks again!

**Comment by yangbyy** [comment]
Hi @yantosca, If I turn Budget Collection on and use BudgetChemistryFull_?ADV? to get the SOA annual production, I should convert the unit kg/s to Tg/yr, so my question is do I need to multiply by the surface area? I would like to make this clear before proceeding to the next step. Very much looking forward to your reply, thanks！

**Comment by theloniuspunk** [comment]
If the units are kg/s for each lat-lon grid, you just need to add all of
the gridboxes. If it's kg/s/m2, then you need to multiply by the area of
each grid box first before adding.

**Comment by yangbyy** [comment]
Okay, I got it, thanks a lot (@theloniuspunk)! Well, I appreciate the guidance from you all, and I think I can close the issue now.
