### ISSUE TITLE
[BUG/ISSUE] Cannot use all tagged O3 tracers

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#187]
I have created this issue on behalf of Hao Yin (yhyh95@mail.ustc.edu.cn):

> I'm using the GEOS-Chem tagged O3. I set it up according to the above instructions of Wiki, but there is no way to run complex mode, so I want to ask you why. My attachment is tagged_o3_mod.F:

  - [tagged_o3_mod.F.txt](https://github.com/geoschem/geos-chem/files/4016373/tagged_o3_mod.F.txt)

**Comment by yantosca** [comment]
Thanks for writing.  The standard simulation is set up to use one tagO3 tracer.  We leave it to users to add their own.

Can you provide us with more specific information about the model version you are using, and the error message?  We would need to see input files and log files.  For a complete list of what to include, [please see this checklist](http://wiki.geos-chem.org/Submitting_GEOS-Chem_support_requests#What_do_I_need_to_include_in_my_support_request.3F)

**Comment by yinhao1995** [comment]
Ok, thanks, Sir! I'm using the version of v12.2.1. The problem I had was that I wanted to use the extension tagged O3 as directed on the wiki, but it didn't work.

**Comment by yantosca** [comment]
How did it not work?  Did it not compile or did it not run?  Can you send us log files?

**Comment by yinhao1995** [comment]
OK, I have been run the extension tagged o3 tracers, but there are only two diagnostic outputs in the result, which is strange. 
![微信截图_20200103223329](https://user-images.githubusercontent.com/45566580/71729001-9f7e5a80-2e79-11ea-9057-ea4bc2e3f4db.png)
![微信截图_20200103224014](https://user-images.githubusercontent.com/45566580/71729626-30096a80-2e7b-11ea-8dfd-57200a91dfdc.png)
![微信截图_20200103224856](https://user-images.githubusercontent.com/45566580/71729648-3ef01d00-2e7b-11ea-8257-56b77f9ebe3e.png)

**Comment by yantosca** [comment]
Thanks for the update.  I think I have found the solution.  You need to list all of the tagged O3 species in the input.geos file, in this order:

```
------------------------+------------------------------------------------------
%%% ADVECTED SPECIES MENU %%%:
Species name            : O3
Species name            : O3strat
Species name            : O3ut
Species name            : O3mt
Species name            : O3row
Species name            : O3pcbl
Species name            : O3nabl
Species name            : O3atbl
Species name            : O3eubl
Species name            : O3afbl
Species name            : O3asbl
Species name            : O3init
Species name            : O3usa
```
This ordering matches the comments in tagged_o3_mod.F:
```F90
!  THE SIMPLE TAGGED O3 SIMULATION (default setting) HAS THESE ADVECTED SPECIES:
!  ----------------------------------------------------------------------------
!  (1 ) O3      : Total O3
!  (2 ) O3Strt  : Stratospheric O3
!                                                                             .
!  THE EXTENDED TAGGED O3 SIMULATION HAS THESE ADVECTED SPECIES:
!  ----------------------------------------------------------------------------
!  (1 ) O3      : Total O3
!  (2 ) O3Strt  : O3 from the Stratosphere      (tropopause - atm top   )
!  (3 ) O3Ut    : O3 produced in Upper Trop     (350 hPa    - tropopause)
!  (4 ) O3Mt    : O3 produced in Middle Trop    (PBL top    - 350 hPa   )
!  (5 ) O3Row   : O3 produced in Rest of World  (surface    - PBL top   )
!  (6 ) O3PcBl  : O3 produced in Pacific BL     (surface    - PBL top   )
!  (7 ) O3NaBl  : O3 produced in N. American BL (surface    - PBL top   )
!  (8 ) O3AtBl  : O3 produced in Atlantic BL    (surface    - PBL top   )
!  (9 ) O3EuBl  : O3 produced in European BL    (surface    - PBL top   )
!  (10) O3AfBl  : O3 produced in N. African BL  (surface    - PBL top   )
!  (11) O3AsBl  : O3 produced in Asian          (surface    - PBL top   )
!  (12) O3Init  : O3 initial conditions         (all levels             )
!  (13) O3USA   : O3 produced over the USA      (all levels             )
!                                                                             .
!  NOTES:
!  ----------------------------------------------------------------------------
!  (1) The stratospheric O3 species must be species #2.  This is due to how
!       the Linoz stratospheric O3 chemistry scheme is written.  We have
!       accordingly reorganized the species numbers below.
!                                                                             .
!  (2) The name "tagged_ox_mod.F" is historical.  The Ox species in GEOS-Chem
!       has now been replaced with O3.  O3 usually makes up about 95% of Ox.
!       The nomenclature "tagged Ox" is interchangeable with "tagged O3".
!       As of Aug 2016, most uses of "tagged Ox" have been replaced with
!       "tagged O3".
!                                                                             .
!  (3) If using all of the tagged O3 species, note that that the sum of
!       production of species #2 - #12 sums together to equal the production
!       of species #1.  In other words:
!                                                                             .
!         PP(I,J,L,1) will equal SUM( PP(I,J,L,2:12) )
!                                                                             .
!       ALSO NOTE: The O3USA species is defined to include all of the
!       O3 produced over the US (at all levels).  Therefore, it should
!       be treated separately from species 2 - 12.
!                                                                             .
!  (4) When starting a long tagged O3 simulation, we recommend that you use
!      a restart file where all species concentrations are set to zero.
!      Then spin up for as many years as it takes to get into steady-state.
!      This will ensure that the sum of tagged O3 species (#2  - #12) will
!      equal the total O3 species (#1).
```

**Comment by yinhao1995** [comment]
THankd for your answer. Although I have set it as you said, there is still an error report. I don't know how to solve it.
![1](https://user-images.githubusercontent.com/45566580/71759642-1273e980-2eeb-11ea-98c2-4ba1ffba2a1e.png)
![2](https://user-images.githubusercontent.com/45566580/71759652-2d465e00-2eeb-11ea-8f09-6f6e13617a3d.png)

**Comment by yantosca** [comment]
I think your issue is that you haven't specified all of the species:
```
%%% ADVECTED SPECIES MENU %%%:
Species name            : O3
Species name            : O3strat
Species name            : O3ut
Species name            : O3mt
Species name            : O3row
Species name            : O3pcbl
Species name            : O3nabl
Species name            : O3atbl
Species name            : O3eubl
Species name            : O3afbl
Species name            : O3asbl
Species name            : O3init
Species name            : O3usa
```
The way the extended O3 simulation is set up, you have to use either none of the extra species (just O3 and O3strat) or all of them,  Try again with all of the species above in your input.geos file, that should work.

**Comment by yinhao1995** [comment]
![3](https://user-images.githubusercontent.com/45566580/71863376-a0dcab00-3137-11ea-8538-1b9508a2c267.pn
![4](https://user-images.githubusercontent.com/45566580/71863621-5c054400-3138-11ea-954c-9b503c558d58.png)
g)
Sir, I am so sorry, but I still haven't solved the problem according to the settings you said. I don't know if there is any problem with other settings

**Comment by yinhao1995** [comment]
![3](https://user-images.githubusercontent.com/45566580/71863835-17c67380-3139-11ea-956a-6596b13248f6.png)
![4](https://user-images.githubusercontent.com/45566580/71863844-1eed8180-3139-11ea-8639-3af63f963b29.png)
Sir, I am so sorry, but I still haven't solved the problem according to the settings you said. I don't know if there is any problem with other settings

**Comment by yantosca** [comment]
Try "O3strat" instead of "O3strt".  That may fix your issue.

**Comment by yinhao1995** [comment]
![5](https://user-images.githubusercontent.com/45566580/71943917-1a8a9c80-31fd-11ea-9c50-6da59a153ed9.png)
![6](https://user-images.githubusercontent.com/45566580/71943957-49087780-31fd-11ea-8bcb-2614d67b3b9f.png)
But there is still no way to run it. I feel confused. I also compiled it.

**Comment by yantosca** [comment]
One more thing.  Do you know if your input.geos file (where you list the species names) has any TAB characters?  Try replacing TABs with spaces. That might be causing your issue.

You can also try updating to a newer version than 12.2.1.  We have 12.6.3 now available, and are about to release 12.7.0 (pending benchmarking).

**Comment by yinhao1995** [comment]
OK, there is something wrong with the tabs. Thank you again!

**Comment by yantosca** [comment]
Thanks.  For now I will close this out.  Feel free to re-open it.
