### ISSUE TITLE
Compilation Issue while running the N2O GEOS-Chem Adjoint Version

### ISSUE THREAD

**Issue by gouravsaha1995** [geoschem/geos-chem#1875]
### Name and Institution (Required)

Name: Gourav Saha
Institution: Indian Institute of Technology, Delhi (IIT Delhi)

Hi all,
Recently I started working on the GEOS-Chem Model. I am actually working with the adjoint version for Nitrous Oxide(N2O). There's a fortran script n2o_mod.f which has an include line where we have to source the local netcdf.inc file. But, when I am trying to source that file this error is being shown. I am putting everything right here. How can I get this issue solved?
```console
ifort -cpp -w -O3 -auto -noalign -convert big_endian -fp-model precise -vec-report0 -traceback -openmp -Dmultitask -mcmodel=medium -i-dynamic -I/home/cas/irdstaff/ird600165/scratch/gourav/GEOS-Chem-Libraries/opt/ifort/nc4/include -L/home/cas/irdstaff/ird600165/scratch/gourav/GEOS-Chem-Libraries/opt/ifort/nc4/lib -c -r8 modified/n2o_mod.f
modified/n2o_mod.f(657): error #5120: Unterminated character constant
include '/home/cas/irdstaff/ird600165/scratch/gourav/GEOS-Chem-Lib
--------------^
modified/n2o_mod.f(657): error #5102: Cannot open include file '/home/cas/irdstaff/ird600165/scratch/gourav/GEOS-Chem-Lib'
include '/home/cas/irdstaff/ird600165/scratch/gourav/GEOS-Chem-Lib
--------------^
compilation aborted for modified/n2o_mod.f (code 1)
make: *** [n2o_mod.o] Error 1
```
I tried breaking the line into smaller chunks but errors kept showing.
The file is in this location : /home/cas/irdstaff/ird600165/scratch/gourav/GEOS-Chem-Libraries/opt/ifort/nc4/include/netcdf.inc

Can anyone suggest me how to solve for this error?

**Comment by msulprizio** [comment]
We defer to the Adjoint Working Group for answering questions related to the GEOS-Chem Adjoint, as it is a separate codebase that lags behind the current GEOS-Chem by several versions). Contact information can be found here: http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_Adjoint.
