### ISSUE TITLE
10-year continuous ozone simulation

### ISSUE THREAD

**Issue by zsx-GitHub** [geoschem/geos-chem#1877]
Dear GCClassic community,

I am conducting a ten-year ozone simulation to look at ozone trends. Instead of conducting simulations continuously for ten years, is it OK to spin up for three months each year so that I can submit ten simulations at the same time? Will this disrupt the simulated long-term ozone trends? Any thoughts will be greatly appreciated!

Best,
Shixian

**Comment by msulprizio** [comment]
I have transferred this issue to the geos-chem science code base repository for better visibility.
