### ISSUE TITLE
[FEATURE REQUEST] Enable calculation of RF from stratospheric changes

### ISSUE THREAD

**Issue by sdeastham** [geoschem/geos-chem#1881]
https://github.com/geoschem/geos-chem/blob/4722f288e90291ba904222f4bbe4fc216d17c34a/GeosCore/rrtmg_rad_transfer_mod.F90#L680C12-L680C49

It would be a trivial change to have RF calculations from RRTMG include changes in stratospheric water vapor (by using the H2O tracer rather than AVGW). As long as there are no objections I will submit a PR which makes this change.

Similarly, it's not clear to me why stratospheric changes in ozone and CH4 (https://github.com/geoschem/geos-chem/blob/4722f288e90291ba904222f4bbe4fc216d17c34a/GeosCore/rrtmg_rad_transfer_mod.F90#L801-L805) are not included in the calculation of ozone- and methane-related RF. I will include these in a subsequent PR.

**Comment by yantosca** [comment]
We can close out this issue as PR #2010 was merged into 14.3.0.
