### ISSUE TITLE
A question about Geoschem-TOMAS

### ISSUE THREAD

**Issue by Fearlessssssss** [geoschem/geos-chem#1883]
### Name and Institution (Required)

Name:Tyler
Institution:THU

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

For TOMAS species, which are calculated as OCLI while Geoschem couple TOMAS running?

**Comment by yantosca** [comment]
Tagging @theloniuspunk @BettyCroft

**Comment by theloniuspunk** [comment]
Hi Tyler (@Fearlessssssss).

Can you expand on your question? I don't understand it as it's written. Thanks!

Jeff

**Comment by Fearlessssssss** [comment]
Hi, Thanks for your reply ! I just want to know, While running GC coupled with TOMAS, is it ok for me to verify the influence of a specific species(such as MONITA) to the CCN? By the way, MONITA is a component of hydrophilic organic carbon, i try to add a special inventory of it and want to know its influence.



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Jeffrey ***@***.***> |
| Date | 07/20/2023 01:25 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [geoschem/geos-chem] A question about Geoschem-TOMAS (Issue #1883) |

Hi Tyler ***@***.***).

Can you expand on your question? I don't understand it as it's written. Thanks!

Jeff

**Comment by theloniuspunk** [comment]
Hi Tyler, 

TOMAS is only coupled to the simple SOA scheme, unfortunately. I believe that MONITA is only part of the complex scheme. Is this correct? 

Coupling TOMAS to the complex scheme is something that's been on my mind for a while, but it requires some pretty substantial changes to some of the numerics, and I haven't had a project in my group that would benefit from it. 

You could assume a size distribution of the bulk aerosol mass species and estimate CCN that way. Or we could try to think of creative ways to modify the yields/proxies in the simple SOA scheme to have the changes show up in TOMAS.

Jeff

**Comment by Fearlessssssss** [comment]
A clearly reply,thanks!



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Jeffrey ***@***.***> |
| Date | 07/20/2023 03:36 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [geoschem/geos-chem] A question about Geoschem-TOMAS (Issue #1883) |

Hi Tyler,

TOMAS is only coupled to the simple SOA scheme, unfortunately. I believe that MONITA is only part of the complex scheme. Is this correct?

Coupling TOMAS to the complex scheme is something that's been on my mind for a while, but it requires some pretty substantial changes to some of the numerics, and I haven't had a project in my group that would benefit from it.

You could assume a size distribution of the bulk aerosol mass species and estimate CCN that way. Or we could try to think of creative ways to modify the yields/proxies in the simple SOA scheme to have the changes show up in TOMAS.

Jeff
