### ISSUE TITLE
Incorrect ocean mask specified for transport tracers with native meteorology

### ISSUE THREAD

**Issue by sdeastham** [geoschem/geos-chem#1886]
When running the tracer transport test with native ("GEOS_FP_Native") meteorology, the ExtData.rc file incorrectly specifies the ocean mask. It reads as

`OCEAN_MASK   1 N Y - none none FROCEAN    ./MetDir/2011/01/GEOSFP.20110101.CN.025x03125.nc`

but should be

`OCEAN_MASK   1 N Y - none none FROCEAN    ./MetDir/GEOS.fp.asm.const_2d_asm_Nx.00000000_0000.V01.nc4`

Issue:

https://github.com/geoschem/geos-chem/blob/4722f288e90291ba904222f4bbe4fc216d17c34a/run/GCHP/ExtData.rc.templates/ExtData.rc.TransportTracers#L237

**Comment by lizziel** [comment]
Yes, I ran into this too in the last couple weeks. I am putting a fix into the next version.

**Comment by lizziel** [comment]
I am putting fix for this into 14.2.1. See https://github.com/geoschem/geos-chem/pull/1974/files.

**Comment by yantosca** [comment]
We can close this issue as PR #1974 has been merged into 14.2.1.
