### ISSUE TITLE
GEOS-Chem data server down?

### ISSUE THREAD

**Issue by haohe1982** [geoschem/geos-chem#1894]
### Name and Institution (Required)

Name: Hao He
Institution: University of Maryland, College Park

### Confirm you have reviewed the following documentation

- [ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

I am running GEOS-Chem with the 0.5x0.625 nested NA grids. Today I cannot download GEOS files from the servers (I tried both wu and cc) as below. The connection was hanging there and lost after half a hour. Is it the problem of the data server or my server?

./download_data.py log.dryrun wu
Log with unique file paths written to: log.dryrun.unique
Downloading data from washu
--2023-07-31 17:32:50--  http://geoschemdata.wustl.edu/ExtData/GEOSCHEM_RESTARTS/v2021-09/GEOSChem.Restart.fullchem.20190101_0000z.nc4
Resolving geoschemdata.wustl.edu (geoschemdata.wustl.edu)... 35.209.233.133
Connecting to geoschemdata.wustl.edu (geoschemdata.wustl.edu)|35.209.233.133|:80... connected.
HTTP request sent, awaiting response...

**Comment by yantosca** [comment]
Tagging @SaptSinha @yidant

**Comment by yantosca** [comment]
Thanks @SaptSinha for letting us know about the data server.

**Comment by yantosca** [comment]
I will close out this issue as the data server is now online.
