### ISSUE TITLE
Request user manual for geos chem12.0

### ISSUE THREAD

**Issue by Pengzhuohoa** [geoschem/geos-chem#1897]
### Name and Institution (Required)

Name:peng
Institution:Chengdu University of Technology
### Confirm you have reviewed the following documentation
- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)
### Description of your issue or question
Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

Hello, I have been studying geoschem recently and I believe it is a very good model. Currently, I am learning how to use 12.0, but this version is lagging behind the current 14.1 version. I cannot find a detailed user manual on the wiki. Therefore, I hope you can share a 12.0 user manual. I am very grateful and looking forward to your reply. Thank you and wish your work a success

**Comment by msulprizio** [comment]
An archive of GEOS-Chem manuals by version may be found at https://geoschem.github.io/gcclassic-manpage-archive/.

If possible, we recommend updating to the latest version of GEOS-Chem as it contains many bug fixes and science updates. We also cannot provide support for older versions.
