### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Pengzhuohoa** [geoschem/geos-chem#1898]
### Name and Institution (Required)

Name:peng
Institution:Chengdu University of Technology
### Confirm you have reviewed the following documentation
- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)
### Description of your issue or question
Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

Hello, I encountered an issue while running geos chem12.0. I created the running directory through UT, modified input.geos, and successfully created geos.mp through make -j4 mpbuild. Subsequently, I entered export OMP_NUM_THREADS=16 and export OMP_ STACKSIZEZ=500m on my terminal, I think my device is suitable for this situation, and then./geos.mp>&log.txt, a Segmentation fault (core dumped) has appeared, and I have checked that there is no error reported in log.txt. If you could reply, I would greatly appreciate it.
[log.txt](https://github.com/geoschem/geos-chem/files/12236889/log.txt)

**Comment by msulprizio** [comment]
Hi @Pengzhuohoa. It is possible your simulation ran out of memory. Please try increasing the resources you have requested.

As mentioned in #1897, we highly recommend updating to the latest version of GEOS-Chem. We cannot provide support for older model versions.

**Comment by yantosca** [comment]
Closing out this issue now.
