### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Pengzhuohoa** [geoschem/geos-chem#1900]
### Name and Institution (Required)

Name:peng
Institution:Chengdu University of Technology

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

Hello, I have read the user manual and historical issue records in 12.0 and have also attempted to apply OMP_ STACKSIZE has increased, but it still has the same error message and even the running records are consistent. No error was found in log.txt. Please help me check my relevant files and point out my problem. Thank you very much, and wish you a smooth work
[log.zip](https://github.com/geoschem/geos-chem/files/12248051/log.zip)

**Comment by yantosca** [comment]
Thanks for writing @Pengzhuohoa.  We cannot support GEOS-Chem 12 any longer as the model is unsupported.  Please update to the current stable version (14.1.1).
