### ISSUE TITLE
Question about aircraft emission setting CMIP6 and AEIC

### ISSUE THREAD

**Issue by jiaying002** [geoschem/geos-chem#1901]
### Name and Institution (Required)

Name: Jiaying Li
Institution: Nanyang Technological University

### Description of your issue or question
I am using GCAP for current scenarios(2001-2014) with v14.0.0. I have a question regarding the aircraft emission.

I noticed that there are two places to set aircraft emissions: AEIC_SCALE_1990_2019 and CMIP6_AIRCRAFT. I checked the explanation from HEMCO_Confid.rc, from lines 4128-4129:
```
(((CMIP6_AIRCRAFT 
# Conversions for SO2 to HCs taken from AEIC.
```
Can I understand it as CMIP6_AIRCRAFT directly using AEIC_SCALE_1990_2019? If yes, I wonder if CMIP6 uses the 2019 data for future scenarios (2040-2049)?

**Comment by ltmurray** [comment]
The CMIP6 aircraft emissions are those from CMIP6. For gases that CMIP6 did not provide aircraft emissions but are included in GEOS-Chem (e.g., C2H6), we calculate them by converting the SO2 emission rate using the same ratios as those from the AEIC inventory. Take a look at the HEMCO documentation on scaling factors, and then look at the third column from the right in HEMCO_Config.rc to understand how this is happening as the model is run.

**Comment by jiaying002** [comment]
Hey @ltmurray, I really appreciate your help! I've got a much better understanding now!

By the way, our group is currently working on analyzing the air quality in Southeast Asia for the future. We're really hoping to get our hands on the 2030 SSP370 and SSP585 meteorology data from GCAP2.0 so that we can run our simulation. I've already sent you an email with all the details from jiaying002@e.ntu.edu.sg. Could you please let me know if there's anything else you need me to do?
