### ISSUE TITLE
Concerns regarding vertical regridding through HEMCO in support of GEOS-Chem

### ISSUE THREAD

**Issue by nicholasbalasus** [geoschem/geos-chem#1904]
### Name and Institution (Required)

Name: Nick Balasus
Institution: Harvard University

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

This is HEMCO-related but I am including it here for visibility. As I understand it, HEMCO is used to process a variety of `x,y,t` fields (emissions, albedo, etc.) and `x,y,z,t` fields (boundary conditions, temperature, etc.). Generally speaking, the `x,y,z,t` fields will have `z = 72` (either from a previous GEOS-Chem output or from our processed MERRA2 or GEOS-FP met fields). If you are running a 47 L simulation, these fields will be mapped to the reduced GEOS-5 grid, typically with the [COLLAPSE](https://github.com/geoschem/HEMCO/blob/477c7e820c253c24e61d7c53df1911cd0e896abf/src/Core/hco_interp_mod.F90#L1220-L1312) subroutine ([which doesn't appear to be implemented correctly right now](https://github.com/geoschem/HEMCO/issues/232), potentially because the subroutine was modified to handle model level edges when it was designed for model levels?). For our 47 L example, the COLLAPSE subroutine works by merging the upper 36 levels of the GEOS-Chem grid into 11 levels. It does this with pressure weighting, specifically with the [AP parameter](https://github.com/geoschem/HEMCO/blob/477c7e820c253c24e61d7c53df1911cd0e896abf/src/Core/hco_interp_mod.F90#L56-L75) from the pressure grid (which is proportional to the pressure at these levels with [BP = 0](http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_vertical_grids)).

The concern is that pressure-weighting regridding is not appropriate depending on the units of the quantity being vertical regridded. For it to be appropriate, concentration units would need to be kg/hPa (for example), suggesting the original application to kg/m3 may have been inappropriate. Quantities defined at model edges (such as fluxes) need a different regridding methodology, as I would assume quantities like temperature and winds do as well.

These concerns may be due to unfamiliarity on my part, so I appreciate any thoughts! My suggested fix would be to inform COLLAPSE or INFLATE of the units of the quantity they are regridding (and potentially MESSy regridding as well, though I'm not as familiar with this), but I fear there would be very different methodology for all of these units.

**Comment by yantosca** [comment]
Also tagging @christophkeller @lizziel @jimmielin @msulprizio

**Comment by nicholasbalasus** [comment]
After discussing with Daniel, here is the suggested action w.r.t. these GCClassic-specific routines (COLLAPSE, INFLATE) that I can work on a fix for:

* for volumetric quantities (e.g., kg/m3), we need to divide by air density first before doing a pressure-based regridding (this probably applies to MESSy as well). This will require HEMCO to be aware of the units of the quantity being regridded which isn't always the current behavior, such as [here](https://github.com/geoschem/geos-chem/blob/f990a769dac3dfd0932796dc491a8dfefda79b76/run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.CH4#L552-L565) (or at least warn the user that a unitless quantity is being regridded as if it is not volumetric).
* for all other quantities (temperature, RH, winds, etc.) use the pressure-based regridding.
* for quantities defined at the model grid cell edges (e.g., fluxes), don't average, but just sample (e.g., for a flux on the native grid at edges 37, 38, 39, ignore edge 38 when going to the reduced grid).
* drop INFLATE all together (Daniel suggested we shouldn't ever be going from 47 to 72 - can the GCST confirm this is won't break anything?)

**Comment by jimmielin** [comment]
Looks good @nicholasbalasus. In terms of regridding routines I think we need to be more verbose in the logs about what is going on - right now there is a lot of hidden behavior w.r.t. model levels and this causes surprises for the user. This is probably a good time to overhaul a little bit of `hco_interp_mod.F90` (and `hcoio_messy_mod.F90`) and make them units-aware.

**Comment by yantosca** [comment]
@nicholasbalasus: There may still be some data files (perhaps the GMI P/L rates?) that were placed on 47L that get updated to 72L.   We would need to confirm.

**Comment by christophkeller** [comment]
I agree with everything said above. I'm not sure if the messy code is actually used anywhere. When I tested it all those years ago, it was extremely slow. But it was very generic, so I decided to keep it in case that there was the need to do some one-off regridding (e.g., for offline calculations).
As for the regridding method, it might be worthwhile doing this on a log(p)-scale. I **think** this is how the default vertical interpolation is done in GEOS.

**Comment by toddmooring** [comment]
@nicholasbalasus Note that a pressure-based regridding of dry-air molar or mass mixing ratios would not be *quite* mass conservative. This is because water vapor apparently counts toward the total pressure in GEOS-Chem (as it should, physically). There are definitely some subtleties in making vertical regriddings appropriately conservative and units-aware.

**Comment by nicholasbalasus** [comment]
Hi @toddmooring - I believe the regridding takes place in HEMCO's standard concentration units (kg/m3) but I'm double-checking on this (in addition to the above fixes).

**Comment by nicholasbalasus** [comment]
Closing - addressed here https://github.com/geoschem/HEMCO/commit/daf54d07ed16d0948302070855468b6b27fdd9a5
