### ISSUE TITLE
Read SF_File Error while running the GEOS-Chem Adjoint Code

### ISSUE THREAD

**Issue by gouravsaha1995** [geoschem/geos-chem#1906]
Name: Gourav Saha (Junior Research Fellow)
Institution: IIT Delhi

While running the adjoint code, I am encountering the following errors. It says 'Cannot open sf files'. But, I have given a 30-day run for another species which worked properly. Can someone please have a look at the error message and suggest a solution..

**_At X0         0 variables are exactly at the bounds
  done setulb FG
  COMPUTING NEW VALUES FOR N_CALC =            1
===============================================================================
S F   F I L E   I N P U T

READ_SF_FILE: Reading OptData/gctm.sf.01
 Error opening filename=OptData/gctm.sf.01
===============================================================================
GEOS-CHEM I/O ERROR    29 in file unit     1
Encountered at routine:location open_bpch2_for_read:1

Error   29: File not found
===============================================================================
     - CLEANUP: deallocating arrays now...
 START CLEANUP_N2O
 END CLEANUP_N2O_**

**Comment by msulprizio** [comment]
We defer to the Adjoint Working Group for answering questions related to the GEOS-Chem Adjoint, as it is a separate codebase that lags behind the current GEOS-Chem by several versions). Contact information can be found here: http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_Adjoint.
