### ISSUE TITLE
How to get Henry's constant at 298 K, Henry temperature dependency and other parameters

### ISSUE THREAD

**Issue by ximuzi0709** [geoschem/geos-chem#1909]
### Name and Institution (Required)

Name: Yali  Li
Institution: Southern University of Science and Technology

In the "HEMCO/run/HEMCO_sa_Spec.rc" file, add the properties of the species. Involving # K0: Henry's constant at 298 K (M/atm, liquid is greater than gas), # CR: Henry's temperature dependence (-dln(KH)/d(1/T), # pKA: Acid Dissociation Constant, where should I get these parameters from? Where is a comprehensive introduction to the chemical and physical properties of halogenated hydrocarbons, and an answer would be appreciated.（GCClassic 14.0.2）

**Comment by yantosca** [comment]
Thanks for writing @ximuzi0709.  @RolfSander (who is the guru of Henry's law constants) has set up a reference website here: https://www.henrys-law.org/henry/

**Comment by RolfSander** [comment]
...and for the pKa values, take a look at the IUPAC Digitized Dataset:

https://github.com/IUPAC/Dissociation-Constants

**Comment by ximuzi0709** [comment]
@yantosca @RolfSander Ok, thank you very much for your replies!

**Comment by yantosca** [comment]
Thanks @ximuzi0709!  I'll close out this issue.
