### ISSUE TITLE
Corrupt files in GEOS_0.5x0.625_NA/MERRA2/

### ISSUE THREAD

**Issue by Row-Bean** [geoschem/geos-chem#1910]
### Name and Institution (Required)

Name: Robin Stevens
Institution: Université de Montréal

### Description of your issue or question

Hi, I'm running GEOS-Chem 13.3.3, and I ran into the following error:

```
HEMCO: Opening /home/rstevens/projects/rrg-hayesp/rstevens/GC/ExtData//GEOS_0.5x0.625_NA/MERRA2/1983/09/MERRA2.19830927.A3dyn.05x0625.NA.nc4

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In Ncrd_4d_R4 #2:  NetCDF: HDF error
    327680         7

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Code stopped from DO_ERR_OUT (in module NcdfUtil/m_do_err_out.F90)

This is an error that was encountered in one of the netCDF I/O modules,
which indicates an error in writing to or reading from a netCDF file!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

I used ncview to take a look at MERRA2.19830927.A3dyn.05x0625.NA.nc4, and when I try to view the RH, ncview crashes with the following error:
```
calculating min and maxes for RH...netcdf_fi_get_data: error on nc_get_vara_float call
cdfid=65536   variable=RH
start, count:
[0]: 3  1
[1]: 0  72
[2]: 0  121
[3]: 0  161
NetCDF: HDF error
```

I re-downloaded the file from the WashU collection using Globus, but the file still seems to be corrupt in the same way.

**Comment by msulprizio** [comment]
@SaptSinha Could you please reprocess this file when you have a chance?

**Comment by SaptSinha** [comment]
@Row-Bean I uploaded the reprocessed "MERRA2.19830927.A3dyn.05x0625.NA.nc4" file. You can access it from WashU's 1983/09 MERRA2 [collection](http://geoschemdata.wustl.edu/ExtData/GEOS_0.5x0.625_NA/MERRA2/1983/09/).

**Comment by Row-Bean** [comment]
Excellent, thank you! I downloaded the new file, it appears not to have any problems.

**Comment by yantosca** [comment]
Thanks @SaptSinha and @Row-Bean! I will close out this issue now.

**Comment by Row-Bean** [comment]
I found another one:
GEOS_0.5x0.625_NA/MERRA2/1983/11/MERRA2.19831102.A3mstC.05x0625.NA.nc4

The GEOS-Chem error is similar:
`In Ncop_Rd, cannot open:  /home/rstevens/projects/rrg-hayesp/rstevens/GC/ExtData//GEOS_0.5x0.625_NA/MERRA2/1983/11/MERRA2.19831102.A3mstC.05x0625.NA.nc4`

And I cannot open this file with ncview at all:
`ncview: can't recognize format of input file MERRA2.19831102.A3mstC.05x0625.NA.nc4`

Again, I tried re-downloading via Globus from the WashU collection, but I still cannot open the file with ncview.

**Comment by SaptSinha** [comment]
Thank you for letting us know about this earlier. I have reprocessed and uploaded the MERRA2.19831102.A3mstC.05x0625.NA.nc4 file. You can find it from our 1983/11 MERRA2 [collection](http://geoschemdata.wustl.edu/ExtData/GEOS_0.5x0.625_NA/MERRA2/1983/11/).

**Comment by Row-Bean** [comment]
Thank you very much! I have downloaded the new file, ncview can read it without any problems.

**Comment by SaptSinha** [comment]
Excellent! I am closing this issue for now but please do not hesitate to open a new one in case you encounter any further data corruptions.

I also wanted to let you know that I will post an update regarding your other issue #1544 sometime this month as we have finally resolved some of the problems that we were previously encountering with inconsistent global dust strength values.

**Comment by Row-Bean** [comment]
I have found another one:

`In Ncop_Rd, cannot open:  /home/rstevens/projects/rrg-hayesp/rstevens/GC/ExtData//GEOS_0.5x0.625_NA/MERRA2/1983/11/MERRA2.19831105.I3.05x0625.NA.nc4`

`ncview: can't recognize format of input file ~/GC/ExtData//GEOS_0.5x0.625_NA/MERRA2/1983/11/MERRA2.19831105.I3.05x0625.NA.nc4`

Would you prefer for me to open a new issue when I find more corrupt files, or would it be best for me to continue to post them here?

**Comment by Row-Bean** [comment]
Thank you! I have one more file for @SaptSinha :

I looked ahead and found one more file that doesn't appear to open with ncview: 
GEOS_0.5x0.625_NA/MERRA2/1983/11/MERRA2.19831106.A3mstE.05x0625.NA.nc4

I did a quick check of the rest of 1983 and 1984, but I didn't find any more corrupt files yet.

**Comment by SaptSinha** [comment]
Thanks for reporting about these corrupted files, @Row-Bean. I have reprocessed and uploaded the files "MERRA2.19831105.I3.05x0625.NA.nc4" and "MERRA2.19831106.A3mstE.05x0625.NA.nc4". You can find them at our 1983/11 MERRA2 [collection](http://geoschemdata.wustl.edu/ExtData/GEOS_0.5x0.625_NA/MERRA2/1983/11/).

**Comment by Row-Bean** [comment]
Thank you again! I downloaded the new files, and ncview can read them without problems.

**Comment by SaptSinha** [comment]
Great! We can keep this issue open in case you encounter any more corrupted files.

**Comment by Row-Bean** [comment]
Hi @SaptSinha, I found another one:
GEOS_0.5x0.625_NA/MERRA2/1983/11/MERRA2.19831105.A3mstE.05x0625.NA.nc4

**Comment by SaptSinha** [comment]
No worries, I finished reprocessing and just uploaded the MERRA2.19831105.A3mstE.05x0625.NA.nc4 file in the same location.

**Comment by Row-Bean** [comment]
Excellent, thanks! I checked the new file, it appears to be corruption-free.

**Comment by yantosca** [comment]
Thanks @SaptSinha and @Row-Bean.  We can close out this issue now.

**Comment by Row-Bean** [comment]
Hi @SaptSinha, I found another one:
GEOS_0.5x0.625_NA/MERRA2/1983/11/MERRA2.19831106.A3dyn.05x0625.NA.nc4

I'm juggling this with a couple of other priorities at the moment, but when I get some free time I'll find a way to look through the files more efficiently to find the corrupt ones. It shouldn't take long to put together a Python script to find them.

**Comment by msulprizio** [comment]
@laestrada Wrote a script to find corrupted met files. You can give this a try to see if it identifies any files ahead of time for you. See https://github.com/geoschem/integrated_methane_inversion/blob/main/src/utilities/find_corrupt_files.sh.

@SaptSinha It may be worth bringing this script into the met-processing workflow to identify corrupted files at WashU before users download them.

**Comment by SaptSinha** [comment]
Hello @Row-Bean, the files below have now been reprocessed and uploaded to http://geoschemdata.wustl.edu/ExtData/GEOS_0.5x0.625_NA/MERRA2/1983/11/. Please feel free to reach out if you need any further assistance.

GEOS_0.5x0.625_NA/MERRA2/1983/11/MERRA2.19831106.A3dyn.05x0625.NA.nc4
GEOS_0.5x0.625_NA/MERRA2/1983/11/MERRA2.19831107.A3cld.05x0625.NA.nc4

**Comment by Row-Bean** [comment]
Excellent, thank you very much! I have downloaded and checked the new files. Fingers crossed, this issue should be closed for the last time this time. I appreciate your assistance with this.
