### ISSUE TITLE
HEMCO diagnostic files don't contain the requested emissions

### ISSUE THREAD

**Issue by akurganskiy** [geoschem/geos-chem#1912]
### Name and Institution (Required)

Name: Alex Kurganskiy
Institution: University of Edinburgh

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question
Hello,

I got an issue with HEMCO diagnostics and I hope to get some help here.
I'm running GEOS-Chem v 14.0.2 for the EU nested domain and CO2-tagged simulations. 
I'm trying to put all my emissions in HEMCO diagnostic files.
For this I added the emission variables in HEMCO_Diagn.rc (attached).
Unfortunately, my HEMCO diagnostic files do not contain any emission variables. 
They are created, but with lon, lat, lev, hyam, hybm, P0, time and AREA variables only. 
I am attaching the configuration and log files of the simulations.
Could you please, have a look and give me a hint on what might be wrong.

P.S. I did a test with GEOS-Chem v12.5 and got the same result. 
So, I believe the issue is not about the model version.
 
[GC.log](https://github.com/geoschem/geos-chem/files/12407711/GC.log)
[geoschem_config.yml.txt](https://github.com/geoschem/geos-chem/files/12407718/geoschem_config.yml.txt)
[HEMCO.log](https://github.com/geoschem/geos-chem/files/12407719/HEMCO.log)
[GC.log](https://github.com/geoschem/geos-chem/files/12407720/GC.log)
[HISTORY.rc.txt](https://github.com/geoschem/geos-chem/files/12407721/HISTORY.rc.txt)
[HEMCO_Diagn.rc.txt](https://github.com/geoschem/geos-chem/files/12407722/HEMCO_Diagn.rc.txt)
[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/12407723/HEMCO_Config.rc.txt)

**Comment by yantosca** [comment]
Thanks for writing @akurganskiy.  In the `HEMCO_Config.rc`, try using:

```console
DiagnFreq:                   00000001 000000
```
and see if that works.  Perhaps the `Daily` is not getting recognized.

**Comment by akurganskiy** [comment]
Thanks @yantosca for the suggestion! 
I tried using "00000001 000000" instead of "Daily" and got the same result.
The diagnostic files are created but without the requested emissions. 
I am attaching the output of the "ncdump -h" command as an example. 
Is there anything else I can try to fix the issue?
[HEMCO_diagnostics_ncdump.txt](https://github.com/geoschem/geos-chem/files/12420020/HEMCO_diagnostics_ncdump.txt)

**Comment by msulprizio** [comment]
@akurganskiy From your HEMCO.log file, it appears the requested diagnostics aren't getting read in. Can you add the following line to the settings section at the top of your HEMCO_Config.rc?

```
DiagnFile:                   HEMCO_Diagn.rc
```

That should tell HEMCO where to find the requested emissions to save out.

**Comment by akurganskiy** [comment]
Thanks @msulprizio! Specifying the file name in my HEMCO_Config.rc helped and I am getting the emission fields in the HEMCO diagnostic files. One more question. As I found here (https://hemco.readthedocs.io/en/latest/hco-ref-guide/diagnostics.html#hco-diag) the diagnostic files contain the average fluxes by default. However, it is also possible to get "instantaneous", "sum" and "cumulsum". 
I would be grateful if someone could advice me on where I should specify, e.g., "sum" option.

**Comment by msulprizio** [comment]
I found [this past issue](https://github.com/geoschem/HEMCO/issues/108) that suggests you can simply change units from kg/m2/s to kg to get the sum but I'm not sure if that holds true for the latest HEMCO version. You could try that and set HEMCO to verbose to print out the diagnostic details to the log file. Failing that, you may have to go into the HEMCO source code.

The code for determining the diagnostic mode is in hco_diagn_mod.F90. Essentially you can change the diagnostic mode by modifying the `OutOper` argument passed to `Diagn_Create`. If `OutOper` is not defined (the default), then it automatically calculates the mean. See [this code](https://github.com/geoschem/HEMCO/blob/4e818813da35bf76dbcee2da6ecc598b9c89b1a7/src/Core/hco_diagn_mod.F90#L1067-L1159)

To change to a different mode, you should be able to change [this line] in Diagn_Create: (https://github.com/geoschem/HEMCO/blob/4e818813da35bf76dbcee2da6ecc598b9c89b1a7/src/Core/hco_diagn_mod.F90#L1095)

```
          ! Will calculate the mean
          ThisDiagn%AvgName = 'mean'
```

Note that changing that line will impact all HEMCO diagnostics (except those manually defined within HEMCO or GEOS-Chem source code).

**Comment by yantosca** [comment]
I will close this issue now as it seems to be resolved.
