### ISSUE TITLE
Gaining Access to GEOS-Chem

### ISSUE THREAD

**Issue by oajoku88** [geoschem/geos-chem#1913]
### Name and Institution (Required)

Name: Osinachi Ajoku
Institution: Howard University

### Confirm you have reviewed the following documentation

- [ ] [Contributing guidelines](https://geos-chem.readthedocs.io/en/stable/reference/CONTRIBUTING.html)

### New GEOS-Chem feature or discussion

I would like to gain access to GEOS-Chem for research and teaching purposes. I am interested in building the code on a local machinge.

**Comment by yantosca** [comment]
Thanks for writing @oajoku88.  You can proceed to download and install GEOS-Chem on your machine.  See our instructions at: https://geos-chem.readthedocs.io

NOTE: The first time you create a run directory for GEOS-Chem, you will be asked to register.

**Comment by yantosca** [comment]
Closing out this issue.  Feel free to open a new issue if you are still encountering problems.
