### ISSUE TITLE
Spack subdirectory not available for GCClassic

### ISSUE THREAD

**Issue by garvitagarwal290** [geoschem/geos-chem#1922]
### Name and Institution (Required)

Name: Garvit Agarwal
Institution: TCS, India

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

I am freshly installing GEOS-Chem classic on my computer and firstly I am following the steps mentioned [here](https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/spack-guide.html) to build the required software dependencies. However in the section 'Clone a copy of GCClassic, GCHP, or HEMCO', it is written that 'The [GCClassic](https://github.com/geoschem/GCClassic), [GCHP](https://github.com/geoschem/GCHP) , and [HEMCO](https://github.com/geoschem/HEMCO) repositories each contain a spack/ subdirectory'. But the main branch of GCClassic doesnt have a spack subdirectory while GCHP does, so currently I am unable to build my dependencies. How do I fix this issue? Thank you.

**Comment by garvitagarwal290** [comment]
Update: For now I have downloaded the GCClassic code from the docs/dev branch, which does have (link to) the spack directory, using which I was able to follow all the instructions given in the documentation to build the code. But I wonder why the spack directory is not made available in the main branch, given its so crucial to building the code.

**Comment by yantosca** [comment]
Thanks for your patience @garvitagarwal290.  The docs/dev branch will be merged into main when GEOS-Chem 14.2.0 ships.  This version has been held up in the benchmark approval phase due to issues in the chemistry mechanism that adversely affected ozone.  We have implemented a fix that seems to correct the problem and are awaiting on the final benchmark review.  We hope to release this version soon.

**Comment by garvitagarwal290** [comment]
Thanks @yantosca. So can I use the docs/dev branch for now? I don't think I will be using the full chemistry simulation for the time being anyway.

**Comment by yantosca** [comment]
You can use the 14.1.1.branch for now but build the software environment from the docs/dev branch.  We hope to be releasing 14.2.0/14.2.1 within a week or so.

**Comment by garvitagarwal290** [comment]
okay thank you!
