### ISSUE TITLE
Wrong download links used in 'auto_generated_download_script.sh' script while downloading input data using dry-run.

### ISSUE THREAD

**Issue by garvitagarwal290** [geoschem/geos-chem#1924]
### Name and Institution (Required)

Name: Garvit Agarwal
Institution: TCS, India

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

I am trying to download the input files for GCClassic (Current status: 14.1.1-40-geb9baae) following the instructions for dry-run at https://geos-chem.readthedocs.io/en/latest/gcclassic-user-guide/dry-run.html. When I ran the command `./download_data.py log.dryrun washu`, it correctly downloaded a subset of the input files but for MERRA2 meteorological files where it wanted to connect to http://geoschemdata.wustl.edu/ExtData/HEMCO/METDIR/, it returned 'HTTP request sent, awaiting response... 404 Not Found' error. 

When I open the link http://geoschemdata.wustl.edu/ExtData/HEMCO/, I see that there is no METDIR folder to begin with. Instead, the MERRA2 files are located at http://geoschemdata.wustl.edu/ExtData/GEOS_4x5/MERRA2/. Upon manually correcting the download links in the 'auto_generated_download_script.sh' script, I am now able to download all the input files.

**Comment by garvitagarwal290** [comment]
[download_data.zip](https://github.com/geoschem/geos-chem/files/12489123/download_data.zip)

I have attached the 2 files in a zip, since .py and .yml format files arent allowed.

**Comment by yantosca** [comment]
Thanks for your patience @garvitagarwal290.  We have been busy with some other developments on this end.  I will take a look when I can.

**Comment by yantosca** [comment]
Thanks @garvitagarwal290.  So there is no `METDIR` folder in the `ExtData/HEMCO` directory structure.  The `METDIR` variable should be filled in with the proper path to `ExtData` at run directory creation.

In fact, we have removed `METDIR` from all `HEMCO_Config.rc` files in https://github.com/geoschem/geos-chem/pull/2042, precisely because the `METDIR` variable in `HEMCO_Config.rc` might conflict with that in geoschem_config.yml.  This will be fixed in GEOS-Chem 14.2.3, to be issued shortly.

**Comment by yantosca** [comment]
Closing out this issue.  Feel free to open a new issue if you are still stuck.
