### ISSUE TITLE
[FEATURE REQUEST] Update dry run option to download restart file from latest 10-year benchmark simulation 

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#1927]
### Name and Institution (Required)

Name: Melissa Sulprizio
Institution: Harvard / GCST

### New GEOS-Chem feature or discussion

When users create run directories for full-chemistry simulations, they are provided with a sample restart file for 2019/07/01. The 10-year benchmark simulations archive monthly restart files for 2010-2019. We should update the dry-run option to check for and download restart files from the latest 10-year benchmark simulation when possible.

Tagging @eamarais who originally requested this feature.

**Comment by eamarais** [comment]
@msulprizio, thanks for starting this feature thread. Happy to give it a test when it's implemented.

**Comment by yantosca** [comment]
Sorry for the delay looking into this.  We do have the restart files set as configurable settings in the `run/shared/download_data.yml` file that is used with the dry-run download.  I think we have to do a better job at updating this file when add/change restart files for simulations.  I will open a PR to address this.

**Comment by yantosca** [comment]
We can now close out this issue as this has been solved by PR #2050.  The rundir creation scripts for GEOS-Chem Classic now read the restart file paths from the `download_data.yml` file.
