### ISSUE TITLE
GCHP advected species not set to background values if missing in restart file

### ISSUE THREAD

**Issue by lizziel** [geoschem/geos-chem#1930]
### Name and Institution (Required)

Name: Lizzie Lundgren
Institution: Harvard University

### Description of your issue or question

Recent testing of the transport tracer simulation updates for new species revealed that GCHP advected species missing from the restart file are not set to background values stored in the species database. This bug came in early in version 13. 

This issue is fixed by https://github.com/geoschem/geos-chem/pull/1929.

**Comment by yantosca** [comment]
We can close this issue as PR #1929 is now merged.
