### ISSUE TITLE
Parameters in species_database.yml

### ISSUE THREAD

**Issue by jinlx** [geoschem/geos-chem#1936]
### Name and Institution (Required)

Name: Lixu Jin
Institution: University of Montana

### Description of your issue or question
Hi GCST,

I trying to add furanoids into the GEOS-Chem species_database.yml in GCv14 but not certain about the meaning of each parameter, especially for those related to depositions. For example, does the Henry_CR represent the Henry’s Law coefficient (in some kind unit), while the Henry_K0 denotes its temperature dependence (∆soln H/R, in units K)? Could you please provide some notes here for used parameteres in yml file and their corresponding units?

Thank you,
Lixu

**Comment by yantosca** [comment]
Thanks for writing @jinlx.  We do have a description of the species database parameters at: https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/species-guide.html.  

Our colleague @RolfSander maintains the website https://henrys-law.org/henry/index.html, which is a comprehensive table of Henry's law constants and related information.

**Comment by jinlx** [comment]
Thanks Bob! This is really helpful! I will go ahead and close the issue now.
