### ISSUE TITLE
Compilation error in using custom chemistry

### ISSUE THREAD

**Issue by jinlx** [geoschem/geos-chem#1937]
### Name and Institution (Required)
Name: Lixu Jin
Institution: University of Montana

### Description of your issue or question
I was trying to compile a custom chemistry in the build directory with errors below in GC14.1.1. To narrow down the potential bug, I tried to use the original custom.eqn and custom.kpp and rebuild the mechanism, but still get the same error. The error does not show up when using the fullchem, thus I guess it is only in the custom mechanism. I was wondering if there is anyway to fix the error. Any insights would be welcome!
```
[ 90%] Building Fortran object src/GEOS-Chem/GeosCore/CMakeFiles/GeosCore.dir/get_met_mod.F90.o
[ 90%] Building Fortran object src/GEOS-Chem/GeosCore/CMakeFiles/GeosCore.dir/input_mod.F90.o
/hellgate/home/lj152920/GEOS-CHEM/rundir/MERRA2_2x25_FUR/CodeDir/src/GEOS-Chem/GeosCore/carbon_gases_mod.F90:374:9:
  374 |     USE carbon_Funcs
      |         1
Fatal Error: Cannot open module file 'carbon_funcs.mod' for reading at (1): No such file or directory compilation terminated.
make[2]: *** [src/GEOS-Chem/GeosCore/CMakeFiles/GeosCore.dir/build.make:127: src/GEOS-Chem/GeosCore/CMakeFiles/GeosCore.dir/carbon_gases_mod.F90.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1183: src/GEOS-Chem/GeosCore/CMakeFiles/GeosCore.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by yantosca** [comment]
Thanks for bringing up this error @jinlx.  I believe this is caused by a missing line in the `KPP/custom/CMakeLists.txt` file. 

https://github.com/geoschem/geos-chem/blob/4722f288e90291ba904222f4bbe4fc216d17c34a/KPP/custom/CMakeLists.txt#L16-L45

The fix would be to add `stub_carbon_Funcs.F90` following line 44 of CMakeLists.txt.  This will compile stub functions (i.e. copies of the actual routine with just the arguments but no code inside) for the carbon simulation, which will satisfy the compilation requirements.   Then configure and build again and you should be all set!

We'll add this fix into 14.2.1.

**Comment by jinlx** [comment]
Just want to update another error after adding the stub_carbon_Funcs.F90 in the header (see error below). 
```
[ 95%] Building Fortran object src/GEOS-Chem/GeosCore/CMakeFiles/GeosCore.dir/fullchem_mod.F90.o
[ 95%] Building Fortran object src/GEOS-Chem/GeosCore/CMakeFiles/GeosCore.dir/aerosol_mod.F90.o
[ 95%] Building Fortran object src/GEOS-Chem/GeosCore/CMakeFiles/GeosCore.dir/sulfate_mod.F90.o
/hellgate/home/lj152920/GEOS-CHEM/rundir/MERRA2_2x25_FUR/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:99:9:

   99 |     USE fullchem_AutoReduceFuncs, ONLY : fullchem_AR_KeepHalogensActive
      |         1
Fatal Error: Cannot open module file 'fullchem_autoreducefuncs.mod' for reading at (1): No such file or directory
compilation terminated.
make[2]: *** [src/GEOS-Chem/GeosCore/CMakeFiles/GeosCore.dir/build.make:283: src/GEOS-Chem/GeosCore/CMakeFiles/GeosCore.dir/fullchem_mod.F90.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1183: src/GEOS-Chem/GeosCore/CMakeFiles/GeosCore.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```
I guess the error is caused by missing line for fullchem_AutoReduceFuncs.F90. However, another error pops out after adding the line and copying fullchem_AutoReduceFuncs.F90 from ../fullchem (see below). The error indicates that the keepSpcActive is not generated in the gckpp_Global.F90 when building the mechanisms with KPP. Just want to make sure if I am on the right track and wonder if you have any insights on which file I should work on to fix it. Thank you!

```
[ 72%] Built target HCOI_Shared
[ 72%] Building Fortran object src/GEOS-Chem/KPP/custom/CMakeFiles/KPP.dir/gckpp_Integrator.F90.o
[ 72%] Building Fortran object src/GEOS-Chem/KPP/custom/CMakeFiles/KPP.dir/gckpp_Model.F90.o
[ 72%] Building Fortran object src/GEOS-Chem/KPP/custom/CMakeFiles/KPP.dir/fullchem_AutoReduceFuncs.F90.o
/hellgate/home/lj152920/GEOS-CHEM/rundir/MERRA2_2x25_FUR/CodeDir/src/GEOS-Chem/KPP/custom/fullchem_AutoReduc                                                                                                                                 eFuncs.F90:52:31:

   52 |     USE gckpp_Global,    ONLY : keepSpcActive
      |                               1
Error: Symbol 'keepspcactive' referenced at (1) not found in module 'gckpp_global'
/hellgate/home/lj152920/GEOS-CHEM/rundir/MERRA2_2x25_FUR/CodeDir/src/GEOS-Chem/KPP/custom/fullchem_AutoReduc                                                                                                                                 eFuncs.F90:129:28:
make[2]: *** [src/GEOS-Chem/KPP/custom/CMakeFiles/KPP.dir/build.make:75: src/GEOS-Chem/KPP/custom/CMakeFiles                                                                                                                                 /KPP.dir/fullchem_AutoReduceFuncs.F90.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:832: src/GEOS-Chem/KPP/custom/CMakeFiles/KPP.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by yantosca** [comment]
Hi @jinlx.  Are you using a KPP version prior to 3.0.0?  If so you will need to upgrade and to rebuild the custom mechanism with that.  See: https://kpp.readthedocs.io. 

The `rosenbrock_autoreduce` integrator is used for the `fullchem` & `custom` mechanisms, but the autoreduce functionality is turned off by default in `geoschem_config.yml` under the chemistry menu.  Then this defaults to the usual Rosenbrock solver algorithm.  But this is only available in KPP 3.0.0 and later.

**Comment by jinlx** [comment]
Hi @yantosca- I just confirmed that we are using the KPP-3.0.2 and I do see that the autoreduce is turned off in geoschem_config.yml by default but still show errors above. Do you have any insights on what else we should look into? The error can occur even without changing anything in the custom chemsitry equations but please let me know if there is anything you need to better troubleshoot. Thanks! ~Lixu

**Comment by yantosca** [comment]
Thanks for your patience @jinlx.  I think I see the issue.  In the file `KPP/fullchem/fullchem.kpp` we have these options:
```console
#MINVERSION   3.0.0                  { Need this version of KPP or later          }
#INTEGRATOR   rosenbrock_autoreduce  { Use Rosenbrock integration method          }
#AUTOREDUCE   on                     { ... with autoreduce enabled but optional   }
```
but in `KPP/custom/custom.kpp` we have these options:
```console
#MINVERSION   2.5.0       { Need this version of KPP or later          }
#INTEGRATOR   rosenbrock  { Use Rosenbrock integration method          }
```
which is causing your compilation issue.  The solution will be to copy the MINVERSION, INTEGRATOR, and AUTOREDUCE options from the `KPP/fullchem/fullchem.kpp` to your `KPP/custom/custom.kpp`, and then run KPP again to regenerate the F90 files.  

Sorry about this inconvenience.  We will fix this bug in the 14.2.1 patch version.

**Comment by yantosca** [comment]
Also tagging @lizziel, who is working on enabling the custom mechanism build in GCHP.

**Comment by jinlx** [comment]
Thanks Bob and Lizziel! The error is fixed after further adding fullchem_AutoReduceFuncs.F90 in the CMakeLists. In short, we need to change two files including CMakeLists.txt and custom.kpp in the ./custom directory. Below goes the modifications for future reference.

**CmakeLists.txt**
```
add_library(KPP
  STATIC EXCLUDE_FROM_ALL
  commonIncludeVars.H
  fullchem_AutoReduceFuncs.F90 # Lixu, added, 20230907
  fullchem_HetStateFuncs.F90
  fullchem_RateLawFuncs.F90
  fullchem_SulfurChemFuncs.F90
  gckpp_Function.F90
  gckpp_Global.F90
  gckpp_Initialize.F90
  gckpp_Integrator.F90
  gckpp_Jacobian.F90
  gckpp_JacobianSP.F90
  gckpp_LinearAlgebra.F90
  gckpp_Model.F90
  gckpp_Monitor.F90
  gckpp_Parameters.F90
  gckpp_Precision.F90
  gckpp_Rates.F90
  gckpp_Util.F90
  rateLawUtilFuncs.F90
  #
  # Build these stub modules to avoid compilation errors.
  # These are symbolic links to files in the ../stubs folder.
  #
  stub_aciduptake_DustChemFuncs.F90
  stub_Hg_HetStateFuncs.F90
  stub_carbon_Funcs.F90 # Lixu, added, 20230905
  )
```
**custom.kpp**
```
#MINVERSION   3.0.0       { Need this version of KPP or later          }
#INTEGRATOR   rosenbrock_autoreduce    { Use Rosenbrock integration method, Lixu, 20230907}
#AUTOREDUCE   on                     { ... with autoreduce enabled but optional, Lixu, 20230907}
#LANGUAGE     Fortran90   { Generate solver code in Fortran90 ...      }
#UPPERCASEF90 on          { ... with .F90 suffix (instead of .f90)     }
#DRIVER       none        { Do not create gckpp_Main.F90               }
#HESSIAN      off         { Do not create the Hessian matrix           }
#MEX          off         { MEX is for Matlab, so skip it              }
#STOICMAT     off         { Do not create stoichiometric matrix        }

#INCLUDE custom.eqn       { Chemical reactions for fullchem mechanism  }
```
I also got the issue mentioend in #1657. Just a quick follow up: would the issue have any impacts on the completeness of the compilation or just the time?

**Comment by yantosca** [comment]
Thanks @jinlx.  The issue in #1657 should just be a warning.  Maybe we also need to add this code to the `KPP/custom/CMakeLists.txt`:

```cmake
# FOR GFORTRAN ONLY: Disable variable tracking for gckpp_Jacobian.F90 in the
# KPP/fullchem mechanism generated with KPP.  This will avoid a compiler
# warning and a restart of the KPP library build.  This only has to be done
# for release types "Release" and "RelWithDebugInfo".
#   -- Bob Yantosca (16 Feb 2023)
if("${CMAKE_Fortran_COMPILER_ID}" STREQUAL "GNU")
  if(NOT ("${CMAKE_Fortran_COMPILER_ID}" STREQUAL "Debug"))
    set_source_files_properties(gckpp_Jacobian.F90
      PROPERTIES
      COMPILE_OPTIONS -fno-var-tracking-assignments
    )
  endif()
endif()
```

**Comment by jinlx** [comment]
Thanks for answering it Bob! I will go ahead and close the issue here.
