### ISSUE TITLE
AEIC2019 Setting

### ISSUE THREAD

**Issue by yangning-code** [geoschem/geos-chem#1939]
### Name and Institution (Required)

Name:NingYang
Institution:JNU

### Confirm you have reviewed the following documentation

- [ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)
Confirm
### Description of your issue or question
I found that AEIC2019 has been updated, but the GEOS-Chemv13.3.2 I am using is still old. Can I directly put the settings about AEIC2019 in the HEMCO_Config.rc file into the old settings? In other words, can I just update the latest AEIC2019 in the old HEMCO_Config.rc file? Do I still need to modify the code block of HEMCO?

**Comment by msulprizio** [comment]
Hi @yangning-code. To use the AEIC2019 inventory, you can simply replace the original AEIC lined in HEMCO_Config.rc with the lines for AEIC2019. You do not need to modify any code within HEMCO.

**Comment by yangning-code** [comment]
Thank you very much
