### ISSUE TITLE
error about Compiling geos-chem

### ISSUE THREAD

**Issue by EkkoWusu** [geoschem/geos-chem#1942]
### Name and Institution (Required)

Name: Ekko
Institution: Peking University

### Confirm you have reviewed the following documentation

- [√ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [√ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ √] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [√ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Dear GCST,

I have encountered the compilation error after using `make -j`: 

```
gc_2x25_47L_merra2_CO2/CodeDir/src/GEOS-Chem/Headers/dictionary_m.F90(26): error #8237: The character length in a component declaration shall either be a colon, be an initialization expression, or be a specification expression.   [KEY]
     character(len=*), allocatable :: key
--------------------------------------^
compilation aborted for /data1/share/eljj_2023_00028/sw/Carbon/GC_Test/gc_2x25_47L_merra2_CO2/CodeDir/src/GEOS-Chem/Headers/dictionary_m.F90 (code 1)
make[2]: *** [src/GEOS-Chem/Headers/CMakeFiles/Headers.dir/dictionary_m.F90.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by yantosca** [comment]
Thanks for writing @EkkoWusu.  We would need some more information from you.  Which version of GEOS-Chem are you using and which compiler?  Also can you post your run directory configuration files to this issue?

**Comment by EkkoWusu** [comment]
There are files in my run directory:

**Comment by yantosca** [comment]
Thanks @EkkoWusu, the important ones are the `geoschem_config.yml`, `HEMCO_Config.rc`, `HEMCO_Diagn.rc`, and `HISTORY.rc`.

Also, it might be that there is some incompatibility with the newest intel compiler.  We have confirmed that the Intel 2020 compiler (which we have in-house) can build GEOS-Chem.  I suspect the Intel 2023 by default assumes that you are using the latest Fortran standard (F2018?) whereas much of the GEOS_Chem code is written to the F90 standard.  You could investigate to see if any compiler options would disable that strict bheavior.

I would also recommend trying to compile with GNU Fortran (from the GNU Compiler Collection) as most Linux distributions have at least one version of the GNU compilers available.  GEOS-Chem should be compatible with the GNU Compiler Collection version 6.2.0 or later.

**Comment by yantosca** [comment]
Also if you look at the `CMakeScripts.txt` file in the GCClassic top-level folder, these are the build options for Intel compilers:

https://github.com/geoschem/GCClassic/blob/d1d71ef9f5f3b2bbb0bbda4843819bf57098f223/CMakeLists.txt#L57-L73

You can look at the manual to see if the behavior of any of these options has changed since Intel 2020.

**Comment by lizziel** [comment]
This is strange since `character(len=*), allocatable :: key` does not appear in our code. It should be `character(len=:), allocatable :: key`, which it is in the latest release. See code in main [here](https://github.com/geoschem/geos-chem/blob/4722f288e90291ba904222f4bbe4fc216d17c34a/Headers/dictionary_m.F90#L26). Are you sure you are using 14.1.1?

**Comment by EkkoWusu** [comment]
Thanks for your attention @lizziel . I noticed that I have modified the code in dictionary_m.F90 when I am dealing with another bug. 

Now I reinstall GEOS-Chem 14.1.1, then compile it with my intel compiler. It works well now. 

Thanks again @yantosca.
