### ISSUE TITLE
How to save hourly outputs and restart files using GEOS-Chem v13.0.2

### ISSUE THREAD

**Issue by debatoshpartha** [geoschem/geos-chem#1945]
### Name and Institution (Required)

Name: Debatosh B. Partha
Institution: Wayne State University

### Description of your issue or question

Hi, I am running a fresh GEOS-Chem v13.0.2 model simulation from 20140101 to 20140105 (Specification: Full chemistry, Troposphere + stratosphere, Standard,  MERRA-2, 2.0  x 2.5, 72) and trying to save out hourly restart files and hourly SpeciesConc. diagnostic outputs but the simulation is not continuing after finishing the first hour of the simulation. It just stops without any warning sign in the log files. 

To save out the hourly restart files and SpeciesConc. diagnostic outputs (I am trying to get one netcdf file for each hour), I am doing the following steps, 

1. Changed the frequency and duration of [HISTORY.txt](https://github.com/geoschem/geos-chem/files/12562558/HISTORY.txt) collections as follows, 
```onsole
Restart.frequency:          00000000 010000
Restart.duration:           00000000 010000

Metrics.frequency:          00000000 010000
Metrics.duration:           00000000 010000

SpeciesConc.frequency:      00000000 010000
SpeciesConc.duration:       00000000 010000
```
2. Changed the frequency of 
[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/12562565/HEMCO_Config.txt) to "Hourly". 

3. Copied previously generated restart files of the first and second hour to the running directory to start the simulation (v13.0.2 does not start without supplying pre-generated restart files from our end). 
```console
GEOSChem.Restart.20140101_0000z.nc4
GEOSChem.Restart.20140101_0100z.nc4

HEMCO_restart.201401010100.nc
```
When I try to run the model, it stops at this stage and kills the job, 
```console
===============================================================================
Successfully initialized ISORROPIA code II
===============================================================================
---> DATE: 2014/01/01  UTC: 00:10  X-HRS:      0.166667
---> DATE: 2014/01/01  UTC: 00:20  X-HRS:      0.333333
     - DO_STRAT_CHEM: Linearized strat chemistry at 2014/01/01 00:20
     - LINOZ_CHEM3: Doing LINOZ
---> DATE: 2014/01/01  UTC: 00:30  X-HRS:      0.500000
---> DATE: 2014/01/01  UTC: 00:40  X-HRS:      0.666667
     - DO_STRAT_CHEM: Linearized strat chemistry at 2014/01/01 00:40
     - LINOZ_CHEM3: Doing LINOZ
---> DATE: 2014/01/01  UTC: 00:50  X-HRS:      0.833333
     - Creating file for SpeciesConc; reference = 20140101 000000
        with filename = OutputDir/GEOSChem.SpeciesConc.20140101_0000z.nc4
```
I am also attaching my 
[gcrun.log.txt](https://github.com/geoschem/geos-chem/files/12562826/gcrun.log.txt)
[HEMCO.log.txt](https://github.com/geoschem/geos-chem/files/12562827/HEMCO.log.txt)
[input.geos.txt](https://github.com/geoschem/geos-chem/files/12562828/input.geos.txt)
here.

**Comment by yantosca** [comment]
Thanks for writing @debatoshpartha.  A couple of things come to mind.

1. Check to see if the SpeciesConc file is write-protected.  That might cause a seg fault.
2. Can you also attach the specific error message to this issue?
3. If you have the GNU debugger, and if your job dropped a core file (i.e. core.12345) (where "12345" is the process ID, your number will be different), you can type:
```console
gdb gcclassic core.12345.    # or whatever your core file is named
```
and then that should take you right to the point of the error. Then you can type "where" to find out the exact line where the job failed.  You can also print out the value of variables in the code to see if there are any NaN's or any other problems.

**Comment by debatoshpartha** [comment]
Hi Mr. Yantosca, thanks for the reply. 

1. I don't think the SpeciesConc is write-protected cause when I save out daily outputs, the simulation runs just fine. 

2. The specific error message comes up in HEMCO.log file (attached above). I am copying the very last portion of the log file where it kills the job and stops the simulation. 

```
File: ./GEOSChem.Restart.20140101_0000z.nc4
--> LOCATION: HCOIO_READ_STD (hcoio_read_std_mod.F90)
TIMEZONES (i.e. OFFSETS FROM UTC) WERE READ FROM A FILE
HEMCO (VOLCANO): Opening /wsu/home/groups/yhgroup/ExtData/HEMCO/VOLCANO/v2019-08/2014/01/so2_volcanic_emissions_Carns.20140101.rc
HEMCO WARNING: No further attempts will be made to read file: ./HEMCO_restart.$YYYY$MM$DD$HH00.nc
--> LOCATION: HCOIO_DataRead (hcoio_dataread_mod.F90)
```

3. I use intel/2019 compiler which doesn't leave a core file if the job fails.

**Comment by debatoshpartha** [comment]
Hi Mr. @yantosca, I still am facing issues running hourly simulations. Could you or anyone please help?

**Comment by yantosca** [comment]
@debatoshpartha: Have you tried r

Also, I wonder if you are hitting a file size limit on your system.  You can check your bash shell limit settings with:
```console
$ ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 771205
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) 30720000
open files                      (-n) 100000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 771205
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```
If `file size` is not `unlimited` you can set it to unlimited by adding
```console
$ulimit -f unlimited
```

I would also reconfiguring the code with `-DCMAKE_RELEASE_TYPE=Debug`, then recompile and run again.  This will add some additional error checks into your executable file.

**Comment by yantosca** [comment]
Closing out this issue
