### ISSUE TITLE
Inquiry Regarding Biogenic Emissions Data for 2000-2013 (BioVOC and SoilNOx)

### ISSUE THREAD

**Issue by Saran-Wang** [geoschem/geos-chem#1947]
### Name and Institution (Required)

Name: Shiyuan Wang
Institution: University of Illinois Urbana-Champaign (UIUC)

### Description of your issue or question

My name is Shiyuan, and I am a PhD student from Professor Christopher Tessum’s research group at the University of Illinois Urbana-Champaign (UIUC). Recently, our group has been actively involved in an air-quality modeling study, and we are looking for biogenic emissions data for use in InMAP simulations.
 
First, I wanted to express our sincere appreciation for your valuable contributions in providing daily soilnox and biovoc emissions data from 2014 to 2023, which we found on the website [http://geoschemdata.wustl.edu/ExtData/HEMCO/](https://urldefense.com/v3/__http:/geoschemdata.wustl.edu/ExtData/HEMCO/__;!!DZ3fjg!8Df60KzHYD_5n20q9u_KraudFlmiMKAuQWLkIONuCWuk-bhz3-8xY1mX185MN_oUkgi_hrOQbfJT8CthAxotmMaYZhrp$). Your efforts have been immensely helpful in advancing our research.
 
However, we still need simulations for 2000-2013. Given the expertise and resources available through your organization, we were wondering if you also have access to or maintain biogenic emissions data for these earlier years. Alternatively, if you are aware of any reputable sources or contacts that could assist us in acquiring the necessary daily soilnox and biovoc emissions data for the 2000-2013 period, we would greatly appreciate your guidance.
 
Thank you for considering our inquiry, and we are grateful for your continued support in advancing the field of air-quality modeling. Looking forward to your reply!

**Comment by yantosca** [comment]
Thanks for writing @Saran-Wang.  I am also tagging @SaptSinha who has been generating the offline emissions for GEOS-Chem, so that he can comment as well.

Are you using GEOS-FP or MERRA-2 meteorology.  I believe the GEOS-FP product started around 2013 so it is not possible to go back further in time.  For earlier dates you can use the MERRA-2 meteorology, which goes back to about 1980.  I think we should have online emissions earlier in time than 2014 for MERRA-2.

**Comment by SaptSinha** [comment]
Thanks for reaching out, @Saran-Wang and @yantosca . We are glad to know that the datasets we produce have been of help to you.

The GEOS-FP native datasets, which are utilized to process the daily offline emissions files for the different species, are not available at the source for older years. As such, we currently only have the offline emissions files for biogenic VOCs and soil NOx from 2014 onwards. The links to these GEOS-FP based offline emissions files for the two species in question are provided below: 
http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_BIOVOC/v2021-12/0.25x0.3125/
http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_SOILNOX/v2021-12/0.25x0.3125/

That said, the MERRA2 raw datasets are available from 1980 onwards. We also produce offline emissions files for biogenic VOCs and soil NOx based on MERRA2. These are available from 1980 and the links to the MERRA2 based offline emissions files for biogenic VOCs and soil NOx are  listed below. These might be helpful to address the year range 2000-2013 for your work.
http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_BIOVOC/v2021-12/0.5x0.625/
http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_SOILNOX/v2021-12/0.5x0.625/

**Comment by Saran-Wang** [comment]
Thank you for the reply! I have another quick question. Is the CRS for those .nc files WGS84 (EPSG:4326)?

**Comment by SaptSinha** [comment]
It might be a good idea to try and see the difference in results you get using the MERRA2 based offline emission files, and compare that with the GEOS-FP based results that you were previously using. @yantosca may be able to provide further information regarding this aspect.

**Comment by yantosca** [comment]
Closing out this issue.  Feel free to open a new issue if you get stuck.
