### ISSUE TITLE
AEIC2019 Species

### ISSUE THREAD

**Issue by yangning-code** [geoschem/geos-chem#1948]
### Name and Institution (Required)

Name: NingYang
Institution: JNU

### Confirm you have reviewed the following documentation
Confirm
- [ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question
Why are species like BENZ, TOLU, XYLE, and NAP missing in the AEIC species list of GEOS-Chem v14.1.1's HEMCO_Config.rc? Have you considered adding these species to the list?

**Comment by yantosca** [comment]
Thanks for writing @yangning-code.  The AEIC emissions (like all GEOS-Chem emissions) come to us from external developers (in this case, @sdeastham).  You might be able to add BENZ, TOLU, XYLE, and NAP to the HEMCO_Config.rc by scaling them from another species that is included in AEIC2019.  But this is beyond our expertise so we would not be able to advise you further.

Also take a look at the [AEIC2019 technical note](http://ftp.as.harvard.edu/gcgrid/data/ExtData/HEMCO/AEIC2019/v2022-03/AEIC_2019_technical_note.pdf), which will give you some more insight into how these emissions were generated.

**Comment by yangning-code** [comment]
Thank you very much

**Comment by yantosca** [comment]
Thanks @yangning-code.  I'll go ahead and close out this issue.  Feel free to open a new issue if you still have questions.
