### ISSUE TITLE
HEMCO Volcano emissions 2022 availability?

### ISSUE THREAD

**Issue by tessac2** [geoschem/geos-chem#1956]
### Name and Institution (Required)
Name: Tessa Clarizio
Institution: University of Illinois Urbana Champaign

### Confirm you have reviewed the following documentation
- [x ] [Contributing guidelines](https://geos-chem.readthedocs.io/en/stable/reference/CONTRIBUTING.html)

### New GEOS-Chem feature or discussion

I was wondering when the /ExtData/HEMCO/VOLCANO/v2021-09/2022 emissions would become available? It seems only January 1, 2022 is uploaded. Thanks!

**Comment by yantosca** [comment]
Hi @tessac2, thanks for writing.  In GEOS-Chem 14.1.0 (I think this was the version) we introduced a volcano climatology that you can use for dates outside of the range of the volcano data archive.   See the entries in this `[HEMCO_Config.rc.fullchem](
https://github.com/geoschem/geos-chem/blob/main/run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem) template file.

I'm not sure if there are more recent volcano emissions available.  Also tagging @msulprizio.

**Comment by yantosca** [comment]
Also tagging the Emissions Working Group co-chairs: @eamarais @jaegle

**Comment by msulprizio** [comment]
We obtain out volcano emissions from GMAO. At this website, it looks like they may have volcano emissions through Feb 2022 via their v202302 release: https://gmao.gsfc.nasa.gov/gmaoftp/geoscf/volcano_so2/v202302/.

We can look into updating these emissions in 14.3.0. In the meantime, we welcome you to download and use the latest emissions. You will just need to update the path to the volcano files in HEMCO_Config.rc.

**Comment by tessac2** [comment]
Thank you for all your help!!

**Comment by yantosca** [comment]
Hi @tessac2, just wanted to close the loop here.  The updated volcano emissions will ship with 14.4.0 (PR #2198 is already in the 14.4.0 development branch).
