### ISSUE TITLE
[BUG/ISSUE]Problem with addding tagged CH4 tracers

### ISSUE THREAD

**Issue by Rainbow1994** [geoschem/geos-chem#196]
# Report a GEOS-Chem bug or technical issue

## Describe the bug
I tried to change tagCH4 species from default setting to my own species types in tag CH4 simulation, so I modified global_ch4_mod.f and hcoi_gc_diagn_mod.f in ./GeosCore and species_database_mod.f in ./Headers. At the same time, I alse modified corresponding input.geos, HEMCO_Config.rc and HEMCO_Diagn.rc. When the number of tag species is 14, my code can compile well and run successfully, but it turns out some unexpected bugs at the end of simulation when I added the species number to 40. 

## To Reproduce
Include the steps that must be done in order to reproduce the observed behavior:

**Compilation commands**
1. make realclean
2. make -j32 mpbuild

**Run commands**
1. ./geos.mp

## Expected behavior
The modified code with any tag species can run sucessfully and complete normally.

## Error messages
here is screenshots when species number is 40 
![image](https://user-images.githubusercontent.com/29177864/72559988-fcc4d380-389d-11ea-9d77-d2b7a922e8be.png)
![image](https://user-images.githubusercontent.com/29177864/72559998-02bab480-389e-11ea-8bfb-87d6d3ef7e0d.png)
 
here is a successful screenshot when tag species number is 14
![image](https://user-images.githubusercontent.com/29177864/72560091-2ed63580-389e-11ea-8790-42ce76580abd.png)

## Required information
Please include the following:
 - GEOS-Chem v12.5.0

## Input and log files to attach
For more info, see: http://wiki.geos-chem.org/Submitting_GEOS-Chem_support_requests
 - The lastbuild file
 - The input.geos file
[input.geos.txt](https://github.com/geoschem/geos-chem/files/4073660/input.geos.txt)

 - The HEMCO_Config.rc file
[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/4073661/HEMCO_Config.rc.txt)

 - The HEMCO_Diagn.rc
[HEMCO_Diagn.rc.txt](https://github.com/geoschem/geos-chem/files/4073662/HEMCO_Diagn.rc.txt)

## Additional context
Include any other context about the problem here.

**Comment by msulprizio** [comment]
It appears your simulation is crashing during the cleanup phase when various module arrays are deallocated. The second screenshot above specifically shows that the run is crashing at line 382 in diag_mod.F when deallocating array AD19. That array holds the BPCH diagnostic information for [methane loss](http://wiki.seas.harvard.edu/geos-chem/index.php/List_of_diagnostics_archived_to_bpch_format#ND19:_CH4_loss).  I would recommend making sure AD19 is allocated and used properly in your updated code, focusing specifically on any changes you made.

If you haven't already, I recommend running with array-out-of-bounds checking turned on to make sure there isn't an upstream issue causing this error. See our [debugging GEOS-Chem](http://wiki.seas.harvard.edu/geos-chem/index.php/Debugging_GEOS-Chem#Recompile_GEOS-Chem_with_debug_options_turned_on) wiki page for more details.

**Comment by yantosca** [comment]
For reference, also see [this post on in our Guide to GEOS-Chem Error Messages](http://wiki.seas.harvard.edu/geos-chem/index.php/Other_less-common_errors#Memory_error:_.22free:_invalid_size.22}.   

This error does seem that you are trying to free memory from a pointer variable that hasn't been allocated yet.

**Comment by Rainbow1994** [comment]
Many thanks for both your kind replies, I'll check array AD19 and find more information from reference.

**Comment by yantosca** [comment]
I will close out this issue for now.  Feel free to reopen if necessary.
