### ISSUE TITLE
Seasalt error in GEOS-Chem

### ISSUE THREAD

**Issue by haohe1982** [geoschem/geos-chem#1962]
### Name and Institution (Required)

Name: Hao He
Institution: University of Maryland

### Confirm you have reviewed the following documentation

- [ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

I am running GEOS-Chem with 0.625x0.5 degree solution but it crashed in Dec 2003 with negative seasalt error (see the attached file). I tried several times to restart the run but failed. Any suggestion on how to fix this problem? Thanks!
[gc.log](https://github.com/geoschem/geos-chem/files/12619934/gc.log)

**Comment by haohe1982** [comment]
I tried to change HEMCO.config but still had this problem. Is it an emissions file problem or boundary conditions problem (I used 4x5 global GC runs as the boundary for the NA domain)?

**Comment by yantosca** [comment]
Thanks for writing @haohe1982.  We recently added some fixes into the upcoming GEOS-Chem 14.2.0 so as to prevent doing seasalt chemistry in the stratosphere (as there all of the seasalt should have been scavenged out).  Please see the following for potential fixes:

- PR #1779
- PR #1933 

Also tagging @msulprizio

**Comment by haohe1982** [comment]
Hi Bob,

Thanks for your quick response. I am using the GCC-classic to build the
model. How should I implement these fixes?

Hao

**Comment by yantosca** [comment]
@haohe1982: What I would do is to clone a second copy of GEOS-Chem Classic, and then in that code, [check out each of the commits](https://geos-chem.readthedocs.io/en/latest/getting-started/quick-start.html#clone-geos-chem-classic) shown here: https://github.com/geoschem/geos-chem/pull/1779/commits and compare that against your code.  Then apply the fixes into your code.

I would also open a new branch in yuoru

**Comment by haohe1982** [comment]
Hi Bob,

I downloaded the latest code (v14.1.1.), but under the
KPP/fullchem/fullchem_HetStateFuncs.F90, I can not find the code like
related to Alk_SSA (see the attached file). Did I download the wrong git? I
used the command 'git clone --recurse-submodules
https://github.com/geoschem/GCClassic.git GCClassic'.

**Comment by yantosca** [comment]
@haohe1982: We will likely be releasing GEOS-Chem 14.2.1 next week.  I would take that version as soon as it releases, as it will have all of the relevant fixes included.

**Comment by yantosca** [comment]
@haohe1982: GEOS-Chem 14.2.1 is now released.  See our [GEOS-Chem Newsletter 2023, Issue 2](https://drive.google.com/file/d/1t-ePO-_csQpPgtbUjoRuDUX0Ib6f-qL2/view) newsletter for details:

**Comment by haohe1982** [comment]
Great. Thanks a lot for your help!

**Comment by yantosca** [comment]
Thanks @haohe1982.  I will close out this issue.
