### ISSUE TITLE
Doubling the SO2 emission

### ISSUE THREAD

**Issue by ast222340** [geoschem/geos-chem#1965]
### Name and Institution (Required)

Name: Subhadeep Ghosh
Institution: IIT Delhi

### Confirm you have reviewed the following documentation

- [Y] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [Y] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [Y] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [Y] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

I am using GEOS-Chem Classic v14.1.1.I want to double SO2 anthropogenic emission.Tell me where to go and which code to change. What have I changed inside the emissions_mod.F90 file but can't see any change HEMCO_diagnostics.201901010000.nc output file same as normal run output file.It would be great if you could tell me where i should go to change or how should be changed in which code.I want the normal emission that is after doubling that emission is showing its double in that output file 'HEMCO_diagnostics.201901010000.nc'(I mean I will see it through plotting or panoply visualization).

**Comment by msulprizio** [comment]
Hi @ast222340. You will want to use scale factors in HEMCO_Config.rc. Please see examples here: https://hemco.readthedocs.io/en/stable/hco-ref-guide/more-examples.html?highlight=scale#scale-factor-examples.

**Comment by ast222340** [comment]
Thank you @msulprizio. When I changed ScalIDs from '-' to 2 in following line (in HEMCO_Config.rc file).I attached my error message.I am not able to do it till now...please help me..How can I change.
0 CEDS_SO2_ENE    $ROOT/CEDS/v2021-06/$YYYY/SO2-em-anthro_CMIP_CEDS_$YYYY.nc           SO2_ene           1750-2019/1-12/1/0 C xy kg/m2/s SO2   2         1 5
https://github.com/geoschem/geos-chem/assets/135971477/29c8477a-05b6-45bc-ac00-449e7d5712c3
https://github.com/geoschem/geos-chem/assets/135971477/534edf2c-2e1a-4ec7-825a-5faba09e0445

**Comment by msulprizio** [comment]
The error you are getting is `HEMCO ERROR: No scale factor with ID: 2`. The value you put in the ScalID column (in this case 2) must match a scale factor ID defined in the Scale Factors section of HEMCO_Config.rc. See [this example](https://hemco.readthedocs.io/en/stable/hco-ref-guide/more-examples.html?highlight=scale#zero-emissions-of-selected-species) -- except instead of zeroing emissions, you will want to use a value of 2.0.

See also the general overview of HEMCO_Config.rc: https://hemco.readthedocs.io/en/stable/hco-ref-guide/hemco-config.html.

**Comment by yantosca** [comment]
Closing out this issue
