### ISSUE TITLE
[DISCUSSION] Profiling GEOS-Chem to locate bottlenecks

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#197]
I was able to do a 1-day GEOS-Chem profiling simulation on the AWS cloud:

 * AWS ```c4.2xlarge``` instance (8 cores)
 * AMI: ```GEOSChem-dev-gcc9.2.0``` (```ami-0db45eda61a721639```)
 * 1-day geosfp_4x5_standard simulation, 2016/07/01 (dev/12.7.0 pre-release version)

My run script was:
```bash
#!/bin/bash
# Script for profiling GEOS-Chem: default values
tau_exec -T serial,pthread -ebs ./geos > log 2>&1
```
The libraries I used were Spack-built and and loaded via the environment-modules :
```
Currently Loaded Modulefiles:
 1) gcc-9.2.0-gcc-7.4.0-ixzamnv      9) openmpi-3.1.5-gcc-9.2.0-dsv3nfy
 2) cgdb-0.7.0-gcc-9.2.0-mysijpp    10) openjdk-11.0.2-gcc-9.2.0-zsbesgk
 3) cmake-3.16.2-gcc-9.2.0-syhmoa5  11) netcdf-c-4.7.3-gcc-9.2.0-vwsyve2
 4) flex-2.6.4-gcc-9.2.0-cwzzptf    12) netcdf-fortran-4.5.2-gcc-9.2.0-fcc6ogr
 5) gdb-8.3.1-gcc-9.2.0-74pltbv     13) ncview-2.1.7-gcc-9.2.0-54fse3n
 6) gmake-4.2.1-gcc-9.2.0-nbjc66h   14) perl-5.30.0-gcc-9.2.0-6dasuuv
 7) hdf5-1.10.5-gcc-9.2.0-qkhexie   15) tau-2.28.2-gcc-9.2.0-cnlhvz2
 8) nco-4.7.9-gcc-9.2.0-nfljt23
```

Machine parameters:
![tau_stats](https://user-images.githubusercontent.com/5880296/72649046-89c56680-394a-11ea-83e9-5173d134f64b.png)

And here is a quick-plot of the maximum time across all cores per function.
![tau_1day_max](https://user-images.githubusercontent.com/5880296/72649060-93e76500-394a-11ea-8273-c5749cbeaa82.png)

The top few routines where time is being spent are:
1. kppdecomp (KPP solver)
2. futex_wait (system library) -- this seems to be some kind of barrier, maybe in !OMP PARALLEL DO loop synchronization?
3. libm.so -- the Math library.  .
4. libc.so -- C-language library?
5. kppsolve (KPP solver)
6. kppdecomp (KPP solver)
7. do_spin -- This seems to be another barrier
8. fun (KPP solver)
9. kppdecomp (KPP solver)
10. do_cloud_convection_constantprop --maybe broadcasting of variables (i.e. setting a whole array to zero, etc)
11. hco_calcemis (HEMCO)
12. jac_sp (KPP)
13. dictionary_m mod (hash lookup)
... etc ...

My observations:
1. It seems like we are spending a lot of time in a barrier state (in futex_wait and do_spin).  Maybe the barrier at the end of parallel loops is incurring this.
2. Also seems like the math library libm may be costing us speed.  We could think about using a faster math library (like Intel Math Kernel Library)?
3. I'm surprised that the constant propagation in convection_mod is taking so long.
4. A lot of time is spent in the KPP libraries, but that's not a surprise.

I can do a deeper dive. You can get line number information from the profiling output, and that can point us to the offending code blocks.

Thoughts: @jimmielin, @JiaweiZhuang, @kilicomu, @msulprizio, @lizziel, @WilliamDowns , @LiamBindle

**Comment by kilicomu** [comment]
@yantosca I think these results are similar to the VTune results that I produced a while ago, and perhaps point towards a workload imbalance between OpenMP threads at some key point (chemistry, maybe?).

**Comment by kilicomu** [comment]
We discussed modifying the scheduling at:

https://github.com/geoschem/geos-chem/blob/00e12f6bc04870dbfdb959bcf1e3cd0068c8ab35/GeosCore/flexchem_mod.F90#L602

as a quick check to see whether or not it would result in a different execution profile.
