### ISSUE TITLE
Segmentation fault: GEOS-Chem 14.1.1 stops after "### MAIN: a INTERP, etc"

### ISSUE THREAD

**Issue by bailu-bailu** [geoschem/geos-chem#1970]
### Name and Institution (Required)

Name: Ao Chen
Institution: Johns Hopkins University 

### Confirm you have reviewed the following documentation

- [X] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [X] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [X] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [X] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.
===> Mode of operation         : GEOS-Chem "Classic"
===> GEOS-Chem version         : 14.1.1

Hi, I encountered a "Segmentation fault" issue while running GEOS-Chem 14.1.1. This problem did not appear in the  `GC.log`, but rather in the `slurm.1663968.out` file. I tried increasing the memory to 60000, but I still encountered the same problem. I also attempted to change the species being run to CO2, but encountered the same issue. 

I downloaded and compiled from scratch without making any changes to the configuration files. In the `gc.log` file, it abruptly stops after `"### MAIN: a INTERP, etc"` without any error messages (I have set my `debug_printout: true`). I had no issues running GEOS-Chem 13.3.1 using the same steps. 

I attached my GC.log, slurm.out, and run script as follows. Thank you very much for your time and patience.

[GC.log](https://github.com/geoschem/geos-chem/files/12713108/GC.log)
[slurm-1663968.out.log](https://github.com/geoschem/geos-chem/files/12713114/slurm-1663968.out.log)
[geoschem.run_sbatch.log](https://github.com/geoschem/geos-chem/files/12713123/geoschem.run_sbatch.log)

**Comment by yantosca** [comment]
Thanks for writing @bailu-bailu.  In your sbatch run script I see you have:
```bash
# Set the proper # of threads for OpenMP
# SLURM_CPUS_PER_TASK ensures this matches the number you set with -c above
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
```
But you will also need to add right below this:
```bash
export OMP_STACKSIZE=500m
```
as this will tell your Bash shell within the SLURM job to use as much stacksize memory as possible.   See: https://geos-chem.readthedocs.io/en/stable/gcc-guide/01-startup/login-env-parallel.html for more information.

**Comment by bailu-bailu** [comment]
Thank you very much for your suggestion! It works! This is amazing that we don't need to add this line in version 13.3.1, but we need to add it in version 14.1.1.

**Comment by yantosca** [comment]
Thanks @bailu-bailu.  You probably have that line in your ~/.bashrc file.  When you run in a SLURM queue you are running in a different shell so you either have to source your ~/.bashrc from within the run script or set the OMP_STACKSIZE variable within the run script.  I'll go ahead and close out this issue.

**Comment by yantosca** [comment]
@bailu-bailu: Glad it worked!
