### ISSUE TITLE
TotalAOD from the RRTMG collection does not match with the sum of all individual AODs from the same collection

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/geos-chem#1972]
### Name and Institution (Required)

Name: Fei Yao
Institution: The University of Edinburgh

### Description of your issue or question

Hi GC team,

I recently conducted a standard RRTMG simulation using the GEOS-Chem Classic 14.1.1 for January 2019. I didn't make any changes to the source codes. Rather, I only configured `HISTORY.rc` to output as many time-averaged RRTMG diagnostics as possible every three hours. However, I noticed a discrepancy: the TotalAOD from the RRTMG collection doesn't align with the sum of all individual AODs from the same collection. 

For instance, when I used the following codes, I found that the main difference is in the high-latitude regions. I'm wondering if my understanding is correct that the total AOD should be the sum of all individual AODs? Or is there something I've misunderstood?

All the best,
Fei

```
import xarray as xr
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cmaps

def plot_dr(dr, cmap=cmaps.WhiteBlueGreenYellowRed):
    fig = plt.figure(figsize=(10,5))
    ax = plt.axes(projection=ccrs.PlateCarree())
    dr.plot(ax=ax, cmap=cmap)
    ax.coastlines()
    return fig

ds_rrtmg = xr.open_dataset("../rundirs/201901/OutputDir/GEOSChem.RRTMG.20190101_0000z.nc4")
fig = plot_dr((ds_rrtmg["RadAOD550nm_PM"]
               -ds_rrtmg["RadAOD550nm_SU"]
               -ds_rrtmg["RadAOD550nm_NI"]
               -ds_rrtmg["RadAOD550nm_AM"]
               -ds_rrtmg["RadAOD550nm_BC"]
               -ds_rrtmg["RadAOD550nm_OA"]
               -ds_rrtmg["RadAOD550nm_SS"]
               -ds_rrtmg["RadAOD550nm_DU"]).mean(dim="time"))

```

![image](https://github.com/geoschem/geos-chem/assets/43779303/e7c3bf15-1184-4431-ba31-c1f37e19cee7)

**Comment by yantosca** [comment]
Tagging @sdeastham

**Comment by lizziel** [comment]
Hi @FeiYao-Edinburgh, it is not clear that the PM diagnostic is supposed to be the totalAOD. I assume you are using it that way based on the computation you provided above. We recommend reaching out to others in the community about this since this is beyond the scope of the GEOS-Chem Support Team.

@sdeastham, do you know the answer to this question or who might be a good person for @FeiYao-Edinburgh to contact?

**Comment by sdeastham** [comment]
Hi all - I think PM is indeed meant to be total AOD. However, @FeiYao-Edinburgh - I think you missed out stratospheric aerosol ("RadAOD550nm_ST")?

**Comment by sdeastham** [comment]
Hi all - I think PM is indeed meant to be total AOD. However, @FeiYao-Edinburgh - I think you missed out stratospheric aerosol ("RadAOD550nm_ST")?

**Comment by FeiYao-Edinburgh** [comment]
Hi @sdeastham  - it's my bad to miss the `RadAOD550nm_ST`, after including which I found that the TotalAOD generally matches the sum of all individual AODs at the level of `rtol=0` and `atol=0.01`:
```
np.allclose(ds_rrtmg["RadAOD550nm_PM"].mean(dim="time"),
            (ds_rrtmg["RadAOD550nm_SU"]
             +ds_rrtmg["RadAOD550nm_NI"]
             +ds_rrtmg["RadAOD550nm_AM"]
             +ds_rrtmg["RadAOD550nm_OA"]
             +ds_rrtmg["RadAOD550nm_BC"]
             +ds_rrtmg["RadAOD550nm_SS"]
             +ds_rrtmg["RadAOD550nm_DU"]
             +ds_rrtmg["RadAOD550nm_ST"]).mean(dim="time"),
            rtol=0,
            atol=0.01)
>>>True
```
The plot has been updated to the following:
![image](https://github.com/geoschem/geos-chem/assets/43779303/23e8b4fc-3aa6-4215-9463-ab6c98cb1118)

Not sure whether we should pay a bit more attention to the values of up to 0.002 around east Africa.

Meanwhile, I found that `RadAOD550nm_ST` is for UCX only. Are we running UCX by default from `v14.1.1`? @yantosca

**Comment by yantosca** [comment]
I will close out this issue for now.  Please feel free to open a new issue if you are still having problems.
