### ISSUE TITLE
SpeciesConc file time is 0 despite no errors

### ISSUE THREAD

**Issue by ncolombi** [geoschem/geos-chem#1975]
### Name and Institution (Required)

Name: Nadia Colombi
Institution: Harvard

### Confirm you have reviewed the following documentation

- [ X] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [X ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ X] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ X] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

I am running GCClassic version 14.2.0. My simulation (beginning 2019-01-01) saving monthly SpeciesConc output is running with no errors. The SpeciesConc files for January and February look normal, but the March and April output are empty (time is 0 as shown in the screenshot below). I've attached the SpeciesConc netCDF for March  as well as my config files below. 

![Screen Shot 2023-10-04 at 10 51 38 AM](https://github.com/geoschem/geos-chem/assets/55603859/1617286f-d408-4bf0-96ac-564affdeb991)

[HEMCO_Config.rc.zip](https://github.com/geoschem/geos-chem/files/12805493/HEMCO_Config.rc.zip)
[GEOSChem.SpeciesConc.20190301_0000z.nc4.zip](https://github.com/geoschem/geos-chem/files/12805378/GEOSChem.SpeciesConc.20190301_0000z.nc4.zip)
[geoschem_config.yml.zip](https://github.com/geoschem/geos-chem/files/12805492/geoschem_config.yml.zip)

**Comment by msulprizio** [comment]
Nadia wrote:

> I think my issue with the SpeciesConc file saying Time = 0 is solved. After waiting a while, I viewed the file again and it now has data. Although the GC.log file says that the simulation is currently on the month of June, the SpeciesConc file GEOSChem.SpeciesConc.20190501_0000z.nc4 is still 0 but the April one is now normal. It seems that the May file is still being written to even though the simulation is already on June. Is this a normal thing and I just didn't realize it before? I've never ran a monthly averaged simulation, only daily averages, so I haven't encountered this before.

@yantosca replied:

> I think the netCDF file isn't flushed until it's written. We may have put a fix in but I'd have to doublecheck.

**Comment by lizziel** [comment]
There was an issue created a while back about the diagnostics not being fully written until the end of the next diagnostic period. https://github.com/geoschem/geos-chem/issues/1464

The issue was closed since a fix went into 14.2.0. If that fix isn't working we should reopen.

**Comment by yantosca** [comment]
Closing this issue, as the discussion has now moved to #2094 and corresponding draft PR #2096.
