### ISSUE TITLE
Some 14.2.1 simulation runs fail due to missing species in restart file

### ISSUE THREAD

**Issue by lizziel** [geoschem/geos-chem#1986]
### Name and Institution (Required)

Name: Lizzie Lundgren
Institution: Harvard University

### Description of your issue or question

GEOS-Chem 14.2.0 and 14.2.1 transport tracer and standard full chemistry simulations fail because several advected species are not found in the restart file that comes with the run directory. The restart files included in run directories are the same as in 14.1.0 and need to be updated. 14.2.0/14.2.1 includes new tracers in these simulations. The transport tracer simulation also features several species with new names.

We will release a version 14.2.2 that uses the new restart files generated during the 14.2.0 benchmark.

**GC-Classic work-around:** Allow GC-Classic to use background values for missing species by updating `HEMCO_Config.rc` time cycling entry for restart variable species (`SPC_` in 2nd column) from `EFY0` to `EY`.

**GCHP work-around**: You can allow GCHP to use background values for missing species by setting `Require_Species_in_Restart` in run directory config file `setCommonRunSettings.sh` to `0` (false).

**Comment by yantosca** [comment]
Also see PR #1990, which adds a check for missing species into the integration test scripts.

**Comment by msulprizio** [comment]
The fix for this (PR #1989) has now been merged into dev/14.2.2.

**Comment by msulprizio** [comment]
Sample restart files from the 1-year fullchem and TransportTracer benchmarks are now available at http://geoschemdata.wustl.edu/ExtData/GEOSCHEM_RESTARTS/GC_14.2.0/.
