### ISSUE TITLE
'Segmentation fault - invalid memory reference' error in a 0.5x0.625 simulation

### ISSUE THREAD

**Issue by garvitagarwal290** [geoschem/geos-chem#1988]
### Name and Institution (Required)

Name: Garvit Agarwal
Institution: TCS, Pune

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

I am trying to run a 0.5x0.625 CO2 simulation from 1st July 2019 to 21st July 2019, keeping all settings unchanged. I downloaded all the required data using the dry run, but when I run the simulation, i get the following error:
```console
=================================================
GEOS-Chem ERROR: Error encountered within call to "Init_CMN_FJX"!
 -> at GC_Allocate_All  (in module GeosCore/gc_environment_mod.F90)
=================================================

=================================================
GEOS-CHEM ERROR: Error encountered in "GC_Allocate_All"!
STOP at  -> at GEOS-Chem (in GeosCore/main.F90)
=================================================
```
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
 
When I try to run the same simulation for lower resolution like 4x5 and 2x2.5, the simulation runs with no error. In my run script, I have also put 'ulimit -s unlimited' and 'export OMP_STACKSIZE=500m'. The system I am running it on has 8 GB RAM. Is it that such high resolution simulation requires more RAM?

**Comment by yantosca** [comment]
Thanks for writing @garvitagarwal290.  Would you be able to post your configuration files (geoschem_config.yml, HEMCO_Config.rc) and also the complete run log to this issue.

It looks like the code is trying to allocate arrays in the FAST-JX photolysis, which shouldn't be needed for CO2.  The config files and run logs will help us figure out what is going on.

**Comment by yantosca** [comment]
@garvitagarwal290: If you are running with a single species only (like CO2) then I would think 8GB would be sufficient.  But when you turn on a lot of diagnostic outputs, the memory usage increases.  You might also want to try turning off all diagnostics to see if the run goes through without failing.

**Comment by garvitagarwal290** [comment]
[GC.log.txt](https://github.com/geoschem/geos-chem/files/12903486/GC.log.txt)
[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/12903488/HEMCO_Config.txt)
[geoschem_config.txt](https://github.com/geoschem/geos-chem/files/12903487/geoschem_config.txt)

**Comment by yantosca** [comment]
Closing out this issue.
