### ISSUE TITLE
About Meteorological field

### ISSUE THREAD

**Issue by Racha711** [geoschem/geos-chem#1995]
### Name and Institution (Required)

Name: Racha Samermit
Institution: Kyoto University

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

I would like to discuss about if we need to simulate future climate change on air quality using GEOS-Chem (GCClassic 14.1.0), particularly see the precipitation changes. To over come the uncertainties that could be happened on such meteorological parameters, if it possible that can we directly use some datasets from CMIP6 ensembles as multi-model mean and incorporated directly to GEOS-Chem or not. 

Thank you very much

**Comment by yantosca** [comment]
Thanks for writing @Racha711.  At present, we would recommend using GCAP2 meteorology for future simulations (tagging @ltmurray who knows more about this data).  

Modifying GEOS-Chem Classic to accept e.g. CMIP6 meteorology inputs is beyond the scope of our expertise, and thus, the GEOS-Chem Support Team would not be able to advise how that can be done.

**Comment by ltmurray** [comment]
The CMIP6 experimental design did not include diagnostics archived at sufficient temporal resolution (hourly for 2-D fields and 3-hourly for 3-D fields) for driving a CTM like GEOS-Chem. One would have to rerun the climate model and output the many additional diagnostics, as I have done for one ensemble member of the GISS E-2.1-R contributions to CMIP6. If you are interested in looking at ensembles, the best solution would be to look at the CMIP6 output from simulations that included online aerosols themselves.

**Comment by Racha711** [comment]
@yantosca @ltmurray Thank you very much for your discussions and suggestions.
