### ISSUE TITLE
v14.2.0 restart files

### ISSUE THREAD

**Issue by cschooling** [geoschem/geos-chem#1996]
### Name and Institution (Required)

Name: Chlöe Schooling
Institution: University of Edinburgh

### Confirm you have reviewed the following documentation

- [x] Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question
Hi,

I have just downloaded the latest version 14.2.0. 
However, I am struggling to access the Restart files for this version, as I am told I don't have permissions.
http://geoschemdata.wustl.edu/ExtData/GEOSCHEM_RESTARTS/

**Comment by msulprizio** [comment]
@cschooling Can you try again? I am able to access the files in http://geoschemdata.wustl.edu/ExtData/GEOSCHEM_RESTARTS/GC_14.2.0/.

**Comment by yantosca** [comment]
@cschooling: We will also be releasing GEOS-Chem 14.2.2, which fixes issue #1986, in which some "out-of-the-box" simulations fail due to missing species in the restart files.  @msulprizio has uploaded the new restart files so that all species are present.

**Comment by msulprizio** [comment]
@cschooling I see the permission issue now. The directory is accessible, but the files are not. 

@SaptSinha @Jourdan-He  Could one of you fix the file permissions in ExtData/GEOSCHEM_RESTARTS/GC_14.2.0?

**Comment by cschooling** [comment]
I am still struggling to access the files

**Comment by SaptSinha** [comment]
The permissions for all the files in the [GEOSCHEM_RESTARTS](http://geoschemdata.wustl.edu/ExtData/GEOSCHEM_RESTARTS/) directory and sub-directories are now fixed, except for a few within the GC_13.0.0 and GC_14.0.0 folders.

**Comment by cschooling** [comment]
Thank you I have access now

**Comment by msulprizio** [comment]
Thanks @SaptSinha! I will close out this issue.
