### ISSUE TITLE
GEOS-FP data

### ISSUE THREAD

**Issue by yangning-code** [geoschem/geos-chem#1999]
### Name and Institution (Required)

Name: NingYang
Institution:  JNU

### Confirm you have reviewed the following documentation
Confirm
- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals]（https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html）
- [x] [Debugging GEOS-Chem and HEMCO errors]（https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html）
- [x] [Current and past Github issues]（https://github.com/geoschem/geos-chem/issues）

### Description of your issue or question
Where can I download earlier GEOS-FP data? For example, data from 2000 to the present.

**Comment by yangning-code** [comment]
Thank you.
But I need to run nested in China with a resolution of only GEOS-FP 0.25x0.3125. Do you have any methods for generating GEOS-FP meteorological data?

**Comment by yantosca** [comment]
@yangning-code: The GEOS-FP data are generated by NASA/GMAO and we just download them.  

You could try using MERRA2 0.25 x 0.625 meteorology and let HEMCO regrid that to the 0.25 x 0.3125 grid.  That might work.

**Comment by yangning-code** [comment]
Thank you.
I don't understand this sentence, "You could try using MERRA2 0.25 x 0.625 meteorology and let HEMCO regrid that to the 0.25 x 0.3125 grid." Are you suggesting directly using HEMCO to call MERRA2 meteorological data, which will automatically adjust the resolution to 0.25x0.3125 for nesting, or are you referring to some other approach?

**Comment by yantosca** [comment]
@yangning-code: Sorry for the confusion.  HEMCO in GEOS-Chem should be able to regrid the meteorological data to the grid resolution that you are using.  However, we don't have much experience in e.g. using MERRA-2 meteorology at the 0.25 x 0.3125 grid.  You would be on your own.

**Comment by yangning-code** [comment]
Thank you

**Comment by yantosca** [comment]
Closing out this issue.  Feel free to open a new issue if you are still stuck.
