### ISSUE TITLE
Corrupt data: GEOS_0.5x0.625_NA/MERRA2/1984/03/MERRA2.19840303.I3.05x0625.NA.nc4

### ISSUE THREAD

**Issue by Row-Bean** [geoschem/geos-chem#2001]
Name: Robin Stevens
Institution: Université de Montréal

The air temperature in file GEOS_0.5x0.625_NA/MERRA2/1984/03/MERRA2.19840303.I3.05x0625.NA.nc4 is mostly zeros for the last two time slices.

![image](https://github.com/geoschem/geos-chem/assets/20319934/8580e1ed-ac29-4e18-89a6-89a63c5130f4)

**Comment by SaptSinha** [comment]
Thank you for letting us know. I have reprocessed and uploaded the MERRA2.19840303.I3.05x0625.NA.nc4 file and it is available for you to access from http://geoschemdata.wustl.edu/ExtData/GEOS_0.5x0.625_NA/MERRA2/1984/03/.

**Comment by Row-Bean** [comment]
Thank you very much! I downloaded the new file, and it looks right.
