### ISSUE TITLE
a question about Carbon monoxide simulation

### ISSUE THREAD

**Issue by CodeCatLZW** [geoschem/geos-chem#2004]
i use the defualt configuration，when i set the simulation's time greater than  2021.1.1，i  while get a error:

>Cannot retrieve data for NOAA_GMD_CH4, CMIP6_Sfc_CH4, or 
SfcVMR_CH4 from HEMCO! Make sure the data source corresponds to your emissions 
year in HEMCO_Config.rc (NOAA GMD for 1978 and later; else CMIP6).
 -> at CHEM_TAGGED_CO (in GeosCore/tagged_co_mod.F90)

This seems to be because GMD_SFC_CH4 has a max-date only up to December 2020，i don't know what should i do now.

**Comment by yantosca** [comment]
Thanks for writing @CodeCatLZW.  You can change the `RY` time cycle flags in HEMCO_Config.rc to `CYS` (see below) so that it will reuse the last year of data.  This may not be scientifically appropriate (you would need to ask your advisor) but that would let the model proceed into 2021 without stopping with the error you saw.
```kconfig
#==============================================================================
# --- NOAA GMD monthly mean surface CH4 ---
#==============================================================================
(((GMD_SFC_CH4
* NOAA_GMD_CH4 $ROOT/NOAA_GMD/v2018-01/monthly.gridded.surface.methane.1979-2020.1x1.nc SFC_CH4 1979-2020/1-12/1/0 RY xy ppbv * - 1 1
)))GMD_SFC_CH4
```

**Comment by CodeCatLZW** [comment]
Thanks for your answer, It helps me a lot.
I would also like to ask about the specific meaning of the `RY` time cycle flags, I do not seem to find a description of the letter `R` in the official documentation.
Thanks again, this solved my problem.

**Comment by yantosca** [comment]
@CodeCatLZW: `R` = "Range".  Which means only to apply the data if the simulation year falls into the range specified.

**Comment by CodeCatLZW** [comment]
Thanks, I also found the description in the official documentation.
`https://hemco.readthedocs.io/en/stable/hco-ref-guide/hemco-config.html?highlight=RY#cmdoption-arg-RY`
