### ISSUE TITLE
[QUESTION] Where are detailed GEOS-Chem Aerosol Optical Depth calculation formula?

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/geos-chem#201]
I have posted the following issue to geos-chem aerosol working group but would also like to put it here in case any of you know it.

Hi there,

From [here](http://acmg.seas.harvard.edu/geos/meetings/2011/pdf/Day1/MonD_AerClim_curci_gabriele_1_pc.pdf) it seems that there is a wiki describing how to calculate aerosol optical depth from aerosol concentrations using a series of aerosol properties. I would be grateful if someone could provide a the link pointing to detailed description for AOD calculation in GEOS-Chem. Currently 3/4 in the slide or aerosol_mod.F surprised me a lot.

Thanks in advance for your help!

Yours faithfully,
Fei

**Comment by yantosca** [comment]
I am adding this reply from Gabriele Curci (gabriele.curci@aquila.infn.it) to this issue:

>Dear Fei,
>
>the formula you see in the slide and the code is derived from Chin et al. 2002: https://www.gfdl.noaa.gov/bibliography/related_files/mchin0201.pdf. The 3/4 factor derives from the fact that at some point there is a division by the volume of a sphere (4/3*pi*r^3) that not completely cancels.
>
>The Q efficiencies for model aerosol species are tabulated in jv_spec.dat as a function of RH. For each aerosol species a size distribution, spectral refractive index and hygroscopic growth factor is assumed (has listed in the headings of jv_spec.dat) and the Q's are calculated using the "spher" program by Michael Mischchenko: https://www.giss.nasa.gov/staff/mmishchenko/brf/.
>
>Hope this helps,
>Gabriele
