### ISSUE TITLE
A question about switching to GEOS_0.25x0.3125_CH

### ISSUE THREAD

**Issue by CodeCatLZW** [geoschem/geos-chem#2016]
I'm using version 14.1.1，and I'm running a simulation of 0.25x0.3125.  
I found that the simulation downloads the following weather file by default.But this file is too big.
![image](https://github.com/geoschem/geos-chem/assets/75576802/51ccf001-c58d-47f8-9a55-cf07f5b5e6c7)

So, I want to know how to switch to the following weather file.
![image](https://github.com/geoschem/geos-chem/assets/75576802/014369d0-24cb-4e6d-903d-16f35fd2da48)

**Comment by yantosca** [comment]
Thanks @CodeCatLZW for writing.  I believe you want the GEOS_0.25x0.3125_AS grid instead.  The CH grid was subsumed into the AS grid.  Also tagging @msulprizio.

When you [create a run directory](https://geos-chem.readthedocs.io/en/latest/gcclassic-user-guide/create-rundir.html), specify that you wish to use the Nested Asia window for GEOS-FP.  Then when you [do a dry-run simulation](https://geos-chem.readthedocs.io/en/latest/gcclassic-user-guide/dry-run.html), the appropriate data will be downloaded.

**Comment by CodeCatLZW** [comment]
Thanks, @yantosca , I create a new  run directory,  and I choose the asia.
![A1HT6U2W3WW76)WMEQMEX6L](https://github.com/geoschem/geos-chem/assets/75576802/8243fd1b-44a7-4fdf-ab20-ff8981f4e8e6)
however, The `dry-run`  generate  the  'log.230101-230103.dryrun'   will still download the global meteorology  file. 
![image](https://github.com/geoschem/geos-chem/assets/75576802/5ae84b7d-d54f-4cca-a95e-05fcff82b4a7)


there is my geoschem_config.yml :
![image](https://github.com/geoschem/geos-chem/assets/75576802/fa24e968-368d-40ad-b9f2-b23f065457e3)

and there is my generated  dryrun file :
![image](https://github.com/geoschem/geos-chem/assets/75576802/daeda3dd-b1d3-49e0-82fc-8449ae949463)
![image](https://github.com/geoschem/geos-chem/assets/75576802/80d4c1d6-5661-4d75-a545-a824bbb280fc)

Maybe I need to change some other configuration, but I just can't find a way.

**Comment by yantosca** [comment]
Thanks @CodeCatLZW.  You might have to edit the entries for the meteorology to add the `_AS` in `HEMCO_Config.rc, then do the dry-run.

**Comment by CodeCatLZW** [comment]
Thanks, @yantosca for your answer. I edit  `METDIR`  in HEMCO_Config.rc  and  add  `.AS` in  HEMCO_Config.rc.gmao_metfields,
![image](https://github.com/geoschem/geos-chem/assets/75576802/e940d6da-f053-42bf-be2c-c9a1589bb4ec)
![image](https://github.com/geoschem/geos-chem/assets/75576802/5ddb53a4-de10-47d9-a408-703d23609333)

then,I do the dry-run  and  I  get  a  dryl.og    which   I  want.
![image](https://github.com/geoschem/geos-chem/assets/75576802/add1752a-ddb8-4270-939e-ac9c6699734f)

This did solve my problem, but I added a lot of `AS` in the process, will your team do the same.
