### ISSUE TITLE
missing MERRA2 0.5x0.625 met files for 2023-05-27  on wustl 

### ISSUE THREAD

**Issue by hgrhgy** [geoschem/geos-chem#2019]
There are only four files for 2023-05-27,  missing **A3cld** and **A3mstC**. 
http://geoschemdata.wustl.edu/ExtData/GEOS_0.5x0.625/MERRA2/2023/05/

**Comment by SaptSinha** [comment]
I have updated the following files for 2023-05-27. Let us know if you encounter any further issues.

MERRA2.20230527.A1.05x0625.nc4
MERRA2.20230527.A3cld.05x0625.nc4
MERRA2.20230527.A3dyn.05x0625.nc4
MERRA2.20230527.A3mstC.05x0625.nc4
MERRA2.20230527.A3mstE.05x0625.nc4
MERRA2.20230527.I3.05x0625.nc4
