### ISSUE TITLE
[QUESTION] GEOS_0.25x0.3125 in 2013 shown as SPEED files?

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/geos-chem#202]
Hi there,

I recently want to download some GEOS_0.25x0.3125 files in 2013. I was guided to download them from Compute Canada. However, I found the files stored [here](http://geoschemdata.computecanada.ca/ExtData/GEOS_0.25x0.3125/GEOS_FP/2013/10/) are like the following. I suppose they are not correct and may request your attention?

![image](https://user-images.githubusercontent.com/43779303/72994772-a43a8c80-3def-11ea-95c1-e8f420d39034.png)

Yours faithfully,
Fei

**Comment by yantosca** [comment]
@FeiYao-Edinburgh, I believe these data are surface wind speed, SQRT(u10m**2 +  v10m**2).  This was a research product that we produced for a proposed dust algorithm but we abandoned work on it.

**Comment by lizziel** [comment]
2013 GEOS-FP 0.25x0.3125 data reprocessed for use in GEOS-Chem is not available. At the time we started processing the quarter degree global data (for use in GCHP) a complete set of the raw data was not readily available that far back.

**Comment by FeiYao-Edinburgh** [comment]
Thanks for letting know!
