### ISSUE TITLE
Question about nested simulation

### ISSUE THREAD

**Issue by ast222340** [geoschem/geos-chem#2020]
### Name and Institution (Required)

Name: Subhadeep Ghosh
Institution: IIT Delhi

### Confirm you have reviewed the following documentation

- [ Y ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ Y ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ Y ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ Y ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

I have done model configuration for Custom grid 
Choose horizontal grid domain:
-----------------------------------------------------------
  1. Global
  2. Asia
  3. Europe
  4. North America
  5. Custom
select option 5.

grid:
  resolution: 0.5x0.625
  number_of_levels: 47
  longitude:
    range: [ 56.0, 106.0]
    center_at_180: true
  latitude:
    range: [0.0, 40.0]
    half_size_polar_boxes: true
  nested_grid_simulation:
    activate: true
    buffer_zone_NSEW: [3, 3, 3, 3]

Thus I run the model successfully and the output file was created. After running the model, I checked with the panoply and found that the model was running above mentioned the nested grid (longitude range,latitude range), Here I have not used any boundary conditions. But the problem is here. 

Many people say that this simulation is not correct because I did not use any boundary conditions. They say that you first do a global simulation of 4.0  x 5.0 and add this boundary condition from there. Boundary condition file will be created for that. The boundary condition file that is generated is used as input to the nested grid simulation.

That't why I am totally confused which is the correct method. It would be great if you could explain it to me better.

**Comment by msulprizio** [comment]
@ast222340 Thanks for writing. Could you please attach your GEOS-Chem log file here? That will provide more information about the model configuration you have set up and how GEOS-Chem calculates the grid.

**Comment by ast222340** [comment]
Thank you @msulprizio.I have attached GC log file.Please suggest me what should i do?
### 
GC.log https://github.com/geoschem/geos-chem/files/13240777/GC.log
[geoschem_config.pdf](https://github.com/geoschem/geos-chem/files/13241039/geoschem_config.pdf)

**Comment by yantosca** [comment]
@ast222340 @msulprizio.  It could be that HEMCO is allowing the run to proceed even though there are no boundary condition files specified.  It could be bootstrapping the fields to default values like 1e-20.

The boundary conditions for nested-grid simulations are needed in order to make sure that "realistic" concentrations are supplied at the edges of the nested-grid domain window.

**Comment by yantosca** [comment]
@ast222340 could you also please post your HEMCO_Config.rc?

**Comment by ast222340** [comment]
Thank you @yantosca.
[HEMCO_Config.pdf](https://github.com/geoschem/geos-chem/files/13243144/HEMCO_Config.pdf)
[HISTORY.pdf](https://github.com/geoschem/geos-chem/files/13243156/HISTORY.pdf)
Finally,it is better to tell me what to do or not to do....

**Comment by yantosca** [comment]
```console
#==============================================================================
# --- GEOS-Chem boundary condition file ---
#==============================================================================
(((GC_BCs
* BC_
$ROOT/SAMPLE_BCs/v2021-09/fullchem/GEOSChem.BoundaryConditions.$YYYY$MM$DD_$HH$MNz.n
c4 SpeciesBC_?ADV? 1980-2021/1-12/1-31/* EFY xyz 1 * - 1 1
)))GC_BCs

```

**Comment by ast222340** [comment]
Thank you @yantosca. You kept this matter for test.
So I will now create the boundary file by doing the global simulation in  4.0 x 5.0 grid.Then the boundary files that will be created will be used as input for nested grid..For now then I will have to do it this way.

**Comment by yantosca** [comment]
Closing out this issue now.  Feel free to open a new issue if you are still stuck.
