### ISSUE TITLE
a question about BoundaryConditions  file in CH4 0.25x0.3125_AS  simulation  by  V14.1.1

### ISSUE THREAD

**Issue by CodeCatLZW** [geoschem/geos-chem#2021]
I am going to run a CH4  0.25x0.3125_AS  simulation from 230101 to 230103,   and I do the dry-run  .   However I find the BoundaryConditions    file  tend  to  download  from   230101 to 230103,  Like this:

> HEMCO: Opening /WRF-Chem/tyuan/ExtData/GEOS_0.25x0.3125_AS/GEOS_FP/2023/01/GEOSFP.20230102.I3.025x03125.AS.nc
HEMCO: REQUIRED FILE NOT FOUND /WRF-Chem/tyuan/ExtData/HEMCO/SAMPLE_BCs/v2021-07/CH4/GEOSChem.BoundaryConditions.20230101_0000z.nc4
HEMCO: Opening /WRF-Chem/tyuan/ExtData/HEMCO/Yuan_XLAI/v2021-06/Yuan_proc_MODIS_XLAI.025x025.2020.nc
HEMCO: Opening ./Restarts/GEOSChem.Restart.20230101_0000z.nc4
TIMEZONES (i.e. OFFSETS FROM UTC) WERE COMPUTED FROM LONGITUDE
 HEMCO already called for this timestep. Returning.
HEMCO WARNING: No further attempts will be made to read file: ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4
--> LOCATION: HCOIO_READ (HCOIO_READ_STD_MOD.F90)
HEMCO: Opening /WRF-Chem/tyuan/ExtData/HEMCO/CH4/v2020-09/GFED/GFED4_CH4_FIRE_2019.nc
HEMCO: Opening /WRF-Chem/tyuan/ExtData/GEOS_0.25x0.3125_AS/GEOS_FP/2023/01/GEOSFP.20230102.A1.025x03125.AS.nc
HEMCO: Opening /WRF-Chem/tyuan/ExtData/GEOS_0.25x0.3125_AS/GEOS_FP/2023/01/GEOSFP.20230102.A3cld.025x03125.AS.nc
HEMCO: Opening /WRF-Chem/tyuan/ExtData/GEOS_0.25x0.3125_AS/GEOS_FP/2023/01/GEOSFP.20230102.A3dyn.025x03125.AS.nc
HEMCO: Opening /WRF-Chem/tyuan/ExtData/GEOS_0.25x0.3125_AS/GEOS_FP/2023/01/GEOSFP.20230102.A3mstC.025x03125.AS.nc
HEMCO: Opening /WRF-Chem/tyuan/ExtData/GEOS_0.25x0.3125_AS/GEOS_FP/2023/01/GEOSFP.20230102.A3mstE.025x03125.AS.nc
HEMCO: Opening /WRF-Chem/tyuan/ExtData/GEOS_0.25x0.3125_AS/GEOS_FP/2023/01/GEOSFP.20230102.I3.025x03125.AS.nc
HEMCO: Opening /WRF-Chem/tyuan/ExtData/GEOS_0.25x0.3125_AS/GEOS_FP/2023/01/GEOSFP.20230103.I3.025x03125.AS.nc
HEMCO: REQUIRED FILE NOT FOUND /WRF-Chem/tyuan/ExtData/HEMCO/SAMPLE_BCs/v2021-07/CH4/GEOSChem.BoundaryConditions.20230102_0000z.nc4
HEMCO: Opening /WRF-Chem/tyuan/ExtData/HEMCO/Yuan_XLAI/v2021-06/Yuan_proc_MODIS_XLAI.025x025.2020.nc
HEMCO: Opening /WRF-Chem/tyuan/ExtData/HEMCO/CH4/v2020-09/GFED/GFED4_CH4_FIRE_2019.nc
HEMCO: Opening /WRF-Chem/tyuan/ExtData/GEOS_0.25x0.3125_AS/GEOS_FP/2023/01/GEOSFP.20230103.A1.025x03125.AS.nc
HEMCO: Opening /WRF-Chem/tyuan/ExtData/GEOS_0.25x0.3125_AS/GEOS_FP/2023/01/GEOSFP.20230103.A3cld.025x03125.AS.nc
HEMCO: Opening /WRF-Chem/tyuan/ExtData/GEOS_0.25x0.3125_AS/GEOS_FP/2023/01/GEOSFP.20230103.A3dyn.025x03125.AS.nc
HEMCO: Opening /WRF-Chem/tyuan/ExtData/GEOS_0.25x0.3125_AS/GEOS_FP/2023/01/GEOSFP.20230103.A3mstC.025x03125.AS.nc
HEMCO: Opening /WRF-Chem/tyuan/ExtData/GEOS_0.25x0.3125_AS/GEOS_FP/2023/01/GEOSFP.20230103.A3mstE.025x03125.AS.nc
HEMCO: Opening /WRF-Chem/tyuan/ExtData/GEOS_0.25x0.3125_AS/GEOS_FP/2023/01/GEOSFP.20230103.I3.025x03125.AS.nc
HEMCO: Opening /WRF-Chem/tyuan/ExtData/GEOS_0.25x0.3125_AS/GEOS_FP/2023/01/GEOSFP.20230104.I3.025x03125.AS.nc
HEMCO: REQUIRED FILE NOT FOUND /WRF-Chem/tyuan/ExtData/HEMCO/SAMPLE_BCs/v2021-07/CH4/GEOSChem.BoundaryConditions.20230103_0000z.nc4
HEMCO: Opening /WRF-Chem/tyuan/ExtData/HEMCO/Yuan_XLAI/v2021-06/Yuan_proc_MODIS_XLAI.025x025.2020.nc

In fact, there is  only one  BoundaryConditions   file  in the  `wustl `   just is   `[GEOSChem.BoundaryConditions.20190101_0000z.nc4](http://geoschemdata.wustl.edu/ExtData/HEMCO/SAMPLE_BCs/v2021-07/CH4/GEOSChem.BoundaryConditions.20190101_0000z.nc4)/` .

I tried to modify the `GC_BCs `entry of  `HEMCO_Config.rc`,  like this :

>  (((GC_BCs
> * BC_ $ROOT/SAMPLE_BCs/v2021-07/CH4/GEOSChem.BoundaryConditions.$YYYY$MM$DD_0000z.nc4 SpeciesBC_?ADV?  1980-2021/1-12/1-31/*   CYS  xyz 1 * - 1 1
> )))GC_BCs

I changed the period from  `EFY `  to   `CYS` , but it seems to be starting to download data for 2021, like this:

> HEMCO: REQUIRED FILE NOT FOUND /WRF-Chem/tyuan/ExtData/HEMCO/SAMPLE_BCs/v2021-07/CH4/GEOSChem.BoundaryConditions.20210101_0000z.nc4

So what should I do now.

**Comment by msulprizio** [comment]
Hi @CodeCatLZW. The boundary condition file provided at WashU is a sample file for testing purposes and should not be used. You will need to generate your own boundary conditions by running a global (4x5 or 2x2.5 simulation) and saving out the BoundaryConditions collection in HISTORY.rc for your period of interest.

**Comment by CodeCatLZW** [comment]
Thank you for your response @msulprizio . I know your means, and then I set the `GC_BCs `clause in the `HEMCO_Config.rc` file to `false`. 
![image](https://github.com/geoschem/geos-chem/assets/75576802/f7282c22-a5bd-4ee6-9b76-933db98ff212)

And it seems to be working quite well. I will generate these boundary condition files later if necessary.

In addition to this, I would also like to know if there is any effect of not using the `boundary condition file` in this CH4 grid simulation.

**Comment by CodeCatLZW** [comment]
Hi, @msulprizio , Happy new week. If you have time, can you help me solve this puzzle. Thank you very much!

**Comment by msulprizio** [comment]
Hi @msulprizio. The `GC_BCs` option should always be true for nested-grid simulations. We do not recommend turning them off as it will result in incorrect species concentrations being advected into your domain. If the boundary conditions files are not found, the species concentrations on all four of the domain edges will be set to a background concentration value (1e-20 for most species, but 1.8e-6 or 1800 ppb for CH4).

**Comment by CodeCatLZW** [comment]
Hi, @msulprizio, Thank you for your reply. I see what you mean, I will try it with `true` later.

**Comment by msulprizio** [comment]
OK. I will close out this issue, but feel free to open another one if you have additional questions.

**Comment by CodeCatLZW** [comment]
thanks,   @msulprizio . I turned on `GC_BCs`, and I changed the emission cycle field of GC_BCs from `EFY `to `EY`, and the simulation no longer stopped because of the lack of boundary conditions files.
