### ISSUE TITLE
How to Change speciesCon unit in Boundary Condition file

### ISSUE THREAD

**Issue by ast222340** [geoschem/geos-chem#2023]
### Name and Institution (Required)

Name: Subhadeep Ghosh
Institution:Delhi

### Confirm you have reviewed the following documentation

- [ Y ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ Y ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ Y ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
-  ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question
I need to change the unit of boundary condition of Species.Default is saved as mol/mol dry air.And when I'm running nested grid.I want it be molec/cm3(I have also changed like this).At the boundary condition,the unit of species(mol/mol) and the unit of nested grid species's(molel/cm3)are different. So that why showing error.
#==============================================================================
# %%%%% THE BoundaryConditions COLLECTION %%%%%
#
# GEOS-Chem boundary conditions for use in nested grid simulations
#
# Available for all simulations
#==============================================================================
  BoundaryConditions.template:   '%y4%m2%d2_%h2%n2z.nc4',
  BoundaryConditions.frequency:  00000000 030000
  BoundaryConditions.duration:   00000001 000000
  BoundaryConditions.mode:       'instantaneous'
  BoundaryConditions.fields:     'SpeciesBC_?ADV?             ',

It is better if you tell me which line to change the unit.
[GC.log](https://github.com/geoschem/geos-chem/files/13248069/GC.log)
[geoschem_config.pdf](https://github.com/geoschem/geos-chem/files/13248072/geoschem_config.pdf)
[HEMCO_Config.pdf](https://github.com/geoschem/geos-chem/files/13248073/HEMCO_Config.pdf)
[HISTORY.pdf](https://github.com/geoschem/geos-chem/files/13248074/HISTORY.pdf)

**Comment by msulprizio** [comment]
Hi @ast222340. We do not recommend changing the units of the boundary conditions files. GEOS-Chem saves them out in the same units that it expects to read them in (mol/mol). Changing the units will cause erroneous values when reading in and applying those boundary conditions to nested grid simulations. If you want to convert the units for other use, you can post-process the boundary condition netCDF files using python or other tools.

**Comment by ast222340** [comment]
Thank you @msulprizio. My idea is now clear.
