### ISSUE TITLE
Is it possible to create a docker image for GEOS-Chem?

### ISSUE THREAD

**Issue by garvitagarwal290** [geoschem/geos-chem#2024]
### Name and Institution (Required)

Name: Garvit Agarwal
Institution: TCS, Pune, India

### Confirm you have reviewed the following documentation

- [ ] [Contributing guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/CONTRIBUTING.html)

### New GEOS-Chem feature or discussion

The compute facility that my company provides doesnt give me a command-line interface where I can install GEOS-Chem and run it. Instead I have been told to create a docker image for GEOS-Chem so that I can run it in a docker container. From my very elementary understanding so far, I think that it should be possible to make a docker image for GEOS-Chem but while we create a run directory, we need to type inputs in the terminal window. I dont know how to incorporate this in my docker file.

**Comment by yidant** [comment]
Thanks for asking @garvitagarwal290. We provide docker images that contain pre-built GCHP source code and the tools for creating a GCHP run directory. See [Use GCHP Containers](https://gchp.readthedocs.io/en/latest/supplement/containers.html) for reference. 

If you'd like to build your own containers, I would recommend you set up the environment and build GCHP in your dockerfile. You can then pull the image and use the terminal to create your run directories.

**Comment by garvitagarwal290** [comment]
Hi, thank you for your response. 

I had a different question. Can you please tell me how emission/met. fields are written in files for the cube-sphere grid? For a lat-long grid, I understand it's simply a 2-D array but for a cube-sphere grid, how is the information stored? Also, how can I regrid the data from cube-sphere to lat-long grid?

**Comment by msulprizio** [comment]
@garvitagarwal290 Could you please open a separate issue for your new question. This helps with issue archival and searching. Thanks!
