### ISSUE TITLE
Nested simulation_severe (174): SIGSEGV, segmentation fault occurred

### ISSUE THREAD

**Issue by yangbyy** [geoschem/geos-chem#2026]
### Name and Institution (Required)

Name: Shuangqin Yang
Institution: Tianjin Normal University, China

### Confirm you have reviewed the following documentation

- [ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question
Hi, I am running an Asian nested simulation (full chemistry, MERRA-2, horizontal resolution of 0.5 x 0.625, 47 layers) using the GEOS-Chem v14.0.0 model. When I run it with the command "_sbatch geoschem.run_", I get the error message "**severe (174): SIGSEGV, segmentation fault occurred**". 
I tried to set _-DCMAKE_RELEASE_TYPE=Debug_, and then I got the message shown below.
![image](https://github.com/geoschem/geos-chem/assets/115625689/08ee39c8-bc23-4924-bc3c-bffd28910f44)
![image](https://github.com/geoschem/geos-chem/assets/115625689/248c75db-8329-4b77-b47b-10246cae0842)

Honestly, I really haven't edited the files **qfyaml_mod.F90** and s**pecies_database_mod.F90**, and I don't know the reason of the error report for the time being, could you help me to check it? Thank you very much!!!
[GC_log.txt](https://github.com/geoschem/geos-chem/files/13259887/GC_log.txt)
[geoschem_config_yml.txt](https://github.com/geoschem/geos-chem/files/13259871/geoschem_config_yml.txt)
[HEMCO_Config_rc.txt](https://github.com/geoschem/geos-chem/files/13259867/HEMCO_Config_rc.txt)
[HISTORY_rc.txt](https://github.com/geoschem/geos-chem/files/13259868/HISTORY_rc.txt)
[species_database_yml.txt](https://github.com/geoschem/geos-chem/files/13259870/species_database_yml.txt)

**Comment by yantosca** [comment]
Thanks for writing @yangbyy.  GEOS-Chem could not read the `species_database.yml` file.  Either it was missing from the run directory, or it did not have the proper Linux permissions to let you read it.

**Comment by yangbyy** [comment]
Thank you! @I'm trying to create a new run directory, and it hasn't been completely resolved yet. Apart from that, I would like to confirm with you the time system used by the GEOC-Chem model, is it UTC? Because I want to compare the hourly averages of the output concentrations, so figuring this out is important to me. Looking forward to your reply!

**Comment by yangbyy** [comment]
@yantosca Thank you! I'm trying to create a new run directory, and it hasn't been completely resolved yet. Apart from that, I would like to confirm with you the time system used by the GEOC-Chem model, is it UTC? Because I want to compare the hourly averages of the output concentrations, so figuring this out is important to me. Looking forward to your reply!

**Comment by yantosca** [comment]
Hi @yangbyy.  The times in GC and Hemco are in UTC (sometimes called Zulu or z for short).
