### ISSUE TITLE
[BUG/ISSUE] Issue about FlexGrid simulation in GC 12.5.0

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#203]
I am adding this issue on behalf of Tianlang Zhao (tzhao@alaska.edu):

>Currently I am using GEOS-Chem 12.5.0 to do 0.5x0.625 resolution regional simulation. The simulation doesn’t crash, but there are many ERROR notes in the log file. Could you please help me figure out these ERRORs? 
>
>I first ran a 2x2.5 resolution global simulation and save the boundary condition files around Alaska. Since I am focusing at Alaska region, which is not default nested grid region, so I create a global simulation run directory instead, and define the region (the same region as I define the boundary condition in the previous run) in the input.geos. Also I modify the HEMCO_Config.rc and add the directory of Boundary condition files. 
>
>I did 2x2.5 boundary condition run from 20180701 to 20180702, and did 0.5x0.625 run for just 20180702, to make sure the boundary condition contains the time 12:00 am. But the ERROR doesn’t disappear.
>
>The ERROR in the log file is like:
```
===============================================================================
---> DATE: 2018/07/02  UTC: 00:10  X-HRS:      0.166667
===============================================================================
GEOS-Chem ERROR: No boundary condition found for NO
-> at Get_Boundary_Conditions (in GeosCore/hcoi_gc_main_mod.F)
===============================================================================
```

**Comment by yantosca** [comment]
Thanks for writing.  At first glance it seems like the code cannot find the files that you created.

Can you attach the input.geos and log files to this issue?  We will need to see those before we can make a proper assessment of what went wrong.  You can just drag & drop files into the comment box (but text files should have the ```.txt``` extension appended to them. 

See our [Submitting GEOS-Chem support requests](http://wiki.seas.harvard.edu/geos-chem/index.php/Submitting_GEOS-Chem_support_requests) wiki page for detailed instructions about which files to include with this issue.

**Comment by Holton1** [comment]
[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/4106830/HEMCO_Config.rc.txt)
[log.txt](https://github.com/geoschem/geos-chem/files/4106831/log.txt)
[input.geos.txt](https://github.com/geoschem/geos-chem/files/4106832/input.geos.txt)

Thank you very much!

**Comment by yantosca** [comment]
Thanks for the files.   I see the issue.  The filename in HEMCO_Config.rc:

```
(((GC_BCs
* BC_      /import/c1/GREENING/tzhao/gcrun1250/merra2_2x25_tropchem/OutputDir/GEOSChem.BoundaryConditions.20180702_0000z.nc4 SpeciesBC_?ADV?
)))GC_BCs
```

should be

```
(((GC_BCs
* BC_      /import/c1/GREENING/tzhao/gcrun1250/merra2_2x25_tropchem/OutputDir/GEOSChem.BoundaryConditions.$YYYY$MM$DD_$HH$MNz.nc4 SpeciesBC_?ADV?
)))GC_BCs
```

Otherwise, it is looking for the specific BC file for 2018/07/02 but because your run is for 2018/07/01, it isn't finding it.
