### ISSUE TITLE
GEOS-Chem versions and corresponding code and user manuals from its inception to the present

### ISSUE THREAD

**Issue by yangning-code** [geoschem/geos-chem#2032]
### Name and Institution (Required)

Name: NingYang 
Institution: JNU

### Confirm you have reviewed the following documentation

- [ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question
I want to thoroughly study the development process of GEOS-Chem, especially the usage and code for each version. Therefore, I would like to find all versions of GEOS-Chem along with their corresponding manuals and source code.
Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

**Comment by msulprizio** [comment]
Hi @yangning-code. The GEOS-Chem documentation was recently migrated to ReadTheDocs: https://geos-chem.readthedocs.io/. You can view the documentation for recent versions (14.0.0+) there by clicking on the link for "v: stable" at the very bottom of the left side bar.

The archive of past user documentation can be accessed here: https://geoschem.github.io/gcclassic-manpage-archive/.

For more information and links, please see the [GEOS-Chem versions](https://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_versions) wiki page.

**Comment by yangning-code** [comment]
On this website (https://geoschem.github.io/gcclassic-manpage-archive/), the oldest version is GEOS-Chem v6-02-05 manual, and it does not have corresponding code. On another website (http://ftp.as.harvard.edu/gcgrid/geos-chem/1yr_benchmarks/), there is GEOS-Chem v4-26, but it also lacks corresponding code. What I'm looking for is the code for each version and its corresponding manual. I'm not sure if you have them organized, but if not, I really appreciate your assistance.

**Comment by yangning-code** [comment]
Thank you

**Comment by msulprizio** [comment]
I will close out this issue, but you may comment here or open a new issue if you have additional questions.
