### ISSUE TITLE
[BUG] ST80 tracer cannot be set correctly due to error in tracer_mod

### ISSUE THREAD

**Issue by sdeastham** [geoschem/geos-chem#2033]
For the tracer transport simulation, the source region can be set by pressure which is necessary for the `st80_25` tracer. The relevant code is linked below, and reads two values (`PresMin` and `PresMax`) from the species database file - in the case of `st80_25` those values are 0 and 80:

https://github.com/geoschem/geos-chem/blob/7e00810e5161a1f0f9855ed416753a8b7961a8b0/GeosCore/tracer_mod.F90#L266-L267

However, as written, this code will not result in the mask being set to zero anywhere. The check incorrectly looks for the lower edge pressure of the grid cell to be greater than the maximum, **and** for the upper edge pressure to be smaller than the minimum. That in turn implies that the cell's upper bound is above the target region AND the lower bound is below the target region, which can happen in at most one cell (in reality it will happen in none for any reasonably-sized source region).

This issue manifests as near constant mixing ratios in the tracer transport tests (see http://ftp.as.harvard.edu/gcgrid/geos-chem/1yr_benchmarks/14.2.0-rc.2/GCHP/TransportTracers/BenchmarkResults/GCHP_GCC_comparison/TransportTracers/AnnualMean/TransportTracers_FullColumn_ZonalMean_AnnualMean.pdf). As shown in the image below, the mixing ratio is constant at 500 hPa which it very much should not be. Interestingly there is a misleading vertical pattern in the zonal plot linked above; this is because, although the source region is incorrectly uniform, the loss region is still correctly specified as the troposphere, so there's an infinitesimal difference between the stratosphere and troposphere.

![image](https://github.com/geoschem/geos-chem/assets/6618732/86467931-c8b6-4711-8420-ce9df7617d73)

I believe the correct fix for this is to replace the logical check with

```
! Set mask to zero outside of pressure levels
    IF ( State_Met%PEDGE(I,J,L)   < SpcInfo%Src_PresMin   .or.  &
         State_Met%PEDGE(I,J,L+1) > SpcInfo%Src_PresMax ) THEN
    Mask(I,J,L) = 0.0_fp
ENDIF
```

however I defer to the GCST as I may not have thought this through in full.

**Comment by lizziel** [comment]
This bug makes sense to me. However, do we want to mask all cells that partially overlap the source pressure region, which is what your fix does, or do we want to include the cells with partial overlap? I think the original code attempted to **not** mask cells with overlap. We could do that by checking if either edge pressures are within the bounds (pseudocode):
```
if ( ( PEDGE(L) >= Pmin .and. PEDGE(L) <= Pmax ) .or. &
      ( PEDGE(L+1) >= Pmin .and. PEDGE(L+1) <= Pmax ) ) then
   set mask
endif
```
But I'm not sure if that is the intention of the diagnostic. I also wonder if there is a bug in the GMAO code. We should check TRGridComp.

**Comment by lizziel** [comment]
My psuedocode needs a further check to see if the source region is included in the entire cell pressure range. If yes, I assume that would not be masked either, as done in the original code.

**Comment by sdeastham** [comment]
I think that strictly we should probably be setting the mask with partial values. It probably doesn't matter _too_ much since (I think?) the pressure levels are constant by the time we get to 80 hPa - but this would get messy if comparing (eg) 72 and 47 level runs, or 72 level runs against the new 91/181-level data whenever it's available. And of course if somebody wanted to have a tracer which is generated at lower altitude or in a thinner band then this would get very messy. Could we set the mask based on the pressure thickness which is within the level?

**Comment by lizziel** [comment]
This bug fell off the radar for a while. We will try to get a fix in for 14.4.

**Comment by lizziel** [comment]
I checked the code in GMAO's TR gridded component and [this](https://github.com/GEOS-ESM/TR/blob/f9110d9a504097eaf7ad6cc1a63489838552ca4f/TR_GridCompMod.F90#L3624-L3627) is what is done for 3D masking given pressure:
```
     IF ( TRIM(spec%src_vert) == "pressures" ) THEN
       WHERE ( (p .GE. spec%src_press1) .AND.  &
               (p .LE. spec%src_press2) )          src_mask3d         = .TRUE.
     END IF
```
Here `src_press1` is minimum pressure and `src_press2` is maximum pressure, set to 0 and 80 in `TR_GridComp---st80_25.rc`  as shown [here](https://github.com/GEOS-ESM/TR/blob/f9110d9a504097eaf7ad6cc1a63489838552ca4f/TR_GridComp---st80_25.rc#L22). The pressure order in the config file does not matter, e.g. `80 0` versus `0 80`. The code finds the min and max of the two values to set `src_press1` and `src_press2`.

I will update the code in GEOS-Chem to use this same algorithm.

**Comment by lizziel** [comment]
@msulprizio, do you remember if why the source pressure mask criteria in GEOS-Chem differs from GMAO TR? Before I make this fix I want to make sure it wasn't intentional.

**Comment by lizziel** [comment]
To be clear, in the TR code `src_mask3d = .TRUE.` means NOT set to zero. So the new code in GEOS-Chem would be:
```
! Set mask to zero outside of pressure levels
IF ( .not. ( State_Met%PEDGE(I,J,L)  >= SpcInfo%Src_PresMin   .and.  &
       State_Met%PEDGE(I,J,L) <= SpcInfo%Src_PresMax ) ) THEN
        Mask(I,J,L) = 0.0_fp
ENDIF
```

**Comment by yantosca** [comment]
We can now close out this issue as PR #2226 has been merged into the "no-diff-to-benchmark" development stream, and will ship with version 14.3.1.
