### ISSUE TITLE
[Clarification] Difference between <Collection>.frequency and <Collection>.duration?

### ISSUE THREAD

**Issue by garvitagarwal290** [geoschem/geos-chem#2035]
### Name and Institution (Required)

Name: Garvit Agarwal
Institution: TCS, Pune, India

### Confirm you have reviewed the following documentation

- [ ] [Contributing guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/CONTRIBUTING.html)

### New GEOS-Chem feature or discussion

What is the difference between <Collection>.frequency and <Collection>.duration parameters in the HISTORY.rc file? I understand that <Collection>.duration is the rate at which a new output file will be created for that collection but then what exactly is the meaning of <Collection>.frequency? Suppose I have 00000100 000000 (monthly) for <Collection>.frequency and 00000100 000000 (monthly) for <Collection>.duration, and <Collection>.mode is 'time-averaged'. Does that mean that each file will have only one reading of the <collection> since both the duration and frequency are monthly? If yes, then in this case it won't be a time-averaged reading and will be 'instantaneous'?

If my above understanding is correct then, if I have 00000001 000000 (daily) for <Collection>.frequency and 00000100 000000 (monthly) for <Collection>.duration, then will each (monthly) file have an average of 30 readings from each day? Thank you.

**Comment by lizziel** [comment]
Hi @garvitagarwal290. GEOS-Chem has the capability of writing multiple times to a single file. The frequency relative to the duration determines how many times will be included. If frequency is equal to duration then each diagnostic file will have one time only. If frequency is half of duration, e.g. duration 24hr and frequency 12hr, then each file will have two times in the file.

For you example (00000100 000000 for both frequency and duration) you will have the monthly mean data in each month's file. If you set the mode to 'time-averaged' then the values will be averaged over the entire month. If you set the mode to instantaneous then you would have the instantaneous value at the start of the month.

For you second example (daily frequency and monthly duration) you will get the daily mean for each day within each monthly file, assuming you set mode to time-averaged. If you set mode to instantaneous then you will get the instantaneous value at the start of each day. I am not sure where you get 30 readings from each day. The values averaged over the entire day are for each timestep, of which there are 6*24 if you have a 10 minute timestep.

**Comment by garvitagarwal290** [comment]
Thank you @lizziel for the clarification, I guess it was self-evident!
