### ISSUE TITLE
Nested simulation_Program received signal SIGABRT

### ISSUE THREAD

**Issue by yangbyy** [geoschem/geos-chem#2037]
### Name and Institution (Required)

Name and Institution (Required)
Name: Shuangqin Yang
Institution: Tianjin Normal University, China

Confirm you have reviewed the following documentation
 [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
 [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
 [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
 [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)
Description of your issue or question
Hi, I am running an Asian nested simulation (full chemistry, MERRA-2, horizontal resolution of 0.5 x 0.625, 47 layers) using the GEOS-Chem v14.0.0 model. 

- When I run it with the command "./gcclassic | tee GC.log", I get the error message "**Program received signal SIGABRT: Process abort signal**." Seriously, I do not know what's wrong with my run, could you please do me a favor? Thank you so so so much!!!

![1](https://github.com/geoschem/geos-chem/assets/115625689/f5c4d3dd-6a8a-4970-9b71-39ea120a40e1)
![2](https://github.com/geoschem/geos-chem/assets/115625689/ab890d43-21b8-494e-b1cc-88600d57aa19)

![state_diag_list_error](https://github.com/geoschem/geos-chem/assets/115625689/d4ccea70-b24c-47fd-87d5-50bb820e4111)
![state_diag_list_erro2r](https://github.com/geoschem/geos-chem/assets/115625689/ceab8cf3-6c23-4dda-8a33-cdbadcd43813)

[GC.txt](https://github.com/geoschem/geos-chem/files/13371525/GC.txt)
[geoschem_config.txt](https://github.com/geoschem/geos-chem/files/13371526/geoschem_config.txt)
[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/13371527/HEMCO_Config.txt)
[HEMCO_Diagn.txt](https://github.com/geoschem/geos-chem/files/13371531/HEMCO_Diagn.txt)
[HISTORY.txt](https://github.com/geoschem/geos-chem/files/13371532/HISTORY.txt)

- Besides, despite running successfully and getting results, some data cannot be opened properly with panoply, showing "**There was an error opening the dataset: The file does not seem to be valid CDM.**"  Do you know what caused this? 
![3](https://github.com/geoschem/geos-chem/assets/115625689/88c9d8a2-62df-426b-9db4-fb3fd4e3c9a8)

**Comment by yantosca** [comment]
Thanks for writing @yangbyy.  There could be a couple of things going on. 
1. Your run might have run out of memory
2. There could have been an out-of-bounds error in the array `State_Diag%AODSOAfromAqIsopWL1`.
Have you tried recompiling with `-DCMAKE_BUILD_TYPE=Debug` and rerunning?  This might provide some better error output.
