### ISSUE TITLE
Cannot revert back to older versions using git checkout

### ISSUE THREAD

**Issue by lshen2009** [geoschem/geos-chem#2041]
### Name and Institution (Required)

Name: Lu Shen
Institution: Peking University

Dear GCST,

I am trying to use an old version of GEOS-Chem. However, the source code from "git checkout tags/13.3.0" is different from the v13.3.0 code I downloaded one year ago.

For example, the number of reactions from KPP/fullchem/gckpp_Parameters.F90 is 921 if using "git checkout tags/13.3.0", which is the same with GCv14.2.2., and is 903 in the v13.3.0 code downloaded last year. Does this mean 'git checkout' doesn't revert back to older versions"?

Thanks.

**Comment by lizziel** [comment]
Hi @lshen2009, can you report the commit hash for the version you checked out one year ago as well as the new one you get when checking tags/13.3.0? This will help us compare the versions.
