### ISSUE TITLE
Are regional simulations completely like a closed box?

### ISSUE THREAD

**Issue by garvitagarwal290** [geoschem/geos-chem#2047]
### Name and Institution (Required)

Name: Garvit Agarwal
Institution: TCS, Pune, India

### Confirm you have reviewed the following documentation

- [ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

When we run a regional simulation in GCClassic by giving custom limits to latitude and longitude in geoschem_config.yml, does the simulation not take into account the meteorological effects coming from outside of the simulation region (like winds)? Similarly, does it not account for the influxes to and out-fluxes from the region of the transported gases?

**Comment by msulprizio** [comment]
The regional simulations, also referred to as nested-grid simulations, utilize boundary conditions saved out from a previous coarse-resolution global simulation. The boundary conditions are 3-hourly instantaneous species concentrations applied to a buffer zone (usually defined as 3 grid cells on each of the domain edges) around the regional domain.

For more details, please see [this description on our GEOS-Chem narrative page](https://geoschem.github.io/narrative.html#nest). The original citation for the nested-grid simulations is [X.Y. Wang et al. (2004)](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2004JD005237).

**Comment by yantosca** [comment]
I wiil close out this issue now.  @garvitagarwal290, feel free to open a new issue if you res till stuck.
