### ISSUE TITLE
How to change MERRA2 specific humidity via HEMCO

### ISSUE THREAD

**Issue by lshen2009** [geoschem/geos-chem#2048]
### Name and Institution (Required)

Name: Lu Shen
Institution: Peking University

Dear GCST, 

I am trying to change specific humidity by 1% through HEMCO. But the following code, which works well in modifying emissions, doesn't work here. Could you help check it? Thanks. 

5080 SF080  0.99 - - - xy 1 1
* SPHU     $METDIR/$YYYY/$MM/$MET.$YYYY$MM$DD.I3.$RES.$NC     QV        1980-2021/1-12/1-31/*           EFY xyz 1  * 5080  1 1

**Comment by yantosca** [comment]
Hi @lshen2009, thanks for writing. Could you post your entire HEMCO_Config.rc file here?  We'll take a look.

**Comment by lshen2009** [comment]
> Hi @lshen2009, thanks for writing. Could you post your entire HEMCO_Config.rc file here? We'll take a look.
Here it is. Please search by '5080' to see the changes. Thanks.
[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/13482184/HEMCO_Config.rc.txt)

**Comment by inku0120** [comment]
@lshen2009 did you find a way to do that??

**Comment by lshen2009** [comment]
@inku0120 It is much easier to modify the original met files.

**Comment by inku0120** [comment]
@lshen2009 Hi Ishen, thanks for the response. May I know what is the approach to change the original met files?

**Comment by yantosca** [comment]
Closing out this issue
