### ISSUE TITLE
403 Forbidden error downloading GFED4 climatology files

### ISSUE THREAD

**Issue by jennyfisher** [geoschem/geos-chem#2049]
### Name and Institution (Required)

Name: Jenny Fisher
Institution: U. Wollongong

### Confirm you have reviewed the following documentation

- [X] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [X] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [X] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [X] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

I am getting a 403 Forbidden error trying to download the 3 climatology files in http://geoschemdata.wustl.edu/ExtData/HEMCO/GFED4/v2023-03/:
- http://geoschemdata.wustl.edu/ExtData/HEMCO/GFED4/v2023-03/GFED4_climatology_2007-2021_05x0625.nc
- http://geoschemdata.wustl.edu/ExtData/HEMCO/GFED4/v2023-03/GFED4_climatology_2010-2019_05x0625.nc
- http://geoschemdata.wustl.edu/ExtData/HEMCO/GFED4/v2023-03/GFED4_monmean_05x0625_2007-2021.nc

I have no problem downloading the directories with annual data (e.g., 2019).

Having looked at other github issues with 403 forbidden, I suspect this has something to do with the permissions settings for these 3 files.

Thanks!
-Jenny

**Comment by SaptSinha** [comment]
The following three files can now be downloaded from the WashU storage cluster:

http://geoschemdata.wustl.edu/ExtData/HEMCO/GFED4/v2023-03/GFED4_climatology_2007-2021_05x0625.nc
http://geoschemdata.wustl.edu/ExtData/HEMCO/GFED4/v2023-03/GFED4_climatology_2010-2019_05x0625.nc
http://geoschemdata.wustl.edu/ExtData/HEMCO/GFED4/v2023-03/GFED4_monmean_05x0625_2007-2021.nc

Please feel free to let us know if the download error persists, or if there are any other files that have similar download errors.

**Comment by jennyfisher** [comment]
All working now, thanks!
