### ISSUE TITLE
Missing GEOS_0.5x0.625 MERRA2 data in 2023-07-02, 2023-08-01 and 2023-09-01

### ISSUE THREAD

**Issue by jjp1987** [geoschem/geos-chem#2052]
There are three file size of GEOS_0.5x0.625 MERRA2 data error:
1.  I3 file in 2023-07-02; 
2. A3dyn file in 2023-08-01; 
3. A3dyn file in 2023-09-01.
The link shows below:
http://geoschemdata.wustl.edu/ExtData/GEOS_0.5x0.625/MERRA2/2023/07/
http://geoschemdata.wustl.edu/ExtData/GEOS_0.5x0.625/MERRA2/2023/08/
http://geoschemdata.wustl.edu/ExtData/GEOS_0.5x0.625/MERRA2/2023/09/

**Comment by SaptSinha** [comment]
The following three files are now rectified:

MERRA2.20230702.I3.05x0625.nc4
MERRA2.20230801.A3dyn.05x0625.nc4
MERRA2.20230901.A3dyn.05x0625.nc4

**Comment by jjp1987** [comment]
Thanks.
