### ISSUE TITLE
Hg simulation restart file

### ISSUE THREAD

**Issue by angothelene** [geoschem/geos-chem#2055]
### Name and Institution (Required)

Name: Helene Angot 
Institution: CNRS/IGE

### Confirm you have reviewed the following documentation

- [ y] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [y ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ y] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [y ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question
@jennyfisher and I have run Hg simulations using v14.2.2 (out of the box). We obtained similar results independently, suggesting that we followed standard procedures. It seems that the provided restart file provided (from http://geoschemdata.wustl.edu/ExtData/GEOSCHEM_RESTARTS/v2021-12/) is problematic. While we could continue running for a bit to allow for a proper spin-up, it might be beneficial to correct this on the server. Are there any other Hg folks, such as @arifein or @viral211, who might have a properly spun-up restart file that we could use instead?

<img width="845" alt="image002" src="https://github.com/geoschem/geos-chem/assets/25373985/d65f9c8e-4fa7-42da-882a-c40bd9096b40">

**Comment by yantosca** [comment]
Thanks @angothelene.  Happy to add a new restart file to the data directory if you can provide us one.  

Also note: We just released 14.2..3, which now makes sure that the same restart file that is used in the run directory creation is also the one that is used in the dry-run data download.  This fixed an issue where the restart files paths could have been inconsistently defined in the two operations.

**Comment by viral211** [comment]
Thanks for pointing this out, @angothelene. Here is a [link](https://drive.google.com/file/d/1hTpsJjl9OKBxQlvyHR8zUzy-n-zbDXkE/view) to a spun-up (15 yrs or so) Hg restart file. I would still recommend at least a one-year spin-up for your runs.

**Comment by yantosca** [comment]
Thanks @viral, @angothelene.  I'll submit a PR to add the new Hg restart file into the rundir creation.

**Comment by yantosca** [comment]
Also note issue #2057 that will affect the Hg simulations in 14.3.0 and later (once Cloud-J photolysis replaces FAST-JX).  You can simply keep using FAST-JX until #2057 is resolved.

**Comment by angothelene** [comment]
@yantosca @viral211 thank you both!!

**Comment by jennyfisher** [comment]
Hi @viral211, @yantosca 

Thanks for the new restart file. I tried to run with it, but the run dies because the species names are not quite the same. In the restart all the species names are fully capitalised (e.g. SpeciesRst_HGBR) whereas it seems this version of the code now expects them without unnecessary capitalisation (e.g. SpeciesRst_HgBr).

What is the easiest way to fix this? Should I rename every species in the restart file using ncrename?

FYI @yantosca whatever fix recommended here will need to go into the public code, too.

Cheers,
Jenny

**Comment by jennyfisher** [comment]
Thanks @yantosca ! Can you post an update here when you've uploaded the new restart files to WUSTL? I think it would be good for me to use the updated restart for my runs to make sure there are no further issues with the newer file (but if it will take a long time, I will use @arifein 's restart in the meantime - thanks Ari!).

**Comment by yantosca** [comment]
Hi @jennyfisher. thanks for your patience.  We have uploaded the new restart file onto the **GEOS-Chem data (WashU)** Globus endpoint, in folder `ExtData/GEOSCHEM_RESTARTS/v2023-12`.  

There is an issue syncing that to the FTP site that we hope to resolve soon.  For now the best thing is to grab the file with Globus.

**Comment by jennyfisher** [comment]
Thanks @yantosca - unfortunately I don't have access to Globus on my system here, so I'll have to wait until it is on the FTP site. Can you let me know when it is there? Thanks! :)

**Comment by msulprizio** [comment]
Hi @jennyfisher. The restart files should now be accessible at http://geoschemdata.wustl.edu/ExtData/GEOSCHEM_RESTARTS/v2023-12/.

**Comment by yantosca** [comment]
I will close out this issue now.  Thanks.

**Comment by jennyfisher** [comment]
Just a note to say thanks, and having tested this new restart it all looks good! :)
