### ISSUE TITLE
Automatically stop while running geoschem

### ISSUE THREAD

**Issue by yutian8888** [geoschem/geos-chem#2056]
### Name and Institution (Required)

Name: Yu Tian
Institution: Rutgers University

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question
When I do GC global run from 2021.01.01 to 2023.01.01, I met this error on 20210228, I checked all the input data, they are all good. The GEOSChem.BoundaryConditions.20210228_0000z.nc4 and GEOSChem.StateMet.20210228_0000z.nc4 have formed , but GEOSChem.SpeciesConc file on that day isn't formed. 
<img width="585" alt="error" src="https://github.com/geoschem/geos-chem/assets/147092225/aaf10eec-8a7d-418c-9a12-4569baa346c8">

**Comment by yantosca** [comment]
Thanks for writing @yutian8888.  [As described here](https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/error-guide.html#netcdf-hdf-error), this type of error can occur if you read from a corrupted file.  It can also happen if you are;
- Trying to write to a file that is write-protected (or the directory doesn't exist)
- Trying to write to a file, but you have gone over your disk quota

Ask your sysadmin how to check the quota on your system.  Usually it is with a command like `quota -v`.  Also check to see that you haven't write-protected your directory or the file you are writing to.

**Comment by yutian8888** [comment]
> Thanks for writing @yutian8888. [As described here](https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/error-guide.html#netcdf-hdf-error), this type of error can occur if you read from a corrupted file. It can also happen if you are;
> 
> * Trying to write to a file that is write-protected (or the directory doesn't exist)
> * Trying to write to a file, but you have gone over your disk quota
> 
> Ask your sysadmin how to check the quota on your system. Usually it is with a command like `quota -v`. Also check to see that you haven't write-protected your directory or the file you are writing to.

Thanks you very much. I followed your suggestions and fixed this problem now. This problem was indeed caused by disk quota not enough disk space. I will close this issue.
