### ISSUE TITLE
Can I customize simulated species in fullchem?

### ISSUE THREAD

**Issue by helpyuan** [geoschem/geos-chem#2067]
### Name and Institution (Required)

Name: liumy
Institution: CAMS

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://gchp.readthedocs.io/en/latest/reference/SUPPORT.html)
- [x] [User manuals](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/GCHP/issues)

### Description of your issue or question
Hi all, I want to simulate global NO2 concentration, and it seems that NO2 can only be simulated in `fullchem` mode. However, the `fullchem` simulation seems to involve many transport species, such as ACET, ACTA, AERI, and so on. Is there a custom method that only allows GCHP to simulate processes related to NO2?

I tried searching for relevant content, but couldn't find it, so I asked this question hoping to get help.

**Comment by yantosca** [comment]
Closing out this issue.  Feel free to open a new issue if you are still stuck.
