### ISSUE TITLE
Include nitrate aerosol in Ox family

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#2070]
### Name and Institution (Required)

Name: Melissa Sulprizio
Institution: Harvard / GCST

### New GEOS-Chem feature or discussion

@djxjacob wrote:

>Haipeng (@jimmielin) brought to my attention that our current definition of Ox does not include nitrate aerosol (NO3A1).  That should be fixed in 14.3 (please add to model development priorities).  NO3A1 should be part of Ox.  That’s a clear issue now because one of the branches of NO3A1 photolysis (to NO2+OH) should conserve Ox. More pernicious is the effect of HNO3 <-> NO3A1 thermodynamics – if shifts in HNO3 <-> NO3A1 partitioning are mis-accounted as Ox sources/sinks that would overestimate Ox production and loss.

@viral211 wrote:

>I assume NO3A1 refers to the GEOS-Chem NIT species. If so, we would also need to include NITs in the Ox family.

**Comment by msulprizio** [comment]
Pull request #2017 containing updates for this issue has now been merged into the 14.3.0 development branch

**Comment by fangzhoupig** [comment]
Thanks!!
