### ISSUE TITLE
How to perform gas-particle partitioning simulation for new species

### ISSUE THREAD

**Issue by ruochongxuthu** [geoschem/geos-chem#2073]
### Name and Institution (Required)

Name: Ruochong Xu
Institution: Tsinghua University

### Description of your issue or question
We are using GEOS-Chem v14.2.3 to have SOA formation modeling. We would like to add several new semivolatile precursor species (not included in GEOS-Chem now) to simulate their gas-phase reactions, partitioning, and other fates in atmosphere. We have succeeded in added the emissions of new species in HEMCO, and I have updated and recompiled the KPP codes (through the .eqn and .kpp files) with new species and new gas-phase reactions. With the above modifications, the model runs well.

However, we now meet an issue. We would like to simulate the gas-particle partitioning of some new oxidation products to form new SOA, but found that the process can't be added through KPP. In KPP, there are no SOA species and no transformation from gas-phase products towards SOA. It seems that the partitioning of SOA is written in the source code (e.g. APM, carbon_mod.F90, aerosol_mod.F90, the code structure seems complicated), but we can not find some guidance or example to help us modify or add new codes.

We think that the ComplexSOA scheme must include the partitioning of SOA (e.g. the paper of Pye et al., 2010), but the partitioning of new species can not be easily realized in KPP or somewhere else. Are there any guidances on how to add gas-particle partitioning of new species? Any help for where we should begin (the source codes are not quite easy to understand without lots of efforts) would be appreciated a lot.

Thank you.

**Comment by yantosca** [comment]
Thanks for writing @ruochongxuthu.   I had looked at trying to port some of the SOA chemistry into KPP but I had to put it aside as it is a bit of a big job to do so (and I had to devote time to other priorities).  Also adding the SOA to KPP involves adding more species and reactions to the chemistry mechanism, which may impact performance.

This is more of a science question, so I would defer to the Aerosols Working Group.

Tagging @viral211 @beckyalexander @theloniuspunk @wporter

**Comment by theloniuspunk** [comment]
I believe that some folks have added species, perhaps Jared Brewer or folks from Shantanu Jathar's group. @yantosca do you know if they are on here to tag?

**Comment by ruochongxuthu** [comment]
@yantosca @theloniuspunk Thank you for the responses! We know it may not be easy to modify those codes, and just would like to get some help on where we should start (e.g. which F90 file), where some materials can be found, or if there are some sample codes.

**Comment by yantosca** [comment]
I am not sure if they are on here @theloniuspunk.

**Comment by theloniuspunk** [comment]
@ruochongxuthu 

Jared Brewer at University of Minnesota has likely done this kind of thing: https://swac.umn.edu/people/jared-brewer brewe222@umn.edu
Kelsey Bilsback has some experience as well: https://www.psehealthyenergy.org/about/staff/kelsey/ kelsey.bilsback@psehealthyenergy.org

I think you can email them both together as they know each other.

**Comment by ruochongxuthu** [comment]
@yantosca @theloniuspunk Thank you so much!

**Comment by yantosca** [comment]
Will close out this issue now.  Thanks @ruochongxuthu @theloniuspunk

**Comment by wangdc98** [comment]
I am sorry to bother you. I am currently planning to add several new semi-volatile substances. I have successfully modified and run them through KPP, but now I need to incorporate gas-particle partitioning. I am quite confused and unsure how to modify the APM module. May I ask if you have already solved this issue? I would be extremely grateful if you could provide any solutions or insights.
