### ISSUE TITLE
HEMCO ERROR: ExtData/HEMCO/CH4/v2023-07/Gridded_GHGI_v2/Express_Extension_Gridded_GHG  I_Methane_v2_2019.nc - Cannot get field GHGI_EE_GAS_DISTRIBUTION_T. 

### ISSUE THREAD

**Issue by XunZhangNJU** [geoschem/geos-chem#2074]
### Name and Institution (Required)

Name: XunZhang
Institution: Nanjing University

### Description of your issue or question
I am running the merra2_4x5_taggCH4 simulation of the latest GEOS-Chem Classic model (Version:14.2.2) and encountered the following error:

HEMCO ERROR: Cannot find file for current simulation time: /home/sdc1/data/GCC
 lassic/ExtData/HEMCO/CH4/v2023-07/Gridded_GHGI_v2/Express_Extension_Gridded_GHG
 I_Methane_v2_2019.nc - Cannot get field GHGI_EE_GAS_DISTRIBUTION_T. Please chec
 k file name and time (incl. time range flag) in the config. file
HEMCO ERROR: Error encountered in routine HCOIO_Read!

I checked the official CH4 initial data (http://geoschemdata.wustl.edu/ExtData/HEMCO/CH4/) and found that version v2023-07 is not available. Where can I download this data? or how should I set up the HEMCO_Config.rc file to avoid this problem?

**Comment by msulprizio** [comment]
Hi @XunZhangNJU. It appears the WashU ftp site is not up to date. Until that is resolved, you can find the latest CH4 data on the Harvard ftp site: https://ftp.as.harvard.edu/gcgrid/data/ExtData/HEMCO/CH4/.
