### ISSUE TITLE
Ask about ways to increase the speed of geos-chem runs

### ISSUE THREAD

**Issue by WangQihao666** [geoschem/geos-chem#2075]
### Name and Institution (Required)

Name: Qihao Wang
Institution:Beijing Normal University

### Confirm you have reviewed the following documentation

- [ Y ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ Y ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ Y ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ Y ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

I'm not experiencing an error report, I'm just wondering if there's any way to go about increasing the speed of the run, I've been running it all day and night only running June 1 - June 20, it's so slow. If I want to run a year's worth of simulations, it's just too long.
Thank  you very much !

[relevant configuration and log files.zip](https://github.com/geoschem/geos-chem/files/13694517/relevant.configuration.and.log.files.zip)
![0](https://github.com/geoschem/geos-chem/assets/65826336/1e8afb43-0cf3-4200-b2c5-bb359c51de2c)

**Comment by yantosca** [comment]
Thanks for writing @WangQihao666.  We have some [tips on how to speed up slow simulations](https://geos-chem.readthedocs.io/en/stable/gcclassic-user-guide/run-speedup.html).

Also make sure that you have set the `$OMP_NUM_THREADS` and `$OMP_STACKSIZE` variables [as described in our documentation](https://geos-chem.readthedocs.io/en/stable/getting-started/login-env-parallel.html).

What type of machine are you using?  If you are using a Linux PC then this might not have enough cores and/or memory to run GEOS-Chem efficiently.  The machine might be swapping out memory to the disk swap file, which is inefficient.  If you can, try to run a high-resolution GEOS-Chem simulation on computational cluster, where there are usually more resources.

**Comment by yantosca** [comment]
If you do not have access to a cluster, you can also try to run GEOS-Chem on the Amazon EC2 cloud as described here: https://geos-chem-cloud.readthedocs.io.

**Comment by WangQihao666** [comment]
Thank you for your response. I am running the simulation on a server, but the speed is still very slow.

**Comment by yantosca** [comment]
@WangQihao666 What is the chipset of your server?  Is it AMD?  And are you compiling with gfortran or ifort?  In our experience, ifort does not optimize well on AMD CPUs.

**Comment by yantosca** [comment]
Closing this issue out
