### ISSUE TITLE
Why the species CH3I in extenson101(seaflux) was commented out?

### ISSUE THREAD

**Issue by Fearlessssssss** [geoschem/geos-chem#2076]
### Name and Institution (Required)

Name:Tyler
Institution:Tsinghua University

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Hi, GCST. I wonder why the species CH3I in extenson101(seaflux) was commented out? Is it ok to calcute the flux of Ch3I online based on the environment conditions？ I simply removed the comments and added CH3I to the seaflux in the EXTENSION SWITCHES, also changed the ExtNr in HEMCO_Diagn.rc of CH3I to 101(Similar to other seaflux species). But the flux output for CH3I is 0. Why is that? Thanks!

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.
[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/13704864/HEMCO_Config.txt)
[HEMCO_Diagn.txt](https://github.com/geoschem/geos-chem/files/13704865/HEMCO_Diagn.txt)
[geoschem_config.txt](https://github.com/geoschem/geos-chem/files/13704866/geoschem_config.txt)

**Comment by yantosca** [comment]
Thanks for writing @Fearlessssssss.  I am not sure why the CH3I is commented out, but it may be due to the fact that we use more recent emissions, see:
```
#==============================================================================
# --- Very-short-lived (VSL) iodocarbon emissions (cf. Carlos Ordonez) ---
#==============================================================================
(((ORDONEZ_IODOCARB
0 ORDONEZ_CH3I   $ROOT/IODINE/v2020-02/CH3I_monthly_emissions_Ordonez_2012_COARDS.nc   CH3I   2000/1-12/1/0 C xy kg/m2/s CH3I   - 1 1
... etc ...
)))ORDONEZ_IODOCARB
```

**Comment by Fearlessssssss** [comment]
I know this base emission. But I wonder is it ok to calcute the flux of Ch3I online based on the environment conditions？

**Comment by yantosca** [comment]
Thanks @Fearlessssssss for the update.  Try editing the entry in the `HEMCO_Diagn.rc` from:

```console
EmisCH3I_Ocean     CH3I   101     1    -1   2   kg/m2/s  CH3I_emission_flux_from_ocean
```
to
```console
EmisCH3I_Ocean     CH3I   101     -1    -1   2   kg/m2/s  CH3I_emission_flux_from_ocean
```
and see if that gets the output to archive.  You can run a very short simulation to test this.
