### ISSUE TITLE
Nested simulation_Program_can't creat NetCDF

### ISSUE THREAD

**Issue by yangbyy** [geoschem/geos-chem#2080]
### Name and Institution (Required)

Name: Shuangqin Yang
Institution: Tianjin Normal University, China

### Confirm you have reviewed the following documentation

- [ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.
Hi, I am running an Asian nested simulation (full chemistry, MERRA-2, horizontal resolution of 0.5 x 0.625, 47 layers) using the GEOS-Chem v14.0.0 model.

When I run it with the command "sbatch geoschem.sh", I get the error message "In Nccr_Wr, cannot create:  OutputDir/GEOSChem.AerosolMass.20161101_0000z.nc4". Actually, I tried recompiling with _-DCMAKE_BUILD_TYPE=Debug_ and rerunning, 
![8fc0150d7d6abace9d01cae56a99a9c](https://github.com/geoschem/geos-chem/assets/115625689/6c9bce85-388e-46a5-9602-d49d50489a99)

 then I got "longjmp causes uninitialized stack frame ***: ./gcclassic terminated". 
![72be14bddd42c599d451f4ccc2becd5](https://github.com/geoschem/geos-chem/assets/115625689/b4374562-3ef9-460a-93f9-1a7e9e28a89f)

I do not know what's this mean, could you please do me a favor? Thank you so so so much!!!
[GC.txt](https://github.com/geoschem/geos-chem/files/13711410/GC.txt)

**Comment by yantosca** [comment]
Thanks for writing @yangbyy.  I'm wondering if this is a memory error.  It seems like the code is stopping in RRTMG, but maybe you are hitting a memory limit.  Try asking for more memory if possible and then see if you get past this error.

**Comment by yangbyy** [comment]
I tried increasing the memory (from 128G to 256G) and it still reports errors. It runs fine on my local computer, I don't know why it's reporting errors when running on a server. 
[GC.log](https://github.com/geoschem/geos-chem/files/13726861/GC.log)

![906731e83a2d6e08c729c263b66192e](https://github.com/geoschem/geos-chem/assets/115625689/cee3d483-5094-48fd-aadb-00daa88dd466)

Here's the code I'm running to use, is the error reporting something to do with that?
[geoschem_sh.txt](https://github.com/geoschem/geos-chem/files/13726856/geoschem_sh.txt)

**Comment by yantosca** [comment]
Hi @yangbyy, I thiink I might see the issue.  You are loading:
```console
module load anaconda/3-Python-3.8.3-phonopy-phono3py
module load netcdf/4.7.2-intel20 mpi/intel/20.0.4 cmake/3.27.5
```
You may have a conflict in the conda environment and the netCDF that is being loaded.  Try removing the `module load anaconda...` command and see if that resolves the issue.

**Comment by yangbyy** [comment]
@yantosca  Thank you! I tried what you said and now it runs fine. You have helped me!
