### ISSUE TITLE
What is the location of the boundary condition files that are read for nested-grid simulations?

### ISSUE THREAD

**Issue by garvitagarwal290** [geoschem/geos-chem#2081]
### Name and Institution (Required)

Name: Garvit Agarwal
Institution: TCS, India

### Confirm you have reviewed the following documentation

- [ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

Hi, I tried looking for this info everywhere, but I couldnt find where the boundary condition files that are read for nested-grid simulations are located. I ran a 0.25x0.3125 nested-grid simulation over Asia and the simulation log mentions reading from a boundary condition file but I can't see which file(s) it is. Please let me know, thank you.

**Comment by yantosca** [comment]
Thanks for writing @garvitagarwal290.

The `HEMCO_Config.rc` file that ships out-of-the-box points to sample boundary condition files that are only used for testing GEOS-Chem.  This is in the section of the HEMCO_Config.rc file that looks like this:

```console
(((GC_BCs
* BC_  $ROOT/SAMPLE_BCs/v2021-09/fullchem/GEOSChem.BoundaryConditions.$YYYY$MM$DD_$HH$MNz.nc4 SpeciesBC_?ADV?  1980-2021/1-12/1-31/* CYS xyz 1 * - 1 1
)))GC_BCs
```
You will have to edit this section to point to boundary conditions that you generate with the same version of the model, but at 4x5 resolution.  Just change the path to the `GEOSChem.BoundaryConditions.$YYYY$MM$DD_$HH$MNz.nc4` files, which are via the History diagnostic collection: "BoundaryConditions".

**Comment by garvitagarwal290** [comment]
Thank you. I had another question. Suppose I run a regional simulation without mentioning any boundary condition file in HEMCO_config.rc. Then the simulation inside the region will run correctly right? (except the inaccuracies due to not having boundary conditions)

**Comment by yantosca** [comment]
@garvitagarwal290: If you do not specify any boundary conditions in the HEMCO_Config.rc file, then it will use the ones from the `SAMPLE_BCs` folder shown above.  This will be incorrect for your simulation as it would be repeating the same day of boundary conditions over and over.

You need the boundary conditions to specify concentrations at the edge of the nested domain for transport.

**Comment by garvitagarwal290** [comment]
So I am able to run simulations where the latitude and longitude ranges are regional, and I turn off the 'nested_grid_simulation' setting. This runs without any problem even though I dont have the SAMPLE_BCs folder or the GC_BCs extension mentioned in my HEMCO_Config.rc. In this case, is GEOS-Chem using 0 boundary conditions?

**Comment by yantosca** [comment]
Also, I just added some documentation to the "latest" ReadTheDocs documentation for nested-grid simulations.  We had this on the GEOS-Chem wiki but some of that information is now obsolete.  See:
https://geos-chem.readthedocs.io/en/latest/supplemental-guides/nested-grid-guide.html

**Comment by garvitagarwal290** [comment]
okay great. Thank you.
