### ISSUE TITLE
[FEATURE REQUEST] Pass rundir name not full path when determining executable name in integration tests

### ISSUE THREAD

**Issue by lizziel** [geoschem/geos-chem#2083]
### Name and Institution (Required)

Name: Lizzie Lundgren
Institution: Harvard University

### New GEOS-Chem feature or discussion

During testing I noticed that RRTMG executables were being used within all integration test run directories. I traced the problem to having "rrtmg" in my test directory path. The absolute path is passed to integration function [exe_name](https://github.com/geoschem/geos-chem/blob/main/test/shared/commonFunctionsForTests.sh#L375) within the GCClassic and GCHP `integrationTestExecute.sh` scripts (see [here](https://github.com/geoschem/geos-chem/blob/3cd802eb4a9b7a226254fc3938778c8db8c07cf2/test/integration/GCClassic/integrationTestExecute.sh#L172-L173) and [here](https://github.com/geoschem/geos-chem/blob/3cd802eb4a9b7a226254fc3938778c8db8c07cf2/test/integration/GCHP/integrationTestExecute.sh#L176-L177)). Changing this to use run directory name rather than full path will make the integration tester more robust.

**Comment by yantosca** [comment]
@lizziel, feel free to close this issue.  It's been merged into the no-diff-to-benchmark branch.
