### ISSUE TITLE
Allocation error while running GEOS-Chem 14.2.3

### ISSUE THREAD

**Issue by mulgamulgi33** [geoschem/geos-chem#2085]
Name: Pritanjali Shende
Institution: Indian Institute of technology Hyderabad

### Confirm you have reviewed the following documentation

- [] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)

- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

I hereby confirm that I have gone through the above links.

### Description of your issue or question

I have been using GEOS-Chem V12.1.1 for the past 4 year.

Now I have planned to shift from GC-v12.1.1 to GCClassic-v14.2.3. but while running make -j command I have achieved the following error (as attached). I an running GEOS-Chem on ubuntu16.04 with libraries netcdf-4.5, cmake-3.5 and gcc-7. 

I would really be happy if you could help me in this regard.

Thanks and best regards,
Pritanjali Shende

![GC_error](https://github.com/geoschem/geos-chem/assets/27491945/e4735ee8-d198-452a-957b-73f1044b68e4)
[GC.log](https://github.com/geoschem/geos-chem/files/13735197/GC.log)

**Comment by yantosca** [comment]
Thanks for writing @mulgamulgi33.  I am wondering if the gcc 7 compiler is too old and cannot handle this type of construct.  Do you have access to a newer version of gcc?  If you can update a more recent version then this issue might resolve.

**Comment by yantosca** [comment]
Closing this issue
