### ISSUE TITLE
Which meteorological field does GEOS-Chem use for (dry) convection?

### ISSUE THREAD

**Issue by garvitagarwal290** [geoschem/geos-chem#2087]
### Name and Institution (Required)

Name: Garvit Agarwal
Institution: TCS, India

### Confirm you have reviewed the following documentation

- [ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

In the documentation, it is mentioned that the 'convection' operation in geoschem_config.ym is for cloud convection. I ran a simulation with the 'convection' operation turned off and noticed that the gas was still transported in the vertical direction. Assuming that this was due to 'dry convection', which meteorological field contains information for this vertical transport? (just like the wind fields are for horizontal transport). Instead, if this is not because of dry convection, then how is the vertical transport happening?

**Comment by yantosca** [comment]
Thanks @garvitagarwal290 for writing.  The "dry" convection would be the PBL mixing.  It would use the PBL height met fields (which I think is PBLH).

**Comment by garvitagarwal290** [comment]
I just tried a simulation where I turned off PBL mixing also, but I see the same vertical transport happening. Is this strange or could there be some other mechanism in the code?

**Comment by yantosca** [comment]
@garvitagarwal290 There is probably also a small (but nonzero) vertical transport component in transport.

**Comment by garvitagarwal290** [comment]
Can you please tell me where GEOS-Chem gets the information for that vertical transport? Or does it calculate the vertical transport all on its own internally?

**Comment by yantosca** [comment]
The vertical transport term is computed internally.  See: https://github.com/geoschem/geos-chem/blob/main/GeosCore/tpcore_fvdas_mod.F90

**Comment by garvitagarwal290** [comment]
okay thank you for answering my questions so quickly!
