### ISSUE TITLE
Feature request: Update documentation for GEOS-Chem Classic nested-grid simulations

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#2089]
### Name and Institution (Required)

Name: Bob Yantosca
Institution: Harvard + GCST

### Confirm you have reviewed the following documentation

- [x] [Contributing guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/CONTRIBUTING.html)

### New GEOS-Chem feature or discussion
I've opened this issue as a reminder to update the ReadTheDocs documentation with the latest information for running a nested-grid simulation.

**Comment by yantosca** [comment]
I've added a [Run nested-grid simulations](https://geos-chem.readthedocs.io/en/latest/supplemental-guides/nested-grid-guide.html) to the "latest" documentation.

@msulprizio @lizziel: feel free to edit further.

**Comment by msulprizio** [comment]
Thanks @yantosca. The nested grid docs looks great! We can add to it as users have additional questions. I will close out this issue.
