### ISSUE TITLE
[BUG/ISSUE] Segmentation fault in GEOS-Chem 12.3.2 nested simulation

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#209]
I am submitting this issue on behalf of Tian Feng (fengtian@nbu.edu.cn):

>I am running the geos-chem model (v12.32) with a nest grid which is merra2_0.5x0.625_as. The boundary condition is provided by a 4x5 simulation also using merra2 meteorology. The problem is that the job was successfully submitted, but quitted with the following error log:

```
forrtl: severe (408): fort: (2): Subscript #2 of the array Q has value 132 which is greater than the upper bound of 131
Image              PC                Routine            Line        Source
libifcoremt.so.5   00002AFA0D86D4C9  for_emit_diagnost     Unknown  Unknown
geos.mp            0000000000D4EBE6  tpcore_window_mod        2185  tpcore_window_mod.F90
geos.mp            0000000000D3F0F3  tpcore_window_mod        1653  tpcore_window_mod.F90
geos.mp            0000000000D31CDE  tpcore_window_mod        1262  tpcore_window_mod.F90
libiomp5.so        00002AFA0F64C103  __kmp_invoke_micr     Unknown  Unknown
libiomp5.so        00002AFA0F60D94B  Unknown               Unknown  Unknown
libiomp5.so        00002AFA0F60CE74  Unknown               Unknown  Unknown
libiomp5.so        00002AFA0F64C571  Unknown               Unknown  Unknown
libpthread-2.17.s  00002AFA0FBC0E25  Unknown               Unknown  Unknown
libc-2.17.so       00002AFA0FECD34D  clone                 Unknown  Unknown
```

>It runs well for the year of 2013, but fails for 2014.
>The array Q in the tpcore_window_mod.F90 is listed below:
```F90
 subroutine ytp(im, jm, fy, q, c, yfx, ng, mg, jord, iv, jfirst, jlast)

 implicit none

! !INPUT PARAMETERS:
 integer im, jm                      !  Dimensions
 integer jfirst, jlast               !  Latitude strip
 integer ng                          !  Max. NS dependencies
 integer mg                          ! 
 integer jord                        !  order of subgrid dist
 integer iv                          !  Scalar=0, Vector=1
 real q(im,jfirst-ng:jlast+ng)       !  advected scalar N*jord S*jord
 real c(im,jfirst:jlast+mg)           !  Courant   N (like FY)
 real yfx(im,jfirst:jlast+mg)         !  Backgrond mass flux

! !OUTPUT PARAMETERS:
 real fy(im,jfirst:jlast+mg)          !  Flux      N (see tp2c)

! !LOCAL VARIABLES:
 integer i, j, jt
 integer js2g0, jn1g1

! work arrays (should pass in eventually for performance enhancement):
 real dm(im,jfirst-ng:jlast+ng)

!     real ar(im,jfirst-1:jlast+1)  ! AR needs to be ghosted on NS
!     real al(im,jfirst-1:jlast+2)  ! AL needs to be ghosted on N2S
!     real a6(im,jfirst-1:jlast+1)  ! A6 needs to be ghosted on NS


   js2g0  = max(2,jfirst)       ! No ghosting
   jn1g1  = min(jm,jlast+1)     ! Ghost N*1

   if(jord == 1) then
        do j=js2g0,jn1g1
          do i=1,im
            jt = float(j) - c(i,j)
            fy(i,j) = q(i,jt)
          enddo
        enddo
   else
```

>Could you please help to figure out what happened and how to handle this issue?
>Thank you very much!

**Comment by yantosca** [comment]
Thanks for writing.  We would need to see more information before we can make an assessment.  Please see [this checklist on our Submitting GEOS-Chem Support Requests page](http://wiki.geos-chem.org/Submitting_GEOS-Chem_support_requests#How_can_I_make_a_support_request.3F).  In particular, we would need to see the input.geos and log files from the simulation.  Also, you didn't specify which compiler you used to compile GEOS-Chem with.

Also, have you checked to make sure that you have the proper meteorology and boundary conditions for the year 2014?  I am wondering if an e.g. corrupted file might be causing this issue.

We also have more information about Segmentation Fault errors at our [Guide to GEOS-Chem error messages](http://wiki.geos-chem.org/Guide_to_GEOS-Chem_error_messages).

**Comment by feng01** [comment]
Thank you Bob!
I use the intel compiler version 19.0.1.144. The input.geos and log files are attached.
[Archive.zip](https://github.com/geoschem/geos-chem/files/4143468/Archive.zip)
The meteorology and boundary conditions for the year 2014 should be okay. I have checked and re-downloaded the merra2 files at the corrupted time. The 4x5 simulation for 2014 runs well with no error.

**Comment by yantosca** [comment]
Have you checked that the BC file is not corrupted?  It seems like it gets to the 18:00 of the last day and then it dies.  That is probably when a boundary condition is getting read in.

**Comment by feng01** [comment]
The 4x5 BC simulation runs well with no corruption. 
I have added some code in the tpcore_window_mod.F90 file to avoid the error (see below), but I am not sure whether the changes are feasible or not. With these changes, the model runs well.
`    call ytp(im,jm,fy, adx,cry,yfx,ng,mg,jord,0,jfirst,jlast)

      do j=js2g0,jn2g0
        do i=1,im
           jp = j-va(i,j)
           if(jp .gt. jn2g0) then       ! Tian, Line 1658 in v12.3.2
               jp = jp - 1
           endif
           wk1(i) = q(i,j) +0.5*va(i,j)*(q(i,jp)-q(i,jp+1))
        enddo

        call xtp(im,  ffsl(j), fx(1,j), wk1,                  &
                 crx(1,j), iord, xfx(1,j), cosp(j), id,       &
                 dm, qtmp, al, ar, a6)
      enddo
 end subroutine tp2d`

`   if(jord == 1) then
        do j=js2g0,jn1g1
          do i=1,im
            jt = float(j) - c(i,j)
            if(jt .gt. jn1g1) then      ! Tian, Line 2188 in v12.3.2
                jt = jt - 1
            endif
            fy(i,j) = q(i,jt)
          enddo
        enddo
   else`

**Comment by yantosca** [comment]
I am going to close out this issue for now.  If you still have problems, feel free to reopen it.
