### ISSUE TITLE
editing group webpage

### ISSUE THREAD

**Issue by lmickley** [geoschem/geos-chem#2091]
### Name and Institution (Required)

Name: Loretta
Institution: Harvard

### Confirm you have reviewed the following documentation

- [ x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question
Happy new year Bob, Melissa, and Lizzie!
Is there a page for how to edit the group webpages? If yes, could you please point me to it?
Thank you.
Loretta

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

**Comment by msulprizio** [comment]
Editing the Harvard ACMG group website can be done through OpenScholar. See my email for details.
