### ISSUE TITLE
Corrupted offline biovoc, soilnox, seasalt files for 1/20/2022 at geoschemdata.wustl.edu

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#2093]
### Name and Institution (Required)

Name: Bob Yantosca
Institution: Harvard + GCST

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

GEOS-Chem user @yutian8888 reported a potential wet deposition error in #2077.  Upon further investigation, it was discovered that the error was instead caused by corrupted data files that had been downloaded from the WashU data server https://geoschemdata.wustl.edu.  I re-downloaded the files in question and have confirmed that they are corrupted on the server.

The files in question are:

- http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_BIOVOC/v2021-12/0.25x0.3125/2022/01/biovoc_025.20220120.nc

- http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_SEASALT/v2019-01/0.25x0.3125/2022/01/seasalt_025.20220120.nc

- http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_DUST/v2021-08/0.25x0.3125/2022/01/dust_emissions_025.20220120.nc

I haven't checked to see if any other files (e.g the 0.5 x 0.625 files) were corrupted as well.  Can someone at WashU look into this? @yidant @SaptSinha

**Comment by SaptSinha** [comment]
The files are now fixed.

**Comment by yantosca** [comment]
Thanks @SaptSinha!   @yutian8888, please grab the new files and see if that fixes the problem in your simulation.

**Comment by yutian8888** [comment]
> Thanks @SaptSinha! @yutian8888, please grab the new files and see if that fixes the problem in your simulation.

Dear @yantosca and @SaptSinha , I replaced with the fixed files and the model now run successfully. Thank you very much for your always help!

**Comment by yantosca** [comment]
Thanks @yutian8888.  I'll close this issue now.

**Comment by eamarais** [comment]
@yantosca, I'm experiencing an issue with offline soil NOx on 1 Jan 2022. It looks like it wasn't reprocessed. My workaround is to delete soilnox_025.20220120.nc and update "EFY" to "CYS" to read the 19 Jan 2022 soil NOx emissions for 20 Jan 2022 instead. Not sure if this is affecting other users?
