### ISSUE TITLE
Modify the initial and boundary conditions of meteorological fields of MERRA-2 input for sensitivity simulations 

### ISSUE THREAD

**Issue by inku0120** [geoschem/geos-chem#2098]
Ankit
Institution: IITM

I need to modify the input MERRA-2 meteorological fields (_few variables; not all_) at each vertical level based on the observations at the domain; since MERRA-2 meteorological fields have few deviations from the observations. Then would run GEOS-Chem with the modified MERRA-2 meteorological fields and analyse the differences.
 
I want to understand what should be the approach to change the input MERRA-2 meteorological fields. Is there a way already given in the model?

Thank you.

**Comment by yantosca** [comment]
Thanks for writing @inku0120.  I'm not sure what types of modifcations you mean.  However, it should be possible to add scale factors to the `HEMCO_Config.rc` file for the meteorology entries (located in the `HEMCO_Config.rc.gmao_metfields` file (both in the run directory).

Please see the [Scale Factors](https://hemco.readthedocs.io/en/stable/hco-ref-guide/hemco-config.html#scale-factors) section in the https://hemco.readthedocs.io documentation.

**Comment by inku0120** [comment]
Dear @yantosca , thanks for a quick response. 
I would elaborate more for a clear understanding since 'scale factor' will not work in my case. Scale factor is used to change the emissions of any entity whereas I am trying to change the meteorological input.
i.e. few meteorological variables of MERRA-2 input have biases (in the case of my study domain) meaning their values are very far from the actual observations. e.g. temperature variable has a bias of +/- 2 degrees. So, I want to include these biases in the meteorological input to make it closer to the observation and then do a sensitivity simulation to see how these biases in meteorological inputs affect the chemistry. 
I hope it gives more clarity to the issue.
I seek your guidance for an appropriate approach to this problem. So, please help me out.

**Comment by yantosca** [comment]
Thanks @inku0120.  Your question is more of a science question, and this is outside of the expertise of the GCST.

It sounds like you would need to do some kind of inversion or data assimilation step to correct biases.  I am tagging @drewpendergrass and @christophkeller who may be able to point you in the right direction.

**Comment by drewpendergrass** [comment]
Hi @inku0120 -- if you want to do a proper data assimilation run (e.g. 3DVar), then GEOS-Chem is not the appropriate tool to correct MERRA2 data. A meteorological model such as WRF would be more appropriate. However, if you just would like to manually adjust MERRA2 data (overwriting some data) and then run GEOS-Chem, this would just be a matter of editing the MERRA2 input files before runtime begins. This would produce a second set of MERRA2 files reflecting your adjustment and the sensitivity run can be performed that way -- a general NetCDF editing tool like xarray in Python would be a nice method to do this algorithmically. Forgive me if I am telling you something you already know!

Are you asking if GEOS-Chem can on-the-fly modify meteorology files as they are read in, avoiding the need to save out another set of MERRA2 files? @yantosca would know more than me about this, but I don't think that is supported in the GEOS-Chem at the moment -- HEMCO scalefactors would be a bit too blunt of a tool in your case.

**Comment by yantosca** [comment]
@drewpendergrass @inku0120: GEOS-Chem does not modify the input meteorology on-the-fly when reading offline fields.

**Comment by inku0120** [comment]
Dear @drewpendergrass and @yantosca ,  Many thanks for the clarification. I was already working on manually editing the MERRA-2 input files but thought of asking the GEOS-Chem community for any alternatives that's why I posted my query. And you gave a lot of clarity.

Regards

**Comment by yantosca** [comment]
Thanks much @inku0120.  I'll go ahead and close out this issue.
