### ISSUE TITLE
[QUESTION] Number density of aerosol in diagnostic output

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#210]
I am submitting this issue on behalf of Xinyi Dong (xdong1@vols.utk.edu):

> I have a quick question regarding GEOS-Chem output: is the number density of aerosol (e.g., black carbon, sulfate, etc) in each bin available in any of the diagnostic files? The aerosol scheme does configure bins for aerosol (e.g., TOMS-12, TOMS-30, etc),  I checked the list of diagnostic files but couldn't find the bin-related variable.

**Comment by yantosca** [comment]
Thanks for writing.  I believe the TOMAS number density fields are denoted by ND* and are advected.  In that case, they should be available in several netCDF collections that use advected species  (?ADV?).

Note that the GCST is not the primary developer of the TOMAS algorithm.  We would recommend that you contact the [Aerosols Working Group](http://wiki.geos-chem.org/Aerosols_Working_Group) for more information and guidance.

**Comment by yantosca** [comment]
I will close this issue out for now.  Feel free to reopen.

**Comment by dxy8413** [comment]
thanks a lot for the response!
