### ISSUE TITLE
Agricultural NOx double counting

### ISSUE THREAD

**Issue by ayhwong** [geoschem/geos-chem#2105]
### Name and Institution (Required)

Name: Anthony Wong
Institution: MIT

### Description of your issue or question

Grid-independent soil NOx seems to include agricultural soil NOx through land cover/fertilizer application. But agricultural NOx (which is from the same source) from anthropogenic emission inventories are not turned off by default. There can be double counting potentially.

**Comment by eamarais** [comment]
Hi @yantosca and @ayhwong, it might be best to tag the person who developed the grid-independent soil NOx emissions. Is this Hongjian Weng from Jintai's group? Not sure if they have a GitHub account.

**Comment by yantosca** [comment]
Closing out this issue
