### ISSUE TITLE
Are there estimates of how long a simulation takes for a given resolution, number of compute cores etc?

### ISSUE THREAD

**Issue by garvitagarwal290** [geoschem/geos-chem#2108]
### Name and Institution (Required)

Name: Garvit Agarwal
Institution: TCS, Pune, India

### Confirm you have reviewed the following documentation

- [ ] [Contributing guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/CONTRIBUTING.html)

### New GEOS-Chem feature or discussion

Are there estimates of how long a GCClassic simulation takes for a given grid resolution, number of compute cores, RAM, processor and other simulation parameters? I want to run a high-resolution year-long simulation but I want to get an idea of how long the simulation might take before having to download the meteorological data etc.

Please provide a clear and concise overview of the discussion topic or new feature requested.

**Comment by yantosca** [comment]
Thanks for writing @garvitagarwal290.  We don't have published estimates of run times for GEOS-Chem simulations, as this would vary significantly depending on the platform, OS, chipset/clock speed, amount of memory (and whether or memory is moved to/from a swap file, etc.).

However you can look at the timings of our benchmark simulations as a guide.  On a computational cluster with 48 cores, a 1-month fullchem benchmark simulation takes around 3-3.5 hours.  On the AWS cloud, 1-month benchmarks take about 6.5 hours (due to having to use a container and the EBS file system, which is slower than e.g. Infiniband.  Also, the benchmark simulations archive a lot of diagnostic output, which incurs extra time to archive and write to disk.  You can speed up a simulation by not archiving diagnostics that you don't need.

**Comment by lizziel** [comment]
Another tip for looking at the benchmark timing is to keep in mind it is run at 4x5 grid resolution. If you want to run at higher resolution global you can use 2x2.5 which would be about 4 times longer than 4x5, all else being the same. Also, since GC-Classic can only run on a single compute node you will be limited in terms of speed up with more cores. If you have compute resources available and want to run fast at high resolution we recommend using GCHP.

**Comment by garvitagarwal290** [comment]
okay thank you. I had a couple follow-up questions:

1) Can I use the thumb rule of the run-time increasing by a factor of 4, every time the lat-long grid gets finer by a factor of 2, if all else is the same (as @lizziel mentioned)?
2) Will the run-time always scale linearly with the number of cores used? 

Related to the second question, I tried running the same simulation using 1 core and 8 cores (by setting the variable OMP_NUM_THREADS appropriately), but the run-time was approximately the same (my machine has total 8 cores). I verified that 8 cores were being used in the latter case using the 'top' command. The memory usage for a core was about 12%. So what could be the reason for this?

**Comment by lizziel** [comment]
> I tried running the same simulation using 1 core and 8 cores (by setting the variable OMP_NUM_THREADS appropriately), but the run-time was approximately the same (my machine has total 8 cores).

There is definitely something wrong if your 1-core job and 8-core job took about the same amount of time to run. Could you check if OMP is turned on when you build? It would show up during the configure step when you run cmake.

**Comment by garvitagarwal290** [comment]
@lizziel I have attached a screenshot of when I build using cmake; it seems OMP is turned on. I checked the run times when I use 1 core vs 8 cores for the same simulation but they still take the same time. My laptop is more than 4 years old, could it just be due to this fact?

![Screenshot from 2024-01-24 15-31-16](https://github.com/geoschem/geos-chem/assets/66527730/9bce4935-d4cf-40b4-8a46-80bbe2f5a8e3)

**Comment by lizziel** [comment]
Hi @garvitagarwal290, you can turn on GEOS-Chem timers in file geoschem_config.yml. I suggest doing that and then running both 1 core and 8 core jobs. The timing breakdown for the entire model can then be compared by looking at the values at the end of the log files. This might shed light on what is happening.

**Comment by garvitagarwal290** [comment]
@lizziel I tried that and got the below result.

When I used 8 cores:

===============================================================================
G E O S - C H E M   T I M E R S
 
  Timer name                       DD-hh:mm:ss.SSS     Total Seconds
-------------------------------------------------------------------------------
  GEOS-Chem                     :  00-00:04:40.539           280.539
  Initialization                :  00-00:00:03.345             3.346
  HEMCO                         :  00-00:01:24.745            84.745
  All chemistry                 :  00-00:00:01.322             1.322
  => FlexChem                   :  >>>>> THE TIMER DID NOT RUN <<<<<
    -> FlexChem loop            :  >>>>> THE TIMER DID NOT RUN <<<<<
    -> Init KPP                 :  >>>>> THE TIMER DID NOT RUN <<<<<
    -> Het chem rates           :  >>>>> THE TIMER DID NOT RUN <<<<<
    -> Photolysis rates         :  >>>>> THE TIMER DID NOT RUN <<<<<
    -> KPP                      :  >>>>> THE TIMER DID NOT RUN <<<<<
       RCONST                   :  >>>>> THE TIMER DID NOT RUN <<<<<
       Integrate 1              :  >>>>> THE TIMER DID NOT RUN <<<<<
       Integrate 2              :  >>>>> THE TIMER DID NOT RUN <<<<<
    -> Prod/loss diags          :  >>>>> THE TIMER DID NOT RUN <<<<<
    -> OH reactivity diag       :  >>>>> THE TIMER DID NOT RUN <<<<<
  => FAST-JX photolysis         :  >>>>> THE TIMER DID NOT RUN <<<<<
  => Aerosol chem               :  >>>>> THE TIMER DID NOT RUN <<<<<
  => Linearized chem            :  >>>>> THE TIMER DID NOT RUN <<<<<
  Transport                     :  00-00:02:26.703           146.703
  Convection                    :  >>>>> THE TIMER DID NOT RUN <<<<<
  Boundary layer mixing         :  00-00:00:12.064            12.064
  Dry deposition                :  >>>>> THE TIMER DID NOT RUN <<<<<
  Wet deposition                :  >>>>> THE TIMER DID NOT RUN <<<<<
  All diagnostics               :  00-00:00:04.423             4.424
  => HEMCO diagnostics          :  00-00:00:00.017             0.018
  => ObsPack diagnostics        :  >>>>> THE TIMER DID NOT RUN <<<<<
  => History (netCDF diags)     :  00-00:00:04.403             4.403
  Unit conversions              :  00-00:00:04.275             4.275
  Input                         :  00-00:01:12.688            72.688
  Output                        :  00-00:00:04.425             4.426
  Finalization                  :  00-00:00:00.383             0.384



When I used 1 core:

===============================================================================
G E O S - C H E M   T I M E R S
 
  Timer name                       DD-hh:mm:ss.SSS     Total Seconds
-------------------------------------------------------------------------------
GEOS-Chem                     :  00-00:04:48.382           288.383
  Initialization                :  00-00:00:03.013             3.014
  HEMCO                         :  00-00:01:04.896            64.896
  All chemistry                 :  00-00:00:00.728             0.729
  => FlexChem                   :  >>>>> THE TIMER DID NOT RUN <<<<<
    -> FlexChem loop            :  >>>>> THE TIMER DID NOT RUN <<<<<
    -> Init KPP                 :  >>>>> THE TIMER DID NOT RUN <<<<<
    -> Het chem rates           :  >>>>> THE TIMER DID NOT RUN <<<<<
    -> Photolysis rates         :  >>>>> THE TIMER DID NOT RUN <<<<<
    -> KPP                      :  >>>>> THE TIMER DID NOT RUN <<<<<
       RCONST                   :  >>>>> THE TIMER DID NOT RUN <<<<<
       Integrate 1              :  >>>>> THE TIMER DID NOT RUN <<<<<
       Integrate 2              :  >>>>> THE TIMER DID NOT RUN <<<<<
    -> Prod/loss diags          :  >>>>> THE TIMER DID NOT RUN <<<<<
    -> OH reactivity diag       :  >>>>> THE TIMER DID NOT RUN <<<<<
  => FAST-JX photolysis         :  >>>>> THE TIMER DID NOT RUN <<<<<
  => Aerosol chem               :  >>>>> THE TIMER DID NOT RUN <<<<<
  => Linearized chem            :  >>>>> THE TIMER DID NOT RUN <<<<<
  Transport                     :  00-00:02:13.583           133.584
  Convection                    :  >>>>> THE TIMER DID NOT RUN <<<<<
  Boundary layer mixing         :  00-00:00:20.931            20.932
  Dry deposition                :  >>>>> THE TIMER DID NOT RUN <<<<<
  Wet deposition                :  >>>>> THE TIMER DID NOT RUN <<<<<
  All diagnostics               :  00-00:00:04.498             4.498
  => HEMCO diagnostics          :  00-00:00:00.014             0.015
  => ObsPack diagnostics        :  >>>>> THE TIMER DID NOT RUN <<<<<
  => History (netCDF diags)     :  00-00:00:04.483             4.483
  Unit conversions              :  00-00:00:02.112             2.112
  Input                         :  00-00:00:55.883            55.884
  Output                        :  00-00:00:04.487             4.487
  Finalization                  :  00-00:00:00.260             0.261


Sorry the formatting is not good, but essentially the time taken by different things is more and less similar and as you can see, the speed advantage upon using 8 cores v/s 1 core is just 8 seconds.

**Comment by yantosca** [comment]
Thanks for the update @garvitagarwal290.  We don't have much experience using GEOS-Chem on a laptop, but I'm wondering if OS may have other systems running on it simultaneously and thus can't allocate the full 8 cores to the GEOS-Chem run.  It could also be that GEOS-Chem is competing with other processes on your system for memory, and thus your multi-core run may end up swapping virtual memory to disk.  Try setting:
```console
$sysctl -w vm.swappiness=10
```
[See this post](https://linuxhint.com/understanding_vm_swappiness/) for a good explanation of what this does.

**Comment by garvitagarwal290** [comment]
Thanks for the suggestion. But the setting didnt make a difference in the simulation time.
Did you miss my previous question: When I define OMP_NUM_THREADS before running geos-chem, I also set the variable OMP_STACKSIZE. While I am changing the former from 8 to 1 or vice versa, I always use the value 500m for the latter. Might this be affecting my case?

**Comment by yantosca** [comment]
@garvitagrawal290: Setting OMP_STACKSIZE to 500m should just tell the OS to set the the stack size limit to the maximum available on your machine.  Rarely will it use 500m but that is a quick way of always maxing it out.
