### ISSUE TITLE
 Forced exit from Rosenbrock error due to the step size too small

### ISSUE THREAD

**Issue by herizonarivelo** [geoschem/geos-chem#2113]
### Name and Institution (Required)

Name: Herizo Narivelo
Institution: Laboratoire d'Aérologie- Université Toulouse III Paul Sabatier (France)

### Confirm you have reviewed the following documentation

- [ x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

Dear GEOS-Chem community, I'm using the GCHP v14.2.2 and I'm experiencing this forced exit problem on a specific date (26 July 2008 at 03:40 as mentionned in the GC.log file) of my simulation starting on 1st of July on 2008 (one month simulaiton test). 
I have attached here the log file for reference GC.log of my one month simulation.

[gchp.20080701_0000z.log](https://github.com/geoschem/geos-chem/files/13890082/gchp.20080701_0000z.log)

Thanks a lot for your support to resolve this error.
Herizo

**Comment by lizziel** [comment]
Hi @herizonarivelo, you may be running into the same issue reported in https://github.com/geoschem/geos-chem/issues/1982. We added a fix to version 14.3.0 that prevents convergence instability in GCHP 14.2. Version 14.3.0 will be released within the next month or so. In the meantime you can find the fix here: https://github.com/geoschem/geos-chem/pull/2006.

**Comment by yantosca** [comment]
Closing out this issue
