### ISSUE TITLE
Missing GEOS_0.5x0.625 MERRA2 data in 2023-10-04

### ISSUE THREAD

**Issue by jjp1987** [geoschem/geos-chem#2114]
### Name and Institution (Required)

Name: Missing GEOS_0.5x0.625 MERRA2 data in 2023-10-04
Institution: The file MERRA2.20231004.A3cld.05x0625.nc4 have lost in http://geoschemdata.wustl.edu/ExtData/GEOS_0.5x0.625/MERRA2/2023/10/

### Confirm you have reviewed the following documentation

- [ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

**Comment by SaptSinha** [comment]
The MERRA2.20231004.A3cld.05x0625.nc4 file is now available in the 2023/10 archive.

**Comment by jjp1987** [comment]
Thank you very much!
