### ISSUE TITLE
OFFLINE_LIGHTNING after 2022 is absent in the washu server.

### ISSUE THREAD

**Issue by PowderL** [geoschem/geos-chem#2118]
### Name and Institution (Required)

Name: Tao Li
Institution: Tsinghua University

### Description of your issue or question
I am running GC in 2023 but the OFFLINE_LIGHTNING is not in the washu server after 2022. I would like to know if the data is ready and if you could update that on the server.

Best wishes

**Comment by SaptSinha** [comment]
@yantosca: The WashU GCST currently does not produce the OFFLINE_LIGHTNING archive. Previously, these were generated by Lee Murray's research group at the University of Rochester which I then pulled into WashU via a Globus transfer from UR. He might be able to help with generating the new datasets beyond 2022.

**Comment by ltmurray** [comment]
The offline lightning is processed and updated annually after the December meteorology for the previous year becomes available; this is typically in early March of the following year. Until it is available, we recommend using the provided offline lightning climatology.

**Comment by yantosca** [comment]
Closing issue as resolved
