### ISSUE TITLE
[BUG/ISSUE]Frequency and variable settings for reading nc files in HEMCO.

### ISSUE THREAD

**Issue by ackerman1225** [geoschem/geos-chem#212]
Hello,

The GEOS-Chem version I am using is 12.1.0, and I want to run the Hg model by replacing the default monthly mean Br_GC concentrations file in the BrOx fields of HEMCO_Config.rc with hourly mean Br&BrO concentrations files(one file an hour, and the names of each file are similar to: ts2013010100.nc, ts2013010101.nc, ts2013010102.nc, ..., ts2018010100.nc). 

Before modification, the BrOx fields of HEMCO_Config.rc is:
```
(((BrOx_GC
* Br_GC      $ROOT/MERCURY/v2018-04/halogens.Johan.Mar16.2007.nc IJ_24H_S__Br   2007/1-12/1/0 C xyz ppbv * - 1 1
* BrO_GC     -                                                   IJ_24H_S__BrO  -             - -   ppbv * - 1 1
)))BrOx_GC
```
After modification(Tip: In ts files, the variable names for Br and BrO are  IJ_AVG_S__Br and  IJ_AVG_S__BrO):
```
(((BrOx_GC
* Br_GC      /data/home/ympeng/GEOS-Chem/ProcessBr/ts$YYYY$MM$DD$HH.nc IJ_AVG_S__Br   2013-2018/$MM/$DD/$HH+30minutes C xyz ppbv * - 1 1
* BrO_GC     -                                                         IJ_AVG_S__BrO  -                               - -   ppbv * - 1 1
)))BrOx_GC
```
However, after running, I found that it doesn't read correctly from the first ts file, I also tried to add the code to output Br&BrO concentrations in global_br_mod.F and found them to be the same, which is obviously not reasonable. An example of the Br&BrO concentrations of the output:
```
 Br_TROP(36,23,5) =  7.763581444386602E-008
 BrO_TROP(36,23,5)=  7.763581444386602E-008
 Br_TROP(60,18,2) =  1.797566073946655E-002
 BrO_TROP(60,18,2)=  1.797566073946655E-002
 C_BR(60,18,2)=   418363.011043022     
 C_BRO(60,18,2)=   418363.011043022     
 C_BR(36,23,5)=   1.77199686061588     
 C_BRO(36,23,5)=   1.77199686061588 
```

After that, we tried to modify the code of mercury_mod.F( ln673-ln731&ln5418-5424) to change the read frequency of Br and BrO, but the results have not improved.

I want it to update every hour while reading ts files, and ensure that the concentration of Br and BrO can be read correctly, should I modify the HEMCO file or the code in mercury_mod.F?

Here is the mercury_mod.F:
[mercury_mod.F.txt](https://github.com/geoschem/geos-chem/files/4151460/mercury_mod.F.txt)

Thanks in advance!

**Comment by yantosca** [comment]
Thanks for writing.  I think you will need to change the time specification in the HEMCO_Config.rc to:

```
* Br_GC      $ROOT/MERCURY/v2018-04/halogens.Johan.Mar16.2007.nc IJ_24H_S__Br   2007/1-12/1-31/0-23 C xyz ppbv * - 1 1
* BrO_GC     $ROOT/MERCURY/v2018-04/halogens.Johan.Mar16.2007.nc IJ_24H_S__BrO  2007/1-12/1-31/0-23 C xyz ppbv * - 1 1
```
See if this works.  The way you had it written before, it was only telling HEMCO to read the first day of the month, at 00 UTC.

**Comment by ackerman1225** [comment]
Thanks for your reply. I tried to run it after modification, and it has been solved!
