### ISSUE TITLE
Photolysis rate of NO2 (jNO2)

### ISSUE THREAD

**Issue by ks3506** [geoschem/geos-chem#2120]
### Name and Institution (Required)

Name: Kaiya Shealy
Institution: Texas A&M Corpus Christi

### Confirm you have reviewed the following documentation

- [x ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [x ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Hi, 
I wanted to ask how the GEOS-Chem model calculates the photolysis rate of NO2 (jNO2), typically used to calculate the Leighton ratio. 
Thanks. 

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

**Comment by yantosca** [comment]
Thanks for writing @ks3506.  GEOS-Chem 14.2.0 and prior versions use the FAST-JX photolysis scheme to compute the photolysis rates.  [See this link for references](https://wiki.seas.harvard.edu/geos-chem/index.php/FAST-JX_v7.0_photolysis_mechanism).

GEOS-Chem 14.3.0 and later will use Cloud-J, which is an updated version of FAST-JX.

Tagging @lizziel

**Comment by lizziel** [comment]
Hi @ks3506, let us know if you have a more specific question than generally how the model calculates the rate. We can point you to code or direct you to the Chemistry Working Group, depending on what level of detail you need. Note that the wiki page @yantosca pointed you to has not been updated for a while. However, the general information is correct. The latest photolysis data files read into Fast-JX (14.2 and prior are [here](https://ftp.as.harvard.edu/gcgrid/data/ExtData/CHEM_INPUTS/FAST_JX/v2021-10/)). The same cross-section data, simply modified for format, are used in [Cloud-J](https://github.com/geoschem/Cloud-J/tree/geos-chem) and are stored [here](https://ftp.as.harvard.edu/gcgrid/data/ExtData/CHEM_INPUTS/CLOUD_J/v2023-05/). You can search the files for `NO2` to see notes specific to that species. Note that Cloud-J differs from Fast-JX primarily in that it handles clouds differently than Fast-JX.

**Comment by yantosca** [comment]
Closing out this issue
