### ISSUE TITLE
Unusual High value around Lake Chad

### ISSUE THREAD

**Issue by jiaying002** [geoschem/geos-chem#2121]
### Name and Institution (Required)
Name:  Jiaying Li
Institution: Nanyang Technological University

### Description of your issue or question
I am using GCClassic v14.0.0 to run my simulations. 
1. 2050: Used RCP8.5 emission (yr 2050) and SSP5-8.5 climate (yr 2049). 
2. 2010: Used RCP8.5emission (yr 2010) and SSP5-8.5 climate (yr 2010).

Below are my PM_2.5 concentration results (from AerosolMass) for both 2010 and 2050 at vertical layer 1 around Lake Chad are extremely high (550 ug/m^3). I attached my ground layer result and my code. Would you please help me to explain why the value there is that high?

Thank you in advance!

For the ground level, I got the annual graphs like this:
![image](https://github.com/geoschem/geos-chem/assets/113654537/6cc74f28-0584-4103-8828-eee90f81da7a)
![image](https://github.com/geoschem/geos-chem/assets/113654537/fe12d12d-5cfc-4fc9-93fd-6b4bdac17f82)
[geoschem_config.yml.txt](https://github.com/geoschem/geos-chem/files/13938444/geoschem_config.yml.txt)
[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/13938446/HEMCO_Config.rc.txt)
[HISTORY.rc.txt](https://github.com/geoschem/geos-chem/files/13938447/HISTORY.rc.txt)
[GEOSChem.AerosolMass.20400104_0000z.nc4.txt](https://github.com/geoschem/geos-chem/files/13938448/GEOSChem.AerosolMass.20400104_0000z.nc4.txt)

**Comment by jiaying002** [comment]
I checked the species that contribute to the PM_2.5, and found out that DUST1 and DUST2 have a pretty high value. In this case, I'd like to ask, should I also false the offline and online DustDead? (I thought DustDead is not anthropogenic emission)

**Comment by yantosca** [comment]
Thanks for writing @jiaying002.  It could be an issue with the GCAP met fields, as the dust mobilization is highly sensitive to the 10m wind speed.  I would check the U10M and V10M fields (or whatever they are named in GCAP2) to see if there are any anomalies.

Also tagging @ltmurray

**Comment by ltmurray** [comment]
As @yantosca said, the dust emissions parameterization is extremely sensitive to wind speed and, consequently, to model resolution. It appears you are running GEOS-Chem at 0.5 x 0.625 resolution, whereas the meteorology is natively at 2 x 2.5, so your maps suggest that the surface maps that go into the dust parameterization (available at finer resolution), may also have a compounding role.

**Comment by jiaying002** [comment]
Thank you @yantosca @ltmurray
