### ISSUE TITLE
14.1.1,Is the official restart file only for "global region"?

### ISSUE THREAD

**Issue by Hugh-Su** [geoschem/geos-chem#2124]
### Name and Institution (Required)

Name: Hugh 
Institution:  Institute for Environment and Climate Research, Jinan University

### Confirm you have reviewed the following documentation

- [ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question
  1.Is the official restart file only for "global region"? Is there any restart file for "Asian region" only?
  2.I am running a CH4 simulation with GEOS-Chem "Classic" v 14.1.1. The catalogue information is as follows :  
  meteorology source : GEOS-FP ;
  horizontal resolution : 0.25 x 0.3125 ;
  horizontal grid domain : Asia ;
  number of levels : 47
  I found that the default restart file in the catalogue is 2x2.5 and for the global region. With the time resolution set to 1 day, I am simulating with that restart file and the subsequent restart file generated is for the Asian region. Can you please tell me if you only provide restart file for global region?

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

**Comment by yantosca** [comment]
Closing out this issue
