### ISSUE TITLE
Issue with aerosol pH in nested simulation

### ISSUE THREAD

**Issue by ktravis213** [geoschem/geos-chem#2126]
### Name and Institution (Required)

Name: Katie Travis
Institution: NASA Langley

### Confirm you have reviewed the following documentation

- [Y ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ Y] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ Y] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [Y ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question
I output aerosol pH from  'Chem_IsorropHplusAccum        ', in HISTORY.rc.  There is a clear issue at the boundaries with aerosol PH. See attached ncview output for aerosol PH from 5/22/16 for the nested Asia domain using GEOS-Chem 13.4.0. 

![AerosolpH](https://github.com/geoschem/geos-chem/assets/4801915/f26e85f4-4b0c-48cd-a599-00b5216fe7c1)

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

**Comment by yantosca** [comment]
Closing out this issue.
