### ISSUE TITLE
Question about the HEMCO folder

### ISSUE THREAD

**Issue by Fearlessssssss** [geoschem/geos-chem#2129]
### Name and Institution (Required)

Name:Tyler
Institution:Tsinghua University

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

Hi,GCST. I have a question about the HEMCO folders for CH3I. The parent folder is named 'CH3I,' but it includes the inventory of CH4 from wetlands and rice. Additionally, this folder does not provide a reference. Where can I find the reference for this folder?"

https://ftp.as.harvard.edu/gcgrid/data/ExtData/HEMCO/CH3I/v2014-07/

**Comment by yantosca** [comment]
Thanks for writing.  I think these data were used for the now defunct CH3I specialty simulation in GEOS-Chem.  Looking at the code, I found these references:
```F90
!  References
!  ============================================================================
!  (1 ) Bell, N. et al, "Methyl Iodide: Atmospheric budget and use as a tracer
!        of marine convection in global models", J. Geophys. Res, 107(D17), 
!        4340, 2002.
!  (2 ) Nightingale et al [2000a], J. Geophys. Res, 14, 373-387
!  (3 ) Nightingale et al [2000b], Geophys. Res. Lett, 27, 2117-2120
!  (4 ) Wanninkhof, R., "Relation between wind speed and gas exchange over
!        the ocean", J. Geophys. Res, 97, 7373-7382, 1992.
```

I think the Bell paper is the source for the CH3i simulation and data.

**Comment by Fearlessssssss** [comment]
Got it！Thanks a lot！
