### ISSUE TITLE
[FEATURE REQUEST] Add #ifdef MODEL_CLASSIC and #ifdef MODEL_GCHP

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#213]
To be consistent with ```#ifdef MODEL_GEOS``` and ```#ifdef MODEL_WRF``` we should also add:

1.  ```#ifdef MODEL_CLASSIC``` for code blocks that only need to execute for GEOS-Chem "Classic", and
2. ```#ifdef MODEL_GCHP``` for code blocks that only need to execute for GCHP.

Also see the discussion in Issue https://github.com/geoschem/geos-chem/issues/168,

**Comment by yantosca** [comment]
And by extension, we would also remove

```F90
#ifdef ESMF_
#ifdef EXTERNAL_FORCING
#ifdef EXTERNAL_GRID
```
as these would no longer be needed.

**Comment by lizziel** [comment]
MODEL_GCHP and MODEL_CLASSIC will be available in 12.7.1. MODEL_GCHPCTM is also available for those of us developing that experimental mode of GCHP.

I am going to close out this feature request. Remaining discussion about removing ESMF_, EXTERNAL_FORCING, etc (see previous comment) can be put on the discussion issue for CPP switches (Issue https://github.com/geoschem/geos-chem/issues/168).
