### ISSUE TITLE
help with solving ncdfUtil bugs while compiling GEOS-Chem V10

### ISSUE THREAD

**Issue by yixinguo0421** [geoschem/geos-chem#2130]
### Name and Institution (Required)

Name: Yixin GUO
Institution: Peking University

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

Dear GEOS-Chem support team,

I am writing for help with compiling GEOS-Chem v10.1.1. I have to use this version because a former group member added some heterogeneous SIA formation code to it and this version would help evaluate our research question of interest.

When I 'make -j4 mpbuild' under the run directory, I received these errors indicating issues with NC_VAR_WRITE_INT and R8 and R4. I googled it and it seems to be related to some bugs with ifort but I am not sure （https://community.intel.com/t5/Intel-Fortran-Compiler/COMPILER-BUG-incorrect-quot-Ambiguous-generic-interface-quot/m-p/1365383). These subroutines seem to have been declared in ncdf_mod.F90 but not used much elsewhere, would it be a quick fix to change the names to make them less identical? Or it is more likely that there are problems with my netcdf libraries. 

I am compiling v10.1.1 on a supercomputer that I used to have successfully compiled v12.9.3, could it be my current netcdf library not compatible with v10.1.1?I have tested my current .bashrc as well as another persons’ who run GCHP. 

My netcdf settings in .bashrc:

export LD_LIBRARY_PATH=“/gpfs/share/software/compilers/intel/2018.0/lib/intel64”
export LD_LIBRARY_PATH
export LD_LIBRARY_PATH_modshare="/gpfs/share/software/netcdf/4.4.1/intel/2018.0/lib/:/gpfs/share/home/2006393084/spack/opt/spack/linux-centos7-skylake_avx512/intel-18.0.0/netcdf-fortran-4.5.3-kkiaol2gxiepgeavyfq5gauydee2k3zq/lib/:/gpfs/share/software/compilers/intel/2018.0/lib/"
 

Very much look forward to receiving your reply and all help is greatly appreciated. 
I read the online documentation for v10 a lot but many links have been deleted. For example, when I want to look into netcdf settings in the documentation page (https://geoschem.github.io/gcclassic-manpage-archive/man.v10-01/index.html, this still works), the actual page no longer exists (http://wiki.seas.harvard.edu/geos-chem/index.php/Installing_libraries_for_GEOS-Chem)

![3521705651012_ pic_hd](https://github.com/geoschem/geos-chem/assets/75709818/22727f65-b9ce-4bf6-8f7c-e24a7055b7fe)

![3551705654707_ pic](https://github.com/geoschem/geos-chem/assets/75709818/2a338645-daba-43d4-a154-54d38a52d0b7)

**Comment by yantosca** [comment]
Thanks for writing @yixinguo0421.  You are probably using a newer version of the ifort compiler, which enforces the newer Fortran standards (e.g. F2003 of F2008).  We encountered the same thing when we were porting GEOS-Chem to GNU Fortran.

I kept a list of the modifications that I had to do to get GEOS-Chem to work with the newer compiler.  There were some modifications in the NcdfUtil folder.  [See this link for details](https://wiki.seas.harvard.edu/geos-chem/index.php/GNU_Fortran_compiler#Modules_in_NcdfUtil ).  You can also take a look at the [most recent ncdf_mod.F90](https://github.com/geoschem/geos-chem/blob/main/NcdfUtil/ncdf_mod.F90) in the GEOS-Chem repository.  I think if you make the same modifications then it'll compile.

**Comment by yixinguo0421** [comment]
Thank you so much for your timely help! I followed the files and it worked. I also encountered some hmco diagnosis problem but the link provided has helped too. I have successfully generated a geos exe now.

**Comment by yantosca** [comment]
Thanks for letting me know it worked @yixinguo0421 !  Happy to hear.  I will close out this issue now.
