### ISSUE TITLE
[QUESTION] Typo in wiki link in readme

### ISSUE THREAD

**Issue by zmoon92** [geoschem/geos-chem#214]
This is more of a bug report, but not about GEOS-Chem directly. The text of the link to the wiki within `README.md` is incorrect:
`http://wiki-geos.chem.org/` does not correctly redirect to the wiki at <http://wiki.seas.harvard.edu/geos-chem/index.php/Main_Page>, but `http://wiki.geos-chem.org/` does.

**Comment by lizziel** [comment]
Thanks for catching that. It will be fixed in the upcoming release, 12.7.1.
