### ISSUE TITLE
[FEATURE REQUEST] Change GCHP run directory terminology to use raw rather than native

### ISSUE THREAD

**Issue by lizziel** [geoschem/geos-chem#2140]
### Name and Institution (Required)

Name: Lizzie Lundgren
Institution: Harvard University

### New GEOS-Chem feature or discussion

The GCHP run directory creation script prompts users to choose between "native" or "processed" meteorology files. This is confusing since in some cases native and processed are the same grid resolution. It would be better to use "raw" instead of native.

**Comment by yantosca** [comment]
This has now been done in PR #2178, which has been merged into the "no-diff-to-benchmark" development stream.  We can now close this issue.
