### ISSUE TITLE
How to obtain CO2 emission files of resolution higher than 1x1? 

### ISSUE THREAD

**Issue by garvitagarwal290** [geoschem/geos-chem#2141]
### Name and Institution (Required)

Name: Garvit Agarwal
Institution: TCS, Pune, India

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Sorry if this question has already been answered, but I couldn't find an existing related issue. I intend to run simulations at resolution 0.25x0.3125 but the emission files for CO2 at http://geoschemdata.wustl.edu/ExtData/HEMCO/CO2/ are either 1x1 resolution or lower. Where and how can I obtain emission files for CO2 at higher resolution? Thank you.

**Comment by yantosca** [comment]
Thanks for writing @garvitagarwal290.  The CO2 specialty simulation emissions probably haven't been updated at a while.  You can look into using CEDS emissions (there is a new version at finer resolution, but I think we haven't pulled that into GEOS-Chem yet).  Tagging @1Dandan.

Also you might check in with the Carbon Gases working group and Emissions Working Group to see if there are newer emissions sources.

**Comment by 1Dandan** [comment]
Yes, anthropogenic CO2 emissions are available at 0.1 degree globally at:
http://geoschemdata.wustl.edu/ExtData/HEMCO/CEDS/v2023-04/
