### ISSUE TITLE
Reduce entries in GCHP HISTORY.rc

### ISSUE THREAD

**Issue by lizziel** [geoschem/geos-chem#2142]
### Name and Institution (Required)

Name: Lizzie Lundgren
Institution: Harvard University

### New GEOS-Chem feature or discussion

GCHP does not have the history wildcard feature and thus there are many entries in the full chemistry `HISTORY.rc` file. Most users will not want to output all species for certain collections. Maintaining the species lists is also a burden. I recommend reducing the collection entries (full chemistry only) except for what is used for GEOS-Chem benchmarking. Collections turned off for benchmarking would remain but have reduced lists, e.g. budget could have only ozone and I can put that update into my existing budget diagnostics PR https://github.com/geoschem/geos-chem/pull/2127.

Does anyone object to this?

**Comment by yantosca** [comment]
The motivation for this issue partly comes from #2139 and #2135.  I now believe the issue with the GCHP DryDep collection in HISTORY.rc is due to incorrect specification of dry-depositing species.

For benchmarking purposes, we can reduce to:
```console
#==============================================================================
# %%%%% THE DryDep COLLECTION %%%%%
#
# Dry depositon fluxes and velocities (for all dry-depositing species)
#
# Available for all simuations that have dry-depositing species
#==============================================================================
  DryDeptemplate:        '%y4%m2%d2_%h2%n2z.nc4',
  DryDep.format:          'CFIO',
  DryDep.timestampStart:  .true.
  DryDep.monthly:         0
  DryDep.frequency:       010000
  DryDep.duration:        010000
  DryDep.mode:            'time-averaged'
  DryDep.fields:          'DryDepVel_ACET       ', 'GCHPchem',
                          'DryDepVel_HNO3       ', 'GCHPchem',
	                  'DryDepVel_NH3        ', 'GCHPchem',
                          'DryDepVel_NH4        ', 'GCHPchem',
                          'DryDepVel_NIT        ', 'GCHPchem',
                          'DryDepVel_NITs       ', 'GCHPchem',
                          'DryDepVel_O3         ', 'GCHPchem',
                          'DryDepVel_SO4        ', 'GCHPchem',
                          'DryDep_O3            ', 'GCHPchem',
::

```

**Comment by lizziel** [comment]
This is now done. Also note I have a new issue at GEOS-ESM/MAPL about wildcard functionality in GCHP:
https://github.com/GEOS-ESM/MAPL/issues/2647
