### ISSUE TITLE
Special species simulation

### ISSUE THREAD

**Issue by ast222340** [geoschem/geos-chem#2146]
### Name and Institution (Required)

Name: Deep
Institution: Delhi

### Confirm you have reviewed the following documentation

- [Y] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [Y] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [Y] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [Y] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question
@lizziel 
I have a question about a particular species.I am working with N2O project.Are there any special simulations related to N2O NOx or Nitrogen?For example,there is a simulation for CH4,CO2,Carbon,.....If so please tell me how to do it.

  Choose simulation type:
-----------------------------------------------------------
   1. Full chemistry
   2. Aerosols only
   3. CH4
   4. CO2
   5. Hg
   6. POPs
   7. Tagged CH4
   8. Tagged CO
   9. Tagged O3
  10. TransportTracers
  11. Trace metals
  12. Carbon

**Comment by lizziel** [comment]
@ast222340, to include nitrogen species in GEOS-Chem you will need to do a full chemistry simulation.
