### ISSUE TITLE
[FEATURE REQUEST] Require scheduler entry in integration tests

### ISSUE THREAD

**Issue by lizziel** [geoschem/geos-chem#2147]
### Name and Institution (Required)

Name: Lizzie Lundgren
Institution: Harvard University

### New GEOS-Chem feature or discussion

I noticed that if you exclude the scheduler option when submitting GEOS-Chem Classic and GCHP integration tests then only the compilation tests are run. This can be an unexpected result if you simply forget to pass that argument. It would be nice to have the following behavior instead:
1. Require scheduler to be specified, and error out if not, with a printout of the options available.
2. Allow `-s none` as an option. If this is passed then give a warning that compile-only tests will be run because no scheduler will be used. Prompt the user to accept this and proceed, or quit.

**Comment by yantosca** [comment]
This is now done in PR #2182 and merged into the GEOS-Chem "no-diff-to-benchmark" development stream.  We can close out this issue now.

**Comment by lizziel** [comment]
I am reopening this issue since a key part of this feature request is to exit with an error if calling integration tests and scheduler is not passed. This avoids unexpected behavior of only running compiler tests.

**Comment by yantosca** [comment]
@lizziel: I believe this was added in commit b93fe8ccab36cbcf1e66f13f8f9def0fd576e7e7.

**Comment by lizziel** [comment]
Ah, great! I think that must have been added after I looked at the PR. Thanks!
