### ISSUE TITLE
[FEATURE REQUEST] Consider activating additional diagnostics in benchmark simulations

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#2149]
### Name and Institution (Required)

Name: Melissa Sulprizio
Institution: Harvard / GCST

### New GEOS-Chem feature or discussion

Benchmark run directories are currently created with the following diagnostic collections enabled in HISTORY.rc:

```
COLLECTIONS: 'Restart',
             'Metrics',
             'SpeciesConc',
             'AdvFluxVert',
             'AerosolMass',
             'Aerosols',
             #'Budget',
             #'CloudConvFlux',
             #'ConcAboveSfc',
             #'ConcAfterChem',
             #'DryDep',
             'JValues',
             #'KppDiags',
             #'KppARDiags',
             #'LevelEdgeDiags',
             #'ProdLoss',
             #'RRTMG',
             #'RxnRates',
             #'RxnConst',
             #'SatDiagn',
             #'SatDiagnEdge',
             #'StateChm',
             'StateMet',
             #'StratBM',
             #'Tomas',
             #'UVFlux',
             #'WetLossConv',
             #'WetLossLS',
             #'BoundaryConditions',             
```

However, for 1-year benchmarks, we need to activate (uncomment) additional diagnostic collections, including:

- DryDep
- ProdLoss
- WetLossConv
- WetLossLS
- LevelEdgeDiags
- ConcAfterChem
- StateChm
- CloudConvFlux

To detect issues and/or changes in these diagnostics earlier, we should include them in 1-hr and 1-month benchmarks. To avoid saving out large files we could consider saving out a subset of specie/diagnostics in each collection.

**Comment by yantosca** [comment]
We can now close this issue as "alldiags" integration test were introduced in PR #2399.
