### ISSUE TITLE
[BUG/ISSUE] Cannot get field GFED_TEMP" in GC 12.5.0

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#215]
I am submitting this issue on behalf of Tianlang Zhao (tzhao@alaska.edu):

>I am now using GEOS-Chem 12.5.0 to run a global 2x2.5 simulation. But HEMCO crashes. Here is the error output.
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
HEMCO ERROR: Cannot find field with valid time stamp in /import/c1/GREENING/shared/data/ExtData/HEMCO/GFED4/v2015-10/2016/GFED4_gen.025x025.201607.nc - Cannot get field GFED_TEMP. Please check file name and time (incl. time range flag) in     the config. file
ERROR LOCATION: HCOIO_READ_STD (hcoio_read_std_mod.F90)
ERROR LOCATION: HCOIO_DataRead (hcoio_dataread_mod.F90)
ERROR LOCATION: ReadList_Fill (hco_readlist_mod.F90)
ERROR LOCATION: ReadList_Read (hco_readlist_mod.F90)
ERROR LOCATION: HCO_RUN (hco_driver_mod.F90) 
```
>I checked the GFED4_gen.025x025.201607.nc file, but the variation DM_TEMP is in the file. The website manual says that it can due to using Restart file from an old version. But I download a 12.6.0 restart file from http://ftp.as.harvard.edu/gcgrid/data/ExtData/GEOSCHEM_RESTARTS/ but it still doesn’t work.

**Comment by yantosca** [comment]
Thanks for writing.  Would you be able to share with the input and log files from the simulation, as described on the wiki here: http://wiki.geos-chem.org/Submitting_GEOS-Chem_support_requests

**Comment by yantosca** [comment]
Have you checked that this file
```
/import/c1/GREENING/shared/data/ExtData/HEMCO/GFED4/v2015-10/2016/GFED4_gen.025x025.201607.nc
```
can be read properly?  It could be that the file might be corrupted on your end (due to incomplete FTP transfer).  Try using the ncdump command:
```
ncdump -cts /import/c1/GREENING/shared/data/ExtData/HEMCO/GFED4/v2015-10/2016/GFED4_gen.025x025.201607.nc
```
If the file is OK, then you should get output from this command.  If not, it will tell you that the file can't be read.

**Comment by zhendonglu** [comment]
I think I encountered the same issue in GCv12.7.0, and I believe my file is OK. So, what's the solution to this issue?
