### ISSUE TITLE
Issues in getting dependencies on an institute HPC.

### ISSUE THREAD

**Issue by garvitagarwal290** [geoschem/geos-chem#2150]
### Name and Institution (Required)

Name: Garvit Agarwal
Institution: IISER Pune

### Confirm you have reviewed the following documentation

- [ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Hi, I am trying to run GEOS-Chem Classic on my institute HPC. I am not able to install the dependencies using Spack since it fails with 'permission denied' (I dont have root access on this HPC). The HPC has several 'modules' available including for netcdf-fortran, hdf5 etc that I am able to load with 'module load <module-name>'. However when I try to build my run directory using command 'cmake ../CodeDir -DRUNDIR=..' , I get the error:

Counldn't find one or more of NetCDF's files! The following
  files/directories weren't found:

      NETCDF_F_LIBRARY: Path to "libnetcdff.so"
      NETCDF_F90_INCLUDE_DIR: Directory containing "netcdf.mod"
      NETCDF_F77_INCLUDE_DIR: Directory containing "netcdf.inc"

I am not able to find these files so I cant provide the path to them to cmake. 

Is it not possible to use GEOS-Chem by loading modules like this?
My bigger question is whether there is another way to build all the dependencies?

**Comment by yantosca** [comment]
Thanks for writing @garvitagarwal290.  You can indeed use modules like this for GEOS-Chem.  You will probably need to use an environment file to set these variables using an environment file (a shell script) such as this: https://geos-chem.readthedocs.io/en/latest/getting-started/login-env-files-gnu.html

When you load the modules (at least on our system), it should define one or more environment file (e.g. `NETCDF_C_HOME`, `NETCDF_C_LIB`) that points to the root folder of the library installation.  You can ask your HPC support staff about this.

**Comment by garvitagarwal290** [comment]
Thanks @yantosca ! Your comment allowed me to make GEOS-Chem run on my HPC!
