### ISSUE TITLE
Dryrun issue!

### ISSUE THREAD

**Issue by saskia222** [geoschem/geos-chem#2152]
### Name and Institution (Required)

Name: Saskia 
Institution: UCD

### Confirm you have reviewed the following documentation

- [ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Hello, I've got a few questions about running the software! I'm using the latest version of GEOS-Chem Classic. I'm currently having problems using the dryrun to download data: 
![image](https://github.com/geoschem/geos-chem/assets/125769299/de04a7b9-f163-4d95-96a6-79146ad66cf3)

I created an ExtData file in the directory, but I'm unsure if that was the right thing to do as it's not really mentioned in the documentation, only in this step. And i think I've labelled the path correctly.

![image](https://github.com/geoschem/geos-chem/assets/125769299/8adbe1b0-b6f8-4efc-9409-6541545b412c)

![image](https://github.com/geoschem/geos-chem/assets/125769299/45b5d099-096e-42ae-92bb-a6fd0b55e374)

![image](https://github.com/geoschem/geos-chem/assets/125769299/1c2a2973-9b38-47f8-ae9f-039e427b4911)

Any help is appreciated! I have never used this software before, and just need it to make a prediction of a verticle profile of ozone concentration with altitude over Ireland for a project. Thanks!

**Comment by yantosca** [comment]
Thanks for writing @saskia222.  The `ExtData/` folder should not g into the run directory but should be in a common space on disk where it can be accessed by multiple users.  Or if you are running GEOS-Chem on an AWS EC2 instance, it can be in your home directory (i..e `/home/ubuntu/ExtData/`)

To fix the issue, try:

```console
$ mv /home/saskia29/.geoschem /home/saskia29/ExtData
$ cd /home/saskia29/gc_05x0625_CU_merra2_tagO3
```
and then edit the `geoschem_config.yml` file:
```yaml
simulation:
  ... etc skipped ...
  root_data_dir: /home/saskia29/ExtData
```
Then re-run the GEOS-Chem dry-run
```console
$ ./gcclassic --dryrun > log.dryrun
$ ./download_data.py log.dryrun --washu
```

**Comment by yantosca** [comment]
@saskia222, are you still having problems with this issue?  If resolved we can close it out. Thanks.

**Comment by yantosca** [comment]
Closing out this issue
