### ISSUE TITLE
Is Version v10-01 available?

### ISSUE THREAD

**Issue by linguo4** [geoschem/geos-chem#2156]
### Name and Institution (Required)

Name: Lin Guo
Institution: University of Illinois Urbana-Champaign

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question
I've been trying to find the source code for GEOS-Chem version v10-01 for some tests and I tried to search the git repo history but it seems not there. Then I tried the [**link**](https://geoschem.github.io/gcclassic-manpage-archive/man.v10-01/chapter_2.html#DownCode) in the documentation and it throws  error below:
![image](https://github.com/geoschem/geos-chem/assets/67442207/e38e99a4-b80d-48a4-ac29-9e1580b4a6ec)

I'd like to ask if there are other ways for me to install v10-01 or I missed anything in the ways I've been trying. Thank you!

**Comment by yantosca** [comment]
Thanks for writing @linguo4.  I think this command will work:
```console
$ git clone -b v10-01-public-release https://github.com/geoschem/geos-chem
```
Also see the manual for this version at: https://geoschem.github.io/gcclassic-manpage-archive/man.v10-01/index.html

NOTE: As v10-01 is an obsolete version we are unable to provide support beyond this information.
