### ISSUE TITLE
Process contribution to concentration of PM2.5 in GEOS-Chem

### ISSUE THREAD

**Issue by YanshunLi-washu** [geoschem/geos-chem#2157]
Name: Yanshun Li
Institution: Washington University in St. Louis

Dear GCST,

I'm recently curious about how model process like emission, BL mixing, chemistry, dry deposition, wet deposition affect the concentration of PM2.5 simulated by GEOS-Chem.

Wondering if any version of GEOS-Chem support the diagnostic that describe the concentration difference of PM2.5 before and after a certain model process, for instance, emission, BL mixing, chemistry, dry deposition, wet deposition.

I used to find out in the source code of GC classic v12, the implementation of emission, BL mixing and dry deposition on species concentration are tangled with each other. Not sure if there are any updates in a more recent version.

Thanks,
Yanshun

**Comment by yantosca** [comment]
Thanks for writing @YanshunLi-washu.  We do have the Budget diagnostic collection which computes the change in species before and after each operation.  We don't have a PM2.5 species but you could probably add the individual species to the diagnostic and compute the difference in PM2.5 in post-processing.

**Comment by YanshunLi-washu** [comment]
Hi Bob @yantosca Thank you so much for the quick and helpful response!

I found the relative content in https://wiki.seas.harvard.edu/geos-chem/index.php/History_collections_for_budgets 
attached as below.

Curious that:
(1) Except for full, troposphere, PBL, is there the diagnostic for the surface model layer (since this is where pollution exposure occurs and received much attention from the community)? For instance, sth like BudgetChemistry**1stLayer**_?ADV?  

If this is not available, could it be doable for me to develop such diagnostic by modifying the source code? **I'm highly interested in.**

(2) About the BudgetEmisDep diagnostic, can we further separate impacts of emission and deposition?

Thanks,
Yanshun

#==============================================================================
# %%%%% THE Budget COLLECTION %%%%% 
#
# GEOS-Chem budget diagnostics defined as species kg/s in the column 
# (full, troposphere, or PBL) due to a single component (e.g. chemistry)
# (default = advected species)
#
# Available for all simulations
#==============================================================================
 Budget.template:     '%y4%m2%d2_%h2%n2z.nc4',
 Budget.format:       'CFIO',
 Budget.frequency:    00000100 000000
 Budget.duration:     00000100 000000
 Budget.mode:         'time-averaged'
 Budget.fields:       'BudgetChemistryFull_?ADV?            ', 'GIGCchem',
                      'BudgetChemistryPBL_?ADV?             ', 'GIGCchem',
                      'BudgetChemistryTrop_?ADV?            ', 'GIGCchem',
                      'BudgetEmisDepFull_?ADV?              ', 'GIGCchem',
                      'BudgetEmisDepTrop_?ADV?              ', 'GIGCchem',
                      'BudgetEmisDepPBL_?ADV?               ', 'GIGCchem',
                      'BudgetTransportFull_?ADV?            ', 'GIGCchem',
                      'BudgetTransportTrop_?ADV?            ', 'GIGCchem',
                      'BudgetTransportPBL_?ADV?             ', 'GIGCchem',
                      'BudgetMixingFull_?ADV?               ', 'GIGCchem',
                      'BudgetMixingTrop_?ADV?               ', 'GIGCchem',
                      'BudgetMixingPBL_?ADV?                ', 'GIGCchem',
                      'BudgetConvectionFull_?ADV?           ', 'GIGCchem',
                      'BudgetConvectionTrop_?ADV?           ', 'GIGCchem',
                      'BudgetConvectionPBL_?ADV?            ', 'GIGCchem',
                      'BudgetWetDepFull_?WET?               ', 'GIGCchem',
                      'BudgetWetDepTrop_?WET?               ', 'GIGCchem',
                      'BudgetWetDepPBL_?WET?                ', 'GIGCchem',

**Comment by yantosca** [comment]
Hi @YanshunLi-washu, @lizziel has developed a category that allows you compute a budget between 2 fixed levels.  You can look at this PR: https://github.com/geoschem/geos-chem/pull/2127.  This is currently in our `dev/no-diff-to-benchmark` branch but will probably go into 14.3.1.  I think you could use this by setting the budget from level1 to level1.

**Comment by yantosca** [comment]
Hi @YanshunLi-washu.  I think it would not be possible to separate emissions & drydep without doing a bit of work in mixing_mod.F90.  This is because emissions and drydep are applied in the non-local PBL mixing.  We don't have that on our radar screen yet.

**Comment by YanshunLi-washu** [comment]
Got it, thanks! @yantosca

**Comment by YanshunLi-washu** [comment]
> Hi @YanshunLi-washu, @lizziel has developed a category that allows you compute a budget between 2 fixed levels. You can look at this PR: #2127. This is currently in our `dev/no-diff-to-benchmark` branch but will probably go into 14.3.1. I think you could use this by setting the budget from level1 to level1.

I checked this thread. And noticed that Lizzie was testing for the column between level 1 to level 35.

If I want to focus on the surface level, do I only need to modify the HISTORY.rc file (not source code), for instance, change BudgetEmisDryDepLevs1to35 to **BudgetEmisDryDepLevs1to1**?

And just like to confirm, in this new development, does Levs1 refers to the surface level (1-based) or Levs0 refers to the surface level (0-based)?

@yantosca @lizziel

**Comment by YanshunLi-washu** [comment]
> Hi @YanshunLi-washu: I think if you modify the history file (`1to35` -> `1to1`) then it should work. Level 1 is the surface (1-based).

Got it, thanks!

**Comment by YanshunLi-washu** [comment]
> Hi @YanshunLi-washu, @lizziel has developed a category that allows you compute a budget between 2 fixed levels. You can look at this PR: #2127. This is currently in our `dev/no-diff-to-benchmark` branch but will probably go into 14.3.1. I think you could use this by setting the budget from level1 to level1.

Hi @yantosca Just checking is there a version of GCHP available now that supports this new feature? Thansk!

**Comment by yantosca** [comment]
Hi @YanshunLi-washu!  Yes, this is now in 14.3.1.

**Comment by YanshunLi-washu** [comment]
> Hi @YanshunLi-washu! Yes, this is now in 14.3.1.
Perfect. Thanks!

**Comment by yantosca** [comment]
Thanks @YanshunLi-washu.  I can close out this issue now.
