### ISSUE TITLE
[FEATURE REQUEST] Initialize GEOS-Chem species database from a file (e.g. JSON, YAML, XML)

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#216]
For GEOS-Chem 13.0.0 it might make sense to replace the hard-coding of several species database parameters by reading them from an input file.  We will need to see which file format makes sense: JSON, YAML, XML, or other.  YAML might make the most sense, as this will probably ensure compatibility with NASA.  But at present this is an open question.  

For now I will leave this as a feature request and we can fill in the details later.

**Comment by yantosca** [comment]
We have decided that YAML would be the best fit.

**Comment by yantosca** [comment]
GCPy now uses YAML files for the species database, benchmark categories, etc.  We can use the same species database file to initialize GEOS-Chem (with all species metadata included) for 13.0.0.

**Comment by msulprizio** [comment]
A `species_database.yml` file has been added to the `feature/SpeciesDatabase_YAML` branch. See https://github.com/geoschem/geos-chem/issues/110 for more details.

**Comment by yantosca** [comment]
As a backup if we can't get yaFyaml to work with older Gfortran versions, I am making some modifications to the existing package https://github.com/jannisteunissen/config_fortran. 

This package does most of what we want, although the input format is a little different.  Some editing on the front-end and adding of GEOS-Chem-style error trapping should allow us to read the species database (which uses simple mappings) from YAML into GEOS-Chem directly w/o having to rely on any external packages.

**Comment by yantosca** [comment]
Using a [subset of the GC species database](https://github.com/geoschem/geos-chem/files/4484036/sample_species_db.txt).  I am now able to get this output with my modified code:
```
 ### Reading species_database_test.yml
                  A3O2%Formula | CH3CH2CH2OO
                 A3O2%Fullname | Primary peroxy radical from C3H8
                     A3O2%MW_g |   75.10
                   A3O2%EmMW_g |    0.00
               A3O2%MolecRatio |    0.00
              A3O2%Is_Advected |       F
                  ACET%Formula | CH3C(O)CH3
                 ACET%Fullname | Acetone
                     ACET%MW_g |   58.08
                   ACET%EmMW_g |   12.00
               ACET%MolecRatio |    0.00
              ACET%Is_Advected |       T
                  ACTA%Formula | CH3C(O)OH
                 ACTA%Fullname | Acetic acid
                     ACTA%MW_g |   60.10
                   ACTA%EmMW_g |    0.00
               ACTA%MolecRatio |    0.00
              ACTA%Is_Advected |       T
                  AERI%Formula | I
                 AERI%Fullname | Iodine on aerosol
                     AERI%MW_g |  126.90
                   AERI%EmMW_g |    0.00
               AERI%MolecRatio |    0.00
              AERI%Is_Advected |       T
                  ALD2%Formula | CH3CHO
                 ALD2%Fullname | Acetaldehyde
                     ALD2%MW_g |   44.05
                   ALD2%EmMW_g |   12.00
               ALD2%MolecRatio |    2.00
              ALD2%Is_Advected |       T
                  ALK4%Formula | 
                 ALK4%Fullname | Lumped >= C4 Alkanes
                     ALK4%MW_g |   58.12
                   ALK4%EmMW_g |   12.00
               ALK4%MolecRatio |    4.30
              ALK4%Is_Advected |       T
                 ASOA1%Formula | 
                ASOA1%Fullname | Lumped non-volatile aerosol products of light aromatics + IVOCs
                    ASOA1%MW_g |  150.00
                  ASOA1%EmMW_g |    0.00
              ASOA1%MolecRatio |    0.00
             ASOA1%Is_Advected |       T
 ### finishing
```
zeros indicate the tags that need to be filled with missing data values.

NOTE: I only attempted to retrieve a subset of tags.  I will test the array-based tag retrieval soon.

ALSO NOTE: This is done in core Fortran.  No external libraries needed!

**Comment by yantosca** [comment]
This update is complete.  It will be added to 12.9.0 (pending the merge of the Halogen chemistry updates). The GEOS-Chem species database is now updated from the following YAML files:

- Headers/species_database.yml
- Headers/species_database_apm.yml
- Headers/species_database_tomas.yml

The *apm.yml and *.tomas.yml files are only read for APM or TOMAS microphysics simulations, respectively.

This feature request can now be closed out.
