### ISSUE TITLE
Need MERRA 2 meteorology files for 47 vertical layers instead of 72

### ISSUE THREAD

**Issue by gouravsaha1995** [geoschem/geos-chem#2160]
### Name and Institution (Required)

Name: Gourav Saha
Institution: Indian Institute of Technology, Delhi

### Confirm you have reviewed the following documentation

- [✓] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [✓] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [✓] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [✓] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Hi guys, I need the merra2 meteorology files for geos-chem forcing for 47 levels. There are 6 files for every day namely MERRA2.20160101.A1.4x5.nc4, MERRA2.20160101.A3cld.4x5.nc4, MERRA2.20160101.A3dyn.4x5.nc4, MERRA2.20160101.A3mstC.4x5.nc4, MERRA2.20160101.A3mstE.4x5.nc4, MERRA2.20160101.I3.4x5.nc4, which have 72 hybrid vertical coordinates. I need the same datasets but for 47 levels to be used for an adjoint simulation. I have a restart file for 47 levels, but because the code has been designed in a manner to process files with 72 levels, every time I try to run the adjoint simulation making changes in the CMN_SIZE file, this error shows or the other:

GEOS-CHEM ERROR: Levels dimension (   72 ) does not match LGLOB (    47)!
                                                      OR
 
READ_RESTART_FILE: Reading ./restarts/restart.merra2_4x5_47L.n2o.2016010100

Min and Max of each tracer, as read from the file:
(in volume mixing ratio units: v/v)
ERROR reading in restart file!
Wrong number of levels encountered!
STOP in CHECK_DIMENSIONS (restart_mod.f)

**Comment by yantosca** [comment]
Thanks for writing @gouravsaha1995.  You must be using a very old version of GEOS-Chem.  Versions older than 13.0.0 are no longer supported.   We would encourage you to update to the latest version of GEOS-Chem, which can read and regrid the 72L meteorology fields to 47L (if you choose to run with a 47L grid).

**Comment by gouravsaha1995** [comment]
Respected Sir @yantosca, I am using the Adjoint Model (v35k) for my research and the version of the forward model that it uses is v8-01-01 which is older than 13.0.0 as you correctly pointed out. So, according to my understanding, since this version of the adjoint that we are using is designed for the older v8-01-01, if I upgrade the forward model code only, will it not create a problem? Also, is it computationally compatible if we use another updated version of the forward model with the older 35k adjoint version?
So Sir, in summary when I try to make a change to the CMN_SIZE script under the MERR2 section and change LGLOB(LLPAR) to 72, then the MERRA2 files are read but the restart file are not and when I change it to 47, then the MERRA2 files are itself not read.

**Comment by yantosca** [comment]
Thanks for the update @gouravsaha1995.  The GEOS-Chem adjoint support is handled separately from GEOS-Chem support.  I would send an email to the geos-chem-adjoint@g.harvard.edu listserv.

**Comment by yantosca** [comment]
Closing out this issue
