### ISSUE TITLE
About the use of parallelism in GEOS-Chem

### ISSUE THREAD

**Issue by yzjiaa** [geoschem/geos-chem#2163]
### Name and Institution (Required)

Name:yzjia
Institution:China University of Geosciences, Wuhan

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stabcem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question
Hello, I am a beginner of GEO-Chem. When running GEOS-Chem, especially for the simulation of boundary conditions, the running speed is very slow, and it usually takes several months to simulate the boundary layer conditions of one year. Is there a parallel method using multiple cores at the same time to speed up the running speed? If so, where is it set? Thank you very much!

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

**Comment by yantosca** [comment]
Thanks for writing @yzjiaa.  You might not have set the proper environment variables for parallelization.  Please see the following documentation on ReadTheDocs:

- [Customize your login environment](https://geos-chem.readthedocs.io/en/latest/getting-started/login-env.html#)
- [Set environment variables for parallelization](https://geos-chem.readthedocs.io/en/latest/getting-started/login-env-parallel.html)
- [Parallelize GEOS-Chem and HEMCO source code](https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/parallel-guide.html)

**Comment by yantosca** [comment]
Closing out this issue
