### ISSUE TITLE
GEOS-CHEM ERROR:  Excessive fall velocity ERROR in UCX_mod

### ISSUE THREAD

**Issue by alexzhang-psu** [geoschem/geos-chem#2167]
Name: Alex
Institution: CARB

Dear GC team,

I'm running a 2x2.5 global simulation with GCClassic_14.3.0, but I keep encountering the following issue:
"GEOS-CHEM ERROR:  Excessive fall velocity?
STOP at  CALC_FALLVEL, UCX_mod"

I've followed the suggestion in the manual and tried to reduce the timestep to 600, 300, or even 100, but still have this issue. This issue is gone when I turned stratospheric chemistry off. But I'd like to keep stratospheric chemistry on. I set a maximum value for fall velocity of stratospheric aerosols in UCX_mod.F to avoid this error temporarily and let my simulation continue. I'm wonder if anyone could help check this issue and/or provide any suggestion for avoiding this "Excessive fall velocity" error in UCX? Thanks very much.

With regards,

**Comment by yantosca** [comment]
Thanks for writing @alexzhang-psu.  We would need to see your input and log files to make a more accurate diagnosis of what is going on.  Could you kindly attach to this issue:
- geoschem_config.yml
- GC.log (or whatever your log file is named)
- HEMCO_Config.rc

**Comment by yantosca** [comment]
Closing out this issue
