### ISSUE TITLE
Black carbon radius and density in gravitational settling of stratospheric aerosols

### ISSUE THREAD

**Issue by cbarker211** [geoschem/geos-chem#2169]
### Name and Institution (Required)

Name: Connor Barker
Institution: University College London

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

To the GC team,

I am working on adding a new aerosol species into GEOS-Chem v14.3.0, which undergoes gravitational settling in the stratosphere, and I have some queries regarding the current code. This process is handled in the settle_strat_aer subroutine in GeosCore/ucx_mod.F90, which adds gravitational settling of sulfate and hydrophilic black carbon. 

![image](https://github.com/geoschem/geos-chem/assets/51411120/58f5ab8d-5384-4464-bbed-a3f3a00ae52a)

Firstly, the code at line 927 loads the wet radius of BCPI from the WERADIUS array, which points to State_Chm%WetAeroRadi. However the index should be WERADIUS(I,J,L,2 **+NDUST** ), not WERADIUS(I,J,L,2) to account for the dust radii which occupy WERADIUS(:,:,:,1-7). Currently the code assigns the wet radius of BCPI as the dry radius of MDUST2, which I have confirmed by printing the 

Secondly, the value for RHO(IBC) on line 938 is commented to say it is taken from aerosol_mod for MSDENS(2), which loads the density from species_database.yml. However BCDEN is instead defined as “1000.e+0_fp ! density (kg/m3)” in ucx_mod.F90 at line 813, and defined differently in the species_database.yml value as 1800 kg/m3. Should the density of BCPI be instead loaded in from species_database.yml, or was the choice of 1000 kg/m3 deliberate?

Thanks,
Connor

![image](https://github.com/geoschem/geos-chem/assets/51411120/58f5ab8d-5384-4464-bbed-a3f3a00ae52a)

**Comment by yantosca** [comment]
Thanks for writing @cbarker211.  I am tagging @sdeastham who is the author of the UCX code.

**Comment by yantosca** [comment]
> Should the density of BCPI be instead loaded in from species_database.yml, or was the choice of 1000 kg/m3 deliberate?

@cbarker211: It could be that the UCX code (which pre-dates the species database) may not have been updated accordingly to get the density from the species database object.  We could fix that if this is indeed a bug.

**Comment by sdeastham** [comment]
Hi all - thanks @yantosca for the tag! I believe this is indeed a bug, and think your assessment of the source (missed during the conversion to species database and other state objects) is probably correct. I'd also say that this old code is badly in need of an update so that all aerosols other than NIT undergo settling through this approach, but that would be a bigger intervention than is called for here.

**Comment by yantosca** [comment]
Thank you @cbarker211 and @sdeastham!  I've merged the bugfix in PR #2176 into the GEOS-Chem 14.4.0 development stream, so these fixes will ship with 14.4.0.  We can close out this issue now.
