### ISSUE TITLE
Scaling factors for 3-d (xyz) emissions in HEMCO

### ISSUE THREAD

**Issue by YanshunLi-washu** [geoschem/geos-chem#2172]
Name: Yanshun Li
Institution: Washington University in St. Louis

Dear GCST,

I have two specific questions about applying diurnal scaling factors on 3-d (xyz) emissions in HEMCO.

(1) If there is a diurnal scale factor, 
```console
26 GEIA_TOD_FOSSIL 0.45/0.45/0.6/0.6/0.6/0.6/1.45/1.45/1.45/1.45/1.4/1.4/1.4/1.4/1.45/1.45/1.45/1.45/0.65/0.65/0.65/0.65/0.45/0.45 - - - xy unitless 1
```
can I apply it only to a specific vertical level in a 3-dimensional (xyz) emission inventory. For instance, the NEI inventory has up to six vertical levels for certain variables. And I'd like to apply the above diurnal scale factors to all NEI emissions in the second vertical layer, what should I do in HEMCO?

(2) Can we scale 2-d emission diurnally and vertically at the same time. For instance, I'd like to turn the 2-d CEDS CO emission into 3-d CO emission with 4 vertical layers and has unique diurnal variation for each vertical layer. On my end, I could prepare 4 different diurnal scaling factors, but I don't know how to set up them in HEMCO to the CEDS CO emission.

Would it be possible to show me some examples for realizing the above two objectives? 

Thanks,
Yanshun

**Comment by yantosca** [comment]
Hi @YanshunLi-washu.  Thanks for writing.  I'll also tag our HEMCO developers @msulprizio @jimmielin @christophkeller, who may know more specifics.

1. I'm not sure you would be able to scale e.g. the NEI emissions on the 2nd data level, as the data is regridded vertically when you read it in.  It might be easier to create new NEI files for those sectors by (1) reading them into an xArray,Dataset object, (2) Scaling the 2nd level as you like, (3) Saving the xarray dataset to a netCDF file, and (4) reading the new file into GEOS-Chem via HEMCO.  That might be the only reliable way to do what you want.

2. You can take a look at what we do for CEDS vertical scaling for the energy and industrial sectors.  But again, I think in HEMCO you can only scale the model levels, but not the data levels.  You might need to follow a similar approach as in item 1 above.
```console
#==============================================================================
# --- CEDS vertical partitioning ---
#==============================================================================
(((CEDSv2.or..or.CEDS_GBDMAPS
315 ENERGY_LEVS   $ROOT/VerticalScaleFactors/v2021-05/gc_layers.nc g_energy   2017/1/1/0 C xyz 1 1
316 INDUSTRY_LEVS $ROOT/VerticalScaleFactors/v2021-05/gc_layers.nc g_industry 2017/1/1/0 C xyz 1 1
317 SHIP_LEVS     $ROOT/VerticalScaleFactors/v2021-05/gc_layers.nc cmv_c3     2017/1/1/0 C xyz 1 1
)))CEDSv2.or.CEDS_GBDMAPS
```

**Comment by YanshunLi-washu** [comment]
Hi @yantosca Thanks for the suggestion.

**Comment by EleeLin** [comment]
Hi @yantosca I'm following your idea to generate some new emission files for monthly NEI. Taking the egu NO emission as an example, the dimension of the emission variable is (1, 4, 400, 900) for (time, lev, lat, lon). The corresponding HEMCO item is:

0 NEI11_EGU_NO         $ROOT/NEI2011/v2017-02-MM/$MM/NEI11_0.1x0.1_2011$MM_monmean_egu.nc      NO       2006-2013/1-12/1/0 C xyz kg/m2/s  NO   25/210/251/1007     1   50

in which 25, 210, 251 are the diurnal, day-of-week, yearly scaling factors and 1007 refer to the regional mask.

Now if I updated the NEI11_0.1x0.1_2011$MM_monmean_egu.nc file into (24, 4, 400, 900) for (time, lev, lat, lon), how should I change the HEMCO item? I guess I can remove 25 from the scaling factors since I have diurnal info in the source file. But how should I update the sourceTime attribute? Should I update 2006-2013/1-12/1/0 to 2006-2013/1-12/1/* or 2006-2013/1-12/1/0-23? 

Thanks!

**Comment by YanshunLi-washu** [comment]
Hi @yantosca I'm following your idea to generate some new emission files for monthly NEI. Taking the egu NO emission as an example, the dimension of the emission variable is (1, 4, 400, 900) for (time, lev, lat, lon). The corresponding HEMCO item is:

0 NEI11_EGU_NO $ROOT/NEI2011/v2017-02-MM/$MM/NEI11_0.1x0.1_2011$MM_monmean_egu.nc NO 2006-2013/1-12/1/0 C xyz kg/m2/s NO 25/210/251/1007 1 50

in which 25, 210, 251 are the diurnal, day-of-week, yearly scaling factors and 1007 refer to the regional mask.

Now if I updated the NEI11_0.1x0.1_2011$MM_monmean_egu.nc file into (24, 4, 400, 900) for (time, lev, lat, lon), how should I change the HEMCO item? I guess I can remove 25 from the scaling factors since I have diurnal info in the source file. But how should I update the sourceTime attribute? Should I update 2006-2013/1-12/1/0 to 2006-2013/1-12/1/* or 2006-2013/1-12/1/0-23?

Thanks!

**Comment by yantosca** [comment]
Hi @YanshunLi-washu, thanks for the update.  For data that is read in each hour, then `2006-2013/1-12/1/0-23` would be correct.

**Comment by YanshunLi-washu** [comment]
Thanks @yantosca But I may not only focus on the 1st day of each month, I want each day in a month use the monthly-mean diurnal information that I put in the file (**24**, 4, 400, 900) for (**time**, lev, lat, lon)?

In this case, should 2006-2013/1-12/1/0-23 work? Or should I produce daily files myself following the format as the hourly NEI inventory?

**Comment by yantosca** [comment]
Hi @YanshunLi-washu.  In that case you can use: `2006-2013/1-12/1-31/0-23` to apply scaling each hour of each day.

**Comment by YanshunLi-washu** [comment]
@yantosca Got it thanks! Curious about how HEMCO matches 0-23 in the sourceTime attribute with hourly dimension in my monthly source file (**24**, 4, 400, 900) for (**time**, lev, lat, lon)?

**Comment by yantosca** [comment]
Closing out this issue
