### ISSUE TITLE
GEOS-Chem .netcdf to .bpch conversion methods

### ISSUE THREAD

**Issue by gouravsaha1995** [geoschem/geos-chem#2174]
Name: Gourav Saha
Institution: IIT Delhi

### Confirm you have reviewed the following documentation

- [✓] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [✓] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [✓] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [✓] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question
Can you please provide me options on how to convert .nc files to .bpch format?

**Comment by yantosca** [comment]
Thanks for writing @gouravsaha1995.  We don't have any methods to convert from netCDF to bpch, as bpch is now unsupported in GEOS-Chem.

**Comment by yantosca** [comment]
Closing out this issue
