### ISSUE TITLE
File corruption of meteorological data.

### ISSUE THREAD

**Issue by PowderL** [geoschem/geos-chem#2179]
### Name and Institution (Required)

Name: Tao Li
Institution: Tsinghua University

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question
When I ran a simulation using **geoschem**, I got an error saying that "cannot open the meteorological file with the name of **MERRA2.20230527.A1.4x5.nc4**". I checked the file on the server and found that this file is zero in size. I think this file is corrupted. I paste a screenshot of this file on the server below. 
![3](https://github.com/geoschem/geos-chem/assets/53364428/2b502c97-1461-474e-bbd8-c882f735aae9)

**Comment by yidant** [comment]
Thanks @PowderL for pointing this out! This issue is now resolved.

**Comment by PowderL** [comment]
I found two other meteorological data files with the same kind of issue. I paste their links in the following:
http://geoschemdata.wustl.edu/ExtData/GEOS_4x5/MERRA2/2023/07/MERRA2.20230702.A3mstC.4x5.nc4
http://geoschemdata.wustl.edu/ExtData/GEOS_4x5/MERRA2/2023/09/MERRA2.20230901.A3cld.4x5.nc4

**Comment by PowderL** [comment]
By the way, I want to know if it is possible for the users to generate the meteorological files for **GEOS-Chem** by themselves? Are there some useful tools such as Python packages to convert the MRRRA2 meteorological files to the input of **GEOS-Chem**?

**Comment by yidant** [comment]
Hi! Those two files are resolved. 

> I found two other meteorological data files with the same kind of issue. I paste their links in the following: http://geoschemdata.wustl.edu/ExtData/GEOS_4x5/MERRA2/2023/07/MERRA2.20230702.A3mstC.4x5.nc4 http://geoschemdata.wustl.edu/ExtData/GEOS_4x5/MERRA2/2023/09/MERRA2.20230901.A3cld.4x5.nc4

**Comment by PowderL** [comment]
Thanks for your reply @yidant @msulprizio. All issues have been resolved. 
Thanks!

**Comment by msulprizio** [comment]
Great! I will close out this issue.
