### ISSUE TITLE
State_Diag reading issue

### ISSUE THREAD

**Issue by yutian8888** [geoschem/geos-chem#2180]
### Name and Institution (Required)

Name: Yu Tian
Institution: Rutgers University

### Confirm you have reviewed the following documentation

- [ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question
Our school is transitioning to a new server, and we're required to migrate the contents from the current directory to a new location. I successfully ran Geos-Chem at the former directory, and after moving the entire Geos-Chem directory to another location and compiling it successfully, I encountered an error. 
![image](https://github.com/geoschem/geos-chem/assets/147092225/e3802f78-ee93-40ff-9f17-44dd4c72fe7b)
![image](https://github.com/geoschem/geos-chem/assets/147092225/55fbb4ae-88c0-450d-8a18-e48883678992)
The error is unusual as it stops at a specific line without any further error messages. Despite several attempts, the outcome remains the same. The allocated space for the execution is identical to what it was previously. Does anyone have any suggestions on how to address this issue?

**Comment by yantosca** [comment]
Thanks for writing @yutian8888.  Would you be able to post the entire run log to this issue?  We would need more context in order to provide a suggestion.

**Comment by yutian8888** [comment]
Dear @yantosca, thanks for replying. Here are the log and configure files.
[GC.2023.01.01.log.txt](https://github.com/geoschem/geos-chem/files/14529963/GC.2023.01.01.log.txt)
[geoschem_config.yml.txt](https://github.com/geoschem/geos-chem/files/14529964/geoschem_config.yml.txt)
[HEMCO_Config.rc.gmao_metfields.txt](https://github.com/geoschem/geos-chem/files/14529965/HEMCO_Config.rc.gmao_metfields.txt)
[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/14529966/HEMCO_Config.rc.txt)
[HISTORY.rc.txt](https://github.com/geoschem/geos-chem/files/14529967/HISTORY.rc.txt)

**Comment by yantosca** [comment]
Thanks for the files @yutian8888.  I noticed that your `HISTORY.rc` file is writing out to the restart collection:
```console
#==============================================================================
# %%%%% THE Restart COLLECTION %%%%%
#
# GEOS-Chem restart file fields
#
# Available for all simulations
#==============================================================================
  Restart.filename:           './Restarts/GEOSChem.Restart.%y4%m2%d2_%h2%n2z.nc4',
  Restart.frequency:          'End',
  Restart.duration:           'End',
  Restart.mode:               'instantaneous'
  Restart.fields:             'SpeciesRst_?ALL?               ',
 #                             'Chem_AeroH2OSNA                ',
 #                             'Chem_ORVCsesq                  ',
                              'Chem_H2O2AfterChem             ',
 #                             'Chem_JOH                       ',
 #                             'Chem_JNO2                      ',
                              'Chem_SO2AfterChem              ',
                              'Chem_DryDepNitrogen            ',
                              'Chem_WetDepNitrogen            ',
                              'Chem_KPPHvalue                 ',
#                              'Chem_StatePSC                  ',
                              'Met_DELPDRY                    ',
#                              'Met_BXHEIGHT                   ',
#                              'Met_TropLev                    ',
::
```
but it is reading 
```console
#==============================================================================
# --- GEOS-Chem restart file ---
#==============================================================================
(((GC_RESTART
* SPC_           ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 SpeciesRst_?ALL?    $YYYY/$MM/$DD/$HH EFYO xyz 1 * - 1 1
* DELPDRY        ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 Met_DELPDRY         $YYYY/$MM/$DD/$HH EY   xyz 1 * - 1 1
* KPP_HVALUE     ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 Chem_KPPHvalue      $YYYY/$MM/$DD/$HH EY   xyz 1 * - 1 1
* WETDEP_N       ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 Chem_WetDepNitrogen $YYYY/$MM/$DD/$HH EY   xy  1 * - 1 1
* DRYDEP_N       ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 Chem_DryDepNitrogen $YYYY/$MM/$DD/$HH EY   xy  1 * - 1 1
* SO2_AFTERCHEM  ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 Chem_SO2AfterChem   $YYYY/$MM/$DD/$HH EY   xyz 1 * - 1 1
* H2O2_AFTERCHEM ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 Chem_H2O2AfterChem  $YYYY/$MM/$DD/$HH EY   xyz 1 * - 1 1
* AEROH2O_SNA    ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 Chem_AeroH2OSNA     $YYYY/$MM/$DD/$HH EY   xyz 1 * - 1 1
* ORVCSESQ       ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 Chem_ORVCSESQ       $YYYY/$MM/$DD/$HH EY   xyz 1 * - 1 1
* JOH            ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 Chem_JOH            $YYYY/$MM/$DD/$HH EY   xy  1 * - 1 1
* JNO2           ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 Chem_JNO2           $YYYY/$MM/$DD/$HH EY   xy  1 * - 1 1
* STATE_PSC      ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 Chem_StatePSC       $YYYY/$MM/$DD/$HH EY   xyz count * - 1 1
)))GC_RESTART
```
There are some fields that are commented out in the HISTORY.rc but are not commented out in the HEMCO_Config.rc (e.g. the `Chem_AeroH2OSNA`).  I wonder if this is the source of the error, i.e. it's trying to read something not in the file.

**Comment by yutian8888** [comment]
> Thanks for the files @yutian8888. I noticed that your `HISTORY.rc` file is writing out to the restart collection:
> 
> ```
> #==============================================================================
> # %%%%% THE Restart COLLECTION %%%%%
> #
> # GEOS-Chem restart file fields
> #
> # Available for all simulations
> #==============================================================================
>   Restart.filename:           './Restarts/GEOSChem.Restart.%y4%m2%d2_%h2%n2z.nc4',
>   Restart.frequency:          'End',
>   Restart.duration:           'End',
>   Restart.mode:               'instantaneous'
>   Restart.fields:             'SpeciesRst_?ALL?               ',
>  #                             'Chem_AeroH2OSNA                ',
>  #                             'Chem_ORVCsesq                  ',
>                               'Chem_H2O2AfterChem             ',
>  #                             'Chem_JOH                       ',
>  #                             'Chem_JNO2                      ',
>                               'Chem_SO2AfterChem              ',
>                               'Chem_DryDepNitrogen            ',
>                               'Chem_WetDepNitrogen            ',
>                               'Chem_KPPHvalue                 ',
> #                              'Chem_StatePSC                  ',
>                               'Met_DELPDRY                    ',
> #                              'Met_BXHEIGHT                   ',
> #                              'Met_TropLev                    ',
> ::
> ```
> 
> but it is reading
> 
> ```
> #==============================================================================
> # --- GEOS-Chem restart file ---
> #==============================================================================
> (((GC_RESTART
> * SPC_           ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 SpeciesRst_?ALL?    $YYYY/$MM/$DD/$HH EFYO xyz 1 * - 1 1
> * DELPDRY        ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 Met_DELPDRY         $YYYY/$MM/$DD/$HH EY   xyz 1 * - 1 1
> * KPP_HVALUE     ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 Chem_KPPHvalue      $YYYY/$MM/$DD/$HH EY   xyz 1 * - 1 1
> * WETDEP_N       ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 Chem_WetDepNitrogen $YYYY/$MM/$DD/$HH EY   xy  1 * - 1 1
> * DRYDEP_N       ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 Chem_DryDepNitrogen $YYYY/$MM/$DD/$HH EY   xy  1 * - 1 1
> * SO2_AFTERCHEM  ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 Chem_SO2AfterChem   $YYYY/$MM/$DD/$HH EY   xyz 1 * - 1 1
> * H2O2_AFTERCHEM ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 Chem_H2O2AfterChem  $YYYY/$MM/$DD/$HH EY   xyz 1 * - 1 1
> * AEROH2O_SNA    ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 Chem_AeroH2OSNA     $YYYY/$MM/$DD/$HH EY   xyz 1 * - 1 1
> * ORVCSESQ       ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 Chem_ORVCSESQ       $YYYY/$MM/$DD/$HH EY   xyz 1 * - 1 1
> * JOH            ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 Chem_JOH            $YYYY/$MM/$DD/$HH EY   xy  1 * - 1 1
> * JNO2           ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 Chem_JNO2           $YYYY/$MM/$DD/$HH EY   xy  1 * - 1 1
> * STATE_PSC      ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 Chem_StatePSC       $YYYY/$MM/$DD/$HH EY   xyz count * - 1 1
> )))GC_RESTART
> ```
> 
> There are some fields that are commented out in the HISTORY.rc but are not commented out in the HEMCO_Config.rc (e.g. the `Chem_AeroH2OSNA`). I wonder if this is the source of the error, i.e. it's trying to read something not in the file.


Hi @yantosca, thanks for replying. It's strange that I set this up in the old directory, and it worked perfectly. 

I'm now trying to install a new GC-14.1.1 in the new directory. I downloaded the source from https://github.com/geoschem/GCClassic/releases. 
But when I unzip it, it seems that some files are missing, as shown in the image. 
![image](https://github.com/geoschem/geos-chem/assets/147092225/fd82bd7c-2f4e-424c-b73a-e0c9b1d33325)

I copied these files from the old path, but then I get an error when I use the git branch command. Could you please help to see what should I do?
![image](https://github.com/geoschem/geos-chem/assets/147092225/a34a5632-fdaa-432d-9778-c42f0d4cef94)

**Comment by yutian8888** [comment]
> Thanks for the files @yutian8888. I noticed that your `HISTORY.rc` file is writing out to the restart collection:
> 
> ```
> #==============================================================================
> # %%%%% THE Restart COLLECTION %%%%%
> #
> # GEOS-Chem restart file fields
> #
> # Available for all simulations
> #==============================================================================
>   Restart.filename:           './Restarts/GEOSChem.Restart.%y4%m2%d2_%h2%n2z.nc4',
>   Restart.frequency:          'End',
>   Restart.duration:           'End',
>   Restart.mode:               'instantaneous'
>   Restart.fields:             'SpeciesRst_?ALL?               ',
>  #                             'Chem_AeroH2OSNA                ',
>  #                             'Chem_ORVCsesq                  ',
>                               'Chem_H2O2AfterChem             ',
>  #                             'Chem_JOH                       ',
>  #                             'Chem_JNO2                      ',
>                               'Chem_SO2AfterChem              ',
>                               'Chem_DryDepNitrogen            ',
>                               'Chem_WetDepNitrogen            ',
>                               'Chem_KPPHvalue                 ',
> #                              'Chem_StatePSC                  ',
>                               'Met_DELPDRY                    ',
> #                              'Met_BXHEIGHT                   ',
> #                              'Met_TropLev                    ',
> ::
> ```
> 
> but it is reading
> 
> ```
> #==============================================================================
> # --- GEOS-Chem restart file ---
> #==============================================================================
> (((GC_RESTART
> * SPC_           ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 SpeciesRst_?ALL?    $YYYY/$MM/$DD/$HH EFYO xyz 1 * - 1 1
> * DELPDRY        ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 Met_DELPDRY         $YYYY/$MM/$DD/$HH EY   xyz 1 * - 1 1
> * KPP_HVALUE     ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 Chem_KPPHvalue      $YYYY/$MM/$DD/$HH EY   xyz 1 * - 1 1
> * WETDEP_N       ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 Chem_WetDepNitrogen $YYYY/$MM/$DD/$HH EY   xy  1 * - 1 1
> * DRYDEP_N       ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 Chem_DryDepNitrogen $YYYY/$MM/$DD/$HH EY   xy  1 * - 1 1
> * SO2_AFTERCHEM  ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 Chem_SO2AfterChem   $YYYY/$MM/$DD/$HH EY   xyz 1 * - 1 1
> * H2O2_AFTERCHEM ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 Chem_H2O2AfterChem  $YYYY/$MM/$DD/$HH EY   xyz 1 * - 1 1
> * AEROH2O_SNA    ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 Chem_AeroH2OSNA     $YYYY/$MM/$DD/$HH EY   xyz 1 * - 1 1
> * ORVCSESQ       ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 Chem_ORVCSESQ       $YYYY/$MM/$DD/$HH EY   xyz 1 * - 1 1
> * JOH            ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 Chem_JOH            $YYYY/$MM/$DD/$HH EY   xy  1 * - 1 1
> * JNO2           ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 Chem_JNO2           $YYYY/$MM/$DD/$HH EY   xy  1 * - 1 1
> * STATE_PSC      ./Restarts/GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 Chem_StatePSC       $YYYY/$MM/$DD/$HH EY   xyz count * - 1 1
> )))GC_RESTART
> ```
> 
> There are some fields that are commented out in the HISTORY.rc but are not commented out in the HEMCO_Config.rc (e.g. the `Chem_AeroH2OSNA`). I wonder if this is the source of the error, i.e. it's trying to read something not in the file.

Dear @yantosca, I set it up in the same way under the original path, and it ran normally. Also, in the new path, I started a simulation for the EAST ASIA region with the same settings for HISTORY.rc and HEMCO, and it runs normally as well. 
What else do you think could be the reason? Is it possible that there's an issue with the restart file? It seems like the restart file is not being read properly, but even after replacing it with a previous restart file, the problem persists.

**Comment by yantosca** [comment]
Closing out this issue
