### ISSUE TITLE
State_Diag%OHreactivity 

### ISSUE THREAD

**Issue by laura-hyesung-yang** [geoschem/geos-chem#2181]
Name: Laura Yang
Institution: Harvard University 
Model version: 14.3.0

I have a question about how `State_Diag%OHreactivity` variable defined in `src/GEOS-Chem/GeosCore/fullchem_mod.F90` is computed. Previously, I used this variable in the `plaenflight_mod.F90` to output the OH reactivity. Let's say `State_Diag%OHreactivity` is definition 1 of OH reactivity. 

The OH reactivity that I truly want is defining the loss rate of OH in `fullchem.kpp` as `LOH : OH`. Then this will tag all the reactions that have OH on the left side with LOH under `gckpp_Monitor.F90`. Next, I'd need to divide the LOH by [OH] to obtain the OH reactivity. Let's say this is definition 2 of OH reactivity. 

Can I expect the definition 1 to be the same as definition 2? Could I ask where the  `State_Diag%OHreactivity` would be computed?

**Comment by yantosca** [comment]
Thanks for writing @laura-hyesung-yang.  The OH reactivity code is written when you build the KPP mechanism with the ``KPP/python/build_mechanism.sh` script.  This calls a Python script named [OHreact_parser.py](https://github.com/geoschem/geos-chem/blob/main/KPP/OHreact_parser.py), which looks at the mechanism that is built and computes creates the proper equation for OH reactivity.

Tagging @msulprizio @christophkeller @mls3v.

**Comment by laura-hyesung-yang** [comment]
@yantosca Thank you, Bob!
