### ISSUE TITLE
file missing in washu net

### ISSUE THREAD

**Issue by zhifeng1310** [geoschem/geos-chem#2183]
### Name and Institution (Required)

Name:Zhifeng Li
Institution:BeiHang university

### Confirm you have reviewed the following documentation

- [ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question
MERRA2.20230528.A1.05x0625.AS.nc4 file in washu net is 0 kb, Is there any other document that can be substituted?
Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

**Comment by zhifeng1310** [comment]
And when I download the file, it reports error that you don't have permission to access this resource.

**Comment by yidant** [comment]
It is fixed!

**Comment by zhifeng1310** [comment]
OK, thank you for your reply, 蟹蟹！
