### ISSUE TITLE
GCC 14.3.0 Nested Simulation Timing Tests

### ISSUE THREAD

**Issue by jgeddes85** [geoschem/geos-chem#2184]
### Name and Institution (Required)

Name: Jeff Geddes
Institution: Boston University

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Hi GCST,

I've just gotten started with some 'out-of-the-box' nested simulations using GCC 14.3.0 with GEOS-FP fields at 0.25x0.3125 over North America. I have reviewed a bunch of the previous issues posted here to get a sense of what to expect for timing and how to increase the speed of the simulation. If I understand correctly based on issues with previous releases, the main recommendations for speeding up nested simulations seem to be: (1) Use cropped meteorological fields instead of the default global files; (2) Increase the number of threads; and (3) reduce vertical levels to 47. 

Attached are details from several of my 1-day timing tests. I seem to be stuck at simulating 1 model day in about 3 hours and 45 minutes of wall clock time. I get the impression this isn't too far off from what can be expected, but I'm puzzled as to why I can't seem to increase the speed further. I started using OMP_NUM_THREADS=28 and using the default global meteorological files. Then I tried comparing this with using the pre-cropped files over North America (I'm sure I switched to these, because I had to manually add the "NA" token to all the file names in the HEMCO_Config.rc.gmao_metfields file). Then I tried increasing OMP_NUM_THREADS=36 using a completely different node on our system. Somehow, all three of these simulations finished within 1-2 minutes of each other. 

Do you know if this experience makes sense? Do you think there are any settings on my shared cluster at BU that I need to investigate further? And do you have any further suggestions for speeding up the simulation? Why hasn't using the pre-cropped meteorological files led to faster simulations, as seemed to be suggested in previous release issues discussed here? 

![Time_tests](https://github.com/geoschem/geos-chem/assets/68356758/166930c3-5440-4912-bbc3-8efcfa8b140b)

Also attached is an example of one of my run scripts to see how I submit the job to our queue.

![gc_submit](https://github.com/geoschem/geos-chem/assets/68356758/b757a81e-f079-4d7b-91a1-d3fceb39fc8c)

Thanks for your help! Happy to provide any further details.

Jeff

**Comment by yantosca** [comment]
Hi @jgeddes85, thanks for doing these tests!

Question: On your system, do you have the abillity to request an entire node?  I ask this because on the Harvard Cannon cluster, if you don't take an entire node for timing tests then other jobs could potentially run on that node.  This can potentially skew timing results.  So we request the entire node even if we don't use all the cores on the node to get a reliable comparison.

Also, going from e.g. 28 to 36 cores might not yield as much of a benefit.  This is an old plot but it suffices to show the behavior that we see with OpenMP (shared-memory, aka serial) parallelization:

![Scalability_ 7-day timing runs with GEOS-Chem 12 0 0](https://github.com/geoschem/geos-chem/assets/5880296/29c1eb5d-c5f1-42d7-aee3-271aeadd249f)

The more cores you add, the more they have to talk to each other and the memory.  Therefore, the overhead increases by adding more cores.  The curve shouldn't "turn over" but will still keep tending towards an asymptote.

For the [Integrated Methane Inversion](https://imi.readthedocs.org), @msulprizio found that pre-processing the emissions with the HEMCO standalone, and then reading the pre-processed emissions into GEOS-Chem can have a big impact on the performance.  This is because less files need to be opened and less scaling/masking needs to be done.

**Comment by jgeddes85** [comment]
Hi @yantosca, 

Thanks for following up!

Good point about requesting an entire node for comparability. I'll follow up with our research computing staff and discuss the best way of doing this for a better round of timing comparisons. I'm meeting with someone on Monday. 

Thanks for sharing that plot of time vs. cores. I did recall this was the case, but couldn't remember where the curve really asymptoted (I did find the similar diagram in Seb's 2018 paper, Fig 3 here: https://gmd.copernicus.org/articles/11/2941/2018/). It seems like 20-28 cores is a sweet spot for now.

But regarding the emissions preprocessing and other I/O-related tasks, it seems to me that, at least for my nested runs above (even if the run times aren't directly comparable), making HEMCO faster won't really change the game. If I managed to reduce HEMCO timing by as much as 50% (is that realistic?), I'd go from a one-day simulation taking 3 hours 45 minutes to taking 3 hours 36 minutes. Or would this also speed up other model components (like transport and chemistry)?

[ For what it's worth, I also did another round of tests earlier using only 8 cores, where I compared using the global met files with the pre-cropped met files, and again using the pre-cropped files actually made the simulation a tiny bit longer instead of shorter. While I can see now why these tests can't be directly compared (since they may not have been on their own node), the result nevertheless still seems surprising? ]

Anyway, I'll try to share results from new timing tests on their own dedicated node, which maybe others will find helpful too. If you have any other suggestions for me to discuss with our computing staff when I meet with them on Monday, I'd welcome it.

I guess I was also just curious if anyone knew whether this kind of timing is about on par with what can be achieved on similar systems for this model version. It would be good to know how much effort I should put into trying to speed things up if it would bear fruit... or whether I'm already in the ballpark. 

Thanks as always!  

Jeff

**Comment by jgeddes85** [comment]
Just following up with additional details. I can confirm that my timing tests above were each performed on dedicated nodes. In particular, I think the comparison between the 28-core run using global meteorological files and the 28-core run using cropped NA meteorological files should be directly comparable (since they were also on the same hardware). It doesn't seem like this made a difference in run time, as suggested for previous model releases. I'm curious if others can confirm the same behavior, or if there's something idiosyncratic about my set-up that doesn't gain from this. But if there's nothing much to add, we can close this issue and hopefully my timing tests will be useful for others.

**Comment by yantosca** [comment]
Closing out this issue
