### ISSUE TITLE
Carbon model - when rate of change and advection turned off the number of molecules still changes?

### ISSUE THREAD

**Issue by cschooling** [geoschem/geos-chem#2186]
### Name and Institution (Required)

Name: Chloe Schooling
Institution: University of Edinburgh

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

I am using the carbon simulation v 14.2.2. I have been working on introducing a new species to this simulation (NOx), however I have come across something in how the number of molecules change when KPP rates (k_Trop/k_Strat) are set to zero that I'm a little confused about.

I first tested this with the NOx species I had added. I turned off NOx emissions and advection and didn't introduce any product/loss rate of NOx. With this, the number of molecules of NOx inside each grid point should not change. What I found was that the mixing ratio (SpeciesConcVV_NOx) remains constant, however the number of molecules (either calculated from the mixing ratio using air mass, or taken from  SpeciesConcMND_NOx*AIRVOL) changes. The number of molecules should be constant as there should be no loss of NOx through chemistry or transport and no gain of NOx through emissions, chemistry, transport. The fact that the mixing ratio stays constant despite changes in the mass/volume of the grid box does not make sense to me. 

I thought it may have been something that I missed when adding in this new species, so I tested this with CO and CO2. I turned off all the KPP rates (k_Trop/k_Strat = 0) and I turned off the advection and emissions for CO and CO2 in turn. However, I see the same thing that mixing ratios stay constant but the number of molecules does not.

Is there something I'm missing here? 

Thanks a lot, Chloe

**Comment by yantosca** [comment]
Thanks for writing @cschooling.  When you say you have turned off "transport", are you also including "transport" and "mixing".  PBL mixing will also change the mixing ratios, and there is also a change in airmass quantities in that step.

Also, are you archiving the diagnostics as time-averaged or instantaneous?  For this type of test I think a ~1 day run with instantaneous SpeciesConcMND archived hourly might be instructive.

**Comment by cschooling** [comment]
Thanks @yantosca - turning off PBL mixing seemed to help. The number of molecules is not completely stable but there are only very small fluctuations - would this be expected?

**Comment by yantosca** [comment]
@cschooling, how small are the fluctuations?  If they are about 5 or 6 magnitudes lower than the values themeselves, we could chalk it up to numerical noise.

**Comment by yantosca** [comment]
Closing out this issue
