### ISSUE TITLE
Missing Data for OFFLINE_BIOVOC again

### ISSUE THREAD

**Issue by JFBrewer** [geoschem/geos-chem#2188]
Name: Jared Brewer
Institution: UMN

### Confirm you have reviewed the following documentation

- [X] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [X] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

Hi GCST,

The issues with corrupted 2018 data for offline_biovocs [highlighted last summer in issue 1861](https://github.com/geoschem/geos-chem/issues/1861) seem to have reasserted themselves, on both the WashU and Harvard repositories, including on the links provided in the prior response. The files in question are:

biovoc_05.20180114.nc
biovoc_05.20180814.nc
biovoc_05.20180822.nc

As you can see on the repositories, these files are significantly smaller because they are missing a subset of hourly data.

My apologies for double-posting here - I am not sure whether the ST gets notifications when someone comments on a closed issue. If you have already seen my comment and just not had time to respond, you can just close this and respond back on 1861!

Thanks,
Jared

**Comment by yidant** [comment]
Thanks @JFBrewer ! The following files have been restored, 

biovoc_05.20180114.nc
biovoc_05.20180814.nc
biovoc_05.20180822.nc

**Comment by JFBrewer** [comment]
Thanks @yidant! This issue is now fixed on the WashU GC repository. Just for your reference - it's still wrong on the Harvard GC repository. I'm uncertain how much that matters since we're telling everyone to use the WashU repositories now, but I figured I'd let you know for completeness.

**Comment by msulprizio** [comment]
@JFBrewer I copied the corrected files over to Harvard now. Please let us know if you run into any other issues.

**Comment by jgeddes85** [comment]
FYI - I just came across what must be an additional corrupt file in the OFFLINE_BIOVOC collection from the WashU repository that killed my GEOS-Chem job. The file in question is:

/HEMCO/OFFLINE_BIOVOC/v2021-12/0.5x0.625/2018/11/biovoc_05.20181120.nc

The file's time dimension 17 instead of 24.

Jeff

**Comment by msulprizio** [comment]
Thanks for reporting @jgeddes85. Did you mean 2018/11/21? The file size of that date looks off.

<img width="1067" alt="Screenshot 2024-03-14 at 9 34 45 AM" src="https://github.com/geoschem/geos-chem/assets/4805437/590d4724-802b-4720-b9f0-342c6a94f0c0">

@yidant could you fix this file at WashU as well?

**Comment by jgeddes85** [comment]
Yes, thanks @msulprizio, that's correct. Appreciate it!

**Comment by yidant** [comment]
> Thanks for reporting @jgeddes85. Did you mean 2018/11/21? The file size of that date looks off.
> 
> <img alt="Screenshot 2024-03-14 at 9 34 45 AM" width="1067" src="https://private-user-images.githubusercontent.com/4805437/312857727-590d4724-802b-4720-b9f0-342c6a94f0c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NDExMjksIm5iZiI6MTcxMDQ0MDgyOSwicGF0aCI6Ii80ODA1NDM3LzMxMjg1NzcyNy01OTBkNDcyNC04MDJiLTQ3MjAtYjlmMC0zNDJjNmE5NGYwYzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTRUMTgyNzA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjgyMjljMWQ0MGMzNWQ5NjM0ZGQ1ZjFlOTUzNjBjZjNlZDIyNjAwM2FlZDkxNTJhZmUxNGZmMWJkM2FhODVkMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WjyiXXg00l1bQEZ9zm-3AMa8f_2g66vssvMRonNhy_I">
> @yidant could you fix this file at WashU as well?

Sure! The following file has been fixed

biovoc_05.20181121.nc

Thanks for reporting @jgeddes85  !

**Comment by msulprizio** [comment]
Thanks @yidant. The corrected file has been copied over to Harvard now too.
