### ISSUE TITLE
HEMCO_diagnostic.nc - Question regaridng MOH biogenic emission 

### ISSUE THREAD

**Issue by laura-hyesung-yang** [geoschem/geos-chem#2189]
Name: Laura Yang
Institution: Harvard University 
Model version: 14.3.0

May I ask a question regarding the `HEMCO_diagnostic.nc` file? I'm trying to see what `EmisMOH_Biogenic` looks like in this file. When I plot the June 2016 monthly HEMCO_diagnostic file `EmisMOH_Biogenic`, it shows MOH biogenic emission is 0. 
![Screenshot 2024-03-08 at 1 54 15 PM](https://github.com/geoschem/geos-chem/assets/42656706/b7754708-e7e3-423b-bd2a-c80df7be1233)

In my `HEMCO_Config.rc` file, I have offline biogenic VOC emission on. 
`    --> OFFLINE_BIOGENICVOC    :       true     # 1980-2020`

The online biogenic VOC emission is also on but to my knowledge, if the species exist in OFFLINE biogenic VOC, online MEGAN computation doesn't get used. 
`108     MEGAN                  : on    ISOP/ACET/PRPE/C2H4/ALD2/MOH/EOH/MTPA/MTPO/LIMO/SESQ/SOAP/SOAS` 

The MOH biogenic source is read from the directory shown below: 
`0 BIOGENIC_MOH       $ROOT/OFFLINE_BIOVOC/v2021-12/0.5x0.625/$YYYY/$MM/biovoc_05.$YYYY$MM$DD.nc MOH_MEGAN     1980-2022/1-12/1-31/* EFY xy kg/m2/s MOH  -  4 2`

When I checked the input file, I found that the emission is not zero for MOH (example from `biovoc_05.20160601.nc` file).  

![Screenshot 2024-03-08 at 1 52 58 PM](https://github.com/geoschem/geos-chem/assets/42656706/ddc5bb4f-38b2-4a11-b6b2-9c4436b07439)

Other biogenic species specified under `OFFLINE_BIOGENICVOC` show emission in `HEMCO_diagnostic.nc` file. I wonder why only MOH shows 0 emissions in the file. Is category 4 the correct one for biogenic sources? I'd greatly appreciate your insight on this matter. Thank you!

**Comment by yantosca** [comment]
Hi @laura-hyesung-yang, thanks for writing.  I think the issue may be that you have the wrong extension number for `EmisMOH_Biogenic` in your `HEMCO_Diagn.rc` file.  By default this should be set to 108 (extension number for MEGAN), but if you switch to use the offline emissions you will need to change that to 0 (extension number for base emissions).

**Comment by laura-hyesung-yang** [comment]
@yantosca Hi Bob! Thank you for such a prompt response. I checked `HEMCO_Diagn.rc` file and indeed `EmisMOH_Biogenic` has an extension number of 108. I will try to run the model with extension number of 0 instead and close this issue if that fixes what I see on `HEMCO_diagnostic.nc`!

**Comment by yantosca** [comment]
Thanks @laura-hyesung-yang.  Also don't forget to change the extension number to 0 in `HEMCO_Diagn.rc` for all of the other biogenic diagnostic species that you need to save out.  Ditto for the other offline emissions such as biomass, etc.

**Comment by laura-hyesung-yang** [comment]
@yantosca Actually all the other biogenic species except for MOH have an extension number of 0 in `HEMCO_Diagn.rc`. It makes sense why I only had 0 emissions for `EmisMOH_Biogenic` in the `HEMCO_diagnostic.nc` file!
