### ISSUE TITLE
[QUESTION] simulation of global PM2.5 concentration

### ISSUE THREAD

**Issue by lyx035** [geoschem/geos-chem#2191]
### Name and Institution (Required)

Name: Yuxuan Li
Institution: Beijing Normal University

### Description of your issue or question
I used GEOS-Chem on AWS to simulate global PM2.5 concentrations (13.4.1, full chem, MERRA-2, standard, one hour). But I didn’t find the results of PM2.5 concentration in the output file GEOSChem.SpeciesConc.20170101_0000z.nc4. What changes should I make to get the global PM2.5 concentrations? [variables.xlsx](https://github.com/geoschem/geos-chem/files/14550109/variables.xlsx) attached is the output variables with “SpeciesConcVV_?ALL?” and “SpeciesConcVV_?AER?” in the HISTORY.rc. 
I noticed that PM25 is removed in 12.7.0, is that means I need to calculate the PM2.5 concentration with the formula mentioned in https://wiki.seas.harvard.edu/geos-chem/index.php/Particulate_matter_in_GEOS-Chem#PM2.5_definition?
<img width="924" alt="image" src="https://github.com/geoschem/geos-chem/assets/156439901/78281b97-2ab3-4fb4-95ec-cf1ff53229c1">
And if I can get the PM2.5 concentrations directly from the output, another question is that I just need the PM2.5 concentration, but there are too many species in the output file. Can I just get PM2.5 concentration data and not other species? I think it may also help to speed up the simulation?
Thanks!
[variables.xlsx](https://github.com/geoschem/geos-chem/files/14550109/variables.xlsx)
[HISTORY.txt](https://github.com/geoschem/geos-chem/files/14550114/HISTORY.txt)

**Comment by yantosca** [comment]
Thanks for writing @lyx035.  We converted the old bpch diagnostics to netCDF starting in version 12.7.0.  We do have the equivalent diagnostic `PM25` as part of the `AerosolMass` history collection.  See:

http://wiki.geos-chem.org/History_collections_for_aerosols#The_AerosolMass_collection

**Comment by lyx035** [comment]
Hi @yantosca 
Thanks for your quick reply! I have gone through the wiki page and now I know what to do. Then I will close the issue.
