### ISSUE TITLE
OFFLINE_SEASALT emissions file format issue in 11-12 2019

### ISSUE THREAD

**Issue by eamarais** [geoschem/geos-chem#2197]
### Name and Institution (Required)

Name: Eloise Marais
Institution: UCL

### Confirm you have reviewed the following documentation

- [ Y] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ Y] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ Y] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ Y] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Issue with the OFFLINE_SEASALT files in ExtData folder http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_SEASALT/v2019-01/. I'm using version 13.0.2 of the model, but I see that this folder is still used in the most recent GEOS-Chem Classic version, so seemed worth reporting this issue.

The files in 11-12 2019 (http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/11/ and http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/12/) are double the size of the files in the other months I've looked at (all other months in 2019 and 01/2020) and the names of the variables are different, so I get the following error message "HEMCO ERROR: Cannot find field SEASALT_SALA. Please check variable name in the config. file". HEMCO is looking for variables "SALA_TOTAL" and "SALC_TOTAL", but the variable names in the files for 11-12 2019 are "EmisSALA_Natural" and "EmisSALC_Natural". 

There are a few workarounds, like using the 0.5 deg OFFLINE_SEASALT files instead, but to prevent other users getting this error, would it be possible to update the files hosted on the WUSTL servers to the same format as the other months?

**Comment by wahababdul638** [comment]
We faced the same issue and then added a new line below SALC and SALA in HEMCO_Config.rc with EmisSALC and EmisSALA (or just change SALC and SALA word to EmisSALC and EmisSALA) for these month and then commented it out when simulation passed this date.
