### ISSUE TITLE
[QUESTION] GTMM restart file?

### ISSUE THREAD

**Issue by Gujing-Grace** [geoschem/geos-chem#220]
I am trying to use GTMM model in GEOS-Chem. When I coupled GTMM model with GEOS-Chem model, it needs a restart file named GTM.toHg.2008010100. This restart file isn't in the rundir. Where can I download it?

**Comment by yantosca** [comment]
Thanks for writing.  The GTMM model is not currently supported in the standard GEOS-Chem 12.  It was used in earlier versions of GEOS-Chem, but then GTMM was not brought up to date with the code newest updates like HEMCO and the netCDF diagnostics.  Also, the GTMM restart file was in binary punch format, which is being phased out of GEOS-Chem in favor of netCDF file format.

I would recommend contacting Colin Thackray (@cpthackray), who has been doing some work on making GTMM compatible with GEOS-Chem 12.  Perhaps he can share with you a development code that would let you run GTMM.

**Comment by Gujing-Grace** [comment]
Thanks for your replay. I have contacted Colin’s team member and they told me that their work hadn’t been finished. Because of this, I chose to use GEOSchem Version9. I have ran the GTMM successfully and want to couple it to GEOS-Chem. The only thing I need is the restarfile named GTM.toHg.2008010100 which is not provided in the run floder of V9. To me, the bpch file is enough. Could you please tell me how to get it?


| |
顾静
邮箱：13913897784@163.com
|

签名由 网易邮箱大师 定制

On 02/10/2020 23:52, Bob Yantosca wrote:

Thanks for writing. The GTMM model is not currently supported in the standard GEOS-Chem 12. It was used in earlier versions of GEOS-Chem, but then GTMM was not brought up to date with the code newest updates like HEMCO and the netCDF diagnostics. Also, the GTMM restart file was in binary punch format, which is being phased out of GEOS-Chem in favor of netCDF file format.

I would recommend contacting Colin Thackray (@cpthackray), who has been doing some work on making GTMM compatible with GEOS-Chem 12. Perhaps he can share with you a development code that would let you run GTMM.

**Comment by yantosca** [comment]
GEOS-Chem v9 is no longer supported, so the GCST doesn't have a bpch restart file for GTMM.  The Hg simulations are maintained by the GEOS-Chem user community, so the GCST looks to the Hg and POPs working group to coordinate code maintenance efforts.

You might ask if anyone in the [Hg and POPs Working Group](http://wiki.seas.harvard.edu/geos-chem/index.php/Hg_and_POPs_Working_Group) would know how to obtain that.  My guess is that not too many people have been using that simulation recently with v9.

**Comment by yantosca** [comment]
I am going to close out this issue as there has not been recent activity.  Please feel free to reopen.
