### ISSUE TITLE
MERRA2 data missing  in 20231202

### ISSUE THREAD

**Issue by jjp1987** [geoschem/geos-chem#2201]
### Name and Institution (Required)

Name: The merra2 data MERRA2.20231202.I3.05x0625.nc4 is missing in http://geoschemdata.wustl.edu/ExtData/GEOS_0.5x0.625/MERRA2/2023/12/MERRA2.20231202.I3.05x0625.nc4
Institution:

### Confirm you have reviewed the following documentation

- [ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

**Comment by yidant** [comment]
Thanks for reporting @jjp1987 ! The following file has been fixed

MERRA2.20231202.I3.05x0625.nc4

**Comment by jjp1987** [comment]
Thanks for your upload. But, when i run the geoschem sim experiment, i get the errors :

HEMCO ERROR: Cannot find field with valid time stamp in /public/home/users/sem                       
 c1/guql/Build_GEOS/ExtData/GEOS_0.5x0.625/MERRA2/2023/12/MERRA2.20231202.I3.05x                                                                                                                                    
 0625.nc4 - Cannot get field PS_NEXTDAY. Please check file name and time (incl.                      
 time range flag) in the config. file    

And the variable time, lev, lat  and lon in MERRA2.20231202.I3.05x0625.nc4 my be wrong, please check it. thanks!

**Comment by msulprizio** [comment]
Hi @jjp1987. Could you check the netCDF file on your end by doing `ncdump MERRA2.20231202.I3.05x
0625.nc4`? If it returns an error then your file may be corrupted and you should try downloading it again.

If you are still getting the error, please set `Verbose: true` in HEMCO_Config.rc. That will provide additional information about the file that is being read to help diagnose the error. If you need help interpreting the log output, please upload the log file here.

**Comment by yantosca** [comment]
@jjp1987, have you been able to resolve this issue?  If so we can close this out.

**Comment by yantosca** [comment]
Closing out this issue
