### ISSUE TITLE
Likely bug in heterogeneous chemistry on stratospheric aerosol

### ISSUE THREAD

**Issue by cdholmes** [geoschem/geos-chem#2204]
### Name and Institution (Required)

Name: Chris Holmes
Institution: FSU

### Description of your issue or question

In version 14.3 (and likely other recent versions), rates of heterogeneous uptake of some gases (NO2, NO3, VOC) on stratospheric aerosol use a formula that I don't recognize. I suspect that this is a bug. In each of the suspect lines (below) the 1st order rate coefficient (1/s) is calculated from the product of aerosol surface area density (m2/m3) and gamma (unitless). This doesn't make sense physically or dimensionally.

NO2 uptake:
https://github.com/geoschem/geos-chem/blob/b288af1563a9a49a154a93bdd0f88be1f58f3f2f/KPP/fullchem/fullchem_RateLawFuncs.F90#L2975

NO3 uptake:
https://github.com/geoschem/geos-chem/blob/b288af1563a9a49a154a93bdd0f88be1f58f3f2f/KPP/fullchem/fullchem_RateLawFuncs.F90#L3053

VOC uptake:
https://github.com/geoschem/geos-chem/blob/b288af1563a9a49a154a93bdd0f88be1f58f3f2f/KPP/fullchem/fullchem_RateLawFuncs.F90#L3454

As I don't know who contributed these lines, could @sdeastham or @barronh perhaps confirm that this is a bug?

(Note that the other uptake reactions on stratospheric aerosol using the `KHETI_SLA` variable do not have a problem, because `KHETI_SLA` is not the same as gamma. `KHETI_SLA` includes gamma time molecular speed divided by 4, which is done in another module. I suspect confusion about the meaning and units of `KHETI_SLA` led to the bug for NO2, NO3, VOC.)

### Proposed solution

The solution is easy: Use the `Ars_L1k` function, as done for most other heterogeneous reactions.

**Comment by barronh** [comment]
@sdeastham - do you know?

**Comment by cdholmes** [comment]
@yantosca, Yes, I think this is an old bug. The 2021 changes made the code clearer, hence easier to notice the bug. Now that I know what to look for, I see that see that the bug goes back to at least version 12.9 and probably earlier.

**Comment by yantosca** [comment]
@cdholmes: Would you be able to make a PR with the fix?  We can try to get this into 14.4.0.

**Comment by cdholmes** [comment]
Fixed via PR #2205. As noted there, I contacted the Strat WG Chairs to let them know about this.

**Comment by sdeastham** [comment]
I think @cdholmes is correct, and that the bug crept in when we went to flexchem - so it's an old one! Back in v10, the N==13 case (i.e. stratospheric aerosol) was always paired with the use of a factor which included c-bar. After the move to flexchem, there are a few cases - het uptake of NO2, NO3, and VOC - where that doesn't take place properly. It'll be interesting to see the magnitude of the effect (hopefully small..).

**Comment by yantosca** [comment]
@cdholmes @sdeastham: All integration tests passed on this PR.  With your blessing, we can merge it into the dev/14.4.0 branch after 14.4.0-alpha.6.

**Comment by yantosca** [comment]
@sdeastham @cdholmes @barronh: 1-month benchmarks for this fix (tagged as 14.4.0-alpha.7) are now available:
[GCC version comparison](https://gc-dashboard.org/difference?primary_key=diff-gcc-4x5-1Mon-14.4.0-alpha.6-gcc-4x5-1Mon-14.4.0-alpha.7)

**Comment by yantosca** [comment]
Thanks @cdholmes @sdeastham @barronh.   This issue is now fixed by #2205, which has now been merged into the 14.4.0 development stream.  We can now close out this issue.

**Comment by barronh** [comment]
Thanks @cdholmes @yantosca @sdeastham
