### ISSUE TITLE
[Question]how to download GEIA_NH3 data？

### ISSUE THREAD

**Issue by cugxiongjiajun** [geoschem/geos-chem#2206]
### Name and Institution (Required)

Name:jiajun xiong
Institution:CUG

### Confirm you have reviewed the following documentation

- [√ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ √] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ √] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ √] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

I am using GEOS-Chem Adjoint, but I have been missing GEIA_NH3, and I can't find the relevant download address on the GEIA official website. Would you like to know how to download the data of GEIA_NH3?

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

**Comment by cugxiongjiajun** [comment]
I have solved it.And I think this issue can be closed.

**Comment by qxx77** [comment]
Hello! I am also a GEOS-Chem Adjoint user. Could you please tell me how to download the GEIA_NH3 data?
