### ISSUE TITLE
Some issues with adding regional emission inventories

### ISSUE THREAD

**Issue by cugxiongjiajun** [geoschem/geos-chem#2209]
### Name and Institution (Required)

Name:jiajun xiong
Institution:CUG

### Confirm you have reviewed the following documentation

- [ √] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ √] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ √] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ √] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question
Hello,I am trying to add the MEIC list to GEOS-Chem. An error is reported when I./gcclassic.

**### !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In Ncrd_1d_R8 #2:  NetCDF: Index exceeds dimension bound
     65536         3

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!**

I set the latitude and longitude according to #1596, but it doesn't work. Whether the sourceTime setting is incorrect, or the input file is incorrect.
This input file is MEIC data for July 2012.

![Snipaste_2024-03-21_17-03-32](https://github.com/geoschem/geos-chem/assets/148510245/c8922c64-a10c-4a49-bfb7-386427e18586)

![Snipaste_2024-03-21_17-04-11](https://github.com/geoschem/geos-chem/assets/148510245/929ed8db-7bdf-4a84-ae06-60bfb82a8208)

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

**Comment by yantosca** [comment]
Thanks for writing @cugxiongjiajun.  Your file lacks several required netCDF attributes, and that is probably why HEMCO cannot read it.  Also you will need to add a `time` variable (even if there is only one time in the file).  Please see the following ReadTheDocs pages for more information:

- [Work with netCDF files](https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/netcdf-guide.html)
- [Prepare COARDS-compliant netCDF files](https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/coards-guide.html)

**Comment by cugxiongjiajun** [comment]
Thank you for your reply, I already know how to deal with this problem, this problem can be closed now.

**Comment by yantosca** [comment]
Thanks @cugxiongjiajun!
