### ISSUE TITLE
[QUESTION] Questions about scaling the NOAA_GMD_CH4 quantity

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#221]
I am posting this question on behalf of @cdholmes:

>I have two related HEMCO questions. 
>
>I would like to apply a constant global scaling factor to the CH4 surface concentrations, multiplying them by 1.05. I thought that I could do this by adding a scale factor in HEMCO, but this is not working, according to the restart output. I then wanted to add the surface CH4 concentration to the HEMCO_Diagn.rc output, but I can’t get that to work either. 
>
>I would appreciate any help that you could provide. I have pasted my attempt below. I am using GEOS-Chem 12.6.1, Standard chemistry, MERRA2 4x5. 
>
>
>1.	In HEMCO_Config.rc, I added a new scale ID to the NOAA_GMD_CH4 variable. I added the scale factor 700.  The rest of the line is unchanged.
```
#==============================================================================
# --- NOAA GMD monthly mean surface CH4 ---
#==============================================================================
* NOAA_GMD_CH4 $ROOT/NOAA_GMD/v2018-01/monthly.gridded.surface.methane.1979-2020.1x1.nc SFC_CH4 1979-2020/1-12/1/0 C xy ppbv * 700 1 1
```
>
>2.	I added a matching scale factor 700 to the scale factor section of HEMCO_Configr.rc  This is similar to the other scale factor lines.
```
#==============================================================================
# Scale factor for sensitivity tests
#==============================================================================
700 SCALE1p05 1.05 - - - xy 1 1
```
>3.	In HEMCO_Diagn.rc, I added a line to write NOAA_GMD_CH4 into the HEMCO diagnostic file. This didn’t work to add the output to the nc file and also didn’t generate an error or output in HEMCO.log.
```
# Name             Spec   ExtNr  Cat Hier Dim OutUnit       LongName
NOAA_GMD_CH4       *      -1     -1  -1    2  ppbv          CH4_surface_boundary_condition
```

**Comment by yantosca** [comment]
Hi Chris.  Thanks for writing.  I think ;HEMCO might only apply scale factors to emission fields, and not the non-emission fields such as NOAA_GMD_CH4.  (@msulprizio please correct me if I"m wrong.)

What you can do is to call HCO_GetPtr to get a pointer to the NOAA_GMD_CH4 file in the code and then manually scale that by 1.05.  I think that may be the only way to proceed.

**Comment by christophkeller** [comment]
As Bob pointed out, field NOAA_GMD_CH4 is read using subroutine HCO_GetPtr (in `set_global_ch4_mod.F90). This routine ignores any scale factors / masking attached to the field and simply returns a pointer that points to the base field on file. Subroutine HCO_EvalFld would return the fully evaluated field, i.e., the base field with all scale factors / masks applied to it. This would look something like this:

> USE HCO_CALC_MOD, ONLY : HCO_EvalFld
> ...
> HCO_EvalFld( am_I_Root, HcoState, 'NOAA_GMD_CH4', SFC_CH4, RC )

In this case, SFC_CH4 needs to be a fully allocated (2D) array instead of a pointer, and HCO_EvalFld needs to be called on every time step (not just on FIRST).

**Comment by yantosca** [comment]
Thanks Christoph for the tip!  Yes, I should have remembered Hco_EvalFld.

**Comment by cdholmes** [comment]
Thank you both.

**Comment by lizziel** [comment]
Related to this issue, we now have a general issue on this top of HCO_GetPtr versus HCO_EvalFld. See new issue https://github.com/geoschem/geos-chem/issues/232 to track progress towards replacing HCO_GetPtr with HCO_EvalFld in the model. This will avoid future issues where masking and scaling are configured in HEMCO_Config.rc but are not applied in the model.
