### ISSUE TITLE
Add ProdLoss diagnostic to aciduptake

### ISSUE THREAD

**Issue by IshirDutta** [geoschem/geos-chem#2210]
Name: Ishir Dutta
Institution: MIT

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### 
Description of your issue or question

Hi folks,

I've been running v14.3.0 of GEOS-Chem Classic, with a handful of prodloss diagnostics added to my version of custom.kpp (I've also added some dummy variables to track reactions in custom.eqn). Now I've been trying to add some of those same modifications to aciduptake.kpp with one addition of PNITD, but I'm not able to build with `./build_mechanism.sh aciduptake` (error attached below).

[aciduptake_build.txt](https://github.com/geoschem/geos-chem/files/14706178/aciduptake_build.txt)

I also noticed that setting up a fresh run directory with aciduptake turned on in `./createRunDir.sh` and compiling as normal (without any variation of the `-DMECH=custom` flag) shows 'fullchem' as the selected KPP version, but allows the aciduptake simulation to run as intended during setup.

Any suggestions are welcome! 
Thanks!

[aciduptake_kpp.txt](https://github.com/geoschem/geos-chem/files/14706151/aciduptake_kpp.txt)
[custom_kpp.txt](https://github.com/geoschem/geos-chem/files/14706152/custom_kpp.txt)
![buildinfo](https://github.com/geoschem/geos-chem/assets/33105692/df0701dc-f486-4515-951e-e56d08ed2f99)

**Comment by yantosca** [comment]
Thanks for writing @IshirDutta.  The aciduptake KPP mechanism isn't supported (work was started on it by @msl3v) but it was never finished.  The aciduptake on dust chemistry is currently handled outside of KPP for now.    

Also the `aciduptake.kpp` file that you've attached is now out of date.  Better to start with the `custom.kpp` file and work from that.
