### ISSUE TITLE
Where can I find/recover GFED4 biomass burning emissions prior to 2010?

### ISSUE THREAD

**Issue by herizonarivelo** [geoschem/geos-chem#2212]
Name: Herizo Narivelo
Institution: Laboratoire d'Aérologie- Université Toulouse III Paul Sabatier (France)

### Confirm you have reviewed the following documentation

- [ x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

Dear Geos-chem community, 

I am using GCHP v14.2.2 to run a multi-year simulation.  In my project, I am going to use GFED4 biomass-burning emissions in my future simulation. I checked in the **$ROOT/GFED4/v2023-03/** directory that there was no emissions  before 2010 whereas in my project we're going to start simulation  before 2010. So, I would like more information on this subject. Did GFED4 emissions have monthly emission  prior to 2010? If so, where can I find monthly emissions data prior to 2010? 
I understand that if the year is not available, I can use the climatology option instead, but I would like to use the monthly emissions  instead. 

This link http://geoschemdata.wustl.edu/ExtData/HEMCO/GFED4/v2020-02/ contains data from 1997 onwards. What does this dataset represent? Knowing that GFED4 refers to the v2023-03 directory in the HEMCO_Config for Geos-Chem v14  and latest version. 

Thank you in advance for your answers and your advice! 

Kind regards,
Herizo Narivelo

**Comment by yantosca** [comment]
Thanks for your email @herizonarivelo.  We rely on outside developers to provide emissions for GEOS-Chem.  I believe the GFED data doesn't extend back past 2010.  You could use a different biomass burning option like GFAS or QFED that has availability for those years.  You can also set the time cycle flag for all of the GFED entries in `HEMCO_Config.rc` to `C`, so that it will reuse the first year of data for years prior to 2010.

**Comment by yantosca** [comment]
Thanks @herizonarivelo.  I will close out this issue.
