### ISSUE TITLE
[FEATURE REQUEST] Retire tagged CH4 simulation

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#2223]
### Name and Institution (Required)

Name: Melissa Sulprizio
Institution: Harvard

### New GEOS-Chem feature or discussion

The carbon simulation will replace the CH4, CO2, and tagCO simulations in the coming months. In preparation for this, we can retire the tagCH4 simulation option. If users want to use the tagged CH4 species (tagged by emissions sector) they should still be able to do so simply by modifying the geoschem_config.rc and HEMCO_Config.rc to include the additional tracers to the carbon simulation.

**Comment by yantosca** [comment]
We can close this issue, as the tagCH4 simulation is now retired in 14.4.0.
