### ISSUE TITLE
Transport of CO molecules based on its lifetimes

### ISSUE THREAD

**Issue by vijaykumarsagar** [geoschem/geos-chem#2229]
Name: Vijay Sagar
Institution: Indian Institute of Tropical Meteorology Pune, India
### Confirm you have reviewed the following documentation
- [x] [Contributing guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/CONTRIBUTING.html)
### New GEOS-Chem feature or discussion

Dear All, 
I want to make Geos-chem simulations for CO with a lifetime of 30 days, 40 days, 50 days, etc., by tagging CO based on its source region. I have installed the GEOS-Chem model (14.3.0), ran it for full-chemistry, and tagged CO simulation (tagCO) for July 2019.

Can you please help me in setting up the model?

**Comment by yantosca** [comment]
Thanks for writing @vijaykumarsagar.  In 14.3.0 and later we have added a new module called `GeosCore/tracer_mod.F90`, which is meant to compute the loss of passive species with a specified lifetime.  This is used in the `TransportTracers` simulation.  I would recommend that you take a look at the code there and perhaps try to modify it for your purposes.

**Comment by vijaykumarsagar** [comment]
Thanks, Bob. I have done `TransportTracers` simulation for one month. The default species are `CO_25` and `CO_50` in the output Species Concentration files. However, I need help finding where and what to change in the `GeosCore/tracer_mod.F90` file for `CO_30,` `CO_40,` `CO_60,` etc. Can you tell me what to modify in `tracer_mod.F90` or other files?

**Comment by msulprizio** [comment]
Hi @vijaykumarsagar. The properties for those species can be found and modified in: https://github.com/geoschem/geos-chem/blob/20e2402baf56c682cc04af74adb139efdb6ca000/run/shared/species_database.yml#L1004-L1025

You can add other CO_* tracers there. You will also need to add them to `geoschem_config.yml` and `HEMCO_Config.rc`.

**Comment by vijaykumarsagar** [comment]
Thanks, @msulprizio, it works perfectly for me.
I have another doubt regarding the source region of tracers. I want to see the transport `CO_100 `and `CO_150 `(which I have set in the model) from Asia to the Arctic region. However, I can see the source region can be defined using the latitude range using the `Snk_Horiz`, `lat_zone`, and `Snk_Lats `options, but the longitude range options are not given. Can you please tell me how I can set only the Asian region as a source region?

**Comment by msulprizio** [comment]
Hi @vijaykumarsagar since the CO source is obtained from HEMCO, the best option would be to apply a mask to the emission fields in `HEMCO_Config.rc`. See the [Masks section](https://hemco.readthedocs.io/en/stable/hco-ref-guide/hemco-config.html?highlight=mask#masks) of the HEMCO documentation for details.

**Comment by vijaykumarsagar** [comment]
Hi @msulprizio, thanks for the valuable suggestions.
I tried to apply a mask to the emission fields by adding the following lines in the `MASKS` and `BASE EMISSIONS` sections of the `HEMCO_Config.rc` file. But, I am getting some errors when running the model due to variable `ASIA_MASK`.

`(((CEDSv2`
`0 SRC_2D_CO_150 1.0 - - - xy molec/cm2/s CO_150 1150 1 1`
`)))CEDSv2`

`(((CEDSv2`
`1150 ASIA_MASK  $METDIR/$CNYR/01/$MET.$CNYR0101.CN.$RES.$NC                                         FRASIA           2000/1/1/0 C xy 1 1       60/0/100/40`
`)))CEDSv2`

Can you please tell me what inputs are needed to set Asia as a source region? What emissions need to be provided in the config file? Please see the attached config file for detailed information.
[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/14865522/HEMCO_Config.rc.txt)

**Comment by yantosca** [comment]
Closing out this issue
