### ISSUE TITLE
[QUESTION] Request for more GEOS-Chem restart files 

### ISSUE THREAD

**Issue by pshchien** [geoschem/geos-chem#223]
Hi all,
I am now running the GEOS-Chem v12.3.2 in different years.
I already checked the GEOS-Chem restart files and realized that there are only 2015, 2016 and 2018.

Is there any chance I can find the standard restart files for other years?  So I can shorter my spin-up times.

Sincerely,

Rong-You Chien

**Comment by yantosca** [comment]
Thanks for writing.   The folder names in GEOSCHEM_RESTARTS (v2015-09/  v2016-07/  v2018-11/) do not refer to the date of the restart files but to the date when the restart files were produced.  The v2018-11 is the most recent restart files, which includes additional species that were added into more recent versions of GEOS-Chem 12.

You can take any of those restart files and use them to spin up your simulation, as long as the spin-up period is sufficient for the type of simulation that you are doing.  For a full-chemistry simulation, a 1-year spinup should suffice.
