### ISSUE TITLE
Reading new HEMCO file every 10 minutes

### ISSUE THREAD

**Issue by cschooling** [geoschem/geos-chem#2230]
### Name and Institution (Required)

Name: Chloe Schooling
Institution: The University of Edinburgh

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

When reading emissions/chemistry into HEMCO I know it is possible to update the file read every hour, by calling a file like so:
```
* Prod_NOx    $ROOT/GCClassic_Output/14.0.0/$YYYY/updated3_GEOSChem.ProdLoss.$YYYY$MM$DD_$HH$MNz.nc4         Prod_NOx_ms     2019-2020/1-12/1-31/0-23 C xyz 1        * - 1 1
``` 

I wasn't sure if there is a way to read in an updated file every 10 minutes or more regularly?
I adjusted the code adding /0-59 to represent each minute. And I have files saved for every 10 minutes. However, this still only called a new file every hour. Is there another way I could do this? Or something I'm missing.

**Comment by yantosca** [comment]
Thanks for writing @cschooling.  I think that HEMCO isn't set up yet to read in anything shorter than an hour.

Tagging @msulprizio @christophkeller

**Comment by yantosca** [comment]
Closing out this issue
