### ISSUE TITLE
 Build required software with Spack for GEOS-Chem Classic , Encountering a tricky problem

### ISSUE THREAD

**Issue by xiaomufeng** [geoschem/geos-chem#2233]
### Name and Institution (Required)

Name:
Institution:
Beijing Normal University

### Confirm you have reviewed the following documentation

- [ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question
cmake ../CodeDir -DRUNDIR=..
<img width="1077" alt="image" src="https://github.com/geoschem/geos-chem/assets/9513284/119342fc-b3ed-4a8c-9da3-f4dbfd63d9e5">

my Spack find
<img width="1075" alt="image" src="https://github.com/geoschem/geos-chem/assets/9513284/bc9fb454-0dfc-4307-8d79-ba8e9eb85c10">

and my spack env file
<img width="1047" alt="image" src="https://github.com/geoschem/geos-chem/assets/9513284/53f2e645-b6d9-4fea-a74a-a28192a293d3">

**Comment by xiaomufeng** [comment]
In this page, the error is in the screenshot below： https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/spack-guide.html#spackguide

<img width="903" alt="image" src="https://github.com/geoschem/geos-chem/assets/9513284/deb2e423-325c-4d81-958f-b814a7034802">

404 Not Found

**Comment by xiaomufeng** [comment]
I'm sorry, according to the method you suggested, I still haven't completed the installation on my end。
Here are some of my operational procedures：
1. arch
<img width="274" alt="image" src="https://github.com/geoschem/geos-chem/assets/9513284/94d128cc-b799-465d-9ff5-bd07c2f4db72">

2. spack find
<img width="973" alt="image" src="https://github.com/geoschem/geos-chem/assets/9513284/4a6a17a3-431e-4a45-991a-7187187b0293">

3. spack install example
<img width="677" alt="image" src="https://github.com/geoschem/geos-chem/assets/9513284/24b2d428-c0c2-4fc1-b33f-88ea0e6ac1f2">

4. cmake errors
<img width="1066" alt="image" src="https://github.com/geoschem/geos-chem/assets/9513284/46a3a6c2-7268-45f7-a795-58fdf0a6f7d1">

5. mak -j  errors
<img width="1080" alt="image" src="https://github.com/geoschem/geos-chem/assets/9513284/1498e0c6-1157-486f-8182-9dfb2ebaae72">

**Comment by yantosca** [comment]
> Thanks @xiaomufeng for reporting this. The proper link to the GCClassic sample environment file in the documentation is:
> 
> * https://geos-chem.readthedocs.io/en/latest/getting-started/login-env-files-gnu.html
> 
> We'll make sure to fix that.

@xiaomufeng: Since we have released 14.4.0, the link to the GCClassic sample environment file is now present in the "stable" documentation as well: 

- https://geos-chem.readthedocs.io/en/stable/getting-started/login-env-files-gnu.html

**Comment by yantosca** [comment]
Closing out this issue
