### ISSUE TITLE
Replace ISORROPIA with HETPv1.0

### ISSUE THREAD

**Issue by lizziel** [geoschem/geos-chem#2235]
### Name and Institution (Required)

Name: Lizzie Lundgren
Institution: Harvard University

### New GEOS-Chem feature or discussion

We plan to replace ISORROPIA in the model with a newer version based on ISORROPIA called HETerogeneous vectorized or Parallel (HETP). HETPv1.0 was developed by Stefan Miller at Environment and Climate Change Canada and is described in a 2024 GMD publication (see [here](https://gmd.copernicus.org/articles/17/2197/2024/)).

We plan to include the HETP software as a separate git submodule within GEOS-Chem Classic and GCHP, alongside HEMCO, GEOS-Chem, and Cloud-J.

Tagging Aerosols WG Co-chairs @beckyalexander, @theloniuspunk, @wporter

**Comment by lizziel** [comment]
1-month full chemistry GC-Classic benchmark comparing ISORROPIA II and HETP is now posted at https://ftp.as.harvard.edu/gcgrid/geos-chem/validation/isorropia_vs_hetp/1mon_fullchem/. This uses GEOS-Chem branch dev/14.4.0 as base.

There is a significant slow-down in the HETP implementation which I am looking into. I will see if I see the same thing in GCHP.

**Comment by yantosca** [comment]
> There is a significant slow-down in the HETP implementation which I am looking into. I will see if this is the case in GCHP too.

NOTE: this was fixed in commit 2cd624fc5de315a06b7ab137f1a617d8b78250e7 by @lizziel.

**Comment by lizziel** [comment]
I spot-checked differences in APM and aerosol-only simulations and see small differences comparable to differences in full chemistry.

**Comment by lizziel** [comment]
This is now merged into 14.4.0.
