### ISSUE TITLE
Help with HEMCO emissions inconsistency between GC12 and GC13

### ISSUE THREAD

**Issue by ktravis213** [geoschem/geos-chem#2239]
### Name and Institution (Required)

Name: Katie Travis
Institution: NASA LaRC

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question
Hi support team.  I found that my implementation of KORUSv5 emissions in GC13.4.0 resulted in 10% higher emissions than in GC12.7.2.  The output from 12.7.2 for the month of May for SO2 for example is 2475 Gg in the original files, 2470 in GC12 (nearly identical so I assume this is the correct implementation), but 2713 Gg (10% higher), in GC13. The two HEMCO_Config.rc files are attached, and I do not see a difference between their implementation.  Any advice on how to debug this would be much appreciated.

[HEMCO_ConfigGC12.rc.txt](https://github.com/geoschem/geos-chem/files/14906514/HEMCO_ConfigGC12.rc.txt)
[HEMCO_ConfigGC13.rc.txt](https://github.com/geoschem/geos-chem/files/14906517/HEMCO_ConfigGC13.rc.txt)

**Comment by yantosca** [comment]
Hi @ktravis213, thanks for writing.

I did a quick diff of the HEMCO_Config.rc files.  I noticed that there are different scale factor definitions:
```diff
< 269 KORUS_BENZ       0.29            - - - xy unitless 1
< 273 KORUS_TOLU       0.75            - - - xy unitless 1
< 190 ALK3toALK4       0.93            - - - xy unitless 1
< 191 ALK4toALK4       1.16            - - - xy unitless 1
< 192 ALK5toALK4       1.86            - - - xy unitless 1
< 193 PRD2toMEK        1.5             - - - xy unitless 1
< 194 ARO2toXYLE       1.125           - - - xy unitless 1
< 195 OLEtoPRPE        1.67            - - - xy unitless 1
---
> 269 KORUS_BENZ       0.1             - - - xy unitless 1
> 273 KORUS_TOLU       0.9             - - - xy unitless 1
> 193 KORUS_C3H8       0.59            - - - xy unitless 1
> 191 KORUS_C2H2       0.41            - - - xy unitless 1
> #190 ALK3toALK4       0.93            - - - xy unitless 1
> #191 ALK4toALK4       1.16            - - - xy unitless 1
> #192 ALK5toALK4       1.86            - - - xy unitless 1
> #193 PRD2toMEK        1.5             - - - xy unitless 1
> #194 ARO2toXYLE       1.125           - - - xy unitless 1
> #195 OLEtoPRPE        1.67            - - - xy unitless 1
```
Have you tried testing both GC12 and GC13 with the same scale factors?

**Comment by ktravis213** [comment]
Thanks @yantosca.  Sorry those definitions are misleading. None of those scale factors are for SO2. I also checked CO, which also has the same 10% difference and no scale factor applied.

**Comment by msulprizio** [comment]
Hi @ktravis213. Could you run each simulation with verbose turned on in HEMCO_Config.rc? That should tell you the min/max of values read in, scale factors used, unit conversions applied, etc. Hopefully that can shed some light on the differences.

**Comment by yantosca** [comment]
@ktravis213: When you compared the emissions, were you comparing just the KORUS-AQ emissions or the total anthropogenic emissions?  There are some differences to the emissions (e.g. aircraft, etc) that might affect the total diagnostics.  You could add a line to the `HEMCO_Diagn.rc` just to save out the KORUS emissions:

```console
EmisSO2_KORUS  SO2  0  1  45  3  kg/m2/s  SO2_emission_flux_from_KORUS_AQ
```

**Comment by ktravis213** [comment]
Thanks for both those tips, I will try them.

**Comment by ktravis213** [comment]
Hi @yantosca, when I add the emissions line to HEMCO_Diagn.rc in my version 12.7.2 code, I get nothing out, but it works fine in v14.  Was this functionality available in v12?
EmisSO2_KORUS      SO2    0      45  -1   2   kg/m2/s  SO2_emission_flux_from_KORUS_AQ

**Comment by msulprizio** [comment]
Hi @ktravis213. I think you have the category and hierarchy values swapped. The entries in HEMCO_Diagn.rc should be:

```
# Name        Spec  ExtNr  Cat Hier Dim OutUnit  LongName
EmisSO2_KORUS SO2   0      1   45   2   kg/m2/s  SO2_emission_flux_from_KORUS_AQ
```

This functionality should remain unchanged between the two versions. If you're still having issues, try changing verbose and warnings to 3 to see if that returns more information about the diagnostic fields.

**Comment by yantosca** [comment]
Closing out this issue
