### ISSUE TITLE
Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation

### ISSUE THREAD

**Issue by amberzju** [geoschem/geos-chem#2241]
### Name and Institution (Required)

Name:amber
Institution:Zhejiang University

### Confirm you have reviewed the following documentation

- [ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question
In order to speed up the simulation under 2*2.5 degree globally, I changed the transport_timestep_in_s from 600 to 1800. I modified the  maximum timestep to 3600 in input_mod.F90. The simulation went well at first, however, after simulating 17 days, I got the error "Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation." Could you please help me with this problem?
![input_mod f90](https://github.com/geoschem/geos-chem/assets/166473432/72de5a34-860c-425d-a620-0978583cf53b)

![geoschem_config yml](https://github.com/geoschem/geos-chem/assets/166473432/7b701609-991e-45e4-b41a-d862e84b1f1c)
![error_info](https://github.com/geoschem/geos-chem/assets/166473432/9a90c35a-7847-4dbd-a75a-0bd06b472a01)

**Comment by yantosca** [comment]
Thanks for writing @amberzju.  The traceback from the log file shows that the error occurred at line 3093 of tpcore_fvdas_mod.F90 (which is the transport module).  That is in this block of code:

https://github.com/geoschem/geos-chem/blob/20e2402baf56c682cc04af74adb139efdb6ca000/GeosCore/tpcore_fvdas_mod.F90#L3080-L3102

It seems like there is a math error (e.g. not-a-number, infinity, underflow, etc.) happening at this line.  You could try recompiling your code with the debug options.  In your run directory, type:
```console
$ mkdir build_debug
$ cd build_debug
$ cmake ../CodeDir -DCMAKE_BUILD_TYPE=Debug -DRUNDIR=..
$ make -j
$ make install
```
and then run again and see if that catches the error.  If you have a restart file on the day the error happened then you can just start from that point.

Also you can use the gdb debugger to see if it'll tell you more information (but this needs to be used with an executable that was built in debug mode such as described above).  You can type:
```console
$ gdb gcclassic
$ (gdb) run
```
and then see where the run fails.  Then you can use command such as:
```console
(gdb) where
(gdb) print il
(gdb) print jv
(gdb) print qquwk(il,jv)
```
You might see something there that indicates the error.  

Also see our supplemental guides on ReadTheDocs:

- https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/error-guide.html
- https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html

**Comment by yantosca** [comment]
@amberzju It also could be that with the timesteps you've selected, you are violating the Courant limit, which may be causing the math to blow up.

**Comment by amberzju** [comment]
Thanks for your reply @yantosca! It seems that with the higher wind speed and smaller grid box, the timestep should be set shoter, according to the courant number limitation equation: u Δt / Δx ≤ 1. 
Maybe in the first several days the wind speed is low, so I didn't meet the error. 
How can I speed up the GC simulation if I can not set a long timestep?
