### ISSUE TITLE
Bug in GEOS-IT processed files

### ISSUE THREAD

**Issue by lizziel** [geoschem/geos-chem#2242]
### Name and Institution (Required)

Name: Lizzie Lundgren
Institution: Harvard University

### New GEOS-Chem feature or discussion

@yuanjianz (WashU) discovered a bug in the GEOS-IT processed files where QI and QL are all zero. GEOS-IT is currently released as beta for validation. @yidant will reprocess the files to continue validation. GEOS-IT raw files, including all cubed sphere files recommended for use in GCHP, are not affected.

A fix is now merged into the main branch of the GEOS_IT processing repository. See https://github.com/geoschem/GEOS_IT/pull/2.

**Comment by yidant** [comment]
The fixed data files are now available!
