### ISSUE TITLE
Best route to run simple passive tracer simulations with GC14?

### ISSUE THREAD

**Issue by aschuh** [geoschem/geos-chem#2243]
### Name and Institution (Required)

Name: Andrew Schuh
Institution:  Colorado State University

### Confirm you have reviewed the following documentation

- [ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

I'm currently migrating from GCC12 to GCC14 and finding the transition very difficult.  I'm usually running large ensembles of passive tracer simulations (no chemistry), either as serial implementation w/ a single tracer or w/ dozens of tracers per GC run.  I've tried using a few of the likely run setups to start from (carbon run and transport run) but had complications with both.  Furthermore, the ExtData requirements seem so immense anymore it seems and I'm almost positive that I don't need 95% of that data.  Can somebody give me a heads-up for the *easiest* simulation that can draw up to, for example, just run a single passive tracer w/ emissions coming from HEMCO?  I'm committed to putting the work into getting it going, but would at least like to know I'm starting from the best spot.  Furthermore, assuming I didn't miss a configuration like this already existing, my guess is that there may be enough folks interested in this kind of run that maybe this simple "run config" could be included in future versions?

thanks,
andrew

**Comment by msulprizio** [comment]
Hi @aschuh! I recommend setting up and running a TransportTracer simulation. That simulation is already set up with several passive species. See the details here: https://wiki.seas.harvard.edu/geos-chem/index.php/TransportTracers_simulation. You should be able to simply delete the species that you don't want to use from the geoschem_config.rc file. If you want to add new species, you will need to define them in geoschem_config.rc, HEMCO_Config.rc, and species_database.yml.

That simulation also has a significantly smaller list of files needed for input. You can use the dry run option to figure out and automatically download the files that your simulation needs. See our documentation for instructions: https://geos-chem.readthedocs.io/en/stable/gcclassic-user-guide/dry-run.html.

**Comment by aschuh** [comment]
Thanks, this was one of the two I tried (carbon and transporttracers), both seemed to end w/ "issues".  That being said, I'll revisit and start from this simulation and provide better feedback on my problems in a new post.  Thanks.
