### ISSUE TITLE
Update to include recent Volcanic emissions throughout 2023

### ISSUE THREAD

**Issue by kelaar** [geoschem/geos-chem#2245]
Name: Aaron van Donkelaar
Institution: Washington University in St. Louis

Background

Current volcanic emissions in HEMCO extend throughout not include include all of 2023.

Feature Request

Extend volcanic emissions throughout 2023.

**Comment by yantosca** [comment]
We can close this issue as the PR #2246 has been merged into the GEOS-Chem 14.4.0 development stream.
