### ISSUE TITLE
GEOS-CHEM Inpit data + OPENDAP

### ISSUE THREAD

**Issue by zion0210** [geoschem/geos-chem#2247]
### Name and Institution (Required)

Name: zion0210
Institution: ASU

### Confirm you have reviewed the following documentation

- [ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

Hello!

Can I use OPENDAP to access GEOS-CHEM input data?

For example, I need to run a 0.5x0.625 nested simulation for a custom region.

I used the wustl repository and the following command:

`ncks -O -d lat,0,10. -d lon,0.,10. $unput_URL $output_file`

But it didn't work.

Are there alternatives to download data for a custom region without OPENDAP?

Best regards,
zion0210

**Comment by yantosca** [comment]
Thanks for writing @zion0210.  GEOS-Chem data is not available via OpenDAP.  There are a few ways that you can download GEOS-Chem data and they are described in the [Download input data](https://geos-chem.readthedocs.io/en/stable/gcclassic-user-guide/download-data.html) chapter of geos-chem.readthedocs.io.

**Comment by zion0210** [comment]
Hello!

Yes, of course, I read the reference documentation, but I have some questions.

For example, to run a simulation lasting 1 year with 0.5x0.625 resolution I need ~1Tb of meteodata.
My internet channel has a theoretical speed of 100Mbit/c, average speed is 30-50Mbit/c.
The duration of data download will ~56 hours.
If I plan a long simulation (10-15 years) the download time will ~1000 hours or ~40 days o_O.
I'm afraid to imagine that I need to run a simulation at 13 km resolution.

I have tested all methods for downloading GEOS-CHEM input data:
1. WashU ftp and http don’t support custom region cutting, for example Arctic. However, they contain some preselected datasets (for example NA), but only a few resolutions.
2. Globus doesn’t support getting of a custom region dataset.
3. And I have a problem with AWS:
```
aws s3 --no-sign-request ls --request-payer=requester s3://gcgrid/
An error occurred (Access Denied) when calling the ListObjects V2 operation: Access Denied
```
Although, I guess that AWS doesn’t support this function.

Make a note to me if I've missed something.

Is this function planned for GEOS-CHEM data repository (OPENDAP or other)?

Thank you for your answers.
Best, zion0210

**Comment by yantosca** [comment]
Thanks @zion0210.  At present we don't have plans to host the GEOS-Chem data on OpenDAP.  That would need to be done at the WashU side.  Tagging @yidant
