### ISSUE TITLE
Registry of Open Data on AWS - GEOS-Chem

### ISSUE THREAD

**Issue by cstner** [geoschem/geos-chem#2252]
### Name and Institution (Required)

Name:  Chris Stoner
Institution: AWS

### Confirm you have reviewed the following documentation

- [ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

You are listed as the contacts for the GEOS-Chem registry page on the Registry of Open Data on AWS: https://registry.opendata.aws/geoschem-input-data/  We have found that your S3 bucket is no longer public and is unreachable.  Can you please look at the bucket and AWS Account public policies.

**Comment by yantosca** [comment]
Also tagging @laestrada

**Comment by lizziel** [comment]
@cstner, thanks for bringing this to our attention. How are you seeing that the bucket is not public?

**Comment by cstner** [comment]
Hi @lizziel - if you paste the AWS CLI command into a command prompt/terminal window: aws s3 ls --no-sign-request s3://gcgrid/  and hit enter, it will attempt to list the bucket but gets an error: "An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied". This usually means the bucket is no longer public.

**Comment by laestrada** [comment]
Hi @cstner, I believe this bucket is set up to be a [requester pays bucket](https://docs.aws.amazon.com/AmazonS3/latest/userguide/RequesterPaysBuckets.html), so that we do not incur charges for data egress. This has always been the case for this bucket as far as I know. You can see the data if you run the following cli command: `aws s3 ls --no-sign-request --request-payer=requester s3://gcgrid/`

Let us know if any further action is needed from us.

**Comment by cstner** [comment]
Hi Lucas, The bucket doesn't need requester pays as this dataset is covered by the open data sponsorship program.  Can you email me at cstner @ amazon.com to discuss?

**Comment by yantosca** [comment]
@cstner @laestrada @yidant @lizziel @msulprizio: Our sysadmin has made the S3 bucket public, so that you won't need to use "requester-pays".  The S3 explorer (https://s3.amazonaws.com/gcgrid/index.html) is also now running so you can download data via the web interface.

**Comment by cstner** [comment]
Excellent!  Thank you
