### ISSUE TITLE
CO2 simulation

### ISSUE THREAD

**Issue by lma6** [geoschem/geos-chem#2255]
### Name and Institution (Required)

Name: Lei Ma
Institution: UMD

### Confirm you have reviewed the following documentation

- [ x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

I am trying to use GC to simulation CO2 concentration with emissions from fossil fuels, land and ocean. I am not sure which simulation type to select when running createRunDir.sh. Should I choose option 4. CO2, or option 12. Carbon & then option 3. Use CO2 only? 

I tried the first simulation type, but it did not read in SiB3_3hr_NEP.nc even though BBIO_SIB3 was enabled. Thus maybe this is not the simulation I need.

I also tried the second simulation type. It did try to read in SiB3_3hr_NEP.nc, but reported an error saying "HEMCO ERROR: Cannot find field SPC_CH2I2. Please check variable name in the config. file". I suspect there may be a missing field for this species in the restart file which was downloaded from http://geoschemdata.wustl.edu/ExtData/GEOSCHEM_RESTARTS/v2023-01/GEOSChem.Restart.carbon.20190101_0000z.nc4. Alternatively, I tried to spin up the model by disabling GC_RESTART and HEMCO_RESTART, then I got this error.

<img width="585" alt="Screenshot 2024-04-19 at 10 00 23 AM" src="https://github.com/geoschem/geos-chem/assets/24945450/33bbe56d-8a5f-4717-979f-55a99f87cad7">

Please advise me on the simulation type and how to configure the model. Thank you!!!

**Comment by yantosca** [comment]
Thanks for writing.  For now I would use the CO2 simulation.  We are working out a few last-minute issues in the carbon/CO2-only simulation.  That should be ready by the 14.4.0 release.

**Comment by lma6** [comment]
Thanks for your reply. I just wanted to confirm that the current version cannot simulate CO2 concentrations from emissions from fossil fuels, land, and the ocean, correct?

**Comment by msulprizio** [comment]
>I just wanted to confirm that the current version cannot simulate CO2 concentrations from emissions from fossil fuels, land, and the ocean, correct?

The current CO2 simulation does include emissions from various sources. See https://github.com/geoschem/geos-chem/blob/main/run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.CO2 for details.

**Comment by msulprizio** [comment]
Hi @lma6. A log file from out latest integration testing for the CO2 simulation shows that those emissions are indeed read:

```
HEMCO: Opening /n/holyscratch01/external_repos/GEOS-CHEM/gcgrid/gcdata/ExtData/HEMCO/CO2/v2022-11/BIO/SiB3_3hr_NEP.nc
```

I would recommend you set Verbose to true in HEMCO_Config.rc, run a short simulation, and check the GEOS-Chem log file to confirm that the emissions are being read. If they are being skipped, the verbose output should also indicate that. Feel free to upload your log file here if you have questions or concerns.

**Comment by lma6** [comment]
@msulprizio Very good suggestion. The log file helped me figured out why these files were not being read on my end; I had renamed the BBIO_SIB3 bracket in the HEMCO_Config for testing, which caused it to be skipped.

I've restored the bracket, and now these files are being read. I'm wondering if I can define a new land flux bracket to replace SIB3 and read in my own data?

**Comment by yantosca** [comment]
Closing out this issue
