### ISSUE TITLE
How to add a Specis in Aerosol-only simulation?

### ISSUE THREAD

**Issue by CraigYEUNG** [geoschem/geos-chem#2258]
During using aerosol-only simulation, it doesn't work by adding species like fullchem. 

I tried adding a new specie SO2abcd in KPP but it doesn't work. So what is the correct way?

**Comment by yantosca** [comment]
Thanks for writing @CraigYEUNG.  The aerosol-only simulation does not use KPP, but rather uses the various chemistry routines in `dust_mod.F90`, `seasalt_mod.F90`, `carbon_mod.F90`, and `sulfate_mod.F90`.  You would need to make corresponding edits in these locations.
