### ISSUE TITLE
Requesting GFAS input after 2022

### ISSUE THREAD

**Issue by jinlx** [geoschem/geos-chem#2262]
### Name and Institution (Required)
Name: Lixu Jin 
Institution: The University of Monanta

### New GEOS-Chem feature or discussion
Hi there,

I am reaching out to request recent GFAS input data (after 2022). Currently, it appears that the HEMCO GFAS inputs rely on processed data from the University of York. This processed data is derived from raw data in ECMWF to make it compatible with GEOS-Chem requirements. 

I am interested in obtaining access to the most recent ECMWF data and exploring the possibility of processing it to generate updated GFAS inputs for GEOS-Chem. If there is an existing script available for data downloading/processing, I would also greatly appreciate access to it and I am happy to facilitate the data integration process from my end and share with the community.

Best,
Lixu

**Comment by msulprizio** [comment]
I am tagging Killian Murphy (@kilicomu) who has provided us with these emissions in the past. Killian, are more recent emissions available?

**Comment by kilicomu** [comment]
Hi - sorry, I've fallen behind with GFAS processing. ECMWF changed things on their end and I haven't got round to fixing up my scripts.

I'll get onto it and get the data sent over to GCST for upload.

**Comment by jinlx** [comment]
Hi Killian (@kilicomu ), I just wanted to check in to see if there have been any updates or progress with the GFAS processing. I understand that these things can take time. I am comfortable with python scripts and if there's anything I can assist with, please don't hesitate to let me know.

**Comment by kilicomu** [comment]
Hi @jinlx - sorry, I've been very busy and didn't realise how much time has passed since I said I'd get on it.

I'll try to make some time tomorrow to catch up with this.

**Comment by kilicomu** [comment]
Hi - I'm having a little trouble with getting hold of GFAS data programmatically from the data source that I would typically get hold of it from!

I'll try some other things and get back to you.

**Comment by kilicomu** [comment]
Hi @jinlx - just to say I've started working on this now.

**Comment by kilicomu** [comment]
Hi @jinlx - I've fixed up my scripts to work with the newer ECMWF data apis and am now downloading and preprocessing the missing data.

It should be available to GCST by the end of the week!

**Comment by jinlx** [comment]
No worries @kilicomu ! Thanks for working on it!

**Comment by kilicomu** [comment]
Hi @jinlx - I've preprocessed all of the data now.

I'm waiting for IT Services at my institution to make a firewall change to allow me to transfer the data to GCST. I'll let you know when that is done.

**Comment by kilicomu** [comment]
Data is now uploading! Sorry for the wait.

Once it's done I'll contact GCST and let them know it's ready for transfer to the WashU data server.

**Comment by jinlx** [comment]
Thanks for letting me know it @kilicomu ! I really appreciate it! Please feel free to close the issue when the data is transfered.

**Comment by msulprizio** [comment]
@jinlx I am transferring them over to Harvard and WashU now.

**Comment by msulprizio** [comment]
@yidant Can you fix the file permissions in http://geoschemdata.wustl.edu/ExtData/HEMCO/GFAS/v2018-09/ for the June 2022 - April 2024 files so they show up for external users?

**Comment by yidant** [comment]
Sure, it is set up. They're now available on WashU data portal!

**Comment by jinlx** [comment]
Hi @kilicomu ! I am trying to download GFAS injection height parameters data but I am struggling with ECMWF API. Could you please share the script you used so that I don't have to rebuild the wheel?

**Comment by kilicomu** [comment]
Hi @jinlx - the scripts are at https://github.com/wacl-york/gfas_scripts.

Sorry, they are not well documented as they were only intended for my use.

There are two scripts in the `bin` directory - `get_gfas.py` and `preprocess_gfas.py`. You need to first run `get_gfas.py` to download data then `preprocess_gfas.py` if you want to preprocess the data for GEOS-Chem. Both scripts have a `--help` option which should tell you how to run them, but let me know if you get stuck.

There is an `environment.yaml` file in the repository which should let you create a `conda` environment to run the scripts.

**Comment by jinlx** [comment]
Hi @kilicomu! This is a piece of art! Thanks for sharing!

**Comment by kilicomu** [comment]
@jinlx Ha yes sorry, the code is not great (especially the preprocessing code, I wrote the most of it 6 years or so ago...) but it does the job!

**Comment by msulprizio** [comment]
Thanks @kilicomu @jinlx! I will close out this issue.
