### ISSUE TITLE
Update documentation regarding AWS S3 bucket, as we no longer need --requester-pays

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#2265]
### Name and Institution (Required)

Name: Bob Yantosca
Institution: Harvard + GCST

### Confirm you have reviewed the following documentation

- [x] [Contributing guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/CONTRIBUTING.html)

### New GEOS-Chem feature or discussion
We need to update the geos-chem.readthedocs.io pages about how to download data as follows:

1. Remove `--requester-pays=requester` from the documentation and the `download_data.yml` file, as this is no longer needed.
2. Also add documentation about the AWS explorer link: https://s3.amazonaws.com/gcgrid/index.html

**Comment by msulprizio** [comment]
This was addressed by https://github.com/geoschem/geos-chem/pull/2303
