### ISSUE TITLE
How to calculate the lifetime of NOx

### ISSUE THREAD

**Issue by Kexin828** [geoschem/geos-chem#2269]
### Name and Institution (Required)

Name: Kexin Zhang
Institution: Tsinghua University

### Confirm you have reviewed the following documentation

- [√] [Contributing guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/CONTRIBUTING.html)

### New GEOS-Chem feature or discussion
Can I calculate the lifetime of NOx based on the output of the Budget in HISTORY.rc? If I want to obtain the loss pathway of NOx, what should I do?
Thanks for your reply.
![image](https://github.com/geoschem/geos-chem/assets/149068356/c53873cf-e74e-4ba9-9e1d-fc90d7ee0fd8)

**Comment by yantosca** [comment]
Thanks for writing @Kexin828.  To get the loss pathway of NOx you should define a`LNOx` family in the `fullchem.kpp` file.  You can follow what is done for `LOx`.
```
#FAMILIES                 { Chemical families for prod/loss diagnostic }
POx : O3 + NO2 + 2NO3 + PAN + PPN + MPAN + HNO4 + 3N2O5 + HNO3 + BrO + HOBr + BrNO2 + 2BrNO3 + MPN + ETHLN + MVKN + MCRHN + MCRHNB + PROPNN + R4N2 + PRN1 + PRPN + R4N1 + HONIT + MONITS + MONITU + OLND + OLNN + IHN1 + IHN2 + IHN3 + IHN4 + INPB + INPD + ICN + 2IDN + ITCN + ITHN + ISOPNOO1 + ISOPNOO2 + INO2B + INO2D + INA + IDHNBOO + IDHNDOO1 + IDHNDOO2 + IHPNBOO + IHPNDOO + ICNOO + 2IDNOO + MACRNO2 + ClO + HOCl + ClNO2 + 2ClNO3 + 2Cl2O2 + 2OClO + O + O1D + IO + HOI + IONO + 2IONO2 + 2OIO + 2I2O2 + 3I2O3 + 4I2O4 + NIT + NITs;
LOx : O3 + NO2 + 2NO3 + PAN + PPN + MPAN + HNO4 + 3N2O5 + HNO3 + BrO + HOBr + BrNO2 + 2BrNO3 + MPN + ETHLN + MVKN + MCRHN + MCRHNB + PROPNN + R4N2 + PRN1 + PRPN + R4N1 + HONIT + MONITS + MONITU + OLND + OLNN + IHN1 + IHN2 + IHN3 + IHN4 + INPB + INPD + ICN + 2IDN + ITCN + ITHN + ISOPNOO1 + ISOPNOO2 + INO2B + INO2D + INA + IDHNBOO + IDHNDOO1 + IDHNDOO2 + IHPNBOO + IHPNDOO + ICNOO + 2IDNOO + MACRNO2 + ClO + HOCl + ClNO2 + 2ClNO3 + 2Cl2O2 + 2OClO + O + O1D + IO + HOI + IONO + 2IONO2 + 2OIO + 2I2O2 + 3I2O3 + 4I2O4 + NIT + NITs;
PCO : CO;
LCO : CO;
PSO4 : SO4;
LCH4 : CH4;
PH2O2 : H2O2;
```
This will be saved to the History diagnostics `ProdLoss` collection as `Loss_NOx`.  You will also need to update the `species_database.yml` file (follow what is done for LOx).

It depends how you want to define LNOx.  The simple definition is NO + NO2 but then you might want to also include HNO3 and PAN.  That is more of a science question though.

**Comment by Kexin828** [comment]
My implementation:
First, I added the following to fullchem.kpp file:

#FAMILIES
...
LNO: NO;
LNO2: NO2;
Then I recompiled the KPP using v3.0.2 running lines like

cd ~/GCClassic/src/GEOS-Chem/KPP/
./build_mechanism.sh fullchem

This is KPP-3.1.0.

KPP is parsing the equation file.
KPP is computing Jacobian sparsity structure.
KPP is starting the code generation.
KPP is initializing the code generation.
KPP is generating the monitor data:
    - gckpp_Monitor
KPP is generating the utility data:
    - gckpp_Util
KPP is generating the global declarations:
    - gckpp_Main
KPP is generating the ODE function:
    - gckpp_Function
KPP is generating the ODE Jacobian:
    - gckpp_Jacobian
    - gckpp_JacobianSP
KPP is generating the linear algebra routines:
    - gckpp_LinearAlgebra
KPP is generating the utility functions:
    - gckpp_Util
KPP is generating the rate laws:
    - gckpp_Rates
KPP is generating the parameters:
    - gckpp_Parameters
KPP is generating the global data:
    - gckpp_Global
KPP is generating the driver from none.F90:
    - gckpp_Main
KPP is starting the code post-processing.

KPP has successfully created the model "gckpp".

Reactivity consists of 189 reactions
Written to gckpp_Util.F90


After recompiling the KPP, I saw that LNO and LNO2 appearing on gckpp_Monitor.F90,gckpp_Parameters.F90, gckpp.kpp, gckpp.log, and fullchem.kpp files. This is consistent with our families that are defined in fullchem.kpp.

Then in my run directory, I modified the species_database.yml file so that it includes definition of LNO and LNO2:

LNO:
  FullName: Dummy species to track loss of NO
  Is_Gas: true
  MW_g: 30.01
LNO2:
  FullName: Dummy species to track loss of NO2
  Is_Gas: true
  MW_g: 46.01

Finally, on my HISTORY.rc, I collect the ProdLoss COLLECTION such as Prod_?PRD? and Loss_?LOS?. My ProdLoss output files show variables that were already predefined in fullchem.kpp such as Loss_CH4,Loss_CO,Loss_Ox. But it doesn't show production and loss rates of NO  or NO2.

When I collect Loss_NO and Loss_NO2 in HISTORY.rc ProdLoss Collection, I get the following error:


HISTORY (INIT): Opening ./HISTORY.rc
===============================================================================
GEOS-Chem ERROR: LOSS_NO is not found in the registry for the DIAG object!
 -> at Registry_Lookup (in Headers/registry_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem ERROR: Could not locate Loss_NO diagnostics state registry.
 -> History_AddItemToCollection (in History/history_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem ERROR: Could not add diagnostic "Loss_NO" to collection: ProdLoss
 -> at History_ReadCollectionData (in module History/history_mod.F90)

 -> ERROR occurred at (or near) line    464 of the HISTORY.rc file
===============================================================================

===============================================================================
GEOS-Chem ERROR: Error encountered in "History_ReadCollectionData"!
 -> at History_Init (in module History/history_mod.F90)
===============================================================================

===============================================================================
GEOS-CHEM ERROR: Error encountered in "History_Init"!
STOP at  -> at GEOS-Chem (in GeosCore/main.F90)
===============================================================================
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
gcclassic          0000000000D149AA  Unknown               Unknown  Unknown
libpthread-2.17.s  00002B3EB42CA630  Unknown               Unknown  Unknown
gcclassic          0000000000C14971  hco_driver_mod_mp         359  hco_driver_mod.F90
gcclassic          00000000004F32FC  hco_interface_gc_        1236  hco_interface_gc_mod.F90
gcclassic          000000000046548A  emissions_mod_mp_         394  emissions_mod.F90
gcclassic          000000000043CDF6  cleanup_                  123  cleanup.F90
gcclassic          00000000009D4539  error_mod_mp_erro         437  error_mod.F90
gcclassic          0000000000412F90  MAIN__                    668  main.F90
gcclassic          000000000040F792  Unknown               Unknown  Unknown
libc-2.17.so       00002B3EB44F9555  __libc_start_main     Unknown  Unknown
gcclassic          000000000040F6A9  Unknown               Unknown  Unknown
real 20.98
user 17.91
sys 2.05
srun: error: comput7: task 0: Exited with exit code 174
srun: Terminating job step 18669.0


I'd greatly appreciate any feedback on my implementation!

**Comment by zpleo** [comment]
@Kexin828 Hi, I also encountered the same problem when I was doing PL diagnostic output. Have you solved it now? Thank you
