### ISSUE TITLE
[QUESTION] Confirm missing SOA in the wiki page

### ISSUE THREAD

**Issue by pshchien** [geoschem/geos-chem#228]
To whom it may concern,
I am now looking at the GEOS-Chem wiki page about the PM.

I found that in the PM2.5 in the 1-yr benchmark plots, there is no SOA_ugm3, but when calculating the PM25, we need to use that.
http://wiki.seas.harvard.edu/geos-chem/index.php/Particulate_matter_in_GEOS-Chem#PM2.5_in_the_1-yr_benchmark_plots

I just want to make sure that the MWaer for SOA is 150, as what we can see in the species in GEOS-Chem wiki page.

Sincerely,

Rong-You Chien

**Comment by yantosca** [comment]
Thanks for writing.  Yes, I believe all SOA species use a MW of 150.  You can see the table on the wiki at:
- http://www.geos-chem.org/Species_in_GEOS-Chem

**Comment by pshchien** [comment]
Dr. Yantosca,
Thanks for verifying.
One more question, how did the 150 molecular weight being decided?
We try to find through the GEOS-Chem wiki page and some paper, but can not find a specific paper discussing this.

Thanks.

**Comment by yantosca** [comment]
That might be a better question for the Aerosols Working Group.  I am not sure why it is 150 but it may be an average weight.

**Comment by yantosca** [comment]
Jeff Pierce wrote:

>I don't believe that the MWs for SOA are used for anything other than converting between mixing ratio units to mass concentration units. Because the SOA schemes are made on a mass basis, the mass concentrations are the ones to work with, not the mixing ratios. Hence, if you have mixing ratios from the model, convert them to mass concentrations using the MW of 150 g/mol. I think this 150 g/mol was chosen somewhat arbitrarily because the choice does not really matter in the model.
>
>Once you have the mass concentrations, you can assume any MW that you think is appropriate if you are doing an offline calculation that requires it.
