### ISSUE TITLE
GEOS-CHEM Aerosol scheme

### ISSUE THREAD

**Issue by zion0210** [geoschem/geos-chem#2280]
### Name and Institution (Required)

Name: zion0210
Institution: ASU

### Confirm you have reviewed the following documentation

- [ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Hello!

I tested the capability of GEOS-CHEM for aerosol simulation.

I can choose TOMAS or APM aerosol microphysics in the fullchem simulation.

However, if I chose "aerosol only" for simulation type, the aerosol microphysics didn't set. 

Related to this, what aerosol scheme does the GC use when I set the simulation to "aerosol only"?

This is my result of the "aerosol only" build:
`cmake ../CodeDir -DAPM=y -DRUNDIR=..`
Not build.
`cmake ../CodeDir  -DTOMAS=y -DTOMAS_BINS=15 -DRUNDIR=..`
Build, doesn't work, sigfault.
`cmake ../CodeDir  -DRUNDIR=..`
Build, works.

I also have a question about RRTMG.
If I enable RRTMG:
`cmake ../CodeDir -DRRTMG=y -DRUNDIR=..`
And did add in geoschem_config.yml 
```
  rrtmg_rad_transfer_model:
    activate: false
    aod_wavelengths_in_nm:
      - 500
```
It works.
If `activate: true`, I got sigfault.

Best regards,
zion0210

**Comment by yantosca** [comment]
Thanks for writing @zion0210.  The APM and TOMAS microphysics schemes are only compatible with the full-chemistry simulations.  They will not work with the aerosol-only simulation.

**Comment by zion0210** [comment]
Thanks for your answer @yantosca. So, if APM and TOMAS microphysics schemes are only compatible with the full-chemistry, I have the following question: what scheme of the microphysics is used for the "aerosol-only" simulation?

**Comment by yantosca** [comment]
Thanks for your patience @zion0210.  There is no microphysics for the "aerosol-only" simulation.  It includes only bulk treatment of aerosols.

**Comment by yantosca** [comment]
Closing out this issue
