### ISSUE TITLE
How to save all layers in THE DryDep COLLECTION in GEOSChemv13.3.2?

### ISSUE THREAD

**Issue by yangning-code** [geoschem/geos-chem#2281]
### Name and Institution (Required)

Name:NingYang
Institution:JNU

### Confirm you have reviewed the following documentation

- [ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

How to save all layers in THE DryDep COLLECTION in GEOSChemv13.3.2?

**Comment by yantosca** [comment]
Thanks for writing @yangning-code.  The DryDep collection is a 2-D output collection.  To save 3D output you would need to add a 3rd spatial dimension to the `State_Diag%DryDep`, `State_Diag%DryDepMix`, and `State_Diag%DryDepChm`.  You can use the `State_Diag%SpeciesConcVV` diagnostic as an example.  Also see: 

-[Adding new History diagnostcs](https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/history-diag-guide.html#adding-new-history-diagnostics) on ReadTheDocs

**Comment by yangning-code** [comment]
Thank you very much @yantosca. I will try it as you suggested. But I also want to ask a question, why is the dry collection set to 2 dimensions instead of 3 dimensions directly? Is there any scientific significance? I think setting it directly to 3D is convenient for users.

**Comment by yangning-code** [comment]
I have another question, which height level does the 2-dimensional data correspond to? Or is it the entire height (47th floor)? I don’t quite understand what this data means?

**Comment by yangning-code** [comment]
[state_diag_mod_drydep.F90.txt](https://github.com/geoschem/geos-chem/files/15228743/state_diag_mod_drydep.F90.txt)
[state_diag_mod_default.F90.txt](https://github.com/geoschem/geos-chem/files/15228751/state_diag_mod_default.F90.txt)

Following your suggestions, I made some modifications and attempts. Specifically, the modification content is in the two files I uploaded. One of them is called state_diag_mod_default.F90.txt, which is the default file of version 13.3.2, and the other state_diag_mod_drydep.F90.txt is the modified file.
When I compile, I get the following error:
src/GEOS-Chem/GeosCore/diagnostics_mod.F90(160): error #6351: The number of subscripts is incorrect. [DRYDEP]
 State_Diag%DryDep(I,J,S) = State_Diag%DryDepChm(I,J,S)
