### ISSUE TITLE
How to caculate PM2.5 compositions?

### ISSUE THREAD

**Issue by fangzhoupig** [geoschem/geos-chem#2286]
![image](https://github.com/geoschem/geos-chem/assets/133865372/e5f9eeb5-ddb1-4f9e-8024-402518e85407)

I want to caculated the PM2.5 composition.

Is the variables (SO4, NH4, NIT) in the code referring to "AerMassSO4","AerMassNH4","AerMassNIT"？ Is "AerMassNIT" the NO3- aerosols? 

Can anyone help? Many thanks.

**Comment by fangzhoupig** [comment]
The SO4, NH4, NIT in PM2.5 as cacluated using "AerMassSO4","AerMassNH4","AerMassNIT" are relatively too small. The sum of the compositios I caculated is less than PM2.5 outputed by GEOSCHEM.

**Comment by fangzhoupig** [comment]
I double check my results. It turns out the sum of the PM2.5 compositions are consistent with the PM2.5 outputed by GEOSCHEM. But still, the  SO4, NH4, NIT are very small. Is it possible that SOA part of PM2.5 also concludes parts of SO4, NH4, NIT?

**Comment by yantosca** [comment]
Thanks for your patience @fangzhoupig.  The `AerosolMass` quantities are in kg/m3.  They are computed in the `GeosCore/aerosol_mod.F90`  The wiki page may be a little out of date, what is in the code is correct.

https://github.com/geoschem/geos-chem/blob/20e2402baf56c682cc04af74adb139efdb6ca000/GeosCore/aerosol_mod.F90#L352-L859

NIT is the inorganic nitrate aerosols.

**Comment by ChangpeiHe** [comment]
1. If you want to calculate pm2.5 concentration (ug/m3) by your mentioned fomula, please use SO4, NH4, NIT, and other compositions in GEOSChem.SpeciesConc.YYYTMMDD_0000z.nc4 instead of GEOSChem.AerosolMass.YYYYMMDD_0000z.nc4. Note that don't forget to use real Temp and Pressure from ''GEOSChem.StateMetYYYYMMDD_0000z.nc4" to generate pm2.5 concentrations in STP condition.
2. or, you can directly use the ''AerMassPM25".

**Comment by fangzhoupig** [comment]
> 1. If you want to calculate pm2.5 concentration (ug/m3) by your mentioned fomula, please use SO4, NH4, NIT, and other compositions in GEOSChem.SpeciesConc.YYYTMMDD_0000z.nc4 instead of GEOSChem.AerosolMass.YYYYMMDD_0000z.nc4. Note that don't forget to use real Temp and Pressure from ''GEOSChem.StateMetYYYYMMDD_0000z.nc4" to generate pm2.5 concentrations in STP condition.
> 2. or, you can directly use the ''AerMassPM25".

do you mean to caculate using PV = nRT, where P is the Met_PS1WET (hPa), R is 8.314 J/(mol·K), T is Met_T (K), n is the mols, n/V meaning how many mols per m3 (mols cm-3). Output GEOSChem.SpeciesConc.YYYTMMDD_0000z.nc4 is in unit molec cm-3. Could tansfer the unit into mols cm-3 by dividing 6.022 x 10^23 (mol-1). Am I correct?

**Comment by ChangpeiHe** [comment]
You are correct. Actually, it's recommended to directly use the 'AerMassPM25' in 'GEOSChem.AerosolMass.YYYYMMDD_0000z.nc4.'

**Comment by ChangpeiHe** [comment]
The "species_database.yml" defines the molecular weights of PM2.5 components, which facilitates the conversion from molec/cm^3 to ug/m^3.

**Comment by fangzhoupig** [comment]
> The "species_database.yml" defines the molecular weights of PM2.5 components, which facilitates the conversion from molec/cm^3 to ug/m^3.

if so, do I still need temperature and pressure data to do the caculation?

**Comment by fangzhoupig** [comment]
> ```
>     ! Apply STP correction factor based on ideal gas law 
>     State_Chm%AerMass%PM25(I,J,L) = State_Chm%AerMass%PM25(I,J,L) * ( 1013.25_fp / PMID(I,J,L) ) * & 
>                   ( T(I,J,L)   / 298.0_fp    ) 
> 
>     State_Chm%AerMass%PM10(I,J,L) = State_Chm%AerMass%PM10(I,J,L) * ( 1013.25_fp / PMID(I,J,L) ) * & 
>                   ( T(I,J,L)   / 298.0_fp    ) 
> ```
> 
> The AerMass unit is ug/m3

Thank you. The code is very useful for my issue.

**Comment by yantosca** [comment]
Thanks @ChangpeiHe and @fangzhoupig.  I will close this issue.  Feel free to open another issue if you still have questions/problems.
