### ISSUE TITLE
[BUG/ISSUE]  GEOS-Chem 12.7.1 compile error -- ranlib needed

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#229]
I am adding this issue on behalf of Lee Murray (lee.murray [at] rochester.edu):

>Version 12.7.1 will not compile on my system (it complains that the ObsPack does not contain any symbols) unless ranlib is explicitly added to the ObsPack/Makefile (see below).

```Make
lib: $(OBJECTS)
      $(AR) crs $(LIBRARY) $(OBJECTS)
      ranlib $(LIBRARY)
      mv $(LIBRARY) $(LIB) 
```

**Comment by yantosca** [comment]
Thanks for writing.  Try setting this environment variable:

```bash
export AR=ranlib
```
On most unix systems the ```ar``` command is used for creating library files (```.a```) but on some systems, ranlib is used instead.

**Comment by ltmurray** [comment]
ranlib doesn't like the "crs" passed to $(AR) in the Makefiles

`ranlib crs libNcUtils.a m_do_err_out.o m_netcdf_io_checks.o m_netcdf_io_close.o m_netcdf_io_create.o m_netcdf_io_define.o m_netcdf_io_get_dimlen.o m_netcdf_io_handle_err.o m_netcdf_io_open.o m_netcdf_io_read.o m_netcdf_io_readattr.o m_netcdf_io_write.o ncdf_mod.o
ranlib: 'crs': No such file
ranlib: 'libNcUtils.a': No such file
ranlib: m_do_err_out.o: File format not recognized`

**Comment by yantosca** [comment]
Which OS are you using?  Is this on MacOS?

If you are using Ubuntu you may be able to do ```sudo apt install ar```, which would solve the problem.   You might also be able to install ar locally with Spack.

The ranlib library is deprecated, most systems use ar instead.  See: https://superuser.com/questions/404603/what-is-ranlib

**Comment by ltmurray** [comment]
No, this is our university's shared HPC system running RHEL (see below).  ar is installed, and works for the GEOS-Chem libraries, just not ObsPack.

NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"
Red Hat Enterprise Linux Server release 7.6 (Maipo)
Red Hat Enterprise Linux Server release 7.6 (Maipo)

**Comment by yantosca** [comment]
OK, let me take a look at the Makefile.

Have you also tried building GEOS-Chem with CMake?  I wonder if that will work for you.   See: http://wiki.geos-chem.org/Compiling_with_CMake

**Comment by yantosca** [comment]
Also, I wonder if there is some issue with finding ar in your search path.  Do you have /usr/bin in your PATH variable?  Usually /usr/bin/ar is the location.

We are going to be retiring GNU Make in 13.0.0, to be replaced with CMake.  If CMake doesn't work then let us know.

**Comment by ltmurray** [comment]
cmake does successfully build.   For other users with issues with GNU Make, the single line in the first post added to Obspack/Makefile allows the model to compile, although it is important to note that the indentation before ranlib is a single tab, not multiple spaces.

**Comment by yantosca** [comment]
If CMake successfully builds, I would use that for now, as GNU Make is being retired.  Thanks for checking!
