### ISSUE TITLE
Satellite Diagnostics not working with 0.25x0.325 grid

### ISSUE THREAD

**Issue by julietajuncosa** [geoschem/geos-chem#2292]
Name: Julieta Juncosa Calahorrano
Institution: University of Minnesota

Hello, I am running a nested simulation on a 0.25x0.325 grid cell. I am interested in the Satellite Diagnostics collection (SatDiagn). However, my simulation gave me the error shown on the screenshot bellow. My colleagues suggested running in a coarser resolution, 0.5x0.625 with the same configuration. That simulation (0.5x0.625) is running normally with no errors from the SatDiagn collection. I am wondering if the SatDiagn has some bug or limitation for the 0.25x0.325 resolution 

![Screenshot 2024-05-03 at 2 08 54 PM](https://github.com/geoschem/geos-chem/assets/132104394/a9e017c5-88f7-4514-976e-894ac7604f12)

**Comment by yantosca** [comment]
Thanks for writing @julietajuncosa.  Would you be able to attach your HISTORY.rc file to this issue?  That might shed some light on the problem.

Also I wonder if this could be a side-effect of an out-of-bounds error.  Another thing to try is to recompile GEOS-Chem (maybe in a fresh run directory) with the `cmake -DCMAKE_BUILD_TYPE=Debug` option.  This will turn on further error checking that may reveal some other problem.  Then run your simulation for a short time like 20 minutes.

**Comment by julietajuncosa** [comment]
Hi Bob! Thanks for your quick response. I try running my simulation updating some of my packages to use Rocky8 rather than Centos7 and now that Satellite Diagnostics is working. I am mentioning this because this was the only change that I made between the last (failed) simulation and the current one which is writing my the output. 

Thank you!
Julieta

**Comment by yantosca** [comment]
Thanks @julietajuncosa.  It could have been that you were using netCDF libraries built on the old OS.  Rocky Linux is close to CentOS7 (they advertise zero-diffs) but you never know.  

I will close out this issue.  If you are going to IGC11, I will see you there!
