### ISSUE TITLE
Forced exit from Rosenbrock : Step size too small error

### ISSUE THREAD

**Issue by ycyeongi** [geoschem/geos-chem#2294]
### Name and Institution (Required)

Name: chaeyeong Yang
Institution: PNU

### Confirm you have reviewed the following documentation

- [ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

GEOS-Chem version : 13.3.0

I am running from February 20-23, 2020 with a resolution of 0.25x0.3125. However, the model stops with an error like this.
![image](https://github.com/geoschem/geos-chem/assets/169321162/3a879a2b-210b-4af9-86ce-8cff84c39cbd)

I saw https://github.com/geoschem/geos-chem/issues/2113 but that's model version is different with mine. 
 Not only this time, but the last time I ran it from February 15th to 25th, it stopped at least 3 times. I set the timestep like this. 
![image](https://github.com/geoschem/geos-chem/assets/169321162/d9fed7eb-90c3-4cd5-bf69-4ce7f7eeb880)

[GC.log](https://github.com/geoschem/geos-chem/files/15321434/GC.log)

**Comment by yantosca** [comment]
Thanks for writing @ycyeongi.  We would recommend updating to the latest version (currently 14.3.1, soon to be 14.4.0), which has several fixes for this sort of issue.

If that is not possible, try to implement the updates described in #1982 and PR #2006.

**Comment by ycyeongi** [comment]
The period I ran was during the yellow dust period.
I changed the timestep to 60 and 120 because the previous timestep did not converge due to the rapidly increasing dust production and transportation volume.
I checked that it works without error.

**Comment by yantosca** [comment]
Thanks so much for the update @ycyeongi!  I can close out this issue now.
