### ISSUE TITLE
What happened if I open two global anthropogenic emissions?

### ISSUE THREAD

**Issue by fangzhoupig** [geoschem/geos-chem#2296]
I noted that if I open CEDS and EDGARv43, the emission would be higher and closer to observation compared with I open CEDS only.
I wonder, how the model processed the emission caculation when two global anthropogenic emissions applied?

**Comment by fangzhoupig** [comment]
I check for the hier number for both emission inventories, for EDGARv4.3, it shows "2", for CEDS, it shows "5", so does it mean CEDS is not working when I open both?

**Comment by fangzhoupig** [comment]
I think I understood now. higher hier number overwrites the lower ones. And, EDGAR can compensate for DICE_AFRICA datasets.

**Comment by yantosca** [comment]
Thanks for writing.  We can close out this issue now.  Feel free to open another issue if you have questions.
