### ISSUE TITLE
When I use the GEOS-Chem simulation, I always get a random error for NetCDF: HDF error【BUG】

### ISSUE THREAD

**Issue by dadastory** [geoschem/geos-chem#2298]
[](url)### Name and Institution (Required)

Name: zhou-kaiy
Institution: Nanjing University

### Confirm you have reviewed the following documentation

- [√] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [√] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [√] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [√] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

When I run a one-month simulation, I always quit randomly on a certain date with an error, and this has been going on for a month. This error always looks the same error, but I have no way of knowing what it is. I re-downloaded the data file with the same issue, confirmed that there was no problem with the .nc file being read.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In Ncwr_3d_R4 #2:  NetCDF: HDF error
     65536        14

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Code stopped from DO_ERR_OUT (in module NcdfUtil/m_do_err_out.F90) 

This is an error that was encountered in one of the netCDF I/O modules,
which indicates an error in writing to or reading from a netCDF file!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

I also checked the .nc file according to the official website and the .nc file is not corrupted, and others use these data simulations without errors, which only happened to me.
At first I suspected it was a dependency issue, so the recompilation used the new netcdf dependencies and HDF5 dependencies for simulation, but I still got this error.
What I can't figure out is why other people use the same data and don't report mistakes, and that's just what happened to me.
This error doesn't provide any valid explanations, and I turned on debug mode and still don't see anything wrong with the logs.
The official statement is that it is because of the .nc file corruption or IO problem, because the computer node that executes the simulation is to read the .nc data file mounted by NFS, I wonder if there is a possibility that the .nc file cannot be read due to NFS transmission, which causes this error?
Because other people use this data to simulate without problems, but only I use this data will stop the simulation with an error on a certain date, excluding file corruption, is there any other explanation?
I hope the official can help find the problem, thank you very much

**Here is the relevant log attachment**
[GC_201907.log](https://github.com/geoschem/geos-chem/files/15345052/GC_201907.log)
[HEMCO.log](https://github.com/geoschem/geos-chem/files/15345053/HEMCO.log)
![343a7751f310a7dce3510937acfd04b](https://github.com/geoschem/geos-chem/assets/84147842/4693bc74-ae45-4aaf-96ed-ab9c375bec3a)

**Comment by lizziel** [comment]
Hi @dadastory, the error is in NetCDF routine `Ncwr_3d_R4` which writes files rather than reads. The last normal message in the log is that the model is writing data to the boundary conditions file. Could you be running out of memory?

**Comment by dadastory** [comment]
Job <25460>, User <hwy>, Project <default>, Status <RUN>, Queue <huawei-v2>, Co
                          mmand <#BSUB -q huawei-v2 ;#BSUB -n 48 ;#BSUB -o %J.o
                          ut;#BSUB -e %J.err;source /share01/user_home/hwy/.bas
                          hrc_gc_v2;./gcclassic > GCv14_luowetdep20240515.log>
Thu May 16 17:27:18 2024: Submitted from host <login>, CWD <$HOME/GC_v1431/gc_0
                          5x0625_AS_47L_merra2_fullchem>, Output File <25460.ou
                          t>, Error File <25460.err>, 48 Task(s);
Thu May 16 17:27:18 2024: Started 48 Task(s) on Host(s) <48*node13>, Allocated 
                          48 Slot(s) on Host(s) <48*node13>, Execution Home </s
                          hare01/user_home/hwy>, Execution CWD </share01/user_h
                          ome/hwy/GC_v1431/gc_05x0625_AS_47L_merra2_fullchem>;
Fri May 17 21:51:51 2024: Resource usage collected.
                          The CPU time used is 3679002 seconds.
                          MEM: 24.1 Gbytes;  SWAP: 0 Mbytes;  NTHREAD: 52
                          PGID: 19293;  PIDs: 19293 19294 19298 20144 


 MEMORY USAGE:
 MAX MEM: 25.5 Gbytes;  AVG MEM: 24.1 Gbytes

 SCHEDULING PARAMETERS:
           r15s   r1m  r15m   ut      pg    io   ls    it    tmp    swp    mem
 loadSched   -     -     -     -       -     -    -     -     -      -      -  
 loadStop    -     -     -     -       -     -    -     -     -      -      -  

 RESOURCE REQUIREMENT DETAILS:
 Combined: select[type == local] order[r15s:pg]
 Effective: select[type == local] order[r15s:pg]

**Comment by dadastory** [comment]
We're all running under LSF with 48 cores per node, and it doesn't look like the memory is exceeded

**Comment by dadastory** [comment]
> Hi @dadastory, the error is in NetCDF routine `Ncwr_3d_R4` which writes files rather than reads. The last normal message in the log is that the model is writing data to the boundary conditions file. Could you be running out of memory?

We're all running under LSF with 48 cores per node, and it doesn't look like the memory is exceeded

**Comment by dadastory** [comment]
> Hi @dadastory, the error is in NetCDF routine which writes files rather than reads. The last normal message in the log is that the model is writing data to the boundary conditions file. Could you be running out of memory?`Ncwr_3d_R4`

@lizziel  What I can't figure out the most is why this problem occurs as long as my measurements, but no one else will have this error, the memory is 200GB, and there should be no memory overflow problem （VAV）

**Comment by lizziel** [comment]
The error is occuring in [this section](https://github.com/geoschem/geos-chem/blob/20e2402baf56c682cc04af74adb139efdb6ca000/NcdfUtil/m_netcdf_io_write.F90#L729-L734) of the GEOS-Chem code.

```
    ierr = NF90_Put_Var(ncid, varid, varwr_3d, start=strt3d, count=cnt3d)

    if (ierr /= NF90_NOERR) then
       err_msg = 'In Ncwr_3d_R4 #2:  ' // NF90_Strerror(ierr)
       call Do_Err_Out(err_msg, .true., 2, ncid, varid, 0, 0.0d0, 0.0d0)
    end if

  end subroutine Ncwr_3d_R4
```

You can add prints to this section, rebuild, and rerun, to find out exactly what all the parameters are when it crashes. The error message already includes error codes returned by your NetCDF library. You will need to look at the your library to find out what they mean since they are often dependent on version and build. The docs for `NF90_StrError` (which is what returns the integers printed in the error message) are [here](https://docs.unidata.ucar.edu/netcdf-fortran/current/f90_datasets.html).

**Comment by dadastory** [comment]
> The error is occuring in [this section](https://github.com/geoschem/geos-chem/blob/20e2402baf56c682cc04af74adb139efdb6ca000/NcdfUtil/m_netcdf_io_write.F90#L729-L734) of the GEOS-Chem code.
> 
> ```
>     ierr = NF90_Put_Var(ncid, varid, varwr_3d, start=strt3d, count=cnt3d)
> 
>     if (ierr /= NF90_NOERR) then
>        err_msg = 'In Ncwr_3d_R4 #2:  ' // NF90_Strerror(ierr)
>        call Do_Err_Out(err_msg, .true., 2, ncid, varid, 0, 0.0d0, 0.0d0)
>     end if
> 
>   end subroutine Ncwr_3d_R4
> ```
> 
> You can add prints to this section, rebuild, and rerun, to find out exactly what all the parameters are when it crashes. The error message already includes error codes returned by your NetCDF library. You will need to look at your library files to find out what they mean since they are often dependent on version and build. The docs for `NF90_StrError` (which is what returns the integers printed in the error message) are [here](https://docs.unidata.ucar.edu/netcdf-fortran/current/f90_datasets.html).

@lizziel I try to ask chatgpt4，it give me some code, could it work? 
```c
if (ierr /= NF90_NOERR) then
   write(err_msg, '(A,I5,A,A)') 'In Ncwr_3d_R4 #2: Error writing variable, error code = ', ierr, ', ', NF90_Strerror(ierr)
   call Do_Err_Out(err_msg, .true., 2, ncid, varid, 0, 0.0d0, 0.0d0)
end if
```

**Comment by yantosca** [comment]
Closing out this issue
