### ISSUE TITLE
Errors when compiling

### ISSUE THREAD

**Issue by ymxu-atm** [geoschem/geos-chem#2299]
### Name and Institution (Required)

Name: Yiming
Institution: Purdue University

Hi,

I was trying to compile the latest GCC classic following the guidelines. While I used the command "make -j", it showed that "Fatal Error: Cannot read module file 'netcdf.mod' opened at (1), because it was created by a different version of GNU Fortran compilation terminated".

I will appreciate it if you can help.

Best,
Yiming

**Comment by yantosca** [comment]
Hi @ymxu-atm, thanks for writing.  You will need to compile GEOS-Chem with the same compiler that the netCDF libraries were built with.  Do you happen to know which GNU version was used to build your netCDF?  (Or is there a sysadmin/research computing staff there that could find out for you?)

**Comment by yantosca** [comment]
@ymxu-atm: Were you able to resolve this issue?

**Comment by ymxu-atm** [comment]
Hi Bob,

Sorry for my late reply. Yes, I have resolved it by loading some packages. Thank you for your time.

Best,
Yiming
