### ISSUE TITLE
[QUESTION] Scaling emissions by country for multiple species, using the same COUNTRY_MASK file, but getting the error:ERROR LOCATION: HCOIO_ReadCountryValues (hcoio_dataread_mod.F90). What could the issue be?

### ISSUE THREAD

**Issue by LukeFakes** [geoschem/geos-chem#230]
I have a collection of country-specific scale factor files which I am trying to add, scaling different species. I've formatted these with the structure suggested on the wiki (http://wiki.seas.harvard.edu/geos-chem/index.php/HEMCO_examples#Scale_emissions_by_country), confirmed they're in ascii format, i.e:

```
# Country mask file name
COUNTRY_MASK

# CountryName CountryID CountryValues
DEFAULT 0 1.0/1.0/1.0/1.0/1.0/1.0/1.0/1.0/1.0/1.0/1.0/1.0
````

But during HEMCO_sa runs I receive the following error:
```
HEMCO ERROR: Cannot open $DATA_DIR/CO_AVIATION.txt
ERROR LOCATION: HCOIO_ReadCountryValues (hcoio_dataread_mod.F90)
```
The only remaining point I can think to change is the scale factor ID to SCALE_COUNTRY' and file name 'scalefactor.txt' to exactly match the wiki ('SCALE_COUNTRY [PATH_TO_FILE]/scalefactor.txt'), but I think this would stop me using more than one scale factor file.  

Do you have any suggestions?

**Comment by yantosca** [comment]
Thanks for writing.  Can you attach the complete HEMCO_Config.rc file to this issue? You will need to rename it to HEMCO_Config.rc.txt so that Github can parse it.

**Comment by LukeFakes** [comment]
Thanks, the scale factor files have IDs 811-876 and the COUNTRY_MASK file is defined at the start of the non-emissions data section. 

[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/4250688/HEMCO_Config.txt)

**Comment by LukeFakes** [comment]
Hi Bob, I think the issue might be related to directory permissions. I've tried moving the .txt files and all seems to be running fine. I will update you on whether the run finishes and that was the issue. If so, thanks for your time on this!

**Comment by yantosca** [comment]
Thanks.  Have you tried moving the country mask definition to the MASKS section (near the end of the file)?  Maybe HEMCO is not interpreting this as mask data.

**Comment by yantosca** [comment]
Or if it seems to be working then let me know and I'll close out the issue.  Thanks.
