### ISSUE TITLE
Error in building dependencies for GEOS-Chem

### ISSUE THREAD

**Issue by garvitagarwal290** [geoschem/geos-chem#2304]
### Name and Institution (Required)

Name: Garvit Agarwal
Institution: TCS Research, Pune

### Confirm you have reviewed the following documentation

- [ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

I have run GEOS-Chem simulations for many months In the past. However now I am trying to set it up again, and I am facing issues in building the dependencies using Spack. I am following the instructions at https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/spack-guide.html but in the step 'spack ${scope_args} install gcc' , I get the following error:

`==>Warning: setting 'compiler:', 'target:' or 'provider:' preferences in a package-specific section of packages.yaml is deprecated, and will be removed in v0.23.

	These preferences will be ignored by Spack, and can be set only in the 'all' section of the same file. You can run:

		$ spack audit configs

	to get better diagnostics, including files:lines where the deprecated attributes are used.

	Use requirements to enforce conditions on specific packages: https://spack.readthedocs.io/en/latest/packages_yaml.html#package-requirements

==> Error: Preference for version 3.22.2 does not match any known version of cmake (in its package.py or any external)
`

I have tried to install cmake=3.22.2 separately but I get the error 'E: Version '3.22.2' for 'cmake' was not found' .

Could you please tell me how to fix this?

**Comment by yantosca** [comment]
@garvitagarwal290: I will try to build a set of libraries with the latest Spack to see if we need to update the instructions on ReadTheDocs.  That will have to wait until after the IGC11 meeting in June.  I wouldn't be surprised if a recent Spack update broke backwards compatibility with older versions.

**Comment by jinlx** [comment]
Hi @yantosca , I ran into the same issue while using the latest version of Spack. I was wondering what specific Spack version was used for the current ReadTheDocs instructions. Would it be helpful to list the recommended Spack version in the documentation to avoid confusion?
