### ISSUE TITLE
When using git clone --recurse-submodules https://github.com/geoschem/GCClassic.git, an error occurs and the download fails

### ISSUE THREAD

**Issue by yangning-code** [geoschem/geos-chem#2310]
### Your name

Ning Yang

### Your affiliation

JNU

### Please provide a clear and concise description of your question or discussion topic.

When using git clone --recurse-submodules https://github.com/geoschem/GCClassic.git, an error occurs and the download fails
![error](https://github.com/geoschem/geos-chem/assets/51811371/731a4ca3-ae7c-4d11-969c-375956187359)

**Comment by yantosca** [comment]
Thanks for writing @yangning-code.  This looks like a network error.  Did this just happen once or does it happen repeatedly?

**Comment by yangning-code** [comment]
Thank you very much! @yantosca 
This is indeed an error caused by network problems.

**Comment by yantosca** [comment]
Thanks @yangning-code.  We can close out this issue now.
