### ISSUE TITLE
Parameterized Effective Radius not accounting OPOA when SVPOA is activated

### ISSUE THREAD

**Issue by yuanjianz** [geoschem/geos-chem#2314]
### Your name

Yuanjian Zhang

### Your affiliation

WashU

### What happened? What did you expect to happen?

https://github.com/geoschem/geos-chem/blob/1ef3d7f88da95ca2425267fc4f96bd1524fc985f/GeosCore/aerosol_mod.F90#L890-L894
Here the OM is essentially OCPISOA, which is already calculated above according to SOA schemes(simplesoa, complexsoa and complexsoa_svpoa). The current procedure misses handling complexsoa_svpoa where OCPI is replaced by OPOA.

### What are the steps to reproduce the bug?

N/A

### What GEOS-Chem version were you using?

14.4.0

### What environment were you running GEOS-Chem on?

Local cluster

### What compiler and version were you using?

gcc 10.2.0

### Will you be addressing this bug yourself?

Yes

### In what configuration were you running GEOS-Chem?

Other (please explain in additional information section below)

### What simulation were you running?

Full chemistry

### As what resolution were you running GEOS-Chem?

N/A

### What meterology fields did you use?

Other (please explain in additional information section below)

### Additional information

Quick fix can be provided. Also tagging @Haihui-Zhu for confirmation.

**Comment by yantosca** [comment]
Closing out this issue since PR #2315 has been merged into the GEOS-Chem 14.5.0 development stream.
