### ISSUE TITLE
MEGAN extension is turned on by default in GCHP run directory

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#2319]
### Your name

Bob Yantosca

### Your affiliation

Harvard + GCST

### What happened? What did you expect to happen?

The HEMCO MEGAN extension is turned on by default when creating a GCHP run directory.  Found by @yuanjianz.

Offline biogenic emissions are recommended for standard full-chemistry GCHP simulations. Having both offline biogenic VOC and MEGAN turned on may double count some emissions.

### What are the steps to reproduce the bug?

Created a GCHP run directory and look at the HEMCO_Config.rc

### What GEOS-Chem version were you using?

14.4.0

### What environment were you running GEOS-Chem on?

Local cluster

### What compiler and version were you using?

gcc10

### Will you be addressing this bug yourself?

Yes

### In what configuration were you running GEOS-Chem?

GCHP

### What simulation were you running?

Full chemistry

### As what resolution were you running GEOS-Chem?

14.4.0

### What meterology fields did you use?

MERRA-2

**Comment by yuanjianz** [comment]
I would suggest that this happens to other configurations like GCClassic as well. See:

https://github.com/geoschem/geos-chem/blob/1ef3d7f88da95ca2425267fc4f96bd1524fc985f/run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem#L197

**Comment by msulprizio** [comment]
This was originally done on purpose for the implementation of MOH in version 12.7 (see pull request #175 and commit https://github.com/geoschem/geos-chem/pull/175/commits/3e2a48f06cd6b5533fa12a7f5a351c7684347baa). From that commit message:

>Update initialization phase to not define certain species (ISOP, ACET, ALD2, C2H4, LIMO, MTPA, MTPO, PRPE, SESQ, SOAP, SOAS, EOH) when the OFFLINE_BIOGENICVOC option is turned on in HEMCO_Config.rc. This will allow use of offline biogenic VOC emissions for those species and online MEGAN emissions will be used for the rest of the species. Right now, just MOH from MEGAN will be fed back into the model and the remaining monoterpene species, methyl butenol, formic acid, and acetic acid will be used for diagnostic purposes only.

At that time, MOH was not included in the offline biogenic emissions so we still needed to call MEGAN to compute the emissions for just that species. MOH is now included in the offline biogenic VOC files (I'm not sure of the exact date of when that occurred) so I'm confirming that we no longer need to call MEGAN when offline biogenic emissions are used.

**Comment by msulprizio** [comment]
A fix for this can go into `dev/no-diff-to-benchmark` since offline emissions are not used in benchmark simulations.

**Comment by yantosca** [comment]
Thanks @msulprizio for confirming.

**Comment by msulprizio** [comment]
The fix for this (#2372) has been merged into 14.4.2. We can close this issue.

In a separate PR, @lizziel will fix a lingering issue where HEMCO_Diagn.rc for MOH still lists the MEGAN extension as its source instead of base emissions (i.e. offline emissions).

```
EmisMOH_Biogenic   MOH    108    -1  -1   2   kg/m2/s  MOH_emission_flux_from_biogenic_sources
```

should be 

```
EmisMOH_Biogenic   MOH      0    4  -1   2   kg/m2/s  MOH_emission_flux_from_biogenic_sources

```

**Comment by laura-hyesung-yang** [comment]
@msulprizio @yantosca Hi Melissa and Bob,

Could I ask you a question regarding this? My HEMCO_Config.rc also has `OFFLINE_BIOGENICVOC` set as `true` and `108 MEGAN on`. As Melissa pointed out, MOH exists in `OFFLINE_BIOGENICVOC`. If this is the case, does `OFFLINE_BIOGENICVOC` overrides online MEGAN computation? I think this is the case because HEMCO_Diag.rc has `EmisMOH_Biogenic   MOH    108    -1  -1   2   kg/m2/s  MOH_emission_flux_from_biogenic_sources
`. When I check HEMCO_Diag.rc MOH biogenic entry, it gives 0 everywhere. Thank you!

**Comment by msulprizio** [comment]
@laura-hyesung-yang It depends on which version of HEMCO you are using. If you're using a version after HEMCO 3.5.0 (GEOS-Chem 14.0.0) then your code should include this code in `HEMCO/Extensions/hcox_megan_mod.F90` introduced in commit https://github.com/geoschem/HEMCO/commit/7d8d8d7c7fb6a80e184bcab7d1c13dcbb9731bd7. 

```
          IF ( .not. Inst%OFFLINE_BIOGENICVOC ) THEN
             Inst%IDTMOH  = HcoIDs(I)
             WRITE(MSG,*) '   MOH        = ',TRIM(SpcNames(I)),Inst%IDTMOH
          ELSE
             WRITE(MSG,*) '   MOH will be obtained from ' // &
                          'offline biogenic VOC emissions'
          ENDIF
```

Therefore, if OFFLINE_BIOGENIC that will be used over the MEGAN emissions. You can confirm this by checking your log file and looking for the message "[species] will be obtained from offline biogenic VOC emissions." You will need to turn offline biogenic emissions off if you prefer to use MEGAN emissions instead.

You will also need to make sure the entry in HEMCO_Diagn.rc matches what is used in HEMCO. If MEGAN emissions are used set ExtNr=108 in `HEMCO_Diagn.rc`, but if offline biogenic emissions are used then set ExtNr=0.

**Comment by laura-hyesung-yang** [comment]
@msulprizio Thank you, Melissa!
