### ISSUE TITLE
OCPISOA and TotalOC not correctly represented in benchmark

### ISSUE THREAD

**Issue by yuanjianz** [geoschem/geos-chem#2321]
### Your name

Yuanjian Zhang

### Your affiliation

WashU

### OCPISOA
OCPISOA in benchmark simulation (simpleSOA and complexSOA are both carried) double counts ISOAAQ as was in PM2.5.
https://github.com/geoschem/geos-chem/blob/1ef3d7f88da95ca2425267fc4f96bd1524fc985f/GeosCore/aerosol_mod.F90#L764-L799
ISOAAQ should be added inside the elseif above to avoid this double-counting.

### TotalOC
TotalOC only includes Isoprene SOA OC in complexSOA_nonSVPOA, where both POA and OPOA are not present.
https://github.com/geoschem/geos-chem/blob/1ef3d7f88da95ca2425267fc4f96bd1524fc985f/GeosCore/diagnostics_mod.F90#L2189-L2200
It should match what is happening in aerosol_mod.F90
https://github.com/geoschem/geos-chem/blob/1ef3d7f88da95ca2425267fc4f96bd1524fc985f/GeosCore/aerosol_mod.F90#L502-L511

### What are the steps to reproduce the bug?

run a fullchem benchmark simulation

### What GEOS-Chem version were you using?

14.4.0

### What environment were you running GEOS-Chem on?

Local cluster

### What compiler and version were you using?

gcc 10.2.0

### Will you be addressing this bug yourself?

Yes

### In what configuration were you running GEOS-Chem?

Other (please explain in additional information section below)

### What simulation were you running?

Full chemistry

### As what resolution were you running GEOS-Chem?

N/A

### What meterology fields did you use?

Other (please explain in additional information section below)

**Comment by yantosca** [comment]
Thanks @yuanjianz for this.  Would you be able to prepare a PR for this?

**Comment by yuanjianz** [comment]
@yantosca Yes, I combine the two OA-related pull requests together. See #2315 .

**Comment by yantosca** [comment]
Closing this issue as PR #2315 has been merged into the GEOS-Chem 14.5.0 development stream.
