### ISSUE TITLE
Goes-Chem input data

### ISSUE THREAD

**Issue by ymxu-atm** [geoschem/geos-chem#2334]
### Your name

Yiming

### Your affiliation

Purdue University

### What happened? What did you expect to happen?

I am trying to download the input data for CO2 simulation from 2003 to 2016 by dry-run. While I cannot download some files, such as: /HEMCO/GFED4/v2023-03/2003/GFED4_dailyfrac_gen.025x025.200303.nc  or  /HEMCO/GFED4/v2023-03/2003/GFED4_dailyfrac_gen.025x025.200303.nc.
I cannot download these for from 2003-2009. I have tried all the data portal.

### What are the steps to reproduce the bug?

To download input data by dry-run. My simulation is from 2003-2016.

### What GEOS-Chem version were you using?

14.2.3

### What environment were you running GEOS-Chem on?

Local cluster

### What compiler and version were you using?

gcc 9.3.0

### Will you be addressing this bug yourself?

Yes

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

CO2

### As what resolution were you running GEOS-Chem?

4*5

### What meterology fields did you use?

MERRA-2

**Comment by lizziel** [comment]
Hi Yiming - According to the data [README](http://geoschemdata.wustl.edu/ExtData/HEMCO/GFED4/v2023-03/README) there is no data available prior to 2010. Climatology files are provided in the GFED4/v2023-03 folder to use outside of the valid data range.

**Comment by yantosca** [comment]
Thanks @lizziel and @ymxu-atm.  Yes, the GFED data only goes back a few years to 2010.  There are other biomass burning products available (e.g. GFAS, QFED) that may go back further.  Or as @lizziel said, you can use a climatology.

I'll close out this issue now.  Thanks again!
