### ISSUE TITLE
new particle formation nucleation

### ISSUE THREAD

**Issue by 1392403848** [geoschem/geos-chem#2339]
### Your name

chenzirui

### Your affiliation

student

### Please provide a clear and concise description of your question or discussion topic.

Dear sir,
    I want to work on a project related to new particle formation using GEOS-Chem. I'm considering using the TOMAS module to study the nucleation process. I need to incorporate various chemical mechanisms to simulation new particle formation, but I'm unsure how to integrate nucleation mechanisms into the TOMAS module. Do I need to modify the TOMAS code myself?

**Comment by yantosca** [comment]
Thanks for writing and thanks for your patience.  Most of us were at the IGC11 meeting earlier in June. 

I am tagging @BettyCroft, who is our contact for the TOMAS simulation and perhaps can give you a better perspective than I can.

**Comment by BettyCroft** [comment]
Thank you for your message and interest in TOMAS. You can go ahead and add additional nucleation mechanisms by modifying the code in tomas_mod.F90 (in the GeosCore directory). Near line 140 of tomas_mod.F90 there are switches for some of the nucleation mechanisms that are currently in use (e.g., bin_nuc and. tern_nuc). Those existing mechanisms can serve as an example for adding further nucleation mechanisms.

**Comment by yantosca** [comment]
Closing out this issue
