### ISSUE TITLE
GFED4 files for the year 2023

### ISSUE THREAD

**Issue by hazel008** [geoschem/geos-chem#2351]
### Your name

Hansen Cao

### Your affiliation

University of York

### What happened? What did you expect to happen?

Hello,

Just found the GFED4 files for the year 2023 are named for the year 2022. I am not sure if it's a naming error or if those files are actually copied from the files of 2022.
<img width="725" alt="Screenshot 2024-06-26 at 11 21 18" src="https://github.com/geoschem/geos-chem/assets/17845904/d54e022b-6479-4dc6-a143-52f8bf218167">
Can anyone take a look at this? Thanks!

### What are the steps to reproduce the bug?

ran standard simulation for the year of 2023

### What GEOS-Chem version were you using?

14.4.0

### What environment were you running GEOS-Chem on?

Local cluster

### What compiler and version were you using?

gcc

### Will you be addressing this bug yourself?

Yes, but I will need some help

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

Full chemistry

### As what resolution were you running GEOS-Chem?

4x5

### What meterology fields did you use?

MERRA-2

**Comment by msulprizio** [comment]
Hi @hazel008. This had been corrected at Harvard but was never propagated to the WashU site. Sorry about that. I transferred over the 2023 files just now. 

@yidant could you please fix the file permissions at WashU so users can access them?

**Comment by yidant** [comment]
Hi @hazel008 and @msulprizio , thanks for letting me know! The files are now available on WashU portal.

**Comment by yantosca** [comment]
Thanks @yidant @hazel008 and @msulprizio!  I think this was just an issue at WashU.  I've confirmed that on the Harvard portal the data is for 2023.

**Comment by msulprizio** [comment]
Thanks all. I will close out this issue. @hazel008 please let us know if you run into any other problems.
