### ISSUE TITLE
geos-chem 14.4.0 +APM "Infinity in DO_CLOUD_CONVECTION"

### ISSUE THREAD

**Issue by zion0210** [geoschem/geos-chem#2354]
### Your name

zion0210

### Your affiliation

ASU

### Please provide a clear and concise description of your question or discussion topic.

Hello!

I have a problem with running geos-chem 14.4.0 +APM
I build the code as follows:
```
cmake ../CodeDir -DRUNDIR=.. -DAPM=y 
make -j 
make install
```
I chose fullchem and APM in config dialog windows.
I got 2 problems:
1. 
```
APM not found BIOMASS_BCPO
APM not found ANTHROPOGENIC_BCPO
APM not found BIOMASS_OCPO
APM not found ANTHROPOGENIC_OCPO

```
2.
```
Infinity in DO_CLOUD_CONVECTION!
K, IC, Q(K):    4 253           NaN   APMCTBC1
GEOS-Chem ERROR: Error encountered in "Do_Cloud_Convection"!
 -> at Do_Convection (in module GeosCore/convection_mod.F)

```
I also studied component of subroutine convection_mod.F and  discovered infinity for part of the values of the Q array for the species 253.

Maybe, if APMCTBC1 is SO4, then infinity values appear because the SO4 global emission source not described in HEMCO_Config.rc.

I attached HEMCO_Config.rc(HEMCO_Config.log) and run.log to the message.

What can I do to complete my simulation?

Regards,
zion0210
[run.log](https://github.com/user-attachments/files/16029376/run.log)
[HEMCO_Config.log](https://github.com/user-attachments/files/16029400/HEMCO_Config.log)

**Comment by yantosca** [comment]
Thanks for writing @zion0210.  I would recommend first compiling again with `cmake -DAPM=y -DCMAKE_RELEASE_TYPE=Debug`.  This will add some extra error checking into the executable which may shed some more light on the situation.

I think APMCTBC1 is one of the black carbon species.  I am not an expert in APM, I would defer to @ganluoasrc (Gan Luo) who is one of the developers.

**Comment by ganluoasrc** [comment]
@zion0210 @yantosca 

APMCTBC1 refers to sulfate coated on BC. In APM, sulfate is formed by SO2 chemistry. No special emission for APM sulfate in HEMCO is needed.

The error is caused by the missing of BC and OC emissions in GC14-APM. We used BC and OC diagnostics from HEMCO to generate BC and OC emissions for APM. It seems BIOMASS_BCPO, ANTHROPOGENIC_BCPO ... are no longer available in diagnostics from HEMCO in GC14. So, you got the notices of 
APM not found BIOMASS_BCPO
APM not found ANTHROPOGENIC_BCPO
APM not found BIOMASS_OCPO
APM not found ANTHROPOGENIC_OCPO

To fix the error, we need to get BC and OC diagnostics from HEMCO. @yantosca, do you have any suggestions? Does GC14 use new variables to replace BIOMASS_BCPO, ANTHROPOGENIC_BCPO ...?

**Comment by yantosca** [comment]
Thanks @ganluoasrc.  I wonder if those were manual diagnostics in HEMCO, which have since been disabled. Tagging @msulprizio, who may know more.

**Comment by msulprizio** [comment]
@yantosca @ganluoasrc It looks like the BIOMASS_BCPO, etc. fields were previously defined in `hcoi_gc_diagn_mod.F90` but were removed in commit https://github.com/geoschem/geos-chem/commit/c8fed808634fbb4b9beddd56c99cc5f0f3c15a95 as part of the initial removal of BPCH diagnostics back in version 12.6.0. Essentially, those fields were manual diagnostic fields that were defined in HEMCO to store the emission fluxes from whichever biomass burning inventory is used. To resolve the first errors mentioned above, we would need to restore these manual diagnostics -- see [these lines of code](https://github.com/geoschem/geos-chem/blob/55f61408dd9922f23b1566058de7b0c9627caf53/GeosCore/hcoi_gc_diagn_mod.F90#L2270-L2287) for an example.

**Comment by yantosca** [comment]
Thanks @msulprizio.  We can add those back in wrapped in an `#ifdef APM` block.

**Comment by ganluoasrc** [comment]
Thanks @msulprizio and @yantosca.

Yes, I agree that we can add those back as that suggested by Bob.

The problem of infinity in Q array is associated with BC and OC run without emissions. After adding BC and OC emissions, the associated problem may be solved.
