### ISSUE TITLE
RRTMG and CH4 radiative forcing

### ISSUE THREAD

**Issue by nuistsky** [geoschem/geos-chem#2356]
### Your name

tiant

### Your affiliation

Nanjing University of Information Science & Technology

### Please provide a clear and concise description of your question or discussion topic.

"I want to simulate the radiative forcing due to CH4 emissions reductions. To save simulation time, I hope to choose 'ch4' under simulation type, but there is no RRTMG radiation transfer option available afterwards. Do I must to select the full chemistry simulation in order to open the RRTMG option for radiative forcing simulation?

**Comment by yantosca** [comment]
Thanks for writing @nuistsky.  Yes, the RRTMG option is only compatible with the full-chemistry simulation, as you need to have the aerosols species defined for the RRTMG to work.

**Comment by yantosca** [comment]
Closing out this issue
