### ISSUE TITLE
[BUG/ISSUE] Can't recompile KPP mechanism

### ISSUE THREAD

**Issue by Duseong** [geoschem/geos-chem#236]
Hello, 

GEOS-Chem could not be compiled after I added a reaction in the KPP mechanism. The KPP compilation process was successful (KPP_log.txt). However, GEOS-Chem raised an error, from a KPP generated file (gckpp_Global.F90 file, please see the attached GC12.0.0_log.txt). One possible reason seemed to be related to the prod/loss families, because the gckpp_Monitor.F90 file showed a lot of RRnnn species (please see the attached file in the directory Tropchem_recompiled). So I tried to compile KPP after removing all the prod/loss related families in gckpp.kpp file (lines under #FAMILIES). Again KPP was successfully compiled, and gckpp_Monitor.F90 file did not show any RRnnn reactions, but GEOS-Chem raised another error from KPP directory. But this time, at least it compiled gckpp_Global.F90 file, but another error came from another file (gckpp_HetRates.F90, GC12.0.0_log_withoutPL.txt). 

Because GEOS-Chem used above was not the out-of-the-box GEOS-Chem version, I tried to test this with the latest GEOS-Chem without any modification. Even though I tested this with the latest GEOS-Chem 12.7.1, it also showed a lot of RRnnn species in gckpp_Global.F90 file. I attached a zipped file which has two directories - original KPP tropchem directory and another KPP tropchem directory after I did build_mechanism.sh without any changes in the code. In this version, I didn't change anything, just re-complied KPP. 

I am using NCAR Cheyenne server (hardware info is available here:https://www2.cisl.ucar.edu/resources/computational-systems/cheyenne), with ifort 18.0.5. 
I also tested this in another private server (Intel(R) Xeon(R) CPU E5-2697 v3 @ 2.60GHz, ifort 15.0.0), but there was the same problem.

Could you help me figure out this issue? Thanks a lot for your help!

Best,
Duseong

[GEOS-Chem_KPP.zip](https://github.com/geoschem/geos-chem/files/4295413/GEOS-Chem_KPP.zip)
[KPP_log.txt](https://github.com/geoschem/geos-chem/files/4295415/KPP_log.txt)
[GC12.0.0_log.txt](https://github.com/geoschem/geos-chem/files/4295416/GC12.0.0_log.txt)
[GC12.0.0_log_withoutPL.txt](https://github.com/geoschem/geos-chem/files/4295417/GC12.0.0_log_withoutPL.txt)

**Comment by yantosca** [comment]
Thanks for writing.  I think when you cloned KPP you got the master branch, but you should be on the GC_updates branch.  In GC_updates, we removed the equivalence statements that are causing the problem.   Try
```
git checkout GC_updates
```
and then rebuild KPP from scratch.

**Comment by Duseong** [comment]
Thanks, but I couldn't find the GC_updates branch, am I missing something? It happened in both GC 12.0.0 and 12.7.1. It looks like I only have the master branch. 

> git checkout GC_updates
error: pathspec 'GC_updates' did not match any file(s) known to git.

>git branch
* master

**Comment by yantosca** [comment]
The GC_updates branch is in the KPP mechanism repo: https://github.com/geoschem/KPP.  Make sure that you are using this branch to create the KPP files that you will add into the GEOS-Chem KPP/Custom folder.

**Comment by Duseong** [comment]
Thanks, I checked that kpp was set to the GC_updates branch. 
git branch
* GC_updates
  master

Do I have to do something in advance in this KPP (kpp-2.2.3_01) folder before changing files in Code.12.7.1_KPP/KPP/Custom folder?

**Comment by yantosca** [comment]
Are you following the steps described here? 
 http://wiki.geos-chem.org/FlexChem#Adding_chemical_mechanisms_in_FlexChem  

I think that is most of what you need to do.

**Comment by Duseong** [comment]
Yes, I followed the steps on that wiki page. Just in case, I followed it again from rebuilding kpp to execute build_mechanism.sh but I got the same problem (found many RRnnn reactions in gckpp_Monitor.F90).

**Comment by Duseong** [comment]
Finally, I figured out the reason, thanks for your help! It was caused by the old kpp version I used. I downloaded the kpp on 21-Jul-2018, and I thought I used the up-to-date kpp because the version numbers were the same (kpp I downloaded in 2018 also has the version number of kpp-2.2.3_01). Downloading new kpp helped solve this problem.

**Comment by yantosca** [comment]
Great, glad it works!  I'll close out the issue.
