### ISSUE TITLE
[QUESTION] Parametrization of Meteorology in classic Geos Chem

### ISSUE THREAD

**Issue by gopikrshnangs44** [geoschem/geos-chem#237]
First of all, I am a beginner to GEOS CHEM and I have simulated the model giving GEOS_FP 4x5 meteorology input.

I am simulating geos chem for the global domain and nesting it for the Indian region with tropchem and classic Geos Chem 12.7.0. 

I have to parametrize it to my region by considering cloud parametrization, model micropysics etc into the scenario. 

The important thing I need to know is whether GEOS_CHEM simulates meteorology or it takes the input and calculates the chemistry accordingly like a coupled model, for eg., WRF with WRF-chem likewise GEOS with GEOS Chem.

And I am giving input from compute canada. How can I take into account these things so that to test the sensitivity of the model?

The things to change are 
1. Microphysics
2. cloud parametrization
3. Aerosol schemes

**Comment by lizziel** [comment]
GEOS-Chem Classic uses offline meteorology for chemistry. Some meteorology fields not included in the offline files are calculated online from the inputs. I suggest taking a looking at file GeosCore/dao_mod.F to see what those are, looking specifically for variables starting with "State_Met%".

Regarding how to test the sensitivity of the model with respect to microphysics, cloud parameterization, and aerosol schemes, this is broad topic. I suggest adding the "discussion" label to this issue and see if anyone in the community chimes in. You can also consider contacting one of the [GEOS-Chem Working Groups](http://acmg.seas.harvard.edu/geos/geos_working_groups.html).
