### ISSUE TITLE
Future emissions in GEOS-Chem - RCP unusable

### ISSUE THREAD

**Issue by r-pound** [geoschem/geos-chem#2370]
### Your name

Ryan Pound

### Your affiliation

University of York

### What happened? What did you expect to happen?

I was looking at running a GCC model with RCP emissions however these files are not on the WashU data server despite being options in HEMCO_Config. After some searching I found the last model version to reference RCP emissions was 12.9.1 which was a bug fix to keep them working, I also discovered Issue #1847 which states that the RCP data was archived but can be retrieved from a link to Globus endpoint. Following this link leads to a page saying the linked endpoint has been deleted. 

#1752 points to CMIP6 SSP scenarios being the future emissions which are being actively maintained and accessible on the Rochester servers. 

It looks like the RCP option is now legacy but the HEMCO_Config file generated for run directories (as of 14.4) still contains the extension switches and configurations to use the RCP inventories. 

If the RCP emissions are now defunct and SSP is the preferred method, it makes sense to remove the RCP entries from the HEMCO_Config.rc templates, the empty folder on the WashU server and the page on the [wiki](https://wiki.seas.harvard.edu/geos-chem/index.php/RCP_future_emissions_scenarios).  

tagging @ltmurray as the future emissions in GEOS-Chem expert

### What are the steps to reproduce the bug?

N/A

### What GEOS-Chem version were you using?

14.4

### What environment were you running GEOS-Chem on?

Local cluster

### What compiler and version were you using?

n/a

### Will you be addressing this bug yourself?

No

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

Full chemistry

### As what resolution were you running GEOS-Chem?

4x5

### What meterology fields did you use?

MERRA-2

**Comment by msulprizio** [comment]
Thanks for pointing this out @r-pound. @yidant are the RCP files still available somewhere at WashU? The globus endpoint that Saptarshi pointed to in [#1847](https://github.com/geoschem/geos-chem/issues/1847#issuecomment-1608488875) is no longer available.

I will defer to @ltmurray and the Emissions WG chairs (@eamarais, @Jaegle, Jintai Lin) on recommendations for removing RCP entries from HEMCO_Config.rc in our next release.

**Comment by yidant** [comment]
Thanks @r-pound and @msulprizio ! We are not able to share this Globus endpoint anymore but I have transferred the RCP files to WashU portal. You can get the files here now: http://geoschemdata.wustl.edu/ExtData/HEMCO/RCP/v2020-07/

**Comment by msulprizio** [comment]
Thanks @yidant. I will close out this issue.

@r-pound and others, feel free to comment here or open a new issue if problems persist and/or if we need to discuss retiring RCP as an option.
