### ISSUE TITLE
If I want to turn ON daily (GFED_daily) GFED fires, do I need to turn OFF monthly (GFED4) inside the HEMCO_Config.rc?

### ISSUE THREAD

**Issue by Hemrajbhattarai** [geoschem/geos-chem#2373]
### Your name

Hemraj Bhattarai

### Your affiliation

CUHK

### Please provide a clear and concise description of your question or discussion topic.

Hi GC team,
I am trying to turn ON the daily GFED (modified with SAGE) fire emissions, but get confused about whether I need to (i) turn OFF monthly if I have to turn ON daily. Or do I need to (ii) turn ON monthly while I still keep the daily ON.

This is screenshot from HEMCO_Config:
![image](https://github.com/user-attachments/assets/1dd1293a-4261-4167-9828-9f004aac9919)

![image](https://github.com/user-attachments/assets/dda981c8-005f-45f8-a4bb-6b5016e4a5ec)

**Comment by yantosca** [comment]
Thanks for writing @Hemrajbhattarai.  You would need to turn on both the `GFED` and `GFED_daily` options.  The daily option applies a daily scale factor to the monthly-mean data inputs.  So you have to tell HEMCO to read both the `GFED_*` and `GFED_FRAC_DAY` data as specified in `HEMCO_Config.rc`.

**Comment by Hemrajbhattarai** [comment]
Thank you so much Bob. Now, I am confident that my approach is right.

**Comment by yantosca** [comment]
Thanks @Hemrajbhattarai.  I'll close out this issue now.
