### ISSUE TITLE
What does xyL * mean in HEMCO_Cnfig.rc?

### ISSUE THREAD

**Issue by helpyuan** [geoschem/geos-chem#2376]
### Your name

liumy

### Your affiliation

CAMS

### Please provide a clear and concise description of your question or discussion topic.

Hi all,

I want to use the **CEDS01** emission inventory  for fullchem simulation, and I found the relevant `HEMCO_Config.rc` file on the webpage (http://[geoschemdata.wustl.edu/ExtData/HEMCO/CEDS/v2024-06/config/HEMCO_Config.rc](http://geoschemdata.wustl.edu/ExtData/HEMCO/CEDS/v2024-06/config/HEMCO_Config.rc)).

Firstly, I would like to confirm if the version of **CEDS01** `v2024-06` is available? Because I found that this version seems to be consistent with the content of `v2023-04`. (http://geoschemdata.wustl.edu/ExtData/HEMCO/CEDS/)

Secondly, there is a variable `xyL*` in the srcDim file of `HEMCO_Config.rc`. I learned from the manual that `xy` represents horizontal data and `L` represents data that can be applied to vertical coordinates. Does `*` mean it applies to all vertical layers? That is, `L*` represents the emission of a 2D field to all vertical layers. I don't know if my understanding is correct.

I will be grateful for any help.

**Comment by yantosca** [comment]
Thanks for writing.  We have a description of this feature under `SrcDim` at this ReadTheDocs page:

- https://hemco.readthedocs.io/en/stable/hco-ref-guide/hemco-config.html#base-emissions

**Comment by helpyuan** [comment]
Thanks @yantosca. I have reviewed this document and I would like to confirm if `*` represents the entire vertical layer?

**Comment by yantosca** [comment]
@helpyuan: Thanks for the followup question.  So `xyL*` is used for the vertical allocation of emissions (such as CEDS).  From the code:
```F90
             ! Wildcard tells HEMCO to emit same value to all emission levels
             ! A scale factor should be applied to distribute the emissions
             ! vertically
```
I think this info may not have made it onto ReadTheDocs.  We'll try to push a fix for that.

**Comment by yantosca** [comment]
@helpyuan: Also the CEDS emissions are going to be updated.  There was a problem with the original data, which now has been resovled.  We will bring this into 14.5.0.

**Comment by helpyuan** [comment]
Thanks @yantosca! So now CEDS data is not recommended for use? Or which version of CEDS data should I use in this directory (http://geoschemdata.wustl.edu/ExtData/HEMCO/CEDS/)?

**Comment by helpyuan** [comment]
Thanks @yantosca! I think all my problems have been solved.
