### ISSUE TITLE
Is the 'Photolysis reactions' section of 'Update chemical mechanisms with KPP' out of date?

### ISSUE THREAD

**Issue by bethkillen** [geoschem/geos-chem#2378]
### Your name

Beth Killen

### Your affiliation

UNSW Sydney

### Please provide a clear and concise description of your question or discussion topic.

I am a new GEOS-Chem user and I have been trying to add new photolysis reactions into GEOS-Chem. I followed the instructions on the KPP readthedocs and my new reactions were not added to the simulation. According to the KPP page, the parameter JVN_ in the module 'Headers/CMN_FJX_MOD.F90' needs to be updated to match the total number of photolysis reactions. However, since GEOS-Chem now uses CLOUDJ as the default, I believe that the module that needs updating is 'Core/cldJ_cmn_mod.F90'. Once I updated JVN_ in this module, the new reactions were added successfully. 
Is this the correct procedure? If so, could the KPP instructions be updated to reflect this change?

**Comment by yantosca** [comment]
Thanks for writing @bethkillen.  Yes, that section is out of date.  The `JVN_` parameter is now found in `[Cloud-J/src/Core/cldj_cmn_mod.F90](https://github.com/geoschem/Cloud-J/blob/main/src/Core/cldj_cmn_mod.F90)`.  We can update the documentation.

**Comment by yantosca** [comment]
Hi @bethkillen.  I've pushed a fix for the documentations.  You can see them at:

- https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/using-kpp-with-gc.html#photolysis-reactions
- https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/using-kpp-with-gc.html#using-kpp-reference-section

**Comment by bethkillen** [comment]
@yantosca That's great, thank you!
