### ISSUE TITLE
KPP integration failed in Carbon simulation type for GEOS-Chem 14.2.3. 

### ISSUE THREAD

**Issue by jjp1987** [geoschem/geos-chem#2381]
### Your name

jjp1987

### Your affiliation

research institute

### Please provide a clear and concise description of your question or discussion topic.

I want to run global Carbon simulation with GEOS-Chem 14.2.3, but in the Release  mode I got an error: 
```console
GEOS-Chem ERROR: KPP integration failed!                                                             
 -> at Chem_Carbon_Gases (in module GeosCore/carbon_gases_mod.F90) 
===============================================================================                      
GEOS-Chem ERROR: Error encountered in "Chem_Carbon_Gases"!                                           
 -> at Do_Chemistry  (in module GeosCore/chemistry_mod.F90)                                          
===============================================================================                      
                                                                                                     
===============================================================================                      
GEOS-CHEM ERROR: Error encountered in "Do_Chemistry"!                                                
STOP at  -> at GEOS-Chem (in GeosCore/main.F90)                                                      
===============================================================================
```
But if I run the Carbon simulation in the Debug mode, there won't be this error anymore.

In the GEOS-Chem 14.4.1, I got the same problem.

**Comment by jjp1987** [comment]
I used the ifort version 17.0.5, netcdf version is 4.9.0。

**Comment by yantosca** [comment]
Thanks for writing @jjp1987.  Can you attach your `geoschem_config.yml`, `HEMCO_Config.rc`, `HISTORY.rc` and log file from the run that failed to this issue?  Also if you have the output from the configure and build steps, please attach that as well.  We do not have enough information to know what went wrong.

Also, please doublecheck that you used `-DMECH=carbon` when you ran cmake to build the executable.

**Comment by jjp1987** [comment]
I used the -DMECH=carbon whem build the executable by cmake.

**Comment by jjp1987** [comment]
I used the -DMECH=carbon whem build the executable by cmake.

**Comment by Liyl2** [comment]
Hi, @jjp1987!  I encountered the same problem with GCClassic v14.4.3, KPP integration failed!  May I ask how your problem was resolved? I'm really looking forward to your reply, thanks in advance!
