### ISSUE TITLE
EmisDST[N]_Natural not populated when changing from offline dust emissions to online

### ISSUE THREAD

**Issue by sdeastham** [geoschem/geos-chem#2382]
### Your name

Sebastian Eastham

### Your affiliation

Imperial College London

### What happened? What did you expect to happen?

Online emissions of dust in GCHP function as expected, but the EmisDST[N]_Natural field is not populated.

### What are the steps to reproduce the bug?

Clone the GCHP run directory
Switch off offline dust emissions in HEMCO
Enable the DustDead extension in HEMCO
Enable the Emissions collection in HISTORY.rc and change its output frequency to hourly
Run a one-hour simulation
Inspect the EmisDST1_Natural variable and observe a field of zeros
Inspect the EmisDST1_Total variable and observe dust emissions which appear to include the natural source

### What GEOS-Chem version were you using?

14.4.0

### What environment were you running GEOS-Chem on?

Local cluster

### What compiler and version were you using?

gcc 11.3.0

### Will you be addressing this bug yourself?

Yes

### In what configuration were you running GEOS-Chem?

GCHP

### What simulation were you running?

Full chemistry

### As what resolution were you running GEOS-Chem?

c24

### What meterology fields did you use?

MERRA-2

**Comment by lizziel** [comment]
Thanks @sdeastham, I'm going to reopen this issue and tag with documentation todo. We can try to improve communication of this in our docs. For GCHP I can also add a check in setCommonRunSetting.sh to make sure HEMCO_Diagn.rc and HEMCO_Config.rc are consistent. We don't have a similar for GC-Classic however.

**Comment by yantosca** [comment]
Thanks @sdeastham and @lizziel.  I've also confirmed this is an issue in GEOS-Chem Classic as well.  I'll have to think about where in HEMCO is the best place to add an error trap for this.

**Comment by msulprizio** [comment]
This was addressed by https://github.com/geoschem/geos-chem/pull/2402 and included in 14.4.3.
