### ISSUE TITLE
Update to Cloud-J v8.0 in GEOS-Chem

### ISSUE THREAD

**Issue by lizziel** [geoschem/geos-chem#2386]
### Your name

Lizzie Lundgren

### Your affiliation

Harvard University

### Provide a clear and concise overview of the new feature requested.

This feature request is to update to Cloud-J v8.0 in GEOS-Chem. See Michael Prather's publication ["An updated cloud-overlap photolysis module for atmospheric chemistry models, UCI Cloud-J v8.0, with near-UV H2O absorption"](https://datadryad.org/stash/dataset/doi:10.7280/D1Q398). Cloud-J v8.0 was not developed off of our [Cloud-J on GitHub](https://github.com/geoschem/cloud-J/) which uses CMake and is used in GEOS-Chem. Changes are not under version control. I will work to incorporate the science updates in v8.0 into the GitHub repository for use in GEOS-Chem. I am targeting the 14.5 release.

### Reference(s)

Prather, Michael (2023). An updated cloud-overlap photolysis module for atmospheric chemistry models, UCI Cloud-J v8.0, with near-UV H2O absorption [Dataset]. Dryad. https://doi.org/10.7280/D1Q398

### Will you be implementing this feature yourself?

Yes

**Comment by yantosca** [comment]
Thanks @lizzie..  We can now close out this issue as Cloud-J v8 is merged into the GEOS-Chem 14.5.0 development stream.
