### ISSUE TITLE
[BUG/ISSUE] HEMCO timing error for offline seasalt and lightning NOx 

### ISSUE THREAD

**Issue by ayhwong** [geoschem/geos-chem#239]
## Describe the bug
The model crashed at the start of Sep 2014 trying to read OFFLINE_LIGHTNING/v2019-01/MERRA2/2014/FLASH_CTH_MERRA2_0.5x0.625_2014_08.nc4 (no filed with valid timestamp). The date of offline seasalt file is also off, reading seasalt_05.20140801.nc at 20140901, but did not directly crash the model 

## To Reproduce

**Compilation commands**
1. make build

**Run commands**
1. ./geos > gcRun.log

## Expected behavior
Model crash when reading offline lightning NOx file at the start of September

## Error messages
```
HEMCO: Opening /projectnb/atmchem/GC/gc_data/ExtData/GEOS_2x2.5/MERRA2/2014/09/MERRA2.20140901.A3mstE.2x25.nc4
HEMCO: Opening /projectnb/atmchem/GC/gc_data/ExtData/GEOS_2x2.5/MERRA2/2014/09/MERRA2.20140901.I3.2x25.nc4
HEMCO: Opening /projectnb/atmchem/GC/gc_data/ExtData/GEOS_2x2.5/MERRA2/2014/09/MERRA2.20140902.I3.2x25.nc4
HEMCO: Opening /projectnb/atmchem/ayhwong_real/data_misc/Global_Land_Cover/processed_map/xlai_2014.nc
HEMCO: Opening /projectnb/atmchem/GC/gc_data/ExtData/HEMCO/OFFLINE_LIGHTNING/v2019-01/MERRA2/2014/FLASH_CTH_MERRA2_0.5x0.625_2014_08.nc4
 Error in HCOIO_DATAREAD called from HEMCO ReadList_Fill: FLASH_DENS
 Error in ReadList_Fill (6) called from HEMCO ReadList_Read
 Error in ReadList_Read called from hco_run
===============================================================================
GEOS-Chem ERROR: Error encountered in "HCO_Run"!
 -> at HCOI_GC_Run (in module GeosCore/hcoi_gc_main_mod.F90)

THIS ERROR ORIGINATED IN HEMCO!  Please check the HEMCO log file for
additional error messages!
===============================================================================

===============================================================================
GEOS-Chem ERROR: Error encountered in "HCOI_GC_Run"!
 -> at Emissions_Run (in module GeosCore/emissions_mod.F90)
===============================================================================

===============================================================================
GEOS-CHEM ERROR: Error encountered in "Emissions_Run"!
STOP at  -> at GEOS-Chem (in GeosCore/main.F)
```
## Required information
Please include the following:
 - GEOS-Chem version: 12.7.0
 - Compiler version that you are using: ifort 18.0.0
 - netCDF: 4.6.1, netCDF-Fortran: 4.4.4
 - Computational environment: Boston University Shared Computing Cluster
 - Are you using "out of the box" code, or have you made modifications: 1 line modification in drydep.F, reproduced the same error using "out of the box" code and HEMCO_Config.rc

## Input and log files to attach
For more info, see: http://wiki.geos-chem.org/Submitting_GEOS-Chem_support_requests
[lastbuild.log](https://github.com/geoschem/geos-chem/files/4309334/lastbuild.log)
[input.geos.txt](https://github.com/geoschem/geos-chem/files/4309336/input.geos.txt)
[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/4309337/HEMCO_Config.rc.txt)
[gcRun.log](https://github.com/geoschem/geos-chem/files/4309338/gcRun.log)
[HEMCO.log](https://github.com/geoschem/geos-chem/files/4309340/HEMCO.log)

**Comment by yantosca** [comment]
Thanks for writing.  I believe the MERRA2 offline lightning fields have not been processed yet (they are updated quarterly).  You may need to run with online lightning for year 2019.  

@msulprizio feel free to add any more suggestions.

**Comment by yantosca** [comment]
Ditto for offline seasalt.  I think those emissions only go up to 2017.  I believe they are still being generated by our colleagues at PKU but we haven't gotten the most recent years.

**Comment by yantosca** [comment]
I am closing out this issue.  Feel free to reopen.
