### ISSUE TITLE
question on file sizes/types for MERRA2 at wustl for 2023

### ISSUE THREAD

**Issue by aschuh** [geoschem/geos-chem#2393]
### Your name

Andrew Schuh

### Your affiliation

Colorado State University

### Please provide a clear and concise description of your question or discussion topic.

Upon pulling MERRA2 driving data for GCC, I've noticed that there are strange file sizes for some of the months in 2023 and running a "file" command to determine type seems to imply that the files for some months might be different format than the others?

Compare file types and sizes for http://geoschemdata.wustl.edu/ExtData/GEOS_2x2.5/MERRA2/2023/07/    and  http://geoschemdata.wustl.edu/ExtData/GEOS_2x2.5/MERRA2/2023/02/.  *A3cld* files are around 173MB for july and 45MB for february. This leads to dirs for some months which are twice as large as others.  Seems to only happen in 2023 I think.  Haven't run with them yet, just curious as to why there is a discrepancy.

**Comment by yidant** [comment]
Thanks @aschuh for reporting this! There seems to be some issues happened when producing the files for July 2023. They are fixed now! Feel free to reach out if you find any other issue!
