### ISSUE TITLE
How to set specify reading the restart file every month by setting the timestamp in HEMCO_Config.rc?

### ISSUE THREAD

**Issue by XunZhangNJU** [geoschem/geos-chem#2395]
### Your name

XunZhang

### Your affiliation

Nanjing University

### Please provide a clear and concise description of your question or discussion topic.

In the HEMCO configuration file (HEMCO_Config.rc), how to set specify reading the restart file every month by setting the timestamp and file path.  How to set it up to read the restart file every month in the (((GC_Restart switch regions? Thanks.
![image](https://github.com/user-attachments/assets/da1b6bac-dbfd-4ba4-a7c7-b5011cdb7e50)

**Comment by lizziel** [comment]
Hi @XunZhangNJU - The GEOS-Chem Classic restart file is only read at the very beginning of the run. The model does not read restart files more than once. If you would like to read in data that is stored in restart files for whatever reason then you would need to add it as a new input within `HEMCO_Config.rc` similar to how it is done for other input files, e.g. entries in the `CHEMISTRY_INPUTS` section.
