### ISSUE TITLE
How to solve Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

### ISSUE THREAD

**Issue by ChenBHXMU** [geoschem/geos-chem#2396]
### Your name

Baihua

### Your affiliation

Xiamen University 

### Please provide a clear and concise description of your question or discussion topic.

Dear @yantosca,

Thank you for taking the time to read my message. I am facing some difficulties with Geos-chem and would like to ask you a question.

I  modified  the start_date and end_date to [20190601, 000000] and [20190601, 002000], respectively.  I also modified the “frequency” and "duration" in History.rc. The DiagnFreq in HEMCO_Config.rc also modified to "End".  However, the issue is: HEMCO ERROR: Cannot find field with valid time stamp in ./Restarts/GEOSChem.Restart.20190601_0000z.nc4. I am very anxious and don't know how to solve it. Although I have read many previous questions from Github, my issue seems to be a missing HEMCO files. However, I downloaded the data using `./download_data.py log.dryrun --washu`.

<img width="566" alt="Untitled" src="https://github.com/user-attachments/assets/d7ca075d-349c-4897-a5e7-eda18511294b">

[Attachment.zip](https://github.com/user-attachments/files/16345801/Attachment.zip)

Best regards,
Baihua

**Comment by lizziel** [comment]
Hi @ChenBHXMU, this issue is likely a problem with the date of your restart file. In GEOS-Chem Classic you must have a restart file that has a time value in the file equivalent to your start date. Please see the GEOS-Chem Classic ReadTheDocs page on restart files for instructions on restart files: [https://geos-chem.readthedocs.io/en/stable/gcclassic-user-guide/restart-files-gc.html](https://geos-chem.readthedocs.io/en/stable/gcclassic-user-guide/restart-files-gc.html).

**Comment by yantosca** [comment]
@ChenBHXMU: Have you resolved your issue?

**Comment by ChenBHXMU** [comment]
The issue has been resolved. Thank you for your response.

**Comment by ChenBHXMU** [comment]
> @ChenBHXMU: Have you resolved your issue?

The issue has been resolved. Thank you for your response.

**Comment by ChenBHXMU** [comment]
Dear Yantosca,


The issue has been resolved. Thank you for your response.


Best regards,
Baihua Chen




简单→愛
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "geoschem/geos-chem"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月30日(星期二) 晚上10:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [geoschem/geos-chem] How to solve Program received signal SIGSEGV: Segmentation fault - invalid memory reference. (Issue #2396)





 
@ChenBHXMU: Have you resolved your issue?
