### ISSUE TITLE
Corrupted biovoc_05.20230701.nc data at WashU

### ISSUE THREAD

**Issue by nicodgomez** [geoschem/geos-chem#2401]
### Your name

Nicolás Damián Gómez

### Your affiliation

Instituto de Investigaciones Fisicoquímicas Teóricas y Aplicadas

### What happened? What did you expect to happen?

I have been facing the following error while running Full Chemistry simulation for the period 01/07/2023-01/08/2023. 

HEMCO ERROR: Cannot find field with valid time stamp in /mnt/d/ExtData/HEMCO/OFFLINE_BIOVOC/v2021-12/0.5x0.625/2023/07/biovoc_05.20230701.nc - Cannot get field BIOGENIC_ACET. Please check file name and time (incl. time range flag) in the config. file.

I attach the following files: 
geoschem_config.yml
HEMCO_Config.rc 
HEMCO_Config.rc.gmao_metfields
GC_48.log (log file with the error message)

Also while inspecting the HEMCO/OFFLINE_BIOVOC/v2021-12/0.5x0.625/2023/07/biovoc_05.202307dd.nc files at WashU, I have noticed that biovoc_05.20230701.nc has a size of 126 K, while all other emissions from month 07 have a size of approximately 54 M. Then, I suspect there is an error with biovoc_05.20230701.nc file.   

### What are the steps to reproduce the bug?

Running Full Chemistry GCClassic 14.2.2 with provided geoschem_config.yml, HEMCO_Config.rc , HEMCO_Config.rc.gmao_metfields files and History.rc files. 

### Please attach any relevant configuration and log files.

[HEMCO_Config.rc.gmao_metfields.txt](https://github.com/user-attachments/files/16420862/HEMCO_Config.rc.gmao_metfields.txt)
[HEMCO_Config.txt](https://github.com/user-attachments/files/16420863/HEMCO_Config.txt)
[HISTORY.txt](https://github.com/user-attachments/files/16420864/HISTORY.txt)
[GC_48.log](https://github.com/user-attachments/files/16420869/GC_48.log)
[geoschem_config.txt](https://github.com/user-attachments/files/16420920/geoschem_config.txt)

### What GCClassic version were you using?

14.2.2

### What environment were you running GCClassic on?

Personal computer

### What compiler and version were you using?

GNU Fortran 8.4.0, under Windows Subsystem for Linux.

### Will you be addressing this bug yourself?

Yes

**Comment by yidant** [comment]
Thanks @nicodgomez for reporting this! The biovoc_05.20230701.nc file was corrupted. I've reproduced this file. Feel free to redownload it at WashU portal.

**Comment by nicodgomez** [comment]
Thank you @yantosca and @yidant, I have downloaded the updated biovoc_05.20230701.nc file and rerun the calculation. A new error appeared related to seasalt_05.20230701.nc file. The error message says,

HEMCO ERROR: Cannot find field with valid time stamp in /mnt/d/ExtData/HEMCO/OFFLINE_SEASALT/v2019-01/0.5x0.625/2023/07/seasalt_05.20230701.nc - Cannot get field SEASALT_SALA. Please check file name and time (incl. time range flag) in the config. file.

Checking seasalt_05.20230701.nc file I have noticed that it has a size of 53 K, much lower than other seasalt files for the same period. Revising other HEMCO files, also soilnox_05.20230701.nc file has a strange size of 53 K. 

Then, I suspect that also seasalt_05.20230701.nc and soilnox_05.20230701.nc files may be corrupted or incomplete. 

I attach the output log file with the error message. 
[GC_48_2.log](https://github.com/user-attachments/files/16435336/GC_48_2.log)

Thank you.

**Comment by yidant** [comment]
Thanks @nicodgomez ! You're right! I've fixed all offline emissions for this day. Please check again.

**Comment by nicodgomez** [comment]
Thanks @yidant for the help, I was able to proceed with the calculation without errors.  :)).

**Comment by yantosca** [comment]
Thanks @nicodgomez and @yidant!  I'll close out this issue.
