### ISSUE TITLE
Store aerosol *.dat files in new data directory CHEM_INPUTS/Aerosol_Optics

### ISSUE THREAD

**Issue by lizziel** [geoschem/geos-chem#2403]
### Your name

Lizzie Lundgren

### Your affiliation

Harvard University

### Provide a clear and concise overview of the new feature requested.

The aerosol dat-files, such as `so4.dat`, are currently stored in `CHEM_INPUTS/FAST_JX`. However, we no longer support Fast-JX except for the mercury simulation, and the files are also used when using Cloud-J.

I propose moving these files to a new data directory in `CHEM_INPUTS` at the same levels as `FAST_JX` and `CLOUD_J`. I propose the name `Aerosol_Optics`. I can put this update into 14.5.0.

### Reference(s)

None

### Will you be implementing this feature yourself?

Yes

**Comment by yantosca** [comment]
Thanks @lizziel, I agree, this will be much cleaner and less confusing.

**Comment by msulprizio** [comment]
This was addressed by https://github.com/geoschem/geos-chem/pull/2426 which has now been merged into the `dev/14.5.0` branch.
