### ISSUE TITLE
Add tropopause level to satellite diagnostic SatDiagn

### ISSUE THREAD

**Issue by eamarais** [geoschem/geos-chem#2407]
### Your name

Eloise Marais

### Your affiliation

UCL, UK

### Provide a clear and concise overview of the new feature requested.

Minor update request to also include option to output tropopause level (TropLev) in the SatDiagn collection. 

Patch created in stdout format after implementing and testing this in v14.1.0 attached. Very minor coding updates required. 
[add_satdiagntroplev_patch.patch](https://github.com/user-attachments/files/16469257/add_satdiagntroplev_patch.patch)

### Will you be implementing this feature yourself?

Yes

**Comment by yantosca** [comment]
Thanks @eamarais!  I'll apply the patch and open a PR.

**Comment by yantosca** [comment]
Thanks @eamarais!  We can now close this issue as PR #2410 has been merged into the GEOS-Chem "no-diff-to-benchmark" development stream.
