### ISSUE TITLE
KPP giving a segfault during build_mechanism.sh

### ISSUE THREAD

**Issue by JFBrewer** [geoschem/geos-chem#2408]
### Your name

Jared Brewer

### Your affiliation

University of Minnesota

### What happened? What did you expect to happen?

In order to take advantage of the recent fixes to the Satellite Diagnostic (#2369 ), I've started working with the branch `dev/no-diff-to-benchmark`.

### What are the steps to reproduce the bug?

When I try to rebuild the carbon mechanism in kpp using `build_mechanism.sh` (without making any changes at all), I keep getting a segfault on the `kpp gckpp.kpp` line. I initially assumed this was due to an outdated version of KPP (I was using 3.0.2) but updating kpp to 3.1.1 hasn't fixed the problem. I don't know how to troubleshoot here. Notably, this isn't happening in 14.1.1 with either version of KPP.

### What GEOS-Chem version were you using?

dev/no-diff-to-benchmark

### What environment were you running GEOS-Chem on?

Local cluster

### What compiler and version were you using?

gcc 8.2.0

### Will you be addressing this bug yourself?

Yes, but I will need some help

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

Carbon

### As what resolution were you running GEOS-Chem?

2x2.5

### What meterology fields did you use?

GEOS-FP

**Comment by JFBrewer** [comment]
I was able to get around this issue by copying in an already-built `KPP/carbon` folder from 14.3.0. At this point I'm uncertain whether this is something only on my end or a real problem. If no-one else replicates it, it's definitely possible I've got something weird going on.

**Comment by yantosca** [comment]
Hi @JFBrewer, wondering if you may need to increase your stacksize memory.  Try `ulimit -s unlimited` and then rebuild.  Otherwise I'm not sure what else could be causing this.
