### ISSUE TITLE
[QUESTION] How to link GEOS-Chem-12.7.1 to CMAQ

### ISSUE THREAD

**Issue by katiegrace-3000** [geoschem/geos-chem#241]
I saw a web page addressed the tool about using GEOS-Chem output as boundary condition to CMAQ, http://wiki.seas.harvard.edu/geos-chem/index.php/Linking_GEOS-Chem_to_CMAQ, while it seems for previous version of GEOS-Chem, I wondered is there any source I could look for regarding the new version of GEOS-Chem to CMAQ. Or is it a good idea to modify pncglobal2cmaq.py provided by the above web page?  Thanks a lot.

**Comment by yantosca** [comment]
Thanks for writing.  Unfortunately, the GEOS-Chem Support Team does not have the expertise to how to generate GC outputs for CMAQ.  I would ask the [GEOS-Chem Chemistry Working Group](http://wiki.seas.harvard.edu/geos-chem/index.php/Chemistry_Working_Group) -- in particular Barron Henderson @barronh, who is the author of geos2cmaq.py.

**Comment by katiegrace-3000** [comment]
Thanks a lot. Bob.

**Comment by barronh** [comment]
I have moved the functionality of pncglobal2cmaq to aqmbc, which allows for easier updating of the definitions to keep up with advancements in both CMAQ and GEOS-Chem. 

I have finished gas-phase mapping for 12.7 and am finishing aerosols.  If you have your own mappings, please consider sharing them via that page.

I'm making a jupyter notebook (via google colab) that demonstrates the use and will post an update here when that is complete (later today). That will make it clear how to install and run.

**Comment by yantosca** [comment]
Thanks @barronh!  We can post that link on the wiki as well.

**Comment by barronh** [comment]
All:

There is a working jupyterlab notebook the aqmbc repo. The link is below. Note that the aerosols part is currently not included. I'll update it when available.

https://github.com/barronh/aqmbc/blob/master/aqmbc_geosv12.ipynb

**Comment by yantosca** [comment]
I am going to close out this issue as there has not been recent activity.  Please feel free to reopen.

**Comment by haohe1982** [comment]
I am new to GEOS-Chem and want to use GEOS-Chem to generate BCs for CMAQ. I successfully installed and run the latest GEOS-Chem 14.0.1 and found this discussion. Looks like link from Barron's post expired. Any update about this issue? Thanks!

**Comment by barronh** [comment]
The IC/BC software was recently updated. Use the root project link below.

https://github.com/barronh/aqmbc/

**Comment by haohe1982** [comment]
Hi Barron,

Thanks for your information. I tried to use the line of ' pip install
https://github.com/barronh/aqmbc.git' to install it under my Anaconda, but
the installation was stuck. Any special environment or software version I
need to use for aqmbc?

 Hao

**Comment by barronh** [comment]
There was a typo in the instructions. It should have been (and has been updated to)

```
pip install git+https://github.com/barronh/aqmbc.git
```

or

```
pip install https://github.com/barronh/aqmbc/archive/refs/heads/main.zip
```

No "special" environment, but you do need Python v3.6 or higher. All the prerequisites will be installed by `pip`. With Anaconda, you may need to separately install `pip`. If you don't have admin rights, you will find the `--user` useful. And, if you have a recent `pip` version, you might find `--prefer-binary` useful.

```
pip install --user --prefer-binary git+https://github.com/barronh/aqmbc.git
```

If your system doesn't recognize `--prefer-binary`, then

```
pip install --user git+https://github.com/barronh/aqmbc.git
```

**Comment by haohe1982** [comment]
Thanks for your help. I have installed the module. Per the instruction on
https://github.com/barronh/aqmbc/, it reads a configuration file named
'gcncv12.cfg' to explain the input/output file directory etc. Could you
please shave a sample of this file?

Hao

**Comment by haohe1982** [comment]
HI Barron,

I figured out how to get the sample file, and please ignore my previous
email. I edited the ' gcncv12.cfg' file (see attached file) per my server
set-up. However when I tried to run the software, it generated the
following error. The differences for my run are: 1)I am using the latest
v14.0.1, but not the v12; 2) my GEOS-Chem outputs are GEOSChem.SpeciesConc,
not GEOSChem.SpeciesBC in the set-up file.  Is my GEOS-Chem set-up not
correct?

Also I believe there should be some place I can define the domain for CMAQ
(e.g., 12US2 is what I want to prepare BCs from GEOS-Chem), but I didn't
find a place to set this variable. I am new to GEOS-Chem so I sincerely
appreciate your help.

############################################################################################################
Geos-chem error:
  File "src/netCDF4/_netCDF4.pyx", line 2463, in
netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in
netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -51] NetCDF: Unknown file format:
b'input/GEOSChem.SpeciesConc.20160101_0000z.nc4'

**Comment by haohe1982** [comment]
Some updates. I figured out the domain definition but aqmbc still failed to
read the GEOS-chem output. Below are the log information.


ozone.umd.edu{hhe}1010: python -m aqmbc gcncv12.cfg
[common]
overwrite = False
verbose = 0
pwd = /data/chemstg67/hhe/geos-chem/cmaq_bc
rcpath = /data/chemstg67/hhe/geos-chem/cmaq_bc
gdnam = 12US2
griddesc = GRIDDESC
vgtop = 5000
vglvls = [
        1.0, 0.9975, 0.995, 0.99, 0.985, 0.98, 0.97, 0.96, 0.95, 0.94,
        0.93, 0.92, 0.91, 0.9, 0.88, 0.86, 0.84, 0.82, 0.8, 0.77,
        0.74, 0.7, 0.65, 0.6, 0.55, 0.5, 0.45, 0.4, 0.35, 0.3,
        0.25, 0.2, 0.15, 0.1, 0.05, 0.0
        ]
vinterp = linear
expressions = [
        "${rcpath}/definitions/gc/gcnc_airmolden.expr",
        "${rcpath}/definitions/gc/gc12_to_cb6r3.expr",
        "${rcpath}/definitions/gc/gc12_soas_to_ae7.expr"
        ]

[source]
input = input/GEOSChem.SpeciesConc.%Y%m%d_0000z.nc4
format = {"format": "gcnc"}
dims = {
        "TSTEP": "time",
        "LAY": "lev",
        "ROW": "lat",
        "COL": "lon"
        }

[ICON]
dates = ["2019-07-01"]
output = ICON/GEOSChem.SpeciesBC.%Y%m%d_0000z.${GDNAM}.ICON.nc

[BCON]
start_date = 2019-07-01
end_date = 2019-07-02
freq = d
output = BCON/GEOSChem.SpeciesBC.%Y%m%d_0000z.${GDNAM}.BCON.nc


Converting input/GEOSChem.SpeciesConc.20190701_0000z.nc4 to BCON/
GEOSChem.SpeciesBC.20190701_0000z.12US2.BCON.nc
open
Traceback (most recent call last):
  File "/data/chemstg67/hhe/python/anaconda3/lib/python3.7/runpy.py", line
193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data/chemstg67/hhe/python/anaconda3/lib/python3.7/runpy.py", line
85, in _run_code
    exec(code, run_globals)
  File
"/data/chemstg67/hhe/python/anaconda3/lib/python3.7/site-packages/aqmbc/__main__.py",
line 36, in <module>
    runcfg(args.config)
  File
"/data/chemstg67/hhe/python/anaconda3/lib/python3.7/site-packages/aqmbc/__init__.py",
line 117, in runcfg
    bc(**opts)
  File
"/data/chemstg67/hhe/python/anaconda3/lib/python3.7/site-packages/aqmbc/bcon.py",
line 182, in bc
    infile = pnc.pncopen(inpath, **format_kw)
  File
"/data/chemstg67/hhe/python/anaconda3/lib/python3.7/site-packages/PseudoNetCDF/_getreader.py",
line 153, in pncopen
    outfile = reader(*args, **kwds)
  File
"/data/chemstg67/hhe/python/anaconda3/lib/python3.7/site-packages/PseudoNetCDF/geoschemfiles/_gcnc.py",
line 213, in __init__
    netcdf.__init__(self, *args, **kwds)
  File
"/data/chemstg67/hhe/python/anaconda3/lib/python3.7/site-packages/PseudoNetCDF/core/_files.py",
line 2471, in __init__
    NetCDFFile.__init__(self, *args, **kwds)
  File "src/netCDF4/_netCDF4.pyx", line 2463, in
netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in
netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -51] NetCDF: Unknown file format:
b'input/GEOSChem.SpeciesConc.20190701_0000z.nc4'

**Comment by barronh** [comment]
Please move this discussion to the aqmbc issues.

**Comment by haohe1982** [comment]
Hi Barron,

Thanks for helping me on this issue. Where should I update (keep track) of
this topic? I didn't find discussion on the aqmbc page (
https://github.com/barronh/aqmbc). Sorry I am new to Github.

**Comment by barronh** [comment]
At the top of any repo, there is "Code", "Issues", etc. You go to "Issues" and open a new issue. Similar to here.
