### ISSUE TITLE
Question about GEOS-FP data in http://geoschemdata.wustl.edu/ repository

### ISSUE THREAD

**Issue by ChangpeiHe** [geoschem/geos-chem#2412]
There are two different file sizes shown here. The smaller file size is more common, but I am not sure if the larger file size indicates an error.
![image](https://github.com/user-attachments/assets/beace30c-947a-498f-94e9-02342c40d860)
![image](https://github.com/user-attachments/assets/c530afb6-acc4-42df-abdd-ede79fc78249)

Looking forward to your reply!

**Comment by yantosca** [comment]
Thanks for writing @ChangpeiHe.  I believe this may be due to some files having been compressed and others not.  @yidant can fill you in with the specifics.

**Comment by yidant** [comment]
Thanks @ChangpeiHe and @yantosca ! Yes, the smaller files are compressed. We want all files to be compressed. I am currently reproducing these files and will replace the larger ones within this week.

**Comment by ChangpeiHe** [comment]
Thanks @yantosca and  @yidant !

**Comment by ChangpeiHe** [comment]
Hi, I have another question. Will larger GEOS-FP files cause inconsistent results in GEOS-Chem compared to smaller files? @yidant

**Comment by yidant** [comment]
Hi @ChangpeiHe! The files are all compressed now!

I don't think there will be any difference. The file content is the same, while the smaller files are optimized for both size and performance using `nccopy`.

**Comment by ChangpeiHe** [comment]
![image](https://github.com/user-attachments/assets/36882773-83a4-4c91-b234-c42dfe67d6c5)
Hi @yidant! I cannot access the updated data.

**Comment by ChangpeiHe** [comment]
Thanks, I can access the data now! The NRT GEOS-FP data facilitate my NRT project. This issue can be closed.

**Comment by yantosca** [comment]
Thanks @ChangpeiHe !
