### ISSUE TITLE
Issue about Configure with CMake and Configure with Make

### ISSUE THREAD

**Issue by InterstellarPenguin** [geoschem/geos-chem#2414]
### Your name

Guo LinYang

### Your affiliation

University of Chinese Academy of 

### What happened? What did you expect to happen?

Hi everyone, im quite new to GC. My GC is GCClassic 14.4.2.  There is an issue about Configuring with CMake

### What are the steps to reproduce the bug?

I have finished Creating run directory
![1](https://github.com/user-attachments/assets/44568a13-3f86-44ee-97eb-8ac24fccd35f)

and then i try to configure with CMake with command 'cmake ../CodeDir -DRUNDIR=..' , but it failed with wrong fortran compiler. 
![image](https://github.com/user-attachments/assets/16cdf0aa-6219-4618-8ce1-2bfbbacb802f)

There is only ifort in my server, so i changed fortran compiler in CMakecache.txt,
![image](https://github.com/user-attachments/assets/94ff11e6-29fc-4d2a-9778-2011be953819)

 and then use 'cmake ../CodeDir -DRUNDIR=..' command again. in this time it works,
![3](https://github.com/user-attachments/assets/79ba7b92-20f9-4a92-847c-1e0ee0e30e75)

 but when I enter the command 'make -j' , an error occurs. 
![4](https://github.com/user-attachments/assets/f541a2ff-d330-4fe0-9b36-70b72b675297)

Looking forward for your helps, thanks!

### What GEOS-Chem version were you using?

14.4.2

### What environment were you running GEOS-Chem on?

Local cluster

### What compiler and version were you using?

ifort version 15.0.2

### Will you be addressing this bug yourself?

Yes

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

Full chemistry

### As what resolution were you running GEOS-Chem?

4x5

### What meterology fields did you use?

MERRA-2

**Comment by yantosca** [comment]
Thanks for writing @InterstellarPenguin.  I suspect the netCDF library you are using was built with a different compiler than you are using to compile GEOS-Chem.  You say you are using ifort 15.0.2 but the `CMAKE_Fortran_COMPILER` shows that the version of ifort that you are using is version 2021.3.0.  You can confirm this with:
```console
$ ifort -V
```
I would recommend switching to the same compiler that was used to build the netCDF library, and then try recompiling GEOS-Chem.

**Comment by InterstellarPenguin** [comment]
![image](https://github.com/user-attachments/assets/f1ab3912-4151-49d7-a3ba-92d1cbe13a35)
Here is my ifort version. If I use gfortran, will this problem be avoided? Thanks for your help!

**Comment by yantosca** [comment]
This should go in your home directory and not in the code directory.

**Comment by InterstellarPenguin** [comment]
Thanks! @yantosca
