### ISSUE TITLE
Difficulty in reaction rate calculation

### ISSUE THREAD

**Issue by ktravis213** [geoschem/geos-chem#2419]
### Your name

Katherine Travis

### Your affiliation

NASA LaRC

### What happened? What did you expect to happen?

I wrote a reaction rate in fullchem_RateLaws.F90 as follows:
```F90
       k4 = 7.45e+7_dp *exp(-4430_dp*(1/TEMP-1/298_dp))
```
I also tried to separate it into parts. 
```F90
       k4b = (TEMP-1/298_dp)
       k4c = exp(-4430_dp*k4b)
       k4 = 7.45e+7_dp *k4c 
```
In either case, if T is 298.55, the answer should be k4 = 7.65E7. However the code outputs k4 = 16.89. Printing out k4b and k4c above, the issue is in k4b which is calculated by fortran as 3.45E-3 when it should be 9.79E-5.  Is there something wrong with my organization in fortran that causes this?

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/ktravis1/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/ktravis1/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">

289.55118
--

</body>

</html>

### What are the steps to reproduce the bug?

Print out the following somewhere in fullchem_RateLaws.F90
```F90
       k4b = (TEMP-1/298_dp)
       k4c = exp(-4430_dp*k4b)
       k4 = 7.45e+7_dp *k4c 
```
Calculate in excel or somewhere else the same code.  Hopefully that reproduces my issue.

### What GEOS-Chem version were you using?

14.4.1

### What environment were you running GEOS-Chem on?

Local cluster

### What compiler and version were you using?

ifort: intel/19.1.3.304

### Will you be addressing this bug yourself?

Yes, but I will need some help

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

Full chemistry

### As what resolution were you running GEOS-Chem?

0.25 Asia

### What meterology fields did you use?

GEOS-FP

**Comment by ktravis213** [comment]
Noticed that I had a typo when I made this issue - k4b = (1/TEMP-1/298_dp).

**Comment by yantosca** [comment]
Thanks for writing @ktravis213.  I've made a test program with your equations as you have them:
```F90
PROGRAM Katie

  IMPLICIT NONE

  INTEGER, PARAMETER :: dp = KIND( 0.0d0 )   ! Double precision
  
 
  ! Test with T = 298.55
  CALL PrintValues( 298.55_dp )

  CONTAINS

    SUBROUTINE PrintValues( temp )

      ! Argument
      REAL(dp), INTENT(IN) :: temp

      ! Local variables
      REAL(dp) :: k4, k4b, k4c

      ! Temparature
      PRINT*, REPEAT( '#', 60 )
      PRINT*, '### temp               : ', temp
      PRINT*, '###'

      ! 1-line calculation
      k4 = 7.45e+7_dp * exp(-4430_dp*(1/TEMP-1/298_dp))
      PRINT*, '### 1/TEMP                 : ', 1/TEMP
      print*, '### 1/298_dp               : ', 1/298_dp
      PRINT*, '### 1/TEMP-1/298_dp        : ', 1/TEMP - 1/298_dp
      PRINT*, '### exponential term       : ', exp(-4430_dp*(1/TEMP - 1/298_dp))
      PRINT*, '### k4, in one line        : ', k4
      PRINT*, '###'

      ! 1-line calculation, with 
      k4 = 7.45e+7_dp * exp(-4430_dp*(1.0_dp/TEMP - 1.0_dp/298.0_dp))
      PRINT*, '### 1.0_dp/TEMP             : ', 1.0_dp/TEMP            
      PRINT*, '### 1.0_dp/298_dp           : ', 1.0_dp/298.0_dp
      PRINT*, '### 1.0_dp/TEMP-1.0_/298_dp : ', 1.0_dp/TEMP - 1.0_dp/298.0_dp
      PRINT*, '### exponential term        : ', exp(-4430_dp*(1.0_dp/TEMP - 1.0_dp/298.0_dp))
      PRINT*, '### k4, in one line         : ', k4

    END SUBROUTINE PrintValues

END PROGRAM Katie
```
Which gives as output:
```console
 ############################################################
 ### temp               :    298.55000000000001     
 ###
 ### 1/TEMP                 :    3.3495226930162453E-003
 ### 1/298_dp               :                     0
 ### 1/TEMP-1/298_dp        :    3.3495226930162453E-003
 ### exponential term       :    3.5955972859675217E-007
 ### k4, in one line        :    26.787199780458035     
 ###
 ### 1.0_dp/TEMP             :    3.3495226930162453E-003
 ### 1.0_dp/298_dp           :    3.3557046979865771E-003
 ### 1.0_dp/TEMP-1.0_/298_dp :   -6.1820049703318475E-006
 ### exponential term        :    1.0277647331307509     
 ### k4, in one line         :    76568472.618240938     
```
So what is happening is that this is integer division.  I think you need to use e.g. `298.0_dp` instead of `298_dp` (since the compiler will think that is an integer because it doesn't have a decimal place).  Then this will do an integer division, where 1/298 = 0.

**Comment by ktravis213** [comment]
Thank you so much!  I can't believe I couldn't figure this out!!!

**Comment by yantosca** [comment]
No worries @ktravis213.  I guessed that it had something to do with operator precedence but I wouldn't have found it unless I made the toy example program.  I'll close this out.
