### ISSUE TITLE
[FEATURE REQUEST] Add diagnostic collection for mean OH (or add to existing collection)

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#242]
Right now the GEOS-Chem "Classic" model writes the mean OH value out to the log file at the end of the run. But this output is not supported in GCHP.

We should add a diagnostic collection (or add to an existing collection) the fields that are required to compute mean OH. This will facilitate benchmarking of GEOS-Chem Classic and GCHP.  The diagnostic output can be treated in the same way by the GCPy benchmarking scripts.

I have this slated for 12.9.0 for now.  It may slip to 13.0.0 depending on time constraints.

**Comment by msulprizio** [comment]
Daniel Jacob also suggested saving out gridded CH4 loss frequency or alternatively CH4 rates (then post-processing divide rates by CH4 concentration to get CH4 frequency) in order to compute CH4 lifetime against tropospheric OH.

**Comment by yantosca** [comment]
In commit c59b91793d3ce38e3392ddaab8b00c6b4f6f33c6, we have introduced modifications to save out the Global Mean OH concentration and the Methylchloroform (aka MCF) Lifetime.  This is done by activating the new Metrics collection in HISTORY.rc (here shown for GEOS-Chem-Classic):

```
#==============================================================================
# %%%%% THE Metrics COLLECTION %%%%%
#
# Diagnostics for chemistry metrics such as global mean OH concentration,
# MCF lifetime, and CH4 lifetime.
#
# This diagnostic collection should always be left on.
# Use the run-directory script ./metrics_fullchem.py to print results.
#
# Commented-out diagnostic fields are available to use, but are not 
# necessary for computing the relevant full-chemistry metrics.
#
# Available for full-chemistry and CH4 simulations only.
#==============================================================================
  Metrics.template:           '%y4%m2%d2_%h2%n2z.nc4',
  Metrics.format:             'CFIO',
  Metrics.frequency:          'End',
  Metrics.duration:           'End',
  Metrics.mode:               'time-averaged'
  Metrics.fields:             'AirMassColumnFull             ', 'GIGCchem',
                              'MCFlossInTrop                 ', 'GIGCchem',
                              'MeanOHcolumnFull              ', 'GIGCchem',
                              #'AirMassColumnTrop             ', 'GIGCchem',
                              #'CH4massColumnTrop             ', 'GIGCchem',
                              #'MeanCH4columnTrop             ', 'GIGCchem',
                              #'MeanOHcolumnTrop              ', 'GIGCchem',
::
```
This will archive column output for air mass in the chemistry grid, mean OH in the chemistry grid, and MCF loss rate in the troposphere.  To compute the overall global values, use the script `metrics_fullchem.py`, which ships with each full-chemistry run directory. This will print output such as:
```
==============================================================================
GEOS-Chem FULL-CHEMISTRY SIMULATION METRICS

Simulation start : 2019-07-01 00:00:00z
Simulation end   : 2019-07-01 02:00:00z
============================================================================== 

Mass-weighted Global Mean OH = 11.22845264439 x 10^5 molec cm-3

MCF lifetime in troposphere  = 5.5392 years
```
In subsequent commits, we will add diagnostic output for CH4 lifetime.

NOTE: The Metrics collection has also been added to the HISTORY.rc template files for GCHP (but using frequency=010000 and duration=010000 instead of "End", which GCHP does not support).

**Comment by yantosca** [comment]
The metrics collection now contains the following fields:
```
  Metrics.fields:             'AirMassColumnFull        ', 'GIGCchem',     # Fullchem and CH4 simulations
                              'CH4emission              ', 'GIGCchem',     # CH4 simulations only
                              'CH4massColumnFull        ', 'GIGCchem',     # CH4 simulations only
                              'CH4massColumnTrop        ', 'GIGCchem',     # CH4 simulations only
                              'LossOHbyCH4columnTrop    ', 'GIGCchem',     # Fullchem and CH4 simulations
                              'LossOHbyMCFcolumnTrop    ', 'GIGCchem',     # Fullchem and CH4 simulations
                              'OHwgtByAirMassColumnTrop ', 'GIGCchem',     # Fullchem and CH4 simulations
::
```
The latest commits in this line of development are 5dc604a880bf298d51238c423fecb94c4c62f57f and 1f85f2c5fd8af48a7d14d2c813618e6bf96dd0d8.

**Comment by yantosca** [comment]
Also, a single Python script (`metrics.py`) can now compute the relevant metrics for both CH4 or fullchem simuations.  This example is from a CH4 specialty simulation run.

![metrics1](https://user-images.githubusercontent.com/5880296/93391431-22dfb080-f83d-11ea-881e-ddc57cbe4e6b.png)
