### ISSUE TITLE
Environment File: Unable to Detect "flex" module and more

### ISSUE THREAD

**Issue by Kheryevan** [geoschem/geos-chem#2421]
### Your name

Yulei Yang

### Your affiliation

Hong Kong University of Science and Technology (Guangzhou)

### What happened? What did you expect to happen?

I was trying to revise the environment file to accomodate the local cluster of our university, but I was unable to detect "flex" module while loading all the modules. "Flex" can't be detected by using command "module spider" nor "spack find". However, if you try "flex --version", somehow it returns flex 2.6.4. I have tried to uninstall and install it again via Spack, I still can't make it work nor make it detectable by the commands above.

### What are the steps to reproduce the bug?

Was trying to create an environment file from this sample:
https://geos-chem.readthedocs.io/en/latest/getting-started/login-env-files-gnu.html

But the issue of "flex" being "undetectable" appears.

Also, for the context, I was not able to load other modules until I drop the "-fasrc01" part from them. In addition, I was only able to load netcdf, not both netcdf-c and netcdf-fortran.

Respectfully and many thanks.

### What GEOS-Chem version were you using?

14.4.0

### What environment were you running GEOS-Chem on?

Local cluster

### What compiler and version were you using?

GCC 10.2.0

### Will you be addressing this bug yourself?

Yes

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

Full chemistry

### As what resolution were you running GEOS-Chem?

4x5

### What meterology fields did you use?

MERRA-2

**Comment by yantosca** [comment]
Thanks for writing @Kheryevan.  On several Linux distros, the `flex` executable program is usually found at the `/usr/bin/flex` path.  However the `flex` library file (`lfl.a`) may not be included by default. 

If you build `flex` with Spack then you should be able to load it with 
```console
$ spack load flex
```
You can also create a module file for it with 
```console
$  spack module lmod refresh -y
```
which will make a module file for the Lmod module manager.  You will also need to update the `MODULEPATH` environment variable to point to the directory where modules are built.  The modules are in the subdirectories of `$SPACK_ROOT/share/spack/lmod/$ARCH`, where `$ARCH` is the architecture.  You can add an `if` statement to your environment file that will set this for you, such as:

```bash
if [[ ! "spack" =~ "${MODULEPATH}" ]]; then
    if [[ $- = *i* ]] ; then
	echo "... Updating module paths, please wait ..."
    fi
    export SPACK_MODULE_ROOT="${SPACK_ROOT}/share/spack/lmod/linux-rocky8-x86_64"
    export MODULEPATH+=":${SPACK_MODULE_ROOT}/Core"
    export MODULEPATH+=":${SPACK_MODULE_ROOT}/gcc/10.2.0"
fi
```
etc.

**Comment by yantosca** [comment]
@Kheryevan, on my cluster we are using Rocky Linux 8 so the `$ARCH` setting is `linux-rocky8-x86_64`.  Also, I would recommend using the `TARGET=x86_64` command in Spack so that it will build the libraries for the generic x86_64 architecture and not a specific chipset.

**Comment by Kheryevan** [comment]
Thank you so much for your feedback, @yantosca. I have reinstalled everything, and now flex appears in "$ spack find".

If there are no error message, should I assume that the modules have been loaded successfully? I have tried using "$ nf-config --help" to test and have seen the expected output. However, if you try using "$ module list", it would return "no modules loaded". 
Thank you.

**Comment by Kheryevan** [comment]
I have come across a useful command of "spack find --loaded", which tells loaded packages through spack.

**Comment by yantosca** [comment]
Thanks for the feedback @Kheryevan.  Yes, if you use `spack load`, it may not show a message like if you use the Lmod `module load ...` command.  But as long as there is no error you should be OK.  Also thanks for the command `spack find --loaded`, I didn't know that one.  :-)  I'll close this out now.  Feel free to reach out again if you still encounter issues.
