### ISSUE TITLE
How to get extinction coefficients from RRTMG in GEOS-Chem

### ISSUE THREAD

**Issue by neyest** [geoschem/geos-chem#2422]
### Your name

Soroush

### Your affiliation

University of California, Riverside

### Please provide a clear and concise description of your question or discussion topic.

Hi there,

I'm using standard full chemistry GEOS-Chem. I was wondering if there's any way to get aerosol extinction coefficient in GEOS-Chem output. Checking HISTORY.rc, I don't see the extinction coefficient in RRTMG fields.

Alternatively, as mentioned here https://github.com/geoschem/geos-chem/issues/1283, AOD per vertical layer would be enough to calculate the extinction coefficient. However, RRTMG AOD (RadAODWL1_PM) in the output file is already vertically integrated. Is there any option to have layered AOD in outputs, instead of total AOD?

Please let me know if you have any questions.

Best,
Soroush

**Comment by yantosca** [comment]
Thanks @neyest for re`aching out.  I am not very familiar with the RRTMG module or with aerosols in general, as I only focus on coding.  Tagging @sdeastham who will probaly know more about this topic.

**Comment by sdeastham** [comment]
Sorry that I didn't see this @yantosca !

Regarding the question, you can use the GC standard AOD diagnostics which do output AOD in each layer. You can then get extinction as necessary. The AOD values in RRTMG, stored in the variable `RTODAER`, are all derived from the standard AOD outputs (see https://github.com/geoschem/geos-chem/blob/6bbd81fae499fc2cb566722be1a38a1567bf6e4c/GeosCore/aerosol_mod.F90#L1815-L1838).

**Comment by neyest** [comment]
Thank you @sdeastham and @yantosca !

**Comment by yantosca** [comment]
Thanks @neyest and @sdeastham.  I'll close out this issue as resolved.
