### ISSUE TITLE
Differences between different versions of the "soilNOx.fert_res.generic.05x05.nc" file

### ISSUE THREAD

**Issue by hlbutterfly** [geoschem/geos-chem#2429]
### Your name

Ling Huang

### Your affiliation

Shanghai University

### Please provide a clear and concise description of your question or discussion topic.

I am recently looking at the fertilizer input file to drive the BDSNP algorithm to calculate the soil NO emissions. It seems that two versions of the nitrogen reservoir files (both with file name "soilNOx.fert_res.generic.05x05.nc") are provided by GEOS-Chem:
version 2012: https://ftp.as.harvard.edu/gcgrid/data/ExtData/GEOS_NATIVE/soil_NOx_201208/
version 2014 (last modified 2021): https://ftp.as.harvard.edu/gcgrid/data/ExtData/HEMCO/SOILNOX/v2014-07/

The v2012 file has a unit of "ng/m2" while the v2014 file has a unit of "kg/m3". According to the readme, the unit in the v2014 file (changed from kg/m2 to kg/m3) was because of the automatic unit conversion of HEMCO. Other than that, these two files should be identical. However, when I compared the totals between the two files, they differ roughly by a factor of 2 (with the v2014 file being higher). 

I am wondering what got changed between the two versions. And if I want to use the file to drive offline BDSNP algorithm, which file should I use?

Thanks
Ling

**Comment by yantosca** [comment]
Thanks for writing @hlbutterfly.  I believe the 2012 files use ng N/m2 and the 2014 files use kg NO/m3.  Thus the 2014 files would have(14 + 16) / 14 = 2x higher totals.

We would recommend using the 2014 data (`HEMCO/SOILNOX/v2014-07/`) as this has been validated with GEOS-Chem benchmark simulations.

**Comment by hlbutterfly** [comment]
Thanks for the reply, Bob!

My follow-up question is: if using the 2014 data, is there any intermediate step within GEOS-Chem that converts NO to N before the BDSNP algorithm? I am asking this because I want to make sure the scaling factor (0.0068) is derived based on the value of 'NO' or the value of 'N'. 

![image](https://github.com/user-attachments/assets/81ee6b00-f92f-4b76-a62d-ba9be2e51200)

Thanks again!
Ling

**Comment by yantosca** [comment]
@hlbutterfly.  I do not know the answer to how the scaling factor was computed.    I presume it is based on NO.  You can do a quick calculation to verify.

**Comment by hlbutterfly** [comment]
@yantosca Thanks Bob! The information on NO vs. N is really helpful.
