### ISSUE TITLE
[BUG/ISSUE] Nested model crashes with error in PARANOX_LUT

### ISSUE THREAD

**Issue by MaggieMarvin** [geoschem/geos-chem#243]
## Description
I'm running the GC (v12.5.0) nested model at 0.25x0.3125 resolution for September 2014 but the model crashes several days into the simulation with an error in PARANOX_LUT.

From HEMCO.log:
```
 HEMCO ERROR: LUT error: Fracnox should be between 0 and 1!
 ERROR LOCATION: PARANOX_LUT
```
From run.log:
```
 PARANOX_LUT: fracnox =   -999.000000
 This occured at grid box           49          40
 Lon/Lat:    105.00000000000000      -0.25000000000000000
 SZA 5 hours ago :   -60.0001373
 SZA at this time:    15.0007019
 The two SZAs should not be more than 75 deg apart!
 If they are, your restart SZA might be wrong.
 You can try to coldstart PARANOx by commenting
 all PARANOX_SUNCOS entries in your HEMCO
 configuration file.
```
To run the nested model, for Southeast Asia (lat=[-10,24] and lon=[90,140]), I use boundary conditions and restart files from the global model run at 2x2.5 degree resolution, which completed successfully for all months of 2014. I start the nested model from GC and HEMCO restart files for 20140901 and the model crashes on starting 20140924. I have also run the nested model for March of 2014 with no problems. 

Help would be very much appreciated, thanks!

## Required information
Please include the following:
 - GEOS-Chem version you are using: 12.5.0
 - Compiler version that you are using: gfortran v4.8.5
 - Computational environment [e.g. a cluster, or the AWS cloud]: local computers (24 cores)
 - Are you using "out of the box" code, or have you made modifications? "Out of the box"

[input.geos.txt](https://github.com/geoschem/geos-chem/files/4326446/input.geos.txt)
[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/4326457/HEMCO_Config.rc.txt)
[run.log.txt](https://github.com/geoschem/geos-chem/files/4326449/run.log.txt)
[HEMCO.log.txt.zip](https://github.com/geoschem/geos-chem/files/4326454/HEMCO.log.txt.zip)

**Comment by msulprizio** [comment]
Did you try running with debug flags turned on to see if there is some other issue (array out-of-bounds, floating point exception, etc.) that is leading to this error? See this wiki post for details: http://wiki.seas.harvard.edu/geos-chem/index.php/Debugging_GEOS-Chem#Recompile_GEOS-Chem_with_debug_options_turned_on.

**Comment by MaggieMarvin** [comment]
I'll give it a try and report back. Please bear with me, it will take a few days to reach the crash point.
Best, Maggie

**Comment by MaggieMarvin** [comment]
Yeah, I just tried running with all of the debug flags turned on, but it doesn't look like any were tripped when the model crashed.

[run.log.txt](https://github.com/geoschem/geos-chem/files/4348684/run.log.txt)
[HEMCO.log.txt](https://github.com/geoschem/geos-chem/files/4348685/HEMCO.log.txt)

**Comment by yantosca** [comment]
Hmm.  This is curious:
```
 SZA 5 hours ago :   -60.0001373
 SZA at this time:    15.0007019
 The two SZAs should not be more than 75 deg apart!
 If they are, your restart SZA might be wrong.
 You can try to coldstart PARANOx by commenting
 all PARANOX_SUNCOS entries in your HEMCO
 configuration file.
```
Apparently, there is some kind of disconnect in the SZA values.  There is a 75 degree swing in the same 5hr interval at the same grid box.

My guess is that it could be a couple of things:
- It may be that the run stage is reading from the wrong restart file
- It could be that a corrupted met field on disk.

Maybe try adding some debug print statements in HEMCO/Extensions/hcox_paranox_mod.F90 to see if you can peg it down to where this is happening.

**Comment by lizziel** [comment]
There are some debug prints in the code that are commented out that you could start with.
```

            PRINT*, 'PARANOX_LUT: fracnox = ', FNOX_TMP
            PRINT*, 'This occured at grid box ', I, J
            PRINT*, 'Lon/Lat: ', HcoState%Grid%XMID%Val(I,J), HcoState%Grid%YMID%Val(I,J)
            PRINT*, 'SZA 5 hours ago : ', VARS(4)
            PRINT*, 'SZA at this time: ', VARS(5)
            PRINT*, 'The two SZAs should not be more than 75 deg apart!'
            PRINT*, 'If they are, your restart SZA might be wrong.'
            PRINT*, 'You can try to coldstart PARANOx by commenting'
            PRINT*, 'all PARANOX_SUNCOS entries in your HEMCO'
            PRINT*, 'configuration file.'

            !print*, I1, I2, I3, I4, I5, I6, I7, I8
            !print*, INDX(1,I1), INDX(2,I2), INDX(3,I3),  INDX(4,I4), &
            !        INDX(5,I5), INDX(6,I6), INDX(7,I7), INDX(8,I8)
            !print*, VARS

            MSG = 'LUT error: Fracnox should be between 0 and 1!'
            CALL HCO_ERROR(HcoState%Config%Err,MSG, RC, THISLOC=LOC )
            RETURN
```

The output of turning on those prints will isolate exactly what part of the loop is accessing -999 in the LUT, which might give some further insight.

**Comment by MaggieMarvin** [comment]
Hi Bob and Lizzie,

Thanks for these suggestions. I tried running the debug prints and this was the result for variables temperature (K), JNO2 (s^-1), O3 (ppb), solar elevation angle 5 hours previous (deg), solar elevation angle at current model time (deg), ratio of JOH:JNO2, NOx (ppt), and wind speed (m/s):

           1           1           1           1           2           1           1           1
           3           1           2           1           8           1           2           1
   301.177399       0.00000000       28.2288227      -60.0001373       15.0007019       0.00000000       298.832947       5.13004160

It looks like the -999 was accessed when the value of 15.0007019 was passed for the solar elevation angle at current model time. The error message cautions that the SEA should not differ by more than 75 degrees between the current model time and 5 hours before, but the values shown here seem ok to me. The error occurs at midnight UTC, which is about 8 am LT for my domain, so SEA values of 15 (t) and -60 (t-5) don't seem unreasonable, and the difference is *just* over 75 degrees. So I tried rounding the SEA calculation with NINT and the model seems to run ok now:

Line 2477:   VARS(4) = NINT( ASIN( Inst%SC5(I,J)                ) / HcoState%Phys%PI_180)
Line 2478:   VARS(5) = NINT( ASIN( ExtState%SUNCOS%Arr%Val(I,J) ) / HcoState%Phys%PI_180)

However, I couldn't isolate in the code where the SEA values for the two times are constricted to a particular range. I'm also a bit concerned that zeros are passed to PARANOX for JNO2 and JOH at 8 am LT. These values should be greater than zero when the sun is up. 

Best,
Maggie

**Comment by yantosca** [comment]
Hi Maggie.  Thanks for the feedback.  I am wondering if it is maybe a compiler or optimization issue.  We have noticed the the newer versions of GC (e.g. 12.7.0+) don't work as well with older gfortran versions.  You could try updating to a later gfortran version (7 or later) and see if you still get the same problem.

**Comment by dorosieun** [comment]
Hi, I got similar problem.
When I run with default source code,  I got same error message like @MaggieMarvin.
![스크린샷 2021-11-05 오후 2 41 22](https://user-images.githubusercontent.com/87462290/140463876-8ebd29c5-12b4-4c29-84d9-38a772bb0df4.png)
-run.log
![스크린샷 2021-11-05 오후 2 41 48](https://user-images.githubusercontent.com/87462290/140463910-575a2cf7-55d0-4f22-8174-690042ffa2d3.png)
-HEMCO.log

Setting:
-grid resolution: 0.25x0.3125
-compiler : ifort 15.0.0
-GEOSChem version: 13.0.0

I tried solution of @MaggieMarvin (edit the code)
But, it made error massage like 'forrtl: error (65): floating invalid'

And as @yantosca said, I also tried using the later compiler, gfortran7.5.0.
But, nothing has solved. (same error)

Can anyone help me?

**Comment by yantosca** [comment]
@doroiesun: Have you tried using NINT instead of INT here, as mentioned above?
```
VARS(4) = NINT( ASIN( Inst%SC5(I,J) ) / HcoState%Phys%PI_180)
VARS(5) = NINT( ASIN( ExtState%SUNCOS%Arr%Val(I,J) ) / HcoState%Phys%PI_180)
```

**Comment by dorosieun** [comment]
@yantosca Yes! I used NINT. And I got 'forrtl: error (65): floating invalid' error.

**Comment by yantosca** [comment]
@doriesun, did you try to print out any values?  That can give you a hint of what is going on.

**Comment by dorosieun** [comment]
![스크린샷 2021-11-07 오후 4 39 55](https://user-images.githubusercontent.com/87462290/140636745-a78b651d-1830-4d89-b7f4-472f077d374e.png)

This is the added code(below the comment, !added by SEL)
And I tried running  GEOSChem with Debug option.

I got this log and error code.
![스크린샷 2021-11-07 오후 4 40 05](https://user-images.githubusercontent.com/87462290/140636814-82eca50d-11a7-4e57-9383-ede28c6afc93.png)

Which values do I have print out and check? Can you give me advice?

**Comment by yantosca** [comment]
@doroiesun, the traceback output is telling you that there is a problem at line 6436 of gckpp_HetRates.F90.  There is probably a division by zero or other such error that is causing the simulation to halt.

**Comment by wahababdul638** [comment]
@yantosca hi there, i am wondering wether this fix is included in later version of GEOS-Chem. I got the same PARANOX_LUT error in my simulation. i will attach the logs here. kindly help me through this error

i am using GEOS-Chem v14.2.3, full chemistry module, simulation year is 2021-2022 for southeast asia (lon: 91-129, lat: -10-29). The error occured when HEMCO tried to open "so2_volcanic_emissions_Carns.20210924.rc"

[afterso2error.log](https://github.com/user-attachments/files/19577510/afterso2error.log)
[geoschem_config.txt](https://github.com/user-attachments/files/19577507/geoschem_config.txt)
[HEMCO_Config.rc.gmao_metfields.txt](https://github.com/user-attachments/files/19577508/HEMCO_Config.rc.gmao_metfields.txt)
[HEMCO_Config.txt](https://github.com/user-attachments/files/19577506/HEMCO_Config.txt)
[HISTORY.txt](https://github.com/user-attachments/files/19577509/HISTORY.txt)

<img width="877" alt="Image" src="https://github.com/user-attachments/assets/f66aa1b7-b9f2-4211-a3ad-16ccfbb304e8" />

**Comment by wahababdul638** [comment]
> [@yantosca](https://github.com/yantosca) hi there, i am wondering wether this fix is included in later version of GEOS-Chem. I got the same PARANOX_LUT error in my simulation. i will attach the logs here. kindly help me through this error
> 
> i am using GEOS-Chem v14.2.3, full chemistry module, simulation year is 2021-2022 for southeast asia (lon: 91-129, lat: -10-29). The error occured when HEMCO tried to open "so2_volcanic_emissions_Carns.20210924.rc"
> 
> [afterso2error.log](https://github.com/user-attachments/files/19577510/afterso2error.log) [geoschem_config.txt](https://github.com/user-attachments/files/19577507/geoschem_config.txt) [HEMCO_Config.rc.gmao_metfields.txt](https://github.com/user-attachments/files/19577508/HEMCO_Config.rc.gmao_metfields.txt) [HEMCO_Config.txt](https://github.com/user-attachments/files/19577506/HEMCO_Config.txt) [HISTORY.txt](https://github.com/user-attachments/files/19577509/HISTORY.txt)
> 
> <img alt="Image" width="877" src="https://private-user-images.githubusercontent.com/49642620/429711989-f66aa1b7-b9f2-4211-a3ad-16ccfbb304e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDM2NDMyODUsIm5iZiI6MTc0MzY0Mjk4NSwicGF0aCI6Ii80OTY0MjYyMC80Mjk3MTE5ODktZjY2YWExYjctYjlmMi00MjExLWEzYWQtMTZjY2ZiYjMwNGU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDAzVDAxMTYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1YzQ0NDQ3MWRhNzhhMzQ3MGRhMzBmMzdmYzE0MWE1N2Y0MjZmODJkM2QyYTk4ZWYxNjA5MTJjZmQ2M2EzMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PTU5vfWG6aNdhdqCzKW3DzVw0nhAjuHaM-DkijnjLg0">

i also added the lines suggested by @MaggieMarvin in /media/data01/abdul/RunDirs/BaseCase/gc_0.25x0.3125_nested_sea_allon_jja_daily/CodeDir/src/HEMCO/src/Extensions/hcox_paranox_mod.F90 but it did not work :(

![Image](https://github.com/user-attachments/assets/52c756d3-4965-4520-8d14-e27d1dcbc6d6)

**Comment by ankitpatel0698** [comment]
hi @wahababdul638 , how did you fix this error, i am also getting the same error when my simulation reaches 24/09

**Comment by wahababdul638** [comment]
> hi [@wahababdul638](https://github.com/wahababdul638) , how did you fix this error, i am also getting the same error when my simulation reaches 24/09

if i rememer correctly i added these lines,

VARS(4) = NINT( ASIN( Inst%SC5(I,J) ) / HcoState%Phys%PI_180)
VARS(5) = NINT( ASIN( ExtState%SUNCOS%Arr%Val(I,J) ) / HcoState%Phys%PI_180)

removed the old build and created new build files with cmake.
