### ISSUE TITLE
Number concentration and mass concentration

### ISSUE THREAD

**Issue by ChenBHXMU** [geoschem/geos-chem#2432]
### Your name

Baihua Chen

### Your affiliation

Xiamen University

### Please provide a clear and concise description of your question or discussion topic.

Dear @yantosca ,

I hope this message finds you well.  While reading hcox_seasalt_mod.F90, I came across this piece of code. I think that SALT and SALT_N should represent mass concentration and number concentration, respectively. I have two question: 1. Will both types of concentration be saved? 2. Which type of concentration is recorded in the GEOSChem.Metrics.xxxxx_xxxxz.nc4 file in the OutputDir folder?

Could you kindly provide guidance or recommend any resources that could help me with this process?

Thank you very much for your assistance.

Best regards,
Baihua Chen

<img width="548" alt="图片1" src="https://github.com/user-attachments/assets/28b715aa-f169-407c-907a-fcf753221a39">

**Comment by yantosca** [comment]
Thanks for writing @ChenBHXMU.

1. I believe the SALT_N fields will be saved to HEMCO diagnostics if the marinePOA option is activated:
```F90
    ! Create marine density diagnostics only if marine POA enabled
    IF ( HcoState%MarinePOA ) THEN

       CALL Diagn_Create ( HcoState   = HcoState,              &
                           cName      = 'SEASALT_DENS_PHOBIC', &
                           ExtNr      = Inst%ExtNrSS,         &
                           Cat        = -1,                    &
                           Hier       = -1,                    &
                           HcoID      = Inst%IDTMOPO,          &
                           SpaceDim   = 2,                     &
                           OutUnit    = 'number_dens',         &
                           AutoFill   = 0,                     &
                           Trgt2D     = Inst%NDENS_MOPO,       &
                           COL = HcoState%Diagn%HcoDiagnIDManual, &
                           RC         = RC                      )
       IF ( RC /= HCO_SUCCESS ) THEN
           CALL HCO_ERROR( 'ERROR 20', RC, THISLOC=LOC )
           RETURN
       ENDIF

       CALL Diagn_Create ( HcoState   = HcoState,              &
                           cName      = 'SEASALT_DENS_PHILIC', &
                           ExtNr      = Inst%ExtNrSS,          &
                           Cat        = -1,                    &
                           Hier       = -1,                    &
                           HcoID      = Inst%IDTMOPI,          &
                           SpaceDim   = 2,                     &
                           OutUnit    = 'number_dens',         &
                           AutoFill   = 0,                     &
                           Trgt2D     = Inst%NDENS_MOPI,       &
                           COL = HcoState%Diagn%HcoDiagnIDManual, &
                           RC         = RC                      )
       IF ( RC /= HCO_SUCCESS ) THEN
           CALL HCO_ERROR( 'ERROR 21', RC, THISLOC=LOC )
           RETURN
       ENDIF

    ENDIF
```
2. The Metrics collection only saves gas-phase fields needed to compute the mean OH concentration, CH4 lifetime, and methyl chloroform lifetime.

**Comment by ChenBHXMU** [comment]
Thank you very much for your assistance. @yantosca
