### ISSUE TITLE
Question about the contribution of aerosol phase methylglyoxal

### ISSUE THREAD

**Issue by EnyuxPolyU** [geoschem/geos-chem#2433]
### Your name

Enyu Xiong

### Your affiliation

The HongKong Polytechnic University

### Please provide a clear and concise description of your question or discussion topic.

Version: GC14.4.1
Simulation: 2x2.5 degree standard
Period: 2018
Setting: default simple SOA scheme

Dear GEOSCHEM support team,

I am currently analyze the global budget of methylglyoxal and I do not know if I am right.

I find the sink of methylglyoxal by SOA uptake is very small <  0.003 Tg/yr, which is not consistent with the result reported by Fu et al. (2008), where the sink should be 16 Tg/yr (14 Tg/yr in cloud and 1.4 Tg/yr in aqueous aerosols).

I looked up the issue #568 and Bates et al. (2019). It seems like the current knowledge about sink of methylglyoxal by SOA has changed compared to Fu et al. (2008). That's why current version removed the speices of SOAGM due to low contribution and lumped into SOAGX. Thus, from today's understanding, the sink of methylgloxyal by SOA uptake should be a small value. I am not sure if I am right. 

The ways I have done for this calculation:
1. adding SOAGM back to KPP and species_database;
2. output Budget diagnositics in HISTORY.rc;
3. calculate the BudgetChemistryFull_SOAGM by summing all gridbox together.

I also calculated BudgetChemistryFull_SOAGX for glyoxal, which was about 5.4 Tg/yr which was relatively closed to Fu et al. (2008) where 5.5 Tg/yr in clouds and 0.95 Tg/yr in aqueous aerosols.

Best,
Enyu

**Comment by yantosca** [comment]
Thanks for writing @EnyuxPolyU.  This is a science question and lies outside of the GCST's expertise.  I would recommend contacting the Chemistry Working Group (geos-chem-oxidants@g.harvard.edu).  Also tagging the Chemistry WG co-chairs: @barronh @luhu0 @jhaskinsPhD @kelvinb

**Comment by EnyuxPolyU** [comment]
Hi @yantosca ,
Thank you very much. I have contacted the Chemistry Working Group and received their detailed response.
