### ISSUE TITLE
 libnetcdff.so.7: cannot open shared object file

### ISSUE THREAD

**Issue by xiaomufeng** [geoschem/geos-chem#2437]
### Your name

zhaohongyan

### Your affiliation

macun19@126.com

### What happened? What did you expect to happen?

dry-run ok, but when I run my job failed, errors:
![image](https://github.com/geoschem/geos-chem/assets/9513284/ad41a056-3061-4275-84ba-cf76dabae535)

### What are the steps to reproduce the bug?

errors info: 
Goldenable & storageenable both are false, job ran without making reserve!
./gcclassic: error while loading shared libraries: libnetcdff.so.7: cannot open shared object file: No such file or directory

### Please attach any relevant configuration and log files.

env infos: 
 CMake 3.20.1
export CMAKE=/public/software/compiler/cmake/3.20.1
#> NetCDF 4.7.4
export NETCDF=/public/software/mathlib/netcdf/intel/4.7.4
#> HDF5
export HDF=/public/software/mathlib/hdf5/intel/1.12.0
#> ifort and impi 2017
export INTEL=/public/software/compiler/intel/2020.1.217/bin

### What GCClassic version were you using?

14.0.1

### What environment were you running GCClassic on?

Local cluster

### What compiler and version were you using?

10.2.0
Intel Fortran Compiler(aka ifort)

### Will you be addressing this bug yourself?

Yes

**Comment by yantosca** [comment]
Thanks for writing @xiaomufeng and thanks for your patience.  It could be that you are trying to use a netCDF library that was built with a different compiler than the compiler you are building GEOS-Chem with.

Have you resolved this issue?  Otherwise, please attach your full compilation log (output from cmake and make) to this issue and we can take a look.

**Comment by yantosca** [comment]
@xiaomufeng: Your system may also be lacking the netCDF-Fortran library.  That is the `libnetcdff` library file.  That has to be bult separately from the netcdf-c library.  See this link for more information:

- https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/spack-guide.html

**Comment by yantosca** [comment]
Closing out this issue
