### ISSUE TITLE
cmake GCClassic with spack，compile  failed

### ISSUE THREAD

**Issue by xiaomufeng** [geoschem/geos-chem#2438]
### Name and Institution (Required)

Name: 
zhaohongyan
Institution:
School of Environment , Beijing Normal University

### Confirm you have reviewed the following documentation

- [ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/GCClassic/issues)

### Description of your issue or question
1. Build required software with Spack
a. GCClassic version : 14.3.1,  build from master
b. 
2. spack find
<img width="1071" alt="image" src="https://github.com/geoschem/geos-chem/assets/9513284/1f3ec844-4f19-4195-9c46-2972c87d2f21">

3. env file 
<img width="1070" alt="image" src="https://github.com/geoschem/geos-chem/assets/9513284/c9359cec-7bf5-4451-9369-92b0aa3b964e">

4. cmake errors
a. <img width="1081" alt="image" src="https://github.com/geoschem/geos-chem/assets/9513284/7d4e2a43-b486-458c-9d52-47612047ba84">
b. FailedCompile.txt log info
<img width="1074" alt="image" src="https://github.com/geoschem/geos-chem/assets/9513284/03ace1b9-0fef-4c0c-ad21-3b4efd9fa0ea">

**Comment by yantosca** [comment]
Thanks for your patience @xiaomufeng.  Are you still having this issue?

It looks like you have loaded gcc@13.20 but the libraries are built with gcc@10.2.0.

**Comment by yantosca** [comment]
Closing out this issue
