### ISSUE TITLE
Separating Wet Deposition Loss from Re-evaporation

### ISSUE THREAD

**Issue by AlfredMayhew** [geoschem/geos-chem#2440]
### Your name

Alfred Mayhew

### Your affiliation

University of Utah

### Please provide a clear and concise description of your question or discussion topic.

I am looking to track the physical loss processes occurring in GEOS-Chem Classic for specific compounds and have output the "DryDep", "WetLossConv", and "WetLossLS" diagnostics. When I've come to analyse the data, I have noticed that often the values are negative. In [this comment](https://github.com/geoschem/geos-chem/issues/1518#issuecomment-1320211571), it is noted that a net re-evaporation of a species will result in a negative value, which makes sense.
However, I'm wondering if there is any way to easily extract only the loss portion of wet deposition? I can't see anything in the WetLossConv and WetLossLS diagnostics so I'm wondering if there's another diagnostic output I can use.

I'd appreciate any advice, thanks!

**Comment by yantosca** [comment]
@AlfredMayhew Maybe my suggestion isn't that great.  What you would need to do is to look at where re-evaporation is being added into the `WetLoss` variable (I tihink in the `Washout` routine) and then perhaps save that into a different variable that you can archive into a separate diagnostic.

**Comment by AlfredMayhew** [comment]
Thanks for the responses. So, to be clear, the first suggestion wouldn't be the best because net-positive values are still less positive than they would be if only the loss term were included because it's offset by the negative re-evaporation term, right?

I'll have a dig around in `GeosCore/wetscav_mod.F90` and see what I can do. Thanks again.

**Comment by yantosca** [comment]
@AlfredMayhew: Yes, I think the first response (just taking values where wetloss > 0) is incorrect since wetloss could have been affected by negatives.  I think you have to track the re-evaporation separately.

**Comment by yantosca** [comment]
Closing out this issue
