### ISSUE TITLE
Forced exit from Rosenbrock 

### ISSUE THREAD

**Issue by NatalliaMiatselskaya** [geoschem/geos-chem#2441]
### Your name

Natallia Miatselskaya

### Your affiliation

Institute of Physics of NAS of Belarus

### What happened? What did you expect to happen?

My simulation crashed with messages "Forced exit from Rosenbrock due to the following error: Step size too small", "INTEGRATE FAILED TWICE", "GEOS-Chem ERROR: KPP failed to converge after 2 iterations!". It happened on a specific day (January 20, 2022, 16:00). 

### What are the steps to reproduce the bug?

I run GCClassic, Full chemistry, GEOS-FP, 2x2.5, v. 14.4.3 with default configuration files. I tried also v. 14.4.1 and 14.3.1. They crashed at the same day. I tried to tighten and to loose the error tolerances. It does not help. I replaced the meteorology files on this day with the older version of the meteorology files. It does not help. However, when I run v. 12.1.1, everything was OK for this day.

### Please attach any relevant configuration and log files.

[GC_gl_20220101.log](https://github.com/user-attachments/files/16799559/GC_gl_20220101.log)

### What GEOS-Chem version were you using?

14.4.3

### What environment were you running GEOS-Chem on?

Personal computer

### What compiler and version were you using?

gcc 11.4.0

### Will you be addressing this bug yourself?

Yes, but I will need some help

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

Full chemistry

### As what resolution were you running GEOS-Chem?

2x2.5

### What meterology fields did you use?

GEOS-FP

**Comment by yantosca** [comment]
Thanks for writing @NatalliaMiatselskaya.  These types of issues can sometimes be hard to track down.  We have some suggestions here:

- https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/error-guide.html#forced-exit-from-rosenbrock

You can also try turning off operations (transport, wet deposition, etc) one by one to see if the simulation gets past that day.  The error could be a side-effect of another error somewhere else.

Also, are you uisng an "out-of-the-box" version, or did you make any modifications to the code?  If you did make revisions, try reverting to a clean checkout of 14.4.3 and then see if the error persists.

**Comment by NatalliaMiatselskaya** [comment]
Thank you for your suggestions. I tracked down this issue. I found that the error is located in ExtData/HEMCO/OFFLINE_SOILNOX/v2021-12/0.25x0.3125/2022/01/soilnox_025.20220120.nc. A lot of SOIL_NOx emissions in this file have unrealistic values 9.96921e+36. Can you please help me how to handle this nc file to replace unrealistic SOIL_NOx values with some reasonable values?

**Comment by yantosca** [comment]
Tagging @yidant who may have some more info on who created the soilNOx data files.

You should be able to do this with the Climate Data Operators (CDO) from the command line:
```console
$ cdo nec,-999.0 soilnox_025.20220120.nc mask.nc
$ cdo mul file.nc mask.nc new.soilnox_025.20220120.nc 
```
Then you can compare the new file to see if worked.  When you are sure then just do:
```console
$ mv new.soilnox_025.20220120.nc soilnox_025.20220120.nc
```
See this post for more info: https://stackoverflow.com/questions/38230923/replace-values-in-netcdf-file-using-python

**Comment by NatalliaMiatselskaya** [comment]
Thank you very much for your help. I used cdo to replace 9.96921e+36 with zero. Now I can continue running my simulation.

**Comment by gopikrishnangs44** [comment]
HI @NatalliaMiatselskaya, 

can you guide me how you figured out that the specific file has these values. Really curious about it.!

Thank you

**Comment by NatalliaMiatselskaya** [comment]
Hi @gopikrishnangs44, 
When the simulation crashes, it creates some messages. I read the message "Species concentrations at problem box", and there was an unrealistic concentration for NO.  I checked the files in HEMCO from which NO can be read, and I found the unrealistic values in soilnox.
