### ISSUE TITLE
"Foribidden"/ Unavailable WashU Input File (FJX/v2024-05/ssa.dat)

### ISSUE THREAD

**Issue by jhaskinsPhD** [geoschem/geos-chem#2444]
### Your name

Jessica Haskins

### Your affiliation

University of Utah 

### What happened? What did you expect to happen?

I think there's a permission error or issue with the following WashU input file that's preventing anyone from downloading it and we're unable to run GCClassic v14.4.3 without it that @lizziel or someone who manages the WashU repo might be able to help with: 
`ExtData//CHEM_INPUTS/FAST_JX/v2024-05//ssa.dat`

We completed a dry run and subsequently ran  `download_data.py` with the outputted log file to download all the input files we didn't have from the WashU repo, which generally works for us. This managed to grab all the input files we didn't have except for the `FAST_JX/v2024-05//ssa.dat` file. 

We subsequently tried using `wget` to download this file, but it returned the following error message: 
```--2024-08-30 14:56:32--  http://geoschemdata.wustl.edu/ExtData/CHEM_INPUTS/FAST_JX/v2024-05//ssa.dat
Resolving geoschemdata.wustl.edu (geoschemdata.wustl.edu)... 35.209.233.133
Connecting to geoschemdata.wustl.edu (geoschemdata.wustl.edu)|35.209.233.133|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-08-30 14:56:32 ERROR 403: Forbidden.
``` 

Finally, we also tried navigating to the Washu repo on the web to manually download this file, but unlike all the other files in the `ExtData/CHEM_INPUTS/FAST_JX/v2024-05/`directory, we got an error: "File Unavailable". We were able to manually grab `ssc.dat`, `soot.dat` and others in the `FAST_JX/v2024-05/` directory , just not this one file. The website shows that this file was updated last on 08/05/2024, while most of the functioning files in the `FAST_JX/v2024-05/` directory seem to have last been updated on 05/12/2024. So, I think there might be a permission error associated with this new version of the file on the WashU repo that's stopping anyone without it from being able to download it. We're not setup to grab things from Amazon, so until this is fixed, we're unable to run v14.4.3.   

### What are the steps to reproduce the bug?

Try downloading the file (ssa.dat) and try downloading (soot.dat) manually from the following link. We are able to get soot.dat but not ssa.dat: [http://geoschemdata.wustl.edu/ExtData/CHEM_INPUTS/FAST_JX/v2024-05/](http://geoschemdata.wustl.edu/ExtData/CHEM_INPUTS/FAST_JX/v2024-05/)

Test a simple wget command at the terminal line (it's a small file). We got a `ERROR 403: Forbidden` error:  `wget http://geoschemdata.wustl.edu/ExtData/GEOS_0.25x0.3125_NA/GEOS_FP/2024/01/`

### Please attach any relevant configuration and log files.

[dry_geoschem.txt](https://github.com/user-attachments/files/16822191/dry_geoschem.txt)

### What GEOS-Chem version were you using?

14.4.3

### What environment were you running GEOS-Chem on?

Local cluster

### What compiler and version were you using?

gcc@11.2.0

### Will you be addressing this bug yourself?

No

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

Full chemistry

### As what resolution were you running GEOS-Chem?

2x2.5

### What meterology fields did you use?

MERRA-2

**Comment by lizziel** [comment]
Tagging @yidant who manages the WashU inventory.

**Comment by yidant** [comment]
Thanks @jhaskinsPhD and @lizziel! I've fixed this issue. Could you please try downloading the file again?

**Comment by jhaskinsPhD** [comment]
I was able to download it now! Thanks!

**Comment by yantosca** [comment]
Thanks @lizziel @yidant and @jhaskinsPhD!  We can close out this issue now.
