### ISSUE TITLE
Could the GEOS-Chem photolysis mechanism calculate Lyman-alpha photolysis at 121.57 nm?

### ISSUE THREAD

**Issue by Liyl2** [geoschem/geos-chem#2445]
### Your name

Yali LI

### Your affiliation

Southern University of Science and Technology

### Please provide a clear and concise description of your question or discussion topic.

I'm using GCClassic 14.0.2 with Fast-JX v7.0a photodissociation mechanism, which considers 177-850nm and divides into 18 bins, and in the Jvalue diagnostics I get the radiative fluxes for each bin (e.g., UVFluxnet_187nm, UVFluxDiffuse_187nm, and UVFluxDirect_187nm). Using the Fast-JX mechanism, can I calculate Lyman-alpha (121.57nm) photolysis? How do I get the radiant flux at 121.57nm? Looking forward to your reply, thanks!

**Comment by yantosca** [comment]
Thanks for writing @Liyl2.  I believe that FAST-JX and Cloud-J are not set up to compute photolysis at Lyman alpha.  You might need to use a standalone radiative transfer model (e.g. LIDORT) to compute other wavelengths.  We would not be able to advise you further.

Tagging @lizziel in case she has any more suggestions.

**Comment by lizziel** [comment]
I concur with @yantosca. The minimum wavelength in `FJX_spec.dat` used for FAST-JX and CLOUD-J in GEOS-Chem is 187 nm.

@pratherUCI - do you see expansion to Lyman-alpha as a possibility for Cloud-J in the future?

**Comment by Liyl2** [comment]
OK，Thanks for your replies. @yantosca @lizziel
