### ISSUE TITLE
HEMCO ERROR: failed to open a restartfile named ./Restarts/GEOSChem.Restart.19810101_0000z.nc4

### ISSUE THREAD

**Issue by InterstellarPenguin** [geoschem/geos-chem#2448]
### Your name

Guo

### Your affiliation

University of Chinese Academy of Science

### What happened? What did you expect to happen?

Hi,

I'm quite new about the model, and I'm running a CO2 simulation from 1980 to 2022 and have completed the compilation. However, I've encountered errors when submitting the run script. The log indicates it is trying to find the file /ExtData/HEMCO/GFED4/v2023-03/1980/xxxx.nc, but after checking the data websites (http://geoschemdata.wustl.edu/ and two other data webs), I found that there is no directory for the year 1980 or before 2010.

I set the simulation start time to 2018, but then another error occurred related to a restart file: HEMCO ERROR: failed to open a restartfile named ./Restarts/GEOSChem.Restart.19810101_0000z.nc4.

Could you help me resolve these issues?

### What are the steps to reproduce the bug?

![6489d41d62e9cf17aa74f485017f558](https://github.com/user-attachments/assets/5968fc6c-096d-4c26-bd99-114364ed492f)
btw, could you tell me where are the data for land and ocean natural carbon fluxes at the surface set?

### What GEOS-Chem version were you using?

14.4.2

### What environment were you running GEOS-Chem on?

Local cluster

### What compiler and version were you using?

ifort version 15.0.2

### Will you be addressing this bug yourself?

Yes

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

CO2

### As what resolution were you running GEOS-Chem?

4x5

### What meterology fields did you use?

MERRA-2

**Comment by yantosca** [comment]
Thanks for writing @InterstellarPenguin.  By default the GEOS-Chem simulation assumes that you have the restart file that is timestamped for the start date of your simulation.  But you can override this behavior by changing the time cycle flag for the ``SPC_` container from e.g. `EFYO` to `CYS`.  Please see this section of the ReadTheDocs manual for more information:

- https://geos-chem.readthedocs.io/en/stable/gcclassic-user-guide/restart-files-gc.html

**Comment by InterstellarPenguin** [comment]
Thanks for your answer ! Could you tell me where are the data for land and ocean natural carbon fluxes input, are they in ExtData/HEMCO/CO2/v2022-11/BIO and /ExtData/HEMCO/CO2/v2022-11/OCEAN?

**Comment by yantosca** [comment]
Thanks @InterstellarPenguin.  The `HEMCO/CO2/v2022-11/BIO` folder contains the balanced biosphere flux and the ocean fluxes are in the `HEMCO/CO2/v2022-11OCEAN/` folder.

NOTE: Some of the inputs for the CO2 simulation are very old.  The folks at JPL are working on updating some of the CO2 emissions / flux data.  See https://github.com/geoschem/GCHP/issues/440.  We hope to have this available in 14.5.1.

Also note: the standalone CO2 simulation is slated to be retired in favor of the multi-species carbon simulation (which you can also configure to run in single tracer mode).  This will likely be done in version 14.6.0.

**Comment by InterstellarPenguin** [comment]
Good to know that! Thanks! @yantosca
