### ISSUE TITLE
How to obtain the BC column concentration 

### ISSUE THREAD

**Issue by yangbyy** [geoschem/geos-chem#2449]
### Your name

Yang Shuangqin

### Your affiliation

Tianjin Normal University

### Please provide a clear and concise description of your question or discussion topic.

Hi all, I have now got the concentration of black carbon at 47 heights in the vertical direction, but I want to calculate the column concentration of black carbon. Is it the right way to do it by adding the concentrations of each vertical layer to calculate the total? Or do I need to multiply it by the air density? Can anyone tell me the exact algorithm? I'd appreciate it very much!

**Comment by yantosca** [comment]
Thanks for writing.  We have the algorithms for the various unit conversions listed in the comments of `GeosUtil/unitconv_mod.F90`.   You can adapt them in your post-processing code.  See:

- https://github.com/geoschem/geos-chem/blob/main/GeosUtil/unitconv_mod.F90

I think you would need to do this in 2 steps:

1. v/v dry -> kg/kg dry 
  - See  routine `convertspc_vv_to_kgkgdry` in `unitconv_mod.F90`
2. kg/kg dry -> molec/cm3 (aka molecular number density or MND).
  - See routine `convertspc_kgkgdry_to_mnd` in `unitconv_mod.F90`

You should convert to molec/cm3 in each grid box and then take the column sum.

**Comment by yantosca** [comment]
Thanks @yangbyy.  In that case, what you would need to do is to multiply the BC mass concentration in ug/m3 in each grid box the grid box volume (i believe `State_Met%AIRVOL` to get ug.  Then sum each column in the vertical (as ug).  Then divide by grid box area (`State_Met%AREA_M2`) to get ug/m2.

**Comment by yangbyy** [comment]
Thank you very much for your detailed reply! I got it.
