### ISSUE TITLE
Error occurred when adding MEIC inventory to HEMCO

### ISSUE THREAD

**Issue by fang159753** [geoschem/geos-chem#2450]
### Your name

fangjiong

### Your affiliation

SHU

### What happened? What did you expect to happen?

I am trying to add the MEIC inventory to HEMCO. I processed the MEIC inventory for all pollutants uniformly, converting their units to kg/m²/s. However, after adding the inventories, only the BC and NOx inventories run without issues. Errors occur when adding the inventories for other pollutants.
![Uploading Snipaste_2024-09-04_22-04-26.png…]()
![2](https://github.com/user-attachments/assets/332582fc-278f-4280-a9c0-5383564fe069)
![3](https://github.com/user-attachments/assets/e1f62dff-507a-47e0-9aa2-82ef1e2d551b)
I would appreciate your help in resolving this error. 

### What are the steps to reproduce the bug?

I attempted to add the MEIC inventory in HEMCO.

### Please attach any relevant configuration and log files.

[GC.log](https://github.com/user-attachments/files/16871998/GC.log)
[HEMCO_Config.rc.txt](https://github.com/user-attachments/files/16871999/HEMCO_Config.rc.txt)

### What GEOS-Chem version were you using?

14.4.0

### What environment were you running GEOS-Chem on?

Local cluster

### What compiler and version were you using?

1

### Will you be addressing this bug yourself?

Yes, but I will need some help

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

Full chemistry

### As what resolution were you running GEOS-Chem?

4×5

### What meterology fields did you use?

MERRA-2

**Comment by yantosca** [comment]
Thanks for writing @fang159753.  Your `time:units` attribute in the data file cannot be 'month', as this does not conform to the COARDS netCDF conventions, and thus HEMCO cannot read the file.  Please see the following guides in our ReadTheDocs for more information about preparing input files for HEMCO:

- [Prepare COARDS-compliant files for HEMCO](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/coards-guide.html
- [Work with netCDF files](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/netcdf-guide.html)

**Comment by yantosca** [comment]
Also your `longitude:units` and `latitude:units` are incorrect.  They should be

`longitude:units = degrees_east`
`latitude:units = degrees_north`

and as described in the ReadTheDocs links,

`time:units = 'hours since YYYY-MM-DD hh:mm:ss"  where YYYY-MM_DD hh:mm:ss should be the first datetime entry in the file.

**Comment by fang159753** [comment]
Thank you for your help; I have successfully resolved the previous issue.
I now have another question: I'm planning to download the VOC emissions from the MEIC inventory, but the download site offers several mechanisms to choose from. Which mechanism should I select for use with GEOS-Chem?
![Snipaste_2024-09-11_15-00-41](https://github.com/user-attachments/assets/456de0ca-7708-464b-b7e6-6f551c3bf487)

**Comment by yantosca** [comment]
Thanks for the feeback @fang159753.  We would be unable to answer your question as this is more of a science issue, and we are not really familiar with MEIC emissions.  You might ask this as a question to the GEOS-Chem Emissions Working Group email list (geos-chem-emissions [at] g.harvard.edu). Tagging the WG co-chairs @eamarais @jaegle.

**Comment by eamarais** [comment]
Hi @fang159753, @kelvinhb or @ktravis213 may know which of the options is most similar to GEOS-Chem. Otherwise, it might require comparing these options to what's included in the version of GEOS-Chem you're using and making some adjustments where VOCs are lumped or follow different naming conventions.

**Comment by fang159753** [comment]
I’m encountering an issue while running a GEOS-Chem script. I need to run a continuous one-month simulation, but the script consistently crashes after about 7 days. Which parameters should I check to debug this? What settings could be influencing the runtime, and where can I find useful tips?

Additionally, I’d like to confirm my understanding of methane concentration simulations. In a full chemistry simulation, I can adjust emissions of pollutants like CO, SO2, and NOx to calculate OH concentrations. However, methane concentrations don’t seem to be affected by changing methane emissions, as there’s a predefined background level. To obtain the actual CH4 concentrations under varying OH levels, I believe I would need to run a separate CH4 chemistry simulation, using the OH results from the full chemistry simulation, and then modify methane emissions to observe the impact on CH4 concentrations.

Is my understanding correct, or is it possible to combine the full chemistry simulation with the CH4 simulation? I’d really appreciate any insights or suggestions!

**Comment by fang159753** [comment]
I’d like to confirm my understanding of methane concentration simulations. In a full chemistry simulation, I can adjust emissions of pollutants like CO, SO2, and NOx to calculate OH concentrations. However, methane concentrations don’t seem to be affected by changing methane emissions, as there’s a predefined background level. To obtain the actual CH4 concentrations under varying OH levels, I believe I would need to run a separate CH4 chemistry simulation, using the OH results from the full chemistry simulation, and then modify methane emissions to observe the impact on CH4 concentrations.

Is my understanding correct, or is it possible to combine the full chemistry simulation with the CH4 simulation? I’d really appreciate any insights or suggestions!

**Comment by yantosca** [comment]
Thanks @fang159753 for the update. 

CH4 is an active species in the full-chemistry simulation (it's in the `#DEFVAR` section of the `KPP/fullchem/fullchem.eqn` file).  So you could potentially let it evolve. 

You could try copying the equations for CH4 from the carbon simulation (`KPP/carbon/carbon.eqn`) into the `fullchem.eqn` file and then rebuild the mechanism. But as this would be a research project, we wouldn't be able to provide any assistance beyond coding/technical issues.  I have no idea what would happen but feel free to try it!

**Comment by yantosca** [comment]
Closing out this issue

**Comment by ChenBHXMU** [comment]
Hi @fang159753    How to convert Mg/month to kg/m²/s?  Thank you！

**Comment by githubpanzhaoyang** [comment]
Hi @fang159753 . I am currently learning GEOS-Chem, and my goal is to simulate aerosols over China using GEOS-Chem. Therefore, incorporating the MEIC emission inventory is essential. I would like to ask whether you could share the relevant code and your experience. I would greatly appreciate your help!
