### ISSUE TITLE
ERROR: KPP integration failed

### ISSUE THREAD

**Issue by InterstellarPenguin** [geoschem/geos-chem#2455]
### Your name

Guolinyang

### Your affiliation

CAS-IAP

### What happened? What did you expect to happen?

Hi, i'm going to run a carbon simulation. 

### What are the steps to reproduce the bug?

I've ran make process with commands **cmake ../CodeDir -DRUNDIR=..
** and then **cmake . -DMECH=carbon**. In the first test, as the last issue#2448, i change the balanced biosphere flux with anthor ncfile.
<img width="701" alt="image" src="https://github.com/user-attachments/assets/474e43e0-7cc3-4775-950d-83482a86be1c">
In the output log it shows that the model has read the ncfile
<img width="525" alt="image" src="https://github.com/user-attachments/assets/e613453d-e366-4e4a-a1f7-bd2318c0604a">

 but i enconter the bug. 
<img width="482" alt="image" src="https://github.com/user-attachments/assets/541828fa-2f73-4a1b-8359-830085f3ded2">
i thought that was the data who cause this bug, so i change it back to data BBIO_SIB3 , unfortunately, the bug persisted even after reverting the data. I then double-checked the process starting from the createRunDir steps and reran the simulation, but the issue remained unresolved.

### Please attach any relevant configuration and log files.

[
[co2_output.txt.log](https://github.com/user-attachments/files/16917944/co2_output.txt.log)
[HEMCO_Config.txt](https://github.com/user-attachments/files/16917945/HEMCO_Config.txt)
[HISTORY.txt](https://github.com/user-attachments/files/16917946/HISTORY.txt)
](url)

[geoschem_config.txt](https://github.com/user-attachments/files/16917953/geoschem_config.txt)

The set i changed is only in the HEMCO_Config.rc

### What GEOS-Chem version were you using?

14.4.2

### What environment were you running GEOS-Chem on?

Local cluster

### What compiler and version were you using?

ifort version 15.0.2

### Will you be addressing this bug yourself?

Yes

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

Carbon

### As what resolution were you running GEOS-Chem?

4x5

### What meterology fields did you use?

MERRA-2

**Comment by yantosca** [comment]
Thanks for your patience @InterstellarPenguin.  I was out for a while and am back now.

It looks like there were multiple cores writing to the log file.  This could be a side-effect of hyperthreading.  

Also, we have had some issues with ifort 15.  We would recommend using a newer compiler if possible, (ifort 19 or higher or GNU 10 or higher).  If you don't have one available you can install a compiler with Spack as described here:

- https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/spack-guide.html#

**Comment by InterstellarPenguin** [comment]
Thank you for your reply, @yantosca. The issue seems to arise because I allocated multiple cores to run the simulation. To speed up the process, I switched to using GCHP.
