### ISSUE TITLE
Question about recent GEOS-FP data files

### ISSUE THREAD

**Issue by ChangpeiHe** [geoschem/geos-chem#2461]
It seems that recent GEOS-FP data is not updated in time. Besides, recent data files were not compressed. The near-real-time GEOS-FP data is crutial to my research project. 

Looking forward to your reply!

Changpei He,
Tsinghua University

**Comment by yidant** [comment]
Thanks @ChangpeiHe for reporting that! We are currently experiencing some issues on our cluster. The processing job didn't start properly. I'll manually process them for now and work with system administrator to resolve that.

**Comment by ChangpeiHe** [comment]
Thanks @yidant !

**Comment by yidant** [comment]
Hi @ChangpeiHe, this issue is resolved! Please let me know if you continue to find any missing file.

**Comment by ChangpeiHe** [comment]
![image](https://github.com/user-attachments/assets/7c718471-d71a-4ac4-ace2-a48979dc514c)
Hi, @yidant, files in 20240827 are missing, and some errors might occur in 20240909 and 20240910 (the file size seems incorrect).

**Comment by yidant** [comment]
Thanks @ChangpeiHe! These two issues are now fixed!

**Comment by ChangpeiHe** [comment]
Thanks @yidant! Some errors might exist on 20240916. In our test, we first downloaded the required original GEOS-FP files, and then processed them using the `./doGeosFpMulti YYYYMMDD `command. We encountered the same issue. 
![image](https://github.com/user-attachments/assets/f9267e08-fb42-438e-af0a-bfd6f45acc3a)

**Comment by ChangpeiHe** [comment]
I'd like to understand why this error occurred, and could you offer some suggestions to us?

**Comment by yidant** [comment]
Hi @ChangpeiHe! You can view the error message under the processing tool directory `GEOS_FP/logs`. It will tell you what makes the processing stop. In this case `20240916`, the log says there's a corrupted raw file, so I redownload it and reprocess this date. The corrupted files are now replaced.

**Comment by ChangpeiHe** [comment]
Thanks！@yidant
