### ISSUE TITLE
How to use climatological met data (using 1 year for multi-year)

### ISSUE THREAD

**Issue by aschuh** [geoschem/geos-chem#2465]
### Your name

Andrew Schuh

### Your affiliation

Colorado State University

### Please provide a clear and concise description of your question or discussion topic.

If I want to use 1 year of met driving data, is it just replacing the default EFY with C in ALL the following met lines of HEMCO? 
```console
# --- A1 fields ---
* ALBEDO    $METDIR/$YYYY/$MM/$MET.$YYYY$MM$DD.A1.$RES.$NC     ALBEDO   1900-2100/1-12/1-31/*/+30minute EFY xy  1  * -  1 1
* CLDTOT    $METDIR/$YYYY/$MM/$MET.$YYYY$MM$DD.A1.$RES.$NC     CLDTOT   1900-2100/1-12/1-31/*/+30minute EFY xy  1  * -  1 1
```

**Comment by msulprizio** [comment]
Hi @aschuh. Yes, you can change `EFY` to `C` to use the closest available date. However, note that HEMCO will choose the closest date according to the data available on your system so if you have other years available if may not stick to the single year as you expect. To force the correct behavior, you should be able to instead change the `$YYYY` token in the met field entries to the year of your choice and HEMCO will only look for files for that year. 

Note: HEMCO does have the option of specifying `Emissions year` in the config file which will hardcode the year of emissions for all inventories, but the same option doesn't exist yet for simulation year. We could consider adding a feature request for this if it would benefit the community. I think this could be done by modifying [these lines in hco_clock_mod.F90](https://github.com/geoschem/HEMCO/blob/41605bda8a89d96f441cb8eb90f3d3c8b21f2b71/src/Core/hco_clock_mod.F90#L498-L504).
