### ISSUE TITLE
Simulating the global distribution of SO3

### ISSUE THREAD

**Issue by 1392403848** [geoschem/geos-chem#2470]
### Your name

chen

### Your affiliation

south china normal university

### Please provide a clear and concise description of your question or discussion topic.

How can this problem be resolved?Thank you !

```
===============================================================================
GEOS-Chem ERROR: LDUST=T but ONLINE DUST AEROSOLS are undefined!
-> at Do_Error_Checks (in GeosCore/input_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem ERROR: Error encountered in "Do_Error_Checks"!
 -> at GC_Init_Extra (in module GeosCore/gc_environment_mod.F90)
===============================================================================

===============================================================================
GEOS-CHEM ERROR: Error encountered in "GC_Init_Extra"!
STOP at  -> at GEOS-Chem (in GeosCore/main.F90)
===============================================================================

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
```

**Comment by msulprizio** [comment]
Please upload your relevant run directory files (geoschem_config.yml, GEOS-Chem log file, etc.) so we can better assist you.

**Comment by 1392403848** [comment]
[SO3.zip](https://github.com/user-attachments/files/17164088/SO3.zip)
Thank you very much！

**Comment by msulprizio** [comment]
Thanks @1392403848. Could you please also upload the complete GEOS-Chem log file?

**Comment by 1392403848** [comment]
[SO3.zip](https://github.com/user-attachments/files/17164343/SO3.zip)
Okay, thank you very much. I can only upload compressed files here, so I added the log file to the SO3 folder and re-compressed and uploaded it again.

**Comment by msulprizio** [comment]
I think the issue is that you have compiled GEOS-Chem for use with TOMAS as indicated in your log file:

```
 %%%%% USING TOMAS MICROPHYSICS PACKAGE %%%%%
```

but the geoschem_config.yml file does not include the TOMAS species -- it seems to be a standard fullchem configuration file.

**Comment by 1392403848** [comment]
Could you please specify that for me in more detail? Thank you very much.
