### ISSUE TITLE
Nucleation in TOMAS

### ISSUE THREAD

**Issue by 1392403848** [geoschem/geos-chem#2471]
### Your name

ok

### Your affiliation

Tsinghua University

### Please provide a clear and concise description of your question or discussion topic.

Hello, I would like to modify the TOMAS file to add a new nucleation mechanism. I should modify the `tomas_mod.F90` file, so I am trying to understand the code of `tomas_mod.F90`. However, I am not quite clear which part I should modify. Could you please give me a more specific hint, such as which part of the function I should modify? Thank you very much.

**Comment by msulprizio** [comment]
I am tagging @BettyCroft and @theloniuspunk who may be able to provide guidance on the TOMAS code

**Comment by theloniuspunk** [comment]
Hi, Jeff Pierce here. I don't work directly with the code much anymore, but I did put nucleation in the first place. Traditionally, each nucleation scheme gets its own subroutine in tomas_mod (see e.g. napa_nucl), where the inputs are passed in and the nucleation rates and sizes are passed out. These subroutines are all called from both the cond_nuc and nucleation subroutines. 

Sam O'Donnell in my group (@samuelod-atmos) has added the Dunne and Riccobono schemes from CLOUD (the latter required adding approximations for HOM organics elsewhere in the code). I don't think it's in the standard code yet, so I've tagged him here.

**Comment by samuelod-atmos** [comment]
Hi, thanks for tagging me. 

For adding in new nucleation mechanisms, there are several places in tomas_mod.F90 that need to be changed. Additionally, if the nucleation mechanisms rely on some quantity besides H2SO4 and NH3 (e.g. HOMs), those quantities have to make their way to the TOMAS code. For example, I have played around with getting an estimate for HOM concentrations from carbon_mod.F90 for organic nucleation in TOMAS, and that requires a bit more altering. 

For adding a new nucleation mechanism, I think it best to add a new subroutine (structured similarly to the current nucleation mechanisms) where the other nucleation subroutines are (VEHK_NUCL and napa_nucl). From there, you can follow the structure for how napa_nucl and vehk_nucl are called. There are switches (0/1) for turning off/on the different nucleation mechanisms at the beginning of tomas_mod.F90 (bin_nuc switch for vehk_nucl and tern_nuc switch for napa_nucl). You can add your own switches for your own nucleation routines. If you follow the structure of how vehk_nucl is called, it should work. 

For example: 
IF (bin_nuc.eq.1) then
call VEHK_NUCL(inputs)
ENDIF

There are calls to the nucleation subroutines in the getNucRate subroutine, so calls to the new nucleation mechanisms will have to be added there. I think this call is for the H2SO4 calculation. Finally, there are calls to the nucleation subroutine in the NUCLEATION subroutine, and these are where particles are actually added to the smallest size bin. 

I hope this helps! Hopefully I can get my updates into the standard code soon as well!

**Comment by 1392403848** [comment]
Thank you very much for your sincere advice, which I find particularly useful. The nucleation mechanism I am using is ternary nucleation, and I am currently trying to modify the code. I have added the variables for the relevant substances to the program, following the original subroutine to add a new subroutine to implement my functionality. However, I haven't quite figured out the ternary nucleation subroutine "napa_nucl" and I don't understand where the numerical parts inside it come from. Another question is that the nucleation mechanism in the original program should be H2SO4-NH3-H2O, right? But I haven't quite understood how these three substances are linked in the code. Is it by inputting the concentrations of H2SO4, NH3, and H2O in the "napa_nucl" subroutine, or how is it handled?

**Comment by theloniuspunk** [comment]
The paper that describes the old Napari scheme is here: https://doi.org/10.1029/2002JD002132 

The model passes it H2SO4, NH3, and relative humidity. The parameterization is just a messy bunch of polynomials that have no physical significance. The native parameterization gives nucleation rates that are way too fast, so it's scaled down in GEOS-Chem-TOMAS by a factor of 1E-5. This works surprisingly well: https://doi.org/10.5194/acp-13-7645-2013

Sam has added the Dunne nucleation schemes from the CLOUD experiments (https://www.science.org/doi/10.1126/science.aaf2649), which includes their ternary schemes. We'll add to the standard code soon, or we could pass you the code. Interestingly, we find that the Dunne ternary scheme needs to be tuned up by 100-1000x, at least in the central US (even while also having the Riccobono organic-H2SO4 scheme on). We suspect that this is because amines are likely important for nucleation in this region, but we currently don't simulation amines.

**Comment by 1392403848** [comment]
Hello, thank you for your sincere advice. I will try to make modifications according to your suggestions. Additionally, you mentioned that the Dunne nucleation scheme should be added to the code. If you could send me the part of the code that needs to be added for reference, that would be greatly appreciated! Have a wonderful day!
