### ISSUE TITLE
Aerosol-only mode using Sulfate_mod to calculate a new SO2 specie

### ISSUE THREAD

**Issue by CraigYEUNG** [geoschem/geos-chem#2480]
### Your name

Craig YEUNG

### Your affiliation

POLYU

### What happened? What did you expect to happen?

I add a new specie as same as SO2, called SO2a into aerosol-only simulation, calculated by sulfate_mod.F90
I only add :
          SO2a0 = Spc(id_SO2a)%Conc(I,J,L)  
          SO2as=SO2a0
          Spc(id_SO2a)%Conc(I,J,L)  = SO2as

it should be low concentration but 
concentration of SO2a is very high and unreasonable distribution!

### What are the steps to reproduce the bug?

cd to Headers/state_chm_mod.F90
change     
State_Chm%Do_SulfateMod_Cld     = .TRUE.
State_Chm%Do_SulfateMod_SeaSalt = .TRUE.

cd to sulfate_mod
add
SO2a0 = Spc(id_SO2a)%Conc(I,J,L) 
below
SO20 = Spc(id_SO2)%Conc(I,J,L)            
 
add
Spc(id_SO2a)%Conc(I,J,L)  = SO2a0
below
Spc(id_SO2)%Conc(I,J,L)  = SO2s(I,J,L)

and add id_SO2a to line 191, and add SO2a0 to line 2466 in sulfate_mod.F90
add SO2a with same information as SO2 into species_database.yml
add SO2a in transport_species in geoschem_config.yml

after simulation for 1day or 1 month,
concentration of SO2a is very high and unreasonable distribution!

### Please attach any relevant configuration and log files.

<img width="456" alt="截屏2024-09-26 19 44 16" src="https://github.com/user-attachments/assets/79c43937-b250-41e3-ab15-e91b52c1056f">

### What GEOS-Chem version were you using?

14.2.2

### What environment were you running GEOS-Chem on?

Local cluster

### What compiler and version were you using?

gcc

### Will you be addressing this bug yourself?

Yes

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

Aerosol

### As what resolution were you running GEOS-Chem?

4x5

### What meterology fields did you use?

GEOS-FP

**Comment by msulprizio** [comment]
Hi @CraigYEUNG. Unfortunately, the GCST does not have the resources to debug customized code. Instead I would refer you to our [debugging pages](https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html). In particular these sections may be of use to you:

- [Send debug printout to the log files](https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html#send-debug-printout-to-the-log-files)
- [Print it out if you are in doubt!](https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html#print-it-out-if-you-are-in-doubt)

**Comment by CraigYEUNG** [comment]
I think this problem is  due to calculation storage, since its result is unreasonable.
Finally I found that I miss to add SO2a to  
!$OMP PRIVATE( SO2, SO2a       )&

after adding it to !$OMP PRIVATE, problem solved.
