### ISSUE TITLE
The program encountered an error during execution.

### ISSUE THREAD

**Issue by ChenBHXMU** [geoschem/geos-chem#2485]
### Your name

Baihua Chen

### Your affiliation

Xiamen University

### Please provide a clear and concise description of your question or discussion topic.

Dear @yantosca 

I hope this message finds you well. 

When I run "cmake ../CodeDir -DRUNDIR=.." , there are some errors.

Thank you for your time and assistance.

Best regards,
Baihua Chen

![微信截图_20240927165246](https://github.com/user-attachments/assets/03ef932d-f3fc-46bd-8ab0-e629f38caa17)

**Comment by yantosca** [comment]
Thanks for writing @ChenBHXMU.  Are you sure you are in the `build/` folder of the run directory when trying to run cmake?

**Comment by ChenBHXMU** [comment]
> Thanks for writing @ChenBHXMU. Are you sure you are in the `build/` folder of the run directory when trying to run cmake?

@yantosca  Yes, I'm sure.  Additionally, when I was downloading the project using Git commands, the download was incomplete. Then I updated the project using the `git submodule update --init --recursive` command. I'm not sure if this process affected the program.

**Comment by yantosca** [comment]
@ChenBHXMU Are you still having problems or can you compile the code now?
