### ISSUE TITLE
Inquiry on Geos-Chem-APM Usage

### ISSUE THREAD

**Issue by ChenBHXMU** [geoschem/geos-chem#2487]
### Your name

Baihua Chen

### Your affiliation

Xiamen University

### Please provide a clear and concise description of your question or discussion topic.

Dear @yantosca 

I hope this message finds you well.

I am currently researching how to utilize Geos-Chem-APM and have encountered an issue. The 'input.geos' file seems to be missing, and I am uncertain about how to proceed with using APM.

Could you please provide guidance or updated documentation on this matter?

Thank you for your assistance.

Best regards,
Baihua Chen

![微信截图_20240929140942](https://github.com/user-attachments/assets/9ca90329-ab59-4df0-a30d-9745dad842b1)

**Comment by yantosca** [comment]
Thanks for writing @ChenBHXMU.  Which version are you using?  If you are using 14.4.0 or later then the input.geos file has been removed and there is now geoschem_config.yml.

Also tagging @ganluoasrc, who is one of the APM developers.

**Comment by yantosca** [comment]
Also the wiki information there may be out of date.

**Comment by ChenBHXMU** [comment]
Dear @ganluoasrc 

I am currently researching how to utilize Geos-Chem-APM and have encountered an issue. The 'input.geos' file seems to be missing, and I am uncertain about how to proceed with using APM. I am using 14.4.0.

Could you please provide guidance or updated documentation on this matter?

Thank you for your assistance.

Best regards,
Baihua Chen

**Comment by ChenBHXMU** [comment]
Thank you for your assistance! @ganluoasrc

**Comment by yantosca** [comment]
I can close out this issue now.  Thanks again @ChenBHXMU and @ganluoasrc
