### ISSUE TITLE
How to archive the rates of each reaction in GEOS-Chem

### ISSUE THREAD

**Issue by lshen2009** [geoschem/geos-chem#2488]
### Your name

Lu Shen

### Your affiliation

Peking University

### Please provide a clear and concise description of your question or discussion topic.

We can define production and loss families for a species (e.g., CH₂Cl₂) in the gckpp.kpp file, and the associated production and loss rates can be archived in the diagnostics. I’m curious if it’s possible to archive the reaction rates for a specific reaction, similar to how P/L rates are archived for individual species. In this case, we want to specifically track and archive the rates for a particular reaction rather than an entire species. Any thoughts? Thank you!

**Comment by yantosca** [comment]
Hi @lshen2009, thanks for writing.  You can archive reaction rate diagnostics in the `RxnConst` history collection, as described here:

- https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/history-diag-guide.html#rxnrates

**Comment by yantosca** [comment]
@lshen2009: also note that this diagnostic may not be working as expected, see #2329.
