### ISSUE TITLE
Issues Adding Chemical Mechanims

### ISSUE THREAD

**Issue by Anna-Gerosolina** [geoschem/geos-chem#2494]
### Your name

Anna Gerosolina

### Your affiliation

Boston College

### Please provide a clear and concise description of your question or discussion topic.

I have a goal of adding new molecules, mechanisms, and rate laws to GEOS-Chem, but am having lots of trouble figuring out how to do it.  I tried a few things that resulted in errors, so am backtracking and trying everything one step at a time.  I am currently trying to just add a dummy molecule to species_database.yml.  My GC.log is not resulting in any errors, nor is it hitting a wall time, but the simulation is not completing (below is end of file).  Any guidance at all is appreciated!

![Screenshot 2024-10-03 065335](https://github.com/user-attachments/assets/393709c8-2e76-4e77-ba1a-46f1620bbbd9)

**Comment by Anna-Gerosolina** [comment]
Hi, thanks so much for the help, I really appreciate it!!!  I have attached the files.  I think I was testing two different methods at once when this was running, but they were in completely different run directories.  We did try to parallelize it for a few months, but kept running into segmentation faults and memory out of bounds errors, so it is currently running on one node and one core.  I have looked at the documentation extensively, but keep getting error messages, so I feel like I am missing something and I am trying to just go step by step at this point.
[GeosChem.zip](https://github.com/user-attachments/files/17246803/GeosChem.zip)

**Comment by yantosca** [comment]
Thanks for your patience @Anna-Gerosolina.  Can you also attach the run script that you are using?  I'm curious why you are getting multiple echos if you are running on 1 core.

**Comment by yantosca** [comment]
Thanks @Anna-Gerosolina.  I think we can get rid of the duplicate outputs to the log file if we use `--hint no-multithread` in the srun command.  Also i think you can run with multiple CPUs.  Save the following to a new run script and then try submitting a new job.

```bash
#!/bin/bash
#SBATCH -c 12
#SBATCH -N 1
#SBATCH -t  1-0:00
#SBATCH --mem=250GB

###############################################################################
### Sample GEOS-Chem run script for SLURM
### You can increase the number of cores with -c and memory with --mem,
### particularly if you are running at very fine resolution (e.g. nested-grid)
###############################################################################

# Set the proper # of threads for OpenMP
# SLURM_CPUS_PER_TASK ensures this matches the number you set with -c above
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

# Run GEOS_Chem.  The "time" command will return CPU and wall times.
# Stdout and stderr will be directed to the "GC.log" log file
# (you can change the log file name below if you wish)
srun --hint=nomultithread -c $OMP_NUM_THREADS time -p ./gcclassic >> GC.log

# Exit normally
exit 0
#EOC
```

**Comment by Anna-Gerosolina** [comment]
Thanks so much! I tried the new run script, but unfortunately that resulted in a lot of segmentation faults. I have attached the log and slurm output files. I have never been able to use multiple cores. I think it may be due to the amount of private variables resulting in memory issues, but have not figured out the reason with certainty. 
[GEOS-Chem.zip](https://github.com/user-attachments/files/17311428/GEOS-Chem.zip)

**Comment by yantosca** [comment]
Thanks @Anna-Gerosolina.  Am wondering if this is something specific to your cluster.  Might be worth reporting the issue to your research computing folks, and ask for suggestions.

**Comment by Anna-Gerosolina** [comment]
Of course, thanks for taking a look at it!  I have already tried contacting our Research Services in order to implement MPI, but we have been unsuccessful.  My goal is to just get the jobs to run even if that requires using only one core.  I am able to run them using only one core so long as I am not trying to add new molecules/mechanisms to the source code.  I will contact Research Services again and see if there are any more suggestions that they have.  I will probably have more questions after meeting with them :)  Thanks again!

**Comment by Anna-Gerosolina** [comment]
Hi, thanks for reaching out!  I am using: Linux l001 4.18.0-477.27.1.el8_8.x86_64 #1 SMP Thu Aug 31 10:29:22 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux.  And sorry, I am not trying to use MPI across nodes, I am just trying to do serial parallelization across cores :).  At this point however, I am totally fine just trying to use one core, it is moreso I am trying to get a normal termination message when putting a dummy variable in as a species.

**Comment by yantosca** [comment]
Thanks @Anna-Gerosolina.  Apologies for the late reply, I was out sick for several days in October.

Have you been able to resolve this issue?  Not knowing much about your system it is difficult for me to advise.

**Comment by Anna-Gerosolina** [comment]
Hi Bob,

    Hope you are feeling better!  Unfortunately I have not fully resolved
the issue yet.  What I am currently trying is using a clean environment and
compiling it on our new cluster instead of our old cluster.  I will let you
know when I have more guided questions.  Thanks so much for reaching out,
and all of your help!

Best,
     Anna :)

**Comment by yantosca** [comment]
Thanks @Anna-Gerosolina.  I am much better now.  

Let's close out this issue for now.  Feel free to open a new GitHub issue if you still have problems on the new cluster.
