### ISSUE TITLE
nested run, GC_RT

### ISSUE THREAD

**Issue by samanehashraf** [geoschem/geos-chem#2501]
### Your name

Samaneh

### Your affiliation

Research associate

### Please provide a clear and concise description of your question or discussion topic.

Hi,
I recently started working with GEOS-Chem RRTMG. I am wondering if a nested run (0.5° x 0.625°) for North America is possible with GC-RT. In the EX data folder (/HEMCO/RRTMG/v2018-11/), I only see MODIS .nc files with 4° x 5° and 2° x 2.5° resolution.

**Comment by yantosca** [comment]
Thanks for your question @samanehashraf.  You should be able to run a GEOS-Chem RRTMG simulation at nested-grid resolution.  HEMCO will regrid the model emissivity etc. data at 2x2.5 will be regridded to the resolution of your nested-grid domain.
