### ISSUE TITLE
The download of GEOS-Chem always fails.

### ISSUE THREAD

**Issue by ChenBHXMU** [geoschem/geos-chem#2503]
### Your name

Baihua Chen

### Your affiliation

Xiamen University

### Please provide a clear and concise description of your question or discussion topic.

Dear @yantosca 

I used "git clone --recurse-submodules https://github.com/geoschem/GCClassic.git GCClassic" to dowload the geos-chem, but it always fails. How should I handle this, or are there other ways to download it?

Thank you for your assistance.

Best regards,
Baihua Chen
![微信截图_20241009133930](https://github.com/user-attachments/assets/31259359-887a-434c-887d-001c10d444b6)

**Comment by yantosca** [comment]
Thanks for writing @ChenBHXMU.  I think this may be due to your network.

You can try this fix (as described [HERE](https://stackoverflow.com/questions/38618885/error-rpc-failed-curl-transfer-closed-with-outstanding-read-data-remaining)
```console
$ git clone http://github.com/geoschem/GCClassic --depth 1
$ cd GCClassic
$ git fetch --unshallow
```

**Comment by yantosca** [comment]
@ChenBHXMU were you able to successfully download GEOS-Chem via Git?

**Comment by ChenBHXMU** [comment]
> @ChenBHXMU were you able to successfully download GEOS-Chem via Git?

Dear @yantosca 

I run these commands, but I still don't solve this question.

Thank you for your help.

Best regard.
Baihua Chen

![微信截图_20241018172721](https://github.com/user-attachments/assets/aaf2d65a-7ad8-41f3-99a7-cf066eb3caaa)

**Comment by yantosca** [comment]
Thanks @ChenBHXMU.  Try running this command:
```console
$ git submodule update --init --recursive
```
