### ISSUE TITLE
SOAS emission in OFFLINE_BIOGENICVOC

### ISSUE THREAD

**Issue by YanshunLi-washu** [geoschem/geos-chem#2504]
### Your name

Yanshun Li

### Your affiliation

Washu

### Please provide a clear and concise description of your question or discussion topic.

Hi Support Team,

I notice that in the OFFLINE_BIOGENICVOC section of HEMCO_Config.rc, there are SOAS emission scaled from precursors:
```console
...
0 BIOGENIC_ISOP_SOAP -                                                                                                            -             -                     -   -  -       SOAP 610 4 2
0 BIOGENIC_ISOP_SOAS -                                                                                                            -             -                     -   -  -       SOAS 610 4 2
...
0 BIOGENIC_LIMO_SOAP -                                                                                                            -             -                     -   -  -       SOAP 611 4 2
0 BIOGENIC_LIMO_SOAS -                                                                                                            -             -                     -   -  -       SOAS 611 4 2
...
0 BIOGENIC_MTPA_SOAP -                                                                                                            -             -                     -   -  -       SOAP 611 4 2
0 BIOGENIC_MTPA_SOAS -                                                                                                            -             -                     -   -  -       SOAS 611 4 2
...
0 BIOGENIC_MTPO_SOAP -                                                                                                            -             -                     -   -  -       SOAP 611 4 2
0 BIOGENIC_MTPO_SOAS -                                                                                                            -             -                     -   -  -       SOAS 611 4 2
...
0 BIOGENIC_SESQ_SOAP -                                                                                                            -             -                     -   -  -       SOAP 612 4 2
0 BIOGENIC_SESQ_SOAS -                                                                                                            -             -                     -   -  -       SOAS 612 4 2
```
Have two questions:
(1) I thought the formation of SOAS should be 100% during chemistry, why we put it into the HEMCO emission module? Feel free to correct me if my understanding is wrong.
(2) Why the scaling factors for SOAP & SOAS are the same?

Thanks,
Yanshun

**Comment by yantosca** [comment]
Thanks for writing @YanshunLi-washu.  I'm tagging the co-chairs of the Emissions WG who may be able to provide more information than I can: @eamarais @jaegle linjt@pku.edu.cn

**Comment by eamarais** [comment]
Hi @YanshunLi-washu, these are fixed mass yields for biogenic VOCs for the simple SOA scheme. These are applied in HEMCO_Config.rc, as these fixed mass yields are tied to emissions. 
In version 14.1.0, the SOA mass yields are 3% for isoprene and 10% for the other biogenic VOCs distributed equally between SOAP and SOAS. GEOS-Chem includes an aging lifetime for SOAP to convert to SOAS. This I think is still dealt with in carbon_mod.F90.

**Comment by YanshunLi-washu** [comment]
Hi @eamarais , thanks a lot for these info! So the mass yields of SOA from isoprene and other VOCs are actually chemical process and we put it in the HEMCO module just for easy implementation? Or do we really we primary SOAS emissions?

**Comment by eamarais** [comment]
Hi @YanshunLi-washu, these mass yields are in HEMCO because these are tied to the emissions and HEMCO is the emissions processing package for GEOS-Chem. As stated in Pai et al. (https://acp.copernicus.org/articles/20/2637/2020/acp-20-2637-2020.pdf), the simple scheme assumes 50% of the SOA (SOAS) is formed promptly (soon after emission) and the other 50% (SOAP) evolves gradually to SOAS with a lifetime of a day.

**Comment by YanshunLi-washu** [comment]
Got it @eamarais Thank you so much for the explanation and recommending the paper! Just further curious about the relationship between VOCs and SOAP. Is SOAP some special category of VOC that will form SOA through aging?

**Comment by YanshunLi-washu** [comment]
Thanks @eamarais for the explanation. It's really helpful!
