### ISSUE TITLE
Encountering the warning of “Program received signal SIGSEGV: Segmentation fault - invalid memory reference.” when running command “./gcclassic > GC.log &”

### ISSUE THREAD

**Issue by Chuanhui0601** [geoschem/geos-chem#2505]
### Your name

Allen WEI

### Your affiliation

University of Southampton

### Please provide a clear and concise description of your question or discussion topic.

When I run the command "./gcclassic > GC.log &", terminal response in following:
```console
(base) allenwei@Allen gc_4x5_merra2_fullchem % ./gcclassic > GC.log &
[1] 56613
(base) allenwei@Allen gc_4x5_merra2_fullchem % 
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x1123fed0f
#1  0x1123fdd63
#2  0x18b6e2a83
#3  0x1005b8347
#4  0x1005b8347
#5  0x1002d05a7
#6  0x100866827

[1]  + segmentation fault  ./gcclassic > GC.log
```
Running equipment: Macbook Pro Apple M1 Max
Running file: geos-chem file.zip
Running command collection: geos-chem running command.zip
All related docs are attached below:

[geos-chem running command.zip](https://github.com/user-attachments/files/17304752/geos-chem.running.command.zip)
https://drive.google.com/file/d/1t6Y5Xw1z5fMjXr5dOb3MnjfX-jqFPImy/view?usp=sharing

**Comment by Chuanhui0601** [comment]
by the way, "input.geos.txt" doesn’t generate.

**Comment by yantosca** [comment]
Thanks for writing @Chuanhui0601.  We don't have a lot of experience running GEOS-Chem on a Macbook Pro.  I am not sure the fullchem simulation would work but maybe simpler simulations (with less species) like the carbon simulation or the TransportTracers simulation would.

Also, on MacOSX, the maximum stack memory is 65532 KB.  This might not be enough to run a GEOS-Chem simulation.  

If you have access to a machine running any flavor of Linux, I would try that.  You can also run GEOS-Chem on the AWS Cloud as described at https://geos-chem.readthedocs.io.

**Comment by yantosca** [comment]
@Chuanhui0601 I forgot to mention that the "stack" is the area of memory where the computer will store local subroutine variables (those that aren't declared with SAVE, or those not at the top of a module) as well as any parallel loop variables declared `!$OMP PRIVATE` or `!$OMP THREADPRIVATE`.  Because of the low limit on MacOS, this may prevent you from running a GEOS-Chem simulation.
