### ISSUE TITLE
Dry Dep flux for OCPO and OCPI in Kg/s from GEOSChem.DryDep diagonestic which have dry dep in molecules/cm-2/s

### ISSUE THREAD

**Issue by wahababdul638** [geoschem/geos-chem#2509]
### Your name

Abdul Wahab

### Your affiliation

Chulalongkor University

### Please provide a clear and concise description of your question or discussion topic.

I am trying to get OCPI and OCPO fluxes in kg/s to calculate OC budget for the Southeast Asia. GEOSChem.DryDep diagnoestic gives dry dep flux in molecules/cm-2/s. When i try to convert molecules/cm-2/s to kg/s using molecular weight of 12.01 for OCPO, I end up with a dry dep flux value of 2.87 kg/s, which is a positive number. But wet dep flux which i got from GEOSChem.Budget diagonestic is negative number (-0.018 kg/s). Is it normal to have a positive drydep flux and negative wet dep flux since both are the removals. I am getting flux by using this.

**Comment by yantosca** [comment]
Thanks for writing @wahababdul638.  Wet deposition also includes re-evaporation, which is interpreted as a negative flux.
