### ISSUE TITLE
How to modify the emission inventory?

### ISSUE THREAD

**Issue by ChenBHXMU** [geoschem/geos-chem#2520]
### Your name

Baihua Chen

### Your affiliation

Xiamen University

### Please provide a clear and concise description of your question or discussion topic.

Dear @yantosca 

I hope this letter finds you well. 

I have modified the file ExtData/HEMCO/NH3/v2019-08/NH3_geos.2x25.nc, reducing its concentration by half. The model covers the time period from July to November 2019. However, when I compared the files in the output, the concentration in SpeciesConcVV_NH3 did not change compared to the output concentration under the normal emission inventory. I am not sure where I made a mistake.

Best regards
Baihua Chen

**Comment by ChenBHXMU** [comment]
> Thanks for writing @ChenBHXMU. You shouldn't have to modify the source file to change emissions. WIth HEMCO you can define a scale factor of 0.5 that can be applied to emission entries. Please see our documentation at hemco.readthedocs.io for more information:
> 
> * [The HEMCO configuration file](https://hemco.readthedocs.io/en/stable/hco-ref-guide/hemco-config.html#scale-factors)
> * [Scale factors](https://hemco.readthedocs.io/en/stable/hco-ref-guide/hemco-config.html#scale-factors)

Dear @yantosca 

Thank you for your help. I have read the contents. The HEMCO file contains many types of emissions. The information provided by this URL offers emission data from GFED. However, I still don't know how to modify the scale of anthropogenic emissions, such as the scale of anthropogenic NOx or NH3 emissions.

Thank you!

Best regards
Baihua Chen

**Comment by yantosca** [comment]
@ChenBHXMU: Try something like this:
```console
###############################################################################
### BEGIN SECTION BASE EMISSIONS
###############################################################################
# ExtNr Name sourceFile sourceVar sourceTime C/R/E SrcDim SrcUnit Species ScalIDs Cat Hier

MY_EMISSION_NH3  /path/to/netcdf/file  NH3 1980-2024/1-12/1/0 C xy kg/m2/s NH3 500 1 1

### END SECTION BASE EMISSIONS ###

###############################################################################
### BEGIN SECTION SCALE FACTORS
###############################################################################
# ScalID Name srcFile srcVar srcTime  CRE Dim Unit Oper

500 ONE_HALF 0.5 - - - 1 1

### END SECTION SCALE FACTORS ###
```
You can adapt this to your `HEMCO_Config.rc` but you get the idea.

**Comment by ChenBHXMU** [comment]
> @ChenBHXMU: Try something like this:
> 
> ```
> ###############################################################################
> ### BEGIN SECTION BASE EMISSIONS
> ###############################################################################
> # ExtNr Name sourceFile sourceVar sourceTime C/R/E SrcDim SrcUnit Species ScalIDs Cat Hier
> 
> MY_EMISSION_NH3  /path/to/netcdf/file  NH3 1980-2024/1-12/1/0 C xy kg/m2/s NH3 500 1 1
> 
> ### END SECTION BASE EMISSIONS ###
> 
> ###############################################################################
> ### BEGIN SECTION SCALE FACTORS
> ###############################################################################
> # ScalID Name srcFile srcVar srcTime  CRE Dim Unit Oper
> 
> 500 ONE_HALF 0.5 - - - 1 1
> 
> ### END SECTION SCALE FACTORS ###
> ```
> 
> You can adapt this to your `HEMCO_Config.rc` but you get the idea.

Dear @yantosca 

Thank you for your help!

But I have other question. This scaleID corresponds to multiple locations and different values; how should I handle this?

Best regards
Baihua Chen

![微信截图_20241017173702](https://github.com/user-attachments/assets/0c88c7ce-959a-45e4-bf99-126e31470b56)
![微信截图_20241017173357](https://github.com/user-attachments/assets/8b93edd1-e238-42da-9a3f-9603f086d865)

**Comment by yantosca** [comment]
Thanks @ChenBHXMU.  As explained in the ReadTheDocs, a scale factor with 24 values is interpreted as hourly, and a scale factor with 31 values is interpereted as daily.  We would recommend reading the documentation thoroughly if you haven't yet already. 

- [The HEMCO configuration file](https://hemco.readthedocs.io/en/stable/hco-ref-guide/hemco-config.html#scale-](https://hemco.readthedocs.io/en/stable/hco-ref-guide/hemco-config.html#scale-factors)
