### ISSUE TITLE
"KPP integration failed!" with GCClassic 14.4.3

### ISSUE THREAD

**Issue by Liyl2** [geoschem/geos-chem#2524]
### Your name

Yali LI

### Your affiliation

Southern University of Science and Technology

### What happened? What did you expect to happen?

Hello, I'm running carbon mechanism (CH4 only) based on GCClassic v14.4.3， but I'm having problems: KPP integration failed!
![屏幕截图 2024-10-17 145333](https://github.com/user-attachments/assets/48703d01-c4de-468f-bb2f-d6469fd03497)

I rebuilt the carbon mechanism with the latest KPP version 3.1.1 although no changes have been made (. /build_mechanism.sh carbon,) and the carbon mechanism is as low as v2.5.0, which I think is sufficient. Other than that, I simply did the following configurations:
1. I didn't find Restart file for GC14.4.0 (http://geoschemdata.wustl.edu/ExtData/), so I used GC14.3.0 instead.
2. for HEMCO, I turned off EDGARv8 and changed ‘EFYO’ to ‘CYS’ for SPC_.

I also tried using the KPP v2.5.0 version and still have the same problem. Had the same problem with GCClassic 14.3.1.

### What are the steps to reproduce the bug?

KPP mechanism rebuilt, GC compiles all fine. Bugs appear after committing tasks.

### Please attach any relevant configuration and log files.

[GC.log](https://github.com/user-attachments/files/17407651/GC.log)
[geoschem_config.yml.txt](https://github.com/user-attachments/files/17407654/geoschem_config.yml.txt)
[HEMCO_Config.rc.txt](https://github.com/user-attachments/files/17407655/HEMCO_Config.rc.txt)
[HISTORY.rc.txt](https://github.com/user-attachments/files/17407656/HISTORY.rc.txt)
[summarize_build.txt](https://github.com/user-attachments/files/17407657/summarize_build.txt)

### What GEOS-Chem version were you using?

GCClassic 14.4.3

### What environment were you running GEOS-Chem on?

Local cluster

### What compiler and version were you using?

gcc 11.2.0，ifort18.0.5 

### Will you be addressing this bug yourself?

Yes

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

Carbon

### As what resolution were you running GEOS-Chem?

4x5°，47L

### What meterology fields did you use?

MERRA-2

**Comment by Liyl2** [comment]
Hi，Hello, I realised that I was using fullchem's Restart before, so reused carbon's Restart (http://geoschemdata.wustl.edu/ExtData/GEOSCHEM_RESTARTS/v2023-01/), but still the same problem: KPP integration failed![image](https://github.com/user-attachments/assets/48e2b057-86f0-44bf-a4d2-a6db280572a4)

**Comment by lizziel** [comment]
Hi Liyl2, are you able to run with the out-of-the-box code, without rebuilding KPP?

**Comment by Liyl2** [comment]
> Hi Liyl2, are you able to run with the out-of-the-box code, without rebuilding KPP?

Hi @lizziel , I ran the source code without rebuilding KPP, it was the same problem, and I was confused because of it.

**Comment by lizziel** [comment]
Could you try a 72 level run, with verbose turned on in `geoschem_config.yml`?

**Comment by Liyl2** [comment]
> Could you try a 72 level run, with verbose turned on in `geoschem_config.yml`?

I have also tried the 72 level carbon simulation, still the same problem. I have been using GCClassic 14.0.2 before, and it worked fine. This is my first time trying the carbon mechanism, and it is strange that even the most primitive code cannot run.

**Comment by Liyl2** [comment]
I also tried fullchem simulation and CH4 simulation based on GCClassic v14.0.3, they are worked well. However, using the carbon mechanism to simulate CO2 does not work either, so it seems to be a problem with the carbon mechanism, but there is no ERROR at compile time, which has puzzled me for a long time. I want to add species to the carbon mechanism, so need to go through the carbon mechanism. Maybe you can give me some tips on what to check first. Thanks!

**Comment by lizziel** [comment]
Could you include your entire log file here? If you add extension `.txt` then you can drag and drop it into the comment box.

**Comment by lizziel** [comment]
Also, did you build with `-DMECH=carbon`?

**Comment by Liyl2** [comment]
> Could you include your entire log file here? If you add extension `.txt` then you can drag and drop it into the comment box.

![image](https://github.com/user-attachments/assets/3355a94a-a17b-451e-bcab-9677367a0d35)

Hi, I've uploaded the GC.log file above. I am sure that I have used -DMECH=carbon and the compilation message also shows that the carbon mechanism has been successfully used.

**Comment by lizziel** [comment]
I am tagging @msulprizio on this since she fixing some problems with the carbon simulation. However, I don't think the problems involved KPP integration errors. Melissa, have you seen this issue before?

**Comment by msulprizio** [comment]
I have not encountered this error. Our carbon simulations are regularly passing integration tests (i.e. they run successfully for 1-hour for carbon, carbon-CH4 only, carbon-CO2 only, and carbon-CO only). 

@Liyl2 I would recommend following suggestions in our [debug guide](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html) to see if you can identify the issue. This would include seeing if you can run with the out-of-the-box configuration, turning on debug output to log files, etc. 

You may also want to try running with the `dev/14.5.0` branch to obtain additional fixes to the carbon simulation. In the GCClassic wrapper, do (1) git pull origin`, (2)`git checkout dev/14.5.0`, (3) `git submodule update --init --recursive`. Then create a fresh run directory, build GEOS-Chem, and try running. 

As Lizzie mentions above, I am working on additional fixes for CO2 in the carbon simulation in https://github.com/geoschem/geos-chem/pull/251](https://github.com/geoschem/geos-chem/pull/2510. Those fixed will go into version 14.5.1, but the carbon simulation should run even without those fixes -- CO2 will just be wrong.

**Comment by Liyl2** [comment]
Hi, @msulprizio Thanks for your suggestion. I was going to use the GDB debugger to find my error, but when I used Debug mode it successfully ran the carbon mechanism based on GCClassic 14.4.3! Although the Release version still do not work. Is there a big difference between Debug and Release versions? Can I run it in Debug?

**Comment by yantosca** [comment]
Thanks for your patience @Liyl2.  The `-DCMAKE_RELEASE_TYPE=Debug` will cause the model to run more slowly.  This is because several runtime error checks will be activated (e.g. checking for array out-of-bounds errors, uninitialized variables, floating-point math errors, etc.)
