### ISSUE TITLE
Why is the default meteorological input path of my nesting setting inconsistent with my geoschem_config.yml setting?

### ISSUE THREAD

**Issue by LittleFeify** [geoschem/geos-chem#2529]
### Your name

Feify

### Your affiliation

South university of science and technology

### Please provide a clear and concise description of your question or discussion topic.

I'm using GEOS-Chemv14.4.3. The outer layer runs the global mode 4*5 from July to August 2019. The boundary file can be output normally. Then I use a nest to simulate the Asian region, 0.5*0.625. The default meteorological input file is for 2015, which differs from my setting. The meteorological file settings are in HEMCO_Config.rc.gmao_metfields. But where can the default settings be modified? Why can the default settings of the outer layer be linked correctly?
Can I change the path on the HEMCO_Config.rc.gmao_metfields?

#---CN fields---
FRLAKE    $METDIR/$CNYR/01/$MET.$CNYR0101.CN.$RES.$NC, The $CNYR is default?

**Comment by lizziel** [comment]
Hi @LittleFeify, the meteorology files that are called "CN fields" are constants. The same values are used for every year of your simulation. There should only be a few of these fields with all of the rest of the meteorology varying in time.

**Comment by LittleFeify** [comment]
Thanks for your reply. I understand.
