### ISSUE TITLE
[QUESTION] about the NEI ship emission

### ISSUE THREAD

**Issue by katiegrace-3000** [geoschem/geos-chem#253]
I am doing 2 simulations,
one is the control global run, with APEI true, MIX true, DICE-Africa true, NEI true, global anthropogenic emission true, SHIP true and CEDS_SHIP True, 1 month simulation is completed. While if I turned on NEI SHIP as True along with SHIP true and CEDS_SHIP True, it didn't go through. 

My another simulation is set APEI false, MIX false, DICE-Africa false, NEI true, global anthropogenic emission false, SHIP false and CEDS_SHIP false and NEI SHIP true. This simulation is to zero out all the anthropogenic emission outside of U.S. Based on this https://github.com/geoschem/geos-chem/issues/173
SHIP False means no ship emission is used. I wondered is it possible  to use only NEI SHIP? Could SHIP False and NEI SHIP ture work ?  This 1 month simulation is completed. Another thing is I wondered should this setting be OK concerning zero out the outside anthropogenic emission? Thanks a lot.

**Comment by yantosca** [comment]
Thanks for writing.  Note that turning SHIP to false will turn off all ship emissions. That is a master switch.

You should keep SHIP true and then turn off individually the inventories you don't want.

**Comment by yantosca** [comment]
I am closing this out for now.  Feel free to reopen.
