### ISSUE TITLE
Adding HCN to my spin up simulation gives me an error

### ISSUE THREAD

**Issue by julietajuncosa** [geoschem/geos-chem#2530]
### Your name

Julieta Juncosa Calahorrano

### Your affiliation

UMN

### What happened? What did you expect to happen?

Hello, I am starting a spin up simulation from 20180701-20190701.

### What are the steps to reproduce the bug?

 I have added HCN to KPP (running a custom mechanism), my species_database.yml, and the list of advected species in geoschem_config.yml. I also added it to the list of species on HEMCO_Config.yml for GFED and SeaFlux. However, my simulation breaks after just a while with the error shown below. 
![Screenshot 2024-10-21 at 11 21 38 AM](https://github.com/user-attachments/assets/897e8668-8fc5-4331-bdec-4749f88ba810)

### What GEOS-Chem version were you using?

14.3.0

### What environment were you running GEOS-Chem on?

Local cluster

### What compiler and version were you using?

gfortran 8.2

### Will you be addressing this bug yourself?

No

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

Full chemistry

### As what resolution were you running GEOS-Chem?

4x5

### What meterology fields did you use?

MERRA-2

**Comment by yantosca** [comment]
Thanks for writing and thanks for your patience @julietajuncosa.  I was unexpectedly out of the office for the last few days.

You will also need to update the GFED emission factors for HCN in the `HEMCO/src/Extensions/hcox_gfed_include_gfed4.H` file.  Here you would list the following emission factors in kg HCN / kg dry matter:
```F90
!  The Inst%GFED4_EMFAC array contains emission factors in kg/kgDM or kgC/kgDM
!  Inst%GFED4_EMFAC(N,1) = Savanna, grassland, and shrubland fires Emission Factor
!  Inst%GFED4_EMFAC(N,2) = Boreal forest fires Emission Factor
!  Inst%GFED4_EMFAC(N,3) = Temperate forest fires Forest Emission Factor
!  Inst%GFED4_EMFAC(N,4) = Deforestation (tropical) and degradation Emission Factor
!  Inst%GFED4_EMFAC(N,5) = Peat fires Emission Factor
!  Inst%GFED4_EMFAC(N,6) = Agricultural waste burning Emission Factor
```
See: https://github.com/geoschem/HEMCO/blob/main/src/Extensions/hcox_gfed_include_gfed4.H
