### ISSUE TITLE
CLOUDJ_ERROR

### ISSUE THREAD

**Issue by yonghumu** [geoschem/geos-chem#2531]
### Your name

Liu Meng

### Your affiliation

LZU

### What happened? What did you expect to happen?

Hello I first run a fullchem simulation using GCClassic (dryrun), I added some reminders that the missing data later runs still have problems：
```
 CLOUDJ_ERROR: Error in read --> LOCATION:  -> at RD_XXX in module cldj_init_mod.F90
 CLOUDJ_ERROR: Error in RD_XXX --> LOCATION:  -> at INIT_CLDJ in module cldj_init_mod.F90
==========================================================================

GEOS-Chem ERROR: Error encountered in subroutine Init_Cldj within Cloud-J photolysis
 -> at Init_CloudJ (in module GeosCore/cldj_interface_mod.F90)
==========================================================================

==========================================================================
GEOS-Chem ERROR: Error encountered in "Init_CloudJ"!
 -> at Init_Photolysis  (in module GeosCore/photolysis_mod.F90)
==========================================================================

==========================================================================
GEOS-CHEM ERROR: Error encountered in "Init_Photolysis"!
STOP at  -> at GEOS-Chem (in GeosCore/main.F90)
==========================================================================
     - CLEANUP: deallocating arrays now...

```

### What are the steps to reproduce the bug?

./gcclassic > GC.log 2>&1

### Please attach any relevant configuration and log files.

[HISTORY.rc.txt](https://github.com/user-attachments/files/17469325/HISTORY.rc.txt)
[geoschem_config.txt](https://github.com/user-attachments/files/17469332/geoschem_config.txt)

### What GEOS-Chem version were you using?

14.4.3

### What environment were you running GEOS-Chem on?

Local cluster

### What compiler and version were you using?

gcc 10.2.0

### Will you be addressing this bug yourself?

No

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

Full chemistry

### As what resolution were you running GEOS-Chem?

2×2.5

### What meterology fields did you use?

MERRA-2

**Comment by yonghumu** [comment]
This is a new problem for me
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

NF90_Def_Var: can not create compressed variable : time

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

NcDef_var_attributes_c: can not define attribute : long_name

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Code stopped from DO_ERR_OUT (in module NcdfUtil/m_do_err_out.F90)

This is an error that was encountered in one of the netCDF I/O modules,
which indicates an error in writing to or reading from a netCDF file!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by lizziel** [comment]
@yonghumu, could include the entire GEOS-Chem log file? If you change the extension to .txt then you can drag and drop it into the comment box.

**Comment by yonghumu** [comment]
[GC.log](https://github.com/user-attachments/files/17483737/GC.log)
OK, this is the entire file, thank you.

**Comment by gopikrishnangs44** [comment]
@lizziel, I too came across a similar issue, while saving the ConcAfterChemistry file in GCClassic 14.4.3

```
---> DATE: 2018/01/01  UTC: 11:50
     - Creating file for ConcAfterChem; reference = 20180101 000000
        with filename = OutputDir/GEOSChem.ConcAfterChem.20180101_0000z.nc4

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

NF90_Def_Var: can not create compressed variable : concAfterChem_MO2

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

NcDef_var_attributes_c: can not define attribute : long_name

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Code stopped from DO_ERR_OUT (in module NcdfUtil/m_do_err_out.F90)

This is an error that was encountered in one of the netCDF I/O modules,
which indicates an error in writing to or reading from a netCDF file!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by lizziel** [comment]
This looks like an issue with installation of your netcdf library. Do you have system administrator on you cluster who could help check your install?

**Comment by yonghumu** [comment]
![image](https://github.com/user-attachments/assets/505e9295-1fd0-485e-9f59-52d2bfd9ea24)
This is the dependency library that I installed, no error with the installation, Can you recommend a more suitable version？

**Comment by gopikrishnangs44** [comment]
@lizziel, I got it solved. The error came because there was repetion of ConcAfterChem_OH in the HIstory.rc

Thank You

**Comment by yantosca** [comment]
Thanks @lizziel and @gopikrishnangs44.  We can close out this issue.
