### ISSUE TITLE
Modify the budget diagnosis lev output to each layer information

### ISSUE THREAD

**Issue by zpleo** [geoschem/geos-chem#2533]
### Your name

Zhang Peng

### Your affiliation

Southern University of Science and Technology

### Please provide a clear and concise description of your question or discussion topic.

I modified state_diag_mod.F90 and diagnostics_mod.F90 to output the budget diagnostics as information for each layer, but after successfully installing the GC, there was no error when running the terminal?
[run_7502809.err.txt](https://github.com/user-attachments/files/17488149/run_7502809.err.txt)

[diagnostics_mod.txt](https://github.com
[GC.txt](https://github.com/user-attachments/files/17488147/GC.txt)
/user-attachments/files/17488131/diagnostics_mod.txt)

[state_diag_mod.txt](https://github.com/user-attachments/files/17488128/state_diag_mod.txt)

**Comment by zpleo** [comment]
[diagnostics_mod.txt](https://github.com/user-attachments/files/17488165/diagnostics_mod.txt)
[GC123.txt](https://github.com/user-attachments/files/17488170/GC123.txt)

**Comment by lizziel** [comment]
@zpleo, I suggest you create a new diagnostic if you want budget for every layer.
