### ISSUE TITLE
Segmentation fault (core dumped)，need help！

### ISSUE THREAD

**Issue by dyblove** [geoschem/geos-chem#2540]
### Your name

Yibo Dou

### Your affiliation

PKU

### What happened? What did you expect to happen?

I am learning GEOS-Chem through Quickstart Guide, I am executing
`./gcclassic > GC.log 2>&1 `
but there is a problem, I didn't get the output I wanted, there is no output file in OutputDir.
I am curious to know what to do. I also provided my HEMCO_Config.rc, which is not in the original running directory.
I created myself, but I don't know how to write the configuration content in it so that my program can complete the simulation.
[GC.log](https://github.com/user-attachments/files/17571339/GC.log)
[HEMCO_Config.txt](https://github.com/user-attachments/files/17571355/HEMCO_Config.txt)

### What are the steps to reproduce the bug?

I followed the steps in the Quickstart Guide exactly, but there seemed to be a problem with the data download, although there were no errors. I didn't get the output I wanted, there is no output file in OutputDir.

### What GEOS-Chem version were you using?

14.4.3

### What environment were you running GEOS-Chem on?

Other (please explain below)

### What compiler and version were you using?

GCC 7.4.0

### Will you be addressing this bug yourself?

No

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

Full chemistry

### As what resolution were you running GEOS-Chem?

4*5

### What meterology fields did you use?

MERRA-2

**Comment by dyblove** [comment]
Your answer helped me a lot! I wonder how I can get it if I don't get HEMCO_Config.rc when creating the run directory, I can't get the default HEMCO_Config.rc setting, which causes me to be unable to confirm what exactly I'm missing? Looking forward to your reply, I would appreciate it very much!

**Comment by dyblove** [comment]
> Thanks for writing @dyblove. Your log file has this error:
> 
> ```
> Reading fields of HEMCO configuration file: HEMCO_Config.rc
> ===============================================================================
> GEOS-CHEM ERROR: Could not find FRLAKE in HEMCO data list!
> STOP at GET_MET_2D (get_met_mod.F90)
> ===============================================================================
>      - CLEANUP: deallocating arrays now...
> ```
> 
> Please make sure that you have the `MERRA2.20150101.CN.4x5.nc4` file, which you can obtain from the link below.
> 
> https://geos-chem.s3-us-west-2.amazonaws.com/GEOS_4x5/MERRA2/2015/01/MERRA2.20150101.CN.4x5.nc4

Your answer helped me a lot! I wonder how I can get it if I don't get HEMCO_Config.rc and HISTORY.rc when creating the run directory, I can't get the default HEMCO_Config.rc setting, which causes me to be unable to confirm what exactly I'm missing? Looking forward to your reply, I would appreciate it very much!

**Comment by yantosca** [comment]
> Your answer helped me a lot! I wonder how I can get it if I don't get HEMCO_Config.rc and HISTORY.rc when creating the run directory, I can't get the default HEMCO_Config.rc setting, which causes me to be unable to confirm what exactly I'm missing? Looking forward to your reply, I would appreciate it very much!

Oh OK, I think I know what you mean.  The met field entries for HEMCO are located in the `[HEMCO_Config.rc.gmao_metfields](https://github.com/geoschem/geos-chem/blob/main/run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.gmao_metfields) file, which is located in the run directory.  This file is "included" into the `HEMCO_Config.rc` file.
