### ISSUE TITLE
HgClHO2 entry in species-database.yml has duplicate key WD_RetFactor

### ISSUE THREAD

**Issue by mbertolacci** [geoschem/geos-chem#2546]
### Your name

Michael Bertolacci

### Your affiliation

University of Western Australia

### What happened? What did you expect to happen?

The entry for HgClHO2 in the default species-database.yml (run/shared/species-database.yml) has the property WD_RetFactor duplicated twice, which can fail YAML validation. I discovered this when trying to read the file into R using the R yaml package.

### What are the steps to reproduce the bug?

Install yamllint or similar, and run `yamllint species-database.yml`

### What GEOS-Chem version were you using?

14.4.0

### What environment were you running GEOS-Chem on?

Personal computer

### What compiler and version were you using?

N/A

### Will you be addressing this bug yourself?

No

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

TransportTracers

### As what resolution were you running GEOS-Chem?

N/A

### What meterology fields did you use?

GEOS-FP

**Comment by yantosca** [comment]
Thanks for finding this @mbertolacci.  We can get this into the upcoming 14.5.1 bugfix version.

**Comment by yantosca** [comment]
We can now close this issue as it has now been merged into the 14.5.1 development stream.
