### ISSUE TITLE
an error in writing to or reading from a netCDF file

### ISSUE THREAD

**Issue by yonghumu** [geoschem/geos-chem#2547]
### Your name

Liu

### Your affiliation

LZU

### What happened? What did you expect to happen?

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

NF90_Def_Var: can not create compressed variable : time

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

NcDef_var_attributes_c: can not define attribute : long_name

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Code stopped from DO_ERR_OUT (in module NcdfUtil/m_do_err_out.F90)

This is an error that was encountered in one of the netCDF I/O modules,
which indicates an error in writing to or reading from a netCDF file!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### What are the steps to reproduce the bug?

./gcclassic

### What GEOS-Chem version were you using?

14.4.3

### What environment were you running GEOS-Chem on?

Local cluster

### What compiler and version were you using?

gcc 10.2.0

### Will you be addressing this bug yourself?

No

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

Full chemistry

### As what resolution were you running GEOS-Chem?

2×2.5

### What meterology fields did you use?

MERRA-2

**Comment by yonghumu** [comment]
nf-config --version
netCDF-Fortran 4.5.3
nc-config --version
netCDF 4.7.4
geoschem_config.yml和HISTORY.rc只是把模拟时间改成了一个小时

**Comment by yantosca** [comment]
Thanks for writing @yonghumu and thanks for your patience.  I've been traveling recently.

Would you be able to attach the full log file from the run that failed to this issue?  I can take a look.

Also, please make sure that you are not exceeding your disk quota.  You may get an error like this if you have filled up all of your disk space.
