### ISSUE TITLE
[FEATURE REQUEST] Expanding types of variables that can be saved out using ObsPack

### ISSUE THREAD

**Issue by chfite** [geoschem/geos-chem#255]
Preface: I am still somewhat new to GEOS-Chem and maybe this question/request has already been addressed:

Is there any headway into making obspack_mod have the capability to save out variables other than just the advected species from input.geos? I am using Planeflight right now because it has the option to save out additional variables (like AOD), and it is relatively easy to make modifications to get a particular variable you want using a new CASE statement. I've made my own modifications to Planeflight code to have it save out specific AOD values, j-values, and other Met variables I needed.  It does not seem as easy to add some of these options to obspack_mod (at least with my limited background working with GC source code). 

The main reason I am asking or hoping for this feature in future ObsPack versions is because ObsPack appears to be much quicker at saving out data than Planeflight, at least in what I have seen so far since using both.

**Comment by yantosca** [comment]
Thanks for writing.  ObsPack was supplied to us by a third party (Andy Jacobson at NOAA) so we implemented it more or less as it was given to us.

We welcome updates from the GEOS-Chem community to extend the functionality of ObsPack. But we regret that we cannot ourselves work on this right now.

**Comment by yantosca** [comment]
See PR #687 which allows all advected species to be output via ObsPack.
