### ISSUE TITLE
A problem when I ran gcclassic.exe

### ISSUE THREAD

**Issue by Leonardchenll** [geoschem/geos-chem#2551]
### Your name

Liliang Chen

### Your affiliation

Chinese research academy of Environmental Science

### What happened? What did you expect to happen?

I could run cmake make make install successfully.However, after I ran the gcclassic.exe,it went like 
![图片](https://github.com/user-attachments/assets/3e7371d0-7431-49cb-b570-2a2081c5c2c9)
But I have access to read the file and dictionary 
![图片](https://github.com/user-attachments/assets/2e0da6ff-52d1-4f20-8108-432071ba28cd)

### What are the steps to reproduce the bug?

the step od  ./gcclassic
the results of cmake is 
![图片](https://github.com/user-attachments/assets/7793d140-e6ba-4b77-bbcc-2ae01d432b9b)
And there is no problem when run make 
![图片](https://github.com/user-attachments/assets/e91a3264-231d-4ec7-ae29-cca6c8145932)
So what is the problem 

I really appreciate it if anyone helps me.

### What GEOS-Chem version were you using?

14.4.3

### What environment were you running GEOS-Chem on?

Local cluster, Personal computer

### What compiler and version were you using?

gcc 11.2.0,netcdf-c.4.8.0  netcdf-f 4.5.3

### Will you be addressing this bug yourself?

Yes

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

Full chemistry

### As what resolution were you running GEOS-Chem?

4x5

### What meterology fields did you use?

MERRA-2

**Comment by yantosca** [comment]
Thanks for writing @Leonardchenll.  It could be that the file is incomplete or corrupted (maybe due to an incomplete download). Try downloading that particular file again and see if you get past the error.
