### ISSUE TITLE
About setting MEGAN in HEMCO_Config.rc file

### ISSUE THREAD

**Issue by yangning-code** [geoschem/geos-chem#2558]
### Your name

Ning Yang

### Your affiliation

JNU

### Please provide a clear and concise description of your question or discussion topic.

I am using GEOS-Chem to simulate pollutants for 2023, but I want to use the online MEGAN emissions for 2013. How should I set it up to achieve this?

**Comment by msulprizio** [comment]
Hi @yangning-code. You can simply set the following in HEMCO_Config.rc:

```
--> OFFLINE_BIOGENICVOC    : false

108     MEGAN                  : on
```

If you would like to utilize the biogenic emissions output diagnostic, you will also need to modify all Biogenic entries in `HEMCO_Diagn.rc` to use `ExtNr  Cat` of `108    -1` (to get the field from the MEGAN extention 108) instead of `0      4` (to get the field from the base emissions).

**Comment by yangning-code** [comment]
Thank you very much. You may have misunderstood what I meant. What I meant was that I am now simulating pollutants for 2023, and the online emission MEGAN also uses 2023, but now I just want to change MEGAN to 2013 emissions. I don’t know how to set up the online MEGAN emissions so that when I run 2023, the MEGAN list for 2013 is called.

**Comment by msulprizio** [comment]
@yangning-code HEMCO extensions will use the meteorology for the simulation dates. 

One way to use 2013 MEGAN emissions is to run your simulation for 2013, keeping in mind that GEOS-Chem will also use 2013 meteorology for the other operations (transport, etc.). If using that method, you can set [`Emission Year`](https://hemco.readthedocs.io/en/stable/hco-ref-guide/hemco-config.html#emission-year) in the settings section of HEMCO_Config.rc to 2023 for the base emissions inventories.

If you wish to simulate GEOS-Chem with 2023 meteorology, all other emissions with 2023 (or latest year available), and only change MEGAN to use 2013 emissions, then you may want to consider running the [HEMCO standalone](https://hemco.readthedocs.io/en/stable/hco-sa-guide/create-rundir.html) for 2013 and saving out 2013 MEGAN emissions via the HEMCO diagnostics. You can then update HEMCO_Config.rc to read those fields (in a similar manner to what is done for the offline biogenic VOC emissions).

**Comment by yangning-code** [comment]
Thank you very much
