### ISSUE TITLE
Some trace metals simulation config files claim to be for transport tracers simulations

### ISSUE THREAD

**Issue by ihough** [geoschem/geos-chem#2559]
### Your name

Ian Hough

### Your affiliation

Université Grenoble Alpes

### What happened? What did you expect to happen?

After using `run/GCClassic/createRunDir.sh` to create a run dir for a trace metals simulation, the comments at the top of `HEMCO_Config.rc` and `HISTORY.rc` incorrectly state that the files are customized for 'Transport Tracers' simulations.

### What are the steps to reproduce the bug?

Use `./run/GCClassic/createRunDir.sh` to create a 'Trace metals' simulation.

### What GEOS-Chem version were you using?

14.4.3

### What environment were you running GEOS-Chem on?

Local cluster

### What compiler and version were you using?

gcc 14.1.0

### Will you be addressing this bug yourself?

Yes

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

Trace metals

### As what resolution were you running GEOS-Chem?

4x5

### What meterology fields did you use?

MERRA-2

**Comment by yantosca** [comment]
We can now close this issue as PR #2560 has been merged.
