### ISSUE TITLE
[BUG/ISSUE] HEMCO ERROR: Cannot fill buffer for more than one species! when the SHIP and NEI2011_SHIP_HOURLY set as true

### ISSUE THREAD

**Issue by katiegrace-3000** [geoschem/geos-chem#256]
GEOS-Chem V12.7.1, for both global 2x2.5 run and North American nested run with 0.5x0.625. Before I set NEI2011_SHIP_HOURLY    :      false, everything is good and the one month simulation is completed. While after I set  `NEI2011_SHIP_HOURLY    :      true` I,  got the following error,
```
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
HEMCO ERROR: Cannot fill buffer for more than one species!
ERROR LOCATION: HCO_CalcEmis (HCO_CALC_MOD.F90)
ERROR LOCATION: HCOX_ParaNOx_Run (hcox_paranox_mod.F90)
ERROR LOCATION: HCOX_RUN (hcox_driver_mod.F90)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
HEMCO ERROR: Error encountered in "HCOX_ParaNOx_Run"!
ERROR LOCATION:  -> at HCOX_RUN (in module HEMCO/Extensions/hcox_driver_mod.F90
```
Any suggestion would be greatly appreciated.

**Comment by yantosca** [comment]
Can you send us the input and log files from your simulation?  Thanks.

**Comment by yantosca** [comment]
I will close out this issue for now.  Please feel free to reopen or submit a new issue.
