### ISSUE TITLE
SOA No Longer Included in PM10 Calculation?

### ISSUE THREAD

**Issue by AlfredMayhew** [geoschem/geos-chem#2563]
### Your name

Alfred Mayhew

### Your affiliation

University of Utah

### Please provide a clear and concise description of your question or discussion topic.

I have recently been working with the dev branch for 14.5.0 as I want to use the updated chemistry in my work and am making preparations to switch across when 14.5.0 goes live.
When making my changes to `GeosCore
/aerosol_mod.F90`, I noticed that there doesn't seem to be any SOA added to the calculation of PM10. It looks like this is related to [these changes](https://github.com/geoschem/geos-chem/commit/2592c6d285de8f9bbb15f47307b8d1acdfa5aad6) where the aerosol module was rewritten slightly. In the current public version (14.4.3) the PM10 calculation adds `OPOA` for SimpleSOA, and `TSOA`, `ASOA`, and `ISOAAQ` for ComplexSOA, to the PM10 calculation. The new code in 14.5.0 still includes these SOA metrics in the calculation of PM2.5, but not PM10.

Am I missing somewhere that this SOA is accounted for, has the SOA been removed from the PM10 calculation intentionally, or has there been a mistake when re-writing this section of code?

Thanks,
Alfie

**Comment by yantosca** [comment]
Thanks for writing @AlfredMayhew.  I am tagging @yuanjianz, who is the author of that commit.

**Comment by yuanjianz** [comment]
Hi @AlfredMayhew, thanks for writing. From the code it does not seem to be the case?...
```fortran
! Particulate matter < 10um [kg/m3]
       State_Chm%AerMass%PM10(I,J,L) = State_Chm%AerMass%PM25(I,J,L) +                    &   ! PM2.5
                     SOILDUST(I,J,L,5) * 0.7_fp     + &   ! + 70%  of DST2
                     SOILDUST(I,J,L,6)              + &   ! + 100% of DST3
                     SOILDUST(I,J,L,7) * 0.9_fp     + &   ! + 90%  of DST4
                     State_Chm%AerMass%SALC(I,J,L)       * SSA_GROWTH
```
After my re-writing, PM10 is defined as PM25 adding coarse particles. So whatever in PM25 should be in PM10 anyway.

**Comment by AlfredMayhew** [comment]
Oh! Sorry, I missed that the first variable in that sum was the PM2.5 rather than PM10 as in previous versions! Thanks for pointing that out, I'll close the comment!
