### ISSUE TITLE
roundoff_mod.F90 (unit = 5, file = 'stdin') Fortran runtime error: End of file

### ISSUE THREAD

**Issue by samanehashraf** [geoschem/geos-chem#2567]
### Your name

Samaneh

### Your affiliation

Research Associate

### What happened? What did you expect to happen?

Hi,
I am trying to run GC-Classic version 14.4.3 to simulate data for 2023, but I encountered an error related to the Fortran code. Could you help me understand what might be causing this problem?

### What are the steps to reproduce the bug?

-

### Please attach any relevant configuration and log files.

[geoschem_config.yml.txt](https://github.com/user-attachments/files/17719799/geoschem_config.yml.txt)
[Slurm.txt](https://github.com/user-attachments/files/17719802/Slurm.txt)

### What GEOS-Chem version were you using?

14.4.3

### What environment were you running GEOS-Chem on?

Local cluster

### What compiler and version were you using?

-

### Will you be addressing this bug yourself?

Yes

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

Full chemistry

### As what resolution were you running GEOS-Chem?

global 2*2.5

### What meterology fields did you use?

MERRA-2

**Comment by yantosca** [comment]
Thanks for writing @samanehashraf.  This looks like it is chking at line 942 of GeosCore/input_mod.F90, which is:

```F90
  State_Grid%DY = Cast_and_RoundOff( subStrs(1), places=4 )
```
You could try printing out what the `SubStrs(1)` and `SubStrs(2)` values are.  They should be string values, which will be converted to real and rounded off.

**Comment by yantosca** [comment]
Also @samanehashraf: what compiler are you using?  If you are using GCC 13 or 14, there may be some weirdness.  We haven't validated GEOS-Chem with those versions yet.  GCC 10, 11, and 12 all work OK.

**Comment by samanehashraf** [comment]
> Thanks for writing @samanehashraf. This looks like it is chking at line 942 of GeosCore/input_mod.F90, which is:
> 
> ```fortran-modern
>   State_Grid%DY = Cast_and_RoundOff( subStrs(1), places=4 )
> ```
> 
> You could try printing out what the `SubStrs(1)` and `SubStrs(2)` values are. They should be string values, which will be converted to real and rounded off.

Hello,
I tried printing it out but I got the same error again 9below), I would appreciate your help.

At line 210 of file /home/samaneha/projects/rrg-hayesp/samaneha/Topic3_2023/gc_2x25_merra2_fullchem_AMJJASO2023_GFAS/CodeDir/src/GEOS-Chem/Headers/roundoff_mod.F90 (unit = 5, file = 'stdin')
Fortran runtime error: End of file

Error termination. Backtrace:
#0  0x1471b88c66e2 in ???
#1  0x1471b88c71b5 in ???
#2  0x1471b88c7d2b in ???
#3  0x1471b8b1a783 in ???
#4  0x1471b8b141a4 in ???
#5  0x1471b8b14cca in ???
#6  0x8965ba in __roundoff_mod_MOD_cast_and_roundoff_str2flex
	at /home/samaneha/projects/rrg-hayesp/samaneha/Topic3_2023/gc_2x25_merra2_fullchem_AMJJASO2023_GFAS/CodeDir/src/GEOS-Chem/Headers/roundoff_mod.F90:210
#7  0x4b9156 in config_grid
	at /home/samaneha/projects/rrg-hayesp/samaneha/Topic3_2023/gc_2x25_merra2_fullchem_AMJJASO2023_GFAS/CodeDir/src/GEOS-Chem/GeosCore/input_mod.F90:942
#8  0x4d416f in __input_mod_MOD_read_input_file
	at /home/samaneha/projects/rrg-hayesp/samaneha/Topic3_2023/gc_2x25_merra2_fullchem_AMJJASO2023_GFAS/CodeDir/src/GEOS-Chem/GeosCore/input_mod.F90:139
#9  0x405995 in geos_chem
	at /home/samaneha/projects/rrg-hayesp/samaneha/Topic3_2023/gc_2x25_merra2_fullchem_AMJJASO2023_GFAS/CodeDir/src/GEOS-Chem/Interfaces/GCClassic/main.F90:25
#10  0x404b56 in main
	at /home/samaneha/projects/rrg-hayesp/samaneha/Topic3_2023/gc_2x25_merra2_fullchem_AMJJASO2023_GFAS/CodeDir/src/GEOS-Chem/Interfaces/GCClassic/main.F90:32
*************   S T A R T I N G   G E O S - C H E M   *************

===> Mode of operation         : GEOS-Chem "Classic"
===> GEOS-Chem version         : 14.4.3
===> Compiler                  : GNU Fortran compiler (aka gfortran)
===> Flexible precision set to : 8-byte real (aka REAL*8)
===> Parallelization w/ OpenMP : ON
===> netCDF diagnostics        : ON
===> netCDF file compression   : SUPPORTED
===> Luo et al (2019) wetdep?  : OFF

===> SIMULATION START TIME: 2024/11/12 16:16 <===

===============================================================================
G E O S - C H E M   U S E R   I N P U T

READ_INPUT_FILE: Opening ./geoschem_config.yml

SIMULATION SETTINGS
-------------------
Simulation name             : fullchem
CHEM_INPUTS directory       : /home/samaneha/projects/rrg-hayesp/rstevens/GC/ExtData/CHEM_INPUTS/
Species database file       : ./species_database.yml
Turn on verbose output      :     F
Verbose output printed on   : root core only
Start time of run           : 20230401 000000
End time of run             : 20231101 000000
Data Directory              : /home/samaneha/projects/rrg-hayesp/rstevens/GC/ExtData/
Meteorology field           : MERRA2
Turn on GEOS-Chem timers    :     F

**Comment by samanehashraf** [comment]
> Also @samanehashraf: what compiler are you using? If you are using GCC 13 or 14, there may be some weirdness. We haven't validated GEOS-Chem with those versions yet. GCC 10, 11, and 12 all work OK.

I'm using GC-Classic 14.3.3 and the compiler is GNU 12
