### ISSUE TITLE
Which collection to use to generate transport and deposition fluxes between gridded elements ?

### ISSUE THREAD

**Issue by EdgarSergues** [geoschem/geos-chem#2568]
### Your name

Edgar Sergues

### Your affiliation

LIRIDE

### Please provide a clear and concise description of your question or discussion topic.

I am working on life cycle impact assessment. I want to generate simplified source-receptor matrix using GEOS-Chem 14. For that, I need to model transport and deposition exchanges between elements of the grid. I saw that the Budget collection could help me do that but it is unclear what transport variables are about (are they horizontal, vertical, both ?). I am therefore wondering if there is another collection that would give me the data I need or if some more information on the budget collection transport variables could be found somewhere ? Thanks !

**Comment by yantosca** [comment]
Thanks for writing @EdgarSergues.  The Budget collection as implemented in GEOS-Chem is the difference in mass across each GEOS-Chem operation.  Please see our ReadTheDocs page for this description of the Budget collection](https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/history-diag-guide.html#budget).

**Comment by EdgarSergues** [comment]
Thanks for your answer @yantosca , I read this documentation already but it is unclear what budget transport is really about (vertical, horizontal, both ...) and if it could be used to identify exchanges between elements.

At the moment I am trying to explore the fortran code to implement new diagnostics that would give me the transported mass between each grid element for each advected species. If there is any documentation to your knowledge that could help me it would be appreciated.

Thanks !

**Comment by yantosca** [comment]
@EdgarSergues: The budget diagnostic are columns (full column, trop column, PBL column) rather than 3D diagnostics.  

You may want to look into archiving the following diagnostics:
```console
AdvFluxZonal_?ADV?
AdvFluxMerid_?ADV?
AdvFluxVert_?ADV?
```
as these will be the mass fluxes advected in each direction.

The TPCORE code used in GEOS-Chem Classic is 3rd-party code.  It's a bit sloppy and undocumented, so it may be a bit of a slog to go through it.

**Comment by EdgarSergues** [comment]
Yes @yantosca I just found these diagnostics yesterday and I think it will fit my need. Is there a specific way to activate those diagnostics or can I just add a field to any collection in the history.rc file ? Thanks !

**Comment by EdgarSergues** [comment]
@yantosca I would have one more question please : Is there a wet deposition diagnostics collection other than the budget ones ? I can only find the DryDep collection at the moment. Thanks a lot !

**Comment by yantosca** [comment]
Thanks for writing @EdgarSergues.  We have a list of collections on ReadTheDocs:

- [Archive output with the History diagnostics](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/history-diag-guide.html)

The wet scavenging collections are: `WetLossLS`, `WetLossConv`

**Comment by EdgarSergues** [comment]
Thanks a lot !
