### ISSUE TITLE
What does 'CONST_N' and 'HcoState%TS_EMIS' mean?

### ISSUE THREAD

**Issue by ChenBHXMU** [geoschem/geos-chem#2569]
### Your name

baihua chen

### Your affiliation

Xiamen University

### Please provide a clear and concise description of your question or discussion topic.

Dear @christophkeller 

I am currently understanding the code related to sea salt. The code is contained in hcox_seasalt_mod.F90. I am not clear on 'CONST_N' and 'HcoState%TS_EMIS'.  In the Jaegle et al. (2011) article, the content was not found.

Thank you for your assistance.

Best regards
Baihua Chen

![微信截图_20241113174551](https://github.com/user-attachments/assets/efe25672-746d-42ba-854a-df44181cf3a6)
![微信图片_20241113175732](https://github.com/user-attachments/assets/177adc8a-2f91-45fa-af79-885f2ae2c6f9)

**Comment by lizziel** [comment]
Hi @ChenBHXMU - You can do a text search for `CONST_N` in the file to see where it is set. There is a comment there indicating it is a unit conversion factor. Similarly, you can do a global search for TS_EMIS in HEMCO. Try this git command at the top-level of HEMCO. It finds and prints lines containing the string (case-insensitive):

`git grep -in "TS_EMIS"`

One of the lines that shows up is this:

> REAL(sp)                    :: TS_EMIS    ! Emission timestep [s]
