### ISSUE TITLE
History diagnostic allows for mistake in frequency/duration error 

### ISSUE THREAD

**Issue by Mbavhi1** [geoschem/geos-chem#2572]
### Your name

Mbavhi

### Your affiliation

University of York

### What happened? What did you expect to happen?

I made a mistake in the frequency and duration rows in HISTORY.rc, setting a frequency greater than the duration. Rather than the model giving an error it instead output files without any data. I would expect this to return an error and model failure rather than creating files with no actual model output.

### What are the steps to reproduce the bug?

In HISTORY.rc

```
#==============================================================================
# %%%%% THE SpeciesConc COLLECTION %%%%%
#
# GEOS-Chem species concentrations (default = all species)
#
# Available for all simulations
#
# Concentrations may be saved out as SpeciesConcVV  [v/v dry air] or
#                                    SpeciesConcMND [molec/cm3]
#==============================================================================
  SpeciesConc.template:       '%y4%m2%d2_%h2%n2z.nc4',
  SpeciesConc.frequency:      00000001 000000
  SpeciesConc.duration:       00000000 010000
  SpeciesConc.mode:           'time-averaged'
  SpeciesConc.fields:         'SpeciesConcVV_?ALL?           ',
                              ##'SpeciesConcMND_?ALL?          ',
::
#==============================================================================

```

### What GEOS-Chem version were you using?

14.4.3

### What environment were you running GEOS-Chem on?

Local cluster

### What compiler and version were you using?

gcc 12.2 

### Will you be addressing this bug yourself?

No

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

Full chemistry

### As what resolution were you running GEOS-Chem?

4x5

### What meterology fields did you use?

MERRA-2

**Comment by lizziel** [comment]
Thanks for reporting this. We will add a fix in the next version.

**Comment by yantosca** [comment]
Thanks @lizziel and @mbavhi1.  I did a test where:

```console
Run duration in geoschem_config.yml: 1 hour
SpeciesConc.frequency: 00000100 000000
SpeciesConc.duration:  00000000 010000
```
This causes an error:
```console
HISTORY (INIT): Opening ./HISTORY.rc
===============================================================================
GEOS-Chem ERROR: No diagnostic output will be created for collection: 
"SpeciesConc"!  Make sure that the length of the simulation as specified in 
geoschem_config.yml (check the start and end dates) is not shorter than the 
frequency setting in HISTORY.rc! For example, if the frequency is 010000 (1 
hour) but the simulation is set up to run for only 20 minutes, then this error 
will occur.
 -> at History_ReadCollectionData (in module History/history_mod.F90)

 -> ERROR occurred at (or near) line     81 of the HISTORY.rc file
===============================================================================
```
because the duration is less than the length of the run specified in `geoschem_config.yml`.  So far so good.

Then I tried:
```console
  Run length in geoschem_config.yml: 1 hour
  SpeciesConc.frequency:      00000000 010000
  SpeciesConc.duration:       00000000 001000
```
and this does not give any error.  Thus:

1. We have an error check if the duration tag is not less than the length of the run in geoschem_config.yml
2. We DO NOT have an error check if the duration tag is not less than the frequency tag.

This should be a straightforward fix.  Thanks @Mbavhi1 for bringing this to our attention.
