### ISSUE TITLE
Changes in GFED4 Emissions Factors between 14.1 and 14.4

### ISSUE THREAD

**Issue by JFBrewer** [geoschem/geos-chem#2575]
### Your name

Jared Brewer

### Your affiliation

University of Minnesota

### Please provide a clear and concise description of your question or discussion topic.

I am curious about the origin of the changes in the species-specific Emissions Factors between GC 14.1 and 14.5, specifically those in `HEMCO/src/Extensions/hcox_gfed_include_gfed4.H`. The changes for ethane in particular are very significant, and I'd love to read something detailed about them. I figured I'd find it [here](https://geoschem.github.io/new-developments.html), but I'm not seeing what I expected. 

Two separate changes seem to have been made between 14.1 and 14.5: one to the GFED files (transitioning from v2020-02 to v2023-03) and one to the actual species-specific emission factors in `HEMCO/src/Extensions/hcox_gfed_include_gfed4.H`. Of these, I am interested in the latter. The change to the various ethane emissions factors shifts the timing of the peak of biomass burning emissions, as well as decreasing the magnitude of the peak, even when run on the same set of input files. The emissions factors in 14.1 appear (based on my brief perusal) to correspond to Akagi 2011. So where are the new ones coming from?

It looks to me like the main changes in GFED during the relevant versions are the changes to GFED by Makoto and @msulprizio, in which they added GFED4 climatology options and extended the GFED4 data through October 2022. However, the paper cited is just the 2013 GFED paper from Giglio et al. I assume this update pertains to the change from v2020-02 to v2023-03 input files. But does it also account for the changed emission factors?

 @kelvinhb added some additional emissions factors for his alkanes, but I don't think this accounts for the changes I'm seeing (the ethane and many other species as well).

Thanks,
Jared

**Comment by kelvinhb** [comment]
Hey Jared -- if you click the "blame" tab on github when you're on the relevant file, you can see what commit the change was part of, and [in this case](https://github.com/geoschem/HEMCO/commit/6d1df55b4b55edde82ccb6a588a911a03e532e69) it looks like it was from last year when Tess Carter updated some of the emission factors to Meinrat Andreae's [2019 paper](https://acp.copernicus.org/articles/19/8523/2019/).

**Comment by kelvinhb** [comment]
Ha, Bob, you beat me to it :)

**Comment by yantosca** [comment]
@kelvinhb: Great minds think alike. :-)

**Comment by JFBrewer** [comment]
Thank you both! I appreciate both the information and the tutorial!
