### ISSUE TITLE
a new problem

### ISSUE THREAD

**Issue by rongbing0353** [geoschem/geos-chem#2582]
### Your name

runbin

### Your affiliation

lanzhou university

### What happened? What did you expect to happen?

make: *** No rule to make target `install'. Stop.
![problem1](https://github.com/user-attachments/assets/19bc778e-ff75-495d-9424-30300ab9eb0a)

### What are the steps to reproduce the bug?

when i do the make install, it hanppens

### What GEOS-Chem version were you using?

13.0.0

### What environment were you running GEOS-Chem on?

Local cluster

### What compiler and version were you using?

gcc10.2

### Will you be addressing this bug yourself?

Yes, but I will need some help

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

Full chemistry

### As what resolution were you running GEOS-Chem?

0.580.625

### What meterology fields did you use?

MERRA-2

**Comment by rongbing0353** [comment]
the erro is :  make: *** No rule to make target `install'. Stop.

**Comment by yantosca** [comment]
Thanks for writing @rongbing0353.  Could you post the entire output of the build command in a log file attached to this issue?  I'd like to see the entire output from CMake and Make and not just the last few lines.

**Comment by yantosca** [comment]
Also note, 13.0.0 is an unsupported version.

**Comment by yantosca** [comment]
I am closing out this issue as version 13 is no longer supported
