### ISSUE TITLE
Discussion on AFCID output

### ISSUE THREAD

**Issue by CloudyJuan** [geoschem/geos-chem#2587]
### Your name

lv juan

### Your affiliation

Nanjing University of Information Science and Technology

### Please provide a clear and concise description of your question or discussion topic.

I found the AFCID emissions inventory, and in different months, although the emissions in a particular month were low, the concentration of DST1 generated in that month was high in china.  I ran two simulations , one with AFCID and the other without AFCID.  The mean monthly concentration of DST1 in a same large area of China was calculated separately as the table. For example, December does not have high emissions, but his DST1 concentration is the highest, while June has the highest emissions, but does not generate high DST1 concentrations. The only variables simulated are whether AFICD is enabled or not, and offline_dust is not enabled. 
I would like to ask if the DST1 concentration generated by AFCID emission is affected by different time periods and how AFCID translates into DST1 concentration, sorry to bother you as I didn't find this part in the code.
![compare](https://github.com/user-attachments/assets/8485d778-f5c1-41d7-9892-fc0acd0f76aa)

**Comment by CloudyJuan** [comment]
I am using GCClassic v12.8.2 to run my simulations. Nested East Asia region, horizontal resolution not 0.5°×0.625°.  Runs for the whole year in 2015. 
[HISTORY.rc.txt](https://github.com/user-attachments/files/17871899/HISTORY.rc.txt)


[HEMCO_Config_withoutAFCID.rc.txt](https://github.com/user-attachments/files/17871900/HEMCO_Config_withoutAFCID.rc.txt)
[HEMCO_Config_withAFCID.rc.txt](https://github.com/user-attachments/files/17871901/HEMCO_Config_withAFCID.rc.txt)

**Comment by yantosca** [comment]
I am closing out this issue as version 12.8.2 is no longer supported.
