### ISSUE TITLE
About HcoState%TS_EMIS

### ISSUE THREAD

**Issue by ChenBHXMU** [geoschem/geos-chem#2589]
### Your name

baihua chen

### Your affiliation

Xiamen University

### Please provide a clear and concise description of your question or discussion topic.

Dear @christophkeller  @yantosca 

I hope this email finds you well.

Recently, I have been studying the calculation of sea salt, but I find that the value of HcoState%TS_EMIS is 1200, and I don't understand why. Why isn't this parameter set to 1 second?

Best regards，
Baihua Chen

![微信截图_20241125100034](https://github.com/user-attachments/assets/601fa169-ac3f-444b-a56a-5a8019a797ed)

**Comment by yantosca** [comment]
Thanks for writing @ChenBHXMU.  The `HcoState%TS_EMIS` is copied from the `Input_Opt%TS_EMIS` value (which is read from `geoschem_config.yml`).  This is the interval that determines when HEMCO will run.  Currently we use 600s (transport/convection/mixing) and 1200s (chemistry/emissions) seconds.

**Comment by ChenBHXMU** [comment]
Thank you!
