### ISSUE TITLE
Error: so4.data File not found

### ISSUE THREAD

**Issue by ChenBHXMU** [geoschem/geos-chem#2594]
### Your name

baihua chen

### Your affiliation

Xiamen University

### Please provide a clear and concise description of your question or discussion topic.

Dear @yantosca 

Hope this message finds you well.

I am running GEOS-Chem (version: 15.0.0), and it shows a missing file, as shown in the figure below.

Best regards
Baihua Chen

[Other Files.zip](https://github.com/user-attachments/files/17916538/Other.Files.zip)

![6eb9f045772ff7f379a1b72d8651d96](https://github.com/user-attachments/assets/d7d8c5ba-c4cc-4fd5-972e-33f8e685447c)

**Comment by yantosca** [comment]
Thanks for writing @ChenBHXMU.  I've seen this error as well when trying to download data with a dry-run simulation.  I think it has to do with permissions at the server.

You can try downloading the files manually in the meantime and put them into your local `CHEM_INPUTS/Aerosol_Optics/v2024-08` folder

- https://geos-chem.s3-us-west-2.amazonaws.com/CHEM_INPUTS/Aerosol_Optics/v2024-08/brc.dat
- https://geos-chem.s3-us-west-2.amazonaws.com/CHEM_INPUTS/Aerosol_Optics/v2024-08/dust.dat
- https://geos-chem.s3-us-west-2.amazonaws.com/CHEM_INPUTS/Aerosol_Optics/v2024-08/h2so4.dat
- https://geos-chem.s3-us-west-2.amazonaws.com/CHEM_INPUTS/Aerosol_Optics/v2024-08/org.dat
- https://geos-chem.s3-us-west-2.amazonaws.com/CHEM_INPUTS/Aerosol_Optics/v2024-08/README
- https://geos-chem.s3-us-west-2.amazonaws.com/CHEM_INPUTS/Aerosol_Optics/v2024-08/so4.dat
- https://geos-chem.s3-us-west-2.amazonaws.com/CHEM_INPUTS/Aerosol_Optics/v2024-08/soot.dat
- https://geos-chem.s3-us-west-2.amazonaws.com/CHEM_INPUTS/Aerosol_Optics/v2024-08/ssa.dat
- https://geos-chem.s3-us-west-2.amazonaws.com/CHEM_INPUTS/Aerosol_Optics/v2024-08/ssc.dat

Feel free to close out this issue if the manual download works.  We will try to fix on the WashU server but it may take some time.

**Comment by ChenBHXMU** [comment]
> Thanks for writing @ChenBHXMU. I've seen this error as well when trying to download data with a dry-run simulation. I think it has to do with permissions at the server.
> 
> You can try downloading the files manually in the meantime and put them into your local `CHEM_INPUTS/Aerosol_Optics/v2024-08` folder
> 
> * https://geos-chem.s3-us-west-2.amazonaws.com/CHEM_INPUTS/Aerosol_Optics/v2024-08/brc.dat
> * https://geos-chem.s3-us-west-2.amazonaws.com/CHEM_INPUTS/Aerosol_Optics/v2024-08/dust.dat
> * https://geos-chem.s3-us-west-2.amazonaws.com/CHEM_INPUTS/Aerosol_Optics/v2024-08/h2so4.dat
> * https://geos-chem.s3-us-west-2.amazonaws.com/CHEM_INPUTS/Aerosol_Optics/v2024-08/org.dat
> * https://geos-chem.s3-us-west-2.amazonaws.com/CHEM_INPUTS/Aerosol_Optics/v2024-08/README
> * https://geos-chem.s3-us-west-2.amazonaws.com/CHEM_INPUTS/Aerosol_Optics/v2024-08/so4.dat
> * https://geos-chem.s3-us-west-2.amazonaws.com/CHEM_INPUTS/Aerosol_Optics/v2024-08/soot.dat
> * https://geos-chem.s3-us-west-2.amazonaws.com/CHEM_INPUTS/Aerosol_Optics/v2024-08/ssa.dat
> * https://geos-chem.s3-us-west-2.amazonaws.com/CHEM_INPUTS/Aerosol_Optics/v2024-08/ssc.dat
> 
> Feel free to close out this issue if the manual download works. We will try to fix on the WashU server but it may take some time.

Thank you!
