### ISSUE TITLE
Dictionary_m allocatable problems with compiling, GC 12.7.1

### ISSUE THREAD

**Issue by JFBrewer** [geoschem/geos-chem#261]
I'm having some trouble compiling GC 12.7.1. I've been following the instructions [here](http://wiki.seas.harvard.edu/geos-chem/index.php/Compiling_with_CMake) and have successfully used cmake to correctly generate the build, at least as far as I can tell. When I try to use `make -j4 install`, however, the compilation fails at 1%. I get a series of 4 errors with the same form:

```
GC_12.7.1/rundirs/geosfp_4x5_standard/CodeDir/Headers/dictionary_m.F90:26.41:
     character(len=:), allocatable :: key
                                         1
Error: Deferred-length character component 'key' at (1) is not yet supported
```

These errors all occur in compiling dictionary_m.F90 at lines 26.41 and 137.16. The code then quickly flashes Error 1 and Error 2 and stops.

The only examples of this error I've been able to find on the internet suggest that it's the result of not using an up-to-date fortran compiler, but I get the same response whether I use gfotran82, gfortran71, or any of the ifort 15-19 compilers. I'm sure I'm missing something obvious but I don't know what it is.

Thanks,
Jared
![Screen Shot 2020-03-30 at 5 22 05 PM](https://user-images.githubusercontent.com/13008012/77971075-0c539600-72ab-11ea-882d-9fcfb10ca85b.png)

**Comment by yantosca** [comment]
Thanks for writing.  I think the statement
```
character(len=:)
```
may be a Fortran 2008 feature.  I've been able to compile it with gfortran 9.2.0 but maybe it chokes on the older compilers.

You could try replacing that with:
```
character(len=*)
```
which is standard Fortran 90.  We can try to make this fix in a future version (maybe 12.8.1).

**Comment by lizziel** [comment]
This should be fine for recent gfortran versions since we test various versions of GCC in our CI pipeline. Those tests failed for gfortran 4 and 5, but passed for later versions. Jared, could you provide your environment file? If you could also load it and then do 'module list', copy that info here as well.

**Comment by lizziel** [comment]
Also drag and drop CMakeCache.txt from your build directory here. This contains information about libraries used.

**Comment by yantosca** [comment]
As @lizziel has been pointing out, our Continuous Integration tests use gfortran 5 through gfortran 9.  So that should work as written.

**Comment by JFBrewer** [comment]
This is coming from an environment built with gfortran82. Modules used are:

  1) git/2.17.0-fasrc01
  2) perl/5.26.1-fasrc01 
  3) IDL/8.4.1-fasrc01 
  4) flex/2.6.4-fasrc01
  5) gmp/6.1.2-fasrc01
  6) mpfr/3.1.5-fasrc01
  7) mpc/1.0.3-fasrc06
  8) gcc/8.2.0-fasrc01
  9) openmpi/3.1.1-fasrc01
 10) zlib/1.2.8-fasrc07
 11) szip/2.1-fasrc02
 12) hdf5/1.8.12-fasrc12
 13) netcdf/4.1.3-fasrc02
 14) libtiff/4.0.9-fasrc01
 15) emacs/26.1-fasrc01
 16) cmake/3.12.1-fasrc01
 17) jdk/1.8.0_172-fasrc01
 18) tau-2.28.2-gcc-9.2.0-dwyutal

My CMakeCache is also attached
[CMakeCache.txt](https://github.com/geoschem/geos-chem/files/4409738/CMakeCache.txt)

Thanks,
Jared

**Comment by yantosca** [comment]
The default CMake is older (3.12).  Try doing
```
cd gcbuild   # or whatever the build folder is called
make -j8      # The number can be set equal to $OMP_NUM_THREADS
make install
```
as separate steps.

**Comment by JFBrewer** [comment]
make -j8 throws the same errors as before. Should I update to a newer CMake?

**Comment by yantosca** [comment]
Also -- type
```
gfortran --version
```
I wonder if somehow you are pointing to the gfortran that ships with Centos7 rather than the one that comes from the module.  If you don't have your $FC, $CC, $CXX variables set properly, this might be happening.

**Comment by lizziel** [comment]
Your CMakeCache.txt has this for fortran compiler:
```
//Fortran compiler
CMAKE_Fortran_COMPILER:FILEPATH=/usr/bin/f95
```

I checked my own build directory for a gfortran8.2 build and I have this:
```
//Fortran compiler
CMAKE_Fortran_COMPILER:FILEPATH=/n/helmod/apps/centos7/Core/gcc/8.2.0-fasrc01/bin/gfortran 
```

So it does seem something isn't being set.

**Comment by JFBrewer** [comment]
The version is GNU Fortran (GCC) 8.2.0

How would I know whether this is the gfortran from Centos7? This is based on the `init.gc-classic.gfortran82.centos7 ` script I stole from you.

**Comment by yantosca** [comment]
The Centos7 version is in/usr/bin/gfortran and is a gfortran4 version
```
[holyjacob01 ~]$ /usr/bin/gfortran --version
GNU Fortran (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
Copyright (C) 2015 Free Software Foundation, Inc.
```

**Comment by JFBrewer** [comment]
So what I'm taking from this is that I am referencing the correct version of gfortran in my init script but somehow it's not actually getting referenced when I use cmake? Is there something more specific I need to do to cmake beyond loading the correct module?

What confuses me doubly is that when I actually run `cmake ../CodeDir`, I get output that certainly looks like it's referencing n/helmod/..../gcc/8.2.0-fasrc01 for something.
![Screen Shot 2020-03-31 at 9 03 56 AM](https://user-images.githubusercontent.com/13008012/78042277-0606fd80-732f-11ea-9721-e1e8fb2beae9.png)

**Comment by JFBrewer** [comment]
Uhh also in unrelated news I have only just now noticed that when I tried to pull 12.7.1 I appear to have actually gotten 12.7.2

**Comment by lizziel** [comment]
What command are you using to get 12.7.1? Also, can you post your CMakeError.log and CMakeOutput.log located in your build directory's subdirectory CMakeFiles?

**Comment by JFBrewer** [comment]
I have worked with Lizzie on this for a while. The issue was that I had not wiped clean the gcbuild directory. Using `rm -rf *` in `gcbuild`, reloading my gfortran compiler, and then starting over with cmake ../CodeDir solved the problem. Thank you.
