### ISSUE TITLE
How to add two sea salt modes?

### ISSUE THREAD

**Issue by ChenBHXMU** [geoschem/geos-chem#2618]
### Your name

Baihua Chen

### Your affiliation

Xiamen University

### Please provide a clear and concise description of your question or discussion topic.

Dear @yantosca 

I hope this message finds you well. I am working on optimizing the calculation of sea salt, which currently includes SALC and SALA. I am trying to add two additional modes and, in the future, aim to compute sea salt more precisely.  In the figures below, SALA2 and SALC2 are the two modes I am trying to add. However, I have encountered some challenges. Despite my best efforts, I have been unable to resolve them.

Attached are the files I have modified. I would appreciate it if you could take a look. Thank you very much for your help.

Best regards,
Baihua Chen

make -j:
![微信截图_20241202105639](https://github.com/user-attachments/assets/6aacf22d-88a6-4fac-8df0-d05aad7255a7)
HEMCO_Config.rc:
![微信图片_20241208144339](https://github.com/user-attachments/assets/7e3d08df-dfc7-47a8-b8f5-878db91672ee)

[Other files.zip](https://github.com/user-attachments/files/18050992/Other.files.zip)

**Comment by ChenBHXMU** [comment]
Dear @yantosca ,

Could you please help me?

Best regards,
Baihua Chen

**Comment by ChenBHXMU** [comment]
Dear @yantosca ,

In GEOS-Chem, sea salt includes two modes, SALA and SALC. I am trying to update it to four modes. Following your advice, I have updated the HEMCO_Diagn.rc file, but I still cannot resolve the issue. This issue is quite challenging for me; how should I handle it?

Thank you for your help.

Best regards,
Baihua Chen

![微信截图_20241211100851](https://github.com/user-attachments/assets/43b1134e-be1a-408d-96d7-19068e6eeaca)
![微信截图_20241211100933](https://github.com/user-attachments/assets/e87dbf4f-f846-4c4c-bc2d-f0864680584d)

**Comment by yantosca** [comment]
@ChenBHXMU: I see the issue.  You would need to add SALA2 and SALC2 to the code in https://github.com/geoschem/geos-chem/blob/main/Headers/aermass_container_mod.F90.  Wherever you see SALA and SALC in the module, you can add the similar modifications for SALA2 and SALC2.

As a rule, we expect GEOS-Chem users to be resourceful and to be somewhat familiar with programming concepts.  We can provide guidance and advice but cannot write code for users.

**Comment by ChenBHXMU** [comment]
Dear @yantosca Thanks a million for your time. I will delve deeper into these codes.

**Comment by yantosca** [comment]
Thanks @ChenBHXMU.  I will close out this issue.
