### ISSUE TITLE
Inquiry about HISTORY.rc

### ISSUE THREAD

**Issue by ChenBHXMU** [geoschem/geos-chem#2622]
### Your name

Baihua Chen

### Your affiliation

Xiamen University

### Please provide a clear and concise description of your question or discussion topic.

Dear @yantosca 

I hope you have a nice day.

In HISTORY.rc, there is the following content. However, I cannot find the corresponding variables, such as AerMassSAL, in the GEOSChem.SpeciesConc.xxxx and HEMCO_diagnostics.xxxx files in the OutputDir folder. Additionally, when I select Full chemistry and Marine POA mode, the data for the variables EmisSALA_Natural and EmisSALC_Natural in the HEMCO_diagnostics.xxxx file is 0. I am curious why it is 0.

Thanks a million for your time, and I look forward to hearing from you.

![微信截图_20241209142712](https://github.com/user-attachments/assets/40d67cd7-7a31-4f30-839b-e2d2e5280b0b)

**Comment by yantosca** [comment]
Thanks for writing @ChenBHXMU.  The `AerMass*` diagnostics will not be sent to the `GEOSChem.SpeciesConc*.nc4` files, but to the `GEOSChem.AerosolMass` files.  Make sure that the `AerosolMass` collection does not have a comment character in front of it in the `COLLECTIONS:` list in `HISTORY.rc`.

We have substantial documentation about the History diagnostics on ReadTheDocs:

- [Archive output with the History diagnostics](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/history-diag-guide.html)

**Comment by ChenBHXMU** [comment]
Dear @yantosca 

Thank you for your help, but I couldn't find the GEOSChem.AerosolMass files in the OutputDir folder.

![微信截图_20241210101749](https://github.com/user-attachments/assets/75ad813a-be4c-4490-a678-b678714fdf84)
![微信截图_20241210102126](https://github.com/user-attachments/assets/95c0879b-e2fd-4524-a5ff-d740f4953f64)

**Comment by yantosca** [comment]
Thanks @ChenBHXMU.  If you are adding a seasalt emissions to HEMCO then the diagnostics would show up in the `HEMCO_Diagnostics*.rc` files.  You would need to update the `HEMCO_Diagn.rc` file like this:
```console
###############################################################################
#####  Sea salt emissions                                                 #####
###############################################################################
EmisSALA_Natural     SALA  0      3   -1   2   kg/m2/s  SALA_emission_flux_from_natural_sources
EmisSALA2_Natural     SALA  0      3   -1   2   kg/m2/s  SALA2_emission_flux_from_natural_sources    # <== add this
EmisBrSALA_Natural BrSALA  0      3   -1   2   kg/m2/s  BrSALA_emission_flux_from_natural_sources
EmisSALAAL_Natural SALAAL  0      3   -1   2   kg/m2/s  SALAAL_emission_flux_from_natural_sources
EmisSALACL_Natural SALACL  0      3   -1   2   kg/m2/s  SALACL_emission_flux_from_natural_sources
EmisSALC_Natural     SALC  0      3   -1   2   kg/m2/s  SALC_emission_flux_from_natural_sources
EmisSALC2_Natural     SALC  0      3   -1   2   kg/m2/s  SALC_emission_flux_from_natural_sources   # <=== add this
EmisBrSALC_Natural BrSALC  0      3   -1   2   kg/m2/s  BrSALC_emission_flux_from_natural_sources
EmisSALCAL_Natural SALCAL  0      3   -1   2   kg/m2/s  SALCAL_emission_flux_from_natural_sources
EmisSALCCL_Natural SALCCL  0      3   -1   2   kg/m2/s  SALCCL_emission_flux_from_natural_sources
```

**Comment by yantosca** [comment]
@ChenBHXMU: also to get the AerosolMass diagnostics you would need to "uncomment" the `AerosolMass` collection name near the top of the `HISTORY.rc` file:
```console
COLLECTIONS: 'Restart',
             'Metrics',
             'SpeciesConc',
             #'AdvFluxVert',
             'AerosolMass',   # <= Remove the leading `#`
             # Aerosols',
             ,,, etc ,,,
```

**Comment by yantosca** [comment]
As a reminder, we have good documentation on the History diagnostics on ReadTheDocs:

- [Archive output with the History diagnostics](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/history-diag-guide.html#)

**Comment by ChenBHXMU** [comment]
Dear @yantosca  Thank you for your help!

**Comment by yantosca** [comment]
Thank you @ChenBHXMU.  I'll close this issue now.
