### ISSUE TITLE
Could not locate the ExtData folder in local disk space

### ISSUE THREAD

**Issue by ChenBHXMU** [geoschem/geos-chem#2624]
### Your name

Baihua Chen

### Your affiliation

Xiamen University

### Please provide a clear and concise description of your question or discussion topic.

Dear @yantosca 

When I run GEOS-Chem on a new computer and then download data, I am prompted with "Could not locate the ExtData folder in local disk space." This time, I manually created the ExtData folder first and then ran ./createRunDir.sh, a process that did not ask me to input the path to the ExtData folder. This should be the reason why the data download could not find the ExtData folder. However, I do not know how to resolve this bug. The vesion of GEOS-Chem is 14.4.3.
 
Thank you for your patience and help, I really appreciate it.

Best regard
Baihua Chen

![微信截图_20241209163324](https://github.com/user-attachments/assets/ff908bab-e6a6-4d16-bf81-16e30bb2295f)
[Files.zip](https://github.com/user-attachments/files/18058654/Files.zip)

**Comment by ChenBHXMU** [comment]
> Thanks for writing @ChenBHXMU. Make sure that the path to your `ExtData` folder matches the path specified by the variable `GC_DATA_ROOT` in your `$HOME/.geoschem/config` file.
> 
> The first time you create a GEOS-Chem run directory, you will be asked for registration information. That is stored in your `$HOME/.geoschem/config` file. The `createRunDir.sh` script uses this information to remember where your ExtData folder is. If you have changed the path to ExtData since registering, you'll need to also change the path in your `$HOME/geoschem/.config` file to match.

Thank you very much!

**Comment by yantosca** [comment]
Thanks!  I'll close out this iseue.
