### ISSUE TITLE
Calculation of PM2.5 Concentration and its Components in full chemistry simulations under GEOSChem V13.2.0

### ISSUE THREAD

**Issue by jiemeiliu** [geoschem/geos-chem#2629]
### Your name

Mer

### Your affiliation

HIT

### Please provide a clear and concise description of your question or discussion topic.

I converted the units of species (NH4, NIT, SO4, BC , OCPO, OCPI, SOAS, DST1, DST2, SALA) concentrations in the GEOSChem.SpeciesConc* file to micrograms per cubic meter using the unit conversion methodology mentioned in the question. and PM2.5 was calculated using pm25_cal = 1.33 * (NH4 + NIT + SO4) + BC + (OCPO + 1.16 * OCPI + 1.16 * SOAS+ DST1+ 0.38 * DST2 + 1.86 * SALA). however, the calculated PM2.5 concentration was not the same as that in the GEOSChem.AerosolMass* file for 'PM25' is different. This is confusing me. I would appreciate if you could tell me where the problem lies.

**Comment by yantosca** [comment]
Thanks for writing @jiemeiliu.  GEOS-Chem 13 is no longer supported.

**Comment by jiemeiliu** [comment]
> Thanks for writing @jiemeiliu. GEOS-Chem 13 is no longer supported.
Thank you @yantosca very much for your reply. I need to get the concentration of each component of PM2.5, including secondary inorganic aerosol, secondary organic aerosol, dust and primary PM2.5 concentration. However it seems that the above components cannot be exported in the GEOSChem.AerosolMass file. So I tried to extract them from the GEOSChem.SpeciesConc file. So I ran into the problem that the sum of the GEOSChem.SpeciesConc component concentrations is not equal to the concentration of the 'PM2.5' variable in GEOSChem.AerosolMass. Can you tell me how to output them individually or how to get the concentrations of the above components? You mentioned that v13 is no longer supported, so can I change to a higher version to perform the PM2.5 concentration mode to achieve the extraction of the above components? Thank you again!

**Comment by yantosca** [comment]
@jiemeiliu: Yes, please update to the latest version of GEOS-Chem, which currently is 14.5.0.

**Comment by jiemeiliu** [comment]
> @jiemeiliu: Yes, please update to the latest version of GEOS-Chem, which currently is 14.5.0.

Thank you very much for your help, I will try to extract the components with the latest version. Have a good day.
