### ISSUE TITLE
The question can't be solved?

### ISSUE THREAD

**Issue by rongbing0353** [geoschem/geos-chem#2631]
### Your name

runbin zhang

### Your affiliation

lanzhou univetsity

### Please provide a clear and concise description of your question or discussion topic.

1.We can't find the  file "InitCFC " in "CHEM_INPUTS/UCX_201403/NoonTime/Grid2x25/InitCFC",it did't exist at all in the AWS S3
2.We use the geoschem-classic 13.0.0 version, not the 14.5.0. We found the FAST_JX files ,and we mannully added them to the folder,but, when the dryrun is done, they were not found at all. what's more, even if these files downloaded from the AWS S3,not mannully, the dryrun still can't find them ?what's the problem? thank you 
```console
 FAST-JX (RD_XXX): REQUIRED FILE NOT FOUND /public/home/zhangrb/ExtData/CHEM_INPUTS/FAST_JX/v2019-10/FJX_spec.dat
FAST-JX (RD_MIE): REQUIRED FILE NOT FOUND /public/home/zhangrb/ExtData/CHEM_INPUTS/FAST_JX/v2019-10/jv_spec_mie.dat
FAST-JX (RD_AOD): REQUIRED FILE NOT FOUND /public/home/zhangrb/ExtData/CHEM_INPUTS/FAST

FAST-JX (RD_AOD): REQUIRED FILE NOT FOUND /public/home/zhangrb/ExtData/CHEM_INPUTS/FAST_JX/v2019-10/soot.dat
FAST-JX (RD_AOD): REQUIRED FILE NOT FOUND /public/home/zhangrb/ExtData/CHEM_INPUTS/FAST_JX/v2019-10/org.dat
FAST-JX (RD_AOD): REQUIRED FILE NOT FOUND /public/home/zhangrb/ExtData/CHEM_INPUTS/FAST_JX/v2019-10/ssa.dat
FAST-JX (RD_AOD): REQUIRED FILE NOT FOUND /public/home/zhangrb/ExtData/CHEM_INPUTS/FAST_JX/v2019-10/ssc.dat
FAST-JX (RD_AOD): REQUIRED FILE NOT FOUND /public/home/zhangrb/ExtData/CHEM_INPUTS/FAST_JX/v2019-10/h2so4.dat
FAST-JX (RD_AOD): REQUIRED FILE NOT FOUND /public/home/zhangrb/ExtData/CHEM_INPUTS/FAST_JX/v2019-10/h2so4.dat
FAST-JX (RD_AOD): REQUIRED FILE NOT FOUND /public/home/zhangrb/ExtData/CHEM_INPUTS/FAST_JX/v2019-10/dust.dat
FAST-JX (RD_PROF_NC): Opening /public/home/lzu_chsy/zhangrb/ExtData/CHEM_INPUTS/FastJ_201204/fastj.jv_atms_dat.nc
FAST-JX (RD_JS_JX): REQUIRED FILE NOT FOUND /public/home/zhangrb/ExtData/CHEM_INPUTS/FAST_JX/v2019-10/FJX_j2j.dat
===============================================================================
```
<img width="645" alt="11" src="https://github.com/user-attachments/assets/6e00e2a2-8a82-4928-b1a4-d3117dc65bf3" />
![22](https://github.com/user-attachments/assets/6e678691-570c-4fc1-90dd-306d482f8d88)
![33](https://github.com/user-attachments/assets/5a24ecb9-6e69-41d9-9c63-e202a31d7591)
![44](https://github.com/user-attachments/assets/c96ebf89-18f7-4007-a665-346595764012)

**Comment by rongbing0353** [comment]
![33](https://github.com/user-attachments/assets/c7534587-001a-4626-afd7-ed3fd1b64c0f)
![44](https://github.com/user-attachments/assets/122ee049-7245-4ded-8d47-6c3394f24708)

**Comment by yantosca** [comment]
I am closing out this issue as version 13 is no longer supported.
