### ISSUE TITLE
When I use the offline emission,how to set the following things

### ISSUE THREAD

**Issue by rongbing0353** [geoschem/geos-chem#2646]
### Your name

runbin

### Your affiliation

lanzhou university

### Please provide a clear and concise description of your question or discussion topic.

When I use fullchem mode to run the the offline emission inventory, how to set the Aerosal Menu, and the deposition munu, and the chemistry menu? for example ,should I colse the online sulfate aerosals in the aerosal menu? or these online aerosal menus must be set true ,no matter if I calculate with offline mode? thanks a lot
![5555](https://github.com/user-attachments/assets/3baaac76-957a-437d-9ff7-38d91986ddeb)

**Comment by yantosca** [comment]
Thanks for writing @rongbing0353.  These settings are more or less the same in the latest version.  You can look at the documentation here: 

- https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/doc/geoschem-config.html#aerosols-settings

If you disable any of the aerosol types (e.g. if you set `ONLINE SULFATE AEROSOLS: F`), you must remove all sulfate aerosols from the list of advected species.

If all you care about is dust, you could just set the list of advected species to DST`, DST2, DST3, DST4, and then set `ONLINE_SULFATE_AEROSOLS: F`, `ONLINE CARBON AEROSOLS: F`, `ONLINE SEASALT AEROSOLS: F`.  That would give you an aerosol-only simulation with just dust.

**Comment by yantosca** [comment]
I am closing this version as we cannot support version 13.
