### ISSUE TITLE
should I use fullchem or aerosal only mode?

### ISSUE THREAD

**Issue by rongbing0353** [geoschem/geos-chem#2647]
### Your name

runbin 

### Your affiliation

lanzhou university

### Please provide a clear and concise description of your question or discussion topic.

Hello, I have a question, I made a new dust pm2.5 inventory and want to use geoschem to verify if it is right, should I  use the full-chem mode or the aerosal mode? when I use full-chem,I found that the process is too slow ,which I can't accept, I calculate the  dust pm2.5,which is one of the total pm2.5 in the emisssion inventory.what should i do? thank you very much

**Comment by yantosca** [comment]
Thanks for writing @rongbing0353.  If all you care about is dust, you can use the aerosol-only simulation.

**Comment by yantosca** [comment]
I am closing out this issue as version 13 is no longer supported.
