### ISSUE TITLE
bug in reading restart file when running GC_12.3.2

### ISSUE THREAD

**Issue by plutologic** [geoschem/geos-chem#265]
# Report a GEOS-Chem bug or technical issue
I use the GCv12.3.2, run the 0.25x0.3125 resolution over China with geosfp met, but it goes wrong when read the 2011/01/GEOSFP.20110101.CN.025x03125.CH.nc, it choose to read a file GEOSFP.20110101.CN.2x25.unknown_nest.nc, ie seems that I made a mistake when generate a geos.mp. I have already run a 2x2.5 for BC, before I run 0.25x0.3125, I compled in the run directory, 
make realclean
make -j4 mpbuild MET=geosfp GRID=025x03125 NEST=CH CHEM=Tropchem BPCH_DIAG=y
is there anything wrong?

Then I tried to run global simulation with 2x25 merra2，use the same code, compile in the run directory like this:
make realclean
make -j4 mpbuild MET=merra2 GRID=2x25 CHEM=Tropchem BPCH_DIAG=y

it also chooses to read the GEOSFP.20110101.CN,2x25.nc file!

**Comment by plutologic** [comment]
solved

**Comment by yantosca** [comment]
Thanks for letting us know that you solved the problem!
