### ISSUE TITLE
./gcclassic: error while loading shared libraries: libnetcdff.so.7: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by dyblove** [geoschem/geos-chem#2651]
### Your name

Yibo Dou

### Your affiliation

PKU

### What happened? What did you expect to happen?

Dear @yantosca, @ltmurray, When I executed the command "./gcclassic --dryrun | tee log.dryrun", I came across the following issue: "./gcclassic: error while loading shared libraries: libnetcdff.so.7: cannot open shared object file: No such file or directory". I am certain that I have successfully and accurately downloaded all the requisite packages as per the requirements on the website (https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/spack-guide.html#spackguide). I am perplexed as to how to solve this. Moreover, I suspect that this might be the cause of the problem I previously encountered (Program received signal SIGSEGV: Segmentation fault - invalid memory reference #2639). I have approximately 60G of memory, yet I am unable to complete even a one-day simulation. I think perhaps this is not attributed to insufficient memory. 
![image](https://github.com/user-attachments/assets/c7b85557-408c-45b3-a566-f2a658cc6725)
![image](https://github.com/user-attachments/assets/1a3ad5bc-abf7-4837-812d-7c0c27f3e649)

### What are the steps to reproduce the bug?

When I executed the command "./gcclassic --dryrun | tee log.dryrun", I came across the following issue: "./gcclassic: error while loading shared libraries: libnetcdff.so.7: cannot open shared object file: No such file or directory". 

### What GEOS-Chem version were you using?

14.5.0

### What environment were you running GEOS-Chem on?

Other (please explain below)

### What compiler and version were you using?

GCC 12.3.0

### Will you be addressing this bug yourself?

Yes, but I will need some help

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

Full chemistry

### As what resolution were you running GEOS-Chem?

2×2.5

### What meterology fields did you use?

MERRA-2

**Comment by yantosca** [comment]
@dyblove: This error `libnetcdff.so.7: cannot open shared object file: No such file or directory" usually means that you are compiling GEOS-Chem with a different compiler than what the netCDF libraries have been compiled with.  Either that or it cannot find the netCDF library itself.

**Comment by dyblove** [comment]
> @dyblove: This error `libnetcdff.so.7: cannot open shared object file: No such file or directory" usually means that you are compiling GEOS-Chem with a different compiler than what the netCDF libraries have been compiled with. Either that or it cannot find the netCDF library itself.

Thank you very much, the package was not found automatically, adding the path to the environment file solved the problem.

**Comment by yantosca** [comment]
Great!  I'll close this issue now @dyblove.  Glad it's working.
