### ISSUE TITLE
[QUESTION] Dry run not picking up missing GEOS-FP files

### ISSUE THREAD

**Issue by dpfinch** [geoschem/geos-chem#267]
I'm not sure if this is a bug or a question (since I might have just set something up wrong). 
I'm running a dry run of GEOS-Chem to find the missing files. The simulation I'm running is:
2013/06/01 - 2015/01/01 tropchem using GEOS-FP 0.25x0.3125 but using flexgrid to run at 2x2.5 (and then will use it to run at 1x1)

I know I don't have GEOS-FP files for any of 2013 (but I do for 2012 and 2014). However when I run the dry run, its not trying to use any 2013 files, its just looping over December 2012 six times then moving onto 2014. Is there a reason why it is doing this? The only changes I've made in HEMCO_Config are to force it to use the chosen resolution. So each line looks something like this:

`* ALBEDO    $METDIR/$YYYY/$MM/$MET.$YYYY$MM$DD.A1.025x03125.$NC     ALBEDO   1980-2019/1-12/1-31/*/+30minute RFY xy  1  *$`

Do I need go change the `RFY` bit? Although I understood it as the `F` would force an error?

Thanks in advance!

**Comment by yantosca** [comment]
Thanks for writing.  Can you attach the log files from the dryrun output (i.e. the log.dryrun and also the log.dryrun.unique)?   I'll take a look.

**Comment by dpfinch** [comment]
Hi, I've attached the log.dryrun and log.dryrun.unique files
(I've had to add .txt to the end of the filenames otherwise GitHub wouldn't let me upload them)
 - thanks! 
[log.dryrun.txt](https://github.com/geoschem/geos-chem/files/4427753/log.dryrun.txt)


[log.dryrun.unique.txt](https://github.com/geoschem/geos-chem/files/4427749/log.dryrun.unique.txt)

**Comment by yantosca** [comment]
Hmm, the log.dryrun.unique file looks like it is only including the missing files.  It should include both missing & found.  I can take a look.
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!! LIST OF (UNIQUE) FILES REQUIRED FOR THE SIMULATION
!!! Start Date       : 20130601 000000
!!! End Date         : 20150101 000000
!!! Simulation       : tropchem
!!! Meteorology      : GEOSFP
!!! Grid Resolution  : 2.0x2.5
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
./GEOSChem.Restart.20130601_0000z.nc4 --> ./HEMCO_CoGEOSCHEM_RESTARTS/v2018-11/initial_GEOSChem_rst.2x25_tropchem.nc
./HEMCO_restart.201306010000.nc
/geos/d21/GC_DATA/HEMCO/GFAS/v2018-09/2013/GFAS_201306.nc
/geos/d21/GC_DATA/HEMCO/GFAS/v2018-09/2013/GFAS_201307.nc
/geos/d21/GC_DATA/HEMCO/GFAS/v2018-09/2013/GFAS_201308.nc
/geos/d21/GC_DATA/HEMCO/GFAS/v2018-09/2013/GFAS_201309.nc
/geos/d21/GC_DATA/HEMCO/GFAS/v2018-09/2013/GFAS_201310.nc
/geos/d21/GC_DATA/HEMCO/GFAS/v2018-09/2013/GFAS_201311.nc
/geos/d21/GC_DATA/HEMCO/GFAS/v2018-09/2013/GFAS_201312.nc
/geos/d21/GC_DATA/HEMCO/MODIS_CHLR/v2019-11/MODIS.CHLRv.V5.generic.025x025.2013.nc
/geos/d21/GC_DATA/HEMCO/MODIS_CHLR/v2019-11/MODIS.CHLRv.V5.generic.025x025.2014.nc
/geos/d21/GC_DATA/HEMCO/OFFLINE_LIGHTNING/v2019-01/GEOSFP/2013/FLASH_CTH_GEOSFP_0.25x0.3125_2013_06.nc4
/geos/d21/GC_DATA/HEMCO/OFFLINE_LIGHTNING/v2019-01/GEOSFP/2013/FLASH_CTH_GEOSFP_0.25x0.3125_2013_07.nc4
/geos/d21/GC_DATA/HEMCO/OFFLINE_LIGHTNING/v2019-01/GEOSFP/2013/FLASH_CTH_GEOSFP_0.25x0.3125_2013_08.nc4
/geos/d21/GC_DATA/HEMCO/OFFLINE_LIGHTNING/v2019-01/GEOSFP/2013/FLASH_CTH_GEOSFP_0.25x0.3125_2013_09.nc4
/geos/d21/GC_DATA/HEMCO/OFFLINE_LIGHTNING/v2019-01/GEOSFP/2013/FLASH_CTH_GEOSFP_0.25x0.3125_2013_10.nc4
/geos/d21/GC_DATA/HEMCO/OFFLINE_LIGHTNING/v2019-01/GEOSFP/2013/FLASH_CTH_GEOSFP_0.25x0.3125_2013_11.nc4
/geos/d21/GC_DATA/HEMCO/OFFLINE_LIGHTNING/v2019-01/GEOSFP/2013/FLASH_CTH_GEOSFP_0.25x0.3125_2013_12.nc4
```

**Comment by yantosca** [comment]
Can you do an "out-of-the-box" dryrun (any year) with the met fields having the same resolution as the grid?  I am wondering if there is also some kind of disconnect between the grid that is specified in the grid menu and the met field grid.

**Comment by dpfinch** [comment]
Here are the files for an out of the box dry run. I did June 2013 to Jan 2014. Now the run seems to be picking up that its meant to be finding 2013 files and can't
The unique log still only has missing files. Although one thing to note is that when I run download_data.py to produce the log.dryrun.unique file, I had to change it so that it would work with out file paths (note there is not 'ExtData/' in our file path, only GC_Data/HEMCO/..). I had to be pretty heavy handed with the edits to make it work quickly so I may have altered something accidentally.
On Monday we're changing our directory structure to match /ExtData/HEMCO so I can rerun it then to see if that helps.
[log.dryrun.unique.txt](https://github.com/geoschem/geos-chem/files/4428386/log.dryrun.unique.txt)
[log.dryrun.txt](https://github.com/geoschem/geos-chem/files/4428388/log.dryrun.txt)

**Comment by dpfinch** [comment]
I've changed our directories to now include ExtData/ in the directory name (which now means I can use the original, unaltered dowload_data.py). Its not made any difference though.

I've been looking at the download_data.py file it makes sense it doesn't print out the found files. Between lines 219 and 231 there is this:
```
    for path in paths["found"]:
        if "GEOSChem.Restart" in path:
            realpath = prefix + "initial_GEOSChem_rst." + \
                       run_info["grid"] + "_" + suffix
            # --------------------------------------------------------                                                                                                                                      
            # KLUDGE to replace geosfp "as" file name with "ch"                                                                                                                                             
            # since symbolic links do not work on AWS s3://gcgrid                                                                                                                                           
            realpath = realpath.replace("025x03125_tropchem_as.nc",
					"025x03125_tropchem_ch.nc")
            # --------------------------------------------------------                                                                                                                                      
            path = path + " --> " + realpath
            new_list.append(path)
    paths["found"] = sorted(new_list)
```
This would mean only paths with `GEOSChem.Restart` in them would be added `new_list` and then that becomes `paths["found"]`. Should `new_list.append(path)` be one less indent (to match line 247)? Then the found paths would be appended to `new_list`

**Comment by dpfinch** [comment]
I've changed our directories to now include ExtData/ in the directory name (which now means I can use the original, unaltered dowload_data.py). Its not made any difference though.
I've been looking at the download_data.py file it makes sense it doesn't print out the found files. Between lines 219 and 231 there is this:
```
    for path in paths["found"]:
        if "GEOSChem.Restart" in path:
            realpath = prefix + "initial_GEOSChem_rst." + \
                       run_info["grid"] + "_" + suffix
            # --------------------------------------------------------                                                                                                                                      
            # KLUDGE to replace geosfp "as" file name with "ch"                                                                                                                                             
            # since symbolic links do not work on AWS s3://gcgrid                                                                                                                                           
            realpath = realpath.replace("025x03125_tropchem_as.nc",
					"025x03125_tropchem_ch.nc")
            # --------------------------------------------------------                                                                                                                                      
            path = path + " --> " + realpath
            new_list.append(path)
    paths["found"] = sorted(new_list)
```
This would mean only paths with `GEOSChem.Restart` in them would be added `new_list` and then that becomes `paths["found"]`. Should `new_list.append(path)` be one less indent (to match line 247)? Then the found paths would be appended to `new_list`

**Comment by yantosca** [comment]
Thanks Doug.  I'll take a look at the script.  I think we might need to reduce the indentation on that new_list.append line, as you say.

**Comment by yantosca** [comment]
I've pushed a commit https://github.com/geoschem/geos-chem-unittest/commit/b610927efa0f7ba596131d9a5f0b489d1af99e2c, which reduces the indentation of an instance of `new_list.append(path)`, which had been indented too deep.  Fixing this now prints out both missing and found files to the log of unique file names:

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!! LIST OF (UNIQUE) FILES REQUIRED FOR THE SIMULATION
!!! Start Date       : 20170701 000000
!!! End Date         : 20170701 002000
!!! Simulation       : standard
!!! Meteorology      : GEOSFP
!!! Grid Resolution  : 4.0x5.0
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
./GEOSChem.Restart.20170701_0000z.nc4 --> /n/holyscratch01/external_repos/GEOS-CHEM/gcgrid/data/ExtData/GEOSCHEM_RESTARTS/v2018-11/initial_GEOSChem_rst.4x5_standard.nc
./HEMCO_Config.rc
./HEMCO_Diagn.rc
./HEMCO_restart.201707010000.nc
./HISTORY.rc
./input.geos
/n/holyscratch01/external_repos/GEOS-CHEM/gcgrid/data/ExtData/CHEM_INPUTS/FAST_JX/v2020-02/FJX_j2j.dat
/n/holyscratch01/external_repos/GEOS-CHEM/gcgrid/data/ExtData/CHEM_INPUTS/FAST_JX/v2020-02/FJX_spec.dat
/n/holyscratch01/external_repos/GEOS-CHEM/gcgrid/data/ExtData/CHEM_INPUTS/FAST_JX/v2020-02/dust.dat
/n/holyscratch01/external_repos/GEOS-CHEM/gcgrid/data/ExtData/CHEM_INPUTS/FAST_JX/v2020-02/h2so4.dat
```
The fix will ship in GEOS-Chem 12.8.0 but you can make the same fix for yourself in your own run directory.

**Comment by dpfinch** [comment]
Thanks Bob, I've changed it in my code as well now so I'm also getting all unique files - not just missing ones (I've attached an example if needed).
Does this help diagnose the problem I was having of the run is using 2012 met fields instead of 2013?

[log.dryrun.unique.txt](https://github.com/geoschem/geos-chem/files/4462185/log.dryrun.unique.txt)

**Comment by dpfinch** [comment]
Hi - I was wondering if there was anything else I can try to address the issue I was having with it not reading the 2013 met fields?
Thank in advance!

**Comment by yantosca** [comment]
Hi Doug.  I have not had a chance to look into this yet.  I have not encountered the dry-run not picking up files, though.  Next time I'm on the cloud I'll try to replicate.

**Comment by yantosca** [comment]
I have not been able to replicate this.  I will close out this issue but please feel free to open a new issue if the problem persists.

**Comment by yantosca** [comment]
This issue may be solved by the fix made to https://github.com/geoschem/geos-chem/issues/312.  You can pull this fix from the bugfix/dryrun branch.  This will go into the standard code in 12.9.0
