### ISSUE TITLE
[FEATURE REQUEST] Allow model to run with nested boundary conditions if you add a new species

### ISSUE THREAD

**Issue by ktravis213** [geoschem/geos-chem#268]
Hi support team!
Currently the model will run with a restart file even if you add a new tracer.  However it will not do the same for boundary conditions.  This makes it difficult to run nested sensitivity tests since you have to rerun the boundary conditions with the new species.  Could we add this functionality to the model?

**Comment by msulprizio** [comment]
Absolutely, we can add this as a functionality in GEOS-Chem 12.8.1. This capability already exists for restart files, so it would make sense to extend it to boundary conditions as well. 

We want users to be aware when species are skipped and background concentrations are used, so we always advise checking the log file to ensure species are being initialized with the expected concentrations. When species aren't found in the restart file (and soon-to-be BC files), a warning is listed in the log file saying it wasn't found and the background concentration (usually 1e-20 v/v) is used.

**Comment by msulprizio** [comment]
This issue is now fixed in commit 2c7ac9ac20d470ccc1c3ec064efdfc1580c92536 and will be included in GEOS-Chem 12.8.1.
