### ISSUE TITLE
A question about GEO-Chem v 12.1.1 need netcdf4 library?

### ISSUE THREAD

**Issue by gc13141112** [geoschem/geos-chem#28]
In Ncop_Rd, cannot open:  /public/cmaq/standard/geoschem/Code.12.1.1/Extdata/HEMCO/EDGARv43/v2016-11/EDGAR_v43.CO.POW.0.1x0.1.nc

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Code stopped from DO_ERR_OUT (in module NcdfUtil/m_do_err_out.F90) 

This is an error that was encountered in one of the netCDF I/O modules,
which indicates an error in writing to or reading from a netCDF file!

**Comment by yantosca** [comment]
GEOS-Chem does need the netcdf4 and netcdf-fortran libraries.  Please see this wiki page for instructions on how to install these libraries:  http://wiki.geos-chem.org/Installing_libraries_for_GEOS-Chem

The error above probably means that GEOS-Chem could not find the file EDGAR_v43.CO.POW.0.1x0.1.nc on disk.  Please make sure you have downloaded it and that the paths in your HEMCO_Config.rc are correct.
