### ISSUE TITLE
[FEATURE REQUEST] Expand isCoards script to check GCHP file requirements

### ISSUE THREAD

**Issue by lizziel** [geoschem/geos-chem#281]
The MAPL I/O library used in GCHP is stricter about file inputs than GEOS-Chem Classic. Sometimes new GEOS-Chem input files are submitted that work fine with GEOS-Chem Classic but fail for GCHP due to a type problem or an issue with metadata. It would be fantastic if the isCoards script used to check NetCDF files prior to submission to GCST be expanded to also check that the files are compatible with MAPL.

Thus far the known file requirements for MAPL that are not an issue in GEOS-Chem Classic are:

- All data must be floating point (not integers)

- Time attributes containing string HH, MM, and SS must not contain decimal places. For example, 00:00:0.0 will cause MAPL to crash.

- The reference time in the time dimension units attribute must accurately reflect the datetimes in the file. For example, "hours since 2015-12-28" with time values starting at 0 is not acceptable for a Dec 29, 2015 file. This sort of error can happen if daily files are copied and filenames are changed, but the metadata is not.

As we encounter or remember other limitations we can put them here on this issue.

**Comment by yantosca** [comment]
This is now completed in [netcdf-scripts v0.1.5](https://github.com/geoschem/netcdf-scripts/releases/tag/v0.1.5).

@lizziel: Feel free to close this issue

**Comment by lizziel** [comment]
Thanks @yantosca!
