### ISSUE TITLE
[BUG/ISSUE] Missing emissions over Asia in nested simulations

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#286]
I am submitting this issue on behalf of Shixian Zhai:

>I recently encountered a strange problem with HEMCO while using GEOS-Chem v12.7.1 at 0.25x0.3125 & 0.5x0.625 resolution. 
>
>Both MIX and KORUS are emissions for Asia, and MEIC is emissions for China.
>
>1. If I turn on MIX (or KORUS) for Asia, and MEIC for China, emissions in Asia outside of China (South Korea and Japan) are all zeros in `HEMCO_diagnostic****.nc`.
>
>2. If I only turn on KORUS (or MIX) for Asia, and turn off MEIC for China, China, South Korea and Japan all have reasonable emissions in `HEMCO_diagnostic****.nc`.
>
>3. In the 4x5 GEOS-Chem v12.7.1, there exists seemingly reasonable emission intensities in `HEMCO_diagnostic****.nc` over South Korea and Japan when both MIX and MEIC are turned on.
>
>4. 0.5x0.625 GEOS-Chem v12.7.1 has the same problem with that of 0.25x0.3125 GEOS-Chem v12.7.1.
>
>5. I then checked results from 0.5x0.625 GEOS-Chem v12.3.1 with MIX and MEIC turned on, emission intensities are correct over China, South Korea, and Japan.
>
>What could be the cause of this problem? Could it be the wrong processing of masks?

**Comment by yantosca** [comment]
Thanks for writing.  It could very well be a masking issue.

We would need to see your input files (HEMCO_Config.rc, input.geos), log files, and HEMCO.log files from all runs so that we can determine what is happening.  Can you please attach them to this issue?

Also -- note that KORUS-AQ and MEIC are non-standard emissions for GEOS-Chem.  They are used in research but we have not tested/benchmarked them in GEOS-Chem yet.  It could be that there are some issues with the input files (although a masking problem is probably more likely).

NOTE:  Right now in the current HEMCO, the data is always regridded from its original resolution to the model grid, and then the data are masked and scaled.  In the future, HEMCO will have an intermediate grid where masking and scaling will happen before regridding.  That isn't ready yet but will be in the near future (Haipeng has been working on that).

**Comment by zsx-GitHub** [comment]
Thank you very much for your reply! 

I have been double checking this, and find that if we change

1009 CHINA_MASK  $ROOT/MASKS/v2018-09/China_mask.generic.1x1.nc    MASK     2000/1/1/0 C xy 1 1  70/10/150/60
to
1009 CHINA_MASK  $ROOT/MASKS/v2018-09/China_mask.generic.1x1.nc    MASK     2000/1/1/0 C xy 1 1  70/10/115 (or 130)/60

The model will use MEIC for China and MIX for the rest of Asia. 

Shixian

**Comment by yantosca** [comment]
Thanks Shixian.  I will go ahead and close out this issue.
