### ISSUE TITLE
[QUESTION] Are Nested Hg Simulations Supported in GEOS-Chem v12.7.2?

### ISSUE THREAD

**Issue by bgeyman** [geoschem/geos-chem#288]
I would like to run the mercury simulation with a nested grid in GEOS-Chem 'Classic' v12.7.2. I notice that the `CopyRunDirs.input` template provided with the unit tester does not currently provide nested Hg options. Is it still possible to perform nested Hg simulations by following the FlexGrid instructions: http://wiki.seas.harvard.edu/geos-chem/index.php/FlexGrid#0.5.C2.B0_x_0.625.C2.B0_nested_North_America

**Comment by yantosca** [comment]
Thanks for writing.  The Hg simulation has gotten out of step with the current model, due to many structural changes that have happened recently.

@cpthackray is our liaison for the Hg simulations.  He might have more suggestions or a path forward.

**Comment by msulprizio** [comment]
@bgeyman Yes, you should still be able to run the nested Hg simulation, simply by taking a run directory that you created for a global Hg simulation and modifying the values in the Grid Menu of input.geos. You'll also need to turn on `GC_BCs` in the HEMCO_Config.rc  for your nested simulation and make sure the path points to the BC files saved out by your global Hg simulation (by turning on the `BoundaryConditions` collection in `HISTORY.rc`).

**Comment by msulprizio** [comment]
I am closing this issue, but feel free to reopen or submit a separate issue if you do encounter any problems running the nested Hg simulation.
