### ISSUE TITLE
[QUESTION] How to calculate PM2.5 with RH controlled to 50%?

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/geos-chem#289]
Hi there,

From your [Particulate_matter](http://wiki.seas.harvard.edu/geos-chem/index.php/Particulate_matter_in_GEOS-Chem) wiki, I believe PM2.5 in GEOS-Chem is calculated with RH controlled to 35%. Nonetheless, the wiki also shows that PM2.5 in Europe is measured at RH=50% (also the case in China). So I just wonder how could I change PM2.5 calculation to RH=50% so as to better compare with those PM2.5 measurements. I have checked the `aerosol_mod.F` and believe the following codes are probably relevant.

```
         ! Density of H2O [kg/m3]
         Rho_wet    = 1000e+0_fp

         ! Growth factor for SO4 + NIT + NH4
		 ! They use SO4_GROWTH for SIA_GROWTH.
		 ! SIA: Sulfate, Inorganic Nitrate, Ammonium
		 ! Hence I can use SIA_GROWTH for anyone of them.
		 ! (fei 10/14/2019)
         Rad_dry    = REAA(1,k_SO4)
         Rad_wet    = REAA(1,k_SO4) + 35e+0_fp *
     &              ( REAA(2,k_SO4) - REAA(1,k_SO4) ) / 50e+0_fp
         Rho_dry    = State_Chm%SpcData(id_SO4)%Info%Density
         SIA_GROWTH = 1 + ( ( ( Rad_wet / Rad_dry ) ** 3 - 1 ) *
     &                        ( Rho_wet / Rho_dry ) )

```

At first glance, I suppose I should only need to change `35e+0_fp` to `50e+0_fp`, but then I found that there was `50e+0_fp` already, so I am getting confused. I would be grateful for you kind help!

**Comment by msulprizio** [comment]
It looks like you're on the right track. The code that you want to modify in `aerosol_mod.F` is:

```
    !=================================================================
    ! Compute growth factors at 35% RH
    !
    ! GF = 1 + [ ( r_wet / r_dry )^3 -1 ] * [ rho_wet / rho_dry ]
    !
    ! and use rho_wet = 1000 kg/m3
    !=================================================================
    IF ( FIRST ) THEN

       ! Species index of REAA from RD_AOD (in fast_jx_mod.F90)
       k_SO4      = 1
       k_ORG      = 3
       k_SSA      = 4

       ! Density of H2O [kg/m3]
       Rho_wet    = 1000e+0_fp

       ! Growth factor for SO4 + NIT + NH4
       Rad_dry    = REAA(1,k_SO4)
       Rad_wet    = REAA(1,k_SO4) + 35e+0_fp * &
                  ( REAA(2,k_SO4) - REAA(1,k_SO4) ) / 50e+0_fp
       Rho_dry    = State_Chm%SpcData(id_SO4)%Info%Density
       SIA_GROWTH = 1 + ( ( ( Rad_wet / Rad_dry ) ** 3 - 1 ) * &
                            ( Rho_wet / Rho_dry ) )

       ! Growth factor for OCPI + SOA
       Rad_dry    = REAA(1,k_ORG)
       Rad_wet    = REAA(1,k_ORG) + 35e+0_fp * &
                  ( REAA(2,k_ORG) - REAA(1,k_ORG) ) / 50e+0_fp
       IF ( IS_POA ) THEN
          Rho_dry    = State_Chm%SpcData(id_POA1)%Info%Density
       ELSE IF ( IS_OCPI ) THEN
          Rho_dry    = State_Chm%SpcData(id_OCPI)%Info%Density
       ENDIF
       ORG_GROWTH = 1 + ( ( ( Rad_wet / Rad_dry ) ** 3 - 1 ) * &
                            ( Rho_wet / Rho_dry ) )

       ! Growth factor for SALA
       Rad_dry    = REAA(1,k_SSA)
       Rad_wet    = REAA(1,k_SSA) + 35e+0_fp * &
                  ( REAA(2,k_SSA) - REAA(1,k_SSA) ) / 50e+0_fp
       Rho_dry    = State_Chm%SpcData(id_SALA)%Info%Density
       SSA_GROWTH = 1 + ( ( ( Rad_wet / Rad_dry ) ** 3 - 1 ) * &
                            ( Rho_wet / Rho_dry ) )

       ! Print debug info
       IF ( prtDebug ) THEN
          WRITE( 6,'(a)') 'Growth factors at 35% RH:'
          WRITE( 6, 100 ) SIA_GROWTH, ' for SO4, NIT, and NH4'
          WRITE( 6, 100 ) ORG_GROWTH, ' for OCPI and SOA'
          WRITE( 6, 100 ) SSA_GROWTH, ' for SALA'
100       FORMAT(F5.2,A)
       ENDIF

    ENDIF
```

Specifically, you will want to change the use of `35e0_fp` in the `Rad_wet` calculation. The `50e+0_fp` used there is part of the calculation and doesn't represent RH, so that should remain unchanged. Note also that the computed values are printed out to the log file if debug print is enabled in input.geos, so you can check that the values make sense there compared to the values for 35% and 50% provided on the particulate matter wiki page.

**Comment by FeiYao-Edinburgh** [comment]
Thanks for answering! Just one more question on `if debug print is enabled in input.geos`. I have not found relevant options in [input.geos](http://wiki.seas.harvard.edu/geos-chem/index.php/The_input.geos_file#Currently-used_menus_in_input.geos), could you please be more specific on which MENU that I should turn to? Or it might be set when compiling?

**Comment by msulprizio** [comment]
If you are using GEOS-Chem 12.6.0 or later, the debug print option can be turned on in the simulation menu at the top of input.geos:

```
------------------------+------------------------------------------------------
%%% SIMULATION MENU %%% :
Start YYYYMMDD, hhmmss  : {DATE1} {TIME1}
End   YYYYMMDD, hhmmss  : {DATE2} {TIME2}
Run directory           : ./
Root data directory     : /n/holyscratch01/external_repos/GEOS-CHEM/gcgrid/data/ExtData
Met field               : geosfp
Simulation name         : benchmark
Turn on debug printout? : T
```

For earlier versions, that option can be turned on by setting ND70 in the diagnostic menu to 1:

```
ND70: Debug output      :  1   all
```

**Comment by FeiYao-Edinburgh** [comment]
Many thanks for your clear clarification!
