### ISSUE TITLE
[QUESTION] Can you run nested domain with same resolution as boundary conditions

### ISSUE THREAD

**Issue by chfite** [geoschem/geos-chem#290]
I was wondering if it’s possible to run a “nested” domain, but with the nested domain being 2x2.5, and using 2x2.5 boundary conditions that I already had from a prior simulation.  I’m using GC 12.6.0. 

Basically, I realized I wanted to rerun my initial simulation to get an additional diagnostic output, but I only needed that new output over a CONUS domain. I was hoping to run my model at 2x2.5, but just have the domain over CONUS, and it would use my 2x2.5 global boundary conditions from my original simulation. I was going to do this so could get my output faster and save time. 

I made the edits in input.geos and HEMCO_Config  to make it attempt to do this. When I run the “nested” simulation it successfully finds my boundary conditions but then has a segmentation fault and kills. 

Is there a specific reason why running a “nested” domain at the same resolution as the boundary conditions is not possible, or are there additional changes I could make that would make it work?

**Comment by msulprizio** [comment]
Theoretically, you should be able to input boundary conditions at any resolution. HEMCO reads in the boundary condition files, calculates the input grid based on fields read from the file, then regrids to the model grid.

Can you try running a short simulation with [debug flags turned on](http://wiki.seas.harvard.edu/geos-chem/index.php/Debugging_GEOS-Chem#Recompile_GEOS-Chem_with_debug_options_turned_on) to see if you get additional error output about the segmentation fault? Please send us that output, along with your GEOS-Chem and HEMCO log files, and HEMCO_Config.rc. You should be able to drop those files here, but you may need to change the extension to .txt.

**Comment by yantosca** [comment]
Also, another option you have in 12.6.0 is to run a full global simulation but also tell the HISTORY diagnostic output that you only want to save output over the CONUS region.  You can subset by adding the LON_RANGE, LAT_RANGE, and LEVELS tags to any collection.   

We have an example of this [on the wiki here](http://wiki.seas.harvard.edu/geos-chem/index.php/Overview_of_History_diagnostics#Sample_HISTORY.rc_diagnostic_input_file).   See the "SpeciesConc.subset" collection in the example.

```

**Comment by chfite** [comment]
Thanks, @msulprizio 

I recompiled using `make -j 20 DEBUG=y BOUNDS=y TRACEBACK=y build`

And it seems to have recompiled and turned on debugging options. However, where was the debugging output supposed to be output when I ran my simulation again? Was it supposed to go to some log file or just print out while the simulation was running? The only log file I see is the HEMCO.log file.

Here was the last few lines of output I got when I ran the simulation, supposedly with debugging turned on:

HEMCO: Opening //net/home_stu/cfite/GEOS-Chem/run_dirs/atmochem_project/geosfp_2x25_complexSOA_SVPOA/OutputDir/GEOSChem.BoundaryConditions.20190812_0000z.nc4
     - FLEXGRID A1 met fields for 2019/08/12 00:30 have been read already
     - FLEXGRID A3 met fields for 2019/08/12 01:30 have been read already
     - Found all I3     met fields for 2019/08/12 03:00
GET_BOUNDARY_CONDITIONS: Found All BCs at 2019/08/12 00:00
NASA-GSFC Tracer Transport Module successfully initialized
forrtl: severe (174): SIGSEGV, segmentation fault occurred
forrtl: severe (174): SIGSEGV, segmentation fault occurred
forrtl: severe (174): SIGSEGV, segmentation fault occurred
forrtl: severe (174): SIGSEGV, segmentation fault occurred
forrtl: severe (174): SIGSEGV, segmentation fault occurred
forrtl: severe (174): SIGSEGV, segmentation fault occurred


It seems that it was successfully finding my boundary conditions but then had trouble applying them? I attached here my HEMCO_Config, HEMCO.log, and input.geos in case you need those.

[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/4540448/HEMCO_Config.txt)
[HEMCO.log.txt](https://github.com/geoschem/geos-chem/files/4540450/HEMCO.log.txt)
[input.geos.txt](https://github.com/geoschem/geos-chem/files/4540451/input.geos.txt)

**Comment by msulprizio** [comment]
The output from the debug flags should be printed to your stdout or stderr which, depending on how you submit your run, may print to the GEOS-Chem log file, a scheduler file, or your terminal window. Could you try also setting Verbose and Warnings to 3 in HEMCO_Config.rc then rerunning. Then please provide your HEMCO.log, GEOS-Chem log, and job output file. Please see this page for more information on [what files will help us diagnose your issue](http://wiki.seas.harvard.edu/geos-chem/index.php/Submitting_GEOS-Chem_support_requests#What_do_I_need_to_include_in_my_support_request.3F).

**Comment by chfite** [comment]
I changed Verbose and Warnings to 3 in HEMCO_Config like you asked.
Here is the GEOS-Chem log file, as well as HEMCO.log and my lastbuild file. I did not see any extra specific debug flags in those, but I had compiled my model using `make -j 20 DEBUG=y BOUNDS=y TRACEBACK=y build` like I had mentioned previously. My simulation does not produce a stdout or stderr file, so is there something additional I need to do to get that debug output?

[GEOSChem.log.txt](https://github.com/geoschem/geos-chem/files/4541613/GEOSChem.log.txt)
[HEMCO.log.txt](https://github.com/geoschem/geos-chem/files/4541619/HEMCO.log.txt)
[lastbuild.txt](https://github.com/geoschem/geos-chem/files/4541620/lastbuild.txt)

**Comment by msulprizio** [comment]
If you are submitting your GEOS-Chem run to a job scheduler (e.g. SLURM), then you may have a output file in your run directory with the run ID in it and the stdout/stderr output may be found in there. If you're running interactively (e.g. executing `./geos` at the command line), then that information may be printed directly in your terminal window. 

From your GEOS-Chem log file, it seems that the model gets one step past reading the boundary conditions. Have you tried increasing your memory to make sure you're not running out?

**Comment by r-pound** [comment]
I have been doing some nested model runs and had a similar error. I made a comment in this thread 
https://github.com/geoschem/geos-chem/issues/251 about some hard coding that when I updated I was able to run the nested grid with resolutions other than 0.5 and 0.25.

**Comment by yantosca** [comment]
I will close out this issue for now.  Feel free to reopen or to submit a new issue or feature request.
