### ISSUE TITLE
[QUESTION] approach to save model convolved by satellite averaging kernels 

### ISSUE THREAD

**Issue by yuexuyan** [geoschem/geos-chem#291]
Hi, I am reading GEOS-Chem Adjoint User's Guide on this address:  
http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_Adjoint_User%27s_Guide#Obtaining_the_adjoint_model 

I think there is a function to save the model as a column value by switch on the " => H(model) " in DIAGNOSTICS MENU in input.gcadj file. 

I want to ask that is this function only exists in adjoint model?

**Comment by yantosca** [comment]
Yes, this is just in the adjoint code.

**Comment by yuexuyan** [comment]
thank you very much
