### ISSUE TITLE
[BUG/ISSUE] HEMCO changing spatial distribution of input emission field.

### ISSUE THREAD

**Issue by jennyfisher** [geoschem/geos-chem#295]
## Describe the bug
I am running a simulation with passive tracers (using the TransportTracers simulation, GEOS-FP, 2x2.5) and have added some new emissions using HEMCO. For the passive tracers I've added, these new emissions are the only source. I am finding that although my original high-resolution input file looks fine, once the emissions have been processed through HEMCO they are somehow getting spread out along longitude lines. See attached screenshots (I've saturated the colour scales to make this clearer).
<img width="1018" alt="OriginalFile" src="https://user-images.githubusercontent.com/1236416/81253239-6d6d4700-906b-11ea-8c19-925763c57015.png">
<img width="1021" alt="FromHEMCOdiagnostics" src="https://user-images.githubusercontent.com/1236416/81253242-7100ce00-906b-11ea-830b-a5a77ff183c0.png">

## To Reproduce
See attached files.

## Expected behavior
Emissions should be at source locations only (but lower resolution that original file).

## Error messages
None

## Required information
 - GEOS-Chem version 12.7.2
 - Compiler version ifort 19.0.3.199
 - netCDF 4.7.1
 - Computational environment Australian NCI Gadi cluster
 - "Out of the box" code with modifications to input files in run directory

## Input and log files attached
 - The lastbuild file
 - The input.geos file
 - The HEMCO_Config.rc file
 - The GEOS-Chem "Classic" log file
 - The HEMCO.log file
 - The HEMCO_Diagn.rc file
 - The header information of the input netcdf file `$ROOT/EWASTE/v2020-04/ewaste_to_burn_kgm2s.nc` (from an ncdump -h command)

[for_GCST.zip](https://github.com/geoschem/geos-chem/files/4590677/for_GCST.zip)

## Additional context
I can share the netcdf file if useful, but it is 50MB...

Thanks,
Jenny

**Comment by msulprizio** [comment]
In the original netCDF file, are the values in gray zero or missing values? If the latter, I wonder if that may be the issue. Maybe you need to either zero those grid boxes or alternatively apply a mask to those emissions. 

@christophkeller Have you seen this before? Do you have any thoughts on the issue?

**Comment by jennyfisher** [comment]
Thanks! They are missing values (NaN). I’ll try setting them to zero later and see if that works better.

**Comment by jennyfisher** [comment]
Setting the missing values to 0 solved it. Thanks @msulprizio !
