### ISSUE TITLE
[BUG/ISSUE] CHEM_INPUTS/FAST_JX/v2020-02/ files missing from ComputeCanada

### ISSUE THREAD

**Issue by jennyfisher** [geoschem/geos-chem#296]
We are using the dryrun option to find and then download files for an out-of-the-box standard simulation with v12.8.0. The dryrun flags a set of missing required files in the `CHEM_INPUTS/FAST_JX/v2020-02/` directory (along with other missing HEMCO files). Using the `download_data.py` script downloads all the missing HEMCO files but prints a series of file not found errors for the FAST_JX files, e.g.:
```
Downloading data from ComputeCanada
--2020-05-07 15:19:18--  http://geoschemdata.computecanada.ca/ExtData/CHEM_INPUTS/FAST_JX/v2020-02/FJX_j2j.dat
Resolving geoschemdata.computecanada.ca (geoschemdata.computecanada.ca)... 206.12.88.212
Connecting to geoschemdata.computecanada.ca (geoschemdata.computecanada.ca)|206.12.88.212|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-05-07 15:19:19 ERROR 404: Not Found.
```

I had a look directly at http://geoschemdata.computecanada.ca/ExtData/CHEM_INPUTS/FAST_JX/ and noticed the v2020-02/ directory does not exist there.

I think this will be resolved if that directory gets added...

[for_GCST.zip](https://github.com/geoschem/geos-chem/files/4590863/for_GCST.zip)

**Comment by jennyfisher** [comment]
Just adding @PaoloSebas to this issue as he was the one who discovered the problem originally!

**Comment by msulprizio** [comment]
@Jun-Meng could you copy this directory to CCVM at your earliest convenience?

**Comment by Jun-Meng** [comment]
> @Jun-Meng could you copy this directory to CCVM at your earliest convenience?

Done.

**Comment by PaoloSebas** [comment]
Thank you very much.
