### ISSUE TITLE
[BUG/ISSUE] UnboundLocalError in download_data.py dry-run download script

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#298]
I am submitting this issue on behalf of Amir Hossein Souri:

>I'm facing this issue when using the dry-run simulation for the python script:
>
>
```UnboundLocalError: local variable 'local_prefix' referenced before assignment```
>
>I'm using python 3.7.

**Comment by yantosca** [comment]
Thanks for writing.  

Although now that you mention it, it does seem that there could be an error in this line:

```
    # Find the local data directory prefix (path to ExtData)
    for path in found + missing:
        if "ExtData" in path:
            index = path.find("ExtData")
            local_prefix = path[:index]
            break

    # Close file and return
    # The "sorted" command will return unique values
    f.close()
    return {"comments": comments, "found": found,
            "missing": missing, "local_prefix": local_prefix}
```

so if your data path does not contain ExtData, then that will cause `local_prefix` not to be defined, and then you'll get the error above.  I can add an error check for the 12.8.1 release that is upcoming.

I would try to specify a download path that includes ExtData, as that is the GEOS-Chem convention.

Also note: we fixed another in 12.8.0: https://github.com/geoschem/geos-chem-unittest/commit/b610927efa0f7ba596131d9a5f0b489d1af99e2c.  You didn't specify a GEOS-Chem version but you might want to apply this fix if you are using 12.7.2 or earlier.

**Comment by ahsouri** [comment]
Thanks, Bob for your help!

I added ExtData to the paths and now it works well.

Amir

**Comment by yantosca** [comment]
Great!  I'll close this out.  We'll put an error trap in for 12.8.1.
