### ISSUE TITLE
[BUG/ISSUE] list-directed I/O syntax error

### ISSUE THREAD

**Issue by ahsouri** [geoschem/geos-chem#300]
Hi,

I'm trying to run the newest version of GEOS-Chem 12.8.0. Unfortunately, I faced this issue which I guess has to do with a bad input file (or inability of the code to read a file) (I have attached the log file too). I read several times to catch a typo or something in the control files (primarily in HEMCO_Config.rc), but either I'm too old to detect or there may be another reason for this.

forrtl: severe (59): list-directed I/O syntax error, unit -5, file Internal List-Directed Read
Image              PC                Routine            Line        Source            
libifcoremt.so.5   00002AAAAB8907B6  for__io_return        Unknown  Unknown
libifcoremt.so.5   00002AAAAB8C8D52  for_read_int_lis_     Unknown  Unknown
libifcoremt.so.5   00002AAAAB8C7A5C  for_read_int_lis      Unknown  Unknown
geos               0000000000906031  hco_chartools_mod         144  hco_chartools_mod.F90
geos               0000000000969D7A  hcoio_read_std_mo        4042  hcoio_read_std_mod.F90
geos               000000000096E174  hcoio_read_std_mo        3716  hcoio_read_std_mod.F90
geos               0000000000967906  hcoio_read_std_mo        3427  hcoio_read_std_mod.F90
geos               0000000000944A43  hco_readlist_mod_         488  hco_readlist_mod.F90
geos               0000000000944142  hco_readlist_mod_         283  hco_readlist_mod.F90
geos               00000000009433F1  hco_driver_mod_mp         163  hco_driver_mod.F90
geos               0000000000412AD0  hcoi_gc_main_mod_         816  hcoi_gc_main_mod.F90
geos               00000000005B928B  emissions_mod_mp_         203  emissions_mod.F90
geos               0000000000403FE0  MAIN__                    757  main.F90
geos               0000000000403B22  Unknown               Unknown  Unknown
libc-2.17.so       00002AAAAEA9E495  __libc_start_main     Unknown  Unknown
geos               0000000000403A29  Unknown               Unknown  Unknown

I also have attached input.geos and HEMCO_Config.rc.

Unfortunately, I don't have the lastbuild file to send it (I guess it is made through CMAKE?). I used intel/19/mvapich-19.5, CHEM=standard. 

Best,

[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/4610267/HEMCO_Config.rc.txt)

[input.geos.txt](https://github.com/geoschem/geos-chem/files/4610269/input.geos.txt)

[log.txt](https://github.com/geoschem/geos-chem/files/4610261/log.txt)

**Comment by ahsouri** [comment]
I found the issue. Sorry for the inconvenience. I did not set DUST_SF at Offline dust scale factors in HEMCO.

**Comment by lizziel** [comment]
Okay, glad you found it!
