### ISSUE TITLE
[BUG/ISSUE] GEOSFP SPEED Met Files

### ISSUE THREAD

**Issue by dpfinch** [geoschem/geos-chem#302]
Not sure if this is a bug or a question:

I'm trying to download the GEOS_FP 0.25x0.3125 global met files for 2013 from Compute Canada from /ExtData/GEOS_0.25x0.3125/GEOS_FP/2013. I've noticed that in the some of the months (6,8,9,10 & 11) only have one file for each day labelled something along the lines of: GEOSFP.20130601.SPEED.025x03125.nc

What is this file? And is there anywhere I can get the usual met fields?
Some of the other months (3, 4, 5 & 12) are missing any files from this year.

**Comment by dpfinch** [comment]
On a related note - I'm wanting 2013 data for a spin up for a 2014 simulation. Do you think I should use MERRA2 met data for this time period instead?

**Comment by Jun-Meng** [comment]
Hi, the GEOSFP met-field only cover data since 2014. See the page for the raw data: https://portal.nccs.nasa.gov/datashare/gmao/geos-fp/das/.

**Comment by dpfinch** [comment]
Hi, 
Thanks for the reply - it dawned on me that that might be the case just as I asked the question! I'll go with the MERRA 2 data then

**Comment by lizziel** [comment]
We've had this question quite a lot since there is a folder for 2013. Do we need to keep that?

**Comment by Jun-Meng** [comment]
I have no idea why the 2013 folder was put there. @ChiLi90 @yantosca any ideas?

**Comment by yantosca** [comment]
Hi  -- the SPEED files were made by Dave Ridley a while ago when he was testing out a new dust emissions algorithm.  But he abandoned that line of work so we didn't need the SPEED files anymore.  You can just ignore those.

**Comment by lizziel** [comment]
I think we should give Dave a heads up that we will delete those files. If he still needs them he can download them before we delete.

**Comment by lizziel** [comment]
@Jun-Meng , would you be able to reach out to Dave about the necessity of keeping these files? it would be great if he could archive them if he still needs them so we can delete them.

**Comment by Jun-Meng** [comment]
Sure.

**Comment by lizziel** [comment]
I will close this issue since the original question is answered.
