### ISSUE TITLE
[FEATURE REQUEST] Reduce memory utilization in GCC dry run

### ISSUE THREAD

**Issue by sdeastham** [geoschem/geos-chem#306]
When running GEOS-Chem Classic in "dry run" mode to get a list of missing data files, it appears that a substantial memory allocation is required. In a test on our cluster, I've found that (for a 2x2.5 simulation) more than 32 GB of memory are needed. If there is some way to reduce the memory requirement that would help to increase the utility of the dry run option.

**Comment by lizziel** [comment]
I wonder if all the diagnostics are being allocated. Do you see a difference if you comment out diagnostic collections in HISTORY.rc?

**Comment by yantosca** [comment]
I could try to check the diaglist...perhaps we can shunt the allocation of diagnostics if dryrun is on.

**Comment by yantosca** [comment]
I just took a look at the code.  The dryrun exits before allocating any of the State_DIag and State_Met arrays.  For State_Chm, the species database is populated, as well as the hash table, but then it exits without allocating memory to any arrays.

I know that in HEMCO we have to populate the containers of the HcoState linked list for the dry-run to work.  Maybe @jimmielin can comment further on that.  We could try to populate the container but not allocate the array if that is the issue.

**Comment by yantosca** [comment]
It appears as if some other non-HEMCO arrays (perhaps in wetdep and probably elsewhere) might still be getting allocated but don't have to be for the dry-run.  Will dig further.

**Comment by jimmielin** [comment]
Hi Bob, I think it may be possible to override the allocation of arrays. This is done somewhere in `HCOIO_Read_Std_Mod` right now, where the dry-run routine will assert the array and thus allocate it within HEMCO. It might not be necessary but I believe this is to make other modules in HEMCO happy. I wasn't able to patch out the allocation when I originally implemented it, so I went with allocating and filling zeroes in. It might be able to be optimized with a closer look. Thanks!

**Comment by yantosca** [comment]
Thanks @jimmielin.  I just pushed some updates to dev/12.8.1 to prevent arrays from being allocated in the GeosCore routines.  But a 2x2.5 dry-run still requires about 32GB, so I think all of that is coming from HEMCO.  I will see if we can shunt the allocation of HEMCO arrays.  Will advise further.

**Comment by yantosca** [comment]
@jimmielin: I found the lines in question:
https://github.com/geoschem/geos-chem/blob/8569729e45ba6f0002ac006e5778fa2ce709a155/HEMCO/src/Core/hcoio_read_std_mod.F90#L316-L341

These populate the data arrays with dummy values (1?) but that takes up a lot of memory.   When I deleted these lines I found that even for a geosfp_2x25_standard dryrun, only 5.3 GB of memory was used (see the line with ryantosca - geos):

![2020_05_14_10_18_52_Greenshot](https://user-images.githubusercontent.com/5880296/81946803-d43fb280-95cd-11ea-9f57-81c10306d940.png)

@jimmielin: Because this touches HEMCO, what is the best way to proceed?  Should I make the commit in the geoschem/geos-chem repo and also submit a pull-request for geoschem/HEMCO?

**Comment by jimmielin** [comment]
Thanks Bob! I believe that is the procedure right now if this has to go in 12.9.0.
I believe @lizziel is also working on `HCOIO_Read_Std_Mod` so her advice will be useful in regards to the handling of the file. Lizzie, may I ask what would be the best way to incorporate Bob's changes for the dry run here? Thanks!

**Comment by yantosca** [comment]
Thanks @jimmielin.  I've pushed to dev/12.8.1 but will set up a PR now for geoschem/HEMCO.

**Comment by yantosca** [comment]
This is now resolved in the GEOS-Chem code (for 12.8.1) with commits https://github.com/geoschem/geos-chem/commit/c84907a00c19af617177759119a24988a84d863c, https://github.com/geoschem/geos-chem/commit/8569729e45ba6f0002ac006e5778fa2ce709a155, and https://github.com/geoschem/geos-chem/commit/56ee92a5665a978b59450c9b7615e59528b2d63c.

A corresponding pull request has been made for the geoschem/HEMCO repo: https://github.com/geoschem/HEMCO/pull/31
