### ISSUE TITLE
[FEATURE REQUEST] Rename operation categories in budget diagnostics

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#308]
The budget diagnostics currently produce output for the following operations:

- Chemistry  
- Convection            
- EmisDryDep
- Mixing
- Transport 
- WetDep 
- ACCUMULATION

This can be confusing because some operations overlap or include multiple operations. We should rename them to be more clear.

**Comment by lizziel** [comment]
Just to clarify, we don't have an ACCUMULATION budget diagnostic. It can be calculated post-processing by summing the 6 budget diagnostics that are output, which is what is done for the budget diagnostic table in GEOS-Chem benchmarks.

**Comment by msulprizio** [comment]
The confusion here is that there is overlap between the emissions, dry deposition, and mixing operations. There is a separate action item currently slated for the early GEOS-Chem 13 release to clearly separate these operations in the code (see https://github.com/geoschem/geos-chem/issues/327). That update should address the budget diagnostic issue here. As a temporary solution, we will add a comment to the top of the budget output file explaining how these output can be interpreted depending on which PBL mixing scheme is used.
