### ISSUE TITLE
[FEATURE REQUEST] Use same input files for GEOS-Chem Classic and GCHP 

### ISSUE THREAD

**Issue by lizziel** [geoschem/geos-chem#314]
There has been some divergence in input files for GEOS-Chem Classic and GCHP over the years due to required file updates needed for compatibility with MAPL in GCHP but not GEOS-Chem Classic. In some cases we started using those files for GEOS-Chem Classic and in others we did not, simply because it does not impact output and therefore is not necessary.

It would be good to assess what all the differences are and then, where possible, use the same files in both. This would have the added benefit of users being able to download most input files for GCHP using the GEOS-Chem Classic dry-run option. Ideally this update would be part of the 13.0 release so that the dry-run option with GEOS-Chem Classic could be used on AWS cloud with that version.

**Comment by msulprizio** [comment]
Input files for GCHP and GCC's full-chemistry and TransportTracer simulations have been made consistent with each other with the [recent move of GEOS-Chem run directory files to this repository](https://github.com/geoschem/geos-chem/issues/283) and with the clean-up of input files that came along with that. The only remaining differences between GCC and GCHP input files are now in the following files in HEMCO_Config.rc:

- GEIA_NH3
- TZOMPASOSA_C2H6
- BIOFUEL C3H8
- ORDONZE_IODOCARB
- DustDead
- CMIP6_SFC_CH4
- SfcVMR

The differences between the above files are that GCC uses the original 4x5 files (converted from bpch in most cases), while GCHP uses 2x2.5 files created from the 4x5 files. The reason for using the 2x2.5 files is to avoid issues in GCHP when running at very high resolutions. To eliminate the remaining differences in GCHP and GCC's HEMCO_Config.rc files, we will update GCC to use the newer files at 2x2.5. This update should only introduce numerical noise. I am testing with an internal 1-month benchmark now.

**Comment by lizziel** [comment]
This update is now complete.
