### ISSUE TITLE
[BUG/ISSUE] Prod/loss rates do not match between NetCDF and BPCH diagnostics

### ISSUE THREAD

**Issue by MaggieMarvin** [geoschem/geos-chem#316]
Hi there, I'm using GEOS-Chem v12.5.0 to run the complexSOA_SVPOA global simulation for 2018 at 2x2.5 degree resolution, and it seems that although the prod/loss diagnostics saved out to NetCDF and BPCH (via ND65) are both reported with the same units, the values do not match. I've only looked at the loss rate for isoprene so far, but the rates from the NetCDF diagnostic are 1000x times higher than the rates from ND65. The loss rates from ND65 seem more reasonable to me and can be used to reproduce expected isoprene lifetimes. Although the loss rates do not match, the isoprene mixing ratios are consistent between the NetCDF and BPCH diagnostics. 

## To Reproduce
1. Add LISOP loss family to gckpp.kpp in the SOA_SVPOA mechanism directory
2. Run KPP
3. Compile GEOS-Chem
4. Turn on ND65 P/L diagnostic
5. Turn on ProdLoss NetCDF diagnostic: save hourly to daily output files
6. Run GEOS-Chem
7. Workup: Compute monthly mean for NetCDF diagnostic and compare to BPCH

## Expected behavior
Given reported units (molec/cm3/s), the values of the isoprene loss rates reported in the NetCDF and BPCH diagnostics should match.

## Error messages
None

## Required information
Please include the following:
 - GEOS-Chem version you are using: v12.5.0
 - Compiler version that you are using: gfortran
 - Computational environment: local computer (24 cores)
 - Are you using "out of the box" code, or have you made modifications? Modified to include LISOP in prod/loss families

[gckpp.kpp.txt](https://github.com/geoschem/geos-chem/files/4653062/gckpp.kpp.txt)
[input.geos.txt](https://github.com/geoschem/geos-chem/files/4653054/input.geos.txt)
[HISTORY.rc.txt](https://github.com/geoschem/geos-chem/files/4653055/HISTORY.rc.txt)

**Comment by yantosca** [comment]
HI Maggie, thanks for writing.  A couple of things:

(1) Have you seen this type of error in an "out-of-the-box" version of GEOS-Chem, with the regular Prod/Loss diagnostics?  I want to be sure that it's not a more general problem first.

(2) Also, have you tried using the debugging flags (DEBUG=y BOUNDS=y FPEX=y)?  That might reveal an upstream error or other corruption.

**Comment by MaggieMarvin** [comment]
Hi Bob,

I tried running my custom version with debugging and it flagged an issue in the ND71 diagnostic, which I had turned on to get hourly max surface ozone. Just turning off ND71 seemed to do the trick, which is fine for me as I don't really need it anyway. I can't replicate this issue with the "out-of-the-box" code, so it must be something funky in my custom setup.

Best,
Maggie

**Comment by yantosca** [comment]
Thanks Maggie.  There must have been an out-of-bounds error or something.  That diagnostic was implemented by @sdeastham a long time ago but I am not sure if recent version updates have broken it.  In any case, it might be easier now to compute hourly max ozone in postprocessing (you can save hourly output in the netCDF diagnostics just for the surface level and whatever lon/lat range you need, and then use a Python script to compute the max values).

Good to know that this works!  I'll go ahead and close out this issue.  Feel free to reopen (or to submit another issue) if you are still having problems.
