### ISSUE TITLE
[BUG/ISSUE] Ozone & OH disappear in tropchem runs

### ISSUE THREAD

**Issue by jennyfisher** [geoschem/geos-chem#317]
## Describe the bug
I'm running v12.8.0 out of the box. When I run the tropchem mechanism, something is going seriously wrong. After a 1-day test run, ozone disappear over the continents, and OH as reported in the log file is also virtually gone. I have replicated this behaviour using both MERRA2 (year 2008) and GEOS-FP (year 2014) simulations at 2x2.5.

Here is a map of surface-level ozone concentrations after a 1-day simulation in tropchem:
<img width="863" alt="image" src="https://user-images.githubusercontent.com/1236416/82401629-a068ff00-9a9d-11ea-8b22-63fa8030210d.png">

And the same test but with standard:
<img width="858" alt="image" src="https://user-images.githubusercontent.com/1236416/82401570-7f081300-9a9d-11ea-9094-ca6f0400bc83.png">

(Note that if I look too closely at the standard run it also looks a bit funny, i.e. lower over eastern China & Europe than surrounding areas, but I have only run one day with no spin-up so expecting that would look ok with a longer run).

OH from the log file using tropchem:
```
===============================================================================
 Mass-Weighted OH Concentration
 Mean OH =   1.269372877018295E-002  [1e5 molec/cm3]
===============================================================================
```

## To Reproduce
GEOS-Chem v12.8.0 out of the box, run at 2x2.5. With MERRA-2 I ran 20080101-20080102. When I tested for reproducibility with GEOS-FP, I ran 20140101-20140102. I made a small change to HEMCO_Config.rc to turn off the offline emissions and turn on the online versions as I didn't have all the files downloaded, but this was the same between tropchem and standard. (I also tried with offline soil NOx instead and saw the same behaviour).

## Expected behavior
Ozone and OH should not go to zero...

## Error messages
None

## Required information
 - GEOS-Chem version you are using 12.8.0
 - intel-compiler/2019.3.199
 - netcdf/4.7.1
 - Gadi cluster
 - "out of the box" code

## Input and log files attached
[bug.zip](https://github.com/geoschem/geos-chem/files/4654532/bug.zip)

**Comment by msulprizio** [comment]
Are you using the same restart files to initialize your tropchem and standard simulations? I notice from your log file that many species are not found in the restart file and are therefore initialized with background concentrations (typically 1e-20). Is that the same case in your standard run?

For what it's worth, I happen to have run several benchmarks with 12.8.0 for the standard mechanism, standard mechanism w/ 47 levels, and tropchem mechanisms to evaluate the differences and haven't seen this behavior yet. I've been running for July 2013 using 4x5 GEOS-FP. Using those simulations and yours, we should be able to figure this out.

**Comment by jennyfisher** [comment]
Hi Melissa,

I’m running with the default restart file that ships with the data directories in both cases. I had a quick look at it and ozone looked ok in it, so I doubt it is to blame. 

Cheers,
Jenny

**Comment by yantosca** [comment]
Hi Jenny... can you try with a different compiler (gfortran)?  Wonder if it's a compiler issue.

**Comment by jennyfisher** [comment]
Not sure - I will look into it when I start work today (we are fairly limited in options on the new supercomputer). But FYI I’ve been using the same compiler for several other flavours of v12 and for standard v12.8.0 without seeing the issue.

**Comment by jennyfisher** [comment]
Just checked - we don't have access to gfortran, only intel compilers.

**Comment by jennyfisher** [comment]
Also I can confirm I get basically the same behaviour using the 4x5 simulation (just slightly higher values, presumably because fewer time steps to get it quite as low).
<img width="878" alt="image" src="https://user-images.githubusercontent.com/1236416/82497417-8aa51980-9b31-11ea-9aba-299560b114c7.png">
```
===============================================================================
 Mass-Weighted OH Concentration
 Mean OH =   0.950497834246970       [1e5 molec/cm3]
===============================================================================
```

Melissa, can you share the restart file you are using so that I can test the impact of that?

**Comment by jennyfisher** [comment]
Actually I can confirm that the restart file isn't responsible, and the problem must be somewhere in the tropchem part of the code. I ran with the code compiled for tropchem but with all other settings as usual for standard (including restart file) and saw the same behaviour.

**Comment by jennyfisher** [comment]
Hi again,

I ran with:
```
  BOUNDS       : y
  DEBUG        : y
  FPE          : y
```
and there were no errors but the ouptut looks normal again. So I guess this is something to do with the compiler...? As I turned all three settings on at once, I am not sure which one fixed the problem - but it makes the simulation VERY slow so I am hoping to not have to continue running with these one. Is there a reason why the tropchem simulation would react so differently than standard with the same compiler?

We don't have many options when it comes to compilers:
- intel-compiler/2019.3.199
- intel-compiler/2019.4.243
- intel-compiler/2019.5.281
- intel-compiler/2020.0.166
- intel-compiler/2020.1.217  
Have you used any of these versions successfully?

**Comment by jennyfisher** [comment]
One final piece of information before I call it a day... when I compile with FPE=y and the runs go smoothly, I do get a number of Rosenbrock errors:
```
 Forced exit from Rosenbrock due to the following error:
 --> Step size too small: T + 10*H = T or H < Roundoff
 T=   1058.52995927636      and H=  7.310059819825918E-013
 ### INTEGRATE RETURNED ERROR AT:          101          73          14
```
I definitely don't understand this part of the code, but I wonder if the difference could be related to the fact that different tolerances are set for UCX and non-UCX runs in flexchem_mod.f90:
```
    ! Relative tolerance
    IF ( Input_Opt%LUCX  ) THEN 
       ! UCX-based mechanisms
       !RTOL      = 2e-2_dp
       !RTOL      = 1e-2_dp
       RTOL      = 0.5e-2_dp
    ELSE 
       ! Non-UCX mechanisms
       RTOL      = 1e-2_dp
    ENDIF
```

**Comment by yantosca** [comment]
Thanks for the feedback.  I suspect an optimization issue in your compiler.  It could be that they chagned the default behavior of certain compiler flags in the newest ifort versions.  My guess is that the optimization level -O2 (which is the default) does something different than it did before.  

The options do the following:

- The `BOUNDS=y` flag is probably the most time-sucking option. That checks for the out-of-bounds errors which can slow down the code.
- Using `DEBUG=y` turns off optimization and executes the code as it is written (i.e. no unrolling loops, etc)... this sets `-g -O0` flags.  This will definitely make the code execute more slowly.
- Using `FPEX=y` looks for floating-point exceptions, which this turns on `-fpe0 -ftrapuv` flags. 
  - The `-fpe0` flag will halt if any floating point exception is encountered.  Unlike the default `-fpe3`, which will convert denormal values to zeros and then continue running.   Perhaps this is the root of the issue.
  - The `-ftrapuv` flag will set all uninitialized values to a large number, to make it easier to find uninitialized values in debugging.

The most recent Intel compiler that we have locally is the 19.0.5.281 build:
```
[holylogin02 ~]$ ifort -V
Intel(R) Fortran Intel(R) 64 Compiler for applications running on Intel(R) 64, Version 19.0.5.281 Build 20190815
Copyright (C) 1985-2019 Intel Corporation.  All rights reserved.
```

Have you been using this compiler?  If not let us know if it works on your end with the default settings.  I believe that we haven't noticed any problems with ifort 19.0.5.281 lately.

Also: is your compiler "wrapped" with options?  In other words, is "ifort" an alias for ifort + certain compiler options.  I remember on the old cluster the sysadmins always set certain options, which may or may not conflict with GEOS-Chem's options.  In any case, if you have more than one compiler option specified in the ifort command, the last option takes precedence.  I would ask your sysadmins.

**Comment by jennyfisher** [comment]
Thanks! I have now tested with compiler versions 2019.5.281 (I think that's the same as yours) and 2020.1.217 (our newest option) and both worked! Slightly disconcerting that a different version of the same compiler can cause a change that catastrophic... In any case glad we have found it. I will stick with 2019.5.281 if that's what you guys are using.

It might be worth a note somewhere to warn others against 2019.3.199. Speaking of which should we have a wiki page on compiler versions that we know work and those that we know are problematic?

**Comment by yantosca** [comment]
Hi Jenny.  Thanks for the feedback.  We do have some information on the wiki about supported compiler versions under our [Guide to compilers for GEOS-Chem](http://wiki.geos-chem.org/Guide_to_compilers_for_GEOS-Chem) wiki page.  In particular see:

- [Intel Fortran compiler: Compiler versions that have been tested with GEOS-Chem](http://wiki.seas.harvard.edu/geos-chem/index.php/Intel_Fortran_Compiler#Intel_Fortran_Compiler_versions_that_have_been_tested_with_GEOS-Chem)
- [Known issues caused by compiler bugs](http://wiki.seas.harvard.edu/geos-chem/index.php/Known_issues_caused_by_compiler_bugs)

To be sure, some of this information needs to be updated (we rely on user feedback for this). I'll add a note about the 2019.3.199 version.

I'll go ahead and close out this issue.
