### ISSUE TITLE
[QUESTION] Issue with creating run directories

### ISSUE THREAD

**Issue by tejendrapsingh** [geoschem/geos-chem#321]
Hi!
I am new to GEOS-CHEM.
I am using git bash on my windows 10 machine for setting up and running GEOS-CHEM. I am trying to execute **gcCopyRunDirs**. It is constantly throwing this error *"does not exist!  Exiting./gcgrid"*. My external data is stored on the G drive, and I have appropriately edited the GCGRID_ROOT to *"/g/GEOS-CHEM/gcgrid"*, and DATA_ROOT to *{GCGRIDROOT}/data/ExtData* in the **CopyRunDirs.input** file. 
How do I resolve this? Any help is highly appreciated. Thanks.

**Comment by yantosca** [comment]
Thanks for writing.  We don't have a lot of experience with GEOS-Chem on Windows machines.

In git bash, I think that /c should get you to the root hard disk folder, and /g should probably get to the external drive.  Maybe there is an issue with that being found.

You can also try using cygwin64 as your Linux-like environment on Windows.  In that case you would use /cygdrive/g/gcgrid... to reach an external drive.

Another thing you could try is to use virtualbox to run a Linux virtual machine on your system.  That might be the easiest thing for you to do.  We unfortunately cannot assist with supporting GEOS-Chem on Windows as it really is intended for use on Linux systems (HPC clusters and the AWS cloud).

**Comment by tejendrapsingh** [comment]
Thanks for the reply.
Realizing that I won't be able to make much progress on windows machine, I am now using CentOS8 Unix machine.
However, I am stuck with the specification of the software libraries. Specifically, there are no *modulefiles* in the */usr/share/Modules/modulefiles*. So, when I do something like `module load netcdf/4.7.0`, I get the following error `ERROR: Unable to locate a modulefile for 'netcdf/4.7.0'`.
How do I write the modulefiles?
Thanks.

**Comment by yantosca** [comment]
You can ask your sysadmin where to find software libraries on your system.  Centos8 should come with at least a version of gcc/gfortran and Git.  You also may have a netCDF library installation too -- netCDF is very common on HPC systems.

If your system has no other libraries, then you (or your sysadmin) can build the latest gfortran compiler and other required libraries using Spack.  You can see my tutorials on the GEOS-Chem Youtube channel for instructions on how to do this.

- [Spack tutorial #1: Building Gfortran 9.2.0](https://www.youtube.com/watch?v=7eMLYKLK9wY)
- [Spack tutorial #2: Building libraries](https://www.youtube.com/watch?v=6tGCD3zQQW0)

**Comment by tejendrapsingh** [comment]
Thanks. 
I will look these up.
I try running the simulations for one month but got the following error. `f77: command not found` So, I need to figure out the computational environment.
Not closing for the time being as I am sure there are issues waiting for me still.

**Comment by yantosca** [comment]
BTW, we have info on that error on our GEOS-Chem wiki:

http://wiki.geos-chem.org/Compile-time_warnings_and_errors#f77:_command_not_found

This is part of our [Guide to GEOS-Chem error messages](http://wiki.seas.harvard.edu/geos-chem/index.php/Guide_to_GEOS-Chem_error_messages), which goes into more depth about some common errors and how to resolve them.

**Comment by tejendrapsingh** [comment]
Thanks.
Yes, I have looked at that.

**Comment by tejendrapsingh** [comment]
See [this](https://github.com/geoschem/geos-chem-cloud/issues/35#issuecomment-633162315).
Thanks.

**Comment by tejendrapsingh** [comment]
Hi!
So, I could compile by manually writing the contents of the `init` file to the terminal.
However, after successful compilation, when I am running the `.geos` I am getting the following error.
As a background, I have not downloaded all the data that is there in the `[HEMCO](http://geoschemdata.computecanada.ca/ExtData/HEMCO/)` directory. I just downloaded the `PARANOX` and `LIGHTNOX`  sub-directories data. 

```
 Error in ReadList_Read called from hco_run
===============================================================================
GEOS-Chem ERROR: Error encountered in "HCO_Run"!
 -> at HCOI_GC_Run (in module GeosCore/hcoi_gc_main_mod.F90)

THIS ERROR ORIGINATED IN HEMCO!  Please check the HEMCO log file for 
additional error messages!
===============================================================================

===============================================================================
GEOS-Chem ERROR: Error encountered in "HCOI_GC_Run"!
 -> at Emissions_Run (in module GeosCore/emissions_mod.F90)
===============================================================================

===============================================================================
GEOS-CHEM ERROR: Error encountered in "Emissions_Run", Phase 0

This error can indicate a missing file. Please check the HEMCO log file for 
additional error messages!

STOP at  -> at GEOS-Chem (in GeosCore/main.F90)
===============================================================================

```

**Comment by yantosca** [comment]
You should look at the HEMCO.log to see which files are missing.  

You should do a dry-run before running a GEOS-Chem simulation.  That will make sure all  necessary data for your simulation and date range is downloaded.  Please see:

 - http://wiki.geos-chem.org/Downloading_data_with_the_GEOS-Chem_dry-run_option

**Comment by tejendrapsingh** [comment]
Hi. 
Thanks for the reply.
I did a dry-run before running the simulation. I downloaded the necessary data for the selected date range. But, I am getting this error. 
Any help is appreciated. Thanks a lot. 

`HEMCO: REQUIRED FILE NOT FOUND /mnt/win/GEOS-CHEM/gcgrid/data/ExtData/HEMCO/OFFLINE_LIGHTNING/v2019-01/GEOSFP/2019/FLASH_CTH_GEOSFP_0.25x0.3125_2019_01.nc4`

**Comment by lizziel** [comment]
Hi @tejendrapsingh. Check to see if file FLASH_CTH_GEOSFP_0.25x0.3125_2019_01.nc4 exists in directory /mnt/win/GEOS-CHEM/gcgrid/data/ExtData/HEMCO/OFFLINE_LIGHTNING/v2019-01/GEOSFP/2019/.

**Comment by lizziel** [comment]
Actually, I just checked our data directory and we do not have offline lightning available for 2019. There is a similar issue on GitHub for 2014, another year without offline lightning data. See https://github.com/geoschem/geos-chem/issues/76 for the suggestions on how to proceed.

**Comment by tejendrapsingh** [comment]
Hi.
Thanks for the help.
So, let me just clarify.
I need to download the `MERRA-2` data and specify the path to the directory where this is saved for lightning fields in the `HEMCO_Config.rc` file, right?

**Comment by tejendrapsingh** [comment]
So, to put this into context. I am trying to get hold of the PM2.5 daily measurements over the Indian sub-continent. I am following the methods in [van Donkelaar et al (2010)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2898863/). I am posting the relevant section on their methods below. I aim to get hold of the _eta_[η] values for the period spanning April 2019 to March 2020. 
If anyone can help in this regard, then I would appreciate it. 

> Estimating PM2.5 from AOD
> Estimating ground-level concentrations of dry 24-hr PM2.5 (micrograms per cubic meter) from satellite observations of total-column AOD (unitless) requires a conversion factor that accounts for their spatially and temporally varying relationship:
>                       **PM_2.5 = η x AOD**
> η is a function of the factors that relates 24-hr dry aerosol mass to satellite observations of ambient AOD: aerosol size, aerosol type, diurnal variation, relative humidity, and the vertical structure of aerosol extinction (van Donkelaar et al. 2006). Following the methods of Liu et al. (2004, 2007) and van Donkelaar et al. (2006), we used a global 3-D CTM [GEOS-Chem; geos-chem.org; see Supplemental Material (doi:10.1289/ehp.0901623)] to calculate the daily global distribution of η.
> 
> The GEOS-Chem model solves for the temporal and spatial evolution of aerosol (sulfate, nitrate, ammonium, carbonaceous, mineral dust, and sea salt) and gaseous compounds using meteorological data sets, emission inventories, and equations that represent the physics and chemistry of atmospheric constituents. The model calculates the global 3-D distribution of aerosol mass and AOD with a transport time step of 15 min. We applied the modeled relationship between aerosol mass and relative humidity for each aerosol type to calculate PM2.5 for relative humidity values that correspond to surface measurement standards [European Committee for Standardization (CEN) 1998; U.S. Environmental Protection Agency 1997] (35% for theUnited States and Canada; 50% for Europe). We calculated daily values of η as the ratio of 24-hr ground-level PM2.5 for a relative humidity of 35% (U.S. and Canadian surface measurement gravimetric analysis standard)and of 50% (European surface measurement standard) to total-column AOD at ambient relative humidity. We averaged the AOD between 1000 hours and 1200 hours local solar time, which corresponded to the Terra overpass period. We interpolated values of η from 2° × 2.5°, the resolution of the GEOS-Chem simulation, to 0.1° × 0.1° for application to satellite AOD values.

**Comment by yantosca** [comment]
Dear @tejendrapsingh, your question about AOD is probably better suited to the Aerosols Working Group.  You can send an email to geos-chem-aerosols@g.harvard.edu for assistance.  The GEOS-Chem Support Team can only assist with coding/computer issues.

**Comment by tejendrapsingh** [comment]
Thanks. I will mail them.

**Comment by yantosca** [comment]
In answer to your prior question, you should do a GEOS-Chem dry run simulation and then use the download_data.py script to get any data files that you don't have locally.

I will close out this issue for now, as your AOD question is a research question, which is something the GCST can't answer.  I see that you have gotten some responses from the Aerosols Working Group members, which is great.
