### ISSUE TITLE
[FEATURE REQUEST] Use consistent OH fields for all specialty simulations

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#330]
Jenny Fisher raised a concern that different specialty simulations are using different versions of OH fields by default. Many simulations use GEOS-Chem v5 OH fields, while mercury uses v7, and tagCO uses v9.  The fields have different magnitudes and also different seasonal cycles. 

For the GEOS-Chem 13.0.0 release, will be running the a 10-year full-chemistry benchmarks for the stratosphere. The GEOS-Chem Steering Committee has requested we can save monthly, 3D OH fields for each year to give users year-specific OH as well as develop a climatology. Prior to the GEOS-Chem 13.0.0 release, the HEMCO_Config.rc files for all specialty simulations should be updated to use these new fields. Users will still have the option to revert to older fields if desired.

**Comment by msulprizio** [comment]
The 10-year benchmark for 13.0.0 is in progress. We will use the output from the last year of this simulation to update the oxidant fields for specialty simulations. This will be completed during the 13.0.0 release candidate period.

**Comment by yantosca** [comment]
Cross-referencing issue #331, which describes creating output from the 10-yr benchmarks for 13.0.0.

**Comment by msulprizio** [comment]
The HEMCO_Config.rc files for all specialty simulations have been updated to use OH fields from the 10-year benchmark with GEOS-Chem Classic 13.0.0. This update can currently be found in the `dev/13.0.0-final` branch and will be included in the final 13.0.0 release.
