### ISSUE TITLE
[QUESTION] Adding New Module in GEOS-Chem

### ISSUE THREAD

**Issue by debatoshpartha** [geoschem/geos-chem#335]
Hello, this is a **followup question** of a previously opened issue. 

I have tried adding my deposition subroutines to hcoi_gc_main_mod.F90 and then tried calling them from my HEMCO emission module but still got no luck as HEMCO modules cannot read GeosCore modules due to the compilation order.

Now I am trying to write my emission module within GeosCore (in reference with the mercury_mod.F/EMISSMERCURY and land_mercury_mod.F) so that my GeosCore emission module can use my geoscore deposition module. I understand I may still have to pass my emission inventories to HEMCO through hcoi_gc_main_mod.F90. I assume (kindly correct me if I'm wrong) calling my emission module by "USE" in hcoi_gc_main_mod.F will automatically be passed to HEMCO. I'd like to know if this is the right way to proceed. If so, can you give me some heads up/suggestion in adding geoscore emission module in hcoi_gc_main_mod.F and how to pass them to HEMCO later?

Thank you in advance.

_Originally posted by @yantosca in https://github.com/geoschem/geos-chem/issues/315#issuecomment-631696810_

**Comment by yantosca** [comment]
Thanks for writing.  I am still unclear on a few things.  Are you using the mercury simulation or a different simulation?  Can you post the relevant files that you are trying to modify here (you can drag and drop to the window.  You will also need to add .txt to the file names so that Github will recognize them).

**Comment by debatoshpartha** [comment]
Hello Mr. Yantosca, 

I am using mercury simulation as a reference to my simulation as I believe they are quite identical. I am only developing codes for the emission of NOx from snow (which is similar to Hg emission from snow). I am attaching 3 codes here that I've revised for NOx simulation. Could you please tell me how to pass them to HEMCO for adding them to emission inventory? 

[land_snownox_mod.F90.txt](https://github.com/geoschem/geos-chem/files/4724809/land_snownox_mod.F90.txt)
[snownox_mod.F90.txt](https://github.com/geoschem/geos-chem/files/4724810/snownox_mod.F90.txt)
[dep_nitrate_mod.F90.txt](https://github.com/geoschem/geos-chem/files/4724811/dep_nitrate_mod.F90.txt)

**Comment by debatoshpartha** [comment]
Hello Mr. Yantosca, 

I have shared my revised Code.12.7.0 with you through one drive that's been successfully compiled. However, I am trying to run a 2x2.5 geosfp simulation and unfortunately the simulation isn't running after sometime. I have attached the HEMCO.log and simulation log file here for you to take a look.  Kindly suggest what should I do to run the simulation successfully. 

[runGC_newcode.log.txt](https://github.com/geoschem/geos-chem/files/4842688/runGC_newcode.log.txt)
[HEMCO.log.txt](https://github.com/geoschem/geos-chem/files/4842689/HEMCO.log.txt)

[NB: Following modules are revised by me, 

1. GeosCore/dep_nitrate_mod
2. GeosCore/land_snownox_mod
3. GeosCore/snownox_mod
4. Header/state_chm_mod
5. Header/input_opt_mod
6. Header/species_database_mod
7. Header/species_mod
8. Header/state_diag_mod
9. Header/state_met_mod
10. GTMM/doNITDeposition_mod
11. GTMM/loadNITDeposition_mod
12. GeosCore/hcoi_gc_diagn_mod @L1382
13. GeosCore/hcoi_gc_main_mod
14. GeosCore/gamap_mod
15. GeosCore/gc_environment_mod
16. HEMCO/Extension/hcox_state_mod ]

**Comment by msulprizio** [comment]
@debatoshpartha Are you still experiencing problems or have you been able to resolve this issue?

**Comment by yantosca** [comment]
I am going to close out this issue due to lack of recent activity.  If you are still experiencing problems, feel free to open a new issue.
