### ISSUE TITLE
[QUESTION] Setting up a run with only EDGAR emissions

### ISSUE THREAD

**Issue by pkasibhatla** [geoschem/geos-chem#343]
How should I set the REGIONAL INVENTORIES, GLOBAL INVENTORIES, and SHIP EMISSIONS switches in HEMCO_config.rc file for a GC 12.8.2 run if I want to only use EDGARv4.3 without overwriting with regional emission inventories? It is not clear to me if should add CEDS VOC, turn off other NH3 inventories, etc.

**Comment by msulprizio** [comment]
You can simply turn off the regional emissions inventories and CEDS and turn on EDGAR at the top of HEMCO_Config.rc.

# ----- REGIONAL INVENTORIES ----------------
    --> APEI                   :       false
    --> NEI2011_HOURLY         :       false
    --> NEI2011_MONMEAN        :       false
    --> MIX                    :       false
    --> DICE_Africa            :       false
# ----- GLOBAL INVENTORIES ------------------
    --> CEDS                   :       false
    --> EDGARv43               :       true
    --> HTAP                   :       false
    --> GEIA_NH3               :       true
    --> SEABIRD_NH3            :       true
    --> POET_EOH               :       true
    --> TZOMPASOSA_C2H6        :       true
    --> XIAO_C3H8              :       true
    --> LIANG_BROMOCARB        :       true
    --> ORDONEZ_IODOCARB       :       true
    --> AEIC                   :       true
    --> DECAYING_PLANTS        :       true
    --> AFCID                  :       true
# ----- SHIP EMISSIONS ----------------------
    --> SHIP                   :       true
    --> CEDS_SHIP              :       true
    --> HTAP_SHIP              :       false
    --> ICOADS_SHIP            :       false
    --> ARCTAS_SHIP            :       false
    --> CORBETT_SHIP           :       false
    --> NEI2011_SHIP_HOURLY    :       false
    --> NEI2011_SHIP_MONMEAN   :       false
```

Turning on EDGAR automatically enables the use of TRASH emissions and CEDS VOC emissions to account for emissions missing from EDGAR. You may also choose to turn off `POET_EOH`, `TZOPMA_C2H6`, and `XIAO_C3H8` to use the VOC emissions from CEDS instead (as is done for the rest of VOCs when using EDGAR). For ship emissions, CEDS is the default global inventory. If you choose turn off `CEDS_SHIP`, you may want to consider turning on the older `ICOADS_SHIP` and `ARCTAS_SHIP` inventories.

In HEMCO_Config.rc, you can see all of the fields included when turning on EDGARv42 by examining the entries between `(((EDGARv43 .... )))EDGARv43`:

```
#==============================================================================
# --- EDGAR v4.3 ---
#
# %%% NOTE: This is an optional inventory. You may select either CEDS, EDGAR,
#  or HTAP for the global base emissions %%%
#
# The following emissions are not included in EDGAR and will be added:
#  * Wiedinmyer et al. (2014) global trash emissions
#  * CEDS VOC emissions
#
# Aviation and shipping emissions from EDGAR are not included here.
# We also do not include the following sources:
#  - Soil emissions of NOx (SOL). These emissions are calculated via the
#    SoilNOx extension.
#  - Open biomass burning (AWB). These emissions are obtained from
#    GFED, QFED, FINN, or GFAS.
#==============================================================================
(((EDGARv43
0  EDGAR_BCPI_POW $ROOT/EDGARv43/v2016-11/EDGAR_v43.BC.POW.0.1x0.1.nc  emi_bc  1970-2010/1/1/0 C xy kg/m2/s BCPI 1201/70         1 2
...

#==============================================================================
# --- NAP ANTHROPOGENIC EMISSIONS: approximate from EDGAR BENZ ---
#
# NOTE: Although this data comes from EDGAR version 2, we are storing it
# in the EDGARv42 data path for convenience.
#==============================================================================
0 EDGAR_NAP $ROOT/EDGARv42/v2015-02/VOCv2/EDGAR2_1985_FF_IND.1x1geos.nc BENZ 1985/1/1/0 C xy kgC/m2/s NAP 80/81/82 1 2

#==============================================================================
# --- Wiedinmyer et al. (2014) global trash emissions to be added to EDGAR ---
#==============================================================================
0 TRASH_CO    $ROOT/TrashEmis/v2015-03/TrashBurn_v2_generic.01x01.nc  CO    2008/1/1/0 C xy kg/m2/s  CO    -     1 2
...

#==============================================================================
# --- CEDS VOC emissions to be added to EDGAR ---
#==============================================================================
# NOTE: EOH files in CEDS/v2018-08 are actually VOC1 (total alchohols) and are split into MOH, EOH, ROH here
0 CEDS_MOH_AGR    $ROOT/CEDS/v2018-08/$YYYY/EOH-em-anthro_CMIP_CEDS_$YYYY.nc           EOH_agr           1750-2014/1-12/1/0 C xy kg/m2/s MOH   26/90     1 5
0 CEDS_EOH_AGR    -                                                                    -                 -                  - -  -       EOH   26/91     1 5
0 CEDS_ROH_AGR    -                                                                    -                 -                  - -  -       ROH   26/92     1 5
...

)))EDGARv43
```

**Comment by pkasibhatla** [comment]
Thanks Melissa! One quick question - was there some reason for the decision not to use the EDGARv43 VOC emissions even when using EDGARv43 for other species like NOx?

**Comment by msulprizio** [comment]
Using CEDS VOCs came in as a recommendation from the Emissions Working Group when we [retired old emissions inventories](http://wiki.seas.harvard.edu/geos-chem/index.php/Issues_now_resolved_in_GEOS-Chem_12#Retire_obsolete_emission_inventories). Eloise Marais wrote:

>[Trash burning is] not mentioned in the Crippa (2018) EDGAR v4.3.2 paper. Perhaps then if EDGAR is selected, it should include CEDS VOCs and Wiedinmyer (2014) TRASH for NOx, SOx, CO, BC and OC. 

It occurs to me now that the current setup may be problematic. I think Eloise may have meant to only include CEDS VOC emissions from the `WST` (waste disposal and handling) sector, and not for all sectors as is currently the case in HEMCO_Config.rc. I will follow up with Eloise to confirm and report back here.

**Comment by eamarais** [comment]
The HEMCO directory includes total NMVOCs emissions and EDGAR does provide speciated NMVOCs, but these haven't been customized for input to GEOS-Chem. Most accessible solution was to use CEDS NMVOCs.

**Comment by msulprizio** [comment]
Thanks for clarifying, @eamarais!
