### ISSUE TITLE
[BUG/ISSUE] RRTMG stratospheric aerosol shortwave forcing is non-physical

### ISSUE THREAD

**Issue by sdeastham** [geoschem/geos-chem#346]
## Describe the bug
When running GEOS-Chem with RRTMG enabled, the shortwave forcing attributed to stratospheric aerosol is positive (as calculated using NetCDF diagnostics, and quantifying stratospheric aerosol forcing as "baseline flux" - "strat aerosol flux" under all-sky conditions). This does not agree with observations, and is likely due to a bug in RRTMG's interface code.

## To Reproduce
Compile and run GEOS-Chem with RRTMG for 1 time step, storing out both `RadAllSkySWTOA_BA` and `RadAllSkySWTOA_ST` in `HISTORY.rc`. Take the `BA` value and subtract the `ST` value to get the forcing. The forcing is positive.

## Expected behavior
Shortwave forcing at TOA for stratospheric aerosol should be negative, as stratospheric aerosol tends to scatter incoming radiation.

## Error messages
N/A

## Required information
Please include the following:
 - GEOS-Chem version: 12.8
 - ifort 19
 - Harvard Odyssey/Cannon cluster
 - Unmodified code

## Additional context
A solution to this will be posted shortly as a pull request.

**Comment by lizziel** [comment]
See also pull request https://github.com/geoschem/geos-chem/pull/347.
