### ISSUE TITLE
[FEATURE REQUEST] Remove "Sav" from State_Chm array names

### ISSUE THREAD

**Issue by lizziel** [geoschem/geos-chem#349]
The original names were often kept in the past when moving several module variables to the arrays in the State_Chm object. Several of them contain the suffix "Sav" to indicate the arrays were saved within the modules. It is no longer necessary to have this in the name for State_Chm arrays, and the array names could be updated to be more apt.

**Comment by yantosca** [comment]
This issue is now resolved by commit 9f70b9f6ad43bf3406b71277db6955a05e11cf30.

**Comment by yantosca** [comment]
Commit 9f70b9f6ad43bf3406b71277db6955a05e11cf30 has been discarded.  We will wait until the merging of the CESM line of development into 13.0.0 before making this update.

**Comment by msulprizio** [comment]
This is now resolved in https://github.com/geoschem/geos-chem/commit/94d6dfc80ca6d0dcd707e31b8d3f9b4f292db290.
