### ISSUE TITLE
[QUESTION] Adding non-tracer diagnostics to planeflight output

### ISSUE THREAD

**Issue by JFBrewer** [geoschem/geos-chem#351]
Hi GEOS-Chem team,

I'm trying to look at aerosol data in the model and it would be very helpful for me if I could output the "PM25", "TotalOA", and "AerMassASOA" diagnostics from the Aerosol and AerosolMass collections in the planeflight diagnostic output. However, tests suggest that I cannot simply write those diagnostic names into the planeflight files - when I try, the run fails and throws an error that says "ERROR: invalid species! Species AerMassASOA not found!". I assume because those diagnostics are for the NETCDF collections and the planeflight menu talks to the bpch collections - is that correct? What would it take to port these aerosol tracers into the planeflight system?

Jared

**Comment by yantosca** [comment]
The planeflight diagnostic is separate from (and predates) the HISTORY diagnostics.  My guess is that you would have to add similar code into planeflight_mod.F90 to compute the SOA diagnostics as is in aerosol_mod.  That is a bit of a mess in the current code.  We hope to clean that up eventually.

**Comment by yantosca** [comment]
Closing out this issue for now.  Please submit a new issue if you are still having problems.  There will be some fixes for the planeflight diagnostic in 13.0.0.
