### ISSUE TITLE
Adding a single-body reaction into the KPP Tropchem.eqn file

### ISSUE THREAD

**Issue by RuochongXu** [geoschem/geos-chem#352]
Hi GEOS-Chem team:

  I would like to add a new single-body reaction into the Tropchem.eqn file in the form below:
  A = B + C +D
  I found the guide on the page of FlexChem to add a two-body reaction using rate calculated from function GCARR based on Arrhenius law in gckpp.kpp. I wonder whether it is appropriate to use the same method for single-body reaction if the reaction rate is based on Arrhenius law.
  I found a reaction in the file, whose form is similar to what I would like to add:
  DHPCARP = RCOOH + CO + OH :   GCARR(2.90E+07, 0.0E+00, -5300.0);   {2017/07/14; Crounse2012; KRT,JAF,CCM,EAM,KHB,RHS}
  I want to make sure because this single-body reaction is important in my study.
  Thanks.

Ruochong Xu

**Comment by yantosca** [comment]
Thanks for writing.  We would recommend for you to try it and see if it works.  If not, then let us know.

You can write a new rate-law function if needed for KPP.

**Comment by msulprizio** [comment]
I will close out this issue for now, but please feel free to comment and reopen if you run into any issues. We'd also recommend you contact the [Chemistry Working Group ](http://wiki.seas.harvard.edu/geos-chem/index.php/Chemistry_Working_Group) with any science questions. May members of that group have experience with writing and updating functions in KPP.
