### ISSUE TITLE
[BUG/ISSUE] Missing metadata for various ND51 tracers

### ISSUE THREAD

**Issue by jennyfisher** [geoschem/geos-chem#353]
## Describe the bug
This is related to issue #260. It seems quite a lot of the various metadata fields for ND51 diagnostics were removed from gamap_mod.F and this creates problems for reading this files with IDL/GAMAP.

In my case, I've had issues with the following tracers 511 (boxheights) and 512 (pressure edges). These are not linked to the `TIME-SER` diagnostic info but rather the `PEDGE-$` and `BXHGHT-$` diagnostics. Those are no longer written to diaginfo.dat and tracerinfo.dat, and so when reading the file using GAMAP, they don't show up at all. I can temporarily "fix" the problem by copying the relevant info from an old version of tracerinfo.dat and diaginfo.dat into the new versions written by the model.

I imagine there are several other tracers in this boat.

Fix would be to re-instate the relevant code in gamap_mod.f until these diagnostics are replaced.

(FYI, I rarely use GAMAP, but it is still the easiest way to convert these files to a COARDS-compliant netcdf file. When I use the bpch_to_nc script that ships with xbpch a lot of information is missing, including the time dimension, which would require a lot of work to recreate!)

## To Reproduce

**Compilation commands**
Follow out of the box instructions.

**Run commands**
In input.geos, turn on ND51 including tracers 511 and 512 (for example). Otherwise run as normal.

## Expected behavior
Metadata for all possible ND51 tracers written to tracerinfo.dat and diaginfo.dat.

## Error messages
None.

## Required information
 - GEOS-Chem version 12.8.2
 - Compiler ifort 19.0.5.281
 - netCDF 4.7.1
 - Gadi cluster
 - "out of the box" code

## Input and log files to attach
I don't think these are needed in this case, but let me know if you would still like them.

**Comment by msulprizio** [comment]
The information relevant for the timeseries diagnostics has been restored in gamap_mod.F90. See commit 11585ed13a3ae290f23b261b33d6128c64b1e943. This fix will be included in 12.9.0.

In the meantime, you can use an old tracerinfo.dat and diaginfo.dat or add the missing entries to those files as a workaround as suggested in https://github.com/geoschem/geos-chem/issues/260.
