### ISSUE TITLE
[BUG/ISSUE] Aerosol-only simulation does not work with 12.9.0

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#354]
In 12.9.0, ISORROPIA expects HCl as a species; however HCl is not included in the aerosol simulation since it is a gas-phase species, so that simulation crashes. These updates came in with the halogen chemistry updates. In `isorropiaII_mod.F90` other gas-phase species like HNO3 utilize code to check if it's a full-chemistry or aerosol-only simulation. If it's a full chemistry simulation, ISORROPIA takes the online species concentration from `State_Chm%Species`. If it's an aerosol-only simulation, ISORROPIA gets offline fields read in via HEMCO. Updates to do the same for HCl have been added to the dev/12.9.0 branch, however we do not currently have HCl fields archived for use as input in aerosol-only simulations. We will save out these fields as part of the 1-year benchmark for 12.9.0 and update the HEMCO_Config.rc file for aerosol-only simulations in 13.0.0 to use those archived fields.

**Comment by msulprizio** [comment]
The 10-year benchmark for 13.0.0 is in progress. From this simulation, we will be archiving monthly species concentrations. These fields can be used to restore the aerosol-only simulation and will be made available prior to the official 13.0.0 release in late January 2021.

**Comment by yantosca** [comment]
This update will be resolved once we have the climatology fields from the 10 year benchmarks, as described in feature request #331.

**Comment by msulprizio** [comment]
This is now resolved in the `dev/13.0.0-final` branch. Updates included reading fields from the GEOS-Chem 13.0.0 10-year benchmark. Several fixes were also needed in the code to restore this simulation as described in commit https://github.com/geoschem/geos-chem/commit/5099c90599747226a7de36e573c6611992b9970c.
