### ISSUE TITLE
[QUESTION] Constructing MERRA-2 pressure levels from Ap and  Bp 

### ISSUE THREAD

**Issue by czr137** [geoschem/geos-chem#358]
I've been browsing the Geos-Chem wiki as I'm having a problem in reconciling the differences in the MERRA-2 Analyzed pressure level data (inst6_3d_ana_Np) and the MERRA-2 Analyzed model level data (inst6_3d_ana_Nv).

I'm trying to reconstruct the geopotential heights from the model level. I'm using a set of equations that I've successfully applied to the ECMWF hybrid model levels. However, when I compare the MERRA-2 geopotential computed values with the values in the MERRA-2 pressure level data, they do not match, and I see shadows of landmases in the data.

For example, the computed geopotential height at 100hPa vs the data in the pressure level file is compared in the two images below.

![MERRA_100hPa_GPH](https://user-images.githubusercontent.com/6153603/84818019-109e6e00-afd3-11ea-8303-61312ea0eb48.png)
![MERRAnv_100hPa_GPH](https://user-images.githubusercontent.com/6153603/84818034-14ca8b80-afd3-11ea-940e-90e09cf473f1.png)

I'm using the following equations to go from the hybrid levels to geopotential heights in the layer:

pressure = (level.a + level.b * PS) / 100

virtual_temperature = T * (1.0 + 0.609133 * QV)
dlogp = np.log(pressure.shift(lev=-1) / pressure)
h = 287.058 * virtual_temperature.shift(lev=-1) * dlogp

level.a and level.b are the hybrid layer definitions.
PS = Pressure at the Surface
T = Temperature
QV = Specific humidity
h = geopotential height difference of the layer.

the .shift just takes the next array element value

Is there a different set of equations I should be using for the MERRA-2 data, or a different "true" surface level pressure?

**Comment by yantosca** [comment]
Thanks for writing.  We use the instantaneous PS field from the inst3_3d_asm_Nv collection in the formulation:
```
pressure(X,Y,Z) = Ap(Z) + Bp(Z) * P(X,Y)

where X,Y are horizontal coordinates and Z is the vertical coordinate
```
This is valid for the the pressure at grid box edges.  To get the pressure at the vertical midpoint of a grid box you average Pressure(X,Y,Z) and Pressure(X,Y,Z+1).
You will want to doublecheck that the Ap coordinates are in the same units as the surface pressure.  MERRA2 pressures in the input files come in Pa, so Ap must also be in Pa.

Also I think there may be a 3D geopotential height field already in the MERRA-2 data set.  You can check the file spec document: https://gmao.gsfc.nasa.gov/pubs/docs/Bosilovich785.pdf

If you have further questions about MERRA-2, the folks at GMAO are probably best poised to answer them.  See: https://gmao.gsfc.nasa.gov/reanalysis/MERRA-2/

**Comment by czr137** [comment]
After studying the problem a bit further it seems to me that the MERRA pressure level data gives the geopotential with reference to the sea level pressure, but if you calculate the geopotential height from the hybrid levels it is with reference to the surface of the Earth (the surface used in the hybrid model).
Does anyone know to calculate the geopotential height of the Earth's surface? I scanned some of geos-chem source code and it looks like it depends on the surface temperature and pressure, but I did not see an equation.

**Comment by yantosca** [comment]
This is beyond our scope.  I would direct your question to GMAO directly.  We only use the GMAO met fields for GEOS-Chem but we do not produce them.

**Comment by czr137** [comment]
Thanks @yantosca,
I emailed them directly about 12 hours ago and I sent them the same information as well as the link to this issue. I now see that there is a PHIS field in the assimilated product that represents the surface geopotential height (which are the differences / offsets I'm looking for.)
Feel free to close this issue.

**Comment by yantosca** [comment]
Great!  Thanks much.  I'll close this out.
