### ISSUE TITLE
[QUESTION] Units for NO and NO2 in HEMCOsa

### ISSUE THREAD

**Issue by Zitely** [geoschem/geos-chem#359]
I couldn't find in the wiki exactly what are the units in which HEMCO standalone returns emissions of NO and NO2. My guess was that it was in kg of N, but when looking at the ratios of NO and NO2 (which normally are 90/10 ~ish) I am getting about 75/25. If I assume that the results are in kg of specie, then the ratio is 84/16; which is closer to the expected value.
Note: the version I am using is 2.1.002.

Many thanks,
Zitely Tzompa

**Comment by yantosca** [comment]
Can you attach the HEMCO_Config.rc that you are using to this issue?

**Comment by msulprizio** [comment]
Since this is a HEMCO standalone run, we'd also need to see the HEMCO_sa_Spec.rc  and HEMCO_Diagn.rc files. The former defines the species properties and the latter should have the units of the diagnostics (usually kg species/m2/s).

**Comment by Zitely** [comment]
Thanks for your responses!

 Attached are the HEMCOsa files (Note: I had to add '.txt' to each file in order to attach them in GitHub).
 
[HEMCO_sa_Config_ek_ptoilgas.rc.txt](https://github.com/geoschem/geos-chem/files/4793926/HEMCO_sa_Config_ek_ptoilgas.rc.txt)
[HEMCO_sa_Diagn.rc.txt](https://github.com/geoschem/geos-chem/files/4793929/HEMCO_sa_Diagn.rc.txt)
[HEMCO_sa_Spec.rc.txt](https://github.com/geoschem/geos-chem/files/4793930/HEMCO_sa_Spec.rc.txt)

**Comment by msulprizio** [comment]
Looks like the units of NO and NO2 in your HEMCO standalone output are [kg species/m2/s].
```
ANTHR_NO     NO    -1   -1   -1   2   kg/m2/s
ANTHR_NO2    NO2   -1   -1   -1   2   kg/m2/s
```
The only automatic conversions that HEMCO does is between kg species and kg C, and we will be getting rid of that soon. There is no automatic conversion to kg N.

**Comment by Zitely** [comment]
OK. Many thanks Melissa!!
