### ISSUE TITLE
KPP do not know the families 

### ISSUE THREAD

**Issue by yingyingyan** [geoschem/geos-chem#36]
I am trying to run geos-chem v12.3.2 with the standard chemistry. When I build the standard chemistry in KPP, the problem occur as follows:

rm: cannot remove `*o': No such file or directory

This is KPP-2.2.

KPP is parsing the equation file.Warning :Standard.eqn:1188: Duplicate equation:  (eqn<559> = eqn<560> )
Error :gckpp.kpp:10: 'FAMILIES': Unknown command (ignored)
Error :gckpp.kpp:11: Extra parameter on command line 'POx'
Error :gckpp.kpp:11: Extra parameter on command line ':'
........
Error :gckpp.kpp:17: Extra parameter on command line ':'
Error :gckpp.kpp:17: Extra parameter on command line 'H2O2'
;
Fatal error : 222 errors and 1 warnings encountered.
Program aborted
KPP failure! Aborting.

The KPP is downloaded from https://bitbucket.org/gcst/kpp/downloads/?tab=branches, I download the GC_updates version

How can I solve this problem, Thank you very much!

**Comment by msulprizio** [comment]
Can you confirm that you did `git checkout GC_updates` and rebuilt KPP? See the steps [here](http://wiki.seas.harvard.edu/geos-chem/index.php/FlexChem#KPP_source_code). The error message is suggesting that you are using a build of KPP that doesn't have the updates for GEOS-Chem.

Could you also attach the gckpp.kpp file that you are using. Did you modify this or any other files in the KPP/Standard directory or are you building the mechanism out-of-the-box? If the latter, you shouldn't need to rebuild the mechanism unless you have made modifications to the mechanism. The gckpp*.F90 files produced by KPP for the existing supported mechanisms are already included in the source code.

**Comment by yingyingyan** [comment]
Yes, I have done git checkout GC_updates and rebuilt KPP.

I did not modify the gckpp.kpp file. I just only made modifications in KPP/Standard/Standard.eqn to update the aromatic chemistry of SAPRC-11 in GEOS-Chem v12.3.2. 

However, before and after my modification, I have the same problem that KPP do not know FAMILIES in gckpp.kpp.

**Comment by yingyingyan** [comment]
> Can you confirm that you did `git checkout GC_updates` and rebuilt KPP? See the steps [here](http://wiki.seas.harvard.edu/geos-chem/index.php/FlexChem#KPP_source_code). The error message is suggesting that you are using a build of KPP that doesn't have the updates for GEOS-Chem.
> 
> Could you also attach the gckpp.kpp file that you are using. Did you modify this or any other files in the KPP/Standard directory or are you building the mechanism out-of-the-box? If the latter, you shouldn't need to rebuild the mechanism unless you have made modifications to the mechanism. The gckpp*.F90 files produced by KPP for the existing supported mechanisms are already included in the source code.

Thank you for your comment.
Yes, I have done git checkout GC_updates and rebuilt KPP.

I did not modify the gckpp.kpp file. I just only made modifications in KPP/Standard/Standard.eqn to update the aromatic chemistry of SAPRC-11 in GEOS-Chem v12.3.2.

However, before and after my modification, I have the same problem that KPP do not know FAMILIES in gckpp.kpp.

**Comment by msulprizio** [comment]
Here are a few suggestions:

1. Navigate to your kpp/kpp-2.2.3_01 directory and view the gitk history. Attach a screenshot of the gitk window here.
2. Rebuild KPP from scratch (again) and attach the log file here. Do:

```
cd kpp/kpp-2.2.3_01
make clean
make > kpp_build.log
```
3. Try rebuilding an unmodified version of the Standard mechanism. If you are still getting the above error, please attach your gckpp.kpp and .eqn files.

**Comment by yingyingyan** [comment]
> Here are a few suggestions:
> 
> 1. Navigate to your kpp/kpp-2.2.3_01 directory and view the gitk history. Attach a screenshot of the gitk window here.
> 2. Rebuild KPP from scratch (again) and attach the log file here. Do:
> 
> ```
> cd kpp/kpp-2.2.3_01
> make clean
> make > kpp_build.log
> ```
> 
> 1. Try rebuilding an unmodified version of the Standard mechanism. If you are still getting the above error, please attach your gckpp.kpp and .eqn files.


Thank you for your comment.
1. As our service can not connect outside network, I can not check the gitk history. One KPP is from Jiawei Zhuang @JiaweiZhuang . He download for me using git and git check the GC_updates. Another KPP is   @@from  https://bitbucket.org/gcst/kpp/downloads/?tab=branches （the GC_updates one）. Both KPP can make successfully and have no idea the FAMILIES when build the standard chemistry.

2.The kpp_build.log is attached. However, the github do not support the gckpp.kpp and standard.eqn file type. I failed to attach these two files. They are from the geos-chem-master version v12.3.2. 

Thank you so much! 

[kpp_build.log](https://github.com/geoschem/geos-chem/files/3185167/kpp_build.log)

**Comment by yingyingyan** [comment]
> Here are a few suggestions:
> 
> 1. Navigate to your kpp/kpp-2.2.3_01 directory and view the gitk history. Attach a screenshot of the gitk window here.
> 2. Rebuild KPP from scratch (again) and attach the log file here. Do:
> 
> ```
> cd kpp/kpp-2.2.3_01
> make clean
> make > kpp_build.log
> ```
> 
> 1. Try rebuilding an unmodified version of the Standard mechanism. If you are still getting the above error, please attach your gckpp.kpp and .eqn files.

I have tried to download the KPP with git on Harvard server. It shows:

[holylogin04 yanyy]$ git clone https://bitbucket.org/gcst/kpp
Cloning into 'kpp'...
remote: Counting objects: 697, done.
remote: Compressing objects: 100% (593/593), done.
remote: Total 697 (delta 336), reused 291 (delta 88)
Receiving objects: 100% (697/697), 3.77 MiB | 6.14 MiB/s, done.
Resolving deltas: 100% (336/336), done.
Checking out files: 100% (400/400), done.
[holylogin04 yanyy]$ git checkout -b GC_updates origin/GC_updates
fatal: not a git repository (or any parent up to mount point /n)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[holylogin04 yanyy]$ git checkout GC_updates
fatal: not a git repository (or any parent up to mount point /n)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

Is there any problem in the KPP branches?

**Comment by yingyingyan** [comment]
> Here are a few suggestions:
> 
> 1. Navigate to your kpp/kpp-2.2.3_01 directory and view the gitk history. Attach a screenshot of the gitk window here.
> 2. Rebuild KPP from scratch (again) and attach the log file here. Do:
> 
> ```
> cd kpp/kpp-2.2.3_01
> make clean
> make > kpp_build.log
> ```
> 
> 1. Try rebuilding an unmodified version of the Standard mechanism. If you are still getting the above error, please attach your gckpp.kpp and .eqn files.

I tried on Harvard server to do this work. 

[holylogin04 kpp-2.2.3_01]$ git checkout GC_updates
Already on 'GC_updates'
Your branch is up to date with 'origin/GC_updates'.
[holylogin04 kpp-2.2.3_01]$ make clean
make[1]: Entering directory `/n/home06/xlu123/yanyy/kpp/kpp-2.2.3_01/src'
make[1]: Leaving directory `/n/home06/xlu123/yanyy/kpp/kpp-2.2.3_01/src'

When build the KPP, I have the result:
 gcc -g -Wall -c debug.c
  gcc -g -Wall y.tab.o lex.yy.o scanner.o scanutil.o kpp.o gen.o code.o code_c.o code_f77.o code_f90.o code_matlab.o debug.o -L/usr/lib64 -lfl -o kpp
/usr/bin/ld: cannot find -lfl
collect2: error: ld returned 1 exit status
make[1]: *** [kpp] Error 1
make[1]: Leaving directory `/n/home06/xlu123/yanyy/kpp/kpp-2.2.3_01/src'

**Comment by yantosca** [comment]
I think I see the issue.  You have to have the "flex" library loaded into your Unix environment.  If you are on the Harvard Odyssey cluster, then you would type:

    module load flex/2.6.4-fasrc01

or include that in your .bashrc or whichever environment file where you load modules.
