### ISSUE TITLE
[QUESTION] Unit conversion for kgNO2

### ISSUE THREAD

**Issue by barronh** [geoschem/geos-chem#360]
This comment is related to #51, but not duplicative. It could be made irrelevant. In working with EPA databases of emissions, I came across a use case that yielded surprising results. 

It is not uncommon for databases to report or store NOx as kgNO2/m2/s. If the file has NO in units of kgNO2/m2/s and the user requests kg/m2/s, `IsInWord(unt, 'kgN')` triggers kilograms nitrogen and leads to an increase rather than a decrease in mass. For my case, I just make sure to have the unit the same in HEMCO and use a scalar to convert to kgNO. This may not come up a lot, but I thought I would share. Is this worth adding a special case unit case?

**Comment by yantosca** [comment]
Thanks for writing.  I will post an issue on the HEMCO repository.  Starting in 13.0.0, GEOS-Chem and HEMCO will be kept in separate repositories so this will have to be made as an update in geoschem/hemco.

**Comment by yantosca** [comment]
Also, now that I think about it, in 13.0.0 we are going to make all of the unit conversions explicit in the HEMCO_Config.rc file with scale factors.  See: https://github.com/geoschem/geos-chem/issues/309.  We can do a similar thing for kg NO2 -> kg N with scale factors.  That might be the cleanest approach.

Feel free to add scale factors in your HEMCO_Config.rc for now as a quick fix.

**Comment by yantosca** [comment]
I am closing this issue as all further comment should be made to the geoschem/HEMCO repository issue https://github.com/geoschem/geos-chem/issues/309.  At that time all unit conversions will be made explicit in the configuration file.
