### ISSUE TITLE
[BUG/ISSUE] HEMCO standalone asking for username and password

### ISSUE THREAD

**Issue by Zitely** [geoschem/geos-chem#367]
## Describe the bug
I am trying to install the newest version of HEMCO standalone, but when building the NcdfUtilities and HEMCO, it is asking me for a username and password. Is this normal? Can you provide those? 

## To Reproduce

This is exactly what I did:
```
ztzompa@ozone:~$ git clone https://github.com/christophkeller/hemco_standalone_full
Cloning into 'hemco_standalone_full'...
remote: Enumerating objects: 44, done.
remote: Total 44 (delta 0), reused 0 (delta 0), pack-reused 44
Unpacking objects: 100% (44/44), done.
Checking connectivity... done.
ztzompa@ozone:~$ mv hemco_standalone_full/ hemco_sa
ztzompa@ozone:~/hemco_sa$ make all >& log
Username for 'https://bitbucket.org': zitely
Password for 'https://zitely@bitbucket.org': 
ztzompa@ozone:~/hemco_sa$ ls
HEMCO  Makefile  README.md  log
```
## Expected behavior

As described in the [wiki](http://wiki.seas.harvard.edu/geos-chem/index.php/HEMCO_installation_guide
[log.txt](https://github.com/geoschem/geos-chem/files/4880906/log.txt)

), I should see the following output near the end of the log file and the HEMCO executable should be created.

 Calculate emissions at 2008-01-01 23:00:00
 HEMCO_STANDALONE FINISHED!

## Error messages
Instead of that, my log file stops here:
```
If your login environment uses bash:
-------------------------------------------
export BIN_NETCDF=
export INC_NETCDF=
export LIB_NETCDF=
export BIN_HDF5=
export INC_HDF5=
export LIB_HDF5=
export NCU_BIN=/home/ztzompa/hemco_sa/NcdfUtil/bin
export NCU_LIB=/home/ztzompa/hemco_sa/NcdfUtil/lib
export NCU_MOD=/home/ztzompa/hemco_sa/NcdfUtil/mod
export HCO_BIN=/home/ztzompa/hemco_sa/HEMCO/bin
export HCO_LIB=/home/ztzompa/hemco_sa/HEMCO/lib
export HCO_MOD=/home/ztzompa/hemco_sa/HEMCO/mod
make[1]: Leaving directory '/home/ztzompa/hemco_sa'
```

## Required information
I tried using the following NETCDF and HDF5 modules, but I got the same error. 

Option 1:
- intel/14.0.1
- hdf5/1.8.11-intel14.0.1
- netcdf/4.3.0-intel14.0.1

Option 2:
- intel/18.0.0               
- hdf5/1.8.19-intel18.0.0
- netcdf/4.4.1-intel18.0.0

## Input and log files to attach
 - log file after unsuccessfully building HEMCO

**Comment by msulprizio** [comment]
The HEMCO repository has been moved to https://github.com/geoschem/HEMCO. I did a quick update to the instructions on the wiki to point to that repository instead and to use CMake for the build. We plan on doing a more thorough update on the HEMCO documentation for the 3.0.0 release that will coincide with GEOS-Chem's 13.0.0 release (see https://github.com/geoschem/HEMCO/issues/36 for updates as they become available).

**Comment by Zitely** [comment]
Thanks Melissa!

Zitely

**Comment by msulprizio** [comment]
No problem. Feel free to open up an issue on that repository if you run into any issues with the HEMCO standalone. That repository is up-to-date with the HEMCO code in GEOS-Chem 12.8.2. In GEOS-Chem 13.0.0, the HEMCO source code will be removed from the GEOS-Chem repository completely in favor of using the HEMCO repository as a Git submodule within the  GEOS-Chem frameworks (i.e. GEOS-Chem Classic, GCHP).
