### ISSUE TITLE
[QUESTION]How can I perform the absorbing process?

### ISSUE THREAD

**Issue by yutao-chen** [geoschem/geos-chem#368]
I'd like to add a series of species with several gas-phase reactions in GEOS-Chem mechanism. The productions of these reactions have  low vapor pressures under atmospheric conditions and likely partition to the particulate phase. And then some of these productions will be absorbed by different size of different kinds of  aerosols.(sulfate aerosol ,dust, sea salt , organic aerosol) What should I do to porform the absorbing process?

**Comment by yantosca** [comment]
Thanks for writing.  Unfortunately, this is more of a science question than a coding question.  As such, the GCST is unable to suggest a path forward (as we have very little chemistry experience).  Perhaps some members of the GEOS-Chem community would have more input than we can currently give.

**Comment by yantosca** [comment]
I am going to close out this issue as there has been a lack of recent activity here.  Please feel free to open another issue.
