### ISSUE TITLE
[BUG/ISSUE] Problems using RCP emissions

### ISSUE THREAD

**Issue by jennyfisher** [geoschem/geos-chem#369]
## Describe the bug
We are having difficulty running GEOS-Chem v12 with RCP emissions (tested with RCP4.5, but I imagine it will be the same for all). We have tried using v12.2 and also v12.8.0.

The first problem is specific to v12.8.0 and has to do with the time cycling flag in the HEMCO_Config.rc. It is set to `ID` which causes HEMCO to die almost immediately saying there is no such time cycling attribute (or something like that). If I change the flag back to `I` (as it was in our v12.2 code), we get past this error.

However, then we have another problem. HEMCO dies with the following:
```
-------------------------------------------------------------------------------
 Calculating emissions for species ALK4
-------------------------------------------------------------------------------
HEMCO: Entering GET_CURRENT_EMISSIONS ( 3)
      
 Evaluate field RCP45_ALK4__A
HEMCO: Leaving GET_CURRENT_EMISSIONS ( 3)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
HEMCO ERROR: Negative emissions in: RCP45_ALK4__A. To allow negatives, edit settings in the configuration file. 
ERROR LOCATION: HCO_CalcEmis (HCO_CALC_MOD.F90)
ERROR LOCATION: HCO_RUN (hco_driver_mod.F90)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

After setting verbose and warnings to 3, we see that emissions of RCP45_ALK4__A (and indeed **all** RCP emissions) are getting set to negative values:
```
    -->Array sum       :  -3.1680220E+34
    -->Array min & max :  -9.9999998E+30  0.0000000E+00
```

However, I've double checked the input files using cdo and they look fine:
```
[jaf574@gadi-login-03 RCP_45]$ cdo infon RCPs_anthro_butanes_2005-2100_27424_kgC.nc 
    -1 :       Date     Time   Level Gridsize    Miss :     Minimum        Mean     Maximum : Parameter name
     1 : 2005-01-01 00:00:00       0   259200       0 :      0.0000  4.3015e-13  5.8777e-10 : ACCMIP        
     2 : 2010-01-01 00:00:00       0   259200       0 :      0.0000  4.2124e-13  5.1093e-10 : ACCMIP        
     3 : 2020-01-01 00:00:00       0   259200       0 :      0.0000  4.0342e-13  3.5725e-10 : ACCMIP        
     4 : 2030-01-01 00:00:00       0   259200       0 :      0.0000  4.5282e-13  5.0675e-10 : ACCMIP        
     5 : 2040-01-01 00:00:00       0   259200       0 :      0.0000  4.5816e-13  5.9245e-10 : ACCMIP        
     6 : 2050-01-01 00:00:00       0   259200       0 :      0.0000  4.1945e-13  6.1433e-10 : ACCMIP        
     7 : 2060-01-01 00:00:00       0   259200       0 :      0.0000  3.9967e-13  6.5590e-10 : ACCMIP        
     8 : 2070-01-01 00:00:00       0   259200       0 :      0.0000  3.7171e-13  7.6631e-10 : ACCMIP        
     9 : 2080-01-01 00:00:00       0   259200       0 :      0.0000  3.3557e-13  9.4557e-10 : ACCMIP        
    10 : 2090-01-01 00:00:00       0   259200       0 :      0.0000  3.1400e-13  7.4416e-10 : ACCMIP        
    11 : 2100-01-01 00:00:00       0   259200       0 :      0.0000  2.9243e-13  5.4276e-10 : ACCMIP        
```

I thought it might be something to do with the interpolation, so I tried setting the flag to `R` instead of `I`. This time the run did not die with the negative values, but the HEMCO.log still shows the same large negatives for Array sum and Array min. The HEMCO_Diagnostics files then shows zero for all anthropogenic emissions.

We also tried compiling with FPE=y and BOUNDS=y and nothing changed.

## To Reproduce
Run v12 out of the box with RCP_45 set to true and all other anthropogenic emissions turned off. In our case we are also running with Emission Year set to 2030, but I tried with 2007 and everything was the same.

## Expected behavior
Run with RCP4.5 and get positive emissions!

## Error messages
See above.

## Required information
 - GEOS-Chem version 12.8.0
 -  ifort 19.0.5.281
 - netCDF 4.7.1
 - NCI Gadi cluster
 - "out of the box" code

## Input and log files to attach
 - The lastbuild file
 - The input.geos file
 - The HEMCO_Config.rc file
 - The GEOS-Chem "Classic" log file
 - The HEMCO.log file
(These are the versions where I set the flag to `R` not `ID` or `I`.)
[forGCST.zip](https://github.com/geoschem/geos-chem/files/4894886/forGCST.zip)

**Comment by jennyfisher** [comment]
Hi @msulprizio @yantosca @christophkeller -- any thoughts on this issue? Thanks!

**Comment by yantosca** [comment]
I am also looping in @jimmielin.  There have been a lot of updates to HEMCO recently (to facilitate connection with other models) so perhaps something got clobbered.

**Comment by jennyfisher** [comment]
Just a very minor addition to what I wrote before - using the `C` flag for the RCP files goes back to the original behaviour where the run dies because of the negative emissions (as it should!).

**Comment by yantosca** [comment]
With these fixes in GEOS-Chem 12.9.1, I was able to get a short simulation to run to completion.  I don't know if that addresses the negative value issue though.

**Comment by yantosca** [comment]
This has also been fixed in the HEMCO repository with commit: https://github.com/geoschem/HEMCO/commit/2d44eda9f31b8e81e8ac70838d1695c210becc6f

**Comment by jennyfisher** [comment]
Thanks Bob. I am trying to download the new files but I seem to be unable to access geoschemdata.computecanada.ca (either from my server or direct using URL). The status page I found (https://status.computecanada.ca/) implies there are no downtime issues - but I can't connect. Do you know if there has been a change to the data access? Thanks!

**Comment by jennyfisher** [comment]
In the meantime, I was able to download the files from the Harvard FTP, and with the updated files plus changes to the HEMCO code, it seems to be working properly! Negative values are gone, reasonable values are present, and HEMCO diagnostics are saving normal looking distributions to the diagnostics files. Thanks!! 👍

**Comment by msulprizio** [comment]
I was just able to transfer the new RCP files over to Compute Canada via Globus. If you have access to Globus, that may be a better way to transfer files from Compute Canada. We still need to add documentation for the Globus endpoint to the wiki, so let me know if you're interested and I can get right on that.

I also can't access http://geoschemdata.computecanada.ca/ExtData/ via a web browser. @Jun-Meng are you aware of any issues on their end?

**Comment by yantosca** [comment]
Also note, we have updated the configuration files in GCHPctm with commit: https://github.com/geoschem/geos-chem/commit/a34f1ba8b7ef63e9ea0b8d2bc3a4b32eb328b8af.

**Comment by jennyfisher** [comment]
Hi Melissa,

I've never heard of Globus - can you provide more information? (I'm good with the RCP files for now, but generally use the Compute Canada http site for other data files we are missing!).

Thanks!
Jenny

**Comment by Jun-Meng** [comment]
> I was just able to transfer the new RCP files over to Compute Canada via Globus. If you have access to Globus, that may be a better way to transfer files from Compute Canada. We still need to add documentation for the Globus endpoint to the wiki, so let me know if you're interested and I can get right on that.
> 
> I also can't access http://geoschemdata.computecanada.ca/ExtData/ via a web browser. @Jun-Meng are you aware of any issues on their end?

Hi Melissa and Jenny, 

The Compute Canada Virtual Machine (CCVM) we are using for archiving the met-fields is under maintenance during July 14 -16. It should be normal tomorrow. 

Jun

**Comment by jennyfisher** [comment]
Great, thanks for clarifying Jun!

**Comment by msulprizio** [comment]
> I've never heard of Globus - can you provide more information? (I'm good with the RCP files for now, but generally use the Compute Canada http site for other data files we are missing!).

@jennyfisher I've added some text for downloading files via Globus to our wiki page. See http://wiki.seas.harvard.edu/geos-chem/index.php/Downloading_data_from_Compute_Canada#File_transfers_with_Globus.

**Comment by jennyfisher** [comment]
Thanks @msulprizio - never heard of it, but it does appear my institution has a log-in!
