### ISSUE TITLE
[QUESTION]How to add a new reaction which only have one reaction rate constant at temperature of 298k ?

### ISSUE THREAD

**Issue by yutao-chen** [geoschem/geos-chem#375]
I'd like to add a new reaction into /KPP/Custom/Custom.equ and need to use the function "GCARR" which need two variables A and E/R. But I just know one reaction rate constant at temperature of 298k since the  lack of previous experimental data and could not compulate the A and E/R .
So If there is a way to add a new reaction just with one k value ?
Look forward to your reply.

**Comment by yantosca** [comment]
Thanks for writing.  You can add your own function to the gckpp.kpp file.  After all the reactions are specified there is this section of the file:

```
#INLINE F90_RATES
  REAL(kind=dp) FUNCTION ARRPLUS( A0,B0,C0,D0,E0 )
     REAL A0,B0,C0,D0,E0 
     REAL(kind=dp) K0     
     K0 = DBLE(A0) * (DBLE(D0)+(TEMP*DBLE(E0)))
     ARRPLUS =  K0 * EXP(-DBLE(B0)/TEMP) * (TEMP/300.0_dp)**DBLE(C0)
     IF (ARRPLUS < 0.0) ARRPLUS = 0.0
  END FUNCTION ARRPLUS        

... etc...
  REAL(kind=dp) FUNCTION GCARR( A0,B0,C0 )
      REAL A0,B0,C0 
      GCARR =  DBLE(A0) * EXP(DBLE(C0)/TEMP) * (300._dp/TEMP)**DBLE(B0)
  END FUNCTION GCARR   
```

So you could create a new function something like GCARR but that takes the arguments that you need.  Then in the Standard.eqn file, you can use the new function that you created as the reaction rate.

**Comment by yantosca** [comment]
I will close out this issue for now.  Feel free to reopen.
