### ISSUE TITLE
[DISCUSSION] Dry Deposition Wesely Look-up Tables

### ISSUE THREAD

**Issue by dpfinch** [geoschem/geos-chem#377]
I’m doing some work using the dry deposition code in GEOS-Chem and was wondering if someone could give some clarifications with some of it.

It says in the code that the 74 Olson land types are mapped to the 11 original Wesely land types (with updates for Amazon & Tundra land types) and then the canopy resistance values for those land types are read in from ‘Olson_2001_Drydep_Inputs.nc’.

However, I noticed that the original Wesely resistance types include seasonal changes as well - and the values in the original Wesely paper can be very different from the ones in GEOS-Chem. I realise the order of the table is different but even taking that into account some of the numbers used in GEOS-Chem don’t seem to match up. 

I had thought the seasonality is taken into account by something like LAI but from what I can see there is only one use where the resistance is corrected for LAI and the rest are taken at face value.

Am I understanding the code correctly? I was wondering if you could shed any more light on where the canopy resistance numbers used in GEOS-Chem come from and if there are any seasonal corrections.

If anyone has any insight into this then that would be a great help!

Thanks in advance,

Doug

**Comment by yantosca** [comment]
Also tagging @ltmurray who is on the Climate-Ecosystem-Chemistry WG.  I am not sure if the other WG chairs are on Github yet.

**Comment by ltmurray** [comment]
I’m cc'ing members of the Chemistry-Ecosystem-Climate and the Emissions & Deposition WGs who know more about dry deposition than I do.

On Jul 15, 2020, at 5:05 PM, Bob Yantosca <notifications@github.com<mailto:notifications@github.com>> wrote:



Also tagging @ltmurray<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ltmurray&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=FZTgar4ZcAerjX-R_LaBWCoXl65de8pQBuW_W4Wb_wQ&m=zLpxpxDVUgFQ8682D7BbmBJVBbkcJM8_PJ-fs0Q-CnY&s=c_7jZi3ZsjqdDcM0edPLuNWwu5LXS62Y6IiiGiI2DtU&e=> who is on the Climate-Ecosystem-Chemistry WG. I am not sure if the other WG chairs are on Github yet.

**Comment by ayhwong** [comment]
A much better reference to GEOS Chem dry deposition routine would be Wang et al. (1998). Compared to the original Wesely scheme, here are the similarity and differences in the canopy resistance:

1) stomatal resistance: Only the temperature function is the same as the original Wesely. GEOS Chem adds dependence to LAI through a routine that is "a polynomial fit to a canopy radiative transfer equation"(BIOFIT). R_s_min is always 200 s m^-1 regardless to land type.

2) cuticular resistance: The baseline value in GEOS-Chem assumes LAI = 1, and scales inversely as LAI, which fits the physical picture better.

That what I understand from the code. Feel free to keep asking and adding more details.
