### ISSUE TITLE
Error building GEOS-Chem with TOMAS in 12.3

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/geos-chem#38]
Hi everyone,

I've been having some trouble building GEOS-Chem with TOMAS ever since the `NC_DIAG` option was removed. What make command should use to build GEOS-Chem Classic with TOMAS in 12.3?

## Context
I've been trying to build from the `geosfp_4x5_TOMAS15` and `geosfp_4x5_TOMAS40` run directories with
```
make mpbuild
```
and 
```
make TOMAS15=yes mpbuild                                         # for TOMAS15
```

**Note:** Before 12.3 I used to build these run directories with
```
make TOMAS15=yes NC_DIAG=n mpbuild                     # for TOMAS15
```

## Problem
With both of those commands, I get the following error:
```
ifort -cpp -w -auto -noalign -convert big_endian -O2 -vec-report0 -fp-model source -openmp -mcmodel=medium -shared-intel -traceback -DLINUX_IFORT -DBPCH_DIAG -DBPCH_TIMESER -DBPCH_TPBC -DGEOS_FP -DGRIDREDUCED -DGRID4x5 -DTOMAS -DTOMAS15 -DNC_HAS_COMPRESSION -DUSE_REAL8 -module ../../mod -I/software/include -c -free hcox_tomas_jeagle_mod.F90
hcox_tomas_jeagle_mod.F90(160): error #6404: This name does not have a type, and must have an explicit type.   [INST] 
    Inst   => NULL()
----^
hcox_tomas_jeagle_mod.F90(161): error #6691: A pointer dummy argument may only be argument associated with a pointer.   [INST]
    CALL InstGet ( ExtState%TOMAS_Jeagle, Inst, RC )
------------------------------------------^
hcox_tomas_jeagle_mod.F90(169): error #6460: This is not a field name that is defined in the encompassing structure.   [TC1]
    Inst%TC1 = 0.0_hp
---------^
hcox_tomas_jeagle_mod.F90(170): error #6460: This is not a field name that is defined in the encompassing structure.   [TC2]
    Inst%TC2 = 0.0_hp
---------^
hcox_tomas_jeagle_mod.F90(221): error #6404: This name does not have a type, and must have an explicit type.   [TOMAS_DBIN] 
             rwet=TOMAS_DBIN(k)*1.0E6*BETHA/2. ! convert from dry diameter [m] to wet (80% RH) radius [um]
------------------^
hcox_tomas_jeagle_mod.F90(235): error #6404: This name does not have a type, and must have an explicit type.   [DRFAC]
             dfo=dfo*DRFAC(k)*BETHA  !hemco units???? jkodros
---------------------^
hcox_tomas_jeagle_mod.F90(277): error #6911: The syntax of this substring is invalid.   [TC2]
       CALL HCO_EmisAdd( am_I_Root, HcoState, Inst%TC2(:,:,:,K), &
```

I get a similar problem when I try to compile with `gfortran`. Is there something I'm missing?

Thanks in advance,

Liam

**Comment by yantosca** [comment]
I think there might be a missing local variable declaration for Inst in HCOX_TOMAS_Jeagle_Run:

    TYPE(MyInst), POINTER  :: Inst

If you look at the other extensions you will see that declaration.  The Inst object is needed so that each core in MPI can have local copies of certain variables (but in GC-Classic there is just one copy).

FYI, I have never gotten TOMAS40 to build with gfortran.  The build chokes with an internal compiler error.  I mentioned that to the TOMAS team but they haven't come up with a workaround.  If you use ifort it should be OK.

**Comment by msulprizio** [comment]
That is right. There are other fixes needed in that module too. I am implementing a fix now and will follow up shortly.

**Comment by LiamBindle** [comment]
Thanks Bob and Melissa. Sounds good.

The error was causing my CMake verification tests to fail for the TOMAS run directories, and I thought I might have missed a change to how TOMAS was supposed to be built.

> FYI, I have never gotten TOMAS40 to build with gfortran.

Oh right, I've actually been getting similar results. 

Thanks again!

**Comment by msulprizio** [comment]
I pushed a fix for compiling TOMAS to the `dev/12.4.0` branch (see https://github.com/geoschem/geos-chem/commit/153d794f0fa4a6795e14bb952e59eadd6061aa3a). That commit fixes the aforementioned issues in hcox_tomas_jeagle_mod.F90m but it also fixes issues in several other modules associated with the implementation of FlexGrid for 12.4.0. You can ignore those if you're not using this version. 

The upshot is your make commands were correct, but you also helped us identify and now fix several bugs/typos in the TOMAS code. Thanks!

**Comment by msulprizio** [comment]
Also, FYI, I was able to compile the `dev/12/4/0` branch with `TOMAS40=y` using gfortran 8.2.0. If there was an issue before it now seems to be resolved.

**Comment by LiamBindle** [comment]
Good to know! Thanks!
