### ISSUE TITLE
[BUG/ISSUE] Tagged CO2 simulations 

### ISSUE THREAD

**Issue by monszel** [geoschem/geos-chem#381]
Hello,

I am trying to run the out-of-the box geosfp_2x25_CO2 simulations using GC.12.9.1. 
I added the following species for a tagged CO2 simulation in input.geos and modified CO2 menu:
```
%%% ADVECTED SPECIES MENU %%%:
Species name            : CO2
Species name            : CO2AV
Species name            : CO2BAL
Species name            : CO2BB
Species name            : CO2BF
Species name            : CO2CH
Species name            : CO2CORR
Species name            : CO2FF
Species name            : CO2NTE
Species name            : CO2OC
Species name            : CO2SE

%%% CO2 SIM MENU %%%    :
Fossil Fuel Emissions   : T
Ocean Exchange          : T
Balanced Biosphere Exch : T
Net Terrestrial Exch    : T
Ship emissions          : T
Aviation emissions 3-D  : T
3-D Chemical Oxid Source: T
Tagged CO2 runs         :---
 Save Fossil in Bckgrnd: T
 Tag Bio/Ocean CO2 reg : T
 Tag Land FF CO2 reg   : T
 Tag Global Ship CO2   : T
 Tag Global Plane CO2  : T
```

I checked quickly output files and as CO2 and CO2OC looks reasonable, for the rest of species I get one value close to zero. I am probably missing something here and would greatly appreciate your help!

Attached HEMCO_Config and input.geos.

Best Regards,
Monika
[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/4953669/HEMCO_Config.txt)
[input.geos.txt](https://github.com/geoschem/geos-chem/files/4953673/input.geos.txt)

**Comment by WilliamDowns** [comment]
Hi @monszel, thanks for submitting this issue. I can confirm that I observe the same problem when running the tagged CO2 simulation for any GEOS-Chem version since at least 12.5.0. I'll let @msulprizio or @yantosca chime in with more info on the current/recent state of the tagged CO2 sim and any other advice.

**Comment by monszel** [comment]
Hi @WilliamDowns,
Thank you for your answer. I think I might figured it out. The species names in GC12.9.1 are inconsistent in HEMCO_Config.rc and species_database (capital/small). I have changed CO2ff -> CO2FF as a test and at least fossil fuel emissions look good. 

Example:
**old:**
(((FOSSIL_ODIAC
0 FOSSILCO2_ODIAC   $ROOT/CO2/v2015-04/FOSSIL/ODIAC_CO2.monthly.generic.1x1.nc   CO2 2000-2014/1-12/1/0 C xy kg/m2/s CO2   40/41/80 1 2
0 FOSSILCO2FF_ODIAC -                                                            -   -                  - -  -       **CO2ff** 40/41/80 1 2
)))FOSSIL_ODIAC

**new:**
(((FOSSIL_ODIAC
0 FOSSILCO2_ODIAC   $ROOT/CO2/v2015-04/FOSSIL/ODIAC_CO2.monthly.generic.1x1.nc   CO2 2000-2014/1-12/1/0 C xy kg/m2/s CO2   40/41/80 1 2
0 FOSSILCO2FF_ODIAC -                                                            -   -                  - -  -       **CO2FF** 40/41/80 1 2
)))FOSSIL_ODIAC


Monika

**Comment by yantosca** [comment]
Thanks Monika for pointing that out.  The species database is now read from a YAML file, and is now case-sensitive.  I can fix the species names in the species database for patch version 12.9.2.

**Comment by yantosca** [comment]
I have fixed this issue by changing the tagged CO2 species names in the species_database.yml to e.g. `CO2ff', `CO2oc`, etc.  This was implemented in commit https://github.com/geoschem/geos-chem/commit/4e81c8ea8fb6c578a2d25298265cd231e46a8413.

When you add new species, make sure that the letters following CO2 are in lower case.  You can also add new tagged CO2 species to the species_database.yml as necessary.

**Comment by kimm1na** [comment]
@monszel  If you have experience with co2 simulation, do you have any ideas for this question( #1126 )? Thank you.
