### ISSUE TITLE
[BUG/ISSUE] HEMCO standalone config file not reading

### ISSUE THREAD

**Issue by lfreese** [geoschem/geos-chem#382]
### Expected behavior: ###
I'm trying to run HEMCO standalone with a pretty standard setup, only changing the root and metdir paths. 

### Actual behavior: ###
When I run ```./hemco_standalone.x HEMCO_sa_Config.rc``` I get: ```Please provide a HEMCO configuration file as input!```
However I've followed the wiki instructions and have the >>>include HEMCO_Config.rc in my HEMCO_sa_Config.rc file.

### Steps to reproduce: the bug:
As instructed in the wiki and in the standalone instructions I have edited the HEMCO_sa_Config.rc file: 
```###############################################################################
### BEGIN SECTION BASE EMISSIONS
###############################################################################

### Drop in a "HEMCO_Config.rc" file from a GEOS-Chem run directory here

>>>include HEMCO_Config.rc

### END SECTION BASE EMISSIONS ###
```
and have modified the root to my own HEMCO directories, as well as uncommenting the geos met data:
```
# Uncomment these lines if you are using GEOS-FP met fields!
METDIR:              /net/geoschem/data/gcgrid/data/ExtData/GEOS_4x5/GEOS_FP
MET:                 GEOSFP
met:                 geosfp
CNYR:                2011
RES:                 4x5
NC:                  nc
```

**Run commands**
1..  __```./hemco_standalone.x HEMCO_sa_Config.rc```

### Error messages
```
Please provide a HEMCO configuration file as input!```

## Required information:

### Your GEOS-Chem version and runtime environment:
 - GEOS-Chem version: __12.8.1
 - Compiler version: __intel/2017.0.1

**Comment by lizziel** [comment]
Hi @lfreese, it looks like you are using an older version of HEMCO. The HEMCO subdirectory in GEOS-Chem 12.8 does not work as HEMCO standalone. Is this what you are using?

We have new instructions for downloading and building HEMCO, now using the HEMCO repository on GitHub. This is still technically in development but we have unofficially released it for use as HEMCO standalone. The official release with be HEMCO 3.0.0 and will coincide with the GEOS-Chem 13.0.0 release this fall.

If you are not already using this, see http://wiki.seas.harvard.edu/geos-chem/index.php/HEMCO_installation_guide#Installing_HEMCO to get set up. I believe this should fix the issues you are encountering, but let us know if you still run into issues.

**Comment by lfreese** [comment]
Hi Lizzie, Thanks for the help! This does get rid of that error. I had been running things based on the directions here: http://wiki.seas.harvard.edu/geos-chem/index.php/HEMCO_standalone#Obtain_HEMCO_standalone_run_directory, but it seems this out of date to use HEMCO standalone? And in order to submit, I should be doing ```./hemco_standalone HEMCO_sa_Config.rc```

**Comment by lizziel** [comment]
Hi @lfreese, yes our documentation needs to be updated. We will be doing this for the upcoming GEOS-Chem 13.0.0 / HEMCO 3.0.0 release.

**Comment by yantosca** [comment]
Hi Lyssa.  Yes, right now HEMCO is in a bit of flux as there are many structural changes going in (mostly to facilitate connection to external models).  We will rewrite the documentation after the dust settles.

For HEMCO in 12.7.0 and higher, you can use this syntax:

```
./hemco_standalone.x -c HEMCO_sa_Config.rc
```
or for a dry-run:
```
./hemco_standalone.x -c HEMCO_sa_Config.rc --dryrun
```

**Comment by lizziel** [comment]
Hi @lfreese, I will close this issue now that it is resolved. I also want to make you aware that the HEMCO run directories created the new HEMCO repository include a script called runHEMCO.sh. You can use this to submit jobs to SLURM (if you use that system) or you can edit it for your own cluster or to submit locally.

**Comment by lizziel** [comment]
Also note that the executable is now hemco_standalone and not hemco_standalone.x.

**Comment by lfreese** [comment]
Thank you! This is all very helpful (especially that there is a dryrun option).

Lyssa
