### ISSUE TITLE
[BUG/ISSUE] There is an error in the MERRA2 file for 19831122

### ISSUE THREAD

**Issue by jaeinjeong** [geoschem/geos-chem#385]
Hi,
I download the input files from the website below.
http://geoschemdata.computecanada.ca
However, there is one error file, so I can't use it for the model.

ExtData/GEOS_0.5x0.625_AS/MERRA2/1983/11/MERRA2.19831122.I3.05x0625.AS.nc4

Thanks.

**Comment by yantosca** [comment]
Thanks for writing.  @jun-meng: can you check this out?

**Comment by Jun-Meng** [comment]
Hi, I have reprocessed the data for that day. It should be working fine now.

**Comment by yantosca** [comment]
Thanks @Jun-Meng.  I will close out this issue for now.
