### ISSUE TITLE
[FEATURE REQUEST] Use GEOS-FP 5.22 data for Jan - May 2020 and store GEOS-FP 5.25 for April - May 2020 as option

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#388]
NASA’s Global Modeling and Assimilation Office (GMAO) announced a major update to the GEOS-FP (“Forward-processing”) data stream. The switchover to GEOS-FP version 5.25.1 occurred on January 30, 2020. This new version contains the following updates to the GCM:

1. New convection scheme: The RAS convection scheme used to date has now been replaced with Grell & Freitas deep convection plus Park & Bretherton shallow convection.
2. New radiation scheme: The Chou-Suarez shortwave model has been replaced by RRTMG.

For more details, please read the [full announcement about the update to GEOS-FP 5.25.1](https://gmao.gsfc.nasa.gov/news/geos_system_news/2020/GEOS_FP_upgrade_5_25_1.php).

**_Andrea Molod (GMAO) wrote:_**

>FP525 began as our FP system on jan 30, 2020. however, about two months into the use of this system some serious issues were found. on april 7, 2020 a new system, that we are calling FP525_p5 (“patch 5”) went into production, with many of these issues addressed.
>just for everyone’s information, FP522 continued to run through this period. perhaps it would be good to “stay with” FP522 in the archives that GeosChem folks are using all the way to april 7.
>In addition to that, it is taking some time, but we at GMAO are still trying to benchmark the transport in the new systems as they emerge. FP525 (and p5) has a totally revamped set of parameterizations related to convection – a new deep convection and the addition of a separate shallow convection. there are indications that the shallow convection is quite active, augmenting transport from the surface to the middle troposphere (that Hongyu says is for the better), but this ends up “stranding” passive tracers in the mid-troposphere (no efficient mechanism to transport from there upward).

Following this recommendation, we will update the GEOS-Chem data archive at Compute Canada to use GEOS-5.22.0 fields for Jan 1 - Apr 6, 2020 and use GEOS-5.25.1-p5 fields for April 7 on. We can document this on both the GEOS-Chem wiki and on the Compute Canada site to make it clear that the change in convection and radiation schemes used to generate the met fields will now occur on April 7 in our GEOS-FP met fields. We'll also include the recommendation to use MERRA-2 when possible to avoid "jumps" in GEOS-Chem simulations.

Hongyu Liu wrote:
>It may be a good idea to send out an email to the GEOS-Chem mailing list when the archived GEOS-5.25.1 fields have been replaced with the GEOS-5.22.0 fields for Jan 1 - Apr 6, 2020 (some users may be using the GEOS-5.25.1 fields).

**Comment by msulprizio** [comment]
I am in the process of transferring the raw met fields from Discover to Dalhousie. @Jun-Meng will process the met fields and transfer to Compute Canada from there.

**Comment by Jun-Meng** [comment]
Thanks Melissa. I saw part of the data on Dalhousie Stetson. Are you using Globus? Do you have an idea about how long it will take to finish roughly?

**Comment by msulprizio** [comment]
I'm hoping by the end of next week. I'm using a combination of Globus to transfer the files I already had on Harvard's cluster and ssh to directly transfer the remaining files from Discover to Dalhousie.

**Comment by msulprizio** [comment]
@Jun-Meng wrote:

>The archiving of GEOS-FP 5.22 met fields for Jan - May 2020 has been completed. They are at the default GC met-field input directories under directory [‘ExtData’ on CCVM](http://geoschemdata.computecanada.ca/ExtData/). I added a README file in each directory. The alongside GEOS-FP 5.25 data for April and May 2020 are under directory ['Transfers/GEOSFP_525_processed/' on CCVM](http://geoschemdata.computecanada.ca/Transfers/GEOSFP_525_processed/). 

Sample README: http://geoschemdata.computecanada.ca/ExtData/GEOS_4x5/GEOS_FP/README
