### ISSUE TITLE
[BUG/ISSUE] HEMCO Standalone is writing LAI met twice, not running

### ISSUE THREAD

**Issue by arianatribby** [geoschem/geos-chem#395]
# Report a GEOS-Chem bug or technical issue

## Describe the bug:

I am attempting to run HEMCO Standalone with a standard setup and I've only changed the root/metdir paths. I followed the wiki instructions for installation. Compilation works, but when it comes to running the standalone, an error (see below) occurs from either HCOI_SA_Run or HCOI_SA_Init subroutines from .../HEMCO/Interfaces/hcoi_standalone_mod.F90. 

### Expected behavior: ###
I expect the standalone to produce nc4 files with emissions in an output directory.

### Actual behavior: ###
No nc4 files are produced, error printed to the command line.

### Steps to reproduce the bug:

**Compilation commands**
1.  make -j4 hcobuild in the run directory created using UT, as advised by the wiki

**Run commands**
1.  I then edit HEMCO_sa_Time.rc to the correct time period I want to run for, which I've made sure I have meteorology for.
2.  ./hemco_standalone.x HEMCO_sa_Config.rc

### Error messages
```
Reading part 1+2 of HEMCO configuration file: HEMCO_sa_Config.rc
Reading part 1+2 of HEMCO configuration file: HEMCO_Config.rc
Option is already defined - use original value of HEMCO_sa_Diagn.rc and ignore the following value: DiagnFile:                    HEMCO_Diagn.rc
Option is already defined - use original value of output/HEMCO_sa.diagnostics and ignore the following value: DiagnPrefix:                  HEMCO_diagnostics
Option is already defined - use original value of 00000001 000000 and ignore the following value: DiagnFreq:                    End
Option is already defined - use original value of 2 and ignore the following value: Unit tolerance:               1
HEMCO ERROR: Error: HEMCO field already exists:LAI
Error in HCOI_SA_INIT
HEMCO_STANDALONE FINISHED!
```
To attempt to debug, I added ```write(*,*) 'LINE=', LINE, '   cName=', TRIM(cName)``` to line 799 of file hco_config_mod.F90 (here is the permalink): 

https://github.com/geoschem/geos-chem/blob/4b605ef0d2451e4f640c19784fde1d00b4ddcc51/HEMCO/src/Core/hco_config_mod.F90#L796-L802

This allowed me to see that LAI was indeed being printed twice to the terminal before the error occurred. 

Here is the first instance: 
```LINE=* LAI       $METDIR/$YYYY/$MM/$MET.$YYYY$MM$DD.A1.$RES.$NC     LAI      1980-2018/1-12/1-31/0-23/+30minute C xy  1  * -  1 1                                                                                                                                     cName=LAI ```

And here is the second instance:  
```
LINE=* LAI      $METDIR/$YYYY/$MM/GEOSFP.$YYYY$MM$DD.A1.4x5.nc     LAI      2011-2018/1-12/1-31/0-23 C xy  1      * -   1 1                                                                                                                                           cName=LAI
HEMCO ERROR: Error: HEMCO field already exists:LAI
Error in HCOI_SA_INIT
HEMCO_STANDALONE FINISHED!
```

The first instance of LAI is from HEMCO_Config.rc, and the second is from HEMCO_sa_Config.rc. If I comment out that line from HEMCO_Config.rc, I get a segmentation fault error. However, if I comment out the line from HEMCO_sa_Config.rc, I get a new error that is the same, except that it says "T2M" already exists. I continued to comment out a handful of others, until I reached a new error message: 
```
Error in HCOI_SA_RUN
HEMCO_STANDALONE FINISHED!
```

I identified this error message to be coming from the following file (permalink included):
https://github.com/geoschem/geos-chem/blob/4b605ef0d2451e4f640c19784fde1d00b4ddcc51/HEMCO/src/Interfaces/hcoi_standalone_mod.F90#L209-L215

I printed RC, which = -999. I then tried adding print messages throughout the HCOI_SA_RUN subroutine. A print statement after the following call worked: 

https://github.com/geoschem/geos-chem/blob/4b605ef0d2451e4f640c19784fde1d00b4ddcc51/HEMCO/src/Interfaces/hcoi_standalone_mod.F90#L581-L588

But any other print statements caused segmentation faults. I have limited Fortran knowledge, so it may have been my error. In any case, I wasn't able to zero in on the exact place in the subroutine where the error is occurring. 

I also took a look at the HEMCO.log file (see attached below). It seems to be having trouble accessing a met variable from 2017/12/01, but why would it need a variable from that time period if I specified the standalone to run from 2018/04-06 on HEMCO_sa_Time.rc? 

I've attached the full output that was printed to the terminal (output.txt) below. 

### Your GEOS-Chem version and runtime environment:

 - GEOS-Chem version:  12.1.1
 - Compiler version: gfortran 2015
 - netCDF version: 4.6.1
 - netCDF-Fortran version (if applicable): __
 - Did you run on a computational cluster, on the AWS cloud: No, on my institutions' HPC
   - If you ran on the AWS cloud, please specify the Amazon Machine Image (AMI) ID: __
 - Are you using GEOS-Chem "out of the box" (i.e. unmodified): yes
   - If you have modified GEOS-Chem, please list what was changed: __

### Input and log files to attach

 - lastbuild: 
[lastbuild.txt](https://github.com/geoschem/geos-chem/files/5009500/lastbuild.txt)
 - HEMCO_Config.rc: 
[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/5009498/HEMCO_Config.txt)
[HEMCO_sa_Config.txt](https://github.com/geoschem/geos-chem/files/5009497/HEMCO_sa_Config.txt)
[HEMCO_sa_Time.txt](https://github.com/geoschem/geos-chem/files/5009504/HEMCO_sa_Time.txt)
 - HEMCO.log: [HEMCO.txt](https://github.com/geoschem/geos-chem/files/5009469/HEMCO.txt)
 - slurm.out or any other error messages from your scheduler: __
[output.txt](https://github.com/geoschem/geos-chem/files/5009493/output.txt)

**Comment by yantosca** [comment]
Thanks for writing.  I noticed that you are using 12.1.1 but there have been a bunch of updates to the standalone since then. You might want to grab a newer version since there have been many updates to the standalone since then.

In the later versions, the met field reading is now handled in the HEMCO_Config.rc (that you drop in) and not in the HEMCO_sa_Config.rc.  This is because newer versions of HEMCO use FlexGrid, which has the met data specifications placed in the HEMCO_Config.rc and not the HEMCO_sa_Config.rc.  That might prevent the LAI from being written out multiple times.

NOTE": The latest HEMCO standalone is in the HEMCO repository.  You can download the code and create a run directory with the following commands:
```
git clone -b dev/GC_13.0.0 https://github.com/geoschem/HEMCO.git
cd HEMCO/run
./createRunDir.sh  
change to the run directory that you just created
mkdir build
cd build
cmake ..
make -j install
cd ..
./hemco_standalone -c HEMCO_sa_Config.rc   
```

**Comment by arianatribby** [comment]
Thanks for your help. Will this prevent me from running the model in 12.1.1 when I am done running the standalone?

**Comment by yantosca** [comment]
I don't think so.  If you are using the standalone to generate data for a GEOS-Chem run, then you can just copy over the HEMCO_diagnostics*.nc files to a folder and then modify the HEMCO_Config.rc in the GEOS-Chem run directory to point to those.

**Comment by arianatribby** [comment]
Thank you. I compiled HEMCO with the new version you provided. I still have the older HEMCO_Config.rc file that corresponds with my version 12.1.1 runs. However, because it is older I ran into an issue with the absence of FLASH_DENS, which I added to my HEMCO_Config.rc file with the help from issue # 153. Now, I am getting an error with SPHU: 
```
/groups/POW/GEOS-CHEM/ExtData/GEOS_4x5/MERRA2/2018/04/MERRA2.20180401.I3.4x5.nc4
--> LOCATION: HCOIO_READ_STD (hcoio_read_std_mod.F90)
HEMCO WARNING: Data is treated as unitless, but file attribute suggests it is not: kg kg-1. File: /groups/POW/GEOS-CHEM/ExtData/GEOS_4x5/MERRA2/2018/04/MERRA2.20180401.I3.4x5.nc4
--> LOCATION: HCOIO_READ_STD (hcoio_read_std_mod.F90)
HEMCO WARNING: Data is treated as unitless, but file attribute suggests it is not: km-2 s-1. File: /groups/POW/GEOS-CHEM/ExtData//HEMCO/OFFLINE_LIGHTNING/v2020-03/MERRA2/2018/FLASH_CTH_MERRA2_0.5x0.625_2018_04.nc4
--> LOCATION: HCOIO_READ_STD (hcoio_read_std_mod.F90)
TIMEZONES (i.e. OFFSETS FROM UTC) WERE READ FROM A FILE
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
HEMCO ERROR: Cannot fill extension field SPHU
ERROR LOCATION: ExtDat_Set_3R (hcox_state_mod.F90)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
I checked my I3 met file, which doesn't have SPHU variable. My current config file has "SPHU1" and "SPHU2", but not "SPHU".

**Comment by msulprizio** [comment]
You will need to update the SPHU entry in your HEMCO_Config.rc. The latest version uses:

```
* SPHU     $METDIR/$YYYY/$MM/$MET.$YYYY$MM$DD.I3.$RES.$NC     QV        1980-2020/1-12/1-31/*           EFY xyz 1  * -  1 1
* SPHU_NEXTDAY $METDIR/$YYYY/$MM/$MET.$YYYY$MM$DD.I3.$RES.$NC QV        1980-2020/1-12/1-31/1/+1day     EFY xyz 1  * -  1 1
```

In GEOS-Chem 12.7.0, we updated to HEMCO 2.2.0 and that version included many fixes and updates to improve file I/O. See this wiki page for details: http://wiki.seas.harvard.edu/geos-chem/index.php/HEMCO_versions#HEMCO_development_history. 

If you can, it would probably be best for you to use the HEMCO_Config.rc that comes with the standalone, as it is up to date with GEOS-Chem 12.9.0 and contains many fixes since GEOS-Chem 12.1.1. You can always add any changes you made to the newer file.

**Comment by arianatribby** [comment]
Sorry if I am simply overlooking something, but I don't see a HEMCO_Config.rc that came with the standalone when I installed by following Bob's instructions. Here were some instructions that were printed to the screen when I created a new run directory (from createRunDir.sh): 
```
Enter path to the HEMCO_Config.rc file with your emissions settings.

NOTE: This may be a HEMCO_Config.rc file from a GEOS-Chem run directory
or a HEMCO_Config.template file from the GEOS-Chem source code repository.
```
But I can't find a HEMCO_Config.template file from the source code of this standalone? I looked in HEMCO/run and HEMCO/src. That is why I chose my old rc file but I would prefer to use the new one.

**Comment by msulprizio** [comment]
You are right. A HEMCO_Config.rc file does not come with the HEMCO standalone. I would recommend you clone a fresh copy of the GEOS-Chem 12.9.3 unit tester, then point to one of the HEMCO_Config.rc files there. That way, you'll get the latest fixes and updates to HEMCO_Config.rc and we have made sure the HEMCO standalone works with that version.

**Comment by arianatribby** [comment]
Thank you, this worked!

**Comment by yantosca** [comment]
Thanks @arianatribby!  We will close out this issue.  Feel free to reopen or to submit a new issue if you still have problems.

Also note: For the correpsonding HEMCO release that will go along with GC 13.0.0, we will have improved documentation on how to use the HEMCO standalone.  Right now a lot of things in HEMCO are in flux due to active development but we will be sure to provide better user documentation soon.
