### ISSUE TITLE
[BUG/ISSUE] Updated MAXAN in planeflight_mod.F90

### ISSUE THREAD

**Issue by jennyfisher** [geoschem/geos-chem#397]
## Describe the bug:
In planeflight_mod.F90, MAXAN is set to 15 (line 99 in current version on github), but there are now 19 AN components included (lines 1362-1365). This will cause the code to stop in `AN_SETUP`.

This is a simple fix - line 99 becomes:
`INTEGER,           PARAMETER   :: MAXAN     = 19`

This is based on GEOS-Chem version 12.9; whatever is current on Github as of 4 Aug 2020, as I've just checked the code here:
https://github.com/geoschem/geos-chem/blob/master/GeosCore/planeflight_mod.F90

**Comment by yantosca** [comment]
Thanks Jenny.  I will push to 12.9.3.  There is also another HEMCO fix going into this version (see https://github.com/geoschem/geos-chem/issues/391).

**Comment by yantosca** [comment]
Thanks for pointing this out, @jennyfisher!  This is now resolved by commit 1bc5d56db51a8eb963833c7013168b9155083936 and will go into 12.9.3 (to be released shortly).
