### ISSUE TITLE
[BUG/ISSUE] fatal error: "HEMCO/POPs/v2015-08/OCPO.geosfp.4x5.nc" "HEMCO/POPs/v2015-08/BCPO.geosfp.4x5.nc"does not exist

### ISSUE THREAD

**Issue by ruifeili** [geoschem/geos-chem#399]
# Report a GEOS-Chem bug or technical issue

## Describe the bug:
I want to simulate the PHE, BaP and PYR in 2014 on the AWS cloud. But I cannot download the needed data from AWS S3 when conducting the geosfp_4×5 POPs simulation.
### Expected behavior: ###

All the data can be download, then I can run the simulation.
### Actual behavior: ###

Fatal error occurred: two files are not exist in AWS S3. So I cannot run the simulation.
### Steps to reproduce: the bug:

1.  mkdir ~/GC  
2.  cd ~/GC 
3.  git clone https://github.com/geoschem/geos-chem Code.GC
4.  git clone https://github.com/geoschem/geos-chem-unittest.git UT
5.  cd UT/perl
6.  emacs CopyRunDirs.input # change the paths and un-comment the geosfp_4×5_POPs
7.  ./gcCopyRunDirs
8. cd ~/GC/geosfp_4x5_POP
9.  emacs input.geos #change the start and end time to 20140101 and 20140201
10.  make realclean
11.  make -j4 build

**Run commands**

1.  ./geos --dryrun > log.dryrun
2.  time ./download_data.py log.dryrun --aws
3.  __

### Error messages

```
fatal error: An error occurred (404) when calling the HeadObject operation: Key "HEMCO/POPs/v2015-08/BCPO.geosfp.4x5.nc" does not exist
fatal error: An error occurred (404) when calling the HeadObject operation: Key "HEMCO/POPs/v2015-08/OCPO.geosfp.4x5.nc" does not exist
```

### Your GEOS-Chem version and runtime environment:

 - GEOS-Chem version: __12.9.2
 - Compiler version: __
 - netCDF version: __
 - netCDF-Fortran version (if applicable): __
 - Did you run on a computational cluster, on the AWS cloud: __yes
   - If you ran on the AWS cloud, please specify the Amazon Machine Image (AMI) ID: __GEOSChem_12.7.0_tutorial_20200205
 - Are you using GEOS-Chem "out of the box" (i.e. unmodified): __
   - If you have modified GEOS-Chem, please list what was changed: __

### Input and log files to attach

 - lastbuild: __
 - input.geos: __
 - HEMCO_Config.rc: __
 - GEOS-Chem "Classic" log file: __
 - HEMCO.log: __
 - slurm.out or any other error messages from your scheduler: __
 - Any other error messages: __

### Additional context

I noticed that the similar error occurred in the tutorial video"Downloading data with a GEOS-Chem "dry-run" simulation". When conducting the geosfp_4×5_standard, the similar error occurred. And it was explained that these files have not yet uploaded. So I think if the support team upload the files which the POP simulation needs, the problem can be solved.

**Comment by yantosca** [comment]
Thanks for writing.  This is probably because the `BCPO.geosfp.4x5.nc` file is symbolically linked to `BCPO.geos5.4x5.nc` and the `OCPO.geosfp.4x5.nc` file is symbolically linked to `OCPO.geos5.4x5.nc`.  I think when we sync files from the Harvard server to AWS, symbolic links might get picked up (because AWS S3 is not a Unix-like system).

As a quick fix, update the lines in your HEMCO_Config.rc from:
```
1002 GLOBAL_OC   $ROOT/POPs/v2015-08/OCPO.$met.$RES.nc              OCPO           2005-2009/
1-12/1/0 C xyz 1       * - 1 1
1002 GLOBAL_BC   $ROOT/POPs/v2015-08/BCPO.$met.$RES.nc              BCPO           2005-2009/1-12/1/0 C xyz 1       * - 1 1
```
to:
```
1002 GLOBAL_OC   $ROOT/POPs/v2015-08/OCPO.geos5.$RES.nc              OCPO           2005-2009/
1-12/1/0 C xyz 1       * - 1 1
1002 GLOBAL_BC   $ROOT/POPs/v2015-08/BCPO.geos5.$RES.nc              BCPO           2005-2009/1-12/1/0 C xyz 1       * - 1 1
```
and then I think the dry-run will pick them up.

**Comment by ruifeili** [comment]
Thank you for help. The problem has been solved.
