### ISSUE TITLE
[BUG/ISSUE] species_database.yml contains MW:g rather than MW_g

### ISSUE THREAD

**Issue by fritzt** [geoschem/geos-chem#400]
## Describe the bug:
The YAML species database contains `MW:g` rather than the conventional `MW_g` for `OPOG1` and `OPOG2`. 
Similarly, I noticed that `DD_Hstar` is occasionally replaced by `DD_HStar`. 

### Expected behavior: ###
Molar weights (and other species characteristics) should be read from species_database.yml
`OPOG1` and `OPOG2` list molar weights as `MW:g` rather than `MW_g`.
Molar weights should be positive.

### Actual behavior: ###
When running a `complexSOA_SVPOA` simulation, `OPOG1` and `OPOG2` have molar weights of -999.0, which is the missing value in `species_mod.F90`.

### Steps to reproduce the bug:
None

### Your GEOS-Chem version and runtime environment:
 - GEOS-Chem version: 12.9.1
 - Compiler version: -
 - netCDF version: -
 - netCDF-Fortran version (if applicable): -
 - Did you run on a computational cluster, on the AWS cloud: No
 - Are you using GEOS-Chem "out of the box" (i.e. unmodified): Yes
   - If you have modified GEOS-Chem, please list what was changed: -

### Input and log files to attach
**None needed**

**Comment by yantosca** [comment]
Thanks @fritzt for catching this.  This is now corrected in commit 284543da0e17335ba2dd6ca6956661ad9e692918, which will be included in bug fix version 12.9.3.
