### ISSUE TITLE
[BUG/ISSUE] Error "Infinity in DO_CLOUD_CONVECTION"

### ISSUE THREAD

**Issue by ltmurray** [geoschem/geos-chem#402]
Hi all, I'm experiencing issue #275 with out-of-the-box nested North American runs using GEOS-FP meteorology and the standard mechanism in 12.9.3, so it appears the underlying problem is still present. It doesn't seem to matter when the simulations start, they go about 8 days before crashing as previously described by @RajMLal and @jennyfisher. I'll update if I figure out what's going on.

**Comment by ltmurray** [comment]
And for me, the culprit species is N2O.

**Comment by ltmurray** [comment]
In my case, the UCX_NOX subroutine at the native resolution tries to divide by LOCALO3 when it is zero, generating a NaN.  The NaNs then grow via advection until one enters the troposphere, where it encounters its first NaN check in DO_CLOUD_CONVECTION. Since UCX_NOX is not called in @RajMLal or @jennyfisher use cases, they are probably also just seeing NaNs generated elsewhere in the code that then trigger the trap in convection.

It may be useful to add a check for NaN or Inf in the main loop at the end of the dynamic timestep, to force the model to gracefully stop closer to the origin of the NaN generation. In my case, the model continued to run for a few days before the error was caught.

**Comment by yantosca** [comment]
I can put in a fix in UCX_NOX to make sure that we do a safe division.  I think we used to have a check for NaN's but this was causing a computational bottleneck, so we took it out.

**Comment by yantosca** [comment]
This issue has been resolved with commit 3195f752b2300af9590536b6666cf52e14f2955e.  We have now placed checks into the code to prevent div-by-zero errors.  See:

https://github.com/geoschem/geos-chem/blob/3195f752b2300af9590536b6666cf52e14f2955e/GeosCore/ucx_mod.F90#L467-L477

and

https://github.com/geoschem/geos-chem/blob/3195f752b2300af9590536b6666cf52e14f2955e/GeosCore/ucx_mod.F90#L513-L522

We can therefore close out this issue.

**Comment by yantosca** [comment]
Note, the commit mentioned in the prior comment was never merged into the mainstream.  The correct commit tag is now ise4a632bf4d5f8790797c8b6b3f84d883cf867261.

**Comment by RuijunDang** [comment]
Hi @ltmurray, I am running the nested version of 12.9.3 and experiencing the same problem as you did. The simulation just stopped after a few days running, and the species is also N2O. I wonder how you resolve it in the end?
