### ISSUE TITLE
[BUG/ISSUE] ProdLoss diagnostic units variable is set to Kg s-1 in NetCDF output

### ISSUE THREAD

**Issue by tsherwen** [geoschem/geos-chem#404]
# Report a GEOS-Chem bug or technical issue

## Describe the bug:

The incorrect units for the prodloss diagnostic (Prod_*/Loss_*) are outputted to the NetCDF units variable. 

### Expected behavior: ###

The units for the prod/loss diagnostic within the Tropchem simulation should be 'molec cm-3 s-1'.

### Actual behavior: ###

Units of "Kg s-1" are stated in the NetCDF file.  Link posted below to test directory of output.

https://webfiles.york.ac.uk/WACL/SHERWEN_TOMAS/TEMP/GCST/ProdLoss/geosfp_4x5_tropchem.v12.6.0.TEST/

### Steps to reproduce: the bug:

Running Tropchem model (v12.6.0), outputting ProdLoss via HISTORY.rc.

Compiled in the out-of-the-box model in the run directory.  

### Your GEOS-Chem version and runtime environment:
 - GEOS-Chem version: v12.6.0
 - Compiler version: ifort 18.0.3
 - Are you using GEOS-Chem "out of the box" (i.e. unmodified): Y

### Input and log files to attach

Entire test directory hosted at link below. 

https://webfiles.york.ac.uk/WACL/SHERWEN_TOMAS/TEMP/GCST/ProdLoss/geosfp_4x5_tropchem.v12.6.0.TEST/

### Additional context

The units are stated as  'molec cm-3 s-1' in `flexchem_mod.F90`, as pasted below.

       !====================================================================
       ! HISTORY (aka netCDF diagnostics)
       !
       ! Prod and loss of families or species [molec/cm3/s]
       !
       ! NOTE: KppId is the KPP ID # for each of the prod and loss
       ! diagnostic species.  This is the value used to index the
       ! KPP "VAR" array (in module gckpp_Global.F90).
       !====================================================================

       ! Chemical loss of species or families [molec/cm3/s]
       IF ( State_Diag%Archive_Loss ) THEN
          DO F = 1, State_Chm%nLoss
             KppID                    = State_Chm%Map_Loss(F)
             State_Diag%Loss(I,J,L,F) = VAR(KppID) / DT
          ENDDO
       ENDIF

       ! Chemical production of species or families [molec/cm3/s]
       IF ( State_Diag%Archive_Prod ) THEN
          DO F = 1, State_Chm%nProd
             KppID                    = State_Chm%Map_Prod(F)
             State_Diag%Prod(I,J,L,F) = VAR(KppID) / DT
          ENDDO
       ENDIF

An option in `Get_Metadata_State_Diag` provides the units for the NetCDF variable and as Tropchem is being run, the units should have been set to  'molec cm-3 s-1'.

    ELSE IF ( TRIM( Name_AllCaps ) == 'LOSS' ) THEN
       IF ( IsDesc    ) Desc  = 'Chemical loss of'
       IF ( isRank    ) Rank  = 3
       IF ( isTagged  ) TagId = 'LOS'

       ! NOTE: Units are different depending on simulation, due to historical
       ! baggage.  Maybe clean this up at a later point to use the same units
       ! regardless of simulation type. (bmy, 12/4/17)
       IF ( isUnits   ) THEN
          IF ( IsFullChem ) THEN
             Units = 'molec cm-3 s-1'
          ELSE
             Units = 'kg s-1'
          ENDIF
       ENDIF

    ELSE IF ( TRIM( Name_AllCaps ) == 'PROD' ) THEN
       IF ( isDesc    ) Desc  = 'Chemical production of'
       IF ( isRank    ) Rank  = 3
       IF ( isTagged  ) TagId = 'PRD'

       ! NOTE: Units are different depending on simulation, due to historical
       ! baggage.  Maybe clean this up at a later point to use the same units
       ! regardless of simulation type. (bmy, 12/4/17)
       IF ( isUnits   ) THEN
          IF ( IsFullChem ) THEN
             Units = 'molec cm-3 s-1'
          ELSE
             Units = 'kg s-1'
          ENDIF
       ENDIF

**Comment by yantosca** [comment]
Thanks Tomas.  We can fix this in 13.0.0.

**Comment by yantosca** [comment]
I had a chance to look at this.  In the 13.0.0 development code we have:

```
        float Loss_CH4(time, lev, lat, lon) ;
                Loss_CH4:long_name = "Chemical loss of CH4" ;
                Loss_CH4:units = "molec cm-3 s-1" ;
                Loss_CH4:_FillValue = -1.e+31f ;
                Loss_CH4:averaging_method = "time-averaged" ;
        float Loss_CO(time, lev, lat, lon) ;
                Loss_CO:long_name = "Chemical loss of CO" ;
                Loss_CO:units = "molec cm-3 s-1" ;
                Loss_CO:_FillValue = -1.e+31f ;
                Loss_CO:averaging_method = "time-averaged" ;
        float Loss_Ox(time, lev, lat, lon) ;
                Loss_Ox:long_name = "Chemical loss of Ox" ;
                Loss_Ox:units = "molec cm-3 s-1" ;
                Loss_Ox:_FillValue = -1.e+31f ;
                Loss_Ox:averaging_method = "time-averaged" ;
        float Prod_H2O2(time, lev, lat, lon) ;
                Prod_H2O2:long_name = "Chemical production of H2O2" ;
                Prod_H2O2:units = "molec cm-3 s-1" ;
                Prod_H2O2:_FillValue = -1.e+31f ;
                Prod_H2O2:averaging_method = "time-averaged" ;
        float Prod_SO4(time, lev, lat, lon) ;
                Prod_SO4:long_name = "Chemical production of SO4" ;
                Prod_SO4:units = "molec cm-3 s-1" ;
                Prod_SO4:_FillValue = -1.e+31f ;
                Prod_SO4:averaging_method = "time-averaged" ;
        float Prod_CO(time, lev, lat, lon) ;
                Prod_CO:long_name = "Chemical production of CO" ;
                Prod_CO:units = "molec cm-3 s-1" ;
                Prod_CO:_FillValue = -1.e+31f ;
                Prod_CO:averaging_method = "time-averaged" ;
        float Prod_Ox(time, lev, lat, lon) ;
                Prod_Ox:long_name = "Chemical production of Ox" ;
                Prod_Ox:units = "molec cm-3 s-1" ;
                Prod_Ox:_FillValue = -1.e+31f ;
                Prod_Ox:averaging_method = "time-averaged" ;
```
So it seems that the unit string is being assigned correctly.

Also note: The other prod/loss diagnostics are mostly updated in sulfate_mod.F90, and are reported as kg/s. 

I don't know if this is what you saw but I could not replicate it.

**Comment by tsherwen** [comment]
Thanks for trying to replicate this in 13.0.0 Bob. 

I am not sure why the out-of-the-box test I did in v12.6.0 gave a different result (exact file linked below). 

https://webfiles.york.ac.uk/WACL/SHERWEN_TOMAS/TEMP/GCST/ProdLoss/geosfp_4x5_tropchem.v12.6.0.TEST/OutputDir/GEOSChem.ProdLoss.20160101_0000z.nc4

The values of the output seem to make sense if I assume the units are `"molec cm-3 s-1"`, but I will explore more this week. 

I also note that now each new Prod/loss flag needs to be manually added to the species database with a `Is_Gas` flag set to true. Maybe we could have a default setting for the prod loss tracers? 

My response is delayed as I have been away on annual leave.

**Comment by yantosca** [comment]
I will remove this issue from the 13.0.0 milestone, as it seems that we do not yet have a definite resolution.

**Comment by yantosca** [comment]
I will close out this issue for now.  If it still persists, please feel free to reopen.
