### ISSUE TITLE
[BUG/ISSUE] stratospheric loss in CH4 simulation v12.9.3

### ISSUE THREAD

**Issue by febfly** [geoschem/geos-chem#410]
I notice a change in global_ch4_mod.F90 in recent version (12.9.3) that now stratospheric loss is executed only when UCX is turned on (See code snippet below; within CHEMCH4 subroutine of global_ch4_mod.F90 ). 

![image](https://user-images.githubusercontent.com/8473067/90473135-c2cdef80-e154-11ea-84af-ecc933d2dd71.png)

There is no this "if (input_opt%LUCX) ..." clause in previous versions (v11.x), so I wonder what have been changed in the new version and where the program now computes stratospheric methane loss if UCX is not turned on (which is a normal setting for a CH4 only simulation). I suspect this change is incorrect because the current CH4_STRAT still reads in archived stratospheric loss rather than use information from UCX calculation.

Thanks!

Yuzhong

**Comment by msulprizio** [comment]
Hi Yuzhong. Thanks for pointing this out. You are correct. This appears to be a bug that came in with commit https://github.com/geoschem/geos-chem/commit/61d0c1daa4f2a462a69d6c667ba27b63540dc119 in GEOS-Chem 12.9.0. Subroutine CHEMCH4 should only be called for CH4 simulations, and never for full-chemistry (including UCX-based) simulations, so the IF statement here is not needed and can be removed. We will correct this in our next release.

**Comment by msulprizio** [comment]
This is now fixed in the dev/13.0.0 branch in commit https://github.com/geoschem/geos-chem/commit/4be9922dcc9beaf11494faed148e50ca7bb3f8af.

**Comment by febfly** [comment]
Thanks Melissa!
