### ISSUE TITLE
[FEATURE REQUEST] jvalues in planeflights

### ISSUE THREAD

**Issue by ktravis213** [geoschem/geos-chem#412]
# Request a new GEOS-Chem feature
Hi support team!  In planeflight_mod.F90, could we please add back in jvalues (at least jNO2 and jO1D), and if possible, the reaction rates that use to exist pre-flexchem?   This is very useful for aircraft comparisons!

**Comment by msulprizio** [comment]
See similar feature request: https://github.com/geoschem/geos-chem/issues/132

We have not been able to prioritize updating the planeflight diagnostic with all of the other model development priorities, however we would happily encourage someone in the community to take this on. I believe this can be accomplish simply by accessing the values in the `ZPJ` array (from CMN_FJX_mod.F90). See uses of `ZPJ` in fast_jx_mod.F90 for reference.

**Comment by ktravis213** [comment]
Oh I completely forgot we already requested this! Thanks, I will work on it.

**Comment by tsherwen** [comment]
Hello @ktravis213/@msulprizo, please could I check if you have been able to make any progress on this? or know if anyone else has? I need to extract photolysis rates for our recent aircraft campaign, so need to have this functionality active again and happy to contribute.

**Comment by msulprizio** [comment]
The GCST has not had time to work on this item. I'm not sure if @ktravis213 made any progress.

**Comment by yantosca** [comment]
I am going to close out this issue, as it is a duplicate of #132, which is still open.
