### ISSUE TITLE
[BUG/ISSUE] CH4-only simulaation bug in reading achived OH and Cl field for version 12.9.3

### ISSUE THREAD

**Issue by febfly** [geoschem/geos-chem#415]
Hi,
I notice a bug was introduced in a recent version (12.9.3) regarding reading in archived OH and Cl fields for CH4 simulation, where the Cl field is erroneously assigned to BOH (and therefore overwrites the original BOH) (see code snippet below). Since archived Cl and OH are in very different unit, this will crash the simulation. 
![image](https://user-images.githubusercontent.com/8473067/91249363-4e650300-e789-11ea-8664-9d329c4600b2.png)

Yuzhong

**Comment by msulprizio** [comment]
Hi Yuzhong! Thanks for pointing out this typo. It is now fixed in commit https://github.com/geoschem/geos-chem/commit/5bd6f302e5b5b8faeeb27e592aed6b452abd4522 and will be included in 13.0.0.
