### ISSUE TITLE
[QUESTION]How could I add a new species into the restart files?

### ISSUE THREAD

**Issue by yutao-chen** [geoschem/geos-chem#419]
I have added a new species into database. How could I add its attributes in the restart file?

**Comment by yutao-chen** [comment]
In other words, how to add sth into an NETCDF file ?

**Comment by msulprizio** [comment]
Please see this post on the GEOS-Chem wiki for guidance on adding new species to GEOS-Chem restart files: http://wiki.seas.harvard.edu/geos-chem/index.php/Working_with_netCDF_data_files#Adding_a_new_variable_to_a_netCDF_file.

**Comment by yutao-chen** [comment]
Thank you for your advice.    But When I run the python file  following the reference, it shows an error said "No module named netCDF4."   Fogive me for the easy question , as I have never used the Python before.

**Comment by yutao-chen** [comment]
> Please see this post on the GEOS-Chem wiki for guidance on adding new species to GEOS-Chem restart files: http://wiki.seas.harvard.edu/geos-chem/index.php/Working_with_netCDF_data_files#Adding_a_new_variable_to_a_netCDF_file.

Thank you for your advice. But When I run the python file following the reference, it shows an error said "No module named netCDF4." Fogive me for the easy question , as I have never used the Python before.

**Comment by jinlx** [comment]
It looks like just a depency issue. You may need to install netCDF4 in python (see https://pypi.org/project/netCDF4/) before run the script.
