### ISSUE TITLE
[QUESTION] C2H6_2010 

### ISSUE THREAD

**Issue by barronh** [geoschem/geos-chem#421]
In the HEMCO_Config.rc file, the C2H6 inventory has oilgas emissions as category 1 and biofuels as category 2 and both are hierarchy 100. The hierarchy 100 is the highest of any emission inventory. This has the effect of overwriting any region or globally specified C2H6 from any anthropogenic sectors. For example, all sectors from CEDS, MIX, DICE, and NEI 2011/2016 are overwritten. In fact, I think the only ethane emissions are from C2H6_2010 and AEIC.

My guess would be that this configuration predates having so many explicit ethane sources. Is this desirable?

**Comment by msulprizio** [comment]
The current recommendation from the Emissions & Deposition Working Group is to use the C2H6 emissions from Tzompa et al. (2017) (aka `C2H6_2010` in HEMCO_Config.rc for 12.6.3 and earlier or `TZOMPASOSA_C2H6` for 12.7.0 and later) over all other regional and global inventories. See [this table](http://wiki.seas.harvard.edu/geos-chem/index.php/Emissions_and_Deposition_Working_Group#Recommended_Default_Emission_Inventories). 

This topic came up again recently in a GEOS-Chem Steering Committee discussion on implementing the new CEDS emissions inventory as default. Daniel Jacob wrote:

>Following on Jenny’s question, what do you recommend that we do for C2H6 (currently Tzompa) and C3H8 (currently Xiao)? Older inventories used to greatly underestimate those emissions because they didn’t properly account for the natural gas source, has the problem gone away?
 
Erin McDuffie responded:
>That’s a great question. I haven’t looked at these species specifically, so others might have more insight than I do. My sense is that there has been a lot work to improve these emissions in the regional/national inventories, but that uncertainties in the oil and gas sector persist. Since the RETRO VOC ratios are also a bit older, it could also be that the total NMVOCs have improved accuracy in the latest inventory, but that the relative contributions of alkanes are not reflected. VOC speciation is definitely known inventory uncertainty, as discussed in the original CEDS paper and the most recent EDGAR inventory paper.

**Comment by Zitely** [comment]
TzompaSosa_C2H6 used 2010 spaceborne methane observations to derive C2H6 emissions. Previous C2H6 emission inventories were based on activity data prior to the 1980's. The current recommendation for using TzompaSosa_2010 is based on the rapid change that the oil and gas industry has had over the last two decades. These changes have continued after 2010 (e.g. the oil and gas activities in the Bakken in North Dakota and Montana, U.S.). As newer C2H6 emission estimates become available, TzompaSosa_2010 can be overwritten for those areas. In the specific case of the NEI2016, my recommendation is to overwrite TzompaSosa_2010 with those.
