### ISSUE TITLE
[BUG/ISSUE] Adding new species for BB/ND28 dianostics in bpch files

### ISSUE THREAD

**Issue by jinlx** [geoschem/geos-chem#422]
Hi,

I am trying to add some new VOC species from BB inventories raw data into bpch files for BB/ND28 diagnostics in GC.12.5.0

I tried two ways however getting same results- the species can be added in ./OurputDir/HEMCO_diagnostics.*.nc but not show up in trac_avg.geosfp_4x5_tropchem.* bpch fles.

Using adding MOH in GFED4 as an example. 
1) First way I tired is changing code in HEMCO_Config.rc from 
```
111     GFED                   : on   NO/CO/ALK4/ACET/MEK/ALD2/PRPE/C3H8/CH2O/C2H6/SO2/NH3/BCPO/BCPI/OCPO/OCPI/POG1/POG2/MTPA/BENZ/TOLU/XYLE/NAP/EOH/SOAP/DMS
```
to

```
111     GFED                   : on    NO/CO/ALK4/ACET/MEK/ALD2/PRPE/C3H8/CH2O/C2H6/SO2/NH3/BCPO/BCPI/OCPO/OCPI/POG1/POG2/MTPA/BENZ/TOLU/XYLE/NAP/EOH/SOAP/DMS/MOH
```
and adding MOH BB source into HEMCO_Diagn.rc

```
EmisMOH_BioBurn    MOH    0     -1   -1   2   kg/m2/s  MOH_emission_flux_from_biomass_burning
```
2) The other way I tired creating GFED4 species data from hmco standalone first and then substitue input files in HEMCO_Config.rc as well as changing code in HEMCO_Diagn.rc. This method is similar to  #383 .

However, these two ways got same results as I mentioned. Do you have any insight on this issue? Or do you recommend another way to try adding ND28 species into bpch output?

Thanks,
Lixu

**Comment by lizziel** [comment]
We are no longer supporting expanding the binary diagnostic output unless an equivalent diagnostic is not available in netCDF. For the case of ND28, [the biomass burning emissions binary output was removed in 12.7.0](http://wiki.seas.harvard.edu/geos-chem/index.php/List_of_diagnostics_archived_to_bpch_format#ND28:_Biomass_burning_emissions). Is netcdf sufficient for what you would like to do? HEMCO_Diagn.rc is used to configure the emissions diagnostics in netcdf format only. Let us know if you would like further guidance on this.

**Comment by jinlx** [comment]
Thanks @lizziel ! It looks like the biggest change from old version(12.5.0) I am using and new versions after 12.7.0 is bpch output are removed. But the netcdf in Outdir is the same. Am I unstanding it right?

**Comment by jinlx** [comment]
Hey @lizziel . I tried GC12.9.3. It works pretty nice for hemco diagnostics. But it looks like it can't create ND51/ND51b output even though the simulation can be done and it has some issue in ND40 as well. I will test it further and create another request pretty soon to discuss this issue.

Cheers,
Lixu

**Comment by lizziel** [comment]
Thanks Lixu!
