### ISSUE TITLE
[BUG/ISSUE] An error said could not locate KPP prod/loss species :POx!

### ISSUE THREAD

**Issue by yutao-chen** [geoschem/geos-chem#423]
![image](https://user-images.githubusercontent.com/67720119/91701319-aea0de00-eba9-11ea-8837-d92212bad31e.png)

**Comment by lizziel** [comment]
Hi @yutao-chen, please see our [wiki post on what to include in a help request](http://wiki.seas.harvard.edu/geos-chem/index.php/Submitting_GEOS-Chem_support_requests#What_do_I_need_to_include_in_my_support_request.3F). We will need additional information before we can help figure out what is going wrong. You can drag and drop any text file into the issue comment box by renaming to have file extension '.txt'

**Comment by yutao-chen** [comment]
I use GEOS-Chem11-02.   I add several new species and their reactions through species_database_mod.F90 and KPP .The mechanism has built successfully .Each new species has an index in /KPP/Custom/gckpp_Parameters.F90 . Now I  put these species into "ADVECTED SPECIES MENU" of " input.geos" after "Species : pFe".   I "make -j4 NC_DIAG=y mpbuild CHEM=Custom" successfully but run failed. The error is like the picture above and I guess that the cause of this error is  related to not find the index of some species in KPP/Custom/gckpp_Parameters.F90.  (I'm not sure.)                                                                                     

[KPP Custom gckpp.kpp.txt](https://github.com/geoschem/geos-chem/files/5154775/KPP.Custom.gckpp.kpp.txt)
[input.geos.txt](https://github.com/geoschem/geos-chem/files/5154818/input.geos.txt)
[last build.mp.txt](https://github.com/geoschem/geos-chem/files/5154819/last.build.mp.txt)

**Comment by yutao-chen** [comment]
> Hi @yutao-chen, please see our wiki post on what to include in a help request. We will need additional information before we can help figure out what is going wrong. You can drag and drop any text file into the issue comment box by renaming to have file extension '.txt'
Hi！  I use GEOS-Chem11-02. I add several new species and their reactions through species_database_mod.F90 and KPP .The mechanism has built successfully .Each new species has an index in /KPP/Custom/gckpp_Parameters.F90 . Now I put these species into "ADVECTED SPECIES MENU" of " input.geos" after "Species : pFe". I "make -j4 NC_DIAG=y mpbuild CHEM=Custom" successfully but run failed. The error is like the picture above and I guess that the cause of this error is related to not find the index of some species in KPP/Custom/gckpp_Parameters.F90. (I'm not sure.)
[input.geos.txt](https://github.com/geoschem/geos-chem/files/5154836/input.geos.txt)
[KPP Custom gckpp.kpp.txt](https://github.com/geoschem/geos-chem/files/5154837/KPP.Custom.gckpp.kpp.txt)
[last build.mp.txt](https://github.com/geoschem/geos-chem/files/5154838/last.build.mp.txt)

**Comment by msulprizio** [comment]
@yutao-chen Could you also attach a copy of your modified Custom.eqn file? I'd like to make sure your new species are defined there as well.

**Comment by yutao-chen** [comment]
> @yutao-chen Could you also attach a copy of your modified Custom.eqn file? I'd like to make sure your new species are defined there as well.

Yes , I defined.   The mechanism has built successfully.
[Custom.equ.txt](https://github.com/geoschem/geos-chem/files/5159551/Custom.equ.txt)

**Comment by yutao-chen** [comment]
> @yutao-chen Could you also attach a copy of your modified Custom.eqn file? I'd like to make sure your new species are defined there as well.

Dear msulprizio:   I finally know the cause of the error.  I compared the KPP/Standard/gckpp_Parameters.F90 and the KPP/Custom/gckpp_Parameters.F90 finding that the "FAMILY POx" Species are transformed to the format of "RR number" in KPP/Custom/gckpp_Parameters.F90  , so those species are not able to identified. May be it is because the bug in kpp . I don't know how to correct them .  The comparison file are below.
[gckpp_Parameters.F90.txt](https://github.com/geoschem/geos-chem/files/5161033/gckpp_Parameters.F90.txt)
[gckpp_Parameters1.F90.txt](https://github.com/geoschem/geos-chem/files/5161034/gckpp_Parameters1.F90.txt)

**Comment by yutao-chen** [comment]
I "make" the kpp-2.2.3_01 again and the warning file is below.
[remake the kpp2.2.3_01.txt](https://github.com/geoschem/geos-chem/files/5161732/remake.the.kpp2.2.3_01.txt)

**Comment by yutao-chen** [comment]
Dear msulprizio: I have solved my problem already.  Thank you so much .

**Comment by msulprizio** [comment]
OK thanks for letting us know. I will close this issue.

**Comment by xpye98** [comment]
> Dear msulprizio: I have solved my problem already. Thank you so much .

Hi,
How did you solve your problem? I met the same error.
Thanks
