### ISSUE TITLE
[FEATURE REQUEST] GC-YIBs biosphere-atmospheric chemistry coupled model

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#425]
Xu Yue (NUIST) wrote:

>I am writing to introduce our recent progresses on the development of global chemistry-vegetation model (GC-YIBs V1.1).
>
>As a near-term priority set by Chemistry-Ecosystem-Climate Working group, GC-YIBs becomes available with the great efforts made by Yadong Lei (my student), Cheng Gong (Prof. Hong Liao’s student), Prof. Liao, and me. The GC-YIBs is a coupled chemistry-vegetation model developed by implementing the Yale Interactive terrestrial Biosphere (YIBs) model version 1.0 into GEOS-Chem version 12.0.0. It is an important step of GC development to be a unique tool for the ecosystem-chemistry interactions.
>
>By coupling with YIBs vegetation model, the GC model can now dynamically predict:
>
> (1) leaf area index (daily) for biogenic emissions;
>(2) land fluxes (hourly) for global carbon cycle (instead of a box model);
>(3) process-based stomatal conductance (hourly) for dry deposition of air pollutants;
>(4) inhibition effects of ozone (hourly) on vegetation photosynthesis.
>
>The details of the model development and evaluations are presented in our recent publications: Lei Y, Yue X, Liao H, Gong C, Zhang L (2020) Implementation of Yale Interactive terrestrial Biosphere model v1.0 into GEOS-Chem v12.0.0: a tool for biosphere-chemistry interactions. Geoscientific Model Development, 13, 1137-1153.
>
>Here, we would like to share the codes with the whole GC community. The latest codes which accommodate all three resolutions (4°×5°, 2°×2.5°, and 0.5°×0.625°) are located at: https://zenodo.org/record/3993832. The input data, however, are huge in size (>100 G). We can upload them to a proper server (e.g., Harvard FTP) for use.
>
>We are glad to make the contributions to GEOS-Chem development. Please let us know your advices on this update.

**Comment by yantosca** [comment]
As discussed at the [GCSC telecon on 03 Sep 2020](http://acmg.seas.harvard.edu/geos/word_pdf_docs/steering_cmte/gc_sc_minutes_03Sep2020.pdf), the Tai group at Chinese University of Hong Kong will maintain the GC-YIBs model and ensure that it stays up-to-date with the latest version of GEOS-Chem.

**Comment by yantosca** [comment]
I am going to close out this feature request, as the GC-YIBs model will be developed and hosted elsewhere (at NUIST or at Hong Kong), and thus there are no action items for the GCST to fulfill.
