### ISSUE TITLE
[BUG/ISSUE] Typo in  mercury_mod.F about saving EmisHg0land

### ISSUE THREAD

**Issue by wintriv** [geoschem/geos-chem#430]
# Report a GEOS-Chem bug or technical issue

## Describe the bug:
I found a typo in the code in mercury_mod.F inside SUBROUTINE SRCHg0 at the lines that read:

         ! Land Hg0 emissions [kg/s]
         IF ( State_Diag%Archive_EmisHg0ocean ) THEN
            State_Diag%EmisHg0land(I,J) = EHg0_ln(I,J,1)
         ENDIF

Should it in fact be like this? 

         ! Land Hg0 emissions [kg/s]
         IF ( State_Diag%Archive_EmisHgLand ) THEN
            State_Diag%EmisHg0land(I,J) = EHg0_ln(I,J,1)
         ENDIF

### Expected behavior: ###

I guess when both ocean and land emission are on, the State_Diag recorded the right values to the right place, i.e. Hg0 ocean emission to EmisHg0ocean and the land Hg0 emisssion to EmisHg0land.  But better correct the code in the upcoming release.

### Actual behavior: ###

The output for land Hg0 emission doesn't look like ocean emission, so the current code did save the land emission to EmisHg0land.

### Your GEOS-Chem version and runtime environment:

 - GEOS-Chem version: __12.6.1

**Comment by msulprizio** [comment]
Thanks for pointing out this typo. It is now fixed in https://github.com/geoschem/geos-chem/commit/9f2e1a0455ff29b43b9d39c24e89ac140ce5a13c and will be included in 13.0.0.
