### ISSUE TITLE
[BUG/ISSUE]GC12.9.3 can't create ND51 output and can't read in ND40 input as well

### ISSUE THREAD

**Issue by jinlx** [geoschem/geos-chem#436]
Hi,

I am trying to get satellite timeseries output (ND51) and ND40 ouput in GC12.9.3 tropchem 4x5. However, from my experience, GC can't create any ND51 output in netcdf and bpch. The code is what I tried input.geos.

1. bpch 
```
%%% ND51 MENU %%%       :
Turn on ND51 diagnostic : T
LT avg timeseries file  : ./ts_satellite/ts_satellite.YYYYMMDD.bpch
Output as HDF5?         : F
Tracers to include      : 1 2 20 26 46 64 66 77 107 501 503 507 511 512 513 516
GMT Hour for disk write :   0
Avg Period [LT hours]   :   9  10
IMIN, IMAX of region    :   1  72
JMIN, JMAX of region    :   1  46
LMIN, LMAX of region    :   1  47
```
2. nc
For netcdf, I only change the output name.

```
LT avg timeseries file  : ./ts_satellite/ts_satellite.YYYYMMDD.nc
```

I also tried ND40 (planeflight diagnositc) in another test simulation as well. It looks like it will report error in log file 
```
ERROR: invalid species!
Species RIO2 not found!
STOP in PLANEFLIGHT!
```
However, even though I delete RIO2 or other species, it will still report error below.
```
ERROR: invalid species!
Species  not found!
STOP in PLANEFLIGHT!
```
The log file and planeflight diagnositc input are attached.
[log_nd40.txt](https://github.com/geoschem/geos-chem/files/5196825/log_nd40.txt)
[Planeflight.dat.20180724.txt](https://github.com/geoschem/geos-chem/files/5196898/Planeflight.dat.20180724.txt)

Do you have any insight on it?

Cheers,
Lixu

**Comment by lizziel** [comment]
Hi Lixu,

The ND51 diagnostic is not available in NetCDF format. The netcdf equivalent for each binary diagnostics is listed at the [wiki page for diagnostics in bpch format](http://wiki.seas.harvard.edu/geos-chem/index.php/List_of_diagnostics_archived_to_bpch_format) (see column 7 of the tables). Were you able to successfully output ND51 binary data?

Could you provide your input.geos file? This may give insight into the issue with ND40.

**Comment by jinlx** [comment]
Hi @lizziel ,

Thanks for clarifying it! The bpch can't be created as well for ND51 even though the simulation can be finished. My input file is attached below.

Cheers,
Lixu
[input.geos.txt](https://github.com/geoschem/geos-chem/files/5196968/input.geos.txt)

**Comment by WilliamDowns** [comment]
I'm able to generate ND51 BPCH when I run a quick 4x5 Tropchem simulation. Before I delve further, are you compiling using CMake? If so, you'll need to [compile with BPCH enabled](http://wiki.seas.harvard.edu/geos-chem/index.php/Compiling_with_CMake#Configuring_with_non-default_options) (the proper syntax is `cmake ../CodeDir/ -DBPCH_DIAG=y`) to generate any bpch output.

**Comment by jinlx** [comment]
Thanks @WilliamDowns ! Sorry for the stupid mistake! ND51 works now. Do you have any insight on the planeflight diagnositc? Does it also work for you?

**Comment by WilliamDowns** [comment]
No problem at all, it's a new option that you didn't need to specify back in 12.5.0. `RIO2` should in fact be removed from the Planeflight.dat file as it is no longer used post-12.8.0. You'll need to update the `# of variables to be output` section at the top based on how many variables you remove (this is causing the `Species  not found! STOP in PLANEFLIGHT!` errors that you're observing for variables aside from `RIO2`). I'm looking into additional errors that are occurring.

**Comment by jinlx** [comment]
Thanks! The error below also occurs in my simulation after removing RIO2. I guess it's same as yours. Please let me know if you have any progress on it. I will also try to dig it a little further to see if it can be fixed.

```
GEOS-CHEM I/O ERROR    64 in file unit    14
Encountered at routine:location read_points:2

Error   64: Input conversion error
```

**Comment by WilliamDowns** [comment]
Yep, that's the same error. Turns out it's due to a missing space in between the Point and Type columns in your Planeflight.dat file. Here's what it looks like now:
```
Point  Type DD-MM-YYYY HH:MM     LAT     LON   PRESS        OBS
    0 C130  24-07-2018 19:07   43.57 -116.23  912.53    912.526
    1 C130  24-07-2018 19:08   43.59 -116.29  892.10    892.105
    2 C130  24-07-2018 19:09   43.61 -116.35  862.46    862.463
```

Here's what it looks like with the added space:
```
Point  Type DD-MM-YYYY HH:MM     LAT     LON   PRESS        OBS
    0  C130  24-07-2018 19:07   43.57 -116.23  912.53    912.526
    1  C130  24-07-2018 19:08   43.59 -116.29  892.10    892.105
    2  C130  24-07-2018 19:09   43.61 -116.35  862.46    862.463
```

Let me know if that fixes your issue.

**Comment by jinlx** [comment]
Yeah! It does fix the issue.  I think I may need to modify the code a little bit to fix the format issue in ND40 source code. Thanks William!
