### ISSUE TITLE
[QUESTION]An operational problem of GEOS-Chem when added a new inventory

### ISSUE THREAD

**Issue by yangxiajie** [geoschem/geos-chem#439]
# Ask a question about GEOS-Chem:

I encountered a problem when using HEMCO to add new emission inventory (in GEOS-Chem 12.0):
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
In Ncrd_1d_R8 #2:  NetCDF: Index exceeds dimension bound

    458752        15
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Code stopped from DO_ERR_OUT (in module NcdfUtil/m_do_err_out.F90)

This is an error that was encountered in one of the netCDF I/O modules,

which indicates an error in writing to or reading from a netCDF file!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
The information of my NetCDF file (yearly emission inventory) is listed below: 

```
        dimensions:
	        lat = 164 ;
	        lon = 280 ;
	        time = 1 ;
        float HCL_POWER(lat, lon) ;
		HCL_POWER:units = "kg/m2/s" ;
		HCL_POWER:long_name = "emission" ;
	float HCL_HEAT(lat, lon) ;
		HCL_HEAT:units = "kg/m2/s" ;
		HCL_HEAT:long_name = "emission" ;
	float HCL_INDUSTRY(lat, lon) ;
		HCL_INDUSTRY:units = "kg/m2/s" ;
		HCL_INDUSTRY:long_name = "emission" ;
	float HCL_RESIDENTIAL(lat, lon) ;
		HCL_RESIDENTIAL:units = "kg/m2/s" ;
		HCL_RESIDENTIAL:long_name = "emission" ;
	float HCL_OTHER(lat, lon) ;
		HCL_OTHER:units = "kg/m2/s" ;
		HCL_OTHER:long_name = "emission" ;
	float HCL_PWASTE(lat, lon) ;
		HCL_PWASTE:units = "kg/m2/s" ;
		HCL_PWASTE:long_name = "emission" ;
	float HCL_TOTAL(lat, lon) ;
		HCL_TOTAL:units = "kg/m2/s" ;
		HCL_TOTAL:long_name = "emission" ;
        float lat(lat, lon) ;
		lat:MemoryOrder = "XY" ;
		lat:long_name = "latitude" ;
		lat:units = "degrees_north" ;
	float lon(lat, lon) ;
		lon:MemoryOrder = "XY" ;
		lon:long_name = "longitude" ;
		lon:units = "degrees_east" ;
	double time(time) ;
		time:units = "hours since 2014-01-01 00:00:00" ;
		time:long_name = "time" ;
```

I want to add it to HEMCO so that the model can read HCl. Therefore, I would like to ask about the solution.

Thakn you.

**Comment by jinlx** [comment]
```
This is an error that was encountered in one of the netCDF I/O modules.
```
From the information provided, it seems like you may need to configure your environment first before running GC. See the website shown below. 

http://wiki.seas.harvard.edu/geos-chem/index.php/Specifying_software_libraries_for_GEOS-Chem

Lixu

**Comment by yangxiajie** [comment]
Hi, @jinlx . Thank you for reply.

I have seen my environment setting, and it seems like as same as the website shown. 

The information of my environment is listed below:

#setting environment for netcdf-fortan
export LD_LIBRARY_PATH=/public/software/mathlib/hdf5-1.10.3/intel/lib:/public/software/mathlib/netcdf-4.6.1-withhdf5/intel/lib:$LD_LIBRARY_PATH
export PATH=/public/software/mathlib/hdf5-1.10.3/intel/bin:/public/software/mathlib/netcdf-4.6.1-withhdf5/intel/bin:$PATH
export NETCDF=/public/software/mathlib/netcdf-4.6.1-withhdf5/intel
export NETCDF_LIB=$NETCDF/lib
export NETCDF_INCLUDE=$NETCDF/include
export NETCDF_HOME=$NETCDF
export NETCDF_DIR=$NETCDF

#for GEOS-Chem
export FC=ifort
export CC=icc
export CXX=icpc
export COMPILER=$FC
export GC_BIN=$NETCDF_HOME/bin
export GC_INCLUDE=$NETCDF_INCLUDE
export GC_LIB=$NETCDF_LIB

I'm not sure whether it's wrong with the environment or the .nc files.

**Comment by yantosca** [comment]
Thanks for writing @jinlx.  I think I see the problem.  The variables in your file are only dimensioned with (lat,lon), which is not COARDS-compliant.  Even if there is only one time point, HEMCO expects that each netCDF variable will be dimensioned with (time, lat, lon), or (time, lev, lat, lon) if it has a vertical dimension.

The solution would be to [add a time dimension](https://sourceforge.net/p/nco/discussion/9830/thread/cee4e1ad/) to each of the HCL_* variables in your netCDF file.

For more information, please see the following wiki pages:
1. [The COARDS netCDF conventions for earth science data](http://wiki.geos-chem.orgThe_COARDS_netCDF_conventions_for_earth_science_data)
2. [Working with netCDF data files](http://wiki.geos-chem.org/Working_with_netCDF_data_files)

**Comment by yangxiajie** [comment]
Hi, @yantosca . Thank you for reply.
I added it into HEMCO successfully by following your instruction.
Thank you very much for your help.

**Comment by yantosca** [comment]
Thanks for letting us know that the fix worked!  I will close out this issue now.
