### ISSUE TITLE
[QUESTION]Units change in HISTORY.rc

### ISSUE THREAD

**Issue by yangxiajie** [geoschem/geos-chem#440]
Since there is no ND50 after GEOS-Chem 12.7.0, I use “THE SpeciesConc COLLECTION” (HISTORY.rc) to generate daily average concentration of species, as a substitute of ND50. However, the species concentration units are “mol mol-1 dry”, which is named “Dry mixing ratio”. Are there any ways to change SpeciesConc units in GEOS-Chem? Or how can I change “mol mol-1 dry” to ppbv?

Thank you.

**Comment by lizziel** [comment]
Hi @yangxiajie , the ND50 output unit ppbv is the same as the SpeciesConc output unit mol/mol dry except scaled by 1e-9. You can convert mol/mol to ppbv by multiplying by that factor.

Beware that the netcdf diagnostic drops the 'C' from carbon-based units. Anywhere you would have seen ppbvC in the binary would appear as mol/mol dry in the netcdf but should be interpreted as mol C/mol dry. See also https://github.com/geoschem/geos-chem/issues/414 for more about this issue.

**Comment by yangxiajie** [comment]
Hi @lizziel .  I understand the relationship between mol/mol and ppbv. 
Thank you very much for your help.
