### ISSUE TITLE
[QUESTION] How to set frequency for restart files if I want to get monthly restart files in a gchp multi-month simulation

### ISSUE THREAD

**Issue by hongjianweng** [geoschem/geos-chem#441]
Hi,

I want to save out a restart file once a month in a multi-month simulation when I run gchp using version 12.7.2 standard.
According to description in the runConfig.sh, it just show a string of format HHmmSS.
I can set 7440000 for some specific month, but I don't think it work in a multi-month simulation.
And I try to set "00000100 000000" and "00000001 000000" according to Bob's advice (https://github.com/geoschem/geos-chem/issues/310).
Unfortunately, if I set it like this, the simulation will die without error reported.
I attach the runConfig.sh and log file and I would like to ask about the solution.
[gchp.log.txt](https://github.com/geoschem/geos-chem/files/5200686/gchp.log.txt)
[runConfig.sh.txt](https://github.com/geoschem/geos-chem/files/5200687/runConfig.sh.txt)

Thanks a lot and waiting for your reply!
Bests

**Comment by lizziel** [comment]
Hi @hongjianweng, you can only specify restart file output interval in hours in GCHP version 12. Using the GC-Classic format of `YYYYMMDD HHmmSS` will not work in GCHP.

One way to get around this is to submit a series of 1-month duration jobs, each of which will output a restart file for use in the next run. This is the approach to get monthly diagnostics as well. You can do this using the `gchp.multirun.sh` script provided in run directory folder for run scripts, which itself uses the `gchp.multirun.run` script also provided in that folder. You can configure `runConfig.sh` to have duration 1-month with start and end date corresponding to start and end of ALL of your runs and set the number of runs and whether you want monthly diagnostics in the file as well. See also [this post](http://wiki.seas.harvard.edu/geos-chem/index.php/Running_GCHP:_Configuration#Split_a_Simulation_Into_Multiple_Jobs) on splitting up GCHP runs into multiple jobs.

**Comment by hongjianweng** [comment]
Thanks a lot and it is helpful for me.
In addition, whether the YYYYMMDD HHmmSS works in later gchp version?

**Comment by lizziel** [comment]
Unfortunately using YYYYMMDD format is still not an option in newer versions of MAPL. It would be a very useful feature and I will continue to suggest it to NASA GMAO as a future update.

**Comment by hongjianweng** [comment]
Okay, thanks a lot for your hard work!
