### ISSUE TITLE
[BUG/ISSUE] HEMCO error reading GFEDv4s 3-hourly fractions

### ISSUE THREAD

**Issue by tianjialiu** [geoschem/geos-chem#443]
When running the nested grid simulation, HEMCO could not read GFEDv4s 3-hourly fractions because of a timestamp error. This error did not appear in the global 4x5 simulation. I've attached my HEMCO.log file, which includes verbose warnings.
```
Processing container: GFED_FRAC_3HOUR
 Parsing source file and replacing tokens
 Opening file: /n/holyscratch01/external_repos/GEOS-CHEM/gcgrid/data/ExtData/HEMCO/GFED4/v2020-02/2015/GFED4_3hrfrac_gen.025x025.201508.nc
HEMCO: Entering GET_TIMEIDX (hco_read_std_mod.F90) ( 6)
 Number of time slices found:            8
 Time slice range :    201508010000.00000        201508012100.00000
          preferred datetime:  201508310000.
              selected tidx1:             -1
        assigned delta t [h]:              0
 local time?  F
HEMCO: Leaving GET_TIMEIDX (hco_read_std_mod.F90) ( 6)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
HEMCO ERROR: Cannot find field with valid time stamp in /n/holyscratch01/external_repos/GEOS-CHEM/gcgrid/data/ExtData/HEMCO/GFED4/v2020-02/2015/GFED4_3hrfrac_gen.025x025.201508.nc - Cannot get field GFED_FRAC_3HOUR. Please check file name and time (incl.
ERROR LOCATION: HCOIO_READ_STD (hcoio_read_std_mod.F90)
ERROR LOCATION: HCOIO_DataRead (hcoio_dataread_mod.F90)
ERROR LOCATION: ReadList_Fill (hco_readlist_mod.F90)
ERROR LOCATION: ReadList_Read (hco_readlist_mod.F90)
ERROR LOCATION: HCO_RUN (hco_driver_mod.F90)
```

[HEMCO.log](https://github.com/geoschem/geos-chem/files/5210801/HEMCO.log)

**Comment by lizziel** [comment]
Hi @tianjialiu, thanks for reporting this. Could you provide the rest of the information listed on the [GEOS-Chem support request wiki page](http://wiki.seas.harvard.edu/geos-chem/index.php/Submitting_GEOS-Chem_support_requests#What_do_I_need_to_include_in_my_support_request.3F)? This will help hone in on the issue faster. Thanks!

**Comment by tianjialiu** [comment]
Version: 12.8.2
MERRA2 Nested Grid - Asia, tropchem, 2015/08/31 - 2015/09/02

[GC_GFED_3HR_Error.zip](https://github.com/geoschem/geos-chem/files/5211439/GC_GFED_3HR_Error.zip)

**Comment by yantosca** [comment]
Hi @tianjialiu: just following up on if you are still encountering this problem.  Let us know.

**Comment by yantosca** [comment]
I will close out this issue for now.  Let us know if you are still having problems.
