### ISSUE TITLE
[QUESTION]A scientific question about chlorine emissions and chemistry

### ISSUE THREAD

**Issue by yangxiajie** [geoschem/geos-chem#446]
It seems that there are no specific emission inventory of HCl and Cl2 in HEMCO. In GEOS-Chem model, how are the sources of these two species generated? If I want to add an emission inventory of HCl and Cl2 in _HEMCO_Config.rc_ file, will it affect the model simulation of Cl chemical reaction?

**Comment by tsherwen** [comment]
Hello Yang Xiajie, 

You can add a new chlorine inventory through simply adding the lines to `HEMCO_Config.rc` to as you say, which will create a new emission source. Related to this, Xuan Wang's recent GEOS-Chem chlorine paper [[Wang et al 2019](https://doi.org/10.5194/acp-19-3981-2019)] included a sensitivity run with an anthropogenic chlorine source (HCl). However, this was not included in the main simulation and therefore is not included in the GEOS-Chem main repository. 

HCl and Cl2 are generated in the model via chemistry (e.g VOC + Cl => ... + HCl) as shown in the KPP mechanism file (linked below). There is more detail on the specific chlorine reactions in the GEOS-Chem coupled halogen paper [[Sherwen et al 2016](https://doi.org/10.5194/acp-16-12239-2016)] and in Xuan Wang's recent update to the chlorine mechanism too [[Wang et al 2019](https://doi.org/10.5194/acp-19-3981-2019)].

https://github.com/geoschem/geos-chem/blob/master/KPP/Standard/Standard.eqn

Cheers, 

Tomas

**Comment by yangxiajie** [comment]
Hi, @tsherwen . Thank you for reply.

Following your introduction, I found the production way of HCl and Cl2 in KPP mechanism file. Thank you very much for your help.

I still have one more question need to be confirmed. 

Currently, I use GEOS-Chem 12.9.3. I want to add anthropogenic chlorine sources (HCl) to find out the chemical process of Cl. However, as you said, HCl is not included in the main simulation. Can I understand that even if I add an emission inventory of HCl in HEMCO, and GEOS-Chem can read it successfully, there is still no effect on the results?

**Comment by tsherwen** [comment]
Hello @yangxiajie, 

To confirm HCl is included in the main simulation, it is just not directly emitted as an anthropogenic surface source. If you add in a new emission source of HCl this will increase the HCl burden and more Cl will be released into the atmosphere via oxidation (e.g. see reactions in [the KPP equation file](https://github.com/geoschem/geos-chem/blob/master/KPP/Standard/Standard.eqn) pasted below). 

`
OH + HCl = H2O + Cl :                        GCARR(1.80E-12, 0.0E+00, -250.0);    {2014/02/03; Eastham2014; SDE}
`
...
`
O1D + HCl = 0.090O + 0.090HCl + 0.240H +
 0.670Cl + 0.240ClO + 0.670OH :              GCARR(1.50E-10, 0.0E+00, 0.0);       {2014/02/03; Eastham2014; SDE}
`

Hope that helps, 

Tomas

**Comment by yangxiajie** [comment]
Hi, @tsherwen . Thank you for reply.
I understand the role of HCl inventory in the modle.
Thank you very much for your help.
