### ISSUE TITLE
[FEATURE REQUEST] Updated CEDS emissions for 1970-2017

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#447]
Erin McDuffie wrote:

>I would like to submit for your consideration for that standard model, an updated version of the CEDS global emission inventory. This inventory is described in the attached paper (recently submitted to Earth Sys. Sci. Data) and includes global gridded emissions (0.5x0.5) of NOx, SO2, CO, NH3, 23 NMVOCs, OC, and BC from 1970 - 2017, as a function of 11 anthropogenic source sectors (agriculture, energy, industry, road transport, non-road/off-road transport, residential, commercial, other energy use, solvents, waste, international shipping) and 4 fuel categories (the combustion of total coal, solid biofuel, liquid oil and gas, and all remaining sources).
>
>I've primarily worked with the CEDS developers (Steve Smith and Patrick O-Rourke at PNNL) to update the underlying activity data and have incorporated updated and new regional emission inventories, including the DICE-Africa inventory, into the CEDS source code. These updates, along with modifications to the sector aggregation and gridding processes have allowed for the extension of this inventory to the year 2017 and the separation of additional source sectors and fuel types relative to the original CEDS inventory (currently the GEOS-Chem default for global emissions). Files formatted for use in the GEOS-Chem HEMCO_Config.rc file (GCv12.1) are available at: https://doi.org/10.5281/zenodo.3754964.  

*Reference:*
McDuffie, E. E., S. J. Smith, P. O'Rourke, K. Tibrewal, C. Venkataraman, E. A. Marais, B. Zheng, M. Crippa, M. Brauer, R. V. Martin, _A global anthropogenic emission inventory of atmospheric pollutants from sector- and fuel- specific sources (1970- 2017): An application of the Community Emissions Data System (CEDS)_, <ins>Earth System Science Data</ins>, Submitted, 2020.

**Comment by msulprizio** [comment]
Erin McDuffie wrote:

>Here is an example HEMCO_Config file that I’ve been using for my simulations. This reads in the fuel and sector specific CEDS emissions that I previously formatted for GEOS-Chem (found here: https://zenodo.org/record/3754964#.XzVo1i3MxTY. You want zip files #2: CEDS_GBD-MAPS_gridded_emissions_by_sector_fuel_[year].zip). 
>
>A few things to note in the Config file. 
>1. To report sectoral and fuel-specific emissions using the HEMCO_Diagn.rc file, I report all the CEDS emissions to category 5. You’ll likely want to switch that back to 1/2. 
>2. Sectoral emissions of each compound have a 3 or 4 digit scaling factor that starts with 5. These factors allow the emissions to be quickly turned off for sensitivity simulations, but should not be included in the default code. 
>3. I’ve also calculated and included sectoral-specific TOD scaling factors (1500-1541) that are based on the NEI2011 emissions. For the default model, I would recommend changing these back to the default TOD profiles for NOx (25) and VOCs (26). 

[HEMCO_Config_CEDS_2020_v1_EXAMPLE_FUEL-SPECIFIC_EMISSIONS.rc.txt](https://github.com/geoschem/geos-chem/files/5220881/HEMCO_Config_CEDS_2020_v1_EXAMPLE_FUEL-SPECIFIC_EMISSIONS.rc.txt)

**Comment by msulprizio** [comment]
The initial 1-month benchmark showed this update slowed down simulations by ~45 minutes. This is likely because of the increased file I/O from the CEDS updates. To reduce the slowdown, we can list the CEDS entries in a more efficient way so that files are only opened once. Files are currently listed by source sector then fuel category. However, since files are by fuel category, we could sort by fuel category first and then source sector. For example, for CO we currently have:

```
0 CEDS_CO_rAGR $ROOT/CEDS/v2020-08/$YYYY/CO-em-process_CEDS_$YYYY.nc                      CO_agr 1970-2017/1-12/1/0 C xy kg/m2/s CO    26     1 5
0 CEDS_CO_gAGR $ROOT/CEDS/v2020-08/$YYYY/CO-em-liquid-fuel-plus-natural-gas_CEDS_$YYYY.nc CO_agr 1970-2017/1-12/1/0 C xy kg/m2/s CO    26     1 5
0 CEDS_CO_bAGR $ROOT/CEDS/v2020-08/$YYYY/CO-em-solid-biofuel_CEDS_$YYYY.nc                CO_agr 1970-2017/1-12/1/0 C xy kg/m2/s CO    26     1 5
0 CEDS_CO_cAGR $ROOT/CEDS/v2020-08/$YYYY/CO-em-total-coal_CEDS_$YYYY.nc                   CO_agr 1970-2017/1-12/1/0 C xy kg/m2/s CO    26     1 5

0 CEDS_CO_rENE $ROOT/CEDS/v2020-08/$YYYY/CO-em-process_CEDS_$YYYY.nc                      CO_ene 1970-2017/1-12/1/0 C xy kg/m2/s CO    26     1 5
0 CEDS_CO_gENE $ROOT/CEDS/v2020-08/$YYYY/CO-em-liquid-fuel-plus-natural-gas_CEDS_$YYYY.nc CO_ene 1970-2017/1-12/1/0 C xy kg/m2/s CO    26     1 5
0 CEDS_CO_bENE $ROOT/CEDS/v2020-08/$YYYY/CO-em-solid-biofuel_CEDS_$YYYY.nc                CO_ene 1970-2017/1-12/1/0 C xy kg/m2/s CO    26     1 5
0 CEDS_CO_cENE $ROOT/CEDS/v2020-08/$YYYY/CO-em-total-coal_CEDS_$YYYY.nc                   CO_ene 1970-2017/1-12/1/0 C xy kg/m2/s CO    26     1 5

0 CEDS_CO_rIND $ROOT/CEDS/v2020-08/$YYYY/CO-em-process_CEDS_$YYYY.nc                      CO_ind 1970-2017/1-12/1/0 C xy kg/m2/s CO    26     1 5
0 CEDS_CO_gIND $ROOT/CEDS/v2020-08/$YYYY/CO-em-liquid-fuel-plus-natural-gas_CEDS_$YYYY.nc CO_ind 1970-2017/1-12/1/0 C xy kg/m2/s CO    26     1 5
0 CEDS_CO_bIND $ROOT/CEDS/v2020-08/$YYYY/CO-em-solid-biofuel_CEDS_$YYYY.nc                CO_ind 1970-2017/1-12/1/0 C xy kg/m2/s CO    26     1 5
0 CEDS_CO_cIND $ROOT/CEDS/v2020-08/$YYYY/CO-em-total-coal_CEDS_$YYYY.nc                   CO_ind 1970-2017/1-12/1/0 C xy kg/m2/s CO    26     1 5
```

While this would be more efficient:

```
0 CEDS_CO_rAGR $ROOT/CEDS/v2020-08/$YYYY/CO-em-process_CEDS_$YYYY.nc                      CO_agr 1970-2017/1-12/1/0 C xy kg/m2/s CO 26 1 5
0 CEDS_CO_rENE -                                                                          CO_ene -                  - -  -       CO 26 1 5
0 CEDS_CO_rIND -                                                                          CO_ind -                  - -  -       CO 26 1 5

0 CEDS_CO_gAGR $ROOT/CEDS/v2020-08/$YYYY/CO-em-liquid-fuel-plus-natural-gas_CEDS_$YYYY.nc CO_agr 1970-2017/1-12/1/0 C xy kg/m2/s CO 26 1 5
0 CEDS_CO_gENE -                                                                          CO_ene -                  - -  -       CO 26 1 5
0 CEDS_CO_gIND -                                                                          CO_ind -                  - -  -       CO 26 1 5

0 CEDS_CO_bAGR $ROOT/CEDS/v2020-08/$YYYY/CO-em-solid-biofuel_CEDS_$YYYY.nc                CO_agr 1970-2017/1-12/1/0 C xy kg/m2/s CO 26 1 5
0 CEDS_CO_bENE -                                                                          CO_ene -                  - -  -       CO 26 1 5
0 CEDS_CO_bIND -                                                                          CO_ind -                  - -  -       CO 26 1 5

0 CEDS_CO_cAGR $ROOT/CEDS/v2020-08/$YYYY/CO-em-total-coal_CEDS_$YYYY.nc                   CO_agr 1970-2017/1-12/1/0 C xy kg/m2/s CO 26 1 5
0 CEDS_CO_cENE -                                                                          CO_ene -                  - -  -       CO 26 1 5
0 CEDS_CO_cIND -                                                                          CO_ind -                  - -  -       CO 26 1 5
```

**Comment by msulprizio** [comment]
This update has now been merged into dev/13.0.0. Changes to emissions are summarized below:

```
###############################################################################
### Emissions totals for inventory CEDS                                     ###
### Ref = GC_13.0.0-alpha.5; Dev = GC_13.0.0-alpha.6                        ###
###############################################################################
                                       Ref                 Dev      Dev - Ref
CEDS ALD2             :           0.154944            0.154743      -0.000201 Tg
CEDS ALK4             :           5.366765            6.206341       0.839575 Tg
CEDS BCPI             :           0.124817            0.091512      -0.033305 Tg
CEDS BCPO             :           0.499270            0.366050      -0.133220 Tg
CEDS BENZ             :           0.538499            0.541164       0.002665 Tg
CEDS C2H6             :           0.000000            0.000000       0.000000 Tg
CEDS C3H8             :           0.000000            0.000000       0.000000 Tg
CEDS CH2O             :           0.207237            0.188888      -0.018349 Tg
CEDS CH4              :           0.000000                 nan            nan Tg
CEDS CO               :          48.242726           43.388253      -4.854473 Tg
CEDS EOH              :           0.338720            0.369722       0.031002 Tg
CEDS HCOOH            :           0.790157            0.788126      -0.002031 Tg
CEDS MEK              :           0.259010            0.318148       0.059138 Tg
CEDS MOH              :           0.235222            0.256753       0.021531 Tg
CEDS NH3              :           4.601724            4.537883      -0.063841 Tg
CEDS NO               :           6.332088            5.364633      -0.967456 Tg
CEDS OCPI             :           0.775254            0.517901      -0.257353 Tg
CEDS OCPO             :           0.775254            0.517901      -0.257353 Tg
CEDS PRPE             :           0.273593            0.278380       0.004787 Tg
CEDS SO2              :           8.222032            5.685026      -2.537006 Tg
CEDS SO4              :           0.254883            0.176235      -0.078648 Tg
CEDS SOAP             :           3.328738            2.993779      -0.334959 Tg
CEDS TOLU             :           0.641471            0.695299       0.053828 Tg
CEDS XYLE             :           0.627999            0.654326       0.026327 Tg
CEDS pFe              :           0.008222            0.005685      -0.002537 Tg


###############################################################################
### Emissions totals for inventory CEDSship                                 ###
### Ref = GC_13.0.0-alpha.5; Dev = GC_13.0.0-alpha.6                        ###
###############################################################################
                                       Ref                 Dev      Dev - Ref
CEDSship ALD2         :           0.000000            0.000000       0.000000 Tg
CEDSship ALK4         :           0.115240            0.099353      -0.015887 Tg
CEDSship BCPI         :           0.002895            0.003195       0.000300 Tg
CEDSship BCPO         :           0.011581            0.012781       0.001200 Tg
CEDSship BENZ         :           0.006376            0.001484      -0.004892 Tg
CEDSship C2H6         :           0.018676            0.018676       0.000000 Tg
CEDSship C3H8         :           0.051811            0.051811       0.000000 Tg
CEDSship CH2O         :           0.000000            0.000000       0.000000 Tg
CEDSship CO           :           0.059695            0.065939       0.006244 Tg
CEDSship EOH          :           0.000000            0.000000       0.000000 Tg
CEDSship HCOOH        :           0.000000            0.000000       0.000000 Tg
CEDSship MEK          :           0.000000            0.000000       0.000000 Tg
CEDSship NH3          :           0.001384            0.001472       0.000087 Tg
CEDSship OCPI         :           0.005497            0.006069       0.000572 Tg
CEDSship OCPO         :           0.005497            0.006069       0.000572 Tg
CEDSship PRPE         :           0.015206            0.003160      -0.012046 Tg
CEDSship SO2          :           0.773045            0.800525       0.027479 Tg
CEDSship SO4          :           0.023964            0.024816       0.000852 Tg
CEDSship SOAP         :           0.004119            0.004550       0.000431 Tg
CEDSship TOLU         :           0.003854            0.001119      -0.002735 Tg
CEDSship XYLE         :           0.004060            0.001798      -0.002262 Tg
CEDSship pFe          :           0.000773            0.000801       0.000027 Tg
```

**Comment by msulprizio** [comment]
The CEDS GCB-MAPS inventory will now also be the default anthropogenic emissions inventory in GEOS-Chem 13.0.0, and older regional inventories will be turned off. Daniel Jacob wrote to the GEOS-Chem Steering Committee:

>Here’s what I suggest as take-away:
>
>1. We adopt CEDS as our global default inventory in version 13.0.0 and use it for benchmarking with no regional overwrites for now, as representing our best estimate of emissions for use in global model applications.  This is the prevailing GCSC view. CEDS already subsumes all the regional emission inventories currently in HEMCO and has the advantage of temporal consistency out to 2017.  The regional inventories have higher spatial resolution and better speciation of VOC emissions, but these are of most interest for nested model users of which they are many but I expect that these nested model users pay particular attention to the emissions they use and may therefore choose to use the regional inventories.
>2.  As to Seb’s good point of exercising a maximum of model options in the benchmark, we do embrace this with OA as you know – but that’s because we don’t have a recommendation on OA for global model users, and because the different OA options could well break with model updates.  We don’t do this for any of the other model options. I see no reason that the regional inventories would break with model updates.
>3. We will supersede CEDS with new regional emission inventories in the default in the future if we decide that they are objectively better. For example, we expect to have soon an updated NEI for US emissions from Barron and I would recommend to have it overwrite CEDS in the default.
>We should still overwrite CEDS with the Tzompa ethane and Xiao propane because we have as of now no assurance that CEDS does better for those. It would be great for someone to look into it!

**Comment by hongjianweng** [comment]
Hi @msulprizio ,

Nice work!
Will the CEDS emissions after 2017 be updated and when will the emissions through 2019 be available?

Thanks!

**Comment by emcduffie** [comment]
Hi @hongjianweng,

The Sept. 2020 pre-release of the CEDS system currently provides national total emissions out to 2019 for all CEDS species except for CO2 and CH4. Updates to the gridded emissions have not been released at this time. The next full release for CEDS is planned for this fall or early next year, after which, the CEDS inventory can be updated in GEOS-Chem. See the CEDS release notes (https://github.com/JGCRI/CEDS/wiki/Release-Notes) for a description of some of the updates between 2017 and 2019.

**Comment by hongjianweng** [comment]
Thanks,   it help a lot.
