### ISSUE TITLE
[QUESTION]DIfferent Emission category between GFED4 and QFED2

### ISSUE THREAD

**Issue by yangxiajie** [geoschem/geos-chem#448]
HEMCO provide GFED4 as biomass burning emissions. However, in _HEMCO_Config.rc_ file, the Emission category of GFED4 is set as 1, which is ANTHRO.  On the contrary, the Emission category of QFED2 is set as 5, which is BIOMASS. 
(in GEOS-Chem v12.9.3)

Are there any differences between Cat=1 and Cat=1 for biomass burning emissions?  If I want to use GFED4, should I change the Emission category form 1 to 5?

**Comment by yantosca** [comment]
Thanks for writing.  I believe that Cat=5 is used for QFED because QFED is emitted under BASE EMISSIONS (i.e. just read from disk).  But GFED4 is implemented as a HEMCO extension, which only has 1 category.  

Perhaps we can make this more clear in the documentation.

**Comment by yangxiajie** [comment]
Thank you very much for your introduction, @yantosca . 

Now I understand the meaning of Cat = 1 for GFED4.
