### ISSUE TITLE
[BUG/ISSUE] Zero Biogenic Emissions in 2018 January 1st

### ISSUE THREAD

**Issue by barronh** [geoschem/geos-chem#450]
The offline biogenic emission file for 2018 Jan 1st has zeros for all species at all times. Only the AREA variable is populated. I checked both Harvard[1] and Compute Canada[2]. Note that both files for that day are 1.1M in size compared to 40-50M for all other days.

I have not run this through GEOS-Chem, so I am not including typical details (compiler, version, etc).

http://ftp.as.harvard.edu/gcgrid/data/ExtData/HEMCO/OFFLINE_BIOVOC/v2019-10/0.5x0.625/2018/01/
http://geoschemdata.computecanada.ca/ExtData/HEMCO/OFFLINE_BIOVOC/v2019-10/0.5x0.625/2018/01/

**Comment by yantosca** [comment]
Hi Barron.  See this issue: https://github.com/geoschem/geos-chem/issues/445

This is probably due to the fact that the biogenic emissions archive only goes up to the end of 2017.

**Comment by barronh** [comment]
Sorry for the duplication.

**Comment by barronh** [comment]
I'll just add a note that the rest of 2018 appears reasonable.
