### ISSUE TITLE
[BUG/ISSUE] Segmentation fault after reading boundary conditions

### ISSUE THREAD

**Issue by junweilovexu** [geoschem/geos-chem#454]
I was using version 12.3.2 offline model and it crashed with a segmentation fault after reading boundary conditions. I thought it was a stack memory issue so I included the memory settings in .bashrc as the following, but didn’t help. 

export KMP_STACKSIZE=500m 
ulimit -s unlimited

I had a successful run with the exactly same code and configurations on another cluster. Comparing the two runs, I noticed that the bad run died before the line “HEMCO emissions successfully calculated!” in HEMCO.log, so there might be something wrong in HEMCO or the environment that HEMCO needs in my settings. I’m not sure what the problem actually was and how to solve it. 

Attached are the log files and the environmental variables (Pegasus_bashrc). Thanks for your help! 

<img width="422" alt="Pegasus_bashrc" src="https://user-images.githubusercontent.com/8321437/94015387-5e4f2180-fddf-11ea-9456-7934ee6eef4d.png">

[GC.log](https://github.com/geoschem/geos-chem/files/5268208/GC.log)

[HEMCO.log](https://github.com/geoschem/geos-chem/files/5268211/HEMCO.log)

**Comment by yantosca** [comment]
HI @junweilovexu.  I didn't see anything that stands out.  

One question: It looks like you are reading in the BPCH boundary condition files. I think in 12.3.2 we had updated those to netCDF boundary conditions.  You might need to [convert those to netCDF](http://wiki.seas.harvard.edu/geos-chem/index.php/Working_with_netCDF_data_files#Converting_files_from_binary_punch_format_to_netCDF) to have HEMCO read them in.

**Comment by msulprizio** [comment]
@junweilovexu were you able to resolve this or are you still running into the same error?

**Comment by yantosca** [comment]
I am closing out this issue as we have not heard back from you in a while.  Feel free to submit a new issue if you are still having problems.
