### ISSUE TITLE
[DISCUSSION] Any plan for updating NEI emission inputs?

### ISSUE THREAD

**Issue by dxy8413** [geoschem/geos-chem#455]
# Ask a question about GEOS-Chem:
The most recent emission data over US is still NEI2011, is there any plan to include NEI2014 and NEI 2017 in HEMCO?
Thanks a lot for your time and help.

**Comment by yantosca** [comment]
Thanks for writing @dxy8413.  This will not happen until after the 13.0.0 public release.

Also, the GEOS-Chem Support Team relies on members of the user community to provide us with emissions updates.  I know that there is a group working on NEI2016 but they have not yet provided us with a final product.

I would recommend directing specific questions about new emissions inventories to the [Emissions and Deposition Working Group](http://wiki.seas.harvard.edu/geos-chem/index.php/Emissions_and_Deposition_Working_Group).

**Comment by yantosca** [comment]
Also tagging @barronh and @lfreese, who may have more information.

**Comment by lfreese** [comment]
I've sent a one month benchmark of new 2016 files, created thanks to a lot of work by @barronh, to the emissions support team with the hopes that it can be included in v13. I'm not sure where the team is in that process--@yantosca if you want me to send this benchmark to you as well to push it forward, I'm happy to do that.

**Comment by yantosca** [comment]
Thanks @lfreese.  Right now we are prioritizing the 13.0.0 release.  Emissions updates will go into 13.1.0 and later versions.

**Comment by dxy8413** [comment]
thanks a lot for the prompt reply, very clear and helpful! @yantosca @lfreese

**Comment by msulprizio** [comment]
The progress of NEI 2016 emissions is now being tracked via https://github.com/geoschem/geos-chem/issues/547.
