### ISSUE TITLE
[QUESTION]Problem with GEOS-Chem installation

### ISSUE THREAD

**Issue by BiggieBud** [geoschem/geos-chem#457]
Hello there, I want ask again about GEOS-Chem installation. When I run ./geos in result I have errors. I don't know what I do incorrect.  Please find screenshot bellow. 
![iss-011](https://user-images.githubusercontent.com/69847101/94261409-d4e34080-feff-11ea-9fcf-5b9a3f0c92cc.png)
![iss-012](https://user-images.githubusercontent.com/69847101/94261413-d6146d80-feff-11ea-8a17-a8afd3a4feaf.png)

**Comment by WilliamDowns** [comment]
Hi there, can you confirm that if you type `ls /home/administratorvm/Geos-chem/gcgrid/data/ExtData/HEMCO/PARANOX/v2015-02/ship_plume_lut_02ms.nc` that you can see a file there? If no file exists, you will need to use the [dry-run functionality (instructions here)](http://wiki.seas.harvard.edu/geos-chem/index.php/Downloading_data_with_the_GEOS-Chem_dry-run_option) to download all of the required files for HEMCO for your run (including but not limited to the ones listed as "NOT FOUND" in your image).

**Comment by BiggieBud** [comment]
![iss-013](https://user-images.githubusercontent.com/69847101/94410279-30ead680-0145-11eb-9735-429afc2b8800.png)
ln /home/administratorvm/Geos-chem/gcgrid/data/ExtData/HEMCO/PARANOX/v2015-02/ship_plume_lut_02ms.nc I haven't this file. I'm use dry-run functionality but in result I have errors. You can see this in screenshot bellow.
![iss-014](https://user-images.githubusercontent.com/69847101/94411130-3399fb80-0146-11eb-9373-98ca9740991c.png)

**Comment by WilliamDowns** [comment]
That dry-run error is likely due to an old version of Python. What is output if you type `python --version`? The dry-run script likely requires a version of Python `>=3.6.0`. The safest way to install a newer version of Python is from within a Conda environment. Install Miniconda using [the instructions here](https://conda.io/projects/conda/en/latest/user-guide/install/linux.html), then type `conda create -n myenv python=3.7` to create a Conda environment that contains a suitable version of Python, then type `conda activate myenv` to enter this environment. From within this environment, you should be able to run the `download_data.py` script as you tried previously.

**Comment by BiggieBud** [comment]
Hi, there. I'm installed new version for all necessary programs and all  works good. And in continuation I have one more question. How I can run simulation and web interface for simulation. I have a set of raw data on PM2.5, PM10, and CO2, and I need to represent graphically this raw data over a small geographical area in my country of about 0.5 km2, where these precise measurements were done at three different altitudes (I used a drone-based measurement station). Could you please suggest me the most suitable GEOS-Chem programs? Also, it would be great to make simple computations, like pollution gradients, so I could be able, in general, to map spatial and temporal gradients of gas-phase species and particulate matter (PM). Any suggestions and help are highly appreciated!

**Comment by yantosca** [comment]
Glad to hear that your simulation is now working @BiggieBud.  

Unfortunately, assisting users with visualization for research purposes is beyond the scope of the assistance that we can provide.  However, you might want to consider creating a Jupyter notebook with Python code to analyze and display your data online.  There are many tutorials about how to create Jupyter notebooks online (such as [this](https://www.dataquest.io/blog/jupyter-notebook-tutorial/) and [this](https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook)).  You can also take a look at our [GEOS-Chem Python Tutorial](https://github.com/geoschem/GEOSChem-python-tutorial), which I think is a pretty good starting point.

**Comment by BiggieBud** [comment]
thanks.

**Comment by yantosca** [comment]
Thanks for your understanding.  I'll close this issue out.
