### ISSUE TITLE
Error: make realclean

### ISSUE THREAD

**Issue by jinlx** [geoschem/geos-chem#46]
Hi there,

I am new to GEOS-CHEM. And when I was trying to type make reclean in my rundir on Ubuntu. Here are bugs showed. Do you guys have any experience on it? 

make[4]: Entering directory '/glade/u/home/lixujin/GEOS-CHEM/Code.12.4.0/KPP/Standard'
ifort: warning #10315: specifying -lm before files may supersede the Intel(R) math library and affect performance
grep: path/to/NetCDF-Fortran/library/files/include/netcdf.inc: No such file or directory
rm -f *.o *.mod geos
make[4]: Leaving directory '/glade/u/home/lixujin/GEOS-CHEM/Code.12.4.0/KPP/Standard'
make[4]: Entering directory '/glade/u/home/lixujin/GEOS-CHEM/Code.12.4.0/KPP/SOA_SVPOA'
make[4]: *** No rule to make target 'clean'.  Stop.
make[4]: Leaving directory '/glade/u/home/lixujin/GEOS-CHEM/Code.12.4.0/KPP/SOA_SVPOA'
Makefile:140: recipe for target 'realclean' failed
make[3]: *** [realclean] Error 2
make[3]: Leaving directory '/glade/u/home/lixujin/GEOS-CHEM/Code.12.4.0/KPP'
Makefile:359: recipe for target 'realclean' failed
make[2]: *** [realclean] Error 2
make[2]: Leaving directory '/glade/u/home/lixujin/GEOS-CHEM/Code.12.4.0/GeosCore'
Makefile:109: recipe for target 'realclean' failed
make[1]: *** [realclean] Error 2
make[1]: Leaving directory '/glade/u/home/lixujin/GEOS-CHEM/Code.12.4.0'
Makefile:641: recipe for target 'realclean' failed
make: *** [realclean] Error 2

**Comment by lizziel** [comment]
Hi there!
I suspect there is a problem in your environment variable GC_F_INCLUDE which is supposed to be a path to the directory that contains netcdf.inc. The error message below looks like that variable is set to some default string "path/to/NetCDF-Fortran/library/files/include".
```
grep: path/to/NetCDF-Fortran/library/files/include/netcdf.inc: No such file or directory
```
Within Makefile_header.mk (top-level of GEOS-Chem source code) there is a call to grep within $GC_F_INCLUDE/netcdf.inc, so if that path is not set right you will get this error. Check to see what you have for $GC_F_INCLUDE (echo $GC_F_INCLUDE). 

If this is indeed the issue, check out our documentation on setting up this and other GEOS-Chem environment variables located here:
http://wiki.seas.harvard.edu/geos-chem/index.php/Setting_Unix_environment_variables_for_GEOS-Chem

Lizzie

**Comment by jinlx** [comment]
After type echo $GC_F_INCLUDE, I get path/to/NetCDF-Fortran/library/files/include. Is it the right place? Also I have already set up the environmental variables. But the bug still shows. Any other possible solution to this issue?

Thanks,
Lixu

**Comment by jinlx** [comment]
Thanks Lizzie. I was wondering how we can find the path of NETCDF_HOME.

Lixu

**Comment by yantosca** [comment]
Thanks for writing.  We aren't sure which compiler version or GEOS-Chem version you are using.  Can you attach more information to this issue?  Please see:

http://wiki.geos-chem.org/Submitting_GEOS-Chem_support_requests#What_do_I_need_to_include_in_my_support_request.3F

**Comment by jinlx** [comment]
Thanks for your suggesion. Information that may help is attached below.

HEMCO configuration file,  Lastbuild file, GEOS-Chem "Classic" log file and HEMCO log file are attached below.

Please feel free to tell me if you need any other information.

Thanks,
Lixu

-------------------------------------------------------------------------------------------------------------
**GEOS-CHEM version: 12.4.0**
**input.goes file**
`  4 Start YYYYMMDD, hhmmss  : 20160701 000000
   5 End   YYYYMMDD, hhmmss  : 20160801 000000
   6 Run directory           : ./
   7 Root data directory     : /glade/p/univ/uumm0001/geos-chem/ExtData
   8 Met field               : geosfp
   9 ------------------------+------------------------------------------------------
  10 %%% GRID MENU %%%       :
  11 Grid resolution         : 4.0x5.0
  12 Longitude min/max       : -180.0 180.0
  13 Latitude  min/max       : -90.0   90.0
  14  Half-sized polar boxes?: T
  15 Number of levels        : 47
  16 Nested grid simulation? : F
  17  Buffer zone (N S E W ) :  0  0  0  0`
**HEMOCO configuration file**
`ROOT:                        /glade/p/univ/uumm0001/geos-chem/ExtData/HEMCO
   39 METDIR:                      /glade/p/univ/uumm0001/geos-chem/ExtData/GEOS_4x5/GEOS_FP
   40 Logfile:                     HEMCO.log
   41 DiagnFile:                   HEMCO_Diagn.rc
   42 DiagnPrefix:                 HEMCO_diagnostics
   43 DiagnFreq:                   End
   44 Wildcard:                    *
   45 Separator:                   /
   46 Unit tolerance:              1
   47 Negative values:             0
   48 Only unitless scale factors: false
   49 Verbose:                     0
   50 Warnings:                    1
   51
   52 ### END SECTION SETTINGS ###`
**lastbuild**
`   1 make[1]: Entering directory '/glade/u/home/lixujin/GEOS-CHEM/rundirs/geosfp_4x5_standard'
   2 LAST BUILD INFORMATION:
   3   CODE_DIR     : /glade/u/home/lixujin/GEOS-CHEM/Code.12.4.0
   4   CODE_BRANCH  : master
   5   LAST_COMMIT  : Remove MET and GRID from make help output
   6   COMMIT_DATE  : Thu Jul 11 14:56:34 2019 -0400
   7   VERSION      : 12.4.0
   8   VERSION_TAG  : GC_12.4.0
   9   MET          : geosfp
  10   GRID         : 4x5
  11   SIM          : standard
  12   NEST         : n
  13   TRACEBACK    : y
  14   BOUNDS       : n
  15   DEBUG        : n
  16   FPE          : n
  17   NO_ISO       : n
  18   NO_REDUCED   : y
  19   CHEM         : Standard
  20   TOMAS12      : n
  21   TOMAS15      : n
  22   TOMAS30      : n
  23   TOMAS40      : n
  24   RRTMG        : n
  25   MASSCONS     : n
  26   TIMERS       : 0
  27   TAU_PROF     : n
  28   BPCH_DIAG    : y
  29   COMPILER     : ifort 16.0.3
  30   Datetime     : 2019/08/21 19:02
  31 make[1]: Leaving directory '/glade/u/home/lixujin/GEOS-CHEM/rundirs/geosfp_4x5_standard'`
**GC**
` 2163 ===============================================================================
 2164 GEOS-Chem ERROR: Error encountered in "HCO_Run"!
 2165  -> at HCOI_GC_Run (in module GeosCore/hcoi_gc_main_mod.F90)
 2166
 2167 THIS ERROR ORIGINATED IN HEMCO!  Please check the HEMCO log file for
 2168 additional error messages!
 2169 ===============================================================================
 2170
 2171 ===============================================================================
 2172 GEOS-Chem ERROR: Error encountered in "HCOI_GC_Run"!
 2173  -> at Emissions_Run (in module GeosCore/emissions_mod.F90)
 2174 ===============================================================================
 2175
 2176 ===============================================================================
 2177 GEOS-CHEM ERROR: Error encountered in "Emissions_Run", Phase 0
 2178
 2179 This error can indicate a missing file. Please check the HEMCO log file for
 2180 additional error messages!
 2181
 2182 STOP at  -> at GEOS-Chem (in GeosCore/main.F)
 2183 ===============================================================================` 
**HEMOCO log file**
` 269 Use emissions extension `Volcano`:
 270  - use the following species (Name, HcoID, Scaling relative to kgS):
 271  SO2,           26,    2.000000
 272  Apply scale field: none
 273   - Emissions data source is AeroCom
 274   - Emit eruptive emissions as category           51
 275   - Emit degassing emissions as category           52
 276 -------------------------------------------------------------------------------
 277 Use inorganic iodine emissions (extension module)
 278  HOI: HOI         145
 279  I2: I2         146
 280 Changed Diagn name to BIOFUEL_CO_a
 281 HEMCO WARNING: Data is treated as unitless, but file attribute suggests it is not: m2 s-2. File: /glade/p/univ/uumm0001/geos-chem/ExtData/GEOS_4x5/GEOS_FP/2011/01/GEOS
     FP.20110101.CN.4x5.nc
 282 --> LOCATION: HCOIO_READ_STD (hcoio_read_std_mod.F90)
 283 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 284 HEMCO ERROR: Cannot find file for current simulation time: /glade/p/univ/uumm0001/geos-chem/ExtData/HEMCO/OLSON_MAP/v2019-02/Olson_2001_Land_Type_Masks.025x025.generic
     .nc - Cannot get field LANDTYPE00. Please check file name and time (incl. time range fla
 285 ERROR LOCATION: HCOIO_READ_STD (hcoio_read_std_mod.F90)
 286 ERROR LOCATION: HCOIO_DataRead (hcoio_dataread_mod.F90)
 287 ERROR LOCATION: ReadList_Fill (hco_readlist_mod.F90)
 288 ERROR LOCATION: ReadList_Read (hco_readlist_mod.F90)
 289 ERROR LOCATION: HCO_RUN (hco_driver_mod.F90)
 290
 291 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 292 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 293 HEMCO ERROR: Error encountered in routine HCOIO_Read_Std!
 294 ERROR LOCATION: HCOIO_READ_STD (hcoio_read_std_mod.F90)
 295 ERROR LOCATION: HCOIO_DataRead (hcoio_dataread_mod.F90)
 296 ERROR LOCATION: ReadList_Fill (hco_readlist_mod.F90)
 297 ERROR LOCATION: ReadList_Read (hco_readlist_mod.F90)
 298 ERROR LOCATION: HCO_RUN (hco_driver_mod.F90)
 299
 300 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 301
 302 -------------------------------------------------------------------------------
 303 HEMCO v2.1.012 FINISHED.
 304 Warnings (level 1 or lower):      1
 305 -------------------------------------------------------------------------------`

**Comment by yantosca** [comment]
Thanks for sending the information.  It looks like you don't have the new MODIS_XLAI data.  These were added in GEOS-Chem 12.3.0.  You might need to download these to your shared data directories on your server:

http://wiki.geos-chem.org/GEOS-Chem_12#New_data_directories_in_12.3.0

along with these, if you haven't already
http://wiki.geos-chem.org/GEOS-Chem_12#New_data_directories_in_12.3.2
http://wiki.geos-chem.org/GEOS-Chem_12#New_data_directories_in_12.4.0

**Comment by lizziel** [comment]
@jinlx Another way of including the log files is to drag the files into the issue. A link will appear which makes the issue content more compact. You may need to rename the files to have .txt extension. See GitHub docs for more information: https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests.

Here is an example of what the link to file would look like:
[HISTORY.rc.txt](https://github.com/geoschem/geos-chem/files/3531529/HISTORY.rc.txt)

**Comment by jinlx** [comment]
Thanks for your suggestion and sorry for the inconvenience I bring. I would keep it in mind next time.

Thanks again,
Lixu
