### ISSUE TITLE
[QUESTION] Can it output chemical production and loss rates of NOx 

### ISSUE THREAD

**Issue by hongjianweng** [geoschem/geos-chem#463]
Hi all,

I want to calculate lifetime of NOx and I need to output chemical production and loss rates of NOx.
As wiki said, some quantities in this collection are not applicable to certain simulations.
I set Prod_NO, Prod_NO2, Loss_NO and Loss_NO2 in HISTORY.rc, but it didn't work.
So I wonder whether I can output Prod_NO, Prod_NO2, Loss_NO and Loss_NO2 and how?

Thanks for your help!

Hongjian

**Comment by xpye98** [comment]
You have to define them in KPP as
http://wiki.seas.harvard.edu/geos-chem/index.php/FlexChem#Production_.26_loss_diagnostic

**Comment by yantosca** [comment]
Thanks @xpye98 for supplying the link.  Yes, you must add all P/L species via KPP because KPP has to compute that internally.

I can close out this issue for now.  Feel free to reply.
