### ISSUE TITLE
[FEATURE REQUEST] Remove RRTMG binary diagnostics in 13.1

### ISSUE THREAD

**Issue by lizziel** [geoschem/geos-chem#466]
Following updates documented in GEOS-Chem issue https://github.com/geoschem/geos-chem/issues/350, the RRTMG diagnostics available in binary format are also comprehensively available in netcdf format. This enables retiring the binary option. This update will go into 13.1.

**Comment by lizziel** [comment]
This update is PR https://github.com/geoschem/geos-chem/pull/651.

**Comment by msulprizio** [comment]
The pull request mentioned above is now merged into `dev` and will be included in 13.1.0.

**Comment by lizziel** [comment]
Validation of the netcdf diagnostics was performed by comparing 1-day mean output against the equivalent binary output using GEOS-Chem Classic 13.0. Results are viewable at:
http://ftp.as.harvard.edu/gcgrid/geos-chem/validation/RRTMG_bpch_vs_netcdf/13.0/gcc_13.0_rrtmg_bpch_vs_nc.pdf

All RRTMG diagnostic differences are small numerical differences introduced within the model due to precision differences in the internal arrays used to calculate the data. GEOS-Chem History calculates the data output to netCDF format and uses REAL8 internal arrays for accumulating and averaging data. GEOS-Chem legacy code for calculating data output to binary format using REAL4.
