### ISSUE TITLE
[QUESTION]How to read NC files with vertical layers more than 72 using HEMCO?

### ISSUE THREAD

**Issue by Rainbow1994** [geoschem/geos-chem#467]
## How to read nc files with vertical layers more than 72 using HEMCO?
Hi there,
I tried to use the HEMCO module to read a multi-layer mask file by setting HEMCO_Config.rc  just as: 
![image](https://user-images.githubusercontent.com/29177864/94628566-361c6280-02b8-11eb-9d69-606f3d14272c.png)
The geos.mp didn't work with the number of vertical layers being larger than 72. 
![image](https://user-images.githubusercontent.com/29177864/94629095-a7a8e080-02b9-11eb-847a-29621a6efc88.png)
When I set the configure item in HEMCO_Config.rc like:
![image](https://user-images.githubusercontent.com/29177864/94629251-1b4aed80-02ba-11eb-96fd-36db1b3c8603.png)
The errors information is:
![image](https://user-images.githubusercontent.com/29177864/94629348-62d17980-02ba-11eb-83fa-38637dbac63b.png)
I wonder if there is a correct way just need to configure some items to achieve my goal, or do I need to modify the source code?

Many thanks in advance!

Best,
Rainbow

**Comment by yantosca** [comment]
A couple of thoughts:

1. I am not sure that masking works on the vertical dimension.  I believe that it only works in the horizontal.
2. There may be a problem with the format of your netCDF file.  Please make sure that all of the variables and attributes adhere to [the COARDS netCDF standards](http://wiki.seas.harvard.edu/geos-chem/index.php/The_COARDS_netCDF_conventions_for_earth_science_data).

**Comment by msulprizio** [comment]
Please note that the HEMCO vertical grids are defined in [Core/hco_vertgrid_mod.F90](https://github.com/geoschem/HEMCO/blob/main/src/Core/hco_vertgrid_mod.F90). If you need to add a new vertical grid, you would do so there.

I will close out this issue for now, but we welcome you to open a new issue on the [HEMCO issue page](https://github.com/geoschem/HEMCO/issues) if there are any further questions.
