### ISSUE TITLE
[QUESTION] convection and vertical diffusion

### ISSUE THREAD

**Issue by aschuh** [geoschem/geos-chem#468]
# Ask a question about GEOS-Chem:

GEOS-Chem-ers,

I'm involved in a transport comparison project using GEOS-Chem.  Recently we wanted to test the effects of "convection" and "vertical diffusion" on trace gas concentrations.  Results have been enlightening and very different for two models I'm looking at.  Hence I want to make sure I'm not missing anything on how I'm running GC.

I'm just using the switches in the namelist:
```
 %%% CONVECTION MENU %%% :
Turn on Cloud Conv?     : T
Turn on PBL Mixing?     : T
 => Use non-local PBL?  : T
Convect Timestep (min)  : 30
```
First question, is there anything "subtle" here, or can I assume if Conv=T, convection is running and if Conv=F, it isn't?  Same for vertical diffusion, which is only PBL mixing (I believe?) in GC.  With PBL mixing turned off then only resolved vertical velocity should be able to move tracers up and down.

I'm going to consider those "parameterized vertical motion" in GC.  I'm using well mixed PBL option so that is pretty straightforward. However, are there any written up details/notes on how the deep convective RAS scheme is implemented via CMFMC/DTRAIN (that might be helpful), or is that just "looking" at the code?

andrew

**Comment by yantosca** [comment]
You are correct.  The line:
```
Turn on Cloud Conv?     : T
```
toggles cloud convection on/off and scavenging of soluble tracers in cloud updrafts on/off. 

These lines
```
Turn on PBL Mixing?     : T
 => Use non-local PBL?  : T
```
toggle the mixed-layer mixing on/off, and also picks the complex (non-local) or simple (fully-mixed) scheme.

And I believe you are also correct that if you turn off both convection and transport, the only updraft would be from associated vertical motions in transport.  You can diagnose that with the netCDF 'AdvFluxVert` diagnostic.

Also, I would take a look at [these references](http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-FP#References).  Some of these are technical memos but I think [this document](https://gmao.gsfc.nasa.gov/pubs/docs/tm28.pdf) might have the info on the parameterization of the RAS scheme.  You might also get some useful info from [Karen Yu's paper](https://gmd.copernicus.org/articles/11/305/2018/gmd-11-305-2018.pdf).

**Comment by aschuh** [comment]
Bob, I've run 4 tests to investigate vertical mixing effects in GC for use in comparing to other CTMs.  I'm running GC v12.0.2 at 2x2.5 w/ MERRA2.  I'm running CarbonTracker 2017 CO2 fluxes (5 tracers) through the model for three years.  I've run a control w/ PBLMix "on" and well mixed (not non-local) and convection "on".  Then I ran tests w/ 1) convection turned off, 2) pbl mixing turned off and 3) convection and pbl mixing turned off.  I found some peculiar behavior w/ respect to mass conservation.  When I turn off pbl mixing, there seems to be a discrepancy in mass conservation, mostly in the bio tracer which presumably is varying quickly in space and time (diurnally) and can be both negative and positive.  Other tracers are somewhat unaffected.  This isn't a huge effect but enough to cause problems for CO2.  When I turn off PBL mixing and convection mixing, it gets much worse, manifesting in a 2-3 ppm offset in column XCO2, which is really big.  It seems to be mostly affecting the bio tracer and mostly tied to the PBL mixing.  I've cobbled together what I could for mass budgets from the 4 simulations (text pasted below).

Is there anyway somebody might be able to do a run w/ the fluxes I'm using and confirm I'm not crazy here?  Or is there some known mass conservation issues when one runs w/ pbl mixing turned off?

Please ping me if more info is needed here, thanks.

CONTROL

2016/1/1

%%%%% PRINT_GLOBAL_SPECIES_KG at pre-advection
Global sum [kg] for CO2_BG       =   2.8634283583536460E+15
 ===> :    4862178742.47415
Global sum [kg] for CO2_FF       =   3.3617788142579300E+15
 ===> :    5705366206.35965
Global sum [kg] for CO2_BIO      =   2.6278971982004050E+15
 ===> :    4449614685.84137
Global sum [kg] for CO2_FIRE     =   2.9859780936932960E+15
 ===> :    5075037642.77087
Global sum [kg] for CO2_OCN      =   2.7314986822331300E+15
 ===> :    4636336741.38168

2018/1/1

%%%%% PRINT_GLOBAL_SPECIES_KG at pre-advection
Global sum [kg] for CO2_BG       =   2.8634283583525530E+15
 ===> :    4935355876.33099
Global sum [kg] for CO2_FF       =   3.4347130781426545E+15
 ===> :    5912824534.08085
Global sum [kg] for CO2_BIO      =   2.6017168685619210E+15
 ===> :    4477247567.62059
Global sum [kg] for CO2_FIRE     =   3.0003382986005065E+15
 ===> :    5175417107.01972
Global sum [kg] for CO2_OCN      =   2.7102279396145700E+15
 ===> :    4667785900.89218

2019/1/1

%%%%% PRINT_GLOBAL_SPECIES_KG at pre-advection
Global sum [kg] for CO2_BG       =   2.8634283583525385E+15
 ===> :    4910352075.40809
Global sum [kg] for CO2_FF       =   3.4721504068503185E+15
 ===> :    5941285680.03606
Global sum [kg] for CO2_BIO      =   2.5839247258676435E+15
 ===> :    4428837559.55180
Global sum [kg] for CO2_FIRE     =   3.0079692778273645E+15
 ===> :    5161879352.29063
Global sum [kg] for CO2_OCN      =   2.7017897711729420E+15
 ===> :    4622006110.78536

###########

NOCONVECTION

2016/1/1

%%%%% PRINT_GLOBAL_SPECIES_KG at pre-advection
Global sum [kg] for CO2_BG       =   2.8634283583536460E+15
 ===> :    4862178742.47415
Global sum [kg] for CO2_FF       =   3.3617788142579300E+15
 ===> :    5705366206.35965
Global sum [kg] for CO2_BIO      =   2.6278971982004050E+15
 ===> :    4449614685.84137
Global sum [kg] for CO2_FIRE     =   2.9859780936932960E+15
 ===> :    5075037642.77087
Global sum [kg] for CO2_OCN      =   2.7314986822331300E+15
 ===> :    4636336741.38168

2018/1/1

%%%%% PRINT_GLOBAL_SPECIES_KG at pre-advection
Global sum [kg] for CO2_BG       =   2.8634283575411875E+15
 ===> :    4935355970.70056
Global sum [kg] for CO2_FF       =   3.4347130781855110E+15
 ===> :    5913592435.54604
Global sum [kg] for CO2_BIO      =   2.6017168948569010E+15
 ===> :    4476905754.23947
Global sum [kg] for CO2_FIRE     =   3.0003382985061960E+15
 ===> :    5175247833.28228
Global sum [kg] for CO2_OCN      =   2.7102279395587945E+15
 ===> :    4668498880.81675

2019/1/1

%%%%% PRINT_GLOBAL_SPECIES_KG at pre-advection
Global sum [kg] for CO2_BG       =   2.8634283575410240E+15
 ===> :    4910352304.06423
Global sum [kg] for CO2_FF       =   3.4721504068929030E+15
 ===> :    5939606309.28284
Global sum [kg] for CO2_BIO      =   2.5839247521624590E+15
 ===> :    4430821225.80210
Global sum [kg] for CO2_FIRE     =   3.0079692777333590E+15
 ===> :    5161176799.10327
Global sum [kg] for CO2_OCN      =   2.7017897711175755E+15
 ===> :    4619584654.67508

######

NOPBL

2016/1/1

%%%%% PRINT_GLOBAL_SPECIES_KG at pre-advection
Global sum [kg] for CO2_BG       =   2.8634283583536460E+15
 ===> :    4862178742.47415
Global sum [kg] for CO2_FF       =   3.3617788142579300E+15
 ===> :    5705366206.35965
Global sum [kg] for CO2_BIO      =   2.6278971982004050E+15
 ===> :    4449614685.84137
Global sum [kg] for CO2_FIRE     =   2.9859780936932960E+15
 ===> :    5075037642.77087
Global sum [kg] for CO2_OCN      =   2.7314986822331300E+15
 ===> :    4636336741.38168

2018/1/1

%%%%% PRINT_GLOBAL_SPECIES_KG at pre-advection
Global sum [kg] for CO2_BG       =   2.8634283578549425E+15
 ===> :    4935355970.70056
Global sum [kg] for CO2_FF       =   3.4347130780091305E+15
 ===> :    5912747833.80259
Global sum [kg] for CO2_BIO      =   2.6019198977565420E+15
 ===> :    4477699640.86669
Global sum [kg] for CO2_FIRE     =   3.0003382985653920E+15
 ===> :    5175370329.79380
Global sum [kg] for CO2_OCN      =   2.7102279394894870E+15
 ===> :    4668208634.30538

2019/1/1

%%%%% PRINT_GLOBAL_SPECIES_KG at pre-advection
Global sum [kg] for CO2_BG       =   2.8634283578547375E+15
 ===> :    4910352283.32074
Global sum [kg] for CO2_FF       =   3.4721504067169915E+15
 ===> :    5938561620.45170
Global sum [kg] for CO2_BIO      =   2.5847153135415640E+15
 ===> :    4430895279.20534
Global sum [kg] for CO2_FIRE     =   3.0079692777923420E+15
 ===> :    5161389953.83970
Global sum [kg] for CO2_OCN      =   2.7017897710479925E+15
 ===> :    4618929882.15044

#########

NO_CONVECTION_NO_PBL

2016/1/1

%%%%% PRINT_GLOBAL_SPECIES_KG at pre-advection
Global sum [kg] for CO2_BG       =   2.8634283583536460E+15
 ===> :    4862178742.47415
Global sum [kg] for CO2_FF       =   3.3617788142579300E+15
 ===> :    5705366206.35965
Global sum [kg] for CO2_BIO      =   2.6278971982004050E+15
 ===> :    4449614685.84137
Global sum [kg] for CO2_FIRE     =   2.9859780936932960E+15
 ===> :    5075037642.77087
Global sum [kg] for CO2_OCN      =   2.7314986822331300E+15
 ===> :    4636336741.38168

2018/1/1

Global sum [kg] for CO2_BG       =   2.8634283579955690E+15
 ===> :    4935355970.70056
Global sum [kg] for CO2_FF       =   3.4347130782658100E+15
 ===> :    5918012452.98405
Global sum [kg] for CO2_BIO      =   2.6097968536115125E+15
 ===> :    4485660353.65045
Global sum [kg] for CO2_FIRE     =   3.0003382987201125E+15
 ===> :    5175770589.09577
Global sum [kg] for CO2_OCN      =   2.7102279397028260E+15
 ===> :    4667869623.25916

2019/1/1

%%%%% PRINT_GLOBAL_SPECIES_KG at pre-advection
Global sum [kg] for CO2_BG       =   2.8634283579953460E+15
 ===> :    4910352341.18848
Global sum [kg] for CO2_FF       =   3.4721504069732830E+15
 ===> :    5939830427.76961
Global sum [kg] for CO2_BIO      =   2.5985397017844095E+15
 ===> :    4452412931.26550
Global sum [kg] for CO2_FIRE     =   3.0079692779475910E+15
 ===> :    5161073532.85665
Global sum [kg] for CO2_OCN      =   2.7017897712611200E+15
 ===> :    4622608787.05502

**Comment by yantosca** [comment]
Hi @andrew, thanks for writing.  We have been occupied trying to release 13.0.0.  I think this might be more of a science issue for the Transport Working Group to consider.  Maybe @hongyuliu3 or @kbowman77 might have some insights.

**Comment by aschuh** [comment]
WIth the help of C. Keller, I was able to track this issue down to a line of code which truncates negative concentrations in mixing_mod.F90.  

             ! Prevent negative concentrations. (ckeller, 3/29/16)
             State_Chm%Species(I,J,L,N) = MAX(State_Chm%Species(I,J,L,N),0.0_fp)

In rare cases, with strong fluxes near surface, e.g. w/ CO2 and pbl mixing off, AND negative fluxes such as bio drawdown, this can create small local negative concentrations which when truncated, result in a mass conservation error on longer time frames.  I will try to bring this up the transport group as longer lived gases such as CO2 have the biggest risk of being affected.
