### ISSUE TITLE
[BUG/ISSUE] GEOS-FP TROPPT field has several zeroes on 2020/05/11

### ISSUE THREAD

**Issue by hansen20** [geoschem/geos-chem#471]
## Describe the bug:
The values of tropopause pressure (‘TROPPT’) from file “GEOSFP.20200511.A1.2x25.nc” are 0 at many grids.

**Comment by Jun-Meng** [comment]
I'm still working on with this issue.

**Comment by Jun-Meng** [comment]
Hi @msulprizio, I have been working on this issue last week. I think it's most likely because the raw data files for May 11 were somehow corrupted. so I was wondering if you could re-download the data for that day and transfer it to stetson? Thanks

**Comment by msulprizio** [comment]
@Jun-Meng All set. The files for 2020/05/11 have been transferred over to Stetson again. You can find them at `/scratch2/upload/GEOS-5.22fp/2020/M05/f522_fp*`.

**Comment by Jun-Meng** [comment]
Hi @hansen20, the bug has been fixed and the data for May 11 2020 has been updated. Thanks again for reporting this issue.
