### ISSUE TITLE
[FEATURE REQUEST] Clean up time cycle flags used in HEMCO_Config.rc

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#475]
It has been an ongoing concern in the community that users might be unknowingly using emissions for past years in their simulations. Traditionally, the time cycle flag `C` is used for emissions datasets so that the last year of emissions is used if running beyond the last year available. To avoid confusion, the GEOS-Chem Steering Committee has requested that we change this default behavior and instead have HEMCO stop with an error message when users attempt to use an emissions field or input dataset that is not available for their simulation year(s). This can be achieved by changing the time cycle flag to `RF` for example. Users will always have the option to change the time cycle flag to ignore this error and use the last year available, but in this way they will be forced to know exactly what data are being used.

**Comment by msulprizio** [comment]
This update is now pushed in commit https://github.com/geoschem/geos-chem/commit/89e136126d3258c1e9ce75e05c039c8e06132077. From that commit message:

>We have changed the time cycle flag to 'RF' for regional inventories that are provided for multiple years. This will force HEMCO to crash with an error that the current time isn't available if a user attempts to use the inventory for a year outside of it's coverage. Users can always manually revert to the 'C' time cycle flag to use the latest year
available. We do not use the 'RF' flags for global inventories (e.g. CEDS) because this would cause all GEOS-Chem and HEMCO standalone simulations for 2018 and after to crash due to unavailable data. The benchmark simulations are now for 2019 and would crash in that case, so we keep the time cycle flag for CEDS and other global inventories as 'C'.
>
>Finally, comments have been added to the emission switches section to make it clear what years each emissions inventory and dataset are available. This should help users when choosing which inventories to turn on/off for their simulations. 

For example, we now have:

```
###############################################################################
### BEGIN SECTION EXTENSION SWITCHES
###############################################################################
# ExtNr ExtName                on/off  Species  Years avail.
0       Base                   : on    *           
# ----- MAIN SWITCHES -----------------------------------------
    --> EMISSIONS              :       true
    --> METEOROLOGY            :       true     # 1980-2020
    --> CHEMISTRY_INPUT        :       true
# ----- RESTART FIELDS ----------------------------------------
    --> GC_RESTART             :       true
    --> STATE_PSC              :       true
    --> HEMCO_RESTART          :       true
# ----- NESTED GRID FIELDS ------------------------------------
    --> GC_BCs                 :       false    # 1980-2020
# ----- REGIONAL INVENTORIES ----------------------------------
    --> APEI                   :       false    # 1989-2014
    --> NEI2011_HOURLY         :       false    # 2006-2013
    --> NEI2011_MONMEAN        :       false    # 2006-2013
    --> MIX                    :       false    # 2008-2010
    --> DICE_Africa            :       false    # 2013
# ----- GLOBAL INVENTORIES ------------------------------------
    --> CEDS                   :       true     # 1970-2017
    etc.
```

**Comment by lizziel** [comment]
Please note the time cycle flags are only relevant for GEOS-Chem Classic. HEMCO time cycle flags are not used in GCHP and MAPL does not yet have the capability to force some but not other inventories to only dates and times available.
