### ISSUE TITLE
[QUESTION] Aerocom Volcano emissions 

### ISSUE THREAD

**Issue by uarporn** [geoschem/geos-chem#477]
I have a few questions related to daily volcano emissions from 2000-2019 listed in this directory:
 
$ROOT/VOLCANO/v2019-04/$YYYY/$MM/so2_volcanic_emissions_Carns.$YYYY$MM$DD.rc
 
1.	Looks like emissions are constant each day in a given year. For example, Redoubt in Alaska (60.49, -152.75) has 2009  emissions of 1289 kt SO2/year, which I believe, mostly related to the eruptive activities in March lasting a few months [https://en.wikipedia.org/wiki/2009_Mount_Redoubt_eruptive_activity]. These eruptive emissions are distributed uniformly each day (at 20.4 kgS/s) in the AEROCOM EI. The OMPS measurements provide daily coverage so I was expecting temporal variation at least on a daily basis. Is there another set of dataset that has temporal variation in each calendar year? Any suggestion on how I can account for the day-to-day variation?   
 
2.	Do these volcano emissions include both degassing and eruptive? In the prior version, eruptive and degassing can be turned on/off. If I follow the old implementation “If the elevation is the same as the cloud column height, the volcano is considered degassing”, emissions from Redoubt would be categorized as degassing all year round in 2009 with the elevation and cloud column constant at 3108 m.  
 
Any lead will help. Thank you.

**Comment by msulprizio** [comment]
From [VOLCANO/v2019-08/README](http://ftp.as.harvard.edu/gcgrid/data/ExtData/HEMCO/VOLCANO/v2019-08/README):

>Valentina Aquila (valentina.aquila@nasa.gov) created these files by joining S. Carn's database, which includes only explosive volcanic eruptions, and degassing volcanic emissions by Thomas Diehl. The program used is 
convert_carn2geos5_degassing_explosive_TOGETHER.py SC database covers 5 Dec 1978 to 28 Apr 2018. 
>
>SC database contains an observed and an estimated injection altitude.  When available, the observed injection altitude has been used, if not the estimated altitude. 
>
>*** NOTE ***
>I have manually changed some volcanoes that appear to be overestimated after comparing the model results to SAGE, OSIRIS, and OMPS observations. I have also added the hours of the eruption when available. 

From that information, I can say the volcano emissions files include both degassing and eruptive emissions. It appears hourly information was only available for select volcanoes (listed in the README linked above). For additional information, I would recommend contacting the developer of these files and/or looking at the papers referenced in the README. 

Christoph Keller (NASA/GMAO) provided us with these files. @christophkeller Do you have anything to add? Or would you also recommend reaching out to Valentina Aquila (email above)?

**Comment by uarporn** [comment]
Thanks for your response. We missed the Redoubt eruption entries suggested in the README because latitude is slightly different from other entries (60.48 vs 60.49). So our previous emission total must be from degassing only, matching with Carn et al, 2017 (https://www.nature.com/articles/srep44095#Sec9). Looks like degassing emissions are distributed uniformly across the year (no day-to-day variation in a given year). I am still interested in getting finer temporal variation if it exists.

**Comment by msulprizio** [comment]
I am going to close out this issue for now. Please follow up with the developer of these emissions and/or open a new issue if there are still remaining questions.
