### ISSUE TITLE
[BUG/ISSUE] Missing  OFFLINE_BIOVOC and OFFLINE_DUST data for Nov and Dec 2019 on http://geoschemdata.computecanada.ca/

### ISSUE THREAD

**Issue by MikhailKleymenov** [geoschem/geos-chem#479]
I want to run 2019 full-chemistry GEOS-Chem Classic standard simulation, but there is no OFFLINE_BIOVOC/v2019-10 and OFFLINE_DUST/v2019-01/ data for November and December on the http://geoschemdata.computecanada.ca/. Could you please tell me if i could expect this data to be uploaded to the server soon? If not, please tell me how could I better run full-year simulation without it or how could I calculate these data myself?

**Comment by msulprizio** [comment]
You do always have the option to set the offline emissions to `false` in HEMCO_Config.rc and setting the corresponding HEMCO extensions to `on`. In this case, if you turn off `OFFLINE_BIOGENICVOC` you would turn on `MEGAN`. If you turn off `OFFLINE_DUST` you would turn on `DustDead`.

@hongjianweng is in charge of updating the offline biogenic VOC emissions and @Jun-Meng (or @LiamBindle now?) is in charge of updating the offline dust emissions. They can provide the status update on those files. The offline emission files are generated by running the HEMCO standalone at the native GEOS-FP and MERRA-2 resolutions.

**Comment by Jun-Meng** [comment]
Currently I'm still in charge of updating the offline dust emissions.

**Comment by MikhailKleymenov** [comment]
A homogeneous set of input data is important for our project. @Jun-Meng, @hongjianweng could you please tell me in what time frame could I expect missing OFFLINE_BIOVOC and OFFLINE_DUST data to be uploaded to the server?

**Comment by hongjianweng** [comment]
Hi @MikhailKleymenov , I will upload OFFLINE_BIOVOC for  Nov and Dec 2019 in a week.
Thanks for waiting, we need to download the meteorological data, calculate and process data.
I will let you know as soon as we're done uploading.

**Comment by Jun-Meng** [comment]
> A homogeneous set of input data is important for our project. @Jun-Meng, @hongjianweng could you please tell me in what time frame could I expect missing OFFLINE_BIOVOC and OFFLINE_DUST data to be uploaded to the server?

Hi @MikhailKleymenov , I will try to update those dust emission files by the end of this month. it is partially my current ongoing research project. I will try to make sure that everything is fine! In the meanwhile, you are welcome to use the online dust emission instead. just simply turn off the office dust option and turn on the online dust option (Ext 105 in HEMCO_Config.rc). Thanks!

**Comment by MikhailKleymenov** [comment]
@Jun-Meng, @hongjianweng thank you very much for responding to my request! I will watch for updates on the server

**Comment by hongjianweng** [comment]
Hi @MikhailKleymenov ,

Thanks for waiting and BIOVOC data have been uploaded.

**Comment by MikhailKleymenov** [comment]
Hi, @hongjianweng, thanks!
