### ISSUE TITLE
[QUESTION] Low CO2 concentration

### ISSUE THREAD

**Issue by lucifer1004** [geoschem/geos-chem#484]
# Ask a question about GEOS-Chem:

I am running standard geos_fp_4x5 simulation, but I found the concentration of CO2 was too low in the restart file, which was around 8.8829f-13 at the lowest level. Can anyone help with this? Is there any misconfiguration?

**Comment by msulprizio** [comment]
Could you please provide more information about your simulation -- see [this wiki post](http://wiki.seas.harvard.edu/geos-chem/index.php/Submitting_GEOS-Chem_support_requests#What_do_I_need_to_include_in_my_support_request.3F) for a list of files and information we need to help diagnose the problem.

**Comment by lucifer1004** [comment]
@msulprizio I have submitted my configuration files to a standalone [repository](https://github.com/lucifer1004/geoschem-configuration).

**Comment by msulprizio** [comment]
@lucifer1004 Could you please also provide your log files for both HEMCO and GEOS-Chem?

**Comment by lucifer1004** [comment]
@msulprizio Log files have been added.

**Comment by msulprizio** [comment]
Thanks. I don't see anything amiss in your setup or log files. Are you using the sample restart file (linked to `ExtData/GEOSCHEM_RESTARTS/v2018-11/initial_GEOSChem_rst.4x5_benchmark.nc`? If so, it's important to note that is mean to be a sample file to help start your simulation, but concentrations don't necessarily actual atmospheric concentrations. To get representative species concentrations, we recommend spinning up your GEOS-Chem simulation for at least a year. For more details on restart files, see: http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_restart_files.

We've also made available restart files from recent 1-year benchmarks (1-year spinup, 1-year production run). You can access those restart files at http://ftp.as.harvard.edu/gcgrid/data/ExtData/GEOSCHEM_RESTARTS/ in subdirectories GC_12.Y.Z. You may want to try initializing your simulation with one of those restart files to see if that improves your results.

**Comment by lucifer1004** [comment]
@msulprizio I have downloaded the restart file `GEOSChem.Restart.fullchem.20160701_0000z.nc4` but after checking, I found the CO2 concentration in this restart file is also very low. Is there anything that I have misunderstood? Does the unit of CO2 concentration differ from those of other species?

**Comment by msulprizio** [comment]
In GEOS-Chem full-chemistry simulations, CO2 is a chemically active species but is not transported or emitted. This is because CO2 is a long-lived species and requires mult-year simulations to properly reproduce. If you're interested specifically in CO2, then you may consider running the CO2 simulation in GEOS-Chem. See the following wiki pages for more information:

- http://wiki.seas.harvard.edu/geos-chem/index.php/Simulations_overview
- http://wiki.seas.harvard.edu/geos-chem/index.php/CO2_simulation

**Comment by lucifer1004** [comment]
@msulprizio Thanks a lot for your detailed explanations.
