### ISSUE TITLE
[DISCUSSION] Change executable name from geos to something more apt

### ISSUE THREAD

**Issue by lizziel** [geoschem/geos-chem#485]
The GEOS-Chem executable has been called geos for a very long time. However, GEOS-Chem is not GEOS. I propose that we rename it to geoschem, or gchp, or something else that is not geos. Thoughts?

**Comment by msulprizio** [comment]
I think this makes sense too. I like Seb's suggestions for names because they follow the names of the wrapper repositories.

**Comment by lizziel** [comment]
This is now done in the dev/13.0.0 branch for GCHP.

**Comment by lizziel** [comment]
I'm doing this for GC-Classic now and wonder if we should have an extension to make it clear it is an executable. 
gchp.x and gcclassic.x?

**Comment by lizziel** [comment]
Looks like we dropped the `.x` from `hemco_standalone.x` in the switch from GNU make to CMake. GMAO uses `.x` but the Unix standard extension for executables is actually no extension. I'll stick with gchp and gcclassic.
