### ISSUE TITLE
[BUG/ISSUE] RRTMG does not compile with GNU Fortran

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#49]
The GEOS-Chem Support Team discovered that the RRTMG code in GEOS-Chem does not compile with the gfortran compiler. The compile error is included below for reference. While users still have the option to use the IFORT compilers, this is somewhat problematic for our movement towards using open-source software. For example, if users run GEOS-Chem on the Amazon Web Services cloud computing environment, we recommend that they use gfortran. We’ve also been using gfortran 7.1.0 for our unit tests because that compiler tends to be more strict.

We wanted to alert you to this unresolved issue in case anyone is interested in pursuing a fix with the folks at AER and/or updating RRTMG in GEOS-Chem. The GCST typically tries to remain hands-off with third party code (e.g. RRTMG, ISORROPIA) in GEOS-Chem. It appears that RRTMG v3.0 was implemented in GEOS-Chem. The latest RRTMG version is 3.3, so it may be that the issue has been resolved on AER’s end but that’s not clear.

```gfortran -cpp -w -std=legacy -fautomatic -fno-align-commons -fconvert=big-endian -fno-range-check -O1 -override-limits -fopenmp -mcmodel=medium -fbacktrace -g -DLINUX_GFORTRAN -DBPCH_DIAG -DBPCH_TIMESER -DBPCH_TPBC -DRRTMG -DGEOS_FP -DGRIDREDUCED -DGRID4x5 -DNC_HAS_COMPRESSION -DUSE_REAL8 -J../mod -I/n/helmod/apps/centos7/MPI/gcc/7.1.0-fasrc01/openmpi/2.1.0-fasrc02/netcdf/4.3.2-fasrc05/include -I/n/helmod/apps/centos7/MPI/gcc/7.1.0-fasrc01/openmpi/2.1.0-fasrc02/netcdf-fortran/4.4.0-fasrc03/include -fdefault-real-8 -fdefault-double-8 -c -O1 -override-limits rrtmg_sw_rad.F90
rrtmg_lw_k_g.F90:4298:0:

       subroutine lw_kgb03

note: variable tracking size limit exceeded with -fvar-tracking-assignments, retrying without

ar crs librad.a rrsw_cld.o rrlw_kg01.o mcica_random_numbers.o rrlw_kg09.o mcica_subcol_gen_sw.o rrlw_wvn.o rrsw_kg28.o rrtmg_sw_setcoef.o rrsw_kg23.o parkind.o rrlw_cld.o rrlw_ncpar.o rrsw_kg29.o rrlw_tbl.o rrsw_kg17.o rrlw_kg11.o rrtmg_sw_spcvmc.o rrsw_tbl.o rrtmg_sw_init.o parrrtm.o rrtmg_sw_k_g.o rrlw_kg04.o rrsw_kg18.o rrlw_kg02.o rrtmg_lw_k_g.o rrtmg_lw_init.o rrtmg_lw_taumol.o rrsw_con.o rrtmg_lw_rtrnmc.o rrsw_kg19.o rrtmg_sw_rad.o rrsw_kg21.o rrsw_kg27.o rrlw_kg16.o rrsw_kg26.o rrsw_ref.o rrtmg_lw_setcoef.o rrtmg_sw_reftra.o rrsw_aer.o rrsw_vsn.o rrlw_kg10.o rrlw_ref.o test_arr_mult.o rrlw_kg12.o rrlw_con.o parrrsw.o rrsw_kg22.o rrsw_kg20.o rrlw_vsn.o rrlw_kg15.o rrtmg_sw_taumol.o rrsw_kg25.o rrsw_kg16.o rrlw_kg03.o rrtmg_lw_cldprmc.o rrlw_kg05.o rrlw_kg14.o rrtmg_sw_cldprmc.o rrlw_kg06.o rrtmg_sw_vrtqdr.o rrlw_kg13.o rrlw_kg07.o rrlw_kg08.o rrsw_wvn.o rrtmg_lw_rad.o rrsw_kg24.o mcica_subcol_gen_lw.o
ar: rrsw_cld.o: No such file or directory
make[4]: *** [lib] Error 1
make[4]: Leaving directory `/n/home05/msulprizio/GC/Code.Dev/GeosRad'
make[3]: *** [librad] Error 2
make[3]: Leaving directory `/n/home05/msulprizio/GC/Code.Dev/GeosCore'
make[2]: *** [lib] Error 2
make[2]: Leaving directory `/n/home05/msulprizio/GC/Code.Dev/GeosCore'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/n/home05/msulprizio/GC/Code.Dev/GeosCore'
make: *** [all] Error 2```

**Comment by yantosca** [comment]
I added commit https://github.com/geoschem/geos-chem/commit/dd97b4154727341faa00ae230f15f8480814177a to resolve some minor syntax errors.  This code now compiles to completion using a Spack-built software stack based on GNU Fortran 9.2.0.

NOTE: The GNU Fortran 8.2.0 compiler that we use on Odyssey (soon to be Cannon) historically has had issues compiling this.  This might be due to errors during the compiler's installation (but I cannot be sure of it).

**Comment by yantosca** [comment]
I should note that using CMake got the RRTMG code to compile.  Using GNU Make did not.

**Comment by yantosca** [comment]
RRTMG actually can now compile with CMake and GNU Make with GNU Fortran 9.2.
