### ISSUE TITLE
[BUG/ISSUE] Error: netcdf-c matches multiple packages

### ISSUE THREAD

**Issue by wintriv** [geoschem/geos-chem#490]
# Report a GEOS-Chem bug or technical issue
I have had some difficulty in the process of installing netcdf using spack on my Linux Mint OS. Somehow I cannot find the log file--  but it looked like I have it installed. But now when I do "spack location -i netcdf-c"  I would get this error message:
==> Error: netcdf-c matches multiple packages.
  Matching packages:
    i5vhc64 netcdf-c@4.7.4%gcc@9.3.0 arch=linux-linuxmint20-skylake
    otwoilc netcdf-c@4.7.4%gcc@9.3.0 arch=linux-linuxmint20-skylake
  Use a more specific spec.

So in the .bashrc where I would export  NETCDF_HOME =$(spack location -i netcdf-c)  the abovementioned error message would appear first thing when a new terminal is opened.
This error lead to my failure to compile geos -- which is similar to another posted thread https://github.com/geoschem/geos-chem/issues/80
Can someone advice what to do here?  

### Error messages

```
==> Error: netcdf-c matches multiple packages.
  Matching packages:
    i5vhc64 netcdf-c@4.7.4%gcc@9.3.0 arch=linux-linuxmint20-skylake
    otwoilc netcdf-c@4.7.4%gcc@9.3.0 arch=linux-linuxmint20-skylake
  Use a more specific spec.
```

### Your GEOS-Chem version and runtime environment:

 - GEOS-Chem version: 12.9.3
 - Compiler version: gfortran
 - netCDF version: 4.7.4
 - netCDF-Fortran version (if applicable): 4.5.3
 - Did you run on a computational cluster, on the AWS cloud: NO
   - If you ran on the AWS cloud, please specify the Amazon Machine Image (AMI) ID: __
 - Are you using GEOS-Chem "out of the box" (i.e. unmodified): YES
   - If you have modified GEOS-Chem, please list what was changed: __

### Additional context

In my attempt to deal with this multiple packages, I thought I would uninstall one of them.  So I tried poking with each of them. This is what I got: 
```
env@env-Z490-AORUS-ELITE-AC:~$ spack uninstall /otwoilc
==> Will not uninstall netcdf-c@4.7.4%gcc@9.3.0/otwoilc
The following packages depend on it:
    -- linux-linuxmint20-skylake / gcc@9.3.0 ------------------------
    isgzxrv netcdf-fortran@4.5.3

==> Error: There are still dependents.
  use `spack uninstall --dependents` to remove dependents too
env@env-Z490-AORUS-ELITE-AC:~$ spack uninstall /i5vhc64
==> Will not uninstall netcdf-c@4.7.4%gcc@9.3.0/i5vhc64
The following packages depend on it:
    -- linux-linuxmint20-skylake / gcc@9.3.0 ------------------------
    z7ketmv cdo@1.9.8

==> Error: There are still dependents.
  use `spack uninstall --dependents` to remove dependents too
env@env-Z490-AORUS-ELITE-AC:~$ spack uninstall /i5vhc64 --dependents
==> Error: Attempting to add compiler, version, or variant to spec netcdf-c@4.7.4%gcc@9.3.0~dap~hdf4~jna+mpi~parallel-netcdf+pic+shared arch=linux-linuxmint20-skylake ^hdf5@1.10.7%gcc@9.3.0~cxx~debug~fortran+hl~java+mpi+pic+shared~szip+threadsafe api=none arch=linux-linuxmint20-skylake ^hwloc@1.11.11%gcc@9.3.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml+pci+shared arch=linux-linuxmint20-skylake ^libiconv@1.16%gcc@9.3.0 arch=linux-linuxmint20-skylake ^libpciaccess@0.16%gcc@9.3.0 arch=linux-linuxmint20-skylake ^libxml2@2.9.10%gcc@9.3.0~python arch=linux-linuxmint20-skylake ^numactl@2.0.12%gcc@9.3.0 arch=linux-linuxmint20-skylake ^openmpi@3.1.6%gcc@9.3.0~atomics~cuda~cxx~cxx_exceptions+gpfs~java~legacylaunchers~lustre~memchecker~pmi~singularity~sqlite3+static~thread_multiple+vt+wrapper-rpath fabrics=none schedulers=none arch=linux-linuxmint20-skylake ^xz@5.2.5%gcc@9.3.0~pic arch=linux-linuxmint20-skylake ^zlib@1.2.11%gcc@9.3.0+optimize+pic+shared arch=linux-linuxmint20-skylake which is already concrete. This is likely the result of adding to a spec specified by hash.
```

**Comment by WilliamDowns** [comment]
Can you try `spack uninstall --dependents /i5vhc64`? I think that Spack's parser is interpreting `--dependents` as a modifier to your package spec (like if you had typed `/i5vhc64@1.0` for example) rather than as an argument to the uninstall command. Confirmed that this change works on my end.

**Comment by wintriv** [comment]
Thank you William. Successfully removed the package.
issue solved.
