### ISSUE TITLE
[BUG/ISSUE] Biomass burning CO emissions from hemco_diagnostic*.nc are ~2X higher than raw data.

### ISSUE THREAD

**Issue by jinlx** [geoschem/geos-chem#492]
Hi there,

I am running 4x5 simulations with GFAS from 2018 July to 2018 September in GC12.9.3. I compared the biomass burning CO from nc output with raw data in ./ExtData/HEMCO/GFAS/v2018-09/2018/GFAS_*.nc. It turns out that CO emissions are about 240 Tg globally which is ~2X higher than the value from raw data. I checked bpch files from GC12.5.0. It looks good. I was wondering if anyone have any insights on the difference. My hemco_diagnostic nc ouput and input files are provided below just in case. 

[HEMCO_diagnostics.zip](https://github.com/geoschem/geos-chem/files/5441855/HEMCO_diagnostics.zip)

Cheers,
Lixu

**Comment by msulprizio** [comment]
I see you're applying the following scale factors to the GFAS data in HEMCO_Config.rc:

```
#==============================================================================
# --- GFAS biomass burning ---
#==============================================================================
(((GFAS
0 GFAS_CO    $ROOT/GFAS/v2018-09/$YYYY/GFAS_$YYYY$MM.nc cofire        2003-2020/1-12/1-31/0 C xyL=1:scal300 kg/m2/s CO   75     5 3

...

#==============================================================================
# --- QFED2 diurnal scale factors ---
#
# Fire diurnal scaling factors (% per hour) from WRAP Report to Project
# No. 178-6, July 2005
#==============================================================================
# lxu, modify for all inventories
(((QFED2.or.GFAS.or.OFFLINE_GFED4.or.OFFLINE_FINN
75 QFED2_TOD 0.1392/0.1392/0.1368/0.1368/0.1368/0.1368/0.1368/0.1368/0.1368/0.48/0.96/1.68/2.4/3.12/3.84/4.08/2.88/1.68/0.96/0.1368/0.1368/0.1368/0.1368/0.1368 - - - xy unitless 1
)))QFED2.or.GFAS.or.OFFLINE_GFED4.or.OFFLINE_FINN

#==============================================================================
# --- GFAS scale factors ---
#==============================================================================
# lxu, modify fir all inventories, using GFAS injection scheme
(((QFED2.or.GFAS.or.OFFLINE_GFED4.or.OFFLINE_FINN
300 GFAS_EMITL $ROOT/GFAS/v2018-09/$YYYY/GFAS_$YYYY$MM.nc mami 2003-2020/1-12/1-31/0 C xy m 1
)))QFED2.or.GFAS.or.OFFLINE_GFED4.or.OFFLINE_FINN
```

Have you tried removing those scaling factors from the GFAS entries to see if you can reproduce the totals from the raw data?

Also, in your HEMCO_Diagn.rc file, you list `EmisCO_BioBurn` as 2-dimensional but you're distributing it vertically in HEMCO_Config.rc. Try changing the 2 to a 3 in the following line to see if that improves the diagnostic output.

```
EmisCO_BioBurn     CO     0    -1  -1   2   kg/m2/s  CO_emission_flux_from_biomass_burning
```

**Comment by jinlx** [comment]
Thanks for looking into the code Melissa! No I haven't tried removing the diurnal scale factor (75) here. The scale factors (75 and 300) for GFAS is the default setting. I assumed it would be fine before. But you've got a good point! I will try to remove the diurnal scale factor and change the dimension into 3 to see what will happen for 1 month simulation. Thanks!

**Comment by jinlx** [comment]
Hey @msulprizio ! After changing the dimention from 2 into 3 in HEMCO_Diagn.rc, the result doesn't change much. I test the simulation within GFAS from default setting as well. It shows same result: total emissions for CO is ~2X higher than the raw data in ./ExtData/HEMCO/GFAS/. 

Since the new version nc output is a little bit different from bpch output, I want to double check just in case that my calcualtion is wrong. There is only one element in time dimension. Is the data from HEMCO_diagnostics.*.nc still daily mean data if I save out the data for every month?

**Comment by msulprizio** [comment]
By default, the HEMCO diagnostic output will be monthly mean. You can change that by setting `DiagnFreq:                   Daily` near the top of HEMCO_Config.rc. See [this section of the HEMCO User's Guide](http://wiki.seas.harvard.edu/geos-chem/index.php/The_HEMCO_User's_Guide#Diagnostics_output_frequency_.28setting_DiagnFreq.29) for more options.

**Comment by jinlx** [comment]
Thanks @msulprizio ! I just want to follow up on this issue. I checked emissions for other three inventories as well- GFED4, FINN and QFED. It turns out the diagnostic output values for those offline emissions (GFAS and QFED) are overestimated by a factor of 2 but those online emissions (GFED4 and FINN) work good when comparing with raw data. I tried offline way for GFED4 and FINN as well. It also shows overestimation. I was wondering if it is related to my diagnostic setting. For HEMCO_Diagn.rc, I only changed extention number but leaving others as default. Do you think I need to make some changes to make the result right (e.g., category number)?

**Comment by msulprizio** [comment]
@jinlx Have you checked your computation taking kg/m2/s output from HEMCO and converting to Tg? I believe the bpch output did that conversion for you, so I'm wondering if there's a unit conversion in your post-processing step.

**Comment by jinlx** [comment]
Thanks for asking Melissa! I did it by multiplying the output with (1e5*1e5*4*5)*(60*60*24*30) to convert the kg/m2/s into Tg.

**Comment by msulprizio** [comment]
You may want to take the AREA field directly from the HEMCO_Config.rc output and multiply your emissions field by that  field to convert to kg/s. Then you would multiply by the number of seconds in the month and convert kg to Tg. You can do this in python or using a tool like [CDO](https://code.mpimet.mpg.de/projects/cdo). For example, with CDO:

```
# Extract area field (m2)
cdo selvar,AREA HEMCO_diagnostics.YYYYMMDD.nc AREA.nc

# Extract emissions field (kg/m2/s)
cdo selvar,EmisCO_BioBurn HEMCO_diagnostics.YYYYMMDD.nc EmisCO_BioBurn.nc

# Convert emissions field to kg/s
cdo mul EmisCO_BioBurn.nc AREA.nc EmisCO_BioBurn_kgs.nc

# Compute emissions total (Tg)
#     -mulc,30 -mulc,86400 converts seconds to month (September)
#     -divc,1e9 converts kg to Tg
#     fldsum computes total of all grid boxes
cdo fldsum -divc,1e9 -mulc,30 -mulc,86400 EmisCO_BioBurn_kgs.nc EmisCO_BioBurn_Total.nc
```

**Comment by jinlx** [comment]
Thanks for the writing @msulprizio ! I did try area filed from GC ouput. However, the overestimation for offline emissions in the GC12.9.3 doesn't change much.

**Comment by yantosca** [comment]
@jinlx, have you been able to resolve this problem?  If so, we can close out this issue.

**Comment by jinlx** [comment]
> @jinlx, have you been able to resolve this problem? If so, we can close out this issue.

Hey Bob! I still haven't soleved the problem yet. I am currently working on the old GC (v12.5.0), which looks good on this issue.

**Comment by yantosca** [comment]
Thanks much @jinlx   I'll close out this issue for now.  We are about to release GEOS-Chem 13.0.0....if you upgrade to this version and you still encounter the same problem, let us know.
