### ISSUE TITLE
[BUG/ISSUE] TOMAS40 simulations exit with a floating-point exception

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#50]
We were unit testing the TOMAS40 code in the GEOS-Chem v11-02-release-candidate (soon to be finalized as 12.0.0) with the debugging flags:

```make –j8 DEBUG=y BOUNDS=y FPEX=y NO_ISO=y ut &```

which revealed a a NaN error. This was thrown at line 903 of GeosCore/tomas_mod.F:

```           ERR_VAR = 'Gcout'
           ERR_MSG = 'After COND_NUC'
            ! check for NaN and Inf (win, 10/4/08)
            do jc = 1, icomp-1
               ERR_IND(1) = I
               ERR_IND(2) = J
               ERR_IND(3) = L
               ERR_IND(4) = 0
               **call check_value( Gcout(jc), ERR_IND, ERR_VAR, ERR_MSG )**

!               if( IT_IS_FINITE(Gcout(jc))) then
!                  print *,'xxxxxxxxx Found Inf in Gcout xxxxxxxxxxxxxx'
!                  print *,'Location ',I,J,L, 'comp',jc
!                  call debugprint( Nkout, Mkout, i,j,l,'After COND_NUC')
!                  stop
!               endif
            enddo```

This error might be caused by the several chemistry and emissions updates that have been added to GEOS-Chem. The GEOS-Chem Support Team has referred the error to the TOMAS development team, who will be investigating further.

**Comment by yantosca** [comment]
We welcome any assistance from the TOMAS team.

**Comment by yantosca** [comment]
Also see this discussion thread: #594

**Comment by yantosca** [comment]
NOTE: This might be resolved by using a well-spun-up TOMAS40 restart file.  It could be that the default TOMAS restart file contains "missing" values (1e-30) for several species, which may be causing the warning & segfaults.    We will try with a better default restart file to see if this issue is fixed.

**Comment by yantosca** [comment]
This issue seems to be fixed when using a properly spun up TOMAS40 restart file.  I'll close this out for now.  Also see the discussion thread #594 for the latest updates.
