### ISSUE TITLE
[BUG/ISSUE] SpeciesRst_?ALL? token in HISTORY.rc causes simulation to crash when writing restart file

### ISSUE THREAD

**Issue by melaniehammer** [geoschem/geos-chem#503]
## Describe the bug:
I am running v.12.1.0, and once my simulation gets to the point where it is writing a new restart file if I have the SpeciesRst_?ALL? token included in the HISTORY.rc file in the restart collection, the simulation will crash upon trying to write the new restart file with this error message:

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Nf_Def_Var: can not define variable : SpeciesRst_^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Code stopped from DO_ERR_OUT (in module NcdfUtil/m_do_err_out.F90)

This is an error that was encountered in one of the netCDF I/O modules,
which indicates an error in writing to or reading from a netCDF file!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
I am not sure what would be causing this behaviour? If I remove the token the simulation doesn't crash, but it gives me a basically useless restart file. I haven't been able to find any documentation for an error like this. There is no additional information given in the HEMCO.log file.

**Comment by yantosca** [comment]
Thanks for writing @melaniehammer.  I wonder if there is some kind of out-of-bounds error that is clobbering the species name.  Have you tried compiling with the debug options (DEBUG=y BOUNDS=y FPEX=y)?

There have been many fixes to the netCDF diagnostics since 12.1.0.  You might want to update to a newer version such as 12.9.3 to see if that fixes your issue.

**Comment by yantosca** [comment]
Hi @melaniehammer.  Can you send your input files (input.geos, HEMCO_Config.rc, etc) and log files?  

It may also be that there is a species that is not accounted for in the species database.  We need to check this.

**Comment by melaniehammer** [comment]
Hi Bob,

Thanks, I am using v12.1.0 code that has some changes to it by a group member, but I am using a run directory downloaded from the unit tester for the out of the box v12.1.0, so I suspect there is some discrepancy there because the group member doesn't have the same issue. If I just use the SpeciesRst_?ADV? token instead I don't get the same problem, and that seems to give me all of the species I need. So I think I will just leave it.

**Comment by yantosca** [comment]
OK.  It might be just a run directory mismatch or something.  I'll close out this issue then.  Feel free to open a new issue if you still have problems.

NOTE: In 13.0.0+, the run-directory generation will be contained in the code itself (and thus will eliminate any rundir-codedir version mismatches.
