### ISSUE TITLE
[BUG/ISSUE] Dust Accumulation

### ISSUE THREAD

**Issue by neyranaz** [geoschem/geos-chem#504]
Version: 12.7.0 ran from the AWS AMI

###### We've been seeing an issue of dust accumulation in an Aerosol Only Nested Grid Run

Hello, we've been working on two identical nested grid runs. To do them we created Boundary Conditions on an hourly basis, for daily files. The only two differences in our runs are the following: 

-  One has the GFAS option activated and the other does not.
- The one that has the GFAS option activated [does not include the (*) correction](https://github.com/geoschem/geos-chem/issues/226#issuecomment-721942939) suggested [here](ROOT/SAMPLE_BCs/v2019-12/tropchem/GEOSChem.BoundaryConditions)

After doing our run, however we've seen accumulation of DST1 and DST2 in the one that does not have the GFAS option activated. This is not happening in the other one. This issue was seen by someone else in the wiki, [here](http://wiki.seas.harvard.edu/geos-chem/index.php/Mineral_dust_aerosols#Update_29_Jun_2018), but apparently was corrected. We wonder if the fact we are using an offline aerosol only nested run is triggering the issue, whether if it is for the lack of the (*) or whether it is due to the use of GFAS.  Does this make any sense? 

You can see the dust accumulation in [a figure that we prepared](https://drive.google.com/file/d/1P97s9MlWEQmteKopiu2m9_MlXTZlrJ6m/view?usp=sharing) for you here.

**Comment by neyranaz** [comment]
I guess the main questions are: 

- Why don't we see accumulation in the Nested Grid Run 2? 
- Would you advise to redo the Nested Grid run 2, based on the lack of change from 0-23 to *, as [inquired here](https://github.com/geoschem/geos-chem/issues/226#issuecomment-721942939)

**Comment by msulprizio** [comment]
I would recommend you try to eliminate the differences between your two nested grid simulations. That is, make sure they both include the boundary condition fix and the same source code that relies on that fix. I would also recommend making sure your BCs are consistent with your nested-grid simulations. The nested run with GFAS enabled should use BCs from a global simulation with GFAS enabled and vice versa. 

You may also want to set Verbose and Warnings to 3 in HEMCO_Config.rc and enable debug printout in input.geos. That will allow you to difference the GEOS-Chem and HEMCO log files from your two simulations to see if you can find any other discrepancies.

**Comment by neyranaz** [comment]
Thank you for your reply Melissa! I guess we are not sure if you would suggest to rerun the Nested Grid run, where the * time-step correction wasn't included or if it doesn't really matter as the BCs are read hourly in both.

But much more importantly, we are concerned about the DST accumulation issue as we read on the wiki, that other people had a similar issue. That issue, occurred in the correct run that my PI supervised, (the one that did include the * correction and all the specifications suggested by Bob). We are concerned about this one, as we've seen that this particular DST accumulation issue seems to have been present in other runs too as it said in the wiki "The cumulative emission flux from all past time-steps were being added to the DST1 species", we are observing exactly the same, in the run where it is not supposed to happen, so we are not sure if we should just subtract the DST components assuming they are independent from each of the other species produced or if there is a particular fix issue with HEMCO/Extensions/hcox_dustdead_mod.F and its interaction with the time-step correction.

**Comment by neyranaz** [comment]
We were looking at this issue in 12.7.0. and we were thinking that the problem of accumulation could be most likely related to [GC not realizing some files are missing](https://github.com/geoschem/geos-chem/issues/355), and to [GC using earlier files](https://github.com/geoschem/geos-chem/issues/312). 

If this was the case, GC would be opening earlier Dust files, and mistakenly using them on later dates. 

For instance, when running the 20191002_20191231 segment we observed (eye on offline_dust): 

`GET_BOUNDARY_CONDITIONS: Found All BCs at 2019/10/03 23:45
---> DATE: 2019/10/03  UTC: 23:50  X-HRS:     47.833332
GET_BOUNDARY_CONDITIONS: Found All BCs at 2019/10/03 23:50
---> DATE: 2019/10/03  UTC: 23:55  X-HRS:     47.916668
GET_BOUNDARY_CONDITIONS: Found All BCs at 2019/10/03 23:55
     - Creating file for SpeciesConc; reference = 20191003 000000
        with filename = OutputDir/GEOSChem.SpeciesConc.20191003_0000z.nc4
---> DATE: 2019/10/04  UTC: 00:00  X-HRS:     48.000000
HEMCO: Opening /home/ubuntu/ExtData/HEMCO/OFFLINE_DUST/v2019-01/0.25x0.3125/2017/10/dust_emissions_025.20171002.nc
HEMCO: Opening /home/ubuntu/ExtData/HEMCO/OFFLINE_SEASALT/v2019-01/0.25x0.3125/2017/10/seasalt_025.20171002.nc
HEMCO: Opening /home/ubuntu/ExtData/GEOS_0.25x0.3125_NA/GEOS_FP/2019/01/GEOSFP.20190104.A1.025x03125.NA.nc`


While, when running the 20150802-20151203 segment, we observed: 

`HEMCO: Opening /home/ubuntu/ExtData/HEMCO/AEIC/v2015-01/AEIC.47L.gen.1x1.nc
HEMCO: Opening /home/ubuntu/ExtData/HEMCO/AFCID/v2018-04/PM25FINE_ECLIPSE_2015.geos.2x25.nc
HEMCO: Opening /home/ubuntu/ExtData/HEMCO/DMS/v2015-07/DMS_lana.geos.1x1.nc
HEMCO: Opening /home/ubuntu/ExtData/HEMCO/UVALBEDO/v2019-06/uvalbedo.geos.2x25.nc
HEMCO: Opening /home/ubuntu/ExtData/HEMCO/OFFLINE_AEROSOL/v2014-09/PH2O2.geos5.2x25.nc
HEMCO: Opening /home/ubuntu/ExtData/HEMCO/OFFLINE_AEROSOL/v2014-09/JH2O2.geos5.2x25.nc
HEMCO: Opening /home/ubuntu/ExtData/HEMCO/OFFLINE_AEROSOL/v2014-09/O3.geos5.2x25.nc
HEMCO: Opening /home/ubuntu/ExtData/HEMCO/OFFLINE_AEROSOL/v2014-09/NO3.geos5.2x25.nc
HEMCO: Opening /home/ubuntu/ExtData/HEMCO/OFFLINE_AEROSOL/v2014-09/THNO3.geos5.2x25.nc
HEMCO: Opening /home/ubuntu/ExtData/HEMCO/OH/v2014-09/v5-07-08/OH_3Dglobal.geos5.72L.2x25.nc
HEMCO: Opening /home/ubuntu/ExtData/HEMCO/GEIA/v2014-07/GEIA_monthscal.generic.1x1.nc
HEMCO: Opening /home/ubuntu/ExtData/HEMCO/EDGARv43/v2016-11/EDGAR_v43.Seasonal.1x1.nc
HEMCO: Opening /home/ubuntu/ExtData/HEMCO/NEI2005/v2014-09/scaling/NEI99.dow.geos.1x1.nc
HEMCO: Opening /home/ubuntu/ExtData/HEMCO/OFFLINE_DUST/v2019-01/0.25x0.3125/2015/08/dust_emissions_025.20150802.nc
HEMCO: Opening /home/ubuntu/ExtData/HEMCO/OFFLINE_SEASALT/v2019-01/0.25x0.3125/2015/08/seasalt_025.20150802.nc
HEMCO: Opening /home/ubuntu/ExtData/GEOS_0.25x0.3125_NA/GEOS_FP/2015/08/GEOSFP.20150802.A1.025x03125.NA.nc`

Does this make sense?

**Comment by msulprizio** [comment]
You may change the CRE flag for the offline dust emissions and meteorology fields to use `RF` instead of `C`. (NOTE: This is now the default in GEOS-Chem 13.0.0 and later. See https://github.com/geoschem/geos-chem/issues/475.) This will tell HEMCO to only use those files for dates that they are available, instead of using the closest available date. If your simulation is outside of the available date range, HEMCO will crash with an error saying it cannot find data for the available date and time. 

If offline dust emissions aren't available for your simulation date, you always have the option to turn off offline dust emissions and turn on the DustDead extension to compute dust emissions via the HEMCO extension.
