### ISSUE TITLE
[QUESTION] Changing biomass burning emission scaling of PBL vs Free Troposphere

### ISSUE THREAD

**Issue by chfite** [geoschem/geos-chem#506]
I am using GC 12.6.0 and I just wanted to verify my understanding is correct for how one goes about changing the vertical distribution of biomass burning emissions, using QFED in particular. I see in HEMCO_Config.rc that 65% of the emissions are released in the PBL and 35% in the free troposphere. If I just change those scale factors that are listed in HEMCO_Config.rc is that the only place I need to apply changes, if say for my own specific purposes, I wanted to release all 100% of the emissions in the PBL?

 I ask because I believe I saw in the source code that for GFED and FINN the scale factors are listed there in the code and not in HEMCO_Config.rc, like QFED and GFAS (and I know GFAS has it's own injection heights). So I just wanted to verify that I would only need to make that one edit in HEMCO_Config.rc to get the vertical distribution the way I would like.

**Comment by yantosca** [comment]
Thanks for writing @chfite.  I believe that is correct, you can try to partition QFED 100% into the boundary layer.  You can try it and see if it works.  If it doesn't, let us know.

GFED and FINN are HEMCO extensions (i.e. are computed from some base quantity like dry matter using met field inputs), so the scaling factors are in the extension code.  QFED and GFAS are base emissions (i.e. just read from disk), so the scale factors are in HEMCO_Config.rc.

**Comment by yantosca** [comment]
Hi @chfite... I was wondering if you have gotten this to work.  If so, would you consider posting a snippet from the HEMCO_Config.rc file here so that other users can follow your example?  Thanks!

**Comment by chfite** [comment]
Sure @yantosca. For simplicity I made the following changes to the vertical partitioning scale factors towards the bottom of my `HEMCO_Config.rc` file. For the PBL fraction I just changed it from 0.65 to 1.00, and for the free troposphere I changed it from 0.35 to 0.00, like so, in order to emit all of my BB emissions in the PBL:

<pre>
#==============================================================================
 --- QFED vertical partitioning ---
 Following Fischer et al. (2014) and Travis et al. (2016), emit 35% of QFED
 emissions above the PBL.
#==============================================================================
311 QFED_PBL_FRAC 1.00 - - - xy 1 1
312 QFED_FT_FRAC  0.00 - - - xy 1 1
</pre>

That was the simplest way to make the changes to get my desired results. However, I suppose doing so would mean there wouldn't be much of a purpose of opening the biomass burning emissions files for the free troposphere to begin with since they would be multiplied by 0 anyway. So one could also just remove the lines that emit emissions in the FT and remove the vertical partitioning scale factors all together. But my original method above was the easiest, and the better in terms of being able to easily modify it back if needed, or to change to other scale factors one may desire.

**Comment by yantosca** [comment]
That's fine @chfite.  I'll close out this issue. Thank you for your solution!
