### ISSUE TITLE
[FEATURE REQUEST] Replace HEMCO built-in unit conversions with scale factors in config file

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#51]
HEMCO checks the unit string in HEMCO_Config.rc for each emission and converts to HEMCO standard units (kg/m2/s) upon file read if the input units are different. For VOCS, it further converts to kgC/m2/s. The code for the unit conversions is in HEMCO/Core/hco_unit_mod.F90.

Since the automatic unit conversion is performed during HEMCO file read it does not get executed in GCHP which uses MAPL/ESMF for I/O. GCHP users must instead manually include the conversion information as scale factors in HEMCO_Config.rc. To increase clarity and to make GCHP and GCC better match we plan on removing the HEMCO built-in unit conversions and replacing them with scale factors in HEMCO_Config.rc. This change may result in small number differences due to order of operations and precision of scale factors.

**Comment by yantosca** [comment]
We are now aiming to do this for 13.0.0.

**Comment by yantosca** [comment]
I believe this issue is now resolved by the removal of carbon units for VOC species, which is detailed in https://github.com/geoschem/geos-chem/issues/309.  We can therefore now close out this issue.
