### ISSUE TITLE
[QUESTION] How to calculate the pressure levels from GEOS Chem CH4 profiles?

### ISSUE THREAD

**Issue by idfarhan** [geoschem/geos-chem#510]
I want to compare the GEOS Chem CH4 with a satellite dataset. I have simulated the CH4 with 47 levels and at an interval of 3 hours. To adjust the model data, I need to do the interpolation according to the pressure levels of the satellite datasets. How to calculate the pressure levels from atmosphere hybrid sigma pressure coordinate?

**Comment by yantosca** [comment]
Thanks for writing @idfarhan.  This wiki page has some information about computing pressure from hybrid grids: http://wiki.geos-chem.org/GEOS-Chem_vertical_grids#Reference_section_for_vertical_grids.

**Comment by yantosca** [comment]
I am going to close out this issue for now.   Feel free to create a new issue if you still have questions.
