### ISSUE TITLE
[QUESTION] A condensation coefficient  of a gas-to-particulate  species in database

### ISSUE THREAD

**Issue by yutao-chen** [geoschem/geos-chem#513]
Dear Sir or Madam:
          The  gas-phase species  can  partition to particulate phase  quickly due to its low vapor pressure.    Is there a "Quntity" representing condensation coefficient of this gas-phase species  in  file "species_database.F90"  ?

**Comment by yantosca** [comment]
Thanks for writing @yutao-chen.  At present there is no such coefficient but you can add one yourself if you feel that it is necessary.

**Comment by yantosca** [comment]
I am going to close out this issue for now.  Please feel free to open another issue if you are still having problems.
