### ISSUE TITLE
[QUESTION] Dry Deposition BIOFIT implementation

### ISSUE THREAD

**Issue by dpfinch** [geoschem/geos-chem#514]
Hello,

I've got a question regarding the implementation of some code in the dry deposition scheme which adjusts the stomatal resistance depending on light - I'm not sure I understand how the FORTRAN code works in this case.

drydep_mod.F90 calls the function BIOFIT with the variables DRYCOEFF, XLAI_FP, SUNCOS_FP, CFRAC_FP & NN.
Within the BIOFIT function (in drydep_toolbox_mod.F90), XLAI, SUNCOS and CFRAC are assigned to the array TERM. 
BIOFIT then calls SUNPARAM(TERM(2)) - where TERM(2) = XLAI (also in drydep_toolbox_mod.F90). 

The comments within SUNPARAM suggest that it expects to get any of LAI, SUNCOS or CFRAC to calculate the light correction. However, from what I can see, it only calls SUNPARAM once with LAI (through TERM(2)). 

Am I understanding this correctly? Does SUNPARAM only deal with LAI as input? Although if that is the case I don't understand how it can loop through this one number (X) in SUNPARAM ( = LAI value for a given grid square) without breaking. 

Thanks for your help (hopefully that made sense...),

Doug

**Comment by yantosca** [comment]
Thanks for writing @dpfinch.  I agree, this code is pretty badly written.  The algorithm is more or less unchanged from the original Wang et al 1998 paper.

```F90
!EOC
!------------------------------------------------------------------------------
!                   Harmonized Emissions Component (HEMCO)                    !
!------------------------------------------------------------------------------
!BOP
!
! !IROUTINE: SunParam_r8
!
! !DESCRIPTION: Subroutine SUNPARAM is called by BIOFIT to perform the
!  light correction used in the dry deposition and canopy NOx modules.
!\\
!\\
! !INTERFACE:
!
  SUBROUTINE SUNPARAM_R8( X )
!
! !DEFINED PARAMETERS:
!
    INTEGER, PARAMETER    :: NN = 3  ! # of variables (LAI, SUNCOS, CLDFRC)
!
! !INPUT/OUTPUT PARAMETERS:
!
    REAL*8, INTENT(INOUT) :: X(NN)   ! LAI, SUNCOS, or cloud fraction
!
! !REMARKS:
!  This routine is ancient code from Yuhang Wang.  It was part of the old
!  Harvard-GISS CTM and was ported into GEOS-Chem.  See this reference for
!  more information:
!                                                                             .
!    Wang, Y., D.J. Jacob, and J.A. Logan, "Global simulation of tropospheric
!     O3-NOx-hydrocarbon chemistry, 1. Model formulation", J. Geophys. Res.,
!     103/D9, 10,713-10,726, 1998.
!
! !REVISION HISTORY:
!  13 Dec 2012 - R. Yantosca - Added ProTeX headers
!  See https://github.com/geoschem/hemco for complete history
!EOP
!------------------------------------------------------------------------------
!BOC

    !===============================================
    ! the sequence is lai,suncos,cloud fraction
    !===============================================

    !  ND = scaling factor for each variable
    INTEGER ND(NN),I
    DATA ND /55,20,11/

    !  X0 = maximum for each variable
    REAL*8 X0(NN),XLOW
    DATA X0 /11.,1.,1./

    DO I=1,NN
       X(I)=MIN(X(I),X0(I))
       ! XLOW = minimum for each variable
       IF (I.NE.3) THEN
          XLOW=X0(I)/REAL(ND(I))
       ELSE
          XLOW= 0.
       END IF
       X(I)=MAX(X(I),XLOW)
       X(I)=X(I)/X0(I)
    END DO

  END SUBROUTINE SUNPARAM_R8
!EOC
END MODULE DryDep_ToolBox_Mod
```
I am not sure why we only pass TERM(2).  But I was able to find an old code version (v8-01-01) and calling sunparam with term(2) is there as well.  
```F77
C $Id: biofit.f,v 1.1.1.1 2003/06/30 20:26:04 bmy Exp $
      REAL*8 FUNCTION BIOFIT(COEFF1,XLAI1,SUNCOS1,CFRAC1)

      IMPLICIT NONE
C===============================================
C Calculate the light correction
C===============================================
C* BIOFIT and SUNPARAM were written by Y.H. Wang.  See comment
C* in subroutine DEPVEL on what these subroutines do.
C*************************************************************
#     include "CMN_SIZE"
#     include "CMN_DEP"
      INTEGER KK
      PARAMETER (KK=4)
      REAL*8 COEFF1(NPOLY),TERM(KK),REALTERM(NPOLY)
      REAL*8 XLAI1,SUNCOS1,CFRAC1
      INTEGER K,K1,K2,K3

      TERM(1)=1.
      TERM(2)=XLAI1
      TERM(3)=SUNCOS1
      TERM(4)=CFRAC1
      CALL SUNPARAM(TERM(2))
      K=0
      DO K3=1,KK
        DO K2=K3,KK
          DO K1=K2,KK
            K=K+1
            REALTERM(K)=TERM(K1)*TERM(K2)*TERM(K3)
          END DO
        END DO
      END DO
      BIOFIT=0
      DO K=1,NPOLY
        BIOFIT=BIOFIT+COEFF1(K)*REALTERM(K)
      END DO
      IF (BIOFIT.LT.0.1) BIOFIT=0.1

      RETURN
      END
```
I would try to look at the Wang et al 1998 paper to see if you can decipher what is meant to be done.  If this is a bug, it's been a bug in the code for the last 25 years.

**Comment by dpfinch** [comment]
I've had a look and also played around with the code a bit (printing out steps of the equations).
It appears that SUNPARAM(TERM(2)) sends (and returns) the last three numbers in TERM whereas I would have thought it would only send the second. Again I would have thought it would be something like SUNPARAM(TERM(2:4)). 

The SUNPARAM function does loop through LAI, SUNCOS and CFRAC and from what I can tell does the correct thing. So not a bug but something I wasn't aware FORTRAN did (and I'm still not clear on why it behaves like that). 

If I were to write this more clearly would there be interest to update this in an upcoming version of the code? (Although no promises on when I might get round to it)

**Comment by yantosca** [comment]
Hi @dpfinch.  Ah, now I know what is going on.  This drydep code pre-dated the F90 standard.  In F77 you could use an statement like TERM(2), which looks like an assignment statement, but is actually pointing to the 1st element of an array that should be passed to a subroutine.  In essensce this is the F77 way you would pass TERM(2:4) to a subroutine that had a 3-element dummy argument.  This is because F77 lacked the ability to do array subscripting like we can in F90.

Yes, in the future we should probably make that explicit in the code.

**Comment by dpfinch** [comment]
Ah OK - that makes more sense! Thanks for the clarification

**Comment by yantosca** [comment]
Thanks.  I'll close out this issue for now.  Maybe in 13.1.0 we can clean that up.
