### ISSUE TITLE
[QUESTION] How to set up hier and cat# for GFAS and QFED in HEMCO_Diagn.rc

### ISSUE THREAD

**Issue by jinlx** [geoschem/geos-chem#515]
Hi there,

I found a disconnection in emissions of HEMCO_diagnostics.*.nc and raw data when I run simulations within GFAS and QFED, which is mentioned in #492 . I suspect it's caused by my settings in HEMCO_Diagn.rc. I only changed the extension to 0 to match GFAS and QFED extension number in the config file while keeping others in a default setting like what I show below. Do you think those are being called correctly for cat and hier #? How should I correct it?

```
# Name             Spec   ExtNr  Cat Hier Dim OutUnit       LongName
EmisACET_BioBurn   ACET   0    -1  -1   2   kg/m2/s  ACET_emission_flux_from_biomass_burning
```

**Comment by yantosca** [comment]
Hi @jinlx, thanks for writing. In HEMCO_Config.rc, we have  Cat=5 and Hier=3 for GFAS:
```
0 GFAS_CO    $ROOT/GFAS/v2018-09/$YYYY/GFAS_$YYYY$MM.nc cofire        2003-2020/1-12/1-31/0 C xyL=1:scal300 kg/m2/s CO   75     5 3
```
and Cat=5 and Hier=2 for QFED2:
```
0 QFED_ACET_PBL  $ROOT/QFED/v2018-07/$YYYY/$MM/qfed2.emis_acet.006.$YYYY$MM$DD.nc4 biomass 2000-2018/1-12/1-31/0 C xyL=1:PBL     kg/m2/s ACET 75/311        5 2
```
I think you should be able to do:
```
# Name             Spec   ExtNr  Cat Hier Dim OutUnit       LongName
EmisACET_BioBurn   ACET   0       5  -1   2   kg/m2/s  ACET_emission_flux_from_biomass_burning
```
If Hier=-1 then it picks up the hierarchy that is being used by the code.   If you have GFAS=false and QFED2=true then it will pick up the QFED2 emissions.  If GFAS=true then that outranks the QFED2 emissions because it has a higher hierarchy value, so then the diagnostic output will be GFAS.

**Comment by jinlx** [comment]
Thanks for answering my questions Bob! However changing cat# doesn't solve the high bias for offline BB inventories. If I am understanding it right, there would be no difference between Cat=-1&Hier=-1  vs Cat=5&Hier=3 when we only turn on GFAS.  I was wondering if you happen to have 1 month/year benchmark for simulations with either GFAS and QFED in the version after 12.7.0.

**Comment by yantosca** [comment]
Hi @jinlx.  We do not use the QFED2 or GFAS inventories for benchmarking, so we don't have any output from such simulations.

**Comment by yantosca** [comment]
I will close out this issue for now.  If you are still having problems then let me know and I can reopen this issue.
