### ISSUE TITLE
[BUG/ISSUE] hemco_standalone.x compilation problem

### ISSUE THREAD

**Issue by wreckdump** [geoschem/geos-chem#516]
# Report a GEOS-Chem bug or technical issue

### Steps to reproduce: the bug:

1.  make -j4 build (at the rundir generated by gcCopyRunDirs)

**Run commands**

1.  N/A

### Error messages

Attached compilation log below

### Your GEOS-Chem version and runtime environment:

 - GEOS-Chem version: 12.9.3
 - Compiler version: 8.3.1
 - netCDF version: 4.6.1 
 - netCDF-Fortran version (if applicable): __
 - Did you run on a computational cluster, on the AWS cloud: No 
   - If you ran on the AWS cloud, please specify the Amazon Machine Image (AMI) ID: __
 - Are you using GEOS-Chem "out of the box" (i.e. unmodified): Yes
   - If you have modified GEOS-Chem, please list what was changed: __

### Input and log files to attach

 - lastbuild: Could not build
 - input.geos: [input.geos.txt](https://github.com/geoschem/geos-chem/files/5534393/input.geos.txt)
 - HEMCO_Config.rc: [HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/5534394/HEMCO_Config.rc.txt)
 - GEOS-Chem "Classic" log file: __
 - HEMCO.log: __
 - slurm.out or any other error messages from your scheduler: __
 - Any other error messages: [compile.log.txt](https://github.com/geoschem/geos-chem/files/5534396/compile.log.txt)

### Additional context

I'm having trouble compiling the Unit Tester case with MERRA2 4x5 data. The error occurs when hemco_standalone.x is being compiled. According to the error messages it seems like netcdf library is not being linked during the compilation stage but, manual linking of netcdf did not solve the problem. So, I have no clue what the problem is. I've uploaded the GEOS-Chem compiler log that I am using, gcc and gfortran version, and netcdf version. I also uploaded .rc files and compilation log.

**Comment by yantosca** [comment]
Thanks for writing @wreckdump.  Have you set the proper Unix environment variables for GEOS-Chem?  See this wiki post for more information: 

http://wiki.geos-chem.org/Setting_Unix_environment_variables_for_GEOS-Chem

**Comment by wreckdump** [comment]
I think I did. Here is the environmental settings that I am using

```
export FC=gfortran
export F90=gfortran
export CC=gcc
export CXX=g++

#Compiler and netCDF binary/header/library location
export GC_INCLUDE=/opt/rh/devtoolset-8/root/usr/include
export GC_BIN=/opt/rh/devtoolset-8/root/usr/bin
export GC_LIB=/opt/rh/devtoolset-8/root/usr/lib
```

**Comment by yantosca** [comment]
Is there a nc-config or nf-config file in the $GC_BIN folder?  If not, then you may be using a version of netCDF that is too old.

**Comment by wreckdump** [comment]
Yes they are all in $GC_BIN. What version of netCDF and netCDF-Fortran does it require?

I have netCDF 4.6.1 and netCD-Fortran 4.4.3.

**Comment by yantosca** [comment]
Those versions of netCDF should be OK.  

Have a hunch the netCDF library installation should be in subfolders of /opt/rh/devtoolset-8/root/usr/lib.  If you are unsure, then ask someone at your institution where to find netCDF.

**Comment by wreckdump** [comment]
So, what is the root of the problem, in your opinion? It is netCDF library related problem, right? It seems that all the netCDF library files are located in the /opt/rh/devtoolset-8/root/usr/lib.

**Comment by wreckdump** [comment]
I found the problem. Like what you said. It was netCDF library problem. For some reason, netcdf.h and netcdf.inc files were not in the same directory.

**Comment by yantosca** [comment]
Thanks for letting us know!
