### ISSUE TITLE
[QUESTION] How to regrid new restart file with GAMAP2

### ISSUE THREAD

**Issue by yangxiajie** [geoschem/geos-chem#519]
In GEOS-Chem v12.0, I used _regridh_restart_nc.pro_ (_gamap2_) to regrid restart file form 2×2.5 to 0.25×0.3125. However, in v12.9.3, the _regridh_restart_nc.pro_ is not useful since the structure of new restart file has been changed. Are there any ways to regrid or generate a new restart file?
Thank you.

**Comment by msulprizio** [comment]
Please see our tips on regridding netCDF files at http://wiki.seas.harvard.edu/geos-chem/index.php/Working_with_netCDF_data_files#Regridding_netCDF_files.

**Comment by lizziel** [comment]
Starting in [GCPy](https://github.com/geoschem/gcpy) version 1.0.0 you will also be able to regrid GEOS-Chem restart files using python. I believe documentation on how to do this is in progress but should be available soon.

**Comment by yangxiajie** [comment]
Hi, @msulprizio  and @lizziel 
Thank you for your reply.
Now I understand how to regrid restart files with CDO and Python.
Thank you very much again for the help!
