### ISSUE TITLE
[QUESTION] What is the easiest way to get a full list of species names corresponding to a certain TagID?

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/geos-chem#520]
Hi GC Team,

It is quite convenient to use TagID (e.g. `?Hyg?` and `?DryDep?`) in HISTORY.rc to collect many diagnostics per time. Well I'd like to ask how can I can a full list of species names corresponding to a certain TagID with the least effort? This way I will be able to collect only those species of my interests avoiding requiring too much space.

I searched the `Get_TagInfo` but did not find anything like hash tables. Maybe I should check `species_database.yml`?

Thanks in advance!

**Comment by lizziel** [comment]
Hi @FeiYao-Edinburgh, for most of the tags the simplest way is to check the species database, looking for the field names that start with `Is_`. For example, all dry deposition species will include `Is_DryDep: true` in their species database entry. Other entries exist for species undergoing wet deposition, hygroscopic growth, photolysis, and advection. Aerosol species are also denoted with a logical.

Using this method does not work for all wildcards. For example, `KPP` includes all KPP species, but the species database only includes advected species. Let us know if you would like guidance for a specific wildcard that is not in the list above.

**Comment by FeiYao-Edinburgh** [comment]
That's brilliant. I will close the issue by myself.
