### ISSUE TITLE
[BUG/ISSUE] AODDust does not refer to 1st wavelength specified in Radiation Menu

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/geos-chem#521]
Hi GC Team,

I thought I might identify a bug. The [wiki](http://wiki.seas.harvard.edu/geos-chem/index.php/History_collections_for_aerosols) stated that AODDust refers to Mineral dust optical depth for 1st wavelength specified in Radiation Menu, but I found the code (dust_mod.F90) sums all wavelengths as below:
```
       !---------------------------------------------------
       ! Set dust optical depth diagnostic
       !---------------------------------------------------
       IF ( State_Diag%Archive_AODDust ) THEN
          !$OMP PARALLEL DO       &
          !$OMP DEFAULT( SHARED ) &
          !$OMP PRIVATE( I, J, L )
          DO L = 1, State_Grid%MaxChemLev
          DO J = 1, State_Grid%NY
          DO I = 1, State_Grid%NX
             State_Diag%AODDust(I,J,L) = SUM( tempOD(I,J,L,:,:) )
          ENDDO
          ENDDO
          ENDDO
          !$OMP END PARALLEL DO
       ENDIF
```
It might be helpful to change to `State_Diag%AODDust(I,J,L) = SUM( tempOD(I,J,L,:,1) )` or modify the wiki. But I suppose the former should be better since I do not think any significance of summing AOD of different wavelengths?

**Comment by yantosca** [comment]
Thanks for writing @FeiYao-Edinburgh.  I believe that for most simulations (except RRTMG), `tempOD(:,:,:,:,2)` and `tempOD(:,::,:,3)` are zero.  Unless you are running RRTMG the wavelengths 2 and 3 are ignored.

**Comment by FeiYao-Edinburgh** [comment]
Thanks for reply @yantosca . The [wiki](http://wiki.seas.harvard.edu/geos-chem/index.php/The_input.geos_file#RRTMG) said the wavelength specified in RRTMG Menu will always be used for the Fast-JX photolysis mechanism, regardless of whether the RRTMG radiative transfer model is used. So I wonder whether there is an impact but please forgive that I have not tested. That being said, I agree that it is always the case that only one wavelength is specified for simulations other than RRTMG.

**Comment by yantosca** [comment]
Thanks for noting that.  We have been preoccupied with the 13.0.0 release.  We will make sure to add a note about this as we update the wiki documentation.
