### ISSUE TITLE
[BUG/ISSUE] Segmentation fault occurred when turn off heterogeneous chemistry on different aerosols

### ISSUE THREAD

**Issue by yangxiajie** [geoschem/geos-chem#523]
In v12.9.3, I try to turn off heterogeneous chemistry in _aerosol_mod.F90_ with :

    TAREA(:,:,:,NDUST+1) = 0.d0 !Sulfate
    TAREA(:,:,:,NDUST+2) = 0.d0 !BC
    TAREA(:,:,:,NDUST+3) = 0.d0 !OC
    TAREA(:,:,:,NDUST+4) = 0.d0 !SS (accum)
    TAREA(:,:,:,NDUST+5) = 0.d0 !SS (coarse)
    TAREA(:,:,:,NDUST+NRHAER+1) = 0.d0 !SLA
    TAREA(:,:,:,NDUST+NRHAER+2) = 0.d0 !SPA

The model can run successfully at first. But when it nearly end, a **segmentation fault** occurred, which is:

       forrtl: severe (174): SIGSEGV, segmentation fault occurred
        Image              PC                Routine            Line        Source
        libifcoremt.so.5   00002B9F072282F6  for__signal_handl     Unknown  Unknown
        libpthread-2.17.s  00002B9F092915E0  Unknown               Unknown  Unknown
        libiomp5.so        00002B9F08D69940  Unknown               Unknown  Unknown
        libiomp5.so        00002B9F08D6C22C  Unknown               Unknown  Unknown
        libifcoremt.so.5   00002B9F07270C10  for_deallocate        Unknown  Unknown
        geos               0000000000B4502B  state_chm_mod_mp_        2291  state_chm_mod.F90
        geos               00000000004C4412  MAIN__                   2196  main.F90
        geos               0000000000403BDE  Unknown               Unknown  Unknown
        libc-2.17.so       00002B9F096C3C05  __libc_start_main     Unknown  Unknown
        geos               0000000000403AE9  Unknown               Unknown  Unknown

I do not know what is the reason for this fault.

**Comment by yantosca** [comment]
Thanks for writing @yangxiajie.  The traceback output shows that the error is at line 2291 at state_chm_mod.F90.  If you go to this line you see a deallocation statement:
https://github.com/geoschem/geos-chem/blob/b95926b8b53d27817090c36e1c9f939110ce03f1/Headers/state_chm_mod.F90#L2290-L2295
It could be that there is an out-of-bounds error in the `State_Chm%AeroRadi` array, or that you have deleted (or commented it out) from the code. 

I would recommend that you check your modifications against an "out-of-the-box" 12.9.3 version and then see if you can pinpoint the error.  You can also try compiling with the debugging flags (BOUNDS=y DEBUG=y FPEX=y).

**Comment by yangxiajie** [comment]
Hi @yantosca . Thank you for reply.
I chose another way to turn off heterogeneous chemistry by setting:
      TAREA(:,:,:,:) = 0.d0
After doing this, the fault above did not occur again.
However, by setting **TAREA(:,:,:,:) = 0.d0**, the O3 concentration in _GEOSChem.SpeciesConc_ become 0.  And **Mean OH =   0.000000000000000E+000  [1e5 molec/cm3]**
On the hand, I set the same **TAREA** in v12.0.0, the O3 concentration is not all 0, and its spatial distribution seems reasonable.
I don't know if this is a bug in v12.9.3. This has a great influence on the study of heterogeneous reactions.

**Comment by yantosca** [comment]
Thanks @yangxiajie.  If you turn off TAREA then I think that will turn off all hetchem, but also it might mess up the photolysis.  

I think your question is more of a scientific question than a programming one.  We are unable to advise how best to proceed.  I would recommend contacting the [GEOS-Chem Chemistry Working Group](http://wiki.seas.harvard.edu/geos-chem/index.php/Chemistry_Working_Group) for guidance.

**Comment by yantosca** [comment]
I am going to close out this issue for now.   Please feel free to submit a new issue if you are still having problems.
