### ISSUE TITLE
[QUESTION] Do you have more years of AEIC and/or AFCID emission inventory?

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/geos-chem#524]
Hi GC team,

When setting HEMCO_Config,rc, I realized that several global emission inventories only cover single or several years.

For a model simulation say from 2004-2013, to some extent, I guess it is reasonable to use GEIA_NH3, Seabird_NH3, LIANG_BROMOCARB, ORDONEZ_IODOCARB, and DECAYING_PLANTS as somewhat climatology values?

But for AEIC, AFCID, I am not sure if it can be thought as dermatological even to a little bit since it is mainly anthropogenic source? I have checked the [AFCID paper](https://iopscience.iop.org/article/10.1088/1748-9326/aa65a4) and thought it might be feasible to produce AFCID emissions for more years since the original [ECLIPSE dataset version V5a](https://iiasa.ac.at/web/home/research/researchPrograms/air/Global_emissions.html) covers 1990-2030?

So I'd like to ask here whether you have more years of AEIC and AFCID? If so could you share it? Otherwise to which extent do you think it is reasonable to use them as climatology for outside years?

Thanks in advance!

**Comment by yantosca** [comment]
Thanks for writing @FeiYao-Edinburgh.  The GCST relies on members of the GEOS-Chem community to provide us with emissons.  The years of emissions that are there are what we have at present.

You can send requests for new emissions datasets (or extra years of existing emissions datasets) to the Emissions Working Group, which is responsible for coordinating all GEOS-Chem emissions activity.

My sense is that we don't have any extra years of AEIC or AFCID.

**Comment by FeiYao-Edinburgh** [comment]
Thanks @yantosca I will join the Emission Working Group and communicate there. I close this issue myself.
