### ISSUE TITLE
[BUG/ISSUE]Tasks always stop automatically on the same date

### ISSUE THREAD

**Issue by ackerman1225** [geoschem/geos-chem#525]
## Describe the bug:
The GEOS-Chem version I'm using is 12.0.0. When I run the tropchem mechanism(4x5 MERRA-2, 19900101-20190101), the task always ending automatically on January 10, 2007. There are no such problems before 2007.

The error message is as follows:

### Error messages
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In Ncrd_3d_R4 #2:  NetCDF: HDF error
    131072         7

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Code stopped from DO_ERR_OUT (in module NcdfUtil/m_do_err_out.F90) 

This is an error that was encountered in one of the netCDF I/O modules,
which indicates an error in writing to or reading from a netCDF file!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
The complete geos.log file is here(used for testing, starting from December 1, 2006):
[geos.log](https://github.com/geoschem/geos-chem/files/5558301/geos.log)

It is certain that there is no problem with nc files and no other error information has been reported.

If you have any suggestion, it will be very helpful!

Thanks in advance.

**Comment by yantosca** [comment]
Thanks for writing @ackerman1225.  What is probably happening is that you have a corrupted met field file MERRA2.20070110.I3.4x5.nc4.  Can you check that the file size is similar to this directory listing:
```
 -rw-rwsr-x+ 1 msulprizio jacob_gcst 18999685 2016-09-03 00:00 MERRA2.20070110.I3.4x5.nc4
```
And also can you try to open the file with a netCDF view (like ncview, panoply, etc).  If you can't open the file, or if you find data that looks weird, then that means your file is corrupted.  Then you can try to re-download that file from the FTP server (or do a new dry-run simulation).

**Comment by ackerman1225** [comment]
It's really something wrong with the met file MERRA2.20070111.I3.4x5.nc4. However, when I redownloaded the file, I found that the file from FTP serve was corrupted. I try to use MERRA2.20070110.I3.4x5.nc4 instead of MERRA2.20070111.I3.4x5.nc4, problem has been solved. Thanks for your reply!

**Comment by yantosca** [comment]
Thanks @ackerman1225 for letting us know.  I'll close out this issue.
