### ISSUE TITLE
[FEATURE REQUEST] Allow HEMCO to read files at specified time intervals to improve file I/O

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#53]
When the met field read was migrated to HEMCO in 12.1.0, we noticed a slow down in run time. We may be able to improve run time by only reading fields at specified intervals and/or by leaving files open until all fields have been read.

**Comment by yantosca** [comment]
Melissa Sulprizio added this commit https://github.com/geoschem/geos-chem/commit/99bfbc3e906f80e9330a07101d187640ad9c305d to read met field files once per day (in HEMCO w/ GEOS-Chem "Classic" or HEMCO standalone only).  This should improve file I/O but more testing and profiling is needed.

Also Melissa added this commit: https://github.com/geoschem/geos-chem/commit/577b386cd617466dd1ec4431cce6a418d5be36b5 to read 3-hourly data for the entire day.

These will ship in GEOS-Chem 12.7.0.  Therefore, we can close out this issue.
