### ISSUE TITLE
[BUG/ISSUE] Errors in locating observation's model layer in planeflight_mod 

### ISSUE THREAD

**Issue by febfly** [geoschem/geos-chem#531]
Hi,
I notice there may be a bug in planeflight_mod.F90, when it tries to locate the model layer that a surface/tower observation belongs to. Below is the relevant code in planeflight_mod.F90. Note state_met%phis is treated as geopotential here and is divided by g0 to get surface altitude.
![image](https://user-images.githubusercontent.com/8473067/99766678-88516580-2b3c-11eb-9704-d442bf40cb24.png)

However, in flexgrid_read_mod.F90, division by g0 is already applied to state_met%phis after it is read from the merra-2 or geos-fp file. So the state_met%phis is already geopotential height in the unit of m. There should be another division by g0 in planeflight_mod.F90
![image](https://user-images.githubusercontent.com/8473067/99766399-f8132080-2b3b-11eb-8314-aa717f38c43d.png)

Yuzhong

**Comment by yantosca** [comment]
Viral Shah wrote:
> Most planeflight diagnostics for aircraft measurements use pressure coordinates and will not be affected by this bug. This bug seems to affect only measurements which use altitudes.

**Comment by febfly** [comment]
And this bug may not affect surface measurements as well (which often uses altitudes), as the code forces 1st layer for TYPE started with "S" (identifier for surface sites)
![image](https://user-images.githubusercontent.com/8473067/100067769-9f13f700-2e71-11eb-85a0-e84026c08c3a.png)

But I wonder if we had to force 1st layer because  the aforementioned bug caused errors in locating a proper model layer. If so, with the bug fixed, we may not need to force 1st layer, which is not a good feature I think. because there are mountain-top surface sites that are designed to sample free troposphere air, e.g., Mauna Loa. Their actual altitudes are considerably higher than coarse grid cell surface. 

Yuzhong

**Comment by yantosca** [comment]
This issue is now fixed in commit 7b1c6183f8294641a9fba853e10d763640a1d478.  This fix will be applied to the 13.0.0 final release.

**Comment by yantosca** [comment]
The main branch of the geoschem/GCClassic superproject repository now points to this update.  It will ship with the 13.0.0-release-candidate.
