### ISSUE TITLE
[DISCUSSION] Aircraft emissions are for 2005. How to deal with these becoming increasingly outdated?

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#534]
This question was raised by @eamarais at the GEOS-Chem Steering Committee meeting on 18 Nov 2020. 

NOTE: An updated inventory does exist, but has licensing issues.  But scaling factors to the existing AEIC 2005 inventory should be implementable. @sdeastham is working on that.

Please add your thoughts in the comment boxes below.

**Comment by sdeastham** [comment]
We have a 2015 inventory with AEIC which can be made available for projects which have a specific need. However, it is subject to some strict licensing (specifically, we have to negotiate every use of the gridded emissions data with the EU agency which supplied some of the aircraft performance data). Although I'm hopeful we will eventually be able to release updated emissions inventories, we are indeed working on a stopgap solution now.
