### ISSUE TITLE
Compilation guide needed

### ISSUE THREAD

**Issue by chazanov** [geoschem/geos-chem#54]
Dear developers,

I'm trying to build the current 12.5.0 dev master branch with gcc-fortran 9.1.0 (@ArchLinux). Common scientific libraries like netcdf (including `nc-config`) are present:

`FC=gfortran make`

miserably fails:

```
make[4]: Entering directory './geos-chem/NcdfUtil'
/bin/bash: /nc-config: No such file or directory
grep: /netcdf.inc: No such file or directory
gfortran -cpp -w -std=legacy -fautomatic -fno-align-commons -fconvert=big-endian -fno-range-check -O3 -funroll-loops -fopenmp -mcmodel=medium -fbacktrace -g -DLINUX_GFORTRAN -DBPCH_TIMESER -DBPCH_TPBC -DUSE_REAL8 -J../mod -I -c -ffree-form -ffree-line-length-none charpak_mod.F90
f951: Warning: Nonexistent include directory '-c' [-Wmissing-include-dirs]
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/../../../../lib/Scrt1.o: in function `_start':
(.text+0x24): undefined reference to `main'
collect2: error: ld returned 1 exit status
make[4]: *** [../Makefile_header.mk:1008: charpak_mod.o] Error 1
```

Probably I've not found the install guide with some obvious advice. Could you please help me further?

**Comment by yantosca** [comment]
Thanks for writing.  It appears that you haven't set some environment variables that tell GEOS-Chem where it can find the netCDF libraries.  See:

http://wiki.geos-chem.org/Setting_Unix_environment_variables_for_GEOS-Chem

If you haven't already, I would recommend looking at our GEOS-Chem manual pages, as they go into great detail about how to configure simulations.  See:

http://wiki.geos-chem.org/Getting_Started_with_GEOS-Chem

**Comment by chazanov** [comment]
It works now; thank you very much for your help. Now moving over to https://github.com/geoschem/gcpy !
