### ISSUE TITLE
[FEATURE REQUEST] Vertically resolve anthropogenic emissions (Barron Henderson, USEPA)

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#545]
This update from @barronh is almost ready for inclusion into GEOS-Chem.

**Comment by msulprizio** [comment]
This is being tracked on the HEMCO repository. See https://github.com/geoschem/HEMCO/issues/46.

**Comment by msulprizio** [comment]
I am reopening this issue to ensure it is brought into GEOS-Chem 13.1.0.

**Comment by msulprizio** [comment]
This is now in the `dev` branch and will be included in GEOS-Chem 13.1.0. See https://github.com/geoschem/HEMCO/issues/46 for details.
