### ISSUE TITLE
[FEATURE REQUEST] Select KPP chemical mechanism at runtime instead of during compilation

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#55]
Sebastian Eastham suggested we implement the capability to select the chemical mechanism at run time. At present, only one chemical mechanism is compiled (via the CHEM compiler flag) and available at run time. However, selecting mechanisms at run time would avoid the need to recompile and would also simplify unit testing.

**Comment by LiamBindle** [comment]
Hi Melissa,

Yeah, I think this should be relatively stratightforward. Right now I'm just thinking of making an abstract base class for KPP, and then instantiating the proper concrete class at runtime based on `input.geos`. 

If anyone has any thoughts/concerns/ideas please let me know! I'm going to be working on this in my downtime so I'm not too sure of a timeline for it yet.

**Comment by msulprizio** [comment]
This will no longer be needed in GEOS-Chem 13.0.0. The tropchem and complexSOA_SVPOA simulations will be retired, and only the standard mechanism will be supported. To maintain a tropchem simulation, users will be able to select a chemistry grid consisting of only the troposphere or one including both the troposphere and stratosphere. See https://github.com/geoschem/geos-chem/issues/332 for more details and status updates.
