### ISSUE TITLE
[FEATURE REQUEST] MEIC regional emissions for China

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#550]
This update by Lu Shen (Harvard) & Gongda Lu (U. Birmingham) was identified by @eamarais as being almost ready for inclusion into GEOS-Chem. 

We will use this feature request issue to track further progress.

**Comment by lizziel** [comment]
Are there any updates on this? Can it be closed?

**Comment by msulprizio** [comment]
@zsx-GitHub has implemented MEIC emissions in her code. We have not added it to the standard code yet. Shixian, do you know if we have permission to share MEIC and implement them in a future version of GEOS-Chem? If yes, could you submit a pull request with these updates?

**Comment by yantosca** [comment]
I will close out this issue.  I believe the MEIC emissions are available on a "ask-permission" basis but have not been something that we have been able to include in the standard GEOS-Chem data directories.

**Comment by PowderL** [comment]
@zsx-GitHub Hi, I am new to GEOS-Chem and am currently working on configuring the MEIC emissions inventory for my simulation. Could you kindly share your ​​HEMCO_config​​ code or any templates you’ve used for integrating MEIC into GEOS-Chem?
If possible, I would greatly appreciate additional guidance on best practices for this setup, as I want to ensure my configuration aligns with established workflows. Please let me know if you need further details about my project or setup.
Thank you for your time and support.
Best regards
