### ISSUE TITLE
[QUESTION] Has the gravitational velocity been included in the DryDepVel of aerosols?

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/geos-chem#554]
Hi GC Team,

I have recently read several subroutines in drydep_mod.F90 and I believe DryDepVel diagnostics are calculated and assigned in DEPVEL and DO_DRYDEP, respectively, using DVEL as the link. In the DEPVEL, `DVEL(I,J,K) = VD(K)`, where `VD(K) = VK(K) +.001D0* DBLE( IUSE(I,J,LDT) )/C1X(K)`, where `C1X(K) = RA + RB + RSURFC(K,LDT)`. For aerosols, RB=0, leaving only RA (aerodynamic resistance) and RSURF (surface resistance). In this regard, can I understand that at least for aerosols, the code ignores the gravitational velocity that is indicated as `Vg` in equation (1) in [Zhang et al. 2001](https://www.sciencedirect.com/science/article/abs/pii/S1352231000003265)?

BTW, around VD assignment, there are
```
          DO 400 K = 1,NUMDEP
             IF (.NOT.LDEP(K)) GOTO 400
             VK(K) = VD(K)
             VD(K) = VK(K) +.001D0* DBLE( IUSE(I,J,LDT) )/C1X(K)
400       CONTINUE
```
, which I think can be simplified? I am a bit confused with the use of VK(K) that seems redundant?
```
          DO 400 K = 1,NUMDEP
             IF (.NOT.LDEP(K)) GOTO 400
             ! VK(K) = VD(K)
             VD(K) = VD(K) +.001D0* DBLE( IUSE(I,J,LDT) )/C1X(K)
400       CONTINUE
```

Thanks!

**Comment by yantosca** [comment]
Thanks for writing @FeiYao-Edinburgh.  I am tagging @jgeddes85, @ltmurray, and @amospktai, who are co-chairs for the Chemistry-Ecosystem-Climate Working Group.  They are probably better able to answer your question than the GCST can.

Also, the current drydep code is very old and probably needs some "pruning".  That instance of VK(K) = VD(K) might be an instance of a "useless" statement.  But we didnt' want to possibly break something so we've left it in there for now.

**Comment by ltmurray** [comment]
The Emissions and Deposition Working Group might be better suited to answer this question? I only know @eamarais 's handle.

**Comment by amospktai** [comment]
Did we not receive a similar request to clarify some aspects of dry deposition before? I remember back then we referred them to Anthony Wong (BU) and Sam Silva (MIT/NCAR), who have extensively looked into the dry deposition module in GEOS-Chem, and attempted to revamp some aspects of it.
--
Amos P. K. Tai, Ph.D., Associate Professor
Earth System Science Programme, Faculty of Science
The Chinese University of Hong Kong
www.cuhk.edu.hk/sci/essc/tgabi/<http://www.cuhk.edu.hk/sci/essc/tgabi/> | amostai@cuhk.edu.hk<mailto:amostai@cuhk.edu.hk> | +852 3943 9687<tel:+852%203943%209687>

On 26 Nov 2020, at 5:30 AM, Lee Murray <notifications@github.com> wrote:

﻿

The Emissions and Deposition Working Group might be better suited to answer this question? I only know @eamarais<https://github.com/eamarais> 's handle.

**Comment by yantosca** [comment]
I am going to close out this issue as there has not been recent activity.
