### ISSUE TITLE
Naphthalene concentrations not passed to planeflight menu and NAP emissions aren't responding as expected [BUG/ISSUE]

### ISSUE THREAD

**Issue by JFBrewer** [geoschem/geos-chem#556]
Hi GCST,

Happy Week Of Thanksgiving! I'm just writing in to let you know that the NAP species concentrations seem not to be able to talk to the planeflight diagnostics - when I attempt to output NAP using the planeflight diagnostics, the number densities are all zeros. This is true regardless of how I represent the emissions of Naphthalene. This is true regardless of how I represent the emissions of Naphthalene (i.e., whether I turn on EDGAR or CEDS or if I add the EDGAR NAP emission to CEDS). I do not think the actual concentrations of NAP are zero, however, for reasons that will become clear shortly.

I've encountered a second issue with naphthalene which may be related. When I run the complex SOA scheme using CEDS emissions as the base inventory, there should, I think, be no emission of Naphthalene present as the only reference to NAP emissions in HEMCO_Config.rc is coming out of EDGAR. I have tried two methods to take care of this. 

1. I copied the line referencing the EDGAR Naphthalene emissions (from benzene) into the CEDS emissions block
2. I instead added new lines to HEMCO_Config.rc linking the emissions currently going to BENZ (CEDS_BENZ_AGR, etc.) to NAP and changing the NAP scale factors (80, 81, and 82) to apply to either EDGARv32 or CEDS.

Crucially I forgot to apply this latter step (changing the NAP scale factors to take EDGARv43.or.CEDS) to the emission in case 1. This matters because the result in both scenarios was identical, and ASOA formation decreased relative to the base case in which I changed nothing about the emissions of NAP.

Is it possible that somehow NAP emissions are not talking properly to HEMCO and that they are being instead handled elsewhere? In that case I would be overriding the NAP emissions with my attempted changes but because I'm doing something wrong those emissions are going to zero? This is the only way I can reconcile my two very different changes having identical SOA-decreasing effects.

Thanks,
Jared

**Comment by msulprizio** [comment]
Hi @JFBrewer. Can you clarify if you're using the complexSOA simulation or the complexSOA_SVPOA? Only the complexSOA_SVPOA simulation includes NAP as an advected species. This can be verified by checking your settings in the advected species and aerosol menus of input.geos. If you can confirm that NAP is there, can you try the following. In HEMCO_Config.rc, set Verbose and Warnings to 3. Rerun a short simulation (~1 hour) and copy the input and output files here (input.geos, HEMCO_Config.rc, GEOS-Chem and HEMCO log files, etc.).

**Comment by msulprizio** [comment]
@JFBrewer were you able to resolve this issue or are you still experiencing problems?

**Comment by JFBrewer** [comment]
Hi Melissa,

I ended up going in a different direction based on some other factors. I
have not solved this issue but it is not crucial at this precise moment

**Comment by msulprizio** [comment]
OK. Thanks for letting us know. I will close this issue.
