### ISSUE TITLE
[FEATURE REQUEST] Implement H2 chemistry

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#559]
@cdholmes wrote:

>GEOS-Chem currently assumes a fixed mole fraction for H2, like O2 and N2. This development makes H2 a transported species, with fixed surface concentration, and completes the H2 chemistry in the KPP chemical mechanism. With the update, we will resolve the full oxidation series of CH4 to H2O and CO2. A paper is forthcoming, focusing on the stratosphere, but the reactions are contained in the JPL compendium. I think we have implemented other kinetics updates without a publication, so I think we could do the same here.

**Comment by lizziel** [comment]
Is there an update on this feature request?

**Comment by cdholmes** [comment]
I can provide the KPP update whenever the Support Team wants it.

**Comment by msulprizio** [comment]
This feature request is now superseded by https://github.com/geoschem/geos-chem/issues/1867.
