### ISSUE TITLE
[FEATURE REQUEST] C2H4 and C2H2 chemistry

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#560]
@kelvinhb wrote:

>Simplified ethene and ethyne chemistry is incorporated into GEOS-Chem, including its reactions with the hydroxyl radical and ozone, based on IUPAC recommendations. The impacts of this chemistry are analyzed in Kwon et al. (below) with particular emphasis on Korea and the Seoul Metropolitan Area (SMA). Ethene has a relatively short lifetime of ~1.5 days and is emitted primarily by industrial sources, with additional biogenic and pyrogenic emissions. Ethene accounts for the second-largest amount of AVOC emissions in South Korea and was ranked fourth in contribution to OH reactivity in SMA during the KORUS-AQ campaign. Adding ethene chemistry to the model increases the HCHO mixing ratio over Korea, bringing it into closer alignment with observations, especially over the Daesan and Busan-Changwon-Geoje areas, for which the mixing ratio increases by 0.25 ppbv.
>
>Kwon, H.-A., Park, R. J., Oak, Y., Nowlan, C. R., Janz, S. J., Kowalewski, M. G., Fried, A., Walega, J.,  Bates, K. H., Choi, J., Blake, D. R., Wisthaler, A, and Woo, J.-H.. Top-down estimates of anthropogenic VOC emissions in South Korea using formaldehyde vertical measurements from aircraft during the KORUS-AQ campaign. Elem. Sci. Anth. In review.

**Comment by msulprizio** [comment]
@michael-s-long has implemented these updates from @kelvinhb and says they should be easy to implement. We will prioritize this in [GEOS-Chem 13.3.0](https://github.com/geoschem/geos-chem/milestone/19). A few items to consider when implementing these updates:

* C2H2 and C2H4 are currently not advected species in GEOS-Chem, but should be added as such in input.geos
* C2H2 needs to be added to species_database.yml and C2H4 in that file should be updated if any properties are missing
* HEMCO_Config.rc may need to be updated for C2H2 and C2H4 emissions. Some notes:
  * The CEDS global anthropogenic emissions inventory already includes these species.
  * The GFED extension should be updated to include scaling for these species.
  * The MEGAN extension already includes C2H4, but we should make sure these are properly updated and saved out via the HEMCO diagnostics.
 
Daniel Jacob says @kelvinhb may be able to help provide us with the updates necessary to include these emissions.

**Comment by msulprizio** [comment]
See PR https://github.com/geoschem/geos-chem/pull/813 submitted by @michael-s-long

**Comment by yantosca** [comment]
Closing this PR since it is now resolved by #904.
