### ISSUE TITLE
[QUESTION]How to add a new sea flux emission likeDMS

### ISSUE THREAD

**Issue by yutao-chen** [geoschem/geos-chem#563]
How to add a new sea flux emission like DMS in HEMCO_Config.rc? And how to calculate the DMS emission flux？

**Comment by yantosca** [comment]
Thanks for writing @yutao-chen.  I think the best thing to do would be to look at the HEMCO extension code (hcox_seaflux_mod.F90), and then to try to copy what has been done for DMS.  You might need a new data source.  You might also be able to scale from DMS depending on your application.
