### ISSUE TITLE
[BUG/ISSUE] Read regional nested ND51 output

### ISSUE THREAD

**Issue by Rainbow1994** [geoschem/geos-chem#564]
# Report a GEOS-Chem bug or technical issue

## Describe the bug:
I turned on ND51 switch in input.geos and set up an Asian nested methane run.  When I read ND51 output bpch files using xbpch python module, the length of 'longitude' doesn't match the size of  'J-AVG-$_CH4' field. I wonder if something wrong I set up in input.geos.

### Error messages

```
ValueError: conflicting sizes for dimension 'lon': length 145 on 'IJ-AVG-$_CH4' and length 576 on 'lon'
```

### Your GEOS-Chem version and runtime environment:

 - GEOS-Chem version: 12.5.0
 - Compiler version: ifort 
 - netCDF version: gcc-4.8.5
 - netCDF-Fortran version (if applicable):  v 4.4.4
 - Did you run on a computational cluster, on the AWS cloud: No
   - If you ran on the AWS cloud, please specify the Amazon Machine Image (AMI) ID: __
 - Are you using GEOS-Chem "out of the box" (i.e. unmodified):  No
   - If you have modified GEOS-Chem, please list what was changed: __

### Input and log files to attach

 - lastbuild: __
 - input.geos: 
[input.geos.txt](https://github.com/geoschem/geos-chem/files/5652045/input.geos.txt)

 - ND51 output:
[ts_satellite.ST000.EN0001-EN0002.20150102.bpch.txt](https://github.com/geoschem/geos-chem/files/5652054/ts_satellite.ST000.EN0001-EN0002.20150102.bpch.txt)

 - Diaginfo.dat:
[diaginfo_sp.dat.txt](https://github.com/geoschem/geos-chem/files/5652047/diaginfo_sp.dat.txt)

 - Tracerinfo.dat: 
[tracerinfo_sp.dat.txt](https://github.com/geoschem/geos-chem/files/5652048/tracerinfo_sp.dat.txt)

 - Any other error messages: __

**Comment by yantosca** [comment]
Thanks for writing @Rainbow1994. I think the issue is this... the ND51 menu is set up to produce global 4x5 output:
```
%%% ND50 MENU %%%       :
Turn on ND50 diagnostic : F
24-hr avg timeser. file : /data/shzhu/rerun_ch4_as//ts_24h_avg.ST000.EN0001-EN0002.YYYYMMDD.bpch
Output as HDF5?         : F
Tracers to include      : 82 83 84 85 86 87
IMIN, IMAX of region    :   1  72
JMIN, JMAX of region    :   1  46
LMIN, LMAX of region    :   1   1
```
but your simulation is a nested-grid run:
```
%%% GRID MENU %%%       :
Grid resolution         : 0.5x0.625
Longitude min/max       :  60.0 150.0
Latitude  min/max       : -11.0  55.0
 Half-sized polar boxes?: F
Number of levels        : 47
Nested grid simulation? : T
 Buffer zone (N S E W ) :  3  3  3  3
```
and I believe this grid has [145 longitude points x 133 latitude points] (http://wiki.geos-chem.org/GEOS-Chem_horizontal_grids#0.5_x_0.625_AS_nested_grid).  Therefore, you should use these settings in the ND51 diagnostic:
```
IMIN, IMAX of region    :   1 145
JMIN, JMAX of region    :   1  133
LMIN, LMAX of region    :   1   1
```

**Comment by Rainbow1994** [comment]
I've set IMIN, IMAX of region in ND51 section as what you said. Do you mean that the min and max parameters of the region in other sections should be the same as those in the ND51 section, though I turned off the section switches?  
![image](https://user-images.githubusercontent.com/29177864/101366972-8528da00-389d-11eb-8eee-88011ac6d471.png)

**Comment by yantosca** [comment]
>I've set IMIN, IMAX of region in ND51 section as what you said. Do you mean that the min and max parameters of the region in other sections should be the same as those in the ND51 section, though I turned off the section switches?

Only if you want output from those other timeseries diagnostics.

**Comment by Rainbow1994** [comment]
Sorry, maybe I didn't make it clear. I ran geos.mp successfully, but I cannot read ND51 output using xbpch module. The error message shows:
ValueError: conflicting sizes for dimension 'lon': length 145 on 'IJ-AVG-$_CH4' and length 576 on 'lon'
![image](https://user-images.githubusercontent.com/29177864/101933022-8296ef00-3bd3-11eb-972b-25c781ace1c6.png)
I wonder if longitude and latitude coordinate variables in Diag51_mod.f are unmatched with ND51 output variables.

**Comment by yantosca** [comment]
Question: what version of xarray are you using?  You might have to go back to xarray so that xbpch will work.  I think updates to the xarray package broke backwards compatibility with xbpch.

Also, if you have solved the problem, please let us know and we can close out the issue.

**Comment by yantosca** [comment]
I am going to close out this issue as there has not been recent activity.  Please feel free to open a new issue if you are still having problems.
