### ISSUE TITLE
[BUG/ISSUE] Error in the tagged O3 simulation w/ extended species list

### ISSUE THREAD

**Issue by sharonshen-wq** [geoschem/geos-chem#569]
HI, I just began to run a tagged O3 (extended) simulation , while there's some question at the begaining, attached is my simulation stuff.

[123.zip](https://github.com/geoschem/geos-chem/files/5680905/123.zip)

**Comment by yantosca** [comment]
Thanks for writing @sharonshen-wq,  There seems to be an inconsistency between the species names in input.geos and the species names in the ./species_database.yml file in your run directory:

In input.geos:
```
%%% ADVECTED SPECIES MENU %%%:
Species name            : O3
Species name            : O3Strat
Species name            : O3Ut
Species name            : O3Mt
Species name            : O3Row
Species name            : O3PcBl
Species name            : O3NaBl
Species name            : O3AtBl
Species name            : O3EuBl
Species name            : O3AfBl
Species name            : O3AsBl
Species name            : O3Init
Species name            : O3USA
```
in species_database.yml:
https://github.com/geoschem/geos-chem/blob/0d390164f3441816defd05519f28dfde574a1cfa/run/shared/species_database.yml#L2868-L2920

As you can see, the tagged O3 species names in the species_database.yml file are all upper case (k.e. O3UT, O3AFBL, etc.).  

To fix the issue, you can try renaming the species names in the species_database.yml file so that they use the same capitalization as in the input.geos file... then your simulation should work.

**Comment by sharonshen-wq** [comment]
thanks, this is the problem, now I successively run this simulation, but there was an error occurred "GEOS-Chem ERROR: BrNO3 is undefined, but is needed for heterogeneous chemistry!-> at Init_HetInfo (in module Headers/state_chm_mod.F90)" , which did not affect the simulation yet. So what's the cause?

**Comment by yantosca** [comment]
Are you using a full-chemistry run directory?  If you are in a tagged O3 run directory and if your input.geos file is set up properly, then the code should not try to initiate heterogeneous chemistry.  Please double check your input files.

On another note, in GEOS-Chem 13.0.0 (final release), we will use all tagged CO species by default.  This was done in commit 7e9bfc36e4c1e939bc45398a8332fcaab386e8dc.

**Comment by sharonshen-wq** [comment]
yes, I run in the tagged O3 directory, the input.geos file is set up according to the sample file which I have uploaded before, and the GC.log indicated that there were no accumulation during the simulation, and the results in the output file were mostly -Infinity, the new attached is my GC.log
[GC.log](https://github.com/geoschem/geos-chem/files/5684920/GC.log)

**Comment by sharonshen-wq** [comment]
also to be mentioned , the units of O3 PROD_LOSS rate in the output file during the standard simulation were molec cm-3 s-1, while in the HEMCO.log file, it printed as "HEMCO WARNING: Data converted from kg/m3/s to kg/m3: O3_PROD: molec cm-3 s-1
" as shown in the attached figure, so what's the causes for the failed accumulation?
![HEMCO](https://user-images.githubusercontent.com/75856423/102098414-32977280-3df5-11eb-9135-09343a9e63cd.png)

,

**Comment by yantosca** [comment]
Also see issue https://github.com/geoschem/geos-chem/issues/573

**Comment by yantosca** [comment]
The tagged O3 species names are now consistent in the `species_database.yml` and `input.geos` files that will ship with GEOS-Chem 13.0.0.  Therefore I will close out this issue for now.  See issue https://github.com/geoschem/geos-chem/issues/573 for the units question.
