### ISSUE TITLE
[QUESTION] The dummy species replace the POx、 LOx species when rebuild mechanism through KPP.

### ISSUE THREAD

**Issue by yutao-chen** [geoschem/geos-chem#576]
I use GEOS-Chemv11-02 and rebuild the mechanism through KPP-2.2.3_01  When I run the model , it shows the error that could nor locate  KPP prod/loss species ：POx.  And I found that many dummy species  took the place of  POx LOx .etc in KPP/Custom/gckpp_Monitor.F90.
（I do the same test in GEOS-Chem 12.9.3 and it shows the same error.）   
I read the flexchem wiki page and it said that this problem has been solved after updating the KPP since GEOS-Chemv11-02a ,  while I can't find the new version of KPP.

**Comment by yantosca** [comment]
Thanks for writing @yutao-chen.  You should be on the GC_updates branch of KPP, not the main branch.  The latest version is KPP 2.2.5_gc (just updated on 04 Jan 2021).

The main branch of KPP does not have the GEOS-Chem specific code included.

**Comment by yantosca** [comment]
Are you still experiencing problems @yutao-chen?

**Comment by yantosca** [comment]
I am closing out this issue for now.  Feel free to submit another issue if you are still having problems.
