### ISSUE TITLE
[QUESTION] netCDF Start+count exceeds dimension bound error

### ISSUE THREAD

**Issue by sharonshen-wq** [geoschem/geos-chem#577]
Hi, everyone, when I run a standard simulation in version 12.6.3, I encountered a problem that stop the run.
![12 6 3](https://user-images.githubusercontent.com/75856423/102719065-c23b9600-42b9-11eb-9a28-fbd31ffe9a14.png), it the restartfile created by the model not available? How can I solve this problem, thanks.

**Comment by yantosca** [comment]
Thanks for writing @sharonshen-wq,  Another user posted a similar issue, see: https://github.com/geoschem/geos-chem/issues/439.

Can you send us the log files from your run?  See this checklist on our [Submitting GEOS-Chem support requests](http://wiki.seas.harvard.edu/geos-chem/index.php/Submitting_GEOS-Chem_support_requests#How_can_I_make_a_support_request.3F) wiki page.

**Comment by sharonshen-wq** [comment]
Sorry, here's the log files included
[GC1.log](https://github.com/geoschem/geos-chem/files/5765574/GC1.log)
[HEMCO.log](https://github.com/geoschem/geos-chem/files/5765575/HEMCO.log)

[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/5765582/HEMCO_Config.rc.txt)
[input.geos.txt](https://github.com/geoschem/geos-chem/files/5765583/input.geos.txt)

**Comment by yantosca** [comment]
Thanks for the logs.  I didn't see anything out of the normal.  Can you also do

```
ncdump --cts GEOSChem.Restart.20120101_0000z.nc4
```
and then attach the output here? There may be something wrong with the dimensions of the restart file (or you may be using a nested restart file with a global GEOS-Chem simulation).

**Comment by sharonshen-wq** [comment]
it seems that the restartfile generated initially by the model had some problems. I replaced this restartfile by anonther one that generated by former simulation, and it's fixed. thanks for your help!

**Comment by yantosca** [comment]
Thanks @sharonshen-wq!  I'll close out this issue.   Happy New Year!
