### ISSUE TITLE
[BUG/ISSUE]Error when running default aerosol configuration with GEOS-Chem v12.9.3

### ISSUE THREAD

**Issue by chuzhaohan** [geoschem/geos-chem#580]
## Describe the bug
When using GEOS-Chem v12.9.3 with gfortran to run default aerosol configuration, I always found a HEMCO ERROR saying "GLOBAL_HCl not found in HEMCO data list!", no matter what time I chose. I used dryrun option to download the files I needed from Compute Canada, and slurm dispatching system with a job script. 

**Compilation commands**
make -j4 build

**Run commands**
./geos > GC.log

### Error messages
```
HEMCO (VOLCANO): Opening /GEOS-Chem/Data/ExtData/HEMCO/VOLCANO/v2019-08/2016/01/so2_volcanic_emissions_Carns.20160101.rc
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
HEMCO ERROR: Cannot find in EmisList: GLOBAL_HCl
ERROR LOCATION: HCO_EvalFld_3d (HCO_calc_mod.F90)
```

### Your GEOS-Chem version and runtime environment:
 - GEOS-Chem version: 12.9.3
 - Compiler version: gfortran 7.2.0
 - netCDF version: 4.7.3
 - netCDF-Fortran version (if applicable): 4.5.2
 - Did you run on a computational cluster, on the AWS cloud: on a computational cluster
 - Are you using GEOS-Chem "out of the box" (i.e. unmodified): Yes

### Input and log files to attach
 - lastbuild: [compile.log](https://github.com/geoschem/geos-chem/files/5750071/compile.log)
 - input.geos: [input.geos.txt](https://github.com/geoschem/geos-chem/files/5750073/input.geos.txt)
 - HEMCO_Config.rc: [HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/5750074/HEMCO_Config.txt)
 - GEOS-Chem "Classic" log file: [GC.log](https://github.com/geoschem/geos-chem/files/5750075/GC.log)
 - HEMCO.log: [HEMCO.log](https://github.com/geoschem/geos-chem/files/5750076/HEMCO.log)

**Comment by chuzhaohan** [comment]
I noticed the same issue from [https://github.com/geoschem/geos-chem/issues/354], but when I used version 13.0.0, I still found the same problem.

**Comment by msulprizio** [comment]
Yes, this is a known issue as reported in https://github.com/geoschem/geos-chem/issues/354. We are currently running the 10-year benchmark simulation for 13.0.0 and will make the updated oxidant fields needed to restore the aerosol-only simulation available from that simulation prior to officially releasing 13.0.0 later this month. Please follow that issue for updates.
