### ISSUE TITLE
[BUG/ISSUE]  error: NC_FLIBS@: No such file or directory

### ISSUE THREAD

**Issue by Aydr199406** [geoschem/geos-chem#583]
Hello,when i compile the GEOS-Chem source code, there are an error "gfortran: error: NC_FLIBS@: No such file or directory." Can you help me to deal with this problem. Thanks!

**Comment by yantosca** [comment]
Thanks for writing.  Could you give us more information about your problem?  [Please see this checklist]( http://wiki.seas.harvard.edu/geos-chem/index.php/Submitting_GEOS-Chem_support_requests#How_can_I_make_a_support_request.3F) for a list of items to include.

**Comment by yantosca** [comment]
Also please see this issue: https://github.com/geoschem/geos-chem/issues/575

**Comment by yantosca** [comment]
Please also make sure that your environment variables are defined properly.  See this wiki page: http://wiki.geos-chem.org/Specifying_compilers_for_GEOS-Chem

**Comment by Aydr199406** [comment]
Thank you very much. The GEOS-Chem version i used is 12.7.0. I will check the environment vatiables again!
