### ISSUE TITLE
[FEATURE REQUEST] Remove negative mass adjustment and exit with error if negative concs are found

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#584]
This feature requests builds upon issue #468. 

## Description

@aschuh wrote:

>I've been struggling w/ some very small mass conservation issues w/ long CO2 simulations (~19-ish years) for some time.  Recently I was doing some transport perturbations where I was shutting off certain transport mechanisms, PBL mixing and convection.  This exacerbated the problem, especially the pbl mixing getting turned off. Christoph Keller help 
point me to a piece of code where negative concs get truncated [(see link here)](https://github.com/geoschem/geos-chem/issues/468).  For those familiar w/ CO2 simulations, I was getting a 0.22ppm offset during 18 year CO2 simulations, not a big mass error but enough that I had to subtract it off somehow. Turning off pbl mixing made it noticeably worse.  CO2 simulations often include bio surface fluxes, which can be positive or negative.  I've not fully verified this, but I believe when the fluxes are strongly negative and get trapped near the ground, occasionally you have your concentrations turning negative and getting truncated to zero, always leading to positive mass error. The errors I've seen in the various runs leads me to believe that while occurring extremely infrequently w/ regular CO2 simulations, I'm guessing it DOES happen w/ regular CO2 background levels. Doubling or tripling bgd levels seems to be a first order bandaid fix and allowed my "no pbl mixing" sims to maintain reasonable mass conservation.  I typically only run a handful of carbon gas sims but I just wanted to alert people to this particular piece of code which I believe might be responsible for small nagging tracer mass errors over time, depending upon your particular modeling setup.    There is really no warning message if you truncate either, as far as I can tell.  Not sure if there is some way that this kind of error could be mitigated or not, or an warning message printed at a minimum, but I thought it was worth bringing up.

Daniel Jacob wrote:

>Thank you for pointing out this problem! That negative mass adjustment to zero should not be done in the model ecause mass conservation is sacrosanct. At the same time, (1) we cannot allow concentrations to go negative, (2) there is no protection from negative concentrations when surface fluxes are negative and zeroth order as is the case for CO2 (which really IS the theoretical problem - at some point if CO2 gets too low the surface fluxes should stop being zeroth-order). 
>
>I think that we should remove this mass adjustment from the code as a bug fix and instead abort the run with an error message if the concentration goes negative. The user can then opt to fix this by increasing the background concentration or by shortening the time step. 

## Solution

We will remove this line of code in `GeosCore/mixing_mod.F90`

```F90
 ! Prevent negative concentrations. (ckeller, 3/29/16)
         State_Chm%Species(I,J,L,N) = MAX(State_Chm%Species(I,J,L,N),0.0_fp)
```
And replace it with a test for negative concentration.  If negative concentrations are found, the code will exit with an error message.

**Comment by msulprizio** [comment]
This is now resolved in e73ca4717ec266695ff72bda4a32f56c31b4a976 and will be included in the final 13.0.0 release.
