### ISSUE TITLE
[BUG/ISSUE] Make install issue with 13.0.0

### ISSUE THREAD

**Issue by eamarais** [geoschem/geos-chem#585]
## Describe the bug:
I get a "make: *** No rule to make target `install'.  Stop." error when I enter "make install" at the command line to build the model version 13.0.0. This is Step 7 on this page: http://wiki.seas.harvard.edu/geos-chem/index.php/Compiling_with_CMake. In the Makefile there doesn't seem to be a rule to "make install". There are no errors in my build and compile steps before this step when I follow the instructions on the wiki page. 

I am using GC Classic 2x2.5 with 47 levels full chemistry troposphere + stratosphere coupled to the RRTMG. I'm using compiler gfortran 9.2.0 and cmake version 3.19.1 obtained with spack, running the model on the UCL servers (computational cluster), using the model out-the-box (i.e. I haven't made any changes to the code).

### Expected behavior: ###
I expect this to generate a geos executable that should be copied to the run directory, though I've only just started using 13.0.0 after using 12.9.3.

### Actual behavior: ###
I get the error message "make: *** No rule to make target `install'.  Stop.". This suggests there isn't a rule in the Makefile to build "geos*"

I'm not sure what would be most helpful for me to include with this issue. I've attached the Makefile from the ./build/ subdirectory in my run directory.
[Makefile.zip](https://github.com/geoschem/geos-chem/files/5776796/Makefile.zip)

**Comment by eamarais** [comment]
Adding @rgryan92 to this thread, a postdoc working in my group who is also trying to address this issue to get 13.0.0 compiled and running on the UCL servers.

**Comment by msulprizio** [comment]
Hi Eloise. I believe the issue is that you need to configure your CMake build with the `-DRUNDIR` option to tell CMake where it should copy the executable. I've updated the documentation on our [Compiling with CMake](http://wiki.seas.harvard.edu/geos-chem/index.php/Compiling_with_CMake#Overview) page to reflect this. You should be able to fix the error by doing:

```
cd build
cmake . -DRUNDIR=/path/to/rundir/
make -j
make install
```

**Comment by eamarais** [comment]
Thanks Melissa. That addressed the error.

**Comment by yantosca** [comment]
Thanks @eamarais and @msulprizio.  We can close out this issue now.

Look for the official announcement of the GEOS-Chem 13.0.0 release candidates shortly!
