### ISSUE TITLE
[QUESTION] HISTORY.rc diagnostic miss 00:00 result at 1st day of simulation

### ISSUE THREAD

**Issue by JinZheeee** [geoschem/geos-chem#586]
Hi support team,
I'm using the v12.9.3 model at 2.5 x 2 resolution for the global CO2 simulation. I want to get three-hourly instantaneous species concentrations. Diagnostics of the 1st day of simulation only contain 7 results at 03:00, 06:00, ..., 21:00, and other days contain 8 results at 00:00, 03:00, ..., 21:00. 
Can I get diagnostics at 8 time points (including 00:00) on the 1st day like the other days?
Or can I get 8 results at 03:00, 06:00, ... , 24:00 every day?

Setting of the HISTORY.rc is as follows:
```
#==============================================================================
# %%%%% THE SpeciesConc COLLECTION %%%%%
#
# GEOS-Chem species concentrations (default = advected species)
#
# Available for all simulations
#==============================================================================
  SpeciesConc.template:       '%y4%m2%d2_%h2%n2z.nc4',
  SpeciesConc.format:         'CFIO',
  SpeciesConc.frequency:      00000000 030000
  SpeciesConc.duration:       00000001 000000
  SpeciesConc.mode:           'instantaneous'
  SpeciesConc.fields:         'SpeciesConc_?ADV?             ', 'GIGCchem',
                                         'Met_PMID                            ', 'GIGCchem',
                                         'Met_PSC2WET                     ', 'GIGCchem',
::
```
Thanks

**Comment by yantosca** [comment]
Thanks @JinZheeee for writing.  This is by design.  The HISTORY diagnostics instantaneous mode write out the diagnostics at the end of each timestep (which is the same as the beginning of the next timestep).

At 00:00 of the first day, the model has not done any computations. Therefore, the species concentrations will be the initial conditions.  But you will get output at 00:00 of each successive day.

**Comment by yantosca** [comment]
I will close out this issue for now.  Please feel free to open another issue if you are still experiencing problems with GEOS-Chem.
