### ISSUE TITLE
[BUG/ISSUE] Access to an undefined portion of a memory object.

### ISSUE THREAD

**Issue by usernamenottakenyet** [geoschem/geos-chem#587]
Hi,
I'm new to GEOS-Chem. I'm using GEOS-Chem 12.9.3 on an Ubuntu machine (gfortran, fopenmp). When running the geosfp_4x5_benchmark, I'm getting:

```
Program received signal SIGBUS: Access to an undefined portion of a memory object.
Backtrace for this error:
#0  0x7fcb191732ed in ???
#1  0x7fcb19172503 in ???
#2  0x7fcb185c0fcf in ???
#3  0x55ae2ccecfe0 in __tpcore_fvdas_mod_MOD_tpcore_fvdas._omp_fn.7
        at /home/hwinkler/GC/Code.12.9.3/GeosCore/tpcore_fvdas_mod.F90:1118
#4  0x7fcb18ba196d in ???
#5  0x7fcb17c046da in ???
#6  0x7fcb186a3a3e in ???
#7  0xffffffffffffffff in ???
```
The error occurs randomly, not at a given date.
Any idea, what that could be? How can I find out?
I did only make three change from the benchmark settings after download:
*47 instead of 72 levels
* Output every month
* longer simulation period (later end date)

-Holger

**Comment by yantosca** [comment]
Thanks for writting @usernamenottakenyet.  We don't have enough information to solve the problem.  Please see the checklist of items to provide at : http://wiki.geos-chem.org/Submitting_GEOS-Chem_support_requests and attach the required information to this Github issue.

**Comment by yantosca** [comment]
Also it looks like your job is failing in TPCORE in the first parallel loop.  It may be that you do not have the proper settings for OpenMP parallelization in your computational environment.  Please see the [Specifying Settings for OpenMP parallelization](http://wiki.seas.harvard.edu/geos-chem/index.php/Specifying_settings_for_OpenMP_parallelization) chapter of the GEOS-Chem User's Guide for more information.
