### ISSUE TITLE
[BUG/ISSUE] GC/Code.GC/Headers does not contain species_database.yml

### ISSUE THREAD

**Issue by emmapetersen** [geoschem/geos-chem#588]
Hi
I am having trouble with the species_database.yml file. I followed the guide 
https://cloud-gc.readthedocs.io/en/latest/chapter02_beginner-tutorial/research-workflow.html
to set up my server on amazon cloud and set up my GEOS-Chem directories.

## Describe the bug:
When I try to create a run directory, I get a message saying that there is no species_database.yml file in the GC/Code.GC/Headers, and therefore, it cannot copy it into my new run directory. 

### Error messages

```
cp: cannot stat '/home/ubuntu/GC/Code.GC/Headers/species_database.yml': No such file or directory
```

### Your GEOS-Chem version and runtime environment:

 - GEOS-Chem version: I tried with both 12.9.3 and the new 13.0.0 - but I got the same problem
 - Did you run on a computational cluster, on the AWS cloud: yes
   - If you ran on the AWS cloud, please specify the Amazon Machine Image (AMI) ID: I tried both ami-04751feef8546fdfe and ami-097f1b62def179f42
 - Are you using GEOS-Chem "out of the box" (i.e. unmodified): no
   - If you have modified GEOS-Chem, please list what was changed: 

I was thinking that maybe it has something to do with the new update? Otherwise, is it possible to download the species_database.yml file into my directory?

Best,
Emma

**Comment by WilliamDowns** [comment]
Thanks for opening this issue. Several instructions are now outdated in that workflow section of the Cloud GC Read The Docs site. The code download and run directory creation steps have changed as of version 13.0.0. We recommend following the instructions on the GEOS-Chem wiki for now, including for [downloading source code](http://wiki.seas.harvard.edu/geos-chem/index.php/Downloading_GEOS-Chem_source_code_(13.0.0_and_later_versions)) and [creating a run directory](http://wiki.seas.harvard.edu/geos-chem/index.php/Creating_run_directories_for_GEOS-Chem_13.0.0_and_later). 

I have personally run into the missing `species_database.yml` issue when following the now-outdated run directory creation workflow from pre-13.0.0 when using the 13.0.0 code. Let us know if following the instructions on the Wiki helps resolve your issue (and we do recommend now using the 13.0.0 AMI you tried with ID **ami-097f1b62def179f42**). We'll update the Cloud GC documentation to be completely up-to-date with 13.0.0.

**Comment by emmapetersen** [comment]
Thank you very much!

**Comment by angothelene** [comment]
Hi, I'm having a similar problem when downloading the code for v12.9.3.
I followed the [instructions on the wiki](http://wiki.seas.harvard.edu/geos-chem/index.php/Downloading_GEOS-Chem_source_code_(12.9.3_and_earlier_versions)): git clone https://github.com/geoschem/geos-chem Code.12.9.3.
When creating a run directory using the UT, I get the following warning:
<img width="672" alt="Screenshot 2021-02-03 at 15 31 01" src="https://user-images.githubusercontent.com/25373985/106761186-da326380-6634-11eb-9176-07c83f284d53.png">
The file is indeed missing.
Thanks!

**Comment by WilliamDowns** [comment]
When you type `git clone https://github.com/geoschem/geos-chem Code.12.9.3`, you are not actually setting your GEOS-Chem version to 12.9.3; you are naming your copy of the repository "Code.12.9.3". To get version 12.9.3 of the code, change to your Code.12.9.3 directory and type `git checkout -b new_branch_name tags/12.9.3`. I've updated the instructions on the wiki to make this more clear. Hope this helps.

**Comment by WilliamDowns** [comment]
Documentation updated by [https://github.com/geoschem/geos-chem-cloud/commit/ac3cc1949a0f44045dd7fe0e02f7f7ac2d5a1714](https://github.com/geoschem/geos-chem-cloud/commit/ac3cc1949a0f44045dd7fe0e02f7f7ac2d5a1714).
