### ISSUE TITLE
[QUESTION]Adding the new Volcanic emissions to the HEMCO_Diagnostic output file

### ISSUE THREAD

**Issue by JeanJGuo** [geoschem/geos-chem#589]
I'm trying to output volcanic degassing and eruptive emissions (in mass units of kg) in the `HEMCO_Diagnostic` output file. 
With the new Volcano emissions, we set the following in the `HEMCO_Config.rc` file

```
117     Volcano                : on    SO2
    --> Volcano_Source         :       AeroCom
    --> Volcano_Table          :       $ROOT/VOLCANO/v2019-08/$YYYY/$MM/so2_volcanic_emissions_Carns.$YYYY$MM$DD.rc
```
and for the `MyDiagnFile.rc` file, I've been trying a bunch of numbers as below:
```
# Name       Spec   ExtNr Cat Hier Dim Unit
###############################################################################
#####   Emissions By Inventory            #####
###############################################################################
Volcano         SO2     117   -1  -1     3   kg
VOL_SO2_ERUPT   SO2     117   51   1     3   kg
VOL_SO2_DEGAS   SO2     117   52   1     3   kg
VOL1_SO2_ERUPT  SO2     117   51  -1     3   kg
VOL1_SO2_DEGAS  SO2     117   52  -1     3   kg
```
However, I'm getting 0's in the output diagnostic netCDF file.

When I set the below values (0 instead of 117 for ExtNr), I get values, but I think it's global SO2 values and not volcanic values.
```
Volcano                 SO2      0  -1  -1    3   kg
```
I saw another answer had said to look for the values to use in HEMCO.log with verbose set to 3. That's where I got 51 and 52 from. But it doesn't seem to be correct and I can't figure out which other lines to look at.

How can I get the volcanic degassing and eruptive emissions in mass units in the `HEMCO_Diagnostic.nc` file? 

----
In older versions, we used the following lines in the `HEMCO_Config.rc.` As a result, VOLCANO had an entry in the body of the `HEMCO_Config.rc` file. Now, we no longer have those 4 lines.

```
--> VOLCANO        :     true
.
.
.
(((VOLCANO
0 VOL_SO2_ERUPT $ROOT/VOLCANO/v2015-02/$YYYY/volc_so2_gen.1x1.47L.$YYYY$MM.nc SO2_erupt 1979-2009/1-12/1-31/0 C xyz kg/m2/s SO2 - 51 1
0 VOL_SO2_DEGAS $ROOT/VOLCANO/v2015-02/$YYYY/volc_so2_gen.1x1.47L.$YYYY$MM.nc SO2_degas 1979-2009/1-12/1-31/0 C xyz kg/m2/s SO2 - 52 1
)))VOLCANO
```
These were the values in the `MyDiagnFile.rc` file:

```
# Name       Spec   ExtNr Cat Hier Dim Unit

###############################################################################
#####   Emissions By Inventory            #####
###############################################################################
VOL_SO2_ERUPT SO2     0     51  1    3   kg
VOL_SO2_DEGAS SO2     0     52  1    3   kg
```

**Comment by msulprizio** [comment]
This is what we are currently using in 13.0.0 and I can confirm that we get non-zero output in the HEMCO diagnostics file.

```
#=============================
# Volcano extension
#=============================
InvVOLCANOerupt_SO2  SO2    117  51  -1  3   kg/m2/s  SO2_eruptive_emission_flux_from_Volcano_extension
InvVOLCANOdegas_SO2  SO2    117  52  -1  3   kg/m2/s  SO2_degassing_emission_flux_from_Volcano_extension
```

Have you changed the default settings for the HEMCO diagnostics in HEMCO_Config.rc? By default we're using:

```
DiagnFile:                   HEMCO_Diagn.rc
DiagnPrefix:                 ./OutputDir/HEMCO_diagnostics
DiagnFreq:                   Monthly
```

but if your simulation is less than one month in duration, you may get zero or no output. 

You can also try changing your units in HEMCO_Diagn.rc from kg back to kg/m2/s to see if that resolves the issue. It may be that the HEMCO automatic unit conversions for the diagnostics are not working properly. 

If you're still having issues, please upload your HEMCO_Config.rc, HEMCO_Diagn.rc, and HEMCO.log files here so we can have a look. (You may need to add a .txt extension to upload those files.)
