### ISSUE TITLE
[QUESTION] GEOS-chem future simulations using HEMCO's RCP and RCP VOCs emission species matching from CMIP6

### ISSUE THREAD

**Issue by yixinguo0421** [geoschem/geos-chem#590]
Greetings!
I am trying to do future GEOS-chem simulations using CMIP6 projections of air pollutant emissions  for 2050. Three questions:

1) How do I set HEMCO? Do I simply open the RCP emissions in HEMCO and turn off all other anthropogenic emission inventories ? Do I set the meteorology year (current year, e.g. 2015) when running the model?

2) How are CMIP5's VOCs species grouped for generating HEMCO's RCP VOC emissions?  This information can be super helpful as I am trying to process CMIP6's emissions for HEMCO to read in the RCP emission section. 
The 1st and 2nd figure below show that CMIP6 have speciated NMVOCs and VOCs emissions, each with over 20 types of VOCs. HEMCO's RCP emissions have a smaller number of VOC species.  Ideally VOC=NMVOC+CH4, why would CMIP6 report both for speciated VOCs and NMVOCs? 

<img width="707" alt="Screen Shot 2021-01-15 at 4 05 34 PM" src="https://user-images.githubusercontent.com/75709818/104698048-b2de2a00-574b-11eb-8b84-477ba1e2c7c6.png">
<img width="699" alt="Screen Shot 2021-01-15 at 4 05 44 PM" src="https://user-images.githubusercontent.com/75709818/104698053-b5d91a80-574b-11eb-9cbb-7ad3194fe6b0.png">

The script I found  http://geoschemdata.computecanada.ca/ExtData/HEMCO/RCP/v2020-07/scripts/RCP_edit.sh only deals with unit conversion from CMIP5 emissions to HEMCO's data files. Where could I find more information about matching VOC emissions?

3) Lastly, have anyone run GEOS-chem with CMIP6 emissions? 

I am tagging the three experts listed in the RCP section of GEOS-chem wiki and your help is greatly appreciated! @christophkeller @sdeastham @yantosca

**Comment by yantosca** [comment]
Thanks for writing @yixinguo0421.

>1. How do I set HEMCO? Do I simply open the RCP emissions in HEMCO and turn off all other anthropogenic emission inventories ? Do I set the meteorology year (current year, e.g. 2015) when running the model?

If you want to use the existing RCP, then I believe that you would turn off all the anthro emissions and turn on the RCP emissions in the `HEMCO_Config.rc`.  I dont' think you need to fix the meteorology year (unless you want to run all years with the same meterorology).

I am also tagging @cdholmes, who has worked a lot with the RCP / CMIP data.  The GCST typically depends on external developers to provide emissions inventories.

**Comment by cdholmes** [comment]
Note that RCP emissions were used in CMIP5. CMIP6 future scenarios use SSP emissions. 

Assuming that you do indeed want to use RCP emissions, Bob is correct that you should turn off anthropogenic emissions (global and regional) in HEMCO when you turn on RCPs. RCP emissions from ships and aircraft are *not* currently implemented in HEMCO, so you should keep those sector emissions on from a different inventory or implement them yourself. (We previously had RCP ship and aircraft emissions in GEOS-Chem but that feature seems to have been lost in the transition to HEMCO.)

For mapping emitted inventory species to GEOS-Chem species, see the RCP section in HEMCO_Config.rc and [this document on implementation details.](http://acmg.seas.harvard.edu/geos/wiki_docs/emissions/GEOS-Chem_RCP_emissions.pdf
)

**Comment by yixinguo0421** [comment]
> Note that RCP emissions were used in CMIP5. CMIP6 future scenarios use SSP emissions.
> 
> Assuming that you do indeed want to use RCP emissions, Bob is correct that you should turn off anthropogenic emissions (global and regional) in HEMCO when you turn on RCPs. RCP emissions from ships and aircraft are _not_ currently implemented in HEMCO, so you should keep those sector emissions on from a different inventory or implement them yourself. (We previously had RCP ship and aircraft emissions in GEOS-Chem but that feature seems to have been lost in the transition to HEMCO.)
> 
> For mapping emitted inventory species to GEOS-Chem species, see the RCP section in HEMCO_Config.rc and [this document on implementation details.](http://acmg.seas.harvard.edu/geos/wiki_docs/emissions/GEOS-Chem_RCP_emissions.pdf)

Dear @cdholmes Christopher, I super super appreciate your help, the guidance document is extremely helpful. 

I do wish to run the CMIP6 SSP emissions and have finished mapping the SSP species to species listed in HEMCO's RCP section (based on the names) - the guidance document provides a second check over the mapping of VOC species. I plan to use the RCP section in HEMCO_Config.rc to read in the SSP emissions through pointing the directories to CMIP6 SSP emission files that I created in the same format as RCP emissions. Does that sound a reasonable approach? 

Also for the biomass burning emissions, I plan to simply use current bio emissions. It seems current RCP emissions also include only anthropogenic emissions and excluding forests and grassland burning. 

Dear @yantosca, thank you for your answer, combing replies from both of you I think I am almost there.

**Comment by yantosca** [comment]
@yixinguo0421, just wanted to check if you have resolved this problem. If so we can go ahead and close out this issue.  Let us know, thanks.
