### ISSUE TITLE
[FEATURE REQUEST] Updated aerosol dry deposition

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#604]
Jeff Pierce (@theloniuspunk) wrote:

>Last year, Delphine Farmer's group published a study (Emerson et al., 2020; https://www.pnas.org/content/117/42/26076) where they updated the Zhang et al. (2001) aerosol dry deposition parameterization based on recently size-resolved dry deposition measurements. In that study, my group tested the sensitivity of the GEOS-Chem-TOMAS mass, number, and aerosol radiative effects to the changes in the dry deposition parameters. However, in the publication, we did not update the deposition for the standard GEOS-Chem aerosol species, only the TOMAS size-resolve aerosol species. Here I show some PM2.5 evaluations, and I'm curious to know if the steering committee would recommend the new scheme for standard implementation. The size-dependent loss rates in the new scheme appear to be much more consistent with direct deposition-flux measurements.
>
>I just updated the dry-dep changes to act on the standard GEOS-Chem aerosols as well. Here is the percent change in PM2.5 going from the Zhang et al. (2001) parameters to those from Emerson et al. (2020) in GCClassic v13.0.0. The standard GC aerosol scheme is on the left, TOMAS is on the right. 
>
>![image](https://user-images.githubusercontent.com/4805437/106774936-a47b8380-6610-11eb-8787-df55e82008ac.png)
>
>The differences between the bulk (standard) and TOMAS PM2.5 changes is likely due to TOMAS predicting somewhat smaller particle sizes in many continental regions than the sizes assumed in the standard scheme. In Emerson, the dry dep velocities are slower relative to Zhang for smaller accumulation-mode particles over continents, but faster for larger accumulation-model particles over continents. 
>
>We evaluated the bulk (standard) PM2.5 against the Hammer et al. (2020; https://pubs.acs.org/doi/10.1021/acs.est.0c01764) climatology. Here is the comparison for when using the Zhang et al. (2001) parameters.
>![image](https://user-images.githubusercontent.com/4805437/106775191-e4426b00-6610-11eb-80dc-4a14a763cf41.png)
>And here is the same comparison for when using the updated Emerson et al. (2020) parameters:
>![image](https://user-images.githubusercontent.com/4805437/106775260-f02e2d00-6610-11eb-9c91-16f9a0e1566e.png)
>In these comparisons, there is little change in the fidelity of the GEOS-Chem PM2.5.
>
>Finally, Yanshun Li in Randall Martin's group evaluated the scheme for hi-res simulation over China, and his evaluation is attached. His results are similar to our global results, but he found that the new scheme helped to reduce a high bias in PM2.5 in China.

**Comment by msulprizio** [comment]
Here is the patch file provided by Jeff. 

[pierce-dry-dep_patch-file.diff.txt](https://github.com/geoschem/geos-chem/files/5919876/pierce-dry-dep_patch-file.diff.txt)

**Comment by yantosca** [comment]
I believe we can close this issue because PR #658 has been merged and will be released pending approval of benchmark results.
