### ISSUE TITLE
[BUG/ISSUE] 12.9.3 HISTORY.rc DryDep diagnostics (besides DryDepVel) all reading zero

### ISSUE THREAD

**Issue by wswanson3** [geoschem/geos-chem#606]
# Report a GEOS-Chem bug or technical issue

[HISTORY.rc.txt](https://github.com/geoschem/geos-chem/files/5922876/HISTORY.rc.txt)

## Describe the bug:
When running the base version of GEOS_Chem 12.9.3 with DryDep diagnostics enabled in the HISTORY.rc file, the only nonzero class of diagnostics is the dry deposition velocity. All other quantities are zero. 
### Expected behavior: ###

For the DryDep collection to output an array of nonzero values for DryDep, DryDepMix, and DryDepChm
### Actual behavior: ###

The Dry Deposition velocity values (DryDepVel_O3, etc) are nonzero and seem correct. All other values (DryDep_O3, DryDepChm_O3, DryDepMix_O3) are zero in all grid cells at all times. 
### Steps to reproduce: the bug:

1.  __make realclean 
2.  __make -j4 build 
3.  __

**Run commands**

1.  __./geos > drypdepBASE2_2
2.  __
3.  __

### Error messages

```
add text here
```

### Your GEOS-Chem version and runtime environment:

 - GEOS-Chem version: __12.9.3
 - Compiler version: __
 - netCDF version: __4
 - netCDF-Fortran version (if applicable): __
 - Did you run on a computational cluster, on the AWS cloud: __
   - If you ran on the AWS cloud, please specify the Amazon Machine Image (AMI) ID: __
 - Are you using GEOS-Chem "out of the box" (i.e. unmodified): __I checked out version 12.9.3 for this run
   - If you have modified GEOS-Chem, please list what was changed: _
[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/5922680/HEMCO_Config.rc.txt)
[HISTORY.rc.txt](https://github.com/geoschem/geos-chem/files/5922681/HISTORY.rc.txt)
[input.geos.txt](https://github.com/geoschem/geos-chem/files/5922682/input.geos.txt)

### Input and log files to attach

 - lastbuild: __lastbuild.txt
 - input.geos: __input.geos.txt
 - HEMCO_Config.rc: __HEMCO_Confid.rc.txt
 - GEOS-Chem "Classic" log file: __drypdepBASE2_2.txt
 - HEMCO.log: __
 - HiSTORY.rc.txt
 - slurm.out or any other error messages from your scheduler: __
 - Any other error messages: __

### Additional context

[lastbuild.txt](https://github.com/geoschem/geos-chem/files/5922674/lastbuild.txt)
[drypdepBASE2_2.txt](https://github.com/geoschem/geos-chem/files/5922675/drypdepBASE2_2.txt)
[GEOSChem.DryDep.20141001_0000z.nc4.txt](https://github.com/geoschem/geos-chem/files/5922676/GEOSChem.DryDep.20141001_0000z.nc4.txt)

**Comment by yantosca** [comment]
Thanks for writing @wswanson3.  How long have you spun up your simulation for?  The initial restart files that ship with the run directories should not be used to start a scientific simulation.  You should spin up for at least a year.  This will remove the signature of the initial conditions from your run.

If the drydep velocities are OK, then the drydep fluxes will be zero in places where the concentration is zero.  So this is something to check as well.

**Comment by wswanson3** [comment]
Bob,
This run was done with an initial restart file, but I had the same issue
when using a restart file that was spun up for a total of 7 months prior.
The Budget diagnostics show nonzero mixing ratios and Emis_DryDep fields.
-Will

**Comment by yantosca** [comment]
@wswanson3,I noticed that you've turned off the non-local mixing scheme, i.e.,
```
Turn on non-local PBL?      :     F
```
Can you try turning that on and see if you get drydep output?  Some of the drydep diagnostics are applied mixing.

**Comment by wswanson3** [comment]
Bob,
Will do, I’ll also make sure to use a spun up restart file.

Regards,
Will

**Comment by wswanson3** [comment]
Bob,
Turning on non-local PBL mixing fixes the DryDep diagnostic problem. When
non-local PBL mixing is set to True, the DryDep and DryDepMix become
nonzero. Using an initial restart file without spinup seems to cause
DryDepChm to go to zero. Thanks!
-Will

**Comment by yantosca** [comment]
Thanks @wswanson3.  I'll go ahead and close out this issue.  Please feel free to open another issue if you are still having problems.  Glad it's working!

**Comment by lizziel** [comment]
I am reopening this issue since it seems like a bug for DryDep and DryDepMix diagnostics to be zero if non-local PBL mixing is true. Also, our restarts are generated via 1-year benchmark simulation which includes a spin-up. It therefore seems odd that using that DryDepChm diagnostics would go to zero if using the initial restart file.
