### ISSUE TITLE
v12.9.3[BUG/ISSUE]

### ISSUE THREAD

**Issue by Yuan-yuan-2021** [geoschem/geos-chem#608]
---> DATE: 2015/07/01  UTC: 00:10  X-HRS:      0.166667
---> DATE: 2015/07/01  UTC: 00:20  X-HRS:      0.333333
forrtl: error (65): floating invalid
Image              PC                Routine            Line        Source
geos               000000000190454D  gckpp_hetrates_mp         522  gckpp_HetRates.F90
geos               000000000080FD74  flexchem_mod_mp_d         801  flexchem_mod.F90
libiomp5.so        00002B6A0F8DB003  Unknown               Unknown  Unknown
Aborted (core dumped)

**Comment by msulprizio** [comment]
We need more information to help with this issue. Please see [this wiki page](http://wiki.seas.harvard.edu/geos-chem/index.php/Submitting_GEOS-Chem_support_requests#What_do_I_need_to_include_in_my_support_request.3F) for information and files to include.



Please also see the following resources for debugging your error:
- [Floating invalid or floating-point exception error](http://wiki.seas.harvard.edu/geos-chem/index.php/Run-time_crashes_and_abnormal_exits#Floating_invalid_or_floating-point_exception_error)
- [Debugging GEOS-Chem](http://wiki.seas.harvard.edu/geos-chem/index.php/Debugging_GEOS-Chem)
- [Guide to GEOS-Chem error messages](http://wiki.seas.harvard.edu/geos-chem/index.php/Guide_to_GEOS-Chem_error_messages)

**Comment by Yuan-yuan-2021** [comment]
> 
> 
> We need more information to help with this issue. Please see [this wiki page](http://wiki.seas.harvard.edu/geos-chem/index.php/Submitting_GEOS-Chem_support_requests#What_do_I_need_to_include_in_my_support_request.3F) for information and files to include.
> 
> Please also see the following resources for debugging your error:
> 
>     * [Floating invalid or floating-point exception error](http://wiki.seas.harvard.edu/geos-chem/index.php/Run-time_crashes_and_abnormal_exits#Floating_invalid_or_floating-point_exception_error)
> 
>     * [Debugging GEOS-Chem](http://wiki.seas.harvard.edu/geos-chem/index.php/Debugging_GEOS-Chem)
> 
>     * [Guide to GEOS-Chem error messages](http://wiki.seas.harvard.edu/geos-chem/index.php/Guide_to_GEOS-Chem_error_messages)

I checked the reason, it may be the problem listed in the link you gave.Floating invalid or floating-point exception error. Thank you very much.

**Comment by msulprizio** [comment]
@Yuan-yuan-2021 Did you resolve the floating point error? If not, we need more information on our end. Please run a short simulation with debug flags turned on and attach the log files here.
