### ISSUE TITLE
[BUG/ISSUE]Error: NetCDF: Index exceeds dimension bound

### ISSUE THREAD

**Issue by map06** [geoschem/geos-chem#609]
Hi, 
I am trying to run full chemistry simulation in  `Geos-Chem v 2.9.3`. But, for some reason the simulation was interrupted. I tried to simulate again by the help  of hourly restart file  produced from the interrupted simulation. But, its giving me following error.  

[compilation_logfiles.zip](https://github.com/geoschem/geos-chem/files/5944651/compilation_logfiles.zip)

   
```!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In Ncrd_3d_R4 #2:  NetCDF: Index exceeds dimension bound
     65536       308

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Code stopped from DO_ERR_OUT (in module NcdfUtil/m_do_err_out.F90) 

This is an error that was encountered in one of the netCDF I/O modules,
which indicates an error in writing to or reading from a netCDF file!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!```

**Comment by yantosca** [comment]
Thanks for writing @map06.  I wonder if you are using a restart file that comes from a nested-grid run directory for your global simulation.  Can you do

```
ncdump -cts  GEOSChem.Restart.20160102_0000z.nc4
```
and post the output here (at least the output of just the dimension sizes), not all restart variables.  That will let us see the dimensions of the restart file and if they are consistent with your run directory.

**Comment by map06** [comment]
```
dimensions:
	time = UNLIMITED ; // (1 currently)
	lev = 72 ;
	ilev = 73 ;
	lat = 46 ;
	lon = 72 ;
```
Although I am not sure this is the same output as I again simulated it from the beginning  and  it seems the file has been overwritten.
