### ISSUE TITLE
[BUG/ISSUE] Spack NetCDF install issue; loading python and "C compiler cannot create executables"

### ISSUE THREAD

**Issue by WilliamDowns** [geoschem/geos-chem#613]
Hannah Horowitz wrote:

> netCDF is not installed on our campus cluster so I have been following the spack installation instructions.
> 
> one thing that came up for me - recognizing I may have inadvertently followed instructions out of order - is that for this to work:
> 
> `. $SPACK_ROOT/share/spack/setup-env.sh `
> 
> I needed to make sure python (version 3) was loaded first.
> 
> My question is that I got an error "C compiler cannot create executables" when actually getting to the installing netCDF part. Please let me know if this is not an appropriate request! I wasn't sure so just in case I thought I'd ask. I saw a similar issue on a github page about installing GCHP on the cloud (https://github.com/JiaweiZhuang/cloud-gchp-paper/issues/4) but it was using a different compiler (Intel, while I am using gcc) and I couldn't figure out how to translate it to my issue. It seems like it should be very simple... I am attaching the errors I got just in case. 
> 

[gcc_errors.txt](https://github.com/geoschem/geos-chem/files/5952836/gcc_errors.txt)
[spack-build-out.txt](https://github.com/geoschem/geos-chem/files/5952837/spack-build-out.txt)

**Comment by WilliamDowns** [comment]
Thank you for pointing out that Python requirement. We can update our Spack documentation to mention this possible requirement.

Regarding the compiler error, can you comment here with output from `spack config get compilers`? This will help diagnose whether Spack is properly recognizing your compiler. 

Assuming your `gcc 7.2.0` was installed outside of Spack, you can try loading the compiler however you normally would outside of Spack (such as by using `module load`), and then executing `spack compiler find` to make Spack save more information about this compiler for the future. This might be enough to fix your issue.

**Comment by hmhorow** [comment]
Thanks so much! 

I realize that when I loaded the python module, it loaded the GCC compiler at the same time. I tried loading it separately and it is the same default version 7.2.0.

this is what happens when I do `spack config get compilers`:

```
compilers:
- compiler:
    spec: gcc@4.8.5
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: centos7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@7.2.0
    paths:
      cc: /usr/local/gcc/7.2.0/bin/gcc
      cxx: /usr/local/gcc/7.2.0/bin/g++
      f77: /usr/local/gcc/7.2.0/bin/gfortran
      fc: /usr/local/gcc/7.2.0/bin/gfortran
    flags: {}
    operating_system: centos7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```

I tried entering `spack compiler find` before `spack install netcdf-fortran %gcc@7.2.0`. I specified the version of gcc since there were two compiler versions listed above. I got the same errors as before as far as I can tell. 

Thank you again!!

**Comment by WilliamDowns** [comment]
Thanks for following up. That all looks normal to me. Unfortunately I'm not sure what the issue is. One alternative is to install a copy of gcc through Spack, e.g. `spack install gcc@8.2.0; spack load gcc@8.2.0; spack compiler find`. This would take some time and disk space, but nothing crazy. This would almost definitely allow you to install netcdf-fortran using `spack install netcdf-fortran %gcc@8.2.0`.

**Comment by hmhorow** [comment]
thanks for the suggestions!

I tried doing `spack install gcc@8.2.0` but I did not enter any spack commands related to compilers beforehand, the gcc 7.2.0 module was loaded but that was it. This seems to require a properly working C compiler? I got a number of errors which I am copying below, and attaching the spack-build-out file. 
[spack-build-out-gcc820attempt.txt](https://github.com/geoschem/geos-chem/files/5954262/spack-build-out-gcc820attempt.txt)



```

==> Installing libiconv-1.16-lsk5sumoawkj4ulkc5muunpqxzlmombx
==> No binary for libiconv-1.16-lsk5sumoawkj4ulkc5muunpqxzlmombx found: installing from source
==> Using cached archive: /projects/horowitz_group/software_installs/spack/var/spack/cache/_source-cache/archive/e6/e6a1b1b589654277ee790cce3734f07876ac4ccfaecbee8afa0b649cf529cc04.tar.gz
==> No patches needed for libiconv
==> libiconv: Executing phase: 'autoreconf'
==> libiconv: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 77:
    '/tmp/hmhorow/spack-stage/spack-stage-libiconv-1.16-lsk5sumoawkj4ulkc5muunpqxzlmombx/spack-src/configure' '--prefix=/projects/horowitz_group/software_installs/spack/opt/spack/linux-centos7-sandybridge/gcc-7.2.0/libiconv-1.16-lsk5sumoawkj4ulkc5muunpqxzlmombx' '--enable-extra-encodings'

2 errors found in build log:
     8     checking for gawk... gawk
     9     checking whether make sets $(MAKE)... yes
     10    checking whether make supports nested variables... yes
     11    checking whether make sets $(MAKE)... (cached) yes
     12    checking for gcc... /projects/horowitz_group/software_installs/spack
           /lib/spack/env/gcc/gcc
     13    checking whether the C compiler works... no
  >> 14    configure: error: in `/tmp/hmhorow/spack-stage/spack-stage-libiconv-
           1.16-lsk5sumoawkj4ulkc5muunpqxzlmombx/spack-src':
  >> 15    configure: error: C compiler cannot create executables
     16    See `config.log' for more details

See build log for details:
  /tmp/hmhorow/spack-stage/spack-stage-libiconv-1.16-lsk5sumoawkj4ulkc5muunpqxzlmombx/spack-build-out.txt

==> Warning: Skipping build of diffutils-3.7-n62sw23voj7olvuj7fha4tqktoe5todq since libiconv-1.16-lsk5sumoawkj4ulkc5muunpqxzlmombx failed
==> Warning: Skipping build of gcc-8.2.0-tsqoxsa3mwhdhv5ojc3ku5xkiwfbarhm since diffutils-3.7-n62sw23voj7olvuj7fha4tqktoe5todq failed
==> Installing libsigsegv-2.12-2dpcylqz5qyz74u7ofnn76nhd7jujq6o
==> No binary for libsigsegv-2.12-2dpcylqz5qyz74u7ofnn76nhd7jujq6o found: installing from source
==> Using cached archive: /projects/horowitz_group/software_installs/spack/var/spack/cache/_source-cache/archive/3a/3ae1af359eebaa4ffc5896a1aee3568c052c99879316a1ab57f8fe1789c390b6.tar.gz
==> No patches needed for libsigsegv
==> libsigsegv: Executing phase: 'autoreconf'
==> libsigsegv: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 77:
    '/tmp/hmhorow/spack-stage/spack-stage-libsigsegv-2.12-2dpcylqz5qyz74u7ofnn76nhd7jujq6o/spack-src/configure' '--prefix=/projects/horowitz_group/software_installs/spack/opt/spack/linux-centos7-sandybridge/gcc-7.2.0/libsigsegv-2.12-2dpcylqz5qyz74u7ofnn76nhd7jujq6o' '--enable-shared'

2 errors found in build log:
     8     checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
     9     checking for gawk... gawk
     10    checking whether make sets $(MAKE)... yes
     11    checking whether make supports nested variables... yes
     12    checking for gcc... /projects/horowitz_group/software_installs/spack
           /lib/spack/env/gcc/gcc
     13    checking whether the C compiler works... no
  >> 14    configure: error: in `/tmp/hmhorow/spack-stage/spack-stage-libsigseg
           v-2.12-2dpcylqz5qyz74u7ofnn76nhd7jujq6o/spack-src':
  >> 15    configure: error: C compiler cannot create executables
     16    See `config.log' for more details

See build log for details:
  /tmp/hmhorow/spack-stage/spack-stage-libsigsegv-2.12-2dpcylqz5qyz74u7ofnn76nhd7jujq6o/spack-build-out.txt

==> Warning: Skipping build of m4-1.4.18-hiadvdat3iwxnoibt3kji6qfyepyqtif since libsigsegv-2.12-2dpcylqz5qyz74u7ofnn76nhd7jujq6o failed
==> Warning: Skipping build of mpfr-3.1.6-5ll3ep3ljkp3tvdqb355citurbu4oxpz since m4-1.4.18-hiadvdat3iwxnoibt3kji6qfyepyqtif failed
==> Warning: Skipping build of mpc-1.1.0-bbvtikqpzuuzime46m3h5g7esjjb2ct5 since mpfr-3.1.6-5ll3ep3ljkp3tvdqb355citurbu4oxpz failed
==> Warning: Skipping build of libtool-2.4.6-lu6jdr5ewkg77plshnfixgfak3sk7vbn since m4-1.4.18-hiadvdat3iwxnoibt3kji6qfyepyqtif failed
==> Warning: Skipping build of gmp-6.1.2-ucysfp2dujttd55bnskhhf63ydm2e3wj since libtool-2.4.6-lu6jdr5ewkg77plshnfixgfak3sk7vbn failed
==> Warning: Skipping build of autoconf-2.69-rvbsvozbkg3txszzehgmhwrk6ihi5s74 since m4-1.4.18-hiadvdat3iwxnoibt3kji6qfyepyqtif failed
==> Warning: Skipping build of automake-1.16.3-hyaouvelrh7xx5qriutxkaei5xhzkles since autoconf-2.69-rvbsvozbkg3txszzehgmhwrk6ihi5s74 failed
==> Installing berkeley-db-18.1.40-xe3wqsg6abujtr3phnxmvfgyrbeqnft4
==> No binary for berkeley-db-18.1.40-xe3wqsg6abujtr3phnxmvfgyrbeqnft4 found: installing from source
==> Using cached archive: /projects/horowitz_group/software_installs/spack/var/spack/cache/_source-cache/archive/0c/0cecb2ef0c67b166de93732769abdeba0555086d51de1090df325e18ee8da9c8.tar.gz
==> Ran patch() for berkeley-db
==> berkeley-db: Executing phase: 'autoreconf'
==> berkeley-db: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 77:
    '/tmp/hmhorow/spack-stage/spack-stage-berkeley-db-18.1.40-xe3wqsg6abujtr3phnxmvfgyrbeqnft4/spack-src/dist/configure' '--prefix=/projects/horowitz_group/software_installs/spack/opt/spack/linux-centos7-sandybridge/gcc-7.2.0/berkeley-db-18.1.40-xe3wqsg6abujtr3phnxmvfgyrbeqnft4' '--disable-static' '--enable-cxx' '--enable-dbm' '--enable-stl' '--enable-compat185' '--with-repmgr-ssl=no'

2 errors found in build log:
     55    checking for mkdir... mkdir
     56    checking for rm... rm
     57    checking for mv... mv
     58    checking for sh... /usr/bin/sh
     59    checking for a BSD-compatible install... /usr/bin/install -c
     60    checking whether the C compiler works... no
  >> 61    configure: error: in `/tmp/hmhorow/spack-stage/spack-stage-berkeley-
           db-18.1.40-xe3wqsg6abujtr3phnxmvfgyrbeqnft4/spack-src/build_unix':
  >> 62    configure: error: C compiler cannot create executables
     63    See `config.log' for more details

See build log for details:
  /tmp/hmhorow/spack-stage/spack-stage-berkeley-db-18.1.40-xe3wqsg6abujtr3phnxmvfgyrbeqnft4/spack-build-out.txt

==> Warning: Skipping build of perl-5.32.1-iqdh4nlpff7ufszrwhwdyuc7bq2oh4hy since berkeley-db-18.1.40-xe3wqsg6abujtr3phnxmvfgyrbeqnft4 failed
==> Installing pkgconf-1.7.3-rxp42xs7tsiqdlyqc4me4qc7qeug75ow
==> No binary for pkgconf-1.7.3-rxp42xs7tsiqdlyqc4me4qc7qeug75ow found: installing from source
==> Using cached archive: /projects/horowitz_group/software_installs/spack/var/spack/cache/_source-cache/archive/b8/b846aea51cf696c3392a0ae58bef93e2e72f8e7073ca6ad1ed8b01c85871f9c0.tar.xz
==> No patches needed for pkgconf
==> pkgconf: Executing phase: 'autoreconf'
==> pkgconf: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 77:
    '/tmp/hmhorow/spack-stage/spack-stage-pkgconf-1.7.3-rxp42xs7tsiqdlyqc4me4qc7qeug75ow/spack-src/configure' '--prefix=/projects/horowitz_group/software_installs/spack/opt/spack/linux-centos7-sandybridge/gcc-7.2.0/pkgconf-1.7.3-rxp42xs7tsiqdlyqc4me4qc7qeug75ow'

2 errors found in build log:
  >> 6    configure: error: in `/tmp/hmhorow/spack-stage/spack-stage-pkgconf-1.7.3-rxp42xs7tsiqdlyqc4me4qc
          7qeug75ow/spack-src':
  >> 7    configure: error: C compiler cannot create executables
     8    See `config.log' for more details

See build log for details:
  /tmp/hmhorow/spack-stage/spack-stage-pkgconf-1.7.3-rxp42xs7tsiqdlyqc4me4qc7qeug75ow/spack-build-out.txt

==> Warning: Skipping build of ncurses-6.2-r6ibqphwkdhvjga6h6xm4rx4qf3jsp46 since pkgconf-1.7.3-rxp42xs7tsiqdlyqc4me4qc7qeug75ow failed
==> Warning: Skipping build of readline-8.0-oi73tiiq2e6axb4se5yptxzhxbkynpoy since ncurses-6.2-r6ibqphwkdhvjga6h6xm4rx4qf3jsp46 failed
==> Warning: Skipping build of gdbm-1.18.1-26tonqiud64sywkqxg2u3zlsi5rlfdv6 since readline-8.0-oi73tiiq2e6axb4se5yptxzhxbkynpoy failed
==> Installing zlib-1.2.11-gaewnqrmfte5bc7ttjigrwyitdcwpjqv
==> No binary for zlib-1.2.11-gaewnqrmfte5bc7ttjigrwyitdcwpjqv found: installing from source
==> Using cached archive: /projects/horowitz_group/software_installs/spack/var/spack/cache/_source-cache/archive/c3/c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1.tar.gz
==> No patches needed for zlib
==> zlib: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 1:
    './configure' '--prefix=/projects/horowitz_group/software_installs/spack/opt/spack/linux-centos7-sandybridge/gcc-7.2.0/zlib-1.2.11-gaewnqrmfte5bc7ttjigrwyitdcwpjqv'
See build log for details:
  /tmp/hmhorow/spack-stage/spack-stage-zlib-1.2.11-gaewnqrmfte5bc7ttjigrwyitdcwpjqv/spack-build-out.txt
```

**Comment by hmhorow** [comment]
sorry to double comment, I tried checking compilers before doing the spack install (spack compilers, spack config get compilers, spack compiler find) but this did not change the above.

**Comment by yantosca** [comment]
Hi @hmhorow, thanks for the update.  You might need to give the compiler name when installing each library, such as:

```
spack install netcdf-fortran %gcc@7.2.0 target=x86_64
```
this will force a build with a specific compiler (has to be one of the compilers in your `~/.spack/config/compilers.yaml` file

Also, I would recommend to add the `target=x86_64` attribute, especially if your computer cluster has more than one type of chipset.  Out of the box, Spack will build for the given type of CPU (e.g. Intel haswell, broadwell, cascade lake, etc)  of the node that you are using.  But this can lead to problems if you built the Spack library for e.g. broadwell but then end up running on another type of CPU.  The `target=x86_cpu` keeps things generic so that it should work across all types of x86 chips.

If you want, you can build a newer compiler using an older compiler, e.g.
```
spack install gcc@9.3.0 %gcc@7.2.0 target=x86_64
```
will use the GNU compilers 7.2.0 to build the GNU complers 9.3.0.  Then for all other libraries you can use e.g.
```
spack install netcdf-fortran %gcc@9.3.0 target=x86_64
spack install cmake %gcc@9.3.0 target=x86_64
etc.
```
You can look at the sequence at this Github issue: https://github.com/geoschem/geos-chem-cloud/issues/35 
(but be sure to also add `target=x86_64` to it.

**Comment by yantosca** [comment]
Also -- if you do build a newer compiler version with Spack you'll have to add it to the `~/.spack/config/compilers.yaml` file before using that newer compiler to build any other libraries.

**Comment by yantosca** [comment]
One more thing...often a build will fail because the download of the source code for that library was interrupted.   was incomplete.  If a spack install command fails, try it again and see if it continues.  It's best to do spack install commands one at a time for this reason (or at least I think so).

**Comment by hmhorow** [comment]
Thanks Bob so much for your input!
So I tried 
`spack install netcdf-fortran %gcc@7.2.0 target=x86_64`
which failed and got similar errors to before, e.g., :

```
==> Error: ProcessError: Command exited with status 77:
    '/tmp/hmhorow/spack-stage/spack-stage-libsigsegv-2.12-aivriptjpc5e4jorh6oyejtubf5pclno/spack-src/configure' '--prefix=/projects/horowitz_group/software_installs/spack/opt/spack/linux-centos7-x86_64/gcc-7.2.0/libsigsegv-2.12-aivriptjpc5e4jorh6oyejtubf5pclno' '--enable-shared'

2 errors found in build log:
     8     checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
     9     checking for gawk... gawk
     10    checking whether make sets $(MAKE)... yes
     11    checking whether make supports nested variables... yes
     12    checking for gcc... /projects/horowitz_group/software_installs/spack/lib/spack/env/gcc/gcc
     13    checking whether the C compiler works... no
  >> 14    configure: error: in `/tmp/hmhorow/spack-stage/spack-stage-libsigsegv-2.12-aivriptjpc5e4jorh6oy
           ejtubf5pclno/spack-src':
  >> 15    configure: error: C compiler cannot create executables
     16    See `config.log' for more details

```

The errors are repeated for almost all individual parts that are installed, except util-macros-1.19 which is successfully installed. Here is the full suite of error messages printed out
[all_errors_netcdf-fortran_gcc720_x86_64.txt](https://github.com/geoschem/geos-chem/files/5954480/all_errors_netcdf-fortran_gcc720_x86_64.txt)
 
So then I tried
`spack install gcc@9.3.0 %gcc@7.2.0 target=x86_64`
but it also failed. I tried entering it a second time but got the same errors. It fails within I would say <30 seconds.  In this case nothing is successfully installed and the same configure errors are repeated for each before it eventually exits. 

```
[hmhorow@golubh4 software_installs]$ spack install gcc@9.3.0 %gcc@7.2.0 target=x86_64
==> Installing libiconv-1.16-deggwmslm3q7abf6vhrfczt3fxcsuyq7
==> No binary for libiconv-1.16-deggwmslm3q7abf6vhrfczt3fxcsuyq7 found: installing from source
==> Using cached archive: /projects/horowitz_group/software_installs/spack/var/spack/cache/_source-cache/archive/e6/e6a1b1b589654277ee790cce3734f07876ac4ccfaecbee8afa0b649cf529cc04.tar.gz
==> No patches needed for libiconv
==> libiconv: Executing phase: 'autoreconf'
==> libiconv: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 77:
    '/tmp/hmhorow/spack-stage/spack-stage-libiconv-1.16-deggwmslm3q7abf6vhrfczt3fxcsuyq7/spack-src/configure' '--prefix=/projects/horowitz_group/software_installs/spack/opt/spack/linux-centos7-x86_64/gcc-7.2.0/libiconv-1.16-deggwmslm3q7abf6vhrfczt3fxcsuyq7' '--enable-extra-encodings'

2 errors found in build log:
     8     checking for gawk... gawk
     9     checking whether make sets $(MAKE)... yes
     10    checking whether make supports nested variables... yes
     11    checking whether make sets $(MAKE)... (cached) yes
     12    checking for gcc... /projects/horowitz_group/software_installs/spack/lib/spack/env/gcc/gcc
     13    checking whether the C compiler works... no
  >> 14    configure: error: in `/tmp/hmhorow/spack-stage/spack-stage-libiconv-1.16-deggwmslm3q7abf6vhrfcz
           t3fxcsuyq7/spack-src':
  >> 15    configure: error: C compiler cannot create executables
     16    See `config.log' for more details
```
The full errors printed out for this one are here:
[all_errors_gcc930_fromgcc720_x86_64.txt](https://github.com/geoschem/geos-chem/files/5954501/all_errors_gcc930_fromgcc720_x86_64.txt)
and the spack-build-out file has only a couple of lines:
```
==> zlib: Executing phase: 'install'
==> [2021-02-09-15:44:29.932987] './configure' '--prefix=/projects/horowitz_group/software_installs/spack/opt/spack/linux-centos7-x86_64/gcc-7.2.0/zlib-1.2.11-fuwbsyd4h6milgbzfi362t25s46hd75r'
Compiler error reporting is too harsh for ./configure (perhaps remove -Werror).
** ./configure aborting.
```

I double checked that gcc7.2.0 is in my `~/.spack/linux/compilers.yaml` file (note I do not have a config directory in the .spack directory, just linux and cache. is this an issue?)

```
- compiler:
    spec: gcc@7.2.0
    paths:
      cc: /usr/local/gcc/7.2.0/bin/gcc
      cxx: /usr/local/gcc/7.2.0/bin/g++
      f77: /usr/local/gcc/7.2.0/bin/gfortran
      fc: /usr/local/gcc/7.2.0/bin/gfortran
    flags: {}
    operating_system: centos7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```

I don't know if there's some issue with extra_rpaths, or the fact that the paths for cc/cxx/f77/fc are written as usr/local/ . 

Thank you again so very much for your help with this!!

**Comment by WilliamDowns** [comment]
What happens if you try any of your install commands with `%gcc@4.8.5` instead of `%gcc@7.2.0`?

**Comment by yantosca** [comment]
Sorry, yes it should be ~/.spack/linux.compilers.yaml.

**Comment by hmhorow** [comment]
thanks for the idea!
I actually tried the netcdf one first (`spack install netcdf-fortran %gcc@4.8.5 target=x86_64`) and it seems to be working - so far everything is installing successfully. It's still going (much longer than any other attempt). 
Is there any issue installing netcdf-fortran with this older version of gcc? if so, then I will try to install a newer version of gcc with gcc4.8.5.  what would you specifically recommend (e.g., 8.2.0, 9.3.0)?

**Comment by yantosca** [comment]
Hi @hmhorow.  I think GEOS-Chem Classic won't build with anything lower than gcc7.  But that's the compiler only.  The libraries built off of older compilers *may* work.  But often you run into compiler-library inconsistencies so I would recommend using the same compiler to build all the libraries and run GEOS-Chem.

Definitely GCHP needs gfortran 8.2.0 or later.  If you can, I would recommend using gcc 9.3.0 or 10.2.0.  I've built Spack. libraries with both of those versions and they work fine.  Maybe gcc 9.3.0 would be a little easier to build (more things seemed to build w/o error).

**Comment by yantosca** [comment]
Also if you want to run GCHP, @WilliamDowns has set up a Spack package for GCHP that installs all the dependencies.  I think we are still updating the doc but he can give you more details about that if you want.

**Comment by hmhorow** [comment]
thank you both so so much for your help! I am so grateful. 
the install ended up getting killed before it was done, because I was trying it on a login node instead of a compute node on our cluster. oops!
But it seems promising that I should be able to install the appropriate newer version of gcc using the working older version of gcc, and then use the newer one to install netcdf (after loading it properly etc.).
I really appreciate your help, and I will let you know how it goes, whenever I get an interactive job going and can try it later tonight. 
I may want to run GCHP in the future, but for now my plans involve GC Classic. thanks for the heads up!

**Comment by hmhorow** [comment]
update: I installed gcc 9.3.0 with gcc 4.8.5, and then loaded the gcc 9.3.0 compiler to install netcdf-fortran successfully! 
thank you again so much for your help!

**Comment by yantosca** [comment]
Thanks @hmhorow, I'm glad it works now.   I like gfortran 9.3.0, it's a very stable compiler and catches a lot of errors (typically the GNU compilers parse the Fortran language more strictly than the ifort compilers do).

I'll close out this issue for now, but feel free to open a new issue if you are still having problems.
