### ISSUE TITLE
[FEATURE REQUEST] Add check that run directory is the same version

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/geos-chem#62]
A check should be added to verify the run directory's version matches GEOS-Chem's version.

I'll follow up in a bit with a PR.

**Comment by yantosca** [comment]
This is now resolved by https://github.com/geoschem/geos-chem/pull/63.  It was merged into dev/12.6.0, which as of this writing is currently undergoing benchmarking.  We can close this out.
