### ISSUE TITLE
[QUESTION] Specifying hourly PM2.5 output in GEOS-Chem 12.9.3

### ISSUE THREAD

**Issue by Yuan-yuan-2021** [geoschem/geos-chem#621]
Hello!
Now I’m trying to use cheo-chem, Code.12.9.3, merra2_2x25_tropchem, I want to output the daily PM2.5 concentration, but now I only output the monthly value. This is my setting. Can you tell me how to set and get the daily value of PM2.5? 
```
%% OUTPUT MENU %%%     : 123456789.123456789.123456789.1--1=ZERO+2=BPCH
Schedule output for JAN : 3333333333333333333333333333333
Schedule output for FEB : 33333333333333333333333333333
Schedule output for MAR : 3333333333333333333333333333333
Schedule output for APR : 333333333333333333333333333333
Schedule output for MAY : 3333333333333333333333333333333
Schedule output for JUN : 333333333333333333333333333333
Schedule output for JUL : 3333333333333333333333333333333
Schedule output for AUG : 3333333333333333333333333333333
Schedule output for SEP : 333333333333333333333333333333
Schedule output for OCT : 3333333333333333333333333333333
Schedule output for NOV : 333333333333333333333333333333
Schedule output for DEC : 3333333333333333333333333333333
------------------------+------------------------------------------------------
%%% GAMAP MENU %%%      :
diaginfo.dat path       : diaginfo.dat
tracerinfo.dat path     : tracerinfo.dat
------------------------+------------------------------------------------------
%%% DIAGNOSTIC MENU %%% :
Binary punch file name  : trac_avg.geosfp_4x5_benchmark.YYYYMMDDhhmm
Diagnostic Entries ---> :  L   Tracers to print out for each diagnostic
ND03: Hg emissions, P/L :  0   all
ND06: Dust aer source   :  1   all
ND44: Drydep flx/vel    :  1   all
ND53: POPs Emissions    :  0   all
ND59: TOMAS aerosol emis:  0   all
ND60: TOMAS rate        :  0   all
ND61: TOMAS 3D rate     :  0   all
ND72: Radiative output  :  0   all
------------------------+------------------------------------------------------
%%% PLANEFLIGHT MENU %%%:
Turn on plane flt diag? : F
Flight track info file  : Planeflight.dat.YYYYMMDD
Output file name        : plane.log.YYYYMMDD
-------------------------------------------------------------------------------
%%% ND51 MENU %%%       :
Turn on ND51 diagnostic : F
LT avg timeseries file  : ts_satellite.YYYYMMDD.bpch
Output as HDF5?         : F
Tracers to include      : 46 504 506
GMT Hour for disk write :   0
Avg Period [LT hours]   :   9  11
IMIN, IMAX of region    :   1  72
JMIN, JMAX of region    :   1  46
LMIN, LMAX of region    :   1  40
-------------------------------------------------------------------------------
%%% ND51b MENU %%%      :
Turn on ND51b diagnstic : F
LT avg timeseries file  : ts_13_15.NA.YYYYMMDD.h5
Output as HDF5?         : F
Tracers to include      : 1 4 20 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 60 61 62 63 64 65 66 72 73 75 82 83 84 85 86 87 93 94 98 99
GMT Hour for disk write :  1
Avg Period [LT hours]   :  13  15
IMIN, IMAX of region    :   1  72
JMIN, JMAX of region    :   1  46
LMIN, LMAX of region    :   1   1
-------------------------------------------------------------------------------
%%% PROD & LOSS MENU %%%: ### ONLY NEEDED FOR TOMAS ###
Turn on P/L (ND65) diag?: T
# of levels for ND65    : 72
------------------------+------------------------------------------------------
END OF FILE             :
------------------------+------------------------------------------------------
```

**Comment by yantosca** [comment]
Thanks for writing @Yuan-yuan-2021.  We have removed the binary punch hourly and daily output from GEOS-Chem 12.9.3.  However, you can save any of the netCDF diagnostic collections with hourly output ([see this link](http://wiki.seas.harvard.edu/geos-chem/index.php/Replicating_the_behavior_of_the_prior_timeseries_diagnostics)).

The PM2.5 diagnostic is contained in the AerosolMass diagnostic collection.  In the HISTORY.rc file in your run directory, you can add a new collection.

1. Add the name of the new collection (call it PM25Hourly) to the COLLECTIONS list at the top of HISTORY.rc.
```
COLLECTIONS: 'Restart',
             'Metrics',
             'SpeciesConc',
             'PM25Hourly',
             ... etc ...
```
2. Further down in the HISTORY.rc file, add the new collection definition:
```
#==============================================================================
# %%%%% THE PM25Hourly COLLECTION %%%%%
#
# Hourly PM2.5 output
#==============================================================================
  PM25Hourly.template:       '%y4%m2%d2_%h2%n2z.nc4',
  PM25Hourly.format:         'CFIO',
  PM25Hourly.frequency:      00000000 010000
  PM25Hourly.duration:       00000001 000000
  PM25Hourly.mode:           'time-averaged'
  PM25Hourly.fields:           'PM25                         ', 'GIGCchem',
::
```
This will create a new file each day with 24 time points (one per hour) to the OutputDir folder in your run directory.  NOTE: The first day will have 23 time points, as diagnostic output for the start of the run is not saved.

You can use any netCDF viewer to look at the data.  If you are new to netCDF and python, we recommend that you look at our [GEOS-Chem python tutorial](https://github.com/geoschem/GEOSChem-python-tutorial).  We also have a python package with some general plotting capabilities called [GCPy](https://github.com/geoschem/gcpy).

**Comment by yantosca** [comment]
Also if you want instantaneous output instead of time-averaged output, you can change the "time-averaged" for the PM25Hourly collection to "instantaneous".  Then you will get the instantaneous data at the top of each hour.

**Comment by Yuan-yuan-2021** [comment]
Thank you very much, dear @yantosca

**Comment by Yuan-yuan-2021** [comment]
> dear @yantosca，I have another question, if I want to simulate 2016 (meteorological fields), but I want to use 2010 emissions, how should I set it? 
> 
> Hello!
> Now I’m trying to use cheo-chem, Code.12.9.3, merra2_2x25_tropchem, I want to output the daily PM2.5 concentration, but now I only output the monthly value. This is my setting. Can you tell me how to set and get the daily value of PM2.5?
> 
> ```
> %% OUTPUT MENU %%%     : 123456789.123456789.123456789.1--1=ZERO+2=BPCH
> Schedule output for JAN : 3333333333333333333333333333333
> Schedule output for FEB : 33333333333333333333333333333
> Schedule output for MAR : 3333333333333333333333333333333
> Schedule output for APR : 333333333333333333333333333333
> Schedule output for MAY : 3333333333333333333333333333333
> Schedule output for JUN : 333333333333333333333333333333
> Schedule output for JUL : 3333333333333333333333333333333
> Schedule output for AUG : 3333333333333333333333333333333
> Schedule output for SEP : 333333333333333333333333333333
> Schedule output for OCT : 3333333333333333333333333333333
> Schedule output for NOV : 333333333333333333333333333333
> Schedule output for DEC : 3333333333333333333333333333333
> ------------------------+------------------------------------------------------
> %%% GAMAP MENU %%%      :
> diaginfo.dat path       : diaginfo.dat
> tracerinfo.dat path     : tracerinfo.dat
> ------------------------+------------------------------------------------------
> %%% DIAGNOSTIC MENU %%% :
> Binary punch file name  : trac_avg.geosfp_4x5_benchmark.YYYYMMDDhhmm
> Diagnostic Entries ---> :  L   Tracers to print out for each diagnostic
> ND03: Hg emissions, P/L :  0   all
> ND06: Dust aer source   :  1   all
> ND44: Drydep flx/vel    :  1   all
> ND53: POPs Emissions    :  0   all
> ND59: TOMAS aerosol emis:  0   all
> ND60: TOMAS rate        :  0   all
> ND61: TOMAS 3D rate     :  0   all
> ND72: Radiative output  :  0   all
> ------------------------+------------------------------------------------------
> %%% PLANEFLIGHT MENU %%%:
> Turn on plane flt diag? : F
> Flight track info file  : Planeflight.dat.YYYYMMDD
> Output file name        : plane.log.YYYYMMDD
> -------------------------------------------------------------------------------
> %%% ND51 MENU %%%       :
> Turn on ND51 diagnostic : F
> LT avg timeseries file  : ts_satellite.YYYYMMDD.bpch
> Output as HDF5?         : F
> Tracers to include      : 46 504 506
> GMT Hour for disk write :   0
> Avg Period [LT hours]   :   9  11
> IMIN, IMAX of region    :   1  72
> JMIN, JMAX of region    :   1  46
> LMIN, LMAX of region    :   1  40
> -------------------------------------------------------------------------------
> %%% ND51b MENU %%%      :
> Turn on ND51b diagnstic : F
> LT avg timeseries file  : ts_13_15.NA.YYYYMMDD.h5
> Output as HDF5?         : F
> Tracers to include      : 1 4 20 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 60 61 62 63 64 65 66 72 73 75 82 83 84 85 86 87 93 94 98 99
> GMT Hour for disk write :  1
> Avg Period [LT hours]   :  13  15
> IMIN, IMAX of region    :   1  72
> JMIN, JMAX of region    :   1  46
> LMIN, LMAX of region    :   1   1
> -------------------------------------------------------------------------------
> %%% PROD & LOSS MENU %%%: ### ONLY NEEDED FOR TOMAS ###
> Turn on P/L (ND65) diag?: T
> # of levels for ND65    : 72
> ------------------------+------------------------------------------------------
> END OF FILE             :
> ------------------------+------------------------------------------------------
> ```
