### ISSUE TITLE
[BUG/ISSUE] installing cdo with spack re-installs netcdf-c, hdf [BUG/ISSUE]

### ISSUE THREAD

**Issue by hmhorow** [geoschem/geos-chem#627]
Hello!
I wanted to install cdo with spack as recommended in the geos chem wiki. I assumed I should specify the same compiler (gcc 9.3.0) I used for all the other geos chem software (e.g., netCDF). so I entered the following:
`spack install cdo %gcc@9.3.0 target=x86_64`

this led to it apparently re-installing the same versions of netcdf-c and hdf that I had previously installed using spack and the gcc 9.3.0 compiler, but with new and different directories. so my .bashrc which previously loaded netcdf (`spack load netcdf-c`) now throws this error:

```
==> Error: netcdf-c matches multiple packages.
  Matching packages:
    zidmuxn netcdf-c@4.7.4%gcc@9.3.0 arch=linux-centos7-x86_64
    bla3o3s netcdf-c@4.7.4%gcc@9.3.0 arch=linux-centos7-x86_64
  Use a more specific spec.

```

When I look in my spack directory I see these duplicated folders:

originals: 
```
hdf5-1.10.7-dpaeyrxmvvuitkuatbfshghiu2ubce3c
netcdf-c-4.7.4-zidmuxngv3m5uiab2hxdhkkplzpccrqy
```

ones that were added when installing cdo:
```
hdf5-1.10.7-3ztabcbhyk4arlrtknfzvl6fw5czhpjo
netcdf-c-4.7.4-bla3o3sbrel75av6ttbl7m5osjsbzmq4
```

I don't want to inadvertently mess up my ability to run geos chem by installing cdo (and eventually also nco). what would be the recommended next steps? 
thank you so much!

**Comment by hmhorow** [comment]
I would like confirmation that this is the correct approach before closing the issue, but I went in and changed how I was loading netCDF-c and specifying the location in my .bashrc to refer to the specific 'spec' of the one that was installed first when I was setting up GEOS-Chem itself, not the one that was installed when I started installing cdo. 

so from this:
`spack load netcdf-c  `
to this:
`spack load /zidmuxn`

and this:
`export NETCDF_HOME=`spack location -i netcdf-c`  `
to this:
`export NETCDF_HOME=`spack location -i /zidmuxn``

not sure if when I try to use cdo it will get confused.. I haven't actually finished installing cdo so I'm also not sure if this will happen with additional spack modules (like netcdf-fortran). 

Thanks again for your help!

**Comment by yantosca** [comment]
Thanks for writing @hmhorow.  

You can remove the duplicate hdf5 and netcdf-c by attaching the hashes:
```
 spack uninstall hdf5 /3ztabcb
 spack uninstall netcdf-c /bla3o3s
```
Also, when installing new spack libraries, you should make sure you have loaded all of your existing spack libraries with `spack load`.  That might have been why the cdo build tried to get new hdf5 and netcdf-c builds., because it couldn't find the existing ones.

Once you uninstall, you can try installing again.  However, the cdo build is tricky and often fails.  I typically stick to just nco with Spack.

**Comment by yantosca** [comment]
@hmhorow, you can also use this syntax to put executable code in a bash script:

```
export NETCDF_HOME=$(spack_location -i netcdf-c)
```

**Comment by hmhorow** [comment]
thanks so much Bob!
would you recommend using github for cdo then? will uninstall and then try nco with spack first (loading all the software beforehand)!

**Comment by yantosca** [comment]
Hi @hmhorow.  I think that sounds reasonable -- try again with Spack first, before manually installing.  

I tried reinstalling cdo in my Spack stack:
```
spack install cdo%gcc@10.2.0 target=x86_64
```
but I also found that it seemed to be trying to rebuild packages that I already had.  I'll dig into it a little bit more when I have the chance.

**Comment by yantosca** [comment]
I think there is an issue on Spack that even if you have a package installed, it will build a package again if there is a newer version available.  So you might have to manually force all of the dependencies, i.e.
```
spack install cdo%gcc@10.2.0 ^netcdf-c@X.Y.Z ^hdf5@X.Y.Z ... target=x86_64
```
I think you can also specify dependencies in the packages.yml file.

**Comment by WilliamDowns** [comment]
I did a little digging and found that what's probably happening is that by default, `spack install cdo` tries to build with the `+netcdf` option, which is presumably desired. This option requires that `hdf5` be built with the `+threadsafe` option as a back-end for `netcdf-c`. However, when you simply do `spack install netcdf-fortran` or `spack install netcdf-c`, this `+threadsafe` option is NOT enabled by default. So if you go to install `cdo` after doing the standard installation of `netcdf-fortran` that we suggest on the Wiki, then it will redo the installation of `hdf5` and `netcdf-c` thanks to this one option changing. If you want to continue trying to install `cdo` with Spack and also want to build and run GEOS-Chem with Spack-built libraries, then you can try uninstalling all of your copies of `hdf5`, `netcdf-c`, and `netcdf-fortran`, and then do `spack install netcdf-fortran ^hdf5 +threadsafe; spack install cdo`. This should reuse the libraries across the two installs.

**Comment by yantosca** [comment]
Thanks @WilliamDowns!  That makes sense.   I am going to try this and let you know how it works.

**Comment by hmhorow** [comment]
Thank you both so much for your help!

Looking forward to hearing how it goes, Bob. Then I will try it myself!

**Comment by yantosca** [comment]
Hi @hmhorow and @WilliamDowns.  To uninstall the existing libraries:
```
source $SPACK_ROOT/share/spack/setup-env.sh
spack gc 
spack uninstall --dependents netcdf-fortran
spack uninstall --dependents netcdf-c
spack uninstall --dependents hdf5
```
To build the threadsafe version of netCDF:
```
spack install hdf5@1.10.7%gcc@10.2.0 target=x86_64 +cxx+fortran+hl+pic+shared+threadsafe
```
NOTE: Do not put the `target=x86_64` at the end of the command, because Spack might not interpret it properly.  It should go before the list of dependencies.  This is what got me into trouble!!

To force the other libraries to use the hdf5 library we just built, you can use install commands of this format:
```
spack install netcdf-fortran%gcc@10.2.0 target=x86_64 ^hdf5@1.10.7%gcc@10.2.0+cxx+fortran+hl+mpi+pic+shared+threadsafe 
spack install ncview%gcc@10.2.0         target=x86_64 ^hdf5@1.10.7%gcc@10.2.0+cxx+fortran+hl+mpi+pic+shared+threadsafe 
spack install nco%gcc@10.2.0            target=x86_64 ^hdf5@1.10.7%gcc@10.2.0+cxx+fortran+hl+mpi+pic+shared+threadsafe 
```
but it may be easier to get the hash of the hdf5 library and use that in the spack install command:
```
$ spack find -l hdf5

==> 1 installed package
-- linux-centos7-x86_64 / gcc@10.2.0 -----------------------------
d7dxmvv hdf5@1.10.7

spack install netcdf-fortran%gcc@10.2.0 target=x86_64 ^hdf5@1.10.7/d7dxmvv
spack install ncview%gcc@10.2.0         target=x86_64 ^hdf5@1.10.7/d7dxmvv
spack install nco%gcc@10.2.0            target=x86_64 ^hdf5@1.10.7/d7dxmvv
```
Then to be absolutely sure that the cdo build won't try to build new packages, you can force it to use the packages on disk:
```
spack find -l cmake     # returns hash AAAAAAA
spack find -l ncurses   # returns hash BBBBBBB
spack find -l zlib      # returns hash CCCCCCC
spack find -l openmpi   # returns hash DDDDDDD

spack install cdo@1.9.9%gcc@10.2.0 target=x86_64 ^cmake@3.19.0/AAAAAAAA ^ncurses@6.2/BBBBBBBB ^zlib@1.2.11/CCCCCCC ^openmpi@3.1.6/DDDDDDD ^hdf5@1.10.7/d7dxmvv
```
Maybe this is a bit overkill but this worked.  I had a problem with the target=x86_64 being in the wrong place when I did this the first time, so it made a bunch of libraries with `arch=linux-centos7-haswell` instead of `arch=linux-centos7-x86_64`, which is the generic target.  Oh well, lesson learned.

After all this, I can now boot up cdo:
```
[holyjacob01 ~]$ cdo --version
Climate Data Operators version 1.9.9 (https://mpimet.mpg.de/cdo)
System: x86_64-pc-linux-gnu
CXX Compiler: /net/seasasfs02/srv/export/seasasfs02/share_root/ryantosca/spack/lib/spack/env/gcc/g++ -g -O2 -fopenmp -pthread
CXX version : g++ (Spack GCC) 10.2.0
C Compiler: /net/seasasfs02/srv/export/seasasfs02/share_root/ryantosca/spack/lib/spack/env/gcc/gcc -g -O2 -fopenmp -pthread -pthread
C version : gcc (Spack GCC) 10.2.0
F77 Compiler: /net/seasasfs02/srv/export/seasasfs02/share_root/ryantosca/spack/lib/spack/env/gcc/gfortran -g -O2
F77 version : GNU Fortran (Spack GCC) 10.2.0
Features: 251GB 24threads C++14 OpenMP45 Fortran PTHREADS HDF5 NC4/HDF5/threadsafe SZ UDUNITS2 PROJ XML2 FFTW3 SSE2
Libraries: HDF5/1.10.7 proj/5.2.0 xml2/2.9.10
Filetypes: srv ext ieg grb1 grb2 nc1 nc2 nc4 nc4c nc5 
     CDI library version : 1.9.9
 cgribex library version : 1.9.5
 ecCodes library version : 2.18.0
  NetCDF library version : 4.7.4 of Feb 25 2021 11:52:00 $
    hdf5 library version : 1.10.7 threadsafe
    exse library version : 1.4.1
    FILE library version : 1.9.1
```

**Comment by hmhorow** [comment]
thank you so much for these details @yantosca !!

I think some of my students are actively using the existing netCDF installation so I may try the uninstall/reinstall later tonight or over the weekend and will confirm then that it works!

**Comment by yantosca** [comment]
Thanks @hmhorow.  Let me know if it works (when you get to it) and then we can close out this issue.

**Comment by yantosca** [comment]
@hmhorow, @WilliamDowns: I posted the instructions for installing software libraries with Spack in #637.  I tried it on the AWS cloud and it worked (except GDB, the GNU Debugger wouldn't build).  But there is a version of that in most OS builds so you might not need to use the Spack version.

**Comment by hmhorow** [comment]
Apologies for not responding until now. it all worked, thank you so much!!
