### ISSUE TITLE
[BUG/ISSUE] downloading input data with dry run from compute canada with gc 13.0.0-rc - restart file is not found

### ISSUE THREAD

**Issue by hmhorow** [geoschem/geos-chem#628]
Hello!
I followed the wiki instructions for doing a 1-day GEOS-Chem dry run for July 1, 2019 to July 2, 2019 with version 13.0.0-rc. This ran as expected (see below for the log.dryrun output). 

Then, I followed the wiki instructions to download the needed input files specifically from compute canada to my institution's computational cluster (http://wiki.seas.harvard.edu/geos-chem/index.php/Downloading_data_with_the_GEOS-Chem_dry-run_option). 

The restart file does not exist; I get the following error in my slurm error file (full file attached below, dl_data_1day.e1514623):
```
--2021-02-16 13:36:42--  http://geoschemdata.computecanada.ca/ExtData/GEOSCHEM_RESTARTS/v2018-11/initial_GEOSChem_rst.4x5_fullchem.nc
Resolving geoschemdata.computecanada.ca (geoschemdata.computecanada.ca)... 206.12.88.212
Connecting to geoschemdata.computecanada.ca (geoschemdata.computecanada.ca)|206.12.88.212|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-02-16 13:36:43 ERROR 404: Not Found.
```

Note that there are no errors in the GEOS-chem log.dryrun.unique file (attached below); but in reality the GEOSCHEM_RESTARTS folder was never created in ExtData and the restart file is symbolically linked to a location that does not exist.

Should I download a different restart file from the Harvard ftp site instead? I just wanted to let you know in case the restart files on compute canada have been renamed or there is something off with the default dry run settings. 

### Expected behavior: ###
./download_data.py log.dryrun --cc would successfully download all the needed input files. 

### Actual behavior: ###
restart file does not get downloaded

### Steps to reproduce: the bug:

**Compilation commands**
followed steps here exactly: http://wiki.seas.harvard.edu/geos-chem/index.php/Compiling_with_CMake#Building_GEOS-Chem 
only difference, for step 4 referred to my run directory as follows:
`cmake . -DRUNDIR=/projects/horowitz_group/hannah/GEOSChem/rundirs/gc_4x5_fullchem`

and step 6 did `make -j4`

### Error messages

```
--2021-02-16 13:36:42--  http://geoschemdata.computecanada.ca/ExtData/GEOSCHEM_RESTARTS/v2018-11/initial_GEOSChem_rst.4x5_fullchem.nc
Resolving geoschemdata.computecanada.ca (geoschemdata.computecanada.ca)... 206.12.88.212
Connecting to geoschemdata.computecanada.ca (geoschemdata.computecanada.ca)|206.12.88.212|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-02-16 13:36:43 ERROR 404: Not Found.
```

### Your GEOS-Chem version and runtime environment:

 - GEOS-Chem version: 13.0.0
 - Compiler version: gcc 9.3.0
 - netCDF version: 4.7.4
 - netCDF-Fortran version (if applicable): 4.5.3
 - Did you run on a computational cluster, on the AWS cloud: computational cluster at UIUC
   - If you ran on the AWS cloud, please specify the Amazon Machine Image (AMI) ID: __
 - Are you using GEOS-Chem "out of the box" (i.e. unmodified): Yes, unmodified
   - If you have modified GEOS-Chem, please list what was changed: __

### Input and log files to attach

 - lastbuild: __
 - input.geos: [input.geos.txt](https://github.com/geoschem/geos-chem/files/6019099/input.geos.txt)

 - HEMCO_Config.rc: [HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/6019098/HEMCO_Config.rc.txt)

 - GEOS-Chem "Classic" log file:[log.dryrun.txt](https://github.com/geoschem/geos-chem/files/6019074/log.dryrun.txt)
[log.dryrun.unique.txt](https://github.com/geoschem/geos-chem/files/6019075/log.dryrun.unique.txt)

 - HEMCO.log: __
 - slurm.out or any other error messages from your scheduler: [dl_data_1day.e1514623.txt](https://github.com/geoschem/geos-chem/files/6019077/dl_data_1day.e1514623.txt)
 - Any other error messages: __

### Additional context

this is what the compute canada folder looks like that says v2018-11 which is what it is trying to download. it does not contain any files with 'fullchem'. 
http://geoschemdata.computecanada.ca/ExtData/GEOSCHEM_RESTARTS/v2018-11/

however their 13.0.0 restarts directory only contains 1 file:
http://geoschemdata.computecanada.ca/ExtData/GEOSCHEM_RESTARTS/GC_13.0.0/

For now I will plan to manually download a restart file from here: 
http://ftp.as.harvard.edu/gcgrid/data/ExtData/GEOSCHEM_RESTARTS/GC_13.0.0/

Thanks!!

**Comment by yantosca** [comment]
I wonder if this is just because the Compute Canada server was either down for maintenance or just busy.  I would try again.  It seems to be up now (I just checked).

**Comment by angharadstell** [comment]
I'm just starting to use GEOSChem, so have very little idea how everything works, I was just copying the youtube tutorial, and had the exact same issue. It looks for this initial_GEOSChem_rst.4x5_fullchem.nc file that doesn't exist? This doesn't seem to be because the server was down/ busy, it downloaded everything else I was missing, bar these two things (that when I manually look for don't exist):

> Downloading data from ComputeCanada
> --2021-03-01 17:01:12--  http://geoschemdata.computecanada.ca/ExtData/GEOSCHEM_RESTARTS/v2018-11/initial_GEOSChem_rst.4x5_fullchem.nc
> Resolving geoschemdata.computecanada.ca (geoschemdata.computecanada.ca)... 206.12.88.212
> Connecting to geoschemdata.computecanada.ca (geoschemdata.computecanada.ca)|206.12.88.212|:80... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2021-03-01 17:01:13 ERROR 404: Not Found.
> 
> --2021-03-01 17:01:13--  http://geoschemdata.computecanada.ca/ExtData/CHEM_INPUTS/UCX_201403/NoonTime/Grid4x5/InitCFC_
> Resolving geoschemdata.computecanada.ca (geoschemdata.computecanada.ca)... 206.12.88.212
> Connecting to geoschemdata.computecanada.ca (geoschemdata.computecanada.ca)|206.12.88.212|:80... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2021-03-01 17:01:13 ERROR 404: Not Found

I ended up renaming initial_GEOSChem_rst.4x5_standard.nc (which is there) to initial_GEOSChem_rst.4x5_fullchem.nc, and managed to get it to run. I don't know what's going on with InitCFC_, but I managed to get it to run without it.

Would be good to know if this just a missing file issue?

**Comment by hmhorow** [comment]
I also tried downloading data again and got the same errors:


```
--2021-03-07 21:39:25--  http://geoschemdata.computecanada.ca/ExtData/GEOSCHEM_RESTARTS/v2018-11/initial_GEOSChem_rst.4x5_fullchem.nc
Resolving geoschemdata.computecanada.ca (geoschemdata.computecanada.ca)... 206.12.88.212
Connecting to geoschemdata.computecanada.ca (geoschemdata.computecanada.ca)|206.12.88.212|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-03-07 21:39:26 ERROR 404: Not Found.

--2021-03-07 21:39:26--  http://geoschemdata.computecanada.ca/ExtData/CHEM_INPUTS/UCX_201403/NoonTime/Grid4x5/InitCFC_
Resolving geoschemdata.computecanada.ca (geoschemdata.computecanada.ca)... 206.12.88.212
Connecting to geoschemdata.computecanada.ca (geoschemdata.computecanada.ca)|206.12.88.212|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-03-07 21:39:26 ERROR 404: Not Found.
```

As I stated above I ended up manually downloading a restart file from here and renaming it: http://ftp.as.harvard.edu/gcgrid/data/ExtData/GEOSCHEM_RESTARTS/GC_13.0.0/

**Comment by hmhorow** [comment]
Wanted to update that the same error happened to me each time I continue to download data for different GEOS chem configurations (GEOS-FP 4x5; MERRA-2 2x2.5) and different months. I am wondering if it will be fixed in the final version of 13.0.0 vs. the 13.0.0-rc. I am not too concerned but just wanted to update :) Thanks all!

**Comment by yantosca** [comment]
Hi @hmhorow, if you do this:
```console
$ git clone -b dev/13.0.0-final https://github.com/geoschem/GCClassic.git
$ cd GCClassic
$ git submodule update --init --recursive
$ cd run
$ ./createRunDir.sh
```
then answer the prompts to create a run directory of your choice.  Then change to the run directory and do a dry-run.  If the error still persists, let us know and we will fix it (perhaps in a 13.0.1 patch version).

**Comment by yantosca** [comment]
Also my point is that if the dry-run works in the dev/13.0.0-final branch, it will work when we release the 13.0.0 official version.  That's all I wanted you to test for.  Sorry for the confusion.

**Comment by yantosca** [comment]
@hmhorow aso see Issue #653.  There is a needed modification in the download_data.py script that we will make in a 13.0.1 patch version.  In the interim you can download the restart file manually.  Sorry for the confusion!

**Comment by yantosca** [comment]
@hmhorow, @angharadstell, @WilliamDowns: I just submitted Pull Request #661, which fixes these issues with the dry-run.  This will go into our patch version 13.0.1.

I will close out the issue as the PR has now been submitted.
