### ISSUE TITLE
[BUG/ISSUE]: Nf_Def_Var_Deflate: can not compress variable : P0（ Code.12.6.3, merra2_2x25_CO2）

### ISSUE THREAD

**Issue by jinjiuping** [geoschem/geos-chem#634]
Dear:
   when I run the SpeciesConc of CO2 with GEOS-Chem, there have a question about netcdf-fortran, the error infomation as below:

  **Nf_Def_Var_Deflate: can not compress variable : P0**

 How can I avoid this problem?

**Comment by yantosca** [comment]
This has been fixed in commit ab0bb02f12262a2b2b540b88f3143d85bdbee5fe, which is available in the 13.0.0-rc (release-candidate) version.

**Comment by yantosca** [comment]
Long story short, the fix involves changing one line of code in subroutine `NCDEF_VARIABLE` (in `NcdfUtil/m_netcdf_io_define.F90`)

Change
```F90
if (present(Compress)) then
```
to
```F90
if (present(Compress) .and. ndims > 0) then
```

**Comment by jinjiuping** [comment]
Thank you very much, dear @yantosca, I have solve this question with your comment.

**Comment by yantosca** [comment]
Thanks for the update @jinjiuping, glad it works!  I'll close out this issue now.
