### ISSUE TITLE
[FEATURE REQUEST] Add !$OMP COLLAPSE() to optimize parallel loops where necessary

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#639]
This is a generalization of Pull Request https://github.com/geoschem/geos-chem/pull/496 (submitted by @cdholmes).  

Adding the `!$OMP COLLAPSE` directive to fully or partially vectorize parallel loops could potentially result in noticeable speedups.  We can focus on vectorizing parallel loops in routines that take a long time to execute, as identified by the TAU performace profiler.

**Comment by yantosca** [comment]
OMP COLLAPSE is not a silver bullet.  For the right loops, OMP COLLAPSE can improve performance, but under some circumstances it can make things worse.  See:

  1. https://stackoverflow.com/questions/28482833/understanding-the-collapse-clause-in-openmp
  2. https://stackoverflow.com/questions/44118788/fortran-openmp-code-creating-threads-but-do-loops-not-running-in-parallel
  3. https://stackoverflow.com/questions/37958151/loop-sequence-in-openmp-collapse-performance-advise

**Comment by yantosca** [comment]
This is now covered in PR #663, which is slated for 13.1.0.

**Comment by msulprizio** [comment]
This PR has now been merged into the `dev` branch and will be included in 13.1.0.
