### ISSUE TITLE
[QUESTION]The problem of the memory usage when running GEOS-Chem  

### ISSUE THREAD

**Issue by huoxiao-C** [geoschem/geos-chem#640]
Dear:
       I output the netcdf4 file in the geos_chem_mod.F, and close the file. When I run the GEOS-Chem model, the memory usage grows with simulation time. Finally the program crashes until the memory runs out.  The GEOS-Chem version used is 12.6.3. 
      Is there any way to solve this problem？
Thanks very much!

**Comment by yantosca** [comment]
Thanks for writing @huoxiao-C.  I believe in 12.6.x versions, the HISTORY diagnostics had an issue that the maximum amount of memory was allocated to diagnostic arrays (in other words, even if you wanted to only output one species, enough space was allocated for the maximum number of species).  We have resolved this in more recent versions.  We would recommend that you update to the 13.0.0-rc version (and 13.0.-final when it comes out.  This should solve the problem of memory usage.

**Comment by huoxiao-C** [comment]
Thank you for your answer **@yantosca** .

**Comment by yantosca** [comment]
I'll close out this issue for now.  Feel free to open a new issue if you are still having problems.
