### ISSUE TITLE
[QUESTION] Telling GEOS-Chem to use a custom mechanism with GNU make (12.9.3)

### ISSUE THREAD

**Issue by angothelene** [geoschem/geos-chem#641]
Hello,
I'm trying to tell GEOS-Chem v12.9.3 to use a custom mechanism (in /KPP/Custom) but the instructions are only available for CMake (https://kpp.readthedocs.io/en/latest/usage-details/use_custom_mech.html). I only have cmake version 2.8.12.2 so I'd like to use GNU Make instead.
Thanks in advance for your help!

**Comment by yantosca** [comment]
Thanks for writing @angothelene.  GEOS-Chem 13.0.0 will not use GNU Make (due to upstream code that we rely on for GCHP).  If you are using GNU Make with 12.9.3, I believe you can request a custom mechanism with
```
make -j4 ... CHEM=custom
```
Also, you can install a more recent CMake version with Spack.  See issue #637 for instructions.

**Comment by angothelene** [comment]
Hi Bob, thanks for getting back to me so quickly. Okay so turns out I now have cmake/3.14.4.
My issue now is that I don't have a build directory within my run directory (see screenshot).
![Screenshot 2021-03-03 at 15 38 12](https://user-images.githubusercontent.com/25373985/109821647-78b2e400-7c36-11eb-9363-db266201e94f.png)

**Comment by yantosca** [comment]
Thanks @angothelene.  You can just make a directory named `build` in your run directory.  The Unit Tester doesn't create that for 12.9.3 but in 13.0.0, GEOS-Chem Classic run directories will have a `build` directory within them.

**Comment by angothelene** [comment]
Okay, making some progress here.
I created the build directory and typed 'cmake ../CodeDir -DCUSTOMMECH=y'
Note the CMake Warning:  Manually-specified variables were not used by the project:

    CUSTOMMECH

![Screenshot 2021-03-03 at 16 02 43](https://user-images.githubusercontent.com/25373985/109825220-e57bad80-7c39-11eb-8d30-d693da9b319d.png)

**Comment by yantosca** [comment]
Thanks @angothelene for the feedback.  I think the Git version you are using may be prior to 1.8.5, which does not allow for the `git -C` command.  You might need to update to a Git 2.0 or later version.

The Git commands here are just used to get the commit name and description for reference.   @LiamBindle: Do you know if there is a workaround to use Git versions that do not allow the -C argument?

**Comment by angothelene** [comment]
Another try with git/2.21.0.

![Screenshot 2021-03-03 at 17 37 51](https://user-images.githubusercontent.com/25373985/109839212-31811f00-7c47-11eb-92c3-9fa1d73008a5.png)

**Comment by yantosca** [comment]
Ah, with 12.9.3, try `MECH=custom`

**Comment by yantosca** [comment]
Sorry, a lot of things changed between 12.9.3 and 13.0.0.

**Comment by LiamBindle** [comment]
@yantosca Our internal `get_repo_version()` macro takes the working directory as an argument. For example

```cmake
get_repo_version(HCO_GIT_DESCRIBE ${CMAKE_CURRENT_SOURCE_DIR}/HEMCO)
```

Would run `git describe` in `${CMAKE_CURRENT_SOURCE_DIR}/HEMCO)` without using git's `-C` argument. This is facilitated by the WORKING_DIRECTORY keyword argument in `execute_process()` (https://github.com/geoschem/GCClassic/blob/b6f7aff35a42c798e3b7cc94c41aa669c27faccd/CMakeScripts/GC-Helpers.cmake#L122).

Note: If possible, we should try to avoid adding macros to our CMakeLists

**Comment by yantosca** [comment]
@LiamBindle, I'll take a look at the CMakeLists.

@angothelene: Try this workaround:
```
cd Code.12.9.3/KPP
mv standard was.standard
mv custom standard
```
Then go back to your build folder in the run directory and type:
```
cmake ../CodeDir -DMECH=standard
```
That should work.

**Comment by yantosca** [comment]
@angothelene Make sure to use "Standard", not "standard".  I misspelled that above (now fixed).

**Comment by angothelene** [comment]
Yeah, I tried that already. It fails because /KPP/Custom (now /KPP/Standard) does not contain a CMakeLists.txt file. I tried copying this file from was.Standard but then I get: 
CMake Error at KPP/Standard/CMakeLists.txt:12 (add_library):
  Cannot find source file:

    gckpp_Function.F90

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at KPP/Standard/CMakeLists.txt:2 (add_library):
  Cannot find source file:

    gckpp_Precision.F90

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at KPP/Tropchem/CMakeLists.txt:12 (add_library):
  Cannot find source file:

    gckpp_HetRates.F90

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at KPP/SOA_SVPOA/CMakeLists.txt:12 (add_library):
  Cannot find source file:

    gckpp_HetRates.F90

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at KPP/Standard/CMakeLists.txt:12 (add_library):
  No SOURCES given to target: KPP_Standard


CMake Error at KPP/Standard/CMakeLists.txt:2 (add_library):
  No SOURCES given to target: KPPFirstPass_Standard


CMake Error at KPP/Tropchem/CMakeLists.txt:12 (add_library):
  No SOURCES given to target: KPP_Tropchem


CMake Error at KPP/SOA_SVPOA/CMakeLists.txt:12 (add_library):
  No SOURCES given to target: KPP_SOA_SVPOA

**Comment by yantosca** [comment]
@angothelene: Ah, yes.  Copy the gckpp_HetRates.F90, gckpp_Integator.F90, and gckpp_Precison.F90 from was.Standard to Standard.  It needs that code.  Sorry for the omission.

**Comment by angothelene** [comment]
Success! Thanks a lot for your help!

**Comment by yantosca** [comment]
Thanks @angothelene.  This will be more streamlined in 13.0.0, which we will release officially when the benchmarks are approved.
