### ISSUE TITLE
[DISCUSSION] 1-D column simulation under GC Classic framework 

### ISSUE THREAD

**Issue by yc-chan** [geoschem/geos-chem#642]
# 1-D column simulation under GC Classic framework

## Overview
After the implementation of FlexGrid, GEOS-Chem in theory should be grid-independent, and all the modeled emission/ chemistry/ mixing/ deposition processes should operate on 1-D columns. While most users use GC for global 3-D simulations, I am thinking whether the latest versions of GC Classic (GCC) can support simulations of an air column over an arbitrary location in the absence of horizontal transport. This type of 1-D column simulations might be of interest to (1) developers who want to test/ debug their chemistry/ deposition/ emission modules for GCC efficiently and (2) users who want to perform quick experiments to study the influence of localized processes. GC Wiki has an obsolete entry on "[GEOS-Chem column code](http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_column_code)”, and I don't know if anyone has done this type of 1-D simulations under the current GCC framework.   

I am trying to do such a 1-D column simulation using a slightly modified version of GC 12.7.0. The results looked good at first. However, after more investigation, I found that some HEMCO functions may not be compatible with my approach, which lead to several issues in modeled emissions. My attempt and findings are described in detail in the section below. I would love to hear from anyone is interested in this type of 1-D column simulations/ has performed similar tasks using versions of GCC with FlexGrid/ has encountered similar issues during the development of GCHP or WRF-GC. I have no experience with using GCHP. Please let me know if GCHP is actually a better tool for doing 1-D column simulation. 

## My attempt

**(I) Model version and general configurations**: 
- 12.7.0
- Tropchem mechanism
- 4 deg*5 deg horizontal resolution, 47 vertical levels
- Driven by GEOS-FP met fields

 **(II) Essential code modifications**
- In input.geos, change GRID MENU: 
<pre>
`%%% GRID MENU %%%       :
Grid resolution         : 4.0x5.0
Longitude min/max       : 112.5 117.5
Latitude  min/max       : 36.0 40.0
 Half-sized polar boxes?: F
Number of levels        : 47
Nested grid simulation? : F
 Buffer zone (N S E W ) :  0  0  0  0`
</pre>
- In input.geos, set 'Turn on Transport' as F in TRANSPORT MENU
- In GeosCore/input_mode, remove '+1' from the computation of y grid dimension 
<pre>
      State_Grid%NY = FLOOR( ( State_Grid%YMax - State_Grid%YMin ) /
     &                         State_Grid%DY ) ! new
      State_Grid%NY = FLOOR( ( State_Grid%YMax - State_Grid%YMin ) /
     &                         State_Grid%DY ) + 1 ! old
</pre>
- In GeosUtil/gc_grid_mod.F90, remove the code for handling the edges of grid boxes along the north pole and south pole (around line 300 to 320).
- In Headers/state_met_mod.F90, remove the code for deallocating fields of the meteorology state object in SUBROUTINE Cleanup_State_Met. (I am doing this to get rid of an error that terminates GC during the final clean-up stage. There should be a better way to resolve the error.)

**(III) Test simulations**
- Simulation period: Aug 2014
- Control set-up: 4*5 global simulation with no transport; The control set-up should produce results identical to column-mode simulation if everything works perfectly. 

**(IV) Results**

- Simulations for a column over North China. Surface [O3] and [NO] from column-mode simulation seem to be very close to outputs from the control set-up. The result looks good. 
![north-china_column-mode-vs-control](https://user-images.githubusercontent.com/20528005/110010539-40adae80-7cd3-11eb-900f-579ee5ee9b8e.png)
- Simulations for a column over the North Pacific. Surface [O3] and [NO] look quite different this time. 
![pacific_column-mode-vs-control](https://user-images.githubusercontent.com/20528005/110011011-c7fb2200-7cd3-11eb-85d5-3ce9b20a9d24.png)
- After checking various diagnostics, I found that the discrepancy between column mode and control set-up is most likely caused by the difference in modeled emissions. A list of unexpected behaviors of HEMCO during my column-mode simulations:

1. No ship emission. I spent some time looking into the code in PARANOX_MOD. The HcoState%Buffer3D%Val and Inst%ShipNO contain only 0 during column-mode simulation, and I am not able to fix the issue. 
2. Lightning NOx emissions change. The lightning flash rate in column mode and the control setup are different. 
3. Offline emissions (dust, sea salt, soil NOx) are different in column mode.
4. Interestingly, anthropogenic and aircraft emissions in column mode and the control setup are identical, which may explain why the discrepancy for surface [NO] and [O3] is smaller over North China.

**Comment by yantosca** [comment]
Thanks for writing @yc-chan.  In theory you should be able to run GEOS-Chem as a single column but I am not sure if we have ever tried that.  Certainly everything except emissions can be treated of as a collection of columns (or in theory a single column).

Are you using the offline emissions for dust, soil NOx, biogenic VOC's, and lightning?  You might find better consistency between the control & column mode.   Also, have you tried a control simulation with PARANOX off?  

Feel free to attach your input & log files here, as well as any error output.
