### ISSUE TITLE
[BUG/ISSUE]

### ISSUE THREAD

**Issue by pkasibhatla** [geoschem/geos-chem#647]
# Report a GEOS-Chem bug or technical issue

### Steps to reproduce: the bug:

1.  __
2.  __
3.  __

**Run commands**

1.  __
2.  __
3.  __

### Error messages

```
add text here
```

### Your GEOS-Chem version and runtime environment:

 - GEOS-Chem version: __
 - Compiler version: __
 - netCDF version: __
 - netCDF-Fortran version (if applicable): __
 - Did you run on a computational cluster, on the AWS cloud: __
   - If you ran on the AWS cloud, please specify the Amazon Machine Image (AMI) ID: __
 - Are you using GEOS-Chem "out of the box" (i.e. unmodified): __
   - If you have modified GEOS-Chem, please list what was changed: __

### Input and log files to attach

 - lastbuild: __
 - input.geos: __
 - HEMCO_Config.rc: __
 - GEOS-Chem "Classic" log file: __
 - HEMCO.log: __
 - slurm.out or any other error messages from your scheduler: __
 - Any other error messages: __

**Comment by yantosca** [comment]
This issue has been moved to #648
