### ISSUE TITLE
[QUESTION] Does sesquiterpenes convert to SOA ?

### ISSUE THREAD

**Issue by dxy8413** [geoschem/geos-chem#650]
Sesquiterpene is not listed as an SOA precursor in the complex SOA scheme, as shown in the wiki page and overview document (http://maraisresearchgroup.co.uk/Publications/GC-v11-02-SOA-options.pdf). But it seems the model code (v12.7.0, carbon_mod.F) shows sesquiterpene is grouped together with monoterpenes in VBS to form SOA. Could you please verify if the document will be updated or I misunderstood the code? Thanks for the time and help!

Xinyi

**Comment by yantosca** [comment]
Thanks for writing @dxy8413.  I believe that the SOA scheme was updated in the GEOS-Chem 12 series, so that document may no longer be accurate.

**Comment by yantosca** [comment]
There was an update in 12.6.0 to remove isoprene from the VBS.  See here: http://wiki.geos-chem.org/Secondary_organic_aerosols#Removal_of_VBS_isoprene_SOA

**Comment by dxy8413** [comment]
@yantosca thanks a lot for the reply !

To follow up this issue: INDIOL is the aerosol phase product remaining from hydrolysis of organic nitrates, but why it is not included when calculating the total mass of SOA or PM?

**Comment by theloniuspunk** [comment]
Yes, I'm 99% sure sequiterpenes are in there. I don't personally use the complex SOA scheme, but Jared Brewer made this spreadsheet of precursors and yields for Shantanu Jathar recently, and it has the Sesq contribution in there.
[Yield_Terms.xlsx](https://github.com/geoschem/geos-chem/files/6149564/Yield_Terms.xlsx)

**Comment by theloniuspunk** [comment]
Oh, I'm not sure about INDIOL... I only saw the subject of the email that came about sequiterpenes, but I didn't realize the most recent question was about INDIOL.

**Comment by msulprizio** [comment]
I found a commit in the Git history titled [Add more fixes for isoprene SOA: Remove INDIOL from AOD and aerosol mass concentrations](https://github.com/geoschem/geos-chem/commit/caa7b2490885dc01042108bf70bc28b1ad680449). See the message there for details. @jennyfisher and @eamarais may be able to elaborate if there are further questions.

**Comment by dxy8413** [comment]
@msulprizio Thanks a lot for the message ! That's exactly what I was asking. I checked Fisher et al. (2016 ACP) but still not get the specific reason why INDIOL was not included for aerosol mass and AOD.

**Comment by eamarais** [comment]
The INDIOL yields were very high in the Fisher et al. scheme and led to unrealistically high AOD and aerosol mass, so were excluded from these calculations. In answer to your original question in this thread, sesquiterpene SOA in the model are represented with the VBS scheme and isoprene is represented with irreversible uptake in the updated complex scheme in the document that you reference.

**Comment by jennyfisher** [comment]
INDIOL in our version wasn't truly INDIOL, it was just the outcome of all organic nitrate hyrdolysis reactions. So it was unrealistic at that point to include in AOD and aerosol mass. These schemes have probably been updated by now (I think Eloise's scheme or perhaps Kelvin Bates' chemistry may have replaced?). If so, it would be worth checking whether the INDIOL amounts are now reasonable and should be added back into the aerosol diagnostics. But someone would need to confirm that they are realistic...

**Comment by dxy8413** [comment]
@eamarais @jennyfisher Thanks for the very clear and helpful answer, I have no other question, appreciate your time and help!

**Comment by yantosca** [comment]
Thanks @dxy8413.  I can close out this issue now.
