### ISSUE TITLE
[BUG/ISSUE] Problem with CMake

### ISSUE THREAD

**Issue by bakusun** [geoschem/geos-chem#652]
### Expected behavior: ###
cmake should produce an output file as described in Section 3 on this page
http://wiki.seas.harvard.edu/geos-chem/index.php/Compiling_with_CMake#3._Initialize_your_build_directory

### Actual behavior: ###
cmake compilation with GEOS-CHEM 12.9.3 doesn't produce expected cmake output when then trying to use make on top of that nothing happens.
### Steps to reproduce: the bug:
<!--- Include the steps that must be done in order to reproduce the observed behavior:
I downloaded GEOS-CHEM version 12.9.3
I downloaded the Unit-Tester for 12.9.3 to generate a run-directory:
~/GC/rundirs/geosfp_4x5_standard/
the run directory contains:
HEMCO_Diagn.rc
README
input.geos
HEMCO_Config.rc
HISTORY.rc
Makefile*
download_data.py*
getRunInfo*
validate.pl*
OutputDir/
CodeDir -> /vol/sci/astro/home/ithaler/GEOS_CHEM/Code.12.9.3//
species_database.yml
GEOSChem.Restart.20170701_0000z.nc4 -> /vol/sci/astro/home/ithaler/GEOS_CHEM/sdata/gcgrid/data/ExtData/GEOSCHEM_RESTARTS/v2018-11/initial_GEOSChem_rst.4x5_standard.nc

changing to the build directory and typing cmake ../CodeDir
leads to the following output:
GEOS-Chem 12.9.3 (science codebase)
Current status: 
-- Configuring done
-- Generating done
-- Build files have been written to: /vol/sci/astro/home/ithaler/GC/rundirs/geosfp_4x5_standard/build
and ls from the build directory shows:

total 84
-rw-r--r-- 1 ithaler sci 13122 Mar 14 13:09 CMakeCache.txt
-rw-r--r-- 1 ithaler sci  2833 Mar 14 13:09 cmake_install.cmake
-rw-r--r-- 1 ithaler sci  8874 Mar 14 13:21 Makefile
drwxr--r-- 3 ithaler sci  4096 Mar 14 13:21 KPP/
drwxr--r-- 3 ithaler sci  4096 Mar 14 13:21 Headers/
drwxr--r-- 3 ithaler sci  8192 Mar 14 13:21 GeosUtil/
drwxr--r-- 3 ithaler sci  8192 Mar 14 13:21 NcdfUtil/
drwxr--r-- 3 ithaler sci  8192 Mar 14 13:21 History/
drwxr--r-- 3 ithaler sci  8192 Mar 14 13:21 ObsPack/
drwxr--r-- 3 ithaler sci  8192 Mar 14 13:21 APM/
drwxr--r-- 3 ithaler sci  4096 Mar 14 13:21 ISORROPIA/
drwxr--r-- 3 ithaler sci  4096 Mar 14 13:21 GeosRad/
drwxr--r-- 3 ithaler sci  8192 Mar 14 13:21 GTMM/
drwxr--r-- 3 ithaler sci  4096 Mar 14 13:21 GeosCore/
drwxr--r-- 4 ithaler sci  4096 Mar 14 13:21 CMakeFiles/

when then typing 'make' in the same directory nothing happens.

to get to this point I also edited the CMakeLists.txt file. it didn't recognize the get_rep_version
and I added :
project(GEOS_Chem VERSION 12.9.3 LANGUAGES Fortran) (see file attached)

*
### Your GEOS-Chem version and runtime environment:
 -cmake version 3.13.4
 - GEOS-Chem version: unmodified 12.9.3
 - Compiler version:  gfortran 8.3.0
 - netCDF version: netCDF 4.6.2
 - I am running GEOS-CHEM on a cluster
 - the only slight modification of GEOS-CHEM 12.9.3 is a change in the CMakeLists.txt (attached
[input.geos.txt](https://github.com/geoschem/geos-chem/files/6136681/input.geos.txt)
[CMakeLists.txt](https://github.com/geoschem/geos-chem/files/6136682/CMakeLists.txt)

)

**Comment by yantosca** [comment]
Thanks for writing @bakusun.  We would need more information to solve the problem.  Can you attach to this issue the full output of the cmake command?

Also note, we are about to release the GEOS-Chem 13.0.0 official release.  We would recommend that you upgrade to this version once it is available, as there are several new important features and fixes.

**Comment by bakusun** [comment]
[cmake_output.txt](https://github.com/geoschem/geos-chem/files/6154853/cmake_output.txt)
Dear Bob,
thanks for your quick reply, yes maybe I should wait for Geos-Chem 13.0.0!
Please find attached the cmake output from the terminal. That's all I get..
Thanks for your help!

**Comment by yantosca** [comment]
Thanks for writing @bakusun.  The CMake output that you sent says:
```
GEOS-Chem 12.9.3 (science codebase)
```
Because it says "science codebase", this is meant to be used with the GCClassic repository, which has the main CMake build scripts and files.  So what you would need to do to clone the https://github.com/geoschem/GCClassic repository, then follow the instructions listed [here in our GEOS-Chem manual](http://wiki.seas.harvard.edu/geos-chem/index.php/Downloading_GEOS-Chem_source_code).  I would also recommend watching our tutorial video about [Getting Started with GEOS-Chem 13.0.0](https://www.youtube.com/watch?v=BV4BIj8WAxE), which will walk you through the process.

As of this writing (Thu Mar 18 13:33:55 UTC 2021), the "main" branch points to the GEOS-Chem 13.0.0-rc (release-candidate).  We hope to release the official GEOS-Chem 13.0.0 version shortly (within this week).   We would recommend updating to the 13.0.0 official release once it's ready.

**Comment by bakusun** [comment]
Ah ok, great that helps!
Thanks a lot! I was not aware of it!
and yes, I will switch to GEOS-Chem 13.0.0 once its out!

**Comment by yantosca** [comment]
Thanks @bakusun.  We just released the official GEOS-Chem 13.0.0 version on 18 Mar 2021.  Please see our [GEOS-Chem Spring 2021 Newsletter](http://wiki.seas.harvard.edu/geos-chem/images/d/de/GEOS-Chem_Newsletter_Spring_2021.pdf) for the latest information.

I will close out this issue now but please feel free to create other issues if you run into problems with GEOS-Chem.  Thanks!
