### ISSUE TITLE
[FEATURE REQUEST] Provide climatology option for lightning NOx

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#655]
@ltmurray has already provided climatology files for lightning in https://github.com/geoschem/geos-chem/issues/279#issuecomment-646120009. These files are currently available at:

- http://geoschemdata.computecanada.ca/ExtData/HEMCO/OFFLINE_LIGHTNING/v2020-03/MERRA2/CLIM/
- http://geoschemdata.computecanada.ca/ExtData/HEMCO/OFFLINE_LIGHTNING/v2020-03/GEOSFP/CLIM/

Disclaimers from the README files:
>These fields are provided for user convenience when simulating more recent periods than current
lightning availability. However, users should always first check with Lee Murray via e-mail to
lee.murray@rochester.edu or at http://ees.rochestere.edu/atmos/data for the most recent available 
lightning products.
>
>Use of climatological lightning flashes is more appropriate than the use of none. However, lightning is no
longer co-located with active convective transport of HOx-rich surface air, and the photochemical impact
is therefore underestimated. Therefore, time-varying lightning should always be preferred for science
applications.

In [GEOS-Chem 13.2.0](https://github.com/geoschem/geos-chem/milestone/18), we will implement the lightning climatologies as an option in HEMCO_Config.rc, along with climatology options for other emissions.

**Comment by ltmurray** [comment]
I believe so.

**Comment by msulprizio** [comment]
I think we need to leave it open. I have the file from Lee, but need to actually implement it as an easy-to-access option in HEMCO_Config.rc. I'll aim to do this for 14.1.0.

**Comment by msulprizio** [comment]
The pull request (#1628) for this feature has now been merged into the 14.2.0 development branch.
