### ISSUE TITLE
[FEATURE REQUEST] Provide climatology option for biomass burning emissions

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#656]
The GEOS-Chem Steering Committee has requested that we provide climatology options for natural emissions. We have several years of biomass burning emissions via several inventories, so it should be simple to compute a climatology of those emissions and provide that as an option in HEMCO_Config.rc.

**Comment by msulprizio** [comment]
Monthly mean biomass burning emissions for each GFED species have been saved out from a HEMCO standalone simulation for 2007-2019. I still needed to merge files by year and compute the mean for each month across the years. The question that remained was which years to average. Daniel said 10-years would suffice, but [the README in ExtData/HEMCO/GFED4/v2020-02](http://ftp.as.harvard.edu/gcgrid/data/ExtData/HEMCO/GFED4/v2020-02/README) indicates GFED emissions for 2017-2019 are beta. Therefore, I wasn’t sure if we should compute the average for 2007-2016 using the same GFED version or if 2010-2019 would be fine. Finally, for this update, the GFED extension also needs to be modified to include the climatology option (similar to what was done for [the volcano extension](https://github.com/geoschem/geos-chem/issues/833)).

**Comment by djxjacob** [comment]
I think that using 2010-2019 for GFED emissions is fine. If somehow there’s a change in 2017-2019 emissions between beta and final (which I doubt) we can recompute them. It’s important that we use a consistent 10-year period for the different climatologies.  Daniel

**Comment by msulprizio** [comment]
> I think that using 2010-2019 for GFED emissions is fine. If somehow there’s a change in 2017-2019 emissions between beta and final (which I doubt) we can recompute them. It’s important that we use a consistent 10-year period for the different climatologies. Daniel

@djxjacob No problem. I can easily compute the climatology for 2010-2019 instead and will make that update here. We have monthly mean output for 2007-2020 and those are also provided in the shared data directories in case users want to generate the averages for different year ranges.

**Comment by msulprizio** [comment]
The pull request for this feature (#1758) has now been merged into the 14.2.0 development branch.
