### ISSUE TITLE
[FEATURE REQUEST] Tracer species with an offline loss field

### ISSUE THREAD

**Issue by lukewestern** [geoschem/geos-chem#660]
### Request a new GEOS-Chem feature:
A colleague and I are currently running some simulations using an offline loss field for different species. 
We're doing this using the CH4 simulation, replacing the stratospheric loss with our offline loss field, switching off other losses and replacing the molecular weight of methane with the species of interest.

It would be good if there was something with similar functionality of TrasportTracer simulations (adding an arbitrary species) but with the option to also have an offline loss field for that species.

**Comment by yantosca** [comment]
Closing out this issue due to lack of activity
