### ISSUE TITLE
[QUESTION]When will the merra2 meteorology data be updated?

### ISSUE THREAD

**Issue by plutologic** [geoschem/geos-chem#662]
We can only get merra2 meteorology data for August 2020 and before, when will it be updated? Also the GEOS-FP met data, ends at October 2020.

**Comment by msulprizio** [comment]
Where are you trying to access these files? The MERRA-2 and GEOS-FP data for all of 2020 are available on Compute Canada. Please see: http://geoschemdata.computecanada.ca/ExtData/.

**Comment by msulprizio** [comment]
@plutologic Just checking in. Have you been able to obtain the latest met fields from Compute Canada? If so, I will close out this issue.

**Comment by yantosca** [comment]
Thanks @plutologic.  You should be able to download directly from http://geoschemdata.computecanada.ca/ExtData/.  Are you having connectivity issues (or is the website blocked from your location)?

**Comment by plutologic** [comment]
> Thanks @plutologic. You should be able to download directly from http://geoschemdata.computecanada.ca/ExtData/. Are you having connectivity issues (or is the website blocked from your location)?

OK, I get it. Thank you！

**Comment by plutologic** [comment]
> @plutologic Just checking in. Have you been able to obtain the latest met fields from Compute Canada? If so, I will close out this issue.

Yes, Now I can successfully download the met data. Thank you!

**Comment by yantosca** [comment]
@plutologic I will close out this issue for now.  Please let us know if you still have issues.  Thanks!
