### ISSUE TITLE
[BUG/ISSUE] Issue with offline dust emissions -- use online dust until further notice

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#665]
Randall Martin wrote:

>I learned from Jun (@Jun-Meng) that the offline dust emissions currently used in GC are buggy.  Solutions are to 1) fix the error and recreate the emissions to be consistent with v12.5 as planned, or 2) to update the offline emissions to Jun's latest manuscript.
>
> I realize that I have been promoting option 1, but I'm now leaning toward option 2 for two reasons.  The first reason is that Jun has completed an evaluation of the new scheme versus ground-based measurements from a compilation created by Jasper Kok.  The manuscript's conclusions remain unchanged by that addition (I wasn't sure what the outcome would be when we first discussed).  Jun has a draft revised manuscript that should be ready for coauthors this week. It could be shared with you and the Aerosol WG in parallel to expedite consideration as the default offline emissions.  The second reason is that switching to the new emissions would avoid the extra work and confusion of creating an offline emission archive that is likely to be quickly superseded.

**Comment by msulprizio** [comment]
In commit eb97d0b0bd670c4b8fb49a467085085c77bbfd38, `OFFLINE_DUST` is set to false and `DustDead` to on by default. A note has also been added to HEMCO_Config.rc telling users to avoid using offline dust emissions until further notice. This will be included in 13.0.1.

**Comment by sdeastham** [comment]
Is there an update on this issue and/or a timeline for the reactivation of offline dust? [tagging @lizziel ]

**Comment by ChangpeiHe** [comment]
Hi, @msulprizio ! I'd like to know whether the online dust emission scheme was updated according to the scheme described in Meng et al. (a high-resolution dust source function and global annual dust emission strength of 2000 Tg yr−1 rather than 909 Tg yr−1 ) for the current version of GEOS-Chem (e.g., v14.x.x)?

**Comment by msulprizio** [comment]
> Hi, @msulprizio ! I'd like to know whether the online dust emission scheme was updated according to the scheme described in Meng et al. (a high-resolution dust source function and global annual dust emission strength of 2000 Tg yr−1 rather than 909 Tg yr−1 ) for the current version of GEOS-Chem (e.g., v14.x.x)?

Please see the responses in #2604
