### ISSUE TITLE
[FEATURE REQUEST] Force GEOS-Chem Classic restart file to match simulation date

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#667]
The time cycle flags for the species concentration fields (`SPC_`) from the restart files were previously either (`EY` or `CYS`). In the case of `EY`, HEMCO would only read the restart file if the date in the restart file matched the simulation date, but would not crash if the correct date was not found. If GEOS-Chem then couldn't find the field from HEMCO, it would set initial species concentrations to the default background values specified in the species database. In the case of `CYS`, HEMCO would use the restart file for the closest available date. If it couldn't find a restart file then HEMCO would skip that field and GEOS-Chem would default to the background concentrations. In both cases, the user might not be aware of this behavior unless they inspected the GEOS-Chem log file.

To avoid using restart files for the wrong date and/or defaulting to background species concentrations without the user's knowledge, we want to use the `EFY` flag for the SPC_ fields. This tells HEMCO to read the initial species concentrations from the restart file only if the date in the file matches the simulation date. If a restart file is not found, then the simulation will crash. Users can then take it upon themselves to modify the time cycle flag, but they will at least do so knowing how the initial concentrations will be handled by HEMCO.

For some simulations, the sample restart file provided does not include all species in that simulation, so the `EFY` flag will always cause those simulations to crash out-of-the-box. To avoid this, we set the time cycle flag for the `SPC_` entries to `EY` so that HEMCO doesn't crash and GEOS-Chem will default to the background concentrations for any missing species. When users create a run directory for these simulations with`createRunDir.sh`, a warning will print to the screen informing users that some species may be missing and to check their GEOS-Chem log file for details on how initial species concentrations are handled. The simulations that this impacts are: complexSOA_SVPOA, aciduptake, marinePOA, APM, tagCH4, tagO3, and POPs.

**Comment by LiamBindle** [comment]
@msulprizio Could you clarify for me what happens in 13.0.0 if the initial restart file's date doesn't match the simulation date? Are some species initialized to the background concentrations?

**Comment by msulprizio** [comment]
Hi @LiamBindle. In 13.0.0, the species concentrations from the GEOS-Chem restart entries (`SPC_`) in HEMCO_Config.rc use the `CYS` time cycle flag by default. This means that if a restart file for the simulation date is not available at the provided path, HEMCO will continue to look for a restart file and if it finds one it will use the one with the closest available date. If it cannot find a restart file (or a given species within a restart file) then the `S` tells HEMCO to skip the field and GEOS-Chem will then assign the initial species concentration value to the default background concentration specified in the species database.

As of 13.0.1, the default time cycle flag used for species concentrations from the GEOS-Chem restart was changed to `EFY` to force the restart file date to match the simulation date. Note that 13.0.1 was buggy in that the changes associated with this update caused meteorology fields to be read only once at the beginning of the simulation. In 13.0.2 the time cycle flag was further changed for species concentrations from the restart file to `EFYO` so that the exact date is forced and only that field is read once (and the behavior to continuously read meteorology fields is restored). Also note that `EFYO` is the default to force the simulation to crash when the simulation and restart file dates don't match, and this is only done to improve user awareness. Users then have the option of obtaining a restart file for the correct date or changing the time cycle flag in HEMCO_Config.rc back to something like `CYS` to use a restart file for a different date. We always recommend checking the GEOS-Chem log file to see if/how species concentrations are being initialized from the restart file and what values are used.

With all of that said, the above descriptions apply to GEOS-Chem Classic only. For GCHP, the restart file reads are handled by MAPL. In GCHP (specifically in Chem_GridCompMod.F90), it looks like MAPL checks if the restart file exists and if it does not then it uses background species concentration values. That behavior hasn't changed in GCHP. @lizziel feel free to add on if I'm forgetting anything here.

**Comment by LiamBindle** [comment]
Thanks @msulprizio!
