### ISSUE TITLE
[BUG/ISSUE] Typo in species_database.yml?

### ISSUE THREAD

**Issue by angharadstell** [geoschem/geos-chem#672]
### Description of the problem
In geos-chem/run/shared/species_database.yml the entry for N2O5 reads:

N2O5:
  Background_VV: 4.0e-15
  DD_F0: 0.0
  DD_Hstar: 1.0e+14
  Formula: N2O5
  FullName: Dinitrogen pentoxide
  Is_Advected: true
  Is_DryDep: true
  Is_Gas: true
  Is_Photolysis: tr2ue
  MW_g: 108.02

I'm guessing it should be "true" not "tr2ue" for "Is_Photolysis"? Found this by chance and haven't actually experienced any problems because of it, but thought it'd be good to let you know

### GEOS-Chem version
13.0.0

**Comment by yantosca** [comment]
Thanks for catching that @angharadstell.  We can fix this in 13.1.0.  I think that will only cause a problem for diagnostics, since the Is_Photolysis tag is used for wildcarding species in the JValues collection.

**Comment by yantosca** [comment]
@angharadstell: I just pushed a fix for this as commit 7faa40efebe464913f898c7447811a68ddf6c785, in our bugfixes branch.  It will go into the next version (13.1.0).  In the meantime you can either pull the fix from bugfixes or just manually edit that in your code.

**Comment by msulprizio** [comment]
This fix is now also merged into the `dev` branch and will be included in 13.1.0.
