### ISSUE TITLE
[BUG/ISSUE] Negative concentrations

### ISSUE THREAD

**Issue by NatalliaMiatselskaya** [geoschem/geos-chem#675]
### Description of the problem
Dear GCST,
I run GEOS-Chem v.12.1.1 classic, nested Europe, 0.25x0.3125. I have found negative concentrations for some tracers (SO2, NIT...) at 2015/01/09 18:00 and later for a few cells. I have found that negative concentrations appear in vdiff_mod.F90, subroutine vdiff. The negative concentrations appear after the block:
```
!-----------------------------------------------------------------------
! Simple bug fix to ensure mass conservation - Jintai Lin 20180809
!   Without this fix, mass is almost but not completed conserved,
!   which is OK for full chemistry simulations but a big problem
!   for long lived species such as CH4 and CO2
!-----------------------------------------------------------------------
    DO M = 1, pcnst
    do I = 1, plonl

       ! total mass in the PBL (ignoring the v/v -> m/m conversion)
       !   including pre-mixing mass and surface flux (emis+drydep)
       sum_qp0 = sum(qp0(I,ntopfl:plev,M) * &
                 State_Met%AD(I,lat,plev-ntopfl+1:1:-1)) &
               + dqbot(I,M) * State_Met%AD(I,lat,1)

       ! total mass in the PBL (ignoring the v/v -> m/m conversion)
       sum_qp1 = sum(qp1(I,ntopfl:plev,M) * &
                 State_Met%AD(I,lat,plev-ntopfl+1:1:-1))

       IF ( IS_SAFE_DIV( sum_qp0, sum_qp1 ) ) THEN
          qp1(I,ntopfl:plev,M) = qp1(I,ntopfl:plev,M) * &
                                 sum_qp0 / sum_qp1
       ENDIF

    enddo
    ENDDO
```
I can see that negative values of qp1 were put to zero before the DO block:
```
    where (qp1 < 0.e+0_fp)
       qp1 = 0.e+0_fp
    endwhere
```
Is it safe to put negative qp1 to zero after the DO block? 

### Description of troubleshooting performed
Describe any troubleshooting that you have already performed here. Also include any leads or suspicions here.

### GEOS-Chem version
12.1.1

### Description of modifications
Describe your modifications here.

### Log files
- Build log (if applicable):
- Run logs (if applicable):
- Run script (if applicable):

### Software versions
- CMake version:
- Compilers (Intel or GNU, and version):
- NetCDF version:

**Comment by yantosca** [comment]
Thanks @NatalliaMiatselskaya.  You can certainly try that.  Sometimes with the nested-grid simulations, species can go to zero more easily, especially if the initial conditions have not been spun up well.

**Comment by NatalliaMiatselskaya** [comment]
Thank you! I already did that, it works. Otherwise the simulation crashes soon after the negative concentrations appear.

**Comment by msulprizio** [comment]
I will close out this issue for now, as you have found a workaround. If you encounter additional problems, please feel free to open a new issue.
