### ISSUE TITLE
[QUESTION] Subscript #2 of the array ZPJ has value -1 which is less than the lower bound of 1

### ISSUE THREAD

**Issue by danphnis** [geoschem/geos-chem#677]
I was trying to run WRF-GC v2.0 when I meet this problem. Hopefully, I may get some suggestions here, since the HEMCO seems to be relevant to this problem.

In the rsl.error file, it prints:
```
forrtl: severe (408): fort: (3): Subscript #2 of the array ZPJ has value -1 which is less than the lower bound of 1

Image              PC                Routine            Line        Source
wrf.exe            0000000003F83940  Unknown               Unknown  Unknown
wrf.exe            00000000033D0606  hcoi_gc_main_mod_        2253  hcoi_gc_main_mod.F90
wrf.exe            00000000033CAEFE  hcoi_gc_main_mod_         904  hcoi_gc_main_mod.F90
wrf.exe            000000000353DDF8  emissions_mod_mp_         202  emissions_mod.F90
wrf.exe            00000000033A3817  gigc_chunk_mod_mp        1191  gigc_chunk_mod.F90
wrf.exe            000000000174D851  chem_driver_              380  chem_driver.f90
wrf.exe            00000000015FD669  Unknown               Unknown  Unknown
wrf.exe            00000000005B68E7  Unknown               Unknown  Unknown
wrf.exe            000000000040DF41  Unknown               Unknown  Unknown
wrf.exe            000000000040DEFF  Unknown               Unknown  Unknown
wrf.exe            000000000040DE9E  Unknown               Unknown  Unknown
libc-2.17.so       00002B99B73BF555  __libc_start_main     Unknown  Unknown
wrf.exe            000000000040DDA9  Unknown               Unknown  Unknown

```
I also attached the HEMCO.log, HEMCO_Config.rc, input.geos and the namelist.input (input file for WRF-GC settings).
I am grateful for your suggestions and help.
[attachments.zip](https://github.com/geoschem/geos-chem/files/6227483/attachments.zip)

**Comment by lizziel** [comment]
I am pinging @jimmielin on this given it is the application in WRF-GC. This question may be better suited in [HEMCO](https://github.com/geoschem/hemco) or [WRF-GC](https://github.com/jimmielin/wrf-gc-release) on GitHub.

**Comment by yantosca** [comment]
@danphnis @jimmielin There is probably an indexing mismatch in the ZPJ array, which holds the J-values that are computed by FAST_JX.  You may want to check the indexing of your photolysis species and make sure that it is consistent with what you have in the FJX_j2j.dat and FJX_spec.data FAST-JX configuration files.

**Comment by jimmielin** [comment]
Hi there @danphnis,

This issue may be caused because your file path to the FAST-JX input files are not specified correctly in your `input.geos`. Please go to your **WRF-GC run directory** (`/WRFV3/run/`) and check the `input.geos` menu option: `FAST-JX directory` which should point to the correct location, in addition to checking the paths in `HEMCO_Config.rc`.

Thank you!

**Comment by danphnis** [comment]
It seems that I have solved this problem, though I don't know how it works...
First, I set the cu_physics (in namelist.input) to 5. Xu Feng (developer of WRF-GC v2.0) has suggest me just to set it to 0 for the resolution I want.
Second, I close the ship emissions (in HEMCO_Config.rc).

**Comment by yantosca** [comment]
@danphnis There may have been an out of bounds error caused by some of the other settings.   Glad you have this resolved.

**Comment by yantosca** [comment]
@danphnis: Your issue may be related to issue #686.  I am working on a fix for that now.  Stay tuned!!!
