### ISSUE TITLE
[QUESTION] How to geos-chem  apply scale factor to co2 emission?

### ISSUE THREAD

**Issue by huoxiao-C** [geoschem/geos-chem#68]
**Ask your question here**
I am running geos-chem_v12.4.0 with only odiac emission inventory. I have some problems about it.
1.The odiac data is monthly data and there is no scale factor item in the HEMCO_Config.rc file. I want to know how HEMCO  scales monthly odiac data to emission data per emission timestep.
2.In which procedure the odiac emissions were added to the co2 concentration？
3.If I use the adjoint method to solve the optimal emission factor of the model simulation, how can I multiply the optimal emission factor by the emission of the mode grid because the lat/lon(2x2.5_d) of the model simulation is inconsistent with the lat/lon(1x1_d) of the odiac emission?
Thanks!

**Comment by yantosca** [comment]
Thanks for writing.  In answer to your questions:

1. HEMCO reads in the monthly data ODIAC data in kg/m2/s.  Then it converts that to kg per emission timestep by multiplying by the surface area in m2 and the emission timestep in s.

2. For the CO2 simulation, the CO2 from CO production is done in routine EMISSCO2 (in co2_mod.F) and the other emissions are added in do_tend (in mixing_mod.F90).

3. This is a question that the GCST cannot answer, as it is more of a science question.  You can direct this question to the Carbon Cycle Working Group (geos-chem-carbon [at] g.harvard.edu).

**Comment by huoxiao-C** [comment]
Yes , for the third problem, I maybe could fix it through the first problem. Would you please tell me the subroutine location which converts that to kg per emission timestep by multiplying by the surface area in m2 and the emission timestep in s.
Thanks!

**Comment by yantosca** [comment]
I think you would have to look through the HEMCO/Core* routines.  It is not so straightforward.

**Comment by huoxiao-C** [comment]
Sincerely thank you very much!!!!!!

**Comment by yantosca** [comment]
If you run HEMCO with VERBOSE: 3 WARNINGS: 3 you will get output in the HEMCO.log file and that should help you determine where it is converting units.
