### ISSUE TITLE
[QUESTION] GCv13.0.1 Restart Files

### ISSUE THREAD

**Issue by klconferUW** [geoschem/geos-chem#684]
### Ask a question about GEOS-Chem:
Hi, I recently started working with version 13.0.1 and noticed that when I execute ./createRunDir.sh it fails to copy over any restart files to my run directory. Is this a bug or is it customary to now download restart files and adjust the simulation start time? Thanks!

**Comment by yantosca** [comment]
Thanks for writing @klconferUW.  The `./createRunDir.sh` script will copy restart files over from one of these folders:

  1. `ExtData/GEOSCHEM_RESTARTS/GC_13.0.0` (fullchem and TransportTracers)
  2. `ExtData/GEOSCHEM_RESTARTS/v2020-02` (TOMAS)
  3. `ExtData/GEOSCHEM_RESTARTS/v2018-11` (other specialty simulations)

If you are a new user of GEOS-Chem then perhaps these restart files haven't yet been downloaded to your system.  The solution would be to do a dry-run simulation and then use the `download_data.py` script to download the data.  This should pick up any missing restart files.

**Comment by msulprizio** [comment]
If you are still having issues after ensuring you've downloaded the restart files, please let us know what options you selected when executing `./createRunDir.sh` and we can try to reproduce it on our end.

**Comment by klconferUW** [comment]
Hi Melissa and Bob, thank you for your response! I was missing the ExtData/GEOSCHEM_RESTARTS/GC_13.0.0 files and downloading them has solved my issue. 

Just to be clear, the restart file that is copied over is only for one date and can be modified to match my desired simulation time?

**Comment by klconferUW** [comment]
Thank you so much! This will help our entire group now!

**Comment by yantosca** [comment]
BTW @klconferUW, we just released GEOS-Chem 13.0.2 as of 12 Apr 2021.  If it is convenient you should update since it has some important bug fixes.

**Comment by klconferUW** [comment]
Thank you, much appreciated @yantosca!
