### ISSUE TITLE
[QUESTION] offline soil nox/sea salt/bvoc emissions at native meteorological resolution past Sept. 2019? 

### ISSUE THREAD

**Issue by hmhorow** [geoschem/geos-chem#690]
### Ask a question about GEOS-Chem:
I was wondering if there are plans to make offline emissions for soil NOx, Sea salt, and BVOC available past 9/30/2019? I noticed that there are no files past 9/30/2019 on the compute canada or Harvard repositories (e.g., http://geoschemdata.computecanada.ca/ExtData/HEMCO/OFFLINE_SOILNOX/v2019-01/0.5x0.625/2019/10/)

If not, would you recommend for any full-year 2019 simulations running online emissions for these species for the entire year, or is it OK to switch in October to online emissions? 

Thanks so much!
-Hannah

**Comment by yantosca** [comment]
Thanks for writing @hmhorow.  I am tagging @YanshunLi-washu who might know more.

**Comment by YanshunLi-washu** [comment]
Thanks Bob. @yantosca Hi @hmhorow. There are definitely plans making these offline emissions available past 9/30/2019. I will check with developers for the schedule and get back to you ASAP. Besides, these emissions are available at 025x03125 resolution for the whole year of 2019

**Comment by hmhorow** [comment]
Thanks so much @yantosca & @YanshunLi-washu ! I really appreciate it, an approximate schedule would be super helpful. 
good to know that the GEOS-FP offline emissions are available for all of 2019! I hadn't realized that. 
We are planning to use MERRA-2 for most simulations, so I think in order to run with offline emissions for those species + MERRA-2 it requires the 0.5x0.625 files if I understand correctly.

**Comment by YanshunLi-washu** [comment]
@hmhorow No problem! Developers said that these offline emissions at 05x0625 resolution during 2019-10-1 - 2019-12-31 will be available at around the end of April. And emissions for 2020 will be available afterwards. Let me know if there is anything else.

**Comment by hmhorow** [comment]
@YanshunLi-washu thanks so much for the update! that's great to hear. Will let you know if anything else comes up.
