### ISSUE TITLE
[QUESTION] Is GC13.0.0 able to output traceinfo.dat as previous version?

### ISSUE THREAD

**Issue by jinlx** [geoschem/geos-chem#692]
Hi there,

I am trying to convert ND40 output into 'sav' format by using scripts in SEAC4RS-IDL-master. However it needs **tracerinfo.dat** and **diaginfo.dat**. I was wondering if there is a way to output these information in the new version.

**Comment by yantosca** [comment]
Thanks for writing @jinlx.  At the configure stage you need to do

```console
$ cd build
$ cmake ../CodeDir -DBPCH_DIAG=y -DRUNDIR=..
$ make -j
$ make -j install
```
and that will output the *.dat files used with GAMAP.  

NOTE: We have migrated most of our data tools from IDL to Python (as this is free and open source).

**Comment by jinlx** [comment]
Hey Bob! Thanks for the reply! It seems that tracerinfo.dat is not produced even with -DBPCH_DIAG=y option but with getting species_databse.yml instead. Since the overall goal is to convert plane in 'log' into 'sav' format. Do you have any suggestions to realize it in python?

**Comment by jinlx** [comment]
We did make the traceinfo from the GC.log file in the end. I will close the question for now. Thanks again!
