### ISSUE TITLE
[BUG/ISSUE] double precision conflict between Flexchem and HEMCO in 12.5.0

### ISSUE THREAD

**Issue by jingqiumao** [geoschem/geos-chem#696]
### Description of the problem
I am trying to add some HEMCO features in Flexchem. So I added these two lines in flexchem_mod.F90
+    USE HCO_INTERFACE_MOD,    ONLY : HcoState, GetHcoID, GetHcoVal
+    USE HCO_ERROR_MOD  !

Then I got all kinds of compilation errors:

flexchem_mod.F90(244): error #6405: The same named entity from different modules and/or program units cannot be referenced.   [DP]
    REAL(dp)               :: RCNTRL     (                  20               )
---------^
flexchem_mod.F90(244): error #6683: A kind type parameter must be a compile-time constant.
    REAL(dp)               :: RCNTRL     (                  20               )
---------^
flexchem_mod.F90(245): error #6405: The same named entity from different modules and/or program units cannot be referenced.   [DP]
    REAL(dp)               :: RSTATE     (                  20               )
---------^
flexchem_mod.F90(245): error #6683: A kind type parameter must be a compile-time constant.
    REAL(dp)               :: RSTATE     (                  20               )
---------^
flexchem_mod.F90(252): error #6405: The same named entity from different modules and/or program units cannot be referenced.   [DP]
    REAL(dp)               :: GLOB_RCONST(State_Grid%NX,State_Grid%NY, &
---------^
flexchem_mod.F90(252): error #6683: A kind type parameter must be a compile-time constant.
    REAL(dp)               :: GLOB_RCONST(State_Grid%NX,State_Grid%NY, &

It seems that there is a conflict on double precision (dp) defined in flexchem vs. HEMCO.

### Description of troubleshooting performed
I was able to reproduce this error by adding the above two lines to 12.5.0 Tropchem.

### GEOS-Chem version
12.5.0

### Description of modifications
Describe your modifications here.

### Log files
- Build log (if applicable):
- Run logs (if applicable):
- Run script (if applicable):

### Software versions
- CMake version:
- Compilers (Intel or GNU, and version): Intel
- NetCDF version:

**Comment by jingqiumao** [comment]
The problem is "USE HCO_ERROR_MOD". If I remove this line, the model seems fine.

**Comment by jingqiumao** [comment]
Or one should claim "USE HCO_ERROR_MOD" before "USE Precision_Mod".

**Comment by msulprizio** [comment]
Hi @jingqiumao. The issue seems to be that both HEMCO (in hco_error_mod.F90) and KPP (in gckpp_Precision_mod.F90) define a parameter with the name `dp`. 

```
hco_error_mod.F90:76:  INTEGER, PARAMETER, PUBLIC  :: dp = KIND( 0.0_8 )  ! Double (r8)

gckpp_Precision.F90:11:  INTEGER, PARAMETER :: dp = SELECTED_REAL_KIND(14,300)
```

If you can find a workaround that gets past the error for now, I would recommend that. If we eventually need to use hco_error_mod.F90 in flexchem_mod.F90 in the standard code, then we would need to modify HEMCO and/or KPP to use different parameter names.

**Comment by jingqiumao** [comment]
Thanks Melissa. Yes, the workaround is that add "USE HCO_ERROR_MOD" before "USE Precision_Mod". At least the compiler does not complain any more.
