### ISSUE TITLE
[QUESTION] Photocatalytic reaction rate

### ISSUE THREAD

**Issue by lixiao-bit** [geoschem/geos-chem#705]
### Ask a question about GEOS-Chem:
Where could I find documents about the reaction rate of photocatalysis? Where could I see the specific points or calculation methods of ’PHOTOL(1)‘ to ’PHOTOL(161)‘？ 
Thank you.

**Comment by yantosca** [comment]
Thanks for writing @lixiao-bit.  In GEOS-Chem 13.0.0+, the `KPP/fullchem/fullchem.eqn` file shows you all of the reactions corresponding to each slot of the PHOTOL array.  In older versions this would be in e.g. `KPP/Standard/Standard.eqn`, etc (depending on which mechanism you are using.

FAST-JX configuration files (with cross-sections and other such data) are located in one of the subfolders of `ExtData/CHEM_INPUTS/FAST_JX/`.  The folder that is used is specified in the `input.geos` file in your run directory.
