### ISSUE TITLE
[QUESTION] How to create MERRA-2  ‎0.5x0.625 Asia nested-grid run directory from v10-01 Unit Tester

### ISSUE THREAD

**Issue by Basudev777** [geoschem/geos-chem#706]
### Ask a question about GEOS-Chem:
Hii, 
How to create MERRA-2  ‎0.5x0.625 Asia nested-grid run directory from v10-01 Unit Tester? Any suggestions are highly appreciated.

**Comment by yantosca** [comment]
Thanks for writing @Basudev777.

GEOS-Chem v10-01 is no longer supported as it is about 6 years old.  Also, support for MERRA-2 was not added into GEOS-Chem until I think v11-01 or v11-02.  

To use GEOS-Chem with MERRA-2 we recommend that you download the most current version (13.0.2).  Please see our manual page [Getting Started with GEOS-Chem](https://wiki.geos-chem.org/Getting_Started_with_GEOS_Chem) for more information.

**Comment by yantosca** [comment]
Closing this issue.
