### ISSUE TITLE
[QUESTION] How can we save out ground sites data?

### ISSUE THREAD

**Issue by jinlx** [geoschem/geos-chem#707]
Hi there,

Since ND48 and ND49 have been removed since GC12.7.0, I was wodering how we could save out ground sites information in GC13.0.0. There are two potential ways I can think about: 1) using SpeciesConcSubset in History.rc; 2) using obspack in input.geos. But I have trouble realizing it in either way.

For SpeciesConcSubset, it seems that we can't add multiple sites otherwise it will show error below.
````
     - Creating file for SpeciesConcSubset; reference = 20190701 000000
        with filename = OutputDir/GEOSChem.SpeciesConcSubset.hourly_subset.20190701_0000z.nc4
     - Creating file for SpeciesConcSubset; reference = 20190701 000000
        with filename = OutputDir/GEOSChem.SpeciesConcSubset.hourly_subset.20190701_0000z.nc4

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In Nccr_Wr, cannot create:  OutputDir/GEOSChem.SpeciesConcSubset.hourly_subset.20190701_0000z.nc4

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Code stopped from DO_ERR_OUT (in module NcdfUtil/m_do_err_out.F90)

This is an error that was encountered in one of the netCDF I/O modules,
which indicates an error in writing to or reading from a netCDF file!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
````
For obspack, I was wondering if we have any prepared python scrits to generate input files by providing lat and lon.

All suggestions are welcome. Thanks!

**Comment by yantosca** [comment]
Thanks for writing @jinlx.

  1.  You can only specify one set of XRANGE and YRANGE per collection.  If you want to save out more than one subsetted region you would have to specify a new collection for each region.

  2. The ObsPack diagnostic was provided to us as third-party code by Andy Jacobson at NOAA.  It is mostly used with observational data in the NOAA obspack format.  We don't have any python scripts that would save coordinates in this format (as that is beyond the scope of the GCST to provide).  But I would imagine that you could write something pretty quickly using the Python xarray package (define an xarray Dataset with coordinates and then use the `.to_netcdf()` method to save it to file. For more information please see https://xarray.pydata.org.

**Comment by jdhask** [comment]
This topic came up today in our office and I wanted to point out for anyone who is interested in doing this in the future, that I have a python script that can create the ObsPack files you need as input to sample v13 and higher from a plane, from ground sites, or from a plane and a ground site on the same day-  easily. I'm hoping to adapt this to sample a whole network soon, which is fairly straight forward. You can find that code & examples on my GitHub page here (specifically the obspack_io.py file) : [https://github.com/jdhask/gcpy_campaigns](https://github.com/jdhask/gcpy_campaigns)
