### ISSUE TITLE
[BUG/ISSUE] v12.9.3, RRTMG, gfortran: variable tracking size limit exceeded with ‘-fvar-tracking-assignments’, retrying without

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/geos-chem#708]
Hi GCST,

Recently we have updated our gfortran compiler to `GNU Fortran (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0` to overcome our previous reported issue described [here](https://github.com/geoschem/geos-chem/issues/464). However, for v12.9.3 RRTMG simulations, we encountered the following bug during compilation. Google searching indicates that "that is just a note from the compiler that the debug info for the particular function will have lower quality, because your code of function is too large/complex so variable tracking reached limit of hash table slots". However, we still cannot get the executable `geos` even if the code retried compiling without tracking assignments. I am aware that you recommend updating to v13.0.2 to use RRTMG simulations, but we may need rely on v12.9.3 for a while to reproduce some old results. So, I'd be very grateful if you could help me address this issue. Many thanks in advance!

```
rrtmg_lw_k_g.F90:4298:0:

 4298 |       subroutine lw_kgb03
      |
note: variable tracking size limit exceeded with ‘-fvar-tracking-assignments’, retrying without
ar crs librad.a mcica_subcol_gen_lw.o rrsw_cld.o rrlw_kg01.o mcica_random_numbers.o rrsw_wvn.o rrlw_kg09.o mcica_subcol_gen_sw.o rrsw_kg22.o rrlw_tbl.o rrsw_kg28.o rrtmg_sw_setcoef.o rrsw_kg23.o rrlw_cld.o rrtmg_sw_cldprmc.o rrsw_kg29.o rrtmg_lw_init.o parrrsw.o rrtmg_sw_spcvmc.o rrtmg_sw_reftra.o rrlw_kg02.o rrtmg_sw_init.o rrtmg_sw_k_g.o rrlw_kg06.o rrsw_kg18.o rrtmg_lw_k_g.o rrlw_kg04.o rrtmg_lw_taumol.o rrtmg_sw_vrtqdr.o rrsw_kg19.o rrlw_kg12.o rrlw_kg14.o rrsw_kg21.o rrsw_kg27.o rrlw_kg16.o rrsw_kg26.o rrsw_ref.o rrlw_ncpar.o rrsw_con.o rrsw_aer.o rrsw_vsn.o rrlw_kg10.o parkind.o test_arr_mult.o rrlw_con.o rrlw_kg15.o rrlw_kg11.o rrtmg_lw_rtrnmc.o rrtmg_lw_setcoef.o rrsw_kg20.o rrlw_vsn.o rrtmg_sw_taumol.o rrsw_kg25.o rrsw_kg16.o rrlw_kg08.o rrtmg_lw_cldprmc.o rrlw_kg03.o rrsw_kg17.o rrlw_wvn.o rrlw_kg05.o rrlw_kg07.o rrtmg_sw_rad.o rrlw_kg13.o rrlw_ref.o rrsw_tbl.o rrsw_kg24.o rrtmg_lw_rad.o parrrtm.o
ar: mcica_subcol_gen_lw.o: No such file or directory
make[5]: *** [Makefile:98: lib] Error 1
make[5]: Leaving directory '/exports/csce/datastore/geos/users/s1855106/PhD-Edinburgh/GCClassic/Code.12.9.3.original/GeosRad'
make[4]: *** [Makefile:230: librad] Error 2
make[4]: Leaving directory '/exports/csce/datastore/geos/users/s1855106/PhD-Edinburgh/GCClassic/Code.12.9.3.original/GeosCore'
make[3]: *** [Makefile:185: lib] Error 2
make[3]: Leaving directory '/exports/csce/datastore/geos/users/s1855106/PhD-Edinburgh/GCClassic/Code.12.9.3.original/GeosCore'
make[2]: *** [Makefile:142: all] Error 2
make[2]: Leaving directory '/exports/csce/datastore/geos/users/s1855106/PhD-Edinburgh/GCClassic/Code.12.9.3.original/GeosCore'
make[1]: *** [Makefile:49: all] Error 2
make[1]: Leaving directory '/exports/csce/datastore/geos/users/s1855106/PhD-Edinburgh/GCClassic/Code.12.9.3.original'
cp -f ./CodeDir/bin/geos geos
cp: cannot stat './CodeDir/bin/geos': No such file or directory
make: *** [Makefile:335: build] Error 1
```

**Comment by lizziel** [comment]
Hi @FeiYao-Edinburgh, this looks like the same issue discussed in issue https://github.com/geoschem/geos-chem/issues/49.
Building with cmake rather than GNU make should fix the problem.

**Comment by FeiYao-Edinburgh** [comment]
HI @lizziel Thanks! Following your hint and another issue [here](https://github.com/geoschem/geos-chem/issues/483), I have managed to compile GEOS-Chem with with CMake rather than GNU Make with `GNU Fortran (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0`. The only annoying thing is that CMake also complains too much assignments to track, thereby leading to much more time required for compilation. Nonetheless, 
```
[ 76%] Built target KPP_Tropchem
/exports/geos.ed.ac.uk/palmer_group/managed/s1855106/solarenergy/gc.12.9.3/global/test/CodeDir/GeosRad/rrtmg_lw_k_g.F90:4298:0:

 4298 |       subroutine lw_kgb03
      |
note: variable tracking size limit exceeded with ‘-fvar-tracking-assignments’, retrying without
[ 76%] Linking Fortran static library libGeosRad.a
```

**Comment by FeiYao-Edinburgh** [comment]
Hi @lizziel I just wonder may we use something like `-fno-var-tracking-assignments` to avoid retrying and thereby save compilation times?

**Comment by lizziel** [comment]
Hi, @FeiYao-Edinburgh, we have not tried that but indeed it may help. At the very least it would get rid of the notes cluttering the compilation messages. Did you end up trying this, and if yes, what did you find? RRTMG will likely still compile slowly due to the very large arrays hard-coded in some of the files.

**Comment by FeiYao-Edinburgh** [comment]
Hi @lizziel thanks for asking. I later on tried `-fno-var-tracking-assignments` but did not have a luck. So I finally choose to simply wait the slowly compilation. Once I get the `geos` I just copied it here and there for convenient uses. I will keep an eye on this issue.

**Comment by lizziel** [comment]
Okay, thanks for trying. At some point I'd like to reach out to the RRTMG developers about reworking the code to speed up compilation time. Ideally the very large arrays could be read from file. Alternatively perhaps it could be pre-compiled. In the meantime it should just be the initial build that is slow. Recompiling shouldn't trigger a complete recompile unless you change libraries and rebuild from scratch.

I'll close out this issue now.
