### ISSUE TITLE
[BUG/ISSUE]Upside-down of CH4 GFED fields

### ISSUE THREAD

**Issue by Rainbow1994** [geoschem/geos-chem#718]
### Description of the problem
When I tried to extend CH4 GFED fields( ..../HEMCO/CH4/v2020-04/GFED/GFED4_CH4_FIRE_YYYY.nc) using original GFED4 inventories, I found existed CH4-GFED fields in 2017 and 2018 seem upside-down. Could you please check them again? Besides, calculation results between using HEMCO standalone module and applying scaling factors to GFED sub-sector emissions are different. They are also different with existed official CH4-GFED fields. Is there something wrong with my HEMCO_Config.rc (shown below)? or some other reasons?

The same problem is also in Wetland inventories update using WetCHARTS ensemble result. I just averaged the ensemble outputs, but the mean fields are only about 0.6~0.65 times of the existed fields(.../HEMCO/CH4/v2020-04/JPL_WetCharts/*). I wonder if just specific ensemble model results used in calculations, or maybe I need to apply for some scaling factors.

Many thanks in advance!

Best regards,
Rainbow  

### GEOS-Chem version
v12.5.0

**Comment by msulprizio** [comment]
Hi @Rainbow1994. I can confirm that the 2017 and 2018 files in `HEMCO/CH4/v2020-04/GFED/` are flipped latitudinally.

![Screen Shot 2021-05-06 at 1 41 47 PM](https://user-images.githubusercontent.com/4805437/117342267-0ac2ad00-ae71-11eb-8b68-1e4d83139420.png)
![Screen Shot 2021-05-06 at 1 41 36 PM](https://user-images.githubusercontent.com/4805437/117342304-131ae800-ae71-11eb-9e6a-a9bca3b949c7.png)

The files in `HEMCO/CH4/v2020-09/GFED/` seem to be fixed, so I would recommend using those instead. You can just download the new directory if you haven't already and update the file paths in HEMCO_Config.rc. Those files were created by Xiao Lu (Harvard) and the script used to generate them can be found in the same directory (see makegfed.R).

There are also updated JPL WetCharts emissions in `HEMCO/CH4/v2020-09`. You may want to update to those as well. I believe these were created by Xiao Lu or Zhen Qu (both at Harvard) and the scripts used to generate them is also included in the subdirectories. The JPL WetCharts files in v2020-04 were generated by [Yuzong Zhang](https://scholar.harvard.edu/yuzhongzhang), but I do not have the scripts used to create them. If you have questions about those files, I would recommend contacting Yuzhong.

**Comment by Rainbow1994** [comment]
Thanks a lot~

**Comment by msulprizio** [comment]
I am keeping this issue open. I would like to fix the problematic files before considering this resolved.
