### ISSUE TITLE
[BUG/ISSUE] Trouble adding a new diagnostic

### ISSUE THREAD

**Issue by jennyfisher** [geoschem/geos-chem#721]
### Description of the problem
I'm trying to add a new diagnostic for the mercury simulation, using code based on v12.9. I'm getting a seg fault and am uncertain as to why.

### Description of troubleshooting performed
I started by modifying state_diag_mod.F90, copying all lines/segments with `EmisHg0anthro`  and giving them a new diagnostic name (`EmisHg0anthroAU`). No matter what I do, I get the following seg fault:
```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
libifcoremt.so.5   00007F91C36D9522  for__signal_handl     Unknown  Unknown
libpthread-2.28.s  00007F91C1380B20  Unknown               Unknown  Unknown
geos               0000000000A86571  registry_mod_mp_r        1215  registry_mod.F90
geos               0000000000AB6652  state_diag_mod_mp        6811  state_diag_mod.F90
geos               0000000000481EA7  gc_environment_mo         278  gc_environment_mod.F90
geos               0000000000412AAC  MAIN__                    539  main.F90
geos               0000000000403C02  Unknown               Unknown  Unknown
libc-2.28.so       00007F91C0FCE7B3  __libc_start_main     Unknown  Unknown
geos               0000000000403B0E  Unknown               Unknown  Unknown

```

I tried commenting out all the lines that I added except the one that declares the variable:
`     REAL(f4), POINTER :: EmisHg0anthroAU         (:,:  )
`

That didn't help. I thought maybe the diagnostic name was too similar, so I also tried with a name `TestDiag`, but that also didn't help. I always get the same error.

I'd appreciate any guidance on how to add new mercury simulation diagnostics via state_diag! Thanks. :)

### GEOS-Chem version
Modified v12.9.0 (from Viral)

### Description of modifications
See above

### Log files
See above

### Software versions
- Compilers: Intel 2019.5.281
- NetCDF version: 4.7.1

**Comment by yantosca** [comment]
Thanks for writing @jennyfisher.  A couple of things:

1. There is a short description on the wiki with info about how to add new diagnostics:  
    -  http://wiki.geos-chem.org/Adding_new_History_diagnostics#Adding_New_Diagnostics
2. The problem seems to be in registration of the new variable.  Did you update the metadata for the diagnostic (see routine Get_MetaData_State_Diag)
3. Have you tried running in a debugger like gdb?

**Comment by jennyfisher** [comment]
Thanks @yantosca.

Yes - I followed the instructions on the wiki and I included the metadata for the diagnostic in Get_MetaData_State_Diag. I don't know much about debuggers, but running in gdb didn't give any extra information (at least not obviously so).

I did however `make clean` and start again -- this time the error message was a bit different:
```
HISTORY (INIT): Opening ./HISTORY.rc
forrtl: severe (71): integer divide by zero
Image              PC                Routine            Line        Source             
libifcoremt.so.5   00007FE042094555  for__signal_handl     Unknown  Unknown
libpthread-2.28.s  00007FE03FD3BB20  Unknown               Unknown  Unknown
geos               0000000000AFC9E0  dictionary_m_mp_d          82  dictionary_m.F90
geos               0000000000AFE085  dictionary_m_mp_g         236  dictionary_m.F90
geos               0000000000A79868  registry_mod_mp_r         569  registry_mod.F90
geos               0000000000808605  history_mod_mp_hi        2063  history_mod.F90
geos               0000000000804BE2  history_mod_mp_hi        1613  history_mod.F90
geos               0000000000809A91  history_mod_mp_hi         173  history_mod.F90
geos               0000000000412BBC  MAIN__                    710  main.F90
geos               0000000000403C02  Unknown               Unknown  Unknown
libc-2.28.so       00007FE03F9897B3  __libc_start_main     Unknown  Unknown
geos               0000000000403B0E  Unknown               Unknown  Unknown
```

If I comment out the new lines I've added, I do not have this issue.

I've attached my state_diag_mod.F90 (renamed as .txt to allow upload here) -- the diagnostic in question is `EmisHg0AnthroAU`. Can you see anything that would be causing the issue?

(Note that I also tried this renaming the diagnostic to `Testing` with no luck).

Thanks!
Jenny

[state_diag_mod.F90.txt](https://github.com/geoschem/geos-chem/files/6455519/state_diag_mod.F90.txt)

**Comment by jennyfisher** [comment]
How embarrassing, I always tell my students to make realclean and then didn't do it myself!! Yes, that fixed it.

Following up on Bob's last comment -- yes I would be very much in favour of moving the mercury emissions diagnostics to HEMCO diagnostics. I don't see an impediment to this, but maybe @viral211 or @cpthackray who have worked with the mercury code more recently can comment...

I'm actually not sure why the basic Hg0 emissions are still done in mercury_mod.F90, as they are read in via the HEMCO_Config.rc. As far as I can tell, the code in mercury_mod.F90 doesn't actually **do** anything with those emission arrays except write them to the diagnostic -- is that correct?

It's also a little problematic because - as I just learned - it seems that the code in mercury_mod.F90 pulls in the emissions without applying masks (and potentially scaling factors). I added a tracer which is a masked version of the full anthropogenic Hg0 emissions, and the diagnostic written to the HEMCO diagnostics files has applied the mask (so the masked totals are << the full totals), but the version written out from mercury_mod.F90 using the HISTORY.rc diagnostics appears not to have applied the mask (so the masked totals == the full totals).

Curious to hear thoughts from others as to whether the mercury_mod.F90 emissions diagnostics are still needed for some reason?

Thanks!

**Comment by jennyfisher** [comment]
Sorry - on looking at the code a bit more, it looks like the emissions read into mercury_mod.F90 **are** the ones being used elsewhere in the model. So it would require a bit of effort from the software engineering team to move all the Hg emissions to HEMCO. But if feasible, this would still be preferable, as right now there is a bit of a disconnect and keeping everything in HEMCO would certainly streamline things.

**Comment by lizziel** [comment]
Hi all, regarding the retrieval of pointers in HEMCO within mercury_mod.F90, note that they are NOT masked/scaled due to the use of `Hco_GetPtr`. There is an open issue of ongoing work to change use of `Hco_GetPtr` to `Hco_EvalFld` so that mask/scaling in `HEMCO_Config.rc` is actually applied. Files left on the list to complete include the mercury files: see issue https://github.com/geoschem/geos-chem/issues/339. 

It's a bit of work to make the change so we were hoping someone in the Hg community would take it on (@cpthackray?). However, if you could clean up the mercury files so that there is a definitive list of what is needed, what should go through HEMCO, etc and delete or list what can be retired or moved, that would be very helpful. We want to avoid doing any work in the Hg files on diagnostics etc that aren't used. We do still want to get rid of the Hg binary diagnostics as well.

Would it be helpful to start a Hg simulation discussion on GitHub? This could serve as a place for both the Hg community and GCST to discuss the files.

**Comment by viral211** [comment]
Hi all, I've been working with @cpthackray on updating the Hg chemistry and there have been many changes to the Hg diagnostics. The code is almost ready to be included in the standard version and it might be better to apply the HEMCO pointer changes in the updated code or include the changes with the update. I am happy to be the point person for this.

**Comment by yantosca** [comment]
@jennyfisher @lizziel @cpthackray @jimmielin: The Hg emissions were implemented as HEMCO diagnostics I think by Christoph during the early implementation of HEMCO.  Probably for backwards compatibility.  There is no really good reason not to streamline those, but as @lizziel mentioned it would be a bit of work.  

@viral211: Glad to hear that you're working on this!

**Comment by jennyfisher** [comment]
Thanks all. @lizziel I wanted to follow up on your comment that fields retrieved from HEMCO within `mercury_mod.F90` are not masked/scaled. I originally thought this was the case, but then found a bug I'd introduced. It seems from my tests that these ARE being masked.

Here are some details...
In my HEMCO_Config.rc, I have the following lines:
```
0 STREETS_HG0   $ROOT/MERCURY/v2020-07/Streets/Streets2019_Hg.nc Hg0 2000-2015/1/1/0 C xy kg/m2/s Hg0     - 1 1 
0 STREETS_HG0AU -                                                -   -               - -  -       Hg0AU 1010 1 1 
```

So a mask is being applied to my Hg0AU tracer but they are otherwise the same. Both fields are read in `mercury_mod.F90` using `GetHcoDiagn` (the first one was already there, the second one I added):
```
       ! Anthropogenic emissions
       DgnName = 'HG0_ANTHRO'
       CALL GetHcoDiagn( DgnName, .TRUE., RC, Ptr2D=Ptr2D )
       IF ( RC /= HCO_SUCCESS ) THEN 
          ErrMsg = 'Could not get HEMCO field ' // TRIM( DgnName )
          CALL GC_Error( ErrMsg, RC, ThisLoc )
          RETURN
       ENDIF
       EHg0_an =  Ptr2D(:,:) * HcoState%Grid%AREA_M2%Val(:,:)
       Ptr2D   => NULL()

       ! Anthropogenic emissions from Australia
       DgnName = 'HG0AU_ANTHRO'
       CALL GetHcoDiagn( DgnName, .FALSE., RC, Ptr2D=Ptr2D )
       IF ( RC /= HCO_SUCCESS ) THEN 
          ErrMsg = 'Could not get HEMCO field ' // TRIM( DgnName )
          CALL GC_Error( ErrMsg, RC, ThisLoc )
          RETURN
       ENDIF
       EHg0AU_an =  Ptr2D(:,:) * HcoState%Grid%AREA_M2%Val(:,:)
       Ptr2D   => NULL()
```

The code prints the totals of both tracers to the log file:
```
    WRITE( 6, 211   ) SUM( EHg0_an ) * SEC_PER_YR * 1e-6_fp
    WRITE( 6, 212   ) SUM( EHg0AU_an ) * SEC_PER_YR * 1e-6_fp
```

With output:
```
M E R C U R Y   E M I S S I O N S

Total Anthro     Hg(0)  :   1.561 [Gg/yr]
   Australia only       :   0.020 [Gg/yr]
```

So it seems to me like it is applying the mask appropriately (the numbers are about what I'd expect...). Is this because it is using `GetHcoDiagn` rather than `Hco_GetPtr`? Would it still need to be updated to `Hco_EvalFld` for some reason?

Re: other points, I'll follow up at #723.

**Comment by yantosca** [comment]
Thanks @jennyfisher.  I do think the use of Get_HCO_Diagn will pick up the masked values, so that may be what you are seeing.

I think we can close this out and move discussion over to #723.

**Comment by lizziel** [comment]
@jennyfisher, to answer your question about would it need to be updated to `Hco_EvalFld`, it would not. `Hco_EvalFld` is to retrieve HEMCO import variables, i.e. the names that are configured in `HEMCO_Config.rc` as inputs. You are retrieving a HEMCO diagnostic container instead, with name, HEMCO category, etc defined in GEOS-Chem code. The HEMCO diagnostic containers get updated during emissions calculation every time emission is run. That calculation includes the masking and scaling so the diagnostic container values are always correct.
