### ISSUE TITLE
[DISCUSSION] Cleanup Hg diagnostics

### ISSUE THREAD

**Issue by viral211** [geoschem/geos-chem#723]
### Overview
The Hg code uses HEMCO diagnostics to feed emissions to the model, which is inconsistent with the Standard GEOS-Chem simulation and the current code doesn't allow making/scaling of emissions. See #721. Besides, there are Hg chemistry updates in the pipeline, which also involve changes to the Hg diagnostics. 

### Action items
1. Identify the Hg emissions and chemistry diagnostics that should be preserved.
2. Move Hg emissions to HEMCO.
3. Remove Hg bpch diagnostics.

@yantosca, @cpthackray, @jennyfisher, @lizziel, @cpthackray, @jimmielin and others please add action items and thoughts.

**Comment by lizziel** [comment]
**Another action item:** create netcdf diagnostic arrays (i.e. in State_Diag) for any non-emissions diagnostics that are specific to mercury.

There could be a mercury collection in `HISTORY.rc` that is always enabled by default when running the Hg simulation. Once this and the HEMCO emissions diagnostics are complete we can remove the bpch. For RRTMG we had one GEOS-Chem release that contained both netcdf and bpch for validation prior to bpch deletion, and I think that would be good to do for mercury as well.

**Comment by jennyfisher** [comment]
This all sounds good. Adding @cdholmes to the conversation. Does anyone know Yanxu's handle? (Another GC-Hg co-chair).

**Comment by lizziel** [comment]
It is @yanxuz.
