### ISSUE TITLE
[BUG/ISSUE] Question about 13.0.0 netcdf diagnostics for StateMet and Metrics, etc.

### ISSUE THREAD

**Issue by tscarter** [geoschem/geos-chem#726]
With v13.0.0, while the species and HEMCO output looks normal, some of the other diagnostics that are now split off appear to have some issues in their netcdfs, such as Metrics and StateMet. They give such errors as:
 
Error in Rsx_nc4_get_vara_double: NetCDF: Index exceeds dimension bound
Var: time  Ndims: 1   Start: 0 Count: 0
Error in ncvar_get_inner(d$dimvarid$group_id, d$dimvarid$id, default_missval_ncdf4(),  :
  C function R_nc4_get_vara_double returned error

**Comment by tscarter** [comment]
Brief update: I ran a quick simulation with the debug flags on and didn't see any out-of-bounds errors. The run finished normally.

**Comment by yantosca** [comment]
Thanks for writing @tscarter.  Can you attach the input.geos file and HISTORY.rc file to this issue.

Also I noticed this in the output:
```
Var: time Ndims: 1 Start: 0 Count: 0
```
Which suggests that it might be a problem in the time variable. The count attribute should be at least 1 if there is one time point.

**Comment by tscarter** [comment]
Thanks. Yea, it would make sense if it was an issue with the time variable.
I'm attaching the input.geos and HISTORY.rc files.
