### ISSUE TITLE
[BUG/ISSUE] Segmentation error while running as a batch job

### ISSUE THREAD

**Issue by croy64** [geoschem/geos-chem#727]
### Description of the problem
I am trying to run Geos-chem (2x2.5, 47 levels, full chemistry) for 2018. I downloaded the restart file from http://ftp.as.harvard.edu/gcgrid/geos-chem/10yr_benchmarks/13.0.0/GCClassic/restarts/
I am trying to run the model as a batch job, but the model is stopping with segmentation error.
[GC1.log](https://github.com/geoschem/geos-chem/files/6483624/GC1.log)
<img width="976" alt="image" src="https://user-images.githubusercontent.com/78569564/118351760-fc345f80-b51a-11eb-8f4d-6f0bc45ada39.png">

### Description of troubleshooting performed
I tried changing the number of cores and the number of threads, but nothing seems to work.
### GEOS-Chem version
GEOS-Chem 13.0.0 (GCClassic)
### Description of modifications
Describe your modifications here.

### Log files
- Build log (if applicable):
- Run logs (if applicable): Attached
```
HEMCO: Opening /home/cccr/chaitri/geoschem_cr/ExtData/HEMCO/OFFLINE_LIGHTNING/v2020-03/MERRA2/2018/FLASH_CTH_MERRA2_0.5x0.625_2018_01.nc4
HEMCO: Opening ./GEOSChem.Restart.20180101_0000z.nc4
Application 171040022 exit codes: 174
Application 171040022 resources: utime ~89s, stime ~177s, Rss ~15990040, inblocks ~0, outblocks ~344
```
- Error file:
```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
gcclassic          0000000000C138C4  Unknown               Unknown  Unknown
libpthread-2.22.s  00002AAAABB8AB20  Unknown               Unknown  Unknown
libiomp5.so        00002AAAAB8CC940  Unknown               Unknown  Unknown
libiomp5.so        00002AAAAB8CF22C  Unknown               Unknown  Unknown
gcclassic          0000000000C45785  Unknown               Unknown  Unknown
gcclassic          00000000009912FB  hco_interp_mod_mp         439  hco_interp_mod.F90
gcclassic          000000000098161E  hcoio_read_std_mo        1295  hcoio_read_std_mod.F90
gcclassic          000000000097D565  hcoio_dataread_mo         250  hcoio_dataread_mod.F90
gcclassic          000000000096F803  hco_readlist_mod_         500  hco_readlist_mod.F90
gcclassic          000000000096F149  hco_readlist_mod_         368  hco_readlist_mod.F90
gcclassic          0000000000952923  hco_driver_mod_mp         155  hco_driver_mod.F90
gcclassic          00000000004AECD2  hco_interface_gc_         849  hco_interface_gc_mod.F90
gcclassic          00000000004559CB  emissions_mod_mp_         202  emissions_mod.F90
gcclassic          000000000040E2E6  MAIN__                    753  main.F90
gcclassic          000000000040DE0E  Unknown               Unknown  Unknown
libc-2.22.so       00002AAAABDB76D5  __libc_start_main     Unknown  Unknown
gcclassic          000000000040DD29  Unknown               Unknown  Unknown
```

### Software versions
- CMake version: 3.5.2
- Compilers (Intel or GNU, and version): intel/19.0.1.144
- NetCDF version: cray-netcdf/4.4.1.1.3

**Comment by lizziel** [comment]
Hi @croy64, there is a second log file called`HEMCO.log` that may have additional information on the error. You can attach it by changing the extension to `.txt` and dragging it into the commend box here on GitHub. Alternatively please copy in any error messages that you see. If there are any they are likely at the very end of the log file.

**Comment by yantosca** [comment]
Thanks for writing @croy64.  One thing I noticed, you are requesting 64 cores but you have `export OMP_NUM_THREADS=1` in your script.  I wonder if your job does not have enough memory to proceed.  Make sure that you are submitting to computational queue that has enough memory for the job.

**Comment by croy64** [comment]
> Hi @croy64, there is a second log file called`HEMCO.log` that may have additional information on the error. You can attach it by changing the extension to `.txt` and dragging it into the command box here on GitHub. Alternatively please copy in any error messages that you see. If there are any they are likely at the very end of the log file.

The error looks like this:
HEMCO WARNING: Data is treated as unitless, but file attribute suggests it is not: kg m-2 s-1. File: /home/cccr/chaitri/geoschem_cr/ExtData/GEOS_2x2.5/MERRA2/2018/01/MERRA2.20180101.A3mstE.2x25.nc4
--> LOCATION: HCOIO_READ_STD (hcoio_read_std_mod.F90)
HEMCO WARNING: Data is treated as unitless, but file attribute suggests it is not: kg m-2 s-1. File: /home/cccr/chaitri/geoschem_cr/ExtData/GEOS_2x2.5/MERRA2/2018/01/MERRA2.20180101.A3mstE.2x25.nc4
--> LOCATION: HCOIO_READ_STD (hcoio_read_std_mod.F90)
HEMCO WARNING: Data is treated as unitless, but file attribute suggests it is not: kg m-2 s-1. File: /home/cccr/chaitri/geoschem_cr/ExtData/GEOS_2x2.5/MERRA2/2018/01/MERRA2.20180101.A3mstE.2x25.nc4
--> LOCATION: HCOIO_READ_STD (hcoio_read_std_mod.F90)
HEMCO WARNING: Data is treated as unitless, but file attribute suggests it is not: kg m-2 s-1. File: /home/cccr/chaitri/geoschem_cr/ExtData/GEOS_2x2.5/MERRA2/2018/01/MERRA2.20180101.A3mstE.2x25.nc4
--> LOCATION: HCOIO_READ_STD (hcoio_read_std_mod.F90)
HEMCO WARNING: Data is treated as unitless, but file attribute suggests it is not: kg kg-1. File: /home/cccr/chaitri/geoschem_cr/ExtData/GEOS_2x2.5/MERRA2/2018/01/MERRA2.20180101.I3.2x25.nc4
--> LOCATION: HCOIO_READ_STD (hcoio_read_std_mod.F90)
HEMCO WARNING: Data is treated as unitless, but file attribute suggests it is not: kg kg-1. File: /home/cccr/chaitri/geoschem_cr/ExtData/GEOS_2x2.5/MERRA2/2018/01/MERRA2.20180102.I3.2x25.nc4
--> LOCATION: HCOIO_READ_STD (hcoio_read_std_mod.F90)
HEMCO WARNING: Data is treated as unitless, but file attribute suggests it is not: km-2 s-1. File: /home/cccr/chaitri/geoschem_cr/ExtData/HEMCO/OFFLINE_LIGHTNING/v2020-03/MERRA2/2018/FLASH_CTH_MERRA2_0.5x0.625_2018_01.nc4
--> LOCATION: HCOIO_READ_STD (hcoio_read_std_mod.F90)
HEMCO WARNING: Data is treated as unitless, but file attribute suggests it is not: g kg-1. File: ./GEOSChem.Restart.20180101_0000z.nc4
--> LOCATION: HCOIO_READ_STD (hcoio_read_std_mod.F90)
HEMCO WARNING: Data is treated as unitless, but file attribute suggests it is not: molec cm-2 s-1. File: ./GEOSChem.Restart.20180101_0000z.nc4
--> LOCATION: HCOIO_READ_STD (hcoio_read_std_mod.F90)
HEMCO WARNING: Data is treated as unitless, but file attribute suggests it is not: molec cm-2 s-1. File: ./GEOSChem.Restart.20180101_0000z.nc4
--> LOCATION: HCOIO_READ_STD (hcoio_read_std_mod.F90)
HEMCO WARNING: Data is treated as unitless, but file attribute suggests it is not: mol mol-1. File: ./GEOSChem.Restart.20180101_0000z.nc4
--> LOCATION: HCOIO_READ_STD (hcoio_read_std_mod.F90)
HEMCO WARNING: Data is treated as unitless, but file attribute suggests it is not: mol mol-1. File: ./GEOSChem.Restart.20180101_0000z.nc4
--> LOCATION: HCOIO_READ_STD (hcoio_read_std_mod.F90)

**Comment by croy64** [comment]
> Thanks for writing @croy64. One thing I noticed, you are requesting 64 cores but you have `export OMP_NUM_THREADS=1` in your script. I wonder if your job does not have enough memory to proceed. Make sure that you are submitting to computational queue that has enough memory for the job.


I made the following changes:

#!/bin/bash
#PBS -q cccr
#PBS -N GC13_cr
#PBS -l select=1:ncpus=36:vntype=cray_compute
#PBS -l walltime=500:00:00
##PBS -l nodes=1:ppn=36
#PBS -l place=scatter
##PBS -j oe


set -eu

cd $PBS_O_WORKDIR
echo $PBS_O_WORKDIR

echo "mother superior: $(uname -n)"
NSLOTS=$(cat $PBS_NODEFILE | wc -l)
echo "running on $NSLOTS cpus ..."
export OMP_STACKSIZE=500m
ulimit -s unlimited
ulimit -a
export OMP_NUM_THREADS=16
#-----------------------------------------------------------------------------
# Env Variables:

MPIPROGINF='DETAIL'                   # program information about speed, vectorization
export MPIPROGINF                     # {NO|YES|DETAIL}
#
MPISUSPEND='ON'                       # select waiting method
export MPISUSPEND                     # {ON|OFF}={SUSPEND/RESUME|SPIN WAIT}
#
F_FTRACE='NO'                         # analysis list from compile option -ftrace
export F_FTRACE                       # {NO|YES|FMT0|FMT1|FMT2}
#
F_ERRCNT=0                            # stop execution after the first run time error
export F_ERRCNT

LD_LIBRARY_PATH="/opt/intel/Compiler/11.0/074/lib/intel64:/opt/cray/pe/netcdf/4.4.1.1.3/INTEL/16.0/lib:/opt/cray/pe/hdf5/1.10.0.3/INTEL/16.0/lib:/home/apps/YAXT/0.5.1/INTEL/17.0.5/yaxt/lib:/home/apps/szip/2.1/intel/17.0.5/SZIP/lib:/home/apps/hdf5/1.10.1/intel/17.0.5/HDF5/lib:/opt/cray/pe/lib64:/opt/cray/pe/mpt/7.6.3/gni/mpich-intel/160/lib:/opt/cray/pe/netcdf/4.4.1.1.3/INTEL/16.0/lib:/opt/cray/pe/hdf5/1.10.0.3/INTEL/16.0/lib:/home/apps/YAXT/0.5.1/INTEL/17.0.5/yaxt/lib:/home/apps/szip/2.1/intel/17.0.5/SZIP/lib:/home/apps/hdf5/1.10.1/intel/17.0.5/HDF5/lib:/opt/cray/pe/lib64:/opt/cray/pe/mpt/7.6.3/gni/mpich-intel/160/lib:/opt/cray/job/2.2.2-6.0.4.0_8.2__g3c644b5.ari/lib64:/opt/intel/compilers_and_libraries_2017.5.239/linux/compiler/lib/intel64:/opt/intel/compilers_and_libraries_2017.5.239/linux/compiler/lib/intel64_lin:/opt/intel/compilers_and_libraries_2017.5.239/linux/mpi/intel64/lib:/opt/intel/compilers_and_libraries_2017.5.239/linux/mpi/mic/lib:/opt/intel/compilers_and_libraries_2017.5.239/linux/ipp/lib/intel64:/opt/intel/compilers_and_libraries_2017.5.239/linux/compiler/lib/intel64_lin:/opt/intel/compilers_and_libraries_2017.5.239/linux/mkl/lib/intel64_lin:/opt/intel/compilers_and_libraries_2017.5.239/linux/tbb/lib/intel64/gcc4.7:/opt/intel/debugger_2017/iga/lib:/opt/intel/debugger_2017/libipt/intel64/lib:/opt/intel/compilers_and_libraries_2017.5.239/linux/daal/lib/intel64_lin"; export LD_LIBRARY_PATH

#----------------------------------------------------------------------------------------
#--- Start the run:

cd /home/cccr/chaitri/geoschem_cr/gc_2x25_new

#aprun -n 1 -N 1 ./gcclassic --dryrun > log.dryrun
aprun -n 1 -d 16 ./gcclassic > GC1.log

**Comment by yantosca** [comment]
Thanks @croy64.  One thing I don't see is a command to request an amount of memory.  I'm not sure if that is done for you by submitting to the `cccr` queue.  A quick google search of the `aprun` command says that the default amount of memory is 16 MB.  IF the memory is not set for you in the queue you will need to manually request enough memory for the run.  If this is a nested-grid run you might need at least 30GB of memory.

**Comment by croy64** [comment]
> Thanks @croy64. One thing I don't see is a command to request an amount of memory. I'm not sure if that is done for you by submitting to the `cccr` queue. A quick google search of the `aprun` command says that the default amount of memory is 16 MB. IF the memory is not set for you in the queue you will need to manually request enough memory for the run. If this is a nested-grid run you might need at least 30GB of memory.

Thank you @yantosca
The default memory allocated is 128gb per node.

**Comment by lizziel** [comment]
@croy64, I wonder if you need to do `-n 16 -N 16` instead. I think the `aprun` command defines `-n` as number of tasks and `-N` as number of tasks per node.

**Comment by yantosca** [comment]
@croy64, were you able to resolve this issue?  Just checking in.

**Comment by croy64** [comment]
@yantosca, Thank you for checking in. I was running the model with 47 levels. So, when I used a restart file with 47 levels instead of 72, it worked!
