### ISSUE TITLE
[QUESTION] Do I need to make 47L data files for HEMCO?

### ISSUE THREAD

**Issue by ymfu2021** [geoschem/geos-chem#730]

**Comment by yantosca** [comment]
I'm using standard GEOS-Chem 12.1.0, and I wanna add few new files through HEMCO.Config.rc. I'd like to know if I need to make variables which are all 72 vertical layer grid in those new files collapse to a 47-layer grid by myself before adding them into GEOS-Chem model, or they'll be collapsed to 47-layer grid automatically by certain codes of GEOS-Chem

**Comment by yantosca** [comment]
Thanks for writing @ymfu2021.  HEMCO will be able to regrid data that is at 72L down to 47L, so you should not have to create new files.

**Comment by ymfu2021** [comment]
Thanks for answering my questions!

**Comment by yantosca** [comment]
You are welcome @ymfu2021.  I'll close out this issue for now.
