### ISSUE TITLE
[DISCUSSION] Chemistry mechanism directory tree

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#731]
### Overview
Very soon we will have multiple KPP-based chemical mechanisms in GEOS-Chem.  Furthermore, we may in the near future also have KPP as a GEOS-Chem submodule (so that KPP will be built and run on the .eqn and gckpp.kpp file every GEOS-Chem is compiled).

Right now we have the following KPP directory structure, where the KPP-generated F90 files are stored:
```
src/GEOS-Chem/
     |--> KPP  (contains build_mechanism.sh)
          |
          |--> fullchem (fullchem.eqn, gckpp.kpp + generated F90 code)
          |--> custom  (custom.eqn, gckpp.kpp)     
``` 
But a lot of the prep for the chemical mechanism is done in flexchem_mod.F90, which is in GeosCore.  Right now we only have one fullchem mechanism, so it is OK, but it might get messy if we try to add code for the other mechanisms in there.

One potential solution would be to have a copy of flexchem_mod.F90 (appropriately named) in each of the chemistry mechanism folders (e.g. fullchem, custom, etc).  Then this could set up the inputs that get passed to KPP.

Also I would propose renaming the KPP top-level folder to "Mechanisms", to avoid confusion with KPP.  Then the KPP-for-GEOS-Chem code could be a sub-folder of Mechanisms.  For example:

```
src/GEOS-Chem/
     |--> Mechanisms  
          |
          |--> KPP (contains KPP source code)
          |--> fullchem
          |--> Hg
          |--> CO-CO2-CH4-OCS
          |--> Superfast (i.e. Makoto Kelp's code)
          |--> Adaptive (i.e. Lu Shen's code)         
          |--> custom    
``` 
or something like this.  The Mechanisms folder could even be a subfolder of a `Chemistry` folder,  which could contain other chemistry components, 

Thoughts? @msl3v @msulprizio @lizziel @WilliamDowns @LiamBindle @YanshunLi-washu @sdeastham @tsherwen

**Comment by msulprizio** [comment]
As discussed in https://github.com/geoschem/geos-chem/issues/654, @kbowman77 and other steering committee members have requested that we still allow for separate carbon species simulations, not just the joint CO-CO2-CH4-OCS simulation. This is just something to keep in mind as we develop that mechanism - do we want it to be a single mechanism or multiple mechanisms that can each be selected? 

Along those lines, Mat Evans had explored in the past the possibility of breaking up the full-chemistry mechanism into components (e.g. having separate .eqn files for halogens, hydrocarbons, etc). I'm not sure if that is in the scope of the updates planned but, again, just something to keep in mind.

**Comment by yantosca** [comment]
@msulprizio at present, I don't think it is in the scope of this project to split up the equations by species type, although that is probably a good idea.

For the CO-CO2-CH4-OCS simulation I could try to implement each separately and then have a combined mechanism that uses `#include` statments.   Worth a shot.
