### ISSUE TITLE
[BUG/ISSUE] CO2 tagged simulations

### ISSUE THREAD

**Issue by monszel** [geoschem/geos-chem#734]
Hello,
I am currently running tagged CO2 simulations using GC13.0.2. Considering the restart files, I have switched from EFYO to CYS as  a restart file that does not contain all the species , i.e.,

`* SPC_           ./GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 SpeciesRst_?ALL?    $YYYY/$MM/$DD/$HH CYS  xyz 1 * - 1 1`

However, the run crashes after a lots of warnings about negative concentrations:

```
WARNING: Negative concentration for species CO2oc at (I,J,L) =
WARNING: Negative concentration for species CO2ff at (I,J,L) =
...
...
```

I have checked that species not found in the restart file  are initialised with the default background concentrations Background_VV = 1e-20. 

The run passes with  the increased initial background or small change in  **mixing_mod.F90**. I substituted following lines:
```
             ! Check for negative concentrations
             ! KLUDGE: skip the warning message for CH4_SAB, which can be
             ! negative (it's a soil absorption flux).  The TagCH4 simulation
             ! is not used regularly as of Feb 2021 -- fix this later if
             ! need by. (bmy, 2/25/21)
             IF ( State_Chm%Species(I,J,L,N) < 0.0_fp ) THEN
                IF ( N /= id_CH4_SAB ) THEN
                 Print*, 'WARNING: Negative concentration for species ',     &
                          TRIM( SpcInfo%Name), ' at (I,J,L) = ', I, J, L
                 ErrorMsg = 'Negative species concentations encountered.' // &
                            ' This may be fixed by increasing the'        // &
                            ' background concentration or by shortening'  // &
                            ' the transport time step.'
                 RC = GC_FAILURE
                ENDIF
             ENDIF
```

with
             ` State_Chm%Species(I,J,L,N) = MAX(State_Chm%Species(I,J,L,N),0.0_fp)`

Did anyone experience similar issues or am I doing something wrong here?

Also, very small thing, but it took me some time to figure it out. When  CO2 run is created, HEMCO_Config is missing one line:
`DiagnFile:                   HEMCO_Diagn.rc`
Without it HEMCO_diagnostic files are empty.

### GEOS-Chem version
13.0.2
### Software versions
- CMake version: 3.16.3
- Compilers (Intel or GNU, and version): intel/19.0.4
- NetCDF version: netcdf-fortran/4.4.4,  netcdf/4.7.0

**Comment by yantosca** [comment]
Thanks @monszel for writing.  I wonder if because the tagged CO2 species default background concentrations are very small, this might be leading to negative values when they get passed through the chemistry.  You might try changing the default background concentrations for the tagged CO2 species to something not so small.  In the species_database.yml file in your run directory look for the lines:

```yaml
CO2:
  << : *CO2properties
  Background_VV: 3.55e-4
  FullName: Carbon dioxide
CO2av:
  << : *CO2properties
  Background_VV: 1.0e-20
  FullName: Carbon dioxide from aviation emissions
CO2bal:
  << : *CO2properties
  Background_VV: 1.0e-20
  FullName: Carbon dioxide from balanced biosphere
... etc...
```
and then change the Background_VV settings to a number more like the background concentration for the total CO2 species (i.e. 3.55e-4).  Then rerun again and see if that prevents the negatives.  You'll want to make sure to spinup for a long time (several years) since CO2 is such a long-lived species.

**Comment by yantosca** [comment]
Also @monszel, if you find a better Background_VV value for the tagged species that we should be using, we can add it into the species_database.yml file that ships with GEOS-Chem.  Let us know.  We don't typically run the CO2 simulation (other than in integration testing) so we aren't always aware of issues such as this.

**Comment by monszel** [comment]
Hi,
thank you for the answer! As I remember correctly I think I used 3.55e-4 for all tagged species but I only did short test to check if the run does not crash after that. Later on, I kept the default values and  changed  
`IF ( State_Chm%Species(I,J,L,N) < 0.0_fp ) THEN {...}` 
to 
`State_Chm%Species(I,J,L,N) = MAX(State_Chm%Species(I,J,L,N),0.0_fp)` 
in **mixing_mod.F90** for that run and it went smoothly (10 years spinup + 4 years production run). But I will have a look at it yet.

**Comment by yantosca** [comment]
Thanks @monzel.  That might be a good fix to add going forward.  We can look into this.

**Comment by kimm1na** [comment]
@monszel 

Hello,

Do you mean that there was no problem when you left the background value as it is (1e-20) 
and modified only mixing_mod.F90?

Thank you.

**Comment by monszel** [comment]
Hi @kimm1na,
yes, I only modified the mixing_mod.F90. However, it works also with increased background values and without code modifications.

Regards
Monika
