### ISSUE TITLE
[QUESTION]how can I get the specific pressure data used in GEOSFP

### ISSUE THREAD

**Issue by ymfu2021** [geoschem/geos-chem#735]
### Ask a question about GEOS-Chem:
I'm learning to run the GEOS-Chem 12.1.0 standard model, using GEOS_FP(4x5) . When I viewed code 'mercury_mod.F', I found some functions such as 'GET_HGBRY_RATE' use thepressure data by the statement:

 P = State_Met%PMID_DRY(I,J,L)'.

then P was used to caculate some other constants and react rates. however, I didn't find such a variable named 'PMIDDRY' in nc files of GEOS_FP. I'd like to know where and how can I get the pressure data. 
In this webpage:  http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_vertical_grids   ,I found some information about 'Pressures and altitudes for a column at atmospheric sea level, from surface upwards', are they the pressure used in GEOS-Chem?

Thanks.

**Comment by ymfu2021** [comment]
Thanks so much!
After checking my HISTORY.rc file, I find that the '#' character in front of 'StateMet' hasn't been removed, so that related file hasn't been output. 
Now if I wanna get this StateMet, is there a faster way than reruning the GEOS-Chem while adding '#' to any other collection?

**Comment by yantosca** [comment]
You can run GEOS-Chem and turn off chemistry, emissions, drydep, transport, PBL, and convection.  This will run and just save out the diagnostics.

**Comment by ymfu2021** [comment]
Get it, Thanks for anwsering my question~

**Comment by ymfu2021** [comment]
@yantosca I have another question, Does the 'StateMet' output stay its value no matter what has been changed inside the GEOS-Chem ? Such as changing 'chemistry' from 'on' to 'off ',like we discussed earlier.

**Comment by yantosca** [comment]
@ymf2021, thanks for writing.  The State_Met output (i.e. Met_DELPDRY, Met_BXHEIGHT) are independent of GEOS-Chem operations (i.e. turning chemistry from on to off).  

CAVEAT: I believe turning off advection in GEOS-Chem Classic will result in slightly different pressures --- if advection is turned off then the pressure-fixer is not applied.  But that will be a small difference if you are averaging over e.g. a monthly period.

**Comment by yantosca** [comment]
I will close out this issue now.  Please feel free to open a new issue if you are still having problems.
