### ISSUE TITLE
[BUG/ISSUE] koh calculation and GCARR function in gckpp.kpp

### ISSUE THREAD

**Issue by jinlx** [geoschem/geos-chem#736]
Hi there, 

I am looking at the rate constant calcualtion in GCv13. It seems that GC calcuates rate constant by using GCARR fucntion as shown below. 

```
REAL(kind=dp) FUNCTION GCARR( A0,B0,C0 )
       REAL A0,B0,C0
       GCARR =  DBLE(A0) * EXP(DBLE(C0)/TEMP) * (300._dp/TEMP)**DBLE(B0)  END FUNCTION GCARR    
END FUNCTION GCARR 
```
It's just k(T) = A x **(300/T)**^n x exp(-Ea/RT). However, I find similar but not exactly same expression in NIST dataset where k is caculated by k(T) = A x **(T/298)**^n x exp(-Ea/RT). I assume that GC uses 300K rather than 298K so that the number is fine. But the second term is supposed to be T/constant rather than cosntant/T comparing to the NIST dataset. I want to double check that if it's a bug.

The source of codes and NIST equation are provided in the links below.
GC codes: https://github.com/geoschem/geos-chem/blob/main/KPP/fullchem/gckpp.kpp
NIST data (e.g., propane): https://kinetics.nist.gov/kinetics/ReactionSearch?r0=74986&r1=3352576&r2=0&r3=0&r4=0&p0=-10&p1=0&p2=0&p3=0&p4=0&expandResults=true&

**Comment by yantosca** [comment]
Thanks @jinlx for writing.  I think you can express the reaction rate expression in more than one way.

I am not a chemist so I cannot comment further.  @kelvinhb @viral211 can one of you comment further?

**Comment by kelvinhb** [comment]
Hi @jinlx and @yantosca -- it's my understanding that we don't actually use the "B0" term in GCARR anywhere in the mechanism, so it's kind of a moot point. Bob's been working on simplifying the KPP equations to speed up the solver, and I think removing the B0 term will be part of that, right? But as Bob says, you can always write these different ways; if you're translating from the NIST database, which uses (T/298)^n, to GCARR, which uses (300/T)^n, you just have to make n negative. (And scale slightly for the 298K vs. 300K offset). But it's good to be aware of these differences!

**Comment by jinlx** [comment]
Thanks @kelvinhb and @yantosca ! It's good to know that B0 is not used so that it will not influence the results anyway. Thanks for the discussion! I will still keep it just in case that there is any other insights but feel free to close the issue as well.

**Comment by yantosca** [comment]
Hi @jinlx and @kelvinhb... Yes, I have been working on writing new rate-law functions that avoid computing terms that don't need to be computed.  This will go into 13.1.0.

Also I am bringing in the heterogeneous chemistry rate-law functions into KPP but that will probably not be ready until 13.3.0.

**Comment by viral211** [comment]
Hi @jinlx @yantosca @kelvinhb, In the standard GEOS-Chem mechanism, B0 is used when GCARR is called from GCJPLPR (the three-body reaction rate function).

**Comment by yantosca** [comment]
@viral211 @jinlx @kelvinhb That is correct.  In the current 13.0.0 code we use GCARR which assumes that you always have 3 terms.  But if you look in the fullchem.eqn file in the KPP/fullchem folder, then many of those calls have B0=0.  For this reason I've split up GCARR into a couple of different functions (GCARR_ac, GCARR_ab) that you can use starting in 13.1.0, which is undergoing benchmarking.  For example, if the B0 term is zero, you would call GCARR_ac (which would completely avoid computing the (300/T)**b0 term.  This saves on CPU cycles.

**Comment by yantosca** [comment]
Going to close the issue @jinlx @kelvinhb @viral211.  Thanks for your feedback!
