### ISSUE TITLE
[QUESTION] Questions about restart files in GEOS-Chem 13.0.0

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#737]
Chaitri Roy wrote:
> I have a few queries regarding restart files in GC13.0
>1.	If I have a restart file for 20090101, and I want to run the model with full chem from 20130101 to 2031231, will it be correct to spin up for 2012 using the file with timestamp 2009, by simply changing the flag, in HEMCO_Config file, from EFY to CYS/C?
>2.	If not, where can I possibly find the restart files for the individual years starting 2007?
>3.	The restart files available on the website had 72 levels, but I am running the model for 47 levels. How do I regrid the restart files available?

**Comment by yantosca** [comment]
Thanks for writing.  To answer your questions:

> 1. If I have a restart file for 20090101, and I want to run the model with full chem from 20130101 to 2031231, will it be correct to spin up for 2012 using the file with timestamp 2009, by simply changing the flag, in HEMCO_Config file, from EFY to CYS/C?

For spinning up 2012-2013, we do have restart files available from our 10-year benchmark simulation for 13.0.0.  Please see: http://ftp.as.harvard.edu/gcgrid/geos-chem/10yr_benchmarks/13.0.0/GCClassic/restarts/.  These go back to 2010.  You can start with the restart file from 2012/01/01.

> 2. If not, where can I possibly find the restart files for the individual years starting 2007?

We do not have 2009 restart files for the full-chemistry simulation.  But you could take a restart file from a different year and then either change the HEMCO timecycle flag (as you have noted above), or use the ncatted command of NCO to change the timestamp in the restart file:

```
ncatted -a units,time,o,c,"hours since 2009-01-01 00:00:00" GEOSChem.Restart.YYYYMMDD_0000z.nc4
```
where YYYYMMDD is the date of a restart file that you have already.

> 3. The restart files available on the website had 72 levels, but I am running the model for 47 levels. How do I regrid the restart files available?

No regridding is necessary!  HEMCO will do that for you at runtime.

**Comment by croy64** [comment]
> Thanks for writing. To answer your questions:
> 
> > 1. If I have a restart file for 20090101, and I want to run the model with full chem from 20130101 to 2031231, will it be correct to spin up for 2012 using the file with timestamp 2009, by simply changing the flag, in HEMCO_Config file, from EFY to CYS/C?
> 
> For spinning up 2012-2013, we do have restart files available from our 10-year benchmark simulation for 13.0.0. Please see: http://ftp.as.harvard.edu/gcgrid/geos-chem/10yr_benchmarks/13.0.0/GCClassic/restarts/. These go back to 2010. You can start with the restart file from 2012/01/01.
> 
> > 1. If not, where can I possibly find the restart files for the individual years starting 2007?
> 
> We do not have 2009 restart files for the full-chemistry simulation. But you could take a restart file from a different year and then either change the HEMCO timecycle flag (as you have noted above), or use the ncatted command of NCO to change the timestamp in the restart file:
> 
> ```
> ncatted -a units,time,o,c,"hours since 2009-01-01 00:00:00" GEOSChem.Restart.YYYYMMDD_0000z.nc4
> ```
> 
> where YYYYMMDD is the date of a restart file that you have already.
> 
> > 1. The restart files available on the website had 72 levels, but I am running the model for 47 levels. How do I regrid the restart files available?
> 
> No regridding is necessary! HEMCO will do that for you at runtime.
Thank you for your. I tried running GC13 for 47 levels with restart file having 72 levels, but it didn't work.

**Comment by yantosca** [comment]
@croy64, would you be able to attach the GEOS-Chem and HEMCO log files to this issue, as well as the input.geos and HEMCO_Config.rc files? You need to add the `.txt` extension to these files and then you can drag & drop them into the Github comment window.
