### ISSUE TITLE
[BUG/ISSUE] Adding Dry depositing species in 12.0.1

### ISSUE THREAD

**Issue by JFBrewer** [geoschem/geos-chem#738]
Hi folks.

I’m trying to add another dry depositing species to my version of GC 12.0.1 - the new species is a copy of R4N2 (the lumped alkyl nitrates tracer) produced solely from alkane oxidation. As part of making this tracer, I copied the entry for R4N2 in species_database_mod.F90. Somehow, this has broken everything with the dry deposition. Specifically, within drydep_mod.F, the NUMDEP incrementor (which counts the number of dry depositing species) correctly increases from 147 to 148 with the addition of this new species but the creation of the NDVZIND array (drydep_mod.F:4089 in my version) becomes bugged. NDVZIND should ideally be an array of all _n_ dry depositing species that basically just counts up _1...n_. In the base GEOS-Chem run, that array is 147 entries, of values (1, 2, ..., 147). However, when I add my new dry depositing species, the length of the array correctly increases to 148 entries, but the final entry is invariably 0: NDVZIND = (1, 2, ..., 147, 0). Since on line 521 this value is then used to reference the DVEL array (`DVZ     =  DVEL(I,J,NDVZ) * 100.e+0_f8`) this causes a segfault that stops my code from running further.

I assume this means I have skipped a step in adding a dry depositing species to the model, but I can't find what step this would have been.

I have tried to troubleshoot this problem simply, by removing the dry deposition from my new addition. Unfortunately, this does not solve the problem as the error now propagates backwards and the updated NDVZIND array now reads (1, 2, ..., 146, 0) instead of ending on 147 as it should. Notably, when I do allow for the dry deposition of ALK4N2, it is not species number 148 in the dry dep initialization - it is species number 3, which is correctly included into the NDVZIND array. I have been unable to figure out which species is the final dry depositing species (i.e., number 147 in the base model and 148 in my updated version).

My initial thought was that since R4N2 is a special case (as an alkyl nitrate, its ddep rate is tied to that of PAN) I had to add it as a special type in the case logic in drydep_mod.F, with Flag = 2. However, I have made that change and it hasn't fixed the problem.

I figure I must have missed some crucial step but I cannot figure out what it is. Does anyone have a good instinct for what might be causing this series of errors in 12.0? The same addition of ALK4N2 works find in 12.9.3, but unfortunately I need to add it to 12.0.1 for the moment.

Thanks,
Jared

**Comment by yantosca** [comment]
Thanks for writing @JFBrewer.  In `INIT_DRYDEP` there is some special handling for R4N2, in this CASE statement:
```F90
          !-----------------------------------------------------
          ! Kludges to match behavior of older code
          !-----------------------------------------------------
          SELECT CASE ( TRIM( SpcInfo%Name ) )

             CASE( 'ACET' )
                ! Flag the species ID of ACET for use above.
                id_ACET = SpcInfo%ModelId

             CASE( 'O3' )
                ! Flag the species ID of O3 for use above
                ID_O3 = SpcInfo%ModelId

            ... etc ...

             CASE(  'MPAN', 'PPN', 'R4N2' )
                ! These specied scale to the Vd of PAN.  We will
                ! explicitly compute the Vd of these species instead
                ! of assigning the Vd of PAN from the drydep velocity array.
                ! The scaling is applied in DO_DRYDEP using FLAG=2.
                !
                ! Make sure to set XMW to the MW of PAN
                ! for the computation of Vd to work properly.
                XMW(NUMDEP)  = State_Chm%SpcData(id_PAN)%Info%MW_g * 1e-3_fp
                FLAG(NUMDEP) = 2

          ... etc ...
          END SELECT
```
If you haven't already, I think you'd need to add the name of your species to the CASE with R4N2.  That should handle it.

**Comment by yantosca** [comment]
Oops but you said that didn't fix the problem.  Well shucks.

**Comment by yantosca** [comment]
This issue was resolved by making sure that the advected species list did not contain any non-advected chemical species.
