### ISSUE TITLE
[BUG/ISSUE] Model abnormal exits

### ISSUE THREAD

**Issue by zsx-GitHub** [geoschem/geos-chem#739]
### Ask a question about GEOS-Chem:
I am running GEOS-Chem v13.0.2. The model was running smoothly, for nearly 2-month simulation, but will stop on a particular day, Dec. 28 2021. Are there any possible reasons why this is happening and how to solve this problem? I am attaching the log files from my simulation.

[v13.0.2.txt](https://github.com/geoschem/geos-chem/files/6540364/v13.0.2.txt)
[HEMCO.txt](https://github.com/geoschem/geos-chem/files/6540365/HEMCO.txt)

**Comment by yantosca** [comment]
Hi @zsx-GitHub, thanks for writing.  I believe the error you saw is described here: https://github.com/geoschem/HEMCO/issues/84.

This will be fixed in 13.1.0.

**Comment by zsx-GitHub** [comment]
Thank you! That solved my problem!
