### ISSUE TITLE
[BUG/ISSUE] build_mechanism.sh adds in redundant lines to gckpp_Function.F90 — error: Aout array defined twice

### ISSUE THREAD

**Issue by ujongebloed** [geoschem/geos-chem#740]
### Problem:

I am trying to run the model with tagged reactions in KPP. I executed ./build_mechanism.sh successfully after fixing the .F90 bug reported earlier, but **even when I made no changes to custom.eqn,** I got the following error after executing "cmake ../CodeDir -DCUSTOMMECH=y -DRUNDIR=.." and "make -j4." **Error message below:**

/home/cindylou/ujongebl/0528_GCClassic.13.0.2/rundir/test_KPP/CodeDir/src/GEOS-Chem/KPP/custom/gckpp_Function.F90(61): error #6417: The dimensions of this array have been defined more than once.   [AOUT]
  REAL(dp), optional :: Aout(NREACT)
------------------------^
/home/cindylou/ujongebl/0528_GCClassic.13.0.2/rundir/test_KPP/CodeDir/src/GEOS-Chem/KPP/custom/gckpp_Function.F90(61): error #6650: This symbol has multiple OPTIONAL statement/attribute declarations which is not allowed.   [AOUT]
  REAL(dp), optional :: Aout(NREACT)
------------------------^
/home/cindylou/ujongebl/0528_GCClassic.13.0.2/rundir/test_KPP/CodeDir/src/GEOS-Chem/KPP/custom/gckpp_Function.F90(925): error #6366: The shapes of the array expressions do not conform.   [AOUT]
  if(present(Aout)) Aout(:) = A(:)
--------------------^
compilation aborted for /home/cindylou/ujongebl/0528_GCClassic.13.0.2/rundir/test_KPP/CodeDir/src/GEOS-Chem/KPP/custom/gckpp_Function.F90 (code 1)

### Troubleshooting
This error occurs because build_mechanism.sh adds a redundant line to the gckpp_Function.F90 file (**bolded** line is redundant):

SUBROUTINE Fun ( V, F, RCT, Vdot, Aout )
! V - Concentrations of variable species (local)
REAL(kind=dp) :: V(NVAR)
! F - Concentrations of fixed species (local)
REAL(kind=dp) :: F(NFIX)
! RCT - Rate constants (local)
REAL(kind=dp) :: RCT(NREACT)
! Vdot - Time derivative of variable species concentrations
REAL(kind=dp) :: Vdot(NVAR)

!### KPP 2.3.0_gc, Bob Yantosca (11 Feb 2021)
!### Aout — Array for returning KPP reaction rates for diagnostics
**REAL(kind=dp), OPTIONAL :: Aout(NREACT)**
REAL(dp), optional :: Aout(NREACT)

If you comment out the bolded line, the model builds and runs correctly even after modifying custom.eqn.

### GEOS-Chem version
13.0.2

### Description of modifications
None to produce this bug

**Comment by yantosca** [comment]
Thanks @ujongebloed for writing.  I recently updated the https://kpp.readthedocs.io  site to provide better guidance as to which version of KPP corresponds to which versions of GEOS-Chem.

RIght now we recommend using KPP 2.2.5_gc for 13.0.2 and prior versions.  Once GEOS-Chem 13.1.0 is released, then we recommend using KPP 2.3.1_gc.

In the future we hope to make KPP a submodule of GEOS-Chem so that any KPP updates can be pegged to GEOS-Chem updates, but that is likely a ways off.

**Comment by ujongebloed** [comment]
Thanks, @yantosca. I'll try using KPP 2.2.5_gc and see if that works. If not, just commenting out the bolded line above fixes the issue for me.
