### ISSUE TITLE
[BUG/ISSUE] Empty files in 2x2.5 GEOS-FP 2021/02

### ISSUE THREAD

**Issue by jennyfisher** [geoschem/geos-chem#741]
Hi team,

Many of the files in `http://geoschemdata.computecanada.ca/ExtData/GEOS_2x2.5/GEOS_FP/2021/02/` are present but empty (size 0).

Thanks,
Jenny

**Comment by LiamBindle** [comment]
Hi Jenny, 

Thanks for writing. I just opened https://github.com/geoschem/geos-chem/issues/748. The metfield preprocessing was migrated to a new cluster ~6 months ago. The new cluster has some filesystem issues, and it looks like some errors might have gotten into the http://geoschemdata.computecanada.ca/ repository.

We're going to go through and validate all the potentially affected files. This will likely take a few weeks. 

In the mean time, we will reprocess 2021-02 and upload those files as soon as possible. Let us know you run into other bad files.

-Liam

**Comment by jennyfisher** [comment]
Thanks Liam!

**Comment by YanshunLi-washu** [comment]
Hi Jenny. I've reprocessed the GEOSFP 2x2.5 data for 202102. Haven't found any empty files in http://geoschemdata.computecanada.ca/ExtData/GEOS_2x2.5/GEOS_FP/2021/02/ now. Hope this helps.

Thanks,
Yanshun

**Comment by jennyfisher** [comment]
Thanks Yanshun!
