### ISSUE TITLE
[QUESTION] Could GEOSChem v13 produce planeflight output and hourly CO2 concentrations?

### ISSUE THREAD

**Issue by zoezhchen** [geoschem/geos-chem#742]
### Ask a question about GEOS-Chem:
Hi,
I am trying to use planeflight function in CO2 simulation with GEOSChem v13
Does this function (planeflight) work for CO2 simulation?

```
Turn on plane flt diag? : T
Flight track info file  : ./Processing/Output/flight/flight.YYYYMMDD
Output file name        : ./OutputDir/plane.log.YYYYMMDD
```

I am wondering if I should set trace number as 001 if I want to output CO2 concentration at lon,lat,lev,time ?
```
--------------------------------------------
1
--------------------------------------------
TRA_001
```
Is there a way to output hourly CO2 concentration for surface sites?

Thanks.

**Comment by zoezhchen** [comment]
After about seven months run, the output is still close to the initial concentration at different levels:  
10    Tamt 20100720 2004   57.67 -152.36  867.01      0.000 000028921 010 00012 00075  9.968E-009
   11    Tamt 20100720 2005   57.61 -152.40  928.03      0.000 000028921 006 00012 00075  9.968E-009
   12    Tamt 20100720 2007   57.67 -152.36  973.79      0.000 000028921 003 00012 00075  9.968E-009
   13    Tamt 20100720 2007   47.41  -98.85  385.33      0.000 000028921 026 00033 00070  9.970E-009
   14    Tamt 20100720 2012   47.49  -99.20  420.70      0.000 000028923 025 00033 00070  9.971E-009
   15    Tamt 20100720 2017   47.48  -99.16  491.20      0.000 000028923 023 00033 00070  9.971E-009
   16    Tamt 20100720 2024   47.46  -99.14  561.50      0.000 000028923 021 00033 00070  9.972E-009
   17    Tamt 20100720 2031   47.44  -99.14  631.68      0.000 000028925 019 00033 00070  9.971E-009
   18    Tamt 20100720 2035   47.46  -99.16  660.89      0.000 000028925 018 00033 00070  9.971E-009
   19    Tamt 20100720 2042   47.45  -99.08  730.95      0.000 000028925 015 00033 00070  9.971E-009
   20    Tamt 20100720 2046   47.39  -99.14  775.29      0.000 000028925 013 00033 00070  9.971E-009
   21    Tamt 20100720 2049   47.47  -99.14  805.62      0.000 000028925 011 00033 00070  9.971E-009
   22    Tamt 20100720 2052   47.36  -99.15  861.58      0.000 000028927 007 00033 00070  9.971E-009
   23    Tamt 20100720 2055   47.40  -99.08  903.54      0.000 000028927 004 00033 00070  9.971E-009
   24    Tamt 20100720 2057   47.46  -99.16  945.65      0.000 000028927 001 00033 00070  9.971E-009

**Comment by yantosca** [comment]
Thanks for writing @zoezhchen.   I believe that the planeflight diagnostic should be able to recognize the name of the species (i.e. CO2) in the `flight.YYYYMMDD` file, at least since 13.0.0 (see issue #528). But you can also use `TRA_001` to reference the species by its index.

Can you post the `flight.YYYYMMDD` file that you are using?  You need to specify a line with the lon/lat/static pressure and timestamp that you want to read for each site.  I wonder if you are specifying the coordinates and pressure properly.

If you have NOAA ObsPack data for CO2, then you can request hourly-averaged output via our ObsPack diagnostic.  See: http://wiki.geos-chem.org/ObsPack_diagnostic

**Comment by zoezhchen** [comment]
Planeflight.dat -- Input file for planeflight diagnostic
GCST
TIER12
--------------------------------------------
1
--------------------------------------------
TRA_001
--------------------------------------------
Now give the times and locations of the flight
--------------------------------------------
TYPE, QDD, QMM, QYY, QHH, QMN, LAT, LON, PRES, OBS
18533   Tamt  2 11 2017 17 40   31.45  -92.89 5425.50      0.000
18534   Tamt  2 11 2017 18  4   32.79  -91.05 5405.00      0.000
18535   Tamt  2 11 2017 19  0   33.21  -91.58  387.00      0.000
18536   Tamt  2 11 2017 19  6   29.01  -93.44  329.10      0.000
18537   Tamt  2 11 2017 19 16   33.54  -92.78  364.00      0.000
18538   Tamt  2 11 2017 19 25   29.00  -94.54  318.30      0.000
18539   Tamt  2 11 2017 19 32   33.86  -94.06  439.00      0.000
18540   Tamt  2 11 2017 19 46   34.23  -95.07  558.00      0.000
18541   Tamt  2 11 2017 19 55   29.56  -95.96  379.40      0.000
18542   Tamt  2 11 2017 19 56   34.49  -95.77  633.00      0.000
18543   Tamt  2 11 2017 20  6   30.00  -96.39  442.20      0.000
18544   Tamt  2 11 2017 20 15   34.99  -97.22  666.00      0.000
18545   Tamt  2 11 2017 20 31   35.46  -98.43  824.00      0.000
18546   Tamt  2 11 2017 20 56   31.93  -94.78 2238.10      0.000
18547   Tamt  2 11 2017 20 59   36.69  -99.92 1253.00      0.000
18548   Tamt  2 11 2017 21 16   36.22  -99.15 2173.00      0.000
18549   Tamt  2 11 2017 21 49   34.43  -96.71 5438.00      0.000
18550   Tamt  2 11 2017 22 40   33.06  -94.62 2250.00      0.000
99999    END  0  0    0  0  0    0.00    0.00    0.00      0.000

Thanks for your reply. This is one of my flight.YYYYMMDD.

**Comment by yantosca** [comment]
Question: you have the pressures going from about 5400 hPa (free trop) to about 300hPa (stratosphere).  Is that correct for your application?

**Comment by zoezhchen** [comment]
Thanks. This is for altitude(m), as the code says if the type is Tamt(Tower), then the numbers are altitude and will be converted to pressure.
