### ISSUE TITLE
[QUESTION] Obspack diagnostic timestamps

### ISSUE THREAD

**Issue by eamarais** [geoschem/geos-chem#744]
Has the time entry for the ObsPack input file changed from "time_component" with 6 entries for individual components (YYYY, MM, DD etc.) to "time" as seconds since 1970? If so, would it be possible to update the wiki page http://wiki.seas.harvard.edu/geos-chem/index.php/ObsPack_diagnostic to reflect this?

**Comment by yantosca** [comment]
Hi @eamarais, thanks for asking.  Also bringing @andyjacobson into the loop.  Some of the newer ObsPack data changed the timestamps for each poing (see issue #631).

**Comment by lizziel** [comment]
I'm reopening this to make sure we update the wiki if the implementation of timestamp in ObsPack module changed. I haven't read the previously mentioned thread about time. We should go back to it to make sure the end result is consistent with the wiki.

**Comment by yantosca** [comment]
I have just updated the ObsPack wiki page noting that the `time` variable is always the center of the observing window.  See this link: http://wiki.geos-chem.org/ObsPack_diagnostic#Input_file_format
