### ISSUE TITLE
[QUESTION] couldn't conduct future simulations of air pollutants in 2050 with RCP 2.6 emission by GEOS-Chem v13.0.2

### ISSUE THREAD

**Issue by Shuto-kop** [geoschem/geos-chem#746]
Hi,

I am trying to conduct a future full-chem simulations of air pollutants in 2050 with RCP 2.6 emission by GEOS-Chem v13.0.2
  
I have three questions:
 
1.    How do I set the meteorology year?
I tried to do fullchem simulations of air pollutants in 2050 by GEOS-Chem v13.0.2  without fixing the meteorological year, but I couldn't finish the simulation because of the error when opening meteorology files(MERRA-2).
The error statement is written in Error_message_Q1.txt
 
[Error_message_Q1.txt](https://github.com/geoschem/geos-chem/files/6605748/Error_message_Q1.txt)

I know you said that I need not fix the meteorology year when I want to do future simulation
on this issue(https://github.com/geoschem/geos-chem/issues/590)
 
2.    How do I set the restart file when I want to conduct future simulation?
As a quick fix for dealing with the above problems, I fixed file name and timestamp of meteorology data. 
However, If I didn't fix file name and timestamp, I couldn't finish the simulation because of the error when opening restart file.
Should I fix file name and timestamp of restart_file?
The error statement is written in Error_message_Q2.txt
 
[Error_message_Q2.txt](https://github.com/geoschem/geos-chem/files/6605749/Error_message_Q2.txt)
 
3.    As a quick fix for dealing with the above problems, I fixed file name and timestamp of meteorology data and restart file. These fixes enabled me to start simulation, but I faced new problem. The simulation stopped immediately, though I turned off both NOAA_GMD_CH4 and CMIP6_SFC_CH4 in HEMCO_Config.rc.
The error statement is written in Error_message_Q3.txt

 [Error_message_Q3.txt](https://github.com/geoschem/geos-chem/files/6605750/Error_message_Q3.txt)

I don't know why this message was shown. Could I ask you to tell me the way to accomplish the simulation properly?
 
I'm looking forward to hearing from you.
 
Regards,

**Comment by msulprizio** [comment]
Hi @Shuto-kop. Sorry for the lack of response. Do you still need help with these questions? If so, I can reopen and respond to each point.
