### ISSUE TITLE
[BUG/ISSUE] Malformed NetCDF files on geoschemdata.computecanada.ca

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/geos-chem#748]
### Description of the problem
Some of the preprocessed meteorological data for the past few months is malformed. This means that some of the meteorological data files on geoschemdata.computecanada.ca are not valid NetCDF files.

### Description of troubleshooting performed
An example of a bad file is http://geoschemdata.computecanada.ca/ExtData/GEOS_0.25x0.3125/GEOS_FP/2021/03/GEOSFP.20210312.I3.025x03125.nc. If you download it and `ncdump` it, you will get 
```console
$ wget http://geoschemdata.computecanada.ca/ExtData/GEOS_0.25x0.3125/GEOS_FP/2021/03/GEOSFP.20210312.I3.025x03125.nc
Connecting to geoschemdata.computecanada.ca (206.12.88.212:80)
GEOSFP.20210312.I3.0 100% |************************************************************************************************************************************************************| 2322M  0:00:00 ETA
$ ncdump -h GEOSFP.20210312.I3.025x03125.nc 
ncdump: GEOSFP.20210312.I3.025x03125.nc: GEOSFP.20210312.I3.025x03125.nc: NetCDF: Unknown file format
```

### Possibly affected files
- All GEOS-FP files since 2020-11.
- All MERRA-2 files since 2020-10.

### Possible culprit
Recently we transitioned metfield preprocessing from stetson (Dalhousie) to Compute1. The Compute1 filesystem has had a number of issues, and specifically, file read/write operations sometime fails/behave strangely.

### How to fix

I think we need to validate all metfields that were preprocessed on Compute1. I have a script that checks for malformed NetCDF files in `Shared/check-nc`.

@YanshunLi-washu Would you be able to help with this? What we need to do is:
1. On Compute1, we need to download all the metfields from geoschemdata.computecanada.ca since the since stetson->C1 migration 
2. Run `check-nc` on all those files.
3. Reprocess months with bad files

**Comment by msulprizio** [comment]
@LiamBindle @YanshunLi-washu Is this still an issue or has the problem been resolved?

**Comment by YanshunLi-washu** [comment]
@msulprizio Hi Melissa, we're still working on that. There will be results later this week. Please keep it opened for another while. Thank you

**Comment by yantosca** [comment]
Please note: geoschemdata.computecanada.ca will now bounce to the WashU server.  See discussion #963.

**Comment by yantosca** [comment]
I will close out this issue for now, as there has been a lack of activity.
