### ISSUE TITLE
[QUESTION] INSTALLATION IN WINDOWS SUBSYSTEM FOR LINUX

### ISSUE THREAD

**Issue by nicodgomez** [geoschem/geos-chem#751]
Hello, my question is if the program have been tested under windows subsystem for linux. I am currently running Windows 10 Home Version 20H2, and i pretend to use the program in my investigations. Thancks.

**Comment by lizziel** [comment]
Hi @nicodgomez, GEOS-Chem is only supported for unix operating systems. We do not support running GEOS-Chem on Windows. If this is not an option for you on your local system then you can also run on Amazon Cloud Services. See the [GEOS-Chem Basics wiki page](http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_basics) for more information.

**Comment by yantosca** [comment]
Thanks for writing @nicodgomez.  As @lizziel mentioned, we do not support running GEOS-Chem on Windows.  As I understand, the Windows Subsystem for Linux is a compatibility layer for Linux applications (even with a version of the Linux kernel).  I am not too familiar with this (as I typically use Cygwin for Windows/Linux emulation).  I would imagine that you may run into some library compatibility issues as it is very difficult to make native Linux apps run in Windows, even with a Linux emulator like WSL.

I would say, feel free to try using GEOS-Chem on WSL for Linux.  But know that the GEOS-Chem Support Team would not be able to assist you in any debugging or support.  

Another thing you could try is to dual-boot your system with a Linux distro and then try running GEOS-Chem on that.  You will want to make sure that you have sufficient memory and disk space if you are going to be running full-chemistry simulations.... you may find that your PC doesn't have enough memory.  If you are running the less-computationally-intensive simulations (Hg, CH4, CO2, etc), then those would have a higher chance of success.

I will close out this issue now.
