### ISSUE TITLE
[QUESTION] question about nonlinearity of chemistry for tagged ozone simulation

### ISSUE THREAD

**Issue by sharonshen-wq** [geoschem/geos-chem#753]
### Ask a question about GEOS-Chem:
Hi, there. I am wondering how large differences there are between the results from standard chemitry simulation and the tagged ozone simulation in version 12.9.3. Related studies have shown a difference within ±5 % existing in old version (e.g. v9.2), but the differences are much larger in my simulations especially in the surface layer, however, my results from tagged ozone simulation catch the variation trends of ozone well with those observations both in horizontal and vertical directions. So I am a little confused about my results from tagged ozone simulation, is it normal or something was wrong during the tagged process?

**Comment by lizziel** [comment]
Hi @sharonshen-wq, I am pinging the [GEOS-Chem Chemistry Working Group](http://wiki.seas.harvard.edu/geos-chem/index.php/Chemistry_Working_Group) heads on this as it is a science-related question. @mje1398, @barronh, @luhu0, do you have any comments?

**Comment by mje1398** [comment]
I've not used the tagged ozone simulation in about 20 years so I'm not sure I can help that much. I'm not sure who was the last person to publish something on the tagged ozone simulation, or put through a new github update? There may be some issues with updated definitions of Ox as the chemistry has changed in the model but the tagged o3 code hasn't kept pace with that. Sorry I can't be more help.

**Comment by yantosca** [comment]
Thanks for writing @sharonshen-wq.  One thing you will want to do is make sure that you generate the O3 prod and loss data from a full-chemistry simulation with the same version of GEOS-Chem that you will use to run a tagged-O3 simulation.

The default HEMCO_Config.rc file for the tagged-O3 run directory points to some sample O3 prod/loss data, but if that was not generated with the same version that you are using, you will see differences.

**Comment by sharonshen-wq** [comment]
yes, I generated the new P/L rate data with this new version, and revised the corresponding contents in the HEMCO_Config.rc file, the differences occurred as described above @yantosca
