### ISSUE TITLE
Mass conservation of convection scheme with scaling

### ISSUE THREAD

**Issue by aschuh** [geoschem/geos-chem#754]
I've looked at the GCHEM convection scheme a few times and it was my gut feeling that scaling the convective mass fluxes that were coming into GCHEM from something like MERRA2 (either in driving files or or in the actual GC convection code) would NOT affect overall tracer conservation.  Can anybody with more familiarity with the GCHEM convection implementation confirm or deny this?  Thanks.

**Comment by yantosca** [comment]
Thanks for writing @aschuh.  That is a little bit out of my wheelhouse so I would defer to others who know more, maybe Hongyu Liu.

**Comment by lizziel** [comment]
Hi @aschuh, I am pinging Hongyu on this in case he has any comments. @hongyuliu3

**Comment by lizziel** [comment]
Our mass conservation tests for GEOS-Chem generally only look at tracer mass between timesteps using the full model. If you would like to break it up further I suggest looking at the budget diagnostics. The 'BudgetConvectionFull_?ADV?' diagnostic is the total column mass change for convection only. We include the budget diagnostics in benchmark output (although we are no longer going to do this starting with the next benchmark). For the budget results for 13.1.0 see [here](http://ftp.as.harvard.edu/gcgrid/geos-chem/1mo_benchmarks/GC_13/13.1.0-beta.1/GCClassic/BenchmarkResults/Tables/Budgets_After_Operations_Jul2019.txt).

That being said, I'm not sure if this fully answers your question. As far as I know we have not scaled the convective mass flux inputs. You could try this and use the budget diagnostics to see the outcome. I'd recommend turning off all components except convection in input.geos and HEMCO_Config.rc and see how that impacts things.

**Comment by aschuh** [comment]
Thanks Lizzie.  I'm still running a modified version of 12.03 (Oct 2018) so I won't have the budget diagnostics.  I'll just put in my own own mass budgets and test this by scaling up/down convection fields.  Just curious whether anybody had gone down this path before, thanks.

**Comment by lizziel** [comment]
Hi @aschuh, let us know what you find. For now I will keep this issue open in case anyone in the community sees it and wants to weigh in. @sdeastham, do you have any insight into this question?

**Comment by sdeastham** [comment]
Hi all - unfortunately convection is not my strength, so I can't say anything definitive on this front. I have the same gut feeling as @aschuh but don't have any rigorous data or logic to back it up.

**Comment by aschuh** [comment]
We can close this issue for now.  I tested by scaling with 1.5X and 3X the CMFMC and DTRAIN fields being read in.  Changes the overall tracer distributions very little and has no effect on mass.  I may continue to explore this issue w/ doing things like redistributing the convective mass fluxes through the column to make sure it still conserves mass but we'll move this discussion to an upcoming transport working group meeting.  Thanks.
