### ISSUE TITLE
[FEATURE REQUEST] Update to CEDS v2 emissions

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#757]
Patrick Campbell (@drnimbusrain) provided files for updating to CEDS v2 emissions through 2019.

>I have is a straightforward use of the release version (https://data.pnnl.gov/dataset/CEDS-4-21-21), with only some simple re-processing for our use in HEMCO. 

The recommendation from the GEOS-Chem Steering Committee is to make the CEDS v2 emissions the default in GEOS-Chem. Daniel Jacob wrote:
* We will bring in the new CEDS inventory as a default in version 13.2 taking advantage of the scripts already generated by Patrick Campbell for input to HEMCO. Before doing so we will do a HEMCO stand-alone comparison of the new CEDS and the current CEDS GBD-MAPS, to make sure that there are no anomalies in the new CEDS and to pick up on any large regional differences. 
* The current CEDS GBD-MAPS with higher sectoral resolution will remain in the HEMCO library for users to choose if they see fit.

**Comment by msulprizio** [comment]
Processed data files have been uploaded to http://ftp.as.harvard.edu/gcgrid/data/ExtData/HEMCO/CEDS/v2021-06/. Testing is in progress.

**Comment by msulprizio** [comment]
This has now been merged into `dev` via PR https://github.com/geoschem/geos-chem/pull/766. 

Evaluation against CEDS GBD-MAPS is ongoing and results will be shared here.

**Comment by msulprizio** [comment]
The comparison of 1-year HEMCO standalone simulations with CEDS GBD-MAPS and CEDSv2 may be found at:
http://ftp.as.harvard.edu/gcgrid/geos-chem/validation/CEDS_comparison/

**Comment by mje1398** [comment]
Hi Melissa, do we know why the VOCs in the latest version of CEDS have dropped so much? 
![CEDS_versions_NMVOCs](https://user-images.githubusercontent.com/23074789/126530285-eecccbcd-7b80-417d-bb30-90406327c0ea.png)

Looking at the tables things like Propane, Ethane, ALK4 emissions have dropped globally by around 30%? 

We've been looking at ethane and that seems to be getting further from the bottom up estimates? 

Do we understand what is going on?

**Comment by msulprizio** [comment]
I do not, but others like @drnimbusrain or @emcduffie may have more insight.

In GEOS-Chem we don't use the ethane and propane emissions from CEDS by default because of the known underestimate. Instead we use [C2H6 from Tzompa-Sosa et al. (2017)](http://ftp.as.harvard.edu/gcgrid/data/ExtData/HEMCO/C2H6_2010/v2019-06/README) and [C3H8 from Xiao et al. (2008)](http://ftp.as.harvard.edu/gcgrid/data/ExtData/HEMCO/XIAO/v2014-09/README).

**Comment by mje1398** [comment]
It would be useful for us to have a conversation about what is going on with this. The Tzompa-Sosa and Xiao are now very old, non-time varying and pretty niche compared to what the rest of the community is using.  Do the CEDS community know that we think there is a large underestimate?

**Comment by msulprizio** [comment]
@mje1398 Agreed. It would be worth discussing with the Emissions & Deposition WG as they noted these differences as well. I'm not sure if the CEDS community is aware of the underestimate.

**Comment by ssmithClimate** [comment]
Globally we're seeing NMVOC emissions that are slightly higher in CEDSv2021_04_20 as compared to CEDS v_2016_07_26 (what you are calling v2018 above), so it would be useful to better understand what you're plotting.  See: https://github.com/JGCRI/CEDS/blob/master/documentation/Version_comparison_figures_v_2021_04_21_vs_v_2016_07_16(CMIP6).pdf (Particularly Figure S2).

**Comment by matt-rowlinson** [comment]
Hi all,
Thanks for the comment @ssmithClimate. We can reproduce that Figure S2 when we add in the NMVOC SOLID-BIOFUEL file. However we can't see any speciated biofuel emissions files, do they exist? When we sum the individual VOC files, we get the same total as from just the NMVOC-em-anthro file.
@msulprizio. Should we be adding the CEDS biofuel emissions into the CEDS anthopogenic emissions in HEMCO?

![full_CEDS_versions_NMVOCs](https://user-images.githubusercontent.com/16290927/126784062-a1a0f02e-ee35-46b2-b305-0daa9bbb3850.png)
![full_CEDS_versions_C2H6](https://user-images.githubusercontent.com/16290927/126783050-76426904-f73d-4f81-988c-0d9903d08e7b.png)
(The previous plots were labelled just based on the HEMCO directories. I've updated them in these plots, based on the version information/date of creation in the files)

**Comment by ssmithClimate** [comment]
The solid biofuel emissions are a subset of what is already in total NMVOCs. Looks like there is something missing in our comparison figures, we'll fix that.  Total NMVOCs did go down in the latest dataset. We are using older speciation data, so we'd like to update that - that might help address some of the issues you are seeing.

**Comment by mje1398** [comment]
@ssmithClimate Thanks for the clarification! 

Is there a simple explanation for the reduction in the emissions especially of the alkanes (~30-40%) like ethane or it a combination of lots of factors? 

Thanks for the help.

**Comment by ssmithClimate** [comment]
So I take it you're asking about our CEDS/RETRO category: VOC06 | hexanes_plus_higher_alkanes?
I would have expected, if anything, those to be higher, since that's a large fraction of the SLV sector and SLV emissions are overall higher in the newer version.

As for ethane (VOC02) itself, a large part is from TRN, and that's slightly higher in the new version globally, but I haven't looked at that in detail by region.

It would be useful to compare emissions by sector to isolate which sector is driving the differences you're seeing.

**Comment by mje1398** [comment]
Sorry. No I was asking about the smaller VOCs. So the new global values when implemented into GC (http://ftp.as.harvard.edu/gcgrid/geos-chem/validation/CEDS_comparison/) have given relatively large drops for global alkane emissions. 

ALK4 Anthro        :        -28.878%
C2H6 Anthro        :        -30.792%
C3H8 Anthro        :        -35.879%
ALK4 Anthro        :        -28.878%

The change in the other hydrocarbons are smaller but still significant
PRPE Anthro        :        -8.378%
BENZ Anthro        :      -12.085%
TOLU Anthro        :       -7.384%
XYLE Anthro        :        -0.223%

Especially when compared to the changes in the inorganics. 
NO Anthro          :          -0.134%
NH3 Anthro         :         1.173%
CO Anthro          :         -1.754%
SO2 Anthro         :        3.567%

I don't think the datafiles we have access to on Glubus for the new emissions have sector level information to be able to compare to the sector levels in the previous versions.
