### ISSUE TITLE
[BUG/ISSUE] Runs starting on 1st Mar-Dec in a leap year, and ending an integer number of years later, fail if history collections frequency/duration set to “End”

### ISSUE THREAD

**Issue by angharadstell** [geoschem/geos-chem#763]
### Description of the problem
I ran a series of 36 CH4 global simulations, starting on the first of each month between Jan 2010 and Dec 2014, each lasting 2 years. All the runs worked apart from those starting in Mar-Dec 2012. These runs were stopped because it thought the history collections with a frequency/duration of “End” were after the end of the simulation, but that’s not true.

### Description of troubleshooting performed
Setting the frequency/duration of the collections to monthly output, or commenting out “End” collections allows the model to run.

The runs also only fail when the runs last for integer number of years.

I tried having a look in the code to see if I could see an obvious issue, but I couldn’t. 

### GEOS-Chem version
I found this on 13.0.0, but it also happens in a clean version of 13.1.1

### Description of modifications
Issue is present on the default CH4 simulation in v13.1.1 with just a change of dates in input.geos

### Log files
- Log for 20120301 run: [GC.log](https://github.com/geoschem/geos-chem/files/6734504/GC.log)

### Software versions
- CMake version: 3.17.0
- Compilers (Intel or GNU, and version): ifort 19.0.3.199
- NetCDF version: 4.7.0

**Comment by yantosca** [comment]
Thanks for writing @angharadstell.  There was fixes (commits ca68f508b956a24663cf49722b437c638e9e9c6f and fb093d61b8321834d5f1d9565760e2828138b321) to try to properly span leap years.  But we didn't test for all edge cases, so it is possible that some difficulties might remain.

If you use shorter simulation intervals (less than 1 year) then the chances are better that you will avoid this type of error.

**Comment by yantosca** [comment]
I've pushed a update that I believe will fix this issue.  See [this comment](https://github.com/geoschem/geos-chem/issues/800#issuecomment-890193839) on issue #800.

I will close out this issue.  The fix will ship in version 13.2.1, which will be released immediately after 13.2.0 (once it clears benchmarking).
