### ISSUE TITLE
[QUESTION]Error reported when turn on Acidic uptake in GEOS-Chem v12.9.3

### ISSUE THREAD

**Issue by yangxiajie** [geoschem/geos-chem#767]
In GEOS-Chem v12.9.3, I try to turn on `Acidic uptake` . However, ERROR reported when `Acidic uptake` is **T** in `input.geos` :

```
===============================================================================
GEOS-Chem ERROR: LDSTUP=T but COATED DUST AEROSOLS are undefined!
-> at Do_Error_Checks (in GeosCore/input_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem ERROR: Error encountered in "Do_Error_Checks"!
 -> at GC_Init_Extra (in module GeosCore/gc_environment_mod.F90)
===============================================================================

===============================================================================
GEOS-CHEM ERROR: Error encountered in "GC_Init_Extra"!
STOP at  -> at GEOS-Chem (in GeosCore/main.F90)
===============================================================================

```
Is there any ways to fix it?

Thank you.

**Comment by tsherwen** [comment]
Hello @yangxiajie, 

It looks like you have not defined the additional aerosol tracers. Did you set up the dust simulation using the unit tester?

Cheers, 

Tomas

**Comment by yangxiajie** [comment]
Hi, @tsherwen ,

Thank you for reply.

I use `Complex SOA` to simulate acid uptake. And now I know the problems.

However, I still have another question. I want to investigate Heterogeneous chemistry of SO2 and HNO3 on dust because I modified γ(HNO3) and γ(SO2) in `dust_mod.F90`.  On the other hand, I still need to investigate other Heterogeneous chemistry, so I have to use `Complex SOA` simulation. Is there any ways to make `acid uptake` compatible with `Complex SOA`?  In other words, if I use `Complex SOA` to  investigate Heterogeneous chemistry of SO2 on dust, should I have to use KPP to adding reactions because there seems no `SO2 + Dust = SO4` in `Tropchem.eqn` ?

**Comment by tsherwen** [comment]
Hello @yangxiajie,

Ah, yes. I thought you may not have had the `acid uptake` species (e.g. `SO4D4`, `NITD4`, `DSTAL4`) input.geos file etc. Glad that fixed it. I assume you have also checked for the other changes in the run directory? e.g. in HEMCO_Config.rc for alkalinity emissions?

The acid uptake reactions are managed in [sulfate_mod.F90](https://github.com/geoschem/geos-chem/blob/main/GeosCore/sulfate_mod.F90), not Tropchem.eqn.

I would recommend also checking out @zsx-GitHub's comments on issue #567 who, like me, is using & updating the acid uptake simulation. 

https://github.com/geoschem/geos-chem/issues/567

Hope that helps, 

Tomas

**Comment by yangxiajie** [comment]
Hi, @tsherwen ,

Thank you for reply. Now I fix it.

Thank you for your help again.

**Comment by 1392403848** [comment]
Hello, I've encountered the same issue, but I'm not sure how to resolve it.
