### ISSUE TITLE
[FEATURE REQUEST] Add diagnostic for number of times KPP is called in each grid box

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#77]
See: https://github.com/geoschem/gchp/issues/44.  

It should be a simple matter to add this diagnostic, perhaps into GEOS-Chem 12.7.0.

**Comment by JiaweiZhuang** [comment]
The number of solver calls (internal ODE integrator steps) will be a good enough metric!

The most direct metric though, is the wall time for this `Integrate` call in each grid box:

https://github.com/geoschem/geos-chem/blob/5f25c0fc6ff27ec076d766ac178554d9b91bf636/GeosCore/flexchem_mod.F90#L988-L991

But the time probably doesn't qualify as a diagnostic collection, as its value is not deterministic (depends on hardware).

Also I remember that other calls like `UPDATE_RCONST` can also take a significant amount of time, in addition to `Integrate`. But those are all fixed computations and shouldn't have load-balancing problems.

**Comment by yantosca** [comment]
@JiaweiZhuang That should be easy to do.  We have the variables commented out but I can restore them.  The itim ivariable would be the wall of integrate each grid box:

https://github.com/geoschem/geos-chem/blob/5f25c0fc6ff27ec076d766ac178554d9b91bf636/GeosCore/flexchem_mod.F90#L1007-L1021

Also KPP returns the various number of calls in ISTATUS.  If you want me to add those I can too... but as you say, they may be hardware dependent and not as instructive.  I can start working on this now that my other deadlines have passed.

**Comment by JiaweiZhuang** [comment]
> The itim ivariable would be the wall time of integrate in each grid box:

Oh I didn't know this `itim` thing! Thanks for pointing this out!

Please just collect number of calls first, so I can make a quick plot😀The wall time will also be very interesting, for example to see whether the number of solver calls is consistent with the actual time.

**Comment by yantosca** [comment]
@JiaweiZhuang: The KPP solver returns several diagnostics per each grid box:

```F90
!    ISTATUS(1)  -> No. of function calls
!    ISTATUS(2)  -> No. of jacobian calls
!    ISTATUS(3)  -> No. of steps
!    ISTATUS(4)  -> No. of accepted steps
!    ISTATUS(5)  -> No. of rejected steps (except at very beginning)
!    ISTATUS(6)  -> No. of LU decompositions
!    ISTATUS(7)  -> No. of forward/backward substitutions
!    ISTATUS(8)  -> No. of singular matrix decompositions
!
!    RSTATUS(1)  -> Texit, the time corresponding to the
!                     computed Y upon return
!    RSTATUS(2)  -> Hexit, last accepted step before exit
!    RSTATUS(3)  -> Hnew, last predicted step (not yet taken)
!                   For multiple restarts, use Hnew as Hstart 
!                     in the subsequent run
```

Here is the plot of ISTATUS(1), which should be the number of times the solver was called in each grid box. This was for a 3hr test run:

![kpp_png](https://user-images.githubusercontent.com/5880296/70255482-e252f280-1754-11ea-8014-806c4dfdf968.png)

Let me know if this looks like it should, or if there are any other diagnostics on that list you need.  We can also print the # of times the jacobian gets updated, and the # of LU decomp calls.

**Comment by JiaweiZhuang** [comment]
I can see the sunrise/sunset patterns, so it makes sense! Is it 3-hour average? I expect a sharper spatial gradient for instantaneous fields (i.e. for one model step, https://github.com/geoschem/gchp/issues/44#issuecomment-537037449)

I think `1. function calls`, `2. jacobian calls`, `3. steps` are particularly useful. For consistency, I would suggest recording all 8 numbers in `ISTATUS`, each is an entry in the`KPP` diagnostics collection.

**Comment by yantosca** [comment]
Yes that is a 3 hr average.  You can kind of see the sunrise-sunset.  Also more calls over the continents.

I'll save out all 8 fields.  Should have that done by today.

**Comment by yantosca** [comment]
@JiaweiZhuang: I have added the new KppDiags collection with all 8 fields of ISTATUS.  The commits are: 
1. https://github.com/geoschem/geos-chem/commit/5ac595c7cd8c315db4408feb58b53cc785d2c004
2. https://github.com/geoschem/geos-chem/commit/1e767e22e044a550f0b0569782d6fa50116b41f0
3.  https://github.com/geoschem/geos-chem-unittest/commit/481213b33c828a7b74bb76debb71f0a2f5a3c852

I will a unit test and diff test on these updates.  If OK, I'll merge into dev/12.7.0, so that it will ship with 12.7.0.

**Comment by yantosca** [comment]
A geosfp_4x5_benchmark diff test yielded identical results:

- Ref: https://github.com/geoschem/geos-chem/commit/0033a186af6a8ac7453a0b386a12c3da168f4e67
- Dev: https://github.com/geoschem/geos-chem/commit/1e767e22e044a550f0b0569782d6fa50116b41f0

```
###############################################################################
### VALIDATION OF GEOS-CHEM OUTPUT FILES
### Run ID: benchmark
##@
### IDENTICAL : HEMCO_restart.201607010100.nc.{Ref,Dev}
### IDENTICAL : GEOSChem.AdvFluxVert.20160701_0000z.nc4.{Ref,Dev}
### IDENTICAL : GEOSChem.AerosolMass.20160701_0000z.nc4.{Ref,Dev}
### IDENTICAL : GEOSChem.Aerosols.20160701_0000z.nc4.{Ref,Dev}
### IDENTICAL : GEOSChem.Budget.20160701_0000z.nc4.{Ref,Dev}
### IDENTICAL : GEOSChem.CloudConvFlux.20160701_0000z.nc4.{Ref,Dev}
### IDENTICAL : GEOSChem.ConcAfterChem.20160701_0000z.nc4.{Ref,Dev}
### IDENTICAL : GEOSChem.DryDep.20160701_0000z.nc4.{Ref,Dev}
### IDENTICAL : GEOSChem.JValues.20160701_0000z.nc4.{Ref,Dev}
### IDENTICAL : GEOSChem.LevelEdgeDiags.20160701_0000z.nc4.{Ref,Dev}
### IDENTICAL : GEOSChem.ProdLoss.20160701_0000z.nc4.{Ref,Dev}
### IDENTICAL : GEOSChem.SpeciesConc.20160701_0000z.nc4.{Ref,Dev}
### IDENTICAL : GEOSChem.StateChm.20160701_0000z.nc4.{Ref,Dev}
### IDENTICAL : GEOSChem.StateMet.20160701_0000z.nc4.{Ref,Dev}
### IDENTICAL : GEOSChem.Transport.20160701_0100z.nc4.{Ref,Dev}
### IDENTICAL : GEOSChem.WetLossConv.20160701_0000z.nc4.{Ref,Dev}
### IDENTICAL : GEOSChem.WetLossLS.20160701_0000z.nc4.{Ref,Dev}
### IDENTICAL : HEMCO_diagnostics.201607010000.nc.{Ref,Dev}
##%
###############################################################################

```

**Comment by JiaweiZhuang** [comment]
Could you upload a 3-hour KppDiags file (instantaneous field, with all 8 entries), so I can verity all entries on my own? An 8-variable NC file should be just a few MBs and can be uploaded as an attachment here. Thanks very much!

**Comment by yantosca** [comment]
The Unit Test on the feature/KPPDiags branch just passed. 

@JiaweiZhuang, here  is the file you wanted.  Let me know if it looks OK.  If it's good, I'll merge up to dev/12.7.0.   I had to gzip it to attach it here. 
[GEOSChem.KppDiags.20160701_0000z.nc4.gz](https://github.com/geoschem/geos-chem/files/3932702/GEOSChem.KppDiags.20160701_0000z.nc4.gz)

**Comment by JiaweiZhuang** [comment]
Thanks @yantosca !!

Below is the analysis of the file, from [this notebook](https://gist.github.com/JiaweiZhuang/10e80c34ebbe223ea34be55259166bcd). The result looks very reasonable and I suggest merging the branch. Thanks for the work😃!

The surface value shows hotspot over the continents and the terminator, which makes perfect sense:
![image](https://user-images.githubusercontent.com/25473287/70339007-ff9ec400-181b-11ea-812e-0e9363303b7c.png)

The column integrated value only highlights the terminator, consistent with my assumption and the Alvanos and Christoudias 2017 paper https://github.com/geoschem/gchp/issues/44#issuecomment-537037449
![image](https://user-images.githubusercontent.com/25473287/70339102-34128000-181c-11ea-9b0e-7b8730a3e19a.png)

The histogram shows a large spread (100~600), indicating a poor load-balancing. With a perfect balancing, there will be almost no spread. 
![image](https://user-images.githubusercontent.com/25473287/70339110-38d73400-181c-11ea-8f9c-bf9bd42289f5.png)

Different diagnostics are highly correlated (just differ by a constant factor), except the "rejected time steps":

![image](https://user-images.githubusercontent.com/25473287/70339120-412f6f00-181c-11ea-8d76-bcfbc7af4556.png)

**Comment by yantosca** [comment]
That's great! I'll merge the branch shortly.  I'll also test with GCHP to make sure that works.

Also -- I wonder why there are no singular matrix decompositions.  Maybe the Rosenbrock solver only uses LU decompositions exclusively?  We can comment that out in the HISTORY.rc since it's all zeroes.

**Comment by yantosca** [comment]
This is now merged into 12.7.0.  I'll close this out.

**Comment by JiaweiZhuang** [comment]
> I wonder why there are no singular matrix decompositions

Most solver options use sparse LU decomp for linear solve (Ax=b); not sure which solver uses SVD though.

**Comment by JiaweiZhuang** [comment]
> @JiaweiZhuang, here is the file you wanted. Let me know if it looks OK. If it's good, I'll merge up to dev/12.7.0. I had to gzip it to attach it here.

Hi @yantosca -- to double check: Is this a time-average diagnostic or an instantaneous field? The sunrise/sunset looks too spread out, which makes me wonder whether it is a 3-hour average, not just a 20-minute chemical step.

**Comment by yantosca** [comment]
@JiaweiZhuang , you are right.  I think I gave you the 3-h field.

Here is instantaneous data  (2016/07/01 @ 00:00 UTC):

### Total KPP integrator counts @ surface
![jiawei_1](https://user-images.githubusercontent.com/5880296/72826398-c7760800-3c46-11ea-81f4-a4efef446927.png)

### Histogram
![jiawei_2](https://user-images.githubusercontent.com/5880296/72826418-ce9d1600-3c46-11ea-9c24-5090b7ca050f.png)

### Column-integrated KPP integrator counts
![jiawei_3](https://user-images.githubusercontent.com/5880296/72826435-d52b8d80-3c46-11ea-9e82-eeba7743e944.png)

### Column integrated histogram
![jiawei_4](https://user-images.githubusercontent.com/5880296/72826447-da88d800-3c46-11ea-9291-4fbd47874d4e.png)


As you can see, the terminator is much narrower, as would be expected for a 20min timestep.

Sorry for the confusion.

**Comment by JiaweiZhuang** [comment]
> Here is instantaneous data

Thanks! This looks right to me. Could you also upload the nc file?

**Comment by yantosca** [comment]
@JiaweiZhuang, here it is, saved in a zip folder: [KppDiags.zip](https://github.com/geoschem/geos-chem/files/4093433/KppDiags.zip)

This is also available on S3 at:
https://s3.console.aws.amazon.com/s3/object/yantosca-gc-bucket/for_jiawei/GEOSChem.KppDiags.20160701_0000z.nc4?region=us-east-1&tab=overview
