### ISSUE TITLE
[BUG/ISSUE]Extremely high ozone and wrong latitude range on full-chem simulation in nested grid

### ISSUE THREAD

**Issue by xiaoyu-ss** [geoschem/geos-chem#771]
### Description of the problem
I am running nested grid full-chem simulation on GEOS-Chem v13, and ozone is one of the gases I'm interested in. Since the location that I need to study is at 7.5 N, 134E, I set the latitude and longitute range in -5 to 19 and 124 to 142, and set the Buffer Zone as ''3 3 3 3'' in the input file. However, I found that the latitude range is very wierd shown both in the SpeciesConc output file and the log file, which is 

> -89.875   -4.500   -4.000   -3.500   -3.000   -2.500   -2.000   -1.500
>   -1.000   -0.500    0.000    0.500    1.000    1.500    2.000    2.500
>    3.000    3.500    4.000    4.500    5.000    5.500    6.000    6.500
>    7.000    7.500    8.000    8.500    9.000    9.500   10.000   10.500
>   11.000   11.500   12.000   12.500   13.000   13.500   14.000   14.500
>   15.000   15.500   16.000   16.500   17.000   17.500   18.000   18.500
>   89.875

So the question is that why it includes the latitudes ''-89.875'' and ''89.875'' which I did not set this range in my input file.

Also, ozone concentrations appear to be particularly upper troposphere for some time periods, compared with global simulations. 

![glob_0121_29](https://user-images.githubusercontent.com/80622781/124457284-e9f0d800-dd8b-11eb-8552-ac85cbe5c0f3.png)
![20x24_0121_29](https://user-images.githubusercontent.com/80622781/124457288-ea896e80-dd8b-11eb-988c-8a89af3c3c87.png)
This is one example of the comparison of the simulation on global 2x2.5 and nested 0.5x0.625 grid. 

![simulation18x2401-01_global](https://user-images.githubusercontent.com/80622781/124457311-f2491300-dd8b-11eb-983e-9b2a54d3cb91.png)
![simulation18x2401-01](https://user-images.githubusercontent.com/80622781/124457313-f2e1a980-dd8b-11eb-8a61-86a286b7dded.png)

This is another example, which shows the simulation results of the nested grid at the site of interest from January to February 2016. It can be seen that there are also particularly high ozone concentrations in the middle troposphere, which is very different from the global simulation results.

I don't know how this happened, is there something wrong with the latitude range that caused the simulation to have some problems? Or is there something wrong with my setup?

Thanks a lot for your time.

### GEOS-Chem version
version 13.0.0

### Description of modifications
I don't think I made some modifications.

### Log files
- Run logs (if applicable):
[input.geos.txt](https://github.com/geoschem/geos-chem/files/6763614/input.geos.txt)
[slurm-6064604.out.txt](https://github.com/geoschem/geos-chem/files/6763615/slurm-6064604.out.txt)
[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/6763626/HEMCO_Config.rc.txt)

### Software versions
- CMake version: 3.16.2
- Compilers (Intel or GNU, and version): gcc/9.3.0
- NetCDF version: netcdf-parallel/ompi/gcc.9/4.7.4

**Comment by xiaoyu-ss** [comment]
I found out what went wrong, I fixed the problem, so I closed it.

**Comment by yantosca** [comment]
Thanks for the update @xiaoyu-ss.  Could I ask you to post the solution here so that others who read this issue will know what you did?  Thanks!

**Comment by lfreese** [comment]
@xiaoyu-ss @yantosca Is there a solution to this issue? We are coming across the same problem when running the nested grid over North America, with extremely high values on the edges of runs. I use v12.9.3, but a labmate using 13.1.1 is also facing the same problems. I'm attaching images of our ozone below. The first is April, May 2016 with 12.9.3 and the second is March 2013. 
<img width="809" alt="Screen Shot 2021-08-13 at 9 33 06 AM" src="https://user-images.githubusercontent.com/50365319/129365145-e4c4c17b-998b-4ac0-aadc-77c7f5a547d7.png">
![image (1)](https://user-images.githubusercontent.com/50365319/129365162-4196accc-a104-45cb-a3d0-be322aada0f1.png)
