### ISSUE TITLE
[QUESTION] Process raw GEOS-FP data for GEOS-Chem

### ISSUE THREAD

**Issue by febfly** [geoschem/geos-chem#775]
Hello, I try to run a simulation for a very recent date (June 2021) but could not find the GEOS-Chem ready GEOS-FP data for download. I wonder if there is a tool that I can use to prepare the raw GMAO GEOS-FP files for GEOS-Chem simulations. Thanks!
-Yuzhong

**Comment by yantosca** [comment]
Thanks @febfly for writing.  @YanshunLi-washu is the one who downloads the meteorological data, so I will let him reply.

I do know that sometimes the data processing runs a little behind real-time.

**Comment by YanshunLi-washu** [comment]
Thanks Bob @yantosca Hi @febfly, there is a recent slowness issue in the compute canada cluster  https://github.com/geoschem/geos-chem/issues/758#issuecomment-868847345. We'll process the GEOS-FP June data and upload them to a new site here https://geoschemdata.ris.wustl.edu ASAP (should be available within two weeks). Hope you could understand and apology for any inconveniences.

**Comment by febfly** [comment]
Thanks for the information! @YanshunLi-washu

**Comment by yantosca** [comment]
Note that you should now be able to download data from https://geoschemdata.wustl.edu.  If you have Globus, there is an endpoint called "GEOS-Chem data (WashU)" on that server.  That should be faster than ComputeCanada.

I will close out this issue for now.  Let us know if you are still having issues.

**Comment by febfly** [comment]
Thanks Bob! That's really good to know.
