### ISSUE TITLE
[QUESTION] nested run over the equator(latitude grid: -11.0 - 55.0N)

### ISSUE THREAD

**Issue by dorosieun** [geoschem/geos-chem#781]
### Ask a question about GEOS-Chem:

Hi :>
I try to run nested run using GEOSChem v13.0.0.
The met field is GEOS_FP 0.25x0.3125.
I want to run Asia domain, which has latitude over equator(-11.0 to 55.0) -> GEOS_FP 0.25x0.3125 Asia domain
It works well by editing latitude from 0.0 to 55.0 in the input.geos file(as below).

![스크린샷 2021-07-15 오후 2 21 37](https://user-images.githubusercontent.com/87462290/125733212-6290939c-8239-46b9-8e0d-ad7180201661.png)

But, with -11.0 to 55.0, it doesn't work.
Log of gcclassic  just stopped at the line which means reading boundary condition.
(For reference, if the latitude grid is 0.0-55.0, it works well with the same boundary condition file.)
![스크린샷 2021-07-15 오후 2 26 08](https://user-images.githubusercontent.com/87462290/125733558-7d888b67-e214-4f97-97fd-c3a7f7930684.png)

What is the problem? How can I do?

Thank you.

**Comment by yantosca** [comment]
Thanks for writing @dorosieun.  Can you do the following:
```console
ncdump -cts .../testrun_global/OutputDir/GEOSChem.BoundaryConditions.20200716_0000z.nc4
```
and then paste the lon and lat values into this issue? What might be happening is that your boundary conditions file might not covert the entire nested grid domain that you are using.

Also, you will want to make sure that you have enough memory allocated for the job.  If you are running GEOS-Chem with a scheduler like SLURM or PBS, you can usually select how much memory you want to allocate for the job.  If you are running on an AWS cloud instance, then you might need to pick an instance like c5.4xlarge or c5.8xlarge to have enough memory.

**Comment by dorosieun** [comment]
Thanks @yantosca. 
This is the lon, lat values of the boundary file.
![스크린샷 2021-07-16 오전 9 15 22](https://user-images.githubusercontent.com/87462290/125873433-a20db398-33ee-4116-8eb7-883e03f73653.png)
It seems no problem to cover the nested grid domain that I want to run.

I will run this with PBS. The setting is OMP_NUM_THREADS=36, OMP_STACKSIZE=500m. It works for global running and other nested grid domain running(0.25x0.3125 CH).

**Comment by dorosieun** [comment]
I tried running the nested region model separately with lat 0-55N and lat -15-0.0. The first one worked well, but the second one(lat -15-0.0) stopped just after beginning time stepping.(below)
![스크린샷 2021-07-16 오후 4 31 10](https://user-images.githubusercontent.com/87462290/125909665-ed42d4f0-2b4a-4741-9c5d-d0c9406a023c.png)

**Comment by yantosca** [comment]
Thanks @dorosieun.  Do you know how much memory you have available to you in your PBS queue?  You might be running in a queue that has less memory that you need for a nested simulation.  Ask someone who knows the particulars of your cluster.

**Comment by dorosieun** [comment]
Thanks @yantosca. 
What do you think about separated run? 
I run the upper part (lat: 0-55) and the lower part (lat: -15-0) separately, and the upper part worked well, but the lower part stopped. 
I think the lower part needs less memory than the upper part because of the domain area.

**Comment by dorosieun** [comment]
Thanks @yantosca. 
I made a mistake on latitude range. The met field domain(GEOS_FP) of Asia is from -11 to 55. 
After editing the latitude range, the separated run worked.(both upper and lower)
But, there is still a problem with the whole nested domain run.
I changed OMP_STACKSIZE from 500m to 2g, but it stopped at the same line of log.
I keep trying to find solution.. :(

**Comment by yantosca** [comment]
Thanks @doriesun for the feedback.  I still think it may be something to do with your cluster.  Maybe you do not have enough memory availble to run this nested simulation.

**Comment by lizziel** [comment]
Hmm, if -11.0 - 0.0 and 0.0 - 55.0 both finished to completion, but -11.0 to 55.0 did not, how about trying a smaller range that also straddles the latitude, such as -5.0 - 5.0? Also, have you checked the HEMCO log file?

**Comment by yantosca** [comment]
@dorosieun: Please see [this comment](https://github.com/geoschem/geos-chem/issues/798#issuecomment-890026756) in issue #788 for a possible solution.  A recent modification for the GCAP2 met fields introduced a side-effect that corrupted the nested-grid cropped grid definition.

**Comment by dorosieun** [comment]
Thank you @lizziel. 
I have already checked the HEMCO log file and tried a smaller but latitude-crossing range, and the two have no problems.
My conclusion is that the memory problem seems to be right. 
-5 to 45 range were possible, but not -11 to 55.

**Comment by dorosieun** [comment]
Thanks @yantosca for your kind and speedy advice.
I asked a person who knows cluster well and checked available memory on my system. I think it is impossible to get more memory. 
I think I have to reduce the domain to run the nested model.
