### ISSUE TITLE
[BUG/ISSUE] how to get this file '/CHEM_INPUTS/RRTMG_201411/species_clim_profiles.025x03125'

### ISSUE THREAD

**Issue by BownsC** [geoschem/geos-chem#782]
### Description of the problem

When I ran the module ‘geosfp_025x03125_RRTMG_ch’ , it was not able to process as expected because the file ‘~/gcgrid/ExtData/CHEM_INPUTS/RRTMG_201411/species_clim_profiles.025x03125’ is missing. 
I couldn’t find this file in my compute as well as in website Compute Canada archive : Index of /ExtData/CHEM_INPUTS/RRTMG_201411 (computecanada.ca). there are just 2x25 and 4x5 file in this website .(http://geoschemdata.computecanada.ca/ExtData/CHEM_INPUTS/RRTMG_201411/) 

Could you tell me how to get this file, and if i get this file and use it to run China area('geosfp_025x03125_RRTMG_ch',70-140°E,15-55°N) ,whether i need to modify this file's  data/longitude and latitude  range to fit China area or not .

### Description of troubleshooting performed

 firstl,  the module 'geosfp_025x03125_RRTMG_ch' can compile and produce 'geos.mp' successfully.
when i submit the task  of  'geosfp_025x03125_RRTMG_ch', because i want to use RRTMG module to get radiative forcing about China 2016 year,the task processed in a while, and it was stopped for could not find this file---ExtData/CHEM_INPUTS/RRTMG_201411/species_clim_profiles.025x03125

### GEOS-Chem version
12.0.0

### Log files
- Build log (if applicable):[lastbuild.txt](https://github.com/geoschem/geos-chem/files/6821767/lastbuild.txt)
- Run logs (if applicable):[run_log.txt](https://github.com/geoschem/geos-chem/files/6821793/run_log.txt)
- Run script (if applicable):
[run_script.txt](https://github.com/geoschem/geos-chem/files/6821980/run_script.txt)

### Software versions
- CMake version:  v10-01i
- Compilers (Intel or GNU, and version): v 3.2
- NetCDF version: v6.40

**Comment by yantosca** [comment]
Thanks for writing @BownsC.  The version that you are using (12.0.0) with RRTMG can only support either 2 x 2.5 or 4 x 5 grids. This is because the data files in the `CHEM_INPUTS/RRTMG_201411` folder are in bpch format.

I would recommend updating to the current stable version of GEOS-Chem (13.1.2).  We have since migrated the RRTMG input files to netCDF format, which can be read and regridded by HEMCO.  Also this version contains some important fixes for RRTMG that were made since 12.0.0.

**Comment by yantosca** [comment]
I am going to close out this issue for now.  Please let us know if you have any further questions.

**Comment by BownsC** [comment]
I'm really grateful for your reply which have solved my question successfully ,meanwhile,i want to make an apology for  i didn't reply your answer as soon as possible,because there was something wrong with my internet and then I forgot about it.Think you and best wish to you
