### ISSUE TITLE
[QUESTION] Applying scaling factors to lightning NOx and BB emissions

### ISSUE THREAD

**Issue by zsx-GitHub** [geoschem/geos-chem#783]
### Ask a question about GEOS-Chem:
Dear GCST,
I am trying to apply scale factors to the 'non-emissions data' in HEMCO but got a little confused. Could anyone help me with this?
When scaling lightning NOx down by 20%, I added ` --> Scaling_NO` as below:
```
103     LightNOx               : on    NO    
    --> CDF table              :       $ROOT/LIGHTNOX/v2014-07/light_dist.ott2010.dat
    --> Scaling_NO             :       0.8
```
Is this correct?
But what if I want to scale all emission species in the biomass burning sector down by 20%?
Thank you.

**Comment by yantosca** [comment]
Thanks for writing @zsx-GitHub.  As far as I know, I believe it is correct to add e.g. `--> Scaling NO` etc. to the lightning and BB entries in HEMCO_Config.rc.

You could also define a constant scale factor of 0.8 in the SCALE FACTORS section, and then add that to each entry that you would like to scale.

Also tagging @msulprizio @elundgren.

**Comment by msulprizio** [comment]
@zsx-GitHub Were you able to address your scaling concerns?

Some other resources to check out include:

- [HEMCO User's Guide: Build-in tools for scaling/masking](http://wiki.seas.harvard.edu/geos-chem/index.php/The_HEMCO_User%27s_Guide#Built-in_tools_for_scaling.2Fmasking)
- [Applying scale factors to non-emissions data](http://wiki.seas.harvard.edu/geos-chem/index.php/HEMCO_examples#Applying_scale_factors_to_non-emissions_data)
