### ISSUE TITLE
[QUESTION] What is the easiest way to output diagnostics of components of PM2.5 and AOD?

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/geos-chem#79]
Hi All,

I am running GC 12.2.1 to collect PM2.5, AOD, and their components, but I found that I can only define some of them in [HISTORY.rc](http://wiki.seas.harvard.edu/geos-chem/index.php/History_collections_for_aerosols). I have searched the `aerosol_mod.F` file and found the following codes that I believe is most relevant to PM2.5 components.
```
#if defined( MODEL_GEOS )
         ! PM2.5 sulfates
         IF ( State_Diag%Archive_PM25su ) THEN
            State_Diag%PM25su(I,J,L) = ( SO4(I,J,L) * SIA_GROWTH  )
     &                               * ( 1013.25_fp / PMID(I,J,L) )
     &                               * ( T(I,J,L)   / 298.0_fp    )
     &                               * 1.0e+9_fp
         ENDIF

         ! PM2.5 nitrates
         IF ( State_Diag%Archive_PM25ni ) THEN
            State_Diag%PM25ni(I,J,L) = ( NH4(I,J,L) * SIA_GROWTH
     &                               +   NIT(I,J,L) * SIA_GROWTH  )
     &                               * ( 1013.25_fp / PMID(I,J,L) )
     &                               * ( T(I,J,L)   / 298.0_fp    )
     &                               * 1.0e+9_fp
         ENDIF
         ! PM2.5 BC
         IF ( State_Diag%Archive_PM25bc  ) THEN
            State_Diag%PM25bc(I,J,L) = ( BCPI(I,J,L) + BCPO(I,J,L) )
     &                               * ( 1013.25_fp  / PMID(I,J,L) )
     &                               * ( T(I,J,L)    / 298.0_fp    )
     &                               * 1.0e+9_fp
         ENDIF
         ! PM2.5 OC
         IF ( State_Diag%Archive_PM25oc  ) THEN
            State_Diag%PM25oc(I,J,L) = ( OCPO(I,J,L)
     &                               +   OCPI(I,J,L) * ORG_GROWTH  )
     &                               * ( 1013.25_fp  / PMID(I,J,L) )
     &                               * ( T(I,J,L)    / 298.0_fp    )
     &                               * 1.0e+9_fp
         ENDIF
         ! PM2.5 dust
         IF ( State_Diag%Archive_PM25du  ) THEN
            State_Diag%PM25du(I,J,L) = ( SOILDUST(I,J,L,1)
     &                               +   SOILDUST(I,J,L,2)
     &                               +   SOILDUST(I,J,L,3)
     &                               +   SOILDUST(I,J,L,4)
     &                               +   SOILDUST(I,J,L,5) * 0.38  )
     &                               * ( 1013.25_fp  / PMID(I,J,L) )
     &                               * ( T(I,J,L)    / 298.0_fp    )
     &                               * 1.0e+9_fp
         ENDIF
         ! PM2.5 sea salt
         IF ( State_Diag%Archive_PM25ss  ) THEN
            State_Diag%PM25ss(I,J,L) = ( SALA(I,J,L) * ORG_GROWTH  )
     &                               * ( 1013.25_fp  / PMID(I,J,L) )
     &                               * ( T(I,J,L)    / 298.0_fp    )
     &                               * 1.0e+9_fp
         ENDIF
         ! PM2.5 SOA
         IF ( State_Diag%Archive_PM25soa ) THEN
            State_Diag%PM25soa(I,J,L) = ( TSOA(I,J,L)   * ORG_GROWTH
     &                                +   ISOA(I,J,L)   * ORG_GROWTH
     &                                +   ASOA(I,J,L)   * ORG_GROWTH
     &                                +   SOAS(I,J,L)   * ORG_GROWTH
     &                                +   ISOAAQ(I,J,L) * ORG_GROWTH  )
     &                                * ( 1013.25_fp    / PMID(I,J,L) )
     &                                * ( T(I,J,L)      / 298.0_fp    )
     &                                * 1.0e+9_fp
         ENDIF
#endif
```
I first tried to add `PM25su, PM25ni, and etc.` to `HISTORY.rc` but the model soon complained that these things have not been registered in `history_mod.F90`. In this sense, **could you suggest an easiest way to collect these things?**

I also wonder whether the practice that `State_Diag%PM25soa(I,J,L)` includes both SOAS and ISOAAQ would cause the double counting problem described in this [page](http://wiki.seas.harvard.edu/geos-chem/index.php/Particulate_matter_in_GEOS-Chem)? 

For PM2.5 components, I found the aforementioned codes contains sulfate, nitrate, bc, oc, dust, ss, soa? How about POA? I searched `AerMassPOA` in `aerosol_mod.F` and found the following.
```
           !--------------------------------------
         ! AerMassPOA [ug/m3], OA:OC=2.1
         !--------------------------------------
         IF ( State_Diag%Archive_AerMassPOA ) THEN
            IF ( Is_POA ) THEN
               State_Diag%AerMassPOA(I,J,L)   = OCPO(I,J,L)
     &                                        * kgm3_to_ugm3
            ELSE
               State_Diag%AerMassPOA(I,J,L)   = ( OCPI(I,J,L)
     &                                          + OCPO(I,J,L) )
     &                                          * kgm3_to_ugm3
            ENDIF
         ENDIF
```
Hence POA=OCPO+OCPI=OC? I almost got lost by these classification...

Regarding AOD, I believe I can only collect them using BPCH diagnostics like from [ND49](http://wiki.seas.harvard.edu/geos-chem/index.php/List_of_diagnostics_archived_to_bpch_format#ND49:_Instantaneous_timeseries)? Nevertheless, that list is somewhat incomplete. How could I collect nitrate AOD, POA AOD, SOA AOD, and etc. just like the practice in PM2.5? Does OC=POA+SOA?

BTW, when specifying `Tracers to include      :`, I believe I can find the number in `NDxx #` field [here](http://wiki.seas.harvard.edu/geos-chem/index.php/List_of_diagnostics_archived_to_bpch_format). I just want to confirm that the number for advected species is exactly the order they appear in `ADVECTED SPECIES MENU` in input.geos? Besides, **What's the main purpose of that MENU?**

**Comment by FeiYao-Edinburgh** [comment]
> could I easily add `PM25su`, `PM25ni`, and etc. to the list of `AerosolMass collection` in `HISTORY.rc` to collect PM2.5 components?

I have tried but the model complained that it could not locate PM25su diagnostics state registry. Do I need to change the code to collect these things? I think so but could you suggest the easiest way?



I believe I can only collect [BPCH diagnostics for AOD](http://wiki.seas.harvard.edu/geos-chem/index.php/List_of_diagnostics_archived_to_bpch_format#ND49:_Instantaneous_timeseries) since there is no netCDF-equivalent diagnostic in GEOS-Chem 12 for ND51 and ND51b. However, when I edit my input.geos, I did not know where to find the number for `Tracers to include      :` for my interested diagnostics. For instance, I tried `517` and the like listed in `ND49 #` field but the model complained bad integers....

**Comment by FeiYao-Edinburgh** [comment]
> Hi All,
> 
> I am running GC 12.2.1 to collect PM2.5, AOD, and **their components**, but I found that I can only define PM2.5 diagnostic in [HISTORY.rc](http://wiki.seas.harvard.edu/geos-chem/index.php/History_collections_for_aerosols). I have searched the `aerosol_mod.F` file and found the following codes that I believe is most relevant to PM2.5 components.
> 
> ```
> #if defined( MODEL_GEOS )
>          ! PM2.5 sulfates
>          IF ( State_Diag%Archive_PM25su ) THEN
>             State_Diag%PM25su(I,J,L) = ( SO4(I,J,L) * SIA_GROWTH  )
>      &                               * ( 1013.25_fp / PMID(I,J,L) )
>      &                               * ( T(I,J,L)   / 298.0_fp    )
>      &                               * 1.0e+9_fp
>          ENDIF
> 
>          ! PM2.5 nitrates
>          IF ( State_Diag%Archive_PM25ni ) THEN
>             State_Diag%PM25ni(I,J,L) = ( NH4(I,J,L) * SIA_GROWTH
>      &                               +   NIT(I,J,L) * SIA_GROWTH  )
>      &                               * ( 1013.25_fp / PMID(I,J,L) )
>      &                               * ( T(I,J,L)   / 298.0_fp    )
>      &                               * 1.0e+9_fp
>          ENDIF
>          ! PM2.5 BC
>          IF ( State_Diag%Archive_PM25bc  ) THEN
>             State_Diag%PM25bc(I,J,L) = ( BCPI(I,J,L) + BCPO(I,J,L) )
>      &                               * ( 1013.25_fp  / PMID(I,J,L) )
>      &                               * ( T(I,J,L)    / 298.0_fp    )
>      &                               * 1.0e+9_fp
>          ENDIF
>          ! PM2.5 OC
>          IF ( State_Diag%Archive_PM25oc  ) THEN
>             State_Diag%PM25oc(I,J,L) = ( OCPO(I,J,L)
>      &                               +   OCPI(I,J,L) * ORG_GROWTH  )
>      &                               * ( 1013.25_fp  / PMID(I,J,L) )
>      &                               * ( T(I,J,L)    / 298.0_fp    )
>      &                               * 1.0e+9_fp
>          ENDIF
>          ! PM2.5 dust
>          IF ( State_Diag%Archive_PM25du  ) THEN
>             State_Diag%PM25du(I,J,L) = ( SOILDUST(I,J,L,1)
>      &                               +   SOILDUST(I,J,L,2)
>      &                               +   SOILDUST(I,J,L,3)
>      &                               +   SOILDUST(I,J,L,4)
>      &                               +   SOILDUST(I,J,L,5) * 0.38  )
>      &                               * ( 1013.25_fp  / PMID(I,J,L) )
>      &                               * ( T(I,J,L)    / 298.0_fp    )
>      &                               * 1.0e+9_fp
>          ENDIF
>          ! PM2.5 sea salt
>          IF ( State_Diag%Archive_PM25ss  ) THEN
>             State_Diag%PM25ss(I,J,L) = ( SALA(I,J,L) * ORG_GROWTH  )
>      &                               * ( 1013.25_fp  / PMID(I,J,L) )
>      &                               * ( T(I,J,L)    / 298.0_fp    )
>      &                               * 1.0e+9_fp
>          ENDIF
>          ! PM2.5 SOA
>          IF ( State_Diag%Archive_PM25soa ) THEN
>             State_Diag%PM25soa(I,J,L) = ( TSOA(I,J,L)   * ORG_GROWTH
>      &                                +   ISOA(I,J,L)   * ORG_GROWTH
>      &                                +   ASOA(I,J,L)   * ORG_GROWTH
>      &                                +   SOAS(I,J,L)   * ORG_GROWTH
>      &                                +   ISOAAQ(I,J,L) * ORG_GROWTH  )
>      &                                * ( 1013.25_fp    / PMID(I,J,L) )
>      &                                * ( T(I,J,L)      / 298.0_fp    )
>      &                                * 1.0e+9_fp
>          ENDIF
> #endif
> ```
> 
> Hence comes my first question, could I easily add `PM25su`, `PM25ni`, and etc. to the list of `AerosolMass collection` in `HISTORY.rc` to collect PM2.5 components?
> 
> I also wonder whether the practice that `State_Diag%PM25soa(I,J,L)` includes both SOAS and ISOAAQ would cause the double counting problem described in this [page](http://wiki.seas.harvard.edu/geos-chem/index.php/Particulate_matter_in_GEOS-Chem)?
> 
> Regarding AOD, I believe I can only collect them from [ND49](http://wiki.seas.harvard.edu/geos-chem/index.php/List_of_diagnostics_archived_to_bpch_format#ND49:_Instantaneous_timeseries)? Nevertheless, that list is somewhat incomplete. How could I collect nitrate AOD, POA AOD, SOA AOD, and etc. just like the practice in PM2.5? Does OC=POA+SOA?

**Comment by christophkeller** [comment]
A while back, I added the speciated PM25 diagnostics so that I can use it within the GEOS-5 model, but bracketed that code with the `#MODEL_GEOS` compiler switch. So these parts of the code are currently only used if you compile with *MODEL_GEOS=yes*. In order to use these PM25 diagnostics outside of the GEOS model, you can try to simply remove the corresponding `#MODEL_GEOS` brackets in `aerosol_mod.F` and `state_diag_mod.F90` and then recompile.

**Comment by FeiYao-Edinburgh** [comment]
> In order to use these PM25 diagnostics outside of the GEOS model, you can try to simply remove the corresponding `#MODEL_GEOS` brackets in `aerosol_mod.F` and `state_diag_mod.F90` and then recompile.

Could you be clearer? Do you mean removing the following two lines, which are in lines 1063, 1124 and 970, 985 in `aerosol_mod.F90` and `state_diag_mod.F90`, respectively.
```
#if defined( MODEL_GEOS )
#endif
```

Since removing that, I think I can still compile the model without MODEL_GEOS=yes and can archive PM2.5 components in `HISTORY.rc`.

Just want to some more confirmation and will try soon!

**Comment by christophkeller** [comment]
Yes, exactly, this is what I meant. In `aerosol_mod.F90` this would be the statement between line 1066-1127. In `state_diag_mod.F90` there are 5 references to the speciated PM2.5 diagnostics, lines 293-308, 992-1007, 3928-4054, 7403-7452, 8763-8798.

**Comment by FeiYao-Edinburgh** [comment]
I use GC 12.2.1, so there might be some differences in line numbers from yours. Anyway, the logic is to remove `#if defined( MODEL_GEOS )` and `#endif` around speciated PM2.5 diagnostics in both `aerosol_mod.F90` and `state_diag_mod.F90`. Will report after testing. Thanks.

**Comment by FeiYao-Edinburgh** [comment]
> So these parts of the code are currently only used if you compile with _MODEL_GEOS=yes_.

Also curious that if I compile the model with _MODEL_GEOS=yes_, is it possible to collect/archive speciated PM2.5 outside GC without modifying the original codes?

**Comment by yantosca** [comment]
The ```MODEL_GEOS``` flag turns on code that is used to interface with the NASA-GEOS model.  It will probably break GEOS-Chem "Classic" if you turn it on.

**Comment by yantosca** [comment]
Also, you can feel free to add extra State_Diag fields for PM2.5.  We have just added those in order to replicate the output from the legacy BPCH ND42 diagnostics.

If you think that more fields should be added to the standard SOA diagnostics, then please feel free to bring that to the attention of the [ Aerosols Working Group ](http://wiki.geos-chem.org/Aerosols_Working_Group).

**Comment by FeiYao-Edinburgh** [comment]
> Will report after testing

Following the guide you provided, I have successfully output all the PM2.5 components defined in the code. I just have two remaining questions about some of these components.

1. I found that you add different SOA for different SOA mechanisms when calculating PM2.5, namely add SOAS for SimpleSOA and TSOA, ISOA, ASOA, ISOAAQ for ComplexSOA. However, I found the following code that confused me.
```
         ! PM2.5 SOA
         IF ( State_Diag%Archive_PM25soa ) THEN
            State_Diag%PM25soa(I,J,L) = ( TSOA(I,J,L)   * ORG_GROWTH
     &                                +   ISOA(I,J,L)   * ORG_GROWTH
     &                                +   ASOA(I,J,L)   * ORG_GROWTH
     &                                +   SOAS(I,J,L)   * ORG_GROWTH
     &                                +   ISOAAQ(I,J,L) * ORG_GROWTH  )
     &                                * ( 1013.25_fp    / PMID(I,J,L) )
     &                                * ( T(I,J,L)      / 298.0_fp    )
     &                                * 1.0e+9_fp
```
From this [page](http://wiki.seas.harvard.edu/geos-chem/index.php/Particulate_matter_in_GEOS-Chem), I believe that you have solved the double-counting problem of SOA in ComplexSOA mechanism? However, would including both SOAS and TSOA, ISOA, ASOA, ISOAAQ above cause another similar double-counting problem?

2. The PM2.5 components classification given from the model is somewhat different from my knowledge. Despite that different classifications exist for different study purpose, I personally think that aerosol/PM is usually classified into sulfate, nitrate, black carbon, dust, sea salt, organic aerosol. The organic aerosol can be further classified into primary organic aerosol (POA) and secondary organic aerosol (SOA). Therefore, I also got confused by the following codes.
```
         ! PM2.5 OC
         IF ( State_Diag%Archive_PM25oc  ) THEN
            State_Diag%PM25oc(I,J,L) = ( OCPO(I,J,L)
     &                               +   OCPI(I,J,L) * ORG_GROWTH  )
     &                               * ( 1013.25_fp  / PMID(I,J,L) )
     &                               * ( T(I,J,L)    / 298.0_fp    )
     &                               * 1.0e+9_fp
         ENDIF
         ! PM2.5 SOA
         IF ( State_Diag%Archive_PM25soa ) THEN
            State_Diag%PM25soa(I,J,L) = ( TSOA(I,J,L)   * ORG_GROWTH
     &                                +   ISOA(I,J,L)   * ORG_GROWTH
     &                                +   ASOA(I,J,L)   * ORG_GROWTH
     &                                +   SOAS(I,J,L)   * ORG_GROWTH
     &                                +   ISOAAQ(I,J,L) * ORG_GROWTH  )
     &                                * ( 1013.25_fp    / PMID(I,J,L) )
     &                                * ( T(I,J,L)      / 298.0_fp    )
     &                                * 1.0e+9_fp
         ENDIF
```
Does OC equal POA in some mechanisms, say complexSOA_SVPOA that I used? I am guessing this because I found the following codes and I think **`Is_POA=Is_complexSOA_SVPOA`?**
```
            ! Hydrophobic OC [kg/m3]
            ! SOAupdate: Treat either OCPO (x2.1) or POA (x1.4)
            IF ( IS_POA ) THEN
               OCPO(I,J,L) = ( Spc(I,J,L,id_POA1) + Spc(I,J,L,id_POA2) )
     &                       * OCFPOA(I,J) / AIRVOL(I,J,L)
            ELSE IF ( IS_OCPO ) THEN
               OCPO(I,J,L) = Spc(I,J,L,id_OCPO)
     &                       * OCFOPOA(I,J) / AIRVOL(I,J,L)
            ENDIF

            ! Hydrophilic OC [kg/m3]
            IF ( IS_OCPI ) THEN
               OCPI(I,J,L) = Spc(I,J,L,id_OCPI)
     &                       * OCFOPOA(I,J) / AIRVOL(I,J,L)
            ENDIF
```
and
```
         IF ( State_Diag%Archive_AerMassPOA ) THEN
            IF ( Is_POA ) THEN
               State_Diag%AerMassPOA(I,J,L)   = OCPO(I,J,L)
     &                                        * kgm3_to_ugm3
            ELSE
               State_Diag%AerMassPOA(I,J,L)   = ( OCPI(I,J,L)
     &                                          + OCPO(I,J,L) )
     &                                          * kgm3_to_ugm3
            ENDIF
```
If I am right that  `Is_POA=complexSOA_SVPOA`, then `AerMassPOA=POA` and it is just calculated through OCPO variable? When it is `not Is_POA`, then `AerMassPOA=OCPO+OCPI`. **Therefore, there seems no difference between POA, (OCPO and OCPI), they are all POAs (after applying OM/OC ratios) used under different context?** Frankly, I almost got lost with POA definitions in GEOS-Chem.

**Comment by FeiYao-Edinburgh** [comment]
> Also, you can feel free to add extra State_Diag fields for PM2.5.

I think I should be able to do that, but the difficulty lies in that I am absolutely not familiar with the GC codes that are in thousands of lines. Do you have a general picture of steps that I should follow when I want to add some more diagnostics that I am interested? For example, I am interested in nitrate AOD that, I think, is strangely missing in `Aerosols` diagnostics, I suppose I should edit `aerosol_mod`, `state_diag_mod.F90`, `CMN_SIZE_mod.F`, `diag51_mod.F`? I worried about this because even the model can successfully got run and give outputs without bugs, I do not dare to say that my edits give physically right answers. Or maybe you do have a wiki describing how to do things like adding more diagnostics that I have missed?

**Comment by yantosca** [comment]
I am not the best person to ask about SOA in the model, as I am not a chemist by training.  Perhaps @msulprizio could give you a better explanation than I can.

You are right that it is a bit confusing.  If you use the complex SOA scheme then OC is really POA, but if not, then OC is OCPI/OCPO.

**Comment by yantosca** [comment]
We do indeed have a Guide to [GEOS-Chem History diagnostics.](http://wiki.geos-chem.org/Guide_to_GEOS-Chem_History_diagnostics)   There is a section on how to [add new diagnostics](http://wiki.geos-chem.org/Adding_new_History_diagnostics) as well.

**Comment by FeiYao-Edinburgh** [comment]
> There is a section on how to [add new diagnostics](http://wiki.geos-chem.org/Adding_new_History_diagnostics) as well.

Thanks! Will check it soon!

**Comment by FeiYao-Edinburgh** [comment]
> If you use the complex SOA scheme then OC is really POA, but if not, then OC is OCPI/OCPO

Thanks for your confirmation! I still would like to confirm the following items. @msulprizio 
1. Does `Is_POA` correspond to `complexSOA_SVPOA`?
2. When not complexSOA, OCPO/OCPI are counted as POA, which is calculated as OC in PM2.5 and archived as AerMassPOA?

I will go through some papers to check but your confirmation is very meaning for me. Thanks!

**Comment by FeiYao-Edinburgh** [comment]
> * Does `Is_POA` correspond to `complexSOA_SVPOA`?

I asked this for several times, could you please do me a favour helping confirm it as it will assist me better understand `aerosol_mod.F`.

**Comment by FeiYao-Edinburgh** [comment]
> 3\. The calculation of PM2.5 SOA includes both SOAS and TSOA, ISOA, etc. Is that reasonable?

To be consistent to PM25 calculation which uses a pair of `if...elseif...endif`, would it be great to update the PM25soa calculation as the follows? @yantosca @christophkeller 
```
         ! PM2.5 SOA      
         IF ( State_Diag%Archive_PM25soa ) THEN
			IF (Is_SimpleSOA) THEN
            State_Diag%PM25soa(I,J,L) = ( SOAS(I,J,L)   * ORG_GROWTH  )
     &                                * ( 1013.25_fp    / PMID(I,J,L) )
     &                                * ( T(I,J,L)      / 298.0_fp    )
     &                                * 1.0e+9_fp
			ELSEIF ( Is_ComplexSOA ) THEN
            State_Diag%PM25soa(I,J,L) = ( TSOA(I,J,L)   * ORG_GROWTH
     &                                +   ISOA(I,J,L)   * ORG_GROWTH
     &                                +   ASOA(I,J,L)   * ORG_GROWTH
     &                                +   ISOAAQ(I,J,L) * ORG_GROWTH  )
     &                                * ( 1013.25_fp    / PMID(I,J,L) )
     &                                * ( T(I,J,L)      / 298.0_fp    )
     &                                * 1.0e+9_fp
			ENDIF
         ENDIF
```

**Comment by msulprizio** [comment]
Sorry for the late reply. I was out of the office at the time that you posted your questions.

> Thanks for your confirmation! I still would like to confirm the following items. @msulprizio
> 
> 1. Does `Is_POA` correspond to `complexSOA_SVPOA`?
> 
> * I guess they are logical variables defined in advected species in `input.geos`? I believe `Is_POA` and `IS_POA` to some extent are the same since Fortran is case insensitive?

While it is correct that `Is_POA` should always be true when using `complexSOA_SVPOA`. They are not the same thing. ComplexSOA_SVPOA refers to the simulation type while `IS_POA` is typically uses to make sure the POA species are defined before doing a calculation to avoid array-out-of-bounds errors.

> 1. When not complexSOA, OCPO/OCPI are counted as POA, which is calculated as OC in PM2.5 and archived as AerMassPOA?

Correct. When not using complex SOA, OCPO and OCPI are added to PM2.5:

```
            ! Hydrophobic OC [kg/m3]
            ! SOAupdate: Treat either OCPO (x2.1) or POA (x1.4) 
            IF ( IS_POA ) THEN
               OCPO(I,J,L) = ( Spc(I,J,L,id_POA1) + Spc(I,J,L,id_POA2) )
     &                       * OCFPOA(I,J) / AIRVOL(I,J,L)
            ELSE IF ( IS_OCPO ) THEN
               OCPO(I,J,L) = Spc(I,J,L,id_OCPO)
     &                       * OCFOPOA(I,J) / AIRVOL(I,J,L)
            ENDIF

            ! Hydrophilic OC [kg/m3]
            IF ( IS_OCPI ) THEN
               OCPI(I,J,L) = Spc(I,J,L,id_OCPI)
     &                       * OCFOPOA(I,J) / AIRVOL(I,J,L)
            ENDIF

      ...

         ! Units: [kg/m3]
         PM25(I,J,L) = NH4(I,J,L)        * SIA_GROWTH
     &               + NIT(I,J,L)        * SIA_GROWTH
     &               + SO4(I,J,L)        * SIA_GROWTH
     &               + BCPI(I,J,L)
     &               + BCPO(I,J,L)
     &               + OCPO(I,J,L)
     &               + OCPI(I,J,L)       * ORG_GROWTH
     &               + SALA(I,J,L)       * SSA_GROWTH
     &               + SOILDUST(I,J,L,1)                 ! DST1
     &               + SOILDUST(I,J,L,2)                 ! DST1
     &               + SOILDUST(I,J,L,3)                 ! DST1
     &               + SOILDUST(I,J,L,4)                 ! DST1
     &               + SOILDUST(I,J,L,5) * 0.38          ! 38% of DST2
```

and output to the AerMassPOA diagnostic:

```
         !--------------------------------------
         ! AerMassPOA [ug/m3], OA:OC=2.1
         !--------------------------------------
         IF ( State_Diag%Archive_AerMassPOA ) THEN
            IF ( Is_POA ) THEN
               State_Diag%AerMassPOA(I,J,L)   = OCPO(I,J,L)            
     &                                        * kgm3_to_ugm3
            ELSE
               State_Diag%AerMassPOA(I,J,L)   = ( OCPI(I,J,L)          
     &                                          + OCPO(I,J,L) )        
     &                                          * kgm3_to_ugm3
            ENDIF
         ENDIF
```

> 2. The calculation of PM2.5 SOA includes both SOAS and TSOA, ISOA, etc. Is that reasonable?

We recommend users choose either the [simple SOA or complex SOA options](http://wiki.seas.harvard.edu/geos-chem/index.php/Secondary_organic_aerosols#SOA_schemes_in_v11-02_and_later), not both. SOAS will only be defined with simple SOA is used and TSOA, ISOA, and ASOA will only be defined for complex SOA. We only turn on both options for benchmarking, and in that case only simple SOA should go towards the PM2.5 calculation. In the current aerosol_mod.F:

```
         ! Include either simple SOA (default) or Complex SOA in
         ! PM2.5 calculation.  In simulations where both Simple SOA and
         ! Complex SOA species are carried (i.e. "benchmark"), then
         ! only the Simple SOA will be added to PM2.5, in order to avoid
         ! double-counting. (bmy, 5/11/18)
         IF ( Is_SimpleSOA ) THEN
            PM25(I,J,L) = PM25(I,J,L)
     &                  + SOAS(I,J,L)    * ORG_GROWTH
         ELSEIF ( Is_ComplexSOA ) THEN
            PM25(I,J,L) = PM25(I,J,L)
     &                  + TSOA(I,J,L)    * ORG_GROWTH
     &                  + ASOA(I,J,L)    * ORG_GROWTH
     &                  + ISOAAQ(I,J,L)  * ORG_GROWTH    ! Includes SOAGX+SOAMG

         ENDIF
```
