### ISSUE TITLE
[BUG/ISSUE] Restart file problems running default v13.1.0 simulations

### ISSUE THREAD

**Issue by LukeFakes** [geoschem/geos-chem#791]
### Description of the problem
I've been having issues trying to run 4x5 tropchem simulations which were previously fine in v12.7. To investigate the issue, I've been using as close to the default model config as possible. 

This has led to errors either:
- early on in the simulations, when HEMCO reads the Restart files and fails to find fields:
```
HEMCO ERROR: Cannot find file for current simulation time: ./GEOSChem.Restart.20160601_0000z.nc4 - Cannot get field SPC_ACET. Please check file name and time (incl. time range flag) in the config. file
ERROR LOCATION: HCOIO_READ (hcoio_read_std_mod.F90)
ERROR LOCATION: HCOIO_DataRead (hcoio_dataread_mod.F90)
ERROR LOCATION: ReadList_Fill (hco_readlist_mod.F90)
ERROR LOCATION: ReadList_Read (hco_readlist_mod.F90)
ERROR LOCATION: HCO_RUN (hco_driver_mod.F90)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
HEMCO ERROR: Error encountered in routine HCOIO_Read!
ERROR LOCATION: HCOIO_READ (hcoio_read_std_mod.F90)
ERROR LOCATION: HCOIO_DataRead (hcoio_dataread_mod.F90)
ERROR LOCATION: ReadList_Fill (hco_readlist_mod.F90)
ERROR LOCATION: ReadList_Read (hco_readlist_mod.F90)
ERROR LOCATION: HCO_RUN (hco_driver_mod.F90)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
HEMCO ERROR: Error in HCOIO_DATAREAD called from HEMCO ReadList_Fill: SPC_ACET
ERROR LOCATION: ReadList_Fill (HCO_ReadList_Mod.F90)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
HEMCO ERROR: Error in ReadList_Fill (1) called from HEMCO ReadList_Read
ERROR LOCATION: ReadList_Read (HCO_ReadList_Mod.F90)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

-------------------------------------------------------------------------------
HEMCO 3.0.0 FINISHED.
Warnings (level 1 or lower):      1
-------------------------------------------------------------------------------
(END)
```
- More often, later on in the simulation (e.g 8 months into a 24 month run),  where the model fails due to wet dep
```GEOS-Chem ERROR: Error encountered in wet deposition!
 -> at SAFETY (in module GeosCore/wetscav_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem ERROR: Error encountered in "Safety"!
 -> at Do_Complete_Reevap (in module GeosCore/wetscav_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem ERROR:
 -> at WetDep (in module GeosCore/wetscav_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem ERROR: Error encountered in "Wetdep"!
 -> at Do_WetDep (in module GeosCore/wetscav_mod.F90)
===============================================================================

===============================================================================
GEOS-CHEM ERROR: Error encountered in "Do_WetDep"!
STOP at  -> at GEOS-Chem (in GeosCore/main.F90)
===============================================================================
real 896.51
user 13129.60
sys 70.61
srun: error: node071: task 0: Exited with exit code 159
```

### Description of troubleshooting performed
I have tried:
- different v13.1.x versions, with the same result. 
-  modifying the default restart file time attributes with ncatted
- changing the `SPC_` restart field time cycle flag from `EFYO` to `CYS`
- using restart files for the same period from v12.7
- rebuilding with the debug option as in [788](https://github.com/geoschem/geos-chem/issues/788), however I do not get a core file.

### GEOS-Chem version
v13.1.0

### Description of modifications
`* SPC_           ./GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 SpeciesRst_?ALL?    $YYYY/$MM/$DD/$HH EFYO xyz 1 * - 1 1`

`* SPC_           ./GEOSChem.Restart.$YYYY$MM$DD_$HH$MNz.nc4 SpeciesRst_?ALL?    $YYYY/$MM/$DD/$HH CYS xyz 1 * - 1 1`

editing time attributes of GEOSChemRestart.20190701_0000z.nc4 to 2016

### Log files
- Build log :
[CMakeCache.txt](https://github.com/geoschem/geos-chem/files/6877998/CMakeCache.txt)
-Run logs:
[GEOS-Chem.Classic.geos.log](https://github.com/geoschem/geos-chem/files/6878000/GEOS-Chem.Classic.geos.log)
[HEMCO.log](https://github.com/geoschem/geos-chem/files/6878001/HEMCO.log)

### Software versions
- CMake version: 3.20.1
- Compiler: Intel 2021.2.0
- NetCDF version: 4.5.3

**Comment by yantosca** [comment]
Thanks for writing @LukeFakes.  In the 13.1.0 series, we modified the default behavior of the restart file read so that it would halt if the restart file date did not match the input.geos start date.  This was done as a fix for issue #648.  The idea is to stop the run if the restart files disagree and let the user take action (i.e. change the time cycle flag etc.)

The fault in wetdep might be due to an initialization issue.  If there are any species that are not present in the restart file, they will get set to a very small background value close to zero.  

One thing you could try is to grab one of the restart files from our 10-year benchmark with 13.0.0.   Those should be well-spun-up.  See the folder: http://ftp.as.harvard.edu/gcgrid/geos-chem/10yr_benchmarks/13.0.0/GCClassic/restarts/

**Comment by LukeFakes** [comment]
Thanks @yantosca, I'm trying the same run now with the appropriate restart and will see if that works.

**Comment by LukeFakes** [comment]
Hi @yantosca, a clean restart with [this file](http://ftp.as.harvard.edu/gcgrid/geos-chem/10yr_benchmarks/13.0.0/GCClassic/restarts/GEOSChem.Restart.20160101_0000z.nc4) fails with the same wet dep error.

**Comment by mje1398** [comment]
I don't think this is a restart file problem. Looking at the log file it is falling over at the top of the stratosphere?

**Comment by yantosca** [comment]
@msulprizio and I were wondering if the UCX P/L files that are used in the stratosphere when UCX=off may be too out of date for the currrent simulation.  One thing to do is to try using the GMI strat data files.

**Comment by LukeFakes** [comment]
Hi @yantosca ,  to use the GMI strat files do you turn off UCX in input.geos?

**Comment by msulprizio** [comment]
Hi @LukeFakes to switch between using UCX and GMI prod/loss rates, you can modify the settings in `HEMCO_Config.rc`:

```
# ----- NON-EMISSIONS DATA ------------------------------------
    --> UVALBEDO               :       true     # 1985
    --> CCM_STRAT_Bry          :       true     # 2007
    --> GMI_STRAT_OH           :       true     # 2005
    --> GMI_PROD_LOSS          :       false
    --> UCX_PROD_LOSS          :       true
    ...
```

**Comment by LukeFakes** [comment]
Hi @msulprizio. This problem is also present in nested grid runs using the same configs as their 4x5 simulation, even after testing with UCX vs GMI on. The error occurs at the first timestep with `DO_CLOUD_CONVECTION`. For info, these are the config and log files
[Files.zip](https://github.com/geoschem/geos-chem/files/7354465/Files.zip)
