### ISSUE TITLE
geos-chem 13.1.2 netcdf I/O (new user)

### ISSUE THREAD

**Issue by clearsky112** [geoschem/geos-chem#792]
**### Description of the problem**

I am a new user. 
1. I downloaded the code from https://github.com/geoschem/GCClassic
   git clone https://github.com/geoschem/GCClassic.git GCClassic.13
2. In the GCClassic.13 folder
    went to ./run and used createRunDir.sh to create a run directory
3. In the run directory
    run cmake commands and first had issue:

[100%] Linking Fortran executable ../bin/gcclassic
/data/mmb/raqm/work/repos/code/2018_SIP/libraries_intel19.1.3.304/nc4hdf5/lib/libnetcdf.a(libnchdf5_la-hdf5file.o): In function `nc4_enddef_netcdf4_file':
hdf5file.c:(.text+0x54c): undefined reference to `H5Fflush'

    I used the netcdf4+hdf5. I thought it might be hdf5 issue, so I switched netcdf to the netcdf libraries (without HDF5), then cmake worked and I could generate ./gcclassic

4. Then I did the dry-run test, using download_data.py and ./gcclassic --dryrun, everything looked ok. 

5. tested a case (not dry run). So I just run ./gcclassic, then I got issues:

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In Ncop_Rd, cannot open:  /home/ycui/ExtData/HEMCO/XIAO/v2014-09/C3H8_C2H6_ngas.geos.1x1.nc

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Code stopped from DO_ERR_OUT (in module NcdfUtil/m_do_err_out.F90) 

This is an error that was encountered in one of the netCDF I/O modules,
which indicates an error in writing to or reading from a netCDF file!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**### Description of troubleshooting performed**
no

**### GEOS-Chem version**
GEOS-Chem 13.1.2

**### Description of modifications**
no

**### Log files**

**### Software versions**
- cmake version 3.15.4
- intel/19.1.3.30
- netcdf library version 4.6.1

**Comment by yangzhenlin-hub** [comment]
Hello, how do you solve this problem?

**Comment by clearsky112** [comment]
> I re-downloaded the file and then it worked.

**Comment by yangzhenlin-hub** [comment]
好哒，谢谢您！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "geoschem/geos-chem"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月15日(星期二) 中午1:26
***@***.***&gt;;
抄送:&nbsp;"◇﹎兔.子~` ***@***.******@***.***&gt;;
主题:&nbsp;Re: [geoschem/geos-chem] geos-chem 13.1.2 netcdf I/O (new user) (#792)





  
I re-downloaded the file and then it worked.
