### ISSUE TITLE
[BUG/ISSUE] GEOS-Chem 13.1.2 netcdf I/O problem (new user)

### ISSUE THREAD

**Issue by clearsky112** [geoschem/geos-chem#793]
**### Description of the problem**

I am a new user. 
1. I downloaded the code from https://github.com/geoschem/GCClassic
   git clone https://github.com/geoschem/GCClassic.git GCClassic.13
2. In the GCClassic.13 folder
    went to ./run and used createRunDir.sh to create a run directory
3. In the run directory
    run cmake commands and first had issue:
```
[100%] Linking Fortran executable ../bin/gcclassic
/data/mmb/raqm/work/repos/code/2018_SIP/libraries_intel19.1.3.304/nc4hdf5/lib/libnetcdf.a(libnchdf5_la-hdf5file.o): In function `nc4_enddef_netcdf4_file':
hdf5file.c:(.text+0x54c): undefined reference to `H5Fflush'
```
I used the netcdf4+hdf5. I thought it might be hdf5 issue, so I switched netcdf to the netcdf libraries (without HDF5), then cmake worked and I could generate ./gcclassic

4. Then I did the dry-run test, using download_data.py and ./gcclassic --dryrun, everything looked ok. 

5. tested a case (not dry run). So I just run ./gcclassic, then I got issues:
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In Ncop_Rd, cannot open:  /home/ycui/ExtData/HEMCO/XIAO/v2014-09/C3H8_C2H6_ngas.geos.1x1.nc

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Code stopped from DO_ERR_OUT (in module NcdfUtil/m_do_err_out.F90) 

This is an error that was encountered in one of the netCDF I/O modules,
which indicates an error in writing to or reading from a netCDF file!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
**### Description of troubleshooting performed**
no

**### GEOS-Chem version**
GEOS-Chem 13.1.2

**### Description of modifications**
no

**### Log files**

**### Software versions**
- cmake version 3.15.4
- intel/19.1.3.30
- netcdf library version 4.6.1

**Comment by Alex-Fang66** [comment]
You can try to re-download the nc file of "/HEMCO/XIAO/v2014-09/C3H8_C2H6_ngas.geos.1x1.nc", and replace the old one.

**Comment by yantosca** [comment]
Thanks for writing @clearsky112.  I think you are using a netCDF version, which does not have the HDF5 library installed.  That is why you are getting that error.

I would ask your sysadmin if there is a netCDF-4 version with HDF5 on your system.  If not, you can install one with Spack by following these instructions in Issue #637.

**Comment by clearsky112** [comment]
Thank you!
1. I tried to re-download/replace the nc file but it didn't work
2. I tried the netcdf -4 with HDF5, but can't compile the model. It shows errors as below:
 /opt/ohpc/pub/utils/intelv18.0.3.222/mmb35wrf/lib/libnetcdf.a(libnetcdf4_la-error4.o): In function `nc_log_hdf5':
error4.c:(.text+0x153): undefined reference to `H5Eprint1'
/opt/ohpc/pub/utils/intelv18.0.3.222/mmb35wrf/lib/libnetcdf.a(libnetcdf4_la-nc4file.o): In function `att_read_var_callbk':
nc4file.c:(.text+0xb6): undefined reference to `H5Aopen'
nc4file.c:(.text+0x1c5): undefined reference to `H5Aget_type'
nc4file.c:(.text+0x1db): undefined reference to `H5Tget_native_type'
nc4file.c:(.text+0x1f1): undefined reference to `H5Tget_class'
nc4file.c:(.text+0x238): undefined reference to `H5Tget_class'
nc4file.c:(.text+0x259): undefined reference to `H5open'

Seems it didn't find hdf5 libraries, where can I add hdf5 libs info in the cmake files? I tried to add them to CMakeCache.txt, but didn't work. 
Thanks.

**Comment by clearsky112** [comment]
I solved this issue, although i don't know whether it's the best way. 
I added *hdf5 libs paths to */build/src/CMakeFiles/gcclassic.dir/link.txt  and the model is compiled (with netcdf-4+hdf5)

**Comment by yantosca** [comment]
Thanks @clearsky112.  You shouldn't have to modify the CMakeFiles.  You can try adding the path to hdf5 libraries to your `LD_LIBRARY_PATH` environment variable.  Also, if your system uses the `module load` command, you might have to do something like
```
module load hdf5
module load netcdf
```
etc.  You can ask your sysadmin for more information.

I'll close out this issue for now.  Feel free to reopen if you still have any problems.
