### ISSUE TITLE
[DISCUSSION] Implement a GEOS-Chem code of conduct?

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#805]
At a recent meeting on Diversity, Inclusion, and Belonging (DIB) at Harvard, one of the questions that came out of the discussion was "Should GEOS-Chem have a publicly displayed code of conduct?".   

Many open-source software packages and atmospheric models (such as CESM) have a code of conduct document on their Github repos stating that bullying and other forms of harassment will not be tolerated on electronic means of communication.  It also lists specifics on how harassers will be held accountable.

Here are a few examples with text that could be adapted for GEOS-Chem:

  1. [CESM Code of Conduct (at github.com/ESCOMP/CESM)](https://github.com/ESCOMP/CESM/blob/master/CODE_OF_CONDUCT.md)
  2. [Open Source Guide - Code of Conduct](https://opensource.guide/code-of-conduct/)
  3. [Contributor Covenant](https://www.contributor-covenant.org/)

I just wanted to open this discussion so that we don't lose sight of it.  Looking forward to your thoughts.

**Comment by djxjacob** [comment]
I don't feel strongly about this. It seems to be targeting a non-issue, so why bother? But if others think it's important then I have no objection
