### ISSUE TITLE
[BUG/ISSUE] GFAS biomass burning emissions not working in version 13.1.1 

### ISSUE THREAD

**Issue by Twize** [geoschem/geos-chem#806]
### Description of the problem
When switching on GFAS biomass burning emissions in version 13.1.1, no emissions are actually being injected into the model. GFED v4 appears to work fine and is injecting emissions correctly. 

### Description of troubleshooting performed
To confirm the issue, I have looked at the HEMCO biomass burning emissions diagnostics, and do not see any emissions at all when using GFAS. Looking at the same diagnostic when using GFED v4 displays reasonable emissions. 

Simulation using GFAS:
![CO_bioburn_emiss_GFAS_20170901](https://user-images.githubusercontent.com/26906734/127673455-7cd4037f-f4f3-4541-a62b-a8fd4a5d0079.png)

Identical simulation, but with GFED v4:
![CO_bioburn_emiss_GFED_20170901](https://user-images.githubusercontent.com/26906734/127673468-a23950e7-f28e-441e-a9dd-4b6edb7b8df7.png)

### GEOS-Chem version
GEOS-Chem Version 13.1.1, 2° x 2.5° resolution, GEOS-FP meteorology

### Description of modifications
No modifications made to the model. 

### Log files
[input.geos.txt](https://github.com/geoschem/geos-chem/files/6908540/input.geos.txt)
[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/6908555/HEMCO_Config.rc.txt)
[gc.log.txt](https://github.com/geoschem/geos-chem/files/6908559/gc.log.txt)

### Software versions
CMake version:
3.19.5

Compilers (Intel or GNU, and version):
Intel compiler v19.0.3.199 (UofT system)

NetCDF version:
4.2 (UofT system)

**Comment by msulprizio** [comment]
Hi @Twize. It looks like you may need to modify your HEMCO_Diagn.rc to properly output the biomass burning emissions. In that file by default, we have:

```
EmisCO_BioBurn     CO     111    -1  -1   2   kg/m2/s  CO_emission_flux_from_biomass_burning
```

where `111` corresponds to the GFED extensions number. The extension number for GFAS emissions is `0` (i.e. base emissions). You can determine this from the number in the first column of the GFAS entries in HEMCO_Config.rc:

```
0 GFAS_CO    $ROOT/GFAS/v2018-09/$YYYY/GFAS_$YYYY$MM.nc cofire        2003-2021/1-12/1-31\
/0 C xyL=1:scal300 kg/m2/s CO   75     5 3
```

Try changing `111` to `0` in HEMCO_Diagn.rc for all "BioBurn" emissions to see if that resolves the issue.

**Comment by kilicomu** [comment]
@msulprizio If this turns out to be an issue with the prepped emissions, drop me a line!

**Comment by Twize** [comment]
> Hi @Twize. It looks like you may need to modify your HEMCO_Diagn.rc to properly output the biomass burning emissions. In that file by default, we have:
> 
> ```
> EmisCO_BioBurn     CO     111    -1  -1   2   kg/m2/s  CO_emission_flux_from_biomass_burning
> ```
> 
> where `111` corresponds to the GFED extensions number. The extension number for GFAS emissions is `0` (i.e. base emissions). You can determine this from the number in the first column of the GFAS entries in HEMCO_Config.rc:
> 
> ```
> 0 GFAS_CO    $ROOT/GFAS/v2018-09/$YYYY/GFAS_$YYYY$MM.nc cofire        2003-2021/1-12/1-31\
> /0 C xyL=1:scal300 kg/m2/s CO   75     5 3
> ```
> 
> Try changing `111` to `0` in HEMCO_Diagn.rc for all "BioBurn" emissions to see if that resolves the issue.

Thanks @msulprizio, I will give that a try. However, I don't think it's only an issue with the diagnostics in this particular case. I am currently looking at comparisons with a ground-based FTIR in the Arctic, and it seems that when using GFAS, there is no influence of the wildfires on the CO total columns (see the plots below): 

Simulation using GFAS: 
![GC_v13_CO_raw_total_columns_EUR_2017(GFAS)](https://user-images.githubusercontent.com/26906734/128037436-8ee5f74d-4e78-47cb-a255-79cff2c87f93.png)

Same simulation, but using GFED v4: 
![GC_v13_CO_raw_total_columns_EUR_2017(GFED)](https://user-images.githubusercontent.com/26906734/128037493-50351ad5-43e7-4776-876f-33749e571608.png)

You can see that in the GFAS simulation, the CO total columns diverges quite drastically from the FTIR around June, when CO is a major driver of the CO seasonal cycle. However, in the GFED v4 simulation, it matches the FTIR quite nicely. 

Is it possible there is some other switch that I am missing for GFAS to ensure the emissions are being injected into the model correctly? Or is it maybe an issue with the prepared emissions?

**Comment by msulprizio** [comment]
I noticed from your GEOS-Chem log file the GFAS emissions for January 2017 seem to be read repeatedly, regardless of the simulation month:

```
---> DATE: 2017/01/02  UTC: 00:00  X-HRS:     24.000000
HEMCO: Opening /data/ctm/ExtData//HEMCO/GFAS/v2018-09/2017/GFAS_201701.nc
...
---> DATE: 2017/02/02  UTC: 00:00  X-HRS:    768.000000
HEMCO: Opening /data/ctm/ExtData//HEMCO/GFAS/v2018-09/2017/GFAS_201701.nc
...
---> DATE: 2017/03/02  UTC: 00:00  X-HRS:   1440.000000
HEMCO: Opening /data/ctm/ExtData//HEMCO/GFAS/v2018-09/2017/GFAS_201701.nc
...
```

Could you check your data directories to ensure you have the files beyond 2017/01 downloaded? It may be that HEMCO can't find the files for later dates, so it uses the closest date available. 

If that's not the culprit, I would recommend setting Verbose and Warnings to 3 in HEMCO_Config.rc and running a short simulation that straddles the month boundary to determine why HEMCO isn't updating the timestamp in the GFAS file.

**Comment by Twize** [comment]
> I noticed from your GEOS-Chem log file the GFAS emissions for January 2017 seem to be read repeatedly, regardless of the simulation month:
> 
> ```
> ---> DATE: 2017/01/02  UTC: 00:00  X-HRS:     24.000000
> HEMCO: Opening /data/ctm/ExtData//HEMCO/GFAS/v2018-09/2017/GFAS_201701.nc
> ...
> ---> DATE: 2017/02/02  UTC: 00:00  X-HRS:    768.000000
> HEMCO: Opening /data/ctm/ExtData//HEMCO/GFAS/v2018-09/2017/GFAS_201701.nc
> ...
> ---> DATE: 2017/03/02  UTC: 00:00  X-HRS:   1440.000000
> HEMCO: Opening /data/ctm/ExtData//HEMCO/GFAS/v2018-09/2017/GFAS_201701.nc
> ...
> ```
> 
> Could you check your data directories to ensure you have the files beyond 2017/01 downloaded? It may be that HEMCO can't find the files for later dates, so it uses the closest date available.
> 
> If that's not the culprit, I would recommend setting Verbose and Warnings to 3 in HEMCO_Config.rc and running a short simulation that straddles the month boundary to determine why HEMCO isn't updating the timestamp in the GFAS file.

Hi @msulprizio, good catch! I did not notice this previously. I checked on our servers and it does in fact look like only the January 2017 GFAS file is downloaded (not entirely sure why). This is likely the cause of the issue since there are probably no biomass burning emissions in the NH during January, I will download the full set GFAS files and re-run a couple months to confirm.

**Comment by msulprizio** [comment]
Great! I will close this issue for now, but please feel free to follow up here with the results or if any issues persist.
