### ISSUE TITLE
[BUG/ISSUE] nested run with Luo et al(2019) wet deposition

### ISSUE THREAD

**Issue by dorosieun** [geoschem/geos-chem#809]
### Description of the problem
I tried to run a nested model with the settings below.
![스크린샷 2021-08-03 오후 4 29 46](https://user-images.githubusercontent.com/87462290/127975558-53b6b11b-20a2-4ad0-8379-adc3c97d5ee4.png)
I turned on Luo et al.(2019) wet deposition option at compile step.(as you can see below)
![스크린샷 2021-08-03 오후 4 31 03](https://user-images.githubusercontent.com/87462290/127975723-885eb21b-7157-4577-8346-76f4c6344b2a.png)
First, I set the start time of run to 20200101 and the end time of run to 20200301.
It worked with no problem until 20200208 21:35.
At that time, log file showed the following error and stopped.
![스크린샷 2021-08-03 오후 4 34 12](https://user-images.githubusercontent.com/87462290/127976195-5dd18593-c926-4a29-aacf-ae96e038b172.png)
...
![스크린샷 2021-08-03 오후 4 34 31](https://user-images.githubusercontent.com/87462290/127976244-b279884c-9f67-4824-b20b-29eb484e0679.png)

I have set debugging option with the commend below.

cmake ../CodeDir 
cmake . -DCMAKE_BUILD_TYPE=Debug 
make -j

but nothing happened. I couldn't get the core file.

The log file and input.geos file attached below is the one used to re-run from 20200207 and the log file released at that time.

### GEOS-Chem version
GEOSChem v13.0.0

### Log files
[GC.log.txt](https://github.com/geoschem/geos-chem/files/6922120/GC.log.txt)
[HEMCO.log.txt](https://github.com/geoschem/geos-chem/files/6922121/HEMCO.log.txt)
[input.geos.txt](https://github.com/geoschem/geos-chem/files/6922122/input.geos.txt)

### Software versions
- CMake version: 3.13.4
- Compilers (Intel or GNU, and version): intel 15.0.0 
- NetCDF version:

**Comment by yantosca** [comment]
Thanks for writing @dorosieun.  The Luo et al 2019 wet deposition is kept as an option, but it was never really adopted because there were some issues with it scientifically.  We would recommend that you take GEOS-Chem 13.2.1 once it is released, which will contain the Luo et al 2020 wetdep scheme.  This will address some of the outstanding issues with the Luo et al 2019 wetdep scheme.

**Comment by yantosca** [comment]
Also it could be that the error you are seeing is due to default background concentrations (~1e-20) being used when e.g. SALAAL is not found in the restart file.

It could also be an out-of-bounds error.  Have you tried configuring GEOS-Chem with `-DCMAKE_BUILD_TYPE=Debug' and recompiling?  That might trap additional errors.

**Comment by dorosieun** [comment]
Thanks @yantosca. I already tried configuring GEOS-Chem with '-DCMAKE_BUILD_TYPE=Debug' and recompiling. But there is nothing different in log file.
Would it be different from 'Turn on debug printout? : T' in input.geos file?

**Comment by dorosieun** [comment]
I found the difference of code between v13.0.0 and before one(v12.8.0).
at v12.8.0 DO_TEND module in GeosCore/mixing_mod.F90 code :
![스크린샷 2021-08-05 오후 4 28 21](https://user-images.githubusercontent.com/87462290/128309540-9a0e4c25-ac86-4ffc-b989-58a3acc56d75.png)

at v13.0.0 DO_TEND module in GeosCore/mixing_mod.F90 code :
![스크린샷 2021-08-05 오후 4 29 06](https://user-images.githubusercontent.com/87462290/128309639-3c8dfbf5-93be-499f-8d65-958e305adda4.png)

Can I just change 
! Check for negative concentrations ... part(v13.0.0) 
to ! Prevent negative concentrations. (ckeller, 3/29/16) ...(v12.8.0)?

**Comment by yantosca** [comment]
@dorosieun, thanks for the feedback.  We put in an error to stop the run to make sure that people would be aware of the issue,   

If it helps, you can reset the negatives to zero.  But first, try to reduce the transport timestep from 300 seconds to 150 and see if that fixes the issue.

**Comment by dorosieun** [comment]
Thanks @yantosca. I did as you told me(reduce the transport timestep) and the part where the error occurred went over(it works). But can we say that the result is the same even if the time step changes?

**Comment by dorosieun** [comment]
Thanks @yantosca. I had similar problem when I ran with MERRA2 0.5x0.625 Met Field from 20200101 to 20200301. And it solved with a smaller timestep you said.
Additionally, I did the model run with the same setting but from 20200701 to 20200901. There is no such problem.
I guess it only happens for the winter season.

**Comment by yantosca** [comment]
Thanks @dorosieun for the feedback.

Also take a look at https://github.com/geoschem/geos-chem/issues/798#issuecomment-890026756.  There was a typo that caused nested-grid simulations to sometimes have weird behavior (probably due to an out-of-bound error).  This will be fixed in GEOS-Chem 13.2.1.

**Comment by yantosca** [comment]
I will close out this issue for now. Please let us know if you are still having problems.
