### ISSUE TITLE
[QUESTION]Relationship between SO4 and SO4D1 - SO4D4 in Aciduptake Mechanisms 

### ISSUE THREAD

**Issue by yangxiajie** [geoschem/geos-chem#815]
There are multiple tracers of sulfate in  `SpeciesConc` from acid uptake mechanisms (SO4, SO4D1, .SO4D2, ..). Introduction from wiki  gave full names of them. However, I wonder if there is a quantitative relationship between them (e.g. SO4 = SO4D1 + SO4D2 + ...). If I want to calculate the concentration of aerosol sulfate in the simulated region, should I choose SO4 or SO4+SO4D1+SO4D2+... ?

**Comment by yantosca** [comment]
Thanks for writing @yangxiajie.  I think the SO4D1.. SO4D4 is sulfate taken up on dust aerosol.   I would defer to the Aerosols Working Group, who may be able to give you better information than I can. 

@theloniuspunk @beckyalexander

**Comment by theloniuspunk** [comment]
I would guess this as well. Becky may know better.
