### ISSUE TITLE
[BUG/ISSUE] Infinity in DO_CLOUD_CONVECTION! while running tagged  ozone simulation.

### ISSUE THREAD

**Issue by map06** [geoschem/geos-chem#821]
### Description of the problem

I am running GEOS-Chem tagged simulation in 4 by 5 degree resolution on cloud. But, whenever I run it, I get `Infinity in DO_CLOUD_CONVECTION! ` error.

### Description of troubleshooting performed

I checked issue #275  and #402. But, both of them seem to be related to nested grid and not for tagged simulation. 
Also, when I turned off transport, there is not any error.

### GEOS-Chem version
13.1.2

### Description of modifications

Haven't modified anything besides adding Production and loss file in the HEMCO from  4 by 5 degree full chemistry simulation.

### Log files
[log_file.zip](https://github.com/geoschem/geos-chem/files/6984134/log_file.zip)

### Software versions
- CMake version:  3.19.2
- Compilers (Intel or GNU, and version): GNU 8.2.0
- NetCDF version: 4.7.4

**Comment by yantosca** [comment]
Thanks for writing @map06.  Have you tried building GEOS-Chem with the debug flags (`-DCMAKE_BUILD_TYPE=Debug`)?  That might reveal further errors.

**Comment by map06** [comment]
@yantosca  Thank you for your reply. I think I understand now what's the problem. The unit of `Prod_Ox` and `Loss_Ox` that I obtained from the full chemistry simulation has units `kg/s`. 
```float Prod_Ox(time, lev, lat, lon) ;
		Prod_Ox:long_name = "Chemical production of Ox" ;
		Prod_Ox:units = "kg s-1" ;
		Prod_Ox:averaging_method = "time-averaged" ;
                float Loss_Ox(time, lev, lat, lon) ;
		Loss_Ox:long_name = "Chemical loss of Ox" ;
		Loss_Ox:units = "kg s-1" ;

```
But `tagged_o3_mod.F90` states 
```
   ! Get production and loss frequencies from HEMCO. The target
    ! will be updated automatically by HEMCO.
    !
    ! Important: the file data are converted by HEMCO to HEMCO
    ! concentration units, e.g. the imported data is in kg/m3
    ! (production) and 1/m3 (loss), e.g. the original data in
    ! units of kg/m3/s multiplied by the emission timestep.
```

So the units of production and loss values  must be in `kg/m3/s` and `1/m3/s`. I tried the older production and loss values that was available in the server, and the model ran successfully.

 Since the unit of my current production and loss values  is already in `kg/s` maybe I might just need to divide it by the volume of each grid box. But, I am not so sure if its the right way and if it's the right way how can I convert the pressure coordinate into altitude since the values are under pressure coordinate system ?

**Comment by yantosca** [comment]
Thanks for writing @map06.  So that might be a bit of legacy coding.  Now that we use the netCDF diagnostics the units of the prod/loss are `kg/s`.  The old bpch diagnostics saved in units of `kg/m3/s`.

To convert e.g. `kg/s` to `kg/m3/s` you can divide by `State_Met%AIRVOL`, which has units of m3.

**Comment by map06** [comment]
@yantosca  Thank you. I was able to convert the units to `kg/m3/s` after dividing it by `State_Met%AIRVOL`. But, the unit of loss should be `1/m3/s`.  So I still  need to divide  the loss by mass of `Ox`. Is there a way to  print out the mass of `Ox` directly, so that the units  are consistent?
```

**Comment by xpye98** [comment]
> @yantosca Thank you. I was able to convert the units to `kg/m3/s` after dividing it by `State_Met%AIRVOL`. But, the unit of loss should be `1/m3/s`. So I still need to divide the loss by mass of `Ox`. Is there a way to print out the mass of `Ox` directly, so that the units are consistent?

Hi, I found the same problem here, don't know how to calculate the mass of Ox. Have you solved that problem? Or any other idea that can fix it? @yantosca @map06

**Comment by map06** [comment]
@xpye98  I calculated the mass of Ox later using the formula used in the diag20 file from previous version, which automatically used to give output in the unit which is required. I modified the formula by using Ox formula present in gckpp. kpp. I downloaded the old version of GEOS-Chem from here https://zenodo.org/record/3507501.

Hopefully this is helpful.
