### ISSUE TITLE
error running GCHP at resolution c24

### ISSUE THREAD

**Issue by cbutenhoff** [geoschem/geos-chem#823]
### Description of the problem
In testing my build of GCHP 13.1.2 I am able to run the default full chemistry standard simulation at C48, i.e. the job completes successfully and writes the output netCDF files,  but when I change the resolution to C24 the job fails after reading in the restart file. I'll add the entire output log below but here are some snippets:

 
```
Character Resource Parameter: GCHPchem_INTERNAL_RESTART_FILE:+initial_GEOSChem_rst.c24_fullchem.nc
 WARNING: use of '+' or '-' in the restart name 'initial_GEOSChem_rst.c24_fullchem.nc' allows bootstrapping!
 Using parallel NetCDF for file: initial_GEOSChem_rst.c24_fullchem.nc
pe=00000 FAIL at line=07503    MAPL_IO.F90                              <status=-101>
pe=00000 FAIL at line=05941    MAPL_Generic.F90                         <status=-101>
```

```
 object: 311,name: STATE_PSC
            type: Field
     object: 312,name: T_DAVG
            type: Field
     object: 313,name: T_PREVDAY
            type: Field
pe=00000 FAIL at line=01627    MAPL_Generic.F90                         <unknown error>
pe=00000 FAIL at line=01600    Chem_GridCompMod.F90                     <status=-1>
pe=00000 FAIL at line=01839    MAPL_Generic.F90                         <needs informative message>
pe=00000 FAIL at line=01506    MAPL_Generic.F90                         <needs informative message>
pe=00000 FAIL at line=00330    GCHP_GridCompMod.F90                     <status=1>
pe=00000 FAIL at line=01839    MAPL_Generic.F90                         <needs informative message>
pe=00000 FAIL at line=00615    MAPL_CapGridComp.F90                     <status=1>
pe=00000 FAIL at line=00908    MAPL_CapGridComp.F90                     <status=1>
pe=00000 FAIL at line=00245    MAPL_Cap.F90                             <status=1>
pe=00000 FAIL at line=00211    MAPL_Cap.F90                             <status=1>
pe=00000 FAIL at line=00154    MAPL_Cap.F90                             <status=1>
pe=00000 FAIL at line=00129    MAPL_Cap.F90                             <status=1>
pe=00000 FAIL at line=00030    GCHPctm.F90                              <status=1>
     object: 314,name: TropLev
            type: Field
     object: 315,name: WetDepNitrogen
            type: Field
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 0.
```
I ran the C24 job exactly like C48, same run script, core count (12), etc., just the change to CS_RES in runConfig.sh

### Description of troubleshooting performed
I tested resolution C90 and that ran successfully.

The problem appears to happen when reading in the initial restart file. Since the log file mentions that parallel netcdf is being used I looked at the configuration of our netcdf libraries:

```
[cbuten@login2 GCHP]$ nc-config --all

This netCDF 4.8.0 has been built with the following features:

  --cc            -> /vol/apps/gcc/gcc-9.2.0/bin/gcc
  --cflags        -> -I/vol/apps/test/net-cdf/stow/net-cdf/4.8.0/include -I/include -I/include
  --libs          -> -L/vol/apps/test/net-cdf/stow/net-cdf/4.8.0/lib -lnetcdf
  --static        -> -lhdf5_hl -lhdf5 -lm -ldl -lz -lcurl

  --has-c++       -> no
  --cxx           ->

  --has-c++4      -> yes
  --cxx4          -> /vol/apps/gcc/gcc-9.2.0/bin/g++
  --cxx4flags     -> -I/vol/apps/test/net-cdf/stow/netcdf-cxx4/4.3.1/include -I/vol/apps/test/net-cdf/stow/net-cdf/4.8.0//include
  --cxx4libs      -> -L/vol/apps/test/net-cdf/stow/netcdf-cxx4/4.3.1/lib -lnetcdf_c++4 -lnetcdf

  --has-fortran   -> yes
  --fc            -> /vol/apps/gcc/gcc-9.2.0/bin/gfortran
  --fflags        -> -I/vol/apps/test/net-cdf/stow/netcdf-fortran/4.5.3/include -I/vol/apps/test/net-cdf/stow/netcdf-fortran/4.5.3/include
  --flibs         -> -L/vol/apps/test/net-cdf/stow/netcdf-fortran/4.5.3/lib -lnetcdff
  --has-f90       ->
  --has-f03       -> yes

  --has-dap       -> yes
  --has-dap2      -> yes
  --has-dap4      -> yes
  --has-nc2       -> yes
  --has-nc4       -> yes
  --has-hdf5      -> yes
  --has-hdf4      -> no
  --has-logging   -> no
  --has-pnetcdf   -> no
  --has-szlib     -> yes
  --has-cdf5      -> yes
  --has-parallel4 -> no
  --has-parallel  -> no
  --has-nczarr    -> no

  --prefix        -> /vol/apps/test/net-cdf/stow/net-cdf/4.8.0
  --includedir    -> /vol/apps/test/net-cdf/stow/net-cdf/4.8.0/include
  --libdir        -> /vol/apps/test/net-cdf/stow/net-cdf/4.8.0/lib
  --version       -> netCDF 4.8.0
```

The --has-parallel options are no, so I assume this means it wasn't build with parallel support. But if this is the problem, then why does this job run at C48 and C90?

I also looked at line1627  in MAPL_Generic.F90 where the first FAIL occurs. I couldn't really parse what the code was doing but it looks like it has to do with ESMF. So maybe there is a problem with my ESMF build, but again if so, why does C48 and C90 work?

### GEOS-Chem version
13.1.2

### Log files

- Run logs (if applicable):  [runlog.txt](https://github.com/geoschem/geos-chem/files/6990074/runlog.txt)
- Run script (if applicable): [runscript.txt](https://github.com/geoschem/geos-chem/files/6990081/runscript.txt)

### Software versions
- CMake version:  3.21
- Compilers (Intel or GNU, and version): gcc 9.2.0
- NetCDF version: netcdf-4.8, netcdf-fortran 4.5.3
- ESMF 8.1.1

**Comment by lizziel** [comment]
Hi @cbutenhoff, this is definitely curious. We have not run into this on our end. Have you tried plotting your C24 restart file to see if it is corrupt?

**Comment by lizziel** [comment]
I should also mention we have not tried using ESMF 8.1.1 yet but are still using 8.1.0. However, as you stated, if it worked for C48 and C90 there isn't really reason it wouldn't work for C24.

**Comment by cbutenhoff** [comment]
Thanks for the suggestion to check the restart file. It was indeed corrupt, something must have happened during download. The C24 run now works fine.

**Comment by lizziel** [comment]
Okay, great. I'll close out this issue.
