### ISSUE TITLE
[DISCUSSION] Timing of nested-grid simulations

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#829]
Colette Heald wrote:

>I am wondering if you are aware of any issues slowing down the nested grid simulations or if anyone else has been reporting a slow down? My group has been telling me that it's taking super long for them to do nested simulations (0.5x0.625) in v13. Obviously there are differences in hardware in my cluster and Harvard but here is a somewhat useful comparison on our system:
>
>v12.1.1: custom nested grid over India took ~16 hr to run one month
>v13.1.1: standard nested domain over the US taking ~80-90h to run one month (same model version set-up takes about 1/3 the time to run a month globally at 2x2.5)
>
>I'll ask folks in my group to turn on the TIMERS for the next nested simulation they do so that we can break this down, but I was curious if this had come up?

Ishir Dutta wrote:

>I completed a 1-month nested run over CONUS with the timers switched on. I’ve attached a bar plot figure that roughly lines up with the one on the wiki, but I found that the top line numbers for each category didn’t quite match the breakdown, so I’ve also included the run log file.
![nested-timed-1-month](https://user-images.githubusercontent.com/4805437/130264015-d906fd01-7e11-4bd2-be1b-d07d56c185fc.png)
>
>Here's a quick rundown of my config:
>
>Version: 13.1.1
>Resolution: 0.5 x 0.625
>Domain longitude:  -130.0000   -60.0000
>Domain latitude:     10.0000    60.0000
>Run time: 81h 20m
>Diagnostics (Monthly output): HEMCO, SpeciesConc, Restart, StateMet, WetLoss (LS + Conv), and DryDep
>Modifications: Luo 2020 wet dep scheme
>
>As a point of comparison, 3 month global runs at 2x2.5 usually take ~80-100h on our system, and the runtimes for 1 month nested sims have been anywhere between 60-130h.
>
>I’m running timers for a month each at 2x2.5 with the wet dep update, as well as at 0.5x0.625 without the wet dep update so that we can dig a little deeper, but do let me know if anything here sticks out to you.
>
>I figured it might be useful to follow up with timed runs of v13.1.1 out of the box, to exclude any possible effects of the wet dep updates.
>
>As before, the nested run is over North America (0.5x0.625) and took ~60h/month. The global run was at 2x2.5 for 3 months and took ~27h/month, which is pretty consistent with what we’ve seen since v12.7.1 (anywhere between 20-30h/mo).
![gc-classic-13 1 1-nested-timed](https://user-images.githubusercontent.com/4805437/130264196-d2bd9086-82cd-4b67-b98d-83de6eb66986.jpg)

**Comment by msulprizio** [comment]
Here are some tips for speeding up nested grid simulations:

1. By default, nested grid simulations read in global high-resolution meteorology fields to allow for domains over any region. The file I/O for the large files can slow down simulations, so we recommend cropping the met fields to your region when possible and updating the file paths in HEMCO_Config.rc to read those files instead. The files can be cropped in a script using tools in python or CDO (see [this example](http://wiki.seas.harvard.edu/geos-chem/index.php/Working_with_netCDF_data_files#Cropping_netCDF_files)). The GCST also provides pre-cropped met fields for our traditional nested-grid domains over Asia, Europe, and North America.
2. Check emission inventories used in nested-grid simulations. Often, users may choose regional inventories with high spatial and temporal frequency. In those cases, ensure that files are read efficiently. For example, for hourly data try setting the `sourceTime` attribute in HEMCO_Config.rc to read all hours once per day instead of reading the files hourly (e.g. use `2006-2013/1-12/1-31/*` instead of `2006-2013/1-12/1-31/0-23`).
3. Reduce the number of vertical levels. The native vertical resolution of GEOS-FP and MERRA-2 met fields is 72 levels, but users may choose to use the reduced 47 levels instead to speed up simulations. If running a full-chemistry simulation, there is also the option to solve for chemistry only in the troposphere and use archived prod/loss rates above as opposed to the standard simulation which solves for chemistry in the troposphere+stratosphere. (Note, however, there may be issues with this "TropChem" option in GEOS-Chem 13.0-13.2 as discussed in [this issue](https://github.com/geoschem/geos-chem/issues/732)).

We are told the simulations above utilize all of these tips, so there may be something else going on here. We are still investigating, but welcome comments from the community.

**Comment by lfreese** [comment]
I've been facing similar issues:
Runs with v12.6.1 took about 2 weeks to run 15 months of simulations with 32 CPUs
Runs with v12.9.3 took about 2 months to run 18 months of simulations with 32 CPUs
I'm currently running v13.1.2 and am getting similarly slower times as with 12.9.3. I am turning on the timers to get some output and see if it is similar to the above. 

I am also transitioning to using the cropped MERRA files, as our system currently uses the global ones, so those changes will be evident in the timer output. I'll re-comment in a bit with how that goes, but I figured it would be useful to know that this has been occurring with more than just one server/group's system.

**Comment by yantosca** [comment]
Thanks @msulprizio and @lfreese.  I did a quick CH4 NA simulation and noticed that we were getting these warnings:
```
At line 744 of file /local/ryantosca/GC/rundirs/test_ch4_na/CodeDir/src/GEOS-Chem/GeosCore/transport_mod.F90
Fortran runtime warning: An array temporary was created for argument 'ps1' of procedure 'tpcore_window'
At line 745 of file /local/ryantosca/GC/rundirs/test_ch4_na/CodeDir/src/GEOS-Chem/GeosCore/transport_mod.F90
Fortran runtime warning: An array temporary was created for argument 'ps2' of procedure 'tpcore_window'
At line 745 of file /local/ryantosca/GC/rundirs/test_ch4_na/CodeDir/src/GEOS-Chem/GeosCore/transport_mod.F90
Fortran runtime warning: An array temporary was created for argument 'ps' of procedure 'tpcore_window'
At line 687 of file /local/ryantosca/GC/rundirs/test_ch4_na/CodeDir/src/GEOS-Chem/GeosCore/tpcore_window_mod.F90
Fortran runtime warning: An array temporary was created for argument 'u' of procedure 'air_mass_flux'
At line 687 of file /local/ryantosca/GC/rundirs/test_ch4_na/CodeDir/src/GEOS-Chem/GeosCore/tpcore_window_mod.F90
Fortran runtime warning: An array temporary was created for argument 'v' of procedure 'air_mass_flux'
At line 697 of file /local/ryantosca/GC/rundirs/test_ch4_na/CodeDir/src/GEOS-Chem/GeosCore/tpcore_window_mod.F90
Fortran runtime warning: An array temporary was created for argument 'xmass' of procedure 'air_mass_flux'
At line 697 of file /local/ryantosca/GC/rundirs/test_ch4_na/CodeDir/src/GEOS-Chem/GeosCore/tpcore_window_mod.F90
Fortran runtime warning: An array temporary was created for argument 'ymass' of procedure 'air_mass_flux'
At line 822 of file /local/ryantosca/GC/rundirs/test_ch4_na/CodeDir/src/GEOS-Chem/GeosCore/tpcore_window_mod.F90
Fortran runtime warning: An array temporary was created for argument 'q' of procedure 'qmap'
```
This means that we are getting array temporaries created under the hood.  This means that the code has to make a copy of the data, then pass it to the subroutine, then destroy the copy of the data.  That usually happens when slices of arrays are passed instead of the entire array.   This is happening in this block:

https://github.com/geoschem/geos-chem/blob/d7baeb8fe51a66914408e9d1f655dd062bd5d4df/GeosCore/transport_mod.F90#L712-L761

I used GNU Fortran 10.2.0 to build GEOS-Chem with `-DCMAKE_BUILD_TYPE=Debug`.  It seems that the array temporaries are created when we use pointers to pick out the horizontal slices of the array.   But the only thing is it seems that the array temporaries are created only the first time that transport_mod.F90 is called, then we don't get the warnings anymore.  Maybe GNU Fortran keeps that memory active so we don't get repeated array temporary creation.  The behavior might be different with Intel fortran.

**Comment by yantosca** [comment]
Also these lines (687-697) and line 822 in tpcore_window_mod.F90

https://github.com/geoschem/geos-chem/blob/bc9873924a613fe8395b2359ab2ce75d1eb80b0d/GeosCore/tpcore_window_mod.F90#L681-L698

https://github.com/geoschem/geos-chem/blob/bc9873924a613fe8395b2359ab2ce75d1eb80b0d/GeosCore/tpcore_window_mod.F90#L814-L824

**Comment by yantosca** [comment]
@lfreese, which compiler are you using?
