### ISSUE TITLE
[DISCUSSION] Soil wetness in 2x2.5 resolution is wrong in coastal regions? 

### ISSUE THREAD

**Issue by joeylamcy** [geoschem/geos-chem#83]
# Regridding soil wetness directly yields scientifically incorrect results in coastal regions

## Overview

Originally, root zone soil wetness (GWETROOT) is lower and surface soil wetness (GWETTOP) is higher in coastal regions, because they defaults to 0 and 1 respectively over the ocean in the MERRA-2 native resolution, and regridding directly yields such results. However, values over the ocean should not have any effects in terms of regridding soil wetness. 

Therefore, soil wetness fields should require pre-processing before regridding. Otherwise, the regridded fields no longer have the same meaning at where land fraction is not 1.

This issue is not caused by GEOS-Chem, but it might affect simulation results, so I decided to put it here.

## Detailed description
As far as I understand, regridding of MERRA-2 from its native resolution uses an [area-preserved mapping scheme](http://wiki.seas.harvard.edu/geos-chem/index.php/Regridding_in_GEOS-Chem) and some interpolation/optimization steps which I did not dive into. Some fields like U-wind and V-wind requires special pre-processing to be regridded correctly. I think soil wetness fields (GWETROOT and GWETTOP) should also require pre-processing to take porosity and land fraction into consideration.

The reason is that soil wetness refers to the volume of water per unit volume of soil pore space, so it should not be multiplied to the area of grid box directly. To convert it into a quantity that the above mapping scheme applies, it should be multiplied by the porosity (volume of soil pore space per unit volume of land) and the land fraction (area of land per area of grid cell). Therefore, _assuming a fixed column height_, the product is essentially an **equivalent area of water per area of grid cell**. Regridding this quantity and dividing it by the product of porosity and land fraction at the coarse resolution would give the correct soil wetness _ideally_. 

A practical complication arises as the interpolation/optimization process may cause the resulting soil wetness to be larger than 1, which is unphysical. So far, I have encountered a maximum value of 1.2 and 1.8 when regridding GWETROOT and GWETTOP respectively for Jan 2012. I wonder if there is a better option, e.g. some special settings during interpolation, other than directly adjusting the results.

## Implication
GWETROOT will increase and GWETTOP will decrease in coastal regions. GWETROOT is currently not used but GWETTOP is used in CH4 simulation and dust mobilization, according to the GEOS-Chem Wiki. I have no idea how this may change the simulation results, but any changes are expected to be slight at most.

## Comparison
Attached below is the comparison of both soil wetness fields between the MERRA-2 dataset at native 0.5x0.625 resolution, the default MERRA-2 dataset at 2x2.5 resolution and my modified dataset at 2x2.5 resolution on 1 Jan 2012. As seen from the graphs, the default MERRA-2 dataset at 2x2.5 resolution deviates from both the native one and the modified one at grid cells with land fraction < 1.

![wetness_compare](https://user-images.githubusercontent.com/41887185/66376676-c21be700-e9e2-11e9-9c98-eb94c7a4a818.png)

## How to reproduce
You may use f2py to convert this [Fortran code](https://github.com/joeylamcy/MERRA2_regridding_issue/blob/master/RegridModule.F90), which I took and briefly modified from [https://github.com/geoschem/MERRA2/blob/master/Code/Merra2_RegridModule.F90](https://github.com/geoschem/MERRA2/blob/master/Code/Merra2_RegridModule.F90), to obtain a python module and use this [Python script](https://github.com/joeylamcy/MERRA2_regridding_issue/blob/master/soil_moisture_regrid.py) to regrid the native MERRA-2 dataset.

**Comment by joeylamcy** [comment]
I don't think I will spend much time on this. It is not really a focus of my project.

In the case of reading raw data directly, I suppose regridding is still required because the simulation and data resolution are different? If that is the case, this issue might still be important.

**Comment by yantosca** [comment]
Thanks Joey.  This is beyond the scope of what the GCST can do.  I can leave this as an open ticket in case someone wants to take it up.

**Comment by JiaweiZhuang** [comment]
I think we can ask the Steering Committee and Working Groups to actively look at and comment on this and other scientific/research issues posted on GitHub, especially if the issues are well-documented and reproducible. Instead of burying the scientific discussions in a pile of emails, I'd much rather to see them being transparent and easily searchable.

**Comment by yantosca** [comment]
I agree.  I've relabeled the subject header to [DISCUSSION].

Also, starting with GEOS-Chem 12.6.1, we are adding a new Github template for extended discussions (as opposed to short-term questions).  This should help to migrate long-term discussions out of email and onto Github, where they will be more visible.
