### ISSUE TITLE
[FEATURE REQUEST] Allow easy disabling of all emissions

### ISSUE THREAD

**Issue by lizziel** [geoschem/geos-chem#831]
In GEOS-Chem 13 there is a toggle in `HEMCO_Config.rc` to turn off emissions separate from meteorology and chemistry inputs read through HEMCO. The setting to turn emissions on/off in `input.geos` is retired. When the emissions toggle is set to `False` in full chemistry simulations, however, the model crashes because it can't find volcano files. I think this is because the toggle excludes online emissions. To turn off all emissions users must set the Emissions setting to `False` and also manually turn off all extensions.

It would be useful for debugging purposes to be able to turn off ALL emissions in one switch. Or have two switches, one for offline emissions and one for online. The offline emissions toggle is useful to preserve the original emissions inventory settings. Having an online emissions toggle would be ideal for the same reasons.

**Comment by yantosca** [comment]
I think this could easily be done with 2 modifications:
 
  1. Wrap the EXTENSION DATA section in `(((EMISSIONS` and `)))EMISSIONS` tags, so that none of the extension data is read in.
  2. If the master emissions switch is toggled off, also toggle off all extensions.  This may be able to be done in `hcox_driver_mod.F90`.

**Comment by lizziel** [comment]
Following up on this issue, there is a further issue where even if you manually turn off all base emissions and extensions then the model crashes. I think this is probably just a matter of updating HEMCO_Config.rc so that required inputs are not turned off when turning off emissions.

**Comment by lizziel** [comment]
@msulprizio, do you know if there is still an issue in the model where it crashes when turning off base emissions and extensions in HEMCO_Config.rc?

**Comment by yantosca** [comment]
This functionality was recently added into into the 14.3.0 development stream by PR https://github.com/geoschem/HEMCO/pull/250.  @lizziel, feel free to close out this issue now.

**Comment by yantosca** [comment]
We can now close this issue as https://github.com/geoschem/HEMCO/pull/250 has been merged into GEOS-Chen 14.3.0 / HEMCO 3.8.0.
