### ISSUE TITLE
[FEATURE REQUEST] 2020 Volcano Emissions

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#833]
@chfite wrote:

>I am running GEOS-Chem simulations into 2020 and my simulation stopped because it couldn’t find volcano emissions past Jan 1, 2020. I looked on the Dalhousie and ComputeCanada sites to download those files but neither site has Volcano emissions past that date. I have not been able to get the Harvard FTP site to load for the past day or so, but I assume the 2020 emissions are not there either? 
>
>If not, is there a way to get those emissions or are there plans to soon have those available?

**Comment by msulprizio** [comment]
Thanks @christophkeller! We can update the volcano emissions up through May 2020 in GEOS-Chem 13.2.0. 

In addition, we will be adding a climatology option soon as discussed in https://github.com/geoschem/geos-chem/issues/500.

**Comment by christophkeller** [comment]
Sounds good! In the tar file that I shared there are daily files up to Jan 1, 2022. The data after May 2020 is just the degassing climatology, which is probably what you would want to use for a climatology? There is also an explicit climatology file (degassing only) in the tar file, named `so2_volcanic_emissions_CARN_v202005.degassing_only.rc`

**Comment by msulprizio** [comment]
This is now resolved by PR https://github.com/geoschem/geos-chem/pull/921 and is currently merged into the `dev` branch. It will be included in GEOS-Chem 13.3.0.

NOTE: The option to use the volcano climatology (i.e. degassing emissions only) has also been included via the pull request https://github.com/geoschem/HEMCO/pull/110.
