### ISSUE TITLE
[BUG/ISSUE] latitude center and edge mix up at 13.1.2

### ISSUE THREAD

**Issue by dorosieun** [geoschem/geos-chem#837]
### Description of the problem
I tried running nested model run and I found something wrong in the log file.

longitude grid>

![스크린샷 2021-08-25 오후 12 06 14](https://user-images.githubusercontent.com/87462290/130720009-dddc3aa2-1b6e-47a9-9f2e-01ad301ee769.png)

latitude grid>

![스크린샷 2021-08-25 오후 12 06 26](https://user-images.githubusercontent.com/87462290/130720017-e614572d-9541-4d4c-8dce-e65b83a70a15.png)

Grid sets of longitude has no problem. But I think grid sets of latitude center and edge are mixed up.
I guess there are some typo in gc_grid_mod.F90.

### Description of troubleshooting performed
Describe any troubleshooting that you have already performed here. Also include any leads or suspicions here.

### GEOS-Chem version
13.1.2

### Description of modifications
Describe your modifications here.

### Log files
- Build log (if applicable):
- Run logs (if applicable): 
[GC.log.txt](https://github.com/geoschem/geos-chem/files/7043163/GC.log.txt)
- Run script (if applicable):
[input.geos.txt](https://github.com/geoschem/geos-chem/files/7043165/input.geos.txt)

### Software versions
- CMake version:
- Compilers (Intel or GNU, and version):
- NetCDF version:

**Comment by dorosieun** [comment]
`    !======================================================================
    ! Global Horizontal Grid
    !======================================================================
    DO J = 1, State_Grid%GlobalNY
    DO I = 1, State_Grid%GlobalNX

      IF ( J == 1 ) THEN
         State_Grid%GlobalYEdge(I,J) = -90.0
      ELSE
         IF ( State_Grid%HalfPolar ) THEN
            State_Grid%GlobalYEdge(I,J) = -90.0 - State_Grid%DY/2.0 + State_Grid%DY*(J-1)
         ELSE
            State_Grid%GlobalYEdge(I,J) = -90.0 + State_Grid%DY*(J-1)
         ENDIF
         IF ( J == State_Grid%GlobalNY ) THEN
            State_Grid%GlobalYEdge(I,J+1) = 90.0
         ENDIF
      ENDIF

      IF ( I == 1 ) THEN
         IF ( State_Grid%Center180 ) THEN
            State_Grid%GlobalXEdge(I,J) = -180.0 - State_Grid%DX / 2.0
         ELSE
            State_Grid%GlobalXEdge(I,J) = -180.0
         ENDIF
      ELSE
         State_Grid%GlobalXEdge(I,J) = State_Grid%GlobalXEdge(1,J) + State_Grid%DX * ( I - 1 )
         IF ( I == State_Grid%GlobalNX ) THEN
            State_Grid%GlobalXEdge(I+1,J) = State_Grid%GlobalXEdge(1,J) + 360.0
         ENDIF
      ENDIF

    ENDDO
    ENDDO

    DO J = 1, State_Grid%GlobalNY
    DO I = 1, State_Grid%GlobalNX
       State_Grid%GlobalYMid(I,J) = 0.5 * ( State_Grid%GlobalYEdge(I,J) + State_Grid%GlobalYEdge(I,J+1) )
       State_Grid%GlobalXMid(I,J) = 0.5 * ( State_Grid%GlobalXEdge(I,J) + State_Grid%GlobalXEdge(I+1,J) )
    ENDDO
    ENDDO

`
this is Global Horizontal Grid code at gc_grid_mod.F90.


`    !======================================================================
    ! Global Horizontal Grid
    !======================================================================
    DO J = 1, State_Grid%GlobalNY
    DO I = 1, State_Grid%GlobalNX

      IF ( J == 1 ) THEN
         State_Grid%GlobalYEdge(I,J) = -90.0 - State_Grid%DY / 2.0
      ELSE
         IF ( State_Grid%HalfPolar ) THEN
            State_Grid%GlobalYEdge(I,J) = -90.0 - State_Grid%DY/2.0 + State_Grid%DY*(J-1)
         ELSE
            State_Grid%GlobalYEdge(I,J) = State_Grid%GlobalYEdge(I,1) + State_Grid%DY * (J-1)
         ENDIF
         IF ( J == State_Grid%GlobalNY ) THEN
            State_Grid%GlobalYEdge(I,J+1) = State_Grid%GlobalYEdge(I,1) + 180.0
         ENDIF
      ENDIF

      IF ( I == 1 ) THEN
         IF ( State_Grid%Center180 ) THEN
            State_Grid%GlobalXEdge(I,J) = -180.0 - State_Grid%DX / 2.0
         ELSE
            State_Grid%GlobalXEdge(I,J) = -180.0
         ENDIF
      ELSE
         State_Grid%GlobalXEdge(I,J) = State_Grid%GlobalXEdge(1,J) + State_Grid%DX * ( I - 1 )
         IF ( I == State_Grid%GlobalNX ) THEN
            State_Grid%GlobalXEdge(I+1,J) = State_Grid%GlobalXEdge(1,J) + 360.0
         ENDIF
      ENDIF

    ENDDO
    ENDDO

    DO J = 1, State_Grid%GlobalNY
    DO I = 1, State_Grid%GlobalNX
       State_Grid%GlobalYMid(I,J) = 0.5 * ( State_Grid%GlobalYEdge(I,J) + State_Grid%GlobalYEdge(I,J+1) )
       State_Grid%GlobalXMid(I,J) = 0.5 * ( State_Grid%GlobalXEdge(I,J) + State_Grid%GlobalXEdge(I+1,J) )
    ENDDO
    ENDDO

`
I changed some code like this.
And the mixing up problem solved.

Does it look okay? Won't it cause any other problems?

**Comment by yantosca** [comment]
I will close this issue as 13.2.1 will be released soon.  Thanks for bringing this to our attention!
