### ISSUE TITLE
[QUESTION] iord_bg and jord_bg values defined in tpcore_window_mod.F90

### ISSUE THREAD

**Issue by eamarais** [geoschem/geos-chem#840]
I've been digging into an issue of negative advected tracer concentrations when I run a nested grid simulation over India. These occur at the boundaries of the nested domain. I tried adjusting the number of buffer cells from 3 to 6, but this didn't address the issue. Changing the domain seems to get around this issue, but doesn't fix it. 

Something I have noticed is that in tpcore_window_mod.F90, values of iord_bg and jord_bg are set to 1 rather than 3 (the value defined for IORD and JORD in input.geos). Is there a reason why these variables are being set to 1? I'm not yet sure whether this will address the negative values, but I'm still curious whether this is bug or intentional. 

I'm using model version 13.0.2 for the following nested domain:
Grid resolution         : 0.25x0.3125
Longitude min/max       : 60.0 100.0
Latitude  min/max       : 5.0  40.0

**Comment by yantosca** [comment]
Thanks for bringing this to our attention @eamarais.  It does appear to be legacy code.  I looked into the Git history but could not find where this change was made.

I've pushed commit a43cbadfd3ce3c3e20fca8fad6dd326f7867b09d, which sets `iord_bg = iord` and 'jord_bg = jord`.  This will go into version 13.2.1.
