### ISSUE TITLE
[QUESTION] Is SOAGX considered as biogenic secondary organic aerosol (BSOA)?

### ISSUE THREAD

**Issue by dxy8413** [geoschem/geos-chem#848]
### Ask a question about GEOS-Chem:
Does SOAGX considered as biogenic secondary organic aerosol (BSOA)? It seems the variable "TotalBiogenicOA" is the sum of "AerMassTSOA", "AerMassSOAIE", "AerMassSOAGX", and "AerMassLVOCOA". But in urban areas SOAGX may be mostly from aromatics.

Thanks for the time and help!

**Comment by djxjacob** [comment]
Hi dxy8413 - this is a science question, not a software/code question. Please contact the Aerosol WG chairs.  Thanks

**Comment by msulprizio** [comment]
The field TotalBiogenicSOA is only used for diagnostic purposes. SOAGX is included in ISOAAQ (isoprene SOA from aqueous formation), which is included in the summation of both the TotalBiogenicSOA and TotalOA diagnostics. From aerosol_mod.F90:

```
       !-------------------------------------------------------
       ! Mass loading of isoprene SOA (ISOAAQ) [kg/m3]
       !-------------------------------------------------------

       ! Glyoxal
       IF ( id_SOAGX > 0 ) THEN
          ISOAAQ(I,J,L) = Spc(I,J,L,id_SOAGX) / AIRVOL(I,J,L)
       ENDIF

       ! IEPOX
       IF ( id_SOAIE > 0 ) THEN
          ISOAAQ(I,J,L) = ISOAAQ(I,J,L) + Spc(I,J,L,id_SOAIE) / AIRVOL(I,J,L)
       ENDIF

       ! SOA from ISOPOOH oxidation product
       IF ( id_LVOCOA > 0 ) THEN
          ISOAAQ(I,J,L) = ISOAAQ(I,J,L) + Spc(I,J,L,id_LVOCOA) / AIRVOL(I,J,L)
       ENDIF

...

       !--------------------------------------
       ! Sum of all biogenic organic aerosol
       !--------------------------------------
       IF ( State_Diag%Archive_TotalBiogenicOA ) THEN
          State_Diag%TotalBiogenicOA(I,J,L) = ( TSOA(I,J,L) + ISOAAQ(I,J,L) ) &
                                                * kgm3_to_ugm3
       ENDIF

       !--------------------------------------
       ! Sum of all organic aerosol [ug/m3]
       !--------------------------------------
       IF ( State_Diag%Archive_TotalOA ) THEN
          State_Diag%TotalOA(I,J,L) = ( TSOA(I,J,L) + &
                                        ASOA(I,J,L) + &
                                        OCPO(I,J,L) + &
                                        OCPI(I,J,L) + &
                                        OPOA(I,J,L) + &
                                        ISOAAQ(I,J,L) ) * kgm3_to_ugm3
       ENDIF
```

I am tagging the Aerosol Working Group leaders (@theloniuspunk, @beckyalexander) and developer of the aqueous isoprene SOA mechanism (@eamarais) in case they have anything to add.

**Comment by dxy8413** [comment]
> Hi dxy8413 - this is a science question, not a software/code question. Please contact the Aerosol WG chairs. Thanks

Hi  djxjacob and Bob - Sorry I didn't notice it the first post was closed because it was not a software question, I thought it was internet problem lost the post and didn't mean to post it twice. I think msulprizio's post explains TotalBiogenicSOA  was only for diagnostic analysis, Thanks for the help!

**Comment by theloniuspunk** [comment]
That seems right, Melissa, though Eloise would know better than me.

**Comment by eamarais** [comment]
That's correct @dxy8413. At the time that I developed the scheme the overwhelming majority of glyoxal in the model was biogenic in origin over the US. Indeed, over locations like China and India (depending on the quality of the inventory) the diagnostic will include anthropogenic glyoxal. And over locations with intense biomass burning, it will also include this component, though the model substantially underestimates this and other oVOCs from biomass burning. 

If you wanted to track the biogenic glyoxal component only, you could include a separate biogenic SOAGX species that forms from the isoprene oxidation branch only, but this won't be perfect, as glyoxal is formed in multiple oxidation steps, so it's not easy to trace its origin though all oxidation steps. Another option could be to run a sensitivity simulation perturbing isoprene emissions to see whether the effect on SOAGX is linear.

**Comment by msulprizio** [comment]
Thanks, @eamarais! 

@dxy8413 I will close out this issue for now, but feel free to comment further or open a new issue.
