### ISSUE TITLE
[FEATURE REQUEST] Create and test a benchmark workflow on AWS for GEOS-Chem Classic and GCHP

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#849]
Resources on Harvard's Cannon Cluster are not always reliable and are subject to the activity of other user groups. To avoid delays in running benchmark simulations, we should have a benchmark workflow on AWS to easily get GEOS-Chem Classic and GCHP benchmark simulations running there. 

The setup would involve evaluating differences in model performance and model output when running benchmarks on AWS vs Cannon. The [GEOS-Chem Internal Benchmark Google Sheet](https://docs.google.com/spreadsheets/d/1Yird5jRUIX1KKdRZq8lZGO_x2VQnsedn0QQK052n__8/edit?usp=sharing) has stats for recent benchmarks on Cannon. 

In addition, it would be good to quantify the cost of running benchmarks and downloading model output from AWS for each benchmark type (e.g. 1-year, 1-month, fullchem, TransportTracers)

**Comment by yantosca** [comment]
Benchmarking in the cloud might be facilitated by using the containers that get pushed to Dockerhub from Azure Pipelines.

Also see: https://github.com/geoschem/geos-chem/pull/459, which will make automated run directory creation easier.

**Comment by laestrada** [comment]
My current plan is to build and push a docker image with GCClassic, GCHP, and GCPY to AWS ECR using pipelines. Once pushed, the docker image will be triggered to run via ECS (also using pipelines). All the relevant output can be pushed up to an s3 bucket prior to the termination of the container. The upside of using ecs is that the ec2 instance will automatically terminate after finishing the given CMD (a shell script running the various benchmark commands) with no intervention from a developer. Does this sound reasonable @LiamBindle?

For the creating the various aws infrastructure (ECR repository, ECS task definition, S3 bucket) I plan to use [terraform](https://www.terraform.io/), which I have experience with, but I could also use cloudformation if that is desirable?

**Comment by LiamBindle** [comment]
@laestrada Terrific! That's sounds awesome. 

When done, I think this could be adapted to run the integration tests in the cloud too (triggered by prerelease tags)! @yantosca

**Comment by yantosca** [comment]
I think we can close out this issue as we now have an automatic benchmark workflow set up on AWS and Compute1.
