### ISSUE TITLE
[BUG/ISSUE] forbidden (403) or not found (404) to wustl server from Korea

### ISSUE THREAD

**Issue by hyungmini** [geoschem/geos-chem#881]
Problem: I am trying to download MERRA2 met field via WUSTL server from Korea. I have tried two ways; one using wget and the other one through the website. 

When using wget I got following message.

> Reusing existing connection to geoschemdata.wustl.edu:80.
> HTTP request sent, awaiting response... 404 Not Found
> 2021-09-03 10:48:17 ERROR 404: Not Found.

When I tried to through the website (http://geoschemdata.wustl.edu/ExtData/GEOS_0.5x0.625_AS/MERRA2/2020/12/MERRA2.20201203.A3cld.05x0625.AS.nc4). I got following message.

> Forbidden
> You don't have permission to access this resource.

I have been trying to download the data from computecanada since ~2 months ago. I wasn't even able to be connected then. I thought it was because of transferring from compute canada to the wustl. But now I don't understand why it is still not working. I will be appreciated with any help.

**Comment by YanshunLi-washu** [comment]
Hi @hyungmini We're working on the permission issue. Will let u know once it's done. Thanks

**Comment by hyungmini** [comment]
Hello,

Now I am able to download through wget from wustl server.
I am not sure if this was the fix though, I used '--no-http-keep-alive --no-cache --no-cookies' flags this time. 
Thanks.

**Comment by LiamBindle** [comment]
@hyungmini Thanks for the update. When we transfered all the data from ComputeCanada to WashU the file permissions got messed up, so we're still working on making sure everything is correct. Initially, there were hundreds of thousands of files with the wrong permissions. We're down to ~30K that still need to be fixed (see [here](http://geoschemdata.wustl.edu/ExtData/maintenance/bad_file_permissions.txt)).

Thanks for bearing with us.
