### ISSUE TITLE
[BUG/ISSUE] Subscript of the array is zero or negative

### ISSUE THREAD

**Issue by NatalliaMiatselskaya** [geoschem/geos-chem#882]
I run GEOS-Chem v.12.1.1 classic, nested Europe, 0.25x0.3125. The simulation was OK from 2015.01.01 to 2015.07.07.  I reran it several times beginning from 2015.07.07 00:00, 22:40, 23:00  etc. It crashed at 22:50 or 23:00 or 23:30... with different messages (negative values in wet deposition, negative values in Lightnox, particle radius or C_Y is neg) or without messages. So I ran the simulation with debugging options. It crashed with compiler message:

nata@met:~/runs/runs_v12.1.1/geosfp_025x03125_EU_complexSOA$ ./geos > trac_avg.eu_complexSOA_daily.20150707_prov.log
forrtl: severe (408): fort: (3): Subscript #2 of the array Q has value 0 which is less than the lower bound of 1
```
Image              PC                Routine            Line        Source             
libintlc.so.5      000014EEF8CFDA7A  Unknown               Unknown  Unknown
libintlc.so.5      000014EEF8CFC576  Unknown               Unknown  Unknown
libifcoremt.so.5   000014EEF996A06C  Unknown               Unknown  Unknown
libifcoremt.so.5   000014EEF98DA2A2  Unknown               Unknown  Unknown
libifcoremt.so.5   000014EEF98DA823  Unknown               Unknown  Unknown
geos               000000000185566B  tpcore_window_mod        2185  tpcore_window_mod.F90
geos               00000000018312E5  tpcore_window_mod        1653  tpcore_window_mod.F90
geos               0000000001817053  tpcore_window_mod        1262  tpcore_window_mod.F90
geos               00000000017F7BC9  tpcore_window_mod         716  tpcore_window_mod.F90
geos               000000000104F8F3  transport_mod_mp_         965  transport_mod.F
geos               0000000001046B93  transport_mod_mp_         283  transport_mod.F
geos               0000000000942105  MAIN__                   1516  main.F
geos               0000000000404A3C  Unknown               Unknown  Unknown
libc.so.6          000014EEF84FFBF7  Unknown               Unknown  Unknown
geos               000000000040493A  Unknown               Unknown  Unknown 
```
I have found that the error is encountered in the subroutine ytp in the block:
```
if(jord == 1) then
        do j=js2g0,jn1g1
          do i=1,im
            jt = float(j) - c(i,j)
            fy(i,j) = q(i,jt)
          enddo
        enddo
   else

I added PRINT to this block:

if(jord == 1) then
        do j=js2g0,jn1g1
          do i=1,im
            jt = float(j) - c(i,j)
      IF(JT<=0)THEN 
      PRINT*,'  JT=',JT
      PRINT*,'  J=',J          
      PRINT*,'  FLOAT(J)=',FLOAT(J)
      PRINT*,'  C(I,J)=',C(I,J)
      END IF
            fy(i,j) = q(i,jt) 
          enddo
        enddo
   else
```
The simulation crashed with:
```
NASA-GSFC Tracer Transport Module successfully initialized
     - OPEN_BC_FILE: Opening /home/nata/BC_2x25_EU/BC.20150707 on unit   14
 JT=           0
 J=          11
 FLOAT(J)=   11.0000000000000     
 C(I,J)=   10.2138578979571     
 JT=           0
 J=          14
 FLOAT(J)=   14.0000000000000     
 C(I,J)=   13.1526727116379     
 JT=           0
 J=          11
 FLOAT(J)=   11.0000000000000     
 C(I,J)=   10.1067642055062
```
So subscript JT of the array Q is zero, and the simulation can not deal with this. Is it possible to fix this?

I can see that in my simulation the Courant number c(i,j) can sometimes be large, more than 2. Is it OK?

**Comment by NatalliaMiatselskaya** [comment]
Thank you! I actually use tropchem. I would like to upgrade to 13.2.1 with chemistry in the stratosphere, but I am not sure that my CPU resources are sufficient. Is 13.2.1 computationally expensive? I created boundary conditions using tropchem 12.1.1 with 2x2.5 resolution. May I use these BC for 13.2.1 nested grid simulation?

**Comment by NatalliaMiatselskaya** [comment]
Thank you!

    On Tuesday, September 7, 2021, 05:31:47 PM GMT+3, Bob Yantosca ***@***.***> wrote:  
 
 


Thanks for writing. The Courant number should definitely not be greater than 1. You might need to reduce the dynamic timestep so tha tthe Courant number limit is not exceeded.

Are you using the tropchem option? We have found that this option can be problematic. Also 12.1.1 by now is a 2+ year old version and there have been several fixes for it since. We would recommend upgrading to 13.2.1 (when it ships, very soon) and using chemistry in the stratosphere for 47 levels. This should result in more stable chemistry.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yantosca** [comment]
We are finalizing the 13.2.0 and 13.2.1 releases now.  This was delayed due to some computer issues on our cluster in recent weeks.

My colleague Melissa (@msulprizio) has done some timing tests with the tropchem simulation.  Those results are listed in issue #839.  If you use 47L with chemistry on in the trop & strat, that is not much more expensive than tropchem at 47 levels (see the plots in that issue).

**Comment by NatalliaMiatselskaya** [comment]
Thank you very much!
