### ISSUE TITLE
ExtData files not readable during GEOSChem runs [BUG/ISSUE]

### ISSUE THREAD

**Issue by tessac2** [geoschem/geos-chem#883]
### Description of the problem
When I run GEOS-Chem (GEOS-FP), I get errors in my GC and HEMCO log file saying that seemingly random files are missing data/not able to be read. I am a bit confused why this is happening, since I ran a dry run over the time period in question (2018). I am running GEOS-Chem for 3 month periods in 2018, but in each time period I have run into this issue. It seems to be resolved if I remove the file, and re-download it. However, this is quite time consuming because there could be multiple files that are missing something, but the GEOS-Chem run only identifies one at a time.  When I go to the file itself and use  "ncdump -h" there is nothing obvious to me that is wrong? Any insight would be much appreciated! 

### Description of troubleshooting performed
The trouble-shooting I have tried so far is just to remove and redownload the missing file, which seems to work ok. This makes me wonder if the dry run ran correctly, or if there is an issue with the run script? 

### GEOS-Chem version
I used GEOS-Chem v13.1.1

### Description of modifications
GEOSFP
Full-chem
Grid resolution 4.0x5.0
72 levels

### Log files
I have attached the GC and HEMCO log files as well as screenshots of when I do "ncdump-h" on the file that the log files indicate was not able to be read. 
![ncdump_GCExtDatafile_Part1](https://user-images.githubusercontent.com/70339432/132253621-66bc4534-7d33-443b-993f-a267db710d50.JPG)
![ncdump_GCExtDatafile_Part2](https://user-images.githubusercontent.com/70339432/132253622-e5f4de4c-f113-400d-8dd9-2ea2e5fd02c6.JPG)
![GClog_error](https://user-images.githubusercontent.com/70339432/132253623-7ae0553d-15b8-49ee-b0d3-c9fbcbb2c227.JPG)
![HEMCOlogerror](https://user-images.githubusercontent.com/70339432/132253751-b3403091-fcd9-465f-bc90-d26bc9578283.JPG)
[GC.log.txt](https://github.com/geoschem/geos-chem/files/7117518/GC.log.txt)
[HEMCOlog.txt](https://github.com/geoschem/geos-chem/files/7117524/HEMCOlog.txt)

**Comment by tessac2** [comment]
After redownloading the file shown in the above images, I ran the model again and got a similar error but for another ExtData file. Again, I am unsure why this is happening, I was able to do a different run with MERRA2 over the same time period with no issues. 
![image](https://user-images.githubusercontent.com/70339432/133317487-6008aad0-8d9b-4ede-bee6-56598ab138ef.png)

**Comment by yantosca** [comment]
Thanks for writing @tessac2.  Were you getting data from ComputeCanada?  If so, that server was having issues recently.

In GEOS-Chem 13.2.1 (released this week), the dry-run can now download data from the WashU server (https://geoschemdata.wustl.edu), which will eventually replace ComputeCanada.  If you have trouble getting data from one server (or not all files come over properly), then you can do a new dry-run for the same time period, and then download data from a different server.  That should pick up the missing data.

If UIUC has a Globus Endpoint, then you can transfer data directly via Globus from the WashU server (use endpoint name `GEOS-Chem Data (WashU)`).   Globus is very fast file transfer.  That might be an option for you as well.

**Comment by tessac2** [comment]
Thank you @yantosca for your reply! I had been getting data from ComputeCanada. I will try running the new GEOS-Chem 13.2.1 with downloading data from the WashU server and see if that works, and follow up accordingly. Thank you for your help!

**Comment by yantosca** [comment]
I will close out this issue.  Please feel free to open a new issue if you are still having problems with the dry-run or data transfer.
