### ISSUE TITLE
[FEATURE REQUEST] Make sure that createRunDir.sh scripts for GCC and GCHP use "main" for the default Git branch

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#885]
The run directory creation scripts (`run/GCClassic/createRunDir.sh` and `run/GCHP/createRunDir.sh`) allow you to put the configuration files in a created run directory under Git version control.  However, by default, the main branch is named `master`, and should be renamed to `main` for consistency with GEOS-Chem Git repo usage.

**Comment by lizziel** [comment]
People can set git to do this for all new directories put under version control with this command:
`git config --global init.defaultBranch main`

**Comment by msulprizio** [comment]
Thanks @lizziel!

Is this update needed anymore? I'm going to remove the 13.2.1 milestone, but we can always add this update to a future version.

**Comment by yantosca** [comment]
This update isn't needed.  I can close.
