### ISSUE TITLE
Forbidden error (403) while trying to download data from wustl server from Russia

### ISSUE THREAD

**Issue by MikhailKleymenov** [geoschem/geos-chem#891]
Hello! 

I'm trying to download offline lighting data v2020-03 for merra2 2020 run but I can't do it neither using wget no through website. 

--2021-09-14 11:20:35--  http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_LIGHTNING/v2020-03/MERRA2/2020/FLASH_CTH_MERRA2_0.5x0.625_2020_01.nc4
Распознаётся geoschemdata.wustl.edu (geoschemdata.wustl.edu)… 35.209.233.133
Подключение к geoschemdata.wustl.edu (geoschemdata.wustl.edu)|35.209.233.133|:80... соединение установлено.
HTTP-запрос отправлен. Ожидание ответа… 403 Forbidden
2021-09-14 11:20:40 ОШИБКА 403: Forbidden.

The website says I don't have permission to access this resource.

I will be grateful for any help.

**Comment by yantosca** [comment]
Thanks for writing @MikhailKleymenov.   I know that the sysadmins for the WashU server were working on adding some folder permissions.  I also do not have permission to view the folder from the USA.  I am tagging @LiamBindle and @YanshunLi-washu, who are at WashU and can probably speak better to this issue than I can.

**Comment by LiamBindle** [comment]
Hi @MikhailKleymenov thanks for reporting this. I fix the permissions for those files. Can you try again now?

**Comment by MikhailKleymenov** [comment]
Hi @LiamBindle Now I can download them, wget works. Thanks!

**Comment by LiamBindle** [comment]
Great! Thanks for reporting this.
