### ISSUE TITLE
Many emissions diagnostics are 0 in mercury model GCClassic 13.1.1 output [BUG/ISSUE]

### ISSUE THREAD

**Issue by hmhorow** [geoschem/geos-chem#895]
### Description of the problem
When running the mercury model in GC version 13.1.1 out of the box, many of the emissions diagnostics in the GEOSChem.MercuryEmis.YYYYMMDD_0000z.nc4 output file are 0 everywhere for each month: EmisHg0anthro; EmisHg0geogenic; EmisHg2rivers; EmisHg2snowToOcean; EmisHg2HgPanthro; and EmisHg0vegetation. I am not sure if this is just a saving out the diagnostic issue or if in the model itself the anthropogenic emissions, for example, are not being properly read in/used. I haven't done more debugging yet on that. 

Also, unrelated to the above, I believe the long_name of FluxHg0fromAirToOcean and FluxHg0fromOceanToAir in the GEOSChem.MercuryOcean.YYYYMMDD_0000z.nc4 files are reversed (based on plotting these two diagnostics to confirm). See the variable names and descriptions here from ncdump -h:
<img width="939" alt="Screen Shot 2021-09-16 at 10 25 06 AM" src="https://user-images.githubusercontent.com/1387715/133640169-befa8b60-de97-486b-acdb-b4c9caace0c7.png">

### GEOS-Chem version
13.1.1, unmodified

### Log files
- Run logs (if applicable): 
[HEMCO.log](https://github.com/geoschem/geos-chem/files/7179065/HEMCO.log)
[GC.log.1year.txt](https://github.com/geoschem/geos-chem/files/7179068/GC.log.1year.txt)

### Software versions
- CMake version: 3.19.2
- Compilers (Intel or GNU, and version): gcc 9.3.0
- NetCDF version: NetCDF-c: 4.7.4; netCDF-fortran: 4.5.3

Example of a monthly mercury emissions NetCDF output file: https://www.dropbox.com/s/rutuil6lkf61jas/GEOSChem.MercuryEmis.20190101_0000z.nc4?dl=0 

tagging @jennyfisher and @viral211 here as this doesn't seem to be an issue in 12.9. Thanks all!

**Comment by yantosca** [comment]
Thanks for writing @hmhorow.  I added the Hg diagnostics in netCDF form but we never were able to do a deep dive into validating these.  I believe you can still get the old bpch diagnostics for the Hg simulation (am not 100% sure).

Also in the older versions many of the Hg diagnostics were kept as manual HEMCO diagnostics.  I

The issue with the flux diagnostics may just be a metadata issue -- the wrong long name for the given name.  I can doublecheck.

Also note: @msl3v and @viral211 have been working on porting the Hg chemistry to a KPP-built mechanism. This is in testing now and should hopefully be ready by 13.4.0 (pending validation).  This ought to simplify the Hg code base.

**Comment by msulprizio** [comment]
I believe the fix submitted in https://github.com/geoschem/HEMCO/pull/121 should resolve this issue. I have asked @yantosca to confirm that this does in fact resolve the diagnostic issues in the Hg simulation.

**Comment by yantosca** [comment]
This should now be fixed in [GEOS-Chem bugfix version 13.3.3](https://github.com/geoschem/GCClassic/releases/tag/13.3.3).  We can close out this issue now.
