### ISSUE TITLE
online sea salt emissions are 0 for GC version 13 up until version 13.2.0 [BUG/ISSUE]

### ISSUE THREAD

**Issue by hmhorow** [geoschem/geos-chem#896]
### Description of the problem
When running GCClassic version 13.1.1 with online sea salt emissions, sea salt emissions are 0 everywhere (EmisSALA_Natural and EmisSALC_Natural) for both HEMCO standalone and GC. In the GC run EmisSALACL_Natural and EmisSALCCL_Natural are also 0 everywhere. I believe this issue would be the same for all GC version 13.0.0 onwards until the blowing snow sea salt emissions code from Lyatt Jaegle and Jiayue Huang was introduced in 13.2.0, as I do not think there were any changes to hcox_seasalt_mod.F90 after 13.0.0 and prior to 13.2.0.  

### Description of troubleshooting performed
In version 13.2.0, FROCEAN and FRSEAICE are used to diagnose where open ocean sea salt emissions should exist. In version 13.1.1, HCO_LANDTYPE was used. Here is a comparison:

**13.2.0:**
<img width="608" alt="Screen Shot 2021-09-16 at 11 52 58 AM" src="https://user-images.githubusercontent.com/1387715/133653512-fab3223a-803d-4eb8-b3c0-10772b4e1818.png">

**13.1.1:** 
<img width="586" alt="Screen Shot 2021-09-16 at 11 52 01 AM" src="https://user-images.githubusercontent.com/1387715/133653609-de34983e-985a-452f-ad54-0e2625d6f947.png">

### GEOS-Chem version
13.1.1 unmodified

### Log files
- HEMCO Standalone MERRA 2 4x5 config file and log files, 1 month July 2019: 
[HEMCO_Config_SA.rc.txt](https://github.com/geoschem/geos-chem/files/7179528/HEMCO_Config_SA.rc.txt)
[HEMCO_SA.log](https://github.com/geoschem/geos-chem/files/7179529/HEMCO_SA.log)
[HEMCO.log](https://github.com/geoschem/geos-chem/files/7179530/HEMCO.log)
emissions output: https://www.dropbox.com/s/lu70ltwdsf5m4pm/HEMCO_sa_diagnostics.201907010000.nc?dl=0

- GC standard 4x5 MERRA 2, 1 day July 1, 2019 Config and log files:
[GC.Online_SS.1day.log](https://github.com/geoschem/geos-chem/files/7179618/GC.Online_SS.1day.log)
[HEMCO_GC.log](https://github.com/geoschem/geos-chem/files/7179620/HEMCO_GC.log)
[HEMCO_Config_GC.rc.txt](https://github.com/geoschem/geos-chem/files/7179621/HEMCO_Config_GC.rc.txt)
emissions output: https://www.dropbox.com/s/mckwlqf8q9yxh6h/HEMCO_diagnostics.201907010000_GC.nc?dl=0

### Software versions
- CMake version: 3.19.2
- Compilers (Intel or GNU, and version): gcc 9.3.0
- NetCDF version: C: 4.7.4 ; Fortran: 4.5.3

**Comment by msulprizio** [comment]
Hi @hmhorow. Can you also upload your HEMCO_Diagn.rc file? I want to check to ensure the ExtNr and Cat in HEMCO_Diagn.rc match those that are being used in HEMCO_Config.rc. By default, I believe they are set to:

```
###############################################################################
#####  Sea salt emissions                                                 #####
###############################################################################
EmisSALA_Natural     SALA  0      3   -1   2   kg/m2/s  SALA_emission_flux_from_natural_sources
EmisBrSALA_Natural BrSALA  0      3   -1   2   kg/m2/s  BrSALA_emission_flux_from_natural_sources
EmisSALAAL_Natural SALAAL  0      3   -1   2   kg/m2/s  SALAAL_emission_flux_from_natural_sources
EmisSALACL_Natural SALACL  0      3   -1   2   kg/m2/s  SALACL_emission_flux_from_natural_sources
EmisSALC_Natural     SALC  0      3   -1   2   kg/m2/s  SALC_emission_flux_from_natural_sources
EmisBrSALC_Natural BrSALC  0      3   -1   2   kg/m2/s  BrSALC_emission_flux_from_natural_sources
EmisSALCAL_Natural SALCAL  0      3   -1   2   kg/m2/s  SALCAL_emission_flux_from_natural_sources
EmisSALCCL_Natural SALCCL  0      3   -1   2   kg/m2/s  SALCCL_emission_flux_from_natural_sources
```

which reflects obtaining sea salt emissions from OFFLINE_SEASALT. When switching to online sea salt emissions, those entries should be changed to:

```
###############################################################################
#####  Sea salt emissions                                                 #####
###############################################################################
EmisSALA_Natural     SALA  107    -1  -1   2   kg/m2/s  SALA_emission_flux_from_natural_sources
EmisBrSALA_Natural BrSALA  107    -1  -1   2   kg/m2/s  BrSALA_emission_flux_from_natural_sources
EmisSALAAL_Natural SALAAL  107    -1  -1   2   kg/m2/s  SALAAL_emission_flux_from_natural_sources
EmisSALACL_Natural SALACL  107    -1  -1   2   kg/m2/s  SALACL_emission_flux_from_natural_sources
EmisSALC_Natural     SALC  107    -1  -1   2   kg/m2/s  SALC_emission_flux_from_natural_sources
EmisBrSALC_Natural BrSALC  107    -1  -1   2   kg/m2/s  BrSALC_emission_flux_from_natural_sources
EmisSALCAL_Natural SALCAL  107    -1  -1   2   kg/m2/s  SALCAL_emission_flux_from_natural_sources
EmisSALCCL_Natural SALCCL  107    -1  -1   2   kg/m2/s  SALCCL_emission_flux_from_natural_sources
```

**Comment by hmhorow** [comment]
Hi @msulprizio - thank you so much for your help!! I feel pretty silly because that is definitely the answer. I just compared my HEMCO_Diagn.rc to what you sent and it was like the first case with ExtNr=0 and Cat = 3, not the second one you included above with ExtNr=107 and Cat=-1. I also tried running online seasalt with 13.2.0 and the same HEMCO_Diagn.rc file (so ExtNr=0 and Cat = 3) and the emissions were also 0. So that's the issue it would seem. 

I had no idea I needed to change settings in the HEMCO_Diagn.rc file. perhaps this could be noted in the HEMCO_Config.rc file where it made it seem to me like all you had to do is turn 2 switches:
```
# ----- OFFLINE EMISSIONS -------------------------------------
# To use online emissions instead set the offline emissions to
# 'false' and the corresponding HEMCO extension to 'on':
#   OFFLINE_DUST        - DustDead or DustGinoux
#   OFFLINE_BIOGENICVOC - MEGAN
#    - Note: MEGAN must always be on for certain
#            species not in OFFLINE_BIOGENICVOC
#   OFFLINE_SEASALT     - SeaSalt
#   OFFLINE_SOILNOX     - SoilNOx
```
I see the ExtNr described with respect to the configuration file here: http://wiki.seas.harvard.edu/geos-chem/index.php/The_HEMCO_User%27s_Guide#Extension_switches; and I see an example of adding new emissions that mentions the ExtNr in the HEMCO_Diagn.rc file: http://wiki.seas.harvard.edu/geos-chem/index.php/The_HEMCO_User%27s_Guide#Example_4:_Adding_biomass_burning_emissions . But I would not have thought to look at those wiki pages for changing offline to online emissions. 

(I do wonder though if you would get different results using a FROCEAN/FRSEAICE-based definition vs. HCO_LANDTYPE definition of where the ocean is. that's a separate question though and not a bug of course! )

Thanks again!

**Comment by msulprizio** [comment]
That's a great suggestion @hmhorow. We will add a note to HEMCO_Config.rc to let users know they should also change the values in HEMCO_Diagn.rc when switching between offline and online emissions.

The change to use FROCEAN and FRSEAICE in 13.2.0 did introduce changes in sea salt emissions along coasts. This change is discussed in https://github.com/geoschem/geos-chem/pull/356. There @lizziel also links to [internal 1-month benchmark results](http://ftp.as.harvard.edu/gcgrid/geos-chem/validation/BlowingSnow/GCC_version_comparison/) to evaluate the impact of these updates. See specifically [these plots showing the difference in natural emissions](http://ftp.as.harvard.edu/gcgrid/geos-chem/validation/BlowingSnow/GCC_version_comparison/Emissions/Natural_Emissions.pdf).

**Comment by hmhorow** [comment]
thank you so much for the info @msulprizio, this is really helpful!
