### ISSUE TITLE
[BUG/ISSUE] Missing variables in 0.5x0.625 offline seasalt emission after 2018

### ISSUE THREAD

**Issue by xpye98** [geoschem/geos-chem#900]
### Description of the problem
After 2018, 0.5x0.625 offline seasalt emission file miss `SALA_TOTAL` and `SALC_TOTAL` variables, but have `EmisSALA_Natural` and `EmisSALC_Natural`.

Should we modify`HEMCO_Config.rc` file to adapt this change?

**Comment by msulprizio** [comment]
The 0.5x0.625 offline seasalt emission files look OK on our end at Harvard. All files through 2019/09/30 have the `SALA_TOTAL` and `SALC_TOTAL` variables. We obtained these files from ComputeCanada. 

However, I do see a switch `SALA_TOTAL` and `SALC_TOTAL` to `EmisSALA_Natural` and `EmisSALC_Natural` in the 0.25x0.3125 files on 2019/11/01. From the history attribute in those files, it appears that files before that date were processed by Jun Meng, but files after that date were processed by Hongjian Weng.

@hongjianweng or @YanshunLi-washu Could you look into this and ensure we are using consistent variable names for all dates?

@xpye98 As a workaround in the meantime, yes, you can change HEMCO_Config.rc for those dates to look for the `EmisSALA_Natural` and `EmisSALC_Natural` variables.

**Comment by YanshunLi-washu** [comment]
Hi @hongjianweng Could you kindly look into it? I don't have much information about this. Thanks!

**Comment by yantosca** [comment]
@hongjianweng @YanshunLi-washu @msulprizio I wonder if this came about due to using two different versions of the HEMCO standalone.  In older versions I think the default emission names in HEMCO_DIagn.rc were SALA_TOTAL and SALC_TOTAL but in one of the 12.x versions that got changed to EmisSALA_Total and EmisSALC_Total.  If that helps.

One thing that could be done is to rename the older names with nco  so as not to have to rerun the whole interval.

**Comment by xpye98** [comment]
Thanks for your help.
I think rename the variable with n

**Comment by xpye98** [comment]
Thanks for your help!
I think rename the variable with nco/cdo would be a good idea as long as these variables are identical.

**Comment by hongjianweng** [comment]
Yes, after the 12.3.2 version, the default emission names are EmisSALA_Total and EmisSALC_Total. And the difference between different versions of the HEMCO standalone for sea salt aerosols is just emission names.
The 0.5x0.625 offline seasalt emission files' names are SALA_TOTAL and SALC_TOTAL at Harvard and Compute Canada for all dates.
The 0.25x0.3125 change to EmisSALA_Total and EmisSALC_Total for 2019/11/01-2019/12/31 at Harvard and Compute Canada. 
Xingpei's data are from Dalhousie, the 0.5x0.625 and 0.25x0.3125 change to EmisSALA_Total and EmisSALC_Total after 2018.

**Comment by msulprizio** [comment]
Thanks for confirming @hongjianweng. I vote we go with Bob's suggestion and run a script on any files using `EmisSALA_Total` and `EmisSALC_Total` in `HEMCO/OFFLINE_SEASALT/v2019-01/` to ensure all files in that directory consistently use `SALA_TOTAL` and `SALC_TOTAL`. @YanshunLi-washu or @hongjianweng Is this something that you could do? I think it would need to be done at WashU and then we can update the files at Compute Canada and Harvard. 

@hongjianweng If I understand correctly, you're in the process of updating the offline seasalt emissions to include the blowing snow and other recent updates? If that's the case, we'll need to create a new directory `HEMCO/OFFLINE_SEASALT/vYYYY-MM` for those files when they are available. It would be fine for those files to use a different variable name, but we should ensure all files within the same vYYYY-MM directory have the same format to avoid continuity issues when running HEMCO and/or GEOS-Chem.

**Comment by msulprizio** [comment]
According to [the HEMCO issue](https://github.com/geoschem/HEMCO/issues/103) referenced above. This is also a problem in the offline soil NOx files.

**Comment by msulprizio** [comment]
>I vote we go with Bob's suggestion and run a script on any files using EmisSALA_Total and EmisSALC_Total in HEMCO/OFFLINE_SEASALT/v2019-01/ to ensure all files in that directory consistently use SALA_TOTAL and SALC_TOTAL. @YanshunLi-washu or @hongjianweng Is this something that you could do? I think it would need to be done at WashU and then we can update the files at Compute Canada and Harvard.

@YanshunLi-washu would you be able to take care of correcting the variable names in the affected files?

**Comment by YanshunLi-washu** [comment]
@msulprizio Yes. I'll work with @hongjianweng to fix it and let you know ASAP. Thanks

**Comment by hmhorow** [comment]
@YanshunLi-washu we ran into this issue and as of today on the WashU server it appears that the variables have not yet been renamed at least in the offline seasalt files in November 2019 onwards. 
Could you let us know the timeline on this or should we rename the variables ourselves? Thank you so much!

**Comment by YanshunLi-washu** [comment]
@hmhorow Apology for the delay. I've been recently busy with fixing corrupted met fields on the data portal. Will start to work on the variable name issue this week. Thanks for your patience.

**Comment by hmhorow** [comment]
@YanshunLi-washu I tested for a file in November and saw the renamed variables, so I think it worked, thank you so much!!

**Comment by YanshunLi-washu** [comment]
@hmhorow No problem! Hi @msulprizio, could we close this one?

**Comment by tessac2** [comment]
@YanshunLi-washu @hmhorow I noticed this same issue is happening with the OFFLINE_SOILNOX/ files, where starting November 2019 the variable is named "EmisNO_Soil" rather than "SOIL_NOx" --would it be possible to also update these variable names? Thanks!

**Comment by tessac2** [comment]
@msulprizio @YanshunLi-washu @hmhorow  Just wanted to follow up on the above comment and see what the time estimate may be for the variable names for OFFLINE_SOILNOX/ November and December files in the 0.25x0.3125 to be updated? Thank you!

**Comment by YanshunLi-washu** [comment]
Hi @tessac2 It should be good row. I renamed the variables to "SOIL_NOx". Let me know anything else.

**Comment by amy1916** [comment]
The 0.25x0.3125 November and December 2019 files for OFFLINE_SEASALT and OFFLINE_SOILNOX are still showing the previous variable names “EmisSALA_Natural / EmisSALC_Natural” and “EmisNO_Soil” rather than the renamed variable names “SALA_Total / SALC_Total” and “SOIL_NOx” on the WashU server. Would you be able to take a look at this please? Thanks

**Comment by kilicomu** [comment]
+1 to @amy1916 's comment - the following 0.25x0.3125 files seem to still have different variable names:

```
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/11/seasalt_025.20191101.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/11/seasalt_025.20191102.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/11/seasalt_025.20191103.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/11/seasalt_025.20191104.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/11/seasalt_025.20191105.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/11/seasalt_025.20191106.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/11/seasalt_025.20191107.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/11/seasalt_025.20191108.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/11/seasalt_025.20191109.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/11/seasalt_025.20191110.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/11/seasalt_025.20191111.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/11/seasalt_025.20191112.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/11/seasalt_025.20191113.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/11/seasalt_025.20191114.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/11/seasalt_025.20191115.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/11/seasalt_025.20191116.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/11/seasalt_025.20191117.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/11/seasalt_025.20191118.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/11/seasalt_025.20191119.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/11/seasalt_025.20191120.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/11/seasalt_025.20191121.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/11/seasalt_025.20191122.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/11/seasalt_025.20191123.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/11/seasalt_025.20191124.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/11/seasalt_025.20191125.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/11/seasalt_025.20191126.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/11/seasalt_025.20191127.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/11/seasalt_025.20191128.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/11/seasalt_025.20191129.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/11/seasalt_025.20191130.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/12/seasalt_025.20191201.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/12/seasalt_025.20191202.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/12/seasalt_025.20191203.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/12/seasalt_025.20191204.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/12/seasalt_025.20191205.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/12/seasalt_025.20191206.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/12/seasalt_025.20191207.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/12/seasalt_025.20191208.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/12/seasalt_025.20191209.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/12/seasalt_025.20191210.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/12/seasalt_025.20191211.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/12/seasalt_025.20191212.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/12/seasalt_025.20191213.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/12/seasalt_025.20191214.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/12/seasalt_025.20191215.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/12/seasalt_025.20191216.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/12/seasalt_025.20191217.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/12/seasalt_025.20191218.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/12/seasalt_025.20191219.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/12/seasalt_025.20191220.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/12/seasalt_025.20191221.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/12/seasalt_025.20191222.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/12/seasalt_025.20191223.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/12/seasalt_025.20191224.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/12/seasalt_025.20191225.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/12/seasalt_025.20191226.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/12/seasalt_025.20191227.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/12/seasalt_025.20191228.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/12/seasalt_025.20191229.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/12/seasalt_025.20191230.nc
OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/12/seasalt_025.20191231.nc
```

**Comment by msulprizio** [comment]
@YanshunLi-washu @SaptSinha @Jourdan-He Would one of you be able to look into this and fix the affected files?

**Comment by YanshunLi-washu** [comment]
Hi @amy1916 @kilicomu @msulprizio Thanks for letting us know! Fixed now. Feel free to check:
http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_SOILNOX/v2021-12/0.25x0.3125/2019/
http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_SEASALT/v2019-01/0.25x0.3125/2019/
Anything other questions about these offline emissions, please let @SaptSinha and me know. Thanks.

**Comment by kilicomu** [comment]
@YanshunLi-washu Thanks for fixing that - looks good to me.

I've updated the offline emissions on my system and will let you know if we see any further issues!

**Comment by msulprizio** [comment]
Thanks @YanshunLi-washu!

I will close this issue for now, but others are welcome to comment further here or open a new issue if other problems arise.

**Comment by YanshunLi-washu** [comment]
No problem! @kilicomu @msulprizio
