### ISSUE TITLE
Re-naming HISTORY diagnostic collection names not allowed in version 13.0.2?

### ISSUE THREAD

**Issue by zsx-GitHub** [geoschem/geos-chem#901]
I am using GEOS-Chem version 13.0.2. I find that re-naming HISTORY diagnostic collection names does not work for this version. For example, if I add a diagnostic collection called "SpeciesConc_daily" in HISTORY.rc, I will receive the following message in v13.0.2.log file:
```
Allocating the following fields of the State_Diag object:
===============================================================================
 State_Diag%SpeciesRst            is registered as: SpeciesRst
===============================================================================
GEOS-Chem ERROR: The mapData%slot2Id array corresponding to collection
"SpeciesConc" contains missing values! This can indicate that this collection
is either undefined or turned off.  Please check the HISTORY.rc configuration
file in your run directory.
 -> at Get_Mapping (in module Headers/state_diag_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem ERROR: Error encountered in "Get_Mapping": SpeciesConc
 -> at Get_MapData_and_NumSlots (in module Headers/state_diag_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem ERROR: Error encountered in "Get_MapData_and_NumSlots"!
 -> at Init_and_Register_R8_4D (in module Headers/state_diag_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem ERROR: Error encountered in "Init_and_Register", diagID =SpeciesConc
 -> at Init_State_Diag (in Headers/state_diag_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem ERROR: Error encountered within call to "Init_State_Diag"!
 -> at GC_Init_StateObj (in GeosCore/gc_environment_mod.F90)
===============================================================================

===============================================================================
GEOS-CHEM ERROR: Error encountered in "GC_Init_StateObj!"!
STOP at  -> at GEOS-Chem (in GeosCore/main.F90)
===============================================================================
```

Has anyone encountered same issues as me? Thank you!

**Comment by yantosca** [comment]
Thanks for writing @zsx-GitHub.  Did you also put the `SpeciesConc_daily` in the `COLLECTIONS` list at the top of the `HISTORY.rc` file?  That might be the problem.

This error can also occur if there are new species that have not been added to the `species_database.yml` file.

**Comment by zsx-GitHub** [comment]
Thank you @yantosca! I do put the SpeciesConc_daily in the COLLECTION list, and the species specified to output are all in the species_database.yml because GC works well when using COLLECTION name 'SpeciesConc'. I actually have been adding new 'daily/hourly' collections in previous GC versions and all have been working well.

**Comment by yantosca** [comment]
@zsx-GitHub, can you attach your HISTORY.rc file here? (Rename it to HISTORY.rc.txt and drag & drop into the comment box.)

**Comment by yantosca** [comment]
Closing this issue, it is related to #917

**Comment by zsx-GitHub** [comment]
Hi @yantosca, thank you! But this is a different issue from #917.  Problems in #917 can be resolve by using compiler gfortran 10.2.0. But here the problems remain even after changing to gfortran 10.2.0. 

I am attaching the HISTORY.rc file here to make sense of this issue.

[HISTORY.rc.txt](https://github.com/geoschem/geos-chem/files/7264821/HISTORY.rc.txt)
