### ISSUE TITLE
[BUG/ISSUE] Corrupted MERRA2.20210317.A3dyn.4x5.nc4 at WashU data server

### ISSUE THREAD

**Issue by nicodgomez** [geoschem/geos-chem#902]
### Description of the problem
Hello I am performing full chemistry calculation within the period 2021-03-01 and 2021-04-01, and the calculation ends with the following message,
```
HEMCO ERROR: Cannot find field with valid time stamp in /mnt/d/GCClassic/ExtData/geoschemdata.computecanada.ca/ExtData/GEOS_4x5/MERRA2/2021/03/MERRA2.20210317.A3dyn.4x5.nc4 - Cannot get field DTRAIN. Please check file name and time (incl. time range flag) in the config. file
ERROR LOCATION: HCOIO_READ (hcoio_read_std_mod.F90)
ERROR LOCATION: HCOIO_DataRead (hcoio_dataread_mod.F90)
ERROR LOCATION: ReadList_Fill (hco_readlist_mod.F90)
ERROR LOCATION: ReadList_Read (hco_readlist_mod.F90)
ERROR LOCATION: HCO_RUN (hco_driver_mod.F90)
```
### GEOS-Chem version
13.1.0

### Software versions
- CMake version: 3.21.1
- Compilers (Intel or GNU, and version): GNU 7.5.0
- NetCDF version: 4.6.0

I attach the respective input.geos, HEMCO_Config.rc, HISTORY.rc,  HEMCO.log and GC.log files.

I am running Geos-Chem within Windows Subsystem for Linux in Windows 10. 

Thancks. 
[GC_26.log](https://github.com/geoschem/geos-chem/files/7196769/GC_26.log)
[HEMCO.log](https://github.com/geoschem/geos-chem/files/7196770/HEMCO.log)
[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/7196781/HEMCO_Config.txt)
[HISTORY.txt](https://github.com/geoschem/geos-chem/files/7196783/HISTORY.txt)
[input_geos.txt](https://github.com/geoschem/geos-chem/files/7196788/input_geos.txt)

**Comment by nicodgomez** [comment]
Also I have recently noticed that in http://geoschemdata.wustl.edu/, the corresponding file http://geoschemdata.wustl.edu/ExtData/GEOS_4x5/MERRA2/2021/03/MERRA2.20210317.A3dyn.4x5.nc4 has a size of 342K much less than the others' MERRA2.year/mounth/date.A3dyn.4x5.nc4 files.

**Comment by msulprizio** [comment]
Thanks for bringing this to our attention. @YanshunLi-washu or @LiamBindle could you check the problematic file on your end?

**Comment by YanshunLi-washu** [comment]
Before regridding to the GEOS-Chem ready data file, the original MERRA2 file MERRA2_400.tavg3_3d_asm_Nv.20210317.nc4 on the Washu data portal is found corrupted. I'll try redownload and reprocessing it again. Thanks.

**Comment by yantosca** [comment]
@YanshunLi-washu, is this issue resolved?  If so we can close out this issue.

**Comment by YanshunLi-washu** [comment]
Thanks Bob @yantosca, Yes! The MERRA2.20210317.A3dyn.4x5.nc4 file has been reproduced and uploaded to the WUSTL website. @nicodgomez

**Comment by yantosca** [comment]
Thanks @YanshunLi-washu!  I'll close this issue now.

**Comment by LiamBindle** [comment]
Thanks @YanshunLi-washu!
