### ISSUE TITLE
[FEATURE REQUEST] Revise N2O5 gamma calculation

### ISSUE THREAD

**Issue by viral211** [geoschem/geos-chem#907]
The gamma values for N2O5 hydrolysis on sulfate and sea salt aerosols in version 13 are calculated using the parameterization from [Bertram & Thornton (2009)](https://acp.copernicus.org/articles/9/8351/2009/acp-9-8351-2009.pdf) and [McDuffie et al. (2018](url)) as follows:

<a href="https://www.codecogs.com/eqnedit.php?latex=\gamma(\mathrm{N_2O_5})=AHk,\\&space;A=\frac{4V}{\nu&space;S},k=\beta(1-exp(-\delta[\mathrm{H_2&space;O(l))}])" target="_blank"><img src="https://latex.codecogs.com/svg.latex?\gamma(\mathrm{N_2O_5})=AHk,\\&space;A=\frac{4V}{\nu&space;S},k=\beta(1-exp(-\delta[\mathrm{H_2&space;O(l))}])" title="\gamma(\mathrm{N_2O_5})=AHk,\\ A=\frac{4V}{\nu&space;S},k=\beta(1-exp(-\delta[\mathrm{H_2&space;O(l))}])" /></a>
where _V_ is the aerosol volume per unit volume of air, _S_ is the aerosol surface area per unit volume of air, _H_ is the dimensionless Henry's law coefficient for N2O5, \nu is the molecular speed, and \beta and \delta are constants. (I am not showing the correction terms for nitrate and OA which are not relevant for this discussion)

This expression results in very high gamma values over the oceans. The plot below shows mean gamma values averaged over all aerosol types (area-weighted) in the bottom 2 km for a 1-day simulation. For reference, the maximum gamma values reported in the lab (eg. Bertram & Thornton, 2009) are ~0.03. 
![gN2O5_Feb](https://user-images.githubusercontent.com/43827782/134253179-26accafb-d334-4bef-82e4-f9fda6e8ca77.jpg)

The issue is that _A_ scales as Volume/Surface area and becomes large for coarse-mode sea salt aerosols. The parameterization is based on the assumption that the N2O5 reaction is volume-limited, but [Gaston & Thornton (2016)](https://pubs.acs.org/doi/full/10.1021/acs.jpca.5b11914) show that the reaction is largely diffusion-limited for particles larger than ~100 nm radius.  

I discussed this with Chris Holmes @cdholmes, and we propose to fix this by capping _A_ to 3.2x10^-8, which is the value reported in Bertram & Thornton (2009). This sets the maximum gamma value to ~0.036, and would be consistent with the lab results. Chris, anything you'd like to add?

I would like to ask the Chemistry WG chairs if this would be an acceptable fix. Tagging @mje1398 @barronh.
I can't find the GitHub handles for Lu Hu and Jingqiu Mao and will email them. Also tagging Erin McDuffie @emcduffie.

**Comment by mje1398** [comment]
Hi All, This seems like the parameterization has come up with a very high value there which isn't appropriate. 0.03 on wet sea-salt is what I had in my very old n2o5 parameterization, so the 0.036 cap would seem appropriate. Would that cap all values of gamma or cap the value on sea-salt. 
Mat

**Comment by viral211** [comment]
It would cap all gamma values to 0.036. For internally-mixed fine-mode sulfate-nitrate-ammonium + sea salt aerosols + OA, the cap will apply only when RH exceeds 95% and particle radius becomes larger than 125 nm. For other aerosol types, gamma values are already lower than 0.03.

**Comment by emcduffie** [comment]
Hi Everyone, 

I just wanted to chime in a say that a cap seems reasonable as 0.4 is very high, though also to note that I don’t think we’ve had any observational studies evaluate gamma in the regions where the values are largest and also to highlight that both laboratory and observational studies have derived gamma values larger than 0.036 (Figure 4 and S26 from McDuffie et al., JGR 2018). 


-----
Erin E McDuffie, PhD
2020-2021 AAAS Science and Technology Policy Fellow
Washington, DC
T: 907-720-8917

**Comment by barronh** [comment]
The cap you propose sounds reasonable to me.

**Comment by yantosca** [comment]
Hi @viral211 @mje1398 @emcduffie @barronh, thanks for this update.  We can try to get it into 13.3.0 if there's time.

Also, could someone point me to the code that computes this?  I have a hard time going from formulae to code, as I mostly deal with the code. :-)

**Comment by viral211** [comment]
Hi @yantosca, _A_ is computed here:
https://github.com/geoschem/geos-chem/blob/ba58da4a6e447e47714fe5e7da488d15432a6fdc/KPP/fullchem/gckpp_HetRates.F90#L2345
We will have to add the following lines after the line referenced above:
` ! Cap A at 3.2D-8 to account to prevent high gamma values when Vol/Area is high`
` A = min( A, 3.2e-8_fp )`

**Comment by yantosca** [comment]
Ah OK, thanks, I see it now, in function `N2O5_InorgOrg`.

FYI, in the 13.3.0 code, the `gckpp_HetRates.F90` has been removed and replaced with a new module `fullchem_RateLawUtilFuncs.F90`.

**Comment by jingqiumao** [comment]
I thought the diffusion limit is reflected on the gas diffusion term in reactive uptake calculation. Even with a large gamma, the first-order reactive uptake rate will be still small if the effective radius is large (in this case it is coarse-mode sea salt aerosols). Jacob 2000 paper has a pretty nice explanation on this. 

So I thought the large gamma might not matter much, but I am happy to be corrected.

**Comment by viral211** [comment]
Hi @jingqiumao, I was referring to aqueous-phase diffusion in my original post. You are right that the gas-phase diffusion will limit the effect of a very large gamma, but when gamma is small (say 0.03), the uptake term will limit the loss rate. For coarse-mode sea salt aerosols, the gas-phase diffusion and the reactive uptake terms are about equal when gamma=0.13.

**Comment by jingqiumao** [comment]
Thanks. I don't have a strong opinion against a cap on gamma_N2O5.

Is it possible to show an impact of this change on ozone? I think it might be worthwhile to document this change.

**Comment by yantosca** [comment]
@jingqiumao: We will run "alpha" benchmarks for this update.  These are internal benchmarks that we don't usually publish, but use internally so that we can tie certain changes in output to a certain feature.  I can post the OH metrics here.

**Comment by yantosca** [comment]
This is now fixed with commit 2833e4d651ea58bff5cc56ff0d7ebaa37d9fb5a2.   Awaiting PR review and merge.

**Comment by jingqiumao** [comment]
Thanks @yantosca. It would be great to know the impact on ozone as well.

**Comment by msulprizio** [comment]
I ran an internal 1-month benchmark to evaluate the impact of these changes (tagged as `13.3.0-alpha.5`). The benchmark plots and tables may be viewed at http://ftp.as.harvard.edu/gcgrid/geos-chem/validation/InternalBenchmarks/GCC_13.3.0-alpha.5/. The OH metrics are included below for quick review:

```
###############################################################################
### OH Metrics
### Ref = GCC_13.3.0-alpha.4; Dev = GCC_13.3.0-alpha.5
###############################################################################

------------------------------------------------------------
Global mass-weighted OH concentration [10^5 molec cm^-3]
------------------------------------------------------------
Ref      : 11.79245633477
Dev      : 11.80156821346
Abs diff :  0.00911187869
%   diff :  0.077269

------------------------------------------------------------
CH3CCl3 (aka MCF) lifetime w/r/t tropospheric OH [years]
------------------------------------------------------------
Ref      :  5.246796
Dev      :  5.240901
Abs diff : -0.005895
%   diff : -0.112358

------------------------------------------------------------
CH4 lifetime w/r/t tropospheric OH [years]
------------------------------------------------------------
Ref      :  8.841421
Dev      :  8.831226
Abs diff : -0.010196
%   diff : -0.115316
```

@jingqiumao The impact on O3 specifically may be viewed in the plots found in http://ftp.as.harvard.edu/gcgrid/geos-chem/validation/InternalBenchmarks/GCC_13.3.0-alpha.5/Oxidants/.

I will close out this issue for now since this is now included in the `dev` branch and will officially be benchmarked in 13.3.0, but please feel free to comment here on any of the changes to model output.

**Comment by jingqiumao** [comment]
Thanks so much, Melissa! This is consistent with what I have in mind. The effect on O3 should be small, as coarse-mode aerosols should only contribute to a small fraction of aerosol surface area, and thus have little impact on N2O5 loss and O3 production.
