### ISSUE TITLE
[FEATURE REQUEST] Convert all .F files to .F90

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#92]
We should be using Fortran90 where possible. This will facilitate running GEOS-Chem in external models. Third-party code (e.g. ISORROPIA, RRTMG) will be left untouched.

**Comment by yantosca** [comment]
This tool may be of use: https://people.sc.fsu.edu/~jburkardt/f_src/f90_to_f77/f90_to_f77.html

**Comment by yantosca** [comment]
This tool may be useful.  I'll test it out.
https://people.sc.fsu.edu/~jburkardt/f_src/f77_to_f90/f77_to_f90.html

**Comment by msulprizio** [comment]
Thanks, @yantosca. I did already see and test out that tool and a few others. I'm using a hybrid approach (running automated scripts then fixing manually). I've already made good progress and will push to a development branch soon.

**Comment by yantosca** [comment]
We anticipate this will be done for the 13.0.0 release.

**Comment by msulprizio** [comment]
This is now included in the `dev/12.8.0` branch.

**Comment by msulprizio** [comment]
These updates also include:
* Moving [GEOS-Chem timers](http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_timers) to an option in input.geos instead of a compile option
* Moving `IS_WATER`, `IS_LAND`, and similar fields to `State_Met`
* Replacing `am_I_Root` with `Input_Opt%amIRoot` (https://github.com/geoschem/geos-chem/issues/102)
* Removing `USE CMN_SIZE_Mod` where it is not needed
* Using `prtDebug = ( Input_Opt%LPRT .and. Input_Opt%amIRoot )` consistently throughout code
* Cleaning up revision history comments to point to Github repository instead
* Cleaning up C-preprocessor switches (https://github.com/geoschem/geos-chem/issues/168)
