### ISSUE TITLE
[BUG/ISSUE] KPP 2.2.5 git pulls 2.2.3

### ISSUE THREAD

**Issue by tscarter** [geoschem/geos-chem#930]
I am trying to customize the GC chemical mechanism, which means, as I understand it, that I need to install KPP-for-GEOS-Chem 2.2.5_gc – for GEOS-Chem 13.0.2 and earlier since I am running 13.0.0. However, when I use the commands on the website (copied below), I get the kpp-2.2.3 instead. This seems to be at least one of the reasons  why kpp compiling is failing. Any thoughts you have would be appreciated. Thanks!

git clone -b 2.2.5_gc https://github.com/geoschem/KPP.git

git -C KPP branch 2.2.5_gc

**Comment by yantosca** [comment]
Hi @tscarter, thanks for writing.  It may be due to the version of Git that you have.  If you have an older version of Git (like before 1.8.5), then `git clone -b` isn't implemented.   Then you have to manually check out the tag and create a branch at the tag.

I was able to do the following commands on my server:
```console
$ git --version
git version 2.17.0

$ git clone -b 2.2.5_gc https://github.com/geoschem/KPP.git
Cloning into 'KPP'...
remote: Enumerating objects: 1144, done.
remote: Counting objects: 100% (432/432), done.
remote: Compressing objects: 100% (261/261), done.
remote: Total 1144 (delta 249), reused 336 (delta 161), pack-reused 712
Receiving objects: 100% (1144/1144), 4.10 MiB | 9.49 MiB/s, done.
Resolving deltas: 100% (638/638), done.
Note: checking out '2d83bdeabd5bcc9b2a8e9c31946f75d678a484d2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

$ cd KPP

$ git log --oneline -1
2d83bde (HEAD, tag: 2.2.5_gc) Increase MAX_INLINE from 20000 to 50000; update version to 2.2.5_gc

$ git branch KPP_2.2.5_gc

$ git log --oneline -1
2d83bde (HEAD, tag: 2.2.5_gc, KPP_2.2.5_gc) Increase MAX_INLINE from 20000 to 50000; update version to 2.2.5_gc
```

So the original git clone was able to checkout the commit at 2.2.5_gc, as noted by the output of `git log --oneline -`.  Then I was able to make a new branch at that spot.

Do you know your Git version?  Type `git --version` to find out.

**Comment by yantosca** [comment]
I can update the RTD page when I get a chance.

Also note: @laestrada and I are preparing a new KPP repository, where all of the updates in the different branches are merged into the main branch.  This is definitely a work in progress.   Until that happens the geoschem/KPP repo is still the one to use.

**Comment by yantosca** [comment]
If the `-b` option doesn't work, you can do this:

```console
$ git clone https://github.com/geoschem/KPP.git
Cloning into 'KPP'...
remote: Enumerating objects: 1144, done.
remote: Counting objects: 100% (432/432), done.
remote: Compressing objects: 100% (261/261), done.
remote: Total 1144 (delta 249), reused 336 (delta 161), pack-reused 712
Receiving objects: 100% (1144/1144), 4.10 MiB | 9.49 MiB/s, done.
Resolving deltas: 100% (638/638), done.
Note: checking out '2d83bdeabd5bcc9b2a8e9c31946f75d678a484d2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

$ git branch KPP_2.2.5_gc

$ git checkout KPP_2.2.5_gc

$ git log --oneline -1
2d83bde (HEAD, tag: 2.2.5_gc, KPP_2.2.5_gc) Increase MAX_INLINE from 20000 to 50000; update version to 2.2.5_gc
```
So you have to do the `git clone` and the `git branch` commands separately.

**Comment by tscarter** [comment]
Thanks for such a quick reply. Our git version is much later (2.9.5), so I
don't think it's that.

I tried your second suggestion of separating out the commands, but I run
into the following error when running "git branch KPP_2.2.5_gc":
Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

Any ideas?

**Comment by yantosca** [comment]
Ooops, I think I got the order wrong.  Git checkout comes first, then git branch.

```console
$ git clone https://github.com/geoschem/KPP.git
$ cd KPP
$ git checkout 2.2.5_gc
$ git branch KPP_2.2.5_gc
$ git log --oneline
2d83bde (HEAD, tag: 2.2.5_gc, KPP_2.2.5_gc) Increase MAX_INLINE from 20000 to 50000; update version to 2.2.5_gc
```
then you'll see the commit checked out at the tag 2.2.5_gc and then also checked out on the branch KPP_2.2.5_gc.

Sorry for the confusion!

**Comment by tscarter** [comment]
Thanks! That worked; although, it still named it kpp-2.2.3_01. I do have
the log write out: Increase MAX_INLINE from 20000 to 50000; update version
to 2.2.5_gc. So should I assume that I have the correct version of KPP but
that it is just named incorrectly?

**Comment by tscarter** [comment]
Perfect. Thanks!

**Comment by yantosca** [comment]
Great.  I'll close out this issue.  Stay tuned for more news about our new KPP repo (but it will might take a while before KPP 3.0.0 is ready).
