### ISSUE TITLE
[QUESTION] Some questions for HEMCO diagnostic files

### ISSUE THREAD

**Issue by yfsong0709** [geoschem/geos-chem#931]
Thank you very much for offering this excellent program. When I was trying to run this model to simulate the tagCO concentration, I got some questions for the output results. Look at the following table, which contains the max value for each emission and each day in HEMCO_Diagnostics.YYYYMMDD0000.nc file.
![image](https://user-images.githubusercontent.com/17495679/135612596-6cac45b9-b4e7-4ad6-8ffa-40f1651ff1f4.png)
There are three questions:
(1) I only switch on the biomass emissions (i.e., QFED2), and set the output frequency to ‘daily’, set CER to ‘EF’. Then, I found that the values of EmisCO_BioBurn in diagnostic files (i.e., HEMCO_Diagnostics.YYYYMMDD0000.nc) are all the same. But when I set CER to ‘C’, these values will be changes for each day. Is there any problem in ‘EF’ mode? Or I make some mistakes in some step?
(2) I compared the output values of EmisCO_BioBurn and EmisCO_Total. I found the output values of EmisCO_Total is lower than EmisCO_BioBurn. Why these two values not be equal? 
(3) In addition, I found there was no data in EmisCOus_BioBurn, EmisCOeur_BioBurn, EmisCOasia_BioBurn, EmisCOoth_BioBurn variables. Is this a formal case?
Could you please help me? Thanks again.

**Comment by yantosca** [comment]
Thanks for writing @yfsong0709.  I think `CER` is not an allowed time cycle option.  If you want to apply the QFED2 data only within the data range then you should use `EFY`.  Otherwise, if your simulation goes past the last year of QFED2 data that you have on disk, then you should use `C` instead.
