### ISSUE TITLE
[QUESTION] Query regarding GEOS-Chem model resolution

### ISSUE THREAD

**Issue by arundathi-c** [geoschem/geos-chem#935]
### Ask a question about GEOS-Chem:
Hello! 

I have a query related to set the GEOS-Chem simulations for finer resolutions, other than the currently supported resolutions such as (4.0°x5.0°, 2.0°x2.5°, 0.5°x0.625°, and 0.25°x0.3125°). Is it possible to set up the simulations for finer resolutions by regrinding the input meteorology and by using FlexGrid?

**Comment by yantosca** [comment]
Thanks for writing @arundathi-c.  Technically you probably could go finer than the standard grids in GC-Classic, but you might find that the regridding incurs a large amount of computational overhead.

We would recommend that you look into using GCHP for high-resolution simulations.  GCHP 13.2.0+ now has a stretched-grid feature that allows you to zoom in on a region of interest.  Please see our GCHP manual (https://gchp.readthedocs.io/) for more information.

**Comment by yantosca** [comment]
I am going to close out this issue.  Feel free to contact us if you are still having problems.
