### ISSUE TITLE
[BUG/ISSUE] PM2.5 including dust when running with RCP emissions 

### ISSUE THREAD

**Issue by tiffpangg** [geoschem/geos-chem#938]
Hello, I am using GEOS-Chem for my thesis and I encountered some issues with the PM2.5 aerosol mass mixed in with dust
### Description of the problem
I am looking into PM2.5 levels in the future scenarios of different RCPs, but in different RCPs they all encountered the same problem -- dust is included in the PM2.5 aerosol mass as visualized below:
![2006_PM](https://user-images.githubusercontent.com/77320011/135888999-92cf915a-aad9-4bff-9639-c3acdb5d124c.png)
Desert areas such as North Africa, Central Australia and Northwest China is with high PM2.5 mass, while they should really be mineral dust instead of PM2.5.
This is a result of my base year (2006) with RCP4.5, so it should not be affected much by future scenarios.
The meteorology year is set to be 2015, and I have disabled all other anthropogenic emissions (except shipping) as suggested by #590.

### Description of troubleshooting performed
I tried comparing my results with another grad student, and he got his results from other current-day emission inventories (Not RCP) in other areas similar to mine except for the desert areas. 

### Description of modifications
Since my project was mainly looking into the relationship between NH3 concentration and PM2.5 surface concentration, I have different NH3 concentrations than the RCP's, so I disabled the RCP's NH3 and used my own NH3 emission inventory instead. Otherwise mostly the same as the default.
Not sure if RCP is the issue here or what other mistake made the mineral dust went into the pm2.5 bin...
If it cannot be removed, how could I separate the two?
### GEOS-Chem version
12.9.3

**Comment by yantosca** [comment]
Thanks for writting @tiffpangg.  Can you confirm, is the plot above from the RCP emissions, or is it the PM25 diagnostic from the Aerosols collection?  I wasn't clear on that.

PM2.5 in GEOS-Chem is computed in `GeosCore/aerosol_mod.F90` as:

```F90
       !==============================================================
       ! P A R T I C U L A T E   M A T T E R
       !
       ! Compute PM2.5 concentration [kg/m3]
       !
       ! PM25 = 1.33 (NH4 + NIT  + SO4 + HMS) + BCPI + BCPO +
       !        2.10 (OCPO + 1.16 OCPI) + 1.16 SOA*   +
       !        DST1 + 0.38 DST2 + 1.86 SALA
       !
       !   * If using simple  SOA, SOA = SOAS;
       !     If using complex SOA, SOA = TSOA + ASOA + ISOAAQ
       !
       ! NOTES:
       ! - We apply growth factors at 35% RH (computed above):
       !    1.33 for SO4, NIT, and NH4
       !    1.33 for HMS (jmm, 06/30/18)
       !    1.16 for OCPI and SOA
       !    1.86 for SALA
       ! - Ratio of OM/OC = 2.1 is applied to OCPI and OCPO above
       ! - Aerosol WG recommends including 38% of DST2 in PM2.5
       ! - Use either simple SOA or complex SOA in PM2.5 calculation.
       !   By default simple SOA will be used.
       !
       ! %%% IMPORTANT %%%
       ! Note that if complex SOA is used then PM2.5 includes all
       ! the SOA formed in both the Marais et al. and Pye et al.
       ! schemes and may include some double-counting of isoprene SOA.
       ! (Aerosol WG)
       !==============================================================

       ! Units: [kg/m3]
       PM25(I,J,L) = NH4(I,J,L)        * SIA_GROWTH + &
                     NIT(I,J,L)        * SIA_GROWTH + &
                     SO4(I,J,L)        * SIA_GROWTH + &
                     HMS(I,J,L)        * SIA_GROWTH + &   ! (jmm, 06/30/18)
                     BCPI(I,J,L)                    + &
                     BCPO(I,J,L)                    + &
                     OCPO(I,J,L)                    + &
                     OCPI(I,J,L)       * ORG_GROWTH + &
                     SALA(I,J,L)       * SSA_GROWTH + &
                     SOILDUST(I,J,L,1)              + & ! DST1
                     SOILDUST(I,J,L,2)              + & ! DST1
                     SOILDUST(I,J,L,3)              + & ! DST1
                     SOILDUST(I,J,L,4)              + & ! DST1
                     SOILDUST(I,J,L,5) * 0.38           ! 38% of DST2

       ! Include either simple SOA (default) or Complex SOA in
       ! PM2.5 calculation.  In simulations where both Simple SOA and
       ! Complex SOA species are carried (i.e. "benchmark"), then
       ! only the Simple SOA will be added to PM2.5, in order to avoid
       ! double-counting. (bmy, 5/11/18)
       IF ( Is_SimpleSOA ) THEN
          PM25(I,J,L) = PM25(I,J,L) + SOAS(I,J,L) * ORG_GROWTH
       ELSEIF ( Is_ComplexSOA ) THEN
          PM25(I,J,L) = PM25(I,J,L)                + &
                        TSOA(I,J,L)   * ORG_GROWTH + &
                        ASOA(I,J,L)   * ORG_GROWTH + &
                        ISOAAQ(I,J,L) * ORG_GROWTH    ! Includes SOAGX

          ! Need to add OPOA to PM2.5 for complexSOA_SVPOA simulations
          ! -- Maggie Marvin (15 Jul 2020)
          IF ( Is_OPOA ) THEN
             PM25(I,J,L) = PM25(I,J,L)             + &
                           OPOA(I,J,L) * ORG_GROWTH
          ENDIF
       ENDIF

       ! Apply STP correction factor based on ideal gas law
       PM25(I,J,L) = PM25(I,J,L) * ( 1013.25_fp / PMID(I,J,L) ) * &
                     ( T(I,J,L)   / 298.0_fp    )

... etc ...
```
So there is a dust component of PM2.5 in the standard GEOS-Chem diagnostic output.  You could comment those lines out if you wish to exclude them from the PM2.5 computation.

**Comment by tiffpangg** [comment]
Thank you so much for your answers!

>  is the plot above from the RCP emissions, or is it the PM25 diagnostic from the Aerosols collection? 

It is a plot from the Output file: GEOSChem.AerosolMass_20060501_0000z.nc4 under variable "PM25"

> You could comment those lines out if you wish to exclude them from the PM2.5 computation.

Does it mean to comment out these lines from the `GeosCore/aerosol_mod.F90` file?

```
                     SOILDUST(I,J,L,1)              + & ! DST1
                     SOILDUST(I,J,L,2)              + & ! DST1
                     SOILDUST(I,J,L,3)              + & ! DST1
                     SOILDUST(I,J,L,4)              + & ! DST1
                     SOILDUST(I,J,L,5) * 0.38           ! 38% of DST2
```


also attaching my HEMCO_Config file: 
[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/7307891/HEMCO_Config.txt)

**Comment by yantosca** [comment]
@tiffpangg, yes,  you can comment out those lines listed above if you wish to exclude these from the computation.

I will go ahead and close out this issue now.  Let us know if you should encounter new problems/issues.
