### ISSUE TITLE
[BUG/ISSUE] Problems related to the restart files in 12.9.3 simulations

### ISSUE THREAD

**Issue by alviswong1221** [geoschem/geos-chem#940]
### Description of the problem
I have tried to run GEOS-Chem simulations in a computer cluster. Due to some technical issues, my geos-chem runs may be stopped by the cluster suddenly without any notice. Once the cluster stopped my job, I will re-run the simulation with the start date be the start of the month before the day the simulation stop, for instance, if the run stopped on 17/3/2014, I will start a new simulation with the starting date be 20140201 000000. However, I find that the output result may have some abrupt changes after the date I restarted the simulation every time.

![Rplot01](https://user-images.githubusercontent.com/64476079/135988301-d7b1f08d-6e89-4813-93af-60879c8f333a.png)

These graphs show the percentage changes of PM2.5 compare to my controlled case in 2014. The title of the graphs represents the month of the simulation result. For example, I re-ran the simulation on 20140301 000000, then the result in the months later will be completely different from that on January and February. And again I re-ran the simulation on 20141101 000000, the results in the months later again show complete differences.

I don't know if this is related to the sudden kill of the simulation, hope I can get some insights from you.

On the other hand, I am running a 72 vertical layers 2x2.5 simulation, and the size of the restart files vary from 600-639 mb. May I ask if this is normal to have such size differences in the restart files?
 
### Description of troubleshooting performed
I have tried to look at the sizes of the restart files generated in a 12.2.0 47 vertical layers 2x2.5 simulation, the sizes will just vary by 1-2 mb.

### GEOS-Chem version
12.9.3

**Comment by yantosca** [comment]
Thanks for writing @alviswong1221.  You might need to also update your `HEMCO_Config.rc` file to save out monthly HEMCO restart files.  Otherwise, HEMCO quantities will be re-initialized to zero.

Also, the restart files are netCDF and use compression, so their size may vary somewhat.

**Comment by yantosca** [comment]
Thanks @alviswong1221.  I will close out this issue.  Please contact us again if you are still having problems.
