### ISSUE TITLE
[BUG/ISSUE] No files shown on http://geoschemdata.wustl.edu/ using a web browser

### ISSUE THREAD

**Issue by eamarais** [geoschem/geos-chem#944]
Is there an issue with http://geoschemdata.wustl.edu/ currently? I was only able to download some months of MERRA2 2020 meteorology at 4x5. When I tried to check whether this data was missing on http://geoschemdata.wustl.edu/ using Google Chrome and Safari, the folders appear empty, as in the attached/below screenshot.
 
![Screenshot 2021-10-06 at 15 41 20](https://user-images.githubusercontent.com/55648553/136226522-a7658d7c-257b-41d4-ba4e-e0b0eff867c4.png)

**Comment by YanshunLi-washu** [comment]
Hi @eamarais It was very likely down for maintenance. I just tried myself a few minutes ago. It looks good now. You're also welcome to use the globus endpoint GEOS-Chem Data (WashU).

**Comment by eamarais** [comment]
Thanks @YanshunLi-washu. Is it possible the permissions for the files are not correct? I tried downloading MERRA2 at 4x5 for Jan-July 2020, but get the message "HTTP request sent, awaiting response... 403 Forbidden".
