### ISSUE TITLE
[BUG/ISSUE] Segmentation fault when reading HEMCO_Config.rc

### ISSUE THREAD

**Issue by stefanyim** [geoschem/geos-chem#947]
### Ask a question about GEOS-Chem:
When using GC v11-01 to run geosfp_2x25_soa compiled by ifort17, I meet a segmentation fault as below:

```
===============================================================================

Reading part 1 of HEMCO configuration file: HEMCO_Config.rc
  
Reading part 2 of HEMCO configuration file: HEMCO_Config.rc
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
libintlc.so.5      00002AF4E49A1BF1  tbk_trace_stack_i     Unknown  Unknown
libintlc.so.5      00002AF4E499FD2B  tbk_string_stack_     Unknown  Unknown
libifcoremt.so.5   00002AF4E3485E52  Unknown               Unknown  Unknown
libifcoremt.so.5   00002AF4E3485CA6  tbk_stack_trace       Unknown  Unknown
libifcoremt.so.5   00002AF4E33DFAAE  for__issue_diagno     Unknown  Unknown
libifcoremt.so.5   00002AF4E33F1592  for__signal_handl     Unknown  Unknown
libpthread-2.17.s  00002AF4E4C045E0  Unknown               Unknown  Unknown
libifcoremt.so.5   00002AF4E34688AF  for_trim              Unknown  Unknown
geos.mp            00000000009CE626  hco_extlist_mod_m         713  hco_extlist_mod.F90
geos.mp            0000000000920280  hcox_soilnox_mod_         730  hcox_soilnox_mod.F90
geos.mp            0000000000912F70  hcox_driver_mod_m         193  hcox_driver_mod.F90
geos.mp            00000000007EA104  hcoi_gc_main_mod_         375  hcoi_gc_main_mod.F90
geos.mp            00000000004C9060  MAIN__                    704  main.F
geos.mp            0000000000404A5E  Unknown               Unknown  Unknown
libc-2.17.so       00002AF4E5036C05  __libc_start_main     Unknown  Unknown
geos.mp            0000000000404960  Unknown               Unknown  Unknown
```

I have been set the environment variable as ’export OMP_STACKSIZE=500m’ and ‘ulimit -s unlimited’. The following is content in hco_extlist_mod_m(line 713):

```
    704 !======================================================================
    705     ! GetExtSpcVal_Sp begins here
    706     !======================================================================
    707 
    708     ! Make sure output is properly allocated
    709     IF ( ALLOCATED(SpcScal) ) DEALLOCATE(SpcScal)
    710     ALLOCATE(SpcScal(NSPC))
    711     SpcScal=DefValue
    712 
    713     CALL GetExtSpcVal_Dr ( HcoConfig, ExtNr, NSPC, SpcNames, Prefix, RC, &
    714                            DefVal_SP=DefValue, SpcScal_SP=SpcScal )
    715 
    716     END SUBROUTINE GetExtSpcVal_sp
    717 !EOC
    718 !------------------------------------------------------------------------------
```

I wonder how to solve this problem, thank you very much.

**Comment by yantosca** [comment]
Thanks for writing.  This error seems to be in the Fortran `TRIM()` function when reading HEMCO_Config.rc.  This could happen if the `HEMCO_Config.rc` you are using is from a different version.

Have you tried turning on `VERBOSE: 3` in your `HEMCO_Config.rc` file?   This will increase the amount of debug output sent to the `HEMCO.log` file.  That might help you narrow down where the error is occurring.  

Also, v11-01 is no longer supported, as it is several years old at this point.  We would recommend that you migrate to one of the GEOS-Chem 13 versions if you are able to.

**Comment by stefanyim** [comment]
Thank you @yantosca !! It seems that my `HEMCO_Config.rc` is from the same version. I have tried turning on VERBOSE: 3 in your HEMCO_Config.rc file, but it did not work. Here are the `HEMCO_Config.rc` and `HEMCO.log` before/after I turned on VERBOSE: 3.
[HEMCO_Config&log.zip](https://github.com/geoschem/geos-chem/files/7342453/HEMCO_Config.log.zip)

**Comment by yantosca** [comment]
@stefanyim, because v11-01 is a very old version at this point, we can no longer support it.  I would recommend updating to one of the more recent versions if possible.  If you have to stick with your v11-01 version, please try recompiling with the debug flags turned on (DEBUG=y BOUNDS=y FPEX=y) and see if that fixes your issue.
