### ISSUE TITLE
[BUG/ISSUE]HEMCO ERROR: Cannot find field SPC_COus, Please check variable name in the config. file

### ISSUE THREAD

**Issue by XunZhangNJU** [geoschem/geos-chem#948]
### Description of the problem
When I run GEOS-Chem version 13.2.1, tagged CO, resolution 2.5x2.5, MET restrart files is MERRA2, run time range: 20130701-20130801.

### Description of troubleshooting performed
After compiled,  run ./gcclassic, GC show this error: 
HEMCO ERROR:  Cannot find field SPC_COus, Please check variable name in the config. file

### GEOS-Chem version
gcclassic 13.2.1

### Description of modifications

Restart files: GEOSChem.Restart.2013.0701_0000z.nc4, download from the website:  http://ftp.as.harvard.edu./gcgrid/geos-chem/10yr_beachmarks/13.0.0-rc.0/GCClassic/restarts/. I used software Panoply check the variable: SPC_COus in the GEOSChem.Restart.2013.0701_0000z.nc4, the restart file has not include the variable SPC_COus. so how to fix this issus.
Input.geos and these hemco_configure settings hasn't changed, I only change the run time period, and based on the HEMCO.log error to fix the restart datasets version.  In the end, this error: HEMCO ERROR:  Cannot find field SPC_COus, Please check variable name in the config. file, I don't figure out this problem and confused.

### Log files
- Build log (if applicable): 
- Run logs (if applicable):
- Run script (if applicable):

### Software versions
- CMake version:
- Compilers (Intel or GNU, and version):
- NetCDF version:

**Comment by BlackFreedom** [comment]
Thank you very much for your reply, Prof. Yantosca. I use CYS in the HEMCO_Config and run successfully. I spin up my simulation at least one year, Right?
