### ISSUE TITLE
[BUG/ISSUE] Wrong precision used for MO2 + HO2 reaction in fullchem.eqn

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#951]
In fullchem.eqn, this reaction:
```
MO2 + HO2 = MP + O2 :                        GCARR_abc(4.10E-13, 0.0E+00, 750.0);
```
should use double-precision exponents:
```
MO2 + HO2 = MP + O2 :                        GCARR_abc(4.10d-13, 0.0d0, 750.0d0);
```
to avoid type errors.  

NOTE: This was not flagged by any integration tests using Gfortran 10.2, but @jimmielin reported this issue in a development branch that he was working on.

**Comment by jimmielin** [comment]
These also seem to have single-precision exponents:
```
B3O2 + NO = NO2 + HO2 + ACET :               GC_RO2NO_B2_aca(2.70E-12, 360.0d0, 3.0d0);                                        {2019/05/10; Fisher2018; JAF}
B3O2 + NO = IPRNO3 :                         GC_RO2NO_A2_aca(2.70E-12, 360.0d0, 3.0d0);                                        {2019/05/10; Fisher2018; JAF}
```

Not sure if they also affect compile, but I fixed all of them to pass gfortran compile with standalone KPP.

**Comment by yantosca** [comment]
PR #952 has now been merged into dev.  We can close this issue.
