### ISSUE TITLE
[FEATURE REQUEST] Use Cloud-J as submodule in GEOS-Chem

### ISSUE THREAD

**Issue by lizziel** [geoschem/geos-chem#953]
This feature request supersedes https://github.com/geoschem/geos-chem/issues/666 (Extract FAST-JX code into separate directory). Cloud-J is an improved Fast-J from Michael Prather that can be run as a standalone model. Rather than pull the existing Fast-J out of GEOS-Chem into a separate module I will instead add Cloud-J as a git submodule within the GEOS-Chem super-projects (GC-Classic and GCHP). I will then replace Fast-J with Cloud-J within GEOS-Chem. I am aiming to add this update to GEOS-Chem version 13.4.

The initial phase of this work was getting Cloud-J onto GitHub and setting it up as a supported repository within the GEOS-chem organization. This is now done. See [geoschem/cloud-j](https://github.com/geoschem/cloud-j). This work allows GCST and Michael Prather to serve Cloud-J to the greater community for use in other models.

Pinging people who may want to discuss Cloud-J in GEOS-Chem and beyond: @pratherUCI, @sdeastham, @jennyfisher, @christophkeller

**Comment by yantosca** [comment]
@lizziel: should we remove the `feature/modularize_fjx` branch if we are abandoning work on FAST-JX in favor of Cloud-J?

**Comment by lizziel** [comment]
Yes, that branch is now deleted.

**Comment by yantosca** [comment]
Adding PR #1522 here for reference.

**Comment by yantosca** [comment]
Closed by #1733

**Comment by msulprizio** [comment]
The pull request for this issue (#1522) has now been merged into the 14.3.0 development branch.
