### ISSUE TITLE
compatibility of gcc-built netCDF libraries with intel compiler? [BUG/ISSUE]

### ISSUE THREAD

**Issue by hmhorow** [geoschem/geos-chem#955]
### Description of the problem
Installed netCDF libraries for GEOS-Chem using spack and gcc compiler. Compiled Viral's GC mercury code with Intel compiler (because gfortran wouldn't work with this version. more info on version below). Ran mercury simulation, it died at the end of the first month because it seems to be unable to write netCDF output files ("In Nccr_Wr, cannot create:  OutputDir/GEOSChem.WetLossLS.20180101_0000z.nc4"). 

### Description of troubleshooting performed
at first we thought it was perhaps a specific history collection that wasn't commented out that we didn't need and perhaps wasn't able to be used with the mercury simulation (vs full chemistry). However then whatever next history collection it got to writing had the same error.  I am wondering if this is because netCDF-c and netCDF-fortran were built with the gcc compiler or if something else is going on. 

### GEOS-Chem version
12.8.0, kpphg branch: https://github.com/viral211/geos-chem/tree/kpphg

### Log files
- Build log (if applicable): lastbuild
[lastbuild.txt](https://github.com/geoschem/geos-chem/files/7347888/lastbuild.txt)
[compile.log](https://github.com/geoschem/geos-chem/files/7347890/compile.log)
- Run logs (if applicable):
[GC.log](https://github.com/geoschem/geos-chem/files/7347902/GC.log)
[HEMCO.log](https://github.com/geoschem/geos-chem/files/7347903/HEMCO.log)

### Software versions
- CMake version: 3.18.4
- Compilers (Intel or GNU, and version): ifort 18.0.1
- NetCDF version: netcdf-c@4.7.4, netcdf-fortran@4.5.3 (installed with gcc@9.3.0)

**Comment by hmhorow** [comment]
Hi @yantosca , thanks so much for your reply! that is what I suspected.

So I just retried compiling with gfortran, and this is the error:

`../Makefile_header.mk:186: *** "Unknown Fortran compiler!  Must be one of ifort, gfortran, or mpifort|mpif90.  Check the FC environment variable in your .bashrc or .cshrc file.".  Stop`

if I enter `echo $FC` it shows this which should be the correct location of the compiler:
`/projects/horowitz_group/software_installs/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-9.3.0-n65slvhxem5wkyc4evokynr5dkp7ofme/bin/gfortran`

Previously, we thought maybe the gfortran compiler hadn't been included in PATH so
 we tried explicitly doing this:
```
export PATH="/projects/horowitz_group/software_installs/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-9.3.0-n65slvhxem5wkyc4evokynr5dkp7ofme/bin/gfortran:$PATH"                                                                                                 
export FC=gfortran  
```
but that didn't make a difference.  

When it prints out the last build information, the compiler is listed as follows

`  COMPILER     : /projects/horowitz_group/software_installs/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-9.3.0-n65slvhxem5wkyc4evokynr5dkp7ofme/bin/gfortran 9.3.0
`
Let me know if you have any ideas, I really appreciate it!!

**Comment by yantosca** [comment]
Hi @hmhorow, thanks for the feedback.  So when I load my own Spack environment, I end up doing (in a script):
```bash
spack load gcc@10.2.0
spack load netcdf-fortran%gcc@10.2.0
spack load netcdf-c%gcc@10.2.0
... etc...

# Compiler environment variables
export FC=gfortran
export F90=gfortran
export F77=gfortran
export CC=gcc
export CXX=g++

# netCDF paths
export NETCDF_HOME=`spack location -i netcdf-c%gcc@10.2.0`
export NETCDF_INCLUDE=${NETCDF_HOME}/include
export NETCDF_LIB=${NETCDF_HOME}/lib

# netCDF-Fortran paths
export NETCDF_FORTRAN_HOME=`spack location -i netcdf-fortran%gcc@10.2.0`
export NETCDF_FORTRAN_INCLUDE=${NETCDF_FORTRAN_HOME}/include
export NETCDF_FORTRAN_LIB=${NETCDF_FORTRAN_HOME}/lib
```
So I end up doing a

```bash
export FC=gfortran
```
etc.  This seems to make the compiler available for me.  But it may also be because I used the `spack load` commands, as I think that loads certain paths into your `PATH` and `LD_LIBRARY_PATH` environment variables.

That error is thrown a check in the Makefile_header.mk.  You could disable it by commenting out these lines in the Makefile_header.mk: 

https://github.com/viral211/geos-chem/blob/d971a18e10531dc5c655913bc12e51c7cf0b2c2b/Makefile_header.mk#L183-L187
