### ISSUE TITLE
[QUESTION]calculation of PM10 concentration

### ISSUE THREAD

**Issue by lixiao-bit** [geoschem/geos-chem#958]
### Ask a question about GEOS-Chem:
How to calculate the concentration of PM10 based on the model‘s outputs?

**Comment by yantosca** [comment]
@lixiao-bit, we are currently waiting from guidance from the GEOS-Chem Steering Committee and hopefully soon should have an accepted definition for the PM10 diagnostic.

**Comment by yantosca** [comment]
We have updated the GEOS-Chem wiki with new information about the current definitions of PM2.5 and PM10.  Please see: http://wiki.geos-chem.org/Particulate_matter_in_GEOS-Chem.   I will be creating a PR shortly.

**Comment by yantosca** [comment]
PR #992 has been merged so we can close this issue.
