### ISSUE TITLE
[BUG/ISSUE] Integrate error in GEOS-Chem 12.7.2 with Bates et al. (2021) aromatic chemistry

### ISSUE THREAD

**Issue by ncolombi** [geoschem/geos-chem#966]
### Description of the problem
Describe your problem here.  Describe the steps to reproduce the problem here, if possible.

I am running a geosfp4x5 global tropchem simulation using GC version 12.7.2. I have added Kelvin/Ke's aromatic chemistry through the steps detailed below in the modifications section. However, I keep getting the the following error: 
 ```console
 Forced exit from Rosenbrock due to the following error:
 --> Step size too small: T + 10*H = T or H < Roundoff
 T=   1.9781772455176429E-026 and H=   1.9781772455176429E-026
 INTEGRATE FAILED TWICE !!!
GEOS-CHEM ERROR: Integrator error code : -7
STOP at INTEGRATE_KPP
```
### Description of troubleshooting performed
Describe any troubleshooting that you have already performed here. Also include any leads or suspicions here.

I found a similar error at the following link: [https://github.com/geoschem/geos-chem/issues/66]

I have adjusted the tolerances, both RTOL and ATOL to be a factor of 10 lower in flexchem_mod.F90, as described in link, shown below:
```F90
!%%%%% CONVERGENCE CRITERIA %%%%%

   ! Absolute tolerance
   ATOL      = 1e-3_dp

   ! Relative tolerance
   IF ( Input_Opt%LUCX  ) THEN
      ! UCX-based mechanisms
      !RTOL      = 2e-3_dp
      !RTOL      = 1e-3_dp
      RTOL      = 0.5e-3_dp
   ELSE
      ! Non-UCX mechanisms
      RTOL      = 1e-3_dp
   ENDIF
```
I have also tried adjusting both RTOL and ATOL to be a factor of 10 higher in flexchem_mod.F90, as shown below:
```F90
!%%%%% CONVERGENCE CRITERIA %%%%%

   ! Absolute tolerance
   ATOL      = 1e-1_dp

   ! Relative tolerance
   IF ( Input_Opt%LUCX  ) THEN
      ! UCX-based mechanisms
      !RTOL      = 2e-1_dp
      !RTOL      = 1e-1_dp
      RTOL      = 0.5e-1_dp
   ELSE
      ! Non-UCX mechanisms
      RTOL      = 1e-1_dp
   ENDIF
```
### GEOS-Chem version
Enter your GEOS-Chem version here.
 Version 12.7.1 

### Description of modifications
Describe your modifications here.

Steps to add aromatic chemistry:

(1) edit the species database: go to your code /Headers/species_database_mod.F90, and add the following cases anywhere in the main body (where other species are similarly declared; I just put them next to benzene and toluene for consistency). There *might* already be case declarations in there for XYLE, C2H2, and C2H4, the first three I've copied below; if so, don't add these duplicates!

          CASE( 'XYLE' )
             FullName      = 'Xylene'
             Formula       = 'C8H10'
             MW_g          = 106.16_fp
             EmMW_g        = 12.0_fp
             MolecRatio    = 8.0_fp
             Is_Gas        = T
             Is_Drydep     = F
             Is_Wetdep     = F

           CASE( 'C2H2' )
             FullName      = 'Ethyne'
             Formula       = 'C2H2'
             MW_g          = 26.00_fp
             EmMW_g        = 12.0_fp
             MolecRatio    = 2.0_fp
             Is_Gas        = T
             Is_Drydep     = F
             Is_Wetdep     = F

           CASE( 'C2H4' )
             FullName      = 'Ethene'
             Formula       = 'C2H4'
             MW_g          = 28.05_fp
             EmMW_g        = 12.0_fp
             MolecRatio    = 2.0_fp
             Is_Gas        = T
             Is_Drydep     = F
             Is_Wetdep     = F

          CASE( 'ETHN' )
             FullName      = 'hydroxy-nitrooxy-ethane'
             Formula       = 'HOCH2CH2ONO2'
             MW_g          = 107.00_fp
             Is_Gas        = T
             Is_Drydep     = T
             Is_Wetdep     = T
             DD_F0         = 0.0_fp
             DD_Hstar_old  = 3.90e+4_fp
             Henry_K0      = 3.90e+4_f8
             Henry_CR      = 8600.0_f8
             WD_RetFactor  = 2.0e-2_fp

           CASE( 'ETHP' )
             FullName      = 'hydroxy-hydroperoxy-ethane'
             Formula       = 'HOCH2CH2OOH'
             MW_g          = 78.0_fp
             Is_Gas        = T
             Is_Drydep     = T
             Is_Wetdep     = T
             Is_Photolysis = T
             DD_F0         = 0.0_fp
             DD_Hstar_old  = 6.50e+5_fp
             Henry_K0      = 6.50e+5_f8
             Henry_CR      = 8800.0_f8
             WD_RetFactor  = 2.0e-2_fp

           CASE( 'BZPAN' )
             FullName      = 'Peroxybenzoylnitrate'
             Formula       = 'C7H5O5N'
             MW_g          = 183.12_fp
             Is_Gas        = T
             Is_Drydep     = T
             Is_Wetdep     = T
             DD_F0         = 1.0_fp
             DD_Hstar_old  = 7.0e-1_f8 * To_M_atm
             Henry_K0      = 7.0e-1_f8 * To_M_atm
             Henry_CR      = 4600.0_f8
             WD_RetFactor  = 2.0e-2_fp

           CASE( 'BENZP' )
             FullName      = 'Phenyl hydroperoxide'
             Formula       = 'C6H6O2'
             MW_g          = 110.11_fp
             Is_Gas        = T
             Is_Drydep     = T
             Is_Wetdep     = T
             Is_Photolysis = T
             DD_F0         = 1.0_fp
             DD_Hstar_old  = 2.9e+1_f8 * To_M_atm
             Henry_K0      = 2.9e+1_f8 * To_M_atm
             Henry_CR      = 6800.0_f8
             WD_RetFactor  = 2.0e-2_fp

           CASE( 'NPHEN' )
             FullName      = 'Nitrophenol'
             Formula       = 'C6H5NO3'
             MW_g          = 139.11_fp
             Is_Gas        = T
             Is_Drydep     = T
             Is_Wetdep     = T
             Is_Photolysis = T
             DD_F0         = 1.0_fp
             DD_Hstar_old  = 2.3e+1_f8 * To_M_atm
             Henry_K0      = 2.3e+1_f8 * To_M_atm
             Henry_CR      = 0.0_f8
             WD_RetFactor  = 2.0e-2_fp

           CASE( 'BZCO3H' )
             FullName      = 'Perbenzoic acid'
             Formula       = 'C6H5CO3H'
             MW_g          = 138.12_fp
             Is_Gas        = T
             Is_Drydep     = T
             Is_Wetdep     = T
             Is_Photolysis = T
             DD_F0         = 1.0_fp
             DD_Hstar_old  = 2.4e+2_f8 * To_M_atm
             Henry_K0      = 2.4e+2_f8 * To_M_atm
             Henry_CR      = 0.0_f8
             WD_RetFactor  = 2.0e-2_fp

           CASE( 'AROMP' )
             FullName      = 'C4 product of aromatics'
             Formula       = 'C4H4O2'
             MW_g          = 68.08_fp
             Is_Gas        = T
             Is_Drydep     = T
             Is_Wetdep     = T
             DD_F0         = 1.0_fp
             DD_Hstar_old  = 4.1e+3_f8 * To_M_atm
             Henry_K0      = 4.1e+3_f8 * To_M_atm
             Henry_CR      = 7500.0_f8
             WD_RetFactor  = 2.0e-2_fp

           CASE( 'IDC' )
             FullName      = 'C5 unsaturated dicarbonyl'
             Formula       = 'C5H6O2'
             MW_g          = 98.10_fp
             Is_Gas        = T
             Is_Drydep     = T
             Is_Wetdep     = F
             DD_F0         = 1.0_fp
             DD_Hstar_old  = 2.0e+4_f8 * To_M_atm
             Henry_K0      = 2.0e+4_f8 * To_M_atm
             Henry_CR      = 0.0_f8

           CASE( 'ONIT' )
             FullName      = 'Generic organonitrates'
             Formula       = 'C6H6O6N'
             MW_g          = 189.12_fp
             Is_Gas        = T
             Is_Drydep     = T
             Is_Wetdep     = T
             Is_Photolysis = T
             DD_F0         = 1.0_fp
             DD_Hstar_old  = 2.9e+1_f8 * To_M_atm
             Henry_K0      = 2.9e+1_f8 * To_M_atm
             Henry_CR      = 6800.0_f8
             WD_RetFactor  = 2.0e-2_fp

           CASE( 'BALD' )
             FullName      = 'Benzaldehyde'
             Formula       = 'C7H6O'
             MW_g          = 106.12_fp
             Is_Gas        = T
             Is_Drydep     = T
             Is_Wetdep     = T
             Is_Photolysis = T
             DD_F0         = 1.0_fp
             DD_Hstar_old  = 3.8e-1_f8 * To_M_atm
             Henry_K0      = 3.8e-1_f8 * To_M_atm
             Henry_CR      = 5500.0_f8
             WD_RetFactor  = 2.0e-2_fp

          CASE( 'CSL' )
             FullName      = 'Cresol'
             Formula       = 'C7H8O'
             MW_g          = 108.14_fp
             Is_Gas        = T
             Is_Drydep     = T
             Is_Wetdep     = T
             DD_F0         = 1.0_fp
             DD_Hstar_old  = 4.2_f8 * To_M_atm
             Henry_K0      = 4.2_f8 * To_M_atm
             Henry_CR      = 8500.0_f8
             WD_RetFactor  = 2.0e-2_fp

         CASE( 'PHEN' )
             FullName      = 'Phenol'
             Formula       = 'C6H6O'
             MW_g          = 94.11_fp
             Is_Gas        = T
             Is_Drydep     = T
             Is_Wetdep     = T
             DD_F0         = 1.0_fp
             DD_Hstar_old  = 2.8e+1_f8 * To_M_atm
             Henry_K0      = 2.8e+1_f8 * To_M_atm
             Henry_CR      = 2700.0_f8
             WD_RetFactor  = 2.0e-2_fp

          CASE( 'MCT' )
             FullName      = 'Methyl catechol'
             Formula       = 'C7H8O2'
             MW_g          = 124.0_fp
             Is_Gas        = T
             Is_Drydep     = T
             Is_Wetdep     = T
             DD_F0         = 1.0_fp
             DD_Hstar_old  = 4.2_f8 * To_M_atm
             Henry_K0      = 4.2_f8 * To_M_atm
             Henry_CR      = 8500.0_f8
             WD_RetFactor  = 2.0e-2_fp

(2) go to your code directory /KPP/Tropchem, edit Tropchem.eqn, and add the following lines to the end of the #DEFVAR section (in mine, that means just after the line XYLE = IGNORE and before the line #DEFFIX)

C2H2       = IGNORE; {C2H2; Ethyne}
ETOO       = IGNORE; {hydroxy-peroxy-ethane radical, formed from ethene + OH}
ETO        = IGNORE; {hydroxy-alkoxy-ethane radical}
ETHN       = IGNORE; {stable hydroxy-nitrooxy-ethane}
ETHP       = IGNORE; {stable hydroxy-hydroperoxy-ethane}
AROMRO2 = IGNORE;
CSL = IGNORE;
PHEN = IGNORE;
BALD = IGNORE;
BENZO2 = IGNORE;
BZPAN = IGNORE;
BENZP = IGNORE;
BENZO = IGNORE;
NPHEN = IGNORE;
BZCO3 = IGNORE;
MCT = IGNORE;
BZCO3H = IGNORE;
AROMP = IGNORE;
IDC = IGNORE;

(3) in the same file, add the following lines to the end of the chemistry section (after the last photolysis reaction; should be the very end of the document, unless yours has some filler lines at the end that mine doesn't)
```
//Ethene and Ethyne chemistry//
C2H4 + O3 = CH2O + CH2OO : GCARR(9.10E-15, 0.0E+00, -2580.0);
C2H4 + OH = ETOO : GCJPLPR(1.10E-28, 3.5E+00, 0.0, 8.4E-12, 1.75, 0.0, 0.5, 0.0, 0.0) ;
ETOO + HO2 = ETHP : GCARR(1.53E-13, 0.0E+00, 1300.0) ;
ETOO + NO = 0.995ETO + 0.995NO2 + 0.005ETHN : GCARR(2.7E-12, 0.0E+00, 360.0) ;
ETOO + NO3 = ETO + NO2 : 2.3E-12 ;
ETOO + MO2 = 0.6ETO + 0.6HO2 + 0.8CH2O + 0.2MOH + 0.2ETHP + 0.2GLYC : 6.00E-13;
ETO = HO2 + 2.000CH2O : GCARR(9.5E-13, 0.0E+00, -5988.0) ;
ETO + O2 = GLYC + HO2 : GCARR(2.5E-14, 0.0E+00, -300.0) ;
ETHN + OH = GLYC + NO2 : 8.40E-13 ;
ETHP + OH = ETOO : GCARR(1.90E-12, 0.0E+00, 190.0) ;
ETHP + OH = OH + GLYC : 1.38E-11 ;
C2H2 + OH = 0.636GLYX + 0.636OH + 0.364CO + 0.364HO2 + 0.364HCOOH : GCJPLPR(5.50E-30, 0.0E+00, 0.0, 8.3E-13, -2.0, 0.0, 0.5, 0.0, 0.0) ;
ETHP + hv = ETO + OH : PHOTOL(138) ;

// Aromatic Chemistry//
BENZ + OH = 0.54PHEN + 0.54HO2 + 0.46AROMRO2 + 0.18GLYX + 0.2CO + 0.56AROMP : GCARR(2.3E-12, 0.0E+00, -193.0) ;
TOLU + OH = 0.19CSL + 0.19HO2 + 0.81AROMRO2 + 0.06BALD + 0.12GLYX + 0.12MGLY + 0.27CO + 0.04MVK + 0.3IDC + 0.68AROMP : GCARR(1.8E-12, 0.0E+00, 340.0) ;
XYLE + OH = 0.15CSL + 0.15HO2 + 0.85AROMRO2 + 0.06BALD + 0.1GLYX + 0.2MGLY + 0.3CO + 0.04MVK + 0.56IDC + 0.28AROMP + 0.45RCOOH : 1.7E-11 ;
AROMRO2 + HO2 = OH + HO2 : 2.91D-13*EXP(1300/TEMP)*0.82 ;
AROMRO2 + NO = NO2 + HO2 : GCARR(2.60E-12, 0.0E+00, 365.0) ;
AROMRO2 + NO3 = NO2 + HO2 : 2.30E-12 ;
AROMRO2 + MO2 = CH2O + HO2 + HO2 : GCARR(1.70E-14, 0.0E+00, 220.0) ;
AROMRO2 + MCO3 = MO2 + HO2 : GCARR(4.20E-14, 0.0E+00, 220.0) ;
PHEN + OH = 0.06BENZO + 0.06GLYX + 0.18AROMP + 0.14AROMRO2 + 0.8MCT + 0.8HO2 : GCARR(4.70E-13, 0.0E+00, 1220.0) ;
PHEN + NO3 = 0.258NPHEN + 0.742HNO3 + 0.742BENZO : 3.8E-12 ;
CSL + OH = 0.727MCT + 0.727HO2 + 0.2AROMRO2 + 0.073BENZO + 0.44IDC : 4.7E-11 ;
CSL + NO3 = 0.5NPHEN + 0.2AROMRO2 + 0.5HNO3 + 0.3BENZO + 0.44IDC : 1.4E-11 ;
MCT + OH = 0.3BENZO + 0.7AROMRO2 + 1.05AROMP : 2.0E-11 ;
MCT + O3 = GAOO + HO2 + OH + AROMP : 9.2E-18 ;
MCT + NO3 = 0.5NPHEN + 0.5HNO3 + 0.3BENZO + 0.2AROMRO2 + 0.3AROMP : 9.9E-11 ;
BALD + OH = BZCO3 : GCARR(5.90E-12, 0.0E+00, 225.0) ;
BALD + NO3 = BZCO3 + HNO3 : 2.4E-15 ;
BZCO3 + HO2 = 0.35CO2 + 0.2BENZO2 + 0.15O3 + 0.2OH + 0.15BENZP + 0.65BZCO3H : GCARR(1.10E-11, 0.0E+00, 340.0) ;
BZCO3 + NO = NO2 + CO2 + BENZO2 : GCARR(7.50E-12, 0.0E+00, 290.0) ;
BZCO3 + NO2 = BZPAN : PAN(3.28E-28,0.,-6.87,1.125E-11,0.,-1.105,0.3);
BZCO3H + OH = BZCO3 : 4.66E-12 ;
BZPAN = BZCO3 + NO2 : PAN(1.10E-5,-10100.,0.,1.90E+17,-14100.,0.,0.3)*0.67;
BZPAN + OH = BENZP + CO2 + NO2 : 1.06E-12 ;
BENZO2 + NO2 = BENZO + NO3 : 7.00E-12 ; {k_3rd(TEMP,2.5E+19,9.7E-29,5.6,9.3E-12,1.5,0.6)}
BENZO2 + NO = BENZO + NO2 : GCARR(2.670E-12, 0.0E+00, 365.0) ;
BENZO2 + NO3 = BENZO + NO2 : 2.30E-12 ;
BENZO2 + HO2 = BENZP : GCARR(2.24E-13, 0.0E+00,1300.0) ;
BENZP + OH = BENZO2 : 3.60E-12 ;
BENZO + O3 = BENZO2 : 2.86E-13 ;
BENZO + NO2 = NPHEN : 2.08E-12 ;
NPHEN + OH = 0.5R4N1 + AROMP + 0.5NO2 : 3.47E-12 ;
NPHEN + NO3 = 0.5HNO3 + NO2 + 0.5R4N1 + AROMP : 2.60E-12 ;
BENZO2 + MO2 = BENZO + HO2 + CH2O : GCARR(2.670E-13, 0.0E+00, 365.0) ;
BZCO3 + MO2 = BENZO2 + CO2 + HO2 + CH2O : GCARR(2.670E-12, 0.0E+00, 365.0) ;
AROMP + OH = 0.6GLYX + 0.25CO + 0.25HCOOH + 0.25OH + 0.33HO2 + 0.33RCO3 + 0.45RCOOH : 5E-11 ;
AROMP + O3 = 0.5HCOOH + 0.5CO + 0.6GLYX + 0.9GAOO + 0.1HO2 + 0.1OH : 8E-16 ;
AROMP = 0.2HO2 + 0.2GLYX + 1.2RCHO : 1.5E-3 ;
IDC + OH = 0.6MGLY + 0.15ACTA + 0.1HCOOH + 0.25OH + 0.33HO2 + 0.33RCO3 + 0.25CO + 0.52RCOOH : 5E-11 ;
IDC + O3 = 0.6MGLY + 0.3ACTA + 0.2HCOOH + 0.5CO + 0.95GAOO + 0.1HO2 + 0.1OH : 8E-16 ;
IDC = 0.2HO2 + 0.2R4O2 + 0.2MGLY + 1.2RCHO : 1.5E-3 ;
BALD + hv = BENZO2 + CO + HO2 : PHOTOL(139) ;
BZCO3H + hv = BENZO2 + OH + CO2 : PHOTOL(140) ;
BENZP + hv = BENZO : PHOTOL(141) ;
NPHEN + hv = HNO2 + CO + CO2 + AROMP + HO2 : PHOTOL(142) ;
NPHEN = ONIT : HET(ind_MONITU,1);
```
(4) in that same KPP/Tropchem folder, run "./build_mechanism.sh". If you haven't compiled KPP before you might run into a problem here where it doesn't recognize the "kpp" command. I'm not sure what the standard is these days for having a kpp path in your bash script.... if it doesn't work, just let me know and we can track it down (or I can always just compile the kpp part for you).

(5) now go to your run directory, and add the new species to input.geos, at the bottom of the advected species menu (after all the other species):
```
Species name            : C2H4
Species name            : C2H2
Species name            : ETHP
Species name            : ETHN
Species name            : PHEN
Species name            : CSL
Species name            : MCT
Species name            : BALD
Species name            : BZPAN
Species name            : BENZP
Species name            : NPHEN
Species name            : BZCO3H
Species name            : AROMP
Species name            : IDC
```
(6) also in input.geos, we have to point it to the path for the modifies photolysis files. Find the photolysis menu, and change the path after "FAST-JX directory" to your run directory

(7) copy the contents of the fast-jx directory (/n/holylfs/EXTERNAL_REPOS/GEOS-CHEM/gcgrid/data/ExtData/CHEM_INPUTS/FAST_JX/v2019-10/) into your run directory

(8) in FJX_j2j.dat in your run directory, add the following lines just before the line "9999":
```
 138 ETHP      PHOTON    ETO       OH                      1.000 /CH3OOH/
 139 BALD      PHOTON    BENZO2 HO2 CO                     0.060 /BALD  /
 140 BZCO3H    PHOTON    BENZO2 OH CO2                     1.000 /CH3OOH/
 141 BENZP     PHOTON    BENZO                             1.000 /CH3OOH/
 142 NPHEN     PHOTON    HNO2 CO CO2 DCB1 HO2              1.000 /PROPNN/
```
(9) in FJX_spec.dat, also in your run directory, add the following lines just before the line "endofJ":
```
BALD   298 0.000E+00 0.000E+00 0.000E+00 0.000E+00 0.000E+00 0.000E+00
           0.000E+00 0.000E+00 0.000E+00 0.000E+00 0.000E+00 2.780E-19
           6.600E-20 7.200E-20 9.200E-20 8.500E-20 0.000E+00 0.000E+00
```
### Log files
- Build log (if applicable): 
[compile.log](https://github.com/geoschem/geos-chem/files/7392148/compile.log)
- Run logs (if applicable):
[HEMCO.log](https://github.com/geoschem/geos-chem/files/7392145/HEMCO.log)

- Run script (if applicable):

### Software versions
- CMake version:  3.12.1
- Compilers (Intel or GNU, and version): /init/init.gc-classic.gfortran71.centos7
- NetCDF version:

**Comment by yantosca** [comment]
I will close out this issue @ncolombi.  Please feel free to open a new issue if you are still having problems.

**Comment by ncolombi** [comment]
I upgraded to version 13.3 and it runs perfectly!

**Comment by yantosca** [comment]
Glad to hear it @ncolombi!
