### ISSUE TITLE
[QUESTION] Running GEOS-Chem 12.9.0 with GISS ModelE2.1

### ISSUE THREAD

**Issue by xin-tie** [geoschem/geos-chem#967]
Hi everyone, I am currently using meteorology from GISS ModelE2.1 as input for running GEOS-Chem 12.9.0 to do a simulation for pre-industrial, although I am stuck at "make -j MET=  GRID=4x5 CHEM=Standard NO_REDUCED=NO" to compile, because I don't know what to use for MET and I tried GCAP but don't think that's the correct one to use. Could anyone give me some suggestions on this? Thanks so much! (I really could not find any useful resources elsewhere, I am quite new to paleo simulation using GEOS-Chem)

**Comment by yantosca** [comment]
I will close this issue for now.  As @msulprizio said, please update to GEOS-Chem 13.1.0 or later.

**Comment by xin-tie** [comment]
Hi @msulprizio and @yantosca , sorry getting back so late and thanks for the suggestion, I have already solved this issue.
