### ISSUE TITLE
[QUESTION] How to disable BPCH diagnostics defined in Diagnostic Menu in input.geos and how to change default vertical levels?

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/geos-chem#97]
I am using GC 12.2.1. I would like to collect all my diagnostics in NetCDF format. However, I found that even though I set all the numbers to zero in the second column in Diagnostic Menu in input.geos, I will still get a file such as `trac_avg.geosfp_2x25_complexSOA_SVPOA.YYYYMMDDhhmm`. Is there a simple way not writing such files?

Since I am still using GC 12.2.1, I do not have a `Grid Menu` in input.geos to help me define vertical levels. What is the suitable way of changing 47 vertical levels to 72 vertical levels for GC prior to 12.4.0?

If I run a nested GC with 72 vertical levels, should I also run a global GC **with 72 vertical levels** to prepare boundary conditions?

**Comment by yantosca** [comment]
Compile with BPCH_DIAG=n BPCH_TPBC=n BPCH_TIMESER=n NO_REDUCED=y to turn off BPCH and also to get 72 levels.

Your global and nested runs should use the same number of vertical levels.

**Comment by FeiYao-Edinburgh** [comment]
Thanks for your quick reply! Very helpful!

Just one more concern, do I need to use Restartfiles with 72 vertical levels if I set NO_REDUCED=y? Previously I downloaded Restartfiles from ftp://ftp.as.harvard.edu/gcgrid/data/ExtData/GEOSCHEM_RESTARTS/v2018-11/ and I found that they only have 47 vertical levels, at least for `initial_GEOSChem_rst.2x25_complexSOA_SVPOA.nc`...

**Comment by msulprizio** [comment]
We do recommend you use a restart file with the appropriate number of levels when possible, but HEMCO does have the capability to vertically regrid fields. If you do rely on HEMCO to do the vertical regridding, we recommend [spinning up your simulation](http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_restart_files) as usual to remove any impact from initial conditions.
