### ISSUE TITLE
[FEATURE REQUEST] Add a line to remove PET*.ESMF_LogFile logs to run/shared/cleanRunDir.sh

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#982]
GCHP now saves out one `PETnn.ESMF_LogFile` per each core `nn` used in a simulation.  For GCHP benchmarks this adds 96 files to the rundir.   Could we add a line such as 
```bash
rm -fv PET*.ESMF_LogFile
```
to the rundir script `run/shared/CleanRunDir.sh`?   This would get rid of these log files along with all of the other logs when cleaning up a GCHP rundir.

Tagging @lizziel @LiamBindle

**Comment by msulprizio** [comment]
See this discussion here: https://github.com/geoschem/GCHP/discussions/153#discussioncomment-1320852

**Comment by LiamBindle** [comment]
I believe @lizziel fixed this in https://github.com/geoschem/GCHP/commit/8bdae2cac33946e8b5763faf9fd641b1d4bde255 (latest commit in 13.3.0)

**Comment by lizziel** [comment]
My fix prevents ESMF error that resulted in the files always being created. But I did not update the createRunDir script to remove them should they be created. @yantosca, adding that line is a good idea. I think a line to remove new log file allPEs.log is also needed. Thanks!

**Comment by yantosca** [comment]
Thanks @lizziel, I'll make a PR shortly for 13.3.1 with these fixes to createRunDir.sh.

**Comment by yantosca** [comment]
@LiamBindle: also I was working with a 13.3.0-alpha.9 benchmark so probably the update from @lizzie wasn't added at that point.

**Comment by yantosca** [comment]
This is now in the development stream for 13.3.1, so we can close this issue.
