### ISSUE TITLE
[QUESTION] TS or T2M temperature in MEGAN and add T2M in HISTORY.rc

### ISSUE THREAD

**Issue by lizziel** [geoschem/geos-chem#984]
### Discussed in https://github.com/geoschem/geos-chem/discussions/979

<div type='discussions-op-text'>

<sup>Originally posted by **luhu0** October 29, 2021</sup>
Hello there,

I am trying to figure out which surface temperature is used to drive MEGAN biogenic VOC emissions and output the right diagnostic for that. I think traditionally we used T2M (surface temperature at 2 m). From the hcox_megan_mod.F90, it looks like we are indeed using the ExtState%T2M, and that is inputted in the HEMCO_Config now. It appears that T2M is not in the meteorology state registry yet so that it cannot be outputted by HISTORY.rc as of v13.2.1. If the above is correct, should the Headers/state_met_mod.F90 be the place to register T2M so that we could output it in HISTORY? Once I register T2M, I can output it via HISTORY, but they are all zero values. How/where should I populate the array with the actual T2M variable? Or did I miss it totally? 

Thanks anyone for helping confirming it or any suggestions on where to track and output this driving temperature. 

Lu</div>

**Comment by yantosca** [comment]
Thanks for writing @luhu0.  In the routine `GeosCore/flexgrid_read_mod.F90`, we read the `T2M` field and store it as `TS`, and then we save the `TS` field as `TSKIN`:

```F90
    ! Read TS
    v_name = "TS"
    CALL Get_Met_2D( Input_Opt, State_Grid, Q, TRIM(v_name), t_index=t_index )
    State_Met%TSKIN = Q

    ! Read T2M
    v_name = "T2M"
    CALL Get_Met_2D( Input_Opt, State_Grid, Q, TRIM(v_name), t_index=t_index )
    State_Met%TS = Q
```
This was done mostly for backwards compatibility.  At some point in the past (maybe at the GEOS-3 to GEOS-4 switchover), the TS field was switched to be the surface skin temperature.  This caused isoprene emissions to skyrocket.  Therefore, as a proxy, we use the 2M temperature as the surface temperature.  This was all pre-HEMCO and we did this to avoid having to recode the model by changing TS everywhere.

**Comment by luhu0** [comment]
Great. Thanks for clarifying it, Bob. This makes sense now.

**Comment by yantosca** [comment]
Thanks @luhu0.  I will close out this issue now.
