### ISSUE TITLE
Missing December 2019 GEOSFP files on WUSTL server [BUG/ISSUE]

### ISSUE THREAD

**Issue by tessac2** [geoschem/geos-chem#987]
### Description of the problem
When running a download script after performing dryrun over 2019 with GEOSFP, I noticed that files from December 2019 were not found in the folder /ExtData/GEOS_4x5/GEOS_FP/2019/.  When I went to the WUSTL website, [http://geoschemdata.wustl.edu/ExtData/GEOS_4x5/GEOS_FP/2019/12/](http://geoschemdata.wustl.edu/ExtData/GEOS_4x5/GEOS_FP/2019/12), I noticed the folder was empty. I was wondering when these files may become available on the WUSTL server?

### Description of troubleshooting performed
If the data remains unavailable from WUSTL, I was planning to try to download manually from [http://ftp.as.harvard.edu/gcgrid/data/ExtData/GEOS_4x5/GEOS_FP/2019/]( http://ftp.as.harvard.edu/gcgrid/data/ExtData/GEOS_4x5/GEOS_FP/2019/ ). 

### GEOS-Chem version
GEOS-Chem version 13.2.1

### Description of modifications
GEOS-FP, 4x5

### Log files

[dl_2019.txt](https://github.com/geoschem/geos-chem/files/7471125/dl_2019.txt)

**Comment by YanshunLi-washu** [comment]
Hi. The data is now available from the WUSTL site. Let me know anything else. Thanks @tessac2

**Comment by tessac2** [comment]
Thank you!

**Comment by tessac2** [comment]
Hi everyone, 

Sorry to re-open the issue, but I realized that HEMCO was missing some files for October, November and December 2019 on the new WUSTL site (HEMCO OFFLINE SEASALT v2019-01/0.5x0.625). I was wondering when this may be updated? [http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_SEASALT/v2019-01/0.5x0.625/2019/](http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_SEASALT/v2019-01/0.5x0.625/2019/ )

I was not sure whether to reopen this thread or to raise the issue on the HEMCO Github--please let me know! 

[HEMCOlog11092021.txt](https://github.com/geoschem/geos-chem/files/7508534/HEMCOlog11092021.txt)



Thanks so much!

**Comment by LiamBindle** [comment]
Hi @tessac2, thanks for pointing this out and reopening. 

I'm looking at the OFFLINE_SEASALT/v2019-01 data, and it looks like the dataset does in fact stop at 2019-09. 
- http://ftp.as.harvard.edu/gcgrid/geos-chem/data/ExtData/HEMCO/OFFLINE_SEASALT/v2019-01/0.5x0.625/2019/ (stops in October 2019)
- https://geoschemdata.computecanada.ca/ExtData/HEMCO/OFFLINE_SEASALT/v2019-01/0.5x0.625/2019/10/ (empty folders after October 2019)
- http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_SEASALT/v2019-01/0.5x0.625/2019/10 (same, empty folders after October 2019)

Do you know if this dataset is supposed to go beyond October 2019?

**Comment by tessac2** [comment]
@LiamBindle Thank you for your reply! I think on further inspection the error I am getting for this run is actually more associated with the different sea salt variable names in the 0.25x0.3125 resolutions for OFFLINE_SEASALT/v2019-01 for November/December compared to other months, similar to this issue: [https://github.com/geoschem/geos-chem/issues/900](https://github.com/geoschem/geos-chem/issues/900 )

My bad for the confusion! I will close out this issue now and follow the other thread.

**Comment by tessac2** [comment]
Hello @YanshunLi-washu  @LiamBindle I am really sorry to open this issue again, but I am now realizing that I am unable to download any of the files from December 2019 (/ExtData/GEOS_4x5/GEOS_FP/2019/12). I can see on the website they are available but whenever I run the dryrun/download script or even just wget I get the error "403 Forbidden
2021-11-23 11:07:51 ERROR 403: Forbidden." Even when I click on the links on the WUSTL webpage itself I get an access forbidden error-- I am not sure why I am getting this error or if others are experiencing this issue?  
![image](https://user-images.githubusercontent.com/70339432/143071528-0b86f131-3dd6-4161-b738-e84c1eaf4b48.png)

**Comment by YanshunLi-washu** [comment]
Hi @tessac2 I granted the permission to those files again. Would you mind giving another try?

**Comment by tessac2** [comment]
@YanshunLi-washu I got it to work! Thank you so much, I really appreciate all your help.
