### ISSUE TITLE
[QUESTION] I want to add scale emissions by country,but get ERROR when run the model

### ISSUE THREAD

**Issue by DancingChild** [geoschem/geos-chem#988]
### I followed the tutorial (http://wiki.seas.harvard.edu/geos-chem/index.php/HEMCO_examples#Scale_emissions_by_country) to set up the HEMCO_Config.rc file, but When I run the model, I get ERROR as follows:
![image](https://user-images.githubusercontent.com/30101596/140247688-f0fb0a1a-7b10-4d1b-a239-2f55a7db585d.png)

### ERROR messages in HEMCO.log are as follow:
![image](https://user-images.githubusercontent.com/30101596/140247745-69368152-4c96-4917-b62e-ec20882f4c47.png)

### My modifications are as follows:
1. in HEMCO_Config.rc file:
![image](https://user-images.githubusercontent.com/30101596/140248164-bf82e42b-64fc-41db-8f66-555ee77ba4d5.png)
I tried to give the CountryID a specific value, e.g. 356, and it still got an error.
2. scalefactor.txt file (I'm sure the file path is correct)
![image](https://user-images.githubusercontent.com/30101596/140248227-c2d437a6-731a-42ca-8bb3-29a84a3b5b8d.png)
3. in HEMCO_Config.rc file:
![image](https://user-images.githubusercontent.com/30101596/140248079-5018dd08-9387-4835-bbeb-2d83656d1311.png)
4. in HEMCO_Config.rc file:
![image](https://user-images.githubusercontent.com/30101596/140248835-053103b3-9683-4d7b-87c5-82358af84632.png)

**Comment by yantosca** [comment]
@DancingChild, have you tried to put the `scalefactor.txt` file in your run directory?   Your example shows it in the HEMCO Root folder.  Then you would list:

```
501 SCALE_COUNTRY ./scalefactor.txt - - - xy unitless 1
```

**Comment by DancingChild** [comment]
> @DancingChild, have you tried to put the `scalefactor.txt` file in your run directory? Your example shows it in the HEMCO Root folder. Then you would list:
> 
> ```
> 501 SCALE_COUNTRY ./scalefactor.txt - - - xy unitless 1
> ```

Thank you for your advice. I tried it and it didn't work.

**Comment by DancingChild** [comment]
I think I solved the problem.  I didn't put the '501 line' in the right place. I put it under 
```
###############################################################################
### BEGIN SECTION SCALE FACTORS
###############################################################################
```
, and the model works.

**Comment by yantosca** [comment]
Ah yes, thanks @DancingChild.  That definitely needs to go in the scale factors section.  I'll close out this issue now.  Let us know if you encounter other problems.
