### ISSUE TITLE
[QUESTION]Which kind of simulation should be chosen for PM25?

### ISSUE THREAD

**Issue by ruifeili** [geoschem/geos-chem#989]
### Ask a question about GEOS-Chem:
Hi, I want to simulate the global PM25 concentrations by using GEOS-Chem model (13.2.1) with MERRA2 at the resolution of 2.0x2.5 with 47 levels.  Then I found that there are two types of simulations (Full chemistry and Aerosol-only simulation) which can provide the results of aerosolmass (PM25).  I also found that the simulation time for Aerosol-only simulation was much faster. I just want to obtain the annual average PM25 concentrations. Do you know which kind of simulation should I choose?

I also want to speed up the simulation. Then I found the website which provide some suggestions about speeding up GEOS-Chem (http://wiki.seas.harvard.edu/geos-chem/index.php/Speeding_up_GEOS-Chem). Is it possible for me to set the timestep like this (Transport/conversion:900 sec, Chemistry/Emission: 1800 sec)?

**Comment by yantosca** [comment]
Thanks for writing @ruifeili.  I would recommend to use the fullchem simulation in GEOS-Chem 13 for saving out PM2.5.

You could experiment with changing the timesteps to see what impact they have on the simulation.  

Also see discussion #875 for more tips on speeding up GEOS-Chem, especially for nested-grid simulatiosn.

**Comment by ruifeili** [comment]
@yantosca Thanks for answering. I have another question about the emission inventory used in fullchem simulation. I use AWS cloud to do the simulation, and I download the emission data according to the HEMCO_Diagn.rc. The emissions (including BC, OC, SO2, NO, NH3,CO) were from CEDS database. But why the emission of NMVOC was not downloaded and used in the fullchem simulation (because I did not find the NetCDF files of NMVOC in the downloaded files and HEMCO_Diagn.rc)?

**Comment by yantosca** [comment]
Can you attach your HEMCO_Config.rc file to this issue, @ruifeili?

**Comment by ruifeili** [comment]
@yantosca I just used the defaulted HEMCO_Config.rc of the fullchem simulatio
[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/7477096/HEMCO_Config.txt)
n.

**Comment by ruifeili** [comment]
@yantosca I just used the default HEMCO_Config.rc of the fullchem simulation.
I noticed that the HEMCO used the emission of OC,BC,CO,NH3,NO and SO2 from CEDS, but not included the emission of NMVOC.
[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/7477102/HEMCO_Config.txt)
.

**Comment by yantosca** [comment]
@ruifeili, the dry-run will only pick up those inventories that you turn on.  I am not clear by what you mean by NMVOC emissions?  Do you mean the biogenic emissions produced by MEGAN?

**Comment by ruifeili** [comment]
@yantosca Sorry for bothering you. I just noticed the note in the HEMCO_Config.rc "NOTE: EOH files in CEDS/v2021-06 are actually VOC1 (total alchohols) and are split into MOH, EOH, ROH here". So the emission of VOC was involved. Now I have no questions. Thank you for your help!
