### ISSUE TITLE
[BUG/ISSUE] Determine if it's necessary for HEMCO to read files twice on first timestep and once on last timestep

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#99]
HEMCO currently reads files twice on the first timestep and once on the last timestep, presumably to update met fields. I believe this was introduced with [FlexGrid Stage 1](http://wiki.seas.harvard.edu/geos-chem/index.php/FlexGrid#Read_in_meteorology_fields_via_HEMCO). We should investigate whether this is necessary and possibly add a feature to mark fields as emissions, met, or chem input, so that only the necessary files are read during different HEMCO phases. This should also improve model performance by removing repeated file reads.

This may also be impacting single vs multi-segmented runs by unnecessarily changing the values of met fields saved out to the restart file.

**Comment by yantosca** [comment]
This issue should now be resolved with commits: https://github.com/geoschem/geos-chem/commit/2d6e025fa2fafbe3c16be30a2bbcfdc190a5a48f and https://github.com/geoschem/geos-chem/commit/02677b3d6cc21c452705fdcd642d4557847c084b.  These fixes will ship with 12.7.0.
