### ISSUE TITLE
[BUG/ISSUE] ParaNOx and NEI11_SHIP_MONMEAN mutually exclusive

### ISSUE THREAD

**Issue by rgstevens** [geoschem/geos-chem#991]
### Description of the problem
If both ParaNOx is on and NEI11_SHIP_MONMEAN is True at the same time, I get an error printed to HEMCO.log stating:
```
HEMCO ERROR: Cannot fill buffer for more than one species!
ERROR LOCATION: HCO_CalcEmis (HCO_CALC_MOD.F90)
ERROR LOCATION: HCOX_ParaNOx_Run (hcox_paranox_mod.F90)
ERROR LOCATION: HCOX_RUN (hcox_driver_mod.F90)
```

### Description of troubleshooting performed
The error does not appear if either ParaNOx is turned off (of course) or if NEI11_SHIP_MONMEAN is set to False. I would guess that this is related to issue #256 

Given the commentary in HEMCO_Config.rc that NEI11_SHIP_* only extends a few kms from the shore, I think that the best solution for me is to just not use NEI11_SHIP_MONMEAN.

### GEOS-Chem version
I am using 13.2.1

### Description of modifications
None

### Log files
- Run logs:
[HEMCO.log.txt](https://github.com/geoschem/geos-chem/files/7477347/HEMCO.log.txt)
[slurm-27368991.out.txt](https://github.com/geoschem/geos-chem/files/7477351/slurm-27368991.out.txt)
- Input files:
[input.geos.txt](https://github.com/geoschem/geos-chem/files/7477359/input.geos.txt)
[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/7477362/HEMCO_Config.rc.txt)

### Software versions
- CMake version: 3.16.5
- Compilers (Intel or GNU, and version): intel 19.1.1.217 
- NetCDF version: 4.7.4

**Comment by yantosca** [comment]
Thanks for writing @rgstevens.  Yes, we typically do not recommend using NEI11_SHIP_MONMEAN.

**Comment by rgstevens** [comment]
Okay. That solves my problem.

Are you interested in investigating and debugging this further, or should we close the issue? I don't mind running further tests, but if the inventories are not recommended for use anyway, then it might not be a worthwhile use of either your or my time.

**Comment by yantosca** [comment]
@rgstevens, I am OK with closing out the issue.  If you would like to investigate further, then please go ahead.   We now use CEDS v2 ship emissions by default in the standard GC 13 code so this is likely not going to be a big issue going forward.
