### ISSUE TITLE
[QUESTION]How to add NO2 photolysis rate coefficient to gckpp_HetRates.F90 ?

### ISSUE THREAD

**Issue by yangxiajie** [geoschem/geos-chem#993]
I try to modify a heterogeneous reaction rate in `gckpp_HetRates.F90` (v12.9.3), which is ralated with NO2 photolysis rate coefficient (`JNO2`). I wonder if there is a golobal variable about NO2 photolysis rate coefficient in GEOS-Chem Code, so that I can add it directly. Or, is there any way to add `JNO2`, as a variable , in `gckpp_HetRates.F90` ?

Thank you for your time.

**Comment by yantosca** [comment]
The NO2 photolysis is stored in the 11th slot of the `PHOTOL` array, as defined in fullchem.eqn:
```
NO2 + hv = NO + O :                          PHOTOL(11);     {2014/02/03; Eastham2014; SDE}NO2 + hv = NO + O :                          PHOTOL(11);     {2014/02/03; Eastham2014; SDE}
```
so you can just use `PHOTOL(11)` in your code.  For other reaction rates, see `fullchem.eqn` and/or `gckpp_Rates.F90`.

**Comment by yantosca** [comment]
I should also mention that `PHOTOL` is in gckpp_Global, which should be available to you in gckpp_HetRates.

**Comment by yangxiajie** [comment]
Thank you @yantosca .

I can add `JNO2` to gckpp_HetRates now. Thank you for help. 

By the way, what is the unit of `PHOTOL` in GEOS-Chem ? s-1 or min-1 ?

**Comment by yantosca** [comment]
Thanks @yangxiajie.  Units of all reaction rates for KPP are s-1.

**Comment by yantosca** [comment]
Also you are right @yangxiajie, PHOTOL is a 1-D array.  It is the array of J-values for species at a given (I,J,L) grid box.  PHOTOL is assigned values in the flexchem_mod.F90 module.

**Comment by yangxiajie** [comment]
Thank you very much @yantosca .

I want to add a heterogeneous reaction, which is only on the ground (L == 1). I found `ADJUSTEDRATE` in `gckpp_HetRates` is also for a (I,J,L) box. Is there any way to restrict the reaction rate to the first level ?

**Comment by yantosca** [comment]
@yangxiajie, yes, you can write or modify a rate law function in gckpp_HetRates so that it returns the reaction rate if L==1 and returns 0 if L >1.

**Comment by yangxiajie** [comment]
Thank you very much @yantosca .
Now I fix all problems. 
Appreciate your time.
