### ISSUE TITLE
[QUESTION] Running GEOS-Chem 13.2.0 before 2019

### ISSUE THREAD

**Issue by nbderenzqy66** [geoschem/geos-chem#996]
### Ask a question about GEOS-Chem:
I'm trying to run aerosol simulation in GEOS-Chem 13.2.0. The restart file it gives me is 20190701. However, I want to run the simulation from 2014. I found the restart file generated from GEOS-Chem 13.2.0 is different from versions before 13. I also tried to find restart files in Compute Canada, but there are only files for 2019. Is there a way that I can find the restart files before 2019 or generate one from previous versions' restart files? 

Thank you!

**Comment by yantosca** [comment]
Thanks for writing @nbderenzqy66.  Please see issue #971 for a solution.

**Comment by nbderenzqy66** [comment]
Thank you!
