### ISSUE TITLE
[FEATURE REQUEST] Update surface resistance for ozone deposition to ice/snow

### ISSUE THREAD

**Issue by r-pound** [geoschem/geos-chem#997]
### Request a new GEOS-Chem feature:
Barten et.al 2021 (https://doi.org/10.5194/acp-21-10229-2021) increased the surface resistance of ozone dry deposition to snow and ice to 1E4 s m−1, this results in a reduction of ozone deposition velocity to ice of ≤ 0.01 cm s−1 (~ 66% reduction) which has better agreement with observations and results in improved comparison between Ozone observations in the arctic. 

Following this reasoning we have also increased the surface resistance term in the ozone to ice dry deposition calculation in version 13.1.2, resulting in the following changes to annual average ozone dry deposition velocity

![polar_ice_change](https://user-images.githubusercontent.com/32539507/140938876-b7db27ac-894f-48fe-b74a-d998c91091fc.png)

The current method uses the IS_SNOW(I,J) array to set the resistance velocity for grid boxes which are snow/ice. This however does capture regions of desert as ice due to snow/ice coverage for this array being determined by albedo, resulting in the reduction in deposition velocity also being incorrectly applied to these regions. 

The reduction in ozone dry deposition to ice results in an increase in surface ozone
![surface_ozone_ice_change](https://user-images.githubusercontent.com/32539507/140938989-3b4c5e3a-62dc-4f77-8d90-eaa921a61884.png)

Comparing these to observations shows the small increase in surface ozone improves comparisons to observations in the Antarctic and Arctic. With minimal/no impact outside of these regions.

![obs_com_ice_change](https://user-images.githubusercontent.com/32539507/140939529-ce18a8bc-3cdb-4fa0-9eb6-cb99ed89338c.png)

With either changes to IS_SNOW or an alternative, we believe that these changes should be adopted into the GEOS-Chem model.

**Comment by yantosca** [comment]
Thanks @r-pound.  I've added this to the [GEOS-Chem model development priorities](http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_model_development_priorities#Feature_integration_not_yet_prioritized) page.

**Comment by yantosca** [comment]
@r-pound: do you have a corresponding PR that we can use?  Thanks.

**Comment by r-pound** [comment]
@yantosca I've created a pull request (#1013) with the changes discussed above. Let me know if there's any questions/issues with the changes

**Comment by yantosca** [comment]
Note: PR #1013 has been superseded by PR #1055

**Comment by yantosca** [comment]
We can close this issue as PR #1055 has been merged into the 13.4.0 development stream.
