### ISSUE TITLE
[FEATURE REQUEST] Update archiveRun.sh scripts

### ISSUE THREAD

**Issue by lizziel** [geoschem/geos-chem#998]
Currently there are differences in the archive directory structure between GCHP and GC-Classic due to differences in archiveRun.sh. Ideally they would be the same, of if needed, GCHP would simply have additional folders. It would also be useful to have the archive directory structure amenable to use with GCPy benchmark scripts. This would allow easy use of archived run directories for comparisons and GCPy validation.

**Comment by yantosca** [comment]
It would be also nice to copy the lumped_species.yml and species_database.yml to the archival folder, so that these could be pointed to by the benchmark scripts.

**Comment by lizziel** [comment]
In 14.0 the GCHP archive run script was changed to copy all the logs and config files to the same level of the archive directory. The diagnostic data is copied over in the OutputDir folder. The restarts must be manually copied (to avoid copying everything, even not relevant, restarts that happen to be Restarts).

**Comment by yantosca** [comment]
@lizziel, has this issue been resolved?  If so we can close it out. Thanks!

**Comment by yantosca** [comment]
Closing out this issue
