### ISSUE TITLE
Error encountered in "EmissCarbonTomas" in TOMAS 15 simulation with GCAP 2.0 met fields. 

### ISSUE THREAD

**Issue by zhaojunri1020** [geoschem/geos-chem#999]
**Ask a question about GEOS-Chem-TOMAS with GCAP2.0 met fields:**

In the HEMCO_Config.rc file,  i just set true the CMIP6_SFC_LAND_ANTHRO, CMIP6_AIRCRAFT, CMIP6_SHIP, BB4MIPS emissions.
When I run RRTMG model, the following error occurred when i trying to run TOMAS15 simulation with  GCAP 2.0 met fields using GEOS-chem v13.20.
I would be grateful if anyone can help me with this issue.

```
"===============================================================================
GEOS-Chem WARNING: HEMCO diagnostic not found: BCPI_ANTH
EMISSCARBONTOMAS (carbon_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem WARNING: HEMCO diagnostic not found: OCPI_ANTH
EMISSCARBONTOMAS (carbon_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem WARNING: HEMCO diagnostic not found: BCPO_ANTH
EMISSCARBONTOMAS (carbon_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem WARNING: HEMCO diagnostic not found: OCPO_ANTH
EMISSCARBONTOMAS (carbon_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem WARNING: HEMCO diagnostic not found: BCPI_BB
EMISSCARBONTOMAS (carbon_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem WARNING: HEMCO diagnostic not found: BCPO_BB
EMISSCARBONTOMAS (carbon_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem WARNING: HEMCO diagnostic not found: OCPI_BB
EMISSCARBONTOMAS (carbon_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem WARNING: HEMCO diagnostic not found: OCPO_BB
EMISSCARBONTOMAS (carbon_mod.F90)
===============================================================================
"
```

**Comment by yantosca** [comment]
Thanks for writing.  I am going to tag Jeff Pierce (@theloniuspunk), who is involved with TOMAS development.

You should also configure your model with:

```console
$ cmake ../CodeDir -DTOMAS=y -DTOMAS_BINS=15 -DBPCH_DIAG=y
```

because TOMAS still needs some of the old bpch diagnostics.

I will say, I am not aware of TOMAS ever having been used with the GCAP 2.0 met fields.  So there is a possibility that some kind of input quantities are in the wrong units or are not present.  We are unable to support such a model configuration.

**Comment by theloniuspunk** [comment]
Thanks, Bob.

It may be that emissions for TOMAS are still configured as 2D, not 3D, so
if GCAP has 3D emission fields, it will throw an error with TOMAS.

TOMAS needs the emissions updated to handle 3D. I don't have the capacity
to do it now. I've mentioned it with Betty Croft in the past. Maybe it's
something she can do.

**Comment by yantosca** [comment]
Thanks @theloniuspunk.  I will leave this issue tagged with "need community input" as it is something that is beyond the scope of the GCST.

**Comment by theloniuspunk** [comment]
Thanks!

**Comment by zhaojunri1020** [comment]
Thanks for helping @yantosca.

**Comment by zhaojunri1020** [comment]
Thanks  @theloniuspunk.
Also i wanna what you mean by "3D emission fields", do you mean those emissions file which have vertical layer ( e.g., aircraft emissions) ?

**Comment by theloniuspunk** [comment]
Yes, emissions files with a 3rd dimension for the vertical distribution of
emissions. Some inventories have aircraft emissions but do not have a 3rd
dimension, rather, it's assumed to be at a certain altitude I think. Right
now, the subroutine which maps mass emissions into the size-resolved TOMAS
bins is expecting 2D emissions fields. It needs to be updated to be
expecting 3D fields and loop over the vertical coordinate. This seems
straightforward, but when I was looking about 9 months ago, there was
something that was making it harder (not impossible, but not something I
could do in an hour). I don't remember what it was though.

Jeff

**Comment by zhaojunri1020** [comment]
Thanks for your detailed explanation! @theloniuspunk 
 
But i have finished the whole year (2020) simulation using GC-TOMAS (v12.6.0) with AEIC emissions turned on in the HEMCO_Config.rc.  And i checked that  AEIC aircraft emission file contains the vertical layer.   Does that mean that TOMAS can handle 3D emission fields？

Junri

**Comment by theloniuspunk** [comment]
Not sure. I was only speculating before about why the crash was happening.
Maybe there's something special for aircraft emissions that allows it to be
handled. I'm sorry, I'm too busy this week to look much into it.

Jeff

**Comment by zhaojunri1020** [comment]
Thanks for your help @theloniuspunk. 
I will continue testing with GCAP2.0 met fields and let you know the test result.

Junri

**Comment by yantosca** [comment]
closing this issue for now, as there has not been recent activity.
